### ISSUE TITLE
3D touch support feature request

### ISSUE THREAD

**Issue by nanotechz9l** [signalapp/Signal-iOS#1018]
It would be nice if long pressing a thread/conversation allows a user to scroll up and down the thread.

**Comment by Calefornia** [comment]
Don't have 3D touch, but I'm wondering if it's possible to load messages more quickly. Currently have to scroll up in history and click "Load Earlier Messages". Couldn't this be done automatically when the top is reached or when pulled harder, like pulling down to refresh other apps?

Also, what is the purpose? Does "Load..." cause messages to be decrypted and loaded into the chat view? I am totally clueless on the technical implementation behind that.

But back to your original post, I am wondering if the technical aspects of loading and encrypting messages would need to be modified to allow easier scrolling (and maybe search, too?)

**Comment by j-f1** [comment]
Looks like messages are now loaded as you scroll @Calefornia.

@nanotechz9l The overlay shown when performing the peek gesture is non-interactive for all apps unfortunately.

**Comment by michaelkirk-signal** [comment]
heh, closing this issue just in time for Apple to retire the 3D touch feature.

We do support 3D touch as a means to preview thread content, but nothing beyond that.

If you'd like to further discuss new features, please do so at the community forum: https://community.signalusers.org
