### ISSUE TITLE
Dark theme would be nice.

### ISSUE THREAD

**Issue by nanotechz9l** [signalapp/Signal-iOS#1019]
A dark theme was previously available in Androids text secure. Please give us the option.

**Comment by allangarcia** [comment]
I don't believe is the iOS way to have themes on apps.

**Comment by pwnsdx** [comment]
@allangarcia You bet? Checkout latest Threema update out yesterday. https://twitter.com/ThreemaApp/status/694083899287322624?p=p

And there is a lot of iOS app that have a dark mode like Tweetbot, Newsify...

**Comment by mkb** [comment]
Yes, please.

**Comment by peterpanondrugs** [comment]
Friends uninstalled / didn't install Signal because they can't choose dark/black theme. 
Chatting (tired) at night is a horror with white screen :-)

**Comment by ebelinski** [comment]
@peterpanondrugs AFAIK, Messages app, Facebook Messenger, and Snapchat don't have dark themes. I wonder why your friends refused Signal because it didn't have a dark theme, when most other texting apps don't have dark themes either.

**Comment by callodacity** [comment]
The Wire app for iOS has a built in dark theme, which gets some descent reviews too 👍

**Comment by meguroyama** [comment]
Bumping this to see if it's considered at all or to see if @michaelkirk or @charlesmchen has any plans for dark mode ( only a small plus not a deal breaker for me ).

**Comment by daniil-g** [comment]
trying to persue friends, they also seek this feature. It's included in telegram and in the android version of signal.

**Comment by emx0r** [comment]
Any update to this? Dark theme would be really great

**Comment by michaelkirk-signal** [comment]
Hey all, we've found that the community forum is a better venue to talk about feature requests.

https://community.signalusers.org/

Please only use Github for reporting bugs, and take a look at our [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md) before posting here again.

We definitely hear the desire for dark theme - but we don't announce features until they are ready. If you're really curious, development is done in the open so you can follow the commit log. Responding to requests for status updates on GitHub just spams all of our repository subscribers who we rely on to help triage bugs.

**Comment by rex4539** [comment]
Very much missing the dark mode. Please implement.
