### ISSUE TITLE
Improve Look and Feel to fit in more with iOS 

### ISSUE THREAD

**Issue by jaredStef** [signalapp/Signal-iOS#1025]
Many parts of the app seem inconsistent and could be better made to fit in with the operating system.
- [ ] Made cells of message groups larger
- [ ] Extend Cell Insets to far right
- [x]  Round the corners more on the message text field 
- [x] Make the send button the same blue the app uses which would imply that it could be tapped and leads to nicer ui
- [ ] Use standard system Alert View Controller and just change the color when picking images
- [ ] Add back button to settings VC so it is more consistent and less confusing than having it segue back when the X is tapped. 
- [x] Make Network Status Not animate when tapped

I know Objective-C and work with iOS apps, so I am willing to add all of these changes myself. I have been using the app a lot recently after convincing my friends to switch from using Skype due to privacy concerns and want the user experience of this app to be the best it can be.

**Comment by nikklassen** [comment]
This is not strictly a look and feel issue, but I thought this was a good place to mention it since this issue is actively being worked on. I would like the font size the be configurable to aid in the accessibility of the app. Is that something that could be added with these changes?

**Comment by jaredStef** [comment]
+1 Everyone should be able to use the app, so we should make it as accessible as possible. My work on my current PR has been postponed a week or two due to me finishing a college class, but when I get to it I would be glad to help. Can anyone else work on this issue?

**Comment by FredericJacobs** [comment]
@nikklassen The messages in the conversation view are DynamicType, so the font size from iOS settings should be taken into account. It has still to be done in other places. It's the #471 issue

**Comment by nikklassen** [comment]
@FredericJacobs Great, thanks! Sorry I missed that one

**Comment by michaelkirk-signal** [comment]
Some of this has been addressed, and the remaining items seem unlikely to change. e.g. the presentation of the settings controller is intentionally modal.

If you have a specific bug to report, please open a new issue. If you'd like to propose other design changes, the community forum is a better place to have that kind of discussion: https://community.signalusers.org
