### ISSUE TITLE
UX issue when viewing images

### ISSUE THREAD

**Issue by prathmeshranaut** [signalapp/Signal-iOS#1030]
When I am trying to view a screenshot image message, the status bar isn't hidden and disturbs the image.
![simulator screen shot dec 30 2015 3 14 52 pm](https://cloud.githubusercontent.com/assets/3950603/12049063/aebbac86-af08-11e5-97f5-a51b435f33d9.png)

I'm submitting a merge request which fixes it and hides the status bar.

![simulator screen shot dec 30 2015 3 15 15 pm](https://cloud.githubusercontent.com/assets/3950603/12049068/c4d2d0c6-af08-11e5-8f9a-0d602c50107a.png)

**Comment by denver-s** [comment]
This behaviour is still happening in version 2.39.0.9.

**Comment by ethylmorphine** [comment]
iOS 12.2, Signal 2.39.0.9. Reproducible with videos as well.

![Image](https://i.imgur.com/HE6OE80.jpg)

**Comment by Mihahn** [comment]
Not happening when entering fullscreen mode for images on Signal 3.4.0.7. Neither for images nor for videos.

**Comment by denver-s** [comment]
@prathmeshranaut can confirm, it doesn't happen anymore.

**Comment by prathmeshranaut** [comment]
Can confirm that it doesn't happen anymore on 3.6.1.4.
