### ISSUE TITLE
Feature request: Marker at last read message in conversations

### ISSUE THREAD

**Issue by Sh4pe** [signalapp/Signal-iOS#1038]
In chats, particularly in group chats with lots of messages coming each day, a marker at the last read message is quite handy. Other messengers (particularly the BIG ONE) have this feature.

I'd really like to see this in Signal too.

Is anyone working on this yet? If not, I would like to try myself on this...

**Comment by siccovansas** [comment]
For implementation reference: the feature is now available in the Android version of Signal.

**Comment by denver-s** [comment]
@Sh4pe this feature has been implemented in Signal iOS.
