### ISSUE TITLE
Show time stamps by sliding left

### ISSUE THREAD

**Issue by petergault** [signalapp/Signal-iOS#1058]
i love signal! Great app, I use it every day. The only thing I miss is seeing time stamps of the messages.

**Comment by 2-4601** [comment]
Duplicate of #695 :)

**Comment by Ginari** [comment]
I think he is meaning that when you slide right in imessage for example it shows you the exact time the message was received/sent.

**Comment by Mojo90** [comment]
Swipe left in iMessage shows the time stamps.
Swipe right is normally to get to the previous screen

**Comment by Ginari** [comment]
I think that was meant. Sliding left then.

**Comment by iadmir** [comment]
This feature really missing on Signal for iOS.
https://media.giphy.com/media/3oEduTcKZONTsu3PUs/giphy.gif

**Comment by basnijholt** [comment]
Yes, this would be great. I have had multiple times that I needed to know the exact time of a certain message. Until now I did it by exporting the debug log and then figure it out, which is a quite horrible solution...

**Comment by iadmir** [comment]
Is there any chance of implemanting this in JSQMessageViewController:
https://github.com/shaps80/iMessageStyleReveal
@charlesmchen

**Comment by Spylon** [comment]
Any chance of this getting implemented soon?

I would be willing to make the change if I got some pointers.

**Comment by michaelkirk-signal** [comment]
We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
