### ISSUE TITLE
Feature Request: remember the input language

### ISSUE THREAD

**Issue by jhwoodyatt** [signalapp/Signal-iOS#1065]
I'm bilingual. An annoyance with Signal compared to Messages is that it forgets the input language I was using in the conversation. Could you make it remember the last input language I used in a conversation— or better still, with a correspondent— so that I don't have to switch input language quite so often? Thanks!

**Comment by likyng** [comment]
Many other messenger app, notably the facebook messenger app remembers the input language used for each person individually as well.

**Comment by jhwoodyatt** [comment]
The duplicate #1284 asked for the Emoji input language not to be memorized as the input language for a correspondent, and I can see the merit in that. Please consider it.

**Comment by michaelkirk-signal** [comment]
This is coming up in the next  beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
