### ISSUE TITLE
v2.2 and onward IPA version

### ISSUE THREAD

**Issue by ldgbc** [signalapp/Signal-iOS#1067]
With older release (https://github.com/WhisperSystems/Signal-iOS/releases) an .ipa version is release. But with the latest v2.2 it become a .zip format.

Will IPA version no longer be release?

**Comment by michaelkirk-signal** [comment]
We don't use GitHub for discussion or feature requests, only bugs with existing app functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss: https://community.signalusers.org/
