### ISSUE TITLE
Performance: Slow video compression

### ISSUE THREAD

**Issue by horsebatterystaple** [signalapp/Signal-iOS#1069]
The transcoding (compression) of a 84 seconds video, filmed (1080p 30fps) and sent on an iPhone 5 (v9.2.1), takes more than 64 seconds. 

Reproduceable.

**Comment by denver-s** [comment]
I filmed a 90 seconds clip with my iPhone 8 Plus (iOS 12.2) in 4k 30fps.
File was 3840x2160 pixels, size 534.3 MB. It took about 20 seconds to transcode, which is not much I think.

Signal iOS 2.38.1.2
