### ISSUE TITLE
Funny looking volume control in video playback 

### ISSUE THREAD

**Issue by horsebatterystaple** [signalapp/Signal-iOS#1070]
Happens in 2/3 of the time I open a video. 

Iphone 5, iOS 9.2.1, Signal 2.2
Don't know if important, but I decreased the text size (Dynamic Type) in the iOS settings. 

![image](https://cloud.githubusercontent.com/assets/17123770/12902165/b230d78a-cf13-11e5-9e83-6cf9fabdd9ed.png)

**Comment by michaelkirk** [comment]
> Don't know if important, but I decreased the text size (Dynamic Type) in the iOS settings.

@horsebatterystaple do you see this behavior with system default text size?

**Comment by michaelkirk-signal** [comment]
We've since replaced the video player. If you're still having problems with the video player please open a new issue.
