### ISSUE TITLE
VoiceOver playback functionality for video and images for blind users

### ISSUE THREAD

**Issue by clemensf** [signalapp/Signal-iOS#1083]
Using VoiceOver it is impossible for blind users to focus and playback videos and images. 
VoiceOver just skips these messages. This may be acceptable for images, but not for video as videos contain sound - which is clearly perceptable by blind users ;-)
Also: Could you please implement Audio attachments - like in the Android version?

Thank you very much!

**Comment by neffs** [comment]
This seems to be a problem with JSQMessagesViewController upstream and a possible solutions is already available as a pull request.
https://github.com/jessesquires/JSQMessagesViewController/pull/886

**Comment by Andre9642** [comment]
Thanks for reporting this. It's also an annoying bug for me.

> VoiceOver just skips these messages. This may be acceptable for images, but not for video as videos contain sound - which is clearly perceptable by blind users ;-)

In my opinion it's not also acceptable for images. For example, sometimes I receive images with text. In this case, I retrieve the image then I process it with an OCR (e.g. Seeing AI, Prizmo Go). And so I can know what the picture contains.
