### ISSUE TITLE
Feature request: Adapted UI for Ipad

### ISSUE THREAD

**Issue by raumzeit77** [signalapp/Signal-iOS#1086]
A friend of mine started using Signal with her Ipad – as she owns no smartphone – but the layout of Signal seems to be quite bad on tablets. The app only works in portrait mode, they keyboard is small and there's _a lot_ white space. 

A quick idea would be to split the screen: 
- left side: list of running conversations
- bottom left: buttons for settings, contacts, (invite?)
- right side: the currently opened conversation. 

How it looks in Telegram: https://s2.mzstatic.com/us/r30/Purple3/v4/08/82/9c/08829cac-7449-2211-b118-2aaf8c9dfb98/screen480x480.jpeg

**Comment by 2-4601** [comment]
Seems like duplicate of #937.

**Comment by raumzeit77** [comment]
well, not exactly. the ui as a whole should be different for Ipad.

**Comment by michaelkirk** [comment]
related #1068

**Comment by FaraoneLele** [comment]
Any news?

**Comment by mkb** [comment]
I'd love an iPad version!

**Comment by Windowly** [comment]
I would as well -- as well as the ability to link it to one's original account.

**Comment by CodeMichael** [comment]
Any chance this could be reviewed?  My inability to respond to signal messages on my iPad is a constant annoyance.  Love all the other work that is being done.

**Comment by AtomicMegaNerd** [comment]
I'd like to add my voice that the ability to link Signal to an iPad is the one feature that would be most transformative in my use of the app.  I hope this feature is still on the roadmap.

**Comment by Cerberus0** [comment]
This is now being tested in beta:

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-3-0-release/10130
