### ISSUE TITLE
Feature request: Different new message sound

### ISSUE THREAD

**Issue by fathorse** [signalapp/Signal-iOS#1094]
I've found that there is a general consensus among my Signal using friends that the current NewMessage.aifc sound should be updated from the current "clomp" to something that's slightly more pleasant to the ear. Alternatively, add a handful of sounds and let the user choose. Thanks! :)

**Comment by michaelkirk** [comment]
I'm not sure if we're talking about the same thing, but I think it's a problem with the audio levels on the second beat.

See my new PR #1095

**Comment by caveman1973** [comment]
I see no problem with the sound.

The real problem is not being able to choose a different sound for different contacts.

**Comment by michaelkirk** [comment]
@caveman1973 you might be interested in https://github.com/WhisperSystems/Signal-iOS/issues/1009

**Comment by mkb** [comment]
I'm not keen on the notification sound either. Custom sounds (#1009) would be ideal but changing the built-in sound would be sufficient.

**Comment by richardsj** [comment]
Yes please - any sound would be nicer than the current one.  There is a pretty nice list here https://notificationsounds.com/notification-sounds - and some of these could be shortened so that the effect is shorter and more subtle.  A few loud ones in there and a menu - job done!

**Comment by michaelkirk-signal** [comment]
This was addressed a while ago, when we added a selection of system sounds and changed the default.
