### ISSUE TITLE
Add support for Bluetooth Message Access Profile (MAP)

### ISSUE THREAD

**Issue by mariuszs** [signalapp/Signal-iOS#1097]
Standard messaging application for Android supports Bluetooth MAP.

https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=215400

**Comment by chrisballinger** [comment]
Only Bluetooth LE (4.0) is supported on iOS without an additional (expensive) entitlement from Apple.

**Comment by mariuszs** [comment]
I'm more interested in android :) I hope this is cheaper platform :)

**Comment by michaelkirk** [comment]
Just to clarify @mariuszs  - this is the *iOS* issue tracker. If you want this feature in android, try over there: https://github.com/WhisperSystems/Signal-Android/issues

**Comment by mariuszs** [comment]
Oh, thanks for clarification
