### ISSUE TITLE
Incoming call can be used to bypass "Sorry - give access to contacts" modal blocker

### ISSUE THREAD

**Issue by ikisusi** [signalapp/Signal-iOS#1144]
- [ x ] I have searched open and closed issues for duplicates and found out that this is slightly related to issue #83. I am wondering why signal actually can be used without giving access to the contacts if done as described below, but maybe this is unintended and thus filing this bug. :)

---
### Bug description

A friend's call can be used to bypass "give access to contacts" requirement and enable use of the App without giving contact access. :)
### Steps to reproduce
- Install Signal iOS
- Start signal
- Refuse to give signal access to your contacts due to being scared of exposing your social network of informants, whisteblowers and other partners in crime
- See signal blocking the App with a modal "Sorry" dialog so that you can't access the settings nor delete the accounts etc.
- Observe your friends starting to send you messages
- Be desparate since you can't really read the messages if you miss the notifications or can't see them in full in the grayed out area behind the blocking "Sorry" dialog
- Ask a friend of you to make an incoming call

**Actual result:** Observe how "Sorry" dialog goes away and you can access the messages you have received, use the app otherwise as well  and finally access the settings to delete your account.
**Expected result:** The "Sorry" dialog to stay and keep you hostage
### Device info

**Device**: iPhone 6
**iOS version**: 9.3.1
**Signal version:** sorry, could not check from the settings, didn't have any friends left to call me :)

**Comment by guillett** [comment]
I can't replicate the issue using the app as of the latest commit (2d639b79e23d7537f3cb3f92ee035270935895b8).

I registered my phone number (which was not clear from _your steps to reproduce_ list).
I received messages that are 'visible' under the Sorry pop-up.
A friend called me but nothing happened one my phone.

Using the app from the AppStore, if I remove Contact access, restart the app I see the Sorry popup. In that situation a call gives access to the application (bypass).

**Comment by michaelkirk** [comment]
FYI @guillett  you can't currently receive calls on non-appstore builds due to the push notification requirement. 

https://github.com/WhisperSystems/Signal-iOS/wiki/Development-Guide#known-limitations

I wouldn't worry about fixing this at the moment, because there is some call related work happening that will otherwise affect this.
