### ISSUE TITLE
Order for Japanese names

### ISSUE THREAD

**Issue by miyar520** [signalapp/Signal-iOS#1158]
Hi,

I am using Signal in Japanese and noticed that the family name and the given name are displayed in the wrong order. For Japanese names written in Japanese, the family name should come before the given name. Moreover, the space between the family name and the given name can be omitted.

For example, if the given name is G and the family name is F, Signal currently shows
G F
but it should be either
F G
or
FG

FG (the space being omitted) is better if it is written in a sentence (e.g., "Missed a call from xxx") since Japanese sentences don't use space. It is safer to show FG everywhere, which is what is done in  Apple's Mail and iMessage.

Since the reverse order appears quite awkward and may give people a bad impression, I would like to ask you to look into this problem.

The problem appears in iPhone 6s with iOS 9.3.1 and Signal 2.2.

Thank you.

**Comment by sopium** [comment]
Same with Chinese names.

**Comment by big-r81** [comment]
only a developer hint (for me): NSPersonNameComponents & NSPersonNameComponentsFormatter ...

**Comment by abcdev** [comment]
The currently best approximation to the users preferences would be to base the NSComperator yielded by [[OWSContactsManager contactComparator]](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/contact/OWSContactsManager.m#L375)  on  [[CNContact comparatorForNameSortOrder:CNContactSortOrderUserDefault]](https://developer.apple.com/reference/contacts/cncontact/1403401-comparatorfornamesortorder?language=objc) .  A iOS 9.0+ feature...

**Comment by ldbfrank** [comment]
`CNContactFetchRequest *requst = [[CNContactFetchRequest alloc] initWithKeysToFetch:[[NSArray alloc] init]]; `
`requst.sortOrder = CNContactSortOrderUserDefault; `
`CNContactStore *store = [[CNContactStore alloc] init];`
` [store enumerateContactsWithFetchRequest:requst error:&error usingBlock:^(CNContact * _Nonnull contact, BOOL * _Nonnull stop) { ... }];`
