### ISSUE TITLE
Does not support IPv6-only networks.

### ISSUE THREAD

**Issue by echarlie** [signalapp/Signal-iOS#1190]
- [X] I have searched open and closed issues for duplicates

---
### Bug description

Messages cannot be sent on IPv6-only network without transition mechanisms.
### Steps to reproduce
- Connect to wireless IPv6-only network **without** transition mechanisms (NAT64, 4rd, DNS64, etc.).
- Try to send message, debug log.
- It _will_ fail.

**Actual result:** Message fails to send, Signal claims to be "offline"
**Expected result:** Message is sent, Signal functions normally.
### Screenshots

This won't show anything of use.
### Device info

**Device**: iPhone 5S
**iOS version**: 9.3.1
**Signal version:** 2.2
### Link to debug log

Can't send debug log on IPv6-only either. Sorry.

**Comment by aaronraimist** [comment]
I don't have any way to test this but just a note for the developers: this needs to be fixed soon, [all new updates to apps will need to support IPV6 networks by June 1, 2016](https://developer.apple.com/news/?id=05042016a).

@michaelkirk

**Comment by echarlie** [comment]
The only reason I was able to test is because my employers have a wireless IPv6-only network; they use it to annoy the vendors. I know that anything running on AWS *cannot* support IPv6, github included, iirc. However, Apple's demand there is rather hypocritical: *most* of **their own apps** break on an IPv6-only network; they assume the use of transition mechanisms as stated in their developer page, though.

**Comment by michaelkirk** [comment]
I don't have at hand an IPV6 network which *doesn't* support NAT64.

But interestingly enough, one of the Apple recommended ways to verify that your app is ipv6 ready is to connect your iDevice to a  [local NAT64 network shared from your mac](https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16).

After connecting to this network, I verified that no relevant ipv4 traffic was transmitted while Signal messages were exchanged.

This isn't settled, but I haven't yet found any obvious ipv4 offenders in the codebase and consider it a good sign that Apple's own recommended ipv6 test setup doesn't immediately flunk Signal.

**Comment by michaelkirk** [comment]
To update, we've had confirmation that Signal works with Apple's ipv6 testing setup.

@echarlie - is it still the case that Signal doesn't work on your employers network? Could it be related to port restriction vs ipv6?

Read more on port restriction here: http://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-

**Comment by echarlie** [comment]
I went through quite a few hoops on my home network to break IPv4. With an IPv6-only network without transition mechanisms, I can still confirm that Signal is broken. I'd assume this is because Signal's central Servers are IPv4-only, or at least don't have AAAA records in DNS. I have confirmed that it works on an IPv6-only NAT64/DNS64 network.

**Comment by okias** [comment]
Nothing changed in terms of IPv6 brokeness
