### ISSUE TITLE
cannot unregister or re-register

### ISSUE THREAD

**Issue by benmayne** [signalapp/Signal-iOS#1208]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Signal started telling me this morning that my phone number was not registered, but I cannot successfully register or manually unregister. Wifi and network (Verizon)
### Steps to reproduce
- open signal
- settings > advanced
- register

**Actual result:** message `MESSAGE_BODY`
**Expected result:** something to let me register my phone
### Screenshots

trying to register: 
![2016-06-09 21 06 19](https://cloud.githubusercontent.com/assets/3374110/15954173/c63ce1ea-2e88-11e6-8209-07b67384aac8.png)

trying to unregister: 
<img width="632" alt="screenshot 2016-06-09 21 27 34" src="https://cloud.githubusercontent.com/assets/3374110/15954202/049f5850-2e89-11e6-8917-c779d08cbea1.png">
### Device info

**Device**: iPhone 6
**iOS version**: 9.3.2
**Signal version:** 2.3
### Link to debug log

https://gist.github.com/anonymous/74cd1b53e8482c4c610ebf3895fa71e7

**Comment by benmayne** [comment]
going through https://whispersystems.org/textsecure/unregister/ and re-installing the app was successful.

**Comment by michaelkirk** [comment]
@benmayne 

That first screenshot, registering for push notifications, is unrelated to your Signal account, but it does show another bug - that "REGISTRATION_BODY" should be localized text. Do you still see that? Is your phone in English or have you chosen another localization?

Secondly, it seems like the source of your trouble is that your application somehow lost it's server authentication credentials (error 403 in the debug log). This would prevent you from communicating with the signal server, including sending/receiving messages and unregistering. 

Did you install Signal from a restore or something? Or did you just wake up one day and your app was :skull:?

**Comment by BMayneFactual** [comment]
There wasn't any known event before this happening - but it was a friend's phone, so I can't confirm for sure anymore. Should be in english. I'll check for `REGISTRATION_BODY` when I can.
