### ISSUE TITLE
Sometimes message history scrolled offscreen when tapping in compose area

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1221]
### Bug description

Sometimes when tapping in the compose box, the message history is scrolled offscreen, leaving the message history area blank, until I swipe down.

This might be a bug in our old version of JSQMessageViewController.
### Steps to reproduce

_Note_ this isn't always reproducible. Happened only a few times.
- When I enter a thread
- Then I see messages in message history area
- When I tap the compose area
- Then I see that keyboard pops up
- But I can no longer see any messages in the message history area
- When I swipe down just a little in the message history area
- Then the messages slide down and "snap" into their proper place.

**Actual result:** Message area becomes blank when I tap on compose area
**Expected result:** Message area should move up a bit to fit the keyboard, but should not be scrolled off screen.
### Device info

**Device**: iPhone 6
**iOS version**: 9.3.2
**Signal version:** 2.3.2+HEAD(8f04f86)

**Comment by julieces** [comment]
Hi! I attempted to reproduce this issue and I don't seem to run into this problem.

Device info

Device: iPhone X
iOS version: 12.2
Signal version: 2.38.1.2

**Comment by denver-s** [comment]
This is probably a fixed issue.
