### ISSUE TITLE
Some users struggle to see the Verification Code field

### ISSUE THREAD

**Issue by runasand** [signalapp/Signal-iOS#1243]
The Verification Code field can be difficult to see for some users. Making this field easier to see would be a usability win.

One way to improve this field would be to change the color from light grey to solid black. Another option would be to change the text from "Verification Code" to "Enter Verification Code Here".

![screen shot 2016-09-17 at 1 12 03 pm](https://cloud.githubusercontent.com/assets/217057/18609775/73050c52-7cd8-11e6-833c-40104de08726.png)
edit: screenshot added by @michaelkirk

**Comment by Calefornia** [comment]
Another issue with signing up is the conflict with iOS's "Low Power Mode" and Signal's need for background app refresh [permissions](http://support.whispersystems.org/hc/en-us/articles/213132457-Are-you-having-trouble-verifying-on-Signal-). I've been super frustrated with the process and thought it was an error on Signal's end... If someone is stumped without seeing any helpful dialog, it's a problem for understanding how to solve the issue. I finally searched around and found the helpful explanation on the link above, but perhaps this could be built into the app?

It should be easy enough to detect issues after someone submits the verification code. If it's stuck there for more than a few seconds, ask people to check their iOS permissions. Is Signal able to detect usage of "Low Power Mode" or if it has access to "background app refresh"? If we can detect these issues and help people solve them, it would be great!! Thanks!

**Comment by michaelkirk** [comment]
@Calefornia can you open a new issue for that and delete your comment here? Seems completely different from the verification code field color.
