### ISSUE TITLE
Media should have selected mask

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1283]
### Bug description

When selecting media via long pressing for copy/delete/save we should indicate which media is selected, same as we do with text messages.

Upstream bug: https://github.com/jessesquires/JSQMessagesViewController/issues/1239
### Steps to reproduce
- long press on text in conversation
- see edit menu popped
- see message bubble highlighted
- long press on image/video/gif/audio bubble in conversation
- see edit menu popped

**Actual result:**
Cell isn't highlighted

**Expected result:** 
Media should have a mask, indicating it's highlighted
### Screenshots

Here I've selected "Dancing". You can see the edit menu and how the bubble is visibly selected.
![image](https://cloud.githubusercontent.com/assets/217057/17031539/80fe751e-4f29-11e6-97a4-68f4e9c886f6.png)

Here I've selected the banana image. You can see the edit menu, but there is no visible indication that the image is selected.
![image](https://cloud.githubusercontent.com/assets/217057/17031518/6fa49974-4f29-11e6-8e2a-628fcc23c58e.png)

 This is especially onerous when multiple messages are in close proximity, and it's not clear which bubble the media item applies to. E.g. It's not clear which of the two raccoon pictures I am editing in this photo (the bottom one).
![image](https://cloud.githubusercontent.com/assets/217057/17031613/d60860c4-4f29-11e6-8caa-062eae4c2f5f.png)

**Comment by big-r81** [comment]
only informational:
It seems that this feature isn't implemented for media messages in the JSQMessagesViewController library.
So we have to implement this by ourselve...

**Comment by paewel** [comment]
I see Signal is pointing to a forked JSQMessagesViewController repository. The last commit there is a bug fix. Maybe both of them were fixed in the newest version? I'm not sure if it's so "Easy Contribution"

**Comment by njdehoog** [comment]
As a newcomer to this project I would like to take stab at this issue, but I'm confused about which version of JSQMessagesViewController the project is supposed to use. According to [this README](https://github.com/WhisperSystems/JSQMessagesViewController) the fork is no longer in use, but is still referenced from the `Podfile`.

I verified that the current `master` branch of Signal builds fine when pointed at `JSQMessagesViewController` 7.3.4, which is the latest version. It also displays a menu over images (still doesn't highlight the image though). Is it likely that pointing the `Podfile` at the main repo of `JSQMessagesViewController` will break things?

**Comment by jonnolen** [comment]
I also was looking for a thing to stab at, and the highlighting of messages (subtle shading) when they are under context menu seems to be not present in master which means messages and media behave the same.

**Comment by denver-s** [comment]
I think this has been fixed.
