### ISSUE TITLE
Unequal vertical margins within chat bubbles

### ISSUE THREAD

**Issue by miyar520** [signalapp/Signal-iOS#1289]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

I am using Signal in Japanese and notice that the text in a chat bubble is misplaced vertically: the top margin is 30% shorter than the bottom margin.
### Screenshots

![signalverticalmargin20160722](https://cloud.githubusercontent.com/assets/18557630/17045081/5070331e-5001-11e6-8b52-fcf2a9ab4cb5.png)

There should be the same amount of space above and below "20."
### Device info

**Device**: iPhone 6s
**iOS version**: iOS 9.3.3
**Signal version:** 2.4.0.2
The same problem is observed in previous versions of iOS and Signal.

**Comment by denver-s** [comment]
I tried with some random words and I can't replicate the issue.

**Comment by michaelkirk-signal** [comment]
We've substantially overhauled the bubble views since this was opened. If this issue is still reproducible please re-open.
