### ISSUE TITLE
Payload shorter than HMAC. 

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#13]
In SRTPStream.m, a lot of streams are having issues with payloads that are too short:

`Operation failed: Payload not long enough to include hmac Expected: [[securedRtpPacket payload] length] >= HMAC_LENGTH(in Signal-iOS/Signal/src/network/rtp/srtp/SrtpStream.m at line 39)`

No clue why this happens.

**Comment by corbett** [comment]
is this still an issue @FredericJacobs?

**Comment by FredericJacobs** [comment]
@corbett: Yes, it happens. Saw it in the logs recently.
