### ISSUE TITLE
Select AddressBook to use with Signal

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#131]
Some people have a home and work addressbook on their phone. They might want to pick only a specific addressbook to work with Signal.

**Comment by abolishme** [comment]
Is there native support on iOS for multiple contact lists? Google turned up nil for me.

**Comment by michaelkirk** [comment]
Reopening as I think this was accidentally closed when corbett closed/reopened a referencing issue.

**Comment by mat1th** [comment]
I think it's a better solution that the app doen't force to use contacts see #1610. Then this problem would also solved. The user could load only his contacts he would like. Then he can disable the contact access.

**Comment by jonathancross** [comment]
Bot: do not close this.
