### ISSUE TITLE
Contact discovery based on international phone number broken

### ISSUE THREAD

**Issue by nixnuex** [signalapp/Signal-iOS#1323]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Contact discovery does not work for contacts with phone number in international format (trailing 00)
### Steps to reproduce
- Alice has been using Signal on iOS with her phone number +41 79 123456789 for a long time
- Bob installed and registered with Signal on iOS, allowing the App access to his address book with Alice' international phone number in it: 0041 79 123456789
- Bob starts a new chat and refreshes his contact list based on his address book

**Actual result:** Alice does not show up in Bob's Signal contacts unless he changes her phone number in his local address book to the equivalent +41 79 123456789 (+ instead of 00)
**Expected result:** Bob should be able to discover Alice with both versions of her international phone number
### Device info

**Device**: iPhone 6S
**Signal version:** HEAD/2.6.0

**Comment by michaelkirk** [comment]
This process of canonicalization can be hairy, and depends on the context from which it's being dialed. e.g. a leading 00 might mean one thing when dialed via a swiss telecom, but something else  when dialed in other parts of the world.

Ultimately, we have to be able to convert your contacts into the same e164 style phone number as we registered them with. If you're interested I can point you at some code.

@nixnuex are you interested in trying to fix this? Or setting up a good failing test case would be helpful. Otherwise I won't be able to get to it for a bit.

**Comment by nixnuex** [comment]
I will have a look at it.

**Comment by nixnuex** [comment]
My understanding of the problem is as follows: The only clear global definition of a phone number is the one including the country code preceded by a _plus_: +4179123456789 (with or without spaces/dashes/brackets). We are lucky, if the user has saved numbers in his iOS address book in this format, contact lookup based on this is unambiguous.

If the user has saved numbers in whatever local format, the guessing starts. Right now, `PhoneNumber.m` tries to generate an e164 number based on the locale settings of iOS (region) and the associated ISO 3166-1 country code. This interpretation by `libPhoneNumber-iOS` might fail. Either because the number is really not usable or because the interpretation was performed based on a wrong region. We could try to catch the latter case.

I would propose adding another layer of phone number interpretation in case the one based on the iOS region setting fails. A simple first approach would be to try with the region based on the country code the user registered with, in case it is different from the iOS settings.

A desirable target state should be that the Signal contact list (successful lookups) does not depend on the iOS region setting. You don't want users to lose contacts in the list just by changing this basic iOS setting.

Any opinion on this?

**Comment by michaelkirk** [comment]
> My understanding of the problem is as follows: ...

Your explanation sounds correct.

> You don't want users to lose contacts in the list just by changing this basic iOS setting.

Is that what happened in the case of Alice and Bob above?

**Comment by nixnuex** [comment]
Yes, I tracked it down to the region setting and the interpretation of the saved numbers based on it.

**Comment by michaelkirk** [comment]
> Yes, I tracked it down to the region setting and the interpretation of the saved numbers based on it.

So if Bob changes his locale to Swiss, then can he find Alice?

I'd be curious to see how Alice's number was internationalized by libPhoneNumber with the leading 00's. 

Here's [Signal-Android's canonicalization function](https://github.com/WhisperSystems/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/api/util/PhoneNumberFormatter.java#L66):
```
/**
* (comments added by @michaelkirk)
* @param number
*     The remote number(i.e. Alice:0041 79 123456789) we want to canonicalize
* @param localNumber
*     The local users (i.e. Bob +41 79 123456789) e164 format**able** (but not neccessarily formatt**ed**) number
*/
public static String formatNumber(String number, String localNumber)
    throws InvalidNumberException
{
  if (number.contains("@")) {
    throw new InvalidNumberException("Possible attempt to use email address.");
  }

  number = number.replaceAll("[^0-9+]", "");

  if (number.length() == 0) {
    throw new InvalidNumberException("No valid characters found.");
  }

  if (number.charAt(0) == '+')
    return number;

  try {
    PhoneNumberUtil util          = PhoneNumberUtil.getInstance();
    // Assumes we can parse localNumber unambiguously. -@mjk
    PhoneNumber localNumberObject = util.parse(localNumber, null)

    String localCountryCode       = util.getRegionCodeForNumber(localNumberObject);
    Log.w(TAG, "Got local CC: " + localCountryCode);

    // Use local country code to establish remote parsing context -@mjk
    PhoneNumber numberObject      = util.parse(number, localCountryCode);
    return util.format(numberObject, PhoneNumberFormat.E164);
  } catch (NumberParseException e) {
    Log.w(TAG, e);
    return impreciseFormatNumber(number, localNumber);
  }
}
```

I think similar to what you're describing, it uses Bob's country code from his Signal ID to determine his context, rather than the phone's locale setting.

I think a good handful of tests would help clear this up. It's a really core feature so I'm cautious (but excited!) about changing it.

**Comment by nixnuex** [comment]
For this moment I can give you the results of my (frontend) tests in a matrix. Bob tries to find Alice and Charly.

Alice's registered phone number (DE): +4915011111111
Bob's registered phone number (DE): +4915022222222
Charly's registered phone number (CH): +41783333333

Bob's address book:
A1: +49 150 22222222
A2: 0049 150 22222222
A3: 0150 22222222
C1: +41 78 3333333
C2: 0041 78 3333333
C3: 078 3333333

Results of Bob's lookup for different region settings and address book entries on Bob's phone.

 | A1 | A2 | A3 | C1 | C2 | C3
--------| --------| --------| --------| --------| --------| ------
US | OK | FAIL | FAIL | OK | FAIL | FAIL
DE | OK | OK* | OK* | OK | OK | FAIL
CH | OK | OK | FAIL | OK | OK* | OK*
FR | OK | OK | FAIL | OK | OK | FAIL

\* duplicates in the address book in different formats result in duplicate contacts in Signal (based on the identical e164 number)

Yes, the Android code does the opposite. It does not care about the phone's region setting. Anyways, there might be a problem in the case `if (number.charAt(0) == '+')` for numbers like: +49015022222222 (spot the zero) which would be returned as is and not in e164 +4915022222222. libphonenumber would take care of this.

I still think, a combination of phone region and region from registered country code would be the best. It does not help the user if a lookup does not take place because some code fails to format the number (if it would succeed with a good guess of second parameter, the region).

**Comment by michaelkirk** [comment]
> On Sep 18, 2016, at 11:56 AM, nixnuex <notifications@github.com> wrote:
> 
> For this moment I can give you the results of my (frontend) tests in a matrix. Bob tries to find Alice and Charly.
> 
> Alice's registered phone number (DE): +4915011111111
> Bob's registered phone number (DE): +4915022222222
> Charly's registered phone number (CH): +41783333333
> 
> Bob's address book:
> A1: +49 150 22222222
> A2: 0049 150 22222222
> A3: 0150 22222222
> C1: +41 78 3333333
> C2: 0041 78 3333333
> C3: 078 3333333
> 
> Results of Bob's lookup for different region settings and address book entries on Bob's phone.
> 
> A1	A2	A3	C1	C2	C3
> US	OK	FAIL	FAIL	OK	FAIL	FAIL
> DE	OK	OK*	OK*	OK	OK	FAIL
> CH	OK	OK	FAIL	OK	OK*	OK*
> FR	OK	OK	FAIL	OK	OK	FAIL
> * duplicates in the address book in different formats result in duplicate contacts in Signal (based on the identical e164 number)
> 
> Yes, the Android code does the opposite. It does not care about the phone's region setting. Anyways, there might be a problem in the case if (number.charAt(0) == '+') for numbers like: +49015022222222 (spot the zero) which would be returned as is and not in e164 +4915022222222. libphonenumber would take care of this.
> 
> I still think, a combination of phone region and region from registered country code would be the best. It does not help the user if a lookup does not take place because some code fails to format the number (if it would succeed with a good guess of second parameter, the region).
> 

I think this makes sense too. As a fallback mode, it would be good to try.
