### ISSUE TITLE
New message under 3D Touch peek and pop yields no contacts available error 

### ISSUE THREAD

**Issue by JohanDoe** [signalapp/Signal-iOS#1326]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

When using peek and pop / 3D touch on the Signal Icon, possibility of directly choosing 'New Message' appears. However, when Signal is not running in the background, no contacts are found to send a message to. 
### Steps to reproduce
- Make sure Signal is not running in the background
- Peek and pop on the Signal icon
- Press 'New Message' 

**Actual result:** 
Screen with message that none of my contacts have Signal (which is not the case).

**Expected result:** 
Ability to choose from my contacts for a new message to send to them
### Device info

**Device**: iPhone 6s
**iOS version**: iOS 10
**Signal version:** 2.4.1

**Comment by Mihahn** [comment]
Can't reproduce on 3.4.0.7.

But: using 3D touch on the Signal icon and selecting "new message" opens the "main screen" with the list of all conversations, not the list of Signal contacts.
