### ISSUE TITLE
Unknown groups not handled

### ISSUE THREAD

**Issue by lorenzhs** [signalapp/Signal-iOS#1337]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

**This is an edge case.** I recently moved from Android to iOS, and enlisted in the Signal-iOS beta to be able to continue using Signal-Desktop. I could link Signal-Desktop just fine, but it kept all my old messages - including group memberships - for some reason (should I file a bug for that?). I can now participate in the groups using Signal-Desktop, but they show up as "New Group" in Signal-iOS. I can't do anything with them in the iOS client - there's no input line, no settings, no members. The messages show up, but that's it.
### Steps to reproduce
- link Signal-Desktop to Signal-Android
- create a group and have a chat with some people
- register the same number with Signal-iOS
- enlist in the Signal-iOS beta
- link to the same installation of Signal-Desktop, without clearing its data
- write something in the group with Signal-Desktop

To fix, someone else in the group has to update the group. The fix is broken for groups without an avatar until #1336 makes it into a beta release.

**Actual result:** Messages show up in Signal-iOS, but the group isn't synced
**Expected result:** An update of the group should be triggered
### Screenshots

![screenshot](https://cloud.githubusercontent.com/assets/142205/18711125/bc33225a-8008-11e6-8142-56f8a6c7200d.PNG)
### Device info

**Device**: iPhone 7
**iOS version**: 10.0 (14A346)
**Signal version:** 2.5.0.14
### Link to debug log

I'm not getting a link, and I don't have any email accounts in the Mail app -- I'll try to get a debug log

**Comment by lorenzhs** [comment]
https://gist.github.com/087a84699866ceeb5cd24fa2fb8e0ee0 - it was really not clear to me that the link would be copied to the clipboard

**Comment by michaelkirk** [comment]
🎉  Wow. Happy #1337 issue everyone! 🎉 

I'll follow up with @liliakai about this.

**Comment by lorenzhs** [comment]
Yay! :tada:

The debug log contains a friend's phone number unobfuscated, can you copy the link internally so I can remove the comment?

**Comment by michaelkirk** [comment]
> https://gist.github.com/087a84699866ceeb5cd24fa2fb8e0ee0 - it was really not clear to me that the link would be copied to the clipboard

Agreed. See https://github.com/WhisperSystems/Signal-iOS/issues/1338

**Comment by lorenzhs** [comment]
Thanks, you're really fast! - but now you've got the original, unobfuscated gist in the link again ;)

**Comment by michaelkirk** [comment]
aye carumba.

**Comment by michaelkirk** [comment]
@lorenzhs - to clarify:

> * link Signal-Desktop to Signal-Android
> * create a group and have a chat with some people
> * register the same number with Signal-iOS
> * enlist in the Signal-iOS beta
> * link to the same installation of Signal-Desktop, without clearing its data
> * write something in the group with Signal-Desktop

At this point,   after installing Signal-iOS and re-linking, but before updating the group, were you *receiving* messages sent from other people in that group on Signal-Desktop?

**Comment by lorenzhs** [comment]
Yes, Signal-Desktop could send and receive messages in the group the whole time (when it was linked, of course). Signal-iOS beta showed the messages that arrived after I sent the first one using Signal-Desktop. Before that, I was on stable and didn't get messages from the group (nor errors). I can't say whether it's due to changes in the beta or sending a message with signal-desktop, though.

**Comment by lobeck** [comment]
Had the same issue and additionally, the groups name appeared as "(null)" in the notifications.

**Comment by lorenzhs** [comment]
As expected, with Signal 2.5.0.19, an update of the group suffices even if it doesn't have an avatar. Of course, that update has to be triggered by someone else.

**Comment by membphis** [comment]
I have the same problem, my signal version: 2.10.1 (iOS version)

when I changed my iphone, reinstall the signal, then I can't chat in group.
