### ISSUE TITLE
Clarify why we need contact access

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1356]
We don't do a good job of explaining why we need peoples contacts and how we use them. Clarify this in the privacy alert users see when they first install Signal.

Having access to contacts allows people to manager their Signal (and any other message apps) from their central contacts store.

This allows us to keep in sync:
- avatars
- names
- adding a contact
- removing a contact

Furthermore we don't upload their contacts' plain text phone numbers to our server.

The trick is to paraphrase all this into a sentence that non crypto nerds will understand.

**Comment by riyapenn** [comment]
For organization and reference

Welcome screen alert:
<img width="293" alt="screen shot 2016-11-17 at 2 10 44 pm" src="https://cloud.githubusercontent.com/assets/4898366/20410495/33589c8e-acd2-11e6-95e5-2d46c12dc4d0.png">

First install permission request alert:
<img width="301" alt="screen shot 2016-11-17 at 2 10 34 pm" src="https://cloud.githubusercontent.com/assets/4898366/20410499/3a417192-acd2-11e6-896c-ae35c239047a.png">

Mid-app permission revocation alert:
<img width="341" alt="screen shot 2016-11-17 at 1 59 20 pm" src="https://cloud.githubusercontent.com/assets/4898366/20410703/457636f0-acd3-11e6-917b-a26f4886119f.png">
