### ISSUE TITLE
Composing new messages for contacts with multiple phone numbers

### ISSUE THREAD

**Issue by stonie08** [signalapp/Signal-iOS#1361]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Address books allow to enter multiple phone numbers for a single contact (e.g. work, home, mobile,...). For a contact that has signal activated on multiple devices, each with a separate phone number (e.g. mobile and work) you can't decide on a specific phone numbers when composing a new message for that contact. Therefore you can't decide to send this message to e.g. the work-phone.
### Steps to reproduce
- Create a contact in your address book
- Add at least two phone numbers activated for signal
- open Signal (you may have to refresh the contacts list)
- Tap the "New Message" Icon try to select a specific phone number of previously created contact.

**Actual result:** 
The contact is listed in the list of available contacts, but the phone number used is chosen by signal.

**Expected result:** 
There should be a dialogue that allows to select which phone number the message should be sent to. Alternatively these contacts should appear multiple time in the addressfield selection screen with an indicator regarding the phone number of this contact
### Device info

**Device**: iPhone 5
**iOS version**: 9.3.5
**Signal version:** 2.5.2

**Comment by tcp100** [comment]
Also seconding this issue. When someone sends a message to a person with multiple numbers and signal on multiple devices, there's zero notification of which device the message was sent to as well. My wife sent me several messages which went to my work Android phone - my iPhone never got them, and she got no notification or indication that they weren't being sent to the right device. 

When composing, and multiple numbers are registered with Signal, a dialog to chose which number should be presented. It's simple, and has gone too long without a fix.

**Comment by retorquere** [comment]
Or even that the message gets sent to all of them. From my point of view, I'm sending the message to a person, not to a device. The phone number is supposed to be a mechanism for contact discovery, right? In the end it's the contact, once discovered, that I want to reach.

**Comment by schwigri** [comment]
I would like to voice my support for this feature, it makes using the app very difficult. I have multiple contacts with multiple phones, and separating them in distinct contacts goes against the point of my address book (and contact names like, "Friend (work)" are ugly).
