### ISSUE TITLE
Headline for linked devices jumps

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#1366]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

The headline for the linked devices screen jumps when the list is switched into edit mode.
### Steps to reproduce
- go to Signal > Settings > linked devices
- use the edit button in the right upper corner

**Actual result:** The headline is pushed to the left.
**Expected result:** The headline should stay in place.
### Screenshots

![img_4558](https://cloud.githubusercontent.com/assets/5073538/19020884/6ac7500e-88a4-11e6-9bc3-299a2fcf54f4.PNG)
![img_4559](https://cloud.githubusercontent.com/assets/5073538/19020885/6b362772-88a4-11e6-88ac-eaa849164cef.PNG)
### Device info

**Device**: iPhone 5
**iOS version**: 10.0.2
**Signal version:** 2.5.3.4 beta

**Comment by michaelkirk** [comment]
Does this still happen with the latest iOS?

We really aren't doing anything special here, but my guess is we're straddling some edge case in the system frameworks based on how close those words are in the German localization.

**Comment by maltemayer** [comment]
Yes, it still happens in v2.6.5.

**Comment by michaelkirk** [comment]
> Yes, it still happens in v2.6.5.

But what version of iOS? 10.0.2 still? Or are you on 10.1?

**Comment by maltemayer** [comment]
Ah, sorry man. Yes, it’s 10.1.

**Comment by denver-s** [comment]
I cannot reproduce this behavior (version 3.1.0.13).

**Comment by maltemayer** [comment]
#2017 is fixed in in Signal 3.1.0.13 beta.
#1366 still reproducible in Signal 3.1.0.13 beta on my end.

**Comment by maltemayer** [comment]
Fixed with redesign.
