### ISSUE TITLE
Thumbprint Access Restriction

### ISSUE THREAD

**Issue by XyberICE** [signalapp/Signal-iOS#1382]
Feature Request: Please add thumbprint access restriction.  If my iPhone is unlocked, ANYONE can see my messages in Signal!

**Comment by jaredklett** [comment]
Many iOS apps have this additional layer of security. If your phone is unlocked, or someone shoulder-surfs your passcode/phrase, it's a nice option to have.

**Comment by openfly** [comment]
there are work arounds, but having it integrated into the app would be beneficial.

**Comment by Sosoyan** [comment]
Please add this feature as priority, if we care about security. It should ask for given Pass Code or Touch-ID every time when you open the App or switch back.

**Comment by denver-s** [comment]
TouchID/FaceID lock when you open Signal has been added long time ago now.
