### ISSUE TITLE
Add the ability to mark conversations as unread

### ISSUE THREAD

**Issue by nimarb** [signalapp/Signal-iOS#1392]
### Description

Marking messages as unread serves as a good indicator to get back to them later, which helps a lot when dealing with many messages of which only some require a response. Thus, all messages are read but some require a reply later. 
### Design Idea

A good way to handle that would be to swipe right on a message threat to reveal a "Mark Unread" button, which is similar to how other popular messenger apps implement this feature. Upon pressing the "Mark unread" button, the threat would become unread again and a blue dot is displayed on the right of the threat view.

**Comment by michaelkirk** [comment]
> On Oct 13, 2016, at 10:47 AM, likyng <notifications@github.com> wrote:
> 
> Description
> 
> Marking messages as unread serves as a good indicator to get back to them later, which helps a lot when dealing with many messages of which only some require a response. Thus, all messages are read but some require a reply later.
> 

An existing option is to use the archive feature for this. Leave things in your inbox only if you want to respond. Otherwise put them in your archive and they’ll pop out once you have a new message.

**Comment by martin-uplex** [comment]
+1 from me, too. This is the feature I miss most! WA has it for ages and I think Signal should not fall behind.

**Comment by erikw** [comment]
Here's the feature request in signal community. Go in and vote for it there! =) 

https://community.signalusers.org/t/add-ability-to-mark-messages-as-unread/2376


Mark as Unread is an essential features for IM.

**Comment by madhums** [comment]
Any update on this? This seems like a very essential feature. It also looks like a lot of people have chipped in on the discussions on discourse thread to voice the favour. @michaelkirk-signal I'd like to hear from the maintainers: 

1. A clear indication of when would this get a priority?
2. What kind of help do we need to make progress and work on this issue?

**Comment by denver-s** [comment]
This feature has been introduced in version 3.10

**Comment by nimarb** [comment]
As @denver-s indicated, this has been implemented, thanks to all involved !

**Comment by madhums** [comment]
Great that this is implemented! 🥳 . One thing that I miss: when you mark a conversation unread, it would be nice to also show the badge count. Right now there are no badges when you have one or more unread conversations.
