### ISSUE TITLE
Date is not shown properly inside chats

### ISSUE THREAD

**Issue by Ecron** [signalapp/Signal-iOS#1401]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Using the iOS app, I noticed that inside a chat, the date is not shown properly in Catalan language. It's shown right now as "6 oct 2016 13:04", but it should be "6 d'oct. de 2016, 13:04". As I didn't find any string related to dates and formatting dates on Transifex, I wonder if you are using an up-to-date version of the CLDR[1], or if you used by mistake the "Stand-alone" form (nominative) of the months (MMM instead of LLL), or if you have the proper translation and format for Catalan dates.

[1] http://cldr.unicode.org/translation/date-time
### Steps to reproduce
- Set Signal for iOS to Catalan language.
- Go to any chat or group.
- Check the date.

**Actual result:** You will see something like "6 oct 2016 13:04".
**Expected result:** You must see something like "6 d'oct. de 2016, 13:04".
### Screenshots

![photo](https://cloud.githubusercontent.com/assets/488803/19428872/e07a1e18-944c-11e6-8909-37f6cc07c9ba.jpg)
### Device info

**Device**: iPhone 6
**iOS version**: 10.0.2
**Signal version:** 2.6.1.3
### Link to debug log

Not needed.

**Comment by n9ne** [comment]
I get this same issue except where one conversation will have correct date and a seperate conversation will say it is a few days different.  This happens randomly and I am unable to reproduce on command.

**Comment by michaelkirk** [comment]
@n9ne are you sure you're reporting the same issue? My understanding of this issue is not that we're showing the incorrect date, but that we're not *localizing* it correctly. 

Can you re-read the bug description, and if the behavior you're seeing is different, please open a new bug. 

Include in that new bug some screenshots of the dates you are seeing and the dates you expect to be seeing.

**Comment by denver-s** [comment]
I guess this bug is still present. I did not notice that dates are not localized.
It shows "Dic 22, 2019" while it should be "22 dic 2019" in most of countries outside US.

![image](https://user-images.githubusercontent.com/31325316/72355942-aa8e8180-36e8-11ea-9780-60dfbb583060.png)

**Comment by Ecron** [comment]
It seems there are 2 types of dates: the ones including the past year and the ones in the present year. For the first type, I get `dd LL yyyy` (Unicode's CLDR notation) and for the second type I get `EE, LL dd`.

This is not how it should work. It should get the locale configuration from the system's locale, or at least consider some formatting strings in the translation files (it should be `EE, dd MM` for Catalan, or `dd MM yyy` for the dates with the year in them).

**Comment by denver-s** [comment]
This issue has been fixed recently.
