### ISSUE TITLE
Invite user to Signal actionsheet item for failed message sending

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1424]
related to: https://github.com/WhisperSystems/Signal-iOS/issues/1417

When I send a message to someone who has uninstalled Signal
I should see that the message failed to send.

When I tap on the message I should see an action sheet with the following actions:
- "Delete"
- "Invite User to reinstall Signal"*
- "Cancel"

"Invite User to reinstall Signal" should push to our invitation flow. Perhaps with some more targeted invite copy.

**Comment by lizziesilver** [comment]
Agreed. I just messaged someone who (unknown to me) had uninstalled Signal, and I did not get any kind of notification that the message failed to send.

**Comment by riyapenn** [comment]
Clarification: surface this action for an unregistered user.  There is no consistency or feedback to Signal servers when a  user uninstalls.
