### ISSUE TITLE
Feature Suggestion: Delete for Everyone

### ISSUE THREAD

**Issue by caveman1973** [signalapp/Signal-iOS#1426]
Have you ever sent a wrong message or a photo to the the wrong chat? 

Would be great if you could delete that message from BOTH sides. Telegram and Wire has it but the latter has an interesting implementation; when you select something to delete, it shows two options:
DELETE FOR EVERYONE or DELETE FOR YOU

I think that DELETING FOR EVERYONE could be the only and default option but showing both options is a good way to explain what is happening.

**Comment by elsehow** [comment]
I think this is a good idea. From a UI perspective, either party should have the ability to censor the conversation. I don't think this feature would leak any more information than read receipts, although I would have to step through it in a little more detail.

**Comment by pantraining** [comment]
Old issue, still valid and increasingly necessary, especially for Human Rights Defenders and other activists! Is it on the Signal-Roadmap for all clients?

**Comment by Mihahn** [comment]
Delete for everyone is available by now. Please close your issue.

**Comment by GPMueller** [comment]
> Delete for everyone is available by now. Please close your issue.


Doesn't seem to work with all my contacts and groups for some reason, but this can indeed be closed.
