### ISSUE TITLE
Debug Log leaks private information in error message for long numbers

### ISSUE THREAD

**Issue by neffs** [signalapp/Signal-iOS#1427]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

Debug Log leaks private information in error message for long numbers. iOS can include eg. PINs for callthrough or mailbox systems which will be dialed with DTMF tones after the connection is established.
### Steps to reproduce
- Save a contact with a long number: 012345678901,12345#,1111111111
- open Signal
- Send Debug Log

**Actual result:** 

Log contains: 

`Issue while parsing number: Error Domain=TOO_LONG Code=0 "Error Domain=TOO_LONG Code=0 "TOO_LONG: 12345678901123451111111111" UserInfo={NSLocalizedDescription=TOO_LONG: 12345678901123451111111111}" UserInfo={NSLocalizedDescription=Error Domain=TOO_LONG Code=0 "TOO_LONG: 12345678901123451111111111" UserInfo={NSLocalizedDescription=TOO_LONG: 12345678901123451111111111}}
2016/10/29 11:22:23:649  Issue while parsing number: Error Domain=NOT_A_NUMBER Code=0 "Error Domain=NOT_A_NUMBER Code=0 "NOT_A_NUMBER:" UserInfo={NSLocalizedDescription=NOT_A_NUMBER:}" UserInfo={NSLocalizedDescription=Error Domain=NOT_A_NUMBER Code=0 "NOT_A_NUMBER:" UserInfo={NSLocalizedDescription=NOT_A_NUMBER:}}`

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Numbers should not be included in complete.
### Device info

**Device**: iPhone 5s
**iOS version**: 10.1
**Signal version:** 2.6.2

**Comment by ntno** [comment]
same- in my logs it looks like a combination of my work # and mobile #
