### ISSUE TITLE
Consolidate dependency management.

### ISSUE THREAD

**Issue by elland** [signalapp/Signal-iOS#1471]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

Currently the app uses both Carthage and Cocoapods for dependency management, making the building and updating process more cumbersome that it needs be.

I propose we move to Carthage exclusively. That way there's only one manager, and using Carthage it's easier to bundle the frameworks as well. 

Carthage is simpler to use and manage than Cocoapods, and in my personal experience not as prone to issues and errors, it also takes much less time to update.

By having all the frameworks bundled with the source code, it makes building and running from a newly cloned repository that much faster and easier, reducing the barrier to entry as well.

If that is not a feasible approach, it should at least move the single Carthage dependency to Cocoapods.

**Comment by michaelkirk** [comment]
Thanks for bringing it up, I agree this is an annoying hack. 

To explain how we got here, some of our dependencies are not currently compatible with being built as dynamic frameworks, and yet others (swift) *must* be built as dynamic frameworks. 

The current situation won't be resolved until all our upstream packages are fixed, which you are free to help with! One approach to find out what needs to be done, would be to add `use_frameworks` to the Podfile and try to build.

I'm ok with either cocoapods or carthage as the final winner. I too have a small preference for the Carthage model, but I don't have much experience using the carthage corollary to "development pods".

**Comment by Elland** [comment]
@michaelkirk as with so many other things I've found in this project, this too should've been documented. I'll see what I can do today to move everything to Frameworks. 👍

**Comment by Elland** [comment]
It's possible this has been a while since someone checked, but I just switched Cocoapods to use Frameworks instead and they all built fine. Or at least it looks like they did.

**Comment by michaelkirk** [comment]
Just checking, did you only run pod install, or did you actually build the
project successfully?

re: documentation, it would be helpful if you could explain more
specifically what documentation would have been helpful to you. It would be
even more helpful if you could submit a PR.

**Comment by Elland** [comment]
@michaelkirk It did work but from that to being able to build Carthage frameworks is quite the distance. I started getting on that, but I'm not sure when I'll be able to finish, since there are so many dependencies that are just pure C code for now.

Documentation: Well, pretty much everything. I'd love to be able to submit a PR with more documentation, but for that I need get to the point where I understand what is going on, and since there's no documentation explaining that, it will be a while.

**Comment by malhal** [comment]
Since this project is already in Git, it should use Git submodules. Those alternatives are only necessary if not using Git.

**Comment by Elland** [comment]
For an app with that amount of dependencies and cross-dependencies, manual  management sounds like a job in itself.

**Comment by malhal** [comment]
Yeh so by merging dependencies I find that adds more issues that it solves. I prefer to allow dependencies to have their own versions of common dependency, and use compiler features to allow them to co-exist. Do you have an example of a cross-depedency in this project?

**Comment by Elland** [comment]
I'd rather just use Carthage instead. With submodules, which is almost no different than just drag and drop files, we could have all kinds of conflicts. So the idea would be to add yet another dependency to try to make sure that the other dependencies don't clash with each other? Sounds like a lot of work. 😢 

That being said, I'd be happier if we could reduce the number of dependencies altogether.

**Comment by malhal** [comment]
Sadly Carthage looks even worse, so many unresolved issues for things that Xcodes own build process handles perfectly already. It kinda reminds me of the needless wrappers we used to see in the early iOS programming days.

**Comment by Elland** [comment]
Worse than cocoa pods? That has not been my experience. I do agree that the whole dependency management landscape for iOS/Mac is pretty bleak tho.

**Comment by michaelkirk** [comment]
I'm sympathetic to the goal, but it's unlikely that we'll be getting rid of all dependency management any time soon. I *do* think this ($1471) is a valid issue, and we should work to make dev set up easier. Eager to see a PR with cocoapods working in the short term if it was really that simple @elland.

For the sake of everyone subscribed to this repository, if you'd like to continue with the discussion on whether Cocoapods or Carthage sucks more, please do so on the forum: https://whispersystems.discoursehosting.net/

**Comment by Elland** [comment]
👌🏻

**Comment by cesarbiods** [comment]
Any update on this issue? It's been years since the last comment and swift has an official package manager (SPM) now.
