### ISSUE TITLE
Swiping on message notification switches to conversation list and then switches to conversation

### ISSUE THREAD

**Issue by zbenjamin** [signalapp/Signal-iOS#1484]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When I swipe to view a text notification on the lock screen and I was most recently in the conversation that the notification is for, Signal appears to switch away from the relevant conversation to the conversation list and then back to the relevant conversation.

Note that I definitely observe this with a group conversation, but I am unsure whether it also occurs with 1:1 conversations. I am also unsure whether the app needs to be closed or unloaded from memory for the bug to trigger, but I can do some additional narrowing if necessary.

### Steps to reproduce
- open up a group conversation
- press the home button
- lock your phone
- have someone else send a message to the group conversation
- swipe on the notification to jump to the message

**Actual result:** Signal opens, showing the group conversation. It switches to the conversation list and then back to the group conversation. During that time, you can't interact with the app.
**Expected result:** Signal opens directly to the group conversation.

### Device info

**Device**: iPhone 6
**iOS version**: 10.1.1
**Signal version:** 2.6.5

**Comment by michaelkirk-signal** [comment]
This was fixed a while back.
