### ISSUE TITLE
Feature suggestion: Call logs and duration time

### ISSUE THREAD

**Issue by iadmir** [signalapp/Signal-iOS#1492]
Sometimes it's good to know how long the call lasted, the current version does not display information about the duration of the call.
Also it would be great to see call logs in a single section.
Perhaps it would be useful to have a call logs instead archives conversations.

**Comment by Aktariel** [comment]
Sometimes archived conversations are useful. And I'm sure there are people out there who use them -  I'm for sure one of them. (https://xkcd.com/1172/)

I don't know of any reason why we couldn't have all three sections though. I'm definitely a fan of call logs. Though they would need to be able to be removed or archived.

**Comment by iadmir** [comment]
@Aktariel You're right, that is best solution and it might look like this.
Calls - Messages - Archive

![designd](https://cloud.githubusercontent.com/assets/23726384/21185775/58c9eda6-c212-11e6-8efa-28707c9ff76c.png)

**Comment by caveman1973** [comment]
And should be off by default.
