### ISSUE TITLE
Display specific error message when downloading attachment 404's

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1503]
When receiving an allocated but un-uploaded attachment, Signal-iOS is put in a weird state.

Although a well behaving client shouldn't be sending empty attachments, it happens. 

There is an info message that says "New attachment queued for retrieval"
But when you tap it, it briefly changes to "Attachment is downloading"
Then back to the "New attachment queued for retrieval"

### Notes

Normally attachment sending works like this:

1. sender's client requests an attachment allocation from SignalService (SS)
2. SS response with (pseudo json) `{attachment_id : 123456789, upload_location: "https://s3bucket/unique-attachment-location"}`
3. sender's client uploads attachments to upload_location
4. sender's client sends a message saying there's an attachment available with id "123456789"
5. receiver asks SS where it can get attachment with id 123456789
6. SS responds with `{attachment_id : 123456789, upload_location: "https://s3bucket/unique-attachment-location"}`
7. receiver fetches attachment from upload_location

If 3. fails, Signal-iOS shouldn't proceed with sending. (I believe this to already be the case). But if a misbehaving client *does* send an empty attachment, 6. will result in a 404. In that case, instead of reverting to "New Attachment Queued for Retrieval" we should say "Attachment Failed to Download".

**you can simulate an empty upload** by commenting out the upload code at https://github.com/WhisperSystems/SignalServiceKit/blob/master/src/Network/API/OWSUploadingService.m#L76 and just calling the `successHandler()` directly.

## Update

There were actually two parts to this bug. The first, solved here: https://github.com/WhisperSystems/Signal-iOS/pull/1534

Was that we were showing "attachment queued" instead of "downloading failed", the second part is still unresolved, and involves surfacing the specific error message to the user.

### Desired Behavior

We should remove the existing "tap to retry-download" behavior.

Instead, when I tap on a failed attachment download, I should see an action sheet.

The body of the action sheet should contain the specific error description.

The actions should be "Delete", "Cancel" and "Download Again".

**Comment by jschneier** [comment]
I looked into this. This is the logic in `TSMessageAdapater.m`
```objc
if (pointer.isDownloading) {
    adapter.messageBody = NSLocalizedString(@"ATTACHMENT_DOWNLOADING", nil);
} else {
    if (pointer.hasFailed) {
        adapter.messageBody = NSLocalizedString(@"ATTACHMENT_QUEUED", nil);
    } else {
        adapter.messageBody = NSLocalizedString(@"ATTACHMENT_DOWNLOAD_FAILED", nil);
    }
}
```

Thus the user only sees the fail message if `_downloading = YES` and `_failed = NO` which in my cursory research inside of SignalServiceKit I'm fairly certain we can't hit.

I see a couple possible ways forward but would like your input first @michaelkirk.

**Comment by michaelkirk** [comment]
> Thus the user only sees the fail message if _downloading = NO and _failed = NO which in my cursory research inside of SignalServiceKit I'm fairly certain we can't hit.

I think that could happen if the app is closed mid download.

**Comment by michaelkirk** [comment]
Actually @jschneier, upon re-reading, that code you pasted just looks plain wrong.

**Comment by michaelkirk** [comment]
I've addressed the most heinous part here: https://github.com/WhisperSystems/Signal-iOS/compare/mkirk/fix-download-failed-message?expand=1

But, as we did with surfacing *specific* error messages for message sending, so should we for attachment downloads. E.g. distinguishing between "You're not online"  vs "404, that attachment doesn't exist" or whatever the `error.localizedDescription` might be.

I've updated the description to describe how I'd envision this working.

**Comment by jschneier** [comment]
@michaelkirk so I mostly agree with your new description with the major caveat that you _can't_ download the 404 to begin with so having the `Download Again` option is misleading. Maybe there needs to be a new state - `corrupted` or similar.

**Comment by michaelkirk** [comment]
Agreed, that in addition to the above, having a notion of terminal failure which precludes the option to retry would be better.
