### ISSUE TITLE
Waiting to "Accept new safety numbers" on outgoing attachment can reference an attachment that is no longer available

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1507]
We don't store attachment blobs for ever, and if Alice attempts to send a photo to Bob, but Bob's client doesn't retrieve it for a long time, when Bob eventually *does* attempt to retrieve it, he will be unable to.

If Bob is just offline for a long time, we can't really do anything about it except display a better error message as here: related: #1503 

One case we *can* prevent though, is a delayed download due to Alice not accepting Bob's changed Safety Number for a long time.

### Details

Normally attachment sending works like this:

1. Alice's client requests an attachment allocation from SignalService (SS)
2. SS response with (pseudo json) `{attachment_id : 123456789, upload_location: "https://s3bucket/unique-attachment-location"}`
3. Alice's client uploads attachments to upload_location
4. Alice's client attempts to send a message to Bob saying there's an attachment available with id "123456789"
5. If Bob's key has changed, then we stop here until Alice accepts Bob's new key and sending can succeed.
6. Bob receives, and asks SS where it can get attachment with id 123456789
7. SS responds with `{attachment_id : 123456789, upload_location: "https://s3bucket/unique-attachment-location"}`
8. Bob fetches attachment from upload_location

If step 5 takes many weeks, it's possible that Bob will receive an attachment notification for an attachment that no longer lives on our asset host.

One solution to this problem: If resending an attachment that was initially sent more than a week ago, re-upload a new attachment before sending.

**Comment by riyapenn** [comment]
Edge case that can be grouped with attachment alert changes https://github.com/WhisperSystems/Signal-iOS/issues/1503
