### ISSUE TITLE
Switching to a third party keyboard scrolls down slightly

### ISSUE THREAD

**Issue by illicitonion** [signalapp/Signal-iOS#1513]
- [x] I have searched open and closed issues for duplicates

### Bug description
Switching to a third party keyboard scrolls down slightly

### Steps to reproduce
- Install a non-default keyboard (in my case, gboard).
- Open a chat thread
- Press the globe-ish icon to switch keyboard to the non-default keyboard.

**Actual result:** The chat window scrolls by a fraction of a message.
**Expected result:** The chat window does not scroll.
Switching back to the default keyboard does not scroll at all.

### Screenshots
See video at https://reich.illicitonion.com/dump/20161201/tapkeyboardbug.mov - the keyboard with the G in the top-left is the custom one. The circle which moves around marks where I tapped.

### Device info
**Device**: iPhone 6
**iOS version**: 10.1.1
**Signal version:** 2.6.6

The debug log was empty, I guess because I didn't actually perform any actions.

This looks similar to https://github.com/WhisperSystems/Signal-iOS/issues/1221 but doesn't feel like it's obviously the same bug.

**Comment by jschneier** [comment]
I noticed this when I was working on the keyboard switching behavior (this behavior was there before that). Nothing stood out to me and this seems like a problem that manifests from upstream (in JSQMessagesViewController). I'll take another look.

**Comment by mrphs** [comment]
I wonder if Signal should not let you use a 3rd party keyboard. Is there a way to make sure that keyboard doesn't call back home and doesn't (potentially) act as a keylogger?

**Comment by illicitonion** [comment]
@mrphs: There is a settings toggle, "Allow Full Access", per-keyboard. If this setting is disabled, keyboards aren't permitted to use the network; Apple claim that there are technical measures in place to prevent network access, and attempting to circumventing them is against appstore policies.

**Comment by Aktariel** [comment]
I would still love to see a toggle in Signal to allow or disable third-party keyboards - a lot of password managers implement this option, for example:

![img_0902](https://cloud.githubusercontent.com/assets/790061/21021357/f68722ce-bd2c-11e6-8c46-7d4ab0f55884.PNG)

**Comment by gfairchild** [comment]
I just came here to report this same issue. I like the idea of a setting to disable 3rd party keyboards, but I don't think it should be forced; it should definitely be a setting.

The scroll bug is pretty irritating, and I'd love to see it get fixed.
