### ISSUE TITLE
UX - there's no way to save or copy the number of a contact

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#1525]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I know there was a [bug with iOS 9](https://github.com/WhisperSystems/Signal-iOS/issues/919) where you couldn't save a contact's number if it wasn't already in your contact list but at least you could copy it and then go to contacts app and save it there. In the latest version I can't seem to find a way to save the number without actually memorizing it and enter it manually in my contacts. I get a bunch of texts from mostly new people every week and the increase in inconvenience of adding new numbers have resulted in me not bothering to save them anymore and it gets kind of ugly from there.

It would be nice to figure out a way to write to contact list. or at the very least, go back to where you could copy the numbers and save them manually, instead of typing them.

### Steps to reproduce
- Have someone who's not on your contact list to text you
- Try to save their numbers
- Now try to find a way to copy their numbers

**Actual result:** There's no way to be able to copy or add numbers. No indicator, help or guidance on what's the right way to do it, which makes the users sometimes feel stupid for not being able to figure something basic out.
**Expected result:** After tapping on the phone number and where you see the rest of the info/settings of that contact, there should be a button to add contact or copy phone number with direction on how to save the number.

### Device info

**Device**: iPhone
**iOS version**: 10.1.1
**Signal version:** 2.6.6

**Comment by michaelkirk** [comment]
Is this really a useful feature if #919 is fixed?

**Comment by mrphs** [comment]
Well before the latest update, you could at least copy the number. Now you can't even do that and it makes everything a pain in the neck. this was a reasonable workaround  for #919 that I don't know why has been removed :/

**Comment by mrphs** [comment]
And this reminds me of another related problem. when somebody texts you a number, if you 3D press it, these options appear:
![signal2](https://cloud.githubusercontent.com/assets/453701/20899944/534f46e0-bb24-11e6-9c02-cb9f161df381.png)
And if you tap to save it, you'll get to this page and then you hit #919 again.
![signal-1](https://cloud.githubusercontent.com/assets/453701/20899980/6f60947e-bb24-11e6-9b2e-41df8131f94a.png)

**Comment by kevinmbeaulieu** [comment]
@michaelkirk If #919 is fixed, this would still be useful for iPhones without 3D touch, right?

**Comment by StephenBoyd** [comment]
Of course the basic ability to create a contact for the person who has messaged you shouldn't be limited to the iPhone 6s and 7. As far as I can tell on my 5s running iOS 10, there's no support for any method of saving contacts at all. I'm about to type a number on my laptop so I can refer to it again after I open up the Contacts app.

**Comment by michaelkirk** [comment]
Just an update, #919 has been fixed, so you can add contacts from Signal, but you still can't interact with a phone number(apart from copy/paster).  The default phone number interactions are confusing because they refer to system actions (e.g. call or text with the system app, not Signal), so we've disabled them.

We (or an open source contributor) could add custom signal actions to phone numbers detected in text, like "Copy", "Save Contact", "send message" (via signal), "call" (via signal).

maybe helpful: https://stackoverflow.com/questions/2543967/how-to-intercept-click-on-link-in-uitextview

**Comment by muellermartin** [comment]
While issue #919 has been fixed, this still is a huge usability issue, e.g. when handling temporary contacts for adding users to groups.

**Comment by mailinglists35** [comment]
>@michaelkirk commented on Dec 5, 2016
>
>Is this really a useful feature if #919 is fixed?

yes. I don't give access to contacts to any app. there is no way I can copy the number. in whatsapp i long tap the number and a "copy number" pop-up appears
