### ISSUE TITLE
keyboard overlays "Rate Signal" when responding to notification

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1530]
## Actual Behavior

From a user report:

> I opened Signal to respond to a message from a friend, and the notification asking me to rate Signal appeared on top of the message from my friend, with the virtual keyboard on top of the notification. Which made it impossible to either dismiss the notification or use Signal.

## Expected Behavior

You should not see the rating pop-up when the app was launched in response to a notification.

**Comment by michaelkirk** [comment]
Saw this again.


![rating_popup](https://cloud.githubusercontent.com/assets/217057/22379884/3cacb786-e489-11e6-8511-8d4e5ce5b5e9.jpg)

Happened here: https://gist.github.com/anonymous/3ce5e80976bd137bdde605bb1e9b24a8#file-org-whispersystems-signal-2017-01-25-19-19-log-L53

**Comment by jaropawlak** [comment]
When iRate object is created, it makes first attempt to display popup instantly, which can happen even before the prevent flag is set. I tried to use iRateShouldPromptForRating delegate method, but during this first attempt, that is not even being checked too. In that situation I have modified AppDelegate not to create iRate object when app is being launched by notification.

**Comment by michaelkirk-signal** [comment]
This should be fixed in the latest appstore release. We're no longer using this custom rating API, and instead using the builtin iOS rating system.
