### ISSUE TITLE
Allow registering multiple numbers to one device

### ISSUE THREAD

**Issue by mhkeller** [signalapp/Signal-iOS#1544]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

It would be nice to be able to access multiple accounts through the iOS app. I'm imagining it could work similar to how the Slack iOS app allows you to add multiple domain accounts and jump between them as separate environments. 

This setup would solve https://github.com/WhisperSystems/Signal-iOS/issues/1120 in a more straightforward way and avoid any fancy auto-detection. The use case for this is you could have Number A registered to Signal Desktop, say for work, on Laptop A. On a personal computer, Laptop B, you would register your personal number, Number B. On your phone, you would have access to both Number A and Number B accounts and avoid the need to  carry two phones. This would also help the iOS app come more in line with the features offered on Signal Desktop, which allows linking multiple numbers afaik.

[edit] Looks like I was wrong on the last point. I don't think Signal Desktop supports this either.

**Comment by rootless4real** [comment]
Many phones around the world support multiple SIM cards. With VoIP numbers, Google Voice, etc., a phone can now support many numbers. Many times the numbers are from different countries (to support contacts in each country with a local number). Without the ability to recognize/register multiple numbers this becomes exceptionally difficult.

**Comment by dcrafti** [comment]
Agreed. I've just moved to another country, and I think I'm not getting messages at all on my existing one, because it's got a new SIM in it.

**Comment by nisc** [comment]
**Fourthed!** Please add multiple number support (or better yet, login via account name / email address).

**Comment by mhkeller** [comment]
@charlesmchen-signal what do you think the status of this is? Is it something we can expect in the future?

**Comment by mweidman** [comment]
Would also like support for this feature, it would be ideal if I could use my Google Voice number in addition to my main phone number all within the Signal app.

**Comment by mailinglists35** [comment]
bad bot stale you are

**Comment by nickensoul** [comment]
any news?

**Comment by justinmayer** [comment]
This is indeed still relevant and important, particularly for folks who live in more than one country and who use multiple SIM cards.

**Comment by Cerberus0** [comment]
Please ignore the stale bot, it does not know the difference between bugs and feature requests because [this is no longer the right place to submit or discuss feature requests](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md). Please let this GitHub issue be closed and continue this discussion on the community forum:

https://community.signalusers.org/c/feature-requests/17

Thanks!

**Comment by mhkeller** [comment]
This would still be a very useful feature

**Comment by EvanHahn-Signal** [comment]
As was mentioned, we'd like to use GitHub for bug reports, not feature requests. Please use [this community forum thread](https://community.signalusers.org/t/multiple-separate-user-profiles-multiple-identites-for-example-but-not-exclusive-to-dual-sim-phones/2361) to discuss this feature further, and the community forums to discuss other feature requests in general.
