### ISSUE TITLE
Phantom notification/empty alert, "New message" notification without message received

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1554]
- [X] I have searched open and closed issues for duplicates and found possibly related issues of: https://github.com/WhisperSystems/Signal-iOS/issues/734 and https://github.com/WhisperSystems/Signal-iOS/issues/272

----------------------------------------

### Bug description
Receive "New message" alert when there is no new message. Or receive "New message" alert but never see the new message displayed

### Steps to reproduce
- Receive "New message" notification
- Open Signal

**Actual result:** Do not see any new messages in any conversation threads
**Expected result:** See the new message if there is one, or never get the notification of a new message if there isn't one

### Device info

**Device**: iPhone 7
**iOS version**: 10.2
**Signal version:** 2.6.8

### Link to debug log

 https://gist.github.com/a26dadc03e75a3ab9a6a44a7851b0f37 

**EDIT: Logs from other users:**
1. https://gist.github.com/8b812f4fd80c712cf0e0f1272e37e6ae, notification received Between 2:37 and 2:40am
2. https://gist.github.com/4e4772737a0e7c47f1a20e748d9f7616, user receives alert after sending a message; Shortly after 3pm
3. https://gist.github.com/1da0d376052e16970505ee892b9c05a5, user receives an alert but no message, receives messages later in the day
4. (v 2.6.15) https://gist.github.com/2fab09918477a8ac3f5322cfb8058bc7
5. (v.2.7.1) https://gist.github.com/anonymous/e7c2d5d042766aacaf7b5a1fe6a3e4b6
6. (v 2.8.3) https://gist.github.com/anonymous/496829ef435bbc6e67640011d62d8f70
7. (v 2.8.2) https://gist.github.com/52957aa74ea768872430e7115c450ece 
8. (v 2.9.2) https://gist.github.com/4bb9e866e2583e88ddc4f0a099754b42

**Comment by seren** [comment]
I just getting a stream of phantom notifications as well. Here's the debug log:
https://gist.github.com/anonymous/c00098aee89377f503c4903ee7deb33e

**Comment by michaelkirk** [comment]
@seren do you have a linked desktop device by chance?

About what time did you see all the phantom notifications?

**Comment by seren** [comment]
Not currently, though it's possible I set one up a year or two ago. It was around 11:30am PDT, and occurred for about 20 minutes.

**Comment by michaelkirk** [comment]
Even if you’re not using it, can you verify that you no longer have a linked device?

Go to Settings > Linked Devices

And make sure nothing is listed. If something is listed, and you’re not using it, you should probably remove it.

M

**Comment by seren** [comment]
Just checked and there aren't any linked devices.

**Comment by nym** [comment]
My wife is having the same issue. It may be due to a linked device, I need to find out.

**Comment by nym** [comment]
She has her laptop linked, and she says the messages appear on her iphone as soon as she disconnects from wifi. Note these are signal messages, not SMS messages she is missing.

**Comment by shadysamir** [comment]
Seeing same behavior with ios 11.0.3 and when trying to send messages it says message failed. The other person sending me only sees one check mark even after I receive the "phantom" notification

**Comment by bond-alexander** [comment]
I am also receiving this behavior on iOS 11.0.3. I have never set up a linked device.

**Comment by christophhagen** [comment]
Same problem. On some days I get multiple "New message" alerts, without any message showing in Signal. One interesting side effect: When I get such a message the icon badge for Signal shows an increasing number of new messages, currently 47. When I open Signal, the badge disappears. When I get another such message, the badge again shows the next higher number. It's as if Signal is counting some type of unread messages.

I've been getting these messages for a while now, with different versions of Signal iOS. It started before I linked Signal Desktop, and has continued afterwards. It also persists across multiple iOS updates, currently on the latest public beta.

Debug log:
https://gist.github.com/509e964aac58aebec5b9d81f6918511d

**Comment by gsbabil** [comment]
Not sure if this is 100% related, but sharing here first before
opening a new issue ticket to avoid being redundant.

#### ## Permanent _"Phantom"_ Notification Badge

- I have a permanent notification badge next to the contact name
  (indicating to a new message), but there's no new message within
  the conversation thread.

- I have scrolled from the very top to bottom of that thread looking
  for the new message (and to get rid of the notification badge),
  but the notification badge won't go away.

My Signal version is `2.25.1.1`. If someone knows how to get rid of
the badge without deleting the app (in order to preserve data),
please share. I'm okay to delete the app and reinstall, if there's a
way to preserve data on iOS.

Thanks.


_P.S._

The notification badge appears both on iOS home-screen on the
top-right corner of the Signal app icon, and also within the Signal
app main view next to the contact's name. Unfortunately, I'm not
very sure how to reproduce this, but having a quick way to delete
all the unread notifications _i.e._ "mark all read", I think could be 
rather useful.

Thanks.

**Comment by michaelkirk-signal** [comment]
@gsbabil - that sounds unrelated to this existing issue. Can you file a new report (and fill out the issue template)?

**Comment by michaelkirk-signal** [comment]
Phantom "New Message" UI banners/lock screen notifications should no longer be happening. Please open a new issue referencing this one if they are.
