### ISSUE TITLE
Neither iPhone party able to call the other 

### ISSUE THREAD

**Issue by zoot** [signalapp/Signal-iOS#1555]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Both people are unable to call the other.

Each person's phone produces a ringing sound on the caller's side for a few rings, after which ringing stops.

No ringing or any other incoming call indication is shown on the receiving person's phone.

Both people are able to send and receive text messages.

### Steps to reproduce

- open existing chat with other party
- tap telephone icon to initiate call

**Actual result:**

- next screen shows "Connecting..." with an audible ringing sound
- After several rings the call screen closes and returns to the chat dialogue
- Dialogue reads "You called Name"

**Expected result:**

- Caller to hear further ringing 
- Receiver of call to hear and see incoming call
- Connect both parties for voice call

### Device info

**Devices**: iPhone 6s and iPhone 7
**iOS version**: 10.1.1 (both phones)
**Signal version:** 2.6.8 (both phones)

### Link to debug log

This debug log is from the iPhone 6s

https://gist.github.com/0cd24f7ef76f6f83ef652f046a31940a

**Comment by riyapenn** [comment]
You AND your contact will both have to be connected to the internet for your call to be placed and connect.  If the call does not complete, it is likely that your contact is not on an internet connection at the time you placed the call or [you need to check your firewall](https://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-).

**Comment by zoot** [comment]
We were both online and successfully chatting via text message on both Signal and Telegram while using the same mobile network. I've never had issues with Signal before on this phone, but have seen several updates since the last time I used the app.

**Comment by riyapenn** [comment]
Did you check your [firewall settings](https://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-)?  Have you tried placing a call when you and your contact are on different internet connections than the ones you were originally one?

**Comment by zoot** [comment]
Ok, we've resolved the issue. My friend upgraded his iPhone 7 to iOS 10.2 and we're now able to call one another. I find that rather strange, as we were both using the same OS version before. Is there a way to retrieve historic debugging info from his phone to shed some light on what may have been the issue?

**Comment by riyapenn** [comment]
No, but your Debug logs may contain a few days worth of info Signal > Settings > Advanced > Submit Debug Log > Email > Send or paste here.

**Comment by zoot** [comment]
Ok, here's the debug log from the iPhone 7, as per my above post. Thank you.

https://gist.github.com/5283ee3f44aa2e8bb988df01351f69fd

**Comment by jonathanou** [comment]
Just wanted to say I am seeing the exact same problem as well.  Both clients are on iOS 10.3.2 and we cannot call each other.  Text messages are fine, though.

When calling I just see Signal "connecting" and no matter how long I wait, my friend's Signal never rings.  As soon as I hang up, however, my friend receives a notification saying she missed my call.  Likewise, she also cannot call me and I similarly receive notices that I missed her call without Signal ever ringing.

This started to happen consistently around this week.  Before this week I was able to successfully call my friend _most_ of the time.

Here is my [debug log](https://gist.github.com/89af9e8f38fca7eb355c71ef1c825292) in case it helps, I have an iPhone 6S.  I tried calling several times on 6/28 and none of them succeeded.

Thank you for creating such a useful app, I hope you guys can fix the voice call problem soon!

**Comment by michaelkirk** [comment]
Hey @jonathanou, sorry you're having trouble connecting calls. We just released a new version (2.6.13) which made some improvements to call connectivity and call logging. Could you both upgrade?

If you still have trouble connecting a call after upgrading, could you **both** paste a debug log in this issue right after the call?

**Comment by jonathanou** [comment]
Upgrading didn't seem to help.  I was able to place 2 or 3 calls successfully, but then it stopped working again.  Here are the logs:

[Caller](https://gist.github.com/anonymous/131187ba6f465847c61f152ccc6d4f66)
[Receiver](https://gist.github.com/anonymous/ddec6150b6b3e1383e1e497d51ca9464)

Hope this helps!

**Comment by sological** [comment]
This has not been solved since I still get this.

**Comment by JoshGrahamMoore** [comment]
Hi there, same issue for me. When calling I just see Signal "connecting" and no matter how long I wait, my friend's Signal never rings. As soon as I hang up, however, my friend receives a notification saying she missed my call.

Exactly the same for me.
