### ISSUE TITLE
when a contact changes its security number, handling the situation with 

### ISSUE THREAD

**Issue by mrkiko** [signalapp/Signal-iOS#1565]
When a contact changes its security number, handling the situation with VoiceOver isn't easy

It can still be done with some long taps, but at least for me, this isn't 
confortable.
Thank you guys for your work.

**Comment by michaelkirk** [comment]
@mrkiko - have you tried the latest safety number change behavior? I'm curious if this is still an issue.

**Comment by mrkiko** [comment]
I will try in a short moment. And I'll let you know here ASAP.
BTW, I can confirm you I am still unable to read incoming messages with 
voiceover when my phone is in italian. Do you think there is a way to fix 
this? Thanks for the great work.
Thank you very much,
Enrico

**Comment by mrkiko** [comment]
Not being able to find a contact who can collaborate with me on this, 
unfortunately.
If someone would like to help, then contact me somehow. Sorry.

Or alternatively, I think we could close this issue. I'll reopen it if I 
notice the problem is still present. Sorry.
