### ISSUE TITLE
Documentation: Export/Import only works for Android, not iOS

### ISSUE THREAD

**Issue by eharris** [signalapp/Signal-iOS#1568]
This is a request for improving the documentation for export/import at:

https://support.whispersystems.org/hc/en-us/articles/212535828-How-do-I-import-or-export-messages-

Searching for help about exporting messages finds that help page, but it wasn't immediately obvious that it only applied to Android, and that no such functionality exists (yet) for iOS.

It would be very nice if the documentation made it clear what features are/are not available in each version.  I had recommended the app to a group of friends based on that functionality being available, and after using it for a while we only then realized that we couldn't save our messages when moving to new devices.

(I would have preferred to have just added this as a comment on #967 rather than a new issue but #967 is locked for comments.)

**Comment by NiklasBr** [comment]
Related because #967 is locked: I added [a bounty](https://www.bountysource.com/issues/28598496-message-export-backup) to fix the missing export or backup option in this app.

**Comment by Ginari** [comment]
Really missing this feature. I don't want to lose all my conversations. At least the option for export/backup should exist, in my mind.

**Comment by wslack** [comment]
Eeeeesh I didn't realize this wasn't available until changing devices. This isn't good.

**Comment by alichtman** [comment]
It looks like this feature has been implemented in https://github.com/signalapp/Signal-iOS/pull/2914, but is restricted to developer usage only. Check out [this comment](https://github.com/signalapp/Signal-iOS/pull/2914#issuecomment-356317801) in specific.

I don't understand why this import / export feature hasn't been exposed to users.

**Comment by wslack** [comment]
I think the documentation has been addressed; the missing feature is still a problem.

**Comment by alichtman** [comment]
Yes, this feature is still missing on iOS.

**Comment by alichtman** [comment]
Nope. No issue duplication, but correcting the title to not be a documentation ask is a good call.

**Comment by larstobi** [comment]
> [4418777](https://app.bountysource.com/people/102370-4418777) started a solution on [Message export/Backup ($1,145)](https://app.bountysource.com/issues/28598496-message-export-backup).
> WhisperSystems 
> 
> 1 day ago

Work on this has been started.

**Comment by NiklasBr** [comment]
@larstobi Nothing is happening. Note that the person claiming to have started on this is actually claiming that his *Signal competitor* [HARIHARANS1995/smsencryptbackup](https://github.com/HARIHARANS1995/smsencryptbackup) which has not seen activity since 2019, and which has nothing to do with Signal will solve this. It is extremely unlikely to fix this issue. It is likely an attempt at a money grab, hoping that by claiming to work on this and hoping that Signal will close this issue (as they are likely to do) he will be rewarded the bounty.

**Comment by larstobi** [comment]
@NiklasBr I see. As per BountySource's Frequently Asked Questions, the backers can accept or reject a solution, and only i they accept they will pay the bounty. So, I'm not sure if moneygrabs work if the backers don't accept the solution.

**Comment by NiklasBr** [comment]
Documentation still missing, bot.

**Comment by NiklasBr** [comment]
Still relevant, dear bot.

**Comment by EvanHahn-Signal** [comment]
We're trying to use GitHub for bug reports and [the community forums](https://community.signalusers.org/c/feature-requests/17) for feature requests. Please open a thread there (or find an existing one).

Message backup is something we'd _love_ to build on iOS but haven't yet had the time.
