### ISSUE TITLE
Toggle button for 'Enable screen security' cannot be switched off

### ISSUE THREAD

**Issue by JohanDoe** [signalapp/Signal-iOS#1572]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Toggle button for 'Enable screen security' cannot be switched off

### Steps to reproduce
- Go to Settings -> Privacy -> Toggle button from 'enabled' to 'disabled' for 'Enable screen security'
- Go back via 'Settings <'
- Press 'Done'
- Check whether Toggle button for 'Enable screen security' is still disabled by repeating first step.

**Actual result:** 
The toggle button for 'Enable screen security' remains 'Disabled' after pressing 'Done'.  I thus can never choose to see and actually see Signal previews in the app switcher.

**Expected result:** 
I expect the toggle button to remain disabled for the 'Enable screen security' once this is chosen. This would enable me to choose to see and actually see Signal previews in the app switcher. 

### Device info

**Device**: iPhone 6s
**iOS version**: 10.2
**Signal version:** 2.6.9

**Comment by caveman1973** [comment]
Mine works fine.
iOS 10.2.1
IPhone 5s
Signal 2.6.13

**Comment by michaelkirk-signal** [comment]
I believe this is no longer an issue. If you're still having trouble, please re-open with some fresh details.
