### ISSUE TITLE
"Failed to unregister from Signal"

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1575]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

I consistently got this error when trying to unregister from Signal.  I was trying to unregister because I had registered a second device using the same phone number for testing purposes, not knowing that it would break the first device registered using that number.

### Steps to reproduce

- Register iOS Signal on device 1 using phone number X.
- Register iOS Signal on device 2 using phone number X.
- Device 1 is now in "broken" state - can't send messages.
- On Device 1, try to unregister.

**Actual result:** "Failed to unregister from Signal" alert.
**Expected result:** Unregistering from a "broken" device should yield a special error message - and possibly reset the app to a non-registered state.

### Screenshots

![img_5913](https://cloud.githubusercontent.com/assets/625803/21618880/2c2bd620-d1bb-11e6-92dd-4306beec3763.PNG)

### Device info

**Device**: One device was an iPhone 7 Plus and the other was a simulator, but I doubt it matters.
**iOS version**: 10.2
**Signal version:** 2.6.9

**Comment by michaelkirk** [comment]
just a note: You'll likely see a 401 unauthorized in this case. See here for similar case handled when trying to send a message after unregistering: https://github.com/WhisperSystems/SignalServiceKit/blob/master/src/Messages/OWSMessageSender.m#L486

**Comment by riyapenn** [comment]
Related to https://github.com/WhisperSystems/Signal-iOS/issues/1562 with regards to user experience for an (unexpected) unregistered device.

**Comment by yaneurabeya** [comment]
+1. I ran into this issue today as well.

**Comment by mamatadesai** [comment]
+1 can't delete account 
![WhatsApp Image 2021-01-15 at 1 37 43 PM](https://user-images.githubusercontent.com/28913776/104781351-2fb2d900-5737-11eb-83a7-36a887bc316e.jpeg)
