### ISSUE TITLE
App crashes when saving contacts

### ISSUE THREAD

**Issue by br4di** [signalapp/Signal-iOS#1591]
Users cannot add contacts from Signal. Clicking on "Create New Contact" brings up a page with fields for contact information, but no option to save said contact to the iOS Contacts app. The app must be closed completely and reopened to return to messages.

**Comment by riyapenn** [comment]
This must only be through the group interface as this option was removed from direct conversations.

**Comment by joostrijneveld** [comment]
While the button is not visually present, I noticed that it's still there. Try clicking in the blank area in the top-right corner to save (and the top-left to cancel).

**Comment by bradixx** [comment]
This is great, thank you. Any idea when a visual button would be added?

**Comment by Mihahn** [comment]
This shouldn't be an issue anymore, right? Please close it then.
