### ISSUE TITLE
Server failed for / can not make outgoing calls on iPhone 6S+, works with iPhone 5 (same WiFi/data networks)

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1613]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Can not place outgoing call on iPhone 6S plus, but can receive.  iPhone 5 on the same internet connection can place calls (to this iPhone 6s plus). 

### Steps to reproduce
- Open Signal on iPhone 6S plus
- Place call to contact

**Actual result:** "Server failed." However, iPhone 5 on the same network successfully places call. 
**Expected result:** successful call placed

### Screenshots

N/A

### Device info

**Device**: iPhone 6S plus
**iOS version**: 10.0.1
**Signal version:** 2.6.10.2

### Link to debug log

https://gist.github.com/2340765f3928bc54a8f213f86cab647b

**Comment by michaelkirk** [comment]
>  2017/01/16 21:59:21:877  [RPAccountManager] Failed to update push tokens: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17022e840> { URL: https://master.whispersystems.org:443/api/v1/accounts/apn } { status code: 401, headers {

That log shows a 401-unauthorized error when contacting the red phone server. My guess is that this user cannot make a call from *any* network.


> 2017/01/16 21:58:29:725  [TSAccountManager] Successfully obtained Redphone token
> 2017/01/16 21:58:29:740  [RPServerRequestsManager] Making request: <RPAPICall: 0x170449000> /api/v1/accounts/token/[ REDACTED_PHONE_NUMBER ]:1484621909:c6cffc22cd02e193e9a0
> 2017/01/16 21:59:19:783  [VersionMigrations] Checking migrations. currentVersion: 2.6.10.2, lastRanVersion: 2.6.10.2 <— !!! indicates a launch
> 2017/01/16 21:59:19:964  The app was launched from inactive

It looks like the user *just* installed Signal, and that their app crashed mid-registration (or it’s possible that they closed it). In any case, they'll have to reinstall to get red phone calling working.

Could you ask them to check for and submit a crash report?
