### ISSUE TITLE
Can't disable call alert vibration with volume down button

### ISSUE THREAD

**Issue by iadmir** [signalapp/Signal-iOS#1624]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I had a call from a friend when I couldn't answer, I tried to turn off the vibration with the volume down button but without success.

### Steps to reproduce
- press volume down button to disable call alert vibration in silence mode

**Actual result:** Still vibrate
**Expected result:** Vibration is disabled

### Device info

**Device**: iPhone 5S
**iOS version**: 10.2
**Signal version:** 2.6.12

**Comment by michaelkirk** [comment]
Thanks for the report.  

This will be fixed for iOS10 users as part of our CallKit integration https://github.com/WhisperSystems/Signal-iOS/issues/1213

We're working on it now. 

This could be addressed for pre-iOS10 users separately doing something like: http://stackoverflow.com/questions/28193626/cleanest-way-of-capturing-volume-up-down-button-press-on-ios-8
