### ISSUE TITLE
Deleting an undelivered message should prevent delivery

### ISSUE THREAD

**Issue by pde** [signalapp/Signal-iOS#1625]
Steps to reproduce:

1. iOS device without functioning network access
2. Attempt to send a message (it's shown as greyed out / not delivered to Whisper Systems' servers)
3. Circumstances change! Hold and press, select "Delete" on the message
4. Bring device online, the message will be delivered anyway.

Expected behaviour:

Delivery attempts should cease when the message is deleted.

**Comment by michaelkirk** [comment]
Sorry to seem pedantic, but I want to double check that we're talking about the same thing: 

When we talk about "delivered" we usually mean the recipient has received it. So after sending a message to the server, it appears "blue" to you . Once the recipient fetches the message it is marked "delivered". There would never be a way for you to cancel an undelivered message once it's been sent.

But I **believe** you are talking about deleting an unsent "failed" (gray) message. That is, it appears to have never made it from your device to the Signal server.

Was this in a one-to-one chat or a group chat?

Do you know if the recipient has linked their phone with Signal-Desktop?

**Comment by pde** [comment]
Apologies for not using accurate terminology. Let me clarify and update my reproduction steps:

1. Connect an iOS device to a flaky network (eg, broken wifi or tenuous cellular data that may not actually deliver packets). Aeroplane mode won't work for reproducing the bug, since it leads to the immediate grey "deilvery failed" state.
2. Send message. Note that the message is shown as pale blue (I believe this is a state where attempts to upload to Whisper servers are still occurring).
3. Delete message
4. Recipient still receives message when my network connection improves.

I don't know if the receipient uses Signal desktop. I do use it.

If you don't have ready access to a broken network, I found the following steps simulated it: disable Cellular Data and Wi-Fi Assist (at the bottom of the very long Settings -> Cellular menu).  Join an `xfinitywifi` Wi-Fi network, without authenticating to it.

**Comment by pde** [comment]
Actually it's kind of tricky to get xfinitywifi to give me a pale blue message state rather than a grey one. But I've managed it at least once :)

**Comment by michaelkirk** [comment]
Was this in a one-to-one chat or a group chat?

**Comment by pde** [comment]
One-to-one.

**Comment by yaneurabeya** [comment]
I wasn't able to repro this via the following steps:
1. Open up Signal.app.
2. Put phone in airplane mode.
3. Send message to contact [other than one's self].
4. Delete message.
5. Bring phone online again.

**Comment by pde** [comment]
@yaneurabeya per [my comment above](https://github.com/WhisperSystems/Signal-iOS/issues/1625#issuecomment-274173340), using airplane mode doesn't give a repro case, but flaky or captive portal networks sometimes allow reproduction.

**Comment by Mihahn** [comment]
As we are able to delete messages remotely now ("Delete message for everyone"), this shouldn't be an issue anymore. If you agree, please close your issue.

**Comment by pde** [comment]
Agreed!
