### ISSUE TITLE
UIUX Message bubble width inconsistency

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1635]
- [X] I have searched open and closed issues for duplicates, most related to: https://github.com/WhisperSystems/Signal-iOS/pull/1269, will probably be related to message bubble sizing for dynamic font feature request: https://github.com/WhisperSystems/Signal-iOS/issues/1453 

----------------------------------------

### Bug description
Message bubble width sometimes is narrow, sometimes is wide

### Steps to reproduce
- No discernible pattern
- Sometimes occurs when navigating away from a conversation 
- "When I type a new message, the bubble is always the normal size right when it sends and will stay that way until I navigate away."

**Actual result:** Bubble width changes
**Expected result:** No change in bubble width

### Screenshots

Narrow:
<img width="231" alt="screen shot 2017-01-23 at 1 06 56 pm" src="https://cloud.githubusercontent.com/assets/4898366/22222876/7671d60a-e16d-11e6-824c-713d8c6195c7.png">

Wide:
<img width="230" alt="screen shot 2017-01-23 at 1 08 00 pm" src="https://cloud.githubusercontent.com/assets/4898366/22222879/7b047c54-e16d-11e6-9213-cca27aa6e980.png">

### Device info

**Device**: iPhone 5S
**iOS version**: 10.2
**Signal version:** 2.6.12

### Link to debug log

https://gist.github.com/a6378283bf64356725fa697453ffbd68
Log 2 (Signal 2.8.3): https://gist.github.com/anonymous/667656fdc23fa46e94dadff92ef06929
Log 3: https://gist.github.com/anonymous/820ba0f0f8cf23c2b8310c6d5091f5b5

**Comment by riyapenn** [comment]
Does this still occur? 
This looks to be resolved on 2.15+ based on the users who have previously reported this issue.

**Comment by denver-s** [comment]
Message bubbles have been recently reworked so this bug should be fixed.

**Comment by michaelkirk-signal** [comment]
Please re-open with some example text if you can reproduce.
