### ISSUE TITLE
App hangs during verification step

### ISSUE THREAD

**Issue by mr100percent** [signalapp/Signal-iOS#164]
While on iOS 8.0.2, during app launch the app asks for SMS verification. The user gets an SMS within seconds of entering their phone #, but when the verification code is entered, the app gets stuck with the spinning wheel and cannot progress. The app can go back, or the user can request a phone call with the verification code, but the app does not progress past the SMS verification step. The app correctly detects an incorrect code, but appears to get stuck on correct codes. Deleting and reinstalling the app on an iPhone 5 does not fix the problem.

**Comment by winkelsdorf** [comment]
Seems not to be fixed entirely, I am observing the same problem today with a fresh install (iPhone 6, iOS 9.1).

**Comment by FredericJacobs** [comment]
I'm unsure this is related to the client. I can see multiple reasons why this could happen. Ports on being open on the network to connect to the RedPhone server, activation server being unresponsive or other criterias.

As far as the client goes, it is not possible to deterministically reproduce this AFAIK.

**Comment by winkelsdorf** [comment]
I just fetched the latest master from the repo and installed it beside the App Store version. Same behavior shown. 

I just verified it to be related to the Client and looks like it's reproducible: In #933 it's mentioned that it might be related to Background App refresh. I quit the app, enabled Background Refresh, and it worked immediately.

So the scenario is:
- Disable Background App Refresh
- Install Signal
- Set Phone number
- Receive Verification Code
- Enter Code and Submit

Test Environment:
- iPhone 6 iOS 9.1
- WLAN Connection with unlimited Internet Access (i.e. outgoing ports not restricted)

Expected:
- Verification completed

Actual:
- Spinner running, never completing Verification
- No Error Message shown (Timeout, Server Response or other Errors)

Workaround:
- Quit App via Task Manager
- Enable Background App Refresh
- Rerun Registration Process
- Verification completes immediately

I had a quick look at it, as far as I can see only CallController uses UIBackgroundTaskIdentifier. I'll have a deeper look at this later..

**Comment by FredericJacobs** [comment]
If there's a bug related to background app refresh I would expect the issue to be in the network library: AFNetworking.

**Comment by winkelsdorf** [comment]
Yes, looks like, please see my edits for the previous post. Already tracked it down to operationManager / AFHTTPSessionManager in RPServerRequestManager.m.

**Comment by winkelsdorf** [comment]
I have no time right now to further debug this, but it's probably NOT related to AFNetworking.

requestPushTokenWithSuccess() in PushManager.m get's called multiple times, but the spinner continues. Probably related to your future handling?

**Comment by rygen** [comment]
Also happening to me with a fresh install (iPhone 5S, iOS 9.1) and in the simulator. Background App Refresh was always on. Tried on 4G and WiFi.
Yesterday it also happened to a friend of mine on a device running the latest version downloaded from the App Store.

**Comment by mikeokner** [comment]
I'm running into this as well with the 9.1 simulator. Had to switch back to my 8.4 simulator which was successfully verified a few months ago.

**Comment by rygen** [comment]
@mikeokner with [akatasonov](https://github.com/WhisperSystems/Signal-iOS/issues/955#issuecomment-160147404)'s help I was able to get past the verification screen. I didn't have push notifications set up for my copy of Signal, that was the culprit. But that's probably not the same issue you're facing...

**Comment by mikeokner** [comment]
I tried turning on push notifications in the "capabilities" section and changing the bundle identifier so that it would work with my provisioning profile, but that didn't fix the issue for me. I was then able to build/run it, but I saw the "we're in debug mode, and registered a fake push identifier" message in the logs and still couldn't get past verification. At that point I gave up & switched to 8.4.

**Comment by andre-richter** [comment]
iOS 9.2 iPhone 6.
I get this too, but even manually enabling background refresh like suggested here doesn't fix it for me.

Can't finish verification, app unusable :(

**Comment by theonemouad** [comment]
Just add Push notifications capabilities to your app and Voilaaa :dancers:
<img width="877" alt="capture d ecran 2015-12-26 a 22 14 32" src="https://cloud.githubusercontent.com/assets/8209011/12008103/12488faa-ac1e-11e5-92b1-69cff4a13dc5.png">

**Comment by fopina** [comment]
I just want to say thank you very much @winkelsdorf 
I've been unable to use the app for the last 2 weeks after some re-install, and enabling background app refresh (which I have always disabled) worked!

**Comment by winkelsdorf** [comment]
@fopina Thank you for the feedback, you're welcome! I've struggled with this for about 2 weeks, too. Glad I could help :)

**Comment by NouryJanse** [comment]
Having the same issues and all solutions above won't help (background refresh is on).

**Comment by kunickiaj** [comment]
Trying to narrow this down as it seems to come and go for me as well. Both built locally (2.3.0.1) and in the App Store version (2.2)

**Comment by shorlong** [comment]
I got this too. After turning Background App Refresh on, it still doesn't work. The code was versioned 0.0.1, reinstalled changing the version to 2.3, voila it's fixed...

**Comment by shorlong** [comment]
I got this too. After turning Background App Refresh on, it still doesn't work. The code was versioned 0.0.1, reinstalled changing the version to 2.3, voila it's fixed...

**Comment by shorlong** [comment]
I got this too. After turning Background App Refresh on, it still doesn't work. The code was versioned 0.0.1, reinstalled changing the version to 2.3, voila it's fixed...

**Comment by molood** [comment]
I have this problem with version 2.8.3. Enabling background app refresh is not helping at all. I've tried turning it off and on multiple times but nothing seems to fix it.
