### ISSUE TITLE
Notifications playing regardless of setting.

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1649]
### Bug description

You should be able to mute Signal without muting your whole phone.

*note* I haven't reproduced this yet.

### Steps to reproduce
In Signal
- go to Settings > Notifications
- Disable notification sounds
- Ensure your silent switch isn't enabled (i.e. you want sounds, just not from Signal)
- lock your phone
- receive a message

**Actual result:** Hear the notification sound. Notifications *are* correctly silenced when the app is in the foreground.

**Expected result:** Should not.

**Comment by fairlothlorien** [comment]
I'm experiencing the same issue on iPhone 7 with iOS 11.2.2.

**Action I took to silence audible Signal notifications:**
- in Signal app, went to Settings (cog) > Notifications
- Disabled "Notification Sounds"
- Phone is not on Silent mode

**Actual result when receiving a message while phone:**
- locked -> hear the notification sound & visual notification displayed
- unlocked and on Home screen -> hear the notification sound & visual notification displayed
- unlocked and in a different app -> hear the notification sound & visual notification displayed
- unlocked and in Signal app -> NO notification sound & no visual notification displayed

**Expected result:**
- in all cases I would expect visual notification/pop-up to appear (even when in Signal app)
- no sound notification at all
