### ISSUE TITLE
Feature request: Confirm call before making it

### ISSUE THREAD

**Issue by dmleong** [signalapp/Signal-iOS#1651]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I often accidentally call someone when texting them and would like to add a confirmation modal to make sure that calling a person is the intended action, or just a finger slip.

### Steps to reproduce
- text prolifically on iPhone 
- finger slip 
- call starts 
- curse loudly 
- cancel call 
- tell the other person you didn't mean to call them 

**Actual result:** Calls the person you were texting 
**Expected result:** Modal pops up and asks if I really want to call 

![iphone](https://cloud.githubusercontent.com/assets/2171822/22384315/a2972b32-e482-11e6-9a8d-e0dbadd2e7a1.jpeg)

### Device info

**Device**: iPhone 5S
**iOS version**: 10.2.1
**Signal version:** 2.6.13

**Comment by JasonLocklin** [comment]
Interestingly, doing this could also improve perceived performance at the same time. On some networks, it takes several seconds to set up the connection (screen says "dialling"). Signal *could* start the connection setup while waiting for the user to confirm the call, and then, only send the actual "ring" event to the other party when the button is pressed. This would give the user the impression that signal calls connect almost instantly.
