### ISSUE TITLE
Can't successfully connect voice call with Android client

### ISSUE THREAD

**Issue by scottyallen** [signalapp/Signal-iOS#1655]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I wasn't able to successfully connect a voice call with a friend on an android client (I'm on iOS).  I tried calling him, and he tried calling me.  I received an incoming call notification, but it stayed at a "Connecting..." screen after I hit the accept button.  He says he did not receive notifications I was calling him.

### Device info
**Device**: iphone 6s
**iOS version**: 10.2.1
**Signal version:** 2.6.13

### Link to debug log

iOS: https://gist.github.com/anonymous/29ff64caf1b44f80c7d267b618855132
Android: https://gist.github.com/fb4af6fd911e68cb615f2c31f5ff3055

**Comment by riyapenn** [comment]
Adding even more logs through EDITS:

iOS: https://gist.github.com/c5dbd43624b4efc860724a6da875ee17
Android: https://gist.github.com/6ff08b09c494517f0b99c8d57cd838ab

**Comment by michaelkirk** [comment]
@scottyallen - we've made a lot of chances to how calling works since you posted those logs. Can you try to reproduce on an up to date client?

@riyapenn - there's a lot going on in those logs. Do you know at what time the call-in-question occurred?

**Comment by michaelkirk** [comment]
@riyapenn  - also who's calling who in that scenario?

**Comment by michaelkirk-signal** [comment]
Several call connectivity issues have been fixed since this was filed.

If you have calling issues in the future, could you please open a new issue with fresh debug logs?
