### ISSUE TITLE
UX issues of playing the audio messages on iOS

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#1721]
- [x] I have searched open and closed issues for duplicates
----------------------------------------

### Bug description
1- The play icon doesn't change to pause icon after tapping on the message to be played. leaving you in a wonder whether the message is loading or has been corrupted or what until sometimes it magically plays
2- Sometimes you've to tap on it a bunch of times to actually play
3- There's an empty gray space in front of the play icon which I think is supposed to show some visualization of the audio and to indicate how far in the audio file you are while listening to it, but it doesn't.
4- The lack of ability to send back audio messages is frustrating when messaging back and forth in an speedy conversation

### Screenshots
![signal](https://cloud.githubusercontent.com/assets/453701/22719486/aee2ea92-ed9d-11e6-99ed-2c4b9c59e08c.png)

**Comment by riyapenn** [comment]
I'm seeing this as a request to increase tappable/play area for all audio. 

If you tap on the gray space and the iPhone is not set to silent/vibrate, does it begin playing?

**Comment by mrphs** [comment]
it's totally unclear what the gray area is for. sometimes when I tap on it, it works and it actually flips the play icon with pause icon but other times it does nothing. or just plays the audio without any indication that it's going to.

The other issue is that when it did play the audio message, it surprisingly played it on speaker! and I had no control on getting it off speaker or even to stop the playback. The only way was to close the app and that faded the audio out.

**Comment by JasonLocklin** [comment]
I have the same issue. I think it is particularly exacerbated with the smaller IPhone SE. The icon is just too small to touch. I suspect that the following will fix the issue:

- Increasing the tap area to at least the grey area.
- (Possibly) increasing the height of the icon/grey area.
- Immediately toggling the icon to a "loading" icon on touch, then to a "playing" icon when the audio is playing.
- A second press should cancel playback. (not sure if it does this already).

**Comment by anatoli26** [comment]
In my case (iPhone 5S/6S, latest iOS, latest Signal) the gray area is the surface that actually activates the audio. If I press the circle with the triangle, it doesn't activate the playback, only the gray area to the right activates it.

**Comment by jschneier** [comment]
Additionally on the SE I also see the length of time remaining get cut off on the far right for certain values as the time counts down.

**Comment by denver-s** [comment]
Audio messages have been completely changed, so this issue might now have been fixed.
