### ISSUE TITLE
Don't require contact access

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#1775]
Now that Signal has the option to send messages to non-contact Signal users, there shouldn't be a need to force contacts permission.

Because of the previous experience with WhatsApp, when the update came out, I assumed that was the case.

This is how composing a new message in WhatsApp looks like when you don't give it contacts permission:

<img src="https://cloud.githubusercontent.com/assets/453701/23002571/72bdfe70-f3e3-11e6-9d09-4e43d63e7e69.jpg" width="300">

**Comment by mat1th** [comment]
See #1610 for the same kind of issue;

**Comment by mat1th** [comment]
With the newest iOS update (2.12.1) it's not necessary to give the app access to the contacts :tada:
So this issue could be closed;

**Comment by mrphs** [comment]
@mat1th That's great news! Would users be able to enter the phone number manually, just like whatsapp (the screenshot above)?

**Comment by mat1th** [comment]
@mrphs It's done on the Whats app way. See screenshot. 
![untitled](https://cloud.githubusercontent.com/assets/6486389/26342466/82168350-3f98-11e7-819d-cfd9be6a1cae.jpg)

**Comment by mrphs** [comment]
Beautiful! Thank you!

**Comment by mailinglists35** [comment]
sorry for offtopic, but @mrphs how did you make whatsapp NOT require contacts access in order to compose a new message? for me it never works, this is how "new message" looks with and without contacts access:

https://imgur.com/a/pTZ56

yoi can reply to my github id at gmail to not create spam annoyances here
