### ISSUE TITLE
Add "share to a different Signal conversation" activity item.

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1788]
This way people can "forward" attachments they receive to other conversations.

**Comment by blujan** [comment]
Would this just be for attachments or for plain messages as well? Ideally, I'd like to see it for both.

**Comment by christophhagen** [comment]
I already asked this for #1810. Is somebody actively working on that? I'd like to do it if nobody has time for it right now.

**Comment by phaze75** [comment]
There has been a similar request in 2015: # 317 No idea why it has been closed.

**Comment by phaze75** [comment]
I also would like to have the possibility to forward text messages to other contacts and groups in this particular menu (e.g. "Forward This Message"):
![IMG_1698](https://user-images.githubusercontent.com/2933023/56410453-73846000-627d-11e9-90f4-0f7702dbd9db.jpg)
As mentioned above I would like to be able to forward media within the app to other contacts and groups as well (e.g. "Forward This Media/Message"):
![IMG_1699](https://user-images.githubusercontent.com/2933023/56410649-2ce33580-627e-11e9-9f1e-27da5e539bb7.jpg)

**Comment by phaze75** [comment]
> I already asked this for #1810. Is somebody actively working on that? I'd like to do it if nobody has time for it right now.

Do you have any idea why this has not been implemented yet? Seems to be a very basic standard functionality of a messenger nowadays. It also has been added to a roadmap in 2015 (#539). Is this "issue" filed correctly to be visible to the Signal developers as a feature request?

**Comment by phaze75** [comment]
@charlesmchen-signal This seems to be a very basic standard feature for a messenger nowadays that has been requested multiple times since 2015. Is there any reason besides prioritization why it has not been implemented yet? Happy Easter btw. ;-)

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
