### ISSUE TITLE
Considering raising base SDK to iOS 9

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1789]

**Comment by ebelinski** [comment]
Are there any particularly good APIs we could start using by doing this?

**Comment by m-cerveny** [comment]
Considering that Signal should help communicate people living in "less free" countries, and in these countries people usually posses older devices, I'd suggest sticking with iOS7. 

iOS8 and iOS9 are similar in device "audience." Although, some people opted not to update higher than iOS7 to preserve deice snappiness.

**Comment by ebelinski** [comment]
@m-cerveny Do you perhaps mean suggesting sticking with iOS 8? Signal never supported iOS 7, and it can't really be changed to support iOS 7 because it relies on APIs introduced in iOS 8.

**Comment by m-cerveny** [comment]
@ebelinski Only from device performance point of view - the older the device the slower using newer iOS.

Given the fact iOS 8 is supported from iPhone 4S and up (iPhone 4 is out), there's not much difference. Still a performance hit, but more functionality / better security might be worth it. 

Thus, if raising base to iOS 9 is sanctioned by use of new API, no objections.

**Comment by Aktariel** [comment]
Anything that can run iOS 8 can run iOS 9, so there's probably minimal harm in upgrading the minimum API. (people still running iOS 7 on purpose for device "snappiness" are missing out on an incredible boatload of security upgrades anyway, so losing a secure messenger is not the largest problem).

I'm curious what raising the base SDK to iOS 9 will gain Signal, though.
