### ISSUE TITLE
Can't fetch updated contact list from server

### ISSUE THREAD

**Issue by EredLithui** [signalapp/Signal-iOS#179]
Don't know if this is a common problem but when I try to update my contact list it loads for a few seconds and then gives me an error ("Bummer! We couldn't fetch..."). I use an iPhone 4s with iOS 8.0.2, Signal 1.0.7, currently vacation in Norway and via airport w-lan, will try and let you know if anything changes when I'm home again.

**Comment by riyapenn** [comment]
EDGE CASE: Resurfacing for user with large contact lists
https://gist.github.com/0b28a9139b165c43a3fb6018bb38f2c3 

Steps from user:
1. dfu restore(iphone) 
2.icloud account: login

I have several iCloud accounts. Log in to the account with less contacts. This account has about 10,000 contacts uploaded.

3.signal install 
4. activate signal 
5. Signal's contact list appears normally

or

1. delete signal app 
2.Sign out of accounts with many contacts uploaded

Many contacts log out of the uploaded account and only one account is logged in.

3.signal install 
4. activate signal 
5. Signal's contact list appears normally

**Comment by michaelkirk** [comment]
@riyapenn - I'm not following your comment can you clarify?

What behavior is the user experiencing? What are they expecting to experience?
