### ISSUE TITLE
Clicking on any conversation opens then immediately returns to conversations list

### ISSUE THREAD

**Issue by rbkhmrcr** [signalapp/Signal-iOS#1795]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
If I click on any conversation, the app opens it but then returns to the conversation list immediately -- I can click on any of the conversations and it'll do exactly the same thing, just returning to the conversation list every time... this is fixed by restarting the app, but obviously it's completely unusable while it's happening. 

### Steps to reproduce
- open app
- click on any conversation

**Actual result:** Conversation opens briefly (not long enough to click on anything/type/get the keyboard up) then immediately returns to conversation list 
**Expected result:** Conversation should open and stay open :) 

### Device info

**Device**: iPhone 5s
**iOS version**: 10.2.1
**Signal version:** 2.7.1

### Link to debug log
https://gist.github.com/46b17ffc92f65b43a1059f3038b1c7a1
(It's one of the last things that happened.. it happens pretty often but I can't actually remember whether or not I had to deal with it at any other point today so I'd advise skipping to the end of the logs :) )

**Comment by rmercer93** [comment]
https://gist.github.com/46b17ffc92f65b43a1059f3038b1c7a1

**Comment by denver-s** [comment]
I cannot reproduce this behavior.

**Comment by michaelkirk-signal** [comment]
This is a pretty old bug report. Please reopen if you can still reproduce.
