### ISSUE TITLE
Group/Conference calls

### ISSUE THREAD

**Issue by CR0CKER** [signalapp/Signal-iOS#1804]
For many organizations, options for secure group calls are severely lacking and it would be great if Signal supported them. I understand this is a challenging feature to implement, which is probably why only few apps support end-to-end encrypted conference calls. But if someone can solve this well, it's probably going to be Open Whispersystems.

**Comment by tnyeanderson** [comment]
Any updates on this? The issue tracking hasn't provided much insight.

**Comment by darkdragon-001** [comment]
There is the same question for Android signalapp/signal-android#6075.

I am wondering which approach needs to transfer less data (and at which group size there is the break-even point)
- Sending encrypted audio stream to all participants *(might be replicated on a server when using a common symmetric key)* → 1 input, n output streams
- Using homomorphic encryption to combine the encrypted streams on the server and sending only one stream to every user *(how much compression is possible!?)* → 1 input, 1 output streams

**Comment by bellabie** [comment]
I've honestly just realized that Signal DOESN'T have group calls, and that makes coordinating with multiple journalists or others in the field incredibly challenging. Big +1 on this!

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by bellabie** [comment]
Thanks, @michaelkirk !

**Comment by darkdragon-001** [comment]
https://community.signalusers.org/t/conference-calls/870
