### ISSUE TITLE
Cannot send messages to specific user

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-iOS#1807]
- [x] I have searched open and closed issues for duplicates

One of my Signal contacts cannot send messages to me any more. I can still send messages to him, which he receives correctly. I am on Android.

When my contact tries to send me a messages he get an error roughly like (I translate because he has a localised Signal): Click again to try again.

A debug log can be found here:
https://gist.github.com/eb4edec657c5fbae0db56073f0459996

My contact tried to send me messages around 15:30 I guess.

**Comment by Trolldemorted** [comment]
can others still send messages to you?

**Comment by janvlug** [comment]
Yes, this specific contact seems the only one that cannot send messages to me.

**Comment by janvlug** [comment]
Update: This problem does not occur anymore. Another Signal user (on Android) had the same issue, for him the problem does also not occur anymore. Both users can send me messages again.
I have no idea what solved the problem. The only actions that I am aware of is that we accepted new identities of seemingly totally unrelated contacts.

**Comment by pipping** [comment]
I might be having the same issue. I'm on 2.8.0.5, iOS. I also use the Chrome desktop app.

And I have one contact who's on android and who can send messages to me (android -> iOS) but who cannot receive my messages (iOS -> android). My messages are labelled as *badly encrypted* on her device, apparently. I have verified that I can still exchange messages with other contacts and so can she.

A debug log can be found [here](https://gist.github.com/anonymous/84bbf0a45013d0bb11288b9c1d93da5a).

Moreover (I do not know if this is related), her messages show up correctly on my phone, but the chrome desktop app says "Error handling message." instead and "Got invalid request to extend chain after it was already closed". Again, this just affects her messages.

**Comment by aassaaaa** [comment]
Hi there,

I am experiencing the same issue. Cannot receive message from a specific contact anymore. Which is weird for one but it gets more weird because we share a group and other contacts in that group receive the messages of this specific contact without any problem but I don’t. 

See my report attached

https://debuglogs.org/c968d08ec31c1ed35e13da08c0ca0f78b8bba5754fa76da02292a4a6f940c710.zip

Looking forward to see this bug fixed. Thank you so much for this great service so far.
