### ISSUE TITLE
Rework "new conversation" view(s).

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1809]
* Improve discoverability of groups by having a single "new conversation" flow.
* Easily add contacts and non-contacts to 1:1 and group conversations.
* Filter contacts by search query, partially matching name and phone number (and eventually other identifiers).
* Don't force user to decide if they are making a 1:1 or group conversation... decision should be implicit.
* Focus user on conversation members, not group name; have better default group names.
* Clarify member selection by surfacing separate "current members" list above UI for adding more members.
* In UI for adding more members, indicate which users are already in the conversation.

![new_conversation_ui](https://cloud.githubusercontent.com/assets/625803/23310434/5f8248e0-fa67-11e6-8852-538e809fab79.png)

**Comment by christophhagen** [comment]
What's the progress on this issue? I'm looking for a bigger junk of work and this looks promising.

**Comment by charlesmchen** [comment]
@christophhagen Hi Christoph this work is already underway but won't ship in the next release. It might or might not make the next.

**Comment by Mihahn** [comment]
I guess this issue can be closed.
