### ISSUE TITLE
Reauthencate device

### ISSUE THREAD

**Issue by Cj-Malone** [signalapp/Signal-iOS#1812]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I should say I'm unauthorized because I thought "Link devices" meant I could use the same phone number across devices, but it means a web browser. So I used a verification code on another device.

Now "network status" loops "connecting" and "offline." It seems like the app has never been designed to deal with this situation, I think I just need to get another verification prompt but it's never been brought up and I can't find a way to prompt it.

[Docs](https://support.whispersystems.org/hc/en-us/articles/213240927--Can-I-use-multiple-devices-Why-is-my-device-offline-) say I'd have to wipe the data to re register, but I don't want to lose my messages and because you can't [backup](https://github.com/WhisperSystems/Signal-iOS/issues/967) I was hoping re authorizing would be enough.

### Steps to reproduce
- verify on anther device
- original device is now unauthorized ( can be checked by going to settings > linked devices and a dialog will saying "401 unauthorized " )

**Actual result:** no prompt to reauthencate
**Expected result:** a prompt like a fresh install to be able to get a code and reauthencate

**Comment by Cj-Malone** [comment]
You can force reauthincation within the Android app by switching Signal to just be the SMS app, then back to the Signal protocol. I know none of that is possible on iOS, but I do think Signal-iOS should be able to handle the server responding with a 401status code.

**Comment by basnijholt** [comment]
I am experiencing the exact same issue.

I would like to preserve my chat history but cannot see how to do this without deleting the app.

I would be willing to work on this, would this (a re-authenticate button) be an easy feature to implement?

**Comment by basnijholt** [comment]
I think this issue might be fixed by https://github.com/WhisperSystems/Signal-iOS/pull/2598, @michaelkirk could you comment?

**Comment by alexforencich** [comment]
Does #2598 fix this?  If so, how is this feature accessed?

**Comment by shiitake** [comment]
I have the same question. I use signal on my iPhone and tried to add it to my iPad and now I'm pretty much locked out from using it on the iPhone.

**Comment by alexforencich** [comment]
Signal seems to have some serious user interface and architectural bugs with multi-device support.  If I had known about that earlier, I might have decided to use a different platform.  As the saying goes, security at the expense of usability is at the expense of security.

**Comment by basnijholt** [comment]
@shiitake and @alexforencich, that PR unfortunately doesn't fix it, I asked this before and @michaelkirk answered [here](https://github.com/WhisperSystems/Signal-iOS/pull/2598#issuecomment-335562870):
>> Would this PR solve this #1812 issue?

> Not completely, but it's in pursuit of that. Currently this is only available for debug builds. Getting this ready for de-authed users is on the roadmap. Updates will be in #1812.

**Comment by ReflexivR** [comment]
> shiitake commented on Dec 6, 2017
> I have the same question. I use signal on my iPhone and tried to add it to my iPad and now I'm pretty much locked out from using it on the iPhone.

I did the same thing. I can use Signal on my iPhone again after reinstalling & re-authing. 

When I open Signal on my iPad it just prompts to authenticate with my phone number. Is there anyway to just link my iPad with my phone like on desktop using QR code? I don't see any option to on my iPad.

**Comment by jekuno** [comment]
For my understanding:

Are we now waiting for the 3 commits in #2598 to be merged into master? Once those commits are merged will it be possible to reauthenticate a device?

**Comment by gandalfsaxe** [comment]
Huh... FYI all / many chats were still there on the desktop application after re-pairing, but not on the phone. Some loaded portions of the chat piecewise when scrolling up. Not sure what the deal is, where it's getting the data from. Still no way to back up though.
