### ISSUE TITLE
Lock screen notifications mishandle '%'

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1831]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Lock screen notifications mishandle text following the %. All numbers following or the immediate letter or character following the % are not displayed in the notification but displayed as expected in all parts of the app. 

### Steps to reproduce
- Alice's iPhone is locked and is able to view Sender name & message
- Bob sends Alice a message test%notifications%20secondattempt

**Actual result:** Alice sees testotificationssecondattempt in the lock screen notification
**Expected result:** Alice sees test%notifications%20secondattempt in the lock screen notification

Other examples: 
%123456789abcdef --> displays 'abcdef'
%abcde  --> displays bcde

### Screenshots

<img width="324" alt="screen shot 2017-03-09 at 5 54 14 pm" src="https://cloud.githubusercontent.com/assets/4898366/23778826/7c34a110-04f1-11e7-9ad9-957b40749e58.png">

### Device info

**Device**: iPhone 5C, 5S
**iOS version**: 10.2.1 
**Signal version:** 2.8.1 

### Link to debug log

 N/A

**Comment by CollinStuart** [comment]
This is because the % symbol has a special use for format strings, so a literal % needs to be converted to %% in order for the text to show up correctly in the notification center. I can do a PR for this.

**Comment by michaelkirk** [comment]
Thanks @CollinStuart, I'm just about to open a PR with this fix included.

**Comment by Mihahn** [comment]
Can't reproduce anymore, I guess you can close your issue.
