### ISSUE TITLE
Consider showing group avatar in conversation view header.

### ISSUE THREAD

**Issue by charlesmchen** [signalapp/Signal-iOS#1836]

**Comment by michaelkirk** [comment]
Why not contacts as well?

**Comment by EthanSchatzline** [comment]
Hey @charlesmchen where in the code-base would I find this? I wouldn't mind working on it.

**Comment by charlesmchen** [comment]
@michaelkirk Good idea.
@EthanSchatzline Hey Ethan thanks for the offer but I think there are some open design questions about how this would work.

**Comment by denver-s** [comment]
I think this can be closed now.
