### ISSUE TITLE
Unfurl (preview) shared hyperlinks for better UX & safer sharing

### ISSUE THREAD

**Issue by jm3** [signalapp/Signal-iOS#1857]
### When:

Someone shares a link in Signal…

### Actual:

…the bare hyperlink is displayed.

### Expected:

…a preview of the link, unfurled, is displayed.

### Screenshot:

![furl-side-by-side](https://cloud.githubusercontent.com/assets/12213/24021952/d476d39c-0a60-11e7-8ada-c1c9e164a689.jpg)

Both Slack and Telegram call this behavior, "unfurling", so I propose we use the same term. Unfurling links via [OEmbed](http://oembed.com/)[1], [OpenGraph](http://ogp.me/) tags [2], and/or HTML meta tags is supported by [Slack](https://api.slack.com/docs/message-link-unfurling), [Telegram](https://api.slack.com/docs/message-link-unfurling), [Twitter](https://dev.twitter.com/cards/overview), [FB Messenger](https://developers.facebook.com/docs/sharing/webmasters), WhatsApp, Messages, etc. because it makes sharing links a richer and clearer experience.

Unfurling links can also help reduce the risk of the subclass of phishing attacks where malicious links are hidden behind `bit.ly` / `t.co`-style [link shorteners](https://www.lookingglasscyber.com/blog/phishing/link-shorteners-in-phishing-attacks-part-i-which-shorteners-do-criminals-use-and-which-brands-are-targeted/) (notably, how FancyBear [delivered their spear-phishing attacks](https://motherboard.vice.com/en_us/article/how-hackers-broke-into-john-podesta-and-colin-powells-gmail-accounts) to the DNC)

This is of course an Android and Chrome issue as well, but it seems like the discussion has to start somewhere, so I've placed it here after searching for previous issues. Please let me know if I should move the issue to another repo.

[1] [More about OEmbed and Slack's implementation thereof](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254)
[2] The [OpenGraph standard](http://ogp.me/) makes it straightforward for apps and websites to display embedded previews of web links.

**Comment by scyclops** [comment]
For documentation, a similar issue is open for the Signal Android app at: https://github.com/WhisperSystems/Signal-Android/issues/5724

**Comment by mailinglists35** [comment]
no. I don't want this. If you do this, make it default disabled with toggle to turn on.

I was actually happy that nobody accesses the URL I sent except the receiver, when he wants and not automated by software.

**Comment by CaptainVascular** [comment]
I saw a lot of people commenting on this and the related suggestions stating privacy concerns. I get it, but some people would find it useful as an optional feature. Why can't we have it available to be enabled at the conversation level? So if I'm in a conversation with a friend I could go into the settings for that specific conversation and enable link previews. That way it isn't forced on anyone, and you'd only enable it for people you trust.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

Especially with something like link previews which affects all platforms.

Here's an existing thread on the topic: https://community.signalusers.org/t/link-preview-when-pasting-links/2370

**Comment by ClayMorde** [comment]
I made a separate issue that is related to this. Instead of giving a preview of a shared URL (which I think should happen) it could be easier to implement the title from the URL as well as the URL. This could be accomplished using the iOS share sheet.

https://github.com/signalapp/Signal-iOS/issues/4098
