### ISSUE TITLE
Be able to place messages from the Contacts app

### ISSUE THREAD

**Issue by NicolasCGN** [signalapp/Signal-iOS#1878]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Feature request
Signal already allows to place voice calls and video calls from the Contacts app but not messages. Other apps allow to place messages from the Contacts app (e.g. WhatsApp)

**Comment by michaelkirk-signal** [comment]
I'm closing as I don't think this is possible.

> Other apps allow to place messages from the Contacts app (e.g. WhatsApp)

Can you show me the steps to do this? I've never seen it.

Feel free to re-open if I'm mistaken.
