### ISSUE TITLE
Add option to cancel sending debug log

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1909]
Signal > Settings > Advanced > Submit Debug Log > edit alert to "printing/creating debug log" as "sending debug log" then add option to Cancel on next screen

**Comment by ebelinski** [comment]
If I'm not mistake it looks like the first alert is already changed to "Sending debug log..." but the second alert still doesn't have "Cancel".

**Comment by CollinStuart** [comment]
There is an option to cancel the type of log to send on the first alert. I believe there isn't a "sending debug log" second alert any more.
