### ISSUE TITLE
Arbitrary length for disappearing messages

### ISSUE THREAD

**Issue by nrrkeene** [signalapp/Signal-iOS#1912]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Feature Request
Feature request: instead of (or in addition to) the list of predefined Disappearing Message timeouts, allow arbitrary lengths to be specified.

Use case: I personally want most of my chats to last long enough that I can go back and use them for reference for quite a while, but not forever. My personal desire is for a timeout of maybe three or six or twelve months. One way to cover the needs of all users would be to allow entry of arbitrary timespans.

### Steps to reproduce
Click "..." -> Disappearing Messages

**Actual result:** 
the popup window appears with "5 Seconds" through "1 Week".

**Desired result:**
the popup window has easy-pick predefined terms as it does now _plus_ an "Other" option with a numeric field and a time-unit menu. I would then enter "6" and select "Months".

### Device info
**Device**: Samsung S7 Edge
**iOS version**: pfft lol iOS as if
**Signal version:** current/recent

### Praise
Thank you very much for Signal it is really wonderful.

**Comment by LeanderH** [comment]
I absolutely agree! It is an awesome feature already, and would achieve the desired goal of the feature even better, if more options are added - or better yet, a custom option. **:-)**

I try to communicate my argument in this comment:
https://github.com/whispersystems/signal-android/issues/5775#issuecomment-315622446

**Comment by tosh** [comment]
this would be a killer feature for collaborative group chats

**Comment by tosh** [comment]
Since the creation of this ticket the maximum time span options got expanded from 1 week to up to 4 weeks which already helps a lot but similar to the OP I think there are many group chat scenarios where a couple of months would be a useful option to have.

**Comment by kaktusztea** [comment]
@tosh: devs communicated that they won't track feature requests on Github anymore, but on Signal community forum.
There is a collection of already casted feature requests:
https://community.signalusers.org/t/wiki-overview-of-open-feature-requests/12008

And there is already a matching one for your request:
https://community.signalusers.org/t/longer-timeframe-more-options-for-disappearing-messages/2744

So I suggest to close this and continue on the forum - you can add a ❤️ to the first comment to elevate the rank of that request.
