### ISSUE TITLE
Conversation view starts in middle of thread after receiving message

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#1929]
- [X] I have searched open and closed issues for duplicates; Most similar to https://github.com/WhisperSystems/Signal-iOS/issues/1731 and https://github.com/WhisperSystems/Signal-iOS/issues/1690

----------------------------------------

### Bug description
Message thread is not opening at the bottom of the thread when viewing

### Steps to reproduce
- receive message
- open Signal
- select thread

**Actual result:** scrolls to random point of message thread
**Expected result:** scrolls to the bottom of the thread OR  "unread message indicator" https://github.com/WhisperSystems/Signal-iOS/issues/638 / https://github.com/WhisperSystems/Signal-Android/commit/d9b42c436907fbf5d0c34b1b5b25baac65c1d628😬 

### Screenshots
 N/A

### Device info

**Device**: iPhone 5C
**iOS version**: 10.3
**Signal version:** 2.9.1

### Link to debug log

https://gist.github.com/b6314fa2b3939ecbf7f0f95ad6398f08

**Comment by kaktusztea** [comment]
I can confirm this issue.
Quite annoying.
