### ISSUE TITLE
Anonymous contacts

### ISSUE THREAD

**Issue by Foaly** [signalapp/Signal-iOS#194]
Hello there!
I don't know if this is the right place to make suggestions like this or if this is just for bugs, but I didn't know where else to put it (feel free to move it).
This is a feature that I saw in some other messaging app (don't remember which one) and that I found very useful and which is also enhancing the users privacy.
It would be nice if there was a way to add a user to your "chat contacts" without having to save there number in your contacts list. Think of it as a one time ticket for establishing a contact. Something like a QR-Code to scan or a short code that the other one has to type in and the first one has to accept it or something along those lines.
I am sure this would be very helpful for a lot of people. For example if you don't want somebodys number in you phone book or the other way round if you don't want somebody to have you cell phone number. This could also be nice for people how use devices that don't have a phone number (like a tablet or an Ipod touch).
What do you guys think? Or is something like that already planned?

**Comment by gardner** [comment]
All information from 156 was erased by @FredericJacobs and the issue was closed without resolution. Please consider reopening this issue. Please consider tagging with help wanted so that potential contributors see this.

**Comment by gardner** [comment]
<img width="831" alt="screen shot 2017-11-18 at 9 39 39 am" src="https://user-images.githubusercontent.com/787026/32967980-7539dab8-cc44-11e7-972d-f5309b8a38fc.png">
