### ISSUE TITLE
17k chars message has unnecessary big bottom-padding

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#1948]
- [x] I have searched open and closed issues for duplicates, maybe related to #1744 and #1635.

----------------------------------------

### Bug description
Unnecessary big bottom-padding is added to the message bubble.

### Steps to reproduce
- Generate a 17k characters text (e.g. here: http://www.blindtextgenerator.de)
- send that text as message

**Actual result:** Unnecessary big bottom-padding is added to the message bubble.
**Expected result:** Bottom-padding should be normal in size like with shorter messages.

### Screenshots

![signal-17k-char-message](https://cloud.githubusercontent.com/assets/5073538/24797558/46ddfea2-1b81-11e7-8931-6901bc48b572.png)

### Device info

**Device**: iPhone 5
**iOS version**: 10.3
**Signal version:** 2.10.0.2 beta

### Link to debug log
https://gist.github.com/c8c1fee1ba4868710b8c3f453867ef89

**Comment by denver-s** [comment]
No longer happening now.

![immagine](https://user-images.githubusercontent.com/31325316/56225333-70b51f80-6071-11e9-99d1-89740559aedc.png)

**Comment by michaelkirk-signal** [comment]
I believe this is fixed. Please re-open with some text which reproduces the issue if you can reproduce.
