### ISSUE TITLE
Scrolling up in conversation leads to app freeze

### ISSUE THREAD

**Issue by Ginari** [signalapp/Signal-iOS#1949]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When in a conversation, scrolling up is normal in the beginning but when hitting "show more messages" for the fifth time or going even higher in the conversation scrolling gets stuck at some point, pressing the button to show more messages takes a couple of seconds and the app freezes for several seconds.
Looks like some sort of memory problem, that the app cannot handle to display "so many" messages.

This makes it practically impossible to check older messages in the App.

### Steps to reproduce
- Go in conversation
- Scroll up to the end (or tab the top edge of the screen) till you hit the "show more messages" button and tab it
- repeat a couple of times (5+)

**Actual result:** App starts to get very slow, laggy and does not respond properly anymore.
**Expected result:** Instant display of older messages, fluid scrolling, no lag.

### Device info

**Device**: iPhone 6s
**iOS version**: 10.3.1
**Signal version:** 2.9.2

**Comment by michaelkirk** [comment]
To help us reproduce, can you provide a breakdown of your messages by type?

text: 0%
video: 0%
static image: 0%
GIF: 0%
Audio: 0%

Does it seem to gradually and evenly get slower? Or is there one page in particular where things get really slow? What kind of media (if any) is on that page?

**Comment by big-r81** [comment]
@michaelkirk 
Hi Michael,

i can confirm this.
I have a thread with approx.

text: 50%
images: 40%
video:10%

Number of Pressing "Loading earlier messages" | scroll behavior | Time to load old messages | crash of app
------------ | ------- | ------ |-----
1|ok||
2|ok||
3|ok||
4|starts lacking - getting jerky||
5|more jerky|2 seconds|
6|more jerky|5 seconds|
7|even more jerky|7 seconds|
8|even more jerky|8 seconds|
9|even more jerky|9 seconds|
10|no scrolling fun|10 seconds| **app hanging some time until i can scroll**
11| ... | ... | ...
12| ... | ... | ...

From the debug log, there are 3 memory warnings:

`2017/04/08 08:40:33:982  [AppDelegate] applicationDidReceiveMemoryWarning.`
`2017/04/08 08:41:14:718  [AppDelegate] applicationDidReceiveMemoryWarning.`
`2017/04/08 08:43:45:814 [AppDelegate] applicationDidReceiveMemoryWarning.`

**Device info**

Device: iPhone 6
iOS version: 10.3.1
Signal version: 2.10.0.3

**Comment by Ginari** [comment]
@michaelkirk For me it behaves very similar to @big-r81's chart. My messages consist of approximately the following:
text: 70%
video: 10%
static image: 20%

It gets slow/laggy gradually as indicated by @big-r81.

**Comment by Ginari** [comment]
And by the way, if you are at it already - why not implement automatic loading of new messages when scrolling up?

Thank you =)

**Comment by michaelkirk-signal** [comment]
The latest beta includes some changes which should better handle loading many old interactions.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
