### ISSUE TITLE
Scroll position isn't saved

### ISSUE THREAD

**Issue by big-r81** [signalapp/Signal-iOS#1955]
### Bug description
After scrolling back in time and opening the conversation settings and going back, the
view shows the latest message.

### Steps to reproduce
- scroll to old message
- tap on contact name
- tap on back

**Actual result:** View show the latest (newest in time) message
**Expected result:** View should show the message before entering the conversation settings

**Comment by arekm** [comment]
Similar case:
- scroll back in conversation
- wait for new message from user we are viewing old conversation
- things get auto scrolled to that new message even if you were reading some old content

**Comment by denver-s** [comment]
I can't reproduce using latest version. I think those two bugs have been fixed.

**Comment by ethylmorphine** [comment]
iOS 12.2, Signal 2.39.0.9. Can reproduce.
