### ISSUE TITLE
Body message of dialog window for camera, contacts and microphone permissions are not translated

### ISSUE THREAD

**Issue by NicolasCGN** [signalapp/Signal-iOS#1956]
The main message for asking permission to access camera, contacts and microphone is not localised
![](http://i.imgur.com/OwKVR3V.jpg)
![](http://i.imgur.com/X6QlZNr.jpg)
![](http://i.imgur.com/5yFhr86.jpg)

**Comment by iadmir** [comment]
These dialogs are also not localized


![img_5905](https://cloud.githubusercontent.com/assets/23726384/25289987/46d5d078-26cc-11e7-9b4f-076f8890c35e.PNG)
![img_5906](https://cloud.githubusercontent.com/assets/23726384/25289989/46d8aa28-26cc-11e7-8ad2-54ad73c53986.PNG)
![img_5907](https://cloud.githubusercontent.com/assets/23726384/25289988/46d89772-26cc-11e7-85be-954a7e2df6fc.PNG)

**Comment by denver-s** [comment]
@NicolasCGN I think this is now fixed.
