### ISSUE TITLE
No progress indicator for download of attachments

### ISSUE THREAD

**Issue by anatoli26** [signalapp/Signal-iOS#1969]
There's no indicator of the download progress for attachments, nor any information about their total size, so one doesn't know if he/she is receiving a small photo or a huge video, and can't estimate the download time (quite important on slow/intermittent cellular connections and/or with per-megabyte paid plans). It would be great to show the already downloaded size / total size (e.g. 345Kb/7.8Mb) and a visual progress bar/circle indicator.

- [x] show download progress
- [ ] show download size

**Comment by denver-s** [comment]
It should be fixed now.
