### ISSUE TITLE
[Request] Location Sharing Like Android

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-iOS#1982]
Can you please add support for location sharing like android has.
Thanks

**Comment by TreatyOfRome** [comment]
A pull request is pending. #1871

**Comment by GPMueller** [comment]
The initial pull request was closed and re-opened as PR #2447.

**Comment by Cerberus0** [comment]
This feature is now included in Signal iOS 2.42.0 (beta): https://github.com/signalapp/Signal-iOS/commit/17f961f6add81f3333d1e366920b59b2f5fc80dc Thanks @Imperiopolis-Signal!

This issue can now be closed. If you're interested in testing the new location sharing feature, join the beta group [here](https://support.signal.org/hc/en-us/articles/360007318471-) and discussion [here](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-2-42-release/9073).
