### ISSUE TITLE
SECURITY ISSUE: Signal doesn't strip EXIF from sent images, including precise location data

### ISSUE THREAD

**Issue by ThePowerOfDreams** [signalapp/Signal-iOS#1984]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal for iOS includes EXIF data in sent images, including precise GPS data if present. Instead, EXIF data should be stripped (possibly except for the absolute bare minimum such as dimension and rotation).

### Steps to reproduce
- Enable Location access for Camera.app
- Take a picture with Camera.app
- Send that picture from the Camera Roll using Signal
- Recipient uses the share sheet to save the image, then opens it in an app such as ExifWizPro

**Actual result:** Recipient sees the precise location the image was taken, along with all other EXIF fields
**Expected result:** Recipient sees no EXIF data whatsoever, as is the case when using Threema

### Device info

**Device**: iPhone 6
**iOS version**: 10.3.1
**Signal version:** 2.10.1

**Comment by ebelinski** [comment]
I'm not so sure about the necessity of this. If I wanted to remove EXIF data, I could get an app that does it, and send the stripped version. Otherwise I would want to send the photo with EXIF data, if I want my recipient to know where and when it was taken, and the aperture, shutter speed, etc. Maybe it could be optional in the app? 

On a side note if we want Signal to be sending completely "anonymous photos", we should definitely be considering the issue of [camera fingerprinting](https://33bits.org/2011/09/19/digital-camera-fingerprinting/) as well. Without making special modifications to a photo, the subtle imperfections of a photo can be used to identify the camera that took it. For example, if you use your phone's camera to take pictures that you post publicly on Facebook, and send a different photo from the same camera to a person anonymously, camera fingerprinting based on the contents of the actual photo could be used to tie the anonymous photo to your Facebook identity, without checking EXIF data.

**Comment by theochino** [comment]
I would like that option because the idea of Signal is to make it as user
friendly as possible; the EXIF data can be easily removed and should be
incorporated.

My 2 Cents.

Regards,
Theo Chino
article78againstNYDFS.com

**Comment by big-r81** [comment]
My thoughts:

I don't think we should go this way.

Why doesn't you forbid the camera app to use the location services if security matters? Why not disable location and/or other services at system level?

The problem is, that some users want a feature other users not and if every feature will get an on/off switch the preference pane will grow with many switches. Maybe they depend on each other or are mutually exclusive... NO that isn't user fiendly and maybe results in deceptive security...

**Comment by sigenc** [comment]
I think the android version strips the exif data. Maybe we should change it for consistency.

**Comment by ThePowerOfDreams** [comment]
The steps to reproduce indeed included enabling Location Services for Camera.app, but the threat exists in many situations, including passing along an image received from someone else. (For example, John McAfee's location while in hiding was revealed precisely this way.)

Information leakage via metadata is a thing, and pretending it isn't only undermines confidence in this project.

**Comment by theochino** [comment]
If signal can strip metadata at minimal cost, then it should do it.

The default for signal is privacy so anything that can reveal it should be
removed; no toggle switch required.

If you need EXIF info to be sent, should be per item (click on picture and
say EXIF enabled.)

Regards,
Theo
https://privacyboard.nyc

**Comment by strugee** [comment]
> including passing along an image received from someone else.

I'm unclear on how the onus is now on the "middleman" in this situation. If the receiver doesn't want their location shared, shouldn't they be the ones turning off location metadata?

**Comment by ebelinski** [comment]
> If the receiver doesn't want their location shared, shouldn't they be the ones turning off location metadata?

I guess I can see the case for stripping EXIF from a user friendly perspective. The average Signal user may not be aware that sending a picture means sending the location the picture was taken if that feature is turned on, and on iPhone it usually is. And even if a user knows that the feature is turned on to collect location information for each photo, it's totally possible that he wouldn't be aware that the location data is stored *inside* the image file itself, and that Signal sends the whole file. After all, iOS abstracts away the concept of files, so many users don't know how metadata is stored on iOS.

**Comment by kaktusztea** [comment]
I would suggest a global checkbox in Settings (Strip image metadata).
Default: ON

**Comment by strugee** [comment]
The answer is not more options: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology

**Comment by theochino** [comment]
*The user doesn't know what a key is.*

Many times I turn an option in the OS, and at the next update I discover
that the option has been turned back in during the update.
Geo-location is actually one of those option that the OS do turn back on.

The system should be as simple for the user regardless of what the OS does.

**Comment by ephemer** [comment]
If users really want to send the photo's location they can just tell the recipient where the photo was taken (or share a pin from Photos.app after sending it).

In my opinion, most "normal" users won't:

1. Save the photo to Photos.app or elsewhere at all
2. Know that location data is available in its metadata if they do

... meaning that *not* stripping EXIF metadata is at best helping only a minimal number of users (for whom simple workarounds exist) and at worst jeopardising people's security without their knowledge.

If the answer is not adding settings (and I agree that it is not), then I'd suggest the answer is strongly in favour of stripping the EXIF data.

**Comment by kaktusztea** [comment]
After read ephemer's comment, an idea:
- default behaviour: strip EXIF data
- long press (1 or 2 sec) on Photo attach label (in dropdown list): do not strip

So "do not strip" would be a deliberate act in a rare, but real scenario.

**Comment by ebelinski** [comment]
Some metadata I think we should definitely not strip by default. For example, when you edit a picture and rotate it with the iOS Photos app, then you delete all metadata, the orientation goes back to the original, because the photo itself wasn't changed, just some metadata.

On an unrelated note, has anyone else noticed that this issue's number is #1984? 🤔😄

**Comment by megraf** [comment]
I agree that stripping should be OPT-OUT rather than OPT-IN. Chances are users won't notice if their EXIF is striped, but they should have the option either way. Signal's initial privacy orientation should make it pretty clear that EXIF should be stripped IMHO.

**Comment by caveman1973** [comment]
Signal should remove ALL EXIF data, not only location. 

If you want to send a picture with EXIF data, use another app.

**Comment by Calefornia** [comment]
Signal absolutely should offer to remove metadata. Period. Adding settings is the answer. This isn't going to clutter the UI. It's very simple and will help protect the privacy of most people using this app.

You have to realize that we are in an extremely small sample size. Most people have no idea what can be leaked through metadata. Most people don't understand the details of surveillance and software to the degree that you guys do.

How many hundreds of thousands of people do you think use this app? Most of them will probably never even visit this repository, let alone understand the dangers of metadata.

So if Signal can do it, it's worth helping out people who aren't as privacy conscious as we are.

**Comment by tomrittervg** [comment]
I disagree. Signal should not offer to remove the metadata. The word 'offer' implies it might be a prompt.  Signal should strip (at a minimum) geolocation data - period.

EXIF data in photos is a fidelity signal from a camera to a photo. It preserves as much metadata about the image as possible for future categorization and record keeping. It's similar to saving a photo in RAW format.

Signal is not designed to be a photo archiving app or editing or storage app. It's for sharing messages and photos. There is no mechanism in Signal to view EXIF data, and doing so is something only particularly technical people would think of or even be able to try. 

And geolocation data is extremely sensitive (it's extremely common to take photos in your own home) and in many or most cases one does not want to share their home address with all the individuals one may wish to send a picture to.

Signal to do the 'safe' thing by default, which would be at a minimum to strip geolocation data.  Maybe, _maybe_ there could be an option to disable this feature, buried somewhere - but I don't even think the option is necessary.

**Comment by Calefornia** [comment]
Okay I agree. Sorry for not being precise with my words. Essentially I meant that Signal should have the capability to do this. And it would be accessible to manage in settings.

Safe by default is the right way to handle. Thanks!

**Comment by CollinBStuart** [comment]
Another angle of looking at this, is that because sometimes it strips EXIF data due to resizing (Android), people might gather that it does all the time. Ex. I do a simple test to make sure it's safe, it passes, then I have a false sense of security and send pictures without thinking about it again.

For the iOS version, the `else` case for selecting images from the library (`didFinishPickingMediaWithInfo`) uses PHAsset/ALAsset which includes metadata, the other cases use UIImage which does not contain metadata information because UIImage represents a decoded image that discards metadata. 

@Calefornia I agree :) - I've had a few people now send me pictures from Android and I save them on iOS camera roll. Then later I look at my Photo's app and that picture shows up in the "Places" group. Turned out I can zoom right to where their house was!! In all cases, the user didn't know about this and I had to give them instructions on how to disable location services.

**Comment by banool** [comment]
What's the status on this? I'm pretty amazed that anyone could think leaving the metadata on (especially by default) is a good idea in an app that espouses security and privacy. Just seems like a huge oversight to me.

**Comment by Calefornia** [comment]
Here's a link to the Metadata Anonymisation Toolkit, which in turn provides links to similar projects:

https://mat.boum.org/

Hopefully someone can integrate code or modify it as needed for Signal.

**Comment by CollinBStuart** [comment]
For iOS, the current logic is that in order to avoid re-encoding GIF/PNGs as JPEG we are retrieving the raw data using the Photo Framework (`PHAsset` instead of using `UIImagePickerControllerOriginalImage`), which happens to include EXIF and GPS data with it.

So, in order to keep the current functionality and code as is, one option available would be to add an extra step - after retrieving that `NSData` from the Photo Framework,
remove the `kCGImagePropertyExifDictionary` and `kCGImagePropertyGPSDictionary` from it. This will remove all the EXIF and GPS data before sending the image. Because the data returned from the Photo Framework is immutable, a copy of the data with the stripped attributes would have to be made.

This is something I could implement and do a PR for, unless anyone has any objections to that solution or better suggestions here.

**Comment by michaelkirk** [comment]
We'd consider a PR which strips out non-orientation exif metadata by default, with an option to leave it in (settings > privacy > remove image meta data).

Be aware that the image picker is not the only source of images. Additionally images can come from the document picker (e.g. iCloud), copy/paste, etc. 

We'd want the same behavior regardless of source. My feeling is that the SignalAttachment class, which all sources flow through, may be the right place to implement this.

**Comment by mailinglists35** [comment]
so much nonsense talk for something you can do it yourself (free app: Koredoko https://itunes.apple.com/us/app/koredoko-exif-and-gps-viewer/id286765236?mt=8)

meanwhile we don't even have yet a way to cleanup received media stored locally, but you all keep complaining for something totally unrelevant

**Comment by cbanowsky** [comment]
This is a must. The aim is to constantly improve and make the software better and protect privacy. Signal is used by people who dont understand the types of protection it truly offers. Knowing that these users dont know what EXIF data is I think it is essential that a user be able to send photos without revealing their private information without their understanding of said EXIF data. I did the same yesterday. Geolocated a person to their precise real time location and disclosed to said individual to ensure their apps do not permit geolocation information stored in photos. 

But I feel as the filer of this issue feels, that that for the majority this is a security issue.

**Comment by cbanowsky** [comment]
In regards to camera fingerprinting. The process isnt as easy as exiftool.

**Comment by cbanowsky** [comment]
@allanlw I think all meta data for any file should be wiped.  but in certain cases to maintain authenticity of a document, let's say, that's problematic.  If meta data and exif is gone I think #2907 works and this can be closed

**Comment by muellermartin** [comment]
While PR #2907 seems to be merged in commit d9b8ce2, the code seems to have been disappeared in 9adf79c. Is there a reason for this? The commit check seems to have failed with the error "Please sign the Contributor Licence Agreement" but in PR #2907 there is a checkmark for the signing.

**Comment by michaelkirk-signal** [comment]
@muellermartin - If this is something you've actually experienced, could you follow up with the steps you took to reproduce?

If you are only going off of the diff in those commits, then I think you're confused.

As you said, https://github.com/signalapp/Signal-iOS/commit/d9b8ce26f5d901670668e96502fb30fa55b5dc4f added an option to remove metadata.

Later, https://github.com/signalapp/Signal-iOS/commit/9adf79c5461f4d4ddc10b13cd57b2f1402249f3d (title: "Always remove metadata") made it so we *always* remove that metadata, rendering that option obsolete.

Look more closely here: https://github.com/signalapp/Signal-iOS/commit/9adf79c5461f4d4ddc10b13cd57b2f1402249f3d#diff-9d624dd0aa572a2e77bebbd0460bbf9eR627

**Comment by mailinglists35** [comment]
>we   always   remove that metadata
  

  
is there any chance you leave this option available for users?   
  

  
  

  
  
>

**Comment by CollinStuart** [comment]
There was a lot of discussion above on this and the consensus I think was to do it "period". Which makes sense given non-technical users, then accidents can't happen etc.

**Comment by muellermartin** [comment]
> @muellermartin - If this is something you've actually experienced, could you follow up with the steps you took to reproduce?
> 
> If you are only going off of the diff in those commits, then I think you're confused.
> 
> As you said, [d9b8ce2](https://github.com/signalapp/Signal-iOS/commit/d9b8ce26f5d901670668e96502fb30fa55b5dc4f) added an option to remove metadata.
> 
> Later, [9adf79c](https://github.com/signalapp/Signal-iOS/commit/9adf79c5461f4d4ddc10b13cd57b2f1402249f3d) (title: "Always remove metadata") made it so we _always_ remove that metadata, rendering that option obsolete.
> 
> Look more closely here: [9adf79c#diff-9d624dd0aa572a2e77bebbd0460bbf9eR629](https://github.com/signalapp/Signal-iOS/commit/9adf79c5461f4d4ddc10b13cd57b2f1402249f3d#diff-9d624dd0aa572a2e77bebbd0460bbf9eR629)

You're totally right, I seem to have been confused by the diffs. I have not encountered issues with metadata removal so far. I just wondered why this issue is still open. Sorry for the confusion and thanks for clarifying.

**Comment by databonanza** [comment]
Where are we at with this?  Does someone have to make the patch vs. just complaining about it here for something to happen?

If you want EXIF data transmission you should be enabling it using a toggle.

EXIF data in images sent on signal should be stripped by default.  Change my mind.

**Comment by timfallmk** [comment]
@databonanza Please read the discussion before commenting. Scrolling up will show you it has already been done, it just needs to be closed.

**Comment by ckujau** [comment]
While the original report was about "Signal doesn't strip [enough] EXIF data", it turned out that people disagreed on that point and maybe a [toggle](https://github.com/signalapp/Signal-iOS/issues/1984#issuecomment-316581975) was needed to strip / don't strip meta data from images (and other media), see also [#5968 Image Meta Data Removal](https://github.com/signalapp/Signal-Android/issues/5968) for a similar discussion for the Android version. So far this toggle has not been implemented for either platform, so I think this report is still valid.

There was [an argument](https://github.com/signalapp/Signal-iOS/issues/1984#issuecomment-296764878) about not wanting too many configuration itmes in the application, but we do have "Sealed Sender" and "Advanced PIN" settings now, so I guess this point is moot now :-)

**Comment by darkBuddha** [comment]
Is this really true? All other messengers are, of course, doing it!

**Comment by ckujau** [comment]
Is there a way to prevent stale bot from trying to close this issue every 5 months?

**Comment by hex-m** [comment]
@ckujau This project uses the [default configuration](https://github.com/signalapp/Signal-iOS/blob/main/.github/stale.yml) of the stale bot. You can read more about it in the [README](https://github.com/probot/stale/blob/master/README.md#usage) of the bot.

**Comment by databonanza** [comment]
Stale devs not stale thread.

This issue is quite important.  Let's ban stale bot from certain threads that are important.  Also, this should be an easy fix.

**Comment by NiklasBr** [comment]
Why won't the bot remove the label?

**Comment by banool** [comment]
5 years of dev silence on a hot issue for it to just to get closed by stale bot, time to switch messaging apps.

**Comment by databonanza** [comment]
> 5 years of dev silence on a hot issue for it to just to get closed by stale bot, time to switch messaging apps.

To what though?  I can't believe this is just left alone.  I have tried to pull exif data from signal photos and "there is none" but I don't know if it's because Signal is scrubbing it.  This is a big problem, who is the person we need to @ to get their attention on this?

**Comment by kaktusztea** [comment]
As far as I know Signal DOES strip the EXIF data for a few years now.
Some folks above wanted to extend this ticket with some feature requests which are not part of this issue IMHO.
So I think closing this ticket is justified. (let's downvote me).

**Comment by banool** [comment]
If it has actually been addressed it should be explicitly closed, not closed by stalebot.

**Comment by m-graf** [comment]
> If it has actually been addressed it should be explicitly closed, not closed by stalebot.

This. Can someone please mark this as resolved (or the equivalent?)

**Comment by tomrittervg** [comment]
[I don't see any indication that the app actually strips EXIF data.](https://github.com/signalapp/Signal-iOS/search?q=exif)  If it does, then someone can link to the functionality.

**Comment by kaktusztea** [comment]
> [I don't see any indication that the app actually strips EXIF data.](https://github.com/signalapp/Signal-iOS/search?q=exif) If it does, then someone can link to the functionality.

I think this is it:
https://github.com/signalapp/Signal-iOS/commit/9adf79c5461f4d4ddc10b13cd57b2f1402249f3d

**Comment by ThePowerOfDreams** [comment]
>If it has actually been addressed it should be explicitly closed, not closed by stalebot.

Is it _actually_ resolved? Moxie still won't let us save our data on iOS since I opened this issue _five fucking years ago_, so Signal is now my third choice behind Threema and Matrix.

Shrug.

**Comment by tomrittervg** [comment]
> > [I don't see any indication that the app actually strips EXIF data.](https://github.com/signalapp/Signal-iOS/search?q=exif) If it does, then someone can link to the functionality.
> 
> I think this is it: [9adf79c](https://github.com/signalapp/Signal-iOS/commit/9adf79c5461f4d4ddc10b13cd57b2f1402249f3d)

Good hunting. That commit removes the option to remove metadata so it's done by default.  I eventually found [this code in the master branch](https://github.com/signalapp/Signal-iOS/blob/main/SignalMessaging/attachments/SignalAttachment.swift#L1048).

I found [this comment on Android](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/jobs/AttachmentCompressionJob.java#L301) and [this for desktop](https://github.com/signalapp/Signal-Desktop/blob/db155b9752160d1b2ce43fe15c43a169f75b1b4e/ts/types/Attachment.ts#L251).

Not well described...

**Comment by ThePowerOfDreams** [comment]
>I found [this comment on Android](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/jobs/AttachmentCompressionJob.java#L301) and [this for desktop](https://github.com/signalapp/Signal-Desktop/blob/db155b9752160d1b2ce43fe15c43a169f75b1b4e/ts/types/Attachment.ts#L251).

What about iOS?

**Comment by ThePowerOfDreams** [comment]
```/**
   * Compresses the images. Given that we compress every image, this has the fun side effect of
   * stripping all EXIF data.
   */```

Why is it presumed that EXIF is stripped due to compression? If that's true, all images would lose their rotation, and that isn't the case.

Sus.

**Comment by databonanza** [comment]
> > If it has actually been addressed it should be explicitly closed, not closed by stalebot.
> 
> Actually, that is right, but devs doesn't really review on old tickets unfotunatelly 🙁 There are a plenty of tickets which could be already closed immediately if devs would do a full overview on open tickets.

There is no need for a full review.  There is a need for accountability in a open source project.  When you fix things that are related to "issues" you update the issue with the current status.
