### ISSUE TITLE
Difficulties of saving contacts from groups

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#1989]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Being in a group with a bunch of people who are not on your contact list can get confusing really quickly. 

### Steps to reproduce
- Join a group where most of the members aren't saved as contact on your phone
- Identify who is who
- Try adding them to your contacts

**Actual result:** Assuming everybody sends a text, introducing themselves, you still have to:
- read that tiny number underneath the text
- memorize it
- switch to your contact app
- save it
- hope you didn't make a mistake
- reload signal to make sure you saved the number correctly
- repeat above for the number of group members.

This can easily become hell when the group of unknown contacts is more than 1 or 2. That is, assuming they identify themselves. If they don't and in situations that you can't ask in group say because there's a conversation going on or it spams others, you'd have to save their number under a dummy name, then message them directly to ask them who they are and then go back to your contact app and edit their name.

**Expected result:** you should be able to do one or both of these:
1- tap on that person's number somewhere and save it directly from the message box
2- be able to send a private message to them to kindly ask them to identify themselves. Then edit their name right in the app.

**Comment by mrphs** [comment]
FWIW, I've some thoughts about the possible designs that I can provide to solve this problem if there's an interest.

**Comment by michaelkirk** [comment]
This will be a bit better with the upcoming 2.12 release - you'll be able to edit contact info for group members in app (and in 1:1).

But I don't think we've completely solved the "lots of strangers in a group" problem yet.
