### ISSUE TITLE
no sound from iphone to android

### ISSUE THREAD

**Issue by richlv** [signalapp/Signal-iOS#2038]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
when calling between android and iphone, sound android->iphone works; there is no sound for iphone->android

### Steps to reproduce
- call between android/iphone
- get sound in one direction only

**Actual result:** one-way sound
**Expected result:** two-way sound

### Device info
**Device 1**: iPhone 6
**iOS version**: 9.3.5
**Signal version:** 2.10.1

**Device 2**: Samsung J710
**Android version**: 6.0.1
**Signal version:** 4.3.2

### Link to debug log

debug log from iphone : https://gist.github.com/227587e4b8483ad0217d8752cf58827b

note that on android, it has been verified that signal has microphone permissons.

unsure which app is to blame - filed in the iphone section as that is what one of the phones reported in automatically.

**Comment by KJHVlJVYlIUB98** [comment]
I have experienced similar between iOS9 and iOS10

**Comment by 0xAF** [comment]
Same problem here.
iphone can hear the android, but there is no sound from iphone to android.

**Comment by ChimeraCoder** [comment]
I've encountered this issue as well. Sometimes the audio works in neither direction, but more often than not the iPhone is the one that can't send audio. Restarting the iPhone sometimes fixes the problem.

**Comment by peterpanondrugs** [comment]
https://gist.github.com/anonymous/e70edc78bc19ee24278a7c269d0f059a

**Comment by fmjrey** [comment]
Also getting no sound from a friend on an iPhone 6 calling two different android phones (galaxy s6 and note 9). All permissions have been granted to Signal on iPhone, iPhone was restarted and app uninstalled + reinstalled,  and normal calls from iPhone work so not a hardware issue. 
To be precise: we hear loud white noise, we can see her video, she can hear and see us fine.

**Comment by nemozny** [comment]
Same issue here, audio works until I switch on Android camera, iPhone immediately loses audio, sometimes gains video, sometimes neither.
This is happening from day one since I bought that iPhone, now half a year.
No amount of updates or permissions worked. I did all I could, it is an app problem.
Very annoying, will have to scratch Signal for Skype.
This sucks.

**Comment by mueller-franzes** [comment]
I think I am facing the same problem: 
As soon as the speaker icon is pressed on the iPhone, the person with the iPhone can be heard well on Android, but the person with the iPhone can no longer hear anything. If the icon is not pressed, the person with the iPhone can barely be heard on Android. The problem does not occur between two Android devices. Reinstalling the app did not help.

**Comment by bolt-blue** [comment]
Seems like this is still occasionally an issue.
Again when it goes wrong the apple side can hear sound from android, but not the other way around.

I want to say I've noticed this only after a recent update, but that might be unfounded.
Both apps are up to date with their respective versions.

Any idea what the source of the problem might be?
Or how we might be able to collect more useful info for it to be debugged?
