### ISSUE TITLE
iOS 9 disappearing messages aren't disappearing

### ISSUE THREAD

**Issue by KJHVlJVYlIUB98** [signalapp/Signal-iOS#2086]
iOS 9.3.5
Signal 2.11.3

Open a conversation with a contact.
Set disappearing messages to 5 minutes.
Compose and send message.
Lock with power button.
Return 1 hour later and unlock device using code.
Open Signal and open conversation.
Message is still present with empty / white hour glass.

Sometimes I have to full close Signal by pushing it off the top of the screen and then reopen it to make the disappearing messages disappear.

**Comment by charlesmchen** [comment]
@KJHVlJVYlIUB98 hi, are you still seeing this issue with the latest release?

**Comment by brianpgrissom** [comment]
@charlesmchen 
This is still true on Signal 2.15.22, IOS 10.3.3.

I am an android user but my parents are IOS users. If I send them a disappearing messages and then change the disappearing setting, the message will remain

Example:
1) set DM to 1 minute
2) send message
3) disable DM
4) message does not disappear

The messages disappear on my android, and if IOS sends to android, both messages will disappear.

**Comment by michaelkirk** [comment]
You mentioned multiple users and platforms - can you help us understand by clarifying your example with who is sending and with what device?

Is this right?

- set DM to 1 minute on Android
- send message to iOS from Android
- disable DM on Android
- message does not disappear on iOS

**Comment by brianpgrissom** [comment]
I apologize - I definitely wasn't clear.

Your understanding is correct. And FWIW I'm using a Pixel XL on 7.2.1 and the most updated Signal for android (I don't have my phone on me so I can't look). The IOS phone is a iPhone 6.
