### ISSUE TITLE
Weird contacts ordering and display

### ISSUE THREAD

**Issue by hodgesmr** [signalapp/Signal-iOS#2154]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I _think_ this started after upgrading to 2.12.2, but not completely sure. I noticed that contacts are now sorted by last name, but have the firs name bolded. This is not how iOS sorts its contacts (which, you can configure). For example, I have my iOS contacts sorted by first name, and the first name is bolded.

### Steps to reproduce
- Tap the compose button, which takes you to your Signal contacts

**Actual result:** Contacts are sorted by last name, but have first name in bold
**Expected result:** I personally like my contacts sorted by first name (and to have first name bolded), but others may prefer sorting by last name (and have last name bolded)

### Device info
**Signal version:** 2.12.2

**Comment by michaelkirk** [comment]
What version of iOS are you running?

Can you attach a screenshot of your contacts settings?

Open the Settings app and go to Contacts

**Comment by hodgesmr** [comment]
iOS version: 10.3.2

![img_4303](https://cloud.githubusercontent.com/assets/1208575/26476723/979cb634-418e-11e7-84c6-291cc589d2fc.JPG)

**Comment by denver-s** [comment]
I think this can be closed now.

**Comment by michaelkirk-signal** [comment]
Please re-open if you're still able to reproduce this.
