### ISSUE TITLE
VoiceOver stops speaking for a while after sending an Audio Memo

### ISSUE THREAD

**Issue by mrkiko** [signalapp/Signal-iOS#2161]
After sending an Audio Memo, VoiceOver won't speak for a while. It seems 
still possible to hear system sounds, but no voice output.
This is unconfortable, since pressing the Home button to go back to the 
home screen won't unmute VoiceOver immediately, at least in some of my 
tests.
Apart from this, the app is amazingly fast in reacting to the finger 
leaving the screen. That's good.

**Comment by paddyblifu** [comment]
I noticed the same here. Another issue is, when I hold my finger on the microfon, the message will allready send. Is it possible to change the microfon button for example you start the recording by one double-tap and then you've to sweep with one finger to the right to a send-button whitch send the recording after pressing. It should be also possible to listen to the recording before send.

**Comment by MarcoZehe** [comment]
I can no longer reproduce this on latest iOS and latest Signal. I can double-tap and hold, the phone vibrates, I can talk, and after I let go, the phone vibrates again and sends the message. Anybody still able to reproduce this?

**Comment by paddyblifu** [comment]
I tested it with the newest IOS-version and VO is speaking correctly after sendimg a voice message.

Tested with Iphone XR and IOS 15.3.

Kind Regards,
Patrick


Von meinem iPhone gesendet
