### ISSUE TITLE
Text cropped in privacy, notification and advanced settings

### ISSUE THREAD

**Issue by guiweber** [signalapp/Signal-iOS#2173]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
In privacy, notification and advanced settings, some of the text is too long for the space provided, causing the text to be cropped. This makes it hard to understand what the option does. Using a smaller font size at these locations could potentially fix the issue without changing the text as the font size used is pretty large and larger than in other locations.

The issue was noticed in the french version of Signal on a phone which is not my own and thus could not be tested in other languages.

**Actual result:** The text is cropped
**Expected result:** The full text is displayed

### Device info
**Device**:  iPhone SE
**iOS version**: 10.3.1
**Signal version:** 2.12.2

### Screenshots
![img_0070](https://cloud.githubusercontent.com/assets/7825368/26701300/8a89f226-46ee-11e7-99ec-91ac01e8c0b4.PNG)
![img_0071](https://cloud.githubusercontent.com/assets/7825368/26701302/8c4e7564-46ee-11e7-9950-4ed26ff7d1e8.PNG)
![img_0072](https://cloud.githubusercontent.com/assets/7825368/26701303/8db4b5ee-46ee-11e7-8694-44b1002ee08d.PNG)

**Comment by ebelinski** [comment]
Can you post a screenshot of what the text size is set to in the iPhone Settings app? The best place to find this is in General > Accessibility > Larger Text. I think this problem should be addressed in the context of a larger font size set in Settings, because from the screenshots, it's clear that the system font size is set to something larger than default.

**Comment by guiweber** [comment]
@ebelinski  As requested, here is a screenshot showing the font size used :

![signal-2017-06-13-164119](https://user-images.githubusercontent.com/7825368/27104308-ca8197c0-5059-11e7-8bcc-72dc808ca73a.png)

**Comment by ebelinski** [comment]
@guiweber I see, thank you.

Since the UI elements that contain the text in these pages are `UITableViewCells`, I think the text cutoff could be fixed by setting the labels' `numberOfLines` to unlimited and setting the cell height dynamically based on the label sizes.
