### ISSUE TITLE
iOS group message positioning in conversation list is not ok when using (only) timed messages.

### ISSUE THREAD

**Issue by SignalBugFound** [signalapp/Signal-iOS#2179]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
iOS group message positioning in conversation list is not ok when using timed messages.

### Steps to reproduce
- create group with two users.
-- one user android OR Desktop
-- one user iphone
- set timer to X minutes (tested with 5)
- send message from android to iphone
- read message on iphone and let the message disappear.
- send message from iphone to android
- read message on android and let the message disappear

**Actual result:** 
You will notice that the conversation latest update time on android & desktop, will be the time of creation of the group. Since the messages have disappeared and did not exist.
Thus when signal is sorting the conversation list, then the created group will be ordered accordingly to the creation date.

On iphone the logic is different. The conversation update time on iphone is that of the last message. Thus when signal is sorting the conversation list, then the created group will be ordered accordingly to the last active (and disappeared) message.

**Expected result:** 
IMHO the android & desktop implementation is the more secure one, since all traces of a timed message should be removed from the system.

### Screenshots
N.A.

### Device info
N.A.

### Link to debug log
N.A.

**Comment by DonnaLynn** [comment]
What does this mean??

**Comment by SignalBugFound** [comment]
That on iOS you can see when an conversation was used for the last time, when there are no messages in it because of the usage of timed messaged.. This is leaving a hint for outsiders that communication have been there.  Does this help?

**Comment by SignalBugFound** [comment]
Is there a way I can help in this issue? since its impact security/privacy of the app user.

**Comment by philshem** [comment]
I have a similar issue, but it's actually on an iOS device.

When all the time messages are deleted, the group/recipient goes all the way to the bottom of the chat list. Although I understand the reason for privacy grounds, the UX is quite tough if there are many groups/participants in the chat list.

**Comment by paskalem** [comment]
Image.jpg
<https://drive.google.com/file/d/0B4PoejGEXL27aU5tU2E0V1o1MWttOWF5ZHZWVGItcXhLamJn/view?usp=drive_web>
