### ISSUE TITLE
Instructions/wiki for setting up full development environment

### ISSUE THREAD

**Issue by chrisballinger** [signalapp/Signal-iOS#222]
I see you're moving ahead quickly with development in the textSecure branch, aw yeah! I realize this is a bit premature, but I'm very interested in contributing to Signal/TextSecure once things have settled down a bit. 

One of the issues I noticed is that to properly test, contributors will need to set up a full TextSecure (and RedPhone?) server on their local machine. There appear to be [community-contributed instructions](https://github.com/WhisperSystems/TextSecure-Server/wiki/Using-your-own-server) for setting up your own TextSecure server, however the RedPhone server source code [remains closed](https://github.com/WhisperSystems/RedPhone/issues/63). I realize how hard it is to set up staging servers, so perhaps it will never be feasible, especially given the support cost.

At the very least it would be useful for potential contributors to have clear instructions for how to bypass the registration process with a dummy/mock server and test account, or even just an easy way to just skip the registration UI and populate the db with test data.

In case any other developers are curious about poking around inside the new UI, you can disable the registration UI in [SignalTabBarController.m L36](https://github.com/WhisperSystems/Signal-iOS/blob/44a38043940aaa6b550e4c9e6951994b436bcba2/Signal/src/view%20controllers/SignalTabBarController.m#L36). 

The new UI looks great by the way!

**Comment by lazzarello** [comment]
I came across this thread and I notice it [references a thread which has been open for > three years](https://github.com/WhisperSystems/RedPhone/issues/63#issuecomment-76894505): the release of the Signal signaling protocol gateway, media proxy and NAT traversal infrastructure for the global RedPhone network. It would be an excellent feature to allow the user base of Signal to communicate with the remainder of the world's open source VoIP services. 

The [published signaling spec](https://github.com/WhisperSystems/RedPhone/wiki/Signaling-Protocol) is a good start. [Three years ago Moxie mentioned](https://github.com/WhisperSystems/RedPhone/issues/63#issuecomment-10310280) off the cuff that "We are planning on releasing the RedPhone server source, but it will not likely be easy for people to run their own servers." it would be an crucial resource to have the ability to develop a protocol gateway between SIP and Signal. The server source code would make this process smooth and quite attractive to many developers worldwide.

And for those of you who would like a more salty read, see my biannual check in over at the legendary [RedPhone issue #63](https://github.com/WhisperSystems/RedPhone/issues/63#issuecomment-76894505).

Help us help you. Open it up for the rest of us!

Sincerely,
Lee
