### ISSUE TITLE
App doesn't recognize valid contact name

### ISSUE THREAD

**Issue by TempSpas** [signalapp/Signal-iOS#2242]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Recently I convinced a friend on Android to start using Signal to message me. He installed the app and sent me a message, but Signal claims that the number is not in my contacts and asks if I would like to block him. On the Inbox screen, his name is not displayed, only the phone number. On the icon where his initials would be, it displays only a "#". When I enter the conversation and tap the top bar for settings, it shows the plain number, but when I tap, "Edit," it brings me to his correct contact information with his name already filled out (as I already have him as a contact).

When I tap the compose new message icon, all of my contacts on Signal are listed including him, but whereas everyone else has their initials displayed in the circle next to their names, his displays the "#".

### Steps to reproduce
- Contact I have in my phone downloaded Signal and message me
- Signal says that contact does not exist
- Tapping settings confirms that the contact does in fact exist, Signal is just not properly recognizing it

### Device info

**Device**: iPhone 6
**iOS version**: 10.3.2
**Signal version:** 2.12.2

**Comment by TempSpas** [comment]
I believe I've figured out the root cause of the bug, but I'm not sure why it happened. When my friend texted me prior to Signal, I had his contact saved as a standard 10-digit number. However, after he downloaded Signal and messaged me through it, somehow that number became prefaced with a 1, which is what appeared to have tripped Signal up. I created a new contact on my phone as `Friend Name1` name but this time with the 1 in front of the number, and that took the place of all references to him on Signal. I then deleted this new contact, leaving only the original, and this appears to have fixed everything in Signal as it now displays his name correctly everywhere.

**Comment by michaelkirk** [comment]
Interesting. Thanks for digging into this. Sounds like a bug in the way we’re matching contacts.

Can you confirm what steps you took - was it like this:

Originally you had your friends, “Alice" number in your contacts as “123-123-1234”
When Alice messaged you in Signal, Signal showed their phone number, not their name, e.g. “+11231231234”
When you went to the conversation settings for “+11231231234” and tapped “edit” to edit their contact details…
Then you saw the system contact information for Alice (including her name). 
But when you left that screen, returning to Signal, you again saw just the “+11231231234”, not her name.

Then you added a new contact to your system contacts, with the phone number “11231231234” and name “Alice”
And deleted the old contact info for “Alice” with the number “1231231234” 
Then when you returned to Signal you saw “Alice’s name properly displayed in the thread.

Is that right?

**Comment by TempSpas** [comment]
Almost; the first part is entirely correct. When I added a new contact with the phone number "+11231231234," I named the contact "Alice1." Signal then displayed the name "Alice1." Then I deleted this new contact, the "Alice1" contact. After that, Signal correctly displayed the original "Alice" contact.

**Comment by MrAlexWeber** [comment]
Is this possibly related to #2021 ?
