### ISSUE TITLE
Cannot administer groups anymore after re-installing signal, groups are not synced to new device

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#2257]
moved from: https://github.com/WhisperSystems/Signal-Android/issues/6754

> @mbiebl said:
> I've been using an Android phone (Nexus 5) with the latest Signal version.
>
> On this phone I created a group called "Family" where I was the admin: I could change the title, picture and members.
>
> A couple of days ago the Nexus phone died. As I had an older iPhone 5s, I used the SIM card from the old Nexus phone, installed the latest Signal version on the iPhone and (re)registered the old mobile number.
> 
> None of the groups that I had created on the old Android phone were synced to the iPhone.
> When someone posted a new message to the Family, a new group showed up on the iPhone labeled "Unknown group". The group picture was not set and I can't edit the group anymore.
> 
> Was I doing something wrong? How can I make sure the existing groups are properly synced to the new device?

**Comment by mbiebl** [comment]
iOS: 10.3.2 (14F89), iPhone 5s
Signal iOS client: 2.12.2
Chrome desktop client: 0.41.3

**Comment by michaelkirk** [comment]
@mbiebl 

By design:
1. the signal service knows nothing about groups
2. no account information is stored, so we can't "restore" your old info when you register on a new device (nor can anyone else who steals your phone number).

However, reinstalling is fairly common thing to do, so we've built some things to try to make it less painful. The way it's supposed to work is like this:

1. Say you are in a group called "Family" with Alice.
2. Then you switch devices or reinstall Signal-iOS
3. Your new device knows nothing about the "Family" group.
4. When Alice messages you, she'll see that your safety number has changed, indicating that the device she is sending to is not the same as before, or reinstalled.
5. When you receive Alice's message, your device doesn't know anything about the group, hence "unknown group"

Now whats *supposed* to happen:

6. Your device requests group info from Alice's device (this should be automatic and require no user action)
7. Provided Alice is on a reasonably up-to-date version, she'll respond with the group info, restoring the groups name, avatar, group members, and your ability to edit.

So!

What would clear this up:

1. What version/platform is Alice running?
2. Can you provide a debug log from Alice after she messages you in the group?
3. Can you provide a debug log form your device after receiving a message in the group?

https://support.whispersystems.org/hc/en-us/articles/115005925767-How-do-I-send-you-a-debug-log-

Thanks!

**Comment by mbiebl** [comment]
thanks a lot for the detailed reply @michaelkirk , this definitely helps to understand how this is supposed to work.
I guess in my case the problem was, that I, via the desktop client, was the first one to post to the group.
Haven't received a reply yet from the other members of the group. Will wait and see if that fixes the problem (step 6.+7.)

**Comment by mbiebl** [comment]
Ok, so now other members of the groups have posted, but this did not trigger 6. + 7.

I guess that means I have to explicitly ask someone to update the group.

**Comment by mbiebl** [comment]
@michaelkirk I now asked another member to temporarily rename the group. This fixed the avator, memberlist etc.

So, I guess the problem was, that I used the desktop client, which was bound to the new iOS device to post the first message.

**Comment by michaelkirk** [comment]
> Ok, so now other members of the groups have posted, but this did not trigger 6. + 7.
>
> I guess that means I have to explicitly ask someone to update the group.

Either the sender is running an old client, or this is broken. Could you get a debug log from them? And would you mind sending one for yourself? And let me know the time (to the best of your recollection) that the message was sent?

Thanks for any help!

**Comment by mbiebl** [comment]
@michaelkirk your request came in too late :-/ I had already asked someone to update the group.

If the given information is not sufficient for you to reproduce the issue, feel free to close the bug report.

**Comment by michaelkirk** [comment]
@mbiebl even though someone has updated group, the requested debug logs will still be helpful.

e.g. was the problem that you failed to request?
that they failed to respond?
that they responed but you couldn't process their response?

if you aren't comfortable sending in debug logs, no problem, but just wanted to clarify that they would still be helpful.
