### ISSUE TITLE
Signal crashes when scrolling up and viewing media

### ISSUE THREAD

**Issue by siccovansas** [signalapp/Signal-iOS#2271]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
On an iPhone 4, when scrolling up in a conversation the app crashes either when media enters the screen or when clicking on the media to view it. This happens consistently and makes the app difficult to use.

**Actual result:** the app crashes
**Expected result:** the app shouldn't crash when viewing the conversation/media

### Device info
**Device**: iPhone 4
**iOS version**: latest
**Signal version:** latest

### Link to debug log
https://gist.github.com/58ef4477690efd5377200f962de2bda3

(Note this is not my phone and I don't have access to it right now. I'll try to obtain a crash log when possible.)

**Comment by big-r81** [comment]
@siccovansas 

Does this still happen with the latest version? You (or your friend) is using version 2.11.4.

**Comment by siccovansas** [comment]
Yes, this problem still occurs and Signal is up to date on that phone. The debug log was exported some time ago so that is why it shows an old version.

**Comment by big-r81** [comment]
Can you past a up-to-date logfile?

**Comment by siccovansas** [comment]
@big-r81 here is an up-to-date logfile: https://gist.github.com/anonymous/576b2325c08fd660ade987d223a105cd

**Comment by michaelkirk** [comment]
@siccovansas  - A crash log would be really helpful if you can find one.

Here are some instructions:
https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-reports

**Comment by siccovansas** [comment]
@michaelkirk this problem doesn't seem to create a crash log as the last crash log for Signal dates back the February 2017. I do have another debug log taken just after a crash, though I'm not sure if that helps.
https://gist.github.com/f64fc9dca5f0b44f10470247dc1c5d0a

To describe the problem once more. It seems mainly image related. Videos seem to always play fine. When I open a chat and click on an image I shortly see the image (with a black background) and then the whole screen turns black for a few seconds and then I see the home screen of the iPhone. If I then open Signal again I'm shown the list of all chats instead of the chat I had opened. Sometimes clicking on an image works as expected (i.e. the image fills the screen with a semitransparent background), but this happens way less then the crashing behavior.

**Comment by michaelkirk** [comment]
The lack of a crash report is consistent with a crash due to running out of memory. Also, being on an older device makes that more likely. We're continuing to make improvements around this - but in the meanwhile you might have better luck if you ensure only the minimal number of apps are running in the background.

**Comment by siccovansas** [comment]
iPhone 4 (last iOS version is 7.1.2) is no longer supported by Signal (requires at least iOS 11.0), so this issue is no longer relevant :)
