### ISSUE TITLE
feature request: notification repeat

### ISSUE THREAD

**Issue by lorrin** [signalapp/Signal-iOS#2311]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I wish there was a feature to repeat the audible notification until a message was read (or some number of times). This is analogous to https://github.com/WhisperSystems/Signal-Android/pull/1623 on Android and [capabilities of Apple's own Messages app](https://apple.stackexchange.com/questions/220792/how-to-get-ongoing-notifications-of-unread-texts) (though that lacks a repeat-indefinitely option). Thanks.

**Comment by TScalzott** [comment]
Yes, please!
