### ISSUE TITLE
External keyboard shortcuts unavailable on iOS

### ISSUE THREAD

**Issue by matthewmcvickar** [signalapp/Signal-iOS#2359]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Beyond typing in text boxes, there is no external keyboard control for the iOS app.

This is particularly noticeable when trying to send a message—pressing <kbd>Enter</kbd> by itself or with a modifier key held down adds a new line instead of sending a message.

### Steps to reproduce
- connect external keyboard
- hold <kbd>⌘</kbd> to expose list of available shortcuts
- hit buttons like <kbd>↑</kbd> <kbd>↓</kbd> to navigate lists
- <kbd>Enter</kbd> to send message

**Actual result:**
- No list of available shortcuts appears.
- Using arrow keys to navigate lists or hitting <kbd>Enter</kbd> to open a message thread doesn't work.
- Hitting <kbd>Enter</kbd> when typing a message enters a newline instead of sending the message.

**Expected result:**
- A list of available shortcuts should appear in a standard iOS keyboard shortcut overlay.
- You should be able to navigate the message thread list with the keyboard.
- You should be able to send messages either using <kbd>Enter</kbd> or <kbd>Enter</kbd> with a modifier key.

### Device info
**Device**: iPad Mini, iPhone 7
**iOS version**: 10.3.3
**Signal version:** 2.14.1.2

**Comment by Imperiopolis-Signal** [comment]
A broad set of keyboard shortcuts are now supported in our 3.0 beta release.
