### ISSUE TITLE
Accessibility voice over call screen labels are incorrect

### ISSUE THREAD

**Issue by riyapenn** [signalapp/Signal-iOS#2396]
- [X] I have searched open and closed issues for duplicates, most related accessibility issue relating to calls (but not reading call screen icons) is https://github.com/WhisperSystems/Signal-iOS/issues/1210

----------------------------------------

### Bug description
Call screen VO labels are not properly labeled.

### Steps to reproduce
- Place a Signal call to a contact
- The call starts and shows the connecting/ringing screen
- The call is answered by the contact 
- Tap on screen to hear options of mute, speakerphone, video. etc

**Actual result:** The names for the buttons such as mute, activate speaker, activate video are not properly labeled with the representing text. 
**Expected result:** Correct voice over labels indicating mute, speakerphone, video, etc.

### Screenshots
 N/A

### Device info

**Device**: all
**iOS version**: all
**Signal version:** 2.15.0

### Link to debug log

N/A

**Comment by hpincket** [comment]
Should this issue be marked as resolved?
