### ISSUE TITLE
Compression & media management?

### ISSUE THREAD

**Issue by dalanmiller** [signalapp/Signal-iOS#2428]
I've noticed that in using Signal over the past couple months, the storage usage by Signal on my phone has increased massively. Over my prior messenger, this is hundreds of megabytes over a timespan that is a quarter or less of the same time of usage. I think there's two problems here.

1. I don't believe there is any default compression occurring on pictures or videos being sent by Signal. The option should be available to save mobile data and storage space. I should be able to decide at the moment of sending whether or not I'd prefer to (lossless-ly? || loss-ily?)  compress media to send. 

2. I have no way of looking at all the media sent and received for a given conversation. I should be able to delete things en masse and be able to see the overall storage usage for a conversation. 

I have not tried deleting an entire conversation which I imagine would fix the problem of course until it eventually hits huge storage problems again but think that these features should be available to be on par with other messengers.

**Comment by caveman1973** [comment]
Signal should compress the file and remove metadata also. It's a nightmare to send a picture of you're under a bad connection.

**Comment by devurandom** [comment]
#1233 discusses this issue, too.
