### ISSUE TITLE
Photo bubble not appear in message view

### ISSUE THREAD

**Issue by iadmir** [signalapp/Signal-iOS#2505]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
This happens very often, after the photos are sent the photo bubble doesn't appear but it is possible to open the image when tap on empty space (see screenshot).
After scrolling up and down, only then the photo bubble appears.

### Steps to reproduce
- open conversation
- choose image from gallery and send to your friend

**Actual result:** Photo bubble not appear
**Expected result:** Photo bubble appear

### Screenshots

![jjj](https://user-images.githubusercontent.com/23726384/29994508-48a5b83c-8fd1-11e7-92a1-7447969a492a.jpg)

### Device info

**Device**: iPhone 5S
**iOS version**: 10.3.3
**Signal version:** 2.15.3.2

**Comment by michaelkirk** [comment]
Thanks for reporting - I haven't reproduced this yet, so I'm hoping I can get some more details.

This only happens immediately after sending: e.g. you when you re-open the conversation the images are always there?

Can you give me any info about the images themselves? Are they from the camera app? Gifs?

**Comment by iadmir** [comment]
This happens very often immediately after sending or recieving photos but also photo bubbles sometimes not appear when scrolling to view earlier photos in conversation.
After scroll up/down photo bubbles appear again in same way as they dissapear.

Regardless of whether they are from the gallery or camera app this happens with both.
I didn't try with gifs.


## Screenshot
![issue](https://user-images.githubusercontent.com/23726384/30100526-790124a6-92e9-11e7-89cf-860dd5085fd9.jpg)

**Comment by kaktusztea** [comment]
I have the same issue for a while now (6 month at least, maybe more).
iOS 10, iPhone 5S, always the latest Signal version.

**Comment by iadmir** [comment]
No changes in 2.16.0.20 and it looks really bad when all previous images not appear.

![30553220-c991b636-9ca0-11e7-96d7-ec326bf51c55](https://user-images.githubusercontent.com/23726384/30554148-d20c7f5a-9ca3-11e7-855f-2431894113a9.jpg)

**Comment by tzs1** [comment]
Never happened to me, I think this bug has been fixed.

**Comment by michaelkirk-signal** [comment]
Closing for now. If this is still happening please do re-open with a fresh debug log and any steps to reproduce you can think of.
