### ISSUE TITLE
UIAlertViews are not localized

### ISSUE THREAD

**Issue by iadmir** [signalapp/Signal-iOS#2506]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
UIAlertView messages are not localized to Croatian, also alert about notifications is fully on English.

### Screenshots

![simulator screen shot 3 sep 2017 18 10 57](https://user-images.githubusercontent.com/23726384/30014476-b8a80a32-914c-11e7-84da-500cb1df990e.png)
![simulator screen shot 3 sep 2017 18 13 23](https://user-images.githubusercontent.com/23726384/30014475-b8a2f916-914c-11e7-9441-335ab8ddafe1.png)
![simulator screen shot 3 sep 2017 18 08 56](https://user-images.githubusercontent.com/23726384/30014474-b8797564-914c-11e7-8168-cbc59f4102b8.png)

### Device info

**Device**: iPhone 5S / Simulator
**iOS version**: 10.3
**Signal version:** 2.15.3.2

**Comment by denver-s** [comment]
This is a problem related to translations, see https://www.transifex.com/signalapp/signal-ios/
