### ISSUE TITLE
Title is out of circle

### ISSUE THREAD

**Issue by iadmir** [signalapp/Signal-iOS#2509]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Actually this isn't an bug but IMO it distorts aesthetics.
I notice that "Tap to Scan" on other languages is out of circle.

## Deutch
![simulator screen shot 5 sep 2017 09 20 30](https://user-images.githubusercontent.com/23726384/30073140-0f8d50b6-926d-11e7-8172-cdf2339f3e34.jpg)

## French
![simulator screen shot 5 sep 2017 09 21 36](https://user-images.githubusercontent.com/23726384/30073173-2baad606-926d-11e7-905e-c3c0db4e87cf.jpg)

## Italian
![taliano](https://user-images.githubusercontent.com/23726384/30074259-29df7d0a-9271-11e7-8391-4fa96b1cabd9.jpg)

##English
![simulator screen shot 5 sep 2017 09 23 28](https://user-images.githubusercontent.com/23726384/30074402-b566c3ce-9271-11e7-9f34-6d69c59dc955.jpg)

### Device info

**Device**: iPhone SE / Simulator
**iOS version**: 10.3
**Signal version:** 2.15.3

**Comment by denver-s** [comment]
I confirm this is happening as of 2.38.1.2.
