### ISSUE TITLE
Censorship circumvention not working in China

### ISSUE THREAD

**Issue by CR0CKER** [signalapp/Signal-iOS#2524]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal on iOS often does not connect when using it in China, likely because it is blocked by the GFW, and when activating Censorship Circumvention in the app settings, it still does not connect. 

Signal support staff seems to be aware that Censorship Circumvention is not working in China, and seems to be content with this situation. Considering how difficult it has become for Chinese to get access to a working VPN on iOS, I think it is crucial to make Signal usable again in China without the use of a VPN. Tor does it with the meek protocol. Why should we not be able to figure this out with Signal?

### Steps to reproduce
- Turn off VPN
- Activate "Censorship Circumvention"

**Actual result:** App often does not connect to Signal servers, messages are not sent
**Expected result:** App should connect to Signal servers and should send and receive messages without any problems.

### Device info
**Device**: iPhone SE
**iOS version**: 10.3.3
**Signal version:** 2.15.3.2

### Link to debug log
https://gist.github.com/a510d6967b4c3023bc296aac568d8445

**Comment by CR0CKER** [comment]
Any updates on this? Signal is rarely useable in China without VPN, and even with VPN receiving calls often fails.

**Comment by nullchinchilla** [comment]
After some investigation the issue with calls seems to be connected mostly to the poor choice of TURN server location (`ap-northeast-1` is perennially congested from China) rather than the GFW. I've opened an issue (8551)
