### ISSUE TITLE
iOS: Accidental delete of Group

### ISSUE THREAD

**Issue by gakudva** [signalapp/Signal-iOS#2543]
One can simply swipe left and delete group.  As this action leads to serious result (exit from the group, and there is no way to get back - unless some one invites you again) -> there needs to be an warning to confirm the Delete action.  

If you see applications like Whatsapp -> the exit from the group is hidden iniside the group attribute.  This prevents accidental delete / exit from the group.

**Comment by michaelkirk-signal** [comment]
This has been addressed. Let us know if you still have issues.

**Comment by gakudva** [comment]
I can confirm that this issue does not exist anymore! Thanks!
