### ISSUE TITLE
[Feature Request] Video Messaging

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-iOS#2554]
Can you please add support for video messaging by direct capture from the camera and as a file attachment.
Thanks

**Comment by denver-s** [comment]
It is possible to add video from the in-app camera mode (long press the central button) and also as file attachment.

**Comment by Mihahn** [comment]
I guess this can be closed by now.

**Comment by zero77** [comment]
@Mihahn 
I know there is video calling, is there now also video messaging.

**Comment by Mihahn** [comment]
I don't know exactly what you want to do, but as @denver-s explained, you can open a conversation, click on the camera icon, long press the main button (or swipe it to the lock) to record the video and send it then. So yes, I guess video messaging is possible.
