### ISSUE TITLE
Existing groups not recreating on new phone. 

### ISSUE THREAD

**Issue by dhoepp** [signalapp/Signal-iOS#2560]
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

When a message is sent in an existing group, on my new phone, I see the message appear, but it’s named “new group.” Entering the group, I don’t have a keyboard, and tapping ‘settings’ doesn’t do anything. 

### Steps to reproduce 
- create group
- reinstall signal
- have someone send a message in that group 

**Actual result:** 
I’m unable to send messages due to not having a keyboard. The group isn’t named properly. 
**Expected result:** 
The group should have the correct name, I should be able to send messages. 

### Device info

**Device**: iPhone 7
**iOS version**: iOS 11 GM
**Signal version:** 2.15.3.2

### Link to debug log

https://gist.github.com/d206cbdab83bcdb589f20b0411eae9bc

**Comment by michaelkirk** [comment]
Seems like your debug log was truncated somehow.

Can you try to attach a new one after receiving a message in the mystery group?

**Comment by dhoepp** [comment]
https://gist.github.com/b57c05f729621fe8314812a26df41041

               -Dustin Hoeppner

**Comment by dhoepp** [comment]
Perhaps something isn’t right with the debug logs 

		-Dustin Hoeppner

**Comment by dhoepp** [comment]
https://gist.github.com/0606d1117c2e35cdca738e7c282367b3

Here is another 

               -Dustin Hoeppner

**Comment by michaelkirk** [comment]
Hm...

Looks like it was truncated again, as the second debug log doesn't even contain the lines of the first debug log.

You're not toggling the debug log switch off an on or something are you?

**Comment by dhoepp** [comment]
Not sure what Unsupported Websocket is.

**Comment by dhoepp** [comment]
I suppose I was between those two, but I haven't turned it off since.

**Comment by michaelkirk** [comment]
It's pretty tough to debug the issue without a full debug log. 

So, one more time from the top, now that debug logs are enabled...

- double tap home, and swipe up on signal to kill signal.
- launch signal so we can get the startup diagnostics in the log
- have someone from that mystery group message you
- then submit a debug log

Thanks for any help getting this resolved

**Comment by riyapenn** [comment]
For Michael's steps above, can you make sure someone from the mystery group messages you from their mobile phone?

**Comment by dhoepp** [comment]
https://gist.github.com/d44db489a1d1a298f5f396abdfe8d767

**Comment by dhoepp** [comment]
about 7:18 is when I received the last message in this log.

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.

**Comment by dhoepp** [comment]
likely resolved in one of the many other bug fixes.
