### ISSUE TITLE
Custom sounds not pushing through from Contacts even though looks like they should

### ISSUE THREAD

**Issue by daemhan** [signalapp/Signal-iOS#2569]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I have custom contact sounds set for a few people in my Contacts on the new iPhone, however, Signal is not using these sounds for messages coming in. For various reasons, it's important to me that I have different sounds for certain individuals. The default message tone is also not very distinctive from other messages and notifications, which are "can wait" things.

I don't believe this is a duplicate of #1009, as it looks like Signal *should* be using the settings from the Contacts entries on the device [see screenshots], and that thread is two years old -- many versions of Signal and iOS ago. [This works just fine on Android [setting sounds in People settings, and they pass through to Signal], and so I figured that since I have access to those settings by calling them directly from within Signal on the iPhone, it must be using all the Contacts settings that are displayed.]

### Steps to reproduce
- Changed sound settings after calling the Contact entry from within Signal
- Settings save
- Able to recall settings after closing and re-opening Signal
- Able to recall settings after restarting device

**Actual result:** Signal continues to use default sounds, despite indicators that it should be pulling the custom settings straight from the Contacts settings. If Signal can't actually use the information stored in Contacts, then that should be indicated somewhere or somehow.

### Screenshots
I've blocked out names and phone numbers, but the following images show how I got to where I was led to believe I could have custom sounds in Signal on iPhone like I had on Android.

![signal-1](https://user-images.githubusercontent.com/9834590/30885503-2bb18024-a2d9-11e7-85eb-bec4d26dd96f.png)
![signal-2](https://user-images.githubusercontent.com/9834590/30885507-2df9602c-a2d9-11e7-9eb5-02ecc940b80c.png)
![signal-3](https://user-images.githubusercontent.com/9834590/30885510-2fb0aeca-a2d9-11e7-9840-5d452fffc049.png)

### Device info

**Device**: iPhone 8 Plus, 256GB
**iOS version**: 11.0.1
**Signal version:** 2.16.1.3

### Link to debug log
https://gist.github.com/anonymous/a073901941903736ac51ed7469d680a9

**Comment by caveman1973** [comment]
This was already mentioned. Waiting years for this feature.

**Comment by halo** [comment]
Dear Bot, while I would not put a high priority on this issue, I still think it is relevant (because it takes much time to re-configure all ringtones manually after installing Signal). 

Searching for a solution to the problem led me to this Github issue. So I think it should remain open (other people like me may find it soothing to know it is not a user handling problem but a software problem, and we can subscribe here to get updates on the status).

Thank you bot, you're the best.

**Comment by NiklasBr** [comment]
This is still relevant, see @halo's comment.

**Comment by NiklasBr** [comment]
This is still relevant, see @halo's comment.

**Comment by NiklasBr** [comment]
This is still relevant, see @halo's comment.

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by EvanHahn-Signal** [comment]
Unfortunately, this is not possible because of restrictions in iOS. We'd love to add it but the OS doesn't allow it.

You _can_ change the message sound by opening the chat's settings inside of Signal. Hope this helps!

**Comment by halo** [comment]
Thank you very much for the clarification and good luck with your other efforts on Signal 👍🏻
