### ISSUE TITLE
Group chat bug iOS

### ISSUE THREAD

**Issue by lewisweil** [signalapp/Signal-iOS#2603]
I’m on iOS 11 on a iphone SE. I cannot reply to group chats and “tap here for settings” does not respond to touch.

I can reply on my chromebook with the signal app.

**Comment by Ashtonian** [comment]
I had the same issue this morning, just to provide a bit more info: The group chat on iOS doesn't have the text box at the bottom and the settings button is nonresponsive. The title of the group is also "new group" even though in the chrome signal app its named properly. I can read messages from the group but not reply as there is no text box to type. 

IOS debug log: 
https://gist.github.com/02a6b40055834772b170204222acc308 

Chrome App debug log: 
https://gist.github.com/cec7b801c954661ec25cc42c9a97b628
