### ISSUE TITLE
IOS Group Chat non responsive

### ISSUE THREAD

**Issue by Ashtonian** [signalapp/Signal-iOS#2607]
- [x] I have searched open and closed issues for duplicates
----------------------------------------

### Bug description
The group chat on iOS doesn't have the text box at the bottom and the settings button is nonresponsive. The title of the group is also "new group" even though in the chrome signal app its named properly. I can read messages from the group but not reply as there is no text box to type. 

### Steps to reproduce
- have a group chat on multiple devices
- wait an x amount of time
- try to use group chat on IOS 

**Actual result:** Can't participate in group chat. 
**Expected result:** Should be able to participate in group chat. 

### Screenshots
na

### Device info
**Device**: iphone 6s
**iOS version**: 11.0.1 (15A402)
**Signal version:** 2.16.2.0

### Link to debug log
IOS debug log: 
https://gist.github.com/02a6b40055834772b170204222acc308 

Chrome App debug log: 
https://gist.github.com/cec7b801c954661ec25cc42c9a97b628

**Comment by temal-** [comment]
Problem persists in the following configuration:
**Device:** iphone 6s
**iOS version:** 11.0.3 (15A432)
**Signal version:** 2.17.0.8

**Comment by temal-** [comment]
Problem persists using the following configuration:
Device: iphone 6s
iOS version: 11.0.3 (15A432)
Signal version: 2.17.1.1
