### ISSUE TITLE
Message details screen does not contain enough detail

### ISSUE THREAD

**Issue by TempSpas** [signalapp/Signal-iOS#2630]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

The newest Signal update added "message details" which purports to display info about when messages were sent. However, compared to the stock messaging app, Signal's timestamp info contains very little detail.

### Steps to reproduce
- Long-press a message
- Select Info
- Observe the Message Info screen

**Actual result:** The screen contains only a vague identifier of the day of the week on which the message was sent.
**Expected result:** Screen should contain exact time and date the message was sent and received, especially when given a new, entirely blank page.

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/3801275/31454283-f6eaeece-ae82-11e7-8ca1-02e125953c29.PNG)

### Device info

**Device**: iPhone 6
**iOS version**: 11.0.2
**Signal version:** 2.17.0.8

**Comment by nrizzio** [comment]
It would also be beneficial to include delivery information per member in group chats similar to how the Android client does: WhisperSystems/Signal-Android@285947eb668d7358c6f0dfd201c3cf63f32db636

**Comment by michaelkirk-signal** [comment]
This has been addressed a couple releases ago (2.20.* IIRC)
