### ISSUE TITLE
Registration Flow Design Issues

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#2645]
Here are some of the most common problems with our registration flow. They're included together rather than as separate issues because there are some overlapping design concerns.

PROBLEM: users request SMS multiple times since there is a delay in receiving it. When the SMS arrives the verification is no longer valid since the user has already requested a new one. Same if they initially requested an SMS then request a call and both are delayed.

PROBLEM: Need users to check country code and special case formatting -- mexico (+521), argentina (+549) , brazil (+5521 example).

PROBLEM: Users register another mobile device i.e. an iPad or second phone thinking they can link the two. They are not aware that registering a second device deactivates the first device.

PROBLEM: Users unaware that there is no "white list" feature of Signal and that anyone with their number who is also a Signal user can message them. Android's SOLUTION via more information text: "Signal makes it easy to communicate by using your existing phone number and address book. Friends and contact who already know how to contact you by phone will be able to easily get in touch by Signal. Registration transmits some contact information to the server. It is not stored."

PROBLEM: when submitting a verification code, it is relatively easy to tap on request new code inadvertently.

**Comment by sophiakc** [comment]
Hi @michaelkirk
Are the problems you're listing observed for both iOS and Android? 
Is there any existing sketch files or equivalent for the iOS screens that you can share?

**Comment by sophiakc** [comment]
@michaelkirk @charlesmchen 
PROBLEM experienced myself: 
I enter my phone number to activate my iOS device. Receive the activation code immediately. Submit the code. And the spinner goes forever. Nothing happens. Of course, same behavior when tapping the link.
Is it a possible explanation to some of the previous problems? (1, 3, 5)
