### ISSUE TITLE
Media Picker Design Problems

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#2646]
Signal continues to add new media types (e.g. Giphy browser,  Documents, Voice notes, Camera, Photo Library).

PROBLEM: Most often, people just want to send a picture - the current design requires a lot of taps to accomplish this. How can we streamline this process while still leaving other media types easily discoverable?

**Comment by sophiakc** [comment]
Hi @michaelkirk 
Can you also share the existing iOS sketch files or equivalent that you have for these screens? So that I can start from the current plate.

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
