### ISSUE TITLE
Per conversation media gallery

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#2647]
Problem: As threads get longer, it can be a pain to find an old image or document. 

Also, sometimes people just want to browse through their old photos/videos.

**Comment by rocknjohn** [comment]
Related stepping stone: "Swiping left or right on a photo should show the next or previous photo in the conversation" https://github.com/WhisperSystems/Signal-iOS/issues/759

**Comment by sophiakc** [comment]
Hi @michaelkirk 
Idem as #2645 and #2646 can you share the existing iOS sketch files or equivalent?

**Comment by mailinglists35** [comment]
what do you need to finish this stuff faster? donations? more coders? being kidnapped and forced at gunpoint into writing this code in a week? seriously, it's a pain to use signal for sending media. do you devs don't use your own app? and if yes, are you not so annoyed at this missing feature?

**Comment by mailinglists35** [comment]
i don't think you need to waste time on 'design' . "oh, let's do it this way. NOOO, do it my way, it's better". just do it like whatsapp or whatever, BUT JUST DO IT SOONER.

**Comment by michaelkirk-signal** [comment]
Fixed in 2.23
