### ISSUE TITLE
Attachments cause app to crash 2.17.0 and 2.17.1

### ISSUE THREAD

**Issue by aruabwba** [signalapp/Signal-iOS#2648]
On IOS 8 tested with Iphone 5 and 6,  version 2.17.0 and today's release 2.17.1  crashes when attaching images from locally stored photo gallery

Did not happen before Oct 10

**Comment by aruabwba** [comment]
To reproduce:

Open contact
Tap paperclip to attach image
Select image
Tap Green send button

At this point it crashes every time

**Comment by michaelkirk-signal** [comment]
We've fixed a couple attachment handling bugs since this was first filed, if you're able to reproduce could you open a new issue with a complete issue template?
