### ISSUE TITLE
Profile picture doesn't refresh on other mobile devices

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#2682]

**Comment by michaelkirk** [comment]
Profile changes do not instantly propagate - they are cached for ~5 minutes. Is it possible you just hadn't waited long enough?

If this happened more than 5 minutes after you updated, could you submit a debug log and have your friend submit a debug log after entering your conversation thread?

**Comment by julmeq** [comment]
Hello @michaelkirk, i posted this issue two weeks after i encountered this bug, so i don't think it's about caching.

My debug log: https://gist.github.com/anonymous/72d75e030304acda09a14216e79c7d30
My friend's debug log: https://pastebin.com/sADS3DyX

**Comment by rocknjohn** [comment]
I find that it's necessary to _receive_ a new message from a contact before their profile picture will update. Not sure if that's intended behavior.

**Comment by julmeq** [comment]
Update: I don't know if it's related to Signal's last update, but the bug seems fixed, except when I delete my user avatar (it doesn't show the classic "user intials + random color")

**Comment by michaelkirk-signal** [comment]
Please re-open if this is still an issue.
