### ISSUE TITLE
[Feature Request] Emoji reacts to messages

### ISSUE THREAD

**Issue by banool** [signalapp/Signal-iOS#2738]
This would essentially be a duplicate of the feature in Messenger, or more extensively of that in Slack, where one can react to messages with emojis. This kind of fun addition would bring Signal closer to parity with other messaging platforms in terms of the "fun factor", if that is one of Signal's goals, similar to #1828. It's also pretty useful at times, people have become quite creative with it.

**Comment by invariant** [comment]
+1 for this .... I also note that Github (which we are using for this) has Reactions so I have applied my 👍 above.

**Comment by valilenk** [comment]
This is a huge communication accelerator and I see large groups of people who do not switch to Signal only because of the lack of possibility of reactions without sending a separate message.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by mguida22** [comment]
Here's the related post on the forum, for those interested.

https://community.signalusers.org/t/emoji-reactions/2776/49
