### ISSUE TITLE
Broken iOS Layout

### ISSUE THREAD

**Issue by PlainSite** [signalapp/Signal-iOS#2760]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
See screenshot.

### Steps to reproduce
- Talk on the phone. End conversation.

**Actual result:** Broken layout with input bar in the middle of the screen.
**Expected result:** Correct layout.

### Screenshots
![img_1717](https://user-images.githubusercontent.com/8204476/32876157-64de6738-ca50-11e7-8555-10e915b35741.PNG)

### Device info

**Device**: iPod Touch
**iOS version**: 11.1.1
**Signal version:** 2.18.2.1

**Comment by charlesmchen** [comment]
Thanks @PlainSite .  This is fixed in the next release, v2.19.

**Comment by axfelix** [comment]
Are you behind on pushing releases to the app store? Just curious as I've just installed the app for the first time and it seems to be running behind this repository for at least a couple numbered builds...

**Comment by michaelkirk** [comment]
This fix has been released for a while now. Please re-open if you see it on anything 2.19.5 or newer.
