### ISSUE TITLE
Empty list of friends numbers on first launch in "invite friends" menu after giving access

### ISSUE THREAD

**Issue by talanov** [signalapp/Signal-iOS#2808]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Empty list of friends numbers on first launch in "invite friends" menu after giving contacts access.

### Steps to reproduce
- First open of app
- Settings -> Invite -> SMS
- Give permission for contacts

**Actual result:** 0 contacts. If clicking again -> opens sms sender with no user to send.
**Expected result:** Shows my contacts

### Device info

**Device**: iPhone 6s
**iOS version**: 10.3.3
**Signal version:** 2.18.2.1

Right now trying to fix, but can forget, so making an issue.

**Comment by michaelkirk** [comment]
Are any of these contacts Signal users?

**Comment by michaelkirk** [comment]
Can you provide a debug log after going to the Invite -> SMS?
