### ISSUE TITLE
iPhone X - Phone call connection erro

### ISSUE THREAD

**Issue by wozney** [signalapp/Signal-iOS#2809]
[ x] I have searched open and closed issues for duplicates

----------------------------------------

 Bug description:

Anytime I make or receive a call on IPhone X, phone freezes, me and the caller cannot hear each other. App worked perfectly on IPhone 7 Plus and 8, switched over and does not work

 Steps to reproduce:

Make or receive a call

 Device info:

**Device**: IPhone X
**iOS version**: Newest version
**Signal version:** Newest version

 Link to debug log

https://gist.github.com/c074dc01bf0d1cab792248f1a6b2b094

**Comment by michaelkirk** [comment]
> Anytime I make or receive a call on IPhone X, phone freezes

Freezes and crashes? Or only momentarily freezes? 

Do you have any crash reports you can share? 

See here for instructions submitting crash reports: https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-reports

**Comment by wozney** [comment]
Sorry I should rephrase that. Sometimes the call timer stays at zero and kinda looks like it froze, but then after about 10 seconds the timer will go back to normal.

But I still cannot hear the caller and they cannot hear me

**Comment by michaelkirk** [comment]
Your debug log looks truncated. Looks like you've only recently enabled debug logging. Can you kill and relaunch signal than reproduce the behavior so we can get a full debug log?

**Comment by wozney** [comment]
https://gist.github.com/d291c4d345ee55beede651738b0021bd

**Comment by michaelkirk** [comment]
Thanks for the follow up.

Can you go to the system settings app and send me a screenshot of your Signal settings?

**Comment by wozney** [comment]
![a221201b-5b9c-4f38-acc9-ab1e38628e96](https://user-images.githubusercontent.com/31085107/33226870-b25a56be-d164-11e7-8e5f-b7f66a989b71.png)

**Comment by michaelkirk** [comment]
There are some changes to how we handle audio devices that might address this in the latest beta. 

If you’re interested in trying, email support@whispersystems.org with the subject “sign me up for the Signal iOS beta”.

Keep in mind that, Being a beta release, it’s more likely to crash or lose data.

**Comment by wozney** [comment]
Why hasn’t any other iPhone X user complained about this issue. Is it possible because I backed up my iPhone 7 Plus then transferred it to IPhone X that the app still thinks I’m using the 7 Plus. Should I try to delete app and reinstall

**Comment by wozney** [comment]
I have figured out the fix for this issue.

When updating from iPhone 7plus to IPhone X you cannot use the backup to restore your data to IPhone X, for some reason it’s screws up something in SIGNAL and doesn’t allow the phone to work.

The fix is to setup phone without using a backup and it will work perfectly. Then download contact from the cloud and then download apps manually
