### ISSUE TITLE
Text entry field is not positioned correctly on iPhone X for emoji keyboard

### ISSUE THREAD

**Issue by abrahamvegh** [signalapp/Signal-iOS#2812]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
On iPhone X, the text entry field is not positioned at the top of the keyboard when using the emoji keyboard.

### Steps to reproduce
- Launch Signal on iPhone X
- Begin a conversation
- Switch to the emoji keyboard

**Actual result:** The text entry field is not visible until you switch back to a textual keyboard.
**Expected result:** The text entry field should be repositioned above the keyboard.

### Screenshots
![img_0207](https://user-images.githubusercontent.com/53161/33285377-1dbc11b4-d380-11e7-9d77-c919e18edbf0.png)

### Device info

**Device**: iPhone X
**iOS version**: 11.1.2 (15B202)
**Signal version:** 2.19.0.22

**Comment by abrahamvegh** [comment]
I have now tested this in the iOS Simulator and it works correctly there, which explains why it wasn’t obvious before shipping. Investigating further…

**Comment by abrahamvegh** [comment]
This is reproducible in the Simulator if the textual keyboard’s ‘Predictive’ mode is disabled. (It is enabled by default.)

**Comment by abrahamvegh** [comment]
This bug seems to be directly related to the changes introduced to `OWSViewController` in 8c69e00a by @michaelkirk. I’m trying to figure out how that math is supposed to be working so I can see if I can discover a fix.

**Comment by abrahamvegh** [comment]
It seems that iOS 11 may not reliably trigger keyboard frame update notifications (see [here](http://openradar.appspot.com/radar?id=5026499329523712)), which means that the code that attempts to compensate for the keyboard height cannot reliably do so. No fix is obvious to me, although there is so much going on around this control that an obvious solution may be eluding me.

**Comment by charlesp-l** [comment]
This problem also happens on iPhone 6 Plus, which supports the case that's a problem with iOS 11, more than a specific device.

**Comment by abrahamvegh** [comment]
I’ve been seeing the same issue in apps like Facebook, and the problem continues with the public release of iOS 11.2, so this is almost definitely not a Signal bug, until Apple fixes the missing notifications.

**Comment by wchresta** [comment]
Issue still persists in Version 2.19.3. Whatsapp and iMessage do not have this problem so people will switch if this is not fixed soon.

**Comment by abrahamvegh** [comment]
This appears to have been fixed in production. Thanks!
