### ISSUE TITLE
Speaker-phone doesn't work if turned on at the begining of the call

### ISSUE THREAD

**Issue by gsbabil** [signalapp/Signal-iOS#2813]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

Speaker-phone functionality doesn't work properly if turned on
immediately after placing a call.

### Steps to reproduce

1. Place a Signal outgoing call

2. Immediately turn on the speaker by tapping the speaker-phone
   button on the ongoing call screen (while the call is still in
   _CONNECTING_ state)

**Actual result:**

  - At step 2, there would not be any audio through the speaker yet
    (only through built-in earphone).

**Expected result:**

  - Audio for both _CONNECTING_, _RINING_ and _ESTABLISHED_
    call-states should pass through the loud speaker once the
    speaker-phone button is turned on

### Screenshots

N/A

### Device info

- **Device**         : `iPhone 6`
- **iOS version**    : `11.1.2`
- **Signal version** : `2.19.022`

### Link to debug log

N/A

**Comment by michaelkirk** [comment]
I’m not able to reproduce this. 

Does it reproduce 100% of the time for you?

After hitting the “call” button can you turn your volume all the way up and confirm there is *no* sound coming from the bottom of your phone for neither “connecting” nor “ringing”?

Is either sound better than the other?

It may be an issue of our audio levels not being loud enough.

**Comment by gsbabil** [comment]
Hi Michael (@michaelkirk),

Thanks for the prompt feedback. Yes, this is reproducible 100% for
me. I'm adding more details below. Please have a look.


## Additional Bug Description

### Nomenclature

Signal in a default set-up on iPhone/iOS, without any external
accessory attached, seems to support the following audio routes:

  1. Phone's quiet speaker _i.e._ when we hold the phone next to the
     ear to listen to audio.

  2. Phone's built-in loud speaker (also known as the
     "speaker-phone") _i.e._ as in playing audio through the phone's
     loud speaker without the need to hold the phone next to the
     ear.

Given the following code in [`CallAudioService.swift`][1], I think
list-item 1 above is the same as _built-in-speaker_, and list-item 2
is the same as _built-in-earpiece_.

```
  // The built-in loud speaker / aka speakerphone
  let isBuiltInSpeaker: Bool

  // The built-in quiet speaker, aka the normal phone handset receiver
  // earpiece

  let isBuiltInEarPiece: Bool
```

### Further Details

Now to clarify the issue, I'm _not_ saying that there's _no audio_
during call connecting-state, ringing state, or during the ongoing
call.

Audio works as expected at the beginning or later in a call, but
comes through the built-in-earpiece only. I'm claiming that there's
no audio through the built-in-speaker, _if_ the speaker-phone button
is turned on immediately after the call is placed, as shown in
[Figure 1][fig-1].

In the case above, audio continues to come through the
built-in-earpiece, even though speaker-phone button is turned on.

If the speaker-phone button is turned on immediately after the call
when the call is in connecting/ringing states, the call eventually
is picked up by the callee and there's bi-directional audio, you'll
notice that the audio even at this stage still doesn't flow through
the built-in-Speaker.

At this stage, if the speaker-phone button is toggled (turned-off
from the turned-on state, and then turned-on again), loud audio
starts to come through the built-in-speaker as expected.

After placing a call in the default behavior, Signal uses the
built-in-earpiece for all audio, and the speaker-phone button is
turned-off as shown in [Figure 2][fig-2].

[1]: https://github.com/WhisperSystems/Signal-iOS/blob/bb22adbeba4a0f41636ba5b8413292a385a5de50/Signal/src/call/CallAudioService.swift

[fig-2]: https://user-images.githubusercontent.com/1061108/33328493-3e929f14-d4ae-11e7-9b3b-8233d55a1041.jpg

[fig-1]: https://user-images.githubusercontent.com/1061108/33328494-3ecd17f2-d4ae-11e7-83fc-8ece6781dfd7.jpg


## Figures

### Figure 1

<img src="https://user-images.githubusercontent.com/1061108/33328494-3ecd17f2-d4ae-11e7-83fc-8ece6781dfd7.jpg" width="375" height="667">

### Figure 2

<img src="https://user-images.githubusercontent.com/1061108/33328493-3e929f14-d4ae-11e7-9b3b-8233d55a1041.jpg" width="375" height="667">

**Comment by michaelkirk** [comment]
Can you please provide a debug log after experiencing this behavior?

Did this function correctly for you before the 2.19 update?

I believe I understand what you're reporting, but I still cannot reproduce it.

Here are my steps:

1. Call Alice
2. hear a "pong" aka "connecting" sound coming through the receiver**
3. enable speakerphone
4. hear another louder "pong", this time it's through the top *and* bottom speakers (which is as expected for speakerphone on my device).
5. call connects, hear "ring" sound through speakerphone
6. Alice answers, I hear Alice through the speakerphone.

**Even if I skip step 2 and enable speakerphone ASAP after hitting the "call" button, the rest of the steps work the same for me.

Are these the same steps you are taking?

**Comment by gsbabil** [comment]
Hi Michael,

The steps 1-6 you described above are correct. In my case, I'm just
enabling speaker-phone before I even start hearing the "pong".

I think I have experienced this issue before the `2.19` realease.
But I don't remember with 100% accuracy.

Please find the debug-log [here][1]. Thank you.

[1]: https://gist.github.com/d7b48b0e321c1f436418a9c357328ba1


P.S.

  - Is there a command-line tool to debug/test these better?
  - What is your standard set-up to do these debugging?
  - Is it possible to have a Signal account registration without a
    real device for testing/debugging purposes? 

Thank you.

**Comment by mailinglists35** [comment]
i encountered this with some older app store release. it no longer happens on latest testflight version

**Comment by fdalvi** [comment]
I face exactly the same issue, with Signal on the latest available version in the AppStore as of today. 

Device : `iPhone 6s`
iOS version : `11.2.51
Signal version : `2.19.5.0`

Will try to post a debug log soon!

**Comment by littleporkchop** [comment]
This happens to me too often as well.  If I receive a call through Signal while I’m connected to Bluetooth device like a speaker sometimes the audio will not work at all even once disconnecting from the Bluetooth

**Comment by ngie-eign** [comment]
+1.

I'm running into this issue with both audio chat and video chat. My friends that are using the Android app frequently complain about not being able to hear me :(...

**Comment by moudstar** [comment]
Im having the same issue on an iPhone 8. Any updates on when there might be a fix?

**Comment by SuperDisk** [comment]
Having the exact same issue. You can turn speakerphone on for real once the call has started by toggling the speakerphone button on and off.

**Comment by victor-perez** [comment]
Same problem with the `Pixel 3a`, `Android 11` and Signal version `5.9.3`. the fastest way to fix it is to turn off video then click on audio and now you will have 3 options where from  **earphone** is selected. You can now select **speaker** and then turn on you video and now it works with both video and speaker
