### ISSUE TITLE
Fonts a little small in iPhone X inbox 

### ISSUE THREAD

**Issue by axfelix** [signalapp/Signal-iOS#2816]
Thanks for pushing iPhone X changes to the app store, working great. Inbox fonts look a little small now though (conversation view is fine).

**Comment by rocknjohn** [comment]
The small font size on the Inbox view is likely due to lack of Dynamic Type in this view https://github.com/WhisperSystems/Signal-iOS/issues/471

**Comment by djc2** [comment]
It's not just iPhone X. A fellow user is refusing to use Signal with me because she can't read the summary text without getting her glasses to read the summary text in the inbox. Her device is iPhone 6 and she is using Dynamic Type to solve this problem on Messages.

**Comment by michaelkirk-signal** [comment]
The inbox should now respect your dynamic type preferences.
