### ISSUE TITLE
Add Option to Completely Mute Contact (No Badge, Conversation not Highlighted)

### ISSUE THREAD

**Issue by peacememories** [signalapp/Signal-iOS#2841]
Hello and thank you especially for the recent improvements to the app.

One thing I have had problems with so far is that muting conversations still results in them adding to the badge count and still being highlighted in the conversations menu when new messages arrive.
I understand that some people might prefer this behavior but I would love to have an option to completely mute the conversation, while still being able to read it (which is not possible when blocking people).

**Comment by michaelkirk** [comment]
Thanks for the suggestion, but we avoid options whenever feasible.
