### ISSUE TITLE
regression: tapping the message area does not hide the keyboard (v 2.19.2.0)

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#2848]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
regression: tapping the message area does not hide the keyboard (v 2.19.2.0)

### Steps to reproduce
- open a conversation
- type a message
- tap an area outside the keyboard

**Actual result:** keyboard does not hide
**Expected result:** keyboard hides

### Device info

**Device**: iPhone SE
**iOS version**: 10.2
**Signal version:** 2.19.2.0

### Link to debug log

this was discussed in #760 then sometime it was reverted and signal behaved like all standard messaging clients (tapping an area hides the keyboard), it worked ok until latest release when a regression in code has bring back the inability to hide keyboard

**Comment by mailinglists35** [comment]
workaround for the other only one user who will be annoyed by this: start dragging the left edge then release it before the swipe is complete. this will cause the keyboard to close while remaining in the conversation.

**Comment by caveman1973** [comment]
As I remember, you have to swipe the keyboard down to hide it. Not always works and it's more cumbersome compared to clicking on the messaging area.

**Comment by mailinglists35** [comment]
another workaround I discovered is to start scrolling down content. the keyboard will hide after several line scrolled. on whatsapp/other apps, the keyboard hides with a simple tap.

**Comment by ismay** [comment]
Regardless of existing workarounds I think tapping outside of the keyboard to close is a pretty established ui pattern. People expect it to work and I think it would be nice if Signal supported it as well.

**Comment by mailinglists35** [comment]
@ismay it seems for me since more than several testflight versions ago, that i can hide the keyboard by tapping an empty area, do not release, then drag down: the keyboard will hide.

still not ideal like i've reported but at least an easy way to hide it.

**Comment by denver-s** [comment]
I do not experience this bug on version 3.0.6.

**Comment by mailinglists35** [comment]
yes, this I believe was fixed some time ago. thanks for mentioning.
