### ISSUE TITLE
Add the ability to set an alias to a phone number instead of having to send the addressbook

### ISSUE THREAD

**Issue by trufae** [signalapp/Signal-iOS#2865]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When using Signal without sharing the addressbook it is not possible to set an alias name to a contact, it's always forcing you to give permissions to share or access the addressbook.

I don't see any technical limitation for having such phone -> alias database inside the app (or inside the chat information), but that would be interesting to have it done securely, so not storing those aliases in plain and removing them as soon as the conversation is removed.

This feature could be used even with addressbook. But will let paranoid users use signal without give extra permissions to the app.

### Steps to reproduce
- install signal for ios
- on launch say no to access to addressbook
- open a chat with phone number
- try to set a name for this phone number. but there's no way

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by lorenzb** [comment]
Would the maintainers be willing to consider a pull request adding support for setting such an alias as part of the "Contact Info" menu?

**Comment by fe60** [comment]
I would like to get this feature (in the Android version), but I think this is the wrong tool to discuss feature requests [1].
Searching for "alias" in the SignalCommunity [2] brought up a feature request for a "Private contact list" [3].
In two discussions about the "usefulness of your profile name" [4] and the necessity to set a profile name [5] the underlying problem of using Signal without granting it access to the address book appears here and there.

[1a] https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md (The issue tracker is for bugs, not feature requests)
[1b] https://github.com/signalapp/Signal-iOS (Contributing Ideas)
[2] https://community.signalusers.org/search?q=alias
[3] https://community.signalusers.org/t/private-contact-list/12466
[4] https://community.signalusers.org/t/usefulness-of-your-profile-name/10588
[5] https://community.signalusers.org/t/do-not-require-a-profile-name-to-be-set-allow-users-to-delete-their-profile-name-or-explain-why-first-name-is-required/11515

**Comment by trufae** [comment]
Not relevant for me because I gave up on trying to use signal without sharing the whole addressbook, so whatever

**Comment by kaktusztea** [comment]
@trufae: then you clould close the ticket.
