### ISSUE TITLE
Suggestion: Let's choose the default browser

### ISSUE THREAD

**Issue by raymontag** [signalapp/Signal-iOS#2871]
Hello,

at the moment links are opened in Safari only. However, it would be nice if I could choose to set the default browser to other installed ones, e.g. Chrome or Firefox.

**Comment by inoas** [comment]
This has been open for more than 2 years.

Tons of iOS apps now support setting their default browser. It is the only really supported way to let users choose their browser

**Comment by inoas** [comment]
Ref https://github.com/signalapp/Signal-iOS/issues/4243
