### ISSUE TITLE
Autocorrect doesn't trigger for last word in a message when clicking Send

### ISSUE THREAD

**Issue by mruffalo** [signalapp/Signal-iOS#2875]
This is just a small quality-of-life suggestion. In Apple's Messages app, you can type something which triggers autocorrect, and pressing "send" will send the corrected version of what you've typed. Signal sends the un-corrected version though, which necessitates pressing the spacebar and backspace before sending a message, if you've mistyped the last word of the message.

It would be nice to match the behavior of Messages and apply any pending autocorrect suggestions when pressing Send in Signal.

**Comment by SuperDisk** [comment]
This problem seems to be a regression as the expected behavior happened until a recent update.

**Comment by NathanJang** [comment]
I have made a pull request #3226; hopefully it gets accepted.

**Comment by lwolfsonkin** [comment]
This is a wonderful feature and I was watching this when it was originally added!

Though, on my device, the current version (5.15.13) no longer does this, now not invoking autocorrect for bolded words in the keyboard when the send button is pressed.

it seems to me this issue should be reopened to signify the regression (assuming others can reproduce this).

Thank you!

**Comment by SuperDisk** [comment]
Can confirm. The bug just got re-introduced, it seems. Blast from the past :)
