### ISSUE TITLE
Swipe right to go back sporadically breaks

### ISSUE THREAD

**Issue by TempSpas** [signalapp/Signal-iOS#2879]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

Signal provides an easy way to navigate back from a conversation to the inbox by swiping right from the left edge of the screen. However, on occasion, this functionality will break entirely, and no navigation will occur.

### Steps to reproduce
- Attempt to swipe right from the left edge
- Observe that there is no screen transition, no navigation
- Observe that the contact name at the top will become overlapped with the back arrow as if the screen transition were occurring, but nothing happens.

**Actual result:** Swipe should navigate back to inbox.
**Expected result:** It doesn't.

### Screenshots

![signal bug](https://user-images.githubusercontent.com/3801275/33911302-ed33b0d8-df5f-11e7-8805-22e5029e6807.png)

The above is a screenshot of the overlap that occurs. Again, this is the only thing on the screen that changes at all when the swipe is initiated. No other transition occurs. I have not found a way to reliably reproduce this. Force quitting the app and restarting it does not fix the issue.

### Device info

**Device**: iPhone 6
**iOS version**: 11.2
**Signal version:** 2.19.2.0

**Comment by TempSpas** [comment]
I've figured out part of what's happening. The bug occurs **when you attempt to swipe anywhere along the left edge that someone else's message is.** The swipe-back works correctly if you swipe along the edge anywhere across from one of your own messages. In other words:

![signal-ios-app](https://user-images.githubusercontent.com/3801275/33912969-e977a48a-df65-11e7-8f46-d66777425a93.png)

The red areas along the side are where the bug occurs and the swipe is broken. The green areas are where it works as intended.

**Comment by mmiller42** [comment]
Also occurs for me on iOS 11 on iPhone 8.

**Comment by michaelkirk** [comment]
This will be fixed in the 2.20 release, stay tuned!
