### ISSUE TITLE
please show Signal in this list (screenshot attached)

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#2880]
![img_7794](https://user-images.githubusercontent.com/2054302/33924285-0b18cd1c-dfde-11e7-84af-bba695f7f4c0.PNG)

**Comment by mateoeh** [comment]
Duplicate of #650

**Comment by michaelkirk** [comment]
closing as dupe of https://github.com/signalapp/Signal-iOS/issues/650
