### ISSUE TITLE
Messages that fail to send don't disappear

### ISSUE THREAD

**Issue by andrewpcone** [signalapp/Signal-iOS#2894]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When a message fails to send, it remains legible in the thread indefinitely, past the disappearing time. Messages a user attempted and failed to send are no less sensitive than ones that succeed—and could reasonably be presumed more sensitive.

### Steps to reproduce
- disconnect the phone from the internet
- send a message in a thread with a given disappearing time
- wait past the disappearing time, and it's still there

**Actual result:** The message is still in the thread.
**Expected result:** A notice *that* a message failed to send is retained in the thread. The contents of that message are not retained. Possibly, a per-thread setting enables one to revert to the current behavior. However, the default should be that the message disappears: if the user has set a disappearing time, that means they need the messages off their phone by then.

### Device info
**Device**: iPhone 6
**iOS version**: 10.1.1
**Signal version:** 2.18.2.1

**Comment by leonardoporpora** [comment]
@michaelkirk yes i noticed this too. i think that the messages must be deleted and maybe just give an alert that message wasn't send but it must be deleted

**Comment by M09NST3R** [comment]
This issue still exists. I've often found myself finding old unsent messages long past the disappearing messages timer.

**Comment by xanoni** [comment]
Still relevant, my friend.

**Comment by xanoni** [comment]
Can't tell if this has been resolved, as I stopped using the iOS app. See a thumbs down though, so I guess worth reopening until someone can confirm.
