### ISSUE TITLE
Is anything preventing the compiler from optimizing isEqualToData_TimingSafe into a short-circuiting loop?

### ISSUE THREAD

**Issue by Strilanc** [signalapp/Signal-iOS#29]
I wrote the method [`isEqualToData_TimingSafe`](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/crypto/CryptoTools.m#L66) to use non-short-circuiting logic, but the language semantics might allow the compiler to optimize it into a loop that does short-circuit, (The compiler would have to reason across the message passing, but it's possible.)

Can this method be delegated to a crypto library?

**Comment by CollinStuart** [comment]
Is this method now named `ows_constantTimeIsEqualToData` - the one used for verifying the HMAC when decrypting the payload for incoming messages?

Inside that method, what about simply adding the `volatile` keyword to the `BOOL isEqual = YES;` definition? (telling the compiler the value of the variable can change at any time without it being able to see)

I can possibly see when `isEqual` is `NO` once in the loop that the rest of the check never needs to happen after the `&&` so the loop can end early. If the `(leftBytes[i] == rightBytes[i])` is before the `&& isEqual` check then it always has to run regardless if `isEqual` is `YES` or `NO`, unless that flag gets cached in a CPU register - I could do some tests to see if I can actually get that theory happen but, it could all change again with another version of Clang, so I think adding the `volatile` keyword might be the best approach.

**Comment by michaelkirk** [comment]
fixed with d5e61dac9
