### ISSUE TITLE
Video attachment upload: Block device from sleeping while compressing/uploading

### ISSUE THREAD

**Issue by jerclarke** [signalapp/Signal-iOS#2902]
- [X ] I have searched open and closed issues for duplicates

(I looked at everything with 'video' or 'upload' in the search)

### Bug description

I use signal to send video clips recorded in the iOS camera app. This is needed especially when the connection is bad, and thus video calling is non-functional, but also requires long upload times to send the recordec clips, triggering this problem.

When the video is long, or if the connection is bad, it takes longer to compress and/or send the video than the auto-lock timer on my iOS device, and the device shuts off before finishing the process (first dimming, then going black). 

It seems Signal does not send whatever message is necessary to iOS that it's current state needs to block auto-sleep while compressing and uploading. 

As I would expect, when watching a video, auto-lock is never triggered. Until the video ends the app will never go to sleep. 

I find the auto-lock coming on during compression/upload frustrating and confusing as a user. Why would I expect the phone to sleep while in the middle of compressing or uploading a video?

It also means that on many occasions, when I turn it back on, I see generic upload failure errors and the video has not been sent. This bug isn't reliable, and sometimes the video has been sent in the background, or continues uploading after I return to the app, but there were many occasions where it did not, and I had to restart a long upload process (by re-selecting the attachment and recompressing) long after I thought my recipient had the video already.

I suspect this might be triggered by performance problems with my iPhone 6, especially related to the recent revelations about battery problems triggering an underclocked mode. Regardless of this though, Signal works fine as long as the auto-lock isn't triggered during upload, so configuring Signal to not go to sleep during upload will likely improve the UX for a lot of users with older devices and/or depleted batteries (i.e. this is an accessibility/inclusion issue). 

In testing the bug for this ticket, I realized that the intended behavior for Signal is to continue the upload even after sleep, and that in ideal conditions it is in fact capable of doing so, which is good, and theoretically justifies leaving auto-lock enabled, but I am here to tell you that in practice this is extremely unreliable, and there needs to be a way to ensure auto-lock doesn't happen while videos are uploading.

**All we need is for the compressing and uploading steps to have the same property of stopping the phone from auto-locking as video playback does.**

Making this change will be good for user confidence both because it is almost certainly what they would expect while the phone is actively doing something for them, and because the bugs triggered by phone sleep are extremely frustrating to deal with when they come up. 

Why this is important: If the video I was sending was extremely important it might never get sent. If I was a protester being arrested, being able to start the upload and let it run, knowing the recipient will get it as long as the phone isn't shut off before upload, would be extremely important. Finding out when released from jail that the video never left my phone because I had battery saver turned on (a security feature in any other context) would be extremely disappointing.

Workaround: I figured out that the best way around this is to start the upload, then immediately find another long video in the same conversation and start it playing while the upload is happening, this way I can reliably upload my video. What a miserable workflow though, especially since usually the bug won't be triggered, but I have no other way to make the process reliable.

### Steps to reproduce

- Have a short auto-sleep timer (**Auto-lock*) on your phone (30s is best for general security)
- Record a video long enough that it will take more than that time to upload (This is tricky, before my battery replacement anything over 2 min was triggering this problem, but after replacing battery I had much better luck even with a 4 min video)
- Select it as attachment in Signal conversation
- (too-slow compression can trigger the problem it at this point)
- Send the video
- (too-slow upload much more likely to trigger the problem at this point)

**Actual result:** 

Compressing: 

* After 30s of compression screen dims and shuts off. 
* When the phone is turned back on, the video may or may not have finished compressing and be ready to send
* Sometimes there is an error and I have to start back at the "select attachment" step

Uploading:

* After 30s of uploading screen dims and shuts off.
* When the phone is turned back on, the video is sometimes sent and watchable
* OTHER times (seemingly dependent on performance context of the phone, likely whether the app needs to "restart" or not) there is an upload error waiting for me, e.g. one had error test similar to "Error contents of the file were invalid"
* In these cases the upload needs to be restarted from the "select attachment" step

To get longer videos to upload I need to babysit my phone tapping the screen constantly (every 25s) to stop it from going to sleep, or else scroll around re-reading old messages or watching old videos so that it doesn't go to sleep. 

**Expected result:** 

Compression:

* Once the compression starts, the auto-lock is subverted and the phone doesn't go to sleep until the compression is complete.
* Users can shut the screen off using the power button if necessary.

Uploading: 

* Once the user hits send, the video begins uploading and the auto-lock is subverted until the upload is complete.
* Users can shut the screen off using the power button if necessary.

Consideration: Is this auto-lock behavior intentional or accidental? If it's intentional, then I guess I'm asking for that to be reconsidered because of the possiblity of interaction with other bugs, as well as the desire for a more reliable and immediate upload workflow. If it's accidental then the request is more simple: Make an explicit decision to disable auto-lock while uploading.

Make it a setting: One option would be to make this a user-configurable setting so that security conscious users can keep the auto-lock for  security benefits (i.e. they'd rather the video didn't send than that someone could grab the phone while the video is uploading) while time-conscious users could disable auto-lock for the sake of more reliable uploading. 

Based on the settings screen in the app though, I suspect you are in the less-is-more camp WRT settings, and will need to make a general decision for all users. If this is the case I strongly propose you disable auto-lock during uploads, because users who WANT their phone to shut off in the middle of an upload can already use the power button, while those who want the phone to stay awake hae no logical option to do so. 

### Screenshots

I tried hard but wasn't able to replicate the error states I've experienced where uploads failed and needed to be restarted from the "choose attachment step". 

The main behavior I'm describing can't be shown in screenshots, but would look like a shadowed out screenshot of a video being uploaded (when the screen dims) and a black screen (when it shuts off)

### Device info
**Device**: iPhone 6
**iOS version**: 11.2.1
**Signal version:** 2.19.3.3

### Link to debug log

https://gist.github.com/anonymous/d25d19989bd9e4f0ae25fbb38068a457

Okay, this error log does has the specific error I mentioned, it happens at approx: 2017/12/31 09:58:32:964

**Comment by hraban** [comment]
Something to explore: is this behaviour different between battery saving mode, and regular battery mode with 30 sec screen lock? I noticed in #4501 that in normal battery mode the screen lock is blocked, but not in battery saving mode.

**Comment by hraban** [comment]
My bad, I was wrong about this. It happens either way. Regard that comment :)

**Comment by hraban** [comment]
yes it's still relevant.

**Comment by jerclarke** [comment]
Still relevant to me.

**Comment by hraban** [comment]
yes

**Comment by hraban** [comment]
it's not stale
