### ISSUE TITLE
Apple Watch 3 - No Signal App on watch.

### ISSUE THREAD

**Issue by wozney** [signalapp/Signal-iOS#2928]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

Apple Watch 3 does not have an icon on the watch display. You can msg thru the app with dictation only when someone messages you first and it come up on the watch display. But when trying to open signal on the watch, signal is not found, I tried the main display menu and search thru Siri and Siri said to open it on the phone.

### Steps to reproduce
Just try and use it on the Apple Watch 3

### Device info

**Device**: Apple Watch 3
**iOS version**: Newest
**Signal version:** Newest

**Comment by platypus5021** [comment]
Still no app for my Apple Watch 6. No means to start a message that is not a direct reply to a message already received.
