### ISSUE TITLE
[Feature Request] Personalized Chat

### ISSUE THREAD

**Issue by blakkmaan** [signalapp/Signal-iOS#2934]
Version of Signal: 2.19.3
Version of iOS: 11.2.2
Phone Model: iPhone 6S

I would like to have more personalized Features like a Chat background for example. Or i would like to change the bubble color or the font size (not using system wide size), so Signal could really become „my messenger“. A Dark Theme would be great too.

Thanks for your efforts, great App!

**Comment by Jules2010** [comment]
Although there is now a dark theme, I often post in the wrong chat, it would be a lot easier with customisation of other chat view objects.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
