### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by ZhuxianQuan** [signalapp/Signal-iOS#2936]
I can upgrade the app in one machine.
But can not upgrade from other devices.
There are pod frameworks and Carthage frameworks.
And the app is not clear in there language.
Signal and SignalMessaging is built by less than Swift 3.2.
And extension is built by Swift 4.0.
So I can not build well.
Could you please check them and do it more easily?

**Comment by michaelkirk** [comment]
Are you following the steps in https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md ?

If you have trouble with those instructions, please include how far you got, which step you had trouble with, and any relevant output, like an error message.

**Comment by ZhuxianQuan** [comment]
huxians-iMac:signal-ios zhuxianquan$ carthage build --platform iOS
*** xcodebuild output can be found in /var/folders/0n/96vml4rj5m14dx924ld9_l3m0000gn/T/carthage-xcodebuild.nSnMan.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/zhuxianquan/My_Projects/Signal-iOS/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

**Comment by CollinStuart** [comment]
@ZhuxianQuan I believe this is caused by Xcode not having the correct command line tool selected in **Preferences > Locations**. Is the **Command Line Tools** set to the same Xcode version that you are using?

**Comment by michaelkirk** [comment]
I agree, it sounds like you don't have XCode command line tools set up. Feel free to re-open if you have trouble after getting that set up.
