### ISSUE TITLE
Unable To Include SignalServiceKit in IOS App

### ISSUE THREAD

**Issue by Ay786** [signalapp/Signal-iOS#2937]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Not able to install SignalServiceKit using Cocoapods.
pod 'SignalServiceKit', git: 'https://github.com/WhisperSystems/Signal-iOS.git'
### Steps to reproduce
- Open Terminal
- Go to the Project directory
- pod install

**Actual result:** [!] Unable to find a specification for `Curve25519Kit` depended upon by `SignalServiceKit`

**Comment by mingynaut** [comment]
I have the same issue (Mac OS Ver 10.14, Xcode Ver 10.1(10B61) )
while attempting to build SignalServiceKit for use in an app.

Below is more info... 

/Users/foobar/Documents/TestSignalServiceKit/Pods/Headers/Private/Curve25519Kit/Curve25519.h:16:1: Duplicate interface definition for class 'ECKeyPair'

/Users/foobar/Documents/TestSignalServiceKit/Pods/Headers/Public/SignalMetadataKit/SignalMetadataKit-umbrella.h:14:9: In file included from /Users/foobar/Documents/TestSignalServiceKit/Pods/Headers/Public/SignalMetadataKit/SignalMetadataKit-umbrella.h:14:

/Users/foobar/Documents/TestSignalServiceKit/Pods/Headers/Private/Curve25519Kit/Curve25519.h:29:1: Duplicate interface definition for class 'Curve25519'


It appears that one definition lives under 25519 and the other under Curve22519Kit

Podfile I am using:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '12.1'
use_modular_headers!

target 'TestSignalServiceKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
# use_frameworks!

  # Pods for TestSignalServiceKit
  pod 'SignalServiceKit', git: 'https://github.com/signalapp/Signal-iOS.git'

  # Dependency pods...
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git'

  pod 'SignalMetadataKit', git: 'https://github.com/signalapp/SignalMetadataKit'

end

**Comment by charlesmchen-signal** [comment]
@Ay786 @mingynaut This is working for me.

Can you please do:

>  pod --version

I'm using Cocoapods 1.5.3.

**Comment by michaelkirk-signal** [comment]
Hi @mingynaut - You'll want to pull Curve25519Kit and other dependencies from the same source as we do in the Signal-iOS [Podfile](https://github.com/signalapp/Signal-iOS/blob/master/Podfile#L21).

Additionally, we reserve Github for bug reporting with the official client, not for development support. The [community forum](https://community.signalusers.org/) is a better venue for development support.
