### ISSUE TITLE
Phone won't stop vibrating

### ISSUE THREAD

**Issue by Pavornoc** [signalapp/Signal-iOS#2943]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When opening/unlocking my phone at the same time as recieving a message in Signal, the phone continues to vibrate and will not stop until I fully power down the phone and reboot.  Closing the app has no affect. As of writing this, I've had this happen 3 times.

### Steps to reproduce
(Kinda tricky, but...)
- Unlock the device at the same time as recieving a message in Signal.  Does not seem to need to be *exact*.  If the phone is still vibrating from the notification while unlocking, it seems to trigger it.
- Unlocks have been done via TouchID, not PIN.

**Actual result:** Phone vibrates constantly and will not stop until phone is powered down.
**Expected result:** The phone eventually stops vibrating, preferably within in a short time frame.

### Screenshots
N/A

### Device info

**Device**: iPhone 7
**iOS version**: 11.2.2
**Signal version:** 2.19.4.4

### Link to debug log
Don't have one at this time.  I will try to capture one and update.

**Comment by michaelkirk** [comment]
@Pavornoc - can you readily reproduce this with the steps you provided, or did it just happen the one time?

I had something similar happen, while running the iOS11.3 beta when unlocking my phone just as an alarm went off (not Signal related in my case).

**Comment by Pavornoc** [comment]
@michaelkirk It happened to me about 5 or 6 times in total, but has not happened in the last month or so.  Possible that a subsequent update fixed this issue inadvertently. 

Might be worth closing this thread.
