### ISSUE TITLE
Separate logs of verification

### ISSUE THREAD

**Issue by theochino** [signalapp/Signal-iOS#2954]
Seperate logs of verification of the safety number 

- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by michaelkirk** [comment]
I'm not sure what you're proposing/requesting. Please fill out the issue template, or if you'd like to discuss a design proposal, the community forums might be a better place to get some feedback:  https://whispersystems.discoursehosting.net/
