### ISSUE TITLE
feature: multiple profiles! for example but not exclusive to dual sim.

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-iOS#2960]
This is a suggestion for a feature which other messenging apps seem to not have put any effort in yet. Therefore, implementing this might also give signal an edge and some publicity.
But besides that its just something some of us expected would be standard in 2018. Need to have.

I for one have a dual sim phone. In my case one sim for private use, anothe for business. The business sim I may take out of my phone once or twice a year to hand over to a buisness partner.

The issue:
In messaging apps including signal, all conversations are part of one account. They are all mixed together. On top of that (issue 2) my buisness partners can see the same profile as my family. This is rather restricting. My mother can see what my girlfriend can see and what my clients can also see. Just take a minute to imagine that. Yea that sucks right?

Suggestion:
Multiple profiles in signal.
Its a rather drastic step, I know. But think about it. Its human nature to uphold different identities. And this is also what privacy is about. I for one would love to keep those identities seperate.
The solution could be to have one identify for each sim card, or the solution could be to allow users to make infinite profiles and group contacts in them.

I know this would be a massive undertaking, all I ask is that we think about this. Could this be something we want?

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by Meteor0id** [comment]
For reference, this feature request is not being discussed in this forum topic: https://community.signalusers.org/t/multiple-seperate-user-profiles-for-example-but-not-exclusive-to-dual-sim-phones/2361
