### ISSUE TITLE
Disappearing message timer disables intermittently

### ISSUE THREAD

**Issue by toomuchio** [signalapp/Signal-iOS#2961]
Related: https://github.com/signalapp/Signal-iOS/issues/2284 - Somebody commented after it was closed to state the issue was present again.

It appears to be an iOS app issue I use Android, but in a group chat with a few other people it appears to turn off when they've: been inactive for an extended period of time, or when they add a new iOS device and speak in the group chat for the first time or anybody already present speaks that already has the disappearing message timer set.

I'm unable to provide debug logs since I myself don't have the iOS app.

**Comment by michaelkirk** [comment]
The next time this occurs, could you verify if the sending user recently linked a new desktop device?

**Comment by toomuchio** [comment]
Sure, but I have seen it in both instances.
A new desktop device is setup the disappearing message timer gets reset. I've only seen that happen once or twice
And a new iOS device is setup the disappearing message timer gets reset.

Has happened a few times, since somebody in my group chat has an aversion to installing apps on their phone. They only used the iOS app to bootstrap then switched to the desktop app and removed the iOS but has since reinstalled and uninstalled a few times.

When that happens the disappearing message timer gets reset whenever there's new activity in a group chat they were already apart of (ie. somebody other than them sends a message and they receive it or they send a new message.)

**Comment by M09NST3R** [comment]
Any update on this? Is this still an issue? I have not observed it myself.

**Comment by M09NST3R** [comment]
I just realized that this could be related: https://github.com/signalapp/Signal-iOS/issues/4953
