### ISSUE TITLE
Q: "More Is Less" /Rosler, Mainka, Schwenk mitigation status?

### ISSUE THREAD

**Issue by glycerine** [signalapp/Signal-iOS#2962]
Searching, I do not find any announcement or issue related to the recently published security flaw in the group chat new member protocol[1][2] -- has it been mitigated? Could someone please provide status update on whether/when a fix will be available.

[1] https://eprint.iacr.org/2017/713.pdf  Paul R¨osler, Christian Mainka, J¨org Schwenk  from Ruhr-University Bochum

[2] https://www.helpnetsecurity.com/2018/01/11/whatsapp-signal-group-chats/

> The problem with Signal and Threema
>Signal handles group management a bit differently. All group members are deemed administrators, and can thus add a new group member by sending an encrypted group management message to the other participants.
>
>But, as it turns out, the Signal protocol does not check whether the message was sent by an actual member of the group, meaning that anyone outside the group can send the message and, consequently, add a new user to the group.
>
>“The good news is that in Signal the attack is very difficult to execute,” Green noted. “The reason is that in order to add someone to your group, I need to know the group ID. Since the group ID is a random 128-bit number (and is never revealed to non-group-members or even the server) that pretty much blocks the attack. The main exception to this is former group members, who already know the group ID — and can now add themselves back to the group with impunity.”

...or former/current group members can provide the group id to anyone else without others approving.

**Comment by michaelkirk** [comment]
Sorry but we don't use github as a Q/A forum. 

Please visit the community forums: https://whispersystems.discoursehosting.net/
