### ISSUE TITLE
Message send success rate inconsistencies 

### ISSUE THREAD

**Issue by julianaakkh** [signalapp/Signal-iOS#2964]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal is generally very slow sending and then delivering messages. There are several frustrating repercussions that arise from this:

- 'Force quitting' an app (killing the process by swiping up in the task manager) will often mean the message will not send, and this will be without the sender's knowledge 
- A message will often get stuck on "sent" even when the app remains in the background, and only become "delivered" when the app is in the foreground.

This is a problem with Signal and not with iOS. Other communications apps such as Whatsapp, iMessage and Messenger do not suffer from similar problems. To my knowledge, neither does the Signal desktop app, and I don't know anybody who uses the Signal app for Android so I can't comment on that.

e: I'd just like to add that this is especially confusing when we remind ourselves that Whatsapp by default implements the Signal protocol for encryption and seems to handle it better than Signal does it itself, and the same could be said about Messenger's "secret" conversations that are the same.

### Steps to reproduce
- Send a message
- Close (but do not kill) the app
- The message will often be stuck on "sent"

**or**

- Send a message
- Kill the app
- The message will often not get sent at all and have to be re-sent. The sender only finds out about this after they check that specific conversation within the app again

**Actual result:** Message send success rate inconsistencies 
**Expected result:** Messages send quicker with a higher success rate.

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3b1 (should be noted this has happened since I first got Signal on iOS 9)
**Signal version:** 2.19.5 (From testflight, above warning applies here)

### Link to debug log

I cannot attach a Debug Log because I get the error "PastelogKit error 10001."

**Comment by michaelkirk** [comment]
> 'Force quitting' an app (killing the process by swiping up in the task manager) will often mean the message will not send, and this will be without the sender's knowledge

Correct - if you choose to terminate a program which is in the middle of something, that thing will not finish. There's not really anything we can do about that.

> A message will often get stuck on "sent" even when the app remains in the background, and only become "delivered" when the app is in the foreground.

When a message is marked as "sent", that means the encrypted contents of your message have been temporarily uploaded to the server, and are waiting to be fetched by the recipient's device. 

Your device being online or offline has no bearing on when it gets delivered. 

When the recipient fetches the message, your device is sent a "delivery receipt". A delivery receipt is what moves a message from "sent" to "delivered".

Normally delivery receipts will be fetched while the app is in the background. But it is possible, especially if your device goes offline, you won't *see* the message as delivered until you fire the app back up and fetch any outstanding delivery receipts.

In the future if you do send a message which takes inordinately long for the recipient to download, please get a debug log from the sender **and** the recipient and we can take a look. Until then there's not enough information here to pursue anything.

> I cannot attach a Debug Log because I get the error "PastelogKit error 10001."

Sorry for the unhelpful error message, but that generally indicates some kind of network connectivity problem.

**Comment by julianaakkh** [comment]
> Correct - if you choose to terminate a program which is in the middle of something, that thing will not finish. There's not really anything we can do about that.

I understand, my point was more that it takes a long time for messages to be sent via the Signal iOS app, more so than other messaging apps, even those using the Signal protocol such as Whatsapp. This has lead to a lot of frustration with getting my friends to move to Signal from other apps because they (along with a lot of other people) have a habit of force closing an app straight after they're done using it. This doesn't stop messages being sent on iMessage, Whatsapp, etc., which makes me think it's because Signal's messages take a while longer to send (more than other messaging apps, for some reason).

> Sorry for the unhelpful error message, but that generally indicates some kind of network connectivity problem.

That's okay, it also probably has something to do with the fact I'm on the iOS beta and PastelogKit is broken for it or something. I'll be sure to update this as soon as it works and I can attach a Debug Log.

In the meantime, thanks for your help.

**Comment by michaelkirk** [comment]
>  it also probably has something to do with the fact I'm on the iOS beta and PastelogKit is broken for it or something.

Hmm... that seems unlikely, we haven't touched PasteLogKit in a minute. If it happens again can you retry when you're sure to be on a good wifi connection? 

And thanks for being a beta tester!

**Comment by julianaakkh** [comment]
![19abc8ad-a57d-4022-87a2-acba746198d3](https://user-images.githubusercontent.com/25619071/35488313-74a0d080-047e-11e8-97a6-e3278be4ed1e.png)
![c7d12300-7e6c-41b9-9e2f-691a4c0fa71a](https://user-images.githubusercontent.com/25619071/35488314-74c873c4-047e-11e8-84dd-679457022c64.png)
Strong Wi-Fi connection and strong 4G connection, yet the problem keeps occurring🤔
