### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by dorucojocaru** [signalapp/Signal-iOS#2967]
I went step by step through the BUILDING.md file, but when I try to build, it fails with error : 
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)

![screen shot 2018-01-30 at 15 16 04](https://user-images.githubusercontent.com/30687142/35568150-8beeca50-05d0-11e8-8ef3-a443e2831921.png)
I tried cleaning the project, reinstalling the pods. 
Any advice will be helpful.

**Comment by michaelkirk** [comment]
Please file a bug with Apple about this.

As for a work around, you might try:

- closing xcode
- deleting your derived data directory
- relaunching xcode
- building

**Comment by charlesmchen** [comment]
@michaelkirk @dorucojocaru 

I've already filed a radar with Apple.

If you get segmentation faults while compiling NSDate+OWS:

* Close all workspaces (or quite XCode).
* Delete derived data folder `rm -rf ~/Library/Developer/Xcode/DerivedData/` (be careful doing this).
* Reopen XCode and rebuild.

**Comment by dorucojocaru** [comment]
@charlesmchen Thanks, it worked!
