### ISSUE TITLE
Signal cannot connect when using LTE + VPN

### ISSUE THREAD

**Issue by ultima-forsan** [signalapp/Signal-iOS#2968]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When using LTE and VPN on iphone, the connection to network cannot be completed and will hang in "Connecting".

### Steps to reproduce
- Make sure iphone network is on LTE only(No Wifi).
- Connect VPN to a server. I was connected to a server within my country.
- Notice Signal cannot connect to network.

**Actual result:** Signal cannot connect when using a combination of LTE + VPN.

**Expected result:** Signal should be able to connect when using LTE + VPN.

**Note:** I am using Fido(Rogers Canada) Carrier and NordVPN as VPN. While I am not connected to network, I still receive new Signal notifications **New message!**

### Device info
**Device**: iPhone 6+
**iOS version**: 11.2.2 (15C202)
**Signal version:** 2.19.5.0

### Link to debug log
https://gist.github.com/f69dcb2a5bb2d1a5163b33e601353159

**Comment by macuser666** [comment]
hi
I'm using Signal with an IKEv2 vpn and Signal works just fine
Note: i'm using https://github.com/trailofbits/algo as a VPN on Digital Ocean

**Comment by caveman1973** [comment]
Mine works just fine.

**Comment by caveman1973** [comment]
I use OpenVPN app btw

**Comment by michaelkirk** [comment]
@ultima-forsan  please follow up with support@signal.org if you continue to have issues.
