### ISSUE TITLE
Can't remove person from group

### ISSUE THREAD

**Issue by ledude1** [signalapp/Signal-iOS#2979]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I can't remove user who used to be part of a group and no longer registered with Signal because that user change to a new number.  I know Signal doesn't support this feature but perhaps you guys should start thinking about it.  The issue is not just because it's annoying to see that user is still part of the group.  The most annoying part is that Signal now shows "Some recipients failed" error because it tried to deliver the message to a member that doesn't exist anymore.

 ### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

Doesn't matter.

**Comment by leonardoporpora** [comment]
this is not a bug. it's how signal works and it's for security reasons that u don't have this feature

**Comment by jongleur1983** [comment]
I agree with @leonardoporpora that this is not a bug, but IMHO it's a seriously missing feature for groups in general.
And I don't understand the claim, "it's for security reasons" - I'd be happy if anybody could elaborate on that or provide more info as a link or similar.

I know of at least one company that thought about using Signal for team communications as a replacement for another messenger solution that must be abandoned for legal reasons (pricacy violations).
Lacking the possibility to force-remove someone from a group (e.g. a coworker that lost the company) was a killer criterion against it (without a proper alternative left, yet).

I'm not sure if this is the best issue describing the problem - at least it's platform independent, but I'd like to follow the topic if possible (so I'm happy to get a hint what other issues to follow).

**Comment by CHEF-KOCH** [comment]
2 years later, going to bump it. 

**Bump**

**Comment by Elschnuppero** [comment]
Wow... i was a huge fan of signal, but this makes the group feature completely unusable

**Comment by AbelLykens** [comment]
Please stop with these comments. Groups work as advertized. All users are equal, so no admins whom can kick others. If you want this feature, look at #4311 for example. Comments like "completely unusable" make no sense. They are usable just fine. The fact you want the app to do something different is a separate discussion.

**Comment by fareszr** [comment]
i don't know how they didn't fix this a long time ago
this an essential feature for a chat app

**Comment by Mihahn** [comment]
This can be closed with the introduction of groups v2 I guess.
