### ISSUE TITLE
When trying to update app getting "Error setting PRAGMA journal_mode"

### ISSUE THREAD

**Issue by mafatah** [signalapp/Signal-iOS#2990]
I have searched open and closed issues for duplicates

### Bug description

The issue happen when i try to update to latest code , i got "Error setting PRAGMA journal_mode: 26 file is not a database"  in beginning of app and app not opening always . i try to get back to previous commit and found issue in commit  "DatabaseConversion" while previous commit working perfect which is "Fix-timer-offset" with my current database .

Mainly it happened in this line which return status error code "26" 

	status = sqlite3_exec(db, "PRAGMA journal_mode = WAL;", NULL, NULL, NULL);
	if (status != SQLITE_OK)
	{
		YDBLogError(@"Error setting PRAGMA journal_mode: %d %s", status, sqlite3_errmsg(db));
		return NO;
	}

### Steps to reproduce

- Checkout "Merge branch 'mkirk/fix-timer-offset'"
- Run app and initate a chat with any user
- Update to "Merge branch 'charlesmchen/databaseConversion'"
- Run again , app will crash in opening

**Actual result:** App crash in opening
**Expected result:** App load database and open normal

### Device info
**Device**: Iphone 7plus
**iOS version**: 11.2.2
**Signal version:** 2.20.0

### Link to debug log

https://gist.github.com/mafatah/ca4f72c92e29c435137a7a0c2ec1ecea

**Comment by michaelkirk** [comment]
There are a lot of database changes in this (not yet stable) release, and I would not be at all surprised if updating between arbitrary unreleased commits on master left your device in a bad state.

That said, if you can reproduce this crash by installing and successfully registering on a pre-2.20 tag, then updating to the head of master, that would be helpful information.

To clarify, are you saying this device can still run Signal without crashing on:
fcb9c2e64 - Merge branch 'mkirk/fix-timer-offset'

**Comment by mafatah** [comment]
Issue not reproduced when i registering on a pre-2.20 tag , then updating to master , app work good without any crash .

Also app can run successfully on fcb9c2e - Merge branch 'mkirk/fix-timer-offset' , if i update to "Merge branch 'charlesmchen/databaseConversion'" , app got crash  at the line:

status = sqlite3_exec(db, "PRAGMA journal_mode = WAL;", NULL, NULL, NULL);

with status 26

**Comment by michaelkirk** [comment]
It sounds like you were running HEAD of master at some unreleased state, and we'd subsequently changed the DB migration in a way that doesn't allow you to gracefully update from the unreleased version you were running.

Unfortunately that is not something we can support. You should not be installing HEAD of master on a device unless you're comfortable losing everything on that device. 

For devices that need stability, please stick with app store releases.

If I've misunderstood, and you can reproduce this crash by upgrading from an appstore release, please re-open.
