### ISSUE TITLE
Signal plays Pixel 3 voice messages incorrectly / too fast

### ISSUE THREAD

**Issue by elya5** [signalapp/Signal-iOS#3029]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Voice messages sent from an Android device are not played correctly by Signal on iOS. It's not possible to understand them (or just barely).  Sending voice messages to other Android devices works as intended.

### Steps to reproduce
- Send voice message from Android to iOS device.
- Listen to message on iOS device.

**Actual result:** Voice message does not play correctly
**Expected result:** The audio of the message should sound the same on iOS and Android.

### Device info

**Device**: Reproducible with an iPhone SE and an iPhone 8.
**iOS version**: iOS 11

### Link to debug log
https://gist.github.com/anonymous/0cdb528b799353cbae6eff19d2781849

**Comment by haffenloher** [comment]
Here's a demo file provided by a forum user: [signal-2018-10-26-110156.zip](https://github.com/signalapp/Signal-iOS/files/2522320/signal-2018-10-26-110156.zip)

They say it was created on a Pixel 3 running Signal 4.29.7. The sped-up playback happens on an iPhone 6 running iOS 12. For more details see the [forum thread](https://community.signalusers.org/t/voice-messages-received-from-android-are-rapidly-sped-up/4559).

**Comment by Johni-M** [comment]
I encountered the same issue.
Voice message sent from Google Pixel 3 to iPhone 6s. Audio Playback on iOS is too fast.
If I play the voice message on Windows Desktop, it sounds correct but the displayed Duration is too short. (by about factor 3)

**Comment by chakalakasp** [comment]
This is still ongoing, I am getting this issue from a Pixel 3A user playing on iOS.  It renders non-realtime voice communications very difficult.  Are the devs not interested in fixing this?

**Comment by Leightonius** [comment]
Having this issue now as well. Sending voice messages from Galaxy S21 with Android 12 and Signal 5.26.11 to an iOS device and the message is playing at 2x speed on iOS.

**Comment by Mlrt55** [comment]
Same issue as well with a Galaxy S21(exynos) since Android 12 and Signal 5.26.11 to an iOS device and the message is playing at 2x speed on iOS.

**Comment by glitchwizard** [comment]
I'm having this same issue with a samsung galaxy s21 ultra 5g

**Comment by stephenvsawyer** [comment]
Same issue still happening… User on latest version of Signal on a Samsung Galaxy S21 sends voice memo to myself on iPhone 12 Pro Max and it’s double speed. No way for either of us to correct the issue on our ends. Started happening a couple of weeks ago, potentially after an Android update? Not sure

**Comment by om-hb** [comment]
Same here, just switched to a Samsung Galaxy S21 (Exynos) and now contacts that are using iPhones are hearing my voice messages too fast. On my phone, messages sound correct, but the displayed duration is wrong.

**Comment by macomonaco** [comment]
I have the same issue: 

Samsung device on the one side. iPhone was the latest iOS 15.2 and latest signal version on the other side. Play back of voice messages on the iPhone is in double speed since few weeks. 

I’m not aware of any setting or work around to prevent this issue.

**Comment by zueskin** [comment]
same issue

samsung s21 ultra to iphone 13 max results in message playing double speed
