### ISSUE TITLE
Friend unable to read messages that I send in iOS app.  I can read hers

### ISSUE THREAD

**Issue by Orangebl00d** [signalapp/Signal-iOS#3038]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

_I can see messages in chat from a friend but he can't see my messages._  Both of us have deleted, reinstalled Signal app and reverified multiple times.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

_Sending phone: iPhone Version: iPhone10,5, iOS Version: 11.2.5
Receiving phone(can't send): iPhone Version: iPhone9,3, iOS Version: 11.2.5_

### Link to debug log

_This is debug log from my phone , which can read but not send: https://gist.github.com/anonymous/cd385e682212fa783b3baed320f66a3a

Debug log from phone that can send but not read:
https://gist.github.com/anonymous/ea0af7bc337d67314f2422b6fbe467b2_

**Comment by michaelkirk** [comment]
The log that’s having trouble sending is filled with lines like:

2018/02/20 10:48:24:541 Websocket did fail with error: Error Domain=SRWebSocketErrorDomain Code=2132 "Proxy Error" UserInfo={NSLocalizedDescription=Proxy Error, HTTPResponseStatusCode=500}

It looks like the sender is in some kind of restricted network.

**Comment by Orangebl00d** [comment]
Thanks Michael.  

That bug log with the websocket errors is from the device that is sending me messages, which I can read.  That device can not read the messages I'm sending.

This error is occurring both when away from home using data and when on home wifi.

Is this possible evidence of hacking and/or surveillance?

**Comment by michaelkirk** [comment]
> That bug log with the websocket errors is from the device that is sending me messages, which I can read. That device can not read the messages I'm sending.

Sorry - you're right,  I jumbled my words. But my point remains, it is the web socket which is responsible for fetching messages, and it is not able to connect to the Signal Service.

From what I've seen, there is no indication that you're having any trouble uploading the messages.

Please have the intended recipient follow up with support@signal.org, which is a better venue for user support.
