### ISSUE TITLE
Signal hangs when attaching image from camera roll (iPhone)

### ISSUE THREAD

**Issue by peterkahl** [signalapp/Signal-iOS#3049]
I already contacted you about this and now attaching the debug log.

**Comment by michaelkirk** [comment]
@peterkahl - we fixed an issue that could cause signal to freeze when sharing a photo in 2.20.1. 

Please update to the latest and try again.

If this is still an issue please reopen, attach an up to date debug log, and send along any crash reports you can find. 

How to submit crash report:
https://support.signal.org/hc/en-us/articles/229676507-How-do-I-submit-an-iOS-debug-log-or-crash-report-
