### ISSUE TITLE
App frozen

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3061]
It’s impossible to use signal in my phone ios 11.2.6 it stucks every thing I do. Example I want to send a photo and signal is blocked and it blocks sometimes even go read messages

**Comment by leonardoporpora** [comment]
https://gist.github.com/ae2925306d682862841c3eeef112e055

**Comment by michaelkirk** [comment]
I’m sorry that Signal isn’t working for you and I appreciate that you are filing issues to try to get things fixed, but you have repeatedly filed issues without filling out the template and instead include vague inactionable statements.

Saying that “everything” causes Signal to freeze is pretty hard to act on. Furthermore your log is filled with activity. So it’s not “everything”.

I can’t reproduce what you are describing, but I do believe that something is wrong and I do want to fix it. We just need actionable information.

So please, in the future do not file a bug report unless you fill out the issue template. Include step by step instructions of what you are doing - describe every tap in the app and every screen that you see which leads up to the issue, and then clarify how often you see the issue.

For example:

Launch Signal
Go to thread with Alice
Tap paperclip
Choose “media library”
Select a photo
See it uploading and send to Alice
As soon as it’s uploaded the app freezes indefinitely.
This happens intermittently, maybe 25% of the time.
It happens the same way regardless of who I’m messaging.
Once frozen, I can’t do anything in Signal at that point unless I force kill and relaunch it.

Does that describe your issue? 

Always include steps like that in your report.
It give us a foothold into solving the issue, and will help you help us to make Signal work better.

**Comment by leonardoporpora** [comment]
I’m pleasured to help signal. I use only signal I don’t have WhatsApp because I believe in privacy and security and Signal it’s the only app that provides it. 
Let’s go on with the issue: 
1 open signal 
2 send photo a
3 send photo b 
4 send photo c 
5 send photo d when I send as in this example 4 photos quickly usb sequence the app freezes. 

Another issue:
When I unlock the phone from the lock screen swiping on the signal notification the app freeze. 
![8c2b9fe6-7555-4f4e-8ec0-3c08dd065c23](https://user-images.githubusercontent.com/34192761/36631688-e59e5844-197c-11e8-959a-9061e30d7fc4.png)

Another issue sometime the app freeze when I switch btw more contacts quickly this isn’t what happen
![a5c12018-2224-4284-9a2f-79b9843cb7de](https://user-images.githubusercontent.com/34192761/36631680-c750ddda-197c-11e8-8492-74983cb8b72a.png)

**Comment by leonardoporpora** [comment]
I have also sent u a debug log

**Comment by leonardoporpora** [comment]
Let me know if you need more infos @michaelkirk

**Comment by leonardoporpora** [comment]
guys have you found anything? @moxie0 @charlesmchen @michaelkirk @caldwell

**Comment by michaelkirk** [comment]
@leonardoporpora please don't bump issues.

**Comment by EvanHahn-Signal** [comment]
Closing this issue as stale. Please open a new one if you're still encountering problems.
