### ISSUE TITLE
Contact Sharing - Signal not in share menu

### ISSUE THREAD

**Issue by HenkiedeHenkie** [signalapp/Signal-iOS#3062]
I absolutely love it that I'm now able to share things using the SAE. However, one app I use often is Keeply, to securely store my photos behind a password. However, when I want to share a picture from this app with Signal, Signal doesn't show up in the share menu. Not even when I edit the share menu. Maybe this is an iOS issue or an issue on Keeply's end, but is there an explanation for this behaviour?

**Comment by jlund** [comment]
Thanks for the bug report. We are keeping track of these edge cases and we'll continue making improvements to the new share extension to support additional content types.

**Comment by stillalex** [comment]
Not sure if this is the right place for this, but I also have 2 apps I'm using that are missing the share integration: 'Apple Music' and 'Brave Browser'.  (I'm on Signal Beta 2.20.0.42)
@jlund should I create separate issues, or is mentioning them here enough?

**Comment by jlund** [comment]
Mentioning them here is enough. Thanks for letting us know!

We are also aware of this issue in Reddit and Tweetbot.

**Comment by NinebitX** [comment]
Signal does not show up as an option in Firefox's share menu.

### Steps to reproduce

1. Open website in Firefox
2. Tap on three dots in upper right hand corner
3. Tap on "Share Page With..." 
4. Swipe to the right and select "More"

**Actual result:** Signal is not listed as an option
**Expected result:** Signal is listed as an option

### Device info

iOS 11.2.6
Signal 2.20.0
Firefox 10.6

**Comment by HenkiedeHenkie** [comment]
I'm curious what the underlying issue is here. Guess that this behaviour isn't app specific, but that there must be an underlying issue... Don't know about the diversity of classes that iOS uses in the SAE, but is it as easy as programming the app to use the underlying classes or must this be done a kind of app to app basis?

**Comment by jlund** [comment]
There was a bug in our handling of apps that share URLs when text is also present. We'll have a hotfix available soon.

**Comment by NinebitX** [comment]
I updated to Signal v2.20.2. Signal is now listed as an option in Firefox, Podcasts, Notes, Maps, App Store, and Google Maps. 🎉

Signal is still not listed as an option in Contacts (to share a contact).

**Comment by stillalex** [comment]
Can confirm it works on Apple Music and Brave Browser.
Thanks a lot!

**Comment by jlund** [comment]
Contact sharing is on the roadmap. Thanks for confirming that the fix is working!

**Comment by michaelkirk** [comment]
Thanks for the organized report @NinebitX. I'm going to rename this issue to highlight that the remaining work is about contact sharing.

**Comment by NinebitX** [comment]
Contact sharing is now available in version 2.27.1. 👍
