### ISSUE TITLE
Cannot send photo after update

### ISSUE THREAD

**Issue by iadmir** [signalapp/Signal-iOS#3069]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I just update Signal to 2.20.0 (stable version from App Store) and cannot send any picture from library, it’s failed.

### Device info

**Device**: iPhone SE
**iOS version**: 11.2.6
**Signal version:** 2.20.0

**Comment by michaelkirk** [comment]
To clarify, how are you trying to send photos?

Is it:

Open signal
Go to conversation
Tap paperclip
choose "Media Library"

Or is it:

Open photos app
tap photo
tap share
tap signal

And what do you mean by "it's failed"?

Do you see an error?
Does the app freeze?
Does the app crash?

**Comment by iadmir** [comment]
Open signal
Go to conversation
Tap paperclip
choose "Media Library"

Sending failed every time immediately after tapping send button.

### Screenshot
![img_1108](https://user-images.githubusercontent.com/23726384/36745420-b562940e-1bef-11e8-867e-fa0d94db1315.PNG)

**Comment by michaelkirk** [comment]
Could you tap the message to show the "retry" dialog and take a screenshot?
Could you also submit a debug log immediately after failure?

Just checking - can you still send *non* attachment messages?

**Comment by iadmir** [comment]
###Screenshot
![d3ac998f-f6f3-4d4b-86c9-d1d42a4aba52](https://user-images.githubusercontent.com/23726384/36750088-eceea5c2-1bfc-11e8-8998-19c9149a23fd.jpeg)

###Link to debug log
https://gist.github.com/62be55756ef368caef6e7b2dcba505b8

I just notice also can’t send text messages - same issue.
Need reinstall?

**Comment by iadmir** [comment]
Working after reinstall.

**Comment by michaelkirk** [comment]
Huh, that error indicates that your client became deauthed,

Your last successful server auth was here: 

```
2018/02/26 12:49:08:431  Succesfully sent sync transcript.
```

Did you use the same phone number to register on another device after that?

**Comment by iadmir** [comment]
Strange, I didn’t use the same phone number to register on another device after that.
