### ISSUE TITLE
Pin messages to protect them from disappearing

### ISSUE THREAD

**Issue by FiloSottile** [signalapp/Signal-iOS#3071]
This is a feature request.

It would be nice to be able to pin individual messages to protect them from disappearing, instead of having to screenshot or copy-paste them.

WhatsApp has a vague analogue with "Clear all except Starred messages".

**Comment by MPlunk** [comment]
I am really surprised about some suggestions here. Signal should be the messenger for people, who really care about privacy and security. Not for everyone.
When I send a disappearing message, let us say with timer set to 5 minutes, then I might (as sender!) have reasons for that. I do not want to stay THIS message longer on the phone of the recipient.
Normally, iOS should offer a feature, that prevents screenshots, when an app asks to do so. Unfortunately this is not possible.
People who want Signal work like other messengers, like whatsapp, should really think about, why they dont use whatsapp then.

**Comment by FiloSottile** [comment]
Please, let's not rediscuss this. As long as text can be copy pasted or a camera can be pointed at a screen, the point of disappearing messages is not self-destruction guarantee, but a shared policy on no log retention.

Anything that makes them more useable is a security win.

**Comment by Volfinger** [comment]
This might be your very personal opinion , which does not mean , that it makes any sense. 

The problem with your argument is , that you can use this to argue against nearly every security feature. For example , Signal does not offer backups for iTunes or iCloud.
Someone suggested here the other day , that Signal for iOS should have a feature to export chats in plain text to an email. This feature does not exist for the same reason , for security reasons.
Now , you could say: come on , someone could copy & paste the whole chat to an email anyways. Or get a camera , make a photo of a chat and attach it to an email. So let us export chats. And with this logic , you can reduce security step by step.

The simple point is , that disappearing messages make only sense , if the sender can trust , that they really disappear after the given time. If you cannot trust in that , there is no point left at all to use it.
Of course you can always copy text , or even typewrite it , but that would not prove anything.

**Comment by michaelkirk** [comment]
We only use Github to report issues and feature requests, not to discuss them (otherwise there's a ton of traffic for our subscribers). 

Please take further discussion on this to the community forums: https://community.signalusers.org/

**Comment by EvanHahn-Signal** [comment]
For this feature specifically, we may not want to implement this. If I send you a disappearing message, I expect it to disappear. With this, it wouldn't. (There are arguments against this, but I still think it might confuse users.)

As was mentioned, we'd like to use GitHub for bug reports, not feature requests. Please use [this community forum thread][0] to discuss a "starred message" feature further, and the community forums to discuss other feature requests in general.

[0]: https://community.signalusers.org/t/bookmarks-favorites-starred-messages/6004
