### ISSUE TITLE
Increase screen message density

### ISSUE THREAD

**Issue by FiloSottile** [signalapp/Signal-iOS#3072]
With the keyboard open and particularly with disappearing messages enabled, there can be as low as 4-5 lines of text of 3-5 words each displayed on screen split over 3 messages.

I realized this even makes me not want to enable disappearing messages, not to reduce screen real estate.

**Comment by MacLemon** [comment]
Maybe increase the density when the keyboard is up, occupying half the screen, but keep a more reading friendly layout when there is no on-screen keyboard?

**Comment by djc2** [comment]
This can go either way. Some people have sight issues and want to be able to read bigger text.
