### ISSUE TITLE
Give an option to hide contact pictures

### ISSUE THREAD

**Issue by MartaKl** [signalapp/Signal-iOS#3079]
Most messengers (for example WhatsApp) show contact pictures in the chat list. Some people like it, some do not. Especially it is annoying, when you have, let's say, 10 contacts, and 9 do not show a picture. You see then a chat with Max Meyers (and seeing the name, I know who it is), and before a big MM.
iMessage, for example, gives you a chance to hide the contact pictures; as an option. 

I think, Signal should do the same. Just give a new option in the settings "Hide contact pictures", so those, who do not like it, can activate it and just see "Max Meyers" in the chat list, instead of MM  Max Meyers. Should be pretty easy to implement.

**Comment by caveman1973** [comment]
You can go to your contact list and add an picture. Very useful since YOU choose them. 

I would like to add an option. To show the picture in the chat window also.
