### ISSUE TITLE
The contact pictures are not displayed

### ISSUE THREAD

**Issue by Healler3108** [signalapp/Signal-iOS#3084]
### Bug description
The contact pictures are not displayed in Signal's contact list on iOS, only those that are assigned in Contacts on iPhone are visible. On Desktop version for Mac all works fine.

### Screenshots
![764573678534675](https://user-images.githubusercontent.com/36985457/36891768-bf3ab7b0-1e13-11e8-9b7e-b7ff0430db76.png)
<img width="968" alt="85426568568" src="https://user-images.githubusercontent.com/36985457/36891769-bf5fd9be-1e13-11e8-86d5-1c8f30a03ea2.png">

### Device info

**Device**: iPhone 8 Plus
**iOS version**: 11.2.6
**Signal version:** 2.20.2.2

### Link to debug log
https://gist.github.com/anonymous/9cf8c7e217b9d23bdc59f596d9a82756

**Comment by michaelkirk** [comment]
This has been fixed for 2.21, which will be in beta soon. 

If you'd like to test it, and are comfortable running beta software, email suppot@signal.org with the subject "Sign me up for the Signal iOS beta".

Keep in mind that beta software is less stable, meaning it's more prone to crashes and data loss.

**Comment by michaelkirk** [comment]
If you enter the conversation with the users who are missing avatars and exchange messages, is this still an issue with the latest release?
