### ISSUE TITLE
Voice message is displayed longer than they really is

### ISSUE THREAD

**Issue by SigTestingTeam** [signalapp/Signal-iOS#3086]
- [ X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
A few voice messages are displayed shorter than they really are.

### Steps to reproduce
- ?

### Screenshots
![signal-2018-03-02-200944](https://user-images.githubusercontent.com/36992888/36917634-a5e141aa-1e57-11e8-8720-118bd056ce35.png)

### Device info
**Device**: iPhone 6
**iOS version**: 11.2.6 (15D100)
**Signal version:** 2.20.2.2

**Comment by ftlno** [comment]
I'll take a look at it

**Comment by leonardoporpora** [comment]
@michaelkirk can you say me the file where the error should be and I will take a look at it because this bug is pretty annoying

**Comment by SignalTestingTeam** [comment]
Any news about the time problem?
Do you have looked on it?
