### ISSUE TITLE
Latest testflight update changed the new message notification sound. Please give me back the sound I'm used to.

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3102]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Latest testflight update changed the new message notification sound.
Please give me back the sound I'm used to.

### Steps to reproduce
- update to latest testflight
- receive a message

**Actual result:** I hear a different sound, like Whatsapp. I can't tell without looking at the phone which app has given the notification.
**Expected result:** Play the old sound that I got used to so I can know what app (in this case, Signal) has emitted the notification. 

### Device info

**Device**: iDevice SE
**iOS version**: 10.2
**Signal version:** 2.21.0.5

**Comment by michaelkirk** [comment]
Did you see the upgrade splash advertising the new sounds?

FYI: You can change back to the "classic" notification sound in Settings > Notification > Sound

**Comment by michaelkirk** [comment]
Based on beta feedback, we've decided to leave legacy users with their existing sounds rather than migrating them to the new default.

New users / reinstalls will use the new defaults. And anyone can pick the sound they prefer in Signal > Settings > Notifications > Sound (or configure it per thread)

Thanks for the feedback!

**Comment by mailinglists35** [comment]
> Did you see the upgrade splash advertising the new sounds?

Yes I did, but I couldn't care about it, it was a screen that prevented me to reach my goal, which was to send a message **NOW**. I immediately dismissed the prompt.

> we've decided to leave legacy users with their existing sounds

Thank you!

**Comment by mailinglists35** [comment]
holy cow, you also changed the ringtone!

Please, for heavens' sake, bring back the classic ringtone, too.
It was really really cute and I got used to it.

**Comment by mailinglists35** [comment]
@michaelkirk is there a chance you can restore the classic ringtone, too?
