### ISSUE TITLE
Answering from home window on iphone turns off disappearing messages

### ISSUE THREAD

**Issue by daz10000** [signalapp/Signal-iOS#3104]
- [ X] I have searched open and closed issues for duplicates

This is similar to #2284 but that issue is closed.  I added a comment last October that it is still occurring but filing a new bug report now to reflect that it is still present in current version 2.20.2

----------------------------------------

### Bug description
Messages that pop up on home page of iphone while phone is locked can be answered with a short-cut.   If a thread has disappearing messages set to one day is answered in such a fashion,   signal quietly disables disappearing messages.  It will be apparent to other people on the thread (they will see that X has disabled disappearing messages), but the person who answered that way will not realize till they notice that the status has changed.

### Steps to reproduce
- set up a thread (I've seen this on 2 way chats and multi way)
- set disappearing messages to 1 day
- have user Y send a message to user X (with an ios phone that is locked)
- have user X reply from the home screen with the answer option and send a short reply
- user Y should receive a message that X has disabled disappearing messages

One small detail I discovered reproducing this.  It depends exactly on which way you reply from the home screen.  If you first ask iphone to show the message, then select reply didn't happen, but in a different context where message popped onto home screen I was able to reply as a menu option without the intermediate step and that disabled the disappearing messages immediately.  I'm not sure if the distinction is clear but the exact method of replying from home screen might be important.  If definitely disabled immediate on my reply.

**Actual result:** 
on a multi way thread, users are frequently and accidentally disabling disappearing messages.  It can be reinstated but every reply from the lock screen will redisable

**Expected result:** 

Reply from home screen does not change disappearing message status.

### Screenshots
This is the message appearing on the desktop client after same user replied from ios lock screen,
![disappearing messages](https://user-images.githubusercontent.com/6342645/36997713-64a1a8b4-206f-11e8-974c-73a8727abd4e.png)

### Device info
**Device**: iPhone 6
**iOS version**:  11.2.6
**Signal version:** 2.20.2

### Link to debug log

https://gist.github.com/aa7f9d0dd50be1e03e7067aa554a9939

**Comment by daz10000** [comment]
Have just reproduced it 4 or 5 times.  Not sure if how you reply matters.   All reproductions were iOS phone talking with a remote windows client (and a second windows client running on same account as iOS device replying and causing the issue).

**Comment by daz10000** [comment]
One more clarification for the screenshot above,  You set the timer to off is result of the bug and next message is me manually restoring the timer.

**Comment by michaelkirk** [comment]
@daz10000 - Thanks for the report. I haven't been able to reproduce this behavior following your steps.

One thing I noticed - your screenshot seems to be from Signal-Desktop. Is that part of the reproduction? Do you only see disappearing messages as disabled on Desktop, or do you see it disabled on both at the same time?

Are both users X and Y on Signal-iOS?

Is the attached log from user X or user Y?

At one time in the log did the disappearing messages become inadvertently disabled?

**Comment by daz10000** [comment]
There is definitely some subtlety to this.  While I was testing, it seemed to not occur on a separate thread.   The specific configuration I was using to test was user X on iOS, latest version of everything triggering the problem.  The recipient Y was on a windows machine with the desktop version of signal.  User X was also logged in from the desktop version and it was here that the message in the screenshot shown above was seen / captured.    I will try to reproduce again and see if it messages are disabled on the iOS client as well.  We are in different time zones so might take 24 hours :(   Attached log file is for user X on the iOS device.   In terms of time,  I didn't log the precise time but it happened exactly as the iOS client replied to the thread.

**Comment by M09NST3R** [comment]
I've not observed this, yet, is this still an open issue that we should be aware of?

Any guidance on how to replicate it these days?
