### ISSUE TITLE
Some profile images are not showing after upgrading to 2.20

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-iOS#3108]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Some profile images are not showing after upgrading to 2.20.x from 2.19.x. They were showing before update, and they are showing also after fresh linking to signal desktop (after removing all data, and verified from logs that it downloads profile pictures from cdn.signal.org.)

Doen not help when such contact changes profile picture, new picture is showing correctly on signal desktop, but signal ios is not showing any profile picture.

### Steps to reproduce
- use signal iOS 2.19.x with contacts that have profile picture
- upgrade to 2.20.x and observe that some profile pictures are not showing anymore

### Device info

**Device**: iPhone SE
**iOS version**: 11.2.6
**Signal version:** 2.20.2.2

### Link to debug log
2018/03/06 17:49:57:348  [ProfileFetcherJob] getProfile: [ REDACTED_PHONE_NUMBER:xxx114 ]
2018/03/06 17:49:57:352  [TSNetworkManager] Making request: <OWSGetProfileRequest: 0x1c043bf20> { URL: v1/profile/[ REDACTED_PHONE_NUMBER:xxx114 ] }
2018/03/06 17:49:57:357  [ProfileFetcherJob] getProfile: [ REDACTED_PHONE_NUMBER:xxx967 ]
2018/03/06 17:49:57:360  [TSNetworkManager] Making request: <OWSGetProfileRequest: 0x1c44292a0> { URL: v1/profile/[ REDACTED_PHONE_NUMBER:xxx967 ] }
2018/03/06 17:49:57:363  [ProfileFetcherJob] getProfile: [ REDACTED_PHONE_NUMBER:xxx887 ]
2018/03/06 17:49:57:364  [TSNetworkManager] Making request: <OWSGetProfileRequest: 0x1c062dc20> { URL: v1/profile/[ REDACTED_PHONE_NUMBER:xxx887 ] }
2018/03/06 17:49:57:366  [ProfileFetcherJob] skipping updateProfile: [ REDACTED_PHONE_NUMBER:xxx084 ], lastTimeInterval: 28.3913509845734
2018/03/06 17:49:58:030  [TSNetworkManager] request succeeded : <OWSGetProfileRequest: 0x1c062dc20> { URL: v1/profile/[ REDACTED_PHONE_NUMBER:xxx887 ] }
2018/03/06 17:49:58:046  [TSNetworkManager] request succeeded : <OWSGetProfileRequest: 0x1c043bf20> { URL: v1/profile/[ REDACTED_PHONE_NUMBER:xxx114 ] }
2018/03/06 17:49:58:071  [TSNetworkManager] request succeeded : <OWSGetProfileRequest: 0x1c44292a0> { URL: v1/profile/[ REDACTED_PHONE_NUMBER:xxx967 ] }
2018/03/06 17:50:06:305  [ConversationViewController] extendRangeToIncludeUnobservedItems: 0
2018/03/06 17:50:06:316  [ConversationViewController] hasAddedNewItems: 0
2018/03/06 17:50:06:954  [ProfileFetcherJob] skipping updateProfile: [ REDACTED_PHONE_NUMBER:xxx084 ], lastTimeInterval: 37.9976379871368
2018/03/06 17:50:06:955  [ProfileFetcherJob] skipping updateProfile: [ REDACTED_PHONE_NUMBER:xxx114 ], lastTimeInterval: 9.60577094554901
2018/03/06 17:50:06:955  [ProfileFetcherJob] skipping updateProfile: [ REDACTED_PHONE_NUMBER:xxx967 ], lastTimeInterval: 9.5964549779892
2018/03/06 17:50:06:955  [ProfileFetcherJob] skipping updateProfile: [ REDACTED_PHONE_NUMBER:xxx887 ], lastTimeInterval: 9.591029047966

**Comment by michaelkirk** [comment]
Thanks for the report. This is fixed in the 2.21 beta. 

Interested in trying it? Contact support@signal.org with the subject "Sign me up for the Signal-iOS beta"

Keep in mind, as beta software, it's less stable, meaning you're more likely to experience crashes or lost data.
