### ISSUE TITLE
dropped audio calls without reason; "submit debug log" gives error. Log included

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3115]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
dropped audio call without reason

### Steps to reproduce
- phone in low power mode
- called someone that is on android
- put on speaker
- press home button
- use assistive touch button - lock device

**Actual result:** I talk and hear for few seconds after I lock the device then call is dropped (screenshot attached).
Attempting to use native "submit debug log" gives error (screenshot attached).
Encrypted log extracted from device and pasted and available for download for the next 30 days from https://defuse.ca/b/9JiWAOp7 email me the Signal number to tell you the password for it at  <this github id that I am using> at gmail dot com. 
**Expected result:** keep talking and hearing

### Device info

**Device**: iDevice SE
**iOS version**: 10.2
**Signal version:** 2.21.0.6

**Comment by mailinglists35** [comment]
![asset 1](https://user-images.githubusercontent.com/2054302/37059937-70a277fa-2197-11e8-9613-cbc12bb43a47.PNG)
![asset 2](https://user-images.githubusercontent.com/2054302/37059938-70f95d0e-2197-11e8-959b-55848f408366.PNG)

**Comment by michaelkirk** [comment]
Thanks for the high quality report!

Sorry, debug log submissions was fixed with the latest beta https://github.com/signalapp/Signal-iOS/pull/3114.

But I was able to reproduce your issue regardless, so getting me the contents of your log shouldn't be necessary.
