### ISSUE TITLE
Signal not opening at all any more since last update.

### ISSUE THREAD

**Issue by dslibby** [signalapp/Signal-iOS#3126]
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by michaelkirk-signal** [comment]
Could you follow up by sending a crash log to support@signal.org and reference the URL of this GH issue?

https://support.signal.org/hc/en-us/articles/229676507-How-do-I-submit-an-iOS-debug-log-or-crash-report-

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
