### ISSUE TITLE
iOS Signal doesn't stop updating database for several days.

### ISSUE THREAD

**Issue by PedAlh** [signalapp/Signal-iOS#3131]
- [x ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

My Signal app for iOS 9.3.5, on iPhone 4S, keeps saying:
"Updating Database
This can take a few minutes."

It has been like that for several days. It has been an entire day updating... and nothing changed. And today it's still telling the same. I wouldn't like to lose all messages inside the my app.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone 4S
**iOS version**: 9.3.5
**Signal version:**2.21.0

**Comment by michaelkirk-signal** [comment]
Do you see any crashes reported? https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports#to-submit-your-crash-report

**Comment by michaelkirk-signal** [comment]
This was fixed in a recent release. Are you still experiencing issues?

**Comment by michaelkirk-signal** [comment]
Please reopen if you're still experiencing this behavior.
