### ISSUE TITLE
Buggy Giphy integration

### ISSUE THREAD

**Issue by HenkiedeHenkie** [signalapp/Signal-iOS#3132]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I experience the use of Giphy in a chat as really unstable. Most of the times, it shows an error that nothing can be found. Sometimes I have to turn off Wifi, disable and re-enable Signal's permissions and force quit the app several times to even get it to show results for my search. 

### Steps to reproduce
- Add a Gif using the extension menu in iOS
- Search for something

**Actual result:** Very buggy behaviour, but most of the times it doesn't work.

**Expected result:** Should work just fine

### Device info

**Device**: iPhone 5s
**iOS version**: 11.2.6
**Signal version:** 2.21.0.15

**Comment by charlesmchen** [comment]
This is an issue in the Giphy API.  We've alerted them and they're working on it.
