### ISSUE TITLE
visually group/collapse chat sessions within a chat

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3134]
I am scrolling up my chat history with a contact and I observe there is a lot we talked.

I found it difficult to find what I was looking for, so the following idea came to my mind: 

It would be much easier for me to see my chat history made up of collapsed/expandable snippets of "chat sessions". 

Feel free to call it different to avoid confusion, but that's the best term I imagined now.

I see a "session" as a series of uninrerrupted talk with someone, easily identifiable from the entire chat by having very small time differences between consecutive messages when compared to the entire conversation.

It would be useful to me to see a chat session collapsed by default, drawn like a horizontal bar from edge to edge, labeled as "start time - end time", and as we advance deeper into past, additionally labeled with "past week", "past month", "past year", and finally year name for even older sessions. 

When I tapped that bar, the session contents would be shown, but keep the bar displayed so when I tap again the bar, it would collapse back.

Thanks

**Comment by denver-s** [comment]
This feature request should belong to https://community.signalusers.org.
