### ISSUE TITLE
able to search text inside a specific chat

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3135]
similar to #3134, I find it difficult to find something I discussed in the past.

A search field would be helpful at the top of the window

thank you

**Comment by NinebitX** [comment]
Dupe of https://github.com/signalapp/Signal-iOS/issues/646

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
