### ISSUE TITLE
Message delivery 

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3136]
It’s a bit difficult to describe this issue cause is not constant, but quite often happens that I send a message and it is not delivered. After 10 minutes or more I send a message and instantly both of the messages get delivered.

**Comment by michaelkirk-signal** [comment]
This can happen for normal reasons if the other party is not online.

We're going to need logs from both parties to address this issue.

Re-open if you can provide a log from both parties *right after* the strangeness occurs.
