### ISSUE TITLE
Xcode displays warnings from third-party Pods

### ISSUE THREAD

**Issue by wtimme** [signalapp/Signal-iOS#3137]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When building, Xcode displays the warnings from the installed Pods, regardless of whether they are development pods (fixable warnings) or regular third-party libraries (non-fixable warnings). This makes it more difficult for me as a developer to see which lines need my attention, and which ones are (as far as this repository is concerned) out of reach for me.

### Steps to reproduce
1. Checkout a clean state of `master`
2. Build the workspace
3. Wait until the build is finished. At the time of writing, Xcode displays a total of 320 warnings
4. Open the issue navigator (`cmd` + `5`)
5. Search for a third-party dependency, e. g. "YYImage"

**Actual result:** The list of warnings contains those of third-party Pods
**Expected result:** The list should only contain warnings for the "Signal" project and for development pods

### Screenshots
<img width="269" alt="screen shot 2018-03-16 at 12 16 51 am" src="https://user-images.githubusercontent.com/1681085/37495809-6d3cc42a-28af-11e8-9a47-37e754226596.png">

### Device info
**Xcode**: 9.2 (9C40b)

**Comment by wtimme** [comment]
I was able to resolve this problem by adding
```
inhibit_all_warnings!
```
to the Podfile, and explicitly enabling warnings for the development pods, like so:
```
pod 'SignalServiceKit', path: '.', :inhibit_warnings => false
```

Should I go ahead and create a pull request?

**Comment by michaelkirk-signal** [comment]
We're already doing something similar, but doing a blacklist vs whitelist approach. Looks like we forgot to blacklist YYImage when we added it.

Your approach might be better - but there are several pods that are our code, SignalServiceKit, AxolotlKit, HKDFKit, Curve25519Kit

Could you include warnings from all those?

**Comment by wtimme** [comment]
Thanks for the feedback, and thanks for the question! Let me explain my thoughts on this change.

When developing, I prefer a clean workspace, and strive to keep the numbers of warnings as low as possible - ideally getting down to zero.
When looking through the warnings, those for a dependency that is not a [development pod](https://medium.com/@euginedubinin/development-pods-de631774751e) are not helpful, since I cannot fix them right away - the files are locked. They are just "noise".

With my change, only the warnings for the Pod [SignalServiceKit](https://github.com/wtimme/Signal-iOS/blob/d61895543df4137be811e26df72f2b7b779cbea2/Podfile#L16) will be displayed in Xcode. I want to see those warnings, as SignalServiceKit is a development pod that is checked-in to this repository.

The commented-out lines for [AxolotlKit](https://github.com/wtimme/Signal-iOS/blob/d61895543df4137be811e26df72f2b7b779cbea2/Podfile#L18), [HKDFKit](https://github.com/wtimme/Signal-iOS/blob/d61895543df4137be811e26df72f2b7b779cbea2/Podfile#L20) and [Curve25519Kit](https://github.com/wtimme/Signal-iOS/blob/d61895543df4137be811e26df72f2b7b779cbea2/Podfile#L22) look like people sometimes use a local development pod of those when developing, and in those situations I of course would want to see those warnings, too.

That's why with [ef3e7b4f6](https://github.com/wtimme/Signal-iOS/commit/ef3e7b4f6), I've added `:inhibit_warnings => false` to those commented-out lines as well, making sure that if one was to use those development pods, the warnings would show up in Xcode.

What's your opinion on this?

**Comment by michaelkirk-signal** [comment]
Please leave the warnings for our Pods as described.

**Comment by michaelkirk-signal** [comment]
Fixed in https://github.com/signalapp/Signal-iOS/commit/a6dbe5bf7a5b00560b0f89799dd4fdc8cec5d8bd
