### ISSUE TITLE
use OPUS for audio recorder?

### ISSUE THREAD

**Issue by ldenoue** [signalapp/Signal-iOS#3156]
I noticed Apple now supports kAudioFormatOpus.
Would it make audio files smaller and playable on Android as well?

https://github.com/signalapp/Signal-iOS/blob/592e6b246185c59224a1d7f34b0aa0e883e1b71b/Signal/src/ViewControllers/ConversationView/ConversationViewController.m#L3226

**Comment by michaelkirk-signal** [comment]
> I noticed Apple now supports kAudioFormatOpus.

Can you help gather some documentation on when this became available?

**Comment by ldenoue** [comment]
WWDC1017
https://developer.apple.com/videos/play/wwdc2017/501/
PDF of the slides https://devstreaming-cdn.apple.com/videos/wwdc/2017/501fo36iwi2moz2l222/501/501_whats_new_in_audio.pdf?dl=1
![image](https://user-images.githubusercontent.com/149561/37913182-94a49f16-3114-11e8-9f33-6cf1f64850d8.png)

**Comment by michaelkirk-signal** [comment]
Specifically which versions of iOS do and do not support this feature? WWDC2017, so sounds like it's new in iOS11?

What would we do on pre-iOS11 devices?

**Comment by ldenoue** [comment]
yes, only iOS 11. For the others, we could fall back to using libopus.
WhatsApp seems to be using OPUS (at least on web), making files smaller.

**Comment by leonardoporpora** [comment]
The quality of audios and calls is really good compared with WhatsApp I wouldn’t change it to the same of WhatsApp because the quality would be worst.

**Comment by michaelkirk-signal** [comment]
@leonardoporpora - this is about audio voice notes, not calls, which already use opus via WebRTC.

This change would need to be coordinated across other clients to make sure they're all capable of playing these files.
