### ISSUE TITLE
Swipe back during a call not working

### ISSUE THREAD

**Issue by peledzius** [signalapp/Signal-iOS#3161]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Impossible to go back to Signal menu or messages during a call. Swiping from left to right does nothing.

### Screenshots

![ss](https://user-images.githubusercontent.com/24360494/37680117-9cc24d84-2c8b-11e8-99bb-3a1ddd3f3309.png)

### Device info

**Device**: Iphone 5s
**iOS version**: 11.2.6
**Signal version:** 2.22.0.4

**Comment by leonardoporpora** [comment]
I think they are working on it. What you want is the possibility to continue chatting during a call right?
