### ISSUE TITLE
Verification SMS doesn't arrive on a data only SIM card in The Netherlands

### ISSUE THREAD

**Issue by vasilisvg** [signalapp/Signal-iOS#3186]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I try to sign up with a data only SIM card in The Netherlands, but whenever I try to verify I never receive a verification SMS. This SIM card is capable of receiving SMSes, it did receive one from Whatsapp for instance. It’s not possible to make a regular phone call to this number.

This number starts with 097, while almost all mobile phone numbers in The Netherlands start with 06. Could it be that _06_ is somehow hard coded somewhere?

**Comment by michaelkirk-signal** [comment]
Can you follow up with support@signal.org please?
