### ISSUE TITLE
Don't dismiss the keyboard when long-pressing a message to show the edit menu.

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3190]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When want to delete a photo

### Steps to reproduce
1. have the keyboard of the iPhone opened like if you want to write something
2. try to delete a message 

**Actual result:**  the keyboard will be closed and once closed you have to rekeep under pressure the message and than click delete
**Expected result:** keep under pressure with the open keyboard and click delete without the keyboard getting closed

### Device info

**Device**: Iphone 6s
**iOS version**: 11.2.6
**Signal version:** 2.22.0.4

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
