### ISSUE TITLE
Unable to Share screenshot

### ISSUE THREAD

**Issue by NooNameR** [signalapp/Signal-iOS#3201]
### Bug description
Hi I can't share photo using default screen shooter from iOS. I tried to reboot device and it not helped
I saw this issue, but I'm not using landscape mode
https://github.com/signalapp/Signal-iOS/issues/3147

### Steps to reproduce
- take a screenshot from screen (using home+power button)
- click "Share" icon
- select "Signal" app
- select recipient

**Actual result:** There is no button to "Send" and write a description
**Expected result:** Write a description and "Send" photo

### Screenshots
![29680470_1675184115894274_1904903788_o](https://user-images.githubusercontent.com/1432637/38020017-de5af092-3281-11e8-8353-ec5a7d3025f0.jpg)

### Device info

**Device**: iPhone 7 Plus
**iOS version**: 11.2.6
**Signal version:** 2.22.0.4

### Link to debug log
https://debuglogs.org/1ad6a748745990ded6deb92c72c7424a7344967e44d2b0456d0542066fa61923.zip

**Comment by leonardoporpora** [comment]
I’m unable to reproduce it.

**Comment by erikstrottmann** [comment]
I experience this same bug. Sharing a screenshot from the Photos app works as expected, but when I share directly from the iOS 11 screenshot overlay, there’s no text field or send button.

**Comment by TreatyOfRome** [comment]
I also mentioned this problem in #3066.

**Comment by NicolasCGN** [comment]
Same problem here with the screenshot overlay in iOS11

**Comment by michaelkirk-signal** [comment]
Is anyone able to duplicate this with iOS11.3?

**Comment by leonardoporpora** [comment]
Yes i am

**Comment by NicolasCGN** [comment]
Me too

**Comment by funkenstrahlen** [comment]
Can confirm this issue still persists in iOS 11.3.

**Comment by michaelkirk-signal** [comment]
Thanks I think we've got the information we need, no need for "me too" comments which just spam all our subscribers.

**Comment by EvanHahn-Signal** [comment]
Closing this issue as stale. Please open a new one if you're still encountering problems.
