### ISSUE TITLE
iOS SMS sync makes it super easy to accidentally deactivate iPhone via an iPad install

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-iOS#3208]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

Modern iOS versions sync SMS messages as well as iMessages between devices. This makes it super easy to accidentally register Signal on a different device, thus deactivating the primary one.

### Steps to reproduce

* Have an iPhone and iPad, both linked to the same Apple ID
* Register on the iPhone
* Download Signal on the iPad and register, manually inputting the iPhone's phone number (my mom did this thinking that it would allow her to see Signal messages on her iPad too, similar to the way the desktop app is linked)
* SMS gets delivered to the iPhone
* SMS gets synced to the iPad
* iPad recognizes the activation code in the SMS and registers with the server, deactivating the iPhone in the process

**Actual result:** The iPhone's Signal is deactivated
**Expected result:** Signal on the iPad should have warned the user against doing this - something like "are you sure? This number is already registered; reregistering will deactivate your iPhone!"

I'm omitting the Signal version and iOS version because it would be a hassle to figure that out and I'm 95% sure it doesn't matter. If that's not the case I can ask my mom.

Possibly this should be folded into #2645, I'm not sure. I'm filing separately since it seems like a more specific case and because this shows IMO a more serious UX issue than those highlighted in that issue (since the SMS sync makes this even easier to get wrong), but feel free to close as a duplicate.

**Comment by Imperiopolis-Signal** [comment]
iPads now work as linked devices, so this shouldn’t be a problem going forward.
