### ISSUE TITLE
iOS to Android and back. Vomit-inducing sent/received picture/video quality.

### ISSUE THREAD

**Issue by Gunner-12** [signalapp/Signal-iOS#3211]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Horrible picture quality of sent and received videos and pictures, the compression is an utter overkill, the sent received data is unusable and worse than MMS.

### Steps to reproduce
- send someone a picture 

**Actual result:** Horrible quality picture at reduced resolution.
**Expected result:** Original image with stripped EXIF, or at least slightly compressed. Or provide a button or an option to be able to send original, is Signal trying to save bandwidth or what?

### Screenshots
No point.

### Device info

**Device**: iPhone 8
**iOS version**: Latest @ March 30, 2018
**Signal version:** Latest @ March 30, 2018

**Comment by michaelkirk** [comment]
some details code help as this is not generally reproducible.

Is it all images that you send that have this problem?

Is it only when receiving an image from an android device which in turn received them image from an iOS device?

I appreciate that you think this is obvious, but some specific steps of devices and versions could help us fix this.

**Comment by michaelkirk-signal** [comment]
Please re-open with some actionable details.

**Comment by kclarkr** [comment]
Well, it's three years later and it's still an issue.

iOS 14.6
Signal iOS 5.13.0.33
Signal Desktop (Linux) 5.3.0  

Here is the orignal photo on the iPhone with properties displayed in the Sony Imaging Edge Mobile app (as iOS doesn't display properties)
![signal-2021-06-01-101406](https://user-images.githubusercontent.com/63563788/120347847-401cb800-c2c2-11eb-813a-9bfa0be0b6b2.jpeg)

Here is what is received on Android and on Signal Desktop (Linux)
![DSC02763](https://user-images.githubusercontent.com/63563788/120347849-40b54e80-c2c2-11eb-8026-1208a6eeda10.jpg)

Here is the properties on the received image.
![Screenshot from 2021-06-01 10-15-55](https://user-images.githubusercontent.com/63563788/120348057-6d696600-c2c2-11eb-9efd-a417d263711f.png)
