### ISSUE TITLE
Signal crashed while I was uploading a video

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3237]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
While I was uploading a video Signal crashed

### Steps to reproduce
It's not systematical so I don't know the steps

**Actual result:** Signal crashed
**Expected result:** should upload without crashing 

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3
**Signal version:** 2.23.0.14

### Link to debug log

https://debuglogs.org/56daf602cb7115b8c918cba85da605b8c00a0a598e94a3a7ea06d81811c19c94.zip

Can I share it here [The crash log]? Or is better to send it through mail? 
I have already 2 opens issue by mail about crash but all of them for different reasons.

**Comment by michaelkirk-signal** [comment]
Can you upload the crashlog to a gist?

**Comment by leonardoporpora** [comment]
https://gist.github.com/leonardoporpora/1962f8613010b1b91ecb590261724aaf

**Comment by leonardoporpora** [comment]
@michaelkirk-signal tell me once you have copied so that i delete the link :+1:

**Comment by michaelkirk-signal** [comment]
I've got it.
