### ISSUE TITLE
Bypass screen locker

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3244]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Bypass screen locker was fixed partially 

### Steps to reproduce
- close Signal (double click on home botton and slide up)
- open signal
- click cancel 
- one click on home button
- open app and you are in 

**Actual result:** Bypass screen locker
**Expected result should ask password

All other info are the same of #3224

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** 2.23.1

**Comment by TreatyOfRome** [comment]
I can confirm this behavior with version 2.23.1.1. 

## Steps to reproduce
- Go to settings > privacy > and activate the screen lock with a timeout of 1 minute.
- Go back to the Signal 'home screen' where all chats are shown
- Close Signal (double click on home button and slide up)
- Wait more than 1 minute
- Open Signal from iPhone home screen
- Signal asks for pass code, click cancel
- One click on home button to return to iPhone home screen
- Open Signal from iPhone home screen and you are presented with the Signal home screen

**Actual result**: Bypass screen locker
**Expected result**: Should ask for pass code again

## Device info
Device: iPhone 5S
iOS version: 11.3
Signal version: 2.23.1.1

**Comment by charlesmchen-signal** [comment]
Fixed in #3246 which will ship in v2.23.2.  Thanks.
