### ISSUE TITLE
Messages not been shown after updating from 2.22.0 to 2.23.0

### ISSUE THREAD

**Issue by x0t0x** [signalapp/Signal-iOS#3245]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
While running Signal-iOS **2.22.0**, i was notified that a newer version (**2.23.0**) was available. After the update operation, older & newer messages are *no more* shown in the application. 

All linked devices are working as they should, but Signal-iOS is neither displaying text- nor audio-messages. Newer and older Multimedia (Photos and videos) messages are *only* available through the account-based feature "All media".

The application gets the notification about new messages, but nothing is displayed in Signal-iOS. I'm able to send new messages with the application, but i can't see those on the device. Those are only shown on linked devices. 
In the Signal-iOS-Mainview, even if the messages are not displayed, their timestamp are updated correctly. 
When the phone is locked, newer messages and their content are correctly displayed as notifications, but when the application is launched, nothing is displayed...
 
Currently running **2.23.1.1** but the issue is still present.

### Device info

**Device**: iPhone X
**iOS version**: 11.3
**Signal version:** 2.23.1.1

**Comment by peter-sc** [comment]
I'm having the same behavior on iPhone7, Signal 2.23.2.0, iOS 11.3. Interestingly, calls are functional. Message content is not displayed for existing conversations, nor for new one. Also uploaded debug logs via email.

**Comment by michaelkirk-signal** [comment]
@x0t0x 

can you provide a debug log?

@peter-sc 

Can you make sure to reference this issue in your thread with support?

To both of you:

It sounds like you see conversations listed in the home view, but you don't see the snippet of text for the "last message".

Furthermore, when you go into any conversations, you always see an empty thread. Is that right?

**Comment by peter-sc** [comment]
@michaelkirk-signal we don't see any content of any conversation - of old (existing one), and also for new one. So if I start a new conversation, the message is sent and arrives to the recipient, but I don't see this message in the conversation history. If the conversation is being archived, it isn't displayed there either. 

Is there any size limit for the DB, where messages+multimedia data are stored? The size Signal takes on my phone is about 1,12 GB.

**Comment by bicycult** [comment]
I’m also experiencing this issue on an iPhone X running iOS 11.3 and Signal 2.23.3.2. None of my messages are appearing whether it be the content of any particular conversation within each thread or the previews for the latest message on the list of threads. Here’s my [debug log](https://debuglogs.org/c707a2b3560e938312dc89cf47a5fd9b963f4f99d95ee1a1af3256288c13a10f.zip).

**Comment by peter-sc** [comment]
If you reinstall Signal, then the problem is resolved. You lose your conversation history though.

**Comment by michaelkirk-signal** [comment]
Thanks for those users that have helped so far. We've identified the fix, which will ship with the 2.25 release. 

2.25 is still too raw for public beta at this point, but if you're experiencing this issue, it makes Signal pretty much unusable. If you are willing to try a rough pre-beta build (read:  possible crashing or data loss) send an email to support@signal.org with the subject: "re: #3245 Missing messages - Sign me up for the Signal-iOS 2.25 pre-beta".

Or if you can wait until the public release (a week or two away), there's a better chance you can get your data without risking other crashes/data loss.

**Comment by jlund-signal** [comment]
We shipped this as a hotfix in version 2.24.1. Can anyone confirm whether or not this has resolved the issue?

**Comment by bicycult** [comment]
Installed 2.24.1 and I can see all my messages. Looks like it worked. Thanks all!
