### ISSUE TITLE
New Logo for Signal-ios

### ISSUE THREAD

**Issue by mirzazulfan** [signalapp/Signal-iOS#3250]
Hallo.
I wanted to contribute to Signal-ios and I designed a logo for Signal-ios. If you like it, you can use it. I'll send you files and pr, is there anything you want ?
![signal app](https://user-images.githubusercontent.com/36124339/38463853-665d20a6-3b2d-11e8-8a56-b973ac722d11.png)

**Comment by caveman1973** [comment]
I'm not convinced. 
Symbol inside looks like a WiFi connection. 
Logo is square. iOS use square with round corners. 
You made it rectangular. 
Why the division? What does the cutting means? In the original icon, you see a chat bubble inside dotted lines (has a meaning). 

If I were your client or boss I'll send you back to the drawing board. 

Don't take it personal.

**Comment by michaelkirk-signal** [comment]
Thanks for the contribution, but we're happy with our current logo.
