### ISSUE TITLE
crash when scrolling up "all media" for a chat

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3254]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
open all media for a chat
scroll up
at some point always the same point it crashes
i don't get a ios crash id, here is a debug log instead
https://debuglogs.org/8bd27b99871b6c014e1262e74d4e91344653c295e43a802c86de45338a77f023.zip

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X
**iOS version**: X.Y.Z
**Signal version:** Z.Y

**Comment by mailinglists35** [comment]
ios 10.2

signal latest from app store (because you published a newer version on app store than on beta so i wanted the latest build)
iphone se

**Comment by mailinglists35** [comment]
here is the same crash using latest beta

https://debuglogs.org/fd55e1fb72db098d4d3e9862214b978231a47999ca587e44719c2c9ff0caed82.zip

**Comment by michaelkirk-signal** [comment]
Can you reproduce this in the media swipe view?

e.g. 
- tap on a piece of media to open the full screen media view
- swipe back to view the previous media until either it crashes or you're at the earliest media

**Comment by mailinglists35** [comment]
interesting, swiping back one by one does not crash

**Comment by mailinglists35** [comment]
still occuring

https://debuglogs.org/3a11dd94698afe21b590c8849d8d63059bce6148ec361e819491cac12362506d.zip1 (remove 1 at the end)

ios crash id: incident_id":"897D383A-864D-4A58-906D-734B4D3BF484"

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.

**Comment by mailinglists35** [comment]
no longer crashes but instead on one of the chats I see grey thumbnails (and full black when opened) for some images. talking about images sent in 2017
