### ISSUE TITLE
iPhone: "No available session for contact." & Desktop: "Error handling incoming message."

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#3265]
### Bug description
I use Signal on both my iPhone and my desktop.  Messages are being sent to me by a friend who is on Android.  

I received two messages on the desktop saying "Error handling incoming message.", after which all messages were received properly.

I received only some of these messages on the iPhone, where the error is, "No available session for contact."

### Device info
Phone:
iPhone 5, IOS 10.3.3

Desktop:
Ubuntu 16.04, Chromium 65.0.3325.181

### Link to debug log
iPhone debug log: https://debuglogs.org/2e3091d9ce8166a137c3aacd9eb78b7108be9cf8292f4e29bfa2c02b3832f51e.zip

Desktop debug log:
https://debuglogs.org/2fa28367f80be4d47d64262e6d9a905eee9b33eb82590bb01a37459b12ef2c06

**Comment by jayallen** [comment]
#1939 may be related

**Comment by diver-down** [comment]
Same issue, with all accounts of Android friends (I'm on iOS, and my iOS friends come through just fine).

**Comment by DiagonalArg** [comment]
Looking at the questions devs are asking at #1939, I'll add that my devices had been linked for months and I use the desktop client regularly.

**Comment by manuel-koch** [comment]
I see this message for my own contact !? I.e. I have added my own phone number to contacts on iPhone and now whenever I get a message from somebody additionally this strange message pops up too !?

**Comment by michaelkirk-signal** [comment]
@manuel-koch - do you have a linked desktop device? 

This is likely a problem with communication between your mobile device and your linked desktop. Can you open a new issue and include debug logs from your mobile device and your desktop device, and tell me what day/time the first message popped up?

**Comment by c-taylor** [comment]
I am reported this problem by both iOS and Andriod recipeints.
Usage intermittency on a desktop client causes this error quite reliably.

My setup is:
Android client: Primary
Desktop client A: Primary, used 5d/week
Desktop client B: Secondary, used with 1mo gaps

**Comment by joannalange** [comment]
I'm having the same issue on iPhone SE, iOS 12.0, signal version 2.29.3.3
[here](https://debuglogs.org/73f903e4e22ce596c50fcbce9f114e0ce46bdc3a22b6a90e984107a0471c28f7.zip)'s the link to my debug log

**Comment by heis2201** [comment]
I am receiving a *No available session for contact" message from a my own account, just as in https://github.com/signalapp/Signal-iOS/issues/1939

Signal: v.2.32.1.0
iOS: 12.1.2 (iphone SE)

**Comment by joe940** [comment]
Chatted with several people tonight from the desktop. For one user only, a long string of "No available session" messages on the iPhone - and while the messages I sent him are there, his replies are not on the phone. There are actually more "no available session" messages than the total number of messages we sent. Everything is normal on both the desktop app and the new iPad app for this user. Latest versions of iOS, desktop Signal, iPad Signal and iPhone Signal.
