### ISSUE TITLE
Screen-lock doesn't always work

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#3288]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Screen lock doesn't always work.

### Steps to reproduce
- turn on screen lock in settings
- set timeout to 1 minute
- use Signal further
- back to iPhone main screen (main button), then lock screen by lock button
- wait 5 minutes
- open iPhone screen lock, open Signal by Signal app icon

**Actual result: Signal opens at last state and I can see every conversations, etc.
**Expected result: Should have check touch ID.

If I kill Signal app and re-start it, then it asks for touch ID as normally.

### Device info
**Device**: iPhone 7
**iOS version**: 11.3
**Signal version:** 2.23.2.0

### Link to debug log
https://debuglogs.org/182d642043517bad3fd17ad26fcd5ba9cfba9e03085cff2a2ea820a9b4b531e0.zip

**Comment by charlesmchen-signal** [comment]
@kaktusztea Thanks for this bug report.  This behavior is by design. We don't require you to authenticate if you've just authenticated to unlock your phone. However, we've already removed this in our next release to avoid exactly this kind of confusion.
