### ISSUE TITLE
Media Message doesn't always appear in conversation after successfully completing share

### ISSUE THREAD

**Issue by mmiller42** [signalapp/Signal-iOS#3291]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

When an existing attachment is shared from within the Signal app to the same Signal conversation, the message does not appear to have sent, but it was.

### Steps to reproduce
- Send a photo attachment to a contact
- Touch the photo to enlarge it
- Press the Share icon
- Share the photo via Signal
- Select the same Signal contact you sent the photo to
- Send the photo

**Actual result:** The photo is sent to the contact a second time; however, the UI does not show the second copy of the attachment. Even navigating back to the main Signal screen (conversations list) and returning to the conversation does not display the second message. Only after the app is closed and reopened does the second sent message appear in the conversation view. 

**Expected result:** The second message should be displayed in the conversation view as soon as it was sent. In other words, after sharing an attachment via Signal, the conversation thread should be refreshed to show the newly sent message. 

### Device info

**Device**: iDevice X
**iOS version**: 11.3
**Signal version:** 2.23.2.0

### Link to debug log

https://debuglogs.org/7077ff76b0326e492e9cfa0ddd2dd060249c730ffa599938fb3ec8295f48b086.zip

**Comment by denver-s** [comment]
@mmiller42 I did encounter this issue but it's been a while since the last time it happened. I think it's been fixed.
