### ISSUE TITLE
Give a confirmation and warning tip before leaving a group when remove the group

### ISSUE THREAD

**Issue by Pingmin** [signalapp/Signal-iOS#3292]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

I use the Chinese language for Signal, so the description may not be exact same as English.

When I removed a group chat thread/session(I just want to clean the chat message history) by sliding it to left and clicking the delete/remove button, BUT I found I also eixted the group too after doing that, then I had to call my friends and ask them to add me into the group again! However, it does't take this effect by removing a single chat.

So, why not give a warning tip and confirmation before exiting a group when remove it?

Thanks!

### Device info

**Device**: iPhone SE
**iOS version**: 11.2.6 & 11.3
**Signal version**: 2.23.2 & 2.23.3

**Comment by michaelkirk-signal** [comment]
Signal no longer leaves the group when deleting a thread.

**Comment by Pingmin** [comment]
:ok: :+1:
