### ISSUE TITLE
Signal app crashes when active. 

### ISSUE THREAD

**Issue by lionatgithub** [signalapp/Signal-iOS#3295]
- [ ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
- makes a call,
- the call gets connected, and immediately disconnected. 
- but, If I attend call, minimise the signal app, the call stays on. During the call, if I open the app as active screen, the call disconnects and says “call failed”

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**iOS version**: Latest 
**Signal version:** Latest 

### Link to debug log

https://debuglogs.org/6ef62dd8e1cc913782759e244ad1b888e75b40e6dcdfe316edcb2ced172e281d.zip

**Comment by michaelkirk-signal** [comment]
> iOS version: Latest
> Signal version: Latest

Can you please fill in the actual values for these?

What (local) time did you experience the crash?

Can you provide a crash report?

To get a crash log:

1. Go to the iOS Settings app.
2. Go to Privacy.
3. Go to Analytics or Diagnostics & Usage.
4. Select Analytics Data or Diagnostics & Usage Data.
5. Locate the .ips crash log for Signal.
    The logs will be named in the format: Signal(DateTime).ips
6. Select the desired Signal log.
7.a iOS 11 users, tap the Share icon in the top right corner and jump to step 10.
7.b iOS 9&10 users, long press to see the option to highlight text and select the entire text of the log. It will end in EOF.
8. Once the text is selected, tap Copy.

Either paste in a comment here, or paste in a gist and attach the link.

Thanks for any clarification!

**Comment by oonimooni** [comment]
i can confirm this crash as well , and also add the answers to ur questions:- 

> Can you please fill in the actual values for these?
ios 11.3
signal version 2.23.3.2

> What (local) time did you experience the crash?

not sure about the question , but once u open the app it will crash. its almost useless now after the last upgrade. 

hope u rise this bug level to "Blocker" or "Critical"

**Comment by georgiagirl6** [comment]
Same thing happening to me. Really no point in using the app because it keeps crashing

**Comment by michaelkirk** [comment]
We’ve just pushed out a release which fixes a recently introduced crash.

Can you update and let me know if you still experience this crash?

**Comment by michaelkirk-signal** [comment]
@lionatgithub sorry, but GH mangled the formatting of that crash report pretty bad. Can you try pasting it in a gist instead?

https://gist.github.com/


Since you're on iOS11, should be these steps:

`
- Go to the iOS Settings app.
- Go to Privacy.
- Go to Analytics or Diagnostics & Usage.
- Select Analytics Data or Diagnostics & Usage Data.
- Locate the .ips crash log for Signal.
- The logs will be named in the format: Signal(DateTime).ips
- Select the desired Signal log.
- tap the Share icon in the top right corner and select "copy"
- go to gist.github.com and paste into the text area
- save and send me the link.

Thanks! 

Also, did the latest release (2.23.4) fix the issue for you?

**Comment by oonimooni** [comment]
> Also, did the latest release (2.23.4) fix the issue for you? 

@michaelkirk-signal  yes it did. thank you.

**Comment by Mihahn** [comment]
If it did, would you please close your issue? Thanks!
