### ISSUE TITLE
Feature request: open or/and preview of PDF files

### ISSUE THREAD

**Issue by laberkeks** [signalapp/Signal-iOS#3303]
Hi, it would be great if its possible to open an pdf file directly in the signal iOS app.
And a preview in the chat history would be also great =)

**Comment by leonardoporpora** [comment]
Use the community for feature requests https://community.signalusers.org/ please close this issue

**Comment by laberkeks** [comment]
done -> https://community.signalusers.org/t/open-or-and-display-preview-of-pdf-files/2678?u=laberkeks
