### ISSUE TITLE
Signal crashes when lock screen on iPhone SE is engaged and then exited from

### ISSUE THREAD

**Issue by Signal13** [signalapp/Signal-iOS#3307]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When using Signal on an iPhone SE the application crashes when the lock screen of the iPhone SE engages and the lock screen is then unlocked. When the phone is unlocked Signal ends the call. Signal will then experience difficulty in re-establishing a call and may drop on and off multiple times in succession. The application will need restarting to overcome the issue. 

### Steps to reproduce
- Receive and accept an incoming Signal voice call while the iPhone SE is locked
- Engage the camera with the phone is in the lock screen to initiate a video feed for the call 
- Input iphone SE pass code

**Actual result:** Signal will then crash after one to two second of video feed
**Expected result:** A video feed should begin without affecting the call

### Device info

**Device**: iPhone SE
**iOS version**: 2.23.4
**Signal version:** 11.3

**Comment by charlesmchen-signal** [comment]
After you unlocked, did Signal crash or end the call?  

Can you please attach a link to your debug logs.  App Settings > Advanced > Submit Debug Log > 

Also, can you please send me any Signal crash logs from your phone. iOS Settings App > Privacy > Analytics > Analytics Data > All logs whose name starts with "Signal" > share by email to matthew@signal.org.  Or you can share by email to yourself and then attach them here as files.  

Thanks

**Comment by mailinglists35** [comment]
related

https://github.com/signalapp/Signal-iOS/issues/3115
