### ISSUE TITLE
Screen Lock Bypass

### ISSUE THREAD

**Issue by willg-c** [signalapp/Signal-iOS#3313]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The screen lock is not enforced when Signal is used to send messages from the iOS share menu in other applications.

### Steps to reproduce
- Open the stock Notes application on iOS
- Create a new note, type a message (e.g. "Getting a new phone, my new Signal number is XXXXX")
- Tap the share icon
- Scroll horizontally, tap "More" and switch on the Signal share extension
- Tap "Done"
- Tap the Signal icon in the share menu
- The "Share to Signal" panel is displayed, showing all of your Signal contacts
- Tap one of your contacts
- Tap "Send"

**Actual result:** The message sends successfully, and the recipient has no idea that anything is wrong.
**Expected result:** The contact list should not be displayed, and the message should not be sent. Immediately after tapping on the Signal icon, the screen lock should be activated. If this is not possible from iOS share extensions, ideally users should be given the option to disable the Signal share extension altogether.

### Device info
**Device**: iPhone 8
**iOS version**: 11.3 (15E216)
**Signal version:** 2.23.4.2

**Comment by leonardoporpora** [comment]
Yes I can coinfirm this

**Comment by willg-c** [comment]
Is this actually deliberate, desired behaviour?

https://github.com/signalapp/Signal-iOS/blob/ef95e0538ad21819af66e8a669507dd7f310bebe/SignalShareExtension/ShareViewController.swift#L107

https://github.com/signalapp/Signal-iOS/blob/ef95e0538ad21819af66e8a669507dd7f310bebe/SignalShareExtension/ShareViewController.swift#L145

**Comment by charlesmchen-signal** [comment]
This is by design. The screen lock is intended to protect your message history.
