### ISSUE TITLE
Local notification banners not shown while app is active

### ISSUE THREAD

**Issue by chrisballinger** [signalapp/Signal-iOS#3316]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
While the app is active, all local notification banners are suppressed. Although the phone vibrates when receiving a new message, it does not show a banner, so you have to go back to the main chat screen. It is easy to show local notifications for non-visible threads, for example:

```swift
    public func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
            // Show chat notification while user is using the app, if they aren't already looking at it
            if let (key, _) = extractThreadInformation(notification: notification) {
                OTRAppDelegate.visibleThread({ (ck) in
                    if key == ck?.key {
                        completionHandler([])
                    } else {
                        completionHandler([.badge, .sound, .alert])
                    }
                })
```

I'd submit a patch for this if this is something that you'd consider merging.

**Comment by michaelkirk-signal** [comment]
First we'd have to upgrade to UNUserNotifications (while continuing to support legacy notifications for our iOS9 users).

**Comment by michaelkirk-signal** [comment]
Yup, feel free to submit a PR. It's a feature we'd like, it just hasn't been prioritized yet.

Feel free to hit me up if you have questions about the codebase along the way - I'd expect that you'd be mostly in the PushManager and NotificationsManager classes.

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by chrisballinger** [comment]
Cheers!
