### ISSUE TITLE
App doesn’t open if I don’t close and open it again

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3330]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
App doesn’t open if I don’t close and open it again

### Steps to reproduce
- open the app

**Actual result:** App doesn’t open its freezed on the main logo (the one that u see if u double click the home button)
**Expected result:** app should open

### Device info

**Device**: iPhone 8
**iOS version**: 11.2.6
**Signal version:** 2.23.4.2

### Link to debug log
 https://debuglogs.org/1a41bdaa243ac04d150e354075ee07e99dedf297f05ff0018dcbed20cf56ccc2.zip

**Comment by charlesmchen-signal** [comment]
@leonardoporpora This issue is fixed in v2.24 which will be released soon.

**Comment by leonardoporpora** [comment]
Thx
