### ISSUE TITLE
Send button missing when sharing a screenshot to Signal from iOS 11 Screenshot Editor

### ISSUE THREAD

**Issue by hypebro** [signalapp/Signal-iOS#3338]
### Bug description
Some background, iOS 11 has a "Screenshot Editor" feature. If you take a screenshot it appears in the bottom left of the screen. You can tap it and then edit the screenshot, save it, share it or cancel. If you tap the "Share" icon, then tap "Signal".  You end up in the Signal screen you see when you are picking  an image to send, but the text input box and Send button are missing!

### Steps to reproduce
- Take a screenshot
- Tap the icon when it pops up in the lower left corner
- Tap the share icon
- Pick a contact, you can't send it anyway so it doesn't matter who!
- Tap the Signal app icon

**Actual result:** You will see the X button to cancel out, but no text bar or send button.
**Expected result:** See the text bar and send button where it usually is
 

### Device info
**Device**: iPhone X
**iOS version**: 11.3.1 (present since 11.2-ish)
**Signal version:** 2.23.4

### Link to debug log
https://debuglogs.org/07bf99bd000090d6555e144099c4005313462ade0f25c34d131203dcafe46605.zip

**Comment by leonardoporpora** [comment]
https://github.com/signalapp/Signal-iOS/issues/3201

**Comment by hypebro** [comment]
Sorry i searched for screenshot but didnt see it.
