### ISSUE TITLE
[Minor thing to fix] Can't slide for more info if the message is short

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3347]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I think this affects all Signal version. I'm not able to slide to see more info if the message is really short like "ok" 

### Steps to reproduce
- send a short message
- the recepient will not be able to slide for more info

**Actual result:** Cannot slide for more info
**Expected result:** should be able to slide for more info

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3.1
**Signal version:** 2.24.0.10

### Link to debug log

Not needed

**Comment by ejanalysis** [comment]
A workaround is to quickly, not slowly, slide the small message to the left by flicking it. If you try to slide it slowly by pressing 
/ holding/ sliding slowly, it slides slowly and you don't have enough space to keep sliding it to make it disappear. Flicking it works.
