### ISSUE TITLE
App crashes when  trying to reply to a media message

### ISSUE THREAD

**Issue by pentachore** [signalapp/Signal-iOS#3349]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
App crashes when clicking on the reply feature of a media message (picture or gif).
Example in the conversation view when clicking on a media message.
And in the all pictures view

### Steps to reproduce
- open a conversation or all media section of any contact
- then long press on the media and click on the reply feature
- that reproduce the bug

**Actual result:** The app closes(crash).
**Expected result:**Should open the reply fiew when you can add a comment to the media

### Device info
**Device**: iPhone 5
**iOS version**: 10.3.3
**Signal version:** 2.24.0.10

### Link to debug log
https://debuglogs.org/8d8c883df5b7d266c56f9e3e7df24e02ef535793274e6b7a9294544a07a301aa.zip

**Comment by leonardoporpora** [comment]
Have you submitted the crash log via mail to signal support@whispersystems.org

To get a crash log:

1. Go to the iOS Settings app.
2. Go to Privacy.
3. Go to Analytics or Diagnostics & Usage.
4. Select Analytics Data or Diagnostics & Usage Data.
5. Locate the .ips crash log for Signal.
    The logs will be named in the format: Signal(DateTime).ips
6. Select the desired Signal log.
7.a iOS 11 users, tap the Share icon in the top right corner and jump to step 10.
7.b iOS 9&10 users, long press to see the option to highlight text and select the entire text of the log. It will end in EOF.
8. Once the text is selected, tap Copy.
9. Paste the copied text into an email.
10. Send the email to support@signal.org with a subject like:
  * "iOS Crash Log: (your github issue)"
  * Example subject: iOS Crash Log: Crash on launch #111
  * Example subject: iOS Crash Log: Crash when sending video #222
-->
