### ISSUE TITLE
Signal no longer can use Face ID after Signal app reinstalled

### ISSUE THREAD

**Issue by ejanalysis** [signalapp/Signal-iOS#3355]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Signal no longer can use Face ID after Signal app reinstalled.

### Steps to reproduce
- face id for screen unlock working fine in signal initially 
- delete signal app (press hold icon, tap x)
- reinstall signal app from app store app by tapping icloud symbol 
- register phone number
- turn on screen lock in signal privacy settings
- go to iphone settings, face id, other apps
- Signal is not listed as an app requesting face id

**Actual result:** Signal does not appear as an app requesting faceid in ios face id settings after signal app deleted and reinstalled from icloud
**Expected result:** Signal should appear as an app requesting faceid in ios face id settings even after signal app deleted and reinstalled from icloud

### Device info

**Device**: iPhone X
**iOS version**: 11.3
**Signal version:** 2.24.0.10

### Link to debug log

https://debuglogs.org/5cd2d4eb3941a3648ba44be7d11fbc5063b527bf82419071158d44f12366d782.zip

**Comment by Banger** [comment]
Same issue:
- On iPhone lock screen, Face ID is used to let me see the message
- When I launch the app, it pops the Keypad to enter my password, it doesn't even try to scan my face.

**Comment by charlesmchen-signal** [comment]
This issue has been addressed. The fix will ship with our next release, v2.25.

**Comment by mfow** [comment]
I'm still having this issue on 2.28.0.15
