### ISSUE TITLE
message disappearing time not syncing

### ISSUE THREAD

**Issue by dgobaud** [signalapp/Signal-iOS#3365]
### Bug description

mobile app does not sync message disappearing time from a conversation started on desktop.

the only way to get to sync is to explicitly turn disappearing messages on in the iOS app for the conversation then it will sync correclty

### Steps to reproduce

1. start new conversation on desktop with disappearing time
2. send message
3. receive message
4. open conversation in iOS
5. send message on iOS

**Actual result:**

the message is sent and shows up in desktop
right below it says "You set timer to off"

**Expected result:**

the timer should not be set to off

### Screenshots

this screenshot is taken from desktop. the last message i sent is from iOS and you can see how it then set the timer off

![image](https://user-images.githubusercontent.com/240811/39505709-06a3d01a-4d89-11e8-88f3-55c05c5f211a.png)

### Device info

**iOS version**: 10.3.3
**Signal version:** 2.23.4.2

### Link to debug log

https://debuglogs.org/cd70ce285eeb4250dafb7fd4b3dac99d4ae025b31fbfffb7e899e2ba6a682e92.zip

**Comment by michaelkirk-signal** [comment]
Thanks for providing the steps to reproduce - but it doesn't immediately reproduce for me.

- start new conversation on desktop with disappearing time
- send message
- receive message
- open conversation in iOS
- send message on iOS

When I do the above, the message sent from iOS has the current timer correctly applied.

Can you provide a similar screenshot from your iOS device, it might help get a complete picture of what's going on.

**Comment by dgobaud** [comment]
that is it - never having opened the conversation with the person before on iOS. Start it on Desktop it won't sync the time. Then if you send messages from iOS they won't show up in desktop UNTIL in iOS app you turn on disappearing messages.

desktop screenshot 1 - starting conversation
![image](https://user-images.githubusercontent.com/240811/39611053-5ca76f86-4f09-11e8-9f3f-5b9fa9c5dcd3.png)

ios screenshot 1 - opened conversation
![image](https://user-images.githubusercontent.com/240811/39611067-80be40de-4f09-11e8-8738-12e677dc8bb9.png)

ios screenshot 2 - sent message
![image](https://user-images.githubusercontent.com/240811/39611077-9319a0e8-4f09-11e8-81b6-09b0b9032304.png)

desktop screenshot 2 - after ios message sent - notice the timer update but no message received!
![image](https://user-images.githubusercontent.com/240811/39611090-a95ce2b6-4f09-11e8-8168-2a7a04791969.png)

ios screenshot 3 - sent message 2 then turned on disappearing messages on iOS
![image](https://user-images.githubusercontent.com/240811/39611120-ff6018ea-4f09-11e8-9eab-ae9755b6e209.png)

desktop screenshot 3 - test3 finally received after iOS turned on disappearing messages
![image](https://user-images.githubusercontent.com/240811/39611132-12d535cc-4f0a-11e8-91d1-44b68fbcc569.png)

**Comment by michaelkirk-signal** [comment]
These screenshots and reproduction steps are super helpful. Thanks! We'll take another look.
