### ISSUE TITLE
Shrink repository download size

### ISSUE THREAD

**Issue by gonsolo** [signalapp/Signal-iOS#3370]
- [x ] I have searched open and closed issues for duplicates

### Bug description
Downloading 460MB for a project of 30MB feels unnecessary.
This mostly stems from including libcrypto.a 58 times which is not used anymore.

### Steps to reproduce
git clone https://github.com/signalapp/Signal-iOS.git

**Actual result:** Downloading 400MB over my LTE line
**Expected result:** Downloading around 60MB over my LTE line

### Suggested remedy:
Find all large files in history:
https://stackoverflow.com/questions/10622179/how-to-find-identify-large-files-commits-in-git-history
Remove files bigger than 4M:
https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

This brought down the repo from 461MB to 74MB, a reasonable size for a project of about 30MB.

Alternatively you could move the repo to Signal-iOS-old and strip all history since the deletion of libcrypto.a.

I think the advantage of not having a 460MB repo outweighs the disadvantage of not having the full history (which would be still available in the old repo).

Thanks.

**Comment by rwc** [comment]
@gonsolo - If operating under bandwidth restrictions, I’d recommend doing a shallow clone.

`git clone --depth 1 <repository>`

**Comment by gonsolo** [comment]
Hi!

@gonsolo <https://github.com/gonsolo> - If operating under bandwidth
> restrictions, I’d recommend doing a shallow clone.
>
> git clone --depth 1 <repository
>

Thanks.

But you can only know about the 30MB/460MB difference *after* you download
the repo and inspect the history.
And a history full of large binaries (and all the same) is ugly as hell. I
think you still should do this.

Anyway, I already downloaded it. ;)

g

**Comment by michaelkirk-signal** [comment]
Thanks but could you use the forums for these kinds of discussions? We use GH to track bugs in the client.

https://community.signalusers.org/
