### ISSUE TITLE
Repeated call failures immediately after call

### ISSUE THREAD

**Issue by rmathus4** [signalapp/Signal-iOS#3375]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
After I receive a call, I consistently get a System Failure message of the call failing.  The call fails within the first 10 seconds.   It didn't seem to happen with version 2.24 so not sure if this is a new thing or what might have changed. 

### Steps to reproduce
- Have a friend call you.
- Answer the call
- The call fails within 10 seconds.  
- Device is off WiFi and there's a full cell signal on my device.   This has happened in a few different locations (so it's not limited to say being near my house).  Yet if I call the same person back (she initiated the call), it works fine.  

**Actual result:** System Failure message on the screen about the call failure
**Expected result:** Expected call not to fail

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3.1
**Signal version:** 2.24.1

### Link to debug log
https://debuglogs.org/2381fdc72c8e27bd1e5f729c577da1908f386af02a0442128808307f52075a24.zip

Edit: sorry #3551 didn't come up when I searched.  My fault. Anyway, debug log is attached if it helps.

**Comment by leonardoporpora** [comment]
same issue https://github.com/signalapp/Signal-iOS/issues/3351

**Comment by rmathus4** [comment]
For what it's worth, this still happens on both WiFi and cellular.  It's intermittent and I can't definitely say it fails when I do XYZ each time.

**Comment by georgiagirl6** [comment]
I’m having the same issue almost every time a call is received or I’m making the call out

**Comment by michaelkirk-signal** [comment]
Thanks for reporting, this should be fixed in the upcoming 2.26 release.
