### ISSUE TITLE
No Option for Opening PDFs (in iBooks, Acrobot etc.)

### ISSUE THREAD

**Issue by khashyarkh** [signalapp/Signal-iOS#3377]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
There is no option to open PDFs directly.

### Steps to reproduce
- open a PDF attachment.

**Actual result:** "The Share Menu Icons Look Maladjusted."
**Expected result:** Open in iBooks, Acrobot etc. option as in Saffari, iMessage and other apps
### Screenshots:
Current Share Menu for PDFs:![signal-2018-05-04-024931](https://user-images.githubusercontent.com/34171942/39606125-fb429294-4f48-11e8-9f08-d346ea07ae04.png)

### Device info

**Device**: iPad 2 
**iOS version**: 9.3.5
**Signal version:** 2.24.1

**Comment by michaelkirk-signal** [comment]
That is a system provided "Activity" sheet - seems like something is up with your device.

I will say, we don't have many users running iPad on iOS 9.

**Comment by khashyarkh** [comment]
@michaelkirk-signal 
there are no other app which has this problem, I've Tested Mega, Dropbox, Telegram, Gmail and Viber among others.
isn't that weird in your opinion? 
it's good to not have a "market share" kind of attitude in these problems.
