### ISSUE TITLE
Send Signal message from the contact app not working

### ISSUE THREAD

**Issue by corsac-s** [signalapp/Signal-iOS#3400]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
From the contacts app, it's not possible to directly send a Signal message.

### Steps to reproduce
- open contact app
- select contact with a Signal number
- long press on “message”

Note: some of my (Signal) contacts avec specific fields for Signal, which I didn't add. Specifically, they have a “social profile” with a “custom service” called signal. This “social profile” field is apparently not used for messaging, but for video calling (although it doesn't work, it only opens Signal but does nothing after that). There is also an “instant message” field, also used by WhatsApp, but which doesn't work.

**Actual result:** 
No “signal” message is available
**Expected result:** 
A “signal” item is available in the list, and tapping on it opens the conversation in the Signal app.

### Device info

**Device**: iPhone SE
**iOS version**: 11.3.1
**Signal version:** 2.24.1.0

**Comment by corsac-s** [comment]
I'm sorry, the explanation isn't really crystal clear, but I'm unsure how to explain better. Feel free to ask question though.

**Comment by corsac-s** [comment]
Doing a quick look at the Apple API it seems that [CNInstantMessageAddress](https://developer.apple.com/documentation/contacts/cninstantmessageaddress) and [CNSocialProfile](https://developer.apple.com/documentation/contacts/cnsocialprofile) might be relevant, but I'm unsure.

**Comment by michaelkirk-signal** [comment]
As far as I know, this is not a feature Apple supports. Have you been able to do this with any messaging app?

Please re-open if I'm mistaken.
