### ISSUE TITLE
Profile sharing not working for iOS users in group chats

### ISSUE THREAD

**Issue by pganssle** [signalapp/Signal-iOS#3406]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
We have a group of some iOS and some Android users, few of whom have one anothers' phone numbers in their contact lists, but for some reason all iOS users are showing up as bare phone numbers despite sharing their profile information with the group.

**What we have tried**:
- Reinstalling / Upgrading Signal does not work
- It does not matter if the group was started by an iOS user or an Android user
- Sending a message to the group does not trigger sharing of profile information to the group (before or after enabling profle sharing).

In the group settings it says "This group can see your profile." even for people whose contact information is not showing up.

Both iOS and Android users can see the profile information of Android users. Neither iOS nor Android users can see the profile information of iOS users.

This issue is affecting *at least* version 2.24.0.1.

### Steps to reproduce
- Start a group with iOS users not in your contact list
- Have iOS users share profile information

**Actual result:** Profile information not visible to others in group.
**Expected result:** Same thing that happens for Android users - profile information visible in group.

### Device info
I am one of the Android users, but it seems that this is reliably happening to *all* iPhone users in the group. I asked one of the others for this information:

**Device**: iPhone
**iOS version**: 11.3
**Signal version:** 2.24.0.1

**Comment by jpurviance** [comment]
I am also experiencing this

**Comment by michaelkirk-signal** [comment]
Fixed in b74f545a6, thanks for the good report.
