### ISSUE TITLE
How to Integrate Signal chat in app?

### ISSUE THREAD

**Issue by harmispatel** [signalapp/Signal-iOS#3422]
Hi,

I have chat feature in my application and as per requirement I need to integrate chat with Signal framework in my application.
First I want to know that, can I integrate Signal framework in my application?
If Yes Please Let me know How?
I am new in iOS.
I have already download "https://github.com/signalapp/Signal-iOS" code from here. But I am not unable to run it as It gives me 'WebRTC' and 'PromiseKit' POD file error, so I have install both required POD and run downloaded application but Still I am getting so many error. So I can't check this framework exactly do.
Please Give me instruction to integrate Signal framework to my application.
Please Provide me some tutorials if it's there for that.

Thanks in advance.

**Comment by marwendoukh** [comment]
I have tried to integrate [SignalServiceKit](https://github.com/signalapp/Signal-iOS/tree/master/SignalServiceKit) via Cocoapods by adding this line to Podfile : 

`pod 'SignalServiceKit', git: 'https://github.com/signalapp/Signal-iOS.git'`

 but I found some issues and I am not able to import it to my project.

I didn't find any documentation that would help us.

**Comment by michaelkirk-signal** [comment]
We only use GH for reporting bugs in the Signal clients, not for development support. 

Please use the forums for that: https://community.signalusers.org/

And please include any error message that you encounter.
