### ISSUE TITLE
Crash on Enabling Video

### ISSUE THREAD

**Issue by khashyarkh** [signalapp/Signal-iOS#3430]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Tried to enable video during a Call right after that the app crashed.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPad 2
**iOS version**: 9.3.5
**Signal version:** 2.24.1

### Link to debug log

https://debuglogs.org/3ace49ca0fcc5b3a11ce3cae03b2c7d8d0cc13329574491773df322b3dd37b3d.zip

**Comment by michaelkirk-signal** [comment]
Thanks for reporting - This should be fixed in 2.26 release.
