### ISSUE TITLE
Problems with time stamp

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3447]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Sometimes I get a reply to my message and it’s shown before my question

### Steps to reproduce
- idk

**Actual result:** reply to my question is when before my question 
**Expected result:** The reply should be shown after my question

### Screenshots

![fd757a30-ce70-42b4-9eff-21e73ee8bb49](https://user-images.githubusercontent.com/34192761/40183659-ab9bb062-59ee-11e8-8875-461f5cfe75a1.jpeg)

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3.1
**Signal version:** 2.24.1.0

### Link to debug log

https://debuglogs.org/dca8a6cbf4f934b8d9bfab48757c0decea7d1d3075b02787b78605d515662db4.zip

**Comment by michaelkirk-signal** [comment]
Looks like someone's device clock is off (either on their mobile or the linked device). 

The date header corresponds to the local time the message was sent, while ordering reflects when they were received.
