### ISSUE TITLE
Deal with AMR files in non-confusing way

### ISSUE THREAD

**Issue by nogoegst** [signalapp/Signal-iOS#3455]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
As far as I know AMR files are not supported on iOS. When someone sends an AMR file to iOS device it is being displayed as a voice recording. There is no feedback why it doesn't play.
AMR plays on Android though.

### Steps to reproduce
- Attach an AMR file and send the message to an iOS device
- Tap play button

**Actual result:** Nothing happens.
**Expected result:** It either should play AMR or present it as a typical unknown file (not as a voice message).

### Device info

**Device**: iPhone
**iOS version**: 11.3.1
**Signal version:** 2.24.1.0

**Comment by Gabardone** [comment]
I had a look at this. It seems like this is a framework (AVFoundation) misbehavior. It technically doesn't support the file format but will load the file, and there's no warning that it won't work until you try to play it using -[AVAudioPlayer play] and it returns NO.

As best as I've been able to ascertain the best solution right now would be to special-case this file type so it gets treated as a generic file in the conversation transcript.

**Comment by michaelkirk** [comment]
@Gabardone - if you or anyone wants to look at this, it may be be that we need to change our supported audio formats via MimeTypeUtil.m

**Comment by Gabardone** [comment]
Ah thanks for the pointer, didn't find out that file 😬.

This should be a simple matter then, and easy to revert if Apple ever starts properly supporting the format again.

**Comment by Gabardone** [comment]
Got a PR for this at https://github.com/signalapp/Signal-iOS/pull/3520

Thankfully the MIMETypeUtil.m changes you suggested seem to work exactly as we'd want.

**Comment by nogoegst** [comment]
As the PR has been merged, I am closing this issue. Thanks for fixing!
