### ISSUE TITLE
Add option to keep or strip meta-data

### ISSUE THREAD

**Issue by kontaxis** [signalapp/Signal-iOS#3456]
https://github.com/signalapp/Signal-iOS/pull/2907 strips meta-data from photos sent over Signal. But there are cases where it is desirable to share the meta-data because revealing EXIF location and other info is not part of the threat model. E.g., between friends where the network is the only adversary.

In fact the missing meta-data might ruin the experience and turn users away from Signal.

This is a request to add a UI element giving the option to keep or strip the meta-data in photos, per conversation or globally. It should default to removing the meta-data.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality please see CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
