### ISSUE TITLE
Switch language of the keyboard depending on the conversation

### ISSUE THREAD

**Issue by jaspervolmer** [signalapp/Signal-iOS#3460]
- [ x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
The language of the keyboard is not linked to the chat. 

### Steps to reproduce
- Configure your iPhone with keyboards with different languages
- go to a chat, select language #1
- go to a different chat, select language #2
- switch back to the original chat (in language #1), now language #2 is selected as the default keyboard instead of #1.

**Expected result:** 
The default keyboard language is set depending on the chat.

### Device info

**Device**: iPhone SE
**iOS version**: 11.3.1
**Signal version: 2.24.1.0

### Link to debug log
https://debuglogs.org/66de904fc3bd77073d91057f4e8ae4f163985107b535dbe7113241866a7d6ac8.zip

Thank you!

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub. 

The forum is a better place to discuss this: https://community.signalusers.org/
