### ISSUE TITLE
Deliver doesn’t work

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3463]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
All past messages look as sent and no more as delivered even if they were delivered cause I know it and because my mate answered me 

### Steps to reproduce
Idk

**Actual result:** Messages are not shown as delivered

**Expected result:** Delivered messages should be shown as delivered

### Screenshots

![672622dd-49cc-46a9-8ff0-8f8932d615df](https://user-images.githubusercontent.com/34192761/40391289-060fc45c-5e18-11e8-95ff-d6787ee055e7.jpeg)

### Device info

**Device**: iPhone 6s

**iOS version**: 11.3.1

**Signal version:** 2.25.0.28

### Link to debug log

https://debuglogs.org/9923471a8617d42885fb36e60824b5e0973fc35e529b6a92fed5114ed0900435.zip

**Comment by michaelkirk-signal** [comment]
To clarify - this is for your existing messages, not for your newly sent ones?

Or are you seeing issues with your newly sent ones as well?

**Comment by leonardoporpora** [comment]
Existing messages. new work good

**Comment by michaelkirk-signal** [comment]
Thanks for the report. This will be addressed in the soon-to-be-released 2.25.1, pending apple's review.

Unfortunately for users who have already upgraded to 2.25.0, some delivery data was lost, so even after upgrading to 2.25.1, some pre-existing messages will continue to show as only "sent" when they were actually "delivered".

**Comment by leonardoporpora** [comment]
Ok, doesn't matter for my data just hope to be helpful for Signal users this is my target :+1: 
keep up the amazing work
