### ISSUE TITLE
Messages do not disappear on iOS

### ISSUE THREAD

**Issue by modisio** [signalapp/Signal-iOS#3465]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages (to self) do not disappear
iOS 11.3.1, Signal 2.25.0.28

### Steps to reproduce
- Send message to self (with "disappearing" set) from MacOS desktop client 
- Update app on iOS 11.3.1 to 2.25.0.28
- Message does not disappear on iOS but does disappear on MacOS

Note that subsequent messages (after update) do indeed disappear. 

### Device info

**Device**: iPhone 5s

**iOS version**: 11.3.1

**Signal version:** 2.25.0.8

**Comment by michaelkirk-signal** [comment]
We’re going to need more information.

To help me understand, it sounds like you sent the message from desktop before you upgraded on iOS?

Can you include a debug log from your iOS and desktop clients?

Can you send a (redacted) screenshot of the affected conversation?

**Comment by modisio** [comment]
Yes:
1. Send message to self from desktop
2. Get it on iOS app
3. Quit iOS app before message is supposed to disappear  
4. Later, upgrade app on iOS
5. Lauch app, message won't disappear


Desktop:
https://debuglogs.org/901233505bf5f5a1d7ea28ffa8040a2e887e927f67923d3f8f16113b4eb0c83b

<img width="592" alt="desktop" src="https://user-images.githubusercontent.com/22117932/40427396-35a58fd0-5e63-11e8-8bd3-8a8480e4b3c7.png">


iOS: Debug log was not set, sorry

![ios](https://user-images.githubusercontent.com/22117932/40427612-d1d1bc4e-5e63-11e8-8faf-89fe97eb4046.png)

**Comment by michaelkirk-signal** [comment]
Thanks for the notes - How about a screenshot of the *bottom* of that message? I'm trying to see if there's a timer in the footer.

**Comment by modisio** [comment]
Hope this helps:
![iosbottom](https://user-images.githubusercontent.com/22117932/40430788-897704ba-5e6b-11e8-8990-4a54e5621e92.png)

**Comment by michaelkirk-signal** [comment]
Thanks for your help. This will be fixed in the soon-to-be-released 2.25.1, which is just pending AppStore review.
