### ISSUE TITLE
I cant delete a chat group

### ISSUE THREAD

**Issue by lc20188** [signalapp/Signal-iOS#3466]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by lc20188** [comment]
https://debuglogs.org/93d894dcbf16df5073bfc4d69f4e3b2ebbf9b8143813a15e31dd5565f0d89c1b.zip

**Comment by michaelkirk-signal** [comment]
Can you please include a crash log?

To get a crash log:

1. Go to the iOS Settings app.
2. Go to Privacy.
3. Go to Analytics or Diagnostics & Usage.
4. Select Analytics Data or Diagnostics & Usage Data.
5. Locate the .ips crash log for Signal.
    The logs will be named in the format: Signal(DateTime).ips
6. Select the desired Signal log.
7.a iOS 11 users, tap the Share icon in the top right corner and jump to step 10.
7.b iOS 9&10 users, long press to see the option to highlight text and select the entire text of the log. It will end in EOF.
8. Once the text is selected, tap Copy.
9. Paste the copied text into an email.
10. Send the email to support@signal.org with a subject like:
  * "iOS Crash Log: (your github issue)"
  * Example subject: iOS Crash Log: Crash on launch #111
  * Example subject: iOS Crash Log: Crash when sending video #222

**Comment by michaelkirk-signal** [comment]
We can't proceed without a crash log. Please re-open if you can provide one.
