### ISSUE TITLE
Phone had to be reset, conversations not restored

### ISSUE THREAD

**Issue by resetthephone** [signalapp/Signal-iOS#3467]
At the Apple store yesterday we had to factory reset my iphone, we did a backup and restored from that. But the data from Signal did not return to the iphone after restore. How do we get it back?

- [Yes] I have searched open and closed issues for duplicates
- [Yes] I am submitting a bug report for existing functionality that does not work as intended
- [Yes] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Backup did not work.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

- Factory reset the store according to Apple.
- After taking a backup.
- Restore the iphone from backup.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Bug? No conversations returned to phone after restore.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Conversations back on Signal.

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3

**Signal version:** 2.25.0.28

**Comment by likyng** [comment]
Unfortunately, it is currently impossible to export/backup Signal messages. There is also no notice that it is impossible to backup your data, so that many people belive an itunes/icloud backup will indeed save their Signal chat history, as it does on e.g. WhatsApp. Apparently this is a "feature". 

For related information please see: #2542 and #967

**Comment by michaelkirk-signal** [comment]
Closing as dupe.

**Comment by resetthephone** [comment]
What the fuck! Are are my conversations not backuped?!?!!???
