### ISSUE TITLE
 Can't receive message when app in background

### ISSUE THREAD

**Issue by halocq** [signalapp/Signal-iOS#3474]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
(same as #3441, and I don't how can I re-open issue, so open new)when app inactive (not kill process), can't receive message, but when active start receive message.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone6s

**iOS version**: 11.3.1

**Signal version:** 2.25.0

### Link to debug log

<<redacted>>

**Comment by michaelkirk-signal** [comment]
Can you send me a screenshot of your system settings for Signal?

(Settings App > Signal)

**Comment by halocq** [comment]
![image](https://user-images.githubusercontent.com/11287047/40530249-985d3a7e-602a-11e8-800d-721582d66ea3.png)

**Comment by leonardoporpora** [comment]
Have you tried to  Re-register for push notifications? 
you have to got in Signal -> Settings -> Advanced -> Re-register for push notifications
Let me know if it works

**Comment by halocq** [comment]
I tried and it's failed, server's problem?

**Comment by michaelkirk-signal** [comment]
It looks like you're running a custom build of the app, in which case remote notifications will not work. This is an apple restriction that we cannot work around.
