### ISSUE TITLE
Text bubble is squished vertically

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-iOS#3476]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some text bubbles are squished vertically, resulting in illegible message.  This doesn't seem to be 100% of the time, but maybe 1 out of 3 times the steps below are acted out.

### Steps to reproduce
- switch between apps from signal, to another, back to signal
OR
- tap message notification to enter signal

**Actual result:** Text bubbles are squished vertically.

**Expected result:** Text bubbles always allow text to be readable.

### Screenshots
![image](https://user-images.githubusercontent.com/4967949/40497734-41ca7690-5f3a-11e8-9e0f-f50425a3ae1a.png)

### Device info

**Device**: iPhone 7

**iOS version**: 11.3.1

**Signal version:** 2.25.0 (but has happened for a few versions now...2.24.x for sure)

### Link to debug log
https://debuglogs.org/b9405bc007e04164c49b93e1d92b54ff23740b3f9d861f171ef185cf8f95aeab.zip

**Comment by devdrey** [comment]
It's very often! I'd even say 2 out of 3 times.
So annoying.

**Comment by michaelkirk-signal** [comment]
I believe this to be resolved. If you can reproduce, please re-open or file a new issue with fresh steps and debug log.
