### ISSUE TITLE
Signal icon is greyed out on my iPhone

### ISSUE THREAD

**Issue by adriansegar** [signalapp/Signal-iOS#3481]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal icon is greyed out on my iPhone

### Steps to reproduce
None

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Touching the icon does nothing. It cannot be deleted. No update shown as available in store.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)
App should be openable by touch, and deletable.

### Device info

**Device**: iPhone 6S MKRY2LL/A

**iOS version**: 11.3.1

**Signal version:** 4.3

### Link to debug log
There is no debug log (and I can't enable one because I can't access Signal)

**Comment by michaelkirk-signal** [comment]
Can you double check your Signal iOS version number? What you have listed doesn’t make sense.

Can you launch the AppStore and upgrade to anything newer?

**Comment by michaelkirk-signal** [comment]
This doesn't sound like anything we'd have control over, but please be sure you've got the latest installed from the app store.
