### ISSUE TITLE
Cannot invite contacts

### ISSUE THREAD

**Issue by ftastisch** [signalapp/Signal-iOS#3484]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot invite contacts to Signal, similar to this bug, which should have been fixed 2 years ago: https://github.com/signalapp/Signal-iOS/issues/922

### Steps to reproduce
-Click Settings
- Invite Your Friends
- Message/Mail (does not matter)
- Select contacts
- Click done
- Nothing happens.

**Actual result:** 
Goes back to Signal conversations.

**Expected result:** 
Message window to edit and send Signal invitations.

### Device info

**Device**: iPhone 8

**iOS version**: 11.3.1

**Signal version:** 2.25.1.1
### Link to debug log
https://debuglogs.org/7bde15c9c5a82ba0b2932aab88a879b6d461c54035a0c02cbdfd9338cafa497c.zip

**Comment by Flixoba** [comment]
I have exactly the same problem,
Signal version 2.25.1.1

**Comment by alexander-sibert** [comment]
I have also the same problem. Generally at the moment Signal is very buggy. Also if i share a link with additional custom text it don't show it on Signal. Only if i type in Signal a message then it show the shared text. Also Signal calls aborting or we don't hear each other.

**Comment by biozitronenbaum** [comment]
Same Problem here with iPhone 6s and iOS 11.4.

**Comment by michaelkirk-signal** [comment]
This will be fixed in the 2.26 release.

**Comment by SVsalon** [comment]
Same Same. 2.25.1.1 Iphone IOS 11.4
When will 2.26 be released?
