### ISSUE TITLE
iOS App should have option to look like Desktop / Android App

### ISSUE THREAD

**Issue by jotkali** [signalapp/Signal-iOS#3499]
The Desktop and Android app have a colourful appearance that mark each participant with a different colour. This makes following a conversation with multiple people MUCH easier than the little 9 point grey person title currently displayed in the iOS app

Please add an option that lets conversations in the iOS app have the appearance of the desktop / android app.

Thanks for Signal.

**Comment by michaelkirk-signal** [comment]
Sorry to bounce you around like this, but we no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
