### ISSUE TITLE
Signal/Video Icon in contacts app

### ISSUE THREAD

**Issue by biozitronenbaum** [signalapp/Signal-iOS#3509]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description
Signal button in iOS contacts-app only Shows up 1x.

### Steps to reproduce
- open iOS integrated contact app
- click on a contact who uses Signal too
- "Signal Icon" appears instead of "Video Icon"
- press back button
- open contact who uses Signal too again
- "Video Icon" appears instead of "Signal Icon"

**Actual result:** 
- "Video Icon" appears instead of "Signal Icon"

**Expected result:** 
- "Signal Icon" should appear instead of "Video Icon"

### Screenshots
![signal](https://user-images.githubusercontent.com/39809771/40806193-0b450616-6521-11e8-9a76-55a3f92a1b56.JPG)
![video](https://user-images.githubusercontent.com/39809771/40806194-0b71b558-6521-11e8-83fa-d46188046efd.jpg)

### Device info
**Device**: iPhone 6s

**iOS version**: 11.4

**Signal version:** 2.25.1.1

**Comment by michaelkirk** [comment]
We don't have any control over what shows up in the systems contact app. It looks like they remember which method you last used to contact that person.

FYI you can longpress on that video button to expose an action sheet of other video calling services.
