### ISSUE TITLE
Current state of backup / export of chats not documented

### ISSUE THREAD

**Issue by basnijholt** [signalapp/Signal-iOS#3510]
There are two open (but locked) issues regarding backups: https://github.com/signalapp/Signal-iOS/issues/967 and https://github.com/signalapp/Signal-iOS/issues/2542.

Recently (March 2018) @charlesmchen made [many commits](https://github.com/signalapp/Signal-iOS/search?q=backup&unscoped_q=backup&type=Commits) that look like some system for backups has been put into place, however, it doesn't seem to be documented of what this code exactly encompasses or (and if) what is needed to finish it.

Currently, there is an [open bounty](https://www.bountysource.com/issues/28598496-message-export-backup) on BountySource of $515 with 10 different supporters, so clearly this is a much wanted feature. 

**Please**, let's **NOT** go down the same path as in the locked issues, so don't post messages like "Yes, I want this" and keep the discussion foccused on the code.

I also found this [discussion](https://whispersystems.discoursehosting.net/t/ios-backup-keeping-message-history-when-switching-phones/1736) on the whispersystems.discoursehosting.net forum.

**Comment by michaelkirk-signal** [comment]
Signal iOS does not currently support backups.

We don't use GitHub for discussions or feature requests, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
