### ISSUE TITLE
Message order on iOS and Windows not aligned

### ISSUE THREAD

**Issue by stjep** [signalapp/Signal-iOS#3511]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Order of messages received in iOS Signal makes no sense, and does not match Windows desktop Signal app.

This does not appear to be a repeat of #655, #691, #2983, or #3447. 

### Steps to reproduce
- Receive multiple messages while offline, in group chat
- Open iOS Signal app, messages are in incoherent order
- Open Windows Signal desktop app, messages are in the order they were sent

**Actual result:** 
See screenshots below for message order on iOS and Windows.

The sent time for the messages in iOS is as follows, working from top to bottom:
- Sender L; Today 7:40am
- Sender J; Today 4:18am
- Sender J; Today 4:19am
- Sender J; Today 7:41am
- Sender J; Today 4:18am

All messages have the same timestamp and were downloaded as one batch: Today 9:40am

**Expected result:** The order of messages should be as in the Windows app. The message that appears to be the newest on iOS was actually the first sent.

What is the oldest message should be second-to-newest.

### Screenshots

![Message order list on iOS](https://user-images.githubusercontent.com/3305421/40816736-e9afe7f2-6591-11e8-9f17-6ab129171ae1.JPG)

![Windows desktop app](https://user-images.githubusercontent.com/3305421/40816814-432cc64c-6592-11e8-9bce-5a7ff63c38ec.PNG).

### Device info

**Device**: iPhone X

**iOS version**: 11.4.0 (where bug noticed); 11.4.1 (when debug log generated)

**Signal version:** 2.25.1.1 for iOS; 1.12.0 for Windows

### Link to debug log

Not sure if the debug log captures the bug, but here goes. Will update if I can get a fresher one.

https://debuglogs.org/7f7b71abe75fbb22501de1cae17bce43725616c4fd4e6af3144d054e0e1de054.zip
​

**Comment by michaelkirk-signal** [comment]
Can you give me the last 2 digits of L's phone number and the last 2 digits of J's phone number?

**Comment by stjep** [comment]
J ends in 58; L in 54. Anything else I can provide?

**Comment by stjep** [comment]
Opening Signal this morning, had the same experience. Order is fine on Windows but messed up on iOS.

Another debug log for you: https://debuglogs.org/87f98bc9da6131142006627e265d2e353d6bcf3bd51dc14fed48032e25c86e4d.zip

**Comment by stjep** [comment]
I'm adding this as a comment because it may be related to this bug, but messages sent on iOS (using the share sheet) not appearing in the Windows client later.

https://debuglogs.org/04516c35470fceace03d91e4d5718110d15337e1cac7393bed3f707e95bc14de.zip
​
![ios missing messsage](https://user-images.githubusercontent.com/3305421/40949148-fd9388c0-68af-11e8-93ba-10bf09e533fa.png)
![windows missing message](https://user-images.githubusercontent.com/3305421/40949149-fdcc728e-68af-11e8-934c-dadc6ff02aea.PNG)

**Comment by laurens94** [comment]
I encountered a problem that might be related, in a private chat between Android and iOS. Messages from Android were shown in the wrong order on iOS after the iOS device has been offline for a few hours. The messages are shown correctly when I open them on Signal for Windows.

**Comment by JiNova** [comment]
I have encountered this problem when using Signal on Linux and MacOS as well, while the iOS App was offline. My chats' messages (1-1 and group chats) are out of order on iOS while they are displayed correctly in all Desktop instances linked to my Signal account.

**Comment by sarahscheffler** [comment]
I have encountered this problem when the iOS device is online (via wifi) but while the Signal app on the phone is not active.  I can send screenshots if it would help.  Usually, my macOS Signal desktop version displays messages in the correct order, but the iOS app rearranges them.  This problem seems to have gotten worse sometime in the last couple months (but this could just be my perception).

I understand the purpose of ordering messages by receive time rather than send time (so that you will not miss them if they were sent a long time ago).  But surely if there is a batch of messages all received around the same time (say because the device was offline), they should be displayed in send order relative to each other?

**Comment by gravyboot** [comment]
This is happening to me now, messages sent/received on windows show up out of order in iOS. https://debuglogs.org/1ba84057ceb6188623dd3d4c07b6f0821d44a4f2564c5507586d5d7d747f4c2f.zip
