### ISSUE TITLE
Permanent "phantom" notification badge without any visible new/unseen message

### ISSUE THREAD

**Issue by gsbabil** [signalapp/Signal-iOS#3523]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

## Permanent "Phantom" Notification Badge

I have a permanent notification badge next to the contact name
(indicating to a new message), but there's no new message within
the conversation thread.

I have scrolled from the very top to bottom of that thread looking
for the new message (and to get rid of the notification badge),
but the notification badge won't go away.

The notification badge appears both on iOS home-screen on the
top-right corner of the Signal app icon, and also within the Signal
app main view next to the contact's name. Unfortunately, I'm not
very sure how to reproduce this, but having a quick way to delete
all the unread notifications i.e. "mark all read", I think could be
rather useful.

### Steps to reproduce

Unfortunately, I don't have a sure-fire way to reproduce this, but I
have been able to repeat this a few times unpredictably by sharing
content from a different app to Signal as discussed in #3521.

**Actual result:**

- Notification badge without an actual new message

- The notification badge wouldn't disappear even after scrolling to
  the very top to bottom on the given conversation

**Expected result:**

- There shouldn't be any notification badge without corresponding
  new/unseen message(s)

- A _"Mark All as Read"_ option could be useful eliminating these
  "phantom" notification badges, and marking all unimportant
  messages within a given conversation thread as read.

### Screenshots

![signal-2018-06-02-182339](https://user-images.githubusercontent.com/1061108/40872569-d4d5210a-6693-11e8-8874-7bebbf146bbc.png)

![signal-2018-06-02-182352](https://user-images.githubusercontent.com/1061108/40872578-e7102446-6693-11e8-86d5-f0b12e3ec6e5.png)

### Device info

- **Device**         : iPhone 6
- **iOS version**    : 11.3.1
- **Signal version** : 2.25.1.1

### Link to debug log

- https://debuglogs.org/c27e0b7bf9212075a3174ddd6c627d99584ca80788d184d85a5235cbdbebc481.zip

**Comment by leonardoporpora** [comment]
I had the same issue and in my case this was a problem with time stamp look if the time stamp of that chat is right or not. If you have like 7:25 am tha 7:30 am and than 7:26 am by deleting the 7:30 am you should be able to fix this problem. Take a look and lemme know

**Comment by gsbabil** [comment]
Hi @leonardoporpora,

Thanks for the prompt reply.

I just went through my messages looking for out of order timestamp
that you advised above. I do not have any such message.

I had two media messages (photos) with same "sent time". I deleted
both of them, but the "phantom" badge remains!

Thank you.

**Comment by FMMT666** [comment]
Same here, since ~9/2017 on iPhone6 and iPhone 8.
It survived all iOS and Signal versions since then.

In the beginning, it helped to rapidly open/close/open/close Signal
and the notification disappeared. This stopped with later versions.

Here, this "phantom 1" seems to be related to one specific contact and
it looks like an offset problem:

- no new message: "1" is displayed in home screen
- this contact writes a message: "2" on home screen
- open Signal but don't read message, a "1" is displayed beside the contact
- close Signal and the "2" disappears, nothing is displayed
- open Signal, read the message and we're at where we started

We mutually already deleted and renewed our "Signal friendship", but that didn't
change anything. Also, the "phantom 1" was displayed while the contact was removed.

**Comment by FMMT666** [comment]
The update to v2.34.026, two days ago, fixed it for me.
Almost crying :'-)

**Comment by Travel-tech** [comment]
I also have the same issue. I'm on iOS 12.4 and using Signal 2.41.1.2, and the phantom notification keeps showing up. Can't find any messages on my linked device that is new either. I've deleted all the threads I no longer want, but that also has not sorted the issue out. Any suggestions?

**Comment by demkodo** [comment]
I hereby report that this phantom notification bug is still a thing. Tried every step from the [documentation](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#ios_notifications_troubleshooting), to no avail. It's driving me nuts :) The fresh update to version 3.13.2 did not solve it. I'm on iOS 13.6. Thanks in advance!

**Comment by dantler** [comment]
@travel-tech There are clean repro steps for one source of phantom badge notifications in #4526 .  Not sure if this is related to your issue.

**Comment by tundrablasen** [comment]
Having the same issue. All iOS versions up to date

**Comment by starboynz** [comment]
I got it!
I have had 16 unread messages for a couple months and now I got rid of them
What it was was this: One of my contacts (a guy called AC) changed his phone and his verifiation number.
AC was in 16 group chats with me and other people, some years old.
Each of those group chats had an alert to tell everybody that AC changed his number.
They never showed up until today I happened to search for AC and all 16 groups came up from years ago with AC in them and this alert in each one telling me hi changed his number. Once I acknowledged them all the alerts went away 

WOOHOOOO!!!!

**Comment by doji-high** [comment]
Yes, I'm having this issue now too, years later after this report was initially submitted.  The "phantom badge bug" is back!  Exactly as the OP described it.  

I've submitted a bug report to Signal Support via the website... we'll see what happens.
