### ISSUE TITLE
Signal needs constant access to contacts

### ISSUE THREAD

**Issue by stillalex** [signalapp/Signal-iOS#3530]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It used to be that Signal did need constant access to phone contacts. I would allow it temporarily to pull profile data for an contact and then cut it again, and it would work, but not anymore. If it doesn't have access to my contacts Signal would only display the phone number and no longer the name (as before) and the share feature is effectively non functioning.

### Steps to reproduce
- go to settings, Signal, toggle off access to contacts
- open Signal
- notice that the contacts are replaced by their respective phone numbers
- 'share' also doesn't see any contacts
- go to settings, allow access to contacts
- open Signal, see proper names of contacts
- disable access to phone contacts
- open Signal see numbers again, it forgot all of the contact info it had

**Actual result:** I only see phone numbers where the names used to be.

**Expected result:** This may have been the previous behavior, not sure but once I would allow access to contacts Signal would grab the name (and photo) and use them even if in the future I would cut access to phone contacts

### Device info

**Device**: iPhone SE

**iOS version**: 11.3

**Signal version:** 2.26.0.20

**Comment by mailinglists35** [comment]
this is happening after latest testflight update. when i go to photos and attempt to share a photo to signal, i used to be able to choose a phone number (contacts access always off) and it also said the signal user name.
now i get zero numbers to send my photo to
this is very frustrating https://imgur.com/a/sogPBMc

**Comment by michaelkirk-signal** [comment]
@mailinglists35 - just to clarify, do you have contact access enabled in System Settings > Signal ?

**Comment by mailinglists35** [comment]
no, i explicitly deny access to contacts to all apps on my smartphone.

ps: latest testflight has fixed this for me, working normally again
