### ISSUE TITLE
[Invite issue] Contacts with multiple Numbers

### ISSUE THREAD

**Issue by linus02** [signalapp/Signal-iOS#3531]
When a contact with multiple numbers Is choosen for an Invite, only the first number of this contact will be used for the invitiation message, No matter if the number Is landline or cell!

**Comment by mhbmd** [comment]
I am a new user of Signal and had this issue with my first invitation to a friend from my Contacts. The invitation defaulted to the first phone number listed, a business land line, and, of course, did not go through to the intended recipient. I see no way to work around this issue, as there does not appear to be a feature to choose the number for the recipient.
