### ISSUE TITLE
Crashes after update 

### ISSUE THREAD

**Issue by dd121** [signalapp/Signal-iOS#3544]
### Bug description
After updating to latest version on Iphone 6 the app will start up briefly and it says "database optimaliseren, this can take a few minutes" then after e few seconds the app closes of crashes.

The funny thing is that I am getting pop-up messages that I have a new message, but as I said I can't open the app.

### Steps to reproduce
- just open the app and everytime the symptom as described above will appear.

**Actual result:the app closes or crashes

**Expected result: after optimising the database i would expect the app to open.

### Device info
<
**Device**: iphone 6

**iOS version**: 11.4

**Signal version:** 2.25

### Link to debug log
will send by mail

**Comment by michaelkirk-signal** [comment]
The latest version of Signal is 2.25.3, can you make sure you're on the latest release?

Can you also check for a crash log?

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by dd121** [comment]
Oh, sorry, my bad. Yes I have latest version 2.25.3 and I already emailed the crashlogs.

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
