### ISSUE TITLE
No screenshot block

### ISSUE THREAD

**Issue by SyntaxxxErr0r** [signalapp/Signal-iOS#3560]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
I disabled the bkocking of screenshot for one message. Went to turn it back on. Can not be found. 

### Steps To reproduce

Turned phone off and on. 
Exited the app and restarted. 
Checkee iOS settings
CheckEd signal settings. 
Took bug report
https://debuglogs.org/6e8d742c6b3b4a22f460d9b402c550235b33444e11e6bc6adb0280b29e5afab7.zip

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
No available settings to resume blocking screenshots.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Should be able to resume blocking the ability to screenshot.

### Device info

**Device**: iphone 6s

**iOS version**: 11.4.1

**Signal version:** 2.25.3

### Link to debug log

https://debuglogs.org/6e8d742c6b3b4a22f460d9b402c550235b33444e11e6bc6adb0280b29e5afab7.zip

**Comment by michaelkirk-signal** [comment]
> I disabled the bkocking of screenshot for one message

There seems to be some confusion - Signal iOS has never supported screenshot blocking.

We do offer "screen security" (and continue to do so). However, this doesn't block screenshots. Instead it obscures the contents of the app in the app switcher. To configure this go to "Settings > Privacy".

**Comment by SyntaxxxErr0r** [comment]
sorry for my delay in response. i had actually forgotten that i made this bug report. thank you for your reply.

for some reason i was under the impression that screenshots could be blocked in the ios like they are in android.  I use signal on all of my devices, and in fact i make everyone trying to call me or text me, do so via signal.  they can try to do so the "normal" way, and i will either ignore it entirely or i just wont see it till months later. lol. so they have learned that if you want to contact me, you must do so in signal.
