### ISSUE TITLE
iOS 2.25.3 crashes on launch

### ISSUE THREAD

**Issue by jang** [signalapp/Signal-iOS#3561]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to the latest version of Signal 2.25.3, it always crashes on app launch.  The opening screen (blue Signal logo) appears for a brief second before it crashes.  Running on iOS 11.4 on iPad mini with Retina display (A7).  All previous versions of Signal ran just fine on the iPad.  I will send the crash log separately but I can't access the debug log (as the app crashes on launch).

### Steps to reproduce
- Open Signal app

**Actual result:**
App crashes, returns to iOS app screen.

**Expected result:**
Signal launches

### Screenshots

N/A

### Device info

**Device**: iPad with retina display

**iOS version**: 11.4

**Signal version:** 2.25.3

### Link to debug log

None (can't open app to access debug log).

**Comment by michaelkirk-signal** [comment]
Thanks for the report - do you know what version you were running *before* this upgrade?

And do you recall when you last successfully launched on that iPad?

**Comment by jang** [comment]
Note that this also means the device was running iOS 11.3.1 at that time (iOS 11.4 wasn't released yet).  I don't know if the combination of iOS 11.3.1 and Signal 2.25.3 works on the device because there was no usage then.  But for sure the crash occurs on iOS 11.4 and Signal 2.25.3.

**Comment by jang** [comment]
Ops, last successful launch and usage on the iPad was Jun 8 (while it was behind a country firewall).

**Comment by jang** [comment]
Here's the latest crash log on iOS 11.4 and Signal 2.26.0


[Signal-2018-07-01-143529.ips.txt](https://github.com/signalapp/Signal-iOS/files/2153056/Signal-2018-07-01-143529.ips.txt)

**Comment by michaelkirk-signal** [comment]
Hey @jang - I believe we addressed this in the latest (2.27) release. Please reopen if this issue is still present.
