### ISSUE TITLE
Notifications don't clear when already on conversation 

### ISSUE THREAD

**Issue by jschneier** [signalapp/Signal-iOS#3585]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Receiving a message while on that conversation does not clear the notification.

### Steps to reproduce
- Navigate to a conversation
- Receive a message from that conversation partner
- Open the app which will land you immediately on the conversation
- Click back to the inbox view
- The notification isn't cleared

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Notification is cleared

### Device info

**Device**: iPhone SE
**iOS version**: 11.4
**Signal version:** 2.25.3

**Comment by michaelkirk-signal** [comment]
How long were you in the conversation when this happened? To avoid a race condition where you receive a message just as you're leaving, we have a naive delay before things are marked as read.

**Comment by leonardoporpora** [comment]
I had the same problem and it was like when I was swiping to main page and a message got delivered it didn’t look as read
