### ISSUE TITLE
Not listing Signal Contacts from MS Exchange container

### ISSUE THREAD

**Issue by blahdeblahde** [signalapp/Signal-iOS#3595]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal seems to be unable to access my contacts at all despite having all the right permissions. 

### Steps to reproduce
- Install Signal on iOS 11.4
- Grant all requested permissions
- Open Signal
- Click the "New Message" icon
- No contacts show at all, just the Find by PHone number and Invite friends
- Click "Find by Phone Number"
- Enter a phone number of someone who is in your contacts list
- No results show up, it just starts a message to the phone number.
- Tap the phone number at the top of the message where it says "Tap here for settings"
- Click "Add to existing contact"
- The only contact that shows up is myself

- I am not sure if this is related, my contacts are managed by an Exchange server. Signal didn't used to have a problem with this and that state has been the same for years.

**Actual result:** 
See description above. No contacts are listed at all in any situation. Prior to reinstalling Signal it was not finding new contacts.

**Expected result:** 
Find and use my iOS contacts

### Screenshots
![2018-06-25 10 59 47](https://user-images.githubusercontent.com/24398981/41880209-bbff7c56-7891-11e8-929b-f43e90ddae51.png)

![2018-06-25 16 00 30-2](https://user-images.githubusercontent.com/24398981/41880240-dbfc6c1c-7891-11e8-990c-d7aa38326e4c.jpg)

### Device info

**Device**: iPhone 6s

**iOS version**: 11.4

**Signal version:** 2.26.0.26

### Link to debug log
https://debuglogs.org/daadc0981892bc70e13941ab5cb18869bc22d38495a8b4acc785bce7fe74cf69.zip

**Comment by michaelkirk-signal** [comment]
@blahdeblahde - can you verify that you have given Signal contacts access in System settings > Privacy > Contacts

And can you verify that any of those people are Signal users? We only show those of your contacts who are also Signal users.

**Comment by blahdeblahde** [comment]
Signal contacts - confirmed. Do you want a screenshot?
I can verify; I have had people who are in my contacts send me Signal messages and they show up only as the phone number followed by their profile name

**Comment by michaelkirk-signal** [comment]
@blahdeblahde - is this a corporate or otherwise restricted devise? e.g. with parental controls?

**Comment by blahdeblahde** [comment]
Nope. No restrictions. It has a corporate policy but that hasn't been updated since before Signal/contact integration broke. 

As noted earlier, the default contacts are from the corporate Exchange account

**Comment by Nurialam** [comment]
aida08787@gmail.com

**Comment by michaelkirk-signal** [comment]
> As noted earlier, the default contacts are from the corporate Exchange account

Right, I don't doubt that's related.

As a test, do you have a convenient way of adding a signal contact to your non-exchange account?

**Comment by blahdeblahde** [comment]
Yup, tried it. It appears to create a contact that Signal can see but that isn't synced with the Exchange contacts. So it is searching/creating them locally despite the configured default for the phone. I think this qualifies as a bug?

**Comment by michaelkirk-signal** [comment]
Thanks for the research!

Would you be willing to install a test version of Signal to test the fix? 

If so could you contact support@signal.org and reference this issue with the subject "re: GH #3595 interested in AdHoc build"

**Comment by blahdeblahde** [comment]
I contacted support but haven't heard back about getting a test build

**Comment by Genis-Sage** [comment]
I don't know it's related but to me it seems to be the same problem
https://faq.whatsapp.com/en/iphone/22077138/?category=5245236

Exchange and contact sync are not so easy since iOS 11.3
and I don't know your version history

since I'm not influenced by this problem, I also can't state if it change again with iOS 11.4

**Comment by blahdeblahde** [comment]
I have found an explanation of the problem - https://discussions.apple.com/thread/8338871
It appears it is an MDM configuration that was changed in 11.3 to enforce behavior against contacts. 
To fix it you need to get the app registered in the MDM as "managed"
