### ISSUE TITLE
Calls are a mess

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3596]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There are multiple issue in calls like:
- i Call Bob he answers me and I hear his voice and the bip of the ringing (you know when the others phone rings in your phone  u hear bip) and he doesn’t hear me. 
-if I close the call while Bobs phone is ringing after the close I see call failed and it comes up 2 times 

### Steps to reproduce
Idk

**Actual result:** calls don’t work as they should

**Expected result:** call should work

### Device info

**Device**: iPhone 6s

**iOS version**: 11.4

**Signal version:** 2.27.0.4

### Link to debug log

https://debuglogs.org/a252c63e2619ce941b097b6e6b59723207e8e960c8eb80dc1d8662655c44ea13.zip

**Comment by nimdajitam** [comment]
Similar here but never happened while calling users of Android version of Signal, iOS to iOS users only.

Usually I'm the perse who is heard but don't hear the other side. 

iOS version: 11.4.1
Device: iPhone 7 Plus
Signal version: 2.27.1.4

**Bug is present for a year at least.**

**Comment by nimdajitam** [comment]
Seems related: https://github.com/signalapp/Signal-iOS/issues/3351

**Comment by oxoocoffee** [comment]
Same here

Calling from iOSs version 11.4.1, Signal Version 2.28.1
Receving Android (Will provide more info about device soon)

**Comment by michaelkirk-signal** [comment]
A handful of calling issues have been resolved since this was created.

If you have calling issues in the future, could you please open a new issue with fresh debug logs instead of resurrecting this one? A lot of the details in this one are now irrelevant.
