### ISSUE TITLE
In some group I get group update without any user interaction is this dangerous?!!

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3637]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In some group I got the message group update group update many times without any update from anyone of the group in fact I checked and there is none new in the group. Is there a possibility that someone is spying and found a way not to be shown as a member?!

**Actual result:** group updates without any interaction 

**Expected result:** Group shouldn’t update

### Device info

**Device**: iPhone 6s

**iOS version**: 11.4

**Signal version:** 2.27.0.4

### Link to debug log

https://debuglogs.org/4c4f5fb5e60e577fa2fb0e62a72a52f6169f27c084687e67666239ba7bcb1ae4.zip

**Comment by michaelkirk-signal** [comment]
This is expected to happen when someone in the group requests group info. This can happen for example if they reinstall their device, or otherwise get their local group sync out of state.

Also, we don't use Github for discussion, please use the forums for that.
