### ISSUE TITLE
Navigating to message via full text results is very slow.

### ISSUE THREAD

**Issue by acoffman** [signalapp/Signal-iOS#3645]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Finding results in the new "full text search" is very quick (and building the index didn't take long at all either!). Unfortunately, actually _navigating_ to a result is extremely slow for large conversations.

### Steps to reproduce
- Have a long running conversation
- Search a text string
- Find a result that's old (in my case its a message from 2016)
- Select the result
- Wait... For my example two year old message, I timed it at 1 minute and 17 seconds of waiting before the app responded. 

**Actual result:** 

It takes over a minute to load the conversation view, and even then it hangs for another second or two before becoming responsive.

**Expected result:** 

It should navigate to the selected message in a reasonable amount of time.

### Device info

**Device**: iPhone 7

**iOS version**: 11.4

**Signal version:** 2.27.0.7

I can provide a debug log or any other information as needed.

**Comment by michaelkirk-signal** [comment]
The latest beta includes some changes which should better handle navigating to old search results.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
