### ISSUE TITLE
Messages delivered from desktop result sent from iPhone  

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3668]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Alice sent A message to Bob from the desktop that is linked with signal for iPhone and in the desktop (in my case linux) looks like delivered whereas in the iPhone the same message looks like sent 

### Steps to reproduce
- send a message from signal desktop
- wait till u see delivered in the desktop 
- look in the iPhone 
- you will see ‘sent’

**Actual result:** A message delivered looks like sent

**Expected result:** message should appear as delivered as in the desktop

### Device info

**Device**: iPhone 6s

**iOS version**: 11.4

**Signal version:** 2.27.0.4

### Link to debug log

https://debuglogs.org/b4d13f1d1d1d1f0612b93dce52e7f6d5d26cfb52ba096e1529042a78dcdf9ea7.zip

**Comment by eaglejoseph1993-alt** [comment]
> * [x]  I have searched open and closed issues for duplicates[x]  I am submitting a bug report for existing functionality that does not work as intended[x]  This isn't a feature request or a discussion topic
> 
> ### Bug description
> Alice sent A message to Bob from the desktop that is linked with signal for iPhone and in the desktop (in my case linux) looks like delivered whereas in the iPhone the same message looks like sent
> 
> ### Steps to reproduce
> * send a message from signal desktop
> * wait till u see delivered in the desktop
> * look in the iPhone
> * you will see ‘sent’
> 
> **Actual result:** A message delivered looks like sent
> 
> **Expected result:** message should appear as delivered as in the desktop
> 
> ### Device info
> **Device**: iPhone 6s
> 
> **iOS version**: 11.4
> 
> **Signal version:** 2.27.0.4
> 
> ### Link to debug log
> https://debuglogs.org/b4d13f1d1d1d1f0612b93dce52e7f6d5d26cfb52ba096e1529042a78dcdf9ea7.zip
