### ISSUE TITLE
.sh: line 2: /usr/local/bin/carthage: No such file or directory

### ISSUE THREAD

**Issue by wangJun-Ocean** [signalapp/Signal-iOS#3673]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michaelkirk-signal** [comment]
Hi @wangJun-Ocean. We only use Github for reporting bugs with the AppStore and TestFlight releases. 

For developer support, please use the community forum: https://community.signalusers.org/

If you are having trouble building Signal, please make sure you're following the steps in:
https://github.com/signalapp/Signal-iOS/blob/master/BUILDING.md

In your forum post, include the last successful step and the first failing step, as well as the full error output.
