### ISSUE TITLE
Not able to build code and getting build time errors for missing files/frameworks

### ISSUE THREAD

**Issue by ManishKatoch** [signalapp/Signal-iOS#3690]
### Bug description
I cloned master branch of the project but I am not able to build the project in my local machine and getting build time errors.

### Steps to reproduce
1. Clone project from master branch
2. Try to build the project
3. Restore Pods
4. Still some files are missing and causing errors

**Actual result:** 
Project should build on local machine but we have errors.
here is the screenshot

![1](https://user-images.githubusercontent.com/6924467/42578835-aaca773c-8544-11e8-9df8-bbcc55544162.png)

**Software versions:**
macOS version 10.13.4
xcode Version 9.2
cocoapods-1.5.3

Please share feedback if you have any ideas?
I am still trying to debug issues and will post progress in comments on the same ticket.

Thanks!

**Comment by michaelkirk-signal** [comment]
Hey @ManishKatoch - we don't use Github for developer support, only for reporting bugs in the released application.

For developer support please see the community forums at: https://community.signalusers.org/

Take a look at BUILDING.md, if you have trouble post on the forum with the step you got stuck at and any error output.
