### ISSUE TITLE
Crashing On Specific Conversation

### ISSUE THREAD

**Issue by JasTySYmKeq93EaCPhWxNBtHwJh6** [signalapp/Signal-iOS#3694]
- [ Y] I have searched open and closed issues for duplicates
- [ Y] I am submitting a bug report for existing functionality that does not work as intended
- [Y ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Crashing On Specific Conversation

### Steps to reproduce
- Send or receive message from specific individual.
- Signal crashes immediately. (Works on desktop with this individual strangely enough).

**Actual result:** Application crashes.

**Expected result: View messages/Send messages.

### Screenshots
N/A

### Device info

**Device**: iPhone 8

**iOS version**: 11.4.1

**Signal version:** 2.27.1.4

### Link to debug log

https://debuglogs.org/00481384d1a87837c006306bfeb7ee3866baa6475951f19fb6e5ab9efa0e1f03.zip

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
Summary: iOS crashes only on a specific person (that used to work) anytime I send them or they send me messages.
Desktop works okay though.

All other conversations work fine on iOS.

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
Another thing I noticed is usually desktop conversations are in sync with iOS conversations.  I see the person's txts and I see my txts.

On this one specific person on desktop I see their txts but never anything I send on iOS (I can get msgs to go through on iOS, the app just crashes after each msg, they go through *mostly).

**Comment by michaelkirk-signal** [comment]
Do you have any recent crash logs that you can include?

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by bbelo** [comment]
Happens to me too. The specific person is on Android.

**Comment by troyjfarrell** [comment]
Debug log and iOS crashlog sent to support@signal.org

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
FYI this one can be closed.  This was resolved a few updates ago from what I can tell.
