### ISSUE TITLE
Increase sound volume on iPhone

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-iOS#3701]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When calling someone with earphones, volume of a sonar is too low, even if sound is on maximum. Then Signal starts ringing (you can hear ringing sound), and volume of this sound is a little higher. And then you start talking, and volume is much more higher, however, it seems it still has some maximum limit - i.e. if I am calling through Signal (with earphones volume on maximum) sound is much lower than if I am calling via GSM network (also with earphones volume on maximum).

And it seems that this problem appeared with some update.

### Steps to reproduce
- put your earphones on
- start calling someone
- you can hear very quiet sonar sound
- when it starts ringing on the other side, ringing sound is a little bit louder
- when conversation is started, sound is even louder
- if you call a person via normal call, sound is much more higher.
  
**Actual result:** Sound levels are not the same. It should be possible to increase the sound when on earphones.

**Expected result:** Sound levels should be the same

### Device info
**Device**: iPhone 8

**iOS version**: 11.4

**Signal version:** 2.27.1.4

**Comment by nimdajitam** [comment]
Similar happens when using iPhone's speaker.

**Comment by ibuddieat** [comment]
This problem is still present (iPhone Xs, iOS 14.4.1).
