### ISSUE TITLE
signal crashes when swiping to delete conversation

### ISSUE THREAD

**Issue by foss-** [signalapp/Signal-iOS#3736]
### Bug description
Signal crashes 100% reproducible when swiping to delete a certain conversation. The issue is limited to that exact conversaion. Other conversations could be deleted without resulting in a crash.

### Steps to reproduce
Swipe to delete conversation OR swipe a bit and tap on "Delete"

**Actual result:**
Signal.app crashes

**Expected result:**
Conversation should have been deleted and app not crashed

### Device info

**Device**: iPhone 6 Plus

**iOS version**: 12b4

**Signal version:** 2.27.1.4 (2.27.1)

### Link to debug log
[Signal-2018-07-22-112813 crash on deleting conversation.txt](https://github.com/signalapp/Signal-iOS/files/2216872/Signal-2018-07-22-112813.crash.on.deleting.conversation.txt)

**Comment by michaelkirk-signal** [comment]
We recently made a change (https://github.com/signalapp/Signal-iOS/commit/48fb652d83b2c80d3e1861889484a5a5e57a1065) that I believe will address this. It's currently in beta.

If you're interested in trying out the Beta, please email support@signal.org with the subject "Sign me up for the iOS Beta"

If you do install the beta, could you reply back to this issue to let us know if it fixed it?

**Comment by foss-** [comment]
2.28.0.12 beta fixes this problem and I was able to delete the conversation in question no problem. thanks for all your work on signal. have a great day.

**Comment by michaelkirk-signal** [comment]
@foss- Even though it's now working for you - would you mind submitting another debug log?

Somehow your device was put into a bad state, and the debug log might help us better understand how you get there.

(Signal > Settings > Advanced > Submit Debug Log)

**Comment by foss-** [comment]
https://debuglogs.org/be6bfd834e56403dc4709fd5f19eb4ba4856d598476d967ae4780bdc943f2a4e.zip

Can't download the log but this is the link that got created. Let me know if you need anything else.

**Comment by michaelkirk-signal** [comment]
Shoot - looks like you enabled debug logging just before submitting, so none of the relevant stuff had been captured.

Thanks for trying anyway.

**Comment by foss-** [comment]
I keep logging disabled by default. Obviously should have let than enabled during testing, sorry :/
