### ISSUE TITLE
Recovering from iTunes backup turns disappearing messages into regular messages

### ISSUE THREAD

**Issue by marcschulder** [signalapp/Signal-iOS#3756]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After reinstalling my iPhone from an iTunes backup, a chat with disappearing messages was still containing those messages that had not disappeared at time of backup. These messages are now handled as normal non-disappearing messages and are staying in the chat. Right below them there is a new message that the other user set a timer and new messages are disappearing as intended.

### Steps to reproduce
- Set disappearing messages to 1 day
- Write messages
- Create iPhone backup on iTunes
- Reset phone
- Restore backup
- Look at chat.

**Actual result:** When restoring a backup, disappearing messages that had not yet disappeared at time of backup are still there and have no disappearance timer anymore.

**Expected result:** When restoring a backup, disappearing messages that had not yet disappeared at time of backup should still have their disappearance timer (if timer not yet exceeded) or have disappeared (if timer exceeded).

### Device info

**Device**: iPhone 7

**iOS version**: 11.4.0.

**Signal version:** 2.27.1.4.

**Comment by NiklasBr** [comment]
Are messages _finally_ being backed up? (disappearing messages obviously should not, at least those with expired timer).

**Comment by marcschulder** [comment]
Sorry, I just realised I remembered it partially wrong (I had not initially noticed the issue). It's not that text was retained on backup, but that when I restored from backup, the timer was not initially active for a few hours. Will update my report accordingly.

**Comment by michaelkirk-signal** [comment]
Hi @marcschulder - Signal on iOS currently doesn't back up any conversation data, so what you're seeing is a consequence of that.

Backups are an important feature and definitely on our radar, but we don't need an issue like this to track it.

In general feature requests and anything else which benefits from ongoing discussion is better suited for the community forum here: https://community.signalusers.org/

Thank you!
