### ISSUE TITLE
Privacy issue regarding screen security flaw

### ISSUE THREAD

**Issue by MicrosoftIsMalware** [signalapp/Signal-iOS#3765]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- Though I am uncertain as to exactly when this issue began, I believe it was after the new ‘consistent-with-iOS-UI’ first came to be.
- While it seems to have improved somewhat, screen security is still behaving erratically, though mostly it simply does not work in many cases.
- I did recognize a pattern before it’s began to improve, and this pattern still holds _mostly_ true.

**Actual result:** 
Signal’s screen is plain to view in many cases while app switching.

**Expected result:** 
Signal’s UI is hidden while multitasking no matter under what conditions / how one is using multitasking.

### Screenshots
![6be73d87-fd51-4239-9c70-a77fccf92481](https://user-images.githubusercontent.com/42001623/43533466-e091bb3e-9582-11e8-8307-78ac4229be65.png)
![106b329a-e70e-4336-9f36-4df5e0873a61](https://user-images.githubusercontent.com/42001623/43533468-e0b658f4-9582-11e8-911b-f458cfc3f193.png)
![f0f79064-f237-4e29-ad4a-2104f9879943](https://user-images.githubusercontent.com/42001623/43533469-e0d8b16a-9582-11e8-9343-73b0434b57bb.png)
![ac67b5bf-b6a9-4c7b-8d13-d7c710923d0d](https://user-images.githubusercontent.com/42001623/43533471-e0f23e50-9582-11e8-840e-c3b0e0941088.png)
![e26dfbb0-df96-4597-9995-06932c89c116](https://user-images.githubusercontent.com/42001623/43533473-e106fbe2-9582-11e8-8a39-e15e9967dfe6.png)
![2ec13739-fd7c-4232-ad4e-f925a5ef4b6c](https://user-images.githubusercontent.com/42001623/43533474-e117ba04-9582-11e8-97c4-bc3d093ab8e6.png)

### Device info
**Device**: iPhone 6 Plus

**iOS version**: 11.4.1β

**Signal version:** 2.28.0β (2.28.0.15)

### Link to debug log: 
https://debuglogs.org/7809e94d2d4df60946e608026c9422f127cd68ceca66ec87fb15d4788d84c118.zip

[Apologies for dual logs; I had already used my clipboard to copy something else.]

Thank-you all! :)

**Comment by michaelkirk-signal** [comment]
We don't have much control over this. Apple only guarantees that screen protection will be applied before the app is *Backgrounded*.

https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforHandlingAppStateTransitions/StrategiesforHandlingAppStateTransitions.html#//apple_ref/doc/uid/TP40007072-CH8-SW22

When you're in Signal and double-tap the home button to enter the app switcher, the app goes from "Active" to "Inactive" (but not yet "Backgrounded"). We actually do request that screen protection be displayed at this point, but iOS makes no guarantees that it will be applied until the app is "Backgrounded".

The app enters the "Backgrounded" state only once you leave the app switcher, either by entering another app or returning to your home screen.

**Comment by MicrosoftIsMalware** [comment]
Interesting though not surprising lack of cooperation on Apple’s behalf.

Perhaps I simply though mistakenly believed, for who knows what reason, that this was not always so. It has been quite awhile - near Signal’s iOS debut - that I’ve been fortunate enough to have access to what is essentially a tool, for both privacy, security, & safety.

I do appreciate the information; thank-you.
