### ISSUE TITLE
Crash on launch after upgrade to 2.28.0

### ISSUE THREAD

**Issue by Barracuda6** [signalapp/Signal-iOS#3777]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Immediately after upgrading to version 2.28.0 of the iOS app today, the app crashes on launch. The app still crashes after restarting the phone.

The debug logs seem to refer to a database issue similar to #3512.

### Steps to reproduce
If it helps any, my last actions included sending two photos to the same contact (one photo through the iOS Photos app sent to Signal, another photo selected from the camera roll directly through Signal), then I received a call from the contact. Later, I exported/deleted the photos from the phone using Image Capture on a macOS machine, and deleted the conversation with the contact in Signal. This was the only Signal conversation - none remained after it was deleted. I then exited the app and upgraded it through the App Store app. Attempts to reopen the app after this resulted in a crash.

### Device info

**Device**: iPhone 7

**iOS version**: 11.4.1 (15G77)

**Signal version:** 2.28.0

### Link to debug log
Crash logs were sent to support@signal.org today. I am unable to retrieve debug logs since the app won't open.

**Comment by Barracuda6** [comment]
Sorry, I meant to say "crash logs" in my original post. I sent those to the support email. I wasn't able to send any debug logs since the app won't open.

**Comment by Barracuda6** [comment]
The app is still crashing on launch after upgrading to app version 2.28.1 today. Additional crash logs were sent to the support email address today.

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
