### ISSUE TITLE
[suggestion] Pls add username feature.

### ISSUE THREAD

**Issue by rickycm** [signalapp/Signal-iOS#3778]
Please add username feature, that can be used to add friends or start a chat. Phone number is too sensitive. Most of the times we don't want to tell phone number. Especially in China, all the phone numbers are registered by real name.
Hope Signal app will be better and more popular. Thx.

**Comment by michaelkirk-signal** [comment]
Hey @rickycm we no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
