### ISSUE TITLE
Signal TouchID & Share Sheet prevents sharing

### ISSUE THREAD

**Issue by scottcarterco** [signalapp/Signal-iOS#3783]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sharing a screenshot from the share sheet when Signal has Touch ID locking causes the sharing to crash.

### Steps to reproduce
- Make sure Touch ID is enabled under Settings > Privacy in Signal.
- Take a screenshot on iOS.
- Tap on Screenshot in bottom left corner.
- Tap on Share icon in bottom left corner of screenshot edit screen
- Tap on Signal in share sheet.
- Touch ID kills the share moment and doesn't send.

**Actual result:** Touch ID prompts you for login and crashes the share moment and doesn't allow you to share.

**Expected result:** Touch ID should prompt you for login and continue on to share the image.

**Note:** This does not happen if sharing directly from Photos app.

### Screenshots
N/A

### Device info

**Device**: iPhone 6S+

**iOS version**: 11.4.1

**Signal version:** 2.28.0.15

### Link to debug log
https://debuglogs.org/d4c2863fea11b148a167d50878d67b367d07494ead4980620505f006daab0681.zip

**Comment by Mihahn** [comment]
Can't reproduce on Signal 2.28.1.5 and iOS 12.0 (16A5345f), it's working fine for me :)

**Comment by tzs1** [comment]
I have similiar issue. Signal 2.29.2.3 / iOS 11.4.1

**Comment by denver-s** [comment]
This bug has not happened again to me. Probably fixed.
