### ISSUE TITLE
Crash when searching through messages

### ISSUE THREAD

**Issue by sseneca** [signalapp/Signal-iOS#3784]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

After searching for any word which we'll call `keyword` and pressing on a message which contained `keyword` which is from a while ago, the app will hang for a while and then crash, OR the app will go to a black screen and if I exit the app and re-enter, it'll crash.

It seems to depend on how many messages have been sent since then. Searching for `keyword` and selecting on an appearance of it which is a little sooner to the time searching will make the app hang (like normal?) but eventually load the chat at that date.

### Steps to reproduce
- search for any word (in this example `keyword`)
- look for an appearance of the word from a while ago in an active chat, given that there have been many messages sent since then (for instance, I'm clicking on a message sent on June 30 in my example)

**Actual result:**

The app will hang for a while (around 4 minutes average out of 3 attempts) and then crash

**Expected result:**

Signal should load the message. Signal hanging isn't a big issue although of course the faster the better but at this moment in time old messages are just unavailable due to the app crashing

### Screenshots

n/a

### Device info

**Device**: iPhone 6s

**iOS version**: 12.4 Public Beta 2 [This has been happening since at least iOS 12.0 public beta 5, and on every iOS 12 iteration since then. This also happens on iOS 13.3 public beta 1]

**Signal version:** 3.0.0 [This has been happening since at least version 2.28.1 (2.28.1.5) and on every Signal version since then]

### Link to debug log

https://debuglogs.org/89d12db536bd56016442bc0bf914dfdbfc3eb13864e2fae83b162d1497cf0485.zip

**Comment by michaelkirk-signal** [comment]
Can you look for any crash logs and attach those as well?

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by sseneca** [comment]
I’ve already sent the crash log to support@signal.org

**Comment by haffenloher** [comment]
A forum user confirmed the issue and sent another crash report via mail: https://community.signalusers.org/t/bug-search-finds-text-but-crashes-times-out-jumping-to-it/3966

**Comment by PierrePQ** [comment]
Experiencing this bug all the time. Even crash still typing the search-phrase.
[Signal-2019-05-21-154020.docx](https://github.com/signalapp/Signal-iOS/files/3202939/Signal-2019-05-21-154020.docx)

**Comment by PierrePQ** [comment]
This happens to me all the time. Even while still typing the search-phrase
Crash log sent to support@signal.org

**Comment by michaelkirk-signal** [comment]
The latest beta includes some changes which should better handle navigating to old search results.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
