### ISSUE TITLE
Request: Show contact's nickname if it is present

### ISSUE THREAD

**Issue by WildYorkies** [signalapp/Signal-iOS#3799]
If an iOS contact has a nickname, show that instead of the First Name / Last Name.

If the contact doesn't have a nickname, show the First Name / Last Name.

Thoughts?

**Comment by outadoc** [comment]
Why was this closed? I'd really like that feature, it would be more consistent with the stock Messages app.

**Comment by trosel** [comment]
@outadoc Signal doesn't track feature requests on github anymore. They track them on their community forum. I closed because I didn't know that at first.

**Comment by outadoc** [comment]
@trosel Ah, I didn't either. My bad :)
