### ISSUE TITLE
Music continues to play when a Signal call is received

### ISSUE THREAD

**Issue by Barracuda6** [signalapp/Signal-iOS#3804]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When music is playing over Bluetooth from the stock Music app to my automobile, and a Signal call is then received and accepted, the music will sometimes continue to play during the call.

Before the call is received, the music is playing through the automobile speakers/sound system. When the call is received and accepted, the call audio is played through the automobile speakers but the music that was playing before the call continues to play through the automobile speakers.

However, when this occurs, it seems that the call quality is significantly reduced (to the quality of a standard cellular call) and the music playing sounds like it is playing in the "background" (hard to describe), almost like it is coming from the person who called. The caller has reported that they are able to hear the music, but I am not sure if they are just hearing the echo.

I do not know if this will only happen over my automobile's Bluetooth system or over any Bluetooth system. I have only had experience with the automobile Bluetooth.

This issue seems to be similar to #1875.

### Steps to reproduce
- Start playing music through the iPhone's stock Music app, over an automobile's Bluetooth system.
- Receive, and (perhaps quickly?) answer a call from another Signal user.

**Actual result:** The music continues to play during the Signal call.

**Expected result:** The music should be paused, and only continue to play after the Signal call has ended.

### Device info

**Device**: iPhone 7

**iOS version**: 11.4.1 (15G77)

**Signal version:** 2.28.1.5

Please note that I first experienced this issue many, many months ago, across several different Signal and iOS versions, and have experienced this quite a few times in total.

### Link to debug log

Logs have been sent to the support email.

**Comment by hoechenberger** [comment]
I have the same experience when listening to music via my AirPods and then accepting a call on Signal.
