### ISSUE TITLE
Support for per-Message Text Directionality (LTR/RTL)

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-iOS#3841]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
RTL text directionality is falsely handled (from left to right).
I also reported the issue on [Signal-Desktop](https://github.com/signalapp/Signal-Desktop/issues/2562). 

### Steps to reproduce
- Send some texts in any RTL Language (Arabic, Farsi etc.).

### Screenshots

![signal-2018-08-23-112018](https://user-images.githubusercontent.com/34171942/44509453-f9d4ac00-a6c6-11e8-861b-1df7bcdb81fb.png)

### Device info

**Device**: iPad 2

**iOS version**: 9.3.5

**Signal version:** 2.29.0.16

**Comment by michaelkirk-signal** [comment]
I'm not immediately able to reproduce...

Can anyone using an RTL language on iOS10, iOS11, or iOS12 chime in to say if you are/are not having this problem?

**Comment by Xashyar** [comment]
@michaelkirk-signal 
Yes.
iPhone 6S
iOS 11.4.1
![signal-2018-08-31-164523](https://user-images.githubusercontent.com/34171942/44935229-176bda80-ad85-11e8-87bd-570f043dd58f.png)

**Comment by Xashyar** [comment]
@michaelkirk-signal @charlesmchen-signal 
this issue was resolved for Signal-Desktop long ago and does not exist on Android,
Please take a look:
https://github.com/signalapp/Signal-Desktop/issues/2562

**Comment by Imperiopolis-Signal** [comment]
This issue is resolved in the upcoming release 2.42
