### ISSUE TITLE
Incorrect voice messages duration 

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#3844]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a voice message is received, it is shown that the length is (let’s say) 14 seconds, instead the audio will reproduce for 17 seconds.

### Steps to reproduce
- receive a voice message
- click play to reproduce
- wait until it reaches the “end”, but it goes on for 3/4 seconds more

**Actual result:** voice message is longer than expected

**Expected result:** voice message length should be the exact duration of the audio

### Screenshots
![45a1a027-0004-49db-9595-8ce07a100bfa](https://user-images.githubusercontent.com/31325316/44616795-c6c12280-a856-11e8-874c-8427f890efb1.jpeg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 11.4

**Signal version:** 2.29.0.16 beta

### Link to debug log

https://debuglogs.org/56a3b60e3fce2dbdf310b822c27c98bf95c50748b54b9e46efabd977f1950f20.zip

**Comment by michaelkirk-signal** [comment]
Can you open a thread with yourself and leave yourself a voice message - does this occur?

Or does it only occur with this one recipient?

Does it occur with every voice message they send you, or just this one?

**Comment by michaelkirk-signal** [comment]
Seems like they might be sending you a malformed audio file. Do you know what device/OS version  they are on?

**Comment by ethylmorphine** [comment]
Confirm. Wrong duration with Android client.

**Comment by purpleplatypus** [comment]
This looks related to #3086. I did a bit of digging into how this might happen; there's some [stackoverflow](https://stackoverflow.com/questions/16264282/avaudioplayer-duration-changing/16265186#16265186) posts about a weird quirk of AVAudioPlayer returning an _estimated_ duration for files it hasn't actually prepared to play (the official docs are silent on this, but I saw a mention of this trait elsewhere as well). @michaelkirk-signal I could make a PR if you want, but I can't reproduce the issue to verify that it works, so it's your call.

**Comment by michaelkirk-signal** [comment]
An audio file that reproduces this behavior would be super helpful.

**Comment by SignalTestingTeam** [comment]
@michaelkirk-signal if you need a audio file with incorrect duration you can contact me...
signalmessenger@t-online.de

**Comment by purpleplatypus** [comment]
Steps to reproduce:
1. Generate an audio message on Android of sufficient length using Signal, and send it to an iPhone user. You do not need to do this, the attached m4a file will reproduce this behavior.
2. Unzip and send the attached m4a file to yourself in Signal iOS.
3. Signal-iOS reports the received file as 26 seconds in length.
4. Play the file. Actual file duration played is 29 seconds. 

It's not clear from the documentation, but AVAudioPlayer apparently won't return an exact length of certain types of audio files without doing a certain amount of preprocessing. I'll make a pull request.

[signal-2018-10-24-202801.m4a.zip](https://github.com/signalapp/Signal-iOS/files/2516999/signal-2018-10-24-202801.m4a.zip)
