### ISSUE TITLE
Linked Devices Title Occludes First Entry

### ISSUE THREAD

**Issue by davidgu** [signalapp/Signal-iOS#3850]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The top of the first entry in Linked Devices is occluded by the title bar, covering up the name of the linked device.

### Steps to reproduce
- Open the iOS app
- Link a desktop by scanning the QR code
- Open the Linked Devices menu under Settings

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The top of the first entry in Linked Devices is occluded by the title bar, covering up the name of the linked device.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The first entry should be shifted downward so that it appears below the title bar.

### Screenshots

![img_0649](https://user-images.githubusercontent.com/21150842/44889860-d05ae800-aca5-11e8-81b7-a55329bef6f0.PNG)

### Device info

**Device**: iPhone 7S

**iOS version**: 11.0.3

**Signal version:** 2.29.0.17

**Comment by patrick99e99** [comment]
+1 and worse than this, if you have no linked devices, it's impossible to add a linked device because the "link new device" option is completely covered by the title bar.  Fortunately if you rotate the phone and put it in landscape mode, you can still tap it.

**Comment by patrick99e99** [comment]
![image](https://user-images.githubusercontent.com/28946/53434222-f3432c00-39aa-11e9-9b90-58c50e2a632d.png)

**Comment by michaelkirk-signal** [comment]
@patrick99e99 - what version of iOS are you running?

**Comment by StephanieJosine** [comment]
I have the same problem and, as @patrick99e99 shared, couldn't tap add at all because I'm a new user and had no existing linked devices. Thanks for the workaround, Patrick ^_^
@michaelkirk-signal fwiw, I am running iOS 11.1.2 and don't want to update because of Apple's planned obsolescence shenanigans!

**Comment by five-c-d** [comment]
Also reported here == https://community.signalusers.org/t/link-new-device-option-isnt-working/7262
