### ISSUE TITLE
Signal is Not Available in App Store of China mainland now, so how to update...

### ISSUE THREAD

**Issue by Pingmin** [signalapp/Signal-iOS#3851]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just found Signal App is not available in App Store of China mainland yesterday. So it can't auto update to the latest version (v2.29.0)! How to fix this?

I see someone says we can change the Apple Id's country/region to another place, such as US, to get the updates. However, I can't change my Apple ID or create a new one without an valid US credit card.

Thanks!

### Steps to reproduce
Just use the Signal with a China mailand's Apple ID.

**Actual result:** Can't get the latest version.

**Expected result:** Auto update to the latest verison in China mainland.

### Screenshots

![signal-2018-08-30-072656](https://user-images.githubusercontent.com/836846/44898876-c6cb9180-ad32-11e8-8d36-21e6351e5634.png)

### Device info

**Device**: iPhone SE

**iOS version**: 11.4.1

**Signal version:** 2.28.1.5

### Link to debug log

<Non.>

**Comment by ethylmorphine** [comment]
Change your Apple ID country, take your SIM out, turn on VPN, change phone’s language, disable location services completely. I’m quite curious if it works.

**Comment by Pingmin** [comment]
So I wonder how to build the App from source code with original Signal signature and install it into my phone...

**Comment by Pingmin** [comment]
It is Not Available in App Store again! My current Signal version is 2.30.2.16, and it has been a  long time to get updates...

![signal-2018-11-17-140900](https://user-images.githubusercontent.com/836846/48657854-a29a6980-ea72-11e8-9b79-2637234f7a9a.png)

**Comment by CR0CKER** [comment]
Can anyone else confirm if this is true? Has Signal really been removed from the App Store in China?

**Comment by WoodpeckerBaby** [comment]
relevant
