### ISSUE TITLE
"Touch to return to call" Strip Obscures the Media Gallery UI

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-iOS#3852]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Green Strip Obfuscates some parts of the App UI.

### Steps to reproduce
- While on a call, hover around to see some images in the Media Gallery.

**Actual result:**
### While on a Call:
![signal-2018-08-31-133329](https://user-images.githubusercontent.com/34171942/44904770-62ee9c00-ad25-11e8-982b-061ab0e2e5e9.png)

### Not on a Call:
![2](https://user-images.githubusercontent.com/34171942/44904830-8c0f2c80-ad25-11e8-9396-e56f916d7ab1.png)

**Expected result:** The green strip doesn't obfuscate any part of the UI.

### Device info

**Device**: iPad 2

**iOS version**: 9.3.5

**Signal version:** 2.29.0.16

**Comment by michaelkirk-signal** [comment]
This is now fixed.

**Comment by Xashyar** [comment]
@michaelkirk-signal
Thanks..!
but now landscape media support won't work while on calls. as in 2.32.16
should I make a separate issue for that?
