### ISSUE TITLE
Text sent with notifications is missing in chat

### ISSUE THREAD

**Issue by wolfo** [signalapp/Signal-iOS#3865]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is related to the issue where you can't open/view large attached images (#3860). In addition to said problem, any text sent with such an attachment is not showing. I noticed because there was text in the notification, but it's missing in the app. My friend confirmed that the text should be there.
The issue does not happen if a small image is sent.

### Steps to reproduce
- Send large image file (from Android at least)
- Include a message with the image
- Receive on the iOS client
- Compare notification vs. chat window

**Actual result:**
Notification shows message, app doesn't

**Expected result:**
You should see the message in the app. (and also view the image, of course)

### Device info
iPhone 6 plus

**iOS version**: 12 DP 12 16A5366a

**Signal version:** 2.29.1.1

### Link to debug log
https://debuglogs.org/8d42e0aa809a7c6f1db956c8da0de6aa135c8419d10a495750741e995fc672cb.zip

**Comment by wolfo** [comment]
Derp, wrong subject line. Should be "Text sent with large images missing in app".

Also, I had my friend send me a small image and everything worked as expected.

**Comment by sneakymister** [comment]
Hi! I'm also experiencing this issue. The message text does appear in the lock screen notification, but once the app's opened, no message: 
![img_4496](https://user-images.githubusercontent.com/15573286/45124172-501a0400-b137-11e8-8e57-2ccc3e3c2e5d.PNG)

**Comment by michaelkirk-signal** [comment]
Hi all, Thanks for the report. We're aware of this issue and actively working on a fix. Stay tuned.

We'll first release the fix to beta, so if you'd like a quicker fix in the meanwhile, you could get signed up for the beta by mailing support@signal.org with the subject "sign me up for the iOS beta".

It's generally fairly stable, but as a Beta it's more prone to crashing, data loss, and other buggy behavior.
