### ISSUE TITLE
Modify server address hint unable to connect

### ISSUE THREAD

**Issue by lh0072** [signalapp/Signal-iOS#3867]
### Bug description

I modified “ textSecureServerURL”
Tips “Signal was unable to connect to the internet. Please try from another WiFi network or use mobile data.”

**Comment by michaelkirk-signal** [comment]
I'm not sure what you're trying to report - Please fill out the entire issue template next time you file a bug with Signal.

Keep in mind, we only use GitHub for reporting bugs with the official client. If you're looking for help developing Signal or using Signal libraries, please use the community forums for that: community.signalusers.org.
