### ISSUE TITLE
How can I log out and switch numbers?

### ISSUE THREAD

**Issue by mhkeller** [signalapp/Signal-iOS#3868]
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request or a discussion topic

----------------------------------------

I am trying to log out of Signal and sign in with a different number. The only option in settings is to "Delete my account." How do I simply log out. I don't want to delete my account or lose any of my information.

**Comment by michaelkirk-signal** [comment]
Hi @mhkeller  - we only use GitHub for reporting issues with existing functionality. For support, try the [community forum](https://community.signalusers.org/) or contact support@signal.org.

Signal on iOS currently does not support switching your phone number - this would require a reinstall, which would wipe your message history.
