### ISSUE TITLE
App crashes when trying to delete files from media overview

### ISSUE THREAD

**Issue by laberkeks** [signalapp/Signal-iOS#3874]
iOS 12 beta 10
Signal 2.29.1.1

Steps to reproduce:
1. Open a chat history 
2. Click on the chat name on top of the history 
3. Select the button for all media content (in German “Alle Medieninhalte”
4. Select an image/file
5. Try to delete it
=> Signal app will crash

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by michaelkirk-signal** [comment]
Can you include a crash log and a debug log?

**Comment by laberkeks** [comment]
I’m now on vacation. So I can’t get the log files

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pingmin** [comment]
Yes, I found this problem too in recent days.

**Comment by tzs1** [comment]
Unable to reproduce using iPhone 8 Plus 11.4.1 / Signal 2.29.2.3 beta

**Comment by kosakian** [comment]
https://debuglogs.org/4c0fa6eaf05c1f83ee732d2455affdc3918cb45b7d270ac4309e68c3d6a054f9.zip

**Comment by laberkeks** [comment]
Signal seems only to crash if the chat contains only one single picture and you try to delete this single picture.
Tested on iOS 12.1 with Signal 2.29.3.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pingmin** [comment]
> Signal seems only to crash if the chat contains only one single picture and you try to delete this single picture.
> Tested on iOS 12.1 with Signal 2.29.3.3
> 
> Sent with [GitHawk](http://githawk.com)

However, I just tried to delete several pictures and it crashed too in past weeks.

**Comment by uschmidt** [comment]
iOS 12.1 Public Beta
Signal 2.30.2.16 Beta

I can reproduce the problem in parts.

Test 1:
- Select 1 image
- Delete it
   => Signal app will **NOT** crash

Test 2:
- Select 2 images from the same time period, e.g. "September"
- Delete images
   => Signal app will **NOT** crash

Test 3:
- Select severeral images from the different time periods, e.g. "September" and "October"
- Delete images
   => Signal app **will crash**

https://debuglogs.org/91ba9622a868f07d3abba5140abfa005d7c92f7cdb67308e1ecf8ca51e9044a0.zip

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.

**Comment by cappic90** [comment]
I can report that I notice it too. Here is my rundown of it:

It affects 3 chats for me:
- One chat has one image left that has no preview and is invisible on click, created earlier this month
- One chat has a single video left that has no preview and does not play on click, created in February this year
- One chat has single image left, that has no preview and ins invisible on click, created just 2 days ago

I attempted to delete all those files with two approaches:
- In "All Media" - Click "select" - Select the file - click delete - crash
- In "All Media" - Click the media in question (something opens, but there is nothing to see) - click delete - crash

https://debuglogs.org/339df763857cae28aea0fe10d02be46a0b31c85eaff2952cdfc0a63058954293.zip

**Comment by DVelbeck** [comment]
Hello,

Same issue experienced today. 
Trying to delete all media fastidiously **one by one** as there is no way to delete all in one shot.
(Why ??? WhatsApp has a delete all media...)

I tried to do manually "by batch", every time, after deletion, the app crashes.
IOS 15.2, Iphone X here.


Also, why not having clear all media from all groups, it would be a huge plus...

**Comment by DVelbeck** [comment]
> Hello,
> 
> Same issue experienced today. Trying to delete all media fastidiously **one by one** in a group conversion, as there is no way to delete all in one shot. (Why ??? WhatsApp has a "select all" option...)
> 
> I tried to do manually "by batch", every time, after deletion, the app crashes. IOS 15.2, Iphone X here.
> 
> Also, why not having clear all media from all groups, it would be a huge plus...

is anybody still facing the same issues ?

**Comment by uschmidt** [comment]
> iOS 12.1 Public Beta
> Signal 2.30.2.16 Beta
> 
> - Select severeral images from the different time periods, e.g. "September" and "October"
> - Delete images
> => Signal app will crash

Testing Signal 5.28.0.32 / iOS 15.3.1

The issue is gone.

**Comment by uschmidt** [comment]
> Trying to delete all media fastidiously one by one in a group conversion, as there is no way to delete all in one shot. (Why ??? WhatsApp has a "select all" option...)

A "Delete all" od "Select all" button would be nice.
