### ISSUE TITLE
no available session for contact error

### ISSUE THREAD

**Issue by dgobaud** [signalapp/Signal-iOS#3875]
### Bug description
On iOS when receiving messages intermittently get "no available session for contact error" and messages does not show

### Steps to reproduce
receive messages

**Actual result:**

get no available session for contact error instead of message

**Expected result:**

get the message

### Device info
**Device**: iPhone 7 Plus

**iOS version**: X.Y.Z
11.4.1

**Signal version:**
2.29.1.1

**Comment by michaelkirk-signal** [comment]
Hi @dgobaud  - sorry Signal is malfunctioning for you, but without debug logs we can't progress on this. 

If this happens again, try to capture debug logs as soon as it starts happening, ideally from the sender as well.

Until then, we can't progress on this issue, so I'm closing.
