### ISSUE TITLE
Large dimension images don't display inline

### ISSUE THREAD

**Issue by Chrismarsh** [signalapp/Signal-iOS#3878]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Large dimension images sent from Android mobile -> iOS mobile display inline, with a .JPEG image place holder. Viewed from desktop, these images correctly show. Examples of images of this size are photos taken with the Pixel XL2.
Testing with various images suggests it's entirely related to the dimension and not file size. Please see attached images for examples that work (2k) and that don't (4k)

### Steps to reproduce
- Send large dimension image (4k x 4k triggers the bug) from Android mobile to iOS mobile 
- Specifically, this image ![4k](https://user-images.githubusercontent.com/630436/45318387-03994480-b4fa-11e8-819f-f7fe6426e60c.jpeg)

**Actual result:** 
- Image appears on iOS client like a file would -- File icon with JPEG txt + size. 
![image](https://user-images.githubusercontent.com/630436/45318402-0f850680-b4fa-11e8-9dcd-a7f142781d66.png)

**Expected result:** 
- Image appears inline

### Screenshots
**How the large dim image appears on iOS**

**This image works**
![2k](https://user-images.githubusercontent.com/630436/45318373-f7ad8280-b4f9-11e8-8b22-296d017dd2f7.jpeg)
**This image does not**
![4k](https://user-images.githubusercontent.com/630436/45318387-03994480-b4fa-11e8-819f-f7fe6426e60c.jpeg)

### Device info

**Device**: iPhone X

**iOS version**: 11.4.1

**Signal version:** 2.29.1.1

### Link to debug log
https://debuglogs.org/1152159afb02a152b506c3525484a42f5de8a10317264b72913ae8fc3f2a8344.zip

**Comment by mro** [comment]
same iOS -> iOS. Would very much prefer compact, mobile-friendly (bandwidth & battery saving) images.

**Comment by Chrismarsh** [comment]
@mro looks very likely. I have no idea how I didn't find that ticket. That update isn't pushed out for me yet so I guess wait and see?

**Comment by Chrismarsh** [comment]
@mro and as soon as I say that, I see the 29.2 update. Yup, that fixes it for me.
