### ISSUE TITLE
recorded video is lost on some actions

### ISSUE THREAD

**Issue by arekm** [signalapp/Signal-iOS#3881]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

**Actual result:**

When recording video from inside signal and accidentally pressing "home" button (on iphones with actual button) or swiping screen from down border up (on iphone X; this action is unfortunately very easy to trigger) the video gets permanently lost.

**Expected result:**

If such action happens signal should end recording and behave just like when user stops recording manually - so make video available for sending to recipient

### Device info
**Device**: tested on iphone 7 plus and iphone X

**iOS version**: 11.4.1

**Signal version:** 2.29.3.2

How to reproduce:
- open signal and conversation with someone
- press + to add video
- video starts recording, now press home button or make swipe action on iphone X
(the one shown here: https://support.apple.com/library/content/dam/edam/applecare/images/en_US/ios11-iphone-x-home-gesture-animation.gif)
- recorded video gets lost

Stock "Camera" app behaviour is consistent with what I described in "Expected result", so signal would match that and also be sane (loosing video is a very bad thing because it usually cannot be recorded again in exactly the same way)

**Comment by u32i64** [comment]
This issue is no longer present (video is not lost) in Signal `2.40.0.21` (I tested with physical Home button).

Furthermore, since it’s now required to hold the capture button to record, it should be harder (if even possible) to accidentally swipe up on iPhones with gesture navigation 😃

**Comment by u32i64** [comment]
@Imperiopolis-Signal I think this can be closed?
