### ISSUE TITLE
iOS interface lags extremely when opening a conversation with many messages

### ISSUE THREAD

**Issue by azapps** [signalapp/Signal-iOS#3882]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The interface lags extremely when opening a Chat with a large amount of messages.

### Steps to reproduce
- Open App
- Select a contact with whom you exchanged many (probably thousands) of messages

**Actual result:** The App lags extremely and it takes many seconds until the chat window is rendered

**Expected result:** The chat window is rendered immediately

### Screenshots
-none-

### Device info

**Device**: iPhone SE 128gb

**iOS version**: iOS 11.4.1

**Signal version:** 2.29.2.4

**Comment by michaelkirk-signal** [comment]
Can you include a debug log after opening a conversation which is slow to open?

Is it faster on subsequent opening, or is it equally slow every time you go into the conversation?

Any hints as to what kind of messages you are sending -

All text? 
Lots of media? 
What kind of media? 
Lots of gifs?

**Comment by fridgecow** [comment]
It's equally slow when re-opening. I have reports from a contact saying that a group chat, with mostly text messages, has now become unbearably slow to open on iOS. I'm afraid I don't have logs.

**Comment by azapps** [comment]
Debug Log: https://debuglogs.org/2007a660c63e958979aeb759ebb2dc3e4c65007d83ee5868fe97fa52b6811978.zip

It is equally slow when reopening. It is even equally slow when opening Signal from the Multitasking menu when the chat is to be opened.
Messages consist of mostly (short) text with some images (small size, e.g. Screenshots).
No gifs, no video, no voice.
