### ISSUE TITLE
Vibration is recorded when recording a voice message

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [signalapp/Signal-iOS#3900]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After tapping on the microphone button on the very bottom right in a chat window my iPhone SE vibrates and the vibration is also recorded in the beginning of the voice message. I could not find an option to disable the vibration.

### Steps to reproduce
- open any chat
- tap and hold the microphone button
- speak short voice message
- release the button
- tap the play button of the new voice message

**Actual result:** vibration can be heard in the new voice message

**Expected result:** only the voice is heard in the new voice message

### Device info
**Device**: iPhone SE (Model MP832DN/A)

**iOS version**: 12.0 (16A366)

**Signal version:** 2.29.3.3

**Comment by Mihahn** [comment]
Can't reproduce on iPhone 7 (iOS 13) with Signal 3.4.0.7.

**Comment by PanCakeConnaisseur** [comment]
Issue still unchanged with iPhone SE, iOS 13.3.1, Signal 3.7.1.0.

**Comment by PanCakeConnaisseur** [comment]
I forgot to mention that this issue only occurs if the phone is in silent mode.

**Comment by dev-dafi** [comment]
The vibration is heard every time on my device, whatever option i choose.
Device is an old iPhone SE with iOS 13.4.1. Silent Mode is turned off, do not disturb likewise. The vibration is again heard in the new message.

**Comment by molzy** [comment]
I'm also experiencing this issue, iPhone SE, iOS 14.3, Signal 5.2.0.4.

I suspect that this issue is far more noticeable on iPhone SE and similar vintage devices, as they still use a real vibration motor, which is fairly loud. The iPhone 6S, 7, and up all use haptic feedback for vibration, which is far quieter and would not show up in a voice message in the same way.

An option to disable vibrations for voice recordings would be a way to solve the issue for iPhone 6 and SE owners.

**Comment by PanCakeConnaisseur** [comment]
Still present in iOS 14.6 and Signal 5.14.0.35.

**Comment by PanCakeConnaisseur** [comment]
I did not observe the aforementioned vibration with iOS 15.1 (19B74) and Signal 5.26.10.0 anymore. For this reason, I am closing this issue.
