### ISSUE TITLE
Signal Call fails when "Always relay calls" is on

### ISSUE THREAD

**Issue by Nafj79** [signalapp/Signal-iOS#3901]
We are two Signal Users running on iOS 12 with Signal version 2.29.3.3 and we have problem making calls. We have activated the option named “Always Relay Calls” under Privacy setting. When we make call neither on of us can be connected to eachother. As soon as we disable the option “Always Relay Calls” it’s working. I can not get my finger on why it’s happens.

We want to make call with the option activated because it is more secure but i never work.

I have sent a debug log. but have anyone here any idea?

https://debuglogs.org/e9e61e1e48b5685d01c3c743a42f2234508b1802221a6e56f43b56981c36de72.zip

**Comment by sierravictor806** [comment]
Same issue!!!!!!!!!

**Comment by sierravictor806** [comment]
https://debuglogs.org/22613bef0328733519761a5c7fc877fff5502017e22068ba98aa07e706a2bae7.zip

**Comment by michaelkirk-signal** [comment]
This should now be resolved in production.

If you have calling issues in the future, could you please open a new issue with fresh debug logs? Thanks!
