### ISSUE TITLE
Android 9 update / clicking on conversation crashes app

### ISSUE THREAD

**Issue by socalmoney** [signalapp/Signal-iOS#3932]
Bug description
I updated my OnePlus 6 to Android 9 and when I click on a signal conversation, the app crashes.

Steps to reproduce
- Sign in to Signal
- Click on conversation
- App crashes

**Actual result:**  I can use the Chrome plug-in and the conversation actually updates on the mobile app but I can't open it. I archived the conversation and restored it and that did not work. I uninstalled and reinstalled and that did not work. I am stuck to using Chrome plug-in only at the moment.

**Expected result:** Correct behavior would be that the conversation opens and I can send are receive messages. Unable to open a conversation without the app crashing.

Device info

**Device**: OnePlus 6

**Android version**: Android 9 / Oxygen 9.0

**Signal version:** 4.62.2

### Link to debug log
https://debuglogs.org/16f2229cf9e1f651d2712815d65c4201bb8e5256c0430c7d3b72ad8a6c3d8029

<!--  If this is a crashing bug, after filing this issue, email a copy of your latest crash report to support@whispersystems.org

**Comment by RiseT** [comment]
You're posting in the Signal iOS project 😃

**Comment by michaelkirk-signal** [comment]
@socalmoney - Could you re-post this https://github.com/signalapp/Signal-Android/issues so the Android folks can help you?

**Comment by socalmoney** [comment]
Apologies, I didn't even see that. Thanks.
