### ISSUE TITLE
Scrolling not possible when re-editing a longer text message

### ISSUE THREAD

**Issue by the-x-at** [signalapp/Signal-iOS#3940]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When returning from the Signal conversation overview to an already existing draft in a conversation, it is initially not possible to scroll the text to e.g. reach the end and continue editing. One needs to insert an arbitrary character in order to bring back scrolling functionality.

### Steps to reproduce
- Choose a conversation thread and start filling in the message text such that there is enough text in the widget to make the first lines disappear. In the screenshots below, characters "A", "B", "C", "D", and "E" were inserted line by line to let the text entry box overflow.
- Press the Back button on the top left corner to return to the list of all conversation partners.
- Tap on the conversation where the new text has been entered.
- The first lines of the previously written text appear at the bottom of the screen.
- Tap on the text entry widget  (left screenshot).

**Actual result:** The cursor and a keyboard appear, but a swiping gesture inside the text entry widget does not scroll the text up or down. Also, the text widget's last line next to the Plus ("+") button is empty. Only after entering the first character (an "x" in the line beginning with "B" in the screenshot on the right hand side), the last line becomes visible along with the ability to scroll the drafted text.

**Expected result:** Scrolling should be possible immediately when tapping on the text entry box.

### Screenshots

![combined](https://user-images.githubusercontent.com/22655921/46537574-291f3100-c8a1-11e8-85ee-13ac792543d8.png)

### Device info

**Device**: iPhone 5s

**iOS version**: 11.4.1

**Signal version:** 2.30.2.9 (beta)

**Comment by the-x-at** [comment]
I upgraded the iPhone from iOS 11 to iOS 12 and the behavior can be reproduced. The above-mentioned empty space to the right of the Plus button ("+") is gone, such that the text box is filled with text down to the last line. The remaining behavior is as described initially, though.

### Device info
**Device**: iPhone 5s

**iOS version**: 12.0.1

**Signal version:** 2.30.2.16

**Comment by ideologysec** [comment]
Select All -> Cut -> Paste will workaround this; not sure what that indicates.

**Comment by k3vy** [comment]
I can reproduce this issue with my iPhone 7 with 12.0.1 and Signal 2.30.2.16.
It's really annoying and I'm using the same workaround as @ideologysec mentioned.
I hope this will be fixed soon ... 😞

**Comment by murphyd** [comment]
Reproducible on iPhone Xs with iOS 12.1.1.

**Comment by petergx** [comment]
Also seeing this on iPhone SE with iOS 12.1.1. Feels like punishment for thinking on a message before sending.

**Comment by gituser94x54102** [comment]
Reproducible on iPhone XS Max with iOS 12.1.1.

**Comment by michaelkirk-signal** [comment]
This should be fixed in the 2.33.0 beta - if you are still experiencing this behavior after updating, please let us know.

**Comment by ngie-eign** [comment]
I just ran into this yesterday on my iPhone 6s with 2.32.2.0 (once I reclicked the text field I could edit the content again). Glad to see this will be fixed in a future version!
