### ISSUE TITLE
[Beta Bug] Sharing from other apps into Signal does not sync with Desktop

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-iOS#3941]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you Share a URL from another app (App Store or Safari) into Signal. two things happen:

1. The Shared URL is **only** shown in the Chat List view, it is not shown when you open the chat, Unless you send another message which somehow updates the chat view.

2. None of the "Shared" stuff syncs with Desktop, only messages typed in within the app not the ones shared from outside. 

### Steps to reproduce
- Share Something from another app into Signal
- Check your Desktop or the contact's chat view on your phone to see if they are sent.

### Device info

**Device**: iPad 2

**iOS version**: 9.3.5

**Signal version:** 2.30.2.9

### Link to debug log
https://debuglogs.org/e994a15f92a1ea3ae9c26ae670c1686485aea7d58208d85b09ee45f141aceb3c.zip

**Comment by michaelkirk-signal** [comment]
I cannot reproduce either of these issues on the latest Signal. 

If you are still able to reproduce, could you follow up with the updated steps?
