### ISSUE TITLE
Missing back button in archive view

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#3943]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the archive view the button in the left upper corner is missing after entering and leaving a conversation.

### Steps to reproduce
- go to the Signal main view
- switch to archived conservations
- enter a archived conversation
- jump back to the archived conversations view

**Actual result:** The button in the left upper corner is missing so that the Signal main view isn’t accessible without restarting the app.

**Expected result:** The button in the left upper corner should be accessible and should bring you back to the Signal main view.

### Screenshots

![missing-back-button](https://user-images.githubusercontent.com/5073538/46586776-bb2a6380-ca72-11e8-9607-6c29e51c0f51.png)

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3

**Signal version:** 2.30.2.9 beta

### Link to debug log
https://debuglogs.org/1753a93d562536df528e9436fd86aad49ba70c2278ddd5bd71909df98a9527d7.zip

**Comment by michaelkirk-signal** [comment]
Thanks for reporting! Fixed in https://github.com/signalapp/Signal-iOS/pull/3944
