### ISSUE TITLE
Long messages overlap

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#3946]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Message bubbles of long messages reach too far off at the top end of the app.

### Steps to reproduce
- enter a random conversation
- long press a message with a long text

**Actual result:** The message is highlighted and a context menu pops up which pushes the message bubble over the iPhone status bar.

**Expected result:** Highlighted messages should not overlap with the iPhone status bar so that elements like the system clock, batery life and wifi status is still visible.

### Screenshots

![long-message-details](https://user-images.githubusercontent.com/5073538/46621628-7ad0f100-cb17-11e8-8d36-06ec8327aca5.png)

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3

**Signal version:** 2.30.2.9

### Link to debug log
https://debuglogs.org/147f0347f44fe3fabc27329ae305fe5794397c60e3f60b114aafb5ba7a7483bc.zip

**Comment by denver-s** [comment]
I don't know if this is the expected behaviour, but it is still happening in version 2.38.1.2.

![immagine](https://user-images.githubusercontent.com/31325316/56309658-45523380-614a-11e9-96ee-6805d4361022.png)

**Comment by denver-s** [comment]
Latest version uses a different context menu which solves this problem.
