### ISSUE TITLE
Ignore spaces for Jumbo emojis 

### ISSUE THREAD

**Issue by rocknjohn** [signalapp/Signal-iOS#3951]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving two emojis, they are jumbo. When sending two emojis, they are not jumbo, but should be.

### Steps to reproduce
- Receive two emojis
- Send two emojis

**Actual result:** Outgoing double emojis are regular text size.

**Expected result:** Outgoing double emojis should be jumbo. 

I consider this a bug because receiving and sending jumbo emoji behavior should be consistent.

### Screenshots
![emoji](https://user-images.githubusercontent.com/11340204/46838257-fcd74900-cda7-11e8-960f-d0a46185dfaa.png)

### Device info

**Device**: iPhone 7
**iOS version**: 12.0
**Signal version:** 2.30.2.11 
Screenshot is from the earlier beta version before the Google colors were removed again (thankfully), but I don't remember what version that was.

**Comment by michaelkirk-signal** [comment]
Hmmm... indeed we should be making outgoing emoji jumbo.

Are you sure there’s not a space between those two emoji?

We only jumbo it if there are exclusively emoji (and only if there’s less than a handful).

**Comment by ebelinski** [comment]
I tried reproducing this, and it does indeed appear that in @rocknjohn's screenshot, there is a space between the two emojis. However, I believe that messages that include spaces with emojis should also become jumbo. There are two reasons for this:

1. This is consistent with the behavior in iMessage. Messages that have have only spaces and up to three emojis still show up as jumbo. For example, a message with: ```🧐______________🤓``` (underscores represent spaces) will have the same font size as `🧐🤓`. 
2. When a user uses an emoji from an [emoji prediction](https://www.macrumors.com/how-to/ios-10-messages-emoji/), a space is automatically added. In this case, it's inconvenient to avoid spaces when constructing a message that is only intended to have emojis in it. See example:

![emoji message with spaces example](https://user-images.githubusercontent.com/4406614/46923424-19a89200-cfdd-11e8-86c0-c8e1a2ca9aa1.gif)

**Comment by rocknjohn** [comment]
Sorry for the confusion. You're correct there's a space between the two emojis. I did not realize. 

However I'm going to rename and leave this issue open for consideration. I think, like @ebelinski describes, it makes sense to ignore spaces when deciding to make emojis jumbo. After the first emoji, a user must use a space before they can type a word if they want iOS to show a suggested emoji. So if a user wants to use more than one suggested emoji, there are going to be spaces.

**Comment by ebelinski** [comment]
I tested it and it is still an issue. I don't think there is anything blocking this from being fixed, but I could be wrong.
