### ISSUE TITLE
Header should have slideIn animation from list view to conversation view

### ISSUE THREAD

**Issue by rocknjohn** [signalapp/Signal-iOS#3952]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the most recent version, the header no long has a slideIn animation when transitioning from the conversation list view to the conversation view. It just jumps in without transition.

### Steps to reproduce
- View conversation list
- Tap any conversation
- Watch header "jump" in instead of animating in like it did in the past.

**Actual result:** Header "jumps" in with no transition animation.

**Expected result:** Header should slideIn.

### Device info

**Device**: iPhone 7
**iOS version**: 12.0
**Signal version:** 2.30.2.11

**Comment by denver-s** [comment]
The header is actually not transitioning along with the conversation view.
I recorded the screen and selected a few screenshots to show the behaviour of the header and the conversation view.

![immagine](https://user-images.githubusercontent.com/31325316/56310410-1b9a0c00-614c-11e9-9225-6d2757782b5c.png)

**Comment by denver-s** [comment]
@rocknjohn I think this is now fixed.
