### ISSUE TITLE
Signal crashes when replying to a message that has been received out of order

### ISSUE THREAD

**Issue by outadoc** [signalapp/Signal-iOS#3954]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when sending a message after an incoming message has been received out of order.

This sounds to me like two bugs, really:
- sometimes messages are received in the wrong order, i.e. my contact will reply to my message, and it will appear on top of the one I sent, but with the correct timestamp
- when I try to reply after such an occurrence, the app crashes

### Steps to reproduce
- send message
- wait for a reply to show up

**Actual result:** Sometimes the reply will show up in the wrong order and be displayed above the sent message, but with the correct timestamp. The notification badge, both in-app and on the springboard, will show (1) and there is no way to clear it, even after forcing the app to restart.
**Expected result:** The reply should show up below the sent message, and the notification badge should be reset after I read it.

- send a reply to that message

**Actual result:** The app crashes. When I open it back up, my reply is marked as failed to send, and I have to tap to retry. When I retry, it works successfully.
**Expected result:** The message is sent and nothing crashes.

### Screenshots
None, sorry. I'll try to get some if I can.

### Device info

**Device**: iPhone 7
**iOS version**: 12.0.1

**Signal version:** 2.29.3. Also happened on the beta but I haven't tested the latest version yet.

### Link to debug log
https://debuglogs.org/fc23725151b25a29933ee265b26f3e38e08b6396b39a832dd13e865d93ce40d6.zip

**Comment by erikstrottmann** [comment]
I can reproduce both issues consistently using the share extension:
1. Send a photo, text snippet, etc. from another app to Signal using the share extension
2. Receive a reply from the same contact
3. Send another message to the same contact

If you open Signal before receiving a reply in step 2, the messages will appear in order and the app won’t crash when you send another message.

**Comment by NateGraff** [comment]
I think I found a workaround:
1. Archive the conversation. The archived conversation will now appear in chronological order without the unread indicator. 
2. Unarchive the conversation.
3. Sending another message does not crash Signal.

**Comment by michaelkirk-signal** [comment]
This should be fixed in the latest version of Signal.
