### ISSUE TITLE
Constant crashing when opening chat thread

### ISSUE THREAD

**Issue by cnhowarth** [signalapp/Signal-iOS#3957]
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

App consistently crashes (including after most recent update) whenever attempting to open a chat thread 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

-open app
-select chat thread 
-curse softly to yourself when nothing happens and you’re now completely frozen

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- total freeze, force reboot

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

-chat should open

### Device info

**Device**: iDevice X

**iOS version**: 12.0

**Signal version:** 2.30.2.16

### Link to debug log

https://debuglogs.org/4a371f89342b8534c1a79cf612ee72d99b1f00f576156841b6b9750892ed21bd.zip

**Comment by carlrusso** [comment]
Seems to happen to me when someone in a thread replies to a message that included a gif; when such a reply message is present, the thread takes upwards of 10 seconds to load. If I delete the reply message, Signal then loads the thread normally.

**Comment by michaelkirk-signal** [comment]
@cnhowarth / @carlrusso - was this happening before your update to the latest version (2.30.2) or did it first start crashing in this scenario with the new update?

**Comment by michaelkirk-signal** [comment]
@cnhowarth / @carlrusso - could you both also email a crash log to support@signal.org and reference this github issue?

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by cnhowarth** [comment]
already logged - thanks!

on the run via [ProtonMail](https://protonmail.ch/) / [@caitlinhowarth](https://twitter.com/caitlinhowarth)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
