### ISSUE TITLE
 Signal uses a very large amount of cellular data. 1MB+ and 80 background requests after receiving one text-only message with the app closed.  Root cause appears to be Signal syncing a larger number of contacts with their attached photos to the Signal Desktop app every time it wakes up.

### ISSUE THREAD

**Issue by varenc** [signalapp/Signal-iOS#3962]
- [x] I have searched open and closed issues for duplicates
  - @866 is a similar old issue that I posted on, but was told to open a new issue
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal uses a very high amount of celluar data.  I observed 500MB in 8 days despite light usage.  Obvious things like sending photos or long video chats are not happening.   This celluar data seems to be consumed in the background and continues to grow even when the app is not opened for day.

Upon further testing with the Signal app closed I observed it making 80 requests and using 1MB+ of data in the background after recieving a text only message.  I believe this behavior is the cause of the underlying high ceullar data usage problem.

### Steps to observe 1MB+ of background data usage from one text-only message
Charles Proxy for iOS was used to observe background requests.  I tried to MITM the traffic, but because Signal seems to use cert pinning MITMing fails and only the requests' domain and data usage can be observed.

Steps:
- Tell a friend to msg me on Signal in 45 seconds
- Close the Signal app on iOS (not move it to the background, but explicitly close it)
- Open up the Charles Proxy and start intercepting
- After the friend sends me a message, observe a new "itunes.apple.com" connection (from the Apple push notification service?) followed by requests to https://textsecure-service.whisphersystems.org 
- The requests to textsecure-service.whisphersystems.org continue for minutes, accumulating more and more data
- In my testing over 80 requests are made. Charles only shows total session data usage but from watching it accumulate it's clear the majority of the data is associated with the Signal requests
- Screenshot from soon after the message is sent
![image](https://user-images.githubusercontent.com/167585/47595429-3629c000-d935-11e8-9926-5509acf34950.png)
- Screenshot after waiting another minute
![image](https://user-images.githubusercontent.com/167585/47595409-1d210f00-d935-11e8-8cc6-1a1164bdc52f.png)
- The requests to textsecure-service.whisphersystems.org continued for another minute, but other iOS background activity complicated the session and I stopped taking screenshots
- Eventually the Signal background requests stoped, and only then did Signal create a local iOS notification (that appears in Notification Center) informing me of the message

My guess is that something about my setup is exacerbating this issue.  Here are some details that might be required to reproduce:
- I have 2000+ contacts on my Phone
- I estimate 300-400 contacts with phone numbers registered with Signal
- I am a light user, only ever really talking with 5-6 individuals/groups
- One group I'm in recieves ~100 messages per day on average.  I've disabled notifications for this group, but my guess is that Signal still gets the push notifications from Apple and wakes up
- I keep the Signal desktop app open most of the time on my desktop computer, but closed it for testing

**Actual result:** After 8 days I see 500MB of data usage.  After 1 text-only message I saw 1MB+ of data usage and 80+ requests while the app was still closed.

**Expected result:** Signal should use less data after waking up from push notifications. Cumulatively, light text-only Signal usage should not lead to 500MB of cellular data usage in 8 days.  I believe these issues are very related.

### Device info

**Device**: iPhone X

**iOS version**: 11.3.1

**Signal version:** 2.29.2.4

### Link to debug log
https://debuglogs.org/c36c1e303c2736fa76a3b89078ac28ebbc505a86832ab84bcea29df82cd43eb3.zip

**Comment by michaelkirk-signal** [comment]
Thanks for the details, we'll definitely look into this.

One more question, can you tell me how roughly many people are in the groups you frequently contact?

**Comment by michaelkirk-signal** [comment]
@varenc - are you on the beta by chance?

**Comment by varenc** [comment]
Nope, I'm actually on the slightly older 2.29.2.4 version of Signal. I think I was on the Signal beta for the new desktop app awhile ago, but the beta is now the default. Besides that have not been involved in any beta.

I can upgrade to the latest Signal version in the app store and try to reproduce again if you'd like, but I believe I've been experiencing this problem for awhile across many past versions so am not optimistic.  If you don't have any theories on the cause of this though I'm happy to try.

**Comment by michaelkirk-signal** [comment]
The beta includes some more detailed logging around attachment upload sizes, which could help diagnose the issue.

**Comment by Xashyar** [comment]
@varenc @michaelkirk-signal 

- Is it possible to the same logging for audio/video calls and voice messages?

- Does the amount of data used depend on the WebRTC encoder (Opus, Vorbis, Apple Audio etc.) configurations?

I checked on voice messages received from Android and iOS on Desktop, here is the MediaInfo for each:

**from iOS**:
> Format : | MPEG-4
> Format profile : | Apple audio with iTunes info
> Codec ID : | M4A (M4A /mp42/isom)
> File size : | 275 KiB
> Duration : | 15 s 720 ms
> Bit rate mode : | Constant
> Overall bit rate : | **143 kb/s**

**from Android**:
> Format : | ADTS
> Format/Info : | Audio Data Transport Stream
> Codec ID : | 2
> File size : | 66.9 KiB
> Duration ~ 16s
> Bit rate mode : | Variable
> Overall bit rate **~** **35 kb/s**

I wasn't able to check this for calls but there seems to be considerable difference in bit rate between iOS and Android.

**Comment by varenc** [comment]
Hi Xashyar. I'm no expert on how the Signal devs do things, but I'd recommend making a separate issue for high audio/video data usage. That seems like it would have a separate cause since that's been ruled out for the issue I'm reporting. I'm seeing high data usage when the app is closed but awaken by push notifications for text-only messages.

If you do open another issue, you could try to get some info using Charles Proxy as I outlined above.  You can track overall data usage but also if media data uses a distinct domain you'll be able to figure out how specifically how much data audio/video is using as well.  It also sounds like you can switch to the [Signal betas](**https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-**) to enable extra logging, which might be helpful when you submit your debug logs.

**Comment by varenc** [comment]
Also @michaelkirk-signal, would you like me to switch to the Signal iOS beta? With that, I can try to reproduce this problem again. 

I believe switching to the iOS beta will delete the Signal app store app and my message history so I'd prefer not to, but if you think this might get you some valuable information just let me know and I'm happy to do it.

**Comment by michaelkirk-signal** [comment]
The beta app installs just like an early update. So you can keep your messages. 

But keep in mind, that as a beta, you are more susceptible to crashes and data loss.

**Comment by varenc** [comment]
So I let Signal use cellular data for a few weeks and came back to this
![image](https://user-images.githubusercontent.com/167585/48749307-3022b880-ec2f-11e8-96fb-38f11ceb8037.png)

(again no voice calls or photo/media usage)

I just updated to the beta and reset cellular data usage tracking. Will report back if the high data usage continues (but my guess is it will)

**Comment by michaelkirk-signal** [comment]
Thanks - now that you've updated to the beta, could you include a debug log
with your next data usage report? There's some additional logging that
might help narrow this down.

**Comment by varenc** [comment]
Here's the latest debug report! I captured this right after reproducing high cellular data usage.

[https://debuglogs.org/6a0e7389edac854b490de857522dc08bf247ea57605ae8d2ae9a93b92ca0b179.zip
](https://debuglogs.org/6a0e7389edac854b490de857522dc08bf247ea57605ae8d2ae9a93b92ca0b179.zip
)

Context: today I checked Signal celluar data usage and saw "only" 38MB in the last 18 hours or so.  But to help test things I sent myself ~15 text only messages while the Signal app was closed and not on WiFi.  After most messaged I opened it and then explicitly closed it so that the push notification would wake it up in the background.  After sending these ~15 messages over the course of a couple minutes, my Signal cellular data usage jumped to 120MB from the 38MB it started with just minutes ago.

**Comment by varenc** [comment]
for context, you can see in the logs that my tests begin around 11:47 of today. I used the Signal desktop app to send the messages to myself.

Note that it seems like Signal creates an iOS notification, but then quickly clears this so I only see it on my phone for less than a second. I'd speculate this happens because Signal creates an iOS notification for a new message, but then since it's a self-sent message it then quickly observes that the message is marked as seen and then clears the iOS notification.   If the app was running in the background (because I didn't explicitly kill it) then I wouldn't see an iOS notification at all.  My guess is that the high data usage is associated with a push notification starting the app up in the background when it's not running at all.

Also, there's a ~5-second delay between sending the message to myself and seeing the iOS notification.  Not sure where this delay in being introduced, but this might be a result of all the work/bandwidth the app does on wake up.  In my testing from awhile ago it seemed like this delay was even larger. I think the logs corroborate this in the time between `application:didFinishLaunchingWithOptions:` and `application:didReceiveRemoteNotification` but am not sure.

I think you can see a specific example of the app waking in the background at `2018/11/20 11:50:57:083` in my latest log. I believe that's Signal starting from a push notification.  I then send myself a few messages, and then explicitly kill the app at `2018/11/20 11:51:11:613`.

**Comment by michaelkirk-signal** [comment]
Thanks for the details @varenc. 

The new logging confirms that the large data usage, at least during your test period, is due to syncing your contacts with your Desktop instance. Signal does this automatically - on startup, periodically, and whenever your local contacts information changes to make sure you see up-to-date info on your desktop device.

Each of your contact syncs is about 32MB, which is quite a bit larger than I'd expect. Any ideas why that might be?

Do you have photos set for most of your contacts in your system contacts?

**Comment by varenc** [comment]
Thanks for looking into this! You are indeed correct. I have a lot of contacts and a long time ago I had Facebook sync profile photos with my contacts so many of them do have photos associated with them.  I find it rather useful that Signal shows me these and it makes the app friendlier and a bit more social.

It sounds like Signal is uploading these photos each time?  Surely there must be some way to confirm that there's been no change to the photos and re-uploading isn't necessary? If avoiding re-uploading is a pain, perhaps just an option to disable contact photo syncing could be valuable for people like me.

Thanks again for investigating!

**Comment by varenc** [comment]
@michaelkirk-signal, just wanted to follow up on this. Is there anything else I can do to help with this?

As another data point: In the last 7 days I've used the Signal iOS app for 13 minutes, but it has logged 1.6hrs of background activity.  It must be spending a lot of time waking up and re-syncing the same contacts photos.

It sounds like removing my contact photos or stopping use of the Desktop app could be a workaround for now...but are there any others? I mainly use Signal on the Desktop so if there was just a way to turn off push notifications on my phone that'd be amazing, but I assume that would interfere with Desktop app usage?  Alternatively, some way to turn off push notification/background wakes for certain group chats could really help.  (local iOS notifications are already disabled, but I assume messages there still trigger background app wakes)

If any part of the solution here seems like a bug fix that's well suited to a new contributor, let me know! Scratching my own particular itch is very motivating...

**Comment by michaelkirk-signal** [comment]
The case of having a 32MB contact sync is a bit of an outlier, so it hasn't yet become the single most important thing for us to work on. That said, having a ton of contacts and avatars is something we'd love to do a better job of supporting.

One way to help the process along as a contributor would be to add some debug logging around the statistics of the contact sync. e.g. how many contacts have avatars, how big is each avatar, whats a running total of the avatar sizes, etc.


A good entry point to start investigating the code would be here, where we build up the contact sync information:
https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncContactsMessage.m#L138

**Comment by varenc** [comment]
on it! I got the Signal app running locally and have added some logging. So far just the avatar size. Oddly OWSLogging I add to "OWSSyncContactsMessage.m" isn't showing up in my xcode console, but I think that's because its listed under the Pods project instead of the Signal one?  Any ideas how to see this log? But I can definitely see Signal syncing full avatar data everytime I set "Sync Contacts" in the debug UI!  I think this is just updating the local contact database, so still fuzzy on how the Desktop app comes into play on this.

Stepping back a bit, I think the best fix would be to avoid syncing contact data to the desktop if there's been no changes.  Is there any sort of contact freshness info or hash that already exists I could make use of? My guess is probably not.  Alternatively I could potentially just look into something less elegant like only syncing avatar data to the desktop once per day. Not the ideal solution, but would definitely address the pain point. (Also I'd need to actual figure out how/where contacts are being uploaded to the desktop...)

That's getting a bit ahead of myself...for now I'm just going to try to just get some good logging in, figure out how to view the log output for something in the Pods project, and submit a small PR with just that!

**Comment by ngie-eign** [comment]
...
> Stepping back a bit, I think the best fix would be to avoid syncing contact data to the desktop if there's been no changes. Is there any sort of contact freshness info or hash that already exists I could make use of? My guess is probably not. Alternatively I could potentially just look into something less elegant like only syncing avatar data to the desktop once per day. Not the ideal solution, but would definitely address the pain point. (Also I'd need to actual figure out how/where contacts are being uploaded to the desktop...)
...

Why not do some simple things like:
1. Compare the avatar file size.
2. Hash the avatar content.
... to see whether or not an update is required?

**Comment by tcurdt** [comment]
@varenc Last time I checked there was no way to check for contact freshness as you call it. (Thanks Apple! (sarcasm)) One would have to walk through all contacts and do some hashing. It's been a while but back in the days it was rather slow to go through all the contacts. Just something to keep an eye on.

**Comment by varenc** [comment]
@tcurdt my look through Apple's docs seems to confirm this.  No way to get a last modified time.  You can add an observation for changes to the contacts, but I'm not sure if that'll always wake the app and just doesn't seem likely it'd be as reliable as needed.

@ngie-eign that'd certainly be the right type of approach! Sadly though I'd need to figure out how to ask the Signal app contact store some info and I don't see anything in the current contact sync code that does that.  It seems to just read all the contacts and send them out without any queries for what already might be there. (this makes sense when this updating just happens locally, as it does for most users, but for people like me with the desktop app open those contacts then get sent over the network to the desktop app as well).  If you have any tips on where to get started with this in the Signal iOS codebase let me know.

**Comment by markdiamond** [comment]
The same issue has struck me for the first time with my data usage increasing from a typical 44 Mb per month to almost 1.4 Gb in three days ... costing a fortune. The sequence of events leading up to this, so far as I recall, was (a) update Signal, (b) almost immediately switch to flight mode (c) a short time later, attempt to send a message, forgetting that I was in flight mode, (d) restore normal mode. A few hours later I discovered that Signal was still trying to send the message from step c although it had (I think) successfully sent other messages in the intervening period. The next thing, I received an alert from my ISP saying that I had exceeded my monthly allowance.

Debug log (which means nothing to me) at : 
https://debuglogs.org/4ad9ceec2b29627df22c6839c769aa5dbb2b05fcec6e7f770083352ad82a70c7

**Comment by varenc** [comment]
@markdiamond are you also using the Signal desktop app?  Do you have a lot of contacts or photos attached to your contacts?

If not, that might be a slightly different data use problem.  Definitely still an issue though...but maybe separate from this issue.

For my own problem where I have a lot of contacts with images and the Signal Desktop app running somewhere, I was able to "fix" this just by denying the Signal app access to my contacts on my phone. This means that on my phone it appears as if I'm just chatting with a bunch of phone numbers, but on my desktop, where I mostly use Signal, it's able to access my contacts and show me their info/contact image just fine. 🤷‍♂️

**Comment by markdiamond** [comment]
@varenc I have only the phone app and around 150 contacts ... and none of the contacts has an associated photo. Syncing usually takes only a small amount of data. As I remarked, the problem seemed to be somehow related to the fact that Signal first attempted to send a message while the phone was set to flight mode and persisted in attempting to send it (but failing) despite exiting flight mode and successfully sending other messages. Even after I deleted the failed/failing message, the data usage appeared to increase dramatically. Eventually, in the hope of stopping the ever-increasing usage/cost, and despite not having any real idea of what was causing the problem I uninstalled the app (which was verion 4.48.17) and reinstalled (now version 4.49.13). The data usage has returned to normal. ... but I'm no longer in a position to provide any useful information about the root cause!

**Comment by jboycha** [comment]
Are you still using this crap? Their rocket scientist has just joined as freshman before he invents the rocket to solve your problem !!🤣🤣

**Comment by marshalleq** [comment]
Came here because signal used up my wife’s entire data plan (1.25GB worth) in a single call of about 45mins. I’m guessing not quite the same issue?

**Comment by christophgrander** [comment]
I am using the latest version of signal on my android device (android 10.0). I do not use signal on any other devices. Signal used 846 mb of mobile data in one day. During this day I did the following:
- sent about 100 messages
- received about 100 messages
- searched for and sent about 5 gifs
- received about 5 gifs
- did not send or receive any photos/files/videos
- had a 10ish minute voice only call

I also use whatsapp which only needed 14.3 mb accpurding to my phones settings app for roughly the same activity as above. In the average month signal consumes about 7.6 gb of data on my phone. Before I used signal, I only used whatsapp, which consumed 1 gb of data on average in those times.

Please fix data consumption of signal, otherwise I will have to deinstall it.

**Comment by christophgrander** [comment]
Me and my friends send a lot of gifs which might explain a large part of signals data consumption on our phones. Afaik signal does not compress gifs in the search. In other words, if i search for gifs it will always download the full gifs for all search results. Also sigbal appearently does not cache gifs, so it will redownload the same gif over and over again for every search. I believe whatsapp does only download a short compressed part of a gif when searching and then downloads the full gif once one is selected. This way gof searching is much faster on whatsapp and also whatsapp consumes much less data

**Comment by marshalleq** [comment]
A gif is pretty small even if not compressed.  And in my case, we're comparing live video with either WhatsApp or Skype.  Using 1.25G of data in 40 mins is not normal for these other apps even on video, which would use more than a Gif.  Much more.

**Comment by Ascendor** [comment]
It's definitely the GIF usage. I used a simple network analyzer, and scrolling through the GIFs pumps up the bandwidth usage to 10+ MB/s. Is there a chance we will see compressed GIF thumbnails in the preview any time?

**Comment by varenc** [comment]
In my personal experience, this issue seems resolved so I'm closing it.  Though I don't know what changed.

I still have 500+ contacts with photos and I still leave the Signal desktop app open on multiple computers and I'm in some large/active Signal threads, though not as many as before, but despite all that, Signal's cellular data usage in the last 3 months is "only" 400MB.  So very good compared to what it used to be.

I'm guessing that Signal no longer syncs contacts with the Desktop app every time it wakes up? The "Chats" pane in the Desktop app's preferences show's the last time contacts were synced.

Cheers!

p.s. thanks stale bot for reminding me of this.

**Comment by marshalleq** [comment]
OK, I guess we need to open another ticket for the insane large data usage when video calling then.
