### ISSUE TITLE
typo in hyperlink/strings/icons, should be sealed-sender (not secret-sender) 

### ISSUE THREAD

**Issue by five-c-d** [signalapp/Signal-iOS#3964]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is a problem with use of incorrect "secret sender" versus the official branding for the new feature of "sealed sender" in some icon-metadata and code comments.  This has user-visible impact in at least one place -- there is a hyperlink that the enduser can click within signal4ios, which launches their browser and takes them to the wrong URL.  

Related, signal4android bug report == https://github.com/signalapp/Signal-Android/issues/8324

Related, signal4android pull request == https://github.com/signalapp/Signal-Android/pull/8325/commits/720561ba11d216b28525a1c627425d3310e24a93

Correct URL == https://signal.org/blog/sealed-sender/
Incorrect URL == https://signal.org/blog/secret-sender/

Line-of-code#A with user-visible problems == https://github.com/signalapp/Signal-iOS/blob/master/Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m#L257

Line-of-code#B with user-visible problems == https://github.com/signalapp/Signal-iOS/blob/master/Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m#L283

Other places where 'secret sender' nomenclature probably ought to eventually be correct, to avoid confusion == https://github.com/signalapp/Signal-iOS/blob/master/Signal/src/ViewControllers/MessageDetailViewController.swift , and referent https://github.com/signalapp/Signal-iOS/blob/master/Signal/Images.xcassets/ic_secret_sender_indicator.imageset/Contents.json , plus strings (need to fix these **before** transifex folks start working on them ideally please), https://github.com/signalapp/Signal-iOS/blob/master/Signal/translations/en.lproj/Localizable.strings#L2096 == table section label, SETTINGS_UNIDENTIFIED_DELIVERY_SECTION_TITLE: "Secret Sender"
https://github.com/signalapp/Signal-iOS/blob/master/Signal/translations/en.lproj/Localizable.strings#L2108 == table section footer, SETTINGS_UNIDENTIFIED_DELIVERY_UNRESTRICTED_ACCESS_FOOTER: "Enable secret sender for incoming messages from non-contacts and people with whom you have not shared your profile."   Also, note the use of 'unidentified delivery' (aka unidentified sender presumably) which conceivably might be another thing needing alteration if unified branding of 'sealed sender' is desired?  

### Steps to reproduce
- install latest signal4ios 
- activate sealed-sender 
- tap hyperlink for more info on new feature

**Actual result:**  HTTP 404 file not found 

**Expected result:** opens non-typo'd  https://signal.org/blog/sealed-sender 

### Device info

**Device**: not tested 

**iOS version**: not tested 

**Signal version:** master branch

**Comment by michaelkirk-signal** [comment]
Fixed, and will be released shortly. Thanks!
