### ISSUE TITLE
Sealed sender settings unidentified

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#3966]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Settings are not properly labelled.

### Steps to reproduce
- Go to settings
- Go to the second option (privacy settings)
- Scroll down to the sealed sender settings

**Actual result:** Some strings are not printed out.

**Expected result:** The sealed sender settings should have meaningful labels.

### Screenshots

![181031-signal-sealed-sender-settings-bug](https://user-images.githubusercontent.com/5073538/47782964-6dafb800-dcf9-11e8-887a-94fda2cabf50.png)

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3

**Signal version:** 2.31.0.25 beta

### Link to debug log

https://debuglogs.org/006b11b905e9901fd156be6cd510bdfe4f866bafaaefae7c127b67a611b5cc3e.zip

**Comment by michaelkirk-signal** [comment]
Sorry about that - this should be fixed.
