### ISSUE TITLE
Add "recently used" emojis at the top -- same as on iMessage

### ISSUE THREAD

**Issue by ventz** [signalapp/Signal-iOS#3985]
Suggestion - consideration for adding "recently used" emojis at the top -- the same way iMessage does on iOS.

It seems very cumbersome to scroll though/find the common ones (ex: thumbs up, smiley face, etc), when it would be very easy/helpful to have them at the top, just like iOS does.

Thanks.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

Also in this case, screenshots or video of your desired behavior would be helpful. The system emoji picker already has the "Frequently Used" page first, so, as-is I'm not sure what feature you're requesting.

**Comment by ventz** [comment]
@michaelkirk-signal - Ill post on the forum. This was supposed to say on macOS - same as iMessage there.

**Comment by michaelkirk-signal** [comment]
Ah, you might want to clarify there that this is a feature request for Signal-Desktop, not Signal-iOS.

**Comment by ventz** [comment]
Thanks -- the word 'iOS' must have been on my mind, because everything about the thread is 'iOS' tagged, and somehow I completely did not register that :)

**Comment by ventz** [comment]
Created it under Signal-Desktop (https://github.com/signalapp/Signal-Desktop/issues/2891)
