### ISSUE TITLE
Blocking wipes name and avatar from profile

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#4021]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Blocking and unblocking a random unser leads to the signal profile’s avatar and name being wiped. 

### Steps to reproduce
- block a random signal user
- unblock the signal user
- go to the signal settings

**Actual result:** Any given avatar and name are deleted from the signal profile.

**Expected result:** The avatar and the name of the profile shouldn’t change or vanish.

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3.

**Signal version:** 2.31.0.29 beta

### Link to debug log
https://debuglogs.org/7b10cff2d8526e799ecc92787d31f961c3da6567b87baf38ddbe2b27a0ac7e87.zip

**Comment by michaelkirk-signal** [comment]
I'm going to close this as it was fixed by #4030, which was released to beta last week actually.

Please re-open if you see this with the current beta.

And thanks for the quality reports!
