### ISSUE TITLE
Sender’s profile name not used in notifications

### ISSUE THREAD

**Issue by s4y** [signalapp/Signal-iOS#4024]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A user’s profile name doesn’t appear in message notifications from that user. Only their phone number appears. (Note: this is on the border between a bug and a feature request. If you’d prefer to track it as a feature request, sorry for submitting it here! I’m taking a risk because it’s small and I don’t have a forum account.)

### Steps to reproduce
- Receive a message from someone who is not in your contacts but does have a profile name.

**Actual result:** The notification identifies them only by phone number.

**Expected result:** The notification identifies them by their profile name, or name and number, or this is user-configurable.

### Device info

**Device**: iPhone X

**iOS version**: 12.1

**Signal version:** 2.30.2.16

**Comment by michaelkirk-signal** [comment]
Hi @s4y, this is intended behavior. 

The forum would be a better place to discuss design decisions like this: https://community.signalusers.org/

**Comment by s4y** [comment]
Cool. Moved to https://community.signalusers.org/t/show-profile-name-in-notifications/4803
