### ISSUE TITLE
Sharing bug

### ISSUE THREAD

**Issue by ethylmorphine** [signalapp/Signal-iOS#4047]
Chat view doesn’t show the last sent (shared through menu) stuff, i.e. photos or audio.

How to reproduce:
0. Open Signal, do not kill the app.
1. Open a picture in other messenger, 9GAG, Reddit, whatever.
2. Share it through a share menu by Signal, select a contact and send.
3. Double-tap on Home, go straight to Signal.
4. Picture might be sent but you’re unable to see it in the chat view.

I have to say this bug is rather random. It may depend on some factors like the size of an object and speed of its delivery because I found out smaller objects are usually displayed instantly in contrast with more massive stuff like audio. This bug is not a big deal though but I still find it annoying a bit.

**Comment by rocknjohn** [comment]
I can confirm this bug exists in 2.32.0.14 Beta.

To add:
* The text "attachment" with the photo icon appears in the conversation list, that works as expected, even though the image itself is not visible in the conversation.
* Sending a message in the conversation makes the shared images visible.
* Importantly, in my testing on 2.32.0.14 Beta, the bug occurs only when sharing an image, as the OP described, _when the previous message from the other person_. But if I had sent the previous message in the conversation (text or image), then my shared image is visible in the conversation. (implies it may be related to key ratcheting?)

**Comment by tzs1** [comment]
I often get this bug when sharing an image from the media gallery. Shared image is shown as last message, while other user reply is shown before it, hence my message is shown as last message of the chat and I cannot flag it as "read".

![_sharing_bug](https://user-images.githubusercontent.com/31325316/49727693-29f18c00-fc71-11e8-81fa-2aca3f041ceb.png)

https://debuglogs.org/9b020927ce87fda7ede2dfa741ef3310bfaa69220e41a89dfc6d8102c20a39bc.zip

**Comment by abjbhat** [comment]
I can confirm this is an issue with the 2.32.0 iOS client. I shared an image using the iOS share sheet (is that the right term?) from the native pictures app. The shared image doesn't show up for some time. 

The [first image](https://user-images.githubusercontent.com/2337475/49774854-1818f300-fd1c-11e8-8871-f16ca3ac23cb.jpeg) is taken at 7:29 am and the [conversation view image](https://user-images.githubusercontent.com/2337475/49774855-18b18980-fd1c-11e8-90d4-30003eff3991.jpeg) was taken at 7:31 am. The shared image doesn't show up the conversation view, but its preview can be seen from the conversation list.

![signal_share_01](https://user-images.githubusercontent.com/2337475/49774854-1818f300-fd1c-11e8-8871-f16ca3ac23cb.jpeg)
![signal_share_02](https://user-images.githubusercontent.com/2337475/49774855-18b18980-fd1c-11e8-90d4-30003eff3991.jpeg)

**Comment by AnsuRio** [comment]
Bug is still there in 2.32.2! Really annoying bug that needs to be resolved...

**Comment by BernhardBln** [comment]
Same here, also experiencing this when simply sharing text, not only with media.

E.g. when reading a web page in the browser and sharing the URL with someone.

I can then also see it in the message list as preview, but not when I open the actual conversation.

**Comment by michaelkirk-signal** [comment]
This should be fixed in the latest version of Signal.
