### ISSUE TITLE
Signal crashes when pictures are opened

### ISSUE THREAD

**Issue by maltemayer** [signalapp/Signal-iOS#4048]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when a picture is being opened.

### Steps to reproduce
- recieve a picture
- try to open picture by tapping on it
- signal crashes

#### Additional way to reproduce
- go to “show all media” in a conversation
- try to open a picture by tapping on it.
 

**Actual result:** Signal crashes immediately. In the all media list of a conversation thumbnails are loaded very slowly and the background collour is black. 

**Expected result:** Signal shouldn’t crash but show the selected picture. In the all media list thumbnails should load more performantive.

### Device info

**Device**: iPhone 5

**iOS version**: 10.3.3

**Signal version:** 2.32.0.13 beta

### Link to debug log

https://debuglogs.org/a6478f726e02e11baed7f4e82258d110c9418bb5c3a1c4f9cd550b7046c0ed32.zip

**Comment by michaelkirk-signal** [comment]
@maltemayer  - can you supply a crash log? 

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by michaelkirk-signal** [comment]
Thanks for the debug and crash log. 

It's not obvious to me when looking at your debug log when the crashing was happening. For example it looks like the app is always running a few hours between launches. And it looks like it was running 8 hours before you submitted the debug log.

To narrow it down, could you toggle debug logging off/on then reproduce the crash and immediately submit another debug log?

**Comment by michaelkirk-signal** [comment]
Actually don't worry about any more logs @maltemayer - I was able to make sense of that crash report.  It's an issue specific to older versions of iOS.

It's in https://github.com/signalapp/Signal-iOS/pull/4055 and should be released to the beta channel before too long.

Thanks for the report!

**Comment by michaelkirk-signal** [comment]
This fix is now available in the beta.
