### ISSUE TITLE
Message sending fails and keeps failing for a certain period

### ISSUE THREAD

**Issue by varjolintu** [signalapp/Signal-iOS#4057]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a while the messages sent via iOS client start to fail. Resending them won't work until you have waited for 8-10 minutes. Then you can send a few messages again, but after a few minutes the failing starts again. If you have linked a desktop client, it has no problems sending the messages even while the iOS client is in the "wait state". The client is connected to the server all the time and I can receive any messages normally. This has been happening since the last iOS stable version update.

### Steps to reproduce
- Send a messages until the delivery fails
- Try sending a message from linked desktop client

**Actual result:** 
Sending succeeds from the desktop client always. Sending from iOS client succeeds only after 8-10 minute wait.

**Expected result:** 
Sending should work normally from iOS client without these weird 8-10 minute gaps where the sending just fails immediately.

### Device info

**Device**: iPhone SE

**iOS version**: 12.1

**Signal version:** 2.30.2.16

### Link to debug log

https://debuglogs.org/0e697a2b534edeca96a4ce2467e84832f11bd87202f1b44a4f5a5b645a69317.zip

**Comment by michaelkirk-signal** [comment]
This is fixed in the current beta. https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

If you don't want to join the beta, one way to avoid this bug in the meanwhile is to ensure you're not unnecessarily killing the Signal app between usages.
