### ISSUE TITLE
Landscape mode image view has wrong top spacing when iOS Hotspot is enabled

### ISSUE THREAD

**Issue by rocknjohn** [signalapp/Signal-iOS#4060]
The landscape view conversation is locked so I cannot add this bug there: https://github.com/signalapp/Signal-iOS/issues/937

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
When iOS hotspot is enabled, viewing an image in landscape mode leads to blank space the size of iOS's blue hotspot banner above the horizontal image viewer.

### Steps to reproduce
- Enable hotspot on phone
- In a conversation, tap to view an image large and rotate phone horizontally to landscape mode

**Actual result:** Notice the blank gap above the image viewer the same size as iOS's blue hotspot banner. 

**Expected result:** This errant padding should not exist and image viewer should fully fill the screen (or the hotspot banner should be shown in this gap but that's valuable real estate in landscape view, so the former may be preferred).

### Device info
**Device**: iPhone 6
**iOS version**: 12.1
**Signal version:** 2.32.0.14 Beta

**Comment by CR0CKER** [comment]
Landscape mode for photos? Holy shit, so cool. Where do I sign up for this feature?
