### ISSUE TITLE
iPhone XR support

### ISSUE THREAD

**Issue by UMAD** [signalapp/Signal-iOS#4063]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal hasn’t been updated to support iPhone XR resolution. Text is big and blurry, spelling suggestions appear under the keyboard...etc

### Steps to reproduce
- install signal on iPhone XR

### Device info

**Device**: iPhone XR

**iOS version**: 12.1

**Signal version:** 2.31.0.39

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
