### ISSUE TITLE
Message time shown in chat list is not correct

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4064]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Last saturday I woke up at 5am, turned on the mobile data and checked Signal. See that my friend sent a message at 5.04 am, a minute before (but it doesn't show "1 min ago"), check the conversation and verify that the message was actually sent the night before at 11.10pm.

Message sent: 1543011014912
Message received: 1543011017348

### Steps to reproduce
- can't say how to reproduce, happened only once

**Actual result:** time of the last updated chat is the same of the current time, not the last message's time.

**Expected result:** time of the chat should be the same of the last message sent.

### Screenshots
Screenshots taken at 5.05am.

![different_time](https://user-images.githubusercontent.com/31325316/49108999-df900880-f289-11e8-836a-a224de5c4e53.png)

### Device info
**Device**: iPhone 8 Plus

**iOS version**: 12.1

**Signal version:** 2.32.0.14

### Other device info
Other user has an Android device, can't say which version.

### Link to debug log
 https://debuglogs.org/e3a4a8760e96460129d17e1722e5f962a22fe569c8dc8b01be1c2ac9b9b0fd0b.zip

**Comment by tzs1** [comment]
![signal-time-incorrect](https://user-images.githubusercontent.com/31325316/49445567-80bf1780-f7d2-11e8-899a-38a933c51d12.png)

Another example. I sent myself an image at 10.50am, then deleted it. Chat still shows 10.50am as last message time.

**Comment by tzs1** [comment]
Happened again.

Steps to reproduce:
1. Set iPhone in airplane mode
2. Receive a message
3. Switch to mobile data
4. Open Signal 

Actual result:
Message shown as received a minute ago. If I open the conversation, it was sent an hour before. Tapping on the “more info” shows that it was sent one hour before and received a minute ago 

Expected result:
Message should be show the sent time and not the received time.

**Comment by michaelkirk-signal** [comment]
I'm a little confused. This is the Signal-iOS repository, and though you mention your iPhone, all your screenshots are of Signal Desktop.

So, if you are trying to report a bug with Signal-iOS, is it possible for you to reproduce the behavior and provide steps/screenshots that don't involve Signal Desktop? I think that'd be easier to understand from my perspective.

If you are instead trying to report a bug with Signal Desktop, please do so here: https://github.com/signalapp/Signal-Desktop/issues/new

**Comment by michaelkirk-signal** [comment]
Oh! 

I think I see what's you're trying to do. Those __are__ Signal-iOS screenshots, but you have two joined together so it looks like Signal-Desktop. You have so much blurred out that it wasn't clear.

**Comment by denver-s** [comment]
The problem persists.

 Steps to reproduce:
- using a one-member chat (or "Note to self" I suppose)
- set iPhone to airplane mode
- from Signal Desktop, send a message (in my case, time is 15.51)
- wait a couple of minutes (15.53)
- turn on mobile data or Wi-Fi
- Signal iOS shows the message time to be 15.53 (received time)
- going to the info of the specific message, it shows 15.51 (sent time)

Signal Desktop:
![image](https://user-images.githubusercontent.com/31325316/70246676-5c48a300-1778-11ea-94b4-d039c1ea8f35.png)

Signal iOS after turning on mobile data:
![image](https://user-images.githubusercontent.com/31325316/70246740-797d7180-1778-11ea-8ad5-4318f5ee1eb2.png)

Message info is correct:
![image](https://user-images.githubusercontent.com/31325316/70246803-9ade5d80-1778-11ea-99e1-27334ba2bc46.png)

**Comment by denver-s** [comment]
Bug still happening in version 3.19
