### ISSUE TITLE
Incoming calls cancel voice messages

### ISSUE THREAD

**Issue by dreamflasher** [signalapp/Signal-iOS#4066]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On receiving a call (can be Signal, phone call, or any app that takes over the screen), if one is currently recording a voice message, that recording is interrupted and the voice message discarded.

### Steps to reproduce
- Record an voice message (still holding the button to record it)
- Get an incoming call

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
the current voice message is discarded

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
sending the current voice message

### Device info

**Device**: iPhone X

**iOS version**: 12.1

**Signal version:** 2.3.10

**Comment by vjcharles** [comment]
ping.
This issue and https://github.com/signalapp/Signal-iOS/issues/4359 are significant annoyances I and friends have noticed. 

Other than fixing this, another solution is allowing a previously recorded message to be cached as it was when the interruption occurred. Then when returning to Signal the user can choose to send, or cancel and start again.

**Comment by josephg** [comment]
I’ve been sending a lot of voice messages recently and there are a number of ways to lose a voice message in progress:

- incoming call
- rotate phone (#4359)
- have an alarm go off
- siri becoming activated
- iOS low battery modal appears over the app

This is really high priority for me - I feel anxious sending voice messages because of how many I’ve incidentally lost. @vjcharles ’s suggestion here sounds good to me!

**Comment by IteDas** [comment]
How come that something like this is not voiced within years and not even commented on. We are now switching back to WhatsApp just for this issue.
