### ISSUE TITLE
Contact photos not displayed

### ISSUE THREAD

**Issue by aikon** [signalapp/Signal-iOS#4068]
- [x] I have searched open and closed issues for duplicates
  - Issue #3084 appears to be similar/the same; it is closed, yet I am still experiencing the issue.
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Contact photos are typically not displayed in either the contact list or in individual chats. Instead, the generic colored circles with the contact's initials is displayed. Occasionally, modifying the contact's iCloud contact card photo will cause the contact's photo to be displayed in Signal for some period of time, but not always.

### Device info

**Device**: iPhone XS
**iOS version**: 12.1 (16B92)
**Signal version:** 2.31.0.39

### Link to debug log

A quick look at the [debug log](https://debuglogs.org/7da6beabdfacc0ffc6655ecb5f8bb448566d78e99d60e5f0715d980ed98797f8.zip) suggests an issue with `downloadAvatarForUserProfile` getting a 403 status code.

**Comment by NightMachinary** [comment]
I have noticed that avatars aren’t available till you have a mutual chat going on.
