### ISSUE TITLE
Message not marked as delivered

### ISSUE THREAD

**Issue by wojciechrak** [signalapp/Signal-iOS#4071]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since few days (one of the recent updates, I guess) my messages are not marked as delivered (double check mark). When sent, they are correctly shown as "sent" with single check mark icon. Then they are only marked as "read" with white double check marks. The other party is also using iOS (both iPhones 6s). I've tried to fix this by reinstalling app, also talked the other party to reinstall, and then this bug appeared also to them.

### Steps to reproduce
- send a message
- wait for message to be delivered

**Actual result:**
There is no indication that message is delivered.

**Expected result:** 
Message is marked as "read" (with no status between "sent" and "read"), when it's actually read.

### Screenshots

1. 
![img_1576](https://user-images.githubusercontent.com/3034230/49386832-b3103c80-f720-11e8-8ae6-3b4d903b1dc6.jpg)
2. 
![img_1577](https://user-images.githubusercontent.com/3034230/49386837-b73c5a00-f720-11e8-8b5a-75531b6ce300.jpg)

### Device info

**Device**: iPhone 6s

**iOS version**: 12.1

**Signal version:** 2.31.1.3

### Link to debug log
Doesn't crash app

**Comment by bamin74** [comment]
I can confirm this bug on my end also. Only appears to be with the iOS version of Signal and only occurred recently with the latest update. Android version seems to be working correctly.

**Comment by wojciechrak** [comment]
@Cerberus0 I can confirm that bug no longer appears after upgrading to 2.31.2.0

**Comment by bamin74** [comment]
Confirmed that it is working. Thank you!

**Comment by michaelkirk-signal** [comment]
Thanks for following up.
