### ISSUE TITLE
Disappearing last line in text bubble

### ISSUE THREAD

**Issue by ethylmorphine** [signalapp/Signal-iOS#4074]
iOS 12.1.1, Signal 2.32.0.21

Steps to reproduce:
1. Text a long message (2 or more lines in text bubble) and send it.
2. Right after that reply to another message utilizing Reply To This message.
3. Wait until time stamp goes down to the last sent message (don’t know how to explain it)
3. Last line of previous sent message would disappear.
4. Send a new message and that line would reappear.

**Comment by ethylmorphine** [comment]
Sure. I use iPhone 7. It happens somewhat randomly, so I will provide screenshots when it happens again. Quite a strange bug.

**Comment by ethylmorphine** [comment]
I’ve made a screen recording of this bug. It’s really easy to reproduce. Take a look [here](https://drive.google.com/file/d/1uwzGpAUlaFEA3PnXYz7eNm-yaE6T-tMG/view?usp=drivesdk).

**Comment by u32i64** [comment]
@MehrabKamrani No, the text disappears on the original message, not on the reply (where it is intended to as you said), and appears back at the end of the recording.

**Comment by MehrabKamrani** [comment]
@u32i64 Thanks, got it now.

**Comment by michaelkirk-signal** [comment]
This was fixed with https://github.com/signalapp/Signal-iOS-Private/pull/304
