### ISSUE TITLE
Landscape mode in “View all media” scroll the media gallery to the top

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4078]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When closing the landscape mode in “View all media” gallery, it scrolls the gallery list to the top.

### Steps to reproduce
- open a chat that has a lot of media
- go to the media gallery
- open a recent media
- go to landscape mode
- exit the landscape mode or just exit the single media viewer

**Actual result:** list is not at the same point as before, but it is now scrolled a bit to the top

**Expected result:** it should go back to the gallery at the same point as you were before when clicked on the media.

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1

**Signal version:** 2.32.0.22

**Comment by tzs1** [comment]
Now it crashes 2.33.0.9

**Comment by denver-s** [comment]
Still happening in version 2.39.0.6.

- open a chat
- go to the media gallery of that chat
- rotate phone horizontally
- gallery scrolls back to January (in my case)

**Comment by denver-s** [comment]
I cannot replicate, I assume this has been fixed. Closing.
