### ISSUE TITLE
[Landscape Media] Screen Goes Black on Calls

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-iOS#4079]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While making a call and viewing an attachment, rotating the phone makes the screen go off.

### Steps to reproduce
- While on a call
- Open a photo
- Rotate the phone
- Watch that screen goes black

### Device info

**Device**: iPhone 6S

**iOS version**: 12.1

**Signal version:** 2.32.0.22

**Comment by michaelkirk-signal** [comment]
I can't reproduce this... here's what I'm doing:

- Send a photo to Alice
- Call Alice
- While still on the call, hit the back button to return to the conversation screen with Alice.
- Tap on the previously sent photo
- Until this point the phone has been in portrait, *now* rotate it to landscape
- Screen is now black

Does that reproduce the issue for you?

**Comment by Xashyar** [comment]
> 
> 
> I can't reproduce this... here's what I'm doing:
> 
>     * Send a photo to Alice
> 
>     * Call Alice
> 
>     * While still on the call, hit the back button to return to the conversation screen with Alice.
> 
>     * Tap on the previously sent photo
> 
>     * Until this point the phone has been in portrait, _now_ rotate it to landscape
> 
>     * Screen is now black (for me it's not)
> 
> 
> Does that reproduce the issue for you?

Yes the only difference is that i used a previously sent photo.
I can send the logs afterwards if necessary.

PS: the rotation does not work at all on iOS 9.3.5 (iPad 2)

**Comment by michaelkirk-signal** [comment]
> Yes the only difference is that i used a previously sent photo. I can send the log afterwards if necessary.

Please do submit a log.

**Comment by Xashyar** [comment]
> 
> 
> > Yes the only difference is that i used a previously sent photo. I can send the log afterwards if necessary.
> 
> Please do submit a log.

@michaelkirk-signal 
Hello again, you were right there's no problem, it's just a result of proximity sensor going off as a result of phone rotation. :D
However as I've already mentioned the feature doesn't work AT ALL, on iOS 9.3.5, is that intended?

**Comment by michaelkirk-signal** [comment]
> However as I've already mentioned the feature doesn't work AT ALL on iOS 9.3.5, is that intended?

 Can you open up a new issue with a complete issue template that details your experience?

**Comment by Xashyar** [comment]
> 
> 
> > However as I've already mentioned the feature doesn't work AT ALL on iOS 9.3.5, is that intended?
> 
> Can you open up a new issue with a complete issue template that details your experience?

4 sure.
