### ISSUE TITLE
Disappearing Messages Aren't Disappearing

### ISSUE THREAD

**Issue by damengilland** [signalapp/Signal-iOS#4081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Despite messages being set to expire, old messages aren't expiring on iOS or MacOS.

### Steps to reproduce
- Set messages to expire.
- Wait
- See old messages still present

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Messaging aren't deleting.  Everyone across all my chats are reporting this same bug.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I would expect every message set to delete to always be deleted across all devices for all users.

### Screenshots

<img width="752" alt="screen_shot_2018-12-08_at_10_06_42_pm" src="https://user-images.githubusercontent.com/1106778/49685319-c7e03c00-fb35-11e8-96a1-7f7b273757e1.png">

### Dupe

Feel free to mark this as a duplicate... just trying to bump up priority.

* Seems similar to this bug that was closed: https://github.com/signalapp/Signal-iOS/issues/1428

* And this bug: https://github.com/signalapp/Signal-iOS/issues/2086

* And this news story. https://motherboard.vice.com/en_us/article/bj3pxd/signal-disappearing-messages-not-disappearing

**Comment by michaelkirk-signal** [comment]
The disappearing messages setting applies to messages sent *after* you enable the feature. It does not apply retroactively to pre-existing messages.

If it’s not just a misunderstanding, and you are in fact seeing this behavior with messages sent *after* you set the timer, could you follow up with some more specific steps to reproduce like:

- Set disappearing messages time to 1 day
- Send a message to Bob
- That message bubble shows/does not show a disappearing timer
- after one day the message is still there

And then also please supply a debug log with the approximate time that you sent a message which should have disappeared and the time st which you expected it to disappear.

**Comment by damengilland** [comment]
Ah OK... but there's no way to set it retroactively?  Just have the app check the new disappearing message window, and remove any that are past that?

**Comment by michaelkirk-signal** [comment]
Thanks for following up @damengilland. 

I'm going to close this issue, as we reserve Github for reporting bugs with existing functionality. 

The forum is a better place to discuss feature requests like altering the way that changes to disappearing messages are applied. 

Could you take this discussion over there? It's possible other folks will have some ideas. https://community.signalusers.org
