### ISSUE TITLE
Shared Items not Appearing in Conversations

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-iOS#4083]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Shared items (from other apps) don't appear until you send another message.

### Steps to reproduce
- Use an app (App Store, Photos etc.) to share an item (link, photo etc.) with a signal client
- open signal & view the corresponding chat
- watch the newly shared message is not shown
- send another message for the missing message to appear

### Device info

**Device**: iPhone 6S

**iOS version**: 12.1

**Signal version:** 2.33.0.9

**Comment by 42mandychen** [comment]
I ran into the same problem a few times too. After quitting and restarting, the shared message appears. My signal version is 2.33.1.0, iOS version is 12.1.2, and device is iPhone Xs.

**Comment by NicolasCGN** [comment]
I have the same problem too and it's reproducible (iOS 12.1.2, iPhone XR)

**Comment by Xashyar** [comment]
related: #3993

**Comment by michaelkirk-signal** [comment]
I believe this has been solved. Please re-open if you can reproduce.
