### ISSUE TITLE
Issue Cloning the repo.

### ISSUE THREAD

**Issue by ialeidan** [signalapp/Signal-iOS#4084]
I got an issue cloning the repo. 
I used the command: 
git clone --recurse-submodules https://github.com/signalapp/Signal-iOS

but I get in one of the submodules:
error: Server does not allow request for unadvertised object 71a3d8c6605e1fa934b37c6d0dbad2b4d03e75e1
Fetched in submodule path 'Pods', but it did not contain 71a3d8c6605e1fa934b37c6d0dbad2b4d03e75e1. Direct fetching of that commit failed.

Thanks.

**Comment by michaelkirk-signal** [comment]
This has been pushed.

**Comment by nderkach** [comment]
Still have the same issue, now with `d74b4688bd6876a7038d30b0ce6ae3f24844ff88` commit.
