### ISSUE TITLE
Search bar is shown even if it should not be visible

### ISSUE THREAD

**Issue by tzs1** [signalapp/Signal-iOS#4086]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening Signal, search bar should not be visible, but it is (just a bit).

### Steps to reproduce
- open Signal chat list

**Actual result:** search bar is a bit visible under menu bar.

**Expected result:** search bar should not be visible unless you scroll down.

### Screenshots

![signal-2018-12-13-152610](https://user-images.githubusercontent.com/31325316/49945383-0fc3e200-feed-11e8-8cde-60499d5699eb.jpg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1

**Signal version:** 2.33.0.9

**Comment by kaktusztea** [comment]
I think that is the connection status indicator. If you don’t have connection and Signal tries to reconnect this line acts as a progress bar showing reconnection status.

**Comment by tzs1** [comment]
That is not the case, firstly because I tried scrolling down and in fact it was the search bar, secondly I think that connection status indicator is full width.

**Comment by tzs1** [comment]
I need to say that this behaviour has not happened again. I can’t replicate the same issue.

**Comment by tzs1** [comment]
I think this can be closed now.
