### ISSUE TITLE
Photos sent with text not visible to Android and desktop clients

### ISSUE THREAD

**Issue by gituser94x54102** [signalapp/Signal-iOS#4087]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending text with a photo on iOS, the photo/text is visible on the iOS client but not on Android or desktop clients

### Steps to reproduce
- Tap the "+" sign next to the new message entry space
-Click Photo library
-Select any photo from the phone's library
-Type text in the gray entry bar near the bottom
-Click the send button

**Actual result:** 
The photo (with accompanying text) will appear as intended on the iOS device
The photo (withOUT accompanying text) will appear on the desktop device
The photo (withOUT accompanying text) will appear on the Android device

**Expected result:** 
The photo (with accompanying text) will appear as intended on the iOS device
The photo (with accompanying text) will appear as intended on the desktop device
The photo (with accompanying text) will appear as intended on the Android device

### Screenshots
<img width="1130" alt="screenshot_signal_photo_bug_ios" src="https://user-images.githubusercontent.com/6323205/49977173-4f9dc000-ff13-11e8-8b86-c21d00b9e6e9.png">
<img width="1048" alt="screenshot_signal_photo_bug_android" src="https://user-images.githubusercontent.com/6323205/49977174-4f9dc000-ff13-11e8-8c26-70dd010514a5.png">
<img width="737" alt="screenshot_signal_photo_bug_web" src="https://user-images.githubusercontent.com/6323205/49977176-4f9dc000-ff13-11e8-89b4-bea20bf9f1c2.png">

### Device info

**Device**: IPhone XS Max

**iOS version**: 12.1.1

**Signal version:** 2.32.0.23

**Comment by michaelkirk-signal** [comment]
Fixed in 2.32.1
