### ISSUE TITLE
Can’t dismiss ‘add contact permissions’ dialog box

### ISSUE THREAD

**Issue by donwilkinsonart** [signalapp/Signal-iOS#4089]
I’m trying to get friends to sign up for signal but there is an error where you can’t dismiss the dialog box that relentlessly requests permission to access contacts and gives pause to those I recommend it to.

**Comment by michaelkirk-signal** [comment]
This is the intended behavior. In the past users have forgotten that they disallowed contact access and wonder why they can't see their friends names in the app. 

If you'd like to further discuss design changes, please do so at the community forum: https://community.signalusers.org/ 

We only use Github to report bugs in the intended behavior. If you do file a bug in the future, please follow the issue template.
