### ISSUE TITLE
Show username before phone number in app

### ISSUE THREAD

**Issue by donwilkinsonart** [signalapp/Signal-iOS#4090]
Hi, there is a strange visual error on iOS where in the main list of conversations, user names are cut off after the phone number.

Can you please offer the option to show user name before the phone number. I don’t want to sync contacts for privacy reasons but the username identifier is more important than the phone number digits to be able to quickly message people and so not sure why the usernames are small and cut off the screen following the phone number. 

Offering the option to show usernames only would tidy up the clutter as well.

**Comment by michaelkirk-signal** [comment]
Hi @donwilkinsonart  - this is working as intended.

As mentioned elsewhere, we don't use Github to discuss design decisions. The community forum  https://community.signalusers.org/ is the place for that. So if you'd like to continue this discussion, please do so there - it's much better suited to cross-app concerns like this one.
