### ISSUE TITLE
Delete Call Logs when Disappearing Messages is Enabled

### ISSUE THREAD

**Issue by caveman1973** [signalapp/Signal-iOS#4091]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you have Disappearing Messages enabled, call logs are not deleted. They accumulate and leave your chat history a mess, specially if you enabled and disabled Disappearing Messages.

### Steps to reproduce
Enable Disappearing Messages. Make or receive calls. You'll see that call logs won't disappear.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/1135956/50560737-e8418780-0cea-11e9-8b55-50ccd7b93451.jpg)

### Device info

**Device**: iPhone SE

**iOS version**: 12.1.2

**Signal version:**  2.32.2.0

**Comment by michaelkirk-signal** [comment]
This is the intended behavior. 

If you'd like to discuss changing this feature across platforms, please see the forums: https://community.signalusers.org
