### ISSUE TITLE
Swift Compiler Error in MessageSender+Promise.swift "ambiguous use of fulfill"

### ISSUE THREAD

**Issue by arslan0786** [signalapp/Signal-iOS#4092]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When i try to compile Signal with Xcode 10.1, It does not work.
I have successfully installed pods but while compiling code i get error
"Ambiguous use of fulfill" on MessageSender+Promise.swift

### Screenshots
<img width="1273" alt="screenshot 2018-12-31 at 6 21 12 pm" src="https://user-images.githubusercontent.com/22588946/50561070-f31b0d00-0d28-11e9-9b84-83edd96c71d2.png">

**Signal version:** 2.33.0.9

**Comment by michaelkirk-signal** [comment]
Hey @arslan0786 - we don't use Github as a forum for developer support. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to have this conversation: https://community.signalusers.org/

Also, be sure you're following the steps in BUILDING.md - specifically it seems like you might have installed the wrong versions of some dependency.

**Comment by arslan0786** [comment]
@michaelkirk Thank you very much.
