### ISSUE TITLE
Very slow at creating new conversation because of TrueCaller

### ISSUE THREAD

**Issue by Ralle** [signalapp/Signal-iOS#4094]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone XR

**iOS version**: 12

**Signal version:** Z.Y

### What

Creating a new conversation is very slow when having TrueCaller installed. TC creates a contact in your phone with 1000s of phone numbers of spammers. It would be nice if Signal would ignore this specific contact (with the name 'SPAM').

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by johnsmith3321** [comment]
This is Truecaller Premium version

https://blackapks.com/en/truecaller-premium

Check it out
