### ISSUE TITLE
Not receiving messages until i reply. Some messages not recvd at all

### ISSUE THREAD

**Issue by Orangebl00d** [signalapp/Signal-iOS#4097]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages from contact are not showing in notifications and not showing in chat until after i reply.

See screenshot attached.

Message from contact did not appear. I reply at 8:26pm and then 15-30 seconds later the message from 12:39 appears in chat.

Friend said they sent another message last night that has not appeared even after i have received a different reply.

Problem is happening intermittently but enough to create issues.

Same issue was happening on friends end few weeks ago but not happening now.

### Steps to reproduce
- Check for messages
- No messages from friends appear
- I reply and then out of time stamp order messages appear.

**Actual result:** 

**Expected result:** I should be receiving notifications and actual messages in real time.

### Screenshots

![img-0531](https://user-images.githubusercontent.com/36681611/50728970-8f615d00-10f7-11e9-8ea3-caa50c95233d.JPG)

### Device info

**Device**: iphone8+

**iOS version**: IOs 12.1.2

**Signal version:** 2.32.2.0

### Link to debug log

https://debuglogs.org/3b641a05deaa6b742550207d534ad2d1ad36e5dd93b8fc4bc98a798413883881.zip

**Comment by tiiiecherle** [comment]
We are having the same problem and I consider this a big one which would be nice if it had priority to solve.
We are using signal on multiple iphones. The problem occurs on all of them irregularly.
Someone sends a message and the message is only delivered when writing a message to the same person, even if it is several hours later.
This is a basic massenger problem if messages are not delivered (and therefore no notifications sent).
Would be really nice to see a quick reliable fix.
Thanks in advance.

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
