### ISSUE TITLE
Share Title for Hyperlink

### ISSUE THREAD

**Issue by ClayMorde** [signalapp/Signal-iOS#4098]
Many messaging services when a URL is sent automatically get the top image, give a preview, etc. There are many people who think this may be a security vulnerability and/or don't want it. Or don't want it to be default. 

Here is a closed issue involving this:
https://github.com/signalapp/Signal-iOS/issues/1857

A solution that will be much easier to implement, not as much of a security risk an many people could enjoy would be when using the Share Sheet action in iOS to provide the title to the link as well as the url. This would help people know what is being shared more easily with out having to click on it.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
