### ISSUE TITLE
iOS Sharing Screen Capture

### ISSUE THREAD

**Issue by ClayMorde** [signalapp/Signal-iOS#4100]
If I take a screen picture and then edit the picture using iOS screen picture editor that comes up and try to share that photo to Signal directly, it does not send. I have to take the screen picture, edit it, save it, and then share the photo to signal from the Photos app.

**Comment by Crocmagnon** [comment]
I also experience this issue, though for me the picture seems sent (it’s displayed in the messages list but I don’t know if the recipients received it)

**Comment by michaelkirk-signal** [comment]
This issue should be resolved in the latest version of Signal available on the app store.
