### ISSUE TITLE
Lag Time for Sharing from Share Sheet

### ISSUE THREAD

**Issue by ClayMorde** [signalapp/Signal-iOS#4101]
When I share from the Photos App or share a URL from Safari and then go right into the Signal App it is not there. It takes a little while before it appears as sent. I don't know if this is a limit of the iOS, issue with Signal or me just needing to calm down, wait and know that it has sent.

**Comment by denver-s** [comment]
I think this lag has been fix and now it takes the right amount of time to share a photo.
