### ISSUE TITLE
 Still receive badges for muted groups

### ISSUE THREAD

**Issue by designakt** [signalapp/Signal-iOS#4102]
### Bug description
After muting a group I still see this group still notifying me about new meessages through the the badge on the app icon. 
Makes the badge icon pretty useless as soon as you have one bussy muted group.
This seams to be a part of #2418 that hasn't been fixed, or changed again since then.

### Steps to reproduce
- join a bussy group chat
- mute the group chat
- wait for messages in the muted group

**Actual result:** 
Badge on App Icon notifys me about number of unread messages in muted chat.

**Expected result:**
Badge only notifys me about new messages from non-muted chats.

### Device info
**Device**: iPhone 6s
**iOS version**: 12.1.2
**Signal version:** 2.33.0.12

**Comment by brian428** [comment]
To the dev team, personally if I mute a group I really just want to stop notifications but still be able to see new items in the badge. So if you consider making this change, please add an option to the mute settings to mute everything (including badge indicators) vs. muting only the notifications but still allowing badge notifications.

**Comment by carlospwk** [comment]
This page is the first result I got when I googled about Signal group chats and badges. Currently I'm in a group chat which I muted and have +30 badges. I have no interest in knowing if those badges are from the group chat but I do want badges from chats with individual people. 

> To the dev team, personally if I mute a group I really just want to stop notifications but still be able to see new items in the badge. So if you consider making this change, please add an option to the mute settings to mute everything (including badge indicators) vs. muting only the notifications but still allowing badge indicators.

This approach seems like win-win.

Is there any plan to add this feature to Signal?

**Comment by sayhar** [comment]
I also have this problem, as do many others. It's incredibly annoying, to the point of pushing me to leave all signal groups I'd rather mute. Please fix it! Please.

**Comment by celikarda** [comment]
They added a switch to solve this issue after waiting three years and one year later, they removed it again? Anyone know why? 

This is so annoying! I might turn off notifications completely...

**Comment by urielgolab** [comment]
In the latest version of Telegram Desktop for Windows, Archived chats display a badge of unread messages and  **it is also counting unread for the app's icon**, which makes me think that I have something left to read, and NO, it's just another annoying group chat that I don't want to leave but also don't want to bother me. 

I would also remove Archived chats badge but would let display the badge of the archived chats.

**Comment by lllamnyp** [comment]
> In the latest version of Telegram Desktop for Windows, Archived chats display a badge of unread messages and it is also counting unread for the app's icon, which makes me think that I have something left to read, and NO, it's just another annoying group chat that I don't want to leave but also don't want to bother me.

Same here for Linux. Also I would like to not see archived chats being displayed in the Unread metafolder.

**Comment by arteteco** [comment]
Telegram desktop v. 2.1.5, still the same problem, the badge is still there for muted chat, unchecking "Include muted chats in unread count" doesn't seem to make a difference.

**Comment by wuwendell** [comment]
iPadOS 15 on iPad Pro 2021 and iOS 15 on iPhone 13 and the issue persists. I don't know what the hold up is, seems like a pretty easy fix.

**Comment by alexbogias** [comment]
Why wont fix?

**Comment by phoenixeliot** [comment]
Looks like it got closed automatically because people weren't commenting on it.
