### ISSUE TITLE
Can't send many pictures at once

### ISSUE THREAD

**Issue by zapashcanon** [signalapp/Signal-iOS#4103]
Hi,

Currently, if you want to send many pictures, you have to repeat the process many times. It should be possible to select many pictures at once, and then, send all of them.

Cheers.

**Comment by michaelkirk-signal** [comment]
There is some existing discussion about this here: https://community.signalusers.org/t/sending-multiple-attachments-at-once/2459/30

We don't currently have this feature, but if you'd like to test it out once we do, consider joining the beta.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
