### ISSUE TITLE
While connected to Bluetooth headphones, if you answer a call and subsequently switch audio output to your headphones, will make the app switch between different audio output options non-stop.

### ISSUE THREAD

**Issue by sdsdsasad12312** [signalapp/Signal-iOS#4104]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Answering a call while connected to Bluetooth headphones will make the app switch between different audio output options by itself non-stop.

### Steps to reproduce
- Make sure to have Bluetooth headphones connected to your iOS device
- Receive a call and answer it
- Switch audio output to your bluetooth headphones

**Actual result:** App switches between different audio output options (e.g. "iPhone" and BT headphones) non-stop, making it impossible to hear what the caller says, as it's a disruptive behavior.

**Expected result:** The audio output shouldn't switch by itself non-stop once it's changed to your bluetooth headphones.

### Device info

**Device**: iPhone 7 Plus

**iOS version**: 12.1.2

**Signal version:** 2.33.1

**Comment by michaelkirk-signal** [comment]
I frequently use bluetooth for calls and have never personally experienced this - can you think of any other factors which may be contributing?

What bluetooth device are you using? Is it reproducible when they are fully charged and in range?

Can you please reproduce and include a debug log immediately after you experience this?

To submit a debug log: Settings > Advances > Submit Debug Log

So that I can find the relevant logging, when you send the log, let me know what time (local time zone) the call started.

**Comment by sdsdsasad12312** [comment]
Hey again,

I just came back from reproducing the bug, and I just realized that the audio output doesn’t instantly switch to my Bluetooth headphones once I answer the call, rather it stays on “iPhone”; but after I switch it to my headphones the bug occurs. The report should be edited by the time you read this. Thanks!

Headphones: Sennheiser HD4.40

PD: not sure if related but when I’m getting called while connected to my headphones, the ringing sound plays on my iPhone rather than on my headphones)

**Comment by sdsdsasad12312** [comment]
Debug log: https://debuglogs.org/dea740280de95c244978a2d567ffbd5baeaf547bb9d3865de3702e5689c0bc23.zip

**Comment by obounaim** [comment]
Hello,

I am also affected by the same issue.

Iphone 6
IOs version 12.1.4
Signal Version 2.37.2.0
Earbud JBL TUNE 205BT Wireless

How to reproduce the problem :

1. Make sure the Earbud are connected to the phone
2. Ask a person to call you on signal
3. Try to route the sound to the earbud

The step 3 fails and the sound works only on the phone ear speaker. 
It works fine if I initiate the call.
 
The Earbud works perfectly when I receive a call on WhatsApps.

**Comment by vlall** [comment]
I've received this same issue above using my car's Bluetooth audio.

Iphone 8
IOS version 12.2
Signal version 2.36.1.0
VW Passat 2015
