### ISSUE TITLE
how to send "OWSSignalServiceProtosEnvelope" using OWSMessageSender in iOS

### ISSUE THREAD

**Issue by kabhi92** [signalapp/Signal-iOS#4107]
Very Important for me Please answer this:
how to send "OWSSignalServiceProtosEnvelope" using OWSMessageSender in iOS
which method should I call please write code.

**Comment by Cerberus0** [comment]
Hi @kabhi92,

As stated in the project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md), this issue tracker is only meant for bug reports. I suggest that you post your question on the community forum instead: https://community.signalusers.org/c/development/ios-development

If you would like to continue contributing to this project here on GitHub, I recommend reading the contribution guidelines and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md

**Comment by michaelkirk-signal** [comment]
What @Cerberus0 said... 

(thanks @Cerberus0!)
