### ISSUE TITLE
Debug app crashes when contact consists a phone number with empty label

### ISSUE THREAD

**Issue by jakublipinski** [signalapp/Signal-iOS#4108]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The application compiled for debugging crashes on startup if there is a contact consisting a phone number with an empty label

### Steps to reproduce
- compile the latest version of the application using XCode
- create contact with phone number and empty label with following steps:
  * launch the Contacts app
  * add new contact by tapping `+` button
  * enter contact name eg. `Test`
  * add phone number by pressing `add phone`
  * enter some phone number assosciated with a Signal account
  * tap the label next to the entered phone number
  * tab the `Add Custom Label`
  * leave the text box empty and tap `return` on the keypad
  * save the contact by tapping `Done`
  * (the label for your phone number will display `phone` but intenally it will be an empty string)
- launch the application in debug mode

**Actual result:** 
The app triggers an `OWSAssertDebug(value);` in `Contact.m:263` even though the app is prepared to handle phone numbers without labels:
https://github.com/signalapp/Signal-iOS/blob/5568482e4cd24908d3be67e6f02879fe2fc6dac2/SignalServiceKit/src/Contacts/Contact.m#L262-L268

**Expected result:** 
The app should not crash and should display `Unknown` label in the debug build too. This is what the App Store version does.

### Device info
**Device**: iPhone XS

**iOS version**: 12.1.2

**Signal version:** https://github.com/signalapp/Signal-iOS/commit/5568482e4cd24908d3be67e6f02879fe2fc6dac2

### Debug log
```
2019-01-15 15:33:10:508 Signal[23887:8816391] [Contact.m:263 -[Contact nameForPhoneNumber:]]: Assertion failed: value
Assertion failed: value
(null)
```

**Comment by michaelkirk-signal** [comment]
It sounds like you're hitting a debug assertion while building the app yourself. We don't
do developer support on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss development support: https://community.signalusers.org/

If you'd like to update that assert, consider opening a pull request.

**Comment by jakublipinski** [comment]
@michaelkirk-signal I did open [a pull request](https://github.com/signalapp/Signal-iOS/pull/4109) and linked it to this issue.

**Comment by michaelkirk-signal** [comment]
Sorry for missing that.
