### ISSUE TITLE
Send button not shown while sharing an image from signal with screen lock turned on

### ISSUE THREAD

**Issue by Raghul-S-1994** [signalapp/Signal-iOS#4114]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
   While trying to share an image from signal to signal with app lock turned on, the New Message text box and Send button is not shown.

### Steps to reproduce
- Turn on screen lock
- Select an image in any Signal conversation
- Share that image with Signal
- Authenticate the Signal App
- Select a user to share the image with

**Actual result:** The New Message text box and Send button are not available

**Expected result:** The New Message text box and Send button should be available 

### Screenshots

Actual result

![signal_with_no_send_button](https://user-images.githubusercontent.com/20701077/51405580-afbffb80-1b7c-11e9-8c31-1284e13065e0.jpeg)  

Expected result

![signal_with_send_button](https://user-images.githubusercontent.com/20701077/51405582-b3538280-1b7c-11e9-8a15-679687e1e8fd.jpeg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1.2

**Signal version:** 2.34.0.24

**Comment by Raghul-S-1994** [comment]
The workaround to obtain the message textbox and send button is to either swipe down the notifications or swipe up the control center and then return back to signal.

**Comment by denver-s** [comment]
This should have been fixed in 3.0.0.2
