### ISSUE TITLE
Unlink device confirmation dialog shows encrypted device name

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-iOS#4116]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
- link recent Signal desktop (1.20.0 or later)
- unlink the device linked in previous step

**Actual result:** Linked device name on the confirmation dialog is a Base64-looking string

**Expected result:** Actual linked device name is shown in the confirmation dialog

### Screenshots

![signal-2019-01-20-162948](https://user-images.githubusercontent.com/4365731/51440581-561d1580-1cd1-11e9-9e51-de11bc85d352.png)

### Device info

**Device**: iPhone SE

**iOS version**: 12.1.2

**Signal version:** 2.33.1.0

**Comment by michaelkirk-signal** [comment]
Thanks for reporting. This was fixed in the 2.34.0 beta, available now.

https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
