### ISSUE TITLE
Security: Messages re-appeared 9 hrs after they should have been disappeared

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#4118]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Around 9 hours ago, I was having a conversation on signal with disappearing messages set to 5 minutes. I was using an iOS device. I believe the other party was using an Android device. I also have signal for desktop on my computer and I believe the other party does too.

During this conversation, signal for desktop was open but I believe my computer was asleep.

Both parties in the conversation were present at the time.

Some 9 hours later when I returned to my computer, after connecting to network, Signal for desktop started fetching all the messages that I received during the time it was disconnected... including the ones that were disappeared! Now these messages quickly disappeared again on the desktop (tho I managed to take a screen shot of one), but it made me wonder... how were they retrieved? And from where? These were only the received messages. Somehow the ones I sent weren't there.

While I was trying to articulate the problem, I was wondering where should I open this ticket? Is this an issue of the desktop client? Or iOS? Was Signal server keeping the messages after they were supposed to disappear? Or was it my phone that kept them in the database longer than it should have? I ended up deciding on iOS since that's the primary client I was using for this conversation. Please feel free to move the ticket to desktop if needed.

### Steps to reproduce
While I'm not sure if this is going to reproduce it exactly, here's how it happened for me:
- Disappearing messages were set to 1 week prior to this conversation.
- Open signal for desktop and while texting on signal iOS, let computer go to sleep or disconnect it from network. 
- Change the disappearing messages to 5 mins.
- Exchange a bunch of texts and wait until they all disappear.
- Go back to computer and watch signal for desktop fetching everything and flashing the messages right in front of your eyes like a dejavu :)

**Actual result:** Disappeared messages were shown on signal desktop 9 hours after they were supposed to disappear.

**Expected result:** Signal shouldn't have had any memory of that conversation. Let alone being able to retrieve it.

### Screenshots

<img width="806" alt="screenshot-signal" src="https://user-images.githubusercontent.com/453701/51702387-95b66b00-200b-11e9-9a18-65c333bd0475.png">

### Device info

**Device**: iPhone 6s

**iOS version**: 12.1.3

**Signal version (iOS client):** 2.33.1.0
**Signal version (Desktop client):** 1.20.0

**Comment by charlesmchen-signal** [comment]
@mrphs 

Linked devices are capable of operating completely independently of the primary device. For example, you can still send messages from Signal Desktop even if your phone has a dead battery. What this means is that each device has its own separate ephemeral message queue on the service.

These messages were not re-appearing. What happened when you reconnected your laptop was that it began retrieving messages from its independent ephemeral queue, and as you noticed it quickly cleared the messages during synchronization. For privacy and metadata reasons, the service does not know which messages are disappearing (or even who has enabled the feature) so each client must do this processing locally.

Hopefully this explanation helps. Thanks for using Signal!

**Comment by mrphs** [comment]
> What happened when you reconnected your laptop was that it began retrieving messages from its independent ephemeral queue

Well then this is quite a serious issue that defeats the purpose of having disappearing messages.

First, at no point (ie while setting the disappearing messages) it is clear to user that this is the expected behavior. 
Second, I can think of a million ways that this can put the security of people at risk. When you set the disappearing messages to 5 mins the expectation is that it does indeed disappear after 5 mins. Not that it will disappear "quickly" after signal for desktop realizes it's been expired.
