### ISSUE TITLE
Is there a public beta test available ? 

### ISSUE THREAD

**Issue by F3000** [signalapp/Signal-iOS#4119]
Maybe I’ve TestFlight?

**Comment by Cerberus0** [comment]
Hi @F3000,

Yes, Signal iOS has a public beta that you can join by following the instructions here: https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

As stated in the project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md), this issue tracker is only meant for bug reports. I suggest that you post any future questions that you may have on the community forum: https://community.signalusers.org/

If you would like to continue contributing to this project here on GitHub, I recommend reading the contribution guidelines and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md
