### ISSUE TITLE
Incoming call failed

### ISSUE THREAD

**Issue by Barracuda6** [signalapp/Signal-iOS#4121]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving an incoming call, the iPhone's lock screen shows a "call failed" Signal entry and a new incoming call immediately after. The call fails immediately after answering.

This happened twice in a row with calls from the same contact, and has happened on previous occasions. It seems that if I wait a few seconds before answering the call, instead of answering immediately, the call will come through.

The phone was connected through a VPN on cellular service, and was connected to a car via Bluetooth.

### Steps to reproduce
- (unknown)
- Receive incoming call
- Answer call

**Actual result:** Call fails.

**Expected result:** Call succeeds.

### Device info

**Device**: iPhone 7

**iOS version**: 12.1.3

**Signal version:** 2.34.0.26

### Link to debug log

https://debuglogs.org/ceee5d561c208bbb02ea8308aceab8316fbb957799af03abcda77caa4aa8f7de.zip
Note: Debug logging was enabled after the first occurrence, and before the second occurrence. Log was generated immediately after the second occurrence.

**Comment by johanw666** [comment]
I noticed the same issue. iPhone 8 calling an Android device. The Android device immediately got  a message that the call failed.

Debuglog: https://debuglogs.org/9b18bbb24ec2307567e8ca0128a3f170f1df79f3cf633016ea79951bcb16b30c.zip
