### ISSUE TITLE
Landscape orientation is not activated when Signal opens

### ISSUE THREAD

**Issue by teor2345** [signalapp/Signal-iOS#4127]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I open Signal with my iPad locked in Landscape orientation, Signal displays in Portrait orientation. Then when I switch away from Signal, and switch back, Signal animates a switch to Portrait orientation.

### Steps to reproduce
- lock your device in Landscape orientation
- open Signal
- check first orientation
- use Home Button to switch away from Signal
- use Dock to quickly switch back to Signal
- check second orientation
- use Home Button to switch away from Signal
- wait long enough for Signal to activate the Touch ID lock
- use Dock to switch back to Signal
- check third orientation
- (you can repeat the quick switch to get Landscape again)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

First and third orientations are Portrait. Second orientation is Landscape.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

All orientations should be Landscape.

### Screenshots

I can not sufficiently obfuscate the screenshots on my iPad.
Let me know if that's an issue, and I'll go fix them on my desktop.

### Device info

Device: iPad (iPad5,2)
iOS Version: 12.1.1 
Signal Version: 2.35.0.13 

### Link to debug log

I can't open the zip file on my iPad. I would like to know what it contains before I link to it publicly. (The app doesn't explain, or let me view it before submitting.)

If it's important, please let me know, and I'll use my laptop to check it.

### Link to Code Responsible

The bug is probably in this code, or the subsequent fixes:
https://github.com/signalapp/Signal-iOS/commit/39de96ac261b89542767b4f971f9d91dac2f2cce#diff-497fb8e87e6b43d3eed8fa7aa9a38927R71

**Comment by michaelkirk-signal** [comment]
Thanks for reporting this.

There was an issue with Signal not respecting landscape mode on launch which should be fixed in the latest app store version.

We intentionally do not support landscape mode for the screen lock authentication screen. This behavior is consistent with your iOS lock screen functionality. I don't expect face ID to work or pin entry to fit in landscape.
