### ISSUE TITLE
add iOS Large Title on HomeScreen

### ISSUE THREAD

**Issue by redflamingoo** [signalapp/Signal-iOS#4129]
Some time ago, iOS had new Guidlines in terms of designs. I think the navbar on top of the homescreen looks much better with a large title instead of a little. 

WhatsApp does it right, as you can see in the picture. On Signal we can Name the big Title "Signal" or "Chats".
I would be really glad if you make this little change. Thank you.

Best regards

![img_2630](https://user-images.githubusercontent.com/44530419/52591462-e7e4f200-2e3b-11e9-818c-821dd0c3b15f.jpg)
![img_2631](https://user-images.githubusercontent.com/44530419/52591465-ea474c00-2e3b-11e9-97fc-78684c6fd6e5.jpg)

**Comment by michaelkirk-signal** [comment]
Hey @redflamingoo  - thanks for the input.

Just so you know, we don't use GitHub for feature requests or discussing design changes. We reserve GitHub only for bugs with intended functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss something like this: https://community.signalusers.org/
