### ISSUE TITLE
Sharing image from a Signal chat to another is impossible

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4130]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since the "forward" option has not yet been implemented, I tried to share an image from "note to self" to a group in which I am the only member. After selecting the share icon and choosing the chat, there is not a way to actually send it. Just a "cancel" button.

### Steps to reproduce
- open chat
- click on an image
- click the "share" icon
- select Signal
- click on another chat

**Actual result:** You can't send it, just cancel it.

**Expected result:** You should be able to add a caption and send it.

### Screenshots
Notice that navbar color at panel 3 is white, making it invisible.

![inkedsignal-sharing-bug_li](https://user-images.githubusercontent.com/31325316/52806970-9a11f900-308a-11e9-87f2-4ed59d5ea318.jpg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.1.2

**Signal version:** 2.36.0.6

### Link to debug log
https://debuglogs.org/50e37b31f7570f17b1dc88933dd7c03bd5d8ed46bc7b553adec283d3f2c58993.zip

**Comment by manufoy** [comment]
It works just fine for me.
![signal-2019-02-16-125627](https://user-images.githubusercontent.com/9674850/52894755-7239a700-31ea-11e9-8993-2aae4f9d3ef8.jpeg)

**Comment by manufoy** [comment]
https://github.com/signalapp/Signal-iOS/issues/4114

**Comment by denver-s** [comment]
This bug seems to be fixed in 3.0.2.
