### ISSUE TITLE
Compose message button causes Signal to freeze

### ISSUE THREAD

**Issue by manufoy** [signalapp/Signal-iOS#4132]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When pressing the 'compose message' button (the button with the square and the pencil, on the top right corner), on my iPhone 6S, it causes my the application to freeze and become unusable. 

### Steps to reproduce
- Open Signal
- Press 'compose message' button (the button with the square and the pencil, on the top right corner)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

Video of bug in action: https://www.dropbox.com/s/29y9zdjvaxivpq3/IMG_4993.mov?dl=0

### Device info

**Device**: iPhone 6S

**iOS version**: 12.1.4 (16D57)

**Signal version:** 2.35.0.13

### Link to debug log

https://debuglogs.org/80b5a9b2f90d64db3f8a36dabca5088c12789102583142f655b88383d02fd294.zip

**Comment by michaelkirk-signal** [comment]
Was this debug log taken immediately after you experienced the freeze? Or at what time (local timezone is fine) did you experience the freeze?

**Comment by manufoy** [comment]
The local time is shown in the video linked.

**Comment by manufoy** [comment]
Here is another debug log I created immediately after making it crash again.  https://debuglogs.org/e9613202465ea2d26039d2f507d26fd7600ac93b66ee0e7aad532ef4d57a76e1.zip
This was at around 8:54am Australia Western Standard Time (GMT/UTC+8)

**Comment by manufoy** [comment]
I ended up finding the cause of the issue. It's because I had a contact added for the purpose of listing spam numbers. There is another issue open related to this, but at the time of creating this issue, I wasn't aware that it was the cause of what I was experiencing. 

https://github.com/signalapp/Signal-iOS/issues/4094

**Comment by manufoy** [comment]
I have since removed the problematic contact, now it works just fine.

**Comment by michaelkirk-signal** [comment]
This should be addressed with the 2.37 release available in the app store.

**Comment by manufoy** [comment]
Great. Just tried it. While the menu popping up is a lot slower with the contact added, it doesn't crash anymore. Thanks.
