### ISSUE TITLE
Issue persists! Uses cellular data even with Wifi-Assist switched off

### ISSUE THREAD

**Issue by thomas2net** [signalapp/Signal-iOS#4133]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I re-open the issue of https://github.com/signalapp/Signal-iOS/issues/866
Possibly affects iOS users only (I have not seen it on Android).
iPhone users experience occasional but heavy use of cellular data during audio or video conversation over wifi, possibly when wifi signal goes weak, despite Wifi-Assist being switched off in the settings.

### Steps to reproduce
I don't know yet how to systematically trigger the problem -- it is expensive to test!

**Actual result:** Talk over Signal with wifi on while cellular data is also enabled and wifi-assist is switched off. Sometimes, large amounts of cellular data are used.

**Expected result:** Provide warnings (e.g. three beeps and a text message) that cellular data is now used instead of wifi.  Possibly provide preliminary warning, e.g. a high pitch to low pitch tone, to warn that wifi data rate is falling.

### Device info

**Device**: iPhone 7

**iOS version**: 12.1.4

**Signal version:** 2.35.0.13

**Comment by purpleplatypus** [comment]
@thomas2net What's an iPhone 7S? Did you mean iPhone 7?

**Comment by thomas2net** [comment]
Corrected to iPhone 7 without S. Apologies.

**Comment by michaelkirk-signal** [comment]
WebRTC routes audio traffic in whatever way it thinks will get it the best quality. 

If you don't want Signal to use Cellular data, please disable cellular data in System Settings > Signal > Cellular Data
