### ISSUE TITLE
Landscape is not supported by Safety Numbers popover

### ISSUE THREAD

**Issue by purpleplatypus** [signalapp/Signal-iOS#4134]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in landscape orientation, trying to view safety numbers still displays the popover in portrait mode. This doesn't change the orientation of the rest of the app, but it's awkward. I didn't see this in the feedback for the Beta, so please close this bug if this was intended design.

### Steps to reproduce
- Open any conversation
- Rotate phone to enter landscape mode
- Go to the contact info screen
- View the safety number for that contact

**Actual result:**  Safety number popover is in portrait mode.

**Expected result:** Safety number popover is in landscape mode, consistent with rest of app.

### Device info

**Device**: iPhone SE

**iOS version**: 12.1

**Signal version:** 2.35.0.13

### Link to debug log
Upon request. It seems superfluous for a design bug.

**Comment by tzs1** [comment]
I can replicate this bug (beta 2.38.0.9).

**Comment by Mihahn** [comment]
Can't reproduce this, but the barcode is missing in landscape mode.
