### ISSUE TITLE
Use of undeclared identifier 'OWSLegacyContactDiscoveryOperation'

### ISSUE THREAD

**Issue by KhaliqCitrusbits** [signalapp/Signal-iOS#4135]
<img width="971" alt="screenshot 2019-02-19 at 12 11 42 pm" src="https://user-images.githubusercontent.com/47349571/52996484-9641f600-343f-11e9-81d2-64fefbdd0f75.png">

Add SignalServiceKit Pod then build will get the above error.

Steps:-
1. Create new project in XCode 10.1.
2. Add Pod file.
3. All all the pods from signal-iOS Pod file.
4. Install pods.
5. Build project.

**Comment by michaelkirk-signal** [comment]
We don't use Github for developer/integration support - only for bugs with existing functionality in the published application. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The community forum would be a better place to get development support: https://community.signalusers.org/

That said, you might take a look at the Podfile used in the Signal app for a working example.

**Comment by carolanitz** [comment]
@michaelkirk the class is not declared as public which is why a third party app can not see it. As @KhaliqCitrusbits stated he already coped all of Signals Pods from your podfile.
