### ISSUE TITLE
Link Device Scanner: Support for Front Camera

### ISSUE THREAD

**Issue by RainerHeinz123** [signalapp/Signal-iOS#4136]
This is probably not the right place but did not know where to put it.
My Phone has a brocken rear Camera and i cant activate the Desktop version, can you pleas implement the Front Camera for the QR code, cant see why this is not possible.

Thanks

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
