### ISSUE TITLE
Reset Secure Session Option is Missing

### ISSUE THREAD

**Issue by alichtman** [signalapp/Signal-iOS#4138]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The `Reset Secure Session` option is missing in all of my conversations, both group and individual, in version 2.35.0.13 on my iPhone X. It is still available in Signal Desktop.

Here's a screenshot to show what I'm seeing in the options panel: 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/20600565/53319046-f9e07f00-3896-11e9-9a56-d60d68e3d1c3.png">

I'm expecting there to be an option to reset the secure session in this menu, and I'm not finding it. I also can not find it anywhere else in the app.

### Device info

**Device**: iPhone X

**iOS version**: 12.1.4

**Signal version:** 2.35.0.13

### Link to debug log

https://debuglogs.org/ebd27a575a57f7807bdb1344679655c9251d5f04bc8cf9197e080ab10a21c314.zip

**Comment by shobrook** [comment]
I have the same issue.

**Comment by michaelkirk-signal** [comment]
This is intentional. Only in the event that you receive a message that you cannot decrypt, indicating a corrupt sessions, do we offer the "reset session" UI.

Are you seeing messages that you cannot decrypt? Otherwise, why do either of you want a button to start a new session?

**Comment by alichtman** [comment]
I've sent messages to others that sometimes are not delivered immediately, or aren't sent immediately. In the past, resetting the secure session seemed to fix this issue (some of the time). Was this due to chance? Could resetting the secure session impact message receiving or delivery even when the session isn't corrupted?

**Comment by michaelkirk-signal** [comment]
Resetting the session will not speed up deliverability of your messages, it’s only useful in the rare case that your encryption session with the other party some how gets out of whack and you’re no longer able to decrypt the incoming messages.

If that happens to you on iOS, you’ll see a decryption error message in your conversation with an option to reset your secure session.

**Comment by alichtman** [comment]
Oh, that makes sense. 

> In the past, resetting the secure session seemed to fix this issue (some of the time)

I guess this was completely unrelated. Thanks for clearing that up.

**Comment by tlaurion** [comment]
I have it on Android.

User on IPhone didnt.

Had to tick it and restart Signal for all pending pictures to be received.
