### ISSUE TITLE
project is not running. Getting webRTC module not found in IOS

### ISSUE THREAD

**Issue by mallikarjunareddy94** [signalapp/Signal-iOS#4140]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michaelkirk-signal** [comment]
Hey @mallikarjunareddy94 - Are you following the instructions in BUILDING.md?

I'm going to close this as we don't use GitHub for developer support, only bug reports with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss this: https://community.signalusers.org/

If you're following BUILDING.md, I'd recommend you paste the step you're having trouble with and the exact error text in a forum thread.
