### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by zatziky** [signalapp/Signal-iOS#4141]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I try to register via an iOS Signal app.

### Steps to reproduce
- Open Signal
- Set number & hit **Register**

**Actual result:** SMS nor phone call never received
**Expected result:** I should receive the verification SMS.

### Device info

**Device**: iPhone SE
**iOS version**: 12.1.4
**Signal version:** 2.36

### Link to debug log
I don't see this option.

### Additional info

I've already written to Signal support by email. The answer didn't come.

I've also waited more than 24 hours before trying to get a phone call. Installed/uninstalled the app and again waited. My friends on the same carrier received the SMS. I can recieve the SMS if I try Telegram or WhatsApp too.

**Comment by michaelkirk-signal** [comment]
Hey @zatziky - Sorry you're having trouble, but we don't use GitHub for support requests. The support email is the right channel for this. We'll respond there as soon as we can.
