### ISSUE TITLE
Failing to register: not receiving SMS verification

### ISSUE THREAD

**Issue by Signaluser6** [signalapp/Signal-iOS#4144]
I am a long term Signal user.

Have just reset phone (latest iOS), installed Signal and attempted to register.

Am not receiving SMS verification or phone call.

Please help urgently as I rely heavily on the app for communication.

**Comment by Kubik2000** [comment]
@Signaluser6  my suspicion is you are using VPN turn it off while creating account

**Comment by michaelkirk-signal** [comment]
If you are still having issues, could you follow up with support@signal.org?
