### ISSUE TITLE
Duplicate "Note to Self" when archived in Share to Signal view

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4145]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Duplicate `Note to Self` entry when that thread is archived in the Share to Signal view.

### Steps to reproduce
- Archive `Note to Self` thread
- Open share sheet (e.g. using a photo from Photos app)
- Choose Signal
- Observe the displayed list

**Actual result:** Duplicate `Note to Self` in `Other Contacts`
**Expected result:** Only one `Note to Self` entry.

### Device info
**Device**: iPhone 6 Plus

###### Test 1
**iOS version**: 12.2 Public Beta 3 (build `16E5201e`)    
**Signal version:** 2.36.0.7

###### Test 2
**iOS version**: 12.2 Public Beta 4 (build `16E5212f`)    
**Signal version:** 2.37.0.8
[**Debug log**](https://debuglogs.org/e709e548f1f360538a83f2259f9b309d170e206b4f513a4c970844e81c5fe043.zip)

### Screenshot
![screenshot](https://user-images.githubusercontent.com/19972511/53749575-b3071080-3eb8-11e9-809f-624fb2019bec.jpg)

**Comment by tzs1** [comment]
I cannot replicate this bug, it might have been fixed.

**Comment by u32i64** [comment]
Hmm, I can still replicate it on latest beta (`2.38.0.9`).

**Comment by michaelkirk-signal** [comment]
@u32i64  - do you by chance have multiple entries for yourself in your system contacts?

Try opening system contacts and searching for your phone number.

**Comment by u32i64** [comment]
@michaelkirk-signal I tried searching for my number in the Phone app, it yields only one result. That contact is also marked as `me` because I chose that in *iOS Settings* > *Contacts* > *My Info*.

**Comment by Mihahn** [comment]
I can reproduce the bug on Signal 3.4.0.7. It's shown two times in the "other contacts" section. One entry is at the position where my name should be in the contact list, the other entry is at the end of the list as the last entry. My phone number is only once stored in the "contacts" app and marked as "me" as well. 

But it is the same conversation. I sent a photo to the first entry, archived it and sent one to the second entry and both photos ended up in the same conversation.

**Comment by u32i64** [comment]
Can't reproduce this anymore on:

**Device:** iPhone SE
**iOS version:** 13.4 Public Beta 4
**Signal version:** 3.6.1.4
