### ISSUE TITLE
Cannot activate Signal using SMS or voice call from VOIP

### ISSUE THREAD

**Issue by bmy** [signalapp/Signal-iOS#4147]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to receive activation SMS or call to Twilio numbers

### Steps to reproduce
- I enter a US or UK number to use with Signal, and eventually choose either to re-send the SMS or use a voice call.

**Actual result:** The activation SMS or voice call never arrives

**Expected result:** The activation SMS or voice call should arrive

### Device info

**Device**: iPhone XS

**iOS version**: 12.1.4

**Signal version:** 2.36.1.0

Naturally this could be an issue with Twilio...I have also reached out to them. I noticed that the VOIP service MySudo also doesn't support receiving from the shortcode format the Signal activation service uses. So I thought in the interest of thoroughness I would also file an issue here in case there's a limitation on Signal's end.

I'm trying to register Signal accounts for dozens of users at an organization, so using a VOIP related API like Twilio is the most viable and secure option. According to the article below, this was a known working way to activate Signal.

https://medium.com/@mshelton/using-signal-without-giving-your-phone-number-3a575580f652

Apart from this issue, does anyone know a similar alternative to quickly, easily, and relatively cheaply register so many users without involving physical SIMs? Thank you

**Comment by bmy** [comment]
Upon more testing, it seems some Signal activations use the same 415 phone number system I remember from back in the day. Why the change (that is, why shortcodes to activate only some Signal accounts)? Or, in fact, am I mistaken/doing something wrong?

**Comment by shanghaiknight** [comment]
We really need a way to create signal accounts, that are NOT dependent on phone numbers.

**Comment by michaelkirk-signal** [comment]
Can you follow up with support@signal.org?
