### ISSUE TITLE
Corrupted thread title when opened from Signal's contact details screen

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4149]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The thread title is corrupted when opened from contact screen. Fixed by (at least partially) going to another view (e.g. begin swiping right to go back to inbox or tap the thread title to view thread information and go back).

### Steps to reproduce
- Share a contact who has Signal on Signal.
- (Tapping "Send Message" opens thread with this contact properly.)
- Tap on the contact to see details in a different view.
- There, tap "Send Message".

**Actual result:** Corrupted thread title.

**Expected result:** Non-corrupted title.

### Screenshots
![screenshot](https://user-images.githubusercontent.com/19972511/54070608-0f7c7e00-4273-11e9-8356-0da96bd697af.png)

### Device info

**Device**: iPhone 6 Plus
**iOS version**: 12.2 Public Beta 4 (build `16E5212f`)
**Signal version:** 2.37.0.8

**Comment by tzs1** [comment]
I can replicate this bug.

![immagine](https://user-images.githubusercontent.com/31325316/55183309-d52a4080-518f-11e9-8987-55457587d1d4.png)

**Comment by michaelkirk-signal** [comment]
I'm having trouble reproducing this.

Did you notice this behavior before updating to iOS 12.2?

Do you see this corruption in every thread?
For the threads you have seen it in, do you see it _every_ time you open the thread?
Is it specific to the text of the conversation name? 
Can you provide conversation name text which reproduces this behavior?

Any other details you could provide?

**Comment by u32i64** [comment]
> Did you notice this behavior before updating to iOS 12.2?

No, I didn't test that before I was on the iOS 12.2 Public beta.
And it is still reproducible on the latest stable iOS `12.2`, build `16E277`, Signal `2.38.0.9`, iPhone 6 Plus.

> Do you see this corruption in every thread?
> For the threads you have seen it in, do you see it every time you open the thread?

Yes, the bug reproduces very consistently.

> Is it specific to the text of the conversation name?
> Can you provide conversation name text which reproduces this behavior?

No, I don't it's specific to the name.
I tried 3 different contacts, including `Note to Self`.
All of their names consist of pure ASCII.

---

> Any other details you could provide?

Just noticed this, the bug reproduces **only in portrait orientation**. In both landscape orientations, the thread title is displayed normally after performing the steps in the original post.

Also, if I:
- reproduce the bug.
- turn the phone sideways.

the thread **title disappears completely**! In this state, the only fix is to turn the phone into portrait orientation (then title is displayed normally, without corruptions). Other things like the below **do not make the title reappear**, while in this state:
- turning phone into different landscape orientation directly (with enough speed so portrait is skipped).
- begin swiping right from the edge (to open inbox), but go back before releasing.
- tap the thread title to view thread information and go back.

Also, the "verified" check mark and `Tap here for settings` are not visible (at least distinguishably), whether the title is corrupted or not present as per the steps above.

**Comment by michaelkirk-signal** [comment]
@u32i64 - Is your system language English or something else?

If you're willing, a screen recording of the reproduction steps would be helpful. You could email it to michael@signal.org.

**Comment by u32i64** [comment]
@michaelkirk-signal I've sent you an email.

**Comment by denver-s** [comment]
Hope this can help.

![immagine](https://user-images.githubusercontent.com/31325316/56232421-fbe9e180-6080-11e9-8c67-0cf3c6b0a863.png)

**Comment by u32i64** [comment]
Thanks @denver-s, but I'm unsure on how this will be useful as I've outlined the necessary steps to reproduce the issue in the [original post](https://github.com/signalapp/Signal-iOS/issues/4149#issue-419059251), and I have also [sent an email](https://github.com/signalapp/Signal-iOS/issues/4149#issuecomment-478086399) with a screen recording of the weird behavior ([outlined here](https://github.com/signalapp/Signal-iOS/issues/4149#issuecomment-478050992)) that can be seen after performing the original reproduction steps.

Still, it's a good visual guide on reproducing the issue and clarifies the steps ~~if anyone wants to try this at home~~ :)

**Comment by denver-s** [comment]
I cannot reproduce this issue as of version 3.5.0.12 with iPhone 8 Plus. @u32i64 ?

**Comment by u32i64** [comment]
Can no longer reproduce with Signal 3.5.0.12, iOS 13.4 Public beta 2 on iPhone SE.

Looks like this is resolved then!
