### ISSUE TITLE
Links in Signal - Please give us choice of browser.

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#4150]
Could you give us a choice of browser when we click on a link in Signal?  I use Brave, but of course the default is Safari.  Note that [Google apps allow you to open links in Chrome](https://www.quora.com/How-do-I-change-my-default-browser-in-iOS):

> ... Google apps do provide the option. When you tap a link in an app made by Google, it’ll open in Chrome. If you live in Google ecosystem (Chrome, Inbox, Keep, Maps, YouTube, Translate, Photos, Docs/Drive, Calendar, etc) you may even completely forget the built-in apps are there.

Apparently there is also a way to globally change the handler for http{,s} requests.  It seems to only be available via a browser called "UpTime," [which installs a switch that allows changing to the UpTime browser *or some other browser*](https://www.levvel.io/our-ideas/How-to-Change-your-Default-Browser-in-iOS).  I don't know if there's a way Signal to institute a general solution like that, but at least giving us the choice when we click in Signal itself would be useful.

**Comment by DiagonalArg** [comment]
Even twitter is now allowing us to open links in Brave.  (Long press, and then we have the choice of browser.)  It's time for Signal!

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by inoas** [comment]
Ref https://github.com/signalapp/Signal-iOS/issues/2871

**Comment by inoas** [comment]
Ref https://github.com/signalapp/Signal-iOS/issues/4243
