### ISSUE TITLE
Message timestamp shown as “NOW” if minutes match 

### ISSUE THREAD

**Issue by meteficha** [signalapp/Signal-iOS#4151]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The message timestamp shows “NOW” when the message was sent in the last minute. However, it also shows “NOW” if the minutes component match. For example, a message sent yesterday at 09:32 will show as “NOW” today at 14:32.

I believe this bug was introduced by https://github.com/signalapp/Signal-iOS/commit/b4b4cd61d9fc8c15fedf47c4380b571b0f3ca398.

### Steps to reproduce
- Receive a message. 
- Wait an hour. 
- Check timestamp.

**Actual result:** “NOW”

**Expected result:** An explicit timestamp. 

### Screenshots

![IMG_9928](https://user-images.githubusercontent.com/767816/54260896-23213080-4562-11e9-994e-b60942351221.jpeg)

### Device info

**Device**: iPhone 7 Plus

**iOS version**: 12.1.4

**Signal version:** 2.37.1.0

**Comment by charlesmchen-signal** [comment]
Thanks @meteficha This will be fixed in the next release.

**Comment by tzs1** [comment]
Should be fixed by https://github.com/signalapp/Signal-iOS/commit/e66b45f6ce5bbb985f155714c348b2085e6ef1dd
