### ISSUE TITLE
Can't make audio calls directly from Phone.app Favorites menu

### ISSUE THREAD

**Issue by mruffalo** [signalapp/Signal-iOS#4152]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not able to make Signal audio calls directly from the iOS Phone app's Favorites menu. I recently switched many of the POTS entries in my favorite contacts list with Signal or FaceTime Audio, and I seem to remember being able to call people using Signal from this interface in the past. This doesn't work now though; attempting to call someone simply opens or restores focus to the Signal app.

### Steps to reproduce
(Add a contact to your Favorites in the iOS Phone app, specifying to call them over Signal audio -- next few steps cover one of multiple ways to do that)
- Open the iOS Phone app
- Press the bottom button for the Favorites section
- Add a new entry by pressing the + button in the top left
- Select a contact who you know uses Signal
- In the popup for which type of communication to add to the Favorites menu, press the down arrow next to Call
- Select Signal
- Select the phone number they have registered with the Signal service
- You should see a new entry in the Favorites menu for that person, which should call them through Signal
(Actual behavior to reproduce bug)
- Attempt to call them through Signal from the Phone app, by pressing the new Favorites entry you just added

**Actual result:**
If the Signal app isn't already open, it opens to the conversation list. If it's already open, whatever screen you were already on in Signal (e.g. conversation) is displayed.

**Expected result:**
Your contact should be called through Signal audio.

### Device info
**Device**: iPhone SE

**iOS version**: 12.1.4

**Signal version:** 2.37.1.0

### Link to debug log
I'll be happy to provide one if it seems useful

**Comment by tjmc** [comment]
Does the contact have a country code in the phone number? For example +1 for US. Looking at the code it seems Signal expects this.

https://github.com/signalapp/Signal-iOS/blob/94a377b4fec143a6d505f01a9dffc55a8de8026c/SignalServiceKit/src/Contacts/PhoneNumber.m#L93

**Comment by charlesmchen-signal** [comment]
Hi @mruffalo Please open signal by trying to call from favorites (as you describe above) then submit a debug log to matthew@signal.org . Thanks.

**Comment by charlesmchen-signal** [comment]
Thanks @mruffalo - this issue will be fixed in the next release, v2.38.0.

**Comment by mruffalo** [comment]
Thanks, much appreciated! Not a big deal, but seemed worth reporting.

**Comment by AliAkinK** [comment]
> Thanks [@mruffalo](https://github.com/mruffalo) - this issue will be fixed in the next release, v2.38.0.

Hi, sorry to bump an old thread. It seems this is still persisting.
