### ISSUE TITLE
notification sounds in group messages can't be set to "none"

### ISSUE THREAD

**Issue by baumfrisstkatze** [signalapp/Signal-iOS#4153]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When message sound in groups is set to "none" there is still a notification sound played whenever there is a new notification

### Steps to reproduce
- go to a group chat
- go to group info
- under notifications set "message sound" to "none"

**Actual result:** whenever there is a new notification from that group a sound will be played

**Expected result:** there should be no message sound, just the visual notification

### Device info

**Device**: iPhone XS

**iOS version**: 12.1.4

**Signal version:** 2.37.1

**Comment by u32i64** [comment]
It appears that this is also already reported in the community forum: [Tone: none does not work](https://community.signalusers.org/t/tone-none-does-not-work/6728).

**Comment by michaelkirk-signal** [comment]
This should be fixed in the latest release, 2.37.2 available in the app store now.
