### ISSUE TITLE
When peer puts me on their speaker I hear my voice echo loud and clear

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#4157]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when ios testflight calls with android one 9 play store, both with speaker on, ios hears his own voice

peer android device: xiaomi mi a2 lite. no debug log available

### Steps to reproduce
- install testflight
- peer installs latest play store
- I call peer
- turn on speaker
- peers turns on speaker

**Actual result:** I hear my voice

**Expected result:** I don't hear my voice at all

### Device info

**Device**: iPhone SE

**iOS version**: 10.2

**Signal version:** latest testflight at the time of writing

### Link to debug log

debug log:

**Comment by mailinglists35** [comment]
https://debuglogs.org/fb9c519ca85d29a0b2bc71d909be103a8cf45a0284113a5f1118017c761a3160.zip1

**Comment by mailinglists35** [comment]
android never complained about hearing their voice (this is reproductible always for ios)

 I haven't confirmed yet if this occurs on their end simmetrically, but I assume that it does not happen to them or else they would have complained

**Comment by michaelkirk-signal** [comment]
Sadly, echo cancellation is a feature that affects the *other* party. So if _you_ are hearing and echo, it's because of a problem on the _other_ client. 

Could you follow up with the Signal-Android folks?

https://github.com/signalapp/Signal-Android/issues/new
