### ISSUE TITLE
Many spurious "Error handling incoming message" messages

### ISSUE THREAD

**Issue by dgobaud** [signalapp/Signal-iOS#4160]
### Bug description
OSX just auto-upgraded to v1.23.0 and had 154 of these "Error handling incoming message" messages

![image](https://user-images.githubusercontent.com/240811/54782596-83f0de80-4bdc-11e9-8aeb-90ed304d9aba.png)

### Steps to reproduce
- auto-upgrade to v1.23.0

**Actual result:**

![image](https://user-images.githubusercontent.com/240811/54782596-83f0de80-4bdc-11e9-8aeb-90ed304d9aba.png)

**Expected result:**

Don't have the error messages

### Screenshots

![image](https://user-images.githubusercontent.com/240811/54782596-83f0de80-4bdc-11e9-8aeb-90ed304d9aba.png)

### Device info

**OSX**: 10.14.3 (18D109)

### Link to debug log

https://debuglogs.org/83767eb8a252aac930b5e2e12e19ac030f97db2e21501707ad33861885d3c508

**Comment by michaelkirk-signal** [comment]
This looks like a desktop log? If you're still seeing this could you follow up with https://github.com/signalapp/Signal-Desktop/issues ?
