### ISSUE TITLE
Registered user appears unregistered to other Signal users but can still send Signal messages

### ISSUE THREAD

**Issue by lardinator007** [signalapp/Signal-iOS#4161]
- [X] I have searched open and closed issues for duplicates
This is probably the same issue as https://github.com/signalapp/Signal-Android/issues/5859, but since the issue is closed I have to start a new one(?). 

- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Contact that I have had conversations with is suddenly marked as "unregistered user". The contact can send messages to me, but I am unable to answer. When I try to find the contact by searching for the telephone number the user does not exist.

### 

### Steps to reproduce
Unfortunately I don't know how to reproduce the bug.

#### My device
**Device**: iPhone SE
**iOS version**: 12.1.4
**Signal version:** 2.37.2.0

#### Contacts device
**Device**: Samsung
**Android version**: Unknown
**Signal version:** Unknow

**Comment by diver-down** [comment]
Same on my end. Am suddenly **unable to message most friends.** 

Specific error message:
`Unregistered user:  [name - redacted]`

When attempting to send them a message:
`SEND FAILED` (red bang)

**Comment by diver-down** [comment]
Update from the desktop.... sending from the Desktop client, no fix.

Reset Secure session, no fix.

Screenshot attached.

<img width="382" alt="Screen Shot 2019-03-24 at 17 53 13" src="https://user-images.githubusercontent.com/35608185/54886383-d5f46700-4e5d-11e9-9a4c-9690e84cbee4.png">

**Comment by fmerhout** [comment]
Same issue here.

**Comment by lardinator007** [comment]
Yes, worked for me and me as well.

**Comment by michaelkirk-signal** [comment]
This typically indicates a problem with the client of the user who you are unable to send *to*. 

In this case it sounds like it was an Android device, if they have issues again, could you encourage them to follow up with the Signal-Android folks?

https://github.com/signalapp/Signal-Android/issues

**Comment by Davidthegreat87** [comment]
I have same issue, was having a conversation with my contact then all of a sudden the contact appeared as not a registered signal user
