### ISSUE TITLE
Two text fields in image approval view when came from iOS screenshot markup

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4164]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Two text fields appear overlapping each other in image approval view when user came from iOS screenshot markup.

### Steps to reproduce
- take a screenshot.
- open the iOS built-in screenshot markup (via the thumbnail of the screenshot).
- tap share icon.
- choose Signal.
- choose recipient.
- start typing some message text, you may already notice the second (gray) cursor at the beginning.
- tap Done on keyboard.
- notice two different fields again, now the y position is different.
- tap to enter text again, erase your text, observe it stays in full in the background until you erase everything (gray cursor will still stay in place), but as you start typing the gray text will reappear.
- continue playing with two different fields...

**Actual result:** Two overlapping text fields.
**Expected result:** One message field.

### Screenshots
See https://github.com/signalapp/Signal-iOS/issues/4164#issuecomment-501170316.

### Device info
**Device**: iPhone 6 Plus
**iOS version**: `12.2`
**Signal version:** `2.38.0.9`, worked on `2.37.x.y` at least as well.

**Comment by u32i64** [comment]
Still reproducible on iOS `12.3.1`, Signal `2.40.0.21`.

While a screenshot does not capture this, screen recording does, so here are some frames from the recording:

• | • | • | •
---|---|---|---
[![1]][1] | [![2]][2] | [![3]][3] | [![4]][4]


[1]: https://user-images.githubusercontent.com/19972511/59334542-63c84b80-8d03-11e9-8de1-ffa2b389f162.JPEG
[2]: https://user-images.githubusercontent.com/19972511/59334611-8d817280-8d03-11e9-8e78-bee9ffd48a76.JPEG
[3]: https://user-images.githubusercontent.com/19972511/59334713-c0c40180-8d03-11e9-95cb-074ff7436e78.JPEG
[4]: https://user-images.githubusercontent.com/19972511/59334732-c9b4d300-8d03-11e9-9021-74e7059b885c.JPEG

**Comment by denver-s** [comment]
I believe this has been fixed as it has never happened again to me since version 3.

**Comment by u32i64** [comment]
Yeah, can't reproduce this anymore on:

**Device:** iPhone SE
**iOS version:** 13.4 Public Beta 4
**Signal version:** 3.6.1.4
