### ISSUE TITLE
Using signal on iOS 12.2 iphone XS causes Private Internet Access VPN app to disconnect

### ISSUE THREAD

**Issue by zygoteplanets** [signalapp/Signal-iOS#4165]
As the title says. This does not happen automatically as soon as I open signal but when I make a call or sometimes when I am looking through pictures in conversation windows. This did not happen in iOS 12.1.4.

**Comment by michaelkirk-signal** [comment]
Signal isn't allowed to disable your VPN app. I recommend you follow up with your VPN provider to see what the issue is.
