### ISSUE TITLE
iOS 12.2 iphone XS lock button ends call while on speaker

### ISSUE THREAD

**Issue by zygoteplanets** [signalapp/Signal-iOS#4167]
iOS 12.2 iphone XS lock button ends call while on speaker. This should only happen if it is a normal call.

**Comment by michaelkirk-signal** [comment]
I believe this is standard iOS behavior, not something we can control.

**Comment by zygoteplanets** [comment]
No. The lock button is supposed to only close non-speaker phone calls. Curiously though when somebody calls me on signal and I use loud speaker, I can press the lock button once to turn off the screen, but the second time shuts down the call.

**Comment by michaelkirk-signal** [comment]
I understand the way Signal behaves isn’t how you would prefer it to work.

Can you verify - does an unencrypted non-signal call behave differently in this regard?

**Comment by zygoteplanets** [comment]
Please don't misunderstand me, I think Signal is a great app, and I understand that it is a work in progress. The usual behavior of an iPhone loud speaker call (verified in a normal phone call), is that lock button simply turns off the screen.  In a normal non-speaker phone phone call the lock button ends the call. With Signal it depends on whether you made the call or if you received it. If you made the call and you are using loud speaker, pressing the lock button ends the call. There is no other direct way of turning the screen off with the iPhone other than using the lock button. When receiving a call on Signal a peculiar thing happens. if you answer and press loud speaker, it momentarily flashes and enables it but then the loud speaker button turns off again. The loud speaker is still on though. You can use the lock button to turn the screen button ONCE only in this scenario. Pressing it again ends the call. I don't know if it was always like this or this a recent glitch as I am recent Signal user.

Thank you for your great app.

**Comment by michaelkirk-signal** [comment]
Thanks for the follow up - sounds like we're doing something different from what native calling does, so I'm going to re-open. 

>  When receiving a call on Signal a peculiar thing happens. if you answer and press loud speaker, it momentarily flashes and enables it but then the loud speaker button turns off again.

To be clear, Signal doesn't have any application logic that says "when the user locks the phone end the call". It's all operating system behavior. I suspect that the root cause may be related to this quote - that something we're doing causes the system not to realize speakerphone is enabled.

**Comment by michaelkirk-signal** [comment]
I believe this may be the same root cause as: https://github.com/signalapp/Signal-iOS/issues/4112

**Comment by Fulp-Piction** [comment]
I am having the same issue, however it is not exclusive to the phone being on speaker as the bug occurs even when speaker is not activated. This wasn't happening to me until a few weeks ago though, prior to that my phone would just deactivate the screen but not the call, therefore I don't believe it is standard iOS behavior.

Device info:
Device: iPhone 6
iOS version: 12.4
Signal version: 2.41.0.21

App state
Screen Lock Timeout 15 minutes, Screen Security enabled

Link to debug log:
https://debuglogs.org/40e468fef6d75586cd523818c62061da4d8187d4c97507191e89a8c3e04c23bb.zip

**Comment by tcullum-gpsw** [comment]
2.44.0 does this for me on the newly updated 13.1.2 on iPhone 8 Plus.

This problem occurs when the phone is in a call with a bluetooth device connected for me, so there is no requirement of being explicitly on Speakerphone. This DOES NOT occur on a standard iPhone phone call. The idea here is to be able to shut the screen off and save battery life during the duration of the call.

**Comment by 211217613** [comment]
I'm pretty sure this is an iOS thing and you need to go into accessibility settings and toggle something with calls. I had the same problem and fixed it through accessibility settings.

**Comment by jkscx** [comment]
Can confirm bug on iOS 13.3.1 iPhone 6s.

While on speakerphone, pressing the lock button ends the call. While the normal behaviour is to just lock the screen and continue the call (native phone app, WhatsApp, ...).

**Comment by zoltan-kollar** [comment]
I have the same problem whether I am on bluetooth headset or just simply on speaker.

Signal v3.8.3.5
iOS 13.4.1
iPhone 8

**Comment by simrun** [comment]
The key consequence of this bug is that Signal speakerphone calls drain your battery :(

**Comment by simrun** [comment]
Also, this is very disconcerting for a new user – the design pattern of pressing power to turn off the screen is pretty engrained. I accidentally hung up on my friends quite a few times before I unlearned that. Not great when I'm trying to convince them to switch!

**Comment by adamdecroy** [comment]
Same problem:

Signal 5.1.0.31
iOS 14.3
iPhone 12 Pro Max

**Comment by simrun** [comment]
A workaround is to press the home button first (to go back to the Home Screen), then press the power button to turn the screen off.

**Comment by sqwwqw5** [comment]
How can this issue still not be addressed? Unbelievable!

**Comment by sqwwqw5** [comment]
> A workaround is to press the home button first (to go back to the Home Screen), then press the power button to turn the screen off.

Doesn't work on ios13.3
No matter where I turn off the screen, the call still ends.
I really want my girlfriend to switch to signal, but this is mind bugging.

**Comment by sqwwqw5** [comment]
I do believe this issue is callkit related.
At least give the user an option to turn off the callkit.

**Comment by altosaar** [comment]
Having the same problem! Have had it for several months on several iOS devices :(

**Comment by sqwwqw5** [comment]
@michaelkirk-signal @charlesmchen-signal
How can no one talks about this bug, you literally can't lock the screen while on speaker otherwise the call hangs up, at least give the option to disable callkit. Telegram also has this bug yet it provides an option to disable callkit. Also, The bug is not unfixable, Whatsapp and  Line don't have this issue.

The reason I suggest the bug has to do with callkit is that for Chinese numbers, callkit is disabled by default, guess what? They don't have this issue, they can lock their screen freely while on call.

I believe this could be a major turn off for users who want to switch to Signal, I hope we will see a fix soon, thanks for all the hard works!

**Comment by felixvd** [comment]
Have hung up and been hung up on accidentally lots of times, very confusing.

**Comment by altosaar** [comment]
Same.

**Comment by balintmaci** [comment]
This issue is still present, latest Signal iOS, latest iOS. The system doesn't always seem to recognize that signal is in loudspeaker mode and ends the call on pressing the power button. Very frustrating when trying to turn the screen off and accidentally hanging up. It is definitely not how it is supposed to work.

**Comment by altosaar** [comment]
This is still an issue! Unbelievable.

**Comment by readstead** [comment]
This needs to be reopened. This is the worst thing about this app and makes me want to smash my phone in rage every time I use it. I can't believe it's been YEARS and there's nothing.

**Comment by readstead** [comment]
@michaelkirk-signal Please reopen this issue, the bot was overzealous.

**Comment by simrun** [comment]
This issue needs to remain open, it's a major bug and has not been fixed.

cc @michaelkirk-signal

**Comment by simrun** [comment]
Can we get some movement on this @Meredith-Signal ?

**Comment by Winterherr** [comment]
Still happening on iOs 16 on my Iphone 8
