### ISSUE TITLE
Send failures - Censorship Cirumvention enabled (Cloudfront error

### ISSUE THREAD

**Issue by 3WfMeCuUqzgXBh** [signalapp/Signal-iOS#4168]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages fail to send when connected from certain locations. In this instance I am connected to a digital ocean droplet in Singapore. This first was intermittent and now seems to be almost permanent.

I sporadically receive messages but I cannot send. 

Client reports: Request Failed: Client Error (421)

Debug logs show an issue connecting to the cloudfront instance:

} }}}, NSLocalizedDescription=Request failed: client error (421), com.alamofire.serialization.response.error.data=<3c68746d 6c3e0d0a 3c686561 643e3c74 69746c65 3e343231 204d6973 64697265 63746564 20526571 75657374 3c2f7469 746c653e 3c2f6865 61643e0d 0a3c626f 64792062 67636f6c 6f723d22 77686974 65223e0d 0a3c6365 6e746572 3e3c6831 3e343231 204d6973 64697265 63746564 20526571 75657374 3c2f6831 3e3c2f63 656e7465 723e0d0a 3c68723e 3c63656e 7465723e 436c6f75 6446726f 6e743c2f 63656e74 65723e0d 0a3c2f62 6f64793e 0d0a3c2f 68746d6c 3e0d0a>}
2019/04/02 19:40:57:587  [OWSSignalService.m:202 -[OWSSignalService CDNSessionManager]]: using reflector CDNSessionManager via: https://cms.souqcdn.com
2019/04/02 19:40:57:588  [OWSSignalService.m:202 -[OWSSignalService CDNSessionManager]]: using reflector CDNSessionManager via: https://cms.souqcdn.com
2019/04/02 19:40:57:591  [OWSSignalService.m:202 -[OWSSignalService CDNSessionManager]]: using reflector CDNSessionManager via: https://cms.souqcdn.com
2019/04/02 19:40:57:592  [OWSSignalService.m:202 -[OWSSignalService CDNSessionManager]]: using reflector CDNSessionManager via: https://cms.souqcdn.com
2019/04/02 19:40:58:134  [ConversationViewController.m:3397 -[ConversationViewController markVisibleMessagesAsRead]]: Not marking messages as read; another view is pushed.
2019/04/02 19:40:58:836  [OWSProfileManager.m:1206 -[OWSProfileManager downloadAvatarForUserProfile:]_block_invoke_3]: avatar download for [ REDACTED_PHONE_NUMBER:xxx439 ] failed with error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={NSLocalizedDescription=Request failed: forbidden (403), NSErrorFailingURLKey=https://cms.souqcdn.com/profiles/hW8nc3q-2SvZQXTmDOWkKw, com.alamofire.serialization.response.error.data=<>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x2804d69c0> { URL: https://cms.souqcdn.com/profiles/hW8nc3q-2SvZQXTmDOWkKw } { Status Code: 403, Headers {
    "Content-Type" =     (
        "application/xml"
    );
    Date =     (
        "Tue, 02 Apr 2019 15:40:57 GMT"
    );
    Server =     (
        AmazonS3
    );
    Via =     (
        "1.1 d8bc31f1690f46d533b518410accf19f.cloudfront.net (CloudFront)"
    );
    "x-amz-cf-id" =     (
        "YzbBmd91wmR4rXp2B19h2b1-s3R2yEiwclVMXiYImnzzgz2BEzdNsg=="
    );
    "x-cache" =     (
        "Error from cloudfront"
    );
} }}
2019/04/02 19:40:58:836  [OWSProfileManager.m:1206 -[OWSProfileManager downloadAvatarForUserProfile:]_block_invoke_3]: avatar download for [ REDACTED_PHONE_NUMBER:xxx863 ] failed with error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={NSLocalizedDescription=Request failed: forbidden (403), NSErrorFailingURLKey=https://cms.souqcdn.com/profiles/EpRL0pHq8qDs2R66KzFTgA, com.alamofire.serialization.response.error.data=<>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x2804d7c80> { URL: https://cms.souqcdn.com/profiles/EpRL0pHq8qDs2R66KzFTgA } { Status Code: 403, Headers {
    "Content-Type" =     (
        "application/xml"
    );
    Date =     (
        "Tue, 02 Apr 2019 15:40:58 GMT"
    );
    Server =     (
        AmazonS3
    );
    Via =     (
        "1.1 84a8283bcf12d6659a335b8d00e9c15b.cloudfront.net (CloudFront)"
    );
    "x-amz-cf-id" =     (
        "mHXXa_gLA53QYx25ToBae-3THz40agTEwetaE4gBUJhkW4MuFyt1ZQ=="
    );
    "x-cache" =     (
        "Error from cloudfront"
    );
} }}

### Steps to reproduce
- I have connected to various networks and have discovered this issue from two locations.
- Just trying to send a message yields the same error.

### Device info

**Device**: iPhone 7

**iOS version**: 12.1.4

**Signal version:** 2.37.2.0

### Link to debug log

https://debuglogs.org/b3b17554144bd1e0643de5cc6f7a3b98018b756972fc5663d4eac6342cf1ad32.zip

**Comment by 3WfMeCuUqzgXBh** [comment]
Did a little bit of digging and I think this may be a cert issue.

The certificate being presented by cms.souqcdn.com is signed by Amazon Root CA 1

The signal app trusts the cert Starfield Services Root Certificate Authority - G2 

SFSRootCAG2 - cms.souqcdn.com
NSArray<NSString *> *certNames = @[ @"SFSRootCAG2" ];

I assume this changed recently?

Reference:

https://www.amazontrust.com/repository/

**Comment by michaelkirk-signal** [comment]
@3WfMeCuUqzgXBh - If you were getting a "Request failed: forbidden (403)" you've established an HTTP connection. How then could it be a cert error? 

What are you seeing that makes you think this is a cert error?

**Comment by 3WfMeCuUqzgXBh** [comment]
@michaelkirk-signal - Good point I see what you mean there. I looked at the certificate pinning policy in the code mainly because there was an issue like this about a year back when google changes the certs and the signal app was not trusting the new CA.

Unless I misinterpreted the code it is trusting the CA SFSRootCAG2 (Starfield Services Root Certificate Authority - G2) but when I browse to cms.souqcdn.com I am presented with a certificate signed by Amazon Root CA 1.

I am back in the UAE now and confirm signal isn't working at all.

I would like to take this opportunity to make a feature request that users in censored countries are allowed to disable censorship circumvention if/when required. I know this was not a popular option when raised previously but when issues occur we all essentially go offline. I have the means to get my traffic outside of the country but because I cannot disable this feature I am offline.

Toggling this feature obviously should warn the user about what they are about to do so it's 100% clear that if disabled is may stop the application from functioning.

**Comment by wakkum** [comment]
Chiming in to confirm same error in Qatar, where censorship prevention is also enabled by default. Signal on local number does not work, but it does for other number which does not have censorship prevention enabled.

**Comment by michaelkirk-signal** [comment]
Could you and anyone else affected by this please contact support@signal.org and reference this GH issue?

We have a potential solution we're hoping to have users test out.

**Comment by michaelkirk-signal** [comment]
This should be working again on the latest AppStore release: 2.38.1

**Comment by denver-s** [comment]
@michaelkirk-signal I've just taken a look at my debug log and see a lot of these errors.

```
2019/04/16 18:50:23:469  [OWSProfileManager.m:1206 -[OWSProfileManager downloadAvatarForUserProfile:]_block_invoke_3]: avatar download for [ REDACTED_PHONE_NUMBER:xxx727 ] failed with error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={NSLocalizedDescription=Request failed: forbidden (403), NSErrorFailingURLKey=https://cdn.signal.org/profiles/zFkqVbftoAuDrEIIdX_s5w, com.alamofire.serialization.response.error.data=<>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x28074e620> { URL: https://cdn.signal.org/profiles/zFkqVbftoAuDrEIIdX_s5w } { Status Code: 403, Headers {
    "Content-Type" =     (
        "application/xml"
    );
    Date =     (
        "Tue, 16 Apr 2019 16:50:23 GMT"
    );
    Server =     (
        AmazonS3
    );
    Via =     (
        "1.1 fba39238fd8fc98a9491893a18564594.cloudfront.net (CloudFront)"
    );
    "x-amz-cf-id" =     (
        "QbtucCptXrJ9pfCR9M-ovHTEQ1hK88Ni5jvQm826UDIIw0ahSx-3eQ=="
    );
    "x-cache" =     (
        "Error from cloudfront"
    );
} }}
```

I am not using censorship circumvention (I'm in Italy).

**Comment by michaelkirk-signal** [comment]
@denver-s - the contents of that log don't necessarily mean anything is incorrect. In some circumstances a 403 is the expected response code.

If you are actually experiencing app behavior that doesn't seem correct, please follow up with an issue.
