### ISSUE TITLE
During videocalls device brightness changes 

### ISSUE THREAD

**Issue by swbugs** [signalapp/Signal-iOS#4169]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by swbugs** [comment]
During Signal video calls the device brightness changes from 100% down to about 50%, after call ends the device brightness changes back to maximum brightness.

**Comment by ethylmorphine** [comment]
I believe, it has something to do with kernel overheating prevention, so it’s not an issue. Videocalls makes an iPhone act like a heater.

**Comment by swbugs** [comment]
Okay, thanks for replying.
