### ISSUE TITLE
Registration using received code freezes on latest iOS on iphone-6S

### ISSUE THREAD

**Issue by githotto** [signalapp/Signal-iOS#4170]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm trying to register the latest Signal version on my iPhone-6S / iOS-12.1.4 and already tried 3 received 'verification' codes but still nothing happens.
Also check that receive-notifications is enabled and background process, but no effect yet?!

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michaelkirk-signal** [comment]
Can you clarify, is this what you're seeing?

You receive the SMS verification codes
you enter the SMS verification code
You see a progress spinner
But the app never progresses to the next screen

Is that right?

Usually if it's actually a freeze, the app will crash after a bit . (~30s). Does the app eventually crash? Or do you just see the spinner forever?

**Comment by michaelkirk-signal** [comment]
We resolved a potential hang during registration with the latest beta.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

If you're able to reproduce, please re-open.
