### ISSUE TITLE
Share Sheet > Image editor: No keyboard and message field in landscape initially

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4171]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No keyboard and message field in landscape image editor (when opened from Share Sheet).

**note:** opening the same view from Signal itself by using *Photo Gallery* attachment type works normally and produces the expected result.

### Steps to reproduce
- turn device into landscape orientation.
- open a share sheet, e.g. using a photo or from screenshot editing screen.
- choose Signal.
- choose recipient.

##### Actual result
- **no** message field.
- virtual keyboard does **not** appear when using text tool.

**note:** turning phone into any different orientation fixes the issue. However, it is not possible to change orientation when user came from iOS screenshot editor (markup).

##### Expected result
- message field.
- virtual keyboard does appear when using text tool.

### Device info
**Device**: iPhone 6 Plus
**iOS version**: `12.3` Public Beta (build `16F5117h`)
**Signal version:** `2.38.1.2`

### Debug log
Will provide if needed.

**Comment by tzs1** [comment]
Similiar issue explained here: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-2-38-release/6980/15

**Comment by denver-s** [comment]
Improvement has been made, but the text area is not full width.

![B1674CD4-A26C-4F8F-B687-3E0CACC44186](https://user-images.githubusercontent.com/31325316/71040995-38963d00-2128-11ea-9ec6-42d308c5808a.png)

**Comment by u32i64** [comment]
This is still an issue. On my device I don't even see the partial-width text area before changing orientation, which isn't possible e.g. when:

> user came from iOS screenshot editor (markup).

**Device:** iPhone SE
**iOS version:** 13.4 Public Beta 4
**Signal version:** 3.6.1.4

**Comment by 211217613** [comment]
I’m having the same problem on iPad in landscape mode. I don’t know how to paste the picture from my iPad though.

**Comment by u32i64** [comment]
This appears to be fixed by https://github.com/signalapp/Signal-iOS/issues/4435#issuecomment-759273705.
