### ISSUE TITLE
Received Image is not shown in chat and cannot be opened. 

### ISSUE THREAD

**Issue by AndHell** [signalapp/Signal-iOS#4173]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Image send from Android to iOS is not shown in the chat an can't be opened.

### Steps to reproduce
- Send the attached image from Android to iOS

**Actual result:** Image send from Android to iOS is not shown in the chat an can't be opened. 

**Expected result:** Image is shown in the empty message bubble. 

### Screenshots

![signal-2019-04-09-125939](https://user-images.githubusercontent.com/11991279/55948973-241caf00-5c41-11e9-859b-16a357c846df.png)

Send Image:

![cf68fa1deadabd65](https://user-images.githubusercontent.com/11991279/55948976-25e67280-5c41-11e9-8cf4-be988b22c8b5.png)

### Device info

Sender: 
**Device**:  Nokia 6.1 
**Android version**: Android 9 (Mach Security patch)

**Signal version:** 4.37.2

Receiver:
**Device**:  iPhone

Sadly I don't know the model, or the Signal version. But the issue appeared with two different contacts, that are both on iPhone.

**Comment by tzs1** [comment]
It would be helpful to the devs if you could provide a debug log (Signal -> Tap on your profile picture -> Advanced -> Send debug log).

**Comment by AndHell** [comment]
I don't own a iPhone, and have no control over the two iPhones where this issue happened. 
So, sadly, I cannot try do reproduce this issue and can provide no debug logs.

However, it should be possible to reproduce it with the attached image.

**Comment by denver-s** [comment]
I successfully replicated the bug.

First, I tried sending the image from Desktop (v1.24.0-beta.3) to myself (2.38.1.2) using a one-member group that I use as a quick note, auto-deleting chat.

The image is shown correctly.

Then, I opened [the image you provided](https://user-images.githubusercontent.com/11991279/55948976-25e67280-5c41-11e9-8cf4-be988b22c8b5.png) with my iPhone, pressed on it and selected "copy image". Went back to Signal iOS and pasted the image. It didn't show a preview but just the filename (as for other file/documents).

Screenshot:
![4C6E44EB-89FA-474F-8DB6-3F5E0A4B6DD4](https://user-images.githubusercontent.com/31325316/56222675-bcb19580-606c-11e9-8fff-c021072df40f.jpg)

Debug log:
https://debuglogs.org/20e01c4424cc8b9ffc18d1635628948f0407bdcd91db324fef207a2b3e05a179.zip

As a side note, the problematic image is showing correctly on Signal Desktop.

**Comment by nathanielnebel** [comment]
I get this too when receiving any images on my IOS device usually from android senders.

 https://debuglogs.org/71be14b10d73ba19d42e39430f4034ba87e2e27369f399316502b23ed7dda0cf.zip

**Comment by LedRevolver** [comment]
I’m having this issue on iOS as well: https://debuglogs.org/d02629a2852fec5dccc5e2c1743cac59adc8be6ae1d30323a72e9c9ccbe43f3f.zip

**Comment by starze** [comment]
My iOS friends are having the same issue. 
We tried reproducing and it seems to depend on the picture resolution. 
When my Android friend is sending a *.png picture with 1080x2160 the iOS APP doesn't display the image but my android is displaying it properly. When I download and re-send this same picture it doesn't show up on their iOS either. But if I share a screenshot or picture with the resolution 1080x1920 then it does show up in their iOS correctly.

**Comment by denver-s** [comment]
I did the test again using the same image and the bug has not occurred anymore.

**Comment by AndHell** [comment]
> I did the test again using the same image and the bug has not occurred anymore.

Also just checked it again; no issue this time with the same image.
The image was sent from Android 9 (v4.50.5) to iOS @ v2.45.2.0.

**Comment by michaelkirk-signal** [comment]
We made some changes a few releases back that should have fixed this for most users and images. Thanks for following up.
