### ISSUE TITLE
Call banner blocks Attachment Approval UI

### ISSUE THREAD

**Issue by kpcyrd** [signalapp/Signal-iOS#4177]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I noticed with an active signal call in the background the signal navigation UI is limited because some buttons are blocked by the active call indicator. In one case you are not able to confirm OR cancel, the only way to return to signal is hanging up the call or glitching the active call indicator to access the cancel button below the call indicator.

### Steps to reproduce
- Start a signal voice call
- Use the back button to return to signal with the call in the background
- Enter the image send UI, try to add multiple images and confirm, tap into the image to enter the "add text to image" mode, you can't use the confirm or cancel buttons if you enter that mode by accident

**Actual result:** Important elements of the signal UI are blocked by the active call indicator, especially the `cancel` and `back` buttons.

**Expected result:** The signal UI can be used without limitations with an active signal call in the background.

### Screenshots

I don't have any actual screenshots, but I found this picture of the behavior I'm referring to. This should be easy to reproduce, let me know if you have any issues.

![](https://i.stack.imgur.com/njNsS.png)

### Device info

**Device**: iPhone Xs

**iOS version**: 12.2

**Signal version:** 2.38.1.2

**Comment by michaelkirk-signal** [comment]
I'm a little confused by your description, but based on your screenshot, it looks like *other* apps are obscured by the system call banner.

What is shown in that screenshot is not UI drawn by Signal - it's UI that the system renders while you're on any kind of call from another app. We have no control over it.

One clarifying note: we do *mimic* the system UI call banner while you're on a Signal call __and still in the Signal app__. 

So if you start a call with Alice, then navigate back to your conversation list while remaining on the call with Alice, you'll see a Call Banner that is intended to look like the system call banner.

But to re-iterate, once you leave the Signal App, any UI glitches you see are not something we can control. So the issue shown in your screenshot is either an OS bug or a bug with whatever app is being obscured. We couldn't change that UI if we wanted to.

**Comment by michaelkirk-signal** [comment]
Whoops - I missed the caption to your screenshot which explains that the screenshot is not of your actual issue. re-opening.

**Comment by michaelkirk-signal** [comment]
This issue seems to specifically affect the Attachment Approval UI, so I've updated the title for clarity. If you know of other screens affected by this issue, please let me know.

Thanks for reporting!

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
