### ISSUE TITLE
App crashes when sending 0 media

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4180]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes when user is able to "send" 0 media from the media selection process.

### Steps to reproduce
- open a chat
- select "send media from library"
- switch to camera (bottom left button)
- take a photo
- go back to media library
- select another media
- click on the bottom right button to go to the "send" view
- remove the photo taken before
- go back to media library
- deselect the previously selected media
- bottom right icon now says "0" but still clickable
- click it
- the "send" view shows a black view
- click "send"
- app crashes

**Actual result:** it is possible to choose no media to send.

**Expected result:** it is not allowed to have less than 1 media to send.

### Screenshots

![immagine](https://user-images.githubusercontent.com/31325316/56684323-cf147a80-66cf-11e9-9272-7f4e53ddbbde.png)

### Device info
**Device**: iPhone 8 Plus

**iOS version**: 12.2

**Signal version:** 2.39.0.4

### Link to debug log
https://debuglogs.org/dc74c7067c2af4421400272b72064f53ec953c82b467e81a80c49c439f710c6c.zip

**Comment by michaelkirk-signal** [comment]
Thanks for reporting! This should be fixed in the upcoming 2.36.0.6 beta.


For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
