### ISSUE TITLE
delayed sending of Read receipts to sender

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-iOS#4182]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Im using signal4android [xxx332], my contact signal4ios [xxx999].
I often receive the read confirmations from my contact late or only after a new interaction.
The case in the debug log of my contact [DL xxx999] was:

I sent a message to my contact (2019/04/21 11:10:28 time of my mobile phone)
[DL xxx999] 2019/04/21 11:10:36:167 Successfully sent 1 Delivery receipts to sender

The message was read at 21:15
[DL xxx999] 2019/04/21 21:15:38:992 Marking 1 messages as read locally
[DL xxx999] 2019/04/21 21:15:39:066 attempt to send the read receipt to my
[DL xxx999] 2019/04/21 21:15:44:782 failing to send the read receipt due to network failure
[DL xxx999] 2019/04/21 21:15:44:839 application is terminated

I sent a the next message (+image) to my contact on 2019/04/23 16:42
[DL xxx999] 2019/04/23 16:42:21:644 Successfully sent 1 Read receipts to sender (for the first message)
[DL xxx999] 2019/04/23 16:42:25:329 Successfully sent 1 Delivery receipts to sender (for the second message)

**Expected result:** 

- it is more often tried to send the message
- the application is not terminated until all messages (Read receipts) have been sent

Annotation:
Maybe this is related also to https://github.com/signalapp/Signal-iOS/issues/4179

### Device info

**Device**: iPhone 9,3

**iOS version**: 12.1.4

**Signal version:** 2.38.1 (2_38_1_2)

### Link to debug log

https://debuglogs.org/3128bdc64f786289b2c74c75a038ff40f6fe881ce25026f42f82731280d052cf.zip

**Comment by denver-s** [comment]
I faced this issue months ago but it seems now to be fixed.
