### ISSUE TITLE
Wrong order of media when mixing camera and gallery media

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4183]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you select two media from the library and switch to camera and take a photo, the latter will be at second position instead of third.

### Steps to reproduce
- open chat
- select "media library"
- select a picture (1)
- go back and select another one (2)
- switch to camera
- take a photo (3)
- go to the "compose media message" view

**Actual result:** media order is not correct (1, 3, 2).

**Expected result:** media order is 1, 2, 3.

### Screenshots

![immagine](https://user-images.githubusercontent.com/31325316/56797713-97174f80-6815-11e9-9f45-a604e2023e5a.png)

### Device info
**Device**: iPhone 8 Plus

**iOS version**: 12.2

**Signal version:** 2.39.0.6

**Comment by michaelkirk-signal** [comment]
Thanks for reporting! This will be fixed in the 2.39.0.7 beta release.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
