### ISSUE TITLE
Group chat with re-verified users always opens to the verification message

### ISSUE THREAD

**Issue by philshem** [signalapp/Signal-iOS#4185]
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I open the group, either from a notification of a new chat in that group, or by opening Signal and clicking on that group, the app opens to the "Verify Safety Number" message, instead of first displaying the newest messages. I then need to click multiple times the blue arrows on the bottom right to descend to the new message(s).

### Steps to reproduce

+ Group chat with 1 week disappearing messages.

+ One group member changes phone, and then I have clicked Verify User.

**Actual result:** 

User verifies correctly, but this chat always shows this screen first.

**Expected result:** 

When I open the chat, I'm shown new messages, and not historical ones.

### Screenshots

Every time I go to the group, either from a notification or from the app chat list, it goes to this view, instead of directly to the new chat messages. 

![image](https://user-images.githubusercontent.com/4997607/57092502-d9f09000-6d0b-11e9-9dd7-3311515fc802.png)

### Device info

**Device**: iPhone SE 32 GB

**iOS version**: 12.2 (16E227)

**Signal version:** 2.38.1.2

### Link to debug log

[link](https://debuglogs.org/ad8ea1d4b12b5dd14993ee87fe8a1d78d770d5e9636e493ac1c8c9724c4fe301.zip)

**Comment by seveke3** [comment]
This is exactly what happens with my phone!!! Is it a bug that can be fixed??

**Comment by philshem** [comment]
Deleted app and signal and installed and created new account. And problem is not repeated.
