### ISSUE TITLE
Unable to find a specification for `SignalCoreKit` depended upon by `Curve25519Kit`

### ISSUE THREAD

**Issue by halocq** [signalapp/Signal-iOS#4187]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:2.30.2

### Link to debug log

When I use pod install, always hint this "Unable to find a specification for `SignalCoreKit` depended upon by `Curve25519Kit`", with other branch Curve25519Kit, also have another errors, how can I do this?

**Comment by michaelkirk-signal** [comment]
We don't use Github for developer support. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to ask for development support: https://community.signalusers.org/

But for a working example Podfile, take a look at the Podfile in the Signal-iOS repository.
