### ISSUE TITLE
Photo taken from front camera is squeezed in the media send composer

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4188]
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Photo taken from front camera is shown horizontally squeezed when sending it.

### Steps to reproduce
- take photo using front camera
- open chat and select "send media" option
- select the photo

**Actual result:** media composer shows the image squeezed.

**Expected result:** media resolution should not be changed.

### Screenshots
Actual photo:
![signal-2019-05-06-152041](https://user-images.githubusercontent.com/31325316/57228178-7ae49100-7013-11e9-91d7-28c54062fddb.jpeg)

Media composer:
![signal-2019-05-06-152041_1](https://user-images.githubusercontent.com/31325316/57228189-7e781800-7013-11e9-8800-e91892241522.jpeg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.2

**Signal version:** 2.39.0.9

**Comment by michaelkirk-signal** [comment]
I can't immediately reproduce this. 

Can you clarify - Did you take it from within Signal's in-app capture tool? Or did you take a photo in an external app like the Photos.app and then attach it from your media library?

Any other details you could offer?

**Comment by denver-s** [comment]
> did you take a photo in an external app like the Photos.app and then attach it from your media library?

Exactly.

**Comment by michaelkirk-signal** [comment]
> Edit 2: photo must be taken horizontally.

That's what I was missing. I can reproduce it now. Thanks for the details!

**Comment by charlesmchen-signal** [comment]
@denver-s This issue has been resolved. The fix will be in v2.39.  Thanks.
