### ISSUE TITLE
Pasted image from Signal Desktop is not displayed

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4189]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Send a large image ([this one](https://upload.wikimedia.org/wikipedia/commons/5/57/Panoramic_sunset_in_Conques_02.jpg) (6552x2317 pixels, 2.2 MB)) from Signal Desktop will not be displayed in Signal iOS.

### Steps to reproduce
- open Signal Desktop
- choose a large image and copy to clipboard
- paste into chat and send

**Actual result:** image is shown in Signal Desktop but not displayed in Signal iOS.

**Expected result:** image is displayed.

But if you:
- save the image on the PC
- attach image to message and send it

**Actual result:** image is shown in Signal Desktop and also in Signal iOS.

Also, if you send [this smaller version of the same image](https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Panoramic_sunset_in_Conques_02.jpg/1024px-Panoramic_sunset_in_Conques_02.jpg) (1024x362 pixels) by copying to clipboard, the image is displayed correctly. It seems related to the resolution of the copied image.

Additional cases:
* this one will not be displayed too: https://upload.wikimedia.org/wikipedia/commons/0/0c/Two-tailed_pasha_%28Charaxes_jasius_jasius%29_Greece.jpg [2952x1968]

### Screenshots
Signal Desktop 1.24.1

![immagine](https://user-images.githubusercontent.com/31325316/57323603-55847f80-7106-11e9-82b0-d62be82f1455.png)

Signal iOS

![immagine](https://user-images.githubusercontent.com/31325316/57323713-8b296880-7106-11e9-8def-cf8f0e4cf83c.png)

Signal iOS when the image is sent from local file, not from clipboard:

![immagine](https://user-images.githubusercontent.com/31325316/57324055-5e298580-7107-11e9-977a-37b415841393.png)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.2

**Signal version:** 2.39.0.9

### Link to debug log
https://debuglogs.org/db53b1101a6c82320e275f069a7779dba648f550ea2d5347e997b17833101b14.zip

**Comment by Cerberus0** [comment]
Possibly related: https://github.com/signalapp/Signal-iOS/issues/4173

**Comment by denver-s** [comment]
Tried again with Signal 3.0.2 and it works fine! Closing.
