### ISSUE TITLE
Window sometime has wrong frame - GUI glitch in Chat screen

### ISSUE THREAD

**Issue by editicalu** [signalapp/Signal-iOS#4192]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Sometimes when opening a chat on the iOS app, the layout doesn't behave as intended.

### Steps to reproduce

Unknown. The bug seems non-deterministic from the user's perspective.

**Actual result:** See screenshot 

**Expected result:** A screen with the normal behavior.

### Screenshots

<img width="320" alt="23883411-D771-4044-8B21-110E70615B3C" src="https://user-images.githubusercontent.com/22838908/57681925-fa381d00-7630-11e9-8093-b1d6cd68267e.PNG">

### Device info

**Device**: iPhone 5S

**iOS version**: 12.2

**Signal version:** 2.39.0.13

### Link to debug log

https://debuglogs.org/4788e08870465c9dc96682bbc9e50dcb7a27c050bff4dcf9512cc9d049816bfa.zip (taken after force-closing the app)

**Comment by riyapenn-signal** [comment]
@editicalu This should be resolved for you in Signal v2.40.1 or later. Let us know if you encounter this again.

If you are not already using Signal v2.40.1, you may want to set up automatic updates as suggested by the [Apple Support page](https://support.apple.com/en-us/HT202180) or the steps below:

1. From the iPhone home screen
2. Tap Settings > [your name] > iTunes & App Store.
4. Turn on Apps
