### ISSUE TITLE
Making links of IDN domain names

### ISSUE THREAD

**Issue by cyphunk** [signalapp/Signal-iOS#4194]
a message with https://üdomain.com will not show up clickable and hyper linked. Users are required instead to use Punycode of the name

**Comment by alvar-freude** [comment]
I have the same issue, only on iOS and not Desktop (MacOS). But on the Desktop client (MacOS), puny code of the name is not a link. Therefore it is not possible to use one type of link for both.

**Comment by alvar-freude** [comment]
See also:
https://github.com/signalapp/Signal-Desktop/pull/4038
https://github.com/signalapp/Signal-Desktop/issues/3966

One version of both should work on all systems.

**Comment by maurerle** [comment]
This issue is still relevant and should be reopened
