### ISSUE TITLE
Media Details Loading Issue

### ISSUE THREAD

**Issue by omaarr90** [signalapp/Signal-iOS#4197]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Media details does not load images correctly.

### Steps to reproduce
- open any conversation
- send around 50 images
- click one image roughly in the middle
- click on all media

**Actual result:** Media loaded are incorrect and duplicate

**Expected result:** Signal should load 100 media, 50 before the clicked image and 50 after it.

### Screenshots
If you need it I will provide it.

### Device info
**Device**: iDevice X

**iOS version**: 12.3

**Signal version:** 2.39

**Actual Code Causing Issue**:

I believe the following snippet is the root cause for this issue.

In Class MediaGalleryViewController.swift:916

```swift
                    let nsRange: NSRange = NSRange(location: unfetchedSet.min()!, length: unfetchedSet.count)
```

the unfetchedSet already has some removed item possibly in the middle because of the initial loading when clicking on an image inside a conversation. 

so using .min and .count to get the range is incorrect in this case. since this will reload some item which have been removed from the unfetchedSet and leave out some items which has not been loaded yet (possibly items with the larger indices)

Please Let me know if you need further information or if I can be of any help

**Comment by michaelkirk-signal** [comment]
Hi @omaarr90 - I'm having a hard time following your "steps to reproduce".

> send around 50 images

Is it necessary to *send* 50 new images during the session to induce this behavior? Or is it sufficient to have sent 50 images at some previous point?

> so using .min and .count to get the range is incorrect in this case. since this will reload some item which have been removed from the unfetchedSet 

I'm not sure I follow, since unfetchedSet is always contiguous, by construction, this should be fine.

**Comment by omaarr90** [comment]
No having sent 50 images should be fine. But you have to click in a photo that is somewhat in the middle.

So as to my understanding, user clicks in a photo, the app loads 10 images to enable scrolling. These indices go to the fetchedSet. 

User go on and click on all media. The App will try to load 100 more. (keep in mind we already fetched 10 in the middle) 

The calculates the set it needs to fetch the 100. then removes the 10 that are already fetched. (Those 10 are in the middle) 

Now going from min to count would give us the wrong range. we will get 90 objects. (not the last 10 but the 10 that we already fetched) 

I'm sorry, but this is the best I could describe it.

**Comment by omaarr90** [comment]
So suppose user clicks in the image in index 25. The app will load from 20 to 30. 

then user will click on all media. The app will try to load from 0-50. it will remove indices from 20-30. 

To this point the unfetchedSet is correct. 

No to calculate the range, you use min and count. 
We will be left with 40 indices to load. we will end up with a range from 0-40. 

So the last 10 will not be loaded. 20-30 will be loaded again. I hope this makes more sense.

**Comment by denver-s** [comment]
I think this bug has been fixed recently @omaarr90 .

**Comment by omaarr90** [comment]
I don’t see all media button any more. So I guess it’s not reproducible

**Comment by michaelkirk-signal** [comment]
> I don’t see all media button any more. So I guess it’s not reproducible

"All Media" is still accessible via Conversation Settings > All Media

**Comment by omaarr90** [comment]
Yes. I meant it’s not there when you open a photo from the conversation. Before there was a button too right that opens all media. 

I think it’s safe to close this issue.

**Comment by paskalem** [comment]
Thank you for all the help 
Respectfully yours 
PM
