### ISSUE TITLE
Other person sees messages as read before I read them

### ISSUE THREAD

**Issue by sirpeanut** [signalapp/Signal-iOS#4199]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I chat daily with a friend on Signal. We are both using Signal on both iOS and Desktop.

Lately, the following has happened multiple times:
* My friend sends me messages while I am asleep. My iPhone is sleeping (screen off, Signal not in the foreground) and my desktop is powered off.
* Some time later, my friend sees the two filled-in check marks, indicating that I have read the messages. But I haven't! I'm asleep! I haven't even *touched* any of my devices.

During the day, when we are actively chatting back and forth, it seems to work fine.

### Steps to reproduce
- send messages from Signal on iOS while the other person is not using the app

**Actual result:** Messages eventually appear as read (two filled-in checkmarks)

**Expected result:** Messages should not appear as read until they're actually read

### Device info
**Device**: iPhone XS Max
**iOS version**: 12.2
**Signal version:** 2.39.1.0

**Comment by michaelkirk-signal** [comment]
Clients should mark a message as Read when they receive a "Read Receipt". So if your friends client is incorrectly showing a message as read, it could be that either your friend's client marked a message as read without reason, or more likely, that one of *your* clients incorrectly sent a read receipt.

Can you provide a few things to help us track down what's going on?

1. The debug log from the device of your affected friend (ios or desktop, whichever one or both which incorrectly showed the message as read).

2. The debug logs from all of your devices, so we can figure out why it sent the read receipt.

3. The "sent" timestamp of one of the messages which was prematurely marked as read, so we know where exactly in the logs to look. The easiest way to find this is to go to Signal-Deasktop, and tap "..." > "More Info" on the affected message.

I've highlighted the part we need in this screenshot:
<img width="421" alt="Screen Shot 2019-05-24 at 5 32 28 PM" src="https://user-images.githubusercontent.com/36971200/58357721-edde6c00-7e49-11e9-834f-89502c0e1354.png">

**Comment by sirpeanut** [comment]
Thanks, will do! Let me reach out to my friend and see if we can reproduce this and I'll get back to you with the requested logs.

**Comment by michaelkirk-signal** [comment]
Just to be clear - if this happened within the last three days, you had debug logging enabled, and you still have the message in question, you should be able submit your existing logs.

Otherwise, let us know once you reproduce. Thanks for your help figuring this out.

**Comment by sirpeanut** [comment]
_Oh!_ I didn't realize debug logging was on by default. That's handy. :) Here you go! Thanks again for looking into this.

Debug log from device of affected friend:
https://debuglogs.org/318b5d659f997ba14a1a7b9f0daf583ee5eb65c1e29ff05f44f30adcf31d19db.zip

Debug logs from my devices:
iOS - https://debuglogs.org/0adb34472e390e6203a192faa97f5c88f938cd437a4cf98deaf7fdb54d79fa29.zip
Desktop - https://debuglogs.org/4270267446d3ec4dfd6466c8a75e3c4a88445d2cff6329c49ee151382ae44390

Timestamps of two messages that were prematurely marked as read (sent by my friend, received by me, seen as read by my friend):

Sent	Friday, May 24, 2019 6:46 AM (1558673211274)
Received	Friday, May 24, 2019 7:06 AM (1558674406240)

Sent	Friday, May 24, 2019 6:47 AM (1558673240068)
Received	Friday, May 24, 2019 7:06 AM (1558674407273)

**Comment by Henner** [comment]
I have the same problem.
If I have a chat to someone open and the app is not in focus / front or the iPhone is closed the sender gets a read notification immediately.
(same problem on the desktop App)
