### ISSUE TITLE
Signal client stuck on 'Optimizing Database', then crashes

### ISSUE THREAD

**Issue by srouter** [signalapp/Signal-iOS#4201]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening the Signal iOS client, it hangs on the "Optimizing Database. This can take a few minutes" message, before eventually crashing. This process takes around 5-10 minutes each time.

Similar issues have been reported before, but those either dealt with the desktop app, or were concerned with earlier versions of iOS/Signal. Some of those issues were fixed after an iOS update of Signal.

To note: I do have a large Signal database. In all, the database is around 3.89GB.

### Steps to reproduce
- Open Signal app
- "Optimizing Database" message appears

**Actual result:** 
- App crashes without loading messages

**Expected result:** 
- App should open with access to the user's messages

### Device info

**Device**:
- iPod Touch

**iOS version**:
- iOS 12.3.1

**Signal version:**
- Signal 2.39.1

### Link to debug log

There is no recent crash log in the iOS Settings section.

**Comment by michaelkirk-signal** [comment]
Sorry to hear that Signal is crashing. It sounds like we might be crashing during a migration on launch.

Do you happen to know what version of Signal you were running the last time you successfully launched?

**Comment by srouter** [comment]
Thanks for the reply—I’m currently on 2.39.1, but I’m not sure if it updated from 2.39.0 before or after this issue started happening, The issue started on Wednesday May 29th. Sorry I can't be more specific.

**Comment by charlesmchen-signal** [comment]
@srouter What model of iPod Touch are you using?

**Comment by srouter** [comment]
It's the iPod Touch 6th Generation.

**Comment by srouter** [comment]
If it's a migration issue, do you think it's worth offloading the app, reinstalling it, and seeing if that resolves the issue? My only concern is losing my database of messages; that's the thing I need to preserve. Will offloading delete the database?

**Comment by nimarb** [comment]
Hello, I have the same problem. 

Signal version: 2.41.1
iOS: 12.4
device: iPhone 6

The following is how it came to this solution, however I am obviously not sure whether it has anything to do with this bug. I my iPhone 6 ran Signal 2.41.1. Then upgraded my iPhone from 12.1.1 to 12.4. Upon completion, I was seeing lots of *No available session for contact* messages for one of my contacts, the messages displayed fine in the desktop client (paired perhaps a year ago, running version 1.26.2). I performed a "secure session reset" on the desktop client, which didn't show up on Signal on my phone. After some time and a phone restart, upon opening the Signal client I am now greeted with *Optimizing Database* and after some time the *This can take a few minuites* appears. 

The "Documents & Data" size of Signal is 1.07GB.

I am very worried about losing all my chat data and photos upon a reinstall - is there anyway to progress forward without deleting everything irretrievably? For example, if I jailbroke my phone and copied over the database would it still be accessible? Thank you!

**Comment by nimarb** [comment]
@srouter I have tried offloading Signal, it does unfortunately not solve the error but does also not delete your data.

I guess I will jailbreak my phone and try to somehow recover the SQLite DB through SSH manually, although I suppose that's a quite hopeless endeavour as it's encrypted w/ device specific keys stored in the SEP afaik.

**Comment by NiklasBr** [comment]
@nimarb I wish you good luck, but the odds are [not in your favour](1568).
