### ISSUE TITLE
Current message loses focus when new message comes in

### ISSUE THREAD

**Issue by JoshuaCrewe** [signalapp/Signal-iOS#4203]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When writing a message in one conversation while a message appears in another conversation, the focus will switch to the new message interrupting the current task. This is most frustrating if I am editing a photo to send to someone when a new message comes in.

i.e. I am writing a message to my mother when my wife texts me. While I am still typing to my mum, the new message from my wife will get opened up. I need to exit the message from my wife and open the message to my mum which has a  half typed reply I can finish. This process gets repeated with every new message that comes in.

### Steps to reproduce
- Open a message and start writing a reply
- Wait for new message to come in

**Actual result:** App redirects focus to new message.

**Expected result:** Focus should remain with current message where typing can continue. A notification should appear at the top of the screen with new message information. Same as when using another app.

### Device info
**Device**: iPhone 5c

**iOS version**: 10.3.3

**Signal version:** 2.39.1

**Comment by JoshuaCrewe** [comment]
Debug log :

https://debuglogs.org/cff753a33d346e30f41796de6f71eb84935d00c688fdf03730a9e6247ad4f403.zip

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by JoshuaCrewe** [comment]
Great! I can confirm that it is fixed. Thanks for your hard work!
