### ISSUE TITLE
Pressing volume button when sending video takes photo insted of regulating volume

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4204]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Pressing volume buttons (up & down) while sending a video doesn't control volume but instead takes a photo.

### Steps to reproduce
- open chat
- select a video from the library
- press volume button (up or down)

**Actual result:** a photo is taken.

**Expected result:** it should regulate the current video volume.

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 12.3.1

**Signal version:** 2.40.0.18

**Comment by Imperiopolis-Signal** [comment]
Thanks for reporting this issue! This will be resolved in our next beta release.
