### ISSUE TITLE
Camera's live preview is low quality - captured image is fine

### ISSUE THREAD

**Issue by ethylmorphine** [signalapp/Signal-iOS#4205]
iOS 12.3.1, Signal 2.40.0.21

When taking photos with instant camera button, image is blurred. On the other hand, taken photos are completely fine.

Steps to reproduce:
1. Tap instant camera button.
2. Focus a camera with tap.
3. Notice blurred image.
4. Take a photo.
5. Notice that photo is alright.

Reference screenshots
![Image](https://i.imgur.com/auDviIM.jpg)
![Image](https://i.imgur.com/0IMrZAr.jpg)

**Comment by Tursko** [comment]
Yeah the live preview is horrible. Good to know that the pictures do turn out fine though.

**Comment by muellermartin** [comment]
I also came across this issue several times, especially because it creates the impression that the image is just out of focus. In contrast to the native photo app, tapping the preview to adjust focus does not work in Signal for iOS or at least it is not visible due to the blurriness of the preview.

**Comment by 4m4rOk** [comment]
I still have this issue in 3.0.3.0 on iOS 13.2.3 on iPhone 6S and iPad Pro (2018).

**Comment by michaelkirk-signal** [comment]
This will be fixed in the next beta  - 3.1.0, which we will release soon.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by michaelkirk-signal** [comment]
3.1 is available in beta now

https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by ethylmorphine** [comment]
3.1.0.11 works perfectly in this aspect. The issue is pretty much gone.
