### ISSUE TITLE
Ghost I-beam in textbox

### ISSUE THREAD

**Issue by ethylmorphine** [signalapp/Signal-iOS#4206]
iOS 12.1.3, Signal 2.40.0.21

There’s a “ghost” gray I-beam when typing a message in a photo-share screen in the null position of a message. It blinks almost simultaneously with a “real” one and does follow the carriage return.

Steps to reproduce:
1. Take a screenshot or choose a photo to share it via the menu with Signal.
2. Tap on the textbox to add a message to the photo.
3. Type anything and notice the appearance of gray duplicate I-beam on the left.
4. Notice it follows lines as you type.

Unfortunately, I wasn’t able to capture it with screenshot because it doesn’t appear on them.

**Comment by u32i64** [comment]
I think this is a fraction of my bug report #4164.

However for me it's not reproducible when sharing generally, only when you use the iOS screenshot markup.

**Comment by mateoeh** [comment]
Reproducible on iOS 12.3.1 but not on 13.0 beta 2

**Comment by denver-s** [comment]
I experienced this bug but it has never shown again since version 3.0.1.
