### ISSUE TITLE
Interactions with the CDN in iOS 13 fail

### ISSUE THREAD

**Issue by vivekpatani** [signalapp/Signal-iOS#4209]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since I've updated iOS 13 (Signal Version: 2.40.0.21) Attachments (Images, Videos, or Docs) failed to be sent.

### Steps to reproduce
- Use iOS 13 Beta 1/2 and update signal
- Try sending an image.
- The circle keeps going round and round

**Actual result:** As soon as I hit the send button Signal tries to upload the image and eventually gives up and fails. It then blocks the next set of messages from being sent. After a minute or two once you the red box appears and you delete that message (or actually still don't know or understand) the queue of messages clears up and starts sending texts at least. Once I try to upload any media it loops through the whole thing again.

**Expected result:** You shouldn't have a dead queue of messages.

### Screenshots

![The message queue after images](https://user-images.githubusercontent.com/9080894/59387459-11485880-8d1e-11e9-84fd-5361db5032fb.jpeg)

### Device info

**Device**: iPhone XS

**iOS version**: iOS 13 beta 1

**Signal version:** 2.40.0.21

### Link to debug log

https://debuglogs.org/611436c5e4ebf2ead72cb3945825547e8f799a1ced2155d728126ba92d132540.zip

## Temp Fix
Re-posting for more visibility, as suggested ![here](https://github.com/signalapp/Signal-iOS/issues/4209#issuecomment-506761995) by ![Stromos](https://github.com/Stromos), the current workaround or temp fix is mentioned ![here](https://www.reddit.com/r/signal/comments/c2q6c6/anyone_using_signal_in_ios_13_beta_iphone) - Remember to clean up certificates once Signal has officially issued a fix for this.

**Comment by n4nd0br** [comment]
Same issue...

**Comment by jasonborchardt** [comment]
Also having this issue.

**Comment by u32i64** [comment]
@n4nd0br  @jasonborchardt  Please do not bump issues like that. From CONTRIBUTING.md:

> **Don’t bump issues**
> Every time someone comments on an issue, GitHub sends an email to [hundreds of people](https://github.com/signalapp/Signal-iOS/watchers). Bumping issues with a “+1” (or asking for updates) generates a lot of unnecessary email notifications and does not help anyone solve the issue any faster. Please be respectful of everyone’s time and only comment when you have new information to add.

If you just want to say that you have the same issue, you can add the `👍` reaction to the original issue post, which does not send useless notifications.

**Comment by rex4539** [comment]
For me, even plaintext fails.

**Comment by batu-one** [comment]
In addition to this, receiving images also seems broken for me in iOS 13 beta. The image fails to load (progress bar stays empty) and the retry arrow appears, repeat.

**Comment by Ki113Ra6bit** [comment]
Same issues persist in iOS 13 beta2. Sending and receiving fail as well as uploading own profile image.

**Comment by Stromos** [comment]
So this was cross posted in the Android tracker with details and a solution and I’ve been waiting for this to update. Here is the information from reddit cause and temporary solution.

https://www.reddit.com/r/signal/comments/c2q6c6/anyone_using_signal_in_ios_13_beta_iphone/?utm_source=share&utm_medium=ios_app&utm_name=ios_share_flow_optimization&utm_term=enabled

Why does signal use a self-signed cert in the first place?

**Comment by Alphakilo** [comment]
A self-signed cert is not bad in itself. It doesn't weaken the [cryptography between client and server](https://www.ssllabs.com/ssltest/analyze.html?d=cdn.signal.org). But without signature from a publicly trusted CA, it leads to failure modes described in this issue.

Also technically, the cert isn't selfsigned. It appears that TextSecure (a.k.a Whisper Systems) are maintaining their own PKI, and the cert is signed by them.

**Comment by Imperiopolis-Signal** [comment]
This is resolved in the latest beta release of our app. If you're running the iOS 13 beta, we encourage you to install this update from TestFlight. 

If you haven't used the beta version of Signal before you can join here: https://testflight.apple.com/join/8FHtd1Jq

**Comment by TCB13** [comment]
Fixed for me at 2.40.2.0.

**Comment by vivekpatani** [comment]
Thanks for fixing the issue, people who added a cert by themselves (according to ![this](https://www.reddit.com/r/signal/comments/c2q6c6/anyone_using_signal_in_ios_13_beta_iphone/), consider removing the added cert now that Signal shipped the solution in 2.40.2.0.

**Comment by Uffje** [comment]
2.40.2.0 fixed sending and receiving images and voice messages and also setting a profile picture.

**Comment by Imperiopolis-Signal** [comment]
@jmmiller60601 what version of iOS 13 are you running? This issue was fixed by Apple in 13.0 beta 6, it will not work on earlier versions.
