### ISSUE TITLE
resetAppData

### ISSUE THREAD

**Issue by bananaXiong** [signalapp/Signal-iOS#4210]
---------------------------------------
### Bug description
I want to change the deleted account to re-login to an account. But after finishing the reset database, and then get the previous database is crash, the obtained data path is already registered, in short, it causes a lot of problems, then how should I delete the database?

### Steps to reproduce
- deleteAccount

**Actual result:** crash

**Expected result:**Delete the data, enter the login interface, and log back in to the new account. 

### Screenshots
<img width="1231" alt="屏幕快照 2019-06-17 下午6 24 29" src="https://user-images.githubusercontent.com/16409590/59649896-d2e7e900-91b6-11e9-8c79-6a7ad3d3a043.png">

**Comment by michaelkirk-signal** [comment]
We don't use GitHub for developer support, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss this: https://community.signalusers.org/
