### ISSUE TITLE
In mixed groups (members with iOS and Android) updating the group picture only updates it for the Android users

### ISSUE THREAD

**Issue by adjwilley** [signalapp/Signal-iOS#4213]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a secure group of users all using Signal, when someone updates the picture for the group icon it updates the image for all the Android users but not the iOS users. 

### Steps to reproduce
Scenario 1:
- An Android user adds or changes the group image/icon

**Actual result:** The image is updated for all the Android users in the group
**Expected result:** The icon is updated for all the users in the group

Scenario 2:
- An iOS user adds or changes the group image/icon

**Actual result:** The image is updated for the iOS user who added the image, plus all the Android users in the group
**Expected result:** The icon is updated for all the users in the group

### Screenshots

iOS screenshot
![image](https://user-images.githubusercontent.com/4167575/59951276-04beb100-943e-11e9-95cf-02b944c52436.png)

Android screenshot
![image](https://user-images.githubusercontent.com/4167575/59951407-7c8cdb80-943e-11e9-9f8b-1405320606f3.png)

### Device info

**Device**: Unknown (I will ask and update the issue when I find out)

**iOS version**: Unknown

**Signal version:** Latest production as of 06/21/2019

**Comment by michaelkirk-signal** [comment]
Thanks for the report! 

This should be fixed in the latest AppStore release: 2.40.1

**Comment by michaelkirk-signal** [comment]
Note: After updating, the iOS user won't automatically see the new avatar.

Someone who *has* the desired avatar will need to send another group update, e.g. they can change the group title, change the avatar, or add another group member.

That'll trigger a new group update message be sent to the iOS client which can now properly handle it.
