### ISSUE TITLE
all ephemeral chats yet 4GB+ storage used?!

### ISSUE THREAD

**Issue by dgobaud** [signalapp/Signal-iOS#4216]
### Bug description
Signal was using 4GB of storage but all my chats are ephemeral...

should be closer to 0 right?

tapping "clear conversation history" fixed it reduced storage to ~112MB

### Steps to reproduce
Use Signal with ephemeral chats. App takes up gigabytes...

**Expected result:** Use close to use 0GB space.

### Device info
**Device**: iPhone 7 Plus

**iOS version**: 12.3.1

**Signal version:** 2.39.2.0

### Link to debug log
I thought logs were the problem so I disabled it but it didn't free the space.

**Comment by arrtchiu** [comment]
Totally random guess as to what it might be: sqlite needing a vacuum.

https://github.com/yapstudios/YapDatabase/blob/5a7e70a2101ba78b1f92bc992b78dc2e06adb941/YapDatabase/YapDatabaseConnection.h#L660-L673

**Comment by b3hni4** [comment]
Is there any update on this? I am having the same issue. Deleted all media from my chats and am still left with close to a gig of used space on my iPhone. 
Using iPhone and iPad (iOS iPadOS 14.4.1) and signal version 5.7.0.19

**Comment by HanSeoulOh** [comment]
still no update? related issue #4916
