### ISSUE TITLE
Share screen is has blank Share button

### ISSUE THREAD

**Issue by Deucem** [signalapp/Signal-iOS#4217]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

The Share sheet that slides up in Signal contains no button to Share. The button is however there, if you tap the top right hand corner it works, however the button is not visible to the end user

### Steps to reproduce

- Open app such as Linkedin Learning
- Share content and select Signal
- Select desired contact to share with
- Witness screen has contacts name, but share button is not visible 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Share screen does not have visible share button

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Share screen should have visible share button

### Screenshots

See below.

![2019-06-25 10_22_55-Photos](https://user-images.githubusercontent.com/49849553/60060396-c96cfc80-9733-11e9-8d67-befc527b96ed.png)

<br />
<br />

![unnamed](https://user-images.githubusercontent.com/49849553/60060398-c96cfc80-9733-11e9-80da-0cb3cc7ec1db.jpg)

### Device info

**Device**: Iphone XS Max

**iOS version**: 12.3.1

**Signal version:** 2.40.1.3

**Comment by denver-s** [comment]
I cannot reproduce this behaviour, I think it has been fixed.
