### ISSUE TITLE
iOS 13 Beta - Small UI bug in Privacy settings

### ISSUE THREAD

**Issue by Orbixx** [signalapp/Signal-iOS#4219]
### Bug description
Option slider placement bugged in iOS 13.

### Steps to reproduce
With Signal already installed, or installed after upgrade to iOS13, open Signal, go to settings and then Privacy and scroll down.

### Screenshots
![image](https://user-images.githubusercontent.com/1606867/60393209-915b2480-9b4c-11e9-9605-140489bf32e2.png)

### Device info

**Device**: iPhone XS

**iOS version**: iOS 13.0 Public beta build 17A5508m

**Signal version:** 2.40.1.3

### Link to debug log
https://debuglogs.org/42d085121f54d5e463ff4899ae7f849a31d65399ff21a4c456f86ec2bb8e5767.zip

**Comment by michaelkirk-signal** [comment]
Thanks, this will be fixed in the next iOS beta.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
