### ISSUE TITLE
Sending GIFs breaks posting

### ISSUE THREAD

**Issue by jbrva** [signalapp/Signal-iOS#4221]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Once you send a GIF, none of the messages after it are received by the person and none of the images sent are received either. You can reset by reinstalling the app, but if you send another GIF the bug reemerges.

### Steps to reproduce
- Install app
- Send GIF
- Send anything else and the other side doesn't receive anything. Their messages to you continue to come in.

**Actual result:** Unable to talk with contacts again unless you reinstall app.

**Expected result:** Sending GIFs shouldn't break sending messages.

### Device info

**Device**: iPhone 7 Plus

**iOS version**: 13.0

**Signal version:** 2.40.1.3

**Comment by l3jyeo** [comment]
> This is resolved in the latest beta release of our app. If you're running the iOS 13 beta, we encourage you to install this update from TestFlight.
>
> If you haven't used the beta version of Signal before you can join here: https://testflight.apple.com/join/8FHtd1Jq

Please see issue https://github.com/signalapp/Signal-iOS/issues/4209

**Comment by jbrva** [comment]
Indeed. Joining TestFlight fixed my problem.
