### ISSUE TITLE
Beta iOS 13.3 iPhone X - can not send or revive media

### ISSUE THREAD

**Issue by KitemanMD** [signalapp/Signal-iOS#4222]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As Title
iPhone X Beta 13.3 - in group and one to one can not revive or send media. 

### Screenshots
Reviving:
![2ABDC9C2-84D0-4249-8EEB-CF05CB505F4F](https://user-images.githubusercontent.com/1299952/60730751-26439080-9f46-11e9-8528-80314313f7d9.jpeg)

Sending:
![F3DFAA75-400A-4A0E-8FC7-1D373BFEAC27](https://user-images.githubusercontent.com/1299952/60730816-4d9a5d80-9f46-11e9-8fbb-781756815027.jpeg)

### Device info

**Device**: iPhone X

**iOS version**: Beta 13.3

**Signal version:** 2.40.1.3

### Link to debug log

https://debuglogs.org/5eaf8945d0e33aab0c0e7840b17af4d0bc3c7abbb843abe165d83fd1c0d7e7b6.zip

https://debuglogs.org/c27a335ab137dcf6724af995af40bf0ebe99c03270947efce7c2339fcfe7b1bd.zip

**Comment by u32i64** [comment]
This is likely fixed in Signal 2.40.2+ (currently in beta), see #4209, https://github.com/signalapp/Signal-iOS/issues/4209#issuecomment-507423733.

**Comment by Cerberus0** [comment]
This issue is a duplicate of https://github.com/signalapp/Signal-iOS/issues/4209.

**Comment by KitemanMD** [comment]
Hey, thanks for the comment. In the Beta and TestFlight it works fine.

**Comment by denver-s** [comment]
@KitemanMD please close the issue if it has been fixed.

**Comment by oculos** [comment]
Same on 2.40.3.2

**Comment by michaelkirk-signal** [comment]
This is a known issue with the iOS13 beta. 

We have a work-around available via our Signal-iOS beta distribution if you'd like to try it.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by MrPickles2009** [comment]
@michaelkirk-signal what is blocking this ability in the new iOS?

**Comment by ideologysec** [comment]
@MrPickles2009 nothing is blocking this ability in the new iOS? Run the Signal beta on the beta operating system, or wait for the non-beta release of Signal 2.40.2+

**Comment by KitemanMD** [comment]
Thank you all for the comments. Issue closed.
