### ISSUE TITLE
App get crashed at sharedDataDatabaseFilePath under ensureIsReadyForAppExtensions Signal iOS App.

### ISSUE THREAD

**Issue by AshwiniSBB** [signalapp/Signal-iOS#4223]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michaelkirk-signal** [comment]
It seems like you are trying to compile and run Signal yourself. This should be possible, but we don't use Github for troubleshooting development setups. We only use GitHub for bugs with existing functionality in the published app. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss this: https://community.signalusers.org/
