### ISSUE TITLE
Cursor zoom showing image instead of text for image sent from photos app

### ISSUE THREAD

**Issue by shawes** [signalapp/Signal-iOS#4226]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When using drag and zoom to move the cursor, the background image is shown instead of the text when sharing image from photos. Note that within the signal app when selecting a photo, the zoom shows the text (the correct behaviour).

### Steps to reproduce
- select a photo in photos
- click the share icon
- choose signal
- type text to associate with the image
- hold down on the text box to move the cursor producing a zoomed circle

**Actual result:** The zoomed circle shows the picture behind

**Expected result:** The zoomed circle shows the accompanying text to place the cursor

### Screenshots
![IMG_3877](https://user-images.githubusercontent.com/3920598/61445639-56e0ec80-a980-11e9-81ec-b614e43b9ec9.PNG)

### Device info
**Device**: iPhone SE

**iOS version**: 12.3.1

**Signal version:** 2.40.3.2

**Comment by denver-s** [comment]
I cannot reproduce this bug using version 3.0.0.2

**Comment by denver-s** [comment]
I am unable to reproduce this bug (iPhone 8 Plus - v3.8.0.32).

**Comment by shawes** [comment]
Well the magnifying glass has disappeared in iOS13, so its not so much of an issue anymore.
