### ISSUE TITLE
Unable to view metadata about messages with only a link as content

### ISSUE THREAD

**Issue by BenEgeIzmirli** [signalapp/Signal-iOS#4228]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is mostly a UX bug... Normally, I use the metadata (long-press on a message I've sent -> more info) to see who in my group has read my message. If the message is purely a link, it seems there is no "safe zone" on the message box where a long-press will open the message metadata dialog. Regardless of where on the message bubble I long-press, it opens the iOS "link actions" dialog.

It is only while writing this bug report that I realized that a long press *next to the message* will bring up the dialog. However, I think this is unintuitive, as it turns the message metadata dialog into a hidden affordance. The implication is that the space next to the message is purely whitespace, and that the message bubble itself is the only interactable element.

### Steps to reproduce
- Send a link to an individual or group in the Signal iOS app
- Long press on the message to get the in-app dialog to delete the message, "more info", etc...

**Actual result:** the iOS "long press on a link" dialog comes up, instead of the Signal app "long press on a message" dialog

**Expected result:** the Signal app "long press on a message" dialog should come up, provided the user pressed on a part of the message bubble that did not actively have a link in it.

### Screenshots

Intended dialog from a long-press is shown below. The UI implies that if I long-press in the circled region, I should get the Signal app's "long press on a message" dialog. Instead, I have to long-press in the region to the left of the message.
![66FAD761-F518-4AC3-8A46-A0F64788AE14](https://user-images.githubusercontent.com/7796950/61836431-0a405a00-ae35-11e9-9087-e0e1b8475a61.jpeg)

If I long-press anywhere in the message bubble itself, I get the following result:
![FE8A83B1-2A3A-4998-BE92-B4EC7B57528B](https://user-images.githubusercontent.com/7796950/61836527-74f19580-ae35-11e9-93bf-7811ef5caeef.jpeg)

### Device info

**Device**: iPhone 8+

**iOS version**: 12.3.2

**Signal version:** 2.40.3.2

### Link to debug log

https://debuglogs.org/4db2616a78e08caaab062f7fcccfa2ca092fc0d78c30ed638138d6dbfc085c4c.zip

**Comment by vinkla** [comment]
I’m having this issue as well. Not able to delete messages with only a link as content.

**Comment by denver-s** [comment]
You need to press beside the message bubble if it contains only a link.
