### ISSUE TITLE
Respect system-wide Dark mode on iOS

### ISSUE THREAD

**Issue by ideologysec** [signalapp/Signal-iOS#4229]
iOS 13 is coming, and it has a system-wide dark mode toggle (finally)! Are there any plans to implement a "light/dark/respect system" toggle for dark mode in Signal?

This would be worth implementing in the share extension as well (ref an earlier issue about dark mode in the extension I can't dig up right now because on mobile).

additionally additionally, are there any plans to implement pure-black (or closer to it) dark mode for OLED screens (X/XS/XS Max)? (It's not strictly necessary, but I do so love the option, even at the cost of the display smearing on scroll a little).

**Comment by michaelkirk-signal** [comment]
We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
