### ISSUE TITLE
No Push Notifications on iOS 12

### ISSUE THREAD

**Issue by klues** [signalapp/Signal-iOS#4230]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A friend of mine is using Signal on iOS 12 and does not receive any push notifications on incoming messages

**Actual result:** No notifications of received messages until Signal app is opened.

**Expected result:** Notifications should show up, even if Signal app is not opened

### Device info
I hope device and version informations can be found in the log, I don't know the exact information of my friend.

### Link to debug log
See log here: https://debuglogs.org/dca680462157c17c11c66009fe7970147a0279fe51d8370cd4d30212b5dae6ab.zip

**Comment by michaelkirk-signal** [comment]
Can you have your friend send a screenshot of Settings > Notifications > Signal ?

**Comment by klues** [comment]
Ok, it seems that she now found the incorrect setting there and it's working now. Thanks for your time!

However it seems that notifications in iOS are not enabled by default?! I don't think that she disabled them there manually.

**Comment by michaelkirk-signal** [comment]
> However it seems that notifications in iOS are not enabled by default?! I don't think that she disabled them there manually.

It's not possible for iOS applications to change a users notification settings for them.

Either: We requested notification access and your friend chose decline.

Or: We requested notification access and your friend initially approved, but later they manually revoked access in settings.
