### ISSUE TITLE
Failed to create directory: (null)

### ISSUE THREAD

**Issue by mahmutsahinn** [signalapp/Signal-iOS#4234]
Hi all, I am getting this error.

<img width="1509" alt="Screen Shot 2019-07-31 at 15 54 30" src="https://user-images.githubusercontent.com/9821483/62213614-f99b6100-b3ab-11e9-8a8e-548b6faff20a.png">

Do you have any idea?

Thanks.

**Comment by michaelkirk-signal** [comment]
We don't do developer support on GitHub, only bugs with the published app's functionality. 

Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss development support: https://community.signalusers.org/
