### ISSUE TITLE
2.41.0.22 Beta crashes on launch on iOS 13.0 Beta / iPhone XS

### ISSUE THREAD

**Issue by johnnyxmas** [signalapp/Signal-iOS#4235]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
2.41.0.22 Beta crashes on launch on iOS 13.0 Beta / iPhone XS

### Steps to reproduce
- Launch the application by tapping the icon
- or, launch by tapping on the message notification banner

**Actual result**
Blue Signal app splash/loading screen appears, disappears, and presents “Signal - Private Messenger Crashed” reporting popup.

**Expected result:**
App would open, displaying message or message list. 

### Screenshots
Can’t add via iOS Safari 

### Device info

**Device**: iPhone XS

**iOS version**: 13.0 Beta

**Signal version:** 2.41.0.22

**Comment by u32i64** [comment]
Same issue on the forum: [Beta Feedback for the upcoming iOS 2.41 release (post 17)](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-2-41-release/8586/17?u=u32i64). You probably should [share a crash report with the developers](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug).

**Comment by johnnyxmas** [comment]
I did that at the same time as the bug submission.

**Comment by denver-s** [comment]
Have you experienced this issue again? Or can this be closed now?

**Comment by johnnyxmas** [comment]
No recurrence; This can be closed.

Thank You,

Johnny Xmas || https://kasada.io
CISSP - GIAC - GPEN || Security Advocate || Infosec Personality
PGP / Keybase: https://keybase.io/j0hnnyxm4s
Twitter & Wickr: @J0hnnyXm4s || Insecure: (410)H4X-0R3D

**Comment by Mihahn** [comment]
@johnnyxmas you have to close it – thanks.

**Comment by johnnyxmas** [comment]
Tested and confirmed resolved.
