### ISSUE TITLE
Image picker is very slow for large photo libraries

### ISSUE THREAD

**Issue by lieven** [signalapp/Signal-iOS#4236]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have a photo library of ± 36000 items on my iPhone SE.
Trying to select a photo from my library often takes multiple seconds.

### Steps to reproduce
- go to a conversation
- tap the + button
- choose Photo Library

**Actual result:** 

- it now takes ±5s before an image can be selected
- if you want to select a second photo by tapping the "back" button or the + button at the bottom, it again takes a long time.

**Expected result:** 

Apps using Apple's standard UIImagePickerController work pretty much instantly on my device.

### Screenshots

If needed, I have a screen recording of me trying to send an image as fast as possible. Between selecting "Photo Library" and landing back in the conversation, there's ±16 seconds.

### Device info
**Device**: iPhone SE
**iOS version**:  iOS 12.4
**Signal version:** 2.41.0

**Comment by lieven** [comment]
I've dug through the code and a potential problem is `ImagePickerController .reloadDataAndRestoreSelection()`, which fetches _all_ assets just to check if they are selected.

I've tried debugging, but I haven't gotten past the phone number registration screen.

**Comment by lieven** [comment]
There were 2 distinct problems:

1. All contents of a collection are fetched just to determine if it's empty or not:
<img width="1176" alt="Screenshot 2019-08-09 at 15 05 33" src="https://user-images.githubusercontent.com/138759/62785312-b2eeea80-bac0-11e9-8b78-80be4ca905c5.png">

2. All contents of the default photo collection are loaded on `viewWillAppear` to set the selection state on the collection view. This can be done later, when the specific cell for an asset is being displayed.
<img width="1176" alt="Screenshot 2019-08-09 at 15 06 05" src="https://user-images.githubusercontent.com/138759/62785319-b5e9db00-bac0-11e9-94cd-fcef7d61e18b.png">

**Comment by denver-s** [comment]
Photo libraries loading have been improved since version 2.42.0

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
