### ISSUE TITLE
Registration Lock doesn't work properly when re-registering device

### ISSUE THREAD

**Issue by 53SWYj3cV8nKsSr** [signalapp/Signal-iOS#4238]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I clean install my iphone and had to re-register my device but when I got to the registration lock step and my PIN didn't work. This was weird because the PIN work before I clean install my device and since I am using a password manager I just copy and paste the PIN so there is literally no way I mistype it. The error message that I got for the entering the registration lock was also weird since it was the verifcation code error message (REGISTRATION_VERIFICATION_FAILED_WRONG_CODE_DESCRIPTION) instead of the registration lock message (REGISTRATION_VERIFICATION_FAILED_WRONG_PIN). On top of all that the the textfield for entering the registration pin was also not right in which my pin was completely visible. All in all it just seem like there some sort of confliction between the verification code view and the registration code view. 

### Steps to reproduce
- Setup a registration lock
- Clean install your device or uninstall the app
- Go through the registration process again
- When you reach the registration lock view, enter your PIN
- Notice that your pin doesn't work
- Notice that the text for PIN is completely visible
- Notice that the error message is wrong

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
You are unable to sign back into your signal because you can't get pass the registration lock view. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Registration pin should work. Text in textfield should be hidden. The error message shoud be related to registration lock and not the verification code.

### Device info

**Device**: iPhone

**iOS version**: 12.4.0

**Signal version:** I download it through App Store so I assume it would be the most recent version (I literally don't where to find it sorry)

### Link to debug log

I can't sign in so I can't get you any debug 😞

**Comment by i2mo** [comment]
Same problem on iOS 13.0 (17A5556d) (public beta5).

**Comment by charlesmchen-signal** [comment]
Update to Signal to v2.41.1 in order to register. Earlier versions of Signal iOS only supported 16-digit PINs but allowed longer PINs during registration, causing a mismatch. If you wish to use a longer pin going forward, you can reset it after updating in Signal Settings > Privacy > Registration Lock.
