### ISSUE TITLE
unable to insert newlines when sending an image

### ISSUE THREAD

**Issue by richlv** [signalapp/Signal-iOS#4242]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending a message, newlines can be added in the text - the keyboard has the "return" button shown.
When sending an image, this button is not present when editing the accompanying text.

### Steps to reproduce
- Send a image.
- Try to insert a newline in the accompanying text.

**Actual result:**
Cannot do it, "return" button missing.

**Expected result:**
The "return" button is present and works.

### Device info
**Device**: iPhone6

**iOS version**: 12.4

**Signal version:** 2.41.0

**Comment by darkBuddha** [comment]
Why would this be a wontfix? It should be fixed. Why would a messenger not allow to add new lines in a message.

**Comment by garywheeler69** [comment]
- [ ]

**Comment by darkBuddha** [comment]
This is still the case, it should not be marked as wontfix. I can not imagine any reason why newlines should be blocked in a messenger.

**Comment by richlv** [comment]
Yeah, cannot even reopen it.
Closing issues like that doesn't motivate users to get involved.

**Comment by phoenix-meadowlark** [comment]
+1 this has been annoying me for a few years. 

One solution would be to keep the replacement of the `return` button with a `done` button on the default letters keyboard panel, but leave the `return` button as-is on the symbols panel (accessible by pressing `123` in the lower left corner of the keyboard). This should be technically possible as a similar behavior can be found on Discord, which replaces `return` with `@` and `#` on the default letters panel, but keeps the `return` button on the symbols panel.

This would continue to allow users who don't realize they can tap the photo to re-maximize it to use the `done` button, while also allowing `return` to be pressed without either deleting the photo or copying the text to the Notes app to add a newline. Users who use punctuation are likely to discover the `return` button organically.

@karlmiche will scope this change out.
