### ISSUE TITLE
Opening Links does not work when Safari is disabled

### ISSUE THREAD

**Issue by inoas** [signalapp/Signal-iOS#4243]
In iOS 12 and for a few versions you can disable Safari entirely and Signal will just stop working in regards to opening links - even if Firefox/Opera/Brave/Chrome are installed.

Other apps will ask what browser to open in.

Please let users configure their default browser on iOS.
As apple forces their way as much as they can this is the only way to let users chose.

p.s.: While all iOS browsers must use webkit many other parts such as password management, syncing, default Search Engines etc are different/better in browsers other than Safari. That includes for instance that Firefox allows to configure Search Engines thus that one can use say Startpage, Ecosia or Wikipedia as the default search engine.

**Comment by inoas** [comment]
See above for a list of similar issues that would all be resolved.

**Comment by michaelkirk-signal** [comment]
We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss adding a configurable browser option: https://community.signalusers.org/

**Comment by DiagonalArg** [comment]
@inoas - see my post here: https://community.signalusers.org/t/links-in-signal-iphone-please-give-us-choice-of-browser/7382

**Comment by inoas** [comment]
> We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.
> 
> The forum would be a better place to discuss adding a configurable browser option: https://community.signalusers.org/

This is not a feature request anymore.
It is a bug now.
It is a commonly available feature to disable Safari now in iOS.
Your app then cannot open links anymore because it is buggy.

**Comment by u32i64** [comment]
@DiagonalArg The author of the post you mention doesn't seem to undersand if it's a bug or not themselves:

- On this issue:
    > This is not a feature request anymore. **It is a bug now.** [...]
- On #1514:
    > [...] **it is not even a Signal bug** as iOS lets you disable Safari and then links just dont work as there is no valid handler... other apps work fine just in Signal links dont.

<sup>(emphasis mine)</sup>
