### ISSUE TITLE
calls never connect to remote android

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#4246]
https://debuglogs.org/b0ce8f871ded84fc79d9629ea15067e33d83780f3ada850823a7de4ab48a361b.zip1

github issue templates are a nightmare on mobile.

ios 10
iphone se

this is basically the same issue as # only that we've been asked to file new issue instead of commenting there

**Comment by mailinglists35** [comment]
https://github.com/signalapp/Signal-iOS/issues/3249

**Comment by mailinglists35** [comment]
call is stuck in "connecting", never "ringing"

**Comment by mailinglists35** [comment]
with or without "relay calls"

**Comment by og113** [comment]
I have the same issue. It seems to happen when calling Andriod phones and not other iPhones.
iOS 12.4.5
Signal 3.3.0.6

**Comment by og113** [comment]
In my case ”always relay calls” is set to OFF
