### ISSUE TITLE
Voice calls have a high probability of no sound

### ISSUE THREAD

**Issue by Lavie-LiuDu** [signalapp/Signal-iOS#4248]
#3814  # Bug description
Voice calls have a high probability of no sound
It is a normal voice call when it is first run. But after you don’t kill the process, continue to use voice calls, there is a high probability that there will be no sound.

### Device info

**Device**: iPhone XS, iPhone 7

**iOS version**: 12.3.1

**Signal version:** 2.41.1.2

**Comment by michaelkirk-signal** [comment]
What version of iOS is the *other* person running?
