### ISSUE TITLE
Enhancement request: Yubikey 5ci Integration

### ISSUE THREAD

**Issue by udf2457** [signalapp/Signal-iOS#4250]
https://www.yubico.com/2019/08/yubico-launches-yubikey-5ci/

Please. Thank you.  It would greatly strengthen Signal security.  ;-)

**Comment by michaelkirk-signal** [comment]
We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
