### ISSUE TITLE
Can’t load photos on iOS

### ISSUE THREAD

**Issue by rex4539** [signalapp/Signal-iOS#4253]
https://debuglogs.org/c31b44f8512175f54bfa094cfbdc69315c4c5ba71c341ead210036ea1177dc12.zip

**Comment by Cerberus0** [comment]
Hi @rex4539,

Could you please fill out [this bug report template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md)? It will help the developers get all the necessary data to fix your issue.

Thanks!

**Comment by sseneca** [comment]
Also getting this issue. Exactly the same as the previous similar issue on iOS 13

**Comment by rex4539** [comment]
https://www.dropbox.com/s/onhlu8qepifynwz/atim6111.mp4?dl=0

**Comment by michaelkirk-signal** [comment]
@rex4539 - I notice you're running iOS13.1. Did this issue start with that update?

@sseneca - can you submit a debug log after reproducing? It's hard to do much for you without that. You can post it here, or email it to me at michael@signal.org if you'd prefer.

**Comment by michaelkirk-signal** [comment]
@rex4539 - Your log shows that you are running an old beta version of the app. Could you please update and let us know if that resolves your issue.

@sseneca - Please make sure you're on the latest version of Signal also.

**Comment by rex4539** [comment]
Updating to the latest beta fixed the bug. Thanks!

**Comment by sseneca** [comment]
I was on the newest beta version at the time (2.41.1) but updating to 2.42.0 when it came out via Testflight fixed the issue; I'm now also on iOS 13.1 with no problems.
