### ISSUE TITLE
Swift compile errors

### ISSUE THREAD

**Issue by zykis** [signalapp/Signal-iOS#4257]
Tried to compile the project with a Swift. Getting following compile time errors:
1. SignalCoreKit/Cryptography.swift:31
Value of type 'UnsafePointer<_>' has no member 'bindMemory'

2. SignalCoreKit/Cryptography.swift:33
Type 'UnsafePointer<_>' does not conform to protocol 'Sequence'

Any suggestions?

**Comment by michaelkirk-signal** [comment]
We don't do developer support on GitHub, we only use it for reporting bugs with existing functionality with the distributed app. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to get development support: https://community.signalusers.org/

Please take a look at BUILDING.md before posting there, and include the last successful step you completed and which step you are having trouble with from the build instructions.

**Comment by QQzheng** [comment]
How do you solve it ?
