### ISSUE TITLE
Missing Text / not shown (in Bubble)

### ISSUE THREAD

**Issue by peterpanondrugs** [signalapp/Signal-iOS#4260]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Missing Text in Bubble

### Steps to reproduce
- (sometimes) receive a message, 
- open Signal chat

**Actual result:** When you receive a message, its not fully shown! Notification shows the full text, as soon you switch into Signal, there are lines missing and the time stamp aswell.

**Expected result:** See the complete text in bubble

### Screenshots

![2](https://user-images.githubusercontent.com/8776733/64717126-f96ea500-d4c3-11e9-9295-0fcc97d43e46.png)

### Device info

**Device**: iPhone 6

**iOS version**: 12.4.1

**Signal version:** 2.42.1

### Link to debug log

[org.whispersystems.signal 2019-09-11--06-18-33-428.log](https://github.com/signalapp/Signal-iOS/files/3601939/org.whispersystems.signal.2019-09-11--06-18-33-428.log)

**Comment by michaelkirk-signal** [comment]
When you leave and return to the conversation, does that text remain missing when you leave and return to the conversation?

Can you send me a screenshot of your "Text Size" setting from the system settings?

**Comment by peterpanondrugs** [comment]
Remains missing! 
![signal-2019-09-19-101022](https://user-images.githubusercontent.com/8776733/65226642-810d7280-dac7-11e9-87ba-18baad33f433.png)
![signal-2019-09-19-100550](https://user-images.githubusercontent.com/8776733/65226643-81a60900-dac7-11e9-9c2d-6e83d10e38a4.png)
