### ISSUE TITLE
Recieved messages not showing - iOS Iphone SE

### ISSUE THREAD

**Issue by PilkisMakenMusic** [signalapp/Signal-iOS#4262]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I updated yesterday to v.2.42.2 on my iphone SE. Since then I still get notifications of recieved messages outside the app. I can also read the messages in the preview windows of iOS. And inside signal it shows the number of new messages via the blue round marker for each conversation. The problem is that I cannot see the new messages themselves inside signal. It only shows text messages that I sent.

### Steps to reproduce
- Update to v.2.42.2
- Recieve text messages

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
As described above, I get the usual notifiactions and previews of the recieved text messages. However, inside the app in the dialogue window the recieved messages are not shown. Only the messages I send are shown, and I verified that they are send correctly.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone SE

**iOS version**: 12.4

**Signal version:** 2.42.2.0

### Link to debug log

https://debuglogs.org/839987c8cba5460552f01281499381052be05369ea54dd55c9c910d1f9deadc5.zip

**Comment by PilkisMakenMusic** [comment]
Correct, I turned on the debug logging just then. I send you here a log with more information after using the app for a while. Still no incoming messages are shown.

https://debuglogs.org/f7d32bab9d24fb9d74faab4bec9aa5c0a4d957b0ddd67546086d664e99b3b281.zip

I also updated the iOS to 12.4.1and Signal to 2.42.3.0, but nothing changed. The problem persists.

My system clock is correct.

**Comment by PilkisMakenMusic** [comment]
I just saw that there was a new update 2.42.4.0. The problem also persists after this update.

**Comment by michaelkirk-signal** [comment]
I see a lot of messages like this in your debug log:

```
Couldn't commit transaction: 11 database disk image is malformed
```

Somehow your database has become corrupted. 

Is there anything you can think of which might have lead to this? e.g. running out of disk space? is the phone jailbroken?

**Comment by PilkisMakenMusic** [comment]
I'm always on the edge with my disc space to be honest. It might have been the case that I was running out of space during an update. Nevertheless, all my other apps work fine. I only have problems with Signal.

Is there anyway I can fix the problem, or will I have to make a new account?

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
