### ISSUE TITLE
Empty message sent to group contacts

### ISSUE THREAD

**Issue by adombeck** [signalapp/Signal-iOS#4263]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description
When I left a signal group yesterday, all (or probably all) group members received a private message (i.e. non-group message) from my Signal account. I don't see those messages myself inside Signal.
On my contacts devices, the message is empty. In the list of their conversations, the preview of the message said "Nachricht mit Medieninhalten" (message with media content).

### Device info
**Device**: iPjome 5s

**iOS version**: 12.4.1

**Signal version:** 2.42.4.0

### Link to debug log
https://debuglogs.org/1f8d8fb459022bfddb1295e039c2618b8b1839be980145e55d0dae0bdd10d9b5.zip

I took a look at the log. The relevant file is org.whispersystems.signal 2019-09-14--03-56-19-479.log, the messages were sent starting at 2019/09/15 00:05:37.

**Comment by michaelkirk-signal** [comment]
As of yet I haven't been able to reproduce this, nor have I found anything glaring in the debug log, so I'm going to need some more details to pursue this.

Can you be more specific about the sequence of events that lead up to this? For example, what sequence of steps did you take to leave the group?

Also, can you provide any information about the state of your device before your group members saw this message? Did your device become unregistered at some point - perhaps because you temporarily registered it on another device?

**Comment by michaelkirk-signal** [comment]
Oh interesting, we don't use the text "Nachricht mit Medieninhalten" in our app anywhere, it seems that it's from Signal-Android.

I wonder if it was an issue with how the Android devices received the message rather than how your device sent it.

Were there any iOS users in that group? Did they see such an error message?

Could you ask any of the recipient users to submit a debug log? Logs are deleted after about three days, so getting them soon would be essential! They can mail them to me at michael@signal.org if they don't want to post them here.

> the messages were sent starting at 2019/09/15 00:05:37

That corresponds with your leaving the group right? 

So the "leave group message" was likely the one with timestamp: 1568498737190, is that right?

**Comment by adombeck** [comment]
Thanks for the fast reply!

> As of yet I haven't been able to reproduce this, nor have I found anything glaring in the debug log, so I'm going to need some more details to pursue this.
> 
> Can you be more specific about the sequence of events that lead up to this? For example, what sequence of steps did you take to leave the group?

I clicked on the 3 dot menu in the group and clicked "leave group". Then the menu became stuck / didn't react, so I clicked the back button. I clicked on the group thread and went back several times. Only after about 2 minutes it showed the message that I had left the group.

> Also, can you provide any information about the state of your device before your group members saw this message? Did your device become unregistered at some point - perhaps because you temporarily registered it on another device?

No, the device did not become unregistered and I didn't register any other devices.

> Oh interesting, we don't use the text "Nachricht mit Medieninhalten" in our app anywhere, it seems that it's from Signal-Android.

Yes, the user who saw that text uses Signal-Android.

> I wonder if it was an issue with how the Android devices received the message rather than how your device sent it.
> 
> Were there any iOS users in that group?

Yes.

> Did they see such an error message?

I don't know yet, but will get back about that. Meanwhile I found out that there were also Android users who did not receive the message, so it was not sent to all users of the group.

> Could you ask any of the recipient users to submit a debug log? Logs are deleted after about three days, so getting them soon would be essential! They can mail them to me at michael@signal.org if they don't want to post them here.

OK.

>     the messages were sent starting at 2019/09/15 00:05:37
> 
> That corresponds with your leaving the group right?

Yes, the messages were sent/received right after I left the group.

> So the "leave group message" was likely the one with timestamp: 1568498737190, is that right?

That's possible, I'm not sure what the purpose of that message is.

**Comment by michaelkirk-signal** [comment]
You say you clicked the “three dot” menu but Signal iOS has no such menu.

Can you clarify what device you were using and the steps you took on that device.

**Comment by adombeck** [comment]
> You say you clicked the “three dot” menu but Signal iOS has no such menu. Can you clarify what device you were using and the steps you took on that device.

Oops. OK, let me clarify: In fact, I'm writing this bug report on behalf of a friend, who uses Signal on iOS. I'm not familiar myself with Signal for

**Comment by adombeck** [comment]
> You say you clicked the “three dot” menu but Signal iOS has no such menu. Can you clarify what device you were using and the steps you took on that device.

Oops. OK, let me clarify: In fact, I'm writing this bug report on behalf of a friend, who uses Signal on iOS. I'm not familiar myself with Signal for iOS, but only Signal for Android and Desktop. So when my friend said that they clicked on the menu with the "leave group" button, I thought they meant the three dotted menu - but now I see that in iOS you have to click the group name to see the settings.

**Comment by michaelkirk-signal** [comment]
Ah ok. Well the most important thing at this point is getting a debug log from an Android user during the time that this empty message bubble appears. If that included you, please send your debug log over.

**Comment by adombeck** [comment]
I checked three different Android debug logs now (one created Sunday afternoon, two within the last hour), but none of them contain any entries from the relevant time :(

**Comment by michaelkirk-signal** [comment]
How about a screenshot of the affected conversation? (please redact anything sensitive)

**Comment by michaelkirk-signal** [comment]
Also, of the android users that saw the mysterious empty bubble message, which ones (if any) use Signal as their default SMS app?

**Comment by adombeck** [comment]
> How about a screenshot of the affected conversation? (please redact anything sensitive)

Here are screenshots from an android user who received the message:

https://user-images.githubusercontent.com/18482300/65149916-4b16b280-da23-11e9-9611-ba567c16264e.png
https://user-images.githubusercontent.com/18482300/65149917-4b16b280-da23-11e9-9390-32c1765796b5.png

> Also, of the android users that saw the mysterious empty bubble message, which ones (if any) use Signal as their default SMS app?

All users I got a response from by now used Signal as their default SMS app.

All the iOS users who responded did *not* receive the message, so maybe only Android users are affected.
