### ISSUE TITLE
iOS 13: Sharing Extension locks Mail App 

### ISSUE THREAD

**Issue by andyggg** [signalapp/Signal-iOS#4265]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 iOS 13 Mail App freezes when trying to send a PDF attached to an email to Signal using the share extension
Might be similar root cause as in issue 4220, see
https://github.com/signalapp/Signal-iOS/issues/4220

### Steps to reproduce
- open email comprising a PDF attachment in iOS mail app
- tap on PDF to display it in full screen
- tap on share icon (at lower left)
- select Signal as target to share

**Actual result:**
- an error message appears (in German, says basically “attachment couldn’t be prepared; the process could not be finished”)
- tap on “Cancel”
- Share Extension and Mail App are now frozen

**Expected result:** 
- PDF should be shared with Signal app

###Screenshots
![42187388-FF36-4CFB-9983-BDDD58161F7B](https://user-images.githubusercontent.com/7358750/65368996-35360700-dc48-11e9-93fd-c6e4d1e891a6.jpeg)

### Device info
**Device**: iPhone X

**iOS version**: 13.0 (official release)

**Signal version:** 2.42.4.0

**Comment by denver-s** [comment]
I cannot replicate this bug. Version 3.4.0.7

**Comment by andyggg** [comment]
Me not either anymore. Has apparently been fixed in the mean time 😀
