### ISSUE TITLE
iOS 13: App closes on attach via Camera functionality

### ISSUE THREAD

**Issue by priyankn** [signalapp/Signal-iOS#4268]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal shuts down when an attachment via Camera is attempted

### Steps to reproduce
- Open Contact and press the "+" icon
- Select the first option i.e. Camera
- Camera app opens but "crashes" the app after ~1 sec

Note: The Attachment works if we attach via the camera icon on the right side (i.e. without going via "+" sign). 

**Actual result:**  Signal Shuts down

**Expected result:**  Attachment via the Camera app should be successful.

### Device info

**Device**: iPhone 8 (device: "iPhone 10,1")
**iOS version**: 13.0

**Signal version:** 2.43.0.17 

### Link to debug log
Not sure if this is an actual "crash", cannot find the actual .ips for today's date. The latest I can find is 4 days ago.

**Comment by Imperiopolis-Signal** [comment]
Can you please attach the debug log from your device? Additionally, if you can include the crash report you have, even if from four days ago, it may be helpful.

**Comment by priyankn** [comment]
Sent to support@signal.org referencing the Issue#

**Comment by priyankn** [comment]
**Update:** Issue persists on iOS 13.1

**Comment by priyankn** [comment]
@Imperiopolis-Signal Still dint get the crash logs, but I figured System logs might be helpful:

default	23:08:03.070855 -0400	CommCenter	Creating service facility connection with <private>
default	23:08:03.071525 -0400	runningboardd	Invalidating assertion 26-55-137842 (target:application<com.apple.BusinessChatViewService>) from originator 55
default	23:08:03.071684 -0400	wifid	__WiFiManagerSBHomeScreenStateUpdate: No change in SB Home Screen state
default	23:08:03.071748 -0400	wifid	__WiFiManagerCameraStateUpdate: No change in camera state
default	23:08:03.072365 -0400	CommCenter	[FBSSystemAppProxy:0x1017e17d0] Service facility connection invalidated
default	23:08:03.072414 -0400	CommCenter	#I FBSDisplayLayoutUpdateHandler: 4. app got notification state: pid=13014 for <private>
default	23:08:03.073197 -0400	assetsd	Connection opened for client with PID: 13014, bundle ID: <private>
default	23:08:03.073976 -0400	tccd	PID[13060] is checking access for target PID[13014]
default	23:08:03.076247 -0400	sharingd	SystemUI changed: 0x0 -> 0x0
default	23:08:03.083419 -0400	assetsd	Updating configuration of monitor <RBSProcessMonitorConfiguration: 0x14584fc40; id: M13060-2; qos: 17> {
    predicates = {
        <RBSProcessPredicate: 0x145843440> {
            predicate = <RBSCompoundPredicate; <RBSCompoundPredicate; <RBSProcessEUIDPredicate; 501>; <RBSProcessBKSLegacyPredicate: 0x145905530>>; <RBSProcessBundleIdentifierPredicate; org.whispersystems.signal>>;
        };
    }
    descriptor = <RBSProcessStateDescriptor: 0x14584e0f0; values: 11> {
        namespaces = {
            com.apple.frontboard.visibility;
        }
    };
}
default	23:08:03.084714 -0400	Signal	Connecting to XPCPhotoLibraryStore <private>
default	23:08:03.087144 -0400	runningboardd	Acquiring assertion targeting application<org.whispersystems.signal> from originator [application<org.whispersystems.signal>:13014] with description <RBSAssertionDescriptor; "Shared Background Assertion 3 for org.whispersystems.signal"; ID: 26-13014-137845; target: 13014> attributes = {
    <RBSLegacyAttribute: 0x105d5e6e0; requestedReason: FinishTask; reason: FinishTask; flags: PreventTaskSuspend>;
    <RBSAcquisitionCompletionAttribute: 0x105d6fb70; policy: 0>;
}
default	23:08:03.087274 -0400	runningboardd	Assertion 26-13014-137845 (target:application<org.whispersystems.signal>) will be created as inactive as start-time-defining assertions exist
default	23:08:03.088175 -0400	runningboardd	Finished acquiring assertion 26-13014-137845 (target:application<org.whispersystems.signal>)
default	23:08:03.128273 -0400	Signal	Creating PLChangeHandlingContainer for library URL: <private>
default	23:08:03.128446 -0400	Signal	PLChangeNode [<private>]: Created change node with UUID <private> for libraryURL: <private>
default	23:08:03.128684 -0400	runningboardd	Invalidating assertion 26-13014-137845 (target:application<org.whispersystems.signal>) from originator 13014
default	23:08:03.132803 -0400	Signal	openPhotoLibraryDatabase: Photo library is already open
default	23:08:03.135343 -0400	distnoted	register name: ACDAccountStoreDidChangeNotification object: kCFNotificationAnyObject token: f489a pid: 13014
default	23:08:03.138434 -0400	accountsd	"<private> (<private>) received"
error	23:08:03.139263 -0400	accountsd	"Cannot check access to a private account type: <private>"
default	23:08:03.139329 -0400	accountsd	"No TCC state found: <private>, <private>"
error	23:08:03.140304 -0400	accountsd	"Client (<private>) attempted to access restricted account type: <private>"
**fault	23:08:03.148542 -0400	accountsd	Unentitled access by client 'Signal' (selector: <private>)**
**error	23:08:03.148624 -0400	Signal	"Error returned from daemon: Error Domain=com.apple.accounts Code=7"**
default	23:08:03.229718 -0400	mediaserverd	-CMSMUtilities- CMSMUtility_PostNotificationToSession: CMSession: Notifications posted successfully. Overall system looks good.

**Comment by lfwinster** [comment]
Have something useful adding to the mix:

I have been suffering from this issue ever since I started using Signal on my iOS device. Looks like there is a gap between you open the camera and before the app shuts down and I've fought against it by taking a photo as fast as I can then click on the send button. If I am fast enough, the picture will get sent. That is how I've been using signal to send pictures :(

Today I accidentally discovered that if I remove signal's access to microphone on my iOS device, the app no longer blackout and exit while using the camera. Maybe there is something wrong about the mic
