### ISSUE TITLE
Not possible to manually delete a message that contains a link

### ISSUE THREAD

**Issue by brenner14** [signalapp/Signal-iOS#4270]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If someone sends you a hyperlink, it's not possible to delete the message by long-pressing on it, like how you can with normal messages. Instead, it will open up a preview of the link.

### Steps to reproduce
- Receive a hyperlink in a message (just a link, no other message content)
- Long press on the message that contains the hyperlink, as if you wanted to delete it
- The link preview context menu will pop up
- There is no way to delete this message (short of deleting entire conversation history?)

**Actual result:** 
The link context menu pops up

**Expected result:** 
The link context menu should include some way to delete the message or shouldn't appear at all (i.e. long pressing the link leads to the preview, but pressing on the negative space in the chat bubble brings up the delete menu).

### Device info
**Device**: iPhone XS
**iOS version**: 13.1
**Signal version:** 2.43.1

**Comment by u32i64** [comment]
Hold outside of the message bubble on the same row as it.

**Comment by brenner14** [comment]
Wow, can't believe I never tried that. Thanks.

**Comment by SilverGreen93** [comment]
Thanks for this tip. This helped me on WhatsApp as well.
