### ISSUE TITLE
New Message text misaligned on 5.8" devices

### ISSUE THREAD

**Issue by titanous** [signalapp/Signal-iOS#4273]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The New Message input text is misaligned on 5.8" devices.

### Screenshots

![image0](https://user-images.githubusercontent.com/13026/65820919-dc90dc00-e1fc-11e9-9300-62065ba63c63.jpeg)

### Device info

**Device**: iPhone 11 Pro (this almost certainly affects the X and XS too)

**iOS version**: 13.1.1

**Signal version:** 2.43.2.1

**Comment by nitishraj** [comment]
This also affects 6.1” devices (XR, 11) as well. I’m on XR with the latest stable release of iOS

**Comment by denver-s** [comment]
I think they fixed this misaligned input text recently.
