### ISSUE TITLE
Message sent by means of Share icon from Photos App - Lossage.

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#4274]
iPhone 5S.  
Signal 2.42.4.0
iOS 12.4.1

I went into the Photos app for the iphone, viewed a photo and then selected the "share" icon in the bottom left.  I selected Signal from there and sent the image to a contact, adding a one line note on the bottom.  The message appears on my Signal desktop under the message stream of the person I sent it to, but it does not appear on the iphone under that stream.  All other messages do appear properly.  Restarting Signal on the iphone does not help.  The message is still not appearing.

Signal log from iPhone: https://debuglogs.org/2f7312b64a165ffb04dae3d52fb465853deb6cb14d78d6e256a2ffe400d0a24c.zip

Desktop log from Ubuntu 16.04 machine:
https://debuglogs.org/8a1bb067d69ece85b656b17f71a5dfcfb270280a7318621231706f1b1fbecd7e

**Comment by denver-s** [comment]
I am unable to reproduce this bug (v3.8.0.32).

**Comment by DiagonalArg** [comment]
I'm not sure if there's anything else I can provide.  Let me know if so.
