### ISSUE TITLE
iOS app not sending messages when Cloudflare Warp is enabled

### ISSUE THREAD

**Issue by binarycleric** [signalapp/Signal-iOS#4275]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal seems to be unable to send messages when Cloudflare Warp is enabled. Messages appear to be stuck in "Sending" and eventually fail. Disabling Warp makes the messages send again successfully.

### Steps to reproduce

- Download Cloudflare Warp
- Enable Warp.
- Try to send a message on Signal.
- (As far as I can tell) it get stuck.
- Disable Warp.
- The message should deliver as usual.

**Actual result:** Messages fail to send if connected to Cloudflare Warp.

**Expected result:** Messages should either send normally or give an error.

### Screenshots

![IMG_3195](https://user-images.githubusercontent.com/197226/65826731-d7548100-e23e-11e9-8e3f-279e70cefb44.png)

Messages sit like this when Warp is enabled. Disabling warp sends & delivers messages as normal.

### Device info

**Device**: iPhone X
**iOS version**: 13.1.1
**Signal version:** 2.43.2.1

### Link to debug log

https://pastebin.com/mYyLZnz3

**Comment by ethylmorphine** [comment]
Well, I lose Internet connection at all when Warp is enabled.

**Comment by michaelkirk-signal** [comment]
Your logs just show that you're failing to connect.

Can you follow up with the warp folks and figure out if or why they're preventing you from accessing the signal service?

**Comment by nitishraj** [comment]
For me, it works most of the time except when Cloudflare Warp routes traffic through SE Asian countries (mostly SG & ID)

**Comment by binarycleric** [comment]
Signal appears to be working after a recent Cloudflare Warp update. If you are impacted can you update and post in here if you are still having problems?

**Comment by brainstorm** [comment]
Works for me too.
