### ISSUE TITLE
Adding 3rd-party library

### ISSUE THREAD

**Issue by zykis** [signalapp/Signal-iOS#4277]
Hello!
I was wondering, if I could add a 3rd-party library (for example: Crashlytics) via cocoapods somehow?
It looks like building process is oriented on .gitmodules. And there will be no difference in editing Podfile, since 'make dependencies' calls 'git submodule update --init' that is pointing on 'https://github.com/signalapp/Signal-Pods'

**Comment by u32i64** [comment]
Note that the GitHub issue tracker is not intended for developer support. You may ask for help on the [community forum](https://community.signalusers.org/) instead.
