### ISSUE TITLE
Contacts new to Signal do not appear in contact list when composing a message

### ISSUE THREAD

**Issue by TempSpas** [signalapp/Signal-iOS#4283]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the past few months, Signal has sent me an alert for two of my contacts that have started using Signal for the first time. I receive a notification that reads "[Contact's name] is on Signal!" and in the app's message list it has created a new conversation thread for that contact. However, when I compose a new message and Signal brings up my contact list, the new contacts are not there. This means that if I delete the conversation thread Signal creates when the new contact joins, I can no longer easily starts a conversation with that contact.

### Steps to reproduce
- Have a contact that has not previously been using Signal download and activate Signal (no invitation).
- Observe Signal sends a notification that this new contact is now on Signal.
- Tap upper right corner to compose new message.
- Observe the new contact is not listed among Signal's contacts.

**Actual result:** The contact that has joined Signal is not listed with the other Signal contacts.

**Expected result:** The contact that has joined Signal should be listed with the other Signal contacts.
### Device info

**Device**: iPhone XR

**iOS version**: 13.1.2

**Signal version:** 2.43.3.1

### Link to debug log

(No log because this bug is not easily reproducible since it requires others without Signal).

**Comment by giga1699** [comment]
Confirm still an issue on Signal 2.44.0.19 running on iOS 13.1.3, also on iPhone XR.

**Comment by giga1699** [comment]
Issue persists on Signal version 2.45.0.29 on iOS 13.2.

**Comment by eidermar** [comment]
Same Problem here!

**Comment by michaelkirk-signal** [comment]
@giga1699, @eidermar, @TempSpas, or anyone else experiencing not seeing users known to be Signal users in their contact list...

Could you please:

- Make sure debug logging has not been disabled (Settings > Advanced > Debug Logs).
- Tap the compose button to go to your list on Signal Contacts
- Pull down to force the client to check for new Signal users now
- If the user is still missing after that, submit a debug log, either to this issue, or you can mail it to michael@signal.org

**Comment by TempSpas** [comment]
I followed the directions and the contact still appears to be missing. Here is the debug log:

https://debuglogs.org/432e3df45558f884cb41721c3761debf3dbe0abe628ccab00844a9649c484b28.zip

**Comment by giga1699** [comment]
This seems to be fixed in Signal 3.0 on both iPhone and iPad.
