### ISSUE TITLE
Pictures not getting send

### ISSUE THREAD

**Issue by Naxterra** [signalapp/Signal-iOS#4284]
Checklist

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When sending Pictures and Videos from iOS 13.1.2, many of them are stuck which a circle button on the bottom right. It is also not able to send any live pictures. Also I think there is a limit of 10 files to be send at the same time because it says error and closes it

### Steps to reproduce
- Open Photos or Google Photos app
- Click share
- Find and click on Signal
- Send pictures and videos (12-13) with live photos and videos (30-40 second small videos)
- Send pictures one by one without delay

**Actual result:** 
First picture gets delivered
If selected one picture afterwards it will stuck on loop
If selected multiple pictures and videos, it gives error and closes it

**Expected result:** 
Send all files normally 

### Screenshots

![2ACB9006-27A5-43F2-8F5D-8D6AC914627D](https://user-images.githubusercontent.com/41871948/66814639-3a306280-ef37-11e9-9f3c-9f16448fac19.jpeg)

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 13.1.2

**Signal version:** 2.43.3.1

### Link to debug log

https://debuglogs.org/e178c36a3ff8ef67ad4303266e1dbe9f2bb6d9327aca52150b5ad38b7d2100e7.zip

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
