### ISSUE TITLE
Camera error when opened quickly from attachment picker

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4289]
May be related to #4268.

### Steps to reproduce
- open a conversation
- tap `+` icon
- quickly tap in relatively the same place (if keyboard is hidden) in order to press the camera button

**Actual result:** Camera error:

![signal](https://user-images.githubusercontent.com/19972511/67418116-e24ac900-f5d2-11e9-8eb1-d1ca5ee2ed45.png)

Or input bar invisible until app is backgrounded and foregrounded (then it may show the above error on the camera screen too):

![signal](https://user-images.githubusercontent.com/19972511/67418240-1aeaa280-f5d3-11e9-91dd-3940978f77c7.jpg)

**Expected result:** Camera is opened and working

### Device info

**Device**: iPhone SE
**iOS version**: 13.2 beta
**Signal version:** 2.44.0.20

### Link to debug log

https://debuglogs.org/8cf2aaf8224e5630b33c3c77177b8c6c162badad0b5db91bdeba5c7ec4884565.zip

**Comment by denver-s** [comment]
Did some tests and using version 3.0.0.2 I cannot reproduce this bug.

**Comment by u32i64** [comment]
I can't reproduce it consistently, but with ~10 tries I managed to get it (note the viewfinder displays the live image properly though):

<details><summary>Screenshot</summary>

![](https://user-images.githubusercontent.com/19972511/76234037-2ebd3b00-623a-11ea-98ae-553320fcc0e8.jpeg)

</details>

**Device:** iPhone SE
**iOS version:** 13.4 Public Beta 4
**Signal version:** 3.6.1.4
