### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1

### ISSUE THREAD

**Issue by lcying** [signalapp/Signal-iOS#4290]
I downloaded Swift 5.0.1, but remind me

**Comment by lcying** [comment]
The Swift standard library from the toolchain cannot be used on devices.

Select a macOS or simulator run destination instead, or use a different toolchain that only provides the compiler.

**Comment by stoneburner** [comment]
more information is in the community forum https://community.signalusers.org/t/unable-to-build-current-master/9777

**Comment by maiorov** [comment]
Same problem here

**Comment by michaelkirk-signal** [comment]
We don't use GH for development support - for that see the community forums.

I'll follow up in https://community.signalusers.org/t/unable-to-build-current-master/9777.
