### ISSUE TITLE
Sent Disappearing messages should only disappear when they do so for the other party

### ISSUE THREAD

**Issue by dimaatmelodromru** [signalapp/Signal-iOS#4291]
### Bug description
Sent Disappearing messages should disappear only when they do so for the other party
### Steps to reproduce
Just send a disappearing message when the other party is not online or the chat view is not open message is not being viewed)

**Actual result:**
Say I set the timeout to 30s.
A sent message will disappear after 30s of being visible _**to me**_ which makes no sense: I can delete my own message whenever I want and I want to see its delivery/view status and that is just not possible when it is gone.

**Expected result:** 

Sent messages should disappear at the same time when they disappear to the recipient.

**Comment by michaelkirk-signal** [comment]
What you have requested is not how disappearing messages are intended to work.

We reserve GitHub only for reports to existing functionality that isn't working as intended. 

If you'd like to discuss the merits of a different approach, please do so at our [community forum](https://community.signalusers.org), which is where feature discussions happen.
