### ISSUE TITLE
'sharedApplication' is unavailable: not available on iOS (App Extension) 

### ISSUE THREAD

**Issue by mansoorshaik93** [signalapp/Signal-iOS#4292]
### Bug description

**'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.**

I am getting this error while try to compiling the code.i have 't made any changes in the code.Just downloaded, installed the pods and ran build

### Steps to reproduce
- pod install
- build

### Screenshots
<img width="511" alt="Screenshot 2019-10-25 at 8 41 50 AM" src="https://user-images.githubusercontent.com/56988164/67540562-64d2a600-f703-11e9-98fe-472187ebde46.png">

### Device info

**Device**: Mac Book Pro

**iOS version**: 10.15

**Signal version:** Latest

**Comment by michaelkirk-signal** [comment]
We only use GitHub for reporting bugs with existing functionality, not for development support. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss getting set up for Signal developement: https://community.signalusers.org/

And be sure to read: https://github.com/signalapp/Signal-iOS/blob/master/BUILDING.md
