### ISSUE TITLE
Keyboard switches to light theme during hiding animation in dark mode

### ISSUE THREAD

**Issue by GabenGitHub** [signalapp/Signal-iOS#4297]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In dark mode when hiding the keyboard in a conversation, during the hiding animation the keyboard switches to light theme.

### Steps to reproduce
- open the keyboard
- hide the keyboard

### Screenshots
![bug](https://user-images.githubusercontent.com/50329419/68014237-3a4a9500-fc8f-11e9-9e94-fe4f937189e2.png)

### Device info
**Device**: iPhone 6s

**iOS version**: 13.2

**Signal version**: 2.45.0.29

**Comment by denver-s** [comment]
Can reproduce in version 3.1.0.13.

**Comment by GabenGitHub** [comment]
Fixed in version 3.2
