### ISSUE TITLE
Messages/pictures take too long to send and receive or don’t send at all

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#4298]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

Bug Description

Signal takes long time to send and receive messages. When I try to send messages it takes a really long time to send and to receive. Sometimes they don’t come in the right order. 

Steps to reproduce
- Type message
- Send measage

**Actual result:** 

Message doesn't send. Gives me error 400 bad request

**Expected result:**
Message should send

Device info
Device: iphone xr

iOS version: 13.2

Signal version:2.45.0.29

Debug log:

https://debuglogs.org/8884a795828442ff06ca43f9d07adfeb0155add17696539cce465f06bd17422a.zip

**Comment by Mihahn** [comment]
Can't reproduce, is this still an issue? If not, please close your issue.
