### ISSUE TITLE
Disappearing messages are visible in quotes even when expired

### ISSUE THREAD

**Issue by nitishraj** [signalapp/Signal-iOS#4299]
### Bug description
Disappearing messages do not expire when quoted. This is reproducible on iOS and Android on both or either sides

### Steps to reproduce
- Turn on Disappearing Messages (Duration Irrelevant but select 5 or 10 sec)
- Exchange messages with contact
- Turn off Disappearing Messages
- Reply to any disappearing message before the timer runs out (doesn’t matter who sent it or who replies to it) - Swipe right on the message or Select Reply to this message by long pressing the message

**Actual result:** 
The quoted message shows the expired message (to both parties) that was supposed to “Disappear”

**Expected result:** 
The quoted message should simply say “Original Message Not Found” as is the case when someone quotes a message deleted on your device

###Possible Fix:
- Disable quoting (Replying to messages) when Disappearing Mode is turned on
- Make it not so easy to turn disappearing mode off, this might only help with shorter durations though, but it’s something.
- Provide an even shorter duration (say 2 sec) if the above two are not viable?

### Screenshots
![IMG_0361](https://user-images.githubusercontent.com/1530142/68049968-3445ca00-fd0a-11e9-87a4-bc949ec887fd.jpg)

### Device info
**Device**: iPhone XR

**iOS version**: 13.2

**Signal version:** 2.45.0.29

**Comment by u32i64** [comment]
> The quoted message should simply say “Original Message Not Found” as is the case when someone quotes a message deleted on your device

IIRC an excerpt of the message is still visible in that case, even if your device has never seen that message before (e.g. you joined a group and existing members quote messages that were sent before you joined).

So this is currently expected behavior. There is a [feature request](https://community.signalusers.org/t/disappearing-messages-are-retained-i-e-leak-through-quoted-reply-previews/7891?u=u32i64) on the forum to change that.

**Comment by denver-s** [comment]
I think this is the correct and intended behavior.

**Comment by Necior** [comment]
I've just had a case when this was an unexpected behavior.

I sent a secret passphrase to non-technical person and they quoted it asking "what's that?" before I explained.

This way the passphrase is still visible in the history.

**Details**:

1. Alice: Set disappearing message time to 1 week.
2. Alice: Send a _secret_.
3. Alice: Disable disappearing messages.
4. Bob: Quote a _secret_ asking "what's that?".
5. Alice (a second later): Explain what's the secret for.
6. Wait 1 week.
7. A _secret_ is still visible in the message (4). Neither Alice or Bob expected that.
