### ISSUE TITLE
No “missed call” lockscreen notifications

### ISSUE THREAD

**Issue by fitzgerg** [signalapp/Signal-iOS#4301]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There are no missed/unanswered call notifications on the iPhone lock screen. There are also no missed/unanswered call notifications displayed on the Signal app badge until you go into and back out of the app.

### Steps to reproduce
- Receive a Signal call from another Signal user
- Don't answer it

**Actual result:**
I received a Signal call and saw the incoming Scall notification on my phone's lock screen. I did not accept the call and the caller hung up. There was no "missed call" notification on my lock screen so if I hadn't actually been watching this happen I wouldn't have known I'd been called. I then unlocked my phone and observed that my Signal app icon had no red "1" indication badge. I opened the app and I did have a notification for the missed call in the message thread for the caller. I then came out of the app and noted that the icon badge had been updated and now had the red "1" I had originally expected to see. I have the "Show Calls in Recents" setting enabled and looking in my iPhone "recent calls" list I saw that the missed call was listed there. This behaviour is easily reproducable and happens every time. I have observed the same behaviour on various models of iPhone within my family (8, 8 Plus, XR, 11). The same thing happens if the caller explicitly ends the call before I answer or if they let the call initiation time out.

**Expected result:**
There should be a "Missed call" notification on the phone lockscreen and the Signal app badge should have a red notification for the missed call as soon as the call initiation has been terminated.

### Screenshots
No screenshot since there is nothing to see.

### Device info

Device: iPhone (iPhone12,1)
iOS Version: 13.2 (17B84)
Signal Version: 2.45.0.29 (I have confirmed the bug is also present in the 2.45.1.1 release)

### Link to debug log

https://debuglogs.org/d86559a39a8fe5dc2490d755cb200dec8c7967670a00f2c3b7ec32a1553a435f.zip

**Comment by fitzgerg** [comment]
I've retested this with the following versions and it now works as expected:

Device: iPhone (iPhone12,1)
iOS Version: 13.2.3 (17B111)
Signal Version: 3.0.3.0

I'm closing this issue since it now seems to have been resolved.

**Comment by michaelkirk-signal** [comment]
This was fixed in 3.0, thanks for following up!
