### ISSUE TITLE
Save Contact dialog buttons almost invisible

### ISSUE THREAD

**Issue by teor2345** [signalapp/Signal-iOS#4303]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The save and cancel buttons in the "Save Contact" dialog are almost invisible. They are dark grey, and the background is black.

### Steps to reproduce
- Go to a group chat user list
- Tap a user you don't have a contact for
- Save the contact

I have dark mode and some accessibility settings on. I don't know if these changes make the dialog less visible.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The save and cancel buttons in the "Save Contact" dialog are almost invisible. They are dark grey, and the background is black.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The save and cancel buttons in the "Save Contact" dialog have enough contrast with the background, so they are visible.

### Screenshots

![7532CC6D-3A98-4875-B908-3904729F491F](https://user-images.githubusercontent.com/8951843/68468770-686a3f00-0264-11ea-9c38-f1a6a30843d7.jpeg).

### Device info

**Device**: iPad Mini 4

**iOS version**: 13.2.0

**Signal version:** 2.45.0

### Link to debug log

I don't think you need the debug log for this, and I'm concerned about leaking contact details.

**Comment by michaelkirk-signal** [comment]
Thanks for reporting! This is fixed and will be released in the upcoming beta.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

Or you can sit tight and this will eventually make it's way to the app store version.
