### ISSUE TITLE
iOS Crash when taking/sending picture

### ISSUE THREAD

**Issue by givemewatermelon** [signalapp/Signal-iOS#4304]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every time I want to take a picture out of the chat window or try to send a picture via the picture browser the app first freezes and crashes finally. I have the latest build and can’t reinstall as there is no backup function either

### Steps to reproduce
- open app
- try to take a picture or open ios picture browser to send one
- crash

**Actual result:** App crashes -> home screen

**Expected result:** picture is taken and sent; selected picture from ios picture browser 
is sent

### Screenshots
no screenshots

### Device info
**Device**: Apple iPhone 7

**iOS version**: 13.2

**Signal version:** 2.45.2.0

### Link to debug log
https://debuglogs.org/7f3f5bdfc1fc29b030d754d42d0fc523524aa40f585be2534952725506e4a815.zip

[crash-log.docx](https://github.com/signalapp/Signal-iOS/files/3839903/crash-log.docx)

**Comment by thisisnotsound** [comment]
Same issue, iOS 13.2.3, XR
Reinstalled app (lost all conversation) and it worked once, from then crashes when opening gallery.

**Comment by nzbart** [comment]
This is still happening to me, several months on.

**Comment by Pikselhode** [comment]
Same issue with iPhone X. 

Deinstalled the app, lost all groups and conversations after reinstalling. 
Worked for half a day, but now the same issue occurs. 
Got the latest version of iOS and latest update of Signal.

https://debuglogs.org/05eccb6d9a487cf80fda184194041e072fd45a92d7081d46fce706b2c07a4162.zip

**Comment by iamgreen0210** [comment]
Same issue in iPhone XR.
It has been happened for few months since I use Signal :(
My iOS is 14.4.2 and the Signal app is the latest version
