### ISSUE TITLE
Draft that only contains spaces prompts a send button. This send button doesn't work.

### ISSUE THREAD

**Issue by tge-linee** [signalapp/Signal-iOS#4305]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you draft a message that only contains spaces, Signal will offer you a send button. Pressing this send button, however, doesn't send the message.

### Steps to reproduce
- open a conversation
- put one or more spaces in the New Message field
- try to press the send button

**Actual result:**
The button changes its color while being touched, the draft containing only spaces doesn't get send.

**Expected result:**
The message containing spaces should be send. Alternatively you should be informed after pressing the send button, that it is not possible to send messages containing only spaces.

### Device info

**Device**: iPhone 8

**iOS version**: 13.2.2

**Signal version:** 2.45.2.0

### Link to debug log
should be easy to reproduce

**Comment by denver-s** [comment]
Using version 3.0.0.2 the send icon does not change color and does not send the message. I think that it’s the correct way to handle empty messages.

**Comment by tomislaveric** [comment]
I was able to reproduce the issue. I've created a PR here: https://github.com/signalapp/Signal-iOS/pull/4452

I was not able to Link the Issue with the PR, maybe due insufficient permissions.
