### ISSUE TITLE
Signal doesn't display messages containing only spaces.

### ISSUE THREAD

**Issue by tge-linee** [signalapp/Signal-iOS#4306]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

See here: https://github.com/signalapp/Signal-Desktop/issues/3739

**Comment by michaelkirk-signal** [comment]
Thanks for reporting. This is being fixed on the desktop end.
