### ISSUE TITLE
"The recipient's key is not valid" errors

### ISSUE THREAD

**Issue by scriptjunkie** [signalapp/Signal-iOS#4309]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"The recipient's key is not valid" errors showing up on iOS (but not desktop) when messaging someone with a new phone who I haven't messaged in a long time. No visible way to accept the new key or forget the old.

### Steps to reproduce
- Have an old Signal contact you haven't communicated with in a long time
- They get a new phone
- You use Signal Desktop (installed since last date of communication)
- They use Signal Desktop
- You send them messages
- They receive them.
- They send you messages

**Actual result:** 
- Only your desktop shows the messages; phone give many "The recipient's key is not valid" errors

**Expected result:** 
Phone and desktop show their messages. Or you get a key changed message which you can accept.

### Device info
**Device**: iPhone 8

**iOS version**: 12.4
**Signal version:** 2.45.2.0

### Link to debug log
https://debuglogs.org/d78e376d171088f9b84c63c15d5c789bf0c8a468100a636f0e077c7d48fc9887.zip

**Comment by scriptjunkie** [comment]
Workaround found: when the remote side re-synced desktop and phone, the problem went away.

**Comment by jessmalja** [comment]
🙏𝓽𝓱𝓪𝓷𝓴𝓼 𝓼𝓸 𝓶𝓾𝓬𝓱

**Comment by michaelkirk-signal** [comment]
This should be fixed with the latest beta (version 3.0.1).

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
