### ISSUE TITLE
Feature request: option to send full resolution images and videos

### ISSUE THREAD

**Issue by MrSimmo** [signalapp/Signal-iOS#4312]
Hi,

It would be great to add the option to send full resolution images and videos across the Signal platform. Conscious this is a request in the iOS section but applies to all. 

With network performance, device storage/processing; it makes sense to negate the need to compress media using lossy mechanisms. 

Please could you add the ability to share media/images/videos at original resolution without loss?

Cheers

**Comment by Imperiopolis-Signal** [comment]
You can send full resolution images and videos by sending them as a document. From the attachment keyboard press "File" and then "Photo Library" to send your photo as a document.

**Comment by MrSimmo** [comment]
Thanks for the quick response - I wasn't aware of that so thanks. 

Would it be worth considering an option so that all photo/video sharing regardless of the method within the app to share was set to original/full resolution? It would save any confusion/misunderstanding and allow many users who aren't so tech savvy to be able to experience the ability to share originals.

**Comment by Imperiopolis-Signal** [comment]
> Would it be worth considering an option in settings, so that all photo/video sharing regardless of the method within the app to share, would set to send original/full resolution?

We generally try and keep the number of settings as small as possible, so it’s unlikely we’d take that specific approach, but there are probably things we could do to make the path to sending full size images clearer. This conversation is turning into more of a feature request, so I’d encourage you to start a thread on our [community forum](community.signalusers.org) where we generally track such things.
