### ISSUE TITLE
MEDIA DISAPPEAR AFTER UPDATED NEW SIGNAL VERSION # 3.0.1

### ISSUE THREAD

**Issue by AbroMansoor** [signalapp/Signal-iOS#4313]
Dear Signal Team,

Yesterday after launching of new update for signal App VER # 3.0.1, i also update on my iPhone 7 device, after updating on my device it took more than 30 minutes to open the app it continuously showing me that its OPTIMIZING DATA and will take few minutes which was 30 mins.

Once it open it was surprise for me that it didn't asked for my TOUCH ID option to open it directly open the interface of the app which is very alarming, 2nd on checking my conversations and its media by tapping on conversation header than to All media option, it shows nothing all data was disappear.

it says "You don't have any media in this conversation" which is very problematic i am using this app since January 2019 never deleted my media and also updated it every time on release but didn't face such issues

following is my Debug report link for your further checking.

https://debuglogs.org/d4fc76960b404e83991defe89993d8880aceb016548f1d8ab1716d0907bcdf14.zip

Also surprisingly when i am scrolling down for old messages it showing me all pictures but it taking to much time to read it out old message even when i am tapping on the conversation its took few second to open that speed is gone

Would appreciate you look into matter and help me to recover the data.

Thank you

**Comment by Imperiopolis-Signal** [comment]
We just released a 3.0.2 build to the app store that will restore your media. The screen lock issue was also resolved, but you will need to re-activate it in settings.

**Comment by AbroMansoor** [comment]
in my APP STORE said new build 3.0.2 is not appearing it is showing same old build 3.0.1 can you advise when it will show up in my App store.

**Comment by Imperiopolis-Signal** [comment]
It will take some time for this to propagate through Apple’s network. I would expect it to show up within the hour.

**Comment by AbroMansoor** [comment]
Great and waiting.

**Comment by AbroMansoor** [comment]
it has been 24 hour but unfortunately haven't receive new build update in my app store, is this a new issue, i am in very much worrying that such delay will not affect my media data

**Comment by Imperiopolis-Signal** [comment]
Unfortunately, Apple is currently experiencing an issue where app updates are not becoming available on the store. All we can do at this point is wait for Apple to resolve this distribution issue and publish our update. Your media is safe on your device and your access to it will be restored as soon as the build becomes available.

In the mean time, if you need to access your media sooner the fix is available on our beta channel. You can join the beta by following the instructions here: https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by Imperiopolis-Signal** [comment]
The build is now live on the app store.

**Comment by AbroMansoor** [comment]
YES and update thanks issue resolved, thank you.

what here i would like to share a suggestion that when will signal provide option to back up the chat, or media files as for iPHONE user we don't have such options.

but i am thankful the quick remedy for said issue.
