### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [signalapp/Signal-iOS#4314]
### Bug description
Building the Signal workspace fails with the following error.

> Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler

### Steps to reproduce
- Install dependancies
- Build Signal project

**Actual result:**
Build fails with the above error at the line `import SignalRingRTC` in the `CallService.swift` file.

**Expected result:**
Build the project successfully.

### Screenshots
<img width="1326" alt="Screenshot 2019-11-29 at 10 21 56" src="https://user-images.githubusercontent.com/2551877/69844406-1aa88b80-1292-11ea-81cc-67ea05a7c355.png">

### Device info
**Device**: Simulator

**iOS version**: -

**Signal version:** latest source

**Comment by BigDada1** [comment]
Same here :(

**Comment by tiendaik** [comment]
Same issue, waiting for solution

**Comment by Imperiopolis-Signal** [comment]
Please follow the [instructions](https://github.com/signalapp/Signal-iOS/blob/master/BUILDING.md) in our readme on building. Currently, you must use Xcode 10.x and Swift 5.0.1 to build the signal app. The project will not build under Xcode 11.

**Comment by Muhaammaad** [comment]
I have created a pull request for compiled frameworks generated with swift 5.1.3, You can check this signalapp/signal-webrtc-ios-artifacts#2
