### ISSUE TITLE
Share Sheet screen unresponsive

### ISSUE THREAD

**Issue by TempSpas** [signalapp/Signal-iOS#4316]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal's Share Sheet is unresponsive to input and scrolling within it is laggy, rendering the feature nonfunctional.

### Steps to reproduce
- Open an app that can use Signal's Share Sheet (e.g. Photos)
- Trigger Signal's Share Sheet
- Tap one of the "Recent Chats" and observe the app does not respond to the input
- Attempt to scroll on the screen and observe laggy scrolling and flickering

**Actual result:** Share Sheet functionality is broken.

**Expected result:** Tapping on the recent chats should immediately bring up Signal's message compose screen. Scrolling should be smooth and not cause flickering.

### Device info

**Device**: iPhone XR

**iOS version**: 13.2.3

**Signal version:** 3.0.2.1

### Link to debug log

[Debug log.](https://debuglogs.org/ff6923448caacee49274573a75d44c579240e579c3de2938f487818fe00b92e0.zip)

I reproduced the bug multiple times – repeatedly tapping a chat in order to trigger a share without any response from the app – so hopefully this is helpful.

**Comment by agottardo** [comment]
I am experiencing the same issue on 3.0.2.1 on an iPhone XS running iOS 13.2.3. I’d like to add that tapping repeatedly on the contact cell eventually fires the selection handler.

**Comment by esstroud** [comment]
I'm experiencing a similar issue with the share extension. When triggered, the Signal share sheet loads contacts and then crashes. 

### Device info
- iPhone 7 Plus
- Signal app v 3.0.4
- iOS v. 13.2.3

### Debug log
[Debug log](https://debuglogs.org/8070145efc3d06d8a5971b7c26e470b8a10eb79878fbbdc484062bbdca66f78f.zip
)

**Comment by denver-s** [comment]
If you are experiencing a crash, you should send a crash report.

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

> **Steps to share a crash report**
> iOS 11 & 12
> 
> Go to iOS Settings > Privacy > Analytics > Analytics Data.
> Locate and select the latest Signal-(DateTime).ips file.
> Tap Share in the top right.
> Send the email to support@signal.org.

**Comment by TempSpas** [comment]
Issue persists on iOS 13.3 and Signal v. 3.1.0.20. @agottardo is correct in that repeatedly mashing the contact will eventually work.

There's no crash involved, so the above comment isn't relevant.

**Comment by TempSpas** [comment]
Issue persists on Signal 3.2.0.10

**Comment by agottardo** [comment]
Can confirm the issue is still there on the latest version.

**Comment by TempSpas** [comment]
Issue persists on iOS 13.3.1 and Signal 3.4.0.7

**Comment by agottardo** [comment]
> Issue persists on iOS 13.3.1 and Signal 3.4.0.7

Same here.

**Comment by TempSpas** [comment]
The new app icon that came with version 3.7.0.10 is certainly pretty, but the share sheet bugs like this one still persist. I would think an issue that affects the basic functionality of a messaging app and interferes with (quite literally) everyday use would be of a higher priority than an icon redesign. Yet this ticket has been open for 4 months now with not so much as an acknowledgement from the developers. A bit of transparency would be appreciated.

**Comment by agottardo** [comment]
Problem is still here on my end too. It's kinda hard to convince the skeptics among my friends to use Signal if basic features such as this are broken.

**Comment by TempSpas** [comment]
Persists on version 3.7.1.0

**Comment by Quorum75** [comment]
Same thing here. Not working with the official release or the beta version. It’s a real pain if you want to send something. It Has been 6 months and the problem has not been solved.

**Comment by TempSpas** [comment]
> I am experiencing the same issue on 3.0.2.1 on an iPhone XS running iOS 13.2.3. I’d like to add that tapping repeatedly on the contact cell eventually fires the selection handler.

I am now experiencing this bug except tapping repeatedly does **not** work, and eventually just dismisses the share sheet.

**Comment by TempSpas** [comment]
Persists on iOS 13.4.1 and Signal 3.8.2.7. Ridiculous.

**Comment by TempSpas** [comment]
Still bugged on iOS 13.5 & Signal 3.9.0.13.

**Comment by nnnnicholas** [comment]
> 
> 
> The new app icon that came with version 3.7.0.10 is certainly pretty, but the share sheet bugs like this one still persist. I would think an issue that affects the basic functionality of a messaging app and interferes with (quite literally) everyday use would be of a higher priority than an icon redesign. Yet this ticket has been open for 4 months now with not so much as an acknowledgement from the developers. A bit of transparency would be appreciated.

This is a VERY old bug. More than a year old, if not two.

iOS 13.5 & iPhone X
