### ISSUE TITLE
Switching to new phone causes groups to appear as "New Group"

### ISSUE THREAD

**Issue by wtangofoxtrot** [signalapp/Signal-iOS#4319]
### Bug description
We switched to new devices using the existing numbers and existing groups that I we were part of now have  title of "New Group" and are missing the group photo.

**Actual result:**
- Seeing "New group" and no group photo for groups we are members of
- The new phones can only observe the group and not participate as any messages sent from the group do not get delivered to any of its members.

**Expected result:** To see the group name and photo like others users do who have not switched devices

### Steps to reproduce
- Phone type doesnt matter, we switched from 2 androids to a new android (oneplus 6t running 9) and iphone 11 (ios 13..2.3)
- upon switching we signed into the new devices using the previously registered numbers)
- Linked the iphone with signal of osx which already had my earlier chats (v1.28.0)
- upon linking my earlier chats were preserved on the desktop app, i messaged on a group chat with the desktop app on a group that was not appearing on my new device yet (no one had messaged on it since the switch)
- upon sending the message from the desktop app the group appeared on both new devices (both devices are members on the group) but now show a title of "New Group" and are missing the group photo
- have multiple groups called "new Group" now

### Screenshots
Comparison photos between signal ios and signal desktop showing the same chat:
desktop app: 
<img width="396" alt="Screen Shot 2019-12-01 at 5 18 41 PM" src="https://user-images.githubusercontent.com/15003248/69921372-14b3d580-145f-11ea-9afc-034e4847ff11.png">
signal ios app on new device:
<img width="414" alt="signal-2019-12-01-172112" src="https://user-images.githubusercontent.com/15003248/69921375-1bdae380-145f-11ea-83cd-f5bf5f7b5ec4.png">

**Comment by 211217613** [comment]
<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/7006850/70251858-5211af00-174e-11ea-8e0a-c6bddf704623.png">

**Comment by wtangofoxtrot** [comment]
Another observation, when stuck in this state I cannot participate in the group on the new device, I can only observe posts and have to participate using the desktop app. Only option currently is to leave the group and get re-aded back on.

**Comment by andyggg** [comment]
Hi,
Did you check the article “New Number or New Phone”? I’d be interested in a solution too as switching to a new iPhone will affect me as well in some time in the future...

https://support.signal.org/hc/en-us/articles/360007062012-New-Number-or-New-Phone#ios_new

**Comment by michaelkirk-signal** [comment]
Thanks for reporting. This will be addressed in the upcoming 3.1 beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

Once it's available, upon receiving a message from another group member, you'll request the latest group state and all the group details will be filled in.

**Comment by michaelkirk-signal** [comment]
In the immediate, a temporary work around would be to ask one of the group members to manually send you a group update. To do that they can temporarily edit  the group name.
