### ISSUE TITLE
iOS: Delay when entering long conversations since update to 3.0

### ISSUE THREAD

**Issue by slangangular** [signalapp/Signal-iOS#4323]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After the update to Signal 3.0 last week, I experience a long delay when entering conversation from the list of conversations. It seems to scale with how long the conversations are with the longest one taking approximately 2 seconds to load.

Moreover, there is a delay when sending a message the first time after entering a conversation. During this delay, the send button is in the state where it looks like it is being pressed (slightly darker). Subsequent messages in a given conversation are fast until I leave it and re-enter (after which the first one is slow again).

Note: I initially posted this [in the community forum](https://community.signalusers.org/t/ios-delay-when-entering-long-conversations-since-update-to-3-0/10373) where one user reported that they had the same issue.

### Steps to reproduce
- Open Signal
- Tap on a conversation to enter it
- Optional: Send a message in this conversation

**Actual result:** There is a delay when opening the conversation and when sending the first message (see description above).

**Expected result:** The conversation opens and messages are sent without noticable delay.

### Device info
Device: iPhone SE

iOS version: 13.2.3

Signal version: 3.0.2.1

### Link to debug log
https://debuglogs.org/11ebcda0bb3822db3e1e42a4701bf03affde26a7559c80f3b6e446c02054248c.zip

**Comment by patjolata** [comment]
Yes, I was the other one in the community forum who has the same problem!

I am also on iPhone SE with iOS 13.2.3 and Signal v. 3.0.2.1.

Here is the link to my debug log from today:

https://debuglogs.org/b1fa198702c6cb5ce9f07227e811887dec2f50fefe6c22eb12331ac0eb3bd58f.zip

**Comment by insideru** [comment]
Same problem here. If the person is typing, the dota animation actually plays while i wait for the conversation to open. 

Not only that, but the keyboard sometimes hangs, when sending messages the app hangs (when you touch send), basically the entire ui lags as hell. Just sometimes!

Here is my debug log:
https://debuglogs.org/0d8535892eb22b3d7618d8d1c9160fd902b1c0e12daf93fd42e2e0990edfdd8b.zip

**Comment by AbroMansoor** [comment]
for this issue i just delete the whole conversation just lost my important chats :(

**Comment by slangangular** [comment]
After updating Signal to 3.0.3.0, the problem with the delay when sending the first message in a conversation is gone. 

However, I don't think the delay when entering the conversation is gone. I don't notice any difference at least and it still feel very slow (approximately 2 seconds for the longest conversation that I have).

**Comment by michaelkirk-signal** [comment]
We're working on a change that specifically addresses a perf degradation when opening long conversations.

**Comment by slangangular** [comment]
Awesome! Thanks for the quick reaction and all the work on this project!

**Comment by Imperiopolis-Signal** [comment]
We just released a 3.0.4 build that should greatly improve this load time and bring it back to approximately what you were seeing pre 3.0. We also hope to follow up with another build soon to improve it even further.
