### ISSUE TITLE
iOS : 3D TOUCH NOT WORKING ON CONVERSATION SINCE UPDATE TO 3.0

### ISSUE THREAD

**Issue by AbroMansoor** [signalapp/Signal-iOS#4324]
Since update to VER 3.0 of Signal Ssince update to 3.0 3D touch not working not can you please check and confirm.

**Comment by Imperiopolis-Signal** [comment]
Apple has discontinued support of 3d touch (and is no longer providing it on their new devices) so we don't intend to continue to support this feature.
