### ISSUE TITLE
iPhone app crashes when OSX app is open and Mac is in sleep mode

### ISSUE THREAD

**Issue by BenSharir** [signalapp/Signal-iOS#4325]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Open app on iOS device (mine is 13.1.3)
- Open app on Mac (mine is v1.28.0 on MacOS Mojave 10.14.6)
- Send a message from either device to one of your contacts
- Put Mac on sleep mode (without exiting Signal)
- Try sending a message from iOS app
- If app didn't crash in step 5 try exiting app on iOS and open again

**Actual result:** 
App crashes on iOS

**Expected result:** 
App should not crash

### Device info

**Device**: iPhone X

**iOS version**: 13.1.3

**Signal version:** 3.0.3.0

### Link to debug log
https://debuglogs.org/95549dd0c09ddc56a19a1b58628954ecad8ea6692677a8f2ae9cbc1caf84cb0d.zip

Apparently there's no crashing bug, maybe because technically the app didn't crash completely even that when I try to go to the app's window or open the app it closes / crashes. I can still receive message notifications after the app crashes but I can't open the app to read the messages.

**Comment by michaelkirk-signal** [comment]
Version 3.0.0 includes a migration from one database to a new one, but the problem is your old one is corrupted. Unfortunately your log is filled with entries like:

```
13144:2019/12/03 20:31:18:191  YapDatabaseTransaction: Error executing 'updateAllForRowidStatement': 11 database disk image is malformed
13145:2019/12/03 20:31:18:192  YapDatabaseTransaction: Couldn't commit transaction: 11 database disk image is malformed
```

It looks like you haven't updated Signal in over a year and a half. Does that sound accurate to you?

```
2876:2019/12/04 09:28:39:599  💛 [AppVersion.m:80 -[AppVersion configure]]: firstAppVersion: 2.13.0
2877:2019/12/04 09:28:39:599  💛 [AppVersion.m:81 -[AppVersion configure]]: lastAppVersion: 2.19.7
2878:2019/12/04 09:28:39:599  💛 [AppVersion.m:82 -[AppVersion configure]]: currentAppVersion: 3.0.3 (3_0_3_0)
```

**Comment by michaelkirk-signal** [comment]
Also, it's unlikely that this is related to the state of any linked desktop device. Because the 3.0 migration is large and could take a bit of time, we choose not to do it if the app is launched in the background, which is why you see notifications. 

However, with your database being corrupted, it seems probably that the app, even if launched, at this point would be fully functional. Do you recall the last time you successfully launched Signal and saw your message history?

**Comment by BenSharir** [comment]
@michaelkirk thanks for your prompt response. 

- I definitely updated the app in less than a year and may not even had it a year ago
- My app store settings is to update all apps automatically when connected to wifi and to power
- The Signal version on my phone is 3.0.3 which is the same as the latest version on app store
- I still use the Signal app for iPhone all the time except for when I forget to exit the Signal app for desktop and computer goes to sleep

**Comment by BenSharir** [comment]
@michaelkirk-signal so my computer was completely off and signal still wouldn't open. I turned on the computer to see if it'll fix the issue and was prompted to update to a new version. The app restarted and now the iPhone app works again.

Here's the debug logs:
Mac version: https://debuglogs.org/a2e893714cdf210f7163fab9c550bd1c6b5c3f8a4fd4a982dfcf62ac23a6c010
iPhone version: https://debuglogs.org/23c33f2df46f99e655af956b005a0ec1848d36e8ed44d92b3e4610160b87bd2c.zip

**Comment by BenSharir** [comment]
Signal app for iPhone opened a few hours ago but doesn't open now. I'm starting to think it has nothing to do with the desktop app since I haven't opened the Signal app for Mac at all today...
