### ISSUE TITLE
Linking iPad to android fails

### ISSUE THREAD

**Issue by kantarjiev** [signalapp/Signal-iOS#4326]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to link iPad to android phone. Link appears to complete, but messages sent from iPad are not delivered to remote user (but do appear on phone). Remote phone gets an error “no available session for contact”. 

### Steps to reproduce
- link iPad to phone
- send message from iPad

**Actual result:** 

Messages sent from iPad aren’t delivered to remote contact.

Also: my contacts are populated from the phone, but *my* image is not populated.

**Expected result:** Messages are delivered properly.

### Device info

**Device**: iPad Pro 10.5

**iOS version**: 12.4.1

**Signal version:** 3.0.3.0

### Link to debug log

https://debuglogs.org/c109f4fcc621b963005a7a9d625580251c0d176bb4febeef8fe65c58b37a7947.zip

**Comment by michaelkirk-signal** [comment]
Can you get a debug log from the person who is seeing the “no available session for contact” error?
