### ISSUE TITLE
New iPad-App: 4-fingers swiping gesture sometimes not working

### ISSUE THREAD

**Issue by andyggg** [signalapp/Signal-iOS#4328]
# Bug description
While the screen keyboard is displayed in a chat, the 4-fingers swiping gesture for quickly switching between apps does not work with the new Signal iPad app when “enable screen security” is activated under “privacy”-settings. 

If “enable screen security” is de-activated under “privacy”-settings, the swiping gesture works as expected. 

If the screen keyboard is not shown, swiping also works as expected (even if screen security is enabled).

### Steps to reproduce
- start Signal on iPad
- make sure that **“enable screen security” is activated** under “privacy”-settings
- **Open any chat**
- **tap on the text input field** at the bottom of the chat to open the screen keyboard

**Actual result:** 
It’s not possible to use the horizontal 4-fingers swiping gesture to switch between apps currently running on the iPad while the screen keyboard is displayed

**Expected result:** 
Swiping horizontally 4-fingers across the display should switch between apps currently running on the iPad, even while keyboard is shown on display. 

### Screenshots
n/a

### Device info

**Device**: iPad Air 2

**iOS version**: 13.2.3

**Signal version:** 3.0.3.0

### Link to debug log
n/a

**Comment by Dovizu** [comment]
Can confirm on iOS 13.3
