### ISSUE TITLE
Feature Request: Apple Watch app

### ISSUE THREAD

**Issue by calebhaye** [signalapp/Signal-iOS#4329]
This is a simple feature request for an Apple Watch app.  I am aware of the existing Apple Watch notification integration, and grateful for it, but I think we need a full-fledged and fully endorsed Apple Watch app.

**Comment by andyggg** [comment]
I support this idea. At least some basic functionality like reading and answering chats on the Watch would be awesome!

**Comment by Tursko** [comment]
This is for issue reporting and not feature requests. This issue should be closed.

You can contribute to the discussion here on the forums - https://community.signalusers.org/t/apple-watch-support/2823

**Comment by notDavid** [comment]
There's also a BUG here: 

When the mute switch on the side of the iPhone is enabled (which most people with an Apple Watch do because you don't want to get the same notifications on 2 devices), all calls and notifications will be forwarded to/seen as notifications/vibrations/sounds on the Apple Watch. But not for incoming Signal audio calls...

So when people call me, i always only see missing calls. Very annoying.
When i call them back, the same issue happens on the other side, and they are not aware i'm calling them either. I'd definitely call that a bug...

**Comment by fitzgerg** [comment]
> 
> 
> There's also a BUG here:
> 
> When the mute switch on the side of the iPhone is enabled (which most people with an Apple Watch do because you don't want to get the same notifications on 2 devices), all calls and notifications will be forwarded to/seen as notifications/vibrations/sounds on the Apple Watch. But not for incoming Signal audio calls...
> 
> So when people call me, i always only see missing calls. Very annoying.
> When i call them back, the same issue happens on the other side, and they are not aware i'm calling them either. I'd definitely call that a bug...

Even when this was previously reported as a bug (see https://github.com/signalapp/Signal-iOS/issues/4158) it was closed as a feature request :-(

**Comment by test-account-0** [comment]
It would be great as there is no sensible messaging app for apple watch apart from imessage.

**Comment by mkonikov** [comment]
+1 for a full featured Watch app.

**Comment by trayntab** [comment]
+1

**Comment by miobio** [comment]
Please please please!!! Add some basic Apple Watch support.

**Comment by vsinha** [comment]
The main feature I'd want out of an Apple watch app is that the WKHaptic api can provide a more gentle notification buzz on the watch. The current code uses `UINotificationFeedbackGenerator.FeedbackType.success`, which I think results in a tap-tap-buzz

https://github.com/signalapp/Signal-iOS/blob/962369b2676a10da9cf130aa27c87f7c45c325cb/Signal/src/Calls/UserInterface/Individual/IndividualCallViewController.swift#L1239 

I think with a dedicated WatchKit app, you'd be able use the [WKHapticType](https://developer.apple.com/documentation/watchkit/wkhaptictype) API which it seems like can do a handful of different responses (and possibly allow choosing which response the signal app uses for notifications, based off this [blog entry](https://www.sneakycrab.com/blog/2015/6/22/haptic-feedback-with-the-taptic-engine-in-watchkit-and-watchos-2-wkinterfacedevice-and-wkhaptic).

This is my biggest single issue with Signal and I'd love to see it addressed!

**Comment by captainfodder** [comment]
+1 for dedicated WatchKit Signal app and haptic customization

**Comment by trayntab** [comment]
.... + 100000000

**Comment by Cerberus0** [comment]
Hello everyone,

As much as I want this feature as well, I think we should first and foremost respect this project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md), which clearly state:

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org). The purpose of this issue tracker is to track bugs in the iOS client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

Please close this GitHub issue and continue the discussion on the community forum:

https://community.signalusers.org/t/apple-watch-support/2823

Thanks!

**Comment by ThatXliner** [comment]
Please reopen this. This does not exist and is still necessary functionality

**Comment by mr-utilman** [comment]
Apple watch support please
