### ISSUE TITLE
Signal iPad app contacts in no particular order

### ISSUE THREAD

**Issue by joe940** [signalapp/Signal-iOS#4330]
### Bug description

On the new iPad app - now updated to 3.0.4 - my contacts are not alphabetized as they are on the iPhone and Mac app, so I have to scroll and hunt.

### Steps to reproduce

Look at contacts in the left pane

**Actual result:** 

Contacts are in random order

**Expected result:** 

Contacts below the group of ongoing conversations at the top should be alphabetized

**Device**: 

iPad mini 2

**iOS version**:

iOS 12.4.3.

**Signal version:**

iPad Signal app 3.0.4 and all earlier versions of the new iPad app

**Comment by andyggg** [comment]
I cannot reproduce this issue on my iPad Air 2:
- the left pane shows the _list of chats_ (not the list of contacts!) in chronological order of activity (which is identical to the ordering in the iPhone).
- the _list of contacts_ appears when tapping on the pencil symbol (see upper left of left pane). This list, however, actually is in alphabetical order as wished...

Did I misunderstand something?

**Comment by joe940** [comment]
The chronological list of chats is fine on the new iPad app. Immediately underneath those in the same pane is all my other contacts who use Signal and those are not alphabetized. This is everyone in my contacts with Signal. Tapping the pencil produces a pop-over list of my Signal contacts, and that one is not only alphabetized but has A-Z headers. It doesn't matter if you hold the iPad horizontally or vertically. Same result. Whilst on the desktop app, the list of contacts underneath the chronological list is alphabetized. That help?
