### ISSUE TITLE
no audio/video calling on ipad - no call buttons, no incoming calls ringing

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#4331]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
no voice/video call features on ipad as linked device

### Steps to reproduce
- using hyphens as bullet points
install ipad version
- list the steps
link from main phone
- that reproduce the bug
attempt video calling sitting confortably with ipad in front of me
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
no calling abilities of ipad linked device. no incoming calls

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
full experience

### Device info

**Device**: iPad Air 3

**iOS version**: 13.2.3

**Signal version:** latest from appstore as of right now

**Comment by Tursko** [comment]
This is intentional. The iPad app works similarly to the desktop app, which means it doesn't have any calling ability. This is not a bug.

**Comment by mailinglists35** [comment]
if this is intentional then the design is broken and should be fixed.
I expect the ipad app to offer 1:1 features as the iphone app

**Comment by Tursko** [comment]
The design is not broken. Its just how device linking functions at this time. You can discuss the subject on the forums.

**Comment by mailinglists35** [comment]
here is an example of wrong design decision that was later silently pulled and fixed. no video and audio calling on ipad is a wrong design decision.

https://github.com/signalapp/Signal-iOS/issues/760#issuecomment-89869120

**Comment by Tursko** [comment]
What I'm trying to say is right now its just not a feature. I'm sure they are working on calling via linked devices but they simply aren't to that point yet. No where did they state that it was never coming. 

This is not an issue and should be closed. You can discuss this on the forums - https://community.signalusers.org/t/adding-voice-and-video-call-support-to-the-desktop-app/1078/28
