### ISSUE TITLE
Staging server URL failure

### ISSUE THREAD

**Issue by mingynaut** [signalapp/Signal-iOS#4335]
Staging server URL failure

On registering a previously unregistered phone number, after second entry of
PIN and clicking 'Next', fatal error is thrown

NOTE: The same steps using the production URL's are successful.
NOTE: Uploaded log file has some comments in it.

Steps to reproduce:

Unregister phone number if previously registered.
(The phone number used was registered on the production side and was 
deregistered before any attempts to use it on the staging side)

Clean Xcode and Build.
Hardware SIM Erase all content and Settings (iPhone Xr)
Run Xcode to load Signal app onto Xr SIM
From SIM running Signal.app

Enter phone number (real phone number changed in submitted log file)

Enter PIN (first time)
[FailedOnStagingServerRegisterFromScratch-Dev10-2019.txt](https://github.com/signalapp/Signal-iOS/files/3951876/FailedOnStagingServerRegisterFromScratch-Dev10-2019.txt)

Enter PIN (second time)

Actual result: 

**Application crashes** 

Fatal error: [KeyBackupService.swift:215 generateAndBackupKeys(with:)]: 
Unexpectedly surfacing a non KBS error: file 
/Users/foo/Signal-2.43.3/Signal-iOS/Pods/SignalCoreKit/SignalCoreKit/src/OWSSwiftUtils.swift, line 37

**Likely cause**:
Preceded by this failure:
Making Non-UD request: 
<TSRequest: 0x7b10001a8380> 
{ URL: v1/attestation/e0f7dee...aa18 }

"Request failed: service unavailable (503)"

Expected result: 
Application would confirm the second PIN submission, and complete registration.
Device info
Device: iDevice iPhone Xr SIM (iOS deployment target is 9.0)
iOS version: SIM 12.2
Signal version: 2.43.3

ADDITIONAL INFO:
curl -v -k -X PUT -H 'User-Agent: Signal/2.43.3 (iPhone; iOS 12.2; Scale/2.00)' -H 'Accept-Language: en;q=1' -H 'Authorization: Basic MTE5NTAzNzM4OTJiYjAwYTdlMDA6MTE5NTAzNzM4OTJiYjAwYTdlMDA6MTU3NjAxNDg0NTphMTY3MWM2ZWFlYWE4N2RhZTc1OQ==' -H 'Content-Type: application/json' --data-ascii '{"clientPublic":"mKwEY2y\/KDSPavLABO4+i90NeQwFToSLswMt2KeYH2s="}' https://api-staging.directory.signal.org/v1/attestation/e0f7dee...3aa18 

> Rest of key intentionally omitted

*   Trying 169.45.65.62...
* TCP_NODELAY set
* Connected to api-staging.directory.signal.org (169.45.65.62) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; O=Open Whisper Systems; OU=Open Whisper Systems; CN=api-staging.directory.signal.org
*  start date: Oct 31 03:30:58 2019 GMT
*  expire date: Oct 28 03:30:58 2029 GMT
*  issuer: C=US; ST=California; L=San Francisco; O=Open Whisper Systems; OU=Open Whisper Systems; CN=TextSecure
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> PUT /v1/attestation/e0f7dee...3aa18 HTTP/1.1 

> Rest of key intentionally omitted

> Host: api-staging.directory.signal.org
> Accept: */*
> User-Agent: Signal/2.43.3 (iPhone; iOS 12.2; Scale/2.00)
> Accept-Language: en;q=1
> Authorization: Basic MTE5NTAzNzM4OTJiYjAwYTdlMDA6MTE5NTAzNzM4OTJiYjAwYTdlMDA6MTU3NjAxNDg0NTphMTY3MWM2ZWFlYWE4N2RhZTc1OQ==
> Content-Type: application/json
> Content-Length: 64
> 
* upload completely sent off: 64 out of 64 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):

**Comment by QQzheng** [comment]
How did you solve it?

**Comment by KishoreKumar-Techment** [comment]
any update on this ?
