### ISSUE TITLE
Crash when trying to open image while downloading

### ISSUE THREAD

**Issue by pwallrich** [signalapp/Signal-iOS#4337]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When clicking on an image that is being downloaded, the app crashes.

### Steps to reproduce
- receive an image
- start downloading
- while downloading tap the image

**Actual result:** Crash

**Expected result:** Not Crashing, either an error alert or open an empty image view

I tried to fix the bug and traced it down to the following:

The function `buildGalleryItem` (MediaGallery.swift:line351) can't cast the TSAttachment to a TSAttachmentstream, which (given the owsFailDebug message) seems to be expected behavior.
```
func buildGalleryItem(attachment: TSAttachment, transaction: SDSAnyReadTransaction) -> MediaGalleryItem? {
        guard let attachmentStream = attachment as? TSAttachmentStream else {
            owsFailDebug("gallery doesn't yet support showing undownloaded attachments")
            return nil
        }

        guard let message = attachmentStream.fetchAlbumMessage(transaction: transaction) else {
            owsFailDebug("message was unexpectedly nil")
            return nil
        }

        let galleryItem = MediaGalleryItem(message: message, attachmentStream: attachmentStream)
        galleryItem.album = getAlbum(item: galleryItem)

        return galleryItem
    }
```

However, the MediaPageViewControllers Initialisation doesn't continue, since the MediaGalleryItem is nil (MediaPageViewController.swift:line90), therefore the initialPage doesn't get initialised.

In the viewDidLoad the MediaPageViewController then tries to get the currentImt, which is nil, but force unwraped when updating the title. 

```
   public var currentViewController: MediaDetailViewController {
        return viewControllers!.first as! MediaDetailViewController
    }

    public var currentItem: MediaGalleryItem! {
        return currentViewController.galleryItemBox.value
    }
```

What would be the desired behavior? Showing the user an alert, that the image is still downloading and can't be opened? Or displaying an empty image view in the gallery and update it, once it finished loading?

I'd like to contribute and fix the bug and I'm happy to get some feedback on the Issue here :)

**Comment by michaelkirk-signal** [comment]
Thanks for reporting this! Since we were just about to roll out a new beta, I opted to quickly fix this before releasing.

**Comment by omaarr90** [comment]
I think a better way is to disable tap gesture for Downloading Media.

in `OWSMessageBubbleView.m` `- (void)handleMediaTapGesture:(CGPoint)locationInMessageBubble`  you can check if the attachment is still downloading and return. no need to show downloading media.
