### ISSUE TITLE
Recipient's name is not displayed when sharing media contents from another app

### ISSUE THREAD

**Issue by gsbabil** [signalapp/Signal-iOS#4339]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that
      does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When sharing textual content from another app, the Signal app text edit
screen will show the target recipient's name selected (screenshot-1
below).

However, when sharing photo/video, the Signal app photo/video edit
screen wont display the target recipient's name selected (screenshot-2
below).

Thank you.

### Steps to reproduce

- Go to any app _e.g._ Reddit or iOS Photos app, and try to share a post
  or photo

- If the post is text, the Signal app, in the screen _after_ selecting
  the recipient, will display the recipient's name

- If the post is photo/video, the Signal app, in the screen _after_
  selecting the recipient, will _not_ display the recipient's name

### Actual result

Signal app does not display the recipient's name in the photo/video edit
screen when the content being shared is of type phone/video.

### Expected result 

Irrespective of the content being shared from another app to Signal, the
recipient's name should be displayed for a final review, and to avoid
sending the message/content to the wrong user.

### Screenshots

**SCREENSHOT-1 (sharing text - recipient's name is displayed)**

<img alt="signal-2019-12-16-134326" src="https://user-images.githubusercontent.com/1061108/70876063-52daf880-200c-11ea-8756-2fd98f3381df.png" height=568 width=320 />

**SCREENSHOT-2 (sharing photo - no recipient's name is displayed)**

<img alt="signal-2019-12-16-134219" src="https://user-images.githubusercontent.com/1061108/70876076-5b333380-200c-11ea-93f9-01af2d996de9.png " height=568 width=320 />

### Device info

- **Device**: iPhone SE
- **iOS version**: 13.3
- **Signal version:** 3.1.0.11 (Beta)

### Link to debug log

- N/A

**Comment by denver-s** [comment]
Cannot replicate this bug. Tried on iPhone 8 Plus, iOS 13.6.1 and Signal 3.16.0.10

**Comment by gsbabil** [comment]
The bug was reported for `Signal version: 3.1.0.11 (Beta)` and seems to be fixed in the latest `3.17.0.9`. Thanks.
