### ISSUE TITLE
Cloning the repo with submodules failed

### ISSUE THREAD

**Issue by bmin** [signalapp/Signal-iOS#4344]
Try to clone the repo: 
git clone --recurse-submodules https://github.com/signalapp/Signal-iOS

error: Server does not allow request for unadvertised object 1f40611aa55a3d613bbd9e8083088da7a347e87e
Fetched in submodule path 'Pods', but it did not contain 1f40611aa55a3d613bbd9e8083088da7a347e87e. Direct fetching of that commit failed.
make: *** [dependencies] Error

**Comment by michaelkirk-signal** [comment]
Hi - this should be fixed now.

By the way, we don't use Github for developer support. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss development. In fact there's already a thread about this responded to earlier: https://community.signalusers.org/t/i-need-help-with-the-latest-ios-src-code/10683
