### ISSUE TITLE
Signal crashes when changing orientation while typing image caption

### ISSUE THREAD

**Issue by muellermartin** [signalapp/Signal-iOS#4345]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After taking a photo via the Signal app and rotating the device back and forth while typing a caption for the image (it's enough to have the focus in the text input field) Signal crashes.

### Steps to reproduce
- take a photo from within the Signal app (e.g. photo icon in conversation list or photo icon in conversation)
- set the focus in the text field of the image caption (nothing needs to be typed in)
- change the device orientation (e.g. from portrait to landscape) and then back while having the focus in the text input field

**Actual result:** The app hangs instead of changing the orientation back and then crashes.

**Expected result:** The app should change the orientation back and allow typing the caption for the image.

### Screenshots
![signal-orientation-change-crash](https://user-images.githubusercontent.com/343302/71227288-f4996880-22de-11ea-8d8b-65daa0c0624f.gif)

### Device info

**Device**: iPhone SE

**iOS version**: 13.1.3 and 13.3 (tested both before and after Update)

**Signal version:** 3.0.6.0

### Link to debug log
https://debuglogs.org/798e609aed986b10fdba9a4a48e26cabab630b00a304c0d9f5341eb01a3e9e78.zip

The debug log is probably not useful due to the crash. I will provide the crash log via email.

**Comment by ethylmorphine** [comment]
I think it might be associated with another UI glitch. If you change orientation from vertical to horizontal with a keyboard on screen, text input box disappears for few brief moments.

**Comment by muellermartin** [comment]
I think I know what you mean: The text input for composing new messages in a conversation disappears while the rotation animation is shown. While this also happens for me, this does not induce a crash in contrast to the caption input for photos.

**Comment by muellermartin** [comment]
Just tested again with version 5.26.10.0 on same device an this issue does not appear anymore (probably fixed sometime in the past). Therefore closing this issue.
