### ISSUE TITLE
Pasted long text is invisible in text area

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4350]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Pasting a long text makes it invisible in text area, but it is possible to send.

### Steps to reproduce
- copy long text such as https://pastebin.com/wBqmvuyT
- paste into chat

**Actual result:** text is pasted but invisible.

**Expected result:** text should be visible.

### Screenshots
![image](https://user-images.githubusercontent.com/31325316/71408938-2b091780-2640-11ea-97d3-79242f32a0fe.png)

![image](https://user-images.githubusercontent.com/31325316/71408993-5429a800-2640-11ea-9bb8-acabdd99cf77.png)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 13.2.3

**Signal version:** 3.1.0.20

**Comment by azuredusk10** [comment]
I've also noticed this for a while.
For me, only the first 10 lines of the pasted text are shown in the "Compose message" box.
If I then type in a character at the end, the pasted text becomes visible.

Uploading ealf0v.mp4…

**Comment by denver-s** [comment]
This bug is still present and very annoying

**Comment by kaktusztea** [comment]
I can confirm this. Still happening at 5.23.1.1.

**Comment by Qata** [comment]
Same issue

iOS 15.1

iPhone 11 Pro
