### ISSUE TITLE
Call icon disappeared

### ISSUE THREAD

**Issue by sekizuri** [signalapp/Signal-iOS#4352]
**Running**

* iOS 13.3
* Signal 3.1.20

**Background**

Firstly, something Very strange happened. I woke up one day and my Signal iPad app was gone from my home-screen. I know I didn’t delete it... Did NSA jump into my phone and analyse my app and then delete it to get rid of traces? We will never know...

Either way, once I re-downloaded it and re-linked it to my iPhone’s Signal app (which works as-usual), the Call icon has disappeared. I click on a contact (whom can see my profile, can receive my messages, etc) but I can only write messages. I did Nothing different from when I linked the application the last time. The app has all permissions including microphone, of course,

**Question**

Where the h- is the call icon? 

Grateful for help!

**Comment by u32i64** [comment]
AFAIK, this behaves as intended. The iPad is a linked device and so (just like Signal Desktop) can't make or receive calls.

Before this, you probably had the Signal app on the iPad set up as a standalone, primary device — without linking it to a Signal app on your phone. You can still do this: on the very first intro screen (which you get when the app isn't yet set up), simply tap the *"broken chain"* icon in the top right corner.

**Comment by sekizuri** [comment]
Thanks! I’ll try but I’m almost certain I linked it to my iPhone... But, could be wrong, or perhaps I failed to do it properly and was unlinked all along.

Will try to use it unlinked!

**Comment by sekizuri** [comment]
Call icon is there now. I’ll just assume I never linked it last time. Thanks for the help. :)
