### ISSUE TITLE
Getting “No available session for contact” error

### ISSUE THREAD

**Issue by joestump** [signalapp/Signal-iOS#4353]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Getting the dreaded “No available session for contact” error with a single contact. This only happens with a single contact and that contact has iPad and iOS devices linked. 

I just changed SIMs in a foreign country and was briefly using a VPN for part of the conversation, but I’m able to message other users who do not have a conversation across multiple synced devices without issue. Mentioning these two just in case. 

Deleting message history didn’t resolve the issue for this specific contact. 

Filed a new report per request on #1939.

### Steps to reproduce

Send a message. 

**Actual result:** Get an error on every message. 

**Expected result:** No errors. 

### Screenshots

n/a

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 13.3

**Signal version:** 3.0.6.0

### Link to debug log

https://debuglogs.org/84707034d983b3aad72090dd451ed1e6d0787750f25d0be69f64251a5c81456b.zip

**Comment by jonstump** [comment]
This started happening for @joestump when I re-linked my iPad to my account for signal. All messages send and receive on my end without issue. On occasion I’ll see the sent check mark and not the received, but other than that I’m seeing no errors on my end.

**Comment by billatq** [comment]
I've gotten this too. I was able to reproduce it by clearing the data on my (iOS) phone, but not clearing data on the desktop. Clearing data on the desktop afterwards didn't help.

I was only able to get the message to go away by messaging contacts with the error, and then resetting the session if the option is provided.

Log: https://debuglogs.org/6bbfc76548c7a16e45da5d41da68fd9cb83f0664385cdd6278c782efb707dd4a.zip

(See the December one)

**Comment by rhodey** [comment]
This issue appears to be closest match to the bug I have to report. The other day I texted my friend, they say they received notification but no message. Here is the debug log from friends' iPhone:

https://debuglogs.org/a0a4beb54ea1e886d3646f321d6c770dcf26231213c77cb2d84e0088de524d03.zip

and the debug log from my iPhone:

https://debuglogs.org/f62ffea16b3a15930082f459666a5e8790912ea86d49aa8b322f9715de71121f.zip

and here is a screenshot of the experience... ![signal](https://i.imgur.com/DykfvHB.jpg)

thnx!

**Comment by michaelkirk-signal** [comment]
Hi Rhodey!

It’ll be helpful to have the utc “sent” timestamp for that “...would like to hangout” message, so we can cross reference it in the log.

Easiest way is from a desktop device - if you had a linked desktop at the time. On desktop, view the details for that message and copy and paste the timestamp.

**Comment by PieterGit** [comment]
Can confirm the issue with ios user to ios user communication. The other user uses Mac and Ipad as linked devices. I'm getting it as `Geen beschikbare sessie voor contactpersoon.` (dutch, nl) which comes from the `ERROR_MESSAGE_NO_SESSION` message. User was using Signal 3.1.1.1, so will see if it happens with upgraded Signal and relinked devices again.

**Comment by rhodey** [comment]
> Hi Rhodey! It’ll be helpful to have the utc “sent” timestamp for that “...would like to hangout” message, so we can cross reference it in the log. Easiest way is from a desktop device - if you had a linked desktop at the time. On desktop, view the details for that message and copy and paste the timestamp.
> […](#)
> On Jan 18, 2020, at 15:02, rhodey ***@***.***> wrote: ﻿ This issue appears to be closest match to the bug I have to report. The other day I texted my friend, they say they received notification but no message. Here is the debug log from friends' iPhone: https://debuglogs.org/a0a4beb54ea1e886d3646f321d6c770dcf26231213c77cb2d84e0088de524d03.zip and the debug log from my iPhone: https://debuglogs.org/f62ffea16b3a15930082f459666a5e8790912ea86d49aa8b322f9715de71121f.zip and here is a screenshot of the experience... thnx! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

sent 1/14/20 10:56 AM - East Cost North America

**Comment by rhodey** [comment]
note: I have no linked devices and I am almost certain my friend does not either.

**Comment by paskalem** [comment]
I don’t think I got that idea?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rhodey** [comment]
again,

my phone: https://debuglogs.org/84f083a97d2500892dc1d675e55f6e616afea8aa8fb95e4e85f68658f0647371.zip

a different friend's phone: https://debuglogs.org/2245271940ec495d2b322781a03902f5a21996131606176b0028d2206291ea6f

![sunshine](https://i.imgur.com/UahxwyJ.jpg)
