### ISSUE TITLE
[iPhone 11 Pro Max] Can't "share" as the contact list disappears immediately

### ISSUE THREAD

**Issue by ahepperla** [signalapp/Signal-iOS#4355]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I try and share to the Signal app, the list of contacts immediately disappears meaning it's unusable

### Steps to reproduce
- Open official Reddit app
- Tap "share" on a post
- select signal app

**Actual result:** Contact list disappears immediately

**Expected result:** Contact list should appear so I can share the link with someone/some group

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 13.3

**Signal version:** 3.1.1

**Comment by momenabdelkarim** [comment]
Do you mind screen-recording this and posting a link?

**Comment by ahepperla** [comment]
This issue was fixed when I updated from 3.1.1 to 3.2.0! But just in case this issue comes up again, here's the video: https://streamable.com/lrbq8

Sorry for the poor quality
