### ISSUE TITLE
[reproducible] Broken group state / unwillingly reappearing as ghost user in previously left group

### ISSUE THREAD

**Issue by relikd** [signalapp/Signal-iOS#4357]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Reproducible bug that leaves group state inconsistent across members / devices.
Group members that have left a group are automatically re-added without appearing in the members list of (mostly) all others. Luckily, message content (from all others) is not leaked but the re-added member is able to post new messages to that group again.

Example scenario (actually happend during my analysis):
Member A sees: A, B, D
Member B sees: A, B, C, D, E
Member C sees: A, B, C, D, E
Member D sees: A, B, D, E

In this case member C can send to all members, but not receive messages from anyone but B.
Member A, B, and D can communicate freely between each other. 
All clients send messages to a different set of members.

The problem occurs when member B leaves, followed by member C leaving. Now if member A adds member B to the group again, things start to get out of sync. Member B still has the old member list where member C was still part of. Because member B never got the leave message from C. The result is that B still sends messages to C and thereby adds C to the group with write permission. The member list is not updated on A though. So, from the perspective of A, member C is not part of the group. On the other hand, C can spam a group without seeing the response of others (in this case A).

Related Android bug: https://github.com/signalapp/Signal-Android/issues/8892
Possibly related bug: #4346

### Steps to reproduce
- Start with a group of three people: A, B, and C
- B taps on 'Leave Group'
- B does **NOT** delete the group from conversations
- B restarts the app (just in case)
- C taps on 'Leave Group'
- C does **delete** the group from conversations
- C restarts the app (probably necessary as the group is not updated otherwise)
- (*Optional:* A adds member D to the group)
- A adds member B to the group
- B sends a message to the group (which sends a re-add to group message to C)

**Actual result:**

Member lists are as follows:
A: A,B,(D)
B: A,B,C,(D)
C: A,B,C,(D)

Member C can still send messages to a group s/he shouldn't be part of anymore. Further, members that were added (D) when neither B nor C were part of the group are passed down to B and C as well. Therefore, newly added members are leaked to C without the knowledge of A.

- C can read all messages from B but no messages from A
- C can send messages to A and B
- A cannot write to C (and doesn't even know C can write to the group)

The signal group update that is transmitted to B contains the current member list.  B does not delete any member that is already stored on the device. B only adds new members to the own member list (and thereby keeping C as if s/he is still a member).

A forced group update – for example by editing the group title – would cause all other members to add C to their lists. Again, only adding new members but not deleting existing members that were not part of the list (expected behavior!). 
Furthermore, if member X has knowledge about additional members that no one else knows about, they will be silently ignored. The device will not respond with a "oh by the way there are even more members you don't know about" (probably by design?).

The reason for this bug is that the local copy of the member list is reused when you have been re-added to that group. Member list is updated but does not delete surplus members (that have left already).

**Expected result:** 

The local group state / member list should be deleted once a person leaves a group. Or at least once a person is re-added to a group it has left earlier. The first group update message when entering a group should be a forced overwrite of the old status.

### Device info

**Device**: iPhone SE

**iOS version**: 13.2.3

**Signal version:** 3.1.1.1

### Link to debug log
N/A

**Comment by muellermartin** [comment]
Why was this closed?

**Comment by relikd** [comment]
Still waiting for a response. 
Is this issue fixed?
Are you working on it?
Or is it silently ignored?

**Comment by michaelkirk-signal** [comment]
This was fixed in a67e2b7 which recently shipped in the 3.3.0 release.

**Comment by papimla** [comment]
Could it be that this fix was [not applied for android](https://community.signalusers.org/t/receiving-messages-from-one-member-of-a-group-i-left-months-ago/14282/13) ?
