### ISSUE TITLE
Signal constantly crashing

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-iOS#4358]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is constantly crashing and making my iPhone unusable. The dialog "Signal crashed. Do you want to submit a bug report?" opens up every second and I can't dismiss it. Signal (and my phone in general) is unusable like that.

### Steps to reproduce
I have no idea.
Edit: After using Signal Desktop (writing, sending stickers, ...), Signal iOS crashes constantly. I can neither dismiss the dialog nor file a bug report, my phone is unusable like that. Only restarting helps.
Edit2: Signal is working fine again after restarting. I have no idea where the problem is, but there was a problem for sure and it happened a few times until now.

### Device info
iPhone 7
13.3.1 beta
3.2.0.8

**Comment by denver-s** [comment]
Steps to share a crash report
iOS 11 & 12

1. Go to iOS Settings > Privacy > Analytics > Analytics Data.
2. Locate and select the latest Signal-(DateTime).ips file.
3. Tap Share in the top right.
4. Send the email to support@signal.org.

**Comment by Mihahn** [comment]
> Steps to share a crash report
> iOS 11 & 12
> 
> 1. Go to iOS Settings > Privacy > Analytics > Analytics Data.
> 2. Locate and select the latest Signal-(DateTime).ips file.
> 3. Tap Share in the top right.
> 4. Send the email to [support@signal.org](mailto:support@signal.org).

I already did.

**Comment by tmace85** [comment]
Hi Guys,

i have a similar issue. every time I send a picture Signal crashes. I can open it right a way and i get no crash report. 

**Steps to reproduce**

Open signal
Go to a chat
Press the + 
Choose a picture 
Send it 

Device info

iPhone XR
iOS 13.3
Signal Version 3.1.1.1

I will send a crashreport right a way.

If you need any further details, please let me know

Cheers tim

**Comment by Mihahn** [comment]
It's still happening on 3.2.0.10. I guess there's a relation between using Signal Desktop (Mac) and Signal iOS. After using Signal Desktop (writing, sending stickers, ...) it crashes constantly on my iPhone. Only restarting the iPhone helps, because the dialog reappears every second and I can neither dismiss it nor file a bug report like that.

**Comment by dw2013** [comment]
Same issue as tmace, but different device and latest version.

iPhone 8
iOS 13.3
Signal version 3.2.0.10

Steps to reproduce

Open signal
Go to a chat
Press the +
Choose a picture

Crashes are very consistent.

**Comment by NiklasBr** [comment]
Make a backup of your data and delete the app, then import the data again. Isn't that the best solution @moxie-signal? ;)
