### ISSUE TITLE
Error occurred while installing the pod.

### ISSUE THREAD

**Issue by sandip-jiniguru** [signalapp/Signal-iOS#4361]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Give an error when installing the pod.

**Terminal Error:** 

[!] Error installing SignalMetadataKit
[!] Failed to download 'SignalMetadataKit': [!] /usr/bin/git clone git@github.com:signalapp/SignalMetadataKit /var/folders/bg/1ry7dq6x669gjqz8vt184h180000gn/T/d20200116-14385-mmb2vr --template= --single-branch --depth 1

Cloning into '/var/folders/bg/1ry7dq6x669gjqz8vt184h180000gn/T/d20200116-14385-mmb2vr'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Imperiopolis-Signal** [comment]
Try using the `release/3.3.0` branch – this should be resolved.
