### ISSUE TITLE
"Received message not synchronized": Receiving a lot of push notifications without receiving any messages 

### ISSUE THREAD

**Issue by amarildolucas** [signalapp/Signal-iOS#4363]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After adding a new contact that I started a conversation, even without sending me a message, Signal doesn't stop to send me push notifications.

### Steps to reproduce
- Add a new contact
- Starts a conversation

**Actual result:** Receiving notification without the contact sending me any message. Push notification shows the message "Received message not synchronized".

**Expected result:** Not receive a notification without receiving any message from a contact.

### Screenshots
![IMG_9070](https://user-images.githubusercontent.com/675211/72989400-f322fa80-3dcc-11ea-8234-1a46fd9f662c.PNG)

### Device info
**Device**: iPhone 6
**iOS version**: 12.4.4
**Signal version:** 3.1.1.1

**Comment by michaelkirk-signal** [comment]
Can you please include a debug log URL?

Signal > Settings > Advanced > Submit Debug Log then copy the URL our way.

Also, could you ask for a debug log URL from the contact who sent those messages?

**Comment by amarildolucas** [comment]
I can provide my logs, the other I'm not so sure, but I'll try and back to this issue. Also, the number of notifications continuously appears on my phone without stopping.

[72ce4e6ca63e5ebb4592b4a14fc56690e7012095cce3dbd39a51a1028083e472.zip](https://github.com/signalapp/Signal-iOS/files/4104657/72ce4e6ca63e5ebb4592b4a14fc56690e7012095cce3dbd39a51a1028083e472.zip)

**Comment by michaelkirk-signal** [comment]
If you open that conversation in Signal, then tap on one of the affected messages, you should be able to reset your cryptographic session with that contact. You won't recover any of the messages which were undecryptable, but going forward you should again be able to send/receive messages with this person.

**Comment by amarildolucas** [comment]
I did it to all messages yesterday, but they don't stop. Touched in "Restore Session" and they send the same message on current Conversation: "Received message not synchronized", Restore Session. And I did it again and again...
