### ISSUE TITLE
Feature Request: Ability to change background image

### ISSUE THREAD

**Issue by torbsch** [signalapp/Signal-iOS#4369]
Would be nice to change the background to a custom background image.

**Comment by Cerberus0** [comment]
From this project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md):

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the iOS client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

I suggest closing this issue and continuing the discussion on the community forum: 

* https://community.signalusers.org/t/wallpaper-custom-background-for-chats/2975

You can easily join the forum with your existing GitHub account.

**Comment by torbsch** [comment]
Fair enough. :-)
