### ISSUE TITLE
Build problem com.apple.developer.pushkit.unrestricted-voip

### ISSUE THREAD

**Issue by donik** [signalapp/Signal-iOS#4371]
Automatic signing is unable to resolve an issue with the "Signal-iOS" target's entitlements. Automatic signing can't add the **com.apple.developer.pushkit.unrestricted-voip** entitlement to your provisioning profile. Switch to manual signing and resolve the issue by downloading a matching provisioning profile from the developer website. Alternatively, to continue using automatic signing, remove this entitlement from your entitlements file and its associated functionality from your code.

**Comment by u32i64** [comment]
Note that this issue tracker is only for bug reports, not development support, as indicated in [CONTRIBUTING.md](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md). You should use the [community forum](https://community.signalusers.org/) instead. Note that your question regarding this build issue (whatever it might be) is probably already answered [in this thread](https://community.signalusers.org/t/capability-com-apple-developer-pushkit-unrestricted-voip/11519/2?u=u32i64).

**Comment by Asylzatwww** [comment]
com.apple.developer.pushkit.unrestricted-voip it is a parameter in file "Signal-AppStore.entitlements" i just deleted, not sure if it was right
