### ISSUE TITLE
Issue when linking a second device

### ISSUE THREAD

**Issue by KaiHicks** [signalapp/Signal-iOS#4372]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to link my ipad (ipados13.3 | signal 3.3.0.6) and my iphone (ios 13.3 | signal 3.3.0.6) to the same signal account. When I attempt to sign in on my ipad, it requires me to re-register my phone number which signs me out on my iphone.

### Steps to reproduce
- Install signal on iphone and sign in
- Install signal on an ipad with imessage set up with the same number as the iphone (I do not know if this is required but I have no way to test is it is)
- Set up signal on the ipad with the same account

**Actual result:** The iphone is no longer registered. 

**Expected result:** I am able to use signal on my iphone and my ipad the same way I can use it on my laptop and desktops. 

### Screenshots

![iphone](https://user-images.githubusercontent.com/11860169/73810350-1ebdc180-478b-11ea-9b8a-754d0dcac2ef.png)
Using iphone after registering ipad
![ipad](https://user-images.githubusercontent.com/11860169/73810351-1feeee80-478b-11ea-8de8-060ab854bba9.png)
Using ipad after registering iphone

### Device info

**Device**: Iphone XR

**iOS version**: 13.3

**Signal version:** 3.3.0.6

**Device**: Ipad Air 3rd Generation

**ipadOS version**: 13.3

**Signal version:** 3.3.0.6

### Link to debug log

iphone log: https://debuglogs.org/c95ab5e828568b3621fefce3bae8587e0b79a1bd4c6b9cea7cbad7699d7f87bf.zip

ipad log: https://debuglogs.org/55a8dc9317b4c4509007de42b79fa228d504f6dcf91f9c71dbee84c07cdae028.zip

**Comment by patjolata** [comment]
@KaiHicks 

You probably registered the iPad with your phone number and then the iPhone will get unregistered because you can only have one device registered with one phone number. To properly link the iPad you should follow the steps described on this website (it's the Signal support site):

https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices#link_ipad
