### ISSUE TITLE
Signal-iOS does not preview heic files correctly

### ISSUE THREAD

**Issue by skunert** [signalapp/Signal-iOS#4374]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving image files from friends I sometimes do not see the image. I am mostly seeing this bug with friends who use a Galaxy S10 with heic files. Other image types render correctly. 

### Steps to reproduce
- On android phone, select heic file from gallery
- Send with signal to ios contact

**Actual result:** Image preview is not rendered inline. Downloading the image and viewing it in another app works fine.

**Expected result:** Image is shown in chat
### Screenshots
![IMG_0819](https://user-images.githubusercontent.com/5718005/74087114-a5271b80-4a89-11ea-830e-a2078c5c9e4f.jpg)

### Device info

**Device**: iPhone XS

**iOS version**: 13.3.1

**Signal version:** 3.4.1.1

### Link to debug log

https://debuglogs.org/49d3e655d0a6f58e24b1289caa59913fd34c083826fef0d63f139f29284a7901.zip

**Comment by u32i64** [comment]
This should be closed as https://github.com/signalapp/Signal-Android/commit/47128338534482a7a92610b5ec6c690925727be1 was merged?

**Comment by iMonZ** [comment]
New issue:

HEIC files now automatically converted to PNG even if they are uploaded as files!
