### ISSUE TITLE
JPEGs from All Media saving as PNGs with incorrect creation time

### ISSUE THREAD

**Issue by zigg** [signalapp/Signal-iOS#4375]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
JPEGs from All Media now saving as PNG image without metadata

### Steps to reproduce
- Open All Media view for a conversation
- Find a piece of media that was originally a JPEG photo
- Tap share icon
- Tap Save to Files

**Actual result:** The file save dialog appears, but the filename is "PNG image". Saving the file saves it as a PNG with the current date and time as creation time.

**Expected result:** As in prior releases (3.3.x?), JPEG images should save as JPEG format, named "signal-yyyy-mm-dd-hhmmss.jpeg" and their creation time should match the date displayed on the media view.

### Device info

**Device**: iPhone 6S Plus

**iOS version**: 13.3.1

**Signal version:** 3.4.1.1

### Link to debug log
https://debuglogs.org/be00042e95f268fdfa1f932ac9468511875b269b09c6df819ff0da16faa69449.zip

Important note on debug log: there's a lot of "media file missing" going on. The missing media is from the month _after_ the JPEGs I'm having trouble saving correctly; I'm scrolling through those to get to the month I'm trying to start saving. I'd previously gone through and saved those one at a time. They're 50% missing now, for some reason—I don't recall if I'd purged them and maybe that failed to complete? Regardless, not the thrust of this bug.

**Comment by zigg** [comment]
Still a problem in 3.6.1.4.

**Comment by mattieb** [comment]
Still a problem in 5.32.0.13. Still unclear what I can do to help.

**Comment by zigg** [comment]
Still a problem in 5.32.0.13.

**Comment by 2085861190** [comment]
This is very much still an issue, thank you.

**Comment by 2085861190** [comment]
@zigg not sure if my comment is enough to reopen this issue.

**Comment by NiklasBr** [comment]
@stale please reopen

**Comment by mattieb** [comment]
Just for the record, I can't reopen this either. I got tired of repeatedly saying what version I was using; it's clear it's not going to be fixed.

**Comment by NiklasBr** [comment]
Ping @jrose-signal, perhaps you can assist?
