### ISSUE TITLE
Frequent crashes when sending a photo

### ISSUE THREAD

**Issue by irlcatgirl** [signalapp/Signal-iOS#4376]
I’ll prefix this by saying this mostly happens with screenshots but sometimes with photos. Send a photo to a contact, then hit back on the chat and open a different chat with a different user and send a different photo. With any luck the app will crash (you might need to try a few times).

I use Signal on the iPhone XR 128GB on AT&T.

Debug logs:

https://debuglogs.org/befb2b202e1bbea90e40f6544a8191ee9834954840a5311fdc6009ee839b4c14.zip

**Comment by dhotopp** [comment]
- [x] I have searched open and closed issues for duplicates
	Reference: Frequent crashes when sending a photo #4376
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic
----------------------------------------
### Bug description
I'm having a similar issue and is very repeatable.  The issue only seems to occur when using a Share to Signal function.  It takes multiple taps to select a contact and once selected, app will close at random times whether typing a new message or just sitting idle for a few seconds. It seems to close more frequently when entering a new message.  This is not an issue when attaching a photo and typing a message from the app directly.

### Steps to reproduce
- Share a photo from iPhone Photos app or from Google Photos (I haven't tried sharing from any other apps).  
- Select Signal.
- Unlock Signal (I use Face ID).
- Attempt to select a contact.
- Tap multiple times and eventually, it will get selected.
- Either wait or start typing a new message.

**Actual result:** After waiting a few seconds or while typing, Signal closes.
**Expected result:** New message can be typed and sent along with photo.

### Screenshots
[SignalBugWhenSendingPhotos.zip](https://github.com/signalapp/Signal-iOS/files/4208807/SignalBugWhenSendingPhotos.zip)

### Device info
**Device**: iPhone XR 64G
**iOS version**: 13.3.1
**Signal version:** 3.4.3.1

### Link to debug log
https://debuglogs.org/44d9da23f58e3002964379cb9ff51084d4acb7ded405eb41de951d1b6306caad.zip

**Comment by benmayne** [comment]
Submitting on behalf of a friend of mine: 

Similar experience, when sending a photo (starting with the plus icon at the bottom left of a signal window), about 1/5 times it closes the app. 

## Device info
Device: iPhone 7
iOS version: 13.3.1

## Link to debug log:
https://debuglogs.org/b0e36c27cd8396a5ff5fd44f8370c82ab61da73717fd25b75978ace4181bca51.zip

**Comment by irlcatgirl** [comment]
I wish we’d see developer acknowledgement. At least several users are submitting debug logs 😶😶😶

**Comment by glward** [comment]
Seeing this as well.

Device: iPhone 11 (SIM-free) and iPad Pro 11”
iOS version: 13.3.1
iPadOS version: 13.4b3

Debug log: https://debuglogs.org/2ef6dd677a1885cf01aaca30fa6d0aa154b15d8b5ee5e48d6866a961aa1c6f98.zip

FWIW, I have a fairly large photo library (15000+ photos, around 50 GB) — I wonder if large libraries are the issue, perhaps?

**Comment by irlcatgirl** [comment]
I use disappearing messages with everyone and have this issue. I only have 165.7MB of photos however. Could iCloud photos play into this issue?

Cordially,
Nathaniel Suchy (they/them)

**Comment by wtangofoxtrot** [comment]
Happening repeatedly to me after I import photos and videos from my camera to my iPhone. The crash happens when I hit the + and I see pixelated placeholders for the new content in my library and then it crashes. 

Device iPhone 11 

https://debuglogs.org/99c40b10f0915b1606e02c10a9214b031d15f9cf8a95b67c72af407a499d9db6.zip

**Comment by benmayne** [comment]
Got another debug log on this: https://debuglogs.org/e2e5f0f33a5bd668944cbcbfdaae5e4c7c2b9ded3fd0af94b466b4c8aab55599.zip
