### ISSUE TITLE
Cannot share Safari full page pdf to Signal

### ISSUE THREAD

**Issue by jonathanou** [signalapp/Signal-iOS#4377]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After taking a full page pdf in Safari, when trying to share the file to Signal, there is an error:  `Cannot load representation of type public.file-url`.

### Steps to reproduce
- Take a full page pdf in Safari (see [here for instructions](https://www.macrumors.com/how-to/save-a-safari-web-page-a-pdf-ios/))
- Tap the Share icon.
- Select Signal icon.

**Actual result:** I get an error message: `Cannot load representation of type public.file-url`.

**Expected result:** I expect to be able to select my Signal contacts to share the file.

### Screenshots
<img width="375" alt="signal-2020-02-10-142908" src="https://user-images.githubusercontent.com/1291962/74126672-86549080-4c13-11ea-8332-f643034759a4.png">

### Device info
**Device**: iPhone 6S

**iOS version**: 13.3.1

**Signal version:** 3.4.2.1

### Link to debug log
https://debuglogs.org/fce1c9b804c982a1956e0fbc51e589b077e1b1143b5001db12bb2e8c2e3bc801.zip

**Comment by denver-s** [comment]
Might be related to #4321

**Comment by denver-s** [comment]
It has been fixed.
