### ISSUE TITLE
Push notification Xcode 11.3.1

### ISSUE THREAD

**Issue by miiip** [signalapp/Signal-iOS#4379]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Don't receive push notification when app is distributed Ad Hoc from Xcode 11.3.1. Push notifications work when app is distributed Ad Hoc from Xcode 10.3. The only difference is that Xcode 11.3.1 signs the code with Apple Distribution Certificate and Xcode 10.3 signs the code with iPhone Distrbution Certificate.
### Steps to reproduce
- Install Xcode 11.3.1
- Generate Apple Distribution and Dev Certificates 
- Archive 
- Distribute through Ad Hoc

**Actual result:** Push notifications don't appear 

**Expected result:** To have a notifications when a message is received

### Device info
**Device**: iPhone XS

**iOS version**: 13.1.3

**Signal version:** 3.2.0.12

I've already ask on StackOverflow:
https://stackoverflow.com/questions/60157101/push-notifications-dont-work-xcode-11-3-1/60158223?noredirect=1#comment106412205_60158223

I use Signal 2.92 Server. On Android push notifications work.

**Comment by michaelkirk-signal** [comment]
We don't use GitHub for developer support, only for bugs with the client we distribute. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss development help: https://community.signalusers.org/
