### ISSUE TITLE
Alphanumeric PIN can't be pasted in, and only numberpad appears, making it impossible to login

### ISSUE THREAD

**Issue by PencilNotPen** [signalapp/Signal-iOS#4380]
- [. ] I have searched open and closed issues for duplicates
- [. ] I am submitting a bug report for existing functionality that does not work as intended
- [. ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I set an alphanumeric PIN to protect my account, it included letters numbers and symbols. The app accepted it and set up correctly. I then updated my phone and reinstalled the signal app. When asked for my PIN, I attempted to paste it in from various sources, but only one or two digits appear in the entry field. I then went to type it in manually, only to realise that the app only brings up the numeric keypad for PIN entry, despite accepting alphanumeric PINs being set. These two things together make it essentially impossible to regain access to the app.

### Steps to reproduce
- set alphanumeric PIN
- reinstall app to trigger login via SMS and PIN request
- attempt to paste in long/alphanumeric/pin with symbols

**Actual result:** Only a few characters appear in the field. The app interface only calls up the numeric pad preventing manual alphanumeric pin entry. 

**Expected result:** Pasting in my PIN would work, or at least I could type in the PIN manually with an alphanumeric keypad.

### Device info

**Device**: iPhone X

**iOS version**: 13.3

**Signal version:** 3.4.3

**Comment by u32i64** [comment]
By any chance, did you use the TestFlight beta version when you set up your PIN, but are now using the production version from the App Store (which AFAIK does not have the new PIN system enabled yet)? In other words, did you set up a "(Signal) PIN" (which you had to because only it can be alphanumeric) but are entering it in a field for a "Registration Lock PIN"?

If so, you could try using the TestFlight beta version instead ([How do I join Signal's beta?](https://support.signal.org/hc/en-us/articles/360007318471)).

**Comment by PencilNotPen** [comment]
I haven't used the Testflight beta at all, nor when I set up the PIN, but the stock app did serve me with the alphanumeric PIN option during set up. Perhaps that's the problem? If the setup screens are done remotely, and the app doesn't cater for them? Anyway, I'll see if subscribing to the beta lets me sort it out somehow

**Comment by michaelkirk-signal** [comment]
Hey @PencilNotPen - sorry that you're not currently able to register. Could you follow up with support@signal.org and reference this github issue?

**Comment by PencilNotPen** [comment]
Done. Hopefully there’s a workaround as I’m currently locked out, and the only option now would be waiting an entire week and then re-registering, wiping all previous account details...

**Comment by vsingleton** [comment]
I am still seeing this issue on Android.  Signal version 4.66.5.

**Comment by fuerst** [comment]
Problem still exists in Signal (iOS) 5.8.1.0 at iOS 14.4.2 with iPhone SE (from 2017)

**Comment by ksauke** [comment]
I'm still unable to enter my alpha numeric pin on the main lock screen of signal.  There is no way to change to an alpha keyboard.  If my fingerprint ever failed, I'd be locked out. I just updated to the latest android version of Signal this morning and changed my pin after the upgrade (still alpha numeric).

**Comment by curkoz** [comment]
GREAT i am now locked out of my account because i choose to use the option to use a safe Alphanumeric PIN. Please fix this obvious problem!

**Comment by alexanderlanganke** [comment]
I have this problem on Android during the "verify pin" reminders.

**Comment by harmathy** [comment]
Please reopen, this is still a problem!

**Comment by alexanderlanganke** [comment]
Agreed

**Comment by kaktusztea** [comment]
@PencilNotPen: you can re-open the ticket, you are the owner.

**Comment by vsingleton** [comment]
I will try to reopen it when I get home I guess.

**Comment by rifkegribenes** [comment]
this is still an issue on ios. i set an alphanumeric pin on android (i'm using molly there) and can enter it at the reminder prompt, but on ios i only get the number keypad

**Comment by com2** [comment]
Same issue still valid but for Android 6.24.4 is still. Alphanumerical PIN is expected and a 4 character numerical PIN with accompanying numerical keyboard is presented.

**Comment by svenhakvoort** [comment]
Still an issue on android 11, also locked out can you please reopen?

**Comment by Miguel-Signal** [comment]
Hi @svenhakvoort 

Can you please email your Signal debug logs to support@signal.org and reference this Github issue number? 
To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.

**Comment by amarder** [comment]
This is happening to me on Signal 6.35.5 on Android 14.

**Comment by Miguel-Signal** [comment]
@amarder Could you please report this on the Android repo? 

Thank you!
