### ISSUE TITLE
How do you add more sticker packs?

### ISSUE THREAD

**Issue by winteriscariot** [signalapp/Signal-iOS#4381]
It's not immediately apparent to me how this is done. In a message, I can click the sticker icon, and it brings up a panel with the 2 pre-installed sticker packs, but no UI element or instructions on how to add more:

![signal-2020-02-11-115739](https://user-images.githubusercontent.com/49098280/74264680-b0b35600-4cc6-11ea-8606-5a2789b9c686.png)

Considering there was a recent blog post extolling the "over five thousand sticker packs" that have been uploaded, Signal has not made it clear how one is to access these.

**Comment by winteriscariot** [comment]
Okay so [on the blog post I was referring to](https://signal.org/blog/swoon/), I realized that clicking the links took me to a signal.art/addsticker/ website that then launches Signal and installs the packs.

This is not made clear, AT ALL, anywhere in Signal or even on the website. Even when I go to https://signal.art , there's literally no instructions on where to go to find sticker packs.

Is there a central hub for this? Going to https://signal.art/addstickers/ takes me to a blank sticker pack that seems to do nothing.

**Comment by Sgn-32** [comment]
First support you can find: https://support.signal.org/hc/en-us/articles/360031836512-Stickers

Also you can use the community: https://community.signalusers.org/
There is also a thread about stickers:
https://community.signalusers.org/t/sticker-pack-collection-thread-makeprivacystick/

For the community you can additional login with your github login.

Hint: Github is only for reporting issues.

**Comment by winteriscariot** [comment]
> Hint: Github is only for reporting issues.

This is an issue. It's a UX issue. There's little to no information within Signal itself on how and where to get sticker packs.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by michaelkirk-signal** [comment]
We don't track feature requests (UX or otherwise) on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss this: https://community.signalusers.org/
