### ISSUE TITLE
Crash when trying to add photo or other attachment on iPad with ipad OS 13.3.1

### ISSUE THREAD

**Issue by thelarsh** [signalapp/Signal-iOS#4388]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to add a photo, gif or other attachment the Signal app crashes

### Steps to reproduce
- press the plus sign in front of new message line
- Wait a second or two in the selection screen
- Crash

**Actual result:** Crash !

**Expected result:** Being able to attach a photo, gif or other attachment

### Device info

**Device**: iPad Pro (9.7 inch)

**iOS version**: 13.3.1

**Signal version:** 3.4.3.1

### Link to debug log

https://debuglogs.org/842c7aa4476a3e183fb6a4e79a2d94b4c0ca1d3ef372c57183098eafbd1e60ae.zip

**Comment by michaelkirk-signal** [comment]
Can you check for an include any crash logs from your device?

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by thelarsh** [comment]
﻿
Hi Michael,

It doesn't produce crashlogs with the name and  location suggested in the link.

Best regards,
Lars

**Comment by thelarsh** [comment]
Hi Michael,

There aren't any crashlogs...

Best regards,
Lars Hameeteman

Verstuurd vanaf mijn iPhone

**Comment by Macnerdy** [comment]
I have noticed the same issue, on iPadOS 13.3 and 13.4! It works on iOS though (iPhone).

**Comment by jun3838** [comment]
Similar issue here

### Bug description
When trying to add a photo, or take a photo in-app
(I can only send a photo as file as of now)

### Steps to reproduce
- Sending a photo (not as file), it crashes during the preview phase
- Sending a photo with a camera (inside signal app), it crashes after the photo was taken

### Actual result
App crashes!
I try to screen record while reproducing the issue, screen record stop once Signal crashes

### Expected result
Should be able to send photo (not as file)

### Screenshots

### Device info
**Device:** iPhone 6s Plus (iPhone8,2)

**iOS version:** 13.3.1

**Signal version:** 3.7.1.0 

### Link to debug log
https://debuglogs.org/66b387c5fd95f4156009c89bf59b8e2ecb9f5431d39510c067198dd91e34e624.zip

**Comment by martinderm** [comment]
Now (the last two releases in the App Store) crash right after tapping on the app icon before even the app appears.

iPad Pro 9.7“; iPad OS 14.1

**Comment by martinderm** [comment]
Version 3.20.1 checking in, not working on iPad Pro gen 1,  9“

**Comment by Enteleform** [comment]
same issue here:
iPad Pro 12.9 3rd Gen
iPad OS 14.4

**Comment by martinderm** [comment]
The issue is still there, iPad Pro 1st gen 9.7"
