### ISSUE TITLE
Calls not connecting, drop at first glance

### ISSUE THREAD

**Issue by cetzosu** [signalapp/Signal-iOS#4389]
Every time I try to make/receive a phone call, the call doesn't get trough. I only get missed call notification. And the other participant the same when I try to call. His other Signal's calls work fine. Only between us is the problem. The other phone is an android. And mine is an iPhone. 
https://debuglogs.org/b44de636b5d726b40fd8746dbf512d20d51cd52ea0b4ebb71b51c12572865593.zip

**Comment by michaelkirk-signal** [comment]
We've made some improvements to call connectivity in the 3.6 release, which is currently in beta.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

Make sure both you and the other person are running 3.6 or newer (or the latest Android release).

If you still have issues, please get a debug log from both parties and let us know, as accurately as possible, the time at which you placed the call so we can track it down in the debug log.
