### ISSUE TITLE
iOS Contacts app shows Signal video icon for all phone numbers

### ISSUE THREAD

**Issue by stefanholek** [signalapp/Signal-iOS#4390]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS Contacts app shows Signal video icon for all phone numbers, not just Signal users.

### Steps to reproduce
- Install Signal 3.4.3.1 on iOS 13.3.1
- Open iOS Contacts app
- View a contact you know does NOT use Signal

**Actual result:** Contact info shows Signal video icon. Signal is also shown in call and video drop-downs.

**Expected result:** Signal is only shown for Signal users.

### Screenshots

![IMG_2413b](https://user-images.githubusercontent.com/134791/75032202-465d9b00-54a8-11ea-92d8-0219460d1896.jpg)
![IMG_2414b](https://user-images.githubusercontent.com/134791/75032210-4bbae580-54a8-11ea-9312-f018f6df3752.jpg)
![IMG_2415b](https://user-images.githubusercontent.com/134791/75032222-507f9980-54a8-11ea-95e1-109e07ac0d4b.jpg)

### Device info

**Device**: iPhone 6s

**iOS version**: 13.3.1

**Signal version:** 3.4.3.1

**Comment by michaelkirk-signal** [comment]
This is system behavior, and not something we can control. iOS doesn't know which of your contacts has Signal installed.

**Comment by stefanholek** [comment]
Well, OK.

This is useless though, and I hope you agree!

Is there truly nothing you can do? I would prefer Signal not showing up in Contacts at all rather than for everyone.

(Contacts does know who has FaceTime, but I guess that's Apple knowing Apple users.)

**Comment by michaelkirk-signal** [comment]
Truly. If you have any other voip apps that use callkit they will also show up for all contacts.
