### ISSUE TITLE
[BUG] Sharing in landscape mode

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-iOS#4392]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to share a link/an image on a linked iPad (same problem on iPhone) the layout glitches and I can't open the keyboard.

<img width="1024" alt="signal-2020-02-24-182328" src="https://user-images.githubusercontent.com/3447340/75175624-ff370a80-5732-11ea-8529-3f93d5d82f39.png">

The issue may be related to #4391 .
### Steps to reproduce
Scenario A (link)
- Open any app (e.g. news)
- Click the share icon and select Signal
- Select a contact (often you have to hit it 3-5 times until it gets selected, see #4376 )

**Actual result:** The layout glitches and when you try to open the keyboard to add some message to your link, it doesn't come up or is off screen.

**Expected result:** The layout shouldn't glitch and a keyboard should come up.

Scenario B (photo)
- Open photos app
- Click the share icon and select Signal
- Select a contact

**Actual result:** The layout doesn't glitch, but when you try to open the keyboard to add some message to your photo, it doesn't come up or is off screen.

**Expected result:** The keyboard should come up.

### Device info
**Device**: iPhone 7
**iOS version**: 13.3.1
**Signal version:** 3.5.0.10

**Comment by TempSpas** [comment]
> Select a contact (often you have to hit it 3-5 times until it gets selected, see #4376 )

Documented with issue #4316 as well

**Comment by igorkulman** [comment]
Same problem on iPad Air 2 and probably all the iPad (which people probably mostly use in landscape).

The share button is not even visible breaking the sharing functionality completely.

![IMG_F3073364E8FD-1](https://user-images.githubusercontent.com/4746070/78356202-64daaa00-75af-11ea-8746-0845b751aab1.jpeg)

**Comment by scottcarterco** [comment]
It appears that this issue is especially persistent in Landscape mode when the keyboard option of “Shortcuts” is turned off. I wonder if it normally anchors above the shortcuts on-screen bar and when it’s disabled, it has nothing to anchor to and disappears.

**Comment by ch1phead** [comment]
Just experienced the same issue as Scenario B. More specifically I can’t even send it, before adding text.  Rotating the device to Portrait makes the edit/send bar show up again.

**Comment by ignaspa** [comment]
Same, the send button does not appear. If I try to click on where I think it is (perhaps because it is hidden) nothing happens, so it seems to truly not exist.

**Comment by scottcarterco** [comment]
It appears the missing send button issue in iPad landscape mode is fixed for me around 3.14 or newer that was released in the last week.

**Comment by IsaiahJTurner** [comment]
I am still not seeing this fixed. At least not when using Magic Keyboard

**Comment by KommX** [comment]
I think, this one is fixed.
