### ISSUE TITLE
"New message" shortcut doesn't open compose screen if app was fully closed

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4393]
If the app was e.g. force closed from the app switcher, the "New message" app icon shortcut (the same that #4288 is about) doesn't open compose screen, instead it just shows the main app screen (conversation list).

### Steps to reproduce
- Make sure Signal is fully closed (via app switcher);
- Haptic touch on Signal icon;
- Choose *New message*.

**Actual result:** Conversation list is shown.
**Expected result:** The "compose" / "choose contact to message" screen appears.

### Device info
**Device**: iPhone SE
**iOS version**: 13.4 Public beta 2
**Signal version:** 3.5.0.10

**Comment by moritzluedtke** [comment]
Still happens on an iPhone XS running iOS 14.6 using Signal 5.14.0.35

**Comment by u32i64** [comment]
This is still reproducible.

**Device:** iPhone XR
**iOS version:** 15.2.1
**Signal version:** `5.27.0.102`

**Comment by u32i64** [comment]
This is still reproducible.

Device: iPhone XR
iOS version: 15.4
Signal version: 5.34.0.8

**Comment by u32i64** [comment]
This is still reproducible.

**Device:** iPhone XR
**iOS version:** 16.0 Public Beta (20A5358a)
**Signal version:** 5.51.0.10

**Comment by u32i64** [comment]
This is still reproducible.

**Device:** iPhone XR
**iOS version:** iOS 16.2 (20C5049e) public beta + iOS 16.2 (b) (20C7750490f)
**Signal version:** 6.4.0.8

**Comment by EvanHahn-Signal** [comment]
Just reproduced this and filed a ticket in our internal tracker.

**Comment by PadraigK** [comment]
I just tested this in version `6.50.1.0` and it seems to be behaving correctly now.

**Comment by moritzluedtke** [comment]
I can confirm that on version `6.50.0.13`.
