### ISSUE TITLE
Clickable URLs are broken if message is abbreviated (aka "Tap for More")

### ISSUE THREAD

**Issue by philshem** [signalapp/Signal-iOS#4394]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Long messages in a chat are abbreviated and can be viewed by clicking "Tap for More". If the preview ends with a clickable URL, the hyperlinked URL is shortened and when clicked, goes to a link that is not intended (usually a 404)

### Steps to reproduce
- Read a long message
- Click the (truncated) link

**Actual result:** 
- Browser opens with an incorrect page

**Expected result:**
- The app knows that the URL has been truncated and although may not display the entire link, opens the full URL in the browser
- OR, more secure, the app doesn't cut the message on a URL

### Screenshots
![image](https://user-images.githubusercontent.com/4997607/75351943-37f8f000-58a9-11ea-8bf2-92694b680f4c.png)

### Device info

**Device**: iPhone SE 32GB

**iOS version**: 13.3.1

**Signal version:** 3.4.3.1

### Link to debug log

https://debuglogs.org/425b692c4780df2ee9c725d702cd8c67588c572e72e434ac84c50f93bc953ef8.zip

**Comment by denver-s** [comment]
Cannot replicate this bug. Tried on iPhone 8 Plus, iOS 13.6.1 and Signal 3.16.0.10

**Comment by StevenBlack** [comment]
I'd like to confirm this bug.

The URL is really long, and the `Read More` link truncates the URL.  When I tap the URL without expanding the message using `Read More", I get a 404 from the web server because the URL invoked is truncated.

When I expand the message by tapping `Read More` then the URL works as expected.

Signal 3.21.3.0 on  iOS 14.1, iPhone Xs Max.

I hope this helps.

![IMG_64D211A62F9C-1](https://user-images.githubusercontent.com/80144/99693236-2409a580-2a59-11eb-93f0-433b52d13888.jpg)

**Comment by jiqz** [comment]
Bug is replicable on Signal 5.26.8 on iOS 15.2.

**Comment by StevenBlack** [comment]
Hello!  I can confirm this is still a bug!  Thanks.

**Comment by StevenBlack** [comment]
More info:

Using Signal 5.29.0 21 on iPhone XS Max running iOS 15.3.1 which is latest.

**Comment by StevenBlack** [comment]
Can I make a suggestion?

Just get rid of "Read More" truncation.

It's just annoying.  Whatever reasons once existed for this probably don't exist anymore?

iOS messaging never does "Read More" truncation.  Nor does Android?

**Comment by StevenBlack** [comment]
This clear bug still persists, yes.

**Comment by max-signal** [comment]
This should be fixed by 1689aec8c6897d947f933f158c9d5a129ff9e62c. Please reopen the issue if you’re still seeing it in the latest version of the app!

**Comment by StevenBlack** [comment]
**\o/ YES!**  Thanks Max! @max-signal

**Comment by laurens94** [comment]
@max-signal it seems this issue still persists in some form:

![Image](https://github.com/user-attachments/assets/15175f01-f3c8-4231-9c6a-d9e142766bc7)

![Image](https://github.com/user-attachments/assets/b1b77d70-87d1-4c9a-9209-e681a2030ad3)

To test it, I used this url to send as Note to self:

```
https://www.booking.com/hotel/nl/bunk.en-gb.html?aid=304142&label=gen173nr-10CAEoggI46AdIM1gEaKkBiAEBmAEzuAEHyAEM2AED6AEB-AEBiAIBqAIBuAKh6bPGBsACAdICJDBmMzg0ZGIzLWJmNTMtNDFiNy1hZWE5LTE2N2RiOGFiODk0ZdgCAeACAQ&sid=5790693a9fde8be96164ad0698980bab&all_sr_blocks=322674809_229107779_0_34_0&checkin=2025-09-20&checkout=2025-09-21&dest_id=-2140479&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&highlighted_blocks=322674809_229107779_0_34_0&hpos=1&matching_block_id=322674809_229107779_0_34_0&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&sr_pri_blocks=322674809_229107779_0_34_0__15628&srepoch=1758263369&srpvid=88ec2d9f8be30512&type=total&ucfs=1&
```

**Comment by StevenBlack** [comment]
I am going to repeat my suggestion from Feb 28, 2022. Three and a half years ago.

**Just get rid of "Read More" truncation.**

It's just annoying.  Whatever reasons once existed for this probably don't exist anymore?

iOS messaging never does "Read More" truncation.  Nor does Android?

**Comment by laurens94** [comment]
I agree that this feature should be removed for normal text messages.

Automatically collapsing messages based on length can be frustrating for people who’ve put time and care into writing them. It also adds extra friction for the recipient, who now has to take an additional action before reading the message and in some cases may not even notice that the message can be expanded at all.

I guess we should continue this discussion back in the Signal Community: https://community.signalusers.org/t/remove-the-need-to-tap-read-more-for-long-messages/13688/37
