### ISSUE TITLE
Hard to leave message detail view after search

### ISSUE THREAD

**Issue by wilhelmtell** [signalapp/Signal-iOS#4398]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

There is no Back button in the message detail view when I get there following a search within a conversation. There is a Back button when I get there from a conversation. I later found a way to go back, but found a visual glitch on the next screen.

### Steps to reproduce

- Enter a conversation.
- Tap the top bar to enter the conversation detail view
- Tap Search Conversation
- Enter a search term that yields some result message
- Long-tap a result message, then tap the circled-i button at the bottom bar to enter the message detail view.

**Actual result:**

The message detail view shows up. There is no back button at the top bar; on iOS, this makes it seems as if there is no way to go back to the search results view, or to carry on a conversation, or do anything on the app other than observe the static message details. I later realized swiping right from the left edge of the screen brings me back to the search result view, albeit the view being visually deformed: the search field is shifted downwards by about its own height, and above it is now a “transparent” gap through which I can see a portion of the search result view. 

**Expected result:**

There should be a Back button on the top bar of the message detail following a search result, as there is when getting there from within a conversation rather than a search result.

### Screenshots
I’m not sure how to put a screenshot here on mobile.

### Device info

**Device**: iPhone 6

**iOS version**: iOS 12.4.5

**Signal version:** 3.5.0.12

### Link to debug log

https://debuglogs.org/25113cf8f2f77bb6da422cd6c43c35d7c5940197917b8adbceabad4ff1da24c2.zip

**Comment by Mihahn** [comment]
Can't reproduce on 3.6.0.7, there is a back button for me and going back to search is working fine, no shifting or anything else.

**Comment by michaelkirk-signal** [comment]
> Can't reproduce on 3.6.0.7, there is a back button for me and going back to search is working fine, no shifting or anything else.

This issue does not affect iOS13 builds. 

There's a fix for legacy versions of iOS in the upcoming 3.7.0 release.

**Comment by denver-s** [comment]
Cannot replicate this bug. Tried on iPhone 8 Plus, iOS 13.6.1 and Signal 3.16.0.10
