### ISSUE TITLE
Relinked Desktop instance not visible in Signal iOS

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-iOS#4404]
### Bug description
I unlinked and relinked my Desktop instance and it doesn't show up in Signal iOS. Imo this may be a security issue, too.

### Steps to reproduce
- Go to Signal / Settings / Linked Devices
- Swipe to unlink
- On Desktop: Click relink and scan the code using your mobile

**Actual result:** Desktop instance is relinked and can be used as usual - but the instance is not shown in Signal / Settings / Linked Devices.

**Expected result:** Desktop instance is relinked, can be used as usual and is visible in Signal / Settings / Linked Devices

### Device info
**Device**: iPhone 7
**iOS version**: 13.4
**Signal version:** 3.6.1.3

**Comment by the-woocash** [comment]
I do confirm a similar case. I have a different issue, so today i wenti into iOS settings and in linked devices I see my two laptops, but i cannot see my Desktop, on which I use Signal all the time, including now.
