### ISSUE TITLE
Signal iOS Does not Properly Display Images with missing/incorrect extensions

### ISSUE THREAD

**Issue by gfs** [signalapp/Signal-iOS#4406]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------
### Bug description
When I share a screenshot that has been cropped on my OnePlus 7 Pro using signal the recipients on iOS cannot view it.

### Steps to reproduce
- Create a group chat with a OnePlus device, another android device, and an iOS Device.  Take a screenshot, crop it in the default screenshot editor, and send it to the group message.

**Actual result:** Image displays properly on my end and for other android users, iOS Recipient receives an image they can't view labeled as a "bin" file
**Expected result:** iOS Recipients can also view the screenshots.

### Screenshots

![iosbug](https://user-images.githubusercontent.com/98900/76021684-8aa25f80-5eda-11ea-942b-e5ec2df4dfd8.jpg)
![androidview](https://user-images.githubusercontent.com/98900/76021088-7742c480-5ed9-11ea-8b37-5d3235595697.jpg)

### Device info

**Device:** iPhone SE
**iOS version:** 13.3.1
**Signal version:** 3.5.1.0

**Comment by gfs** [comment]
https://debuglogs.org/48e125916b77eefa7700f28c2d725ec74029572a1c97da0e82da416ecdaaf75a.zip

**Comment by tobybryans** [comment]
This stopped happening for a while, but is happening again now for me. I'm using Beta on Android to send, and my iOS non beta friend cannot receive the images, and the beta desktop client gets this:

![image](https://user-images.githubusercontent.com/2099245/96247312-e0c39f00-0fa1-11eb-8d2d-ad997951a450.png)

This only happens on screenshots and other messaging clients cope with them fine (conversations, WhatsApp).

Anything I can do to help research this one?

**Comment by gfs** [comment]
A follow up here. I think I've identified a discrepancy.  If you take a screenshot on a OnePlus phone and crop it, and then share directly from the crop menu you will not be able to share.  The workaround is to finish your crop, and then click save, and then share the saved image from your camera roll.

**Comment by gfs** [comment]
I can also repro this on Signal Desktop

Here is a sample file.  Note that the file name in Signal was `signal-2020-10-17-114550.*`  I had to rename it in order to upload it to github to `.png`.  To test it exactly how it was downloaded from signal remove the `.png` extension.
![signal-2020-10-17-114550 *](https://user-images.githubusercontent.com/98900/96351187-a96ef400-106e-11eb-83fe-363979b65480.png)

If you send this file named `signal-2020-10-17-114550.*` signal Desktop will display it as the dot type file above in @tobybryans's screenshot.  If you send it but name it `.png` it will be rendered correctly by Signal Desktop.

This appears to be a difference in how Signal Desktop, SIgnal iOS and SIgnal Android parse data types.  It appears that Signal Desktop and iOS both appear to rely on the extention being a valid one that they can see.  It doesn't appear to matter if the extension is correct.  You can see this by sharing the above image as both a `.png` and a `.jpeg` without changing their content of the file.

It would appear that OnePlus's screenshot app doesn't append an extension to the file name, which is handled fine on android but not on other platforms.

The workaround on OnePlus phones to be able to share your screenshots is to be sure to save the image to your device, which will save it named `.jpg`.

The bug here seems to be relying on file extensions instead of checking for file headers.

**Comment by ajeesh1987** [comment]
Screenshot sharing from oneplus Still an issue. Some videos are also not downloading.

**Comment by ztNFny** [comment]
Same issue here with a OnePlus 7 on sending and iPhone / Signal Desktop on the receiving side. Saving the file to gallery didn't help though.

**Comment by MathieM** [comment]
Hello there, this bug is not fixed.
Do we know if it'll be fixed in futur update ?

**Comment by ztNFny** [comment]
Still therr

**Comment by NiklasBr** [comment]
This is still relevant, stop spamming Stale-bot!

**Comment by NiklasBr** [comment]
WTF
