### ISSUE TITLE
Signal Desktop - Push Notifications Issue

### ISSUE THREAD

**Issue by stevenmical** [signalapp/Signal-iOS#4408]
### Bug description:
-Signal app for Desktop is not pushing notifications or badges when app is closed. 
-When the app is open I do receive notifications/badges as expected. 
-When the app is closed and then I open it, no backlog of notifications appears, though I do see that I have unread messages in the app window.

Signal is not open on other devices when this occurs.

### Steps to reproduce:
- ensure Signal is not open on other devices.
-ensure that Signal for Desktop is closed.
-have someone send a message to my Signal account
-[receive no notifications on the Signal Desktop app]
-open Signal Desktop

**Actual result:** 
see that there is an unread message, with no push notifications or badges

**Expected result:** 
When Signal Desktop app is closed, push notifications/badges are expected to appear.

**Device**: 
2009 Macbook Pro
OS X El Capitan 10.11.6

**Signal version:**
v1.32.1

**Comment by Cerberus0** [comment]
Hi @stevenmical,

Welcome to the Signal iOS issue tracker! Is there a reason you're posting this issue here instead of the [Signal Desktop issue tracker](https://github.com/signalapp/Signal-Desktop/issues)?

**Comment by stevenmical** [comment]
Reposting there, hadn't noticed the different issue tracker repositories.

Thanks @Cerberus0 !
