### ISSUE TITLE
Adding emoji reactions to messages containing only a link is unintuitive

### ISSUE THREAD

**Issue by lutoma** [signalapp/Signal-iOS#4410]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is difficult to add emoji quick-reactions to Signal messages that contain only a link and nothing else.

### Steps to reproduce
- Send Signal message that contains only "https://example.org"
- Long-press on the message to add a quick reaction

**Actual result:** Link context menu pops up regardless of where you tap.
**Expected result:** Optimally, the menu to add quick reactions would show up in addition to (or as part of) the link context menu. However, I'm not sure if this is possible in iOS.

Messages that contain a link and something else don't have this issue, since you can tap the non-link parts of the message to add quick reactions.

As has been pointed out in the first comment, it is possible to add quick reactions by tapping _next_ to the message, but that is very uninituitive. At least I didn't figure that out by myself, and I work with computers for a living.

### Screenshots
![2F6937AA-99E2-407C-8A67-640E57DAB2F9](https://user-images.githubusercontent.com/179393/76565697-6e3e8e00-64ab-11ea-8ae4-d8b983a8f656.jpeg)

### Device info

**Device**: iPad Air 3rd Gen / iPhone 8
**iOS version**: 13.3.1
**Signal version:** 3.6.1.4 (Testflight)

**Comment by u32i64** [comment]
It is very much possible. Just hold on the space to the side of the message bubble.

**Comment by lutoma** [comment]
@u32i64 Oh, thanks for the heads-up, I was unaware of that. I still believe it's an issue then, but one of unintuitive UX. I've adjusted the title accordingly.
