### ISSUE TITLE
Option to disable sticker suggestions

### ISSUE THREAD

**Issue by paddor** [signalapp/Signal-iOS#4411]
Please let users opt out of the sticker madness. I don’t want Signal to suggest stickers when I type a simple “👍”

**Comment by romainricard** [comment]
You could just uninstall all the stickers, so the app won't propose them as you type emojis

**Comment by paddor** [comment]
Thanks for the suggestion. I finally found where to uninstall these stickers (the icon inside the textbox). After restarting the app, I can finally type without sticker suggestions popping up.

**Comment by anuyts** [comment]
As stated on [this support page](https://support.signal.org/hc/en-us/articles/360031836512-Stickers), "Signal has a built-in list of default sticker packs that are available to all users, and we'll add more stickers over time." Indeed, I have had to uninstall a new pack today.
So are users supposed to google again and again how to uninstall new automatically installed stickers packs? I **never** want **any** sticker suggestions, this is not a complicated preference.

**Comment by paddor** [comment]
We're back to the same madness. I can't even type a simple emoji without these sticker popping up. And uninstalling them does not seem to be possible anymore.

Please add an option to disable ALL STICKERS.

**Comment by mattspew** [comment]
Why am I seeing stupid stickers again? I don't want them.

Didn't want them a year ago, and now they're back again. https://www.reddit.com/r/signal/comments/fxpptr/stop_stickeremoji_suggestions/

**Comment by jobooker** [comment]
Also had to google to find this. I had disabled Android sticker suggestions at the OS level, expecting this to be disabled. I didn't realize Signal had it's own stickers. Please consider reopening this.

**Comment by ankitsharma07** [comment]
An option to opt out fir sticker suggestions would be nice. Telegram does this.

**Comment by donkeypagoda** [comment]
This is STILL a problem with every update for me. It's been the reason that multiple people I have convinced to use Signal have stopped - they think its a kid's app with the stickers autosuggestions. Please provide an easy disable function for the grown ups in the room
