### ISSUE TITLE
'Share to Signal' does not generate previews

### ISSUE THREAD

**Issue by Merrit** [signalapp/Signal-iOS#4413]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
'Share to Signal' does not generate previews

### Steps to reproduce
- Use built-in share function from YouTube, reddit, etc
- Share target > Signal
- Choose contact
- Fullscreen compose opens with link, no preview is generated. If sent, no preview.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Link is added to a fullscreen compose, no preview generation is attempted

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Link is added to compose, preview generation should begin

### Screenshots

![1](https://user-images.githubusercontent.com/9575627/77101938-78521680-69ee-11ea-849c-07539b1c1199.png)

![2](https://user-images.githubusercontent.com/9575627/77101949-7d16ca80-69ee-11ea-9069-9a077229b72a.png)

![3](https://user-images.githubusercontent.com/9575627/77101957-7f792480-69ee-11ea-91c8-423f8ea52cc7.png)

![4](https://user-images.githubusercontent.com/9575627/77101962-81db7e80-69ee-11ea-82a7-9a451110ae95.png)

As you can see in the screenshots, if I just copy the exact same link and paste it in the normal Signal compose window it generates a preview as expected.

### Device info

**Device**: iPad 2018

**iOS version**: 13.3.1

**Signal version:** 3.6.1.4

### Link to debug log

https://debuglogs.org/f1b96f878678bd98ea0a557a8d5807ab9fadd2a1890c1e6de323dc3cee3cb0df.zip

**Comment by denver-s** [comment]
It is now possible to generate previews for any website. @Merrit can you close this now?
