### ISSUE TITLE
Feature Request: Link previews for Twitter

### ISSUE THREAD

**Issue by astubbs** [signalapp/Signal-iOS#4414]
Feature Request: Link previews for Twitter.

Currently Signal allows Link previews for several sites, including instagram, reddit, and pinterest. Twitter would be a good addition!

desktop feature request: https://github.com/signalapp/Signal-Desktop/issues/3374

**Comment by astubbs** [comment]
root feature request: https://community.signalusers.org/t/twitter-message-preview/12040

**Comment by alan-signal** [comment]
Please use the community forum only for feature requests https://community.signalusers.org/

**Comment by denver-s** [comment]
It is now possible to generate previews for any website.

**Comment by denver-s** [comment]
@astubbs can you close this now?
