### ISSUE TITLE
Video not uploading when shared from photos app

### ISSUE THREAD

**Issue by wtangofoxtrot** [signalapp/Signal-iOS#4415]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sharing video from external app leads to an infinite spinner and the video never uploads if the video is trimmed

### Steps to reproduce
- open video in some app and share with signal
- select a group to share with
- trim the video but removing the last 25% and share

**Actual result:** the video will not be shared, opening the group chat on the device shows a s spinner with no progress

**Expected result:** the video should have been uploaded

### Screenshots

![IMG_0742](https://user-images.githubusercontent.com/15003248/77461991-a9509380-6dc0-11ea-8d65-ef70ecc05c51.PNG)

### Device info

**Device**: iphone 11

**iOS version**: 13.3.1

**Signal version:**3.6.1.4

### Link to debug log
https://debuglogs.org/b1fb14039369d2b1f864ee3349a09947955b2645e85a441df874d4f9c278beb6.zip

**Comment by wtangofoxtrot** [comment]
I just experienced this issue on ios signal 3.7.0.10 running ios 13.3.1, video was shared from photos app and has been stuck on uploading for an hour. I did not trim it using the signal app this time so I dont think that matters.

logs: https://debuglogs.org/b5eaa85ddd5c086bf5550edcf27e3c8d0ac16f25f1a3bbbf908f7044c9b0b89a.zip

![IMG_A2413B09ACDA-1](https://user-images.githubusercontent.com/15003248/78409529-c2c2be00-75be-11ea-8b5f-171595d07db0.jpeg)

**Comment by wtangofoxtrot** [comment]
Still happening on iOs with 3.11.1.1, https://debuglogs.org/8a4abced1f490699172d1f8b5b77cdcbc2b5fc62c2278c09ffc589c228ad56b8.zip

**Comment by jboycha** [comment]
A year and we still don't not have a resolution I wonder if you are still using signal ? These guys are developing technology to send your video to Mars and still recruiting rocket scientist 🤣 the rocket scientist has just joined as freshman in college so it will be another 4 years to get them a resolution and probably Mark Zukerberg would have retired by that time 🤣🤣

**Comment by sa1** [comment]
https://debuglogs.org/80a2350db6f03573688af086f91dc26bbf86d686db0a63b9ad059453d0a758cc.zip

It happens even when sharing via other mediums too. Sharing bigger videos is more likely to fail. Copy pasting videos almost always succeeds. Sharing from Photos almost always fails.

**Comment by EranBoudjnah** [comment]
This one should be getting more attention. I spent so much time and energy to switch my family to Signal and because of this they're now applying pressure on me to switch back to WhatsApp. 😔

**Comment by jboycha** [comment]
> This one should be getting more attention. I spent so much time and energy to switch my family to Signal and because of this they're now applying pressure on me to switch back to WhatsApp. 😔

Most of them are back to WhatsApp Signal has been very poor in managing media upload or share. They are catching up but, most of them are back to WhatsApp so you end up just keeping the Signal App most of the screen time still goes to WhatsApp 
![image](https://user-images.githubusercontent.com/78777509/114859921-6793f000-9dfc-11eb-9d99-741bea8d4dcf.jpeg)

**Comment by sa1** [comment]
Seems fixed in 5.10 beta for me
