### ISSUE TITLE
Signal on iPad crashes after being switched into background and another app is open

### ISSUE THREAD

**Issue by weirdnik** [signalapp/Signal-iOS#4419]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal on iPad (Mini 5) crashes after being switched into background and another app is open

### Steps to reproduce
- open Signal
- do something
- press the Home button
- open another app

**Actual result:** a notification of Signal crash with an option to send bug report appears after about 30 seconds

**Expected result:** Signal works in background normally
### Device info
Device: iPad (iPad5,1)
iOS Version: 13.3.1 (17D50)
Signal Version: 3.7.0.9 

### Link to debug log
https://debuglogs.org/ae075218b24d3ddb8adc8b8b6aa0349ff479df9fd45fec08ad7efe2573488f22.zip

**Comment by 211217613** [comment]
I would almost blindly assume that this is iOS managing background tasks. iOS has issues with memory management for background tasks.

**Comment by weirdnik** [comment]
Background updates are enabled for Signal and this is the only application that crashes this way.

**Comment by weirdnik** [comment]
Same with iOS 13.4.1 on iPad, while on iPhone works as expected.

**Comment by cva** [comment]
I am having the same issue on an iPad Mini 4 running iOS 13.6. I'm currently on 3.13.2.6, but it's been happening for quite a while now.

Crash report:
[Signal-2020-07-18-211652.ips.beta.zip](https://github.com/signalapp/Signal-iOS/files/4943133/Signal-2020-07-18-211652.ips.beta.zip)
