### ISSUE TITLE
Ability to pin ‘note to self’ to top of chat

### ISSUE THREAD

**Issue by Githubuxer** [signalapp/Signal-iOS#4420]
It would be great if we could pin ‘note to self‘ to top of chat as it is easy to forget about the feature as it disappears down the list over time.

**Proposed Process**

- Swipe on selection/Note to self
- Select pin from swipe menu

**Comment by Cerberus0** [comment]
Hi @Githubuxer,

Welcome to the Signal iOS issue tracker! Please note that this project only uses GitHub to track bug reports, not feature requests, support questions, or other discussion topics:

* https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#issues

Those can be posted on the [community forum](https://community.signalusers.org/), where you can easily sign up / log in with your existing GitHub account. Please use the provided [bug report template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md) if you decide to report issues here in the future. Thanks!
