### ISSUE TITLE
Hang on launch

### ISSUE THREAD

**Issue by josharian** [signalapp/Signal-iOS#4421]
Signal recently started hanging on launch for me.

Possibly a red herring, but it appears to have started right around the time when I got an “update available” alert.

I have a tenuous internet connection, so if anything on launch is blocking on a request failing or succeeding, that would explain it. 

I’m happy to provide logs etc to debug. Just let me know what would be helpful. Thanks!

**Comment by charlesmchen-signal** [comment]
Hi @josharian 

If you wait a couple of minutes, does the UI become responsive?  

If so, please send us debug logs. app settings > advanced > submit debug logs > email me the URL at matthew@signal.org.

If not, could you please send the app to background, wait 2-5 minutes.  A crash report should show up.  Please send it to me.  iOS Settings app > Privacy > Analytics & Improvements > Analytics Data > find the most recent crash report(s) that starts with Signal and send them to me at matthew@signal.org.

Thank you, and sorry for the inconvenience.
