### ISSUE TITLE
Uploading from Files application to Signal deletes source file

### ISSUE THREAD

**Issue by temal-** [signalapp/Signal-iOS#4427]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When sharing certain files via the Files application on iOS, the file is deleted after it is sent.

### Steps to reproduce

- Open Files application on iOS
- Select the file you want to send
- Click share icon
- Select Signal
- Select group, member or "note to self"
- Click send icon
- Close the file you just sent

**Actual result:** File is now deleted

**Expected result:** File is not deleted

### Screenshots

![signal](https://user-images.githubusercontent.com/5236825/78926575-9666e000-7a9d-11ea-8024-a73072762193.gif)

I cut out the parts where it would show personal data.

### Device info

**Device**: iPhone 11 Pro

**iOS version**: 13.4.1

**Signal version:** 3.7.1.0

### Link to debug log

https://debuglogs.org/9b3e5742bfd3fbaf246f806ea4871d59509aa6854811f2f5310adb76bdc04f86.zip

**Comment by exchgr** [comment]
at the risk of spamming, i am also having this issue

**Comment by fumiakiy** [comment]
I believe this issue has been resolved by now. See my comment in the PR for more information.
