### ISSUE TITLE
No request for contacts done on iOS 13.3.1

### ISSUE THREAD

**Issue by gir489** [signalapp/Signal-iOS#4438]
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can not request contacts on iPhone 8 Plus iOS 13.3.1.

### Steps to reproduce
- Completely uninstall the app so that no remanent is left.
- Reinstall the app and sign up with Signal.
- Attempt to send someone a message.

**Actual result:** Create a system contact, the user is greeted with a message box that says to enable it in settings, but no actual Contact field is present in settings.

**Expected result:** The phone should ask for the contacts at least once when starting the app, because no native iOS request for contacts is being presented.

### Screenshots
![signal-2020-04-17-202202](https://user-images.githubusercontent.com/7742541/79623360-d7887100-80e9-11ea-8a74-f803d49658d5.png)
![signal-2020-04-17-202202_2](https://user-images.githubusercontent.com/7742541/79623371-e53df680-80e9-11ea-86d0-3d867f3c25b3.png)

### Device info
**Device**: iPhone 8 Plus

**iOS version**: 13.3.1

**Signal version:** 3.7.1.0

### Link to debug log
https://debuglogs.org/852caed1922ff15c6da29fe97b842fa42d5d43bf095be594af0f7865b02e29bb.zip

**Comment by charlesmchen-signal** [comment]
@gir489 Please open the compose view by tapping the pencil icon on the home view.  Then pull-to-refresh.  Does the contacts permission request appear?

Would you be willing to sign up for our beta program?  If so, please send me your email address at matthew@signal.org and I'll invite you.

**Comment by gir489** [comment]
I tired that and all it did was refresh then go away no request was made. I will email you.

**Comment by gir489** [comment]
@charlesmchen-signal I have not received an E-Mail from you yet. I sent an E-Mail on April 22nd, shortly after my comment.

![image](https://user-images.githubusercontent.com/7742541/80765171-5d57e380-8b10-11ea-833f-a72e208255b8.png)

**Comment by gir489** [comment]
Still not fixed in v3.8.0.34 iOS v13.4.1

**Comment by gir489** [comment]
Still not fixed in v3.8.2.7
