### ISSUE TITLE
Photos appear mostly off-screen after tapping on a photo to see enlarged photo from iPad Split View or Slide Over

### ISSUE THREAD

**Issue by s4ryan** [signalapp/Signal-iOS#4439]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While using Signal on an iPad, when Signal is used in either Split View or Slide Over (i.e. https://support.apple.com/en-us/HT207582), when clicking on a photo to see the enlarged view, the enlarged view’s width is not calculated correctly. This causes the photo to appear mostly off-screen to the right, and also causes the buttons at the bottom of the view and the text and title at the top of the view to also be off-center and render partly off-screen. It appears that the math is based on the width of the whole screen, rather than the available width to the Signal app at the moment (I.e. the width of the Split View or Slide Over).

### Steps to reproduce
- On an iPad, put Signal into Split View or Slide Over
- On the list of conversation threads, click one
- Within the conversation thread, click on a photo that was previous sent to enlarge it 
- Every time, the view will not render correctly

**Actual result:** Both the photo and the UI controls are not centered and render mostly off-screen

**Expected result:** The photo and UI controls should be centered in the available space and no part of them should be rendered off-screen.

### Device info
**Device**: iPad Pro 11 inch

**iOS version**: 13.3.1

**Signal version:** 3.7.1.0

**Comment by Cerberus0** [comment]
This should now be fixed in version 3.10:

>We fixed a bug that prevented iPad users from viewing media while split-screen multitasking. Now you can keep your friend’s picture of a sunset on one side of the screen and write a journal entry about how it makes you feel on the other.

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-3-10-release/14628

**Comment by Cerberus0** [comment]
@s4ryan: Version 3.10 is no longer in beta. Could you confirm that this issue is now fixed?

**Comment by s4ryan** [comment]
@Cerberus0: It works great, thanks for the fix!
