### ISSUE TITLE
Crash on iOS while changing sounds

### ISSUE THREAD

**Issue by rmottola** [signalapp/Signal-iOS#4440]
### Bug description
Testing several notification sounds caused crash of app.

### Steps to reproduce
Go to settings change notification sounds repeatedly. Does not happen once or or every time.

### Device info

**Device**: iPhone SE

**iOS version**: 13.3.1

**Signal version:** 3.7.1.0

### Link to debug log

https://debuglogs.org/8980bbf7eda8870529547aaf0c10e029aaa47c129c4b74414e27cf1b26beda20.zip

**Comment by charlesmchen-signal** [comment]
Hi @rmottola Can you please send us your crash report(s)?

iOS Settings app > Privacy > Analytics & Improvements > Analytics Data > find the most recent crash report(s) that starts with Signal and send them to me at matthew@signal.org.

**Comment by rmottola** [comment]
> Hi @rmottola Can you please send us your crash report(s)?
> 
> iOS Settings app > Privacy > Analytics & Improvements > Analytics Data > find the most recent crash report(s) that starts with Signal and send them to me at [matthew@signal.org](mailto:matthew@signal.org).

Hi @charlesmchen-signal just sent. Does the link with zip does not work? it was generated by Signal when I did "report bug"

**Comment by rmottola** [comment]
I received no updates from Matthew however with signal 5.26.10 I cannot reproduce the issue. Maybe he worked on it and we can close?
