### ISSUE TITLE
Signal crashes several times a minute on iOS

### ISSUE THREAD

**Issue by Maximillian0007** [signalapp/Signal-iOS#4441]
- [ ] I have searched open and closed issues for duplicates
- [ yes ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Signal keeps on crashing over and over preventing me from sending more than one message at a time. I have to restart the app several times per minute. I tried deleting the app and re-downloading it and it worked for about two days before the same issue started occurring again.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by n0sign4l-cys4** [comment]
Hi @Maximillian0007 writing issue like that is completely useless, please follow the structure of the template, and if possible submit the crashlog. Maybe related to: https://github.com/signalapp/Signal-iOS/issues/4425?

**Comment by charlesmchen-signal** [comment]
Hi @Maximillian0007 Can you please send us your crash report(s)?

iOS Settings app > Privacy > Analytics & Improvements > Analytics Data > find the most recent crash report(s) that starts with Signal and send them to me at matthew@signal.org.

**Comment by Maximillian0007** [comment]
Just sent it
