### ISSUE TITLE
Dutch 13-digit data-only numbers are not accepted

### ISSUE THREAD

**Issue by bartv42** [signalapp/Signal-iOS#4442]
On Dutch phones, only 11-digit +31 6 xxx numbers are accepted during registration. Data-only plans with the 13-digit +31 9 xxx numbers are rejected. These can receive SMS messages, but not voice calls. Note that other platforms like WhatsApp and Telegram do accept these numbers.

**Comment by cacaosteve** [comment]
It seems like the metadata is stored gzipped in NBGeneratedPhoneNumberMetaData.h. I was going to try fixing this one and doing a pull request but it also needs to be fixed server side and the metadata needs to be modified properly.

I'm getting a 400 request failed if I try with a longer number.

https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+3161234567822?client=ios

**Comment by PieterGit** [comment]
@cacaosteve : I think I found the source of these data. 
AFAICT the source data comes from https://github.com/signalapp/libPhoneNumber-iOS which uses the data from https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

I'm hoping pull request https://github.com/google/libphonenumber/pull/2499 fixes this.
