### ISSUE TITLE
Signal app not at all opening

### ISSUE THREAD

**Issue by Revenge3** [signalapp/Signal-iOS#4443]
- [ ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
I updated the signal app to 3.7.1 version. Since I did that it is not at all opening. In offline mode, it says can’t verify the app in AppStore. 

It was working fine until this update was rolled out. When opened, the signal icon opens for a few moments and closes automatically.

### Steps to reproduce
- update the app to 3.7.1
- upon clicking the app, the app opens and closes automatically when connected to internet
- Offline mode opening evokes a message which says: connect to network to verify the app in the AppStore

**Actual result:** the app is closing automatically. Only the signal icon appears for a few moments and closes

**Expected result:** App to work after updating

### Device info

**Device**: iPhone X

**iOS version**: 13.4.1

**Signal version:** 3.7.1

Unable to get a crash log for Signal
-->

**Comment by monicacalcagnini** [comment]
I have got the same exactly issue.... Signal is the only IM I'm using and I cannot access to it, right now I can only use SMS... Its unbelievable that in nearly a month this hasn't been fixed...

**Comment by flagster76** [comment]
I have the same issue - I'm on the latest version (3.8.0), iPhone 6 Plus, iOS 12.4.6
App crashes within seconds of opening and displaying inbox.
