### ISSUE TITLE
Incorrect "Last active" timestamp for Linked Devices

### ISSUE THREAD

**Issue by i7u** [signalapp/Signal-iOS#4448]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Looking at my "Linked Devices" list, I notice that the "Last active" timestamps are incorrect. For example, a linked device that I used today is listed as "Last active: 28/03/2020" - which (maybe not coincidentally) is also the "Linked" date.

### Steps to reproduce
- Go to Settings -> Linked Devices
- Read the "Last active" dates.

**Actual result:** The wrong "Last active" dates are listed. Maybe the "Last active" field actually displays the "Linked" date, as I see at least two such cases.

**Expected result:** I would expect the "Last active" date to match the date when the linked device was last used (i.e. the application was opened and used to read or send messages).

### Screenshots
![image](https://user-images.githubusercontent.com/2001138/80923768-7ca77880-8d7d-11ea-9e11-9106fb8d3382.png)

### Device info
**Device**: iPhone 8

**iOS version**: 13.4.1

**Signal version:** 3.7.1.0

### Link to debug log
https://debuglogs.org/8b58d4abfda42796298a38fe83edcd97ea21d0b3be11b43e32db20cd62fbb03b.zip

**Comment by Imperiopolis-Signal** [comment]
This should be resolved now, please re-open if you're still encountering the issue.
