### ISSUE TITLE
Remove Giphy (since it was acquired by Facebook)

### ISSUE THREAD

**Issue by caveman1973** [signalapp/Signal-iOS#4453]
Time to remove Giphy from Signal.

I know that Signal [works as a VPN for Giphy](https://signal.org/blog/giphy-experiment/) but now that the company was acquired by Facebook, we can bet they'll use their resources to gather as much data as possible.

R.I.P Giphy

**Comment by u32i64** [comment]
This is not a bug report, but a feature request/discussion topic. It should be discussed on the forum and there happens to already be a [topic about it](https://community.signalusers.org/t/14135?u=u32i64) there.

Quoting [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

> ### The issue tracker is for bugs, not feature requests
>
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.
