### ISSUE TITLE
signal loading screen, low quality screen recordings 

### ISSUE THREAD

**Issue by ki77iaz** [signalapp/Signal-iOS#4457]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

--------------------------------------

fix the load screen when loading signal app, invoking control center, or returning to signal after multitasking from a different app 

screenshot videos appear in standard definition, distorted 

when iphone is locked or in a different app, 3D touching or long pressing an incoming Signal notification opens menu options. Muting a conversation would be more useful than “mark as read” 

when in the signal home screen (where you see all conversations in a list), 3D touching or long pressing a conversation should open menu options - and the menu should be persistent even after lifting finger from screen 

there should be an unsend message feature 

there should be better emojis / stickers - look to telegram for inspiration! 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Genis-Sage** [comment]
hey @ki77iaz 

github is used as bug tracker
for feature requests, behaviour changes and discussions, please go to the community forum
https://community.signalusers.org/

additionally:
it does not make sense to post more than one issue in one thread
