### ISSUE TITLE
“Link new device Scan QR code”

### ISSUE THREAD

**Issue by shanechicago** [signalapp/Signal-iOS#4458]
- [ ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When linking another device, there is no QR code generated on the other device to scan. 

### Steps to reproduce
- followed instructions on screen
- read the users manual
- reinstalled app on both devices 
- repeat all steps above

**Actual result:** No QR code to scan in order to link another device 

**Expected result:** Link an unregistered device (iPhone 11 Pro Max) with a registered device (iPhone 7). 

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 13.4.13

**Signal version:** 3.8.3.5

### Link to debug log

https://debuglogs.org/f4050a4601ee34f859e2b80a2e103862722a8ae39d4e6c20bf6c9b6b6c79c0d4.zip

**Comment by patjolata** [comment]
@shanechicago Well, you can't link an iPhone to an iPhone. You can only link the desktop app or an iPad to the iPhone. You can only link devices like explained in the following support page:

https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices
