### ISSUE TITLE
Share Link from any 3rd app

### ISSUE THREAD

**Issue by frdonn** [signalapp/Signal-iOS#4459]
When I want to share a link from a third app (example: YouTube, go to a Chan, ... menu, share, more, select Signal)
It try to go to Signal but it comes back to YouTube app.

**Comment by Genis-Sage** [comment]
hey @frdonn 

could you fill out the issue template, and give more information:

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

### Link to debug log

**Comment by frdonn** [comment]
Hi,

Please find the form filled up.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
