### ISSUE TITLE
not able to register account on new iOS device

### ISSUE THREAD

**Issue by KypDurron** [signalapp/Signal-iOS#4460]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to Register existing account on an new iOS Device, always shows error "PIN could not be verified"

### Steps to reproduce
- Install Signals latest version from appstore
- start signal
- enter telephonenumber and receive and enter SMS verification
- -enter the PIN

- setup the new iphone from icloud backup
- start signal
- enter telephonenumber and receive and enter SMS verification
- I´m beeing asked about the PIN
- entering the PIN

On my old Phone the PIN´s are working!

**Actual result:** PIN is not accepted

**Expected result:** PIN is accepted and device will be registered

### Device info
"old" Device iPhone Xr 
"new" Device iPhone SE

**iOS version**: 13.5

**Signal version:** latest in appStore

**Comment by spookymulder1293** [comment]
hi how were you able to fix this? i'm having the same issue where the pin can't be created.
