### ISSUE TITLE
PIN Code Bypass

### ISSUE THREAD

**Issue by bryan-campbell** [signalapp/Signal-iOS#4462]
----------------------------------------

### Bug description
PIN prompt can be bypassed by closing the app

### Steps to reproduce
Download iOS app
Enter wrong pin
Force close App
Reopen App
It will prompt for username entry and not ask for the Pin

**Actual result:** PIN is not asked if app is closed

**Expected result:** PIN request should not allow a user to gain access to contacts using signal if PIN entry isn't entered correctly, nor closing the app and reopening should not bypass this request

### Device info

**Device**: iPhone X

**iOS version**: 13.5

**Signal version:** 3.8.4.3

### Link to debug log

https://debuglogs.org/2b53dbdefa9606b17690919a47d98e66c3d70ee45cb90fc36f1cfc568138b781.zip

**Comment by Imperiopolis-Signal** [comment]
The Signal PIN is not intended to protect access to the app, it protects your data that is stored with Signal. The prompts to enter your PIN are to ensure you do not forget it, as it's not recoverable. They by design do not prevent access to the application.
