### ISSUE TITLE
Does this project require Xcode version or Mac OS?

### ISSUE THREAD

**Issue by nihaolifei999** [signalapp/Signal-iOS#4463]
Mac OS : 10.14.6
Xcode : 11.3.1

There are something wrong with my project:
such as 
![image](https://user-images.githubusercontent.com/20531505/83125564-4a820000-a10a-11ea-9089-b60dba4533f2.png)

**Comment by u32i64** [comment]
Signal doesn't use GitHub for development support. Please use the [community forum](https://community.signalusers.org)'s [iOS Development category](https://community.signalusers.org/c/development/ios-development/21) instead.
