### ISSUE TITLE
NIP problem, totally blocked

### ISSUE THREAD

**Issue by Funkynovus** [signalapp/Signal-iOS#4464]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

After ios 13.5 update i launch signal, i put my number Ok ,my verification code OK, my name Ok my NiP NOK, i try different code its not ok , impossible to create NIP so I’m blocked 

### Device info

**Device**: iDevice XS

**iOS version 13.5

**Signal version:3.9.0

**Comment by Funkynovus** [comment]
I regret having switched all my friends on signal, impossible to have help despite emails and forums. I am totally blocked

**Comment by Imperiopolis-Signal** [comment]
Can you please provide  debug logs so we can diagnose your issue? You can generate these by tapping 8 times anywhere on the screen.

**Comment by NiklasBr** [comment]
I’m also stuck on the PIN screen:

![375BC877-FC90-4995-B6E5-0710E235D794](https://user-images.githubusercontent.com/279826/83561357-f9ae4500-a517-11ea-9cc5-8a09195f7b18.png)

**Comment by Imperiopolis-Signal** [comment]
> I’m also stuck on the PIN screen:

This isn't the PIN screen – did you reinstall the app? You'll need to try to register again before you fetch logs

**Comment by NiklasBr** [comment]
> did you reinstall the app? 

I would never do that because I would then lose all my data because backups have been disabled, even though I fully trust my local machine I use for backups. It's been like this since I tried adding a PIN when you requested it in the 3.9 update. I'm stuck now. Can't get through with my number. Can't access anything.

**Comment by Funkynovus** [comment]
hey , its ok for me , i use an other iphone  with my phone number for verification code and i reinstall signal on my phone .
i lost my history .

good luck
