### ISSUE TITLE
Signal on iPad gives pin generation failure and does nothing else

### ISSUE THREAD

**Issue by coughingmouse** [signalapp/Signal-iOS#4465]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

1. Unlink iPad from synced iPhone by not accessing it for a very long time and messing with synced devices
2. Wait until your iPad signal would request for a pin address(or so?)
3. Open iPad to find that it requests setting a PIN.
4. Set it. 
5. Watch pin generation fail. 
6. Redo. Fail again.
7. Switch to another app and come back. 
8. It’s pitch black and there’s nothing you can do except restarting the so and failing PIN generation. 
9. Uninstall Signal so that you can use it again. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Repeating PIN generation algorithm that always fails and gives blackout after switching to another app. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Do something useful.

### Screenshots

I’ll add in whenever I can. 

### Device info

**Device**: iPad Pro 11 inch (WiFi)

**iOS version**: 13.4.1

**Signal version:** 3.9.0

### Link to debug log

https://debuglogs.org/b407ed687b4b1fac3c70330e0e5a86a14d0c46a241c74a601c6f00e6f681073a.zip

**Comment by Imperiopolis-Signal** [comment]
I don't really understand what you're encountering, but a linked iPad should never ask you for a PIN. Can you elaborate on what you're seeing?
