### ISSUE TITLE
iOS Error this user is already added 

### ISSUE THREAD

**Issue by mewe123** [signalapp/Signal-iOS#4467]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
-open Signal Group Chat 
-Go to group chat settings 
-Edit Group
-Add new member
-Choosing new member produces the error “User already in this group 

**Actual result:** 
-                 “Error”
-“User already in this group”

**Expected result:**
-User is added to group chat

### Device info
**Device**: IPhone 11 Pro Max

**iOS version**: 13.5

**Signal version:** 3.9.0.13

### Link to debug log
https://debuglogs.org/5a49dfe5d04a944dbc9fe8bad9c099eb4041de722eeebbbcd7665bb6ef850e28.zip

### Screenshots

https://share.icloud.com/photos/0Kui3Fqr9lV5w3zHPMq86srhw

https://photos.app.goo.gl/zeTpFgbD6U8LUAAH9

**Comment by AlpacaFur** [comment]
I have the same issue (iOS 13.3.1, iPhone 7, Signal 3.9.0.13)

**Comment by Pingmin** [comment]
Me too!

(iOS 13.5, iPhone SE, Signal v3.9.0.13)

**Comment by Pingmin** [comment]
I just found this is duplicated to #4466

**Comment by dobar11** [comment]
Having same issue. - iOS 13.4.1 - iPhone XS Max - Signal version 3.9.0.13

**Comment by Imperiopolis-Signal** [comment]
This is fixed in the 3.9.1 build that went out early today, thanks for reporting it!
