### ISSUE TITLE
Delay After Tapping Address Contact While Forwarding Link or Attachment

### ISSUE THREAD

**Issue by coreythrasher** [signalapp/Signal-iOS#4473]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you try to forward a link to one of your Signal contacts via another app, tapping on any of the contacts doesn't work at first. You have to keep tapping and doing so works after about 15-30 seconds. This delay also happens when attempting to forward a photo from the built-in Photos app.

### Steps to reproduce
- Open an app (e.g., Chrome) that contains functionality to forward a link to something (article, Web page, etc.)  to one of your Signal contacts.
- Press the forward icon (located at the end of the address bar in Chrome).
- Select Signal among the list of apps that iOS displays.
- Signal opens to display your address list.
- Click on any contact. On my iPhone, nothing happens.
- Keep tapping and eventually a conversation window including the link appears.

**Actual result:** An annoying delay in forwarding information.

**Expected result:** Finger tap on the chosen contact instantly opens the conversation window with the forwarded information.

### Device info

**Device**: iPhone XR

**iOS version**: 13.5.1

**Signal version:** 3.10.1.1

**Comment by epvuc** [comment]
I, too, am plagued by this problem.
