### ISSUE TITLE
chat keyboard inaccessible after sending emoji reaction from overflow list

### ISSUE THREAD

**Issue by bakennedy** [signalapp/Signal-iOS#4474]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Adding an emoji reaction from the overflow menu item of extra emoji breaks tapping on the chat text box to bring up the keyboard. User must exit the app and return to raise the keyboard in chat again.

### Steps to reproduce
- receive message
- long press message until reaction pop up pops up
- tap ...
- tap any emoji
- tap the chat text box 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Nothing happens

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The keyboard appears allowing chat text box text entry

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** 3.10.1.1

**Comment by Imperiopolis-Signal** [comment]
This is resolved in 3.10.3
