### ISSUE TITLE
Add Documents View

### ISSUE THREAD

**Issue by florianbegusch** [signalapp/Signal-iOS#4475]
* Feature request
Please add a "Documents" view for things like PDFs, like on Signal-Desktop.
![image](https://user-images.githubusercontent.com/26567162/83962033-f1903580-a888-11ea-929f-62bdd9e0be71.png)

**Comment by Cerberus0** [comment]
Hi @florianbegusch,

That sounds like a good idea, but this is not the right place for feature requests. As stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md):

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the iOS client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

If you want, you can easily join the forum by signing up with your existing GitHub account. You can also show your support for individual feature requests on the forum by using the "like" button.

**Comment by florianbegusch** [comment]
Thank you. I must admit I have not read it.
