### ISSUE TITLE
Call icon missing on latest iPad Build

### ISSUE THREAD

**Issue by th3sn3k** [signalapp/Signal-iOS#4478]
Running 
- iPadOS 13.5
- Signal 3.10.3

Background 
The call icon video and Normal call icons are missing on the app reinstalling the app doesn’t fix it
This same issue is present even when downgrading the app
Also reference to #4352
![image](https://user-images.githubusercontent.com/33957556/84100591-d7da2400-aa29-11ea-9dca-887a5fb00515.jpeg)

**Comment by Imperiopolis-Signal** [comment]
Calls from iPad are currently only available in beta. You can join our beta [here](https://testflight.apple.com/join/8FHtd1Jq).

**Comment by th3sn3k** [comment]
Oh I was going through the documentation on the website and it said it was supported.
