### ISSUE TITLE
Cannot increase the size of emoji as big in messenger

### ISSUE THREAD

**Issue by nesrineabdmouleh** [signalapp/Signal-iOS#4481]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I found two issues related to Facebook Messenger emojis:
- Facebook Messenger does not let users enlarge default emoji as they want
- The emojis list doesn't exist, there are only stickers and GIF.

### Steps to reproduce
- Open Facebook messenger
- Tap and hold on the emoji you want to send
- Send the default emoji

**Actual result:** 
- The emoji size is normal and not increased as the user wants
- The emojis list doesn't exist there is only stickers and GIF.

**Expected result:** 
- The feature that allows users to increase the size of emoji does not work. -> the size of the emoji must be large as the user wishes.
- The emojis list should be visible.
 
### Screenshots

The big emoji is sent by computer.
![Capture d'écran de 2020-06-11 15:59:19](https://user-images.githubusercontent.com/24647495/84393995-a06fa100-abfc-11ea-85ac-aee245d941d1.png)

### Device info

**Device**: iPhone 7 plus, iPhone Xs

**iOS version**: iOS 13.5.1

**Signal version:** 3.10.4.7

**Comment by Genis-Sage** [comment]
hey @nesrineabdmouleh 
you are writing, that you habe problems with the Facebook messenger
and also your screenshot is from Facebook messenger

how is this connected to the Signal messenger?

**Comment by ATaysikuu** [comment]
uhhhh... @nesrineabdmouleh seems that someone's a bit lost here?

**Comment by nesrineabdmouleh** [comment]
Hi @Genis-Sage @ATaysikuu,
Oops, it looks I made a mistake, sorry about that! I thought it is the messanger_facebook repo.
Sorry again, I'm closing this issue.
