### ISSUE TITLE
Signal app requests permission to connect to devices on local network

### ISSUE THREAD

**Issue by RahulRachuri** [signalapp/Signal-iOS#4487]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Once I installed iOS/iPadOS 14 I found this pop up (image attached) the first time I opened Signal on my devices. For some reason it requests permission to scan the local network to connect to other devices, although I’m not sure what functionality requires this.

### Steps to reproduce
- Install iOS/iPadOS 14
- Open Signal for the first time

### Screenshots

![IMG_3687](https://user-images.githubusercontent.com/8736273/85340928-55e90100-b4e7-11ea-9bc3-7a2b81db4131.jpeg)

### Device info
**Device**: iPhone 11 Pro and iPad Pro (2019)

**iOS version**: 14.0

**Signal version:** 3.11.1.1

**Comment by u32i64** [comment]
This is used for [transferring your Signal data to a different device](https://signal.org/blog/ios-device-transfer) when you're switching devices.

**Comment by RahulRachuri** [comment]
I see, would it be possible to indicate that this is why it needs to do it so that people don't freak out (like I did)?

**Comment by u32i64** [comment]
> Would it be possible to indicate that this is why it needs to do it so that people don't freak out (like I did)?

First of all, just to clear up potential confusion, please note that my responses aren't official. Signal staff usually has a `-signal` suffix in their username, and should be a *Member*/*Collaborator*.

Although I agree that the reason should be indicated, it should be taken into account that iOS/iPadOS 14 is still only in **developer beta** at this moment. Installing that you should be prepared to see unexpected and strange behavior from the OS, apps, etc.

That said, I'm sure Signal iOS developers are aware of this new permission, and will implement support for it soon.

**Comment by RahulRachuri** [comment]
Ah, my bad haha.

Yes yes, I'm aware of that. The point of the thread was to make them aware of it just in case (although as you mentioned it seems unlikely that they aren't already aware of it). Thanks!
