### ISSUE TITLE
URL without https:// not clickable

### ISSUE THREAD

**Issue by felixwortmann** [signalapp/Signal-iOS#4488]
When you receive a message with f.e. "abc.com", you can not open it by clicking on it. If the message is: "https://abc.com", you can open it.

In the android version of signal, both of them are openable with one click. I think this should either work on both or work on neither of the platforms.

**Comment by Imperiopolis-Signal** [comment]
I can't reproduce this behavior. Links without the schema, provided they have a valid TLD, seem appropriately tappable. Your example of abc.com specifically works as expected. Can you share any further context?

**Comment by felixwortmann** [comment]
Actually this happened to me with another url. After I tried abc.com it worked as it should. 

abc.app does not work for me though. Could you see if you can reproduce it with that?

**Comment by Imperiopolis-Signal** [comment]
.app is not a TLD apple's data detectors support – it's possible they will add support in a later iOS version. I suggest you file a bug with Apple via the Feedback Assistant about this issue. You should see the same behavior in the Messages app as well as a number of others.
