### ISSUE TITLE
Light sensor toggles voicemail playing

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#4490]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Phone needs to be unlocked with sufficient incoming environmental light in order to continue to play voicemails. This is both a security vulnerability (as in driveby phone theft) and a serious inconvenience (as in not being able to play messages in the dark). A similar problem exists on Android, in the sense that the phone can't be put to sleep while still playing a voicemail (even though that's fortunately not the case with voice calls.)

### Steps to reproduce
- Ask a friend to send you a voicemail of at least 3 minutes' length.
- Go into a room. 
- Play the message.
- Shut off all light sources.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Observe that playing halts shortly after the room darkens.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Playing continues, regardless of darkness or lock state.

### Screenshots
N/A

### Device info
**Device**: iPhone 7
**iOS version**: (latest)
**Signal version:** (latest)
### Link to debug log
N/A

**Comment by lebensmittel** [comment]
This issue still persists in November 2020.

I'd like to add:

When playing a voice mail in any chat, the screen turns black as soon as the light sensor is recieving less enough light to assume the phone is put away, i.e. in your pant's pocket. The voicemail playback further switches to the standard call-speaker for the time the sensor is blocked.

My device info:

Device: iPhone 5s
iOS version: 12.4.9
Signal version: 3.22.0.8

Debug log:
https://debuglogs.org/9a7fd4b925d018782e46f94e134bfa289882811567b178a08578638e04219f61.zip

**Comment by sailbird** [comment]
@greyson-signal I'm still getting complaints from my iOS peers about this issue. Seems that voicemails still stop playing as soon as the phone is put to sleep, or puts itself to sleep because it senses that the environment is dark. Definitely not an issue on Android. So, architecturally speaking, why the dichotomy? Seems like a design flaw.

I'll leave this to you (or whoever the right team member is) to investigate. I don't log in often but have nothing else to add, apart from my sincere thanks in advance for having a look.

Happens on iPhone 12. That's all I know.

**Comment by sailbird** [comment]
This has gotten worse. From a friend using iOS:

"Also that thing where if I cover the light sensor or it’s too dark then it pauses playback - they’ve doubled down and increased the sensitivity such that even wafting my hand past the phone 6+ inches away causes it to shut down, then start playing [the voicemail] again a few seconds later in the message meaning I have to rewind (without my hand going near the light sensor again)"
