### ISSUE TITLE
Signal SMS and insecure SMS are (still) dangerously easy to confuse

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#4493]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sorry to submit a bug like this, but it's so much of an accident waiting to happen that it frankly exceeds the threshold for being considered a fault.

### Steps to reproduce
There are several ways in which the one can be mistaken for the other. The worst case is probably iPhone's SMS app, which has an icon almost identical to Signal's. It's just too easy to insecurely SMS someone from the Contacts app rather than Signal SMS them. Yes, _technically_ this is on the user, but it's bad design. It's also too easy to do this: (1) friend signs up for Signal, (2) you enter their phone number into Signal (because the first contact doesn't work from Contacts, for whatever reason), (3) you start typing away and send a message, just assuming that it will be transmitted securely because they've already registered but (4) you failed to notice the "insecure SMS" warning. It would be far safer if Signal, at least by default, never did an SMS on the user's behalf. It was _only_ secure. And your phone's messaging app was _only_ insecure. And (ideally) the Signal icon was radically different from the iPhone message app icon, rather than subtly so.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Humans like me are sometimes careless. Without being really meticulous, we suddenly end up creating more vertices in a social graph by mistaking insecure SMS for Signal SMS.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Maybe "expected" is too strong a word. More like, it would be nice if you didn't build the barrel of the pistol pointing back at the user by default.

### Screenshots
N/A

### Device info
**Device**: iPhone 7
**iOS version**: (latest)
**Signal version:** (latest)

### Link to debug log
N/A

**Comment by Imperiopolis-Signal** [comment]
Signal for iOS does not have the ability to send SMS so I'm not really sure what your steps 1-4 refer to. It seems like your only even marginally relevant issue is the minor similarities in app icon, but I would describe them as far more than "subtly" different.
