### ISSUE TITLE
Link following dangerously easy

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#4494]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Tapping a few millimeters off target when trying to select text -- or just "pressing" too briefly so as to be interpreted as "tapping" -- can cause a link to fire off without confirmation. So now the topic of your conversation gets sent to third party sites or apps. Or worse, you end up following a link when you wanted to copy it to someone else for authenticity verification before the fact.

### Steps to reproduce
- Ask a friend to send you a YouTube (or other) link.
- Tap it.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- YouTube (or other) app "just launches" with no warning. (This is fine as an opt-in, but it's too trigger-happy for most users.) Now YouTube et al knows the topic of your conversation. It would be nice to have a dialog (maybe even with "don't ask me again") warning the user that the conversation is now going to be compromised in some qualitative sense.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Ask the user if they realize the security ramifications of what they're about to do.

### Screenshots
N/A

### Device info
**Device**: iPhone 7
**iOS version**: (latest)
**Signal version:** (latest)

### Link to debug log
N/A

**Comment by Tursko** [comment]
This is more of a feature request. You can post your feature requests on the forum: http://community.signalusers.org/
