### ISSUE TITLE
QR-Code for transfer covered by enlarged text

### ISSUE THREAD

**Issue by Eldiabolo21** [signalapp/Signal-iOS#4495]
### Bug description
When I try to use the transfer feature of Signal and have the text enlarged in the settings, the text covers the QR-Code and it cannot be read.

### Steps to reproduce
- iOS-Settings -> Accessebility -> Display and Text Size -> Larger Text -> Move slider at bottom all the way to the right
- Transfer Signal content from an old to a new iphone. have QR-code open (see screenshot)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
QR cannot be read because its covered by information text

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Information text should sit below the QR regardless of text size

### Screenshots
![signal-2020-07-05-110131_edited](https://user-images.githubusercontent.com/5549781/86529462-23f57880-beb1-11ea-94f9-27d5a05a7f3b.png)

### Device info
**Device**: iPhoneSE

**iOS version**: 13.5.1

**Signal version:** 3.12.2.4

### Link to debug log
No debug log neccesseray

**Comment by guimspace** [comment]
Same issue on iPhone SE 2nd gen, iOS 14.6, Signal v5.15.0. A scroll bar can aid the issue.

**Comment by Eldiabolo21** [comment]
Yes, still relevant.

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by NiklasBr** [comment]
Why was this closed?
