### ISSUE TITLE
Video message exceeding size limit: deleted without option to save it, losing user data

### ISSUE THREAD

**Issue by hraban** [signalapp/Signal-iOS#4497]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

This issue is about video messages, accessed by clicking the camera to the right of the input box, and holding the camera button. It works fine for short videos, but if the video becomes too long, it will be too large in file size. e.g. when you reach 127 MB and click send, it will say "attachment is too large" , and just drop you straight back in the message thread. **It loses the entire video that you just recorded,** which is never good.

### Steps to reproduce
- open a direct message convo with someone on the iOS app
- click the camera icon
- hold the camera button. it will start recording. hold it for a long time, 10 minutes should work (it probably depends on the camera resolution how long it takes for you to exceed the file limit? I assume the limit is 100MB, but it's pure conjecture. On an iPhone SE 2020, you need ~7min of front facing camera)
- it will show the file size, and a send button; click the send button

**Actual result:**

Flashes an error message for half a second, then drops you back in the chat and deletes the video entirely.

**Expected result:**

One of:

- when the filesize reaches a limit, stop recording, and send that, explaining I've reached the limit, OR
- split the video into multiple files which are each under the limit, OR
- allow me to save the video to my local camera roll so I can send it another way

but don't delete all that user data :( a lot of work goes into a long video message, kind of by definition.

### Screenshots

![IMG_1907](https://user-images.githubusercontent.com/137852/86928115-0d0e8a80-c12c-11ea-92d9-b2a4e83f3ef8.jpg)
![IMG_1908](https://user-images.githubusercontent.com/137852/86928125-0f70e480-c12c-11ea-9930-6e20b863e1a1.PNG)

### Device info

**Device**: iPhone SE 2020

**iOS version**: 13.5.1

**Signal version:** 3.12.0.16

**Comment by hraban** [comment]
Exasperated update: apparently the limit is closer to 6:30. Do not, under any circumstances, ever record a video message longer than that.

I am off to go cry somewhere now.

**Comment by dougpagani** [comment]
+1 I also have experienced this issue; it happens on iPhone 11 as well, seemingly around 7 minutes. There is a nontrivial amount of frustration associated with this user experience.

**Comment by hraban** [comment]
The limit seems to have been lowered; it just happened to me with a video between 6min and 6:30min, of 92MB. This was 100% possible when I originally posted this issue. Same phone, ios v 14.6, app v 5.14.0.35.

**Comment by hraban** [comment]
it is still relevant.

**Comment by hraban** [comment]
Different failure mode, but definitely still relevant. Now it just crashes, or turns the video into a single frame photo (!?).
