### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by jmg1023** [signalapp/Signal-iOS#4499]
Even though all settings are correct and phone has been restarted twice, problem started Monday night and persists. Yes, have latest update. Only time you hear a chime is if app is open and user is on it. Otherwise there is zero notifications. Even the badge with message number doesn’t work.

**Comment by adamrwarner** [comment]
I'm having the exact same issue

**Comment by iHarryme** [comment]
Same issue after the update. Signal: 3.13.1.0 ; iOS: 13.5.1
https://debuglogs.org/59c3ad68b233a2b5de9f98c2411394c340ef455d0023829d0e268142e7074cfb.zip

**Comment by dannyparsonscs** [comment]
Having the same issue here now.

**Comment by chuchiring** [comment]
same here, please fix it

**Comment by dfritsch1989** [comment]
I am having the same issue. Still not resolved.

**Comment by mavericks065** [comment]
same.

**Comment by chipang** [comment]
same
