### ISSUE TITLE
Signal does not request contacts permission again after resetting iOS privacy settings

### ISSUE THREAD

**Issue by chenxiaolong** [signalapp/Signal-iOS#4505]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

After performing the "Reset Location & Privacy" operation in the global iOS settings, Signal fails to prompt for access to contacts again. This only happens with the contacts permission. The app has no problem prompting for camera, face ID, etc. access again.

### Steps to reproduce

- Open the iOS Settings app
- Go to General -> Reset -> Reset Location & Privacy
- Open Signal
- If touch ID or face ID was previously enabled, it should prompt for access to it
- Signal shows modal dialog "Turn on Contacts?"
[(screenshot)](https://user-images.githubusercontent.com/646253/87615972-f3e47b80-c6e1-11ea-8a3b-01f8761c0428.jpeg)
- Tap "Turn On"
- Signal tells user to go to Settings app to enable the permission
[(screenshot)](https://user-images.githubusercontent.com/646253/87616073-3ad27100-c6e2-11ea-8d1f-01483f7117c4.jpeg)
- The Settings app does not list the Contacts permission
[(screenshot)](https://user-images.githubusercontent.com/646253/87616171-7a00c200-c6e2-11ea-9920-a6ae304929fb.png)

**Actual result:** Signal directs the user to the Settings app, but iOS is no longer aware that Signal ever requested the Contacts permission, so there's no switch for it.

**Expected result:** Signal should prompt for Contacts access again, similar to the initial app launch. The app seems to already do this properly for other permissions, like Camera and face ID.

### Screenshots

(Linked inline above)

### Device info

**Device**: iPhone 11 Pro Max and iPad Pro 12.9 4th gen

**iOS version**: 14.0 dev beta 2 and 13.6

**Signal version:** 3.13.1

### Link to debug log

https://debuglogs.org/1d73bf8af0dcf31c6c79a8a80ae93b0685fe181213742b1c9c7043e9b702df4e.zip

**Comment by seba31000** [comment]
Hello,

Did you try to see the privacy settings going through “Contacts”? Does Signal appears there ?
Thanks.

**Comment by chenxiaolong** [comment]
It didn't appear there either. However, I was able to work around it by tapping on an existing chat. Once I did that, Signal properly re-requested the Contacts permission again.
