### ISSUE TITLE
The certificate has expired. Can they be renewed?

### ISSUE THREAD

**Issue by aliiiii544** [signalapp/Signal-iOS#4511]
The certificate has expired. Can they be renewed?

**Comment by Imperiopolis-Signal** [comment]
What are you talking about?

**Comment by aliiiii544** [comment]
Testimony of the right to download software from external stores

**Comment by 01111010t** [comment]
Are you able to provide more information? For example, you could follow the layout below:
Bug description

Steps to reproduce

Actual result

Expected result:

Screenshots

Device info

**Comment by aliiiii544** [comment]
في أربعاء، ٥ أغسطس، ٢٠٢٠ في ٧:٠٦ م، كتب 01111010t <notifications@github.com

**Comment by King75106** [comment]
![image](https://user-images.githubusercontent.com/76516258/104140676-31b41b00-5378-11eb-8847-4f9c62641061.png)
