### ISSUE TITLE
Unable to Unregister Signal Number

### ISSUE THREAD

**Issue by smophos** [signalapp/Signal-iOS#4512]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Unable to Unregister Signal Number
I deleted the app and then tried to reinstall it; but it never completes the registration process; there seems to be some issue where the signal server thinks my number is still connected to a device. Hence I cannot access my account. I have tried to report issue but no luck. I am trying to use https://signal.org/textsecure/unregister/ to unregister it from my account so that I am able to register it again but it gives me an error.Please Help.

### Steps to reproduce
- download Signal iOS
- try to register number

**Actual result:** code never comes, call never comes. Using the unregister form produces no result. It has been two weeks. 

**Expected result:** Registration of my number should be possible as I have done it before.

### Device info

**Device**: iPhone X

**iOS version**: 13.5.1

**Signal version:** 3.13.2

**Comment by mkincaid** [comment]
These steps within the app should let you unregister the number:
https://support.signal.org/hc/en-us/articles/360007061192-Unregister-or-Delete-Account

But yeah, I agree, that defunct webform should be either fixed or removed.
