### ISSUE TITLE
App crashes on photo attachment iOS

### ISSUE THREAD

**Issue by miniharryc** [signalapp/Signal-iOS#4516]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

https://debuglogs.org/36cd4d11da2a5e9e69d0c414bc60119df05afc1c30ee1fabcf40b36a4f2b6e67.zip

### Steps to reproduce
- open a conversation
- attempt to attach photo
- app freezes then exits 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone8

**iOS version**: 13.6

**Signal version:** 3.13.3.10

### Link to debug log

https://debuglogs.org/36cd4d11da2a5e9e69d0c414bc60119df05afc1c30ee1fabcf40b36a4f2b6e67.zip

**Comment by IsaiahJTurner** [comment]
Seeing this as well.

**Comment by cardassian-tailor** [comment]
Also have the same issue. Easy to reproduce.

**Comment by denver-s** [comment]
I am unable to reproduce this bug.

**Comment by miniharryc** [comment]
I’m on an iPhone 13 Pro now and don’t see this issue in current releases.
