### ISSUE TITLE
Camera does not enable light for video

### ISSUE THREAD

**Issue by martinjthompson** [signalapp/Signal-iOS#4518]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic
(In my opinion this is not a feature request anyway :)
----------------------------------------

### Bug description
When videoing after enabling the camera flash, the light does not turn on

### Steps to reproduce
- open camera
- click the flash icon to solid lightning bolt
- hold shutter to start video recording

**Actual result:** Video records in the dark

**Expected result:** Flash should turn on and illuminate the scnece

### Screenshots
N/A

### Device info
**Device**: iPhoneSE
**iOS version**: 13.5.1

**Signal version:** 3.13.2.6

### Link to debug log
N/A

**Comment by JRHonda** [comment]
Took a peek at the PhotoCaptureViewController `beginMovieCapture()` and `switchFlashMode()` methods and I think a quick patch can be made by leveraging the `captureOutput.flashMode` property when `.on` to activate `torchMode`

Here is a helper method and enum (for readability):

```

enum Toggle {
    case on
    case off
}

func switchTorch(_ on: Toggle) {
        
        guard let device = AVCaptureDevice.default(for: .video) else { return }
        
        if device.hasTorch {
            
            do {
                
                // lock
                try device.lockForConfiguration()
                
                if on == .on {
                    device.torchMode = .on
                } else {
                    device.torchMode = .off
                }
                
                // release lock
                device.unlockForConfiguration()
                
            } catch {
                // Uh-oh...handle error
            }
            
        } else {
            // Shucks...no torch.
        }
    }

```

Implementation in method `beginMovieCapture()` : 

```

...

if self.captureOutput.flashMode == .on {
    switchTorch(.on)
}

...

```

**Comment by denver-s** [comment]
It is now possible to use torch when recording a video.

**Comment by martinjthompson** [comment]
The torch now (5.26.10.0) flashes on briefly at the start of the video recording but then turns off almost immediately.
