### ISSUE TITLE
Long delay between tapping conversation and it opening

### ISSUE THREAD

**Issue by dannyparsonscs** [signalapp/Signal-iOS#4519]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There are huge delays when trying to open a conversation from the main screen. This is true whether there are many messages between it was last opened or just going back and forth between conversation and main screen. 

### Steps to reproduce
- Open app
- Tap on a conversation

**Actual result:** Takes >25 seconds to open a conversation after tapping. 

**Expected result:** Ideally, take less than 1 second to open a conversation. 

### Device info

**Device**: iPhone SE

**iOS version**:13.5.1

**Signal version:** 3.13.3.10

### Link to debug log
[org.whispersystems.signal 2020-08-07--15-02-49-600.log](https://github.com/signalapp/Signal-iOS/files/5042177/org.whispersystems.signal.2020-08-07--15-02-49-600.log)

**Comment by gual** [comment]
Seems like #4348

**Comment by AbroMansoor** [comment]
same issue

**Comment by Imperiopolis-Signal** [comment]
dupe
