### ISSUE TITLE
No prompt to transfer messages after registering on a new phone

### ISSUE THREAD

**Issue by selbetar** [signalapp/Signal-iOS#4520]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After verifying my phone number on the new device and entering the registration PIN, I was not prompted to transfer my account and message history from another iOS device, instead, I was taken directly to an empty conversations window as if I have just started afresh.

### Steps to reproduce
- Install signal on the new device
- Enable WiFi and Bluetooth on both devices
- Both devices are close to each other
- Complete registration and enter registration PIN on the new iPhone with the same number as the old device

**Actual result:** 
No migration prompt was shown after verifying my phone number and PIN and was taken to an empty conversation window once the PIN has been confirmed.

**Expected result:**
After verifying my phone number, I should have been presented with a migration prompt as described in the support [article](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore).

### New Device info

**Device**: iPhone 11

**iOS version**: 13.6

**Signal version:** 3.13.3.10

### Old Device info
**Device**: iPhone 8

**iOS version**: 13.6

**Signal version:** 3.13.3.10

**Comment by Imperiopolis-Signal** [comment]
Was your old device registered when you updated to 3.13? Or did it have the banner at the top of the screen asking you to re-register?

**Comment by selbetar** [comment]
I would like to state that I'm reporting this issue on behalf of my friend.

In reference to your question, they said it was registered and there was no re-registration banner; we also did communicate securely through signal just fine on July the 30th.

However, there are other issues that we have encountered, and registration could be related to it.

### The first issue:
- The safety number kept on changing when switching back and forth between the two devices (while signal is open)
- This resulted in bad encrypted messages. Resetting the session did not solve it
- One of my messages failed to be sent because of safety number changes
- This happened the very first time Signal was installed on the new device.

### Screenshots [From my perspective]

![1](https://user-images.githubusercontent.com/46614065/90644791-0161b980-e1ea-11ea-8ab0-16016b3e043a.png)
![2](https://user-images.githubusercontent.com/46614065/90644798-032b7d00-e1ea-11ea-9897-4cab9d20407b.png)

----

### The second issue:
Failure to disable PIN.

- Attempted to disable registration PIN
- There is now an option called `Create a PIN` and not `Change your PIN` under privacy settings
- However, the registration lock is still on, and if we try to turn it off, it just turns back on
- The PIN is still active as the installation process on the new device still asks for a PIN

Attempting to create a new PIN by clicking on `Create a PIN`
results in the following:

**PIN Creation Failed**
**Your PIN was not saved. We'll prompt you to create a PIN later.**

We generated a debug log after failing to disable the PIN.

### Link to debug log (Old Device)
https://debuglogs.org/9a791152c90a6b05c517b836f3efd0ec5ad45139d7336fdf0c4ad34f34b49c72.zip

**Comment by selbetar** [comment]
Because of my friend's phone number, censorship circumvention is enabled by default, however, they are currently in a country where censorship circumvention is not needed.

###  On the old device:
After disabling censorship circumvention, the banner you mentioned appeared as can be seen in the screenshot.

![1](https://user-images.githubusercontent.com/46614065/91186392-d7097380-e6a3-11ea-9828-e98e3a1d6b3e.jpeg)


We went through re-registration on the old device and the prompt to transfer messages finally appeared during re-registration.

### On the new device:
After re-registering successfully on the old device and going through the steps mentioned above in **steps to reproduce**, we still do not get a prompt to transfer messages. I believe this is happening because of censorship circumvention.


### Debug Logs (new device)
Generated during registration flow:
https://debuglogs.org/6aa2964fd6b098d67fd0b657b9756729f83a0772097cc847f46d2f7556e94583.zip

Generated after registration:
https://debuglogs.org/c3b8c514483021d651d66bd00ed142c0f14c74f96a16dd905158dbab38e5c692.zip

**Comment by selbetar** [comment]
Tried again today and the issue seems to have been fixed.
