### ISSUE TITLE
Can I develop a function that can set an independent lock screen password?

### ISSUE THREAD

**Issue by fireworksdancewindsing** [signalapp/Signal-iOS#4523]
Can I develop a function that can set an independent lock screen password?
The current software is to set the lock screen unlock password to be consistent with the system, I don't want to use the system password or fingerprint to unlock the software.
And I hope to add the password function required to open the software. Can it be achieved? Thank you.

**Comment by michelle-signal** [comment]
This isn't something we're planning on adopting in the near future. If you'd like to see this included in a future release, the [community forums](https://community.signalusers.org/) are the best place to submit feature requests.
