### ISSUE TITLE
TAKING LONG TIME TO OPEN A CONVERSATION

### ISSUE THREAD

**Issue by AbroMansoor** [signalapp/Signal-iOS#4524]
from last few updates, SIGNAL MESSENGER behaving very weird, always take 02 to 05 min to open a conversation from lay out always get stuck we pray that this get normal we dont want childish features we just simple want a messenger that can be easily use for communication.

please please look in to this an resolve the matter

**Comment by benlevy0** [comment]
Duplicate #4348
