### ISSUE TITLE
Camera can't work in conversation

### ISSUE THREAD

**Issue by RabbitNever** [signalapp/Signal-iOS#4525]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a conversation, I clicked the 'Camera' button at bottom to take a photo, but camera can't work. A error message "The operation couldn't be completed (Signal.PhotoCaptureError error 1.)" was shown on screen. If you debug with xCode, you will find the app crashes at line 199 in PhotoCaputure.swift. I can guarantee that I have allowed the app use camera.

### Steps to reproduce
- open a conversation
- click bottom '+' button
- click 'Camera' button

**Actual result:** Camera can't work and show error message.

**Expected result:** Camera can work well.

### Screenshots

![IMG_7878FE2670AD-1](https://user-images.githubusercontent.com/20531484/90583802-b2288280-e203-11ea-9500-e1dca757a52e.jpeg)

### Device info

**Device**: iPhone Xs Max

**Model Number**: MT742CH/A

**iOS version**: 13.5.1

**Signal version:** 3.13.3.10

**Comment by Joebortscheller** [comment]
Why

**Comment by Joebortscheller** [comment]
Why is iOS not compatible

**Comment by michelle-signal** [comment]
There are a few duplicate reports of this issue stretching back for some time. Here's one: https://github.com/signalapp/Signal-iOS/issues/4289

The current understanding is there might be something happening within iOS itself. Workarounds usually involve either rebooting the device or launching the system camera app and switching to video mode.

Are you able to get into this state after rebooting the device? Or do you only hit this sporadically?

Going to close this and direct discussion towards #4289.
