### ISSUE TITLE
Badge count not updated on deletion of unread

### ISSUE THREAD

**Issue by dantler** [signalapp/Signal-iOS#4526]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I delete an unread "X is on Signal!" notification/conversation, the badge count does not decrement.

### Steps to reproduce
- Have a "John Appleseed is on Signal!" item in conversation list
- Mark this conversation as "Unread"
- Verify that Badge count = 1 on Home Screen
- Delete the conversation

**Actual result:** 
- Badge count = 1.
- OCD on the fritz

**Expected result:** 
- Badge count = 0.
- Peace and tranquility

### Device info

**Device**: iPhone X

**iOS version**: 13.6.0

**Signal version:** 3.14.1.2

**Comment by michelle-signal** [comment]
Thanks for finding this! It looks like this happens will any sort of conversation thread, not just the "X is on Signal!" threads. Leaving this open until he have a fix.

**Comment by denver-s** [comment]
Should've been fixed by https://github.com/signalapp/Signal-iOS/commit/f8cb80926c5af2e76c0c6aa4374dacb043babe89

**Comment by dantler** [comment]
After updating to v3.18, my phantom notification is gone. Thank you!  Closing the issue.
