### ISSUE TITLE
"Transfer from iOS Device" panel on source iPhone closes when opening command center

### ISSUE THREAD

**Issue by mstange** [signalapp/Signal-iOS#4528]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When setting up Signal on a new iPhone and transferring data from the old iPhone, the panel that is displayed on the old iPhone during the transfer is very brittle. It disappears automatically when either of the following happens:

 1. The user pulls up the command center from the bottom of the device. Or
 2. The "low battery" modal dialog is displayed by the system. Or
 3. Probably other things, like pulling down the notification center from the top.

Once the panel is gone, there is no obvious way to bring it back.
There is no progress indication on the old phone any more.
And the warning text about the fact that Signal must stay open during the transfer is also gone. (This caused me to close Signal and unintentially abort the transfer.)

### Steps to reproduce

 - Have an old iPhone with message history in Signal
 - On a second iPhone with a fresh install of Signal, initiate message history transfer.
 - On the old iPhone, press the buttons and scan the QR code so that the transfer begins.
 - a) On the old iPhone, pull up the command center from the bottom of the screen, or
 - b) Wait for the old iPhone's battery percentage to drop below 20% during the transfer, so that the system displays the modal dialog to enable low power mode.

**Actual result:** The transfer status panel on the old iPhone disappears.

**Expected result:** The transfer status panel on the old iPhone should remain on the screen.

### Device info

**Device**: iPhone 6S

**iOS version**: 13.5.1

**Signal version:** 3.14.2.2

**Comment by michelle-signal** [comment]
Device transfer will be interrupted if the app ever moves to background. But it should be robust against moving to the inactive state, (e.g. during control center presentation, system alert presentation, etc).

I'm not seeing this reproduce locally. I'm able to present control center over device transfer, and things continue normally. [Debug logs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) would definitely help us here. If you're able to reproduce consistently, would you be able to collect logs?
