### ISSUE TITLE
"Transfer from iOS device" causes the source iPhone to overheat

### ISSUE THREAD

**Issue by mstange** [signalapp/Signal-iOS#4530]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When transferring message history data to a new iPhone, the source iPhone can get very hot. This is more likely to happen when the source iPhone is also charging at the same time.
This is problematic because, once a certain critical temperature is reached, the system displays a "temperature warning", and this warning causes the transfer to abort (see #4529).

Two of my transfer attempts today failed due to the overheating problem. Attempt 5 finally succeeded, after disconnecting phone from the charger and resting it on a cold plastic water bottle. This phone does not usually have any heat problems.

It feels like the transfer process is rather heavy on the CPU.

### Device info

**Device**: iPhone 6S

**iOS version**: 13.5.1

**Signal version:** 3.14.2.2

**Comment by michelle-signal** [comment]
I'm really sorry you're running into this issue. Device transfer is very CPU and networking heavy, but it shouldn't be so heavy that iOS starts throwing thermal warnings. This is something we'd like to improve, but at the moment I can't say when we'll have a fix for this.

**Comment by ThePowerOfDreams** [comment]
How about allowing us to back up Signal data as part of an encrypted local backup? Conversation data is _our_ data, not yours, and deliberately preventing us from backing it up is a terrible decision.
