### ISSUE TITLE
When "Transfer from iOS device" is interrupted, Signal requires a new confirmation SMS

### ISSUE THREAD

**Issue by mstange** [signalapp/Signal-iOS#4531]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When transferring message history data to a new iPhone, a multitude of problems can cause the transfer to be aborted midway through. Once this happens, the destination Signal app resets, and requires a new confirmation SMS.

This is annoying because it runs into rate limiting: After a certain number of tries, the user is asked to wait "for a minute" (in reality: at least 30min, apparently) before another transfer can be attempted.

The forced waiting time causes extra grief for the user who is already frustrated by the failed transfers.

**Expected result:** After the confirmation code from the SMS has been received on the new iPhone, this code should allow an infinite amount of transfer attempts. Failed transfers should reset to a post-activation state.

### Device info

**Device**: iPhone SE

**iOS version**: 13.5.1

**Signal version:** 3.14.2.2

**Comment by michelle-signal** [comment]
Thanks for really hammering on the device transfer flow. These issues have been helpful feedback.

With regards to rate limiting, the server has some rate limiting logic that is more complicated than "Please wait a minute before trying again" might suggest. But in general, you should be able to attempt within three minutes.

The larger issue here is the registration flow requiring an SMS approval before every transfer attempt. There are areas we could improve here, but it greatly increases the complexity of state we need to track. We'll continue to track improvements here, but I can't make any guarantees on when that might be available.
