### ISSUE TITLE
OPTION OF BACK UP REQUIRED

### ISSUE THREAD

**Issue by AbroMansoor** [signalapp/Signal-iOS#4533]
NEED A WAY TO EXPORT THE CHAT.

ALSO NEED SELECTION OF ALL MEDIA IN ONE GO SO WE CAN SAME IT OR MOVE IT TO OTHER PLACE

**Comment by michelle-signal** [comment]
Feature requests should be directed to the [Signal Community forums](https://community.signalusers.org/). Github issues are reserved for bugs.
