### ISSUE TITLE
"Note to Self" isn't sorted after deleting messages

### ISSUE THREAD

**Issue by guimspace** [signalapp/Signal-iOS#4534]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
By deleting the last few messages, except the very last message, from the "Note to Self" history, the thread isn't correctly sorted in the list of chats.

### Steps to reproduce
**Note** Make sure "Note to Self" is not the most recent/first thread in the list of chats.
1. Send at least 2 messages in "Note to Self". For example 4 messages. "Note to Self" should be in the top list at this point.
2. Delete the last few messages except the most recent message (so 3 from the example).
3. Back in the list of chats, "Note to Self" isn't the top chat despite the date of the last message. It is back in the position before step 1.

**Actual result:** Note to Self is not correctly positioned/sorted in the thread list.
**Expected result:** Note to Self is sorted by date according to the most recent message.

### Device info
**Device**: iPhone SE 2020
**iOS version**: 13.6.1
**Signal version:** 3.14.2.2

**Comment by michelle-signal** [comment]
Thanks @u32i64! @guimspace, this should be fixed in 3.15. If it's not, please comment back and we'll continue to look into this.
