### ISSUE TITLE
safety bug, wrong logic or setting problem !!!!

### ISSUE THREAD

**Issue by liufeijin** [signalapp/Signal-iOS#4536]
I have set all message will disappear in signal on my iphone6s(ios14 beta5)
,but when i install the signal soft wear on laptop , all disappear message are present again!
All message are not disappeared at all, they just disappeared on my iphone!, All message are stored at somewhere.
Who is keeping all message always.

It is danger, you think your all message already gone but it still at here.
Somebody(or GOV) just sing in signal on other platform (sometime you must give them password), will get all evidence.

I don't find any setting for this. so is it a safety bug, wrong logic or setting problem?

???

**Comment by liufeijin** [comment]
I found this also, it is so danger .  i sent and received messages  will appear in signal on desktop ver.
Now i need login signal on desktop ver to delete all message, but i think it is not really deleted still , it can be found in your friend ID when they login signal on desktop. it is big problem. Signal has no safety at all.

**Comment by Imperiopolis-Signal** [comment]
Hi, I'm sorry but it's really hard to understand your issue report. In general, each device associated with your account receives messages independently. Deleting a message on one device deletes it only on that device. As for disappearing messages, the disappearing countdown will start on all devices as soon as the message is seen on one device. If you're still having an issue, please let me know.
