### ISSUE TITLE
Voice message seen as a file and not displayed

### ISSUE THREAD

**Issue by n0sign4l-official** [signalapp/Signal-iOS#4539]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One of my friends forwarded to me an audio message from signal Android to iOS. before sending it to me he just typed something below it (like when you add a description to a photo). When i received it i couldn't open it. IMPORTANT: the audio sent from the android phone was coming from Whatsapp but he had no problem to listen to it from signal android

### Steps to reproduce
- send whatsapp audio
- forward it from signal to a android signal user
- now the android signal user forwards to ios signal user
- cannot open the audio

### Link to debug log

https://debuglogs.org/d132c20ceaf035d9f99aaa34e34ca1f703852331ce29fd77fe5574e80331fddc.zip

**Comment by guimspace** [comment]
The attachment is displayed as a binary file named "Attachment". Exporting it to "Files" renames the file with its UID and ".bin" extension.

**Comment by ibby89** [comment]
Confirming this one. The audio file is showing correctly on signal-desktop. Screenshots below:
iOS: 14.4.2, Signal: 5.10.0.49
https://pasteboard.co/JZ5EGqg.jpg
Desktop: Win 10 19041.928, Signal: 5.0.0
https://pasteboard.co/JZ5G5nu.jpg

**Comment by leandroprz** [comment]
I'm experiencing this exact same issue.
I'm using iOS 14.3 on a 6s and Signal v5.11.1,
Windows 10 Pro, Signal v5.1.0.

**Comment by coezbek** [comment]
I have the same problem when migrating some old voice messages from Whatsapp to Signal: While I can play these files on Android, my wife on iOS cannot.

It seems the files are `.ogg` with `opus` codec which aren't supported natively on iOS.

**Comment by mehmetb** [comment]
Those binary files are rendered as audio messages in the Signal Desktop app. So I have to switch to Signal Desktop every time I receive such a message.

**Comment by coezbek** [comment]
This issue is still present in the iOS client 5.27.0.

**Comment by NiklasBr** [comment]
Stop bot.

**Comment by mehmetb** [comment]
Stop bot.

**Comment by EvanHahn-Signal** [comment]
We're tracking this bug in our internal tracker. There is no need to comment further here.

**Comment by keithzg** [comment]
This remains a problem as of today, so it seems incorrect for it to be closed.

**Comment by locusus** [comment]
I came here to remark that ogg and opus files sent from my Signal android or desktop to iOS users never seem to work.

**Comment by anmagr** [comment]
This is still a problem. This ticket needs to be reopened

**Comment by Miriam3141** [comment]
Just started being a problem for me too. Other user is on Android, I am on the latest iPhone version. Can open desktop to listen to the message.

**Comment by TM818** [comment]
This is an issue for me and has been for a long time - using the latest version of the Signal client (7.46.0) for the latest version of Mac OS (15.3.2), if I attempt to copy / paste text to a Signal chat window from a variety of apps, such as the latest version of Microsoft Word (16.95) for Mac OS, Signal interprets Word's text at an image, forcing me to first paste the text into an app like TextEdit to remove all formatting, then copy the text from TextEdit, THEN post it to the Signal chat window. It's been an annoyance for years.
