### ISSUE TITLE
Will Signal merge some new features of the Session messenger?

### ISSUE THREAD

**Issue by Pingmin** [signalapp/Signal-iOS#4541]
Sorry for this is just a feature discussion.

I want to know what Signal will do when I click "Reset session", so I just searched "Signal messenger reset session" yesterday(20200903), and then I just found the [Session messenger](https://getsession.org) accidentally. It's [forked from Signal messenger](https://github.com/loki-project/session-ios), but with some new features, such as it doesn't need a phone number, and uses the onion routing...

So I just want to know:

Will Signal messenger **MERGE** some new features of the Session messenger(e.g.: no phone number, onion routing), even though this will impact on user experience in someway?

Thanks!

@Imperiopolis-Signal @charlesmchen-signal

**Comment by Genis-Sage** [comment]
hey @Pingmin 

as you already received the answer to this question from greyson in the [Android repo](https://github.com/signalapp/Signal-Android/issues/9987),
you should close the issue here, as it will be the same answer


also directly tagging the devs is not the nice way

**Comment by Pingmin** [comment]
@Genis-Sage OK, and sorry. Thanks all!
