### ISSUE TITLE
Cannot delete a left group

### ISSUE THREAD

**Issue by siair** [signalapp/Signal-iOS#4542]
### Bug description
When searching in signal, a left group was found, and the group has no members. However, this group cannot be deleted by swiping to the left in the search results. And this group will not be displayed in the message list, but can only be found through search. Why does a group without any members continue to exist instead of being destroyed? 

### Device info
**Device**: iPhone 6

**iOS version**: 12.4.6

**Signal version:** 3.15.0.23

**Comment by soulseller** [comment]
I positively confirm that the issue still persists in version 5.0.3.0 on iOS 14.3.

**Comment by sunknudsen** [comment]
Also trying to find how to remove left groups from search... hopefully someone can help us figure this out.

**Comment by sunknudsen** [comment]
Reinstalling the app on iOS "fixed" the issue.

The issue is likely caused by a corrupted dataset on the device.

**Comment by halo** [comment]
I see the same behavior on Signal Desktop `5.27.0-beta.1` on macOS though. So I suspect this is not related to iOS alone. Is there maybe already an issue open for that?

> When searching in signal, a left group was found

To be precise, on iOS searching through existing contacts/groups does not reveal the deleted groups. However, when composing a message, those groups show up.

On Signal Desktop, both standard searching (filtering) existing contacts/groups **as well as** choosing contacts in the compose message search, show the previously deleted groups.

**Comment by halo** [comment]
Dear Bot, I think this problem is still relevant and has quite some potential to cause confusion to users. You may keep it open. Thank you Bot, you're the best 🔧

**Comment by halo** [comment]
Yes, dear bot. It is still causing friction.

**Comment by BionicBison05** [comment]
Issue is still present on 5.37.2.

**Comment by BionicBison05** [comment]
Still happens on 5.41 iOS. This may have always been the case, but it is not present on Signal Desktop 5.46.

**Comment by BionicBison05** [comment]
Still present on 5.46

**Comment by BionicBison05** [comment]
Present on 5.51 iOS. This is a potential privacy concern as when you delete a group, Signal stays "this chat will be removed from your device" when it clearly isn't. The bare minimum to protecting users of the service from potential threats such as data recovery is actually deleting data rather than hiding it and claiming that it was deleted.

**Comment by eugene-shvarts** [comment]
Present on 5.55 iOS, happy two-year bug-iversary

**Comment by BionicBison05** [comment]
Still present on 6.6.0.14

**Comment by BionicBison05** [comment]
Still present on version 6.39.0.11. Happy three years everyone.
