### ISSUE TITLE
Changing group name not reflected on settings page

### ISSUE THREAD

**Issue by james-culp** [signalapp/Signal-iOS#4545]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I open a group chat’s settings screen, I am able to tap the current group name to edit it. However, after accepting the new name, the group setting screen still does not show it until I go back to the list of group messages. There, the new name is shown. 

### Steps to reproduce

- start in main message list 
- open a group chat 
- tap the title of the chat to enter the group settings screen 
- tap the title of the chat again to edit it. Change it to “new title “
- accept the change, returning to group settings screen

**Actual result:** Old title is still shown until I leave the group settings screen 

**Expected result:** New title is shown on group settings screen

### Screenshots
 None

### Device info

**Device**: iPhone 11 Pro

**iOS version**: 13.7

**Signal version:** 3.15.0.23

**Comment by Imperiopolis-Signal** [comment]
This is resolved in the 3.17 beta that is currently in TestFlight.
