### ISSUE TITLE
Misaligned multi-select checkboxes

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4552]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when I try to delete multiple messages the checkboxes on the left side of the screen appear misaligned.

### Steps to reproduce
- select a message
- click on "multi select" icon

**Actual result:** misaligned checkboxes.

**Expected result:** aligned checkboxes.

### Screenshots

![image](https://user-images.githubusercontent.com/31325316/92919874-90e93980-f431-11ea-9cf0-f13823860625.png)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 13.6.1

**Signal version:** 3.17

**Comment by michelle-signal** [comment]
Unfortunately, I'm not able to reproduce this on my device. A couple questions that might help:

1. Are you able to consistently reproduce?
2. Does this only happen in certain conversations? Can you provide details on these (1:1, group, etc.)
3. Do you need to scroll around to make hit this? Or will this happen without any scrolling?
4. What language is your device set in?
5. Do the misaligned checkboxes occur on the same message? Or is it random? Do you see any pattern on the kinds of messages that have misaligned textboxes? (e.g. only outgoing, only incoming, only multiline, only narrow message)

**Comment by denver-s** [comment]
> * Are you able to consistently reproduce?
Unfortunately not, but I'm trying to reproduce and let you know if I find something.

> * Does this only happen in certain conversations? Can you provide details on these (1:1, group, etc.)
This happened with the Note to Self chat, 1 week disappearing messages (don't know if relevant).
It happened once weeks ago (don't remember which chat) but I just let it go, I thought it might've been a single case but as it reoccurred I filed this issue.

> * Do you need to scroll around to make hit this? Or will this happen without any scrolling?
When I filed this bug I tried both scrolling to the bottom and scrolling up. In both cases the bug occurred.

> * What language is your device set in?
Italian.

> * Do the misaligned checkboxes occur on the same message? Or is it random? Do you see any pattern on the kinds of messages that have misaligned textboxes? (e.g. only outgoing, only incoming, only multiline, only narrow message)
I tried many times and it was not random. The messages were all outgoing (Note to Self), single-line (I did not test with multiline messages) and of various length.

> * Do you have any other details that might be helpful?
I cannot reproduce at the moment but I will do my best to do so.

**Comment by denver-s** [comment]
It just happened again, now with horizontal view. Didn’t do anything special.

![F8800BE4-CDFC-4A44-B6ED-A4E94DF2D3EF](https://user-images.githubusercontent.com/31325316/92994662-952e5900-f4fc-11ea-9e3b-072c0742360d.png)

**Comment by denver-s** [comment]
Notice that like the other screenshot, it’s just the first two visible checkboxes that have this problem.

**Comment by elisioff** [comment]
> 1. Are you able to consistently reproduce?

You should be able to reproduce this if you:
1. open a conversation
2. scroll up a little bit
3. go back to the conversation list (leaving the scroll at that point)
4. open the same conversation
5. scroll down
6. enter edit mode by tapping any bubble (surely at least by long pressing the ones at the bottom)

> 5. Do the misaligned checkboxes occur on the same message? Or is it random? Do you see any pattern on the kinds of messages that have misaligned textboxes? (e.g. only outgoing, only incoming, only multiline, only narrow message)

So far it has happened to me only on incoming messages

> 6. Do you have any other details that might be helpful?

If you scroll while in the edit mode the bubble will realign once they go off and back in screen. So I'd guess reusing cells fixes this

**Comment by denver-s** [comment]
Yes! I can replicate as @elisioff perfectly explains.

**Comment by denver-s** [comment]
I think this bug has been fixed recently.
