### ISSUE TITLE
Can’t link to iPad device after upgrade

### ISSUE THREAD

**Issue by kumogithub** [signalapp/Signal-iOS#4555]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It keeps saying I need to update to latest version in iPad but I already did.

### Steps to reproduce
Just link the account with iPad device using the latest version 3.17.0.15

**Actual result:** Describe here what happens after you 
You need to update your version

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michelle-signal** [comment]
Could you please try reproducing and [grabbing logs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) from both devices? Instead of emailing support, just copy the URLs and paste them here. Thanks!

**Comment by kalehv** [comment]
I had the same issue. Probably not the solution you'd like but reinstalling iPhone app made it work for me. It linked successfully with both macOS and iPadOS apps. Definitely a bug though.

**Comment by philnord** [comment]
I also have this issue on both iPad and Mac. If necessary I can try to get logs as well?

**Comment by charlesmchen-signal** [comment]
@philnord @kalehv @kumogithub are you in our beta program?

**Comment by philnord** [comment]
> @philnord @kalehv @kumogithub are you in our beta program?

I am not.

**Comment by philnord** [comment]
> I had a same issue. Probably not the solution you'd like but reinstalling iPhone app made it work for me. It linked successfully with both macOS and iPadOS apps. Definitely a bug though.

If I do this, will the current messages and data be lost? Thanks in advance!

**Comment by kumogithub** [comment]
> @philnord @kalehv @kumogithub are you in our beta program?

Hi, I am not in your beta program. Thanks for looking into this

**Comment by kalehv** [comment]
> @philnord @kalehv @kumogithub are you in our beta program?

Neither am I but I'm on iOS 14 Beta 8, iPadOS 14 Beta 8 and macOS 10.16.6 (latest GA) if that matters.

Attaching a screenshot of iPadOS app error when I tried linking.![image](https://user-images.githubusercontent.com/588703/93108743-05a5b900-f668-11ea-81d0-d975fd46a532.jpeg)

**Comment by kumogithub** [comment]
I notice this problem has been fixed in version 3.17.1.  Thanks
