### ISSUE TITLE
Displayed waiting time between registration events does not match actual waiting time

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-iOS#4559]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During several attempts to transfer data from an iPad to an iPhone (see #4558), the Signal was reinstalled multiple times on an iPhone. Each time, a registration was necessary. However, after some attempts, a message tells you to wait for a minute (in German) since there were too many registration attempts. However, even on a retry after several minutes the same error message is shown.

### Steps to reproduce
- Deinstall and reinstall Signal on an iPhone several times in a row
- Register your phone number each time.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
I expect the time between registration attempts that is shown in the error message to match the actual backoff time.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The message tells to wait for 1 minute (in German) each time although it does not work even after a few more minutes.

### Device info
**Device**: iPhone X

**iOS version**: 14

**Signal version:** 3.17.1

### Link to debug log
After several attempts, my friend got frustrated and deleted the app immediately. No chance to get a log.

**Comment by Buddabrezn** [comment]
Same issue here

**Comment by d108** [comment]
I don't want to reopen this issue unnecessarily, but I found the same problem as @merkste when registering a phone number. We can improve the registration experience if we receive a critical server value.

Many calculations of registration wait times depend on the "Retry-After" HTTPS response header from a Signal server. Unfortunately, the server doesn't appear to deliver it, along with the number of seconds before a subsequent attempt could succeed. 

Instead, the displayed wait times come from fallback values like one or five minutes. However, the actual duration could be much longer, but we cannot know its exact value without the header.

The described results are reproducible when repeatedly registering a phone number.

![reporting of times@0 5x](https://user-images.githubusercontent.com/3375306/227802843-e256c0c2-ed45-442d-8251-03804e6a55f0.png)
