### ISSUE TITLE
iOS client doesn't receive stickers sent from Android

### ISSUE THREAD

**Issue by koponomarenko** [signalapp/Signal-iOS#4562]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS client doesn't receive stickers sent from Android

### Steps to reproduce
It may be hard to describe how I actually got into this problem. Because at the beginning the stickers were actually delivering to iOS from Android.
I have an Android phone, Samsung S10+, Android 10. I have also installed a few sticker packs from this website https://signalstickers.com/ .
The sticker packs I installed (in this order): 
- Tarantinos by Telegram Mirror
- Buddhismus by mattuu
- Rage Faces by 4chan
- Rick and Morty by floopyb
- Classic memes by Internet
- South Park by Comedy Central
- South Park by South Park
- UNIX Stickers by Szymon
- SpongeBobMemePants by not a pinhead
- SpongeBob by Nickelodeon
- Mr. Bean
- Mr. Bean by Ulyana Tkachenko

At first there was no problem. All stickers were received by iOS. But after a few days I installed these new stickers:
- South Park by w1ze
- Quentin Tarantino by Serbun

And I noticed that people didn't receive those stickers from the last two packs. Then, some iOS users were able to receive those stickers, while some stopped receiving even the default preinstalled stickers.

The IOS version is 13.7, 13.6.1, 14.

**Actual result:** Stickers are perfectly sent from my device (Android 10), but not shown in the signal app on iOS (while there is IOS notification that a message was received) - there is nothing in the app, literally no message.

**Expected result:** iOS users receive and see stickers sent from Android.

### Device info

**Device**: Samsung S10+ (Android 10), Apple iPhone XR.

**iOS version**: 14

**Signal version:** 4.71.5

### Link to debug log
IOS
https://debuglogs.org/9ced526ac6efe361eb9102252454bdb8736a534f9bcb643bf9706f3df03fcd3d.zip
Android
https://debuglogs.org/d76de1dfa0fd6b0a47fdccd84cce8f3123c2ad3d45f5e62093377f87649f4d4a

**Comment by koponomarenko** [comment]
![Screenshot_20200920-133931_Signal](https://user-images.githubusercontent.com/3629232/93709507-56755000-fb47-11ea-9982-814f85084af2.jpg)

![signal-2020-09-20-133902](https://user-images.githubusercontent.com/3629232/93709516-65f49900-fb47-11ea-802e-6f95c96473a4.png)

**Comment by makarychev** [comment]
Hi,

Same behavior on Windows 10, Desktop client for me. If you don't install stickers manually you cannot see received one.

**Comment by larryv** [comment]
I'm seeing the same behavior as the original reporter on iOS (v3.17.1.1, iOS 12.4.1), from some Android users but not others. In the macOS desktop client (v1.36.1, macOS 10.14.6 build 18G6020), affected stickers are displayed as generic file icons—I can even click on them and download and view the stickers.

**Comment by romainricard** [comment]
If this can help, the South Park sticker pack seems to have been created via the Desktop Sticker Creator tool, not from API or other mean. ([source](https://www.reddit.com/r/signal/comments/ei9cjk/south_park_sticker_pack/fcsje47/?context=3))

**Comment by Imperiopolis-Signal** [comment]
Thanks, we're aware of this issue. There is a bug in Signal-Android causing this behavior and hopefully it will be addressed soon.

**Comment by koponomarenko** [comment]
@Imperiopolis-Signal should we mention the bug id here so it is linked?

**Comment by schmeat** [comment]
Still experiencing this issue. 

### The following packs do not work:

- https://signal.art/addstickers/#pack_id=3bc77ee5ddace6200746010bcc6435c4&pack_key=5fb91b4df31f6562c366253b7416ed470ddc294a205d57a9810fba52348fc002
- https://signal.art/addstickers/#pack_id=f3038d1e6d8a45df6c5223c0b7f01947&pack_key=2025a3d857598eef5c8f0bbf61a27506143351fd154316477bab00ebeffb35a8
- https://signal.art/addstickers/#pack_id=d61a5dec78bab59cdc38d964c8a9b461&pack_key=dbb6c5939df09d71c717e876a15ec364d4746f702cb2744520f9d39d397c7500

### The following pack does work:

- https://signal.art/addstickers/#pack_id=3089661aee8e8ccf6a2f7ec85f40cfb7&pack_key=0276fee8944718fa4799e0f1e78a43925d76595b8b55fcd16eb0897164a7ca0c

### This animated pack only works if the user manually downloads it:

- https://signal.art/addstickers/#pack_id=bc593c890809a5374f42448acb1bbbd2&pack_key=6a0947cada9d0450ae3bb6e94c5d16c09cf5ad01ffefc0ac2024940d0cae509a

### Debug Logs:

- https://debuglogs.org/eced43efd8ea32296669e1c663f066f4928d73943353d40cd50f5bfe2d136024.zip


![signal-2021-02-14-131918](https://user-images.githubusercontent.com/1139817/107885355-c1913b80-6ec7-11eb-9faa-e637d5307ec1.png)

**Comment by bammerlaan** [comment]
Looks like this issue is still happening. I was sending my friend who's using iOS stickers from my Android device, and the stickers I downloaded from signalstickers.com didn't work. The default French bulldog ones did work.

**Comment by h45h74x** [comment]
Same here! I'm on Android and used [Adhesive](https://github.com/signalstickers/Adhesive) to convert my Telegram stickers to Signal. After using the stickers for ages, I found out yesterday that my girlfriend doesn't see any of them on her iPhone 15.

**Comment by crazycrystals** [comment]
Just because it's been three months since you addressed something doesn't mean it went away. It just means you ignored an issue until it disappeared, but it's still affecting users. Remove the fucking stale bot, it's caused nothing but problems
