### ISSUE TITLE
Wrong contact shown for non-signal call

### ISSUE THREAD

**Issue by ReedyBear** [signalapp/Signal-iOS#4563]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My friend who uses iOS receives spam calls that appear to be from me (I'm on Android)

"This is the second time it’s said that you’re calling me signal and I answer and it’s not you. It’s spam. (Or maybe the first one was a political call? Idk) what the heckkkkkk though," says my friend
 

### Steps to reproduce
- It appears to be intermittent and triggered by external actors & does not correlate with me actually calling my friend

**Actual result:** iPhone shows i am calling & signal is connecting audio

**Expected result:** iPhone would show phone number of spam caller & would NOT be connecting Audio to Signal

### Screenshots
![Capture+_2020-09-22-15-52-10](https://user-images.githubusercontent.com/8450080/93936361-b3aa0680-fceb-11ea-9063-3460e9fd412a.png)

### Device info

**Device**: iPhone XS Max

**iOS version**: iOS 14

**Signal version:** (friend failed to give me this)

### Link to debug log
I asked my friend to send it to me when/if it happens again, at which time I will post it. I'll also share my own debug log at that time if i can, in case it's malware on my phone or something?

**Comment by Imperiopolis-Signal** [comment]
The only way I can imagine this would happen is if they have other phone numbers in their contact for you on their phone beyond your actual number. Maybe a former number that you no longer use? Regardless, more information is needed for us to do much of anything here.

**Comment by Taeluf** [comment]
Just checked. No old numbers for me. That shouldn't try to connect Signal anwyay, though, right? I would think Signal would "know" which numbers to connect it's own audio for. & They said the actual number shows in their call history. I know that's not enough to go on. 

Hopefully I'll get you a debug log soon (or hopefully it doesn't happen again lol)

**Comment by Imperiopolis-Signal** [comment]
The only way a call can occur via Signal is if someone started a call via Signal. My theory is that they had another number in their system contacts with your name, but someone had registered that number with Signal. What do they see in the Signal app? Is there a record of a call in their conversation with you? Do you see a call record in the conversation on your phone?

**Comment by Imperiopolis-Signal** [comment]
I’ll also add that this is something that is almost certainly user error in some way, I’m not sure how much help debug logs will be here. Your friend needs to identify in the signal app where that call initiated. It’s also possible someone just set their profile name to be your name and called them.

**Comment by antondomratchev** [comment]
I recently observed the same issue. I think this might be an iOS14 bug rather than Signal bug.
