### ISSUE TITLE
Use in xcode12 with Swift 5

### ISSUE THREAD

**Issue by ksd711** [signalapp/Signal-iOS#4565]
I want to use SignalServiceKit with Swift 5 and xcode 12 but its giving 105 errors.

please see attached screen shot.
Can you please suggest something what to do on urgent basis because i want to update my app urgently.
![Uploading Screenshot 2020-09-24 at 2.37.28 PM.png…]()

**Comment by Imperiopolis-Signal** [comment]
We don't support Xcode 12 yet, currently only Xcode 11.6 is supported.
