### ISSUE TITLE
Only sent messages syncing

### ISSUE THREAD

**Issue by chrisandtre** [signalapp/Signal-iOS#4566]
iPad
Android phone

Yesterday iPad stopped receiving messages, though messages being sent from ipad, do show across devices

https://debuglogs.org/96b740866611f54558ff4292546affd4d23c0ec1e2e5278a1f9ed43f774bd59b.zip

**Comment by punctuationmarks** [comment]
Have this same issue, after clearing all messages on machine. Sync only started after I sent an initial message and all messages previously "received" between clearing messages and first message sent were never received
