### ISSUE TITLE
Muting then re-enabling microphone doesn't work in audio call

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#4567]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Muting then re-enabling microphone doesn't work in audio call.

### Steps to reproduce
- Receive a Signal call
- Answer it, speak
- Use microphone mute button for muting in call screen
- Re-enable microphone with the same button

**Actual result:** 
The caller doesn't hear me even if I re-enabled my mic on call screen.
If I repeat turning off-on-off-on-... mic muting button it doesn't help either, my mute remains muted.
I have to hang up and call again, or wait for being called. Then (after re-calling) my mic. works again.

**Expected result:** 
My microphone should work again if I re-enable it in call screen.

### Screenshots
None

### Device info
iPhone SE 2020

**iOS version**
14.0

**Signal version:**
3.17.5.1

### Link to debug log
https://debuglogs.org/4f68bfddc5d04d43854bc77b176c45856f439e7ca7a91e4b5e995fd4ef1e1a60.zip

**Comment by antondomratchev** [comment]
Observed on 14.2 Beta as well

**Comment by Imperiopolis-Signal** [comment]
Thanks, we've been able to reproduce this issue and are looking into it. It appears like a bug introduced by Apple in iOS 14, but hopefully we can workaround it. For now, if you unlock your phone the in app mute button should work correctly.
