### ISSUE TITLE
Unable to use “select more photos” feature of iOS 14 on iPhone

### ISSUE THREAD

**Issue by Nick-SHM** [signalapp/Signal-iOS#4569]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Describe here the issue that you are experiencing.

Signal is not working well with iOS 14’s feature to grant only access of selected photos to an app on iPhone. The photo picker to select more photos inside the app disappears immediately after showing up. The issue isn’t present on iPad.

### Steps to reproduce
- Use Signal on an iPhone with iOS 14.
- Set the photo permission of Signal to “selected photos.”
- Try to send a photo in Signal.
- Signal will prompt “select more photos” or “keep current selection.”
- Tap “select more photos.”

**Actual result:** the picker shows up and disappears immediately before any photo can be selected. If I then view Signal from multitasking, the picker can be seen (see the screenshot).

**Expected result:** the picker shows up and I am able to select photos.

### Screenshots

![IMG_3164](https://user-images.githubusercontent.com/10667496/94290892-6b117800-ff8d-11ea-98dc-18928021fa1c.png)

### Device info

**Device**: iPhone XR 

**iOS version**: 14.0.1

**Signal version:** 3.17.5.1

### Link to debug log

https://debuglogs.org/b88c5b02e715957a44ad4ad1aeaa784b335936a8363455594d5e60de1e58173a.zip

**Comment by Imperiopolis-Signal** [comment]
Can you share more detail on how you get into this state? We're unable to reproduce.

**Comment by Nick-SHM** [comment]
Here is a [screen recording](https://youtu.be/-n3A4jUzDvw) of the issue. This issue has been present on my iPhone since I upgraded to iOS 14.

**Comment by Imperiopolis-Signal** [comment]
Thanks, was able to reproduce now. Seems specifically related to when “screen security” is enabled. We’ll fix it up.
