### ISSUE TITLE
Disallow message previews from notifications on recipient’s phone

### ISSUE THREAD

**Issue by domgregori** [signalapp/Signal-iOS#4570]
Can we add a feature to disallow message previews on the recipient's phone? If the recipient hasn't turned off message previews, all it takes is someone to look at their lock screen, without unlocking the phone, to see messages that you sent. It's a privacy concern.

**Comment by Imperiopolis-Signal** [comment]
Signal is for messaging with people you trust, and that includes letting them decide how to manage their own device, so this is not a feature we're likely to implement. Also, in general feature requests should be brought up on our [community forum](community.signalusers.org). If you'd like to discuss this further, you can start a topic there.
