### ISSUE TITLE
Issues in Pods when updating App from Swift 3 to latest 

### ISSUE THREAD

**Issue by ksd711** [signalapp/Signal-iOS#4571]
Hello 
I have developed an App and is live on iTunes using Signals . Now when I am updating the app with latest Swift version and making it compatible  to latest Xcode , I am facing a lot of errors in PODS . All errors in Pods . 
I have changed all GitHub links ..i.e. source links which has been changed till date like 
#pod 'SignalServiceKit',           git: 'https://github.com/WhisperSystems/SignalServiceKit.git' with latest one and even other PODS too but still I get issues again and again and again . 
Can any body help me please to get them fixed so I can update my App to latest version .

**Comment by ksd711** [comment]
@Nora Trapp I need your help . Please can you guide me ...I have tried all whatever I could but still issues in Signal Service kit library .

**Comment by Imperiopolis-Signal** [comment]
We don't yet support the latest Xcode, but will probably in a month or so

**Comment by ksd711** [comment]
Hello 
its not about Xcode 12 , the app gives a lot of errors in Signal Service kit Pod when I run it even in Xcode 11 or 11.6 or any Xcode 11 version . 
Like I mentioned ...I have developed the app using using old GitHub signal repository but now since you have stopped it updating and when I am changing  it with new one ..it gives me a lot of issues in PODS .
So I need your help with his and I really appreciate any sort of help in this regard .

**Comment by Imperiopolis-Signal** [comment]
Sorry, but this is not something we actively support. You can ask on our [community forums](https://community.signalusers.org) and someone might be able to help you.
