### ISSUE TITLE
Error Sending WebP Images with iOS 14

### ISSUE THREAD

**Issue by tonyb486** [signalapp/Signal-iOS#4572]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal cannot send downloaded WebP images on iOS 14, possibly because it seems unable to strip them of their metadata.

This is related to #1547, but because iOS 14 now has support for WebP images natively, Signal now attempts to send them and comes up with a brief error message that is automatically dismissed, and an otherwise silent failure.  Given the native support of WebP images in iOS 14, this might be a significantly simpler issue than previously.

### Steps to reproduce
- Use iOS 14, which has native support for WebP Images
- Access a WebP image with Safari (_e.g._, this photo of a dog: https://i.imgur.com/LRoLTlK.webp)
- Save the WebP image to the camera roll from Safari by selecting "Add to Photos" after long-pressing on it.
- Select the image to send in a Signal conversation.
- Confirm and try to send the image.

**Actual result:**  An error pops up briefly but then goes away and the image is unsent.

**Expected result:** No error pops up, and image is sent.  Alternatively, if WebP images are not to be supported, a clear error message informs the user of this.

### Screenshots

![signal-2020-09-27-104020_001](https://user-images.githubusercontent.com/135970/94367619-e702e180-00ad-11eb-8e12-2010a9821c06.jpeg)

![signal-2020-09-27-104020_002](https://user-images.githubusercontent.com/135970/94367622-e9653b80-00ad-11eb-9bf6-053845c1accc.png)

### Device info

**Device**: iDevice X

**iOS version**: 14.0

**Signal version:** 3.17.5.1

### Link to debug log

https://debuglogs.org/df18ec1bc7634025c24dc9ebef65e13e9d6444a109feb82b1095703dad91a13b.zip

**Comment by tonyb486** [comment]
After investigating a bit, I've found a couple things:

1. The logic for determining image size treats every WebP image is animated because this is [hardcoded](https://github.com/signalapp/Signal-iOS/blob/4c0ce6b9a7a3dab875d5edb2d12fc096a372b05a/SignalServiceKit/src/Util/NSData%2BImage.m#L707), and I'm not sure why. 

2. When stripping metadata from a WebP image, [CGImageDestinationCreateWithData](https://github.com/signalapp/Signal-iOS/blob/4c0ce6b9a7a3dab875d5edb2d12fc096a372b05a/SignalMessaging/attachments/SignalAttachment.swift#L992) fails because, as far as I can tell, iOS 14 does not support creating WebP images, only decoding them.

**Comment by tschannik** [comment]
Don't know it this is related but if i sync some of my .jpg images from my Mac into my iCloud library i'm not able to share the file. The in-app screen looks exactly like the first screenshot in the issue but i'm actually able to send the file. But upon upload I and my group members only get a grey screen and nobody is able to download or open the file. 

If i send the exact same file from my Mac client everything looks good.

lmk if you need further screenshots/information

**Comment by tonyb486** [comment]
Looks like this was fixed with https://github.com/signalapp/Signal-iOS/commit/81b06025aa0d2ebbd851d58b138dd8c40d6c6b8e .
