### ISSUE TITLE
Picture captions are not working on iPad.

### ISSUE THREAD

**Issue by mateMathieu** [signalapp/Signal-iOS#4575]
### Bug description
On iPad, upload of a pic from iOS “share function”, the caption functions does not want to accept “Send” command. The button is not clickable.

### Steps to reproduce
- iPad Pro 11 2018, latest iOS
- End your drawing on Procreate for instance, send the picture to a friend on signal, and try to type a IM text caption to your pic.
- Cannot select the send function, the icon is misplaced/non active contact zone of the UI. I can type but cannot send it.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour): 
Unable to send, so “Cancel” then upload without caption.

**Expected result:** Describe here what should happen after you run the steps above:
Send the pic with caption, AND add the “Shift+Enter” option to send message using iPad’s keyboard.  ^^

### Device info
**Device**: iPad Pro 11 2018
**iOS version**: iOS 13.7
**Signal version:** latest

**Comment by mateMathieu** [comment]
Extra coding seems to apply on different level of conning and OS functionalities. It should be easily reproducible.

**Comment by jwaschkau** [comment]
It only does not work in landscape mode. If you rotate the device to portrait mode the button works fine.
