### ISSUE TITLE
Internal Microphone Used for Audio Message Instead of Headphones

### ISSUE THREAD

**Issue by jneplokh** [signalapp/Signal-iOS#4576]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When recording an audio message, the internal microphone is used even if headphones (with a microphone of course) are connected.

### Steps to reproduce

- Connect headphones (with mic) to device
- Record an audio message with the phone
- Cover up the internal microphone when talking
- Play it back and you will hear the audio being muffled which shows the headphone microphone is not being used

**Actual result:** When recording an audio message, the phone's internal microphone is used.

**Expected result:** I expect that the headphone's/external microphone is used instead to record the message.

### Device info

**Device**: iPhone 8

**iOS version**: iOS 14.0

**Signal version:** 3.17.5

**Comment by Fennek88** [comment]
This issue does still persist and I wonder why this hasn't been tackled yet and why nobody else bothers about this.

**Comment by paintedbicycle** [comment]
Looks like the same issue as https://github.com/signalapp/Signal-iOS/issues/5399
