### ISSUE TITLE
Not able to archive my build after installing new pod. I installed new pod "Siren" but now my build fails in archive

### ISSUE THREAD

**Issue by HaritaDave** [signalapp/Signal-iOS#4579]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Imperiopolis-Signal** [comment]
This sounds like an issue in your own project, we don't provide support here for third party forks. You can try asking for support on our [community forums](https://community.signalusers.org).
