### ISSUE TITLE
iPadOS: Predicting typing hides the text editing field on “slide-over” arrangement

### ISSUE THREAD

**Issue by mateMathieu** [signalapp/Signal-iOS#4581]
- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the iPad, using a physical keyboard only. While using signal in a slide-over manner, the text editing field is hidden by the predicting text bar.

### Steps to reproduce
- Use a physical keyboard with your iPad
- Grab and slide-over the signal app while you are working with another app in the background (to see what is slide over go to http://support.apple.com/en-us/HT207582)
- Select the text editing field and start typing text to your best friend. The predictive text bar pops-up.

**Actual result:** The text is mostly hidden behind the predicting text bar at the bottom of the screen

**Expected result:** The typing field moves a little bit upward to arrange its space with the predictive text bar. Take a look at how iMessages does, it moves a little bit upward/shrinks the size of the whole slide-over’ed app.

### Screenshots
![IMG_0189](https://user-images.githubusercontent.com/3027020/95302341-1f5ea880-0882-11eb-9249-43b47638ffd4.jpeg)

### Device info
**Device**: iPad 11” 2018
**iOS version**: 14.0.1
**Signal version:** 3.17.6.2

**Comment by Imperiopolis-Signal** [comment]
We may be able to work around this, but this is a bug in iPadOS – the OS doesn’t accurately tell us when the predictive text bar is there, so we can’t resize to adapt to it.

**Comment by jos128** [comment]
I got a similar bug:

I can't complete sharing a file with signal, if it's in landscape orientation.

* When tapping the send button the shown above keyboard fragment appears and somehow blocks further interactions.
* No external keyboard or anything.
* Other apps don't have this bug, so I am not sure this is all down to iPadOS.
* Practical workaround seems to be turning the iPad into portrait mode, which immediately solves the issue.

**Comment by mateMathieu** [comment]
Yes you are right, this is also a problem with file upload that is related to iPadOS.
