### ISSUE TITLE
Unable to paste images in latest iOS from e.g. Imgur

### ISSUE THREAD

**Issue by fracture-point** [signalapp/Signal-iOS#4583]
### Bug description
I often paste images that are long-press-copied from websites, e.g. Imgur.  Something has changed recently (within the last ~3 weeks) such that this almost always fails now with the message "Unable to remove metadata from image". It seems to arise from the code added here - https://github.com/signalapp/Signal-iOS/pull/2907/files.  The only workaround is to screenshot the image + crop, which is clunky and time consuming.

### Steps to reproduce
- Long-press copy an image from a website, e.g. imgur
- Context-menu paste into a Signal Chat + press send
- The screen very quickly flashed the error "Unable to remove metadata from image" and then goes back to an empty message editor (no image).  

**Actual result:** The image is not sent.

**Expected result:** The image is sent.

### Device info
**Device**: iPhone Xr

**iOS version**: 14.0.1

**Signal version:** 3.18

### Link to debug log
https://debuglogs.org/8ecbbeb85eb6b5f0264bf9bc7a10853179b56b9ed82c0b2e465d5486a8095c86.zip

**Comment by FaultyJuggler** [comment]
Can confirm currently happening

**Comment by fumiakiy** [comment]
The root cause of this issue is the same as the other issue #4572 ; Copying an image in iOS 14 Safari copies the WebP image as WebP.

**Comment by h4knet** [comment]
Here is a video of the bug:

https://user-images.githubusercontent.com/1595901/104000791-0d511680-519f-11eb-89c3-1be07e3bfbfe.mp4

As we can see, the error message also disappear instantly, so it's hard for a regular user to read and understand the issue.

**Comment by h4knet** [comment]
I'm on beta 5.26.10 on iOS.
The issue seems to be fix with simply providing the URL now.

It would be **great** if Signal could actually support the file format instead of having the link to the file. :heart:

**Comment by h4knet** [comment]
Testing can be done by trying to share / save / upload file from the following URL : https://www.gstatic.com/webp/gallery/1.webp
