### ISSUE TITLE
https://debuglogs.org/964bd08efdc42ec0e1f8fcd711e84d792c5319a5c10adcb9a5b9f1e9ccd31619.zip

### ISSUE THREAD

**Issue by ltorres022716** [signalapp/Signal-iOS#4586]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Imperiopolis-Signal** [comment]
Without knowing what the issue is you're facing, this report is unfortunately not helpful
