### ISSUE TITLE
Cursor and text field unable to move.

### ISSUE THREAD

**Issue by XxBlackHatxX** [signalapp/Signal-iOS#4588]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The issue is when you’re typing a long text message the cursor has issues going to the correct location. In the text box scrolls up and down erratically and incorrectly.

Please note that this has been happening since The start of the iOS 14 beta. And has not changed since the official iOS version has been released. I am currently on the official iOS version and I have tried the most newest official version of signal. I currently have signal beta installed now. And in all of the above cases it has never worked. This used to work before iOS 14. And yes I have submitted a bug report to Apple as well but that was months ago and the issue is still present. This issue was not present in the official Apple messages up.

### Steps to reproduce
-  type something long enough that it requires the scroll bar to show up.
-try using the press and hold the space bar on the iPhone to move the cursor. Or try moving the cursor in iOS 14. You can also try tapping the location you want the cursor to go. It will not go to the correct location at all.

**Actual result:**  it’s scrolls a radically and the cursor never stops where you want it to. Even when using the space bar/iOS 14 cursor features it will not stop where you stopped the cursor. It will move somewhere else.

**Expected result:** Stop the cursor where I land the cursor. And stop the scroll bar from erratically moving and gradually move as the cursor is on the edge of the text box.

### Screenshots
I have a 34 second screen recording please let me know how I can share this.

### Device info
**Device**: iPhone 11

**iOS version**: 14.0.1

**Signal version:** 3.19.0.8

### Link to debug log

<!--  If this is a crashing bug, after filing this issue, email a copy of your latest crash report to support@whispersystems.org

**Comment by kpcyrd** [comment]
I have the same problem, composing long messages on signal iOS is really painful. I've started composing/editing long messages in the notes app and then paste them over to signal, although I think this workaround leaks the message content into icloud.

**Comment by idontcareaboutusernames65** [comment]
Same problem here and probably many thousand times more out there. Sent several complaints to Signal to no avail. Very glad that I‘m not the only one.

**Comment by XxBlackHatxX** [comment]
> I have the same problem, composing long messages on signal iOS is really painful. I've started composing/editing long messages in the notes app and then paste them over to signal, although I think this workaround leaks the message content into icloud.
> 
> 
> 
> **Device:** iPhone Xs
> 
> **iOS version:** 14.0.1
> 
> **Signal version:** 3.19.1.2

Same here. But what I do is so have a set the lock on the note first. When you setup your notes lock it uses end to end encryption according to the [official 2020 apple platform security documentation](https://support.apple.com/guide/security/secure-features-in-notes-app-sec1782bcab1/web) on their website. "The Notes app includes a secure notes feature that allows users to protect the contents of specific notes. Secure notes are end-to-end encrypted using a user-provided passphrase that is required to view the notes in iOS, iPadOS, macOS, and the iCloud website. Each iCloud account (including “On my” device accounts) can have a separate passphrase." Just make a title for the note first.

**Comment by XxBlackHatxX** [comment]
Update on this issue in signal beta 3.21.0.10 the drag and drop curser(holding the space) work better and stops where it is supposed to. But tapping where the cursed should go does not drop it on the right line and will cause it to scroll to a different part of the message like it was before.  The scrolling when moving the cursor using the space bar isn’t fixed it move to drastically and makes it hard to place the curse if it on a line towards the end or the beginning of the text box. Please let me know where to send this screen recording of the issue.

**Comment by eccgecko** [comment]
Would also like to add my voice to this. As a frequent user of Signal, and a composer of long messages, this bug is infuriating, and makes Signal unusable when composing long messages. So frustrating. When you press on a word, the cursor jumps to completely the wrong place. Or you try and scroll the message with the cursor using the space-bar press-and-hold method, and the cursor jumps from the bottom to the top and it’s impossible to slowly scroll the message and easily and accurately move it into position. It makes navigating a long message quite disorientating. Hope this gets looked into and fixed asap.

**Comment by XxBlackHatxX** [comment]
Just want to say this is still a problem and it's still very frustrating. I am surprised that it has not been resolved and it's already been a few months.￼

**Comment by martin-uplex** [comment]
Same for me! :(

**Comment by nadau** [comment]
Signal cannot be used productively with this bug, because editing longer messages takes a lot of time and brings a lot of frustration. I also don't want to use a workaround via other apps or devices, but want to have a functional messenger.

**Comment by XxBlackHatxX** [comment]
@nadau I completely agree. Especially since this bug has been happening since the beginning of the iOS 14 beta. They’ve had more than enough time to fix this but they have yet to do it. They really need to change their development schedule. To better time periods of fixing bugs and periods of feature development.

**Comment by Imperiopolis-Signal** [comment]
This is fixed in 5.0.1 (releasing to test flight in a few hours, app store in ~a day once Apple approves it)

**Comment by martin-uplex** [comment]
Works for me, thank you so much!! (5.0.1, iPhone SE1, iOS 14.2)
