### ISSUE TITLE
Please remove permission reminders

### ISSUE THREAD

**Issue by lil5** [signalapp/Signal-iOS#4590]
I would like to use Signal without allowing permissions to my contacts.

This is possible, except that every so often I get "reminded" about this (permission pop-up to allow access to contacts). This feels like coercion,

**Comment by Imperiopolis-Signal** [comment]
We're not going to remove the reminders. Signal works best when you provide access to notifications and contacts, and these reminders are generally helpful for people who didn't intentionally disable the settings. We used to receive a lot of reports that people "didn't see their contacts" or "didn't receive notifications" because they inadvertently denied these permissions – Signal now works better for those people. If you don't want to provide that access, you still don't need to – you can simply tap remind me later once a month and never provide access.

**Comment by acardona** [comment]
It's unfortunate that this monthly "request" looks like the ratchet dark pattern. Once granted, it's nigh impossible to undo. The optics of this choice are bad, even if there are valid use cases.

**Comment by nukeop** [comment]
I am going to bump this issue once a month

**Comment by SoKamil** [comment]
Just provide an option to disable it in super secret settings mentu that you have to type konami code to ender and then accept warning with big red disclaimer 2 times and then manually type in textfield „YES I CONSENT” all capital letters

**Comment by lpar** [comment]
I'll note that Signal doesn't upload any of the contact information, contact matching [is performed using hashes](https://signal.org/blog/private-contact-discovery/) generated on the device. The dialog really ought to say something about contact info not being uploaded.

That said, given that you are reminded about the contact permissions literally every time you go to create a new message:

<img width="1206" height="653" alt="Image" src="https://github.com/user-attachments/assets/fc0d99b6-54ac-48ec-8be5-f56c95b74fe4" />

…it seems particularly unnecessary to use a dark pattern and not have a "Don't Allow Access" on the pop-up:

<img width="1206" height="431" alt="Image" src="https://github.com/user-attachments/assets/d16504cd-229b-478b-afd9-175c8955e225" />

But for those looking for a way to disable the abusive nag message, you can give Signal partial access to your contacts and then only let it access a single dummy contact:

<img width="1206" height="1185" alt="Image" src="https://github.com/user-attachments/assets/b364402e-15f3-4837-8fa4-273794eb4aea" />

**Comment by nukeop** [comment]
Can we remove that now?

And while we're at it, if notifications are disabled, I don't want no "We'll remind you later". Don't remind me. I want them off.

**Comment by max-signal** [comment]
We’ve adjusted the contact permission reminder (in b51cdef35688aa391e5a0cc47da41f30bbcf85b9) to show just once per install.

**Comment by nukeop** [comment]
Hey everyone, are you ready to remove the reminders about contacts and notifications now?

**Comment by mikez** [comment]
@max-signal Thank you for listening. :)
Would it be possible to use a similar pattern for the reminder about showing notifications?
