### ISSUE TITLE
Have to scroll down to read newest messages

### ISSUE THREAD

**Issue by Sowers25** [signalapp/Signal-iOS#4592]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I get a new message from a contact and go into the app I have to scroll down to see it, every single time. It's super annoying and was not an issue 3 updates ago. This happens on my phone AND my partners phone. It started happening at the same time. It's super annoying and has sent me back to imessage because It's so annoying. 
### Steps to reproduce
Nothing, it's simply just there at all times.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone X

**iOS version**: 14

**Signal version:** 3.19.1.2

**Comment by briankung** [comment]
Have to agree, this is extremely annoying.

**Comment by Imperiopolis-Signal** [comment]
Thanks for the report, there is a fix for this issue in our upcoming 3.21 release. You can [join the beta](https://testflight.apple.com/join/8FHtd1Jq) to get this fix sooner.

**Comment by Sowers25** [comment]
I got the update for 3.21 and it is still happening. Why is this not a toggle option? It's incredibly annoying and makes the app unusable.
