### ISSUE TITLE
Unable to send any media (photos, videos, audio)

### ISSUE THREAD

**Issue by kaishin** [signalapp/Signal-iOS#4593]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to send media to any recipient.

### Steps to reproduce
- Attempt to send any media (stickers, images, recorded audio, etc).

**Actual result:** Failed to send with error "The operation couldn't be completed (SignalCoreKit.OWSAssertionError error 1)"

**Expected result:** Media should send without issues.

### Device info

**Device**: iPhone XS

**iOS version**: 14.0.1

**Signal version:** 3.19.1.2

### Link to debug log
https://debuglogs.org/6aedc242b394f88407a4477ce95c08761d7a647c10ee1983f411849559938223.zip

**Comment by kaishin** [comment]
I looked at the logs myself and I am seeing this line:

`SignalCoreKit.OWSAssertionError(errorCode: 31, description: "Missing location header.")`

I suspected it has something to do with location but I didn't find anything location related in settings.

**Comment by kaishin** [comment]
Looked at the source and ended up here: https://github.com/signalapp/Signal-iOS/blob/4b80dae93ad7452a434a615e4dd1f700b17ca83f/SignalServiceKit/src/Network/API/OWSUpload.swift#L399

Not quite clear to me where this header is set and I unfortunately don't have the time to pull the project locally for the time being.

**Comment by ltitus210** [comment]
I have the same "SignalCoreKit.OWSAssertionError error 1" error when sending from the iOS app. Media messages do successfully send if sent using Signal Desktop (v1.37.2) on MacOS.

Device info
Device: iPhone 11 Pro MWAR2LL/A
iOS version: 14.1
Signal version: 3.21.0.10

**Comment by kaishin** [comment]
This was fixed for me somehow after an update. Still not sure what the problem was so will leave it here until the maintainers decide to take action on it.

**Comment by ltitus210** [comment]
Ditto. Updating to iOS 14.2 resolved the problem. ¯\_(ツ)_/¯

**Comment by QUAKEULUS** [comment]
Just got this error while trying to send a 96MB video file in iOS

signal 5.4.0.17
14.4

**Comment by schmiggedi** [comment]
Hey @QUAKEULUS 

do you also have this issue with smaller files/videos? My sister has this issue with all videos and also with long voicemails. I created a topic in signal community for this. Would be great if you would participate so this issue gets a little more attention.

https://community.signalusers.org/t/unable-to-send-videos-photos/28517

Best regards.
