### ISSUE TITLE
Couldn't able to run the code. Pod installation issue

### ISSUE THREAD

**Issue by balu3083** [signalapp/Signal-iOS#4594]
Hi,
I have download the source code from your repo. When I try to pod installation I m getting an error. I am adding error screen shot with this post please check it.

OS = 10.15.7, 
Xcode = 12.0.1
Signal Version: 3.20.0.4
<img width="913" alt="Screenshot 2020-10-22 at 11 36 04 AM" src="https://user-images.githubusercontent.com/45266052/96832855-0f87bc80-145d-11eb-977a-9cf31cdeae37.png">

**Comment by Gulshan1993** [comment]
Because in your project no Third Party Folder That's why to show this error

**Comment by balu3083** [comment]
Hi,
I have added "Third Party" folder and tried to install it. again I am getting issue. I am adding screen shot below please check it.

Thank you
Balu
<img width="1185" alt="Screenshot 2020-10-22 at 2 24 56 PM" src="https://user-images.githubusercontent.com/45266052/96956697-72895a00-1516-11eb-977d-2d5fa7087ce3.png">

**Comment by gxzlolo** [comment]
> Hi,
> I have added "Third Party" folder and tried to install it. again I am getting issue. I am adding screen shot below please check it.
> 
> Thank you
> Balu
> <img alt="Screenshot 2020-10-22 at 2 24 56 PM" width="1185" src="https://user-images.githubusercontent.com/45266052/96956697-72895a00-1516-11eb-977d-2d5fa7087ce3.png">
hi,the problem is solved?

**Comment by balu3083** [comment]
No I m getting the error while installing pod 
"Error installing ZXingObjc"
Faild to download "ZXingObjc"

**Comment by balu3083** [comment]
Hi Any update regrading above issue?

**Comment by Guolanlan** [comment]
不用pod，直接clone，git clone --recurse-submodules https://github.com/signalapp/Signal-iOS
--recurse-submodules 这个不能去掉
clone 下来就有pod，
