### ISSUE TITLE
Add an option in the settings to disable permission reminders

### ISSUE THREAD

**Issue by lil5** [signalapp/Signal-iOS#4596]
I personally feel these reminders go against the privacy promise of this app.

An option in the settings to opt out of reminders would be handy.

As this option would be in the settings, and off by default, it should lessen any fears from support from any "non-power-users" that accidentally decline the permissions on installation

**Comment by lil5** [comment]
This relates to #4592

**Comment by Imperiopolis-Signal** [comment]
We only use github issues for tracking bugs, not feature requests. You can start a topic on our [community forums]https://community.signalusers.org) if you want to discuss this further.
