### ISSUE TITLE
Clicking group member who is not in system contacts freezes app

### ISSUE THREAD

**Issue by kaylee42** [signalapp/Signal-iOS#4597]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Note: I'm currently only in legacy groups as groups I'm in have not migrated over, so group here refers to the legacy groups.

When I am in a group, if I click a user to bring up the user-specific menu (not sure what this is officially called - it gives option to message, call, block, add to another group, view safety number, etc) it only functions as expected if the user is already in my system contacts. If the user is not in my system contacts, the app freezes and the only way to restore functionality is to quit and restart the app. This happens when clicking into the user-specific menu both from the group chat view (ie clicking on their avatar) or from the all group members view in the group settings. I am virtually positive the connecting thread is whether or not a given user is in my system contacts, as I've tested across multiple groups and users and it holds true for all of them (have tested four groups and ~20 users). This is particularly problematic because without being able to open the user-specific menu, there's no way to add the user to my system contacts and work around this.

### Steps to reproduce
- Create a group (unsure if required to be legacy group?)
- Add a user to the group who can add someone to it who isn't in your system contacts
- Attempt to click on the user who isn't in your system contacts, either by clicking their avatar in the chat or the group members list

**Actual result:** The entire app freezes - nothing else is clickable, or scrollable until you quit and restart

**Expected result:** You should get the user-specific menu for this user, allowing you to direct message them, add them to your contacts, etc. 
If this change was the result of some sort of privacy change where you can no longer see the phone number for users you don't know or something, at an absolute minimum the app should not freeze and you should receive some sort of notification for that.

### Screenshots
none included just cause i feel weird posting pictures of people's names and stuff without their permission? but there wouldn't be anything interesting to see anyway

### Device info

**Device**: iPhone SE (the original one, not the new one that just came out)

**iOS version**: 14.1 (however I actually just updated because I thought maybe a newer version of Signal would solve the problem - this was happening on 13 also but I'm not sure the minor version I was on)

**Signal version:** 3.20.0.4 (again, just updated and unfortunately am not sure the previous version I also saw this on)

### Link to debug log
Emailing most recent crash log

**Comment by simonv3** [comment]
I can confirm I'm seeing similar things on Signal 3.21.0.10, on iOS 14.1 on an iPhone 8. 

I have seen this before with a previous version of Signal (a couple of months ago), but I don't recall now if it had been fixed. Can confirm that I am able to click on existing contacts in my system, but that it crashes with users who aren't in my system.

**Comment by DanShockley** [comment]
Interesting. 
I can’t reproduce the freeze you describe. I’m on iOS 14.0.1, iPhone XS, Signal 3.19.1.2. 
But, I updated Signal and still can’t reproduce the freeze. In a group chat, I looked at the member list, then tapped someone who isn’t in my system contacts. No problem. It shows their info and gives me the option to add to system contacts. 
I’m still on iOS 14.0.1, while the reporter said they are on 14.1 - maybe that’s the difference? 
I wonder if there is some new privilege issue around system contacts causing the freeze.

**Comment by karerua** [comment]
I am also facing hang when i click on user in a group who is not in my contact list, app freezes. I have iphone 12 pro

**Comment by micja** [comment]
iOS 14.4 here, Signal 5.3.2 on an old iPhone SE. Exact same issue, happens every time. Not only is it impossible to send a private message to a group member who‘s not in my contacts, it also freezes the app and requires a restart.

**Comment by GeckoEidechse** [comment]
Same here

- Signal version 5.7.0.19
- iPhone SE 1st gen
- iOS 14.4

[Debug Log](https://debuglogs.org/ed1f7a3a2d709ac513cfcfd0a78326fbbd8a73889702778aa2a0ee593e250c28.zip)

**Comment by GeckoEidechse** [comment]
Fixed for me

- Signal version 5.26.10.0
- iPhone SE 1st gen
- iOS 15.2.1
