### ISSUE TITLE
Video orientation mismatch between iOS and Android

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#4598]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

If iOS video is landscape, then Android video renders as the middle third of this rectangle, as portrait orientation. There is then a gross mismatch between what the iOS user thinks is being shown, and what the Android user actually sees. There's no obvious way to toggle this behavior, for that matter.

### Steps to reproduce

- Initiate a video call between iOS and Android Signal installations. (This might also apply to other combinations that I didn't test.)
- Hold the iOS phone horizontally so as to create a landscape orientation. Then, no matter how the Android phone is oriented, it will always show the middle third vertical strip of the landscape.

**Actual result:** 

Android: "I said, hold the phone horizontally!"
iOS: "I am! Can't you see the left and right side of the street?"
Android: "No! I see only the road ahead! Don't you know the difference between portrait and landscape?!"

**Expected result:**

WYSIWYG, like it's been since the dark ages of UI design.

This sounds related, but not quite the same issue:

https://github.com/signalapp/Signal-Android/issues/9865

### Device info

**Device**: iPhone 7

**iOS version**: 14.1

**Signal version:** (latest as of this date)

**Comment by Imperiopolis-Signal** [comment]
This is a bug in the Android app - if your iPhone is in landscape the Android phone should render in landscape. Please open an issue on that project.
