### ISSUE TITLE
User running latest version but can't be added to new groups

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#4605]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to add a new users to a v2 group, it says that they need to upgrade their signal where as they're running the latest version 3.21.0.10. The group invitation link doesn't work for them either.

### Steps to reproduce
- create a new group on Signal for ios
- select members to be added
- generate a group invite link as an alternate way to join the group

**Actual result:**

one of the members who is running 3.21.0.10 doesn't get added. screen shots added below.

**Expected result:** 

user should be added to the group as they're running the latest version. group links should also work. 

### Screenshots

This is what the admin sees:
![signaladmin](https://user-images.githubusercontent.com/453701/97478599-8a524b00-1927-11eb-9d49-831bf7c9c272.jpeg)

and this is what the user sees after they try the group invite link:
![signaluser](https://user-images.githubusercontent.com/453701/97478636-976f3a00-1927-11eb-872a-e0b472ce1159.png)

### Device info

**Device**: iPhone

**Signal version:** 3.21.0.10

**Comment by phil-davis** [comment]
I had this problem, but after updating all linked desktop Signal installs (2 of them) and unlinking an old one that I could not reach, I am able to join a new-style group.

**Comment by mrphs** [comment]
@phil-davis thanks for the tip! Did you have to do this as the admin or as the user?

**Comment by mrphs** [comment]
Ok we just tried it. First the user did this and it was still the same. Then the admin re-linked the signal desktop and the user could request to join the group via the link but interestingly enough, their request doesn't show up for admin in the pending list.

**Comment by mrphs** [comment]
oh the workaround for that was that admin had to quit the app entirely and start it again. It was only then that request to join was shown.

**Comment by phil-davis** [comment]
> @phil-davis thanks for the tip! Did you have to do this as the admin or as the user?

My desktops are Ubuntu. I update with `sudo apt`... so in my case updating is an "admin" thing. But it might depend on your OS and how you installed Signal.

**Comment by mrphs** [comment]
> > @phil-davis thanks for the tip! Did you have to do this as the admin or as the user?
> 
> My desktops are Ubuntu. I update with `sudo apt`... so in my case updating is an "admin" thing. But it might depend on your OS and how you installed Signal.

to be clear, i was asking whether the admin of the group needed to re-link or the user that needed to be added.
