### ISSUE TITLE
Landscape orientation issues when sending or recording media

### ISSUE THREAD

**Issue by XxBlackHatxX** [signalapp/Signal-iOS#4607]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When moving the phone in landscape while sending ANY type of media or in the middle of recording a VM the action current action will stop.

### Steps to reproduce

Scenario 1
Send a photo, video, or VM in portrait mode. While the media is still uploading move the device to landscape. The media will stop uploading and then start over.

Scenario 2
Start recording a voice message in portrait mode. While still recording even with recording lock on turn the device to landscape. The recording will be deleted and you will need to start from the beginning.

**Actual result:** 
Scenario 1
The media will stop uploading and then start over.

Scenario 2
The recording will be deleted and you will need to start from the beginning.

**Expected result:** 
Scenario 1
The media will still continue to upload no matter how many times you turn the device.

Scenario 2
If recording lock IS OFF the recording will stop but you will still be able to send or delete it.
If recording lock IS ON the recording will continue regardless of how many time you rotate the device.

### Device info

**Device**: iPhone 11

**iOS version**: 14.1

**Signal version:** 3.21.0.10

**Comment by 4ndre4s** [comment]
I have the same problem.

**Comment by elahmo** [comment]
I am having this issue since I started using signal, and I want to literally break my phone and stop using technology completely when this happens.

**It is the MOST ANNOYING THING IN THE WORLD SPEAKING FOR 3 MINUTES AND THEN SUDDENLY TILTING PHONE A BIT AND SEEING IT VIBRATE BECAUSE SIGNAL THOUGHT I WANTED TO CHANGE TO LANDSCAPE IN A MIDDLE OF A VOICE RECORDING. HAVING TO REPEAT WHAT YOU WERE SAYING IS ONE OF THE MOST DIFFICULT THINGS IN THE WORLD**

Please fix this.

**Comment by elahmo** [comment]
It is no relevant, most of the people I know have moved away from Signal due to terrible UI. It's a shame but issues like this that are open for years are a reflection of how neglected the actual app is.

**Comment by elahmo** [comment]
No one cares about Signal anymore. Bugs like this make people use any other viable option since it is obvious the foundation or developers do not care enough about a platform that has billion of users.

**Comment by NiklasBr** [comment]
Yes

**Comment by elahmo** [comment]
Thanks bot!

It's a shame that a great project like this suffers from childish bugs, such as this one, which end up preventing mass adoption of it.

**Comment by tr1ng0** [comment]
This is fixed since version v5.47 see: #5404

**Comment by elahmo** [comment]
Great! Glad to see it fixed, a bit sad it took two years.

**Comment by EvanHahn-Signal** [comment]
Looks like this was fixed. Closing this issue.

Please open a new one if you're still running into problems.
