### ISSUE TITLE
Messages not being received, contact shows Received message was out of sync

### ISSUE THREAD

**Issue by kalenpw** [signalapp/Signal-iOS#4608]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
NOTE: This issue affects people on Android, and iOS. I suspect may be server issue but with their issues turned off I am reporting here as I, the reporter, use iOS. 

Messages not received from one contact in group chats. In private messages we see 'Received message was out of sync'. Resetting the session fixes the issue, but it will come back. 

### Steps to reproduce
- Create group chat 
- Communicate in it throughout week
- Eventually we notice one person hasn't been sending messages
- We can then each go to that persons contact and click reset session at which point their messages start coming in

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
We do not see this persons messages without frequently having to reset session

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Expect to not have to reset session to continue receiving messages

### Screenshots

![IMG_1788](https://user-images.githubusercontent.com/13550971/97754943-f8c91180-1abd-11eb-8a41-6ec382b31612.jpg)

### Device info

Device whose messages are not being received

**Device**: Samsung Galaxy S10+
**Android version**: 10
**Signal version:** 4.75.4

----

The following devices are the ones NOT receiving person's messages

**Device**: iPhone SE 2
**iOS version**: 14.1
**Signal version:** 3.19.0.7 

**Device**: iPhone XS
**iOS version**: 14.0.1
**Signal version:** 3.21

**Device**: iPhone SE 2
**iOS version**: 13.7
**Signal version:** 3.21

**Device**: Galaxy A50
**Android version**: 10
**Signal version:** 4.75.4

### Link to debug log

https://debuglogs.org/3de3ac62b710b7d5b7b0daea53e7c36b0e2a7fb30b0dded79c1c9db0b56bc7c8.zip

**Comment by musm** [comment]
We are also having he exact same issue.
