### ISSUE TITLE
Link share preview image showing "your browser is deprecated" message.

### ISSUE THREAD

**Issue by niftynei** [signalapp/Signal-iOS#4609]
### Bug description
A 'link share preview' for a YouTube Music link is showing a "Your browser is deprecated" message in the link preview.

Link shared: https://music.youtube.com/watch?v=jg51kFe7CWU

### Screenshots
![image](https://user-images.githubusercontent.com/1097769/97786326-cd572d00-1b78-11eb-8750-4191cd908330.png)

### Device info
**Device**: iPhone Xs

**iOS version**: 13.7

**Signal version:** 3.20.0.4

**Comment by Genis-Sage** [comment]
hey @niftynei 
as you see, i copied the issue over to the Android issue tracker,
but some days ago, i did not get the "outdated" message anymore

how is it for Signal-iOS?
