### ISSUE TITLE
Signal issu

### ISSUE THREAD

**Issue by shl23** [signalapp/Signal-iOS#4612]

**Comment by shl23** [comment]
https://debuglogs.org/5de07f0401e63c2bd59592fda4c232768d7da9a3258788cc049ee576ed8478f7.zip

**Comment by Genis-Sage** [comment]
hey @shl23 
I am not a signal dev, but I am quite sure, that the devs will have a hard time to find the issue, which you want to report,
if you don't say what you want to report

also, there is an issue template, at least, if you open a issue though a brower:



- [ ] I have searched open and closed issues for duplicates
  

---

### Bug Description



### Steps to Reproduce



1.  step one
2.  step two
3.  step three

Actual Result:



Expected Result:



### Screenshots



### Platform Info

Signal Version:



Operating System:



Linked Device Version:



### Link to Debug Log

**Comment by Imperiopolis-Signal** [comment]
As mentioned, we need a description of the issue you're facing. I'm closing this for now, but if you follow up with more information we can consider re-opening the issue.
