### ISSUE TITLE
Note-to-Self: Signal Profile Picture/ iOS Contact Photo is not displayed

### ISSUE THREAD

**Issue by privacy-advo** [signalapp/Signal-iOS#4615]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
The Note-to-Self is not able to display the Signal Profile Picture or iOS contact photo. 

### Device info
**Device**: iPhone 11
**iOS version**: 13.7
**Signal version:** 3.21.0.10

**Comment by Imperiopolis-Signal** [comment]
This is by design, we show a "note-to-self" specific icon. If you'd like a change to this behavior, you can make a feature request on our [community forums](https://community.signalusers.org/). GitHub is only used to track bugs.
