### ISSUE TITLE
Floating Bottom-Toolbar-View

### ISSUE THREAD

**Issue by lighthouse16** [signalapp/Signal-iOS#4617]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I will call it the Bottom-Toolbar-View... its floating when reopening the app

### Steps to reproduce
- open a chat
- tap on textfield so keyboard appears 
- go to homescreen
- open signal again
- results in a floating Bottom-Toolbar-View

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
a floating Bottom-Toolbar-View

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Bottom-Toolbar-View should stick to the bottom of the screen... or reopen the keyboard

### Screenshots
![IMG_1343](https://user-images.githubusercontent.com/42917186/98460805-b7b0bb80-21a7-11eb-9303-81e7ae05cef1.jpg)

### Device info
**Device**: iPhone 12 Pro
**iOS version**: 14.2
**Signal version:** 3.21.0.10

**Comment by Imperiopolis-Signal** [comment]
I am unable to reproduce this behavior, does it happen reliably for you? If possible, could you provide a video recording of what you’re seeing?

**Comment by lighthouse16** [comment]
So when I wanted to record a video... it stopped happening... when you open back Signal from homescreen or the App Library it doesn't happen. It only happens when you open from **Siri Suggestions**. Signal not on the homescreen anymore for me..
I open a lot of apps by swiping down to open Spotlight. Often the app I want is available in Siri Suggestions. Also when you open the app from a **Spotlight search** it behaves the way written above..
