### ISSUE TITLE
Apple Maps Sharing not working like Google Maps Sharing

### ISSUE THREAD

**Issue by maxbrandes** [signalapp/Signal-iOS#4618]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If I send a location (lets say a coffee place where I want to meet) and use Google Maps, everything is fine. It shows the location of the business in the chat, including the name of the business. If I send a location from Apple Maps however, it only sends the street address to signal, not the business name.

### Steps to reproduce
- Open Google Maps
- Search for a business location, like a coffee place
- Use the iOS sharing menu to send the place to a signal contact
- The business is being send to the signal contact. It shows the business name
- Open Apple Maps
- Search for a business location, like a coffee place
- Use the iOS sharing menu to send the place to a signal contact
- The send text does not contain the business name but only the street detail

**Actual result:** Location sharing of a business (e.g. coffee place) does result in sending the street address instead of the business itself

**Expected result:** I would expect to send the business name

### Screenshots
![IMG_4293](https://user-images.githubusercontent.com/5220611/98471407-de8ce300-21e3-11eb-84c5-f069ca78865d.png)

### Device info

**Device**: iPhone 11 Pro

**iOS version**: 14.2

**Signal version:** 3.21.0.10

**Comment by Imperiopolis-Signal** [comment]
This is not something we control, but rather the Open Graph tags that Apple and Google provide on their websites. You can open a bug with Apple requesting they add more details OG tags to apple maps.

**Comment by maxbrandes** [comment]
![F5FAB440-7C3B-4A7F-8CB6-D0CAF8B64B67](https://user-images.githubusercontent.com/5220611/98779449-2c783580-23f4-11eb-88f5-3cfa54c08ad2.jpeg)

@Imperiopolis-Signal 
Why does it then work with WhatsApp, telegram and iMessage? The example image is taken from WhatsApp

**Comment by Imperiopolis-Signal** [comment]
It appears you're not sharing a link there from Apple maps, but rather an image and some text. Signal prefers to share the link as this is more useful generally. Other messaging platforms may have add a custom special case for Apple maps to not share the link, to work around the fact that Apple maps is broken and doesn't provide proper OG tags.
