### ISSUE TITLE
Account Transfer attempt crashes on opening QR code screen (iOS 14.1)

### ISSUE THREAD

**Issue by qmeandm** [signalapp/Signal-iOS#4620]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Attempting to transfer accounts from an old device to a new device on iOS 14.1. Signal can open and get through the text-verification process. When the QR code reader opens the app crashes immediately. Upon reopening the app, user must once again verify the phone number via text. If attempted too often user gets rate-limited "you have tried too often. please wait a minute."

### Steps to reproduce
- open unregistered signal app on a new iOS 14.1 device
- input phone # and verify with security code received via text
- tap 'transfer from iOS device' when prompted

**Actual result:** App crashes / force quits immediately and iOS returns to the home screen

**Expected result:** Result is described on the signal support page:
https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore

**Device**: iPhone 8 and iPhone 12

**iOS version**: 14.1 (both devices)

**Signal version:** 3.21.0.10

### crash log submitted via email.

**Comment by Imperiopolis-Signal** [comment]
Please try installing our beta build on your new phone as it may have a fix for this issue. You can safely install the app store version over it after transferring if you don’t want to use the beta. https://testflight.apple.com/join/8FHtd1Jq

**Comment by qmeandm** [comment]
Hi Nora,

After installing the beta and trying again, Signal is now able to generate
the QR code without crashing. However, when the QR code is scanned, Signal
reports it as being invalid. Even after multiple attempts several minutes
apart, with fresh text verification codes, the QR code fails to
authenticate each time. Both devices have WiFi and Bluetooth enabled.

I've submitted a screenshot via the beta reporting feature in TestFlight.
Please let me know how you'd like me to proceed.

Thanks,
Alex

**Comment by Imperiopolis-Signal** [comment]
You’re trying to scan the QR code with the wrong screen, you don’t need to go to the “linked devices” flow.

Ensure the “local network” permission is enabled on both devices and WiFi + Bluetooth is on.

When your new device presents the QR code your old device should automatically present a dialog asking if you want to transfer on top of the list of chats.

**Comment by sirgogo** [comment]
Same exact issue here on the new iPhone 12 Pro. This occurs when first setting up signal, just after verifying. Here are some screenshots 
![E6662C4D-C6CF-4698-A50F-6E87D96DAC3E](https://user-images.githubusercontent.com/5591329/98912680-4741bd00-247b-11eb-8b7a-0588ce02512e.jpeg)
![A7F0EF9D-321F-4BA3-A9B6-B80776071F96](https://user-images.githubusercontent.com/5591329/98912686-4872ea00-247b-11eb-8574-0f7ae61b7ee5.jpeg)

**Comment by mgollo** [comment]
Hi,
I just want to report that I experienced an issue similar, but not identical when trying to transfer chats between an iPhone 7 and an iPhone 12 Pro on iOS 14.2. Signal did not crash, but on the new iPhone, Signal did not ask for the "Local network" permission and thus the old iPhone never showed the screen to scan the QR code. After installing the beta mentioned above on both phones, the transfer worked out. 
Should I leave the beta installed on the new phone? What happens if the beta becomes stable? Will the beta version then be replaced with the stable version from the App Store?

Thanks,
Martin

**Comment by Imperiopolis-Signal** [comment]
You can switch back from the beta to the app store version by installing from the app store over your beta installation. This won’t always work if there have been database changes, but if that’s the case it won’t break there will just be a warning that you need to go back to the beta version. Presently, there are no database changes between testflight and app store builds.

**Comment by Imperiopolis-Signal** [comment]
> Same exact issue here on the new iPhone 12 Pro. This occurs when first setting up signal, just after verifying. Here are some screenshots

You’re running an old version of Signal, please update to the latest and try again. You may need to run the beta version if the latest on the AppStore does not work.

**Comment by ThinIce** [comment]
> I just want to report that I experienced an issue similar, but not identical when trying to transfer chats between an iPhone 7 and an iPhone 12 Pro on iOS 14.2. Signal did not crash, but on the new iPhone, Signal did not ask for the "Local network" permission and thus the old iPhone never showed the screen to scan the QR code.

I have the same on an iPhone SE 2020 and my old phone, a 5s. The local network permission does not appear under the app on either phone and the transfer wizard never appears on the old phone.

**Comment by Imperiopolis-Signal** [comment]
> I have the same on an iPhone SE 2020 and my old phone, a 5s. The local network permission does not appear under the app on either phone and the transfer wizard never appears on the old phone.

If you’re not seeing the prompt for local network permissions on iOS 14, as has been mentioned here before, you need to update Signal to the latest version.

**Comment by sirgogo** [comment]
> > Same exact issue here on the new iPhone 12 Pro. This occurs when first setting up signal, just after verifying. Here are some screenshots
> 
> It’s clear from your screenshots that you’re running an old version of Signal, please update to the latest and try again. You may need to run the beta version if the latest on the AppStore does not work.

It is the latest version of Signal available on the App store. Are you able to acknowledge this as a bug, that could be fixed in the next release, or something else? I'm not able to use Signal on my phone in the meantime without wiping out my previous messages..

**Comment by Imperiopolis-Signal** [comment]
> It is the latest version of Signal available on the App store.

What is the version of the app you are running? Because from the screenshot it is very clearly not the latest. Perhaps the AppStore is for whatever reason not giving you access to the latest build. We released a build that very specifically fixes the issue you’re describing over a week ago, and the QR code screen looks different in that build than your screenshot.

**Comment by sirgogo** [comment]
> > It is the latest version of Signal available on the App store.
> 
> What is the version of the app you are running? Because from the screenshot it is very clearly not the latest. Perhaps the AppStore is for whatever reason not giving you access to the latest build. We released a build that very specifically fixes the issue you’re describing over a week ago, and the QR code screen looks different in that build than your screenshot.

Perfect, thank you! Yeah, it looks like I'm on 3.21.1, but my AppStore isn't showing any other updates (USA). It shows the latest update is 3.21.1 as 2d ago.

**Comment by Zajn** [comment]
FWIW just for reporting purposes, I'm experiencing the same crash on the "Waiting for other device" screen, migrating from an iPhone 6S -> 12 pro.

The app store shows me the latest version of Signal as 3.21.1, updated 2 days ago. Both phones have that version.

I'll give the TestFlight beta a try. Thanks for your help!

**Comment by qmeandm** [comment]
@Imperiopolis-Signal the beta allowed me to transfer accounts last night, and I was able to install the app store version on top afterward. Everything is working fine now. Thanks so much to you and the team for your help!

**Comment by Imperiopolis-Signal** [comment]
Great news, glad to hear it.

**Comment by ThinIce** [comment]
3.21.2.1 has arrived on my old device via the app store. It still does not show the local network permission. The app store on the new device shows 3.21.2 (can't get into the app to see if the version string is different). The waiting for other device screen shows the "not seeing the prompt on your old device?" text. Similarly, there is no local network permission under the app in iOS settings on the new device.

Which version number are we waiting for please? Many thanks.
