### ISSUE TITLE
I can't run app

### ISSUE THREAD

**Issue by Sargis** [signalapp/Signal-iOS#4621]
Hi everyone
I get following error, 
I was trying some changes but it is doesn't help.
Any idea?
<img width="919" alt="Screen Shot 2020-11-12 at 20 18 43" src="https://user-images.githubusercontent.com/11997973/98966135-59c40100-2524-11eb-91a1-3246d8135df0.png">

**Comment by Imperiopolis-Signal** [comment]
Hi, we generally don’t provide development support in GitHub issues, it is purely for bugs. You can ask for help building on our [community forums](https://community.signalusers.org)
