### ISSUE TITLE
I'm Muted and CAN'T Unmute Myself. Being Called or Calling someone (IOS 14.0.1)

### ISSUE THREAD

**Issue by MrWaste** [signalapp/Signal-iOS#4622]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is 2 Problems but both dealing with not be able to Unmute yourself. 
Calling or Someone is calling You.
Your NOT able to unmute yourself what so ever. 
This only happens on IOS - iPhone.

### Steps to Reproduce
iPhone Calling Android Phone:

0. Load Signal App
1. Call the person
2. Everything is normal so far.
3. Mute yourself
4. Can't Unmute yourself after you mute
5. The button is locked in the mute function. Can't be undone.

Reproduced every time. 100%

### Steps to Reproduce
Android Phone is Calling you:

0. Load Signal App
1. Android Phone is Calling You.
2. Accept Call
3. Your Muted right away
4. Can't Unmute.
5. The button is locked in the mute function. Can't be undone.

Reproduced every time. 100%

### Ways around this
1. iPhone Call the Android Phone
2. Can't Mute yourself ever again.
3. or you will have to start with step 1.

### Screenshots

Just looks like a normal mute Button

### Device info

**Device**: iPhoneXR

**iOS version**: 14.0.1

**Signal version:** 3.21.1

**Comment by MrWaste** [comment]
Please Check Out, there still is a problem and no one has fixed it yet.


https://github.com/signalapp/Signal-Android/issues/10127

**Comment by caveman1973** [comment]
Same problem here. Can't unmute.

iOS 14.2

**Comment by jlindgren90** [comment]
A friend and I are experiencing this also -- I am on Android, she is on iPhone. The same symptoms:
- If I call her (Android -> iPhone), she is muted and can't unmute
- If she calls me, I can hear her until she mutes, then she can't unmute again

Any chance this could be related? (I can't figure out what releases it is actually in.)
https://github.com/signalapp/Signal-iOS/commit/f7fccb35a1452db482a68cf4c6fe8c8c565da8b9

Has anyone identified an older working version of the iOS app that she could downgrade to?

**Comment by Imperiopolis-Signal** [comment]
Can you please provide debug logs when this is occurring? We cannot reproduce the behavior you're describing even following your exact steps to reproduce. Muting always seems to work correctly.

**Comment by jlindgren90** [comment]
For us, a recent update (there were 3 in the past week) seems to have fixed the problem.

**Comment by MrWaste** [comment]
That's great to hear, hopefully it stays that way...
