### ISSUE TITLE
iOS Signal icon is missing in share menu for photos, videos, hyperlinks, and probably more.  Screenshots and selected text OK.

### ISSUE THREAD

**Issue by wdormann** [signalapp/Signal-iOS#4625]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When viewing a photo on my phone, I've historically been able to click the "share" icon at the bottom within the Photos app, and I could select the Signal app to receive the photo to be shared to whomever I want.  But at some recent point, the Signal icon stopped being present.  While I can share from within the Signal app itself by adding a photo, I can no longer share from that same photo itself.

Oddly, screenshots that I take **can** be shared using the above technique.

### Steps to reproduce
- Take a photo on your iPhone
- View the photo in the built-in Photos app
- Click the Share icon in the bottom left corner
- (optional) Click the Edit Actions link at the bottom of the list if you did not see signal in the row of available icons.

Variant 2:
Do the same steps, except with a screenshot rather than a photo.

Variant 3:
Do the same steps, except starting with sharing selected text.

Variant 4:
Do the same steps, except starting with a hyperlink from a browser.

**Actual result:** 
For photos, videos, etc. there is no Signal icon to share to/with.  It's also not available in the Edit Actions list of apps.
Screenshots are able to be shared from viewing the screenshot itself for me.
Selected text can be shared with Signal.
Hyperlinks (shared via a 

**Expected result:** 
Photos, videos, screenshots, text, hyperlinks, and just about everything should **all** give Signal as a valid recipient of sharing.

### Screenshots
Attempt to share a photo:
![signal_no_icon](https://user-images.githubusercontent.com/14325582/99460589-1d1a5000-28fe-11eb-9f1a-55831fca41f4.jpg)

Attempt to share a screenshot:
![signal_screenshot_icon](https://user-images.githubusercontent.com/14325582/99460604-24d9f480-28fe-11eb-9e8e-3359c2fa28ba.jpeg)

### Device info

**Device**: iPhone 11 Pro

**iOS version**: 14.2

**Signal version:** 3.21.3.0

### Link to debug log
https://debuglogs.org/20c0602fac06f53775971d298e4a03c0145b09d7f7427bab0e1649c8fd5cac80.zip

Final info:
On a whim, I just tried rebooting my phone.  After this, Signal was available as a share recipient from photos, URIs, etc.  So everything is back to normal.  I wouldn't expect a reboot to be necessary though.
In case there's anything that can be done on the Signal app side of things, I'm still submitting this ticket for the record (and potentially to help anybody else who may be experiencing the problem).

**Comment by Imperiopolis-Signal** [comment]
This is a bug in iOS 14.2 where apple stops surfacing random apps for sharing, it can and will happen with other apps as well and the only current solution is rebooting your phone. Hopefully Apple resolves this in the next iOS release.

**Comment by mflaxman** [comment]
Same issue, reboot fixed it

**Comment by dregad** [comment]
> This is a bug in iOS 14.2 [...] Hopefully Apple resolves this in the next iOS release.

I just faced the same issue, on 14.4 (18D52), so I guess that bug is still outstanding. Reboot fixed it though.

**Comment by dregad** [comment]
FWIW I have not experienced this since I upgraded my phone to ios 15, so maybe apple did fix it...

**Comment by JanMalte** [comment]
I just had the same issue with iOS 15.3.1
