### ISSUE TITLE
Can not send videos made by iPhone 12

### ISSUE THREAD

**Issue by Chabulga** [signalapp/Signal-iOS#4627]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Videos taken by an iPhone 12 cannot be send in a chat they produce just purple video

### Steps to reproduce
- use a iPhone 12 
- set video format to high efficiency ( this is set by default on iPhone 12)
- create a video 
- send it in any chat

**Actual result:** 
The video gets replaced by just a purple screen. Audio is still there. 

**Expected result:**
A proper video shall be send

### Device info

**Device**: iPhone 12

**iOS version**: 14.2

**Signal version:** 3.22.0.8 and 3.23

**Comment by katerberg** [comment]
I saw the same thing and found [this Reddit post](https://www.reddit.com/r/signal/comments/jn3gcn/teal_green_screen_sending_video/) for a workaround (switching from high efficiency videos to "most compatible"), but obviously that's not good long term.

Let me know if you need help replicating!

**Comment by figureone** [comment]
This is what it looks like when attempting to upload a video:

![B57E96F8-B39F-4195-997A-8BE933F8517D](https://user-images.githubusercontent.com/125274/99867772-a0d37700-2b60-11eb-8bc5-4c601e5b3651.png)

**Comment by katerberg** [comment]
Just to make clear since the original post might not seem as high of a priority (since it indicates that you should "set video format to high efficiency"), this prevents all videos from being shared from a new iPhone.

The default case is for high efficiency.

**Comment by GatoPharaoh** [comment]
for everyone having this issue - there is no need switching to "Max Compatibility"

The bug here is caused by HDR - go to Settings - Camera - Video and disable HDR

this will make videos work with Signal again

**Comment by Chabulga** [comment]
This is also just a work around not a solution. I hope this gets generally fixed. All other messengers I tried (Threema, WA, iMessage) do not have that issue

**Comment by bejd** [comment]
Thanks @GatoPharaoh, as a workaround I’ve been able to share videos previously recorded with HDR enabled by opening them in iMovie, then exporting with HDR turned off (tap Options in the share menu for the HDR toggle).

**Comment by katerberg** [comment]
Has there been any progress on this one? I still can't share videos by default and it makes it hard to recommend the app :-/

**Comment by GatoPharaoh** [comment]
Being on the latest beta version 5.1.0.30 it does look like they fixed it. HDR and max efficency does work for me again.

**Comment by tmughal** [comment]
@GatoPharaoh I just downloaded the Beta. Not working for me. Running on an iPhone 12 Pro Max. 

Seems like only videos that were shot on `Most Compatible` setting work. 

This is annoying as its hard convincing people to switch when you can’t send video shot on your phone.

**Comment by GatoPharaoh** [comment]
I'am on 14.3 - so maybe it was the iOS update that fixed. Stable and Beta version does now work as expected.

**Comment by katerberg** [comment]
Just got the `5.3.0.16` and it appears to work now. I think this is okay to close at this point?

**Comment by jboycha** [comment]
It still does not work. You need to be a rocket since tier to use crap Signal, I have been seeing this video issue since last 3 months. I have posted multiple support post directly, it still does not work. What is the big deal? and why would I need workarounds? All you need is take video and share, is that so difficult to do ? Every other app out there does like cake walk?

**Comment by GatoPharaoh** [comment]
@jboycha as multiple people have confirmed that updating (Singal and iOS) fixed it, you may provide more details about your settings to figure out what's wrong in your case.

What iOS version are you on and what Signal version do you have? What video settings do you use?

**Comment by jboycha** [comment]
> @jboycha as multiple people have confirmed that updating (Singal and iOS) fixed it, you may provide more details about your settings to figure out what's wrong in your case.
> 
> 
> 
> What iOS version are you on and what Signal version do you have? What video settings do you use?

Signal Version: 5.4.0.17
IOS Version: 14.4
Videos: a) Direct recording as phone video from IPhone 12 Pro Max b)downloaded video from internet .mp4 or WhatsApp saved or shared video .mp4 c) Videos of size upto 6Mb does not give problem anything above that does not upload any of the mentioned videos, same video if I resize and upload it works upto 6Mb d)it does not master I use 5G or WiFi problem is the same

**Comment by jboycha** [comment]
Guys this signal still can not upload videos of more than 5MB, I see threads which are there for
More than 3 years!!anybody! Interested having this resolved ?

**Comment by jboycha** [comment]
> Just got the `5.3.0.16` and it appears to work now. I think this is okay to close at this point?

Can you see this ? ![image](https://user-images.githubusercontent.com/78777509/107976052-67c96800-6fd2-11eb-8bf4-2e472efa508f.jpeg)

**Comment by jboycha** [comment]
Who said it is working and which version was that ? I have uploaded a dozen mail to support and for
Months nothing has happened? I got a 80Mb video in Telegram in a snap not em WhatsApp can do that ? Guys you are wasting your time in signal and trying to gain ground. Most had moved to Signal and then moved back to WhatsApp because of pathetic user support and basic feature support for ages

**Comment by jboycha** [comment]
This is my version anybody there ? 


--- Support Info --- 
Filter: Signal iOS Support Request 
Hardware: iPhone 
HID: 13,4 
iOS Version: 14.4 (18D52) 
Signal Version: 5.4.0.17

**Comment by katerberg** [comment]
Not sure what is going on, but at least on my iPhone 12 Mini, it is now working (and just shared two 8 second videos in a one-on-one chat, one recorded in the app, and one recorded outside of the app).

Screenshots with potentially helpful info for the developers.
![6AD97CF1-B3EE-4A80-B327-FEB6793C75DD_1_105_c](https://user-images.githubusercontent.com/479643/108085746-46e92d00-703b-11eb-9dbc-d416887f4847.jpeg)
![F96E67A3-D6D3-4095-ADC0-E7323E6252B4_1_105_c](https://user-images.githubusercontent.com/479643/108085749-46e92d00-703b-11eb-9e31-6f7331416fb4.jpeg)
![IMG_6378](https://user-images.githubusercontent.com/479643/108085750-46e92d00-703b-11eb-8023-e885c983dffe.PNG)
![IMG_6379](https://user-images.githubusercontent.com/479643/108085752-4781c380-703b-11eb-8819-a09aa0cb6413.PNG)

**Comment by jboycha** [comment]
I can upload upto 5MB of video anything beyond that won't upload

**Comment by katerberg** [comment]
Just sent an 11MB video. I was on wifi and recorded it with the Camera app, then switched to Signal and uploaded it there.

Hopefully the devs can reproduce the issue, but I'm not able to here. Sorry :(

**Comment by jboycha** [comment]
Hey! Thanks for posting that. I have posted the debug log. Hopefully somebody looks at it. I I'd try WiFi and 5G nothing quite worked?

**Comment by jboycha** [comment]
> Just sent an 11MB video. I was on wifi and recorded it with the Camera app, then switched to Signal and uploaded it there.
> 
> 
> 
> Hopefully the devs can reproduce the issue, but I'm not able to here. Sorry :(

Found out new thing. After your post and I did not tweak any setings; 

If I make a video using the Camera App in IPhone 12 Pro Max then there is absolutely no issue in Sharing the video in Signal. Only the videos I get it from other apps or download video's I am unable to share or send

**Comment by ralphstone1** [comment]
I have phone 11. Is it same feature? Ty

**Comment by katerberg** [comment]
@jboycha That sounds like it might be a different issue (and worthy of a new Issue on Github) since it's probably not related to the "compatibility mode" and it might get lost if it's just on this thread.

**Comment by jboycha** [comment]
> @jboycha That sounds like it might be a different issue (and worthy of a new Issue on Github) since it's probably not related to the "compatibility mode" and it might get lost if it's just on this thread.

Yup! already opened another issue when I suspected this!
