### ISSUE TITLE
Error text field 

### ISSUE THREAD

**Issue by rodolfo-valtierra** [signalapp/Signal-iOS#4632]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When I am typing the text field it doesn't show up i need to type at least 20 characters or drop the chat to let me show it up again while I am typing and the last message can't see it
### Steps to reproduce
- version 3.22.08
- typing in a chat
- minimize it
- maximize the app with the chat and type again, while you don't drop the chat you have the error

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The text field doesn't show up while I am typing

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Show up the text field while I am typing and watch the last message

### Device info

**Device**: iDevice XR iOS 14.2

**iOS version**: X.Y.Z
![466F4CD3-DF7D-4EFA-ACCF-2B929E672498](https://user-images.githubusercontent.com/59891152/100194252-f68a8500-2eba-11eb-8cfe-4ee26d5eb20d.jpeg)

**Signal version:** 3.22.0.8

**Comment by Dyras** [comment]
Same issue here.

Iphone 8
Latest iOS
Latest Signal-iOS

How to reproduce:
1. Open a chat, any chat really.
2. Press the message field to start writing a message
3. The message field is now hidden by the keyboard
(Optional)
4. Open WhatsApp or whatever and try the same thing there
5. Note it works properly there.
https://debuglogs.org/b4c0fafd5d2260b7f54072b63ce48be98c310f8724ce8a3fe3f48d25b9befd6f.zip

**Comment by danyberlin** [comment]
this problem can be circumvent for now by turning the phone into landscape and back to portrait mode. 
i have the same issue with an iphone 7

**Comment by FilLuge** [comment]
Same here on iPhone X and iPad Air 2, both with iOS 14.2.

Workaround is to first input an "Enter", than the text input field becomes visible.

**Comment by danyberlin** [comment]
🤦‍♂️ thank you!

**Comment by Dyras** [comment]
@FilLuge I already figured that much out, I just wish it was fixed permanently :(

**Comment by Leryan** [comment]
the bug appears all the time, as soon as i focus the input field and keyboard shows up, the view doesn't refresh.

the workaround "press enter once" works indeed.

**Comment by constructivecomplaining** [comment]
iPhone 12 Pro Max running iOS 14.3
I am also experiencing the same issue, as described by OP. I will add that it seems to occur when opening signal from the Home Screen, or App Switcher while Signal is running in the background.

Once I have Signal open, if I navigate to the main area, (the list of my chats), select a chat, and start typing the text field works fine. If signal is quit (no longer running in the background), then opening it from the home screen places me in the main area first. So upon selecting a chat, the text field works fine. 

I suspect it has something to do when the program goes into suspension. The bug exists with background app refreshing on and off.

**Comment by Imperiopolis-Signal** [comment]
Please update to 5.1 which we released yesterday. This issue is resolved.

**Comment by Leryan** [comment]
yep, fixed, thanks!

**Comment by rodolfo-valtierra** [comment]
fixed, thanks, it has lag but great job guys 👍

**Comment by Dyras** [comment]
Thanks for a fix! Love the patch notes too!

**Comment by slimal** [comment]
Fixed, Thanks <3
