### ISSUE TITLE
Audio/Video calls fail on IPv6 Cellular Network

### ISSUE THREAD

**Issue by RobusK** [signalapp/Signal-iOS#4633]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While using Cellular Data provider with a IPv6 APN (concrete technology unknown, connecting with IPv4 websites works fine), audio/video calls fail. Messaging works fine. 
I suspect the issue lies with IPv6 because the same provider uses a IPv4 APN for the iPhone hotspot. When using said hotspot, calls work fine. Censorship Circumvention does not fix the issue.

### Steps to reproduce
- Call someone or be called

**Actual result:** When initiating a call, the status stays on "Connecting". Eventually, it switches to Call Failed. The recipient receives a Missed Call notification, but their phone never rings. Conversely, when being called, we only get a Missed Call notification.

**Expected result:** The call switches to "Ringing" / Is established successfully

### Screenshots
<img width="563" alt="Excerpt from the app System Status: hw monitor" src="https://user-images.githubusercontent.com/6713161/100259518-96dabb00-2f48-11eb-9563-d1ef98035809.png">
Excerpt from the app System Status: hw monitor

### Device info

**Device**: iPhone XS 64GB

**iOS version**: 14.2, but been observing this issue since at least iOS 13

**Signal version:** 3.22.0.8

### Link to debug log
https://debuglogs.org/a4c9b4158f09f5c76ff9ea695dd4de64c88f4eb394642aed66406ff2d47a75cf.zip

**Comment by 211217613** [comment]
Is my issue related? #4994 

How would I check to see if my provider is using IPv6

**Comment by RobusK** [comment]
@211217613 sounds similar, you could download the app I mentioned ("System Status: hw monitor") and post it/compare to mine. 

Note: as of 2021-05-16, I am still experiencing this issue.

**Comment by 211217613** [comment]
I did some debugging and seems to be an issue with dual sim config on my iPhone.
