### ISSUE TITLE
Text input field disappears when using Google's swipe keyboard

### ISSUE THREAD

**Issue by ashleyharvey** [signalapp/Signal-iOS#4640]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

As of recently, the text input field disappears so you can't see what's being typed. To fix it, I press and hold inside the text field before the keyboard pops up.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

Install Gboard and Signal.
Try and type a message. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Text input field disappears below/behind keyboard.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

Video: https://share.icloud.com/photos/02pBAExrBehzFWGDV3nYxWC1g

### Device info

**Device**: iPhone XS

**iOS version**: 14.2

**Signal version:** 3.22.0.8

### Link to debug log

https://debuglogs.org/396af071f3bc8392ea65b5c39b407cad313659bb3aeb9a125c2ae3dceac5d95f.zip

**Comment by Genis-Sage** [comment]
hey @ashleyharvey 

this seems to be a duplcate of #4632
only difference on first reading is that you specify the keyboard you use

**Comment by ashleyharvey** [comment]
> hey @ashleyharvey
> 
> this seems to be a duplcate of #4632
> only difference on first reading is that you specify the keyboard you use

Sure looks like it. Mine has some different/important details -- e.g. I show how to work around it which may help devs find the bug faster, and also the steps to reproduce the other one are more complex than mine. My issue happens 100% of the time but in that other one it sounds like one needs to minimize and maximize the app first?

Anyway I'm sure it's the same issue, thanks for pointing that out. Should I close this and just add my comments and video to the other one?
