### ISSUE TITLE
App crashes when I select "Change Photos"

### ISSUE THREAD

**Issue by nathantypanski** [signalapp/Signal-iOS#4642]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I select `Change Photos` on the latest iPhone 12 Mini, the app completely crashes.

### Steps to reproduce
- Set the privacy settings for Signal to only allow selected photos
- Open Signal
- Open a conversation with someone
- Open the modal photo selection dialog
- Scroll all the way to the right
- There's a box for "Change Photos". Rather than clicking it, click the space directly above it
- Watch the app crash to the home screen

**Actual result:** The app crashes to the home screen.

**Expected result:** The app loads the photo selection dialog.

### Device info

**Device**: iPhone 12 Mini

**iOS version**: 14.1

**Signal version:** 3.22.0.8

### Link to debug log

(Sent)

**Comment by febLey** [comment]
I could reproduce this on iPhone 11 and iPad 2018 with iOS 14.3 and Signal 5.2.
You need to have at least one photo selected.
