### ISSUE TITLE
update caused APP not to launch 2

### ISSUE THREAD

**Issue by Leptopoda** [signalapp/Signal-iOS#4643]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Similar to https://github.com/signalapp/Signal-iOS/issues/4626 update to 3.23 via testflight didn't fix it.
EDIT2/3: according to testflight I'm on 3.23.0.1 so the fix of the previous issue ~~hasn't been applied yet. But as it's still iOS 14 and not the mentioned 11 I'm gonna wait and keep this one open.~~ **has** been applied so it is not working for me

### Steps to reproduce
- just happemed i asume after an auto update 
(It happened yesterday in the morning and evening on two devices)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: 2. gen ipad pro (small one), iPhone 11

**iOS version**: 14.2

**Signal version:** 3.22 (update to 3.23 didn't fix it)

### Link to debug log
Sending them in a few minutes...
EDIT: sent them via the Apple crash dialogue

**Comment by Leptopoda** [comment]
Finally got a log from my girlfriend. Seems like she is still on iOS 14.1

**Comment by Leptopoda** [comment]
ups sorry

**Comment by Imperiopolis-Signal** [comment]
The fix we made was only for users on iOS 11, the bug you're encountering is something else. We'll look into it.

**Comment by Imperiopolis-Signal** [comment]
A fix for this will be released to the beta channel in the next few hours.

**Comment by Leptopoda** [comment]
Works fine on my iPad.
Is this going to be available in the stable branch as well? My girlfriend doesn't like the word 'beta'.

**Comment by Imperiopolis-Signal** [comment]
Yes, it’s pending review by apple and should be available in the next ~24 hours.

**Comment by Leptopoda** [comment]
Hi Nora 
So the update just came in this morning and didn't seem to have fixed anything although I could convince her about the beta and version 5.0 fixed it fine 🤷‍♀️
So I gonna close it anyways

**Comment by Mihahn** [comment]
It's definitely not fixed for me on the latest 5.0 beta. So this is still an issue – but I'll just reopen my #4646 if it's fixed for you.

**Comment by Imperiopolis-Signal** [comment]
> So the update just came in this morning and didn't seem to have fixed anything although I could convince her about the beta and version 

The update hasn’t been approved by apple yet, so not sure what you saw. 3.22.2.0 is the pending production build with the fix. Apple is taking a long time to review it.

**Comment by Leptopoda** [comment]
Looks like I'm to dum reading the number 11 as an 11 and not a 14

Read the 'fixes a bug for a crash in iOS 11'
