### ISSUE TITLE
Unable to send message to one contact

### ISSUE THREAD

**Issue by stewartsmith** [signalapp/Signal-iOS#4645]
Contact reregisted to Signal after not receiving first message (new phone), so my first message went nowhere, and my second (post new identity) gets "too many errors" and I cannot send them a message. Someone else can though.

https://debuglogs.org/85e93ec28e5ec0398c698775dad445447fcb1194807c3ced91274261c2b9cfb2.zip

**Comment by stewartsmith** [comment]
After some time (roughly from when filed to when this comment was posted) things fixed themselves. So maybe there's some fun Eventual Consistency going on?

**Comment by rachel1286** [comment]
i also get same problem, i can send messages to other contacts/group chats, but not in a particular chat.

https://debuglogs.org/b57f507f1046bba7acaccae8df9500d1d9581ad3b811cc4d3aa71aeaf553f13a.zip

**Comment by ah07** [comment]
Similar problem. This was happening frequently last year, and has started again - soon after an update to signal. I cannot send messages to one particular recipient using signal on an android device  ( I am iOS). I can receive messages from this person, and all they see is the ... as though I’m writing a message, but it hangs and doesn’t send.

Sending to all other recipients is fine except to this one. This recipient can also receive messages from others, although we haven’t tested to see if from the same iOS version. 

The only way we’ve been able to fix it is for me to uninstall and reinstall. It makes no difference if they do the same. 
Any clues?

**Comment by ah07** [comment]
https://debuglogs.org/44e522e9974d319c892cf7587464b78da373f088be40a23722f3070cb0bac3a3.zip

**Comment by stewartsmith** [comment]
I haven't been able to reproduce, so unless someone else can, I think we can close it.
