### ISSUE TITLE
Signal crashing after a few seconds

### ISSUE THREAD

**Issue by Mihahn** [signalapp/Signal-iOS#4646]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes after about 8 seconds, regardless of the action (opening a chat, going to settings, ...). When I'm trying to send a message and it's still in the process of sending when Signal crashes, the message is deleted and never sent.

### Steps to reproduce
I just open the Signal app on my iPhone 7 (14.2) and after about 8 seconds it crashes and I'm back on my home screen. 

Edit: With flight mode enabled there's no crash on launch!

### Device info
**Device**: iPhone 7
**iOS version**: iOS 14.2
**Signal version:** 5.0.0.61

### Link to debug log
https://debuglogs.org/a685825b7081e2573cca2f45775d4dc1265837430bbbd83f7e33308398d20ced.zip
Crash log sent!

**Comment by Mihahn** [comment]
Looks like it's a bug which is not only affecting the beta version. A friend of mine on the latest AppStore release had the same problem today – she reinstalled Signal and told me it's working fine again. For me reinstalling is not an option as I don't want to loose my messages...

**Comment by CoreISP** [comment]
> Looks like it's a bug which is not only affecting the beta version. A friend of mine on the latest AppStore release had the same problem today – she reinstalled Signal and told me it's working fine again. For me reinstalling is not an option as I don't want to loose my messages... 

Should you have a spare iPhone, you could consider transferring your entire account and history there. Then reinstall on your own phone and move it back. I'm afraid we'll be stuck with major difficulties like this until we finally get the extremely important backup feature. If we ever will. ;)

**Comment by Mihahn** [comment]
> Should you have a spare iPhone, you could consider transferring your entire account and history there. Then reinstall on your own phone and move it back. I'm afraid we'll be stuck with major difficulties like this until we finally get the extremely important backup feature. If we ever will. ;)

Yes, I know, I did this a few weeks ago when I had to reset my iPhone. But if I do it now, I can’t help the Signal team debugging, so I hope they are able to release a potential fix which I can test then!

**Comment by Mihahn** [comment]
Looks like I missed #4643 which might be the same bug. If it’s not (according to the crash log I sent in), feel free to reopen!

**Comment by Mihahn** [comment]
Sidenote for other users experiencing that problem: do **not** downgrade to the AppStore release (3.22.2) if you are already on 5.0 – you'll get a database error if you do this.
