### ISSUE TITLE
iPad Pro iOS 14.2 won't link to Huawei P40

### ISSUE THREAD

**Issue by 1024kbdotcodotnz** [signalapp/Signal-iOS#4647]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Linking iPad Pro 2 iOS 14.2 Jailbreaked to Signal on Huawei P40 Googlefied won't complete. Huawei accepts the link. Communication happens - if I change iPad name the new name is shown in Linked Devices on Huawei. iPad just sits there with spinning icon endlessly.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
- Download & install Signal from App Store
- Attempt to link to Huawei P40
- Scan barcode

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- iPad generates barcode. 
- Huawei accepts barcode. 
- Finish Linking on iPad doesn't finish.
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
iPad would link to Signal on Huawei. (Desktop & laptop Windows both linked successfully.)
### Device info

**Device**: iPad Pro 2 10.5"

**iOS version**: 14.2

**Signal version:** Tried with Beta & stock release.

### Link to debug log

- 
![IMG_20201207_113404](https://user-images.githubusercontent.com/22295156/101295254-5bfa5080-3881-11eb-97ce-a219e875d704.jpg)
Can't, setup doesn't complete.

**Comment by Saad1406** [comment]
[](https://debuglogs.org/eccd730bc9f92202f02a96248e00550f3479c7bf19dc514ea03937b89bda25ca.zip)
