### ISSUE TITLE
images dont load

### ISSUE THREAD

**Issue by mariakatsiki** [signalapp/Signal-iOS#4648]
- [ ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iphoneSE

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Goldin83** [comment]
You have to go into the setting of the iOS phone and tap the signal app and then change the photos settings to "allow access to all photos" ![image](https://user-images.githubusercontent.com/52721941/102023085-aa5f9180-3d50-11eb-90ca-b1c55df6da65.png)![image](https://user-images.githubusercontent.com/52721941/102023089-afbcdc00-3d50-11eb-8ffd-b0a3b21eb4f3.png)
I HAVE Attached screen shots for an example!

**Comment by Goldin83** [comment]
> 
> 
> 
> 
> - [ ] I have searched open and closed issues for duplicates
> 
> - [x ] I am submitting a bug report for existing functionality that does not work as intended
> 
> - [ ] This isn't a feature request or a discussion topic
> 
> 
> 
> ----------------------------------------
> 
> 
> 
> ### when my contacts try to send me photos they will not try to load at all and dont apear in the shared media either
> 
> 
> 
> ### Steps to reproduce
> 
> - using hyphens as bullet points
> 
> - list the steps
> 
> - that reproduce the bug
> 
> 
> 
> **Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
> 
> 
> 
> **Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
> 
> 
> 
> ### Screenshots
> 
> 
> 
> 
> 
> 
> 
> ### Device info
> 
> 
> 
> **Device**: iphoneSE
> 
> 
> 
> **iOS version**: X.Y.Z
> 
> 
> 
> **Signal version:** Z.Y
> 
> 
> 
> ### Link to debug log
> 
> 
> 
> 
> 
> 
> 
>
