### ISSUE TITLE
iOS app crashes on clicking a notification

### ISSUE THREAD

**Issue by teoclaid** [signalapp/Signal-iOS#4650]
The iOS app had been going straight to a crash report if I clicked on a signal notification banner. Today with the new update, the app crashed while I was in it because I clicked on a notification banner from another app. [bug log](https://debuglogs.org/f41c6b36a7ee1512415bf6fe46dba336bd403298bcf81565476c74fb853b3ce6.zip)

**Comment by rajathsn** [comment]
Signal app crashes when I click on notification. And I’m using “no name or contact” notification settings

**Comment by rohanaurora** [comment]
I am able to reproduce this issue. 

```
iOS 14.3
iPhone SE
Signal Version 5.1.0.31
```

**Steps to Reproduce**
- Clicking on the push notification on the Signal app
- The app launches and crashes immediately. 
- The workaround is to kill the app and do a cold start (re-launch).

Here are my debug logs exactly after the crash and then re-opening.

[8ce81b7bbd7e9f893a33aba885b89a1b557670e8ec9fae1dfd7598829d2a3fc7.zip](https://github.com/signalapp/Signal-iOS/files/5810046/8ce81b7bbd7e9f893a33aba885b89a1b557670e8ec9fae1dfd7598829d2a3fc7.zip)

**Comment by rohanaurora** [comment]
This issue can be closed. I am no longer able to reproduce this with the latest version of iOS and Signal.
