### ISSUE TITLE
Camera on when adding file or photo to message

### ISSUE THREAD

**Issue by victoriavdm** [signalapp/Signal-iOS#4651]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever the "plus" icon is tapped fo adding a photo or attachement, the green light in iOS 14 turns on, indicating that the camera is turned on. However, the 'camera' option has not been selected yet, so a user might as well be seen through the camera when browsing through its camera roll.

### Steps to reproduce
- Enter a conversation
- Tap the + icon bottom left
- Don't select camera, GIF, file, etcetera yet. 
- In the top right of the screen, you will see a green dot, indicating the camera is on.

**Actual result:** User can be seen through the camera without choosing this option and without knowing so.

**Expected result:** No green light, only after "camera" option is chosen

### Screenshots

One photo attached
![screenshot_signal](https://user-images.githubusercontent.com/9196678/102494137-806dde00-4074-11eb-82c1-543e454a03d6.PNG)

### Device info

**Device**: iPhone 11

**iOS version**: 14.2 (18B92)

**Signal version:** 5.0.2.0

**Comment by Genis-Sage** [comment]
Hey @victoriavdm
I am not an ios user, so I can't test it myself

But to my knowledge, the camera button is a live preview:
https://community.signalusers.org/t/please-stop-activating-the-camera-when-i-press-the-button/16899

If my knowledge is correct, then the preview is the reason, and the camera activity indicator is expected

**Comment by victoriavdm** [comment]
Hi @Genis-Sage,

When I tested this before the preview didn't show, so I supposed they had removed that function but forgot this aspect of it. But I do see it now. So thank you, I'll close the issue!
