### ISSUE TITLE
Joe Rogan's complaint: Please don't tell people in my contacts that I have signal

### ISSUE THREAD

**Issue by lev-kusanagi** [signalapp/Signal-iOS#4657]
Like Joe, many of us don't wanna talk to people in our contacts, or for them to reach out to us.

Provide the option to not show others in your contacts that you have signal, and not automatically receive their messages if they try to text you.

Make it opt-in, or at least, give the option to opt-out.

Cheers!

**Comment by Mihahn** [comment]
Guess you should switch over to the Signal Forums and discuss the issue [here](https://community.signalusers.org/t/why-are-users-who-have-my-phone-number-in-their-contacts-notified-that-ive-joined-signal/1320) as Github shouldn't be used for feature requests but rather for bug reports.

**Comment by Genis-Sage** [comment]
Hey @lev-kusanagi 
@Mihahn is right

Signal devs reserved the iOS isuue tracker for bugs

Feature request belong into the mentioned forum, as the issue template (which you can see in other issues) and the [Contributing guide](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md)  state 


And for you to understand:
1) Not people in you contacts are informed, but only people who have you in their contacts are informed.. the message is generated locally on their phone
(Also, Signal devs are already working on improvements at that front) 

2) if someone is in your contacts, you will get their messages. 
If someone is not in your contacts, you only will get an invite: https://signal.org/blog/message-requests/

**Comment by lev-kusanagi** [comment]
posted in the linked thread in the forum
