### ISSUE TITLE
Transfering data to new ipad makes the app crash on startup.

### ISSUE THREAD

**Issue by eike-fokken** [signalapp/Signal-iOS#4660]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After transferring the chat data from the old Ipad, Signal doesn't start on the new Ipad. Instead a black screen appears for a split second and signal exits immediately.
On the old ipad all data is deleted, as expected.

### Steps to reproduce
Presumably
1. Clone your ipad from an old ipad (as advertised by the ipad setup procedure)
2. Start Signal and try to transfer the data
3. Wait for it to finish.
4. Start Signal.

**Actual result:** The App doesn't start.

**Expected result:** The app works as usual.
A useful alternative would be: The old ipad waits for a confirmation from the new one that all works now before it deletes the data.

### Device info

**Device**: Ipad Air 2

**iOS version**: 14.3 

**Signal version:** current..

### Link to debug log

Can't do that as the app doesnt start.

I sent a crash log per mail.

**Comment by Mihahn** [comment]
Have you tried turning on flightmode first and launching Signal then? I'm asking because I'm experiencing a similar issue (database got corrupted somewhere) and Signal crashes as soon as I open it – when there's no connection to the internet I have no issues.

**Comment by Mihahn** [comment]
Have you tried turning on flightmode first and launching Signal then? I'm asking because I'm experiencing a similar issue (database got corrupted somewhere) and Signal crashes as soon as I open it – but if there's no connection to the internet, I have no issues and all my messages and all the data is there.

**Comment by eike-fokken** [comment]
Thanks for the hint!
I tried it but the behavior is the same regardless of airplane mode.

**Comment by riyapenn-signal** [comment]
Please share a crash report with support@signal.org https://support.signal.org/hc/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug

**Comment by eike-fokken** [comment]
As I said in my first post: I did.

The emails subject was "iOS Crash Log: #4660"
It was sent on
Fri, 01 Jan 2021 18:27:45 Berlin Time.

**Comment by naryasece** [comment]
I think I have the same issue, the Signal app crashes at launch after transferring from an iPhone 6s to 12 mini.

I've emailed my crash logs to support@signal.org, subject `Crash logs iPhone 6s to 12 mini transfer`. I had previously emailed in crash logs on 2020/11/28 (subject: iPhone 12 mini crash log) and again on 2020/12/8 (subject: More crash logs) for the same issue.

Thanks!

**Comment by ctriley** [comment]
I think I also am having this issue. I transferred my files and it appeared that the transfer completed successfully. However, when I closed the app and reopened it, it crashed immediately. I've tried unloading and reloading the app, and disabling various settings and nothing seems to work.

I've also emailed my crash logs multiple times but have yet to receive a response from support.

**Comment by eike-fokken** [comment]
What exactly is the advantage of closing it? I don't have an Ipad with Signal and can't tell, whether the issue is still relevant. But maybe someone else who had this issue knows, whether this still happens?
