### ISSUE TITLE
App Won’t Open Keeps Crashing!

### ISSUE THREAD

**Issue by GDUBBZ253** [signalapp/Signal-iOS#4662]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Every Time I Try To Open The App It Crashes Started 2 Days Ago But Up Until Then Everything Has Always Worked Perfectly.

#
- I Press On The Signal App On My Iphone And It Immediately Crashes Each Time I Try.

**Actual result:** 
App Crashes Within Seconds Of Trying To Launch It.

**Expected result:** 
In Expect The App To Open/Launch.

### Device info

**Device**: iPhone Xs

**iOS version**: 14.3

**Signal version:** 5.0.3

**Comment by Mihahn** [comment]
Did you already send a crash report? Don't forget to reference your issue here (#4662).

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug

**Comment by ctriley** [comment]
I'm also having this issue. I sent signal a crash report but never got a response from support confirming that they are looking into it.

**Comment by GDUBBZ253** [comment]
Mine Is Working Fine Now I Think It May Have Just Been Due To The Thousands Moving From Whatsapp To Signal All At Once That Affected Me But All Is Fine With My Signal Now.
