### ISSUE TITLE
Protobuf make generates classes that do not extend NSObject. This causes "@objc" attribute to fail.

### ISSUE THREAD

**Issue by cemsozens** [signalapp/Signal-iOS#4663]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Protobuf make generates classes that do not extend NSObject. This causes "@objc" attribute to fail.

### Steps to reproduce
- Download project from GitHub
- Open protobuf folder from terminal
- run "make" command
- On Xcode observe that generated swift files include classes that use "@objc" but do not extend NSObject 

**Actual result:** Generated swift classes include classes that use "@objc" but do not extend NSObject 

**Expected result:** Generated swift classes that use "@objc" attribute should extend NSObject

### Screenshots

![Screen Shot 2021-01-04 at 14 54 57](https://user-images.githubusercontent.com/25372033/103532759-db893880-4e9c-11eb-985f-1420dd3e7857.png)

### Device info

**Device**: Big Sur 11.1, Xcode 12.3, swift-protobuf 3.14.0

**iOS version**: -

**Signal version:** 5.0.2.0

**Comment by skumarm** [comment]
> * [x]  I have searched open and closed issues for duplicates
> * [ ]  I am submitting a bug report for existing functionality that does not work as intended
> * [x]  This isn't a feature request or a discussion topic
> 
> ### Bug description
> Protobuf make generates classes that do not extend NSObject. This causes "@objc" attribute to fail.
> 
> ### Steps to reproduce
> * Download project from GitHub
> * Open protobuf folder from terminal
> * run "make" command
> * On Xcode observe that generated swift files include classes that use "@objc" but do not extend NSObject
> 
> **Actual result:** Generated swift classes include classes that use "@objc" but do not extend NSObject
> 
> **Expected result:** Generated swift classes that use "@objc" attribute should extend NSObject
> 
> ### Screenshots
> ![Screen Shot 2021-01-04 at 14 54 57](https://user-images.githubusercontent.com/25372033/103532759-db893880-4e9c-11eb-985f-1420dd3e7857.png)
> 
> ### Device info
> **Device**: Big Sur 11.1, Xcode 12.3, swift-protobuf 3.14.0
> 
> **iOS version**: -
> 
> **Signal version:** 5.0.2.0

I am also facing this issue. Any solution for this ?
