### ISSUE TITLE
Android 10- Asus zenphone6 - over heat - batter drain

### ISSUE THREAD

**Issue by abhishekshah458** [signalapp/Signal-iOS#4665]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Phone over heats on vedio call

### Steps to reproduce
- call the person from signal
- Over heat and battery drain starts with in 5min

**Actual result:**
Over heat and battery drain, camera unit gets super 

> hot

**Expected result:** 
No over heat should happen

### Screenshots
Cannot be recorded

### Device info

**Device**: Asus zenphone 6

**iOS version**: android version 10

**Signal version:** 5.0.8

**Comment by elistone** [comment]
This is the iOS repo.
Think you need to post this in the android on: https://github.com/signalapp/signal-android/issues

**Comment by abhishekshah458** [comment]
Opening 8n android form

> This is the iOS repo.
> Think you need to post this in the android at: https://github.com/signalapp/signal-android/issues

Thanks
