### ISSUE TITLE
reply box dissapears when replying with a sticker

### ISSUE THREAD

**Issue by lalo** [signalapp/Signal-iOS#4666]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I reply a specific message with a sticker, the reply box is gone.

### Steps to reproduce
- open a chat
- swipe right on any previous message received (to reply to that specific message)
- select a sticker
- sticker is not sent as reply, it is sent as a normal message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- no reply UI around the sticker

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- reply box around the sticker

### Device info

**Device**: iPhone 11

**iOS version**: 14.3

**Signal version:** 5.0.3.0

**Comment by Fondor1** [comment]
I was able to confirm this behavior on an iPhone SE, iOS version 14.3, Signal version 5.0.3.0.

**Comment by Genis-Sage** [comment]
hey @lalo and @Fondor1 
this is expected behaviour
see comment on the Android tracker:
https://github.com/signalapp/Signal-Android/issues/9971#issuecomment-709385271


if you want to discuss a change here, please visit the [community forum](https://community.signalusers.org/)
