### ISSUE TITLE
Not an issue but more of a question related to MITM attacks

### ISSUE THREAD

**Issue by ylu620** [signalapp/Signal-iOS#4667]
I understand that the security code exists as a way to prevent mitm attacks. But that got me thinking, based on how asymmetric cryptography works, when I make a request to signal's directory service for my contact's public key, can we not encrypt that request itself with the service's public key? That way there's no way for the man in the middle to sniff the request.
This would require signal's directory service to have an immutable pair of keys. And have the public key prebuilt in the app. So after installing no requests need to be made to get that public key. 
I know I'm probably most likely missing something here but this just reali got me thinking.

**Comment by Sgn-32** [comment]
Hi ylu620,

the community forum is place for general discussion.

https://community.signalusers.org/
