### ISSUE TITLE
Can’t find any option to stop automatic download of media(images, files etc. )

### ISSUE THREAD

**Issue by samarthsaxena** [signalapp/Signal-iOS#4670]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by samarthsaxena** [comment]
iOS 14.3
Iphone 12 pro

**Comment by hrishikesh-dahiya** [comment]
Yes, there seem to be no chat settings available where we can disable media auto-download in Signal iOS app. Surprisingly, the android app has this feature, so maybe implementing this feature for iOS should not be a big task.
There seem to many features in android app which are not there in iOS app, I think the features should be in sync for both

Requesting Signal app devs to focus on these issues as people are migrating at large to your app you would want to make the onboarding easier.

**Comment by nileshtrivedi** [comment]
A friend report this and said that restricting auto download of images is pretty important. Otherwise it messes up the media library.

**Comment by 4xfu** [comment]
The same issue is mentioned in #4715 , seems to be included in version 5.3
