### ISSUE TITLE
Keyboard is rendered above messages / message view is not scrolled up some times when opening keyboard

### ISSUE THREAD

**Issue by trahman-nep** [signalapp/Signal-iOS#4672]
Device: iPhone 12 Pro Max
OS: iOS 14.3
Signal version: 5.0.3.0

**Comment by callmebalazs** [comment]
Same here, portrait, landscape affected.
Device: iPhone 12 pro
iOS: 14.3
Signal: 5.0.3.0

Not affected:
iPhone Xs (same OS and Signal versions, both portrait, landscape unaffected).
iPad 6th gen (iPadOS: 14.3, Signal: same 5.0.3.0, both portrait, landscape unaffected).

Will test soon on iPhone Xr which has same 6.1" screen size as iPhone 12 pro but different display tech, resolution and ppi.

**Comment by stegmannt** [comment]
Same here.

Device: iPhone 8
iOS: 14.3 (18C66)
Signal: 5.0.3.0

**Comment by inertjade** [comment]
Same here. 

Device: iPhone 11
iOS: 14.3
Signal: 5.0.3.0

https://debuglogs.org/fb3aad36386e68332b75232b4e299b517b3f161f1aba52a501a1d47bd7a53b4e.zip

**Comment by stegmannt** [comment]
Works in 5.1.0.31 again, although it's lagging a bit on an Iphone 8, when scrolling down.

**Comment by trahman-nep** [comment]
5.1.0.31 also a tad laggy on iPhone 12 Pro Max/ iPhone 7. 
Most likely global, across all iOS devices?

**Comment by inertjade** [comment]
Works in 5.1

**Comment by callmebalazs** [comment]
Works in 5.1.0.31 - thanks - resolution is a bit laggy.
It happens in two stages:
1) shows the keyboard and text input field after touching the input field
2) jump-scrolls the stored conversation properly
But there's a slight delay between the steps which makes the perception of a sub-second lag.

**Comment by Imperiopolis-Signal** [comment]
Please update to 5.1 which we released yesterday. This issue is resolved.
