### ISSUE TITLE
Deleted contact still appears as a user within Signal app albeit not as a named contact but as a number, example UK: +44 etc.

### ISSUE THREAD

**Issue by trahman-github** [signalapp/Signal-iOS#4674]
Device: iPhone 12 Pro Max
OS: iOS 14.3
Signal version: 5.0.3.0

**Comment by trahman-nep** [comment]
Okay, so I read the how to guide on the website that a user needs to be blocked then they would disappear, so I've done that and unblocked them too. That works. But it's just a long winded process IMO. Is this privacy prohibitive?

**Comment by swaroop1012** [comment]
@trahman-nep same thing happened with me, same iOS and Signal version. The number disappeared from contacts after a while. Looks like it takes a while to sync.

**Comment by ywoly** [comment]
@trahman-nep I have the same annoying problem in Signal 5.1.0.31 and the workaround you mention works, thank you!

@swaroop1012 However, it's been months since I noticed this problem so I doubt it's a delay problem for synchronization.

**Comment by swaroop1012** [comment]
@ywoly It worked for a couple of contacts that I initially deleted but now it isn't. Let me see if I did anything else to get rid of them (definitely didn't block them).

**Comment by trahman-nep** [comment]
Left a few removed contacts for a few days, have deleted the app, still there. Blocked one of them, they're gone.
Still an annoyance for sure.
