### ISSUE TITLE
Contacts not syncing even after trying many things

### ISSUE THREAD

**Issue by apkpro** [signalapp/Signal-iOS#4675]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked one [x] accordingly. -->

- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Contacts not syncing 

### Device info

**Device**: iPhone XR

**iOS version**: 14.3

**Signal version:** 5.0.3.0

### Link to debug log
-->
https://debuglogs.org/a0ac675af6c974ef9b0f0c6616cce0cd9930252354ce10e1b7a174caa297955d.zip

**Comment by mexson** [comment]
Server overload, see: https://twitter.com/signalapp/status/1347629649090600963?s=21
