### ISSUE TITLE
About video calling in signal 

### ISSUE THREAD

**Issue by KishoreRY** [signalapp/Signal-iOS#4676]
Talking in video call was a bad experience..the screen was blinking and not properly receiving receivers voice

**Comment by Genis-Sage** [comment]
hey @KishoreRY 
with this minimal amount of information, it's hard to see isolate the issue

please fill out the issue template

> ### Bug description
> Describe here the issue that you are experiencing.
> 
> ### Steps to reproduce
> - using hyphens as bullet points
> - list the steps
> - that reproduce the bug
> 
> **Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
> 
> **Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
> 
> ### Screenshots
> 
> 
> 
> ### Device info
> 
> **Device**: iDevice X
> 
> **iOS version**: X.Y.Z
> 
> **Signal version:** Z.Y
> 
> ### Link to debug log
> 
> 

apart from that, it could also be a server side issue because of the many new people joining signal,

so you should try it again in some days
