### ISSUE TITLE
No activation code came , every time recaptcha hard version

### ISSUE THREAD

**Issue by hakanoktay** [signalapp/Signal-iOS#4677]
Hi all,
I am writing here because I cannot find a contact form on the site.

I decided to quit whatsapp and switch to signal, but I ran into some problems. and as a result I gave up.
my first membership experience was terrible

- No activation code came as sms (or i don't know how coming) 
- Every time reCAPTCHA and i think hard version (reCAPTCHA making me crazy. why? i have glasses)

sorry signal, i realy want to use you but ...

maybe next time. 

I hope signal's developers found a solution to this first sign up bullshit

thank you.

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by mexson** [comment]
Too many people are trying to register at the same time since the new WhatsApp privacy policy, see https://twitter.com/signalapp/status/1347960260191948800?s=21
