### ISSUE TITLE
The Dutch translation "Nodig kenissen uit" contains a typo

### ISSUE THREAD

**Issue by stevenbeeckman** [signalapp/Signal-iOS#4686]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Dutch translation "Nodig kenissen uit" contains a typo, it should be "kennissen" with two "n"'s.

### Steps to reproduce
- Go to the settings by tapping your credentials in the top left of the Signal Home Screen.
- The first menu says "Nodig kenissen uit" 

**Actual result:** A menu item stating "Nodig kenissen uit".

**Expected result:** A menu item stating "Nodig kennissen uit".

### Screenshots

None

### Device info

**Device**: iPhone XS

**iOS version**: 14.2 (18B92)

**Signal version:** 5.0.3.0

### Link to debug log
Not applicable, this is a translation issue.

**Comment by stevenbeeckman** [comment]
I have tried Transifex but I couldn't find the Dutch translation project.

A pull request fixing the bug didn't merge automatically.

**Comment by Sgn-32** [comment]
Translation is only done with transifex. Here is the dutch part:
https://www.transifex.com/signalapp/signal-ios/language/nl/

**Comment by stevenbeeckman** [comment]
There was already a suggestion to correct it in Transifex. I'm not sure how to get it published from there.
