### ISSUE TITLE
Unable to add new members, accept new requests to join, or join via link

### ISSUE THREAD

**Issue by supriyas7** [signalapp/Signal-iOS#4689]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by supriyas7** [comment]
issues with Signal group. (All these were working until 2 AM CDT on Jan 10, 2021)

- Unable to add new members to group
- Members are unable to join using links
- Unable to accept new requests to join groups

**Comment by Nisc3d** [comment]
Servers are overloaded at the moment.
