### ISSUE TITLE
Cannot use more than one emoji on the group name

### ISSUE THREAD

**Issue by Jemmaxx** [signalapp/Signal-iOS#4691]
> iPhone 12pro

> ios 14.2

> Hong Kong time: 23:58

https://user-images.githubusercontent.com/58415346/104127970-f3325680-539f-11eb-9f0c-e2d42eb5e68f.MP4

**Comment by Francois-D** [comment]
Hello,  
Which version of Signal are you on?  

I was able to make a group name with multiple emojis.  
![image](https://user-images.githubusercontent.com/46973576/104134580-7f209000-5358-11eb-9477-31216792070c.png)

**Comment by Lord-V15** [comment]
This is a different issue. You can have multiple emojis but the text field space for the group name is limited.
A max of 5 emojis can be added according to my testing.
In the image below you can see that 4 emojis and text is written. 
<img src="https://user-images.githubusercontent.com/46837998/104134478-be2e0000-53af-11eb-856a-6bf088c0b217.PNG" width="300"/>

- Therefore, @michaelkirk-signal I suggest this issue be closed as this itself is not an issue. 
- Rather, a feature request can be created related to this but that would be for the [community forum](https://community.signalusers.org/c/feature-requests).
