### ISSUE TITLE
No contacts on Singal

### ISSUE THREAD

**Issue by bobomok** [signalapp/Signal-iOS#4693]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

no contacts on Singal, i cannot text to anybody!

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Lord-V15** [comment]
@charlesmchen-signal kindly close this as it does not fulfil the guidelines.
Also, most of the information is missing.

**Comment by revher** [comment]
It might be because you don't yet have contacts on Signal! And if you don't get contacts on your desktop as it was my case with my Mac, after quitting Signal from both, Smartphone and Desktop, and reloading (on the same Wifi), I got back my Smartphones contacts (those subscribed to Signal, of course).

**Comment by bobomok** [comment]
> It might be because you don't yet have contacts on Signal! And if you don't get contacts on your desktop as it was my case with my Mac, after quitting Signal from both, Smartphone and Desktop, and reloading (on the same Wifi), I got back my Smartphones contacts (those subscribed to Signal, of course).

thanks for ur reply, but someone has added me by searching my phone number, so i do hv contacts on Signal.....

**Comment by rushi47** [comment]
> > It might be because you don't yet have contacts on Signal! And if you don't get contacts on your desktop as it was my case with my Mac, after quitting Signal from both, Smartphone and Desktop, and reloading (on the same Wifi), I got back my Smartphones contacts (those subscribed to Signal, of course).
> 
> 
> 
> thanks for ur reply, but someone has added me by searching my phone number, so i do hv contacts on Signal.....

@bobomok if it's solved then you should be closing the issue, it helps people working on it to track active issues better.

**Comment by Imperiopolis-Signal** [comment]
as we see unprecedented growth, our contact lookup service was at capacity. this should now be resolved.
