### ISSUE TITLE
Allow “swipe to reply” to be disabled

### ISSUE THREAD

**Issue by hmottestad** [signalapp/Signal-iOS#4697]
Having a configuration option to disable "swipe to reply" would be great for making Signal more accessible. Scrolling up and down can sometimes accidentally trigger the swipe to reply function for users with poorer dexterity.

**Comment by Genis-Sage** [comment]
hey @hmottestad 
as stated in the [contributing.md](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests), github issue tracker is reservered for bugs

feature requests are handled on the [community forum](https://community.signalusers.org/c/feature-requests)
