### ISSUE TITLE
Able to create group without adding anyone

### ISSUE THREAD

**Issue by prem-parmar** [signalapp/Signal-iOS#4700]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When i create a group in signal, i able to create without adding any other person.

### Steps to reproduce
- open signal app
- click on pencil icon
- click on "New Group"
- click on "Next" (Without selecting members)
- give group name
- create group

**Actual result:** Group created with just admin.

**Expected result:** You should give error like "Please select member"

### Screenshots

![Image from iOS](https://user-images.githubusercontent.com/55223134/104182550-8acb8f80-5408-11eb-8c9f-abc1cda9d676.png)

### Device info

**Device**: iphone 6

**iOS version**: 12.5

**Signal version:** 5.1

**Comment by varkrishna** [comment]
What if I add only one other member while creating a group and then I remove that other person, then also there will be only one member in the group. I don't think this is an issue or am I missing anything.

**Comment by Nisc3d** [comment]
I think this is not a bug. The Android Team recently added this functionality too.

**Comment by denver-s** [comment]
I am able (since 2018) to create a group chat without anybody else.

**Comment by Imperiopolis-Signal** [comment]
This is intended behavior. For example, you may want to create an empty group and then share a group link with people to join themselves.
