### ISSUE TITLE
Name in addressbook not displayed

### ISSUE THREAD

**Issue by c1piotto** [signalapp/Signal-iOS#4706]
### Bug description
I have many contact in addressbook (iPhone) with only Field Society filled out
This contact in Signal is showed only with telefon number 

### Steps to reproduce
- modify any of your contacts on Signal by inserting only the Company field
- close and reopen Signal 

**Actual result:** 
Signal show the  phone number instead the Company field

**Expected result:** 
Showing Company field 

### Device info
**Device**: iPhone SE

**iOS version**: 14.3

**Signal version:** 5.1.0.31

### Link to debug log

https://debuglogs.org/1e36ae6f34f5830cd8d66b2cc49550e8ea841dc25a749b8becf26939f5e8c613.zip

**Comment by c1piotto** [comment]
This is my problem

Sergio

**Comment by c1piotto** [comment]
![IMG_1629](https://user-images.githubusercontent.com/77295652/104362135-b12a2180-5513-11eb-92c3-6395978f009b.jpg)
![IMG_1631](https://user-images.githubusercontent.com/77295652/104362138-b25b4e80-5513-11eb-81c9-4d795daa8849.jpg)

**Comment by vasu-negi** [comment]
Yup, i was able to replicate this in the 5.1.0.31 version. I have found the bug. Thanks for raising the issue.
