### ISSUE TITLE
Dynamic Type 

### ISSUE THREAD

**Issue by corbett** [signalapp/Signal-iOS#471]
eventually we want to change the line height on the font to give more spacing

Here's where we're currently handling Dynamic Font:
- [ ] Message View
  - [x] Message Bubbles
  - [ ] Timestamps
  - [ ] Group Update messages
  - [ ] Group update menu
    -[ ] Info Messages
  - [ ] Call log
  - [x] Compose Field
  - [ ] Send Button
  - [ ] Delivery Status
- [ ] Inbox
- [ ] Settings

**Comment by abolishme** [comment]
If @corbett and @FredericJacobs think it's doable for the next point release, I think this issue should actually be "Inherit global font size preference for conversation typography".

In iOS, users can set their preferred font size in the native Settings app. It's found in `Settings > Display & Brightness > Text Size`. The user has two options here, the first is setting the Text Size with a slider from large to small, and the second is to opt for bolder text.

Signal should respect these preferences, and the line-height for the type should be variable based on these numbers.

**Comment by abolishme** [comment]
Additionally, there is an accessibility setting called `Larger Accessibility Sizes` that I believe is intended to control user interface text. We should also investigate how to support this.

**Comment by FredericJacobs** [comment]
That sounds something we can do for 2.1

**Comment by FredericJacobs** [comment]
This is partially implemented but there are still a few things to address.
![slice 1](https://cloud.githubusercontent.com/assets/400296/7748828/8e5d3a62-ffc8-11e4-9994-ac2128bc8380.png)

**Comment by michaelkirk-signal** [comment]
Closing this old issue. If there are specific screens not working well with large/small type faces, let us know with a new issue and screenshots.
