### ISSUE TITLE
Custom Stickers Support

### ISSUE THREAD

**Issue by UtkarshBhatthere** [signalapp/Signal-iOS#4710]
The current sticker framework is limited (I also noticed that every sticker is internally mapped to some emoji so when I received a sticker in the contact menu equivalent emoji was being displayed). Although this seem childish but stickers are one of the major modes of instant communication (along with gifs). Support for adding custom stickers from apps like Sticker.ly or from chats (sent to us by someone else) is important. If you guys do decide to open the sticker framework in signal I would definitely like to contribute to this feature. 😊

**Comment by professor0x** [comment]
I tried these workaround on iOS: 
Copied sticker from WhatsApp — didn't work. 
Copied sticker from Telegram — worked. It is transparent with the background on iOS so supports both Light and Dark mode.

**Comment by UtkarshBhatthere** [comment]
@professor0x how are you copying (importing) stickers ??

**Comment by professor0x** [comment]
I made a recording to demonstrate:
https://www.loom.com/share/60620ccb6f4745cbaf510d91154050e8

**Comment by UtkarshBhatthere** [comment]
Thanks, few questions, did it copy the sticker as a sticker resource or an image. I mean the final object after getting copied in signal was it a sticker ? If yes, does it get stored in signal's sticker frame or we need to be copy-pasting inside signal as well ? Someone told me there's a way to inject stickers in signal Desktop that's why I asked.
