### ISSUE TITLE
[fixed on 5.1] Keyboard hides last messages and doesn't show written texts

### ISSUE THREAD

**Issue by slimal** [signalapp/Signal-iOS#4713]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

In the conversation menu, when I tap "new message" to open keyboard, the keybord show up but :
- hides the lasts messages
- doesn't show text that is been written, unless I type "return"

### Steps to reproduce
- go to any conversation
- tap on "new message"
- type some texts 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
-  the last message received isn't visible
- The typed text isn't visible

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)
- When the keyboards appears, previous text messages should be visible
- typed text should be visible 
### Screenshots

https://user-images.githubusercontent.com/35033632/104303883-ef4f2300-54ca-11eb-9cf1-c2d45c2a6be1.mp4

### Device info

SmartPhone: iPhone 8

**iOS version**: 14.3

**Signal version:** 5.0.3.0

### Link to debug log

https://debuglogs.org/8ff1adebd7fcbd6e98cf7441146ef18ddc999e834f5f235bc894260178ccc16f.zip

**Comment by StefanLobbenmeier** [comment]
Almost Duplicates #4640 but for specific keyboard instead of default I guess

**Comment by slimal** [comment]
> Almost Duplicates #4640 but for specific keyboard instead of default I guess

Thanks for the answer Stefan. I'm using the default BOOT apple keybord.
Part of the problem yes : the fact that the text previous messages aren't visible.

It's also a duplicate of #4632 which is closed. 
It may be related to the size of the screen of the iphone 8.

**Comment by StefanLobbenmeier** [comment]
Yeah could be, I have the issue on iPhone 7 (same screen size as iPhone 8)

**Comment by StefanLobbenmeier** [comment]
#4632 was fixed:  https://github.com/signalapp/Signal-iOS/issues/4632#issuecomment-758083089

**Comment by slimal** [comment]
Yeaaay, it's fixed on version 5.1 !

I'll cancel this issue. 

Thanks !
