### ISSUE TITLE
Setting "Chats and media" present on Android but missing on iOS

### ISSUE THREAD

**Issue by StefanLobbenmeier** [signalapp/Signal-iOS#4715]
- [x ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just compared the iOS app to the Android App. It seems that on Android there is a whole Settings page "Chats and media" that is missing completely on iOS.

### Steps to reproduce
- Check Signal on Android: "Chats and media" is present

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Check Signal on iOS: there is no setting page "Chats and media" and none of the options from that Android page are available on ther pages
- 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Expected: Android and iOS apps have roughly the same options

### Device info

**Device**: iPhone 7

**iOS version**: 14.3

**Signal version:** 5.0.3.0

**Comment by Imperiopolis-Signal** [comment]
Thanks for your report. You can find the download settings in our recently released 5.2 beta. If you’re interested in participating, join the beta group [here](https://support.signal.org/hc/en-us/articles/360007318471-).
