### ISSUE TITLE
Scrolling messages is very choppy

### ISSUE THREAD

**Issue by gfs** [signalapp/Signal-iOS#4717]
- [ x ] I have searched open and closed issues for duplicates
- I found a closed issue from 2016 about a regression. I believe this is unlikely to be related. 
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug 
Scrolling becomes very choppy over time on iOS unless you force quit signal. 

### Steps to reproduce
- Open a chat
- scroll the chat

**Actual result:**
Scrolling is very choppy. This reproduced on all conversations. 

**Expected result:**
Scrolling is smooth like iMessage. 

**Workaround:**
Force quit signal and reopen it. 

### Screenshots

https://user-images.githubusercontent.com/98900/104353509-d0e22b00-54bc-11eb-8dd0-10dabfaacb91.MOV

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 14.3

**Signal version:** 5.0.3.0

### Link to debug log

https://debuglogs.org/cad1d29d65ce880a0cadc7ffef216cd4920b564bee4c3e6f71b87c74ceaa4dc8.zip

**Comment by vchernin** [comment]
Is this issue still reproducible on the latest version of signal ios? (current latest is 5.2). This issue specifies version 5.0.3.0, while the release from a few days ago (5.1) says scrolling responsiveness was greatly improved.

**Comment by gfs** [comment]
I tried to get updates but I’m not seeing 5.2. I do now have 5.1.0.31 and it is indeed much better than when I was seeing the issue.

**Comment by vchernin** [comment]
That is good to hear. Do you think this issue can be closed now or are there still performance issues?

**Comment by gfs** [comment]
I think it can be closed now. I will reopen with a new repro video if I see it again.

Thanks!
