### ISSUE TITLE
Threaded discussions (feature request)

### ISSUE THREAD

**Issue by RoyTinker** [signalapp/Signal-iOS#4720]
Much of the discussion that takes place in forums and social media (like Hacker News) centers around a top-level post (often a link to an article, a question, or a paragraph intended to spark discussion) followed by threaded comments where people can reply to each other.

Along with others (I'm sure), I would love to be able to have these sorts of topical discussions with friends on Signal.

Threaded discussions could be added as a feature within group chats, or perhaps as a new feature that creates a new group chat under the hood for each new discussion with a particular set of contacts added by default to new threaded discussions.

(Hopefully this could be implemented without changes to the Signal protocol?)

I don't trust social media but really enjoy thoughtful discussions with friends -- I'm hoping Signal could provide a better alternative.

As always, thank you so much for providing secure and private messaging.

**Comment by Imperiopolis-Signal** [comment]
@RoyTinker thanks for your request. In general, we try and keep github issues reserved for bug reports. If you'd like to discuss your feature request further, you can post it on our [community forums](https://community.signalusers.org).

**Comment by RoyTinker** [comment]
Ok, thanks for the note @Imperiopolis-Signal and have a great day.
