### ISSUE TITLE
Sharing Photo

### ISSUE THREAD

**Issue by SpeedyR0B0T** [signalapp/Signal-iOS#4722]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When sharing photo from photos app to signal while in landscape mode when you select person then click send it does nothing but if I put in vertical mode it will send.  
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
- Turn Device in Landscape mode
- chose photo from library and click on Share
- choose signal
- Choose person or note to self
- Click send
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Doesn’t send
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Should send photo
### Device info

**Device**: iPad Pro (10.5-inch)

**iOS version**: 14.3

**Signal version:** 5.1.0.31

**Comment by Imperiopolis-Signal** [comment]
This is resolved in our 5.2 beta. Today we’re releasing version 5.2 to beta. If you’re interested in participating, join the beta group here.

b60ffd38a42825ea33aefd5f247b9c84e0234a21
