### ISSUE TITLE
Story option needed

### ISSUE THREAD

**Issue by Jithinkrishnapu** [signalapp/Signal-iOS#4723]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Sgn-32** [comment]
Hi Jithinkrishnapu,

please use the community forum for feature requests.

https://community.signalusers.org/t/stories-status-updates/2565

**Comment by HolySuicidalTurkey** [comment]
1.) Issues is not the place for feature reqests.
2.) A story feature would contradict the privacy-oriented design of Signal.

Enough said
