### ISSUE TITLE
Typing Indicator Not Showing on iOS 14

### ISSUE THREAD

**Issue by DarBeck** [signalapp/Signal-iOS#4728]
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

Phone Details:
Model Name: iPhone 7 Plus
Model Number: MN4C2LL/A
OS Software Version: 14.3 (Also had issue on 14.0)

Signal Version: 5.1.0.31

### Issue
I am not seeing the typing indicator when the person on the other end is typing a message. This is also the case in group chats. It has never worked since downloading the app. 

The person messaging me can see the typing indicator. We both have typing indicator set to true. The person was using the Android version. I haven't got to try with someone else using an iOS version.

If the same person messages me from the desktop app I see the typing indicator.

Update: It seems to be a bug as it works from another contact using the same Android Signal version (5.1.8).

I will update this issue once I get to test with someone using the iOS version.

### Steps to reproduce
- open chat
- have contact send you a message while you are in chat

**Actual result:** Typing Indicator is not visible

**Expected result:** Typing indicator to be visible while the other contact is typing

Debug Log: https://debuglogs.org/45f0bc7357196bb59143acd569a54ff57d20dc31edb0cafbf76d1b214ae28e75.zip

**Comment by DarBeck** [comment]
Based on further testing this does not seem to be an iOS issue and I'm not sure I can point it to an Android issue either as I was not able to replicate the issue from another Android device. It can very much be an account issue or a software bug. 

From the same account the typing indicator is only one way to other contacts. Therefore on the Android device I can see the typing indicator when the other contact is typing but none of the other contacts are seeing the typing indicator.

**Comment by atk8877** [comment]
I got same issue here and i cant fix it

**Comment by DarBeck** [comment]
> I got same issue here and i cant fix it

Is this happening with a specific contact or are you not seeing it for any of your contacts?
