### ISSUE TITLE
completeSilenty not work with iOS 12

### ISSUE THREAD

**Issue by tiendaik** [signalapp/Signal-iOS#4733]
Hi,
My app has granted com.apple.developer.usernotifications.filtering entitlement by Apple, and I silent incoming notification by below code:
self.contentHandler([[UNMutableNotificationContent alloc] init]);
On iOS 13 and above, that line of code is working fine, but on iOS 12 (12.4.8), it still show origin notification.
Please help me to fix this. Thanks!

**Comment by aidan2129** [comment]
This feature was first impletmented on ios 13 it apperars going by the docs. 
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering 
This is probably why the notification displays on IOS 12.
