### ISSUE TITLE
Video sending pb

### ISSUE THREAD

**Issue by shitijarora** [signalapp/Signal-iOS#4735]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video frames not visible when sent to a contact. Only blue screen

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by shitijarora** [comment]
Xxx

**Comment by SUMUKHA-PK** [comment]
Can you describe more? Send a screencast of this? This doesnt tell anything

**Comment by miktm** [comment]
I experience the same issue, preview of video from library is just light blue. Screenshot is attached.
iPhone 12, iOS 14.3
![B78129D1-263C-43CD-A9D5-0973F628F597](https://user-images.githubusercontent.com/5842972/104708150-9a571b00-571d-11eb-863d-6a1adf8ddb61.png)

**Comment by miktm** [comment]
Update: after upgrading to lastest iOS patch version (and restarting) the issue disappeared. Videos can now be shared correctly 👍
