### ISSUE TITLE
Unable to import data into desktop version Mac OS

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#4737]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Unable to import data into my desktop version MacBook Pro version 11.1.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
- 
open desktop app, go to settings > Contacts > import now.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Show import failed, make sure your computer and phone are connected to internet 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Data from phone will be imported into the desktop version

### Device info

**Device**: iPhone 12 mini

**iOS version**: 14.3

**Signal version:** 5.1.0.31

### Link to debug log

https://debuglogs.org/7476a25cbbd04a551023fdb37c1def228e969a8f30532f0dd04ddf7ab32fa1f1.zip

**Comment by kapfab** [comment]
Same issue here with iOS 14.3 and macOS Mojave 10.15.7.
After several failed attempts, contacts have finally synced, but groups are still missing.
Everything else seems to work OK (no actual network issue).

**Comment by ivanvermeyen** [comment]
Same here with MacOS Big Sur 11.1 and iOS 14.3.
New chats are synced, but importing existing chats from the phone to the desktop app does not work with the above error.

**Comment by PierreFunck** [comment]
Same here. macOS 10.14.6 and iPhone 12 mini with iOS 14.2

**Comment by JasTySYmKeq93EaCPhWxNBtHwJh6** [comment]
Same issue.

**Comment by hutstep** [comment]
Same issue, but with Windows 10 + iPhone 12 and latest Signal versions.
Import ist not working. I also can't send from desktop app to Note to self. From my iPhone it works and appears in the desktop app.

**Comment by jeremy-eccles** [comment]
I'm experiencing the same issue with Signal-desktop/Settings/Import now.  It returns "Import failed, make sure your computer and phone are connected to internet"

And as for hutstep above, from the desktop app, on trying to send to 'Note to self' the error "Partially sent, click for details" is displayed in the message bubble.  On clicking there are no more details of the failure. The message does not appear on my iPhone.    Messages to all signal users (including 'Notes to Self') from my iPhone all seem to work and do appear in the desktop app.

I'm using MacOS 10.13.6, iOS 14.3, Signal (iOS) 5.2.1.3, Signal-desktop (MacOS) 1.39.5,

**Comment by kapfab** [comment]
Seems to be working fine now, likely a server-side issue.

**Comment by attikadrian** [comment]
Adding to this issue, this is still happening :(

Downloaded Signal tonight and it didn't auto import the messages and groups from my iPhone 5SE iOS 13.5.1 - tried manually importing using the "Import Now" button in the chat settings and it just hung: 

![Signal Desktop Preferences 2021-11-29 22-03-29](https://user-images.githubusercontent.com/46480402/143950156-d2292324-6644-45b9-9fbc-07e9efc6d46a.jpg)

* macOS: Catalina 10.15.7
* Signal: 5.24.0 production

**Comment by attikadrian** [comment]
Adding to this issue, this is still happening :(

Downloaded Signal tonight and it didn't auto import the messages and groups from my iPhone 5SE iOS 13.5.1 - tried manually importing using the "Import Now" button in the chat settings and it just hung: 

![Signal Desktop Preferences 2021-11-29 22-03-29](https://user-images.githubusercontent.com/46480402/143950156-d2292324-6644-45b9-9fbc-07e9efc6d46a.jpg)

* macOS: Catalina 10.15.7
* Signal: 5.24.0 production

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by kapfab** [comment]
App says contacts have been imported but nothing appear in the side bar list.
Individual contacts can be searched but not groups.

**Comment by kaktusztea** [comment]
@kapfab: do you have a Signal PIN?
It is needed to store group membership info.

**Comment by kapfab** [comment]
@kaktusztea, I do.
I don’t know if the macOS should have asked me to enter my PIN, but it did not.

**Comment by kaktusztea** [comment]
No, desktop doesn't ask for PIN.
Then the PIN part is not the problem.

Maybe try the pairing again and if it fails again, then submit the debug log and copy its URL here to help devs to investigate.

**Comment by kapfab** [comment]
Retried today, contacts and groups did synchronise correctly this time.
Also, why isn’t it possible to get conversation history as well?

**Comment by Cerberus0** [comment]
Only contacts synchronization has been implemented so far. The implementation of conversation history syncing is being tracked here:

https://community.signalusers.org/t/message-history-sync-for-newly-linked-desktop-and-ipad-devices/2839

Next time, please ignore the stale bot. It does not know the difference between bugs and feature requests because [this is no longer the right place to submit or discuss feature requests](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md). You are welcome to continue this discussion over on the community forum.

**Comment by NiklasBr** [comment]
We can't ignore the stale bot because it will incorrectly close issues.

**Comment by Cerberus0** [comment]
Of course! I did not mean that you should ignore the stale bot in general, just in the case of this particular issue.

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by EvanHahn-Signal** [comment]
As was mentioned, we'd like to use GitHub for bug reports, not feature requests. Please use [this community forum thread](https://community.signalusers.org/t/message-history-sync-for-newly-linked-desktop-and-ipad-devices/2839) to discuss this feature further, and the community forums to discuss other feature requests in general.
