### ISSUE TITLE
Pin creation failed Signal IOS

### ISSUE THREAD

**Issue by littl3rud3** [signalapp/Signal-iOS#4742]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
Hey, I just registered a new acc and when I completed the first stages there was “PIN creation Failed”, but after 2 days I still can’t set the PIN.
I have no VPN, I tried to use Wi-Fi and Cellular, but result is the same always same phrase “Your PIN was not saved. We’ll prompt you to create PIN later.”

**Actual result:** error “Your PIN was not saved. We’ll prompt you to create PIN later.”

**Expected result:** PIN created successfully

### Screenshots
![5B7FEF42-88CA-45D4-ABE3-F5DA51142995](https://user-images.githubusercontent.com/67325745/104607323-c331ce80-5691-11eb-9420-760fc233b9b6.jpeg)

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 14.3 (18C66)

**Signal version:** 5.2.0.4

### Link to debug log

https://debuglogs.org/d4a3413275681526951890727a89be23db56aee475eaa1a8e5cc00bf007cf479.zip

**Comment by scuac** [comment]
I am facing the same issue. In my case I had successfully created a 4-digit PIN when I first installed the app, but later I found out the PIN could be longer (easy to miss), and today when I tried to replace the PIN I run into the same error. Now it seems there is no PIN set at all (the old one is gone) but still cannot enter a new PIN.

**Comment by marilou000** [comment]
I would like to ask if the issue still persists?
I have log a report as well but its not been attended by the Signal team.
