### ISSUE TITLE
Camera switched on in gallery view

### ISSUE THREAD

**Issue by Lozik** [signalapp/Signal-iOS#4751]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As of 5.2, the camera is not flicked on automatically when tapping on the "+" at the bottom of a chat. **Thank you for that!** However I noticed a bug related to the camera and the camera roll:
The camera is switched on in the gallery view, the view where one can select an image from the camera roll for a message. This is confirmed by the green camera indicator. Switching to the camera from that view (using the camera button on the bottom left) goes fast (which is great) but imho it would be better to enable the camera AFTER one presses the camera button.

### Steps to reproduce
- Navigate to a message
- Tap the "+" button on the bottom left
- Tap the gallery icon
- Wait 3 seconds

**Actual result:** The camera is turned on in the background and the green camera indicator lights on.

**Expected result:** The camera should not be turned on, except when I need it to. This would e.g. the case when I tap the camera icon in the gallery view or the camera icon in the message view.

### Device info
Signal for iOS 5.2, latest iOS release

**Comment by UrsKahmann** [comment]
I can confirm this on an iPhone 8 (iOS 14.3, Signal Version 5.2.0.4).

**Comment by GoodBoyNinja** [comment]
Can confirm this as well on iphone 6s plus. It also stays open as you edit a photo before sending it

**Comment by MEPoss** [comment]
Can confirm on iPad 6th gen (iPadOS 14.4) with Signal Version 5.4

**Comment by wtangofoxtrot** [comment]
This issue is still there in the gallery view when selecting images on 5.11.1.1
