### ISSUE TITLE
Memoji appearing with white background in newest version but not prior

### ISSUE THREAD

**Issue by notnicehat** [signalapp/Signal-iOS#4752]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In 5.2.0.4 Signal iOS memoji are appearing from my phone (and others with the same version) with a white square background. Users with prior versions (5.1.x) Signal IOS posting memoji in the same chat have backgrounds that are transparent or otherwise match the light/dark appearance. 

### Steps to reproduce
- In chat with someone (group or 1-1)
- Click bottom left emoji icon
- swipe from left to right to get to iOS memoji stickers
- post memoji sticker

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- appears in chat with white background
 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- appears in chat with no background

### Screenshots

![Screenshot 2021-01-14 at 3 12 33 PM](https://user-images.githubusercontent.com/8051939/104660437-5c091f80-567b-11eb-8f98-f25eaf2fe56f.png)
You can see my cow with white background, my friend's warthog without. 

### Device info

**Device**:
My (problematic) device: iPhone 11Pro 
My friend's (fine) device: iPhone 12Mini

**iOS version**: 14.3 both

**Signal version:** 
My problematic device: 5.2.0.4
My friend's fine device: 5.1.0.31

### Link to debug log

My log: https://debuglogs.org/2b32d776562dacd69947667abf1b90ad04011f3b1759435735e63b6cb46c61af.zip
My friend's log: https://debuglogs.org/8ad137c3135d84fdbb928cacd3ca14831bf63254048ceeb1d91a70961145db1c.zip

not a crashing bug

**Comment by ankitsharma07** [comment]
yeah, this is been reported in the 5.2.0.4 version

**Comment by janruplays** [comment]
I still can't find a fix for this. Sad.
