### ISSUE TITLE
Signal does not remember keyboard language

### ISSUE THREAD

**Issue by alejandromolinaml** [signalapp/Signal-iOS#4754]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have 3 keyboard languages, whenever I open signal, it always sets the keyboard to the default language (in my case english)

### Steps to reproduce
- open app
- set keyboard to german
- send messages
- leave the app (say to open safari)
- Go back to the app
- The keyboard is now set to english

**Actual result:** 
after leaving the app and returning again, the keybord language is always reset to the language used by the app before reopening  signal.
Furthermore, switching between chats, doesn’t remember the language used in every chat.

**Expected result:** 
The keyboard should remember the last language used on every chat.
According to the forum, this was introduced long ago in version 2.45.

https://community.signalusers.org/t/remember-keyboard-language-for-each-chat/8650

### Device info

**Device**: iphone XS

**iOS version**: 14.3

**Signal version:**: 5.2 and 5.2.0.5

**Comment by doopler** [comment]
+1 same thing

**Comment by shadzik** [comment]
Same here, but I think it's somehow connected to iOS 14. In my own app I'm trying to achieve the same effect and it's just not working - more, the official sample code from Apple also doesn't work.

https://github.com/MessageKit/MessageKit/issues/1515

**Comment by alejandromolinaml** [comment]
I played with it a bit more, it turns out that switching the keyboard language in safari and then opening signal, leads to the language safari had.
However, the same is not true if I use WhatsApp in between and change keyboard languages in WhatsApp. Once I open signal again, the language will still be whatever safari is using, even if I changed languages in WhatsApp.

it seems like WhatsApp saves the keyboard configuration on open, and restores it when it leaves focus.

Another interesting situation is that when I change languages in signal and go back to safari, safari keeps the language it had before and ignores whatever language changes signal made.

maybe this helps a bit? Unfortunately I don’t know much about iOS development.

**Comment by tsvenbla** [comment]
This happens to me too. However, I find that the keyboard language always returns to English, no matter what keyboard language I ended up using earlier, as @alejandromolinaml seems to experience above.

**Comment by shadzik** [comment]
What I have noticed in my chats is that older chats where I have set the language a while back, use the correct keyboard - new chats however reset to a default language - for me it's not English. Therefore I believe that the `textInputContextIdentifier` works halfway - as it restores the lang if it was set on a previous iOS version (my guess is < iOS 14) but doesn't set it properly currently. All speculation though.

**Comment by uros-gardasevic** [comment]
I have confirmed that this is an issue with iOS14. Use of `textInputContextIdentifier` in IOS14.* is totally broken. 

Ran tests on both iOS13/14 simulators and with help of symbolic breakpoints i could see the that sequence of calls to `activeInputMode` and `textInputContextIdentifier` is not right.

**Comment by uros-gardasevic** [comment]
Only Whatsapp has so far made a workaround for this iOS issue (Messages, Viber, Telegram not retaining language preference per conversation either).

It even works somewhat better if `textInputContextIdentifier` is not overridden at all. Then it reopens the last used keyboard (used by any app).

**Comment by shadzik** [comment]
iOS 14.4 RC release notes suggest a fix is near :)

**Comment by shadzik** [comment]
For me it works with iOS 14.4

**Comment by uros-gardasevic** [comment]
Its solved elsewhere.
