### ISSUE TITLE
There's a Problem when Dialing a Call with Speaker

### ISSUE THREAD

**Issue by jeremygautama** [signalapp/Signal-iOS#4756]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I started dialing, I usually put my phone on 'speaker' mode. But when i'm waiting for it to be picked up, the speaker ring sounds like a non speaker ring and thus I don't know if it is ringing or not. 

### Steps to reproduce
- Open the signal app
- Go to one of your contacts
- Press the call/phone button
- Press Speaker 

**Actual result:** The 'speaker' sound when dialing a person doesn't sound like it's on 'speaker' mode

**Expected result:** When you press 'speaker', even though it has not yet been connected, it should sound like it's on 'speaker' mode (you can hear the sound of the phone dialing out loud)

### Device info
**Device**: iPhone 7

**iOS version**: iOS 14

**Signal version:** 5.1.0.31

**Comment by HolySuicidalTurkey** [comment]
....... and does it use speaker for the actual call audio?

**Comment by jeremygautama** [comment]
For the actual call audio, it does use speaker

**Comment by HolySuicidalTurkey** [comment]
> For the actual call audio, it does use speaker

i mean, if your call audio is still on speaker, do we really have that much of a problem?

**Comment by jeremygautama** [comment]
In normal calls we hear both dialing and voice audio when using speaker. Personally, I got used to that. So it's quite odd when I used Signal. So to answer your question, it's a problem for me.

**Comment by HolySuicidalTurkey** [comment]
I don't want to come off as rude, or that I don't care about your issue, but the app is currently experiencing a major influx of users, and the team has many priorities, such as expanding the infrastructure or fixing critical bugs. I will look into it though.

**Comment by jeremygautama** [comment]
> I don't want to come off as rude, or that I don't care about your issue, but the app is currently experiencing a major influx of users, and the team has many priorities, such as expanding the infrastructure or fixing critical bugs. 

Oh I see. Keep up the good work 👍

> I will look into it though.

Thank you. Very much appreciated
