### ISSUE TITLE
Messages won't send after latest update

### ISSUE THREAD

**Issue by JJ077** [signalapp/Signal-iOS#4757]
I am not able to send or receive messages after the latest update. My Internet seems to be working fine as I am able to send/recieve messages on other apps

**Comment by josephcappadona** [comment]
Same. It keeps saying “Request failed: bad gateway (502)”. Here is a link to a debug log: https://debuglogs.org/7d60c3ae0564cdcb26c6399c8bcc6b335c4a393bf2e4d7a0a867d6e3897dcfef.zip

**Comment by TimLai125** [comment]
Also having the same issue as @josephcappadona , following message is shown from `More Info` of Desktop version.
`The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 502)`

**Comment by TimLai125** [comment]
> Also having the same issue as @josephcappadona , following message is shown from `More Info` of Desktop version.
> `The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 502)`

I suspect this might be related to internet issue, I am able to send message when I enable VPN.

**Comment by CatalystRed** [comment]
Messages are going through, just have to “send again”.  Obviously less than optimal.

**Comment by 501st-alpha1** [comment]
I'm having the same issue: originally it just hangs on sending for a while, but eventually it gives `bad gateway (502)`.  After retrying several times, the message finally went through.  I was not on the latest version originally (not sure which version it was), but after updating to the latest version, and the same issue is occurring.

**Comment by 501st-alpha1** [comment]
Developers responded in [#4853 on Signal-Desktop](https://github.com/signalapp/Signal-Desktop/issues/4853#issuecomment-761034317):

> Signal is having some server issues right now, which we're actively working on.

Presumably that is what's causing these errors too.

**Comment by jrpentland** [comment]
trying to send messages and starting today it’s sending like one (of that) of every 10-20 I send.  My wireless is fine on every other device in the house.

![A3241DA4-1687-432E-8782-9ACB7156746D](https://user-images.githubusercontent.com/70303551/104763353-be255b80-5733-11eb-810d-8765cf63a50e.jpeg)

**Comment by michaelb-ae** [comment]
it's because of the massive arrival of news user, they do their maximum to update the server please wait a bit

**Comment by shliachtx** [comment]
My internet is connect, but Signal is showing that I am disconnected, and I receive the following error from about half of the contacts in the group `The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 502)`

**Comment by 501st-alpha1** [comment]
I believe this issue was fixed and can be closed.
