### ISSUE TITLE
Can’t register my phone number on IOS (SignalServiceKit.NetworkManagerError error 0)

### ISSUE THREAD

**Issue by SoniaMalki** [signalapp/Signal-iOS#4758]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can’t register my phone number on Signal. I’m new to the app, first time downloading it. I’m on the last version of IOS with an IPhone 11.

I’ve tried uninstalling and reinstalling it. I turned off my phone and turned it on again. Tried closing completely the app and running it again. I’ve also tried registering with another phone number. 

Nothing worked. 

### Steps to reproduce
- installing the application from IOS store
- accepting the notification and the access to the list of contacts
- enter a phone number and tap « next »

**Actual result:** Can’t go past the register process. It shows an error « SignalServiceKit.NetworkManagerError error 0 »

**Expected result:** Registering my phone number 

### Screenshots
![802E644D-F09C-4E62-A9C1-08EB85A7CF13](https://user-images.githubusercontent.com/15875537/104752171-a3181300-5756-11eb-8973-10ed988a9ee2.jpeg)

### Device info

**Device**: iPhone 11

**iOS version**: IOS 14.3

**Signal version:** 5.2

### Link to debug log
No debug log in the settings

**Comment by nicolasdasriaux** [comment]
Same error as you.  iOS 14.3. iPhone 7 Plus.

Online support does not help at all. Security screen do not match the actual screen.

**Comment by michaelb-ae** [comment]
it's because of the massive arrival of news user, they do their maximum to update the server please wait a bit

**Comment by shinyelf** [comment]
I have the same issue when registering my number. Waited several hours between attempts.same issue

**Comment by honzab** [comment]
> Signal is experiencing technical difficulties. We are working hard to restore service as quickly as possible.

https://twitter.com/signalapp/status/1350118809860886528?s=20

**Comment by jsgro** [comment]
Thanks for the Twitter link... I have the same error (in English)
Message is: `The operation couldn't be completed. (SignalServiceKit.NetworkManagerError error 0.)`

On my iPhone 8 Plus, iOS 14.3 (latest) and `Signal` 5.2 (latest) - just installed after viewing `WhatsApp` changes...

**Comment by michaelb-ae** [comment]
it's not only an ios problem it's a servers side problem, so no update on our side is mandatory

**Comment by donna12358** [comment]
Please reopen.  I'm having the same issue.
