### ISSUE TITLE
Messages arrive late 

### ISSUE THREAD

**Issue by alessandram95** [signalapp/Signal-iOS#4759]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by alessandram95** [comment]
Messages take so much time before they arrive to destination. Sometimes an error occurs and I have to resent the text

**Comment by michaelb-ae** [comment]
it's because of the massive arrival of news user, they do their maximum to update the server please wait a bit
