### ISSUE TITLE
Cannot send payment requests

### ISSUE THREAD

**Issue by liviakuhn** [signalapp/Signal-iOS#4760]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to use the Signal app send a payment request, an error is shown and the payment request is not sent.

### Steps to reproduce
- Create a payment request via your banking app.
- Select Signal when prompted for a way to share the payment request.

**Actual result:** An error is shown: 
Unable to Send Attachment
The operation couldn't be completed.
(SignalServiceKit.NetworkManagerError error 0.)

While the payment request is shown in the chat, it remains 'stuck': ![message_status_sending](https://user-images.githubusercontent.com/39652631/104753618-8b418e80-5758-11eb-9abf-d4dc9de632d8.png)

**Expected result:** A message is displayed saying that the payment request was sent.

### Screenshots
![signal-bug](https://user-images.githubusercontent.com/39652631/104752728-5123bd00-5757-11eb-9322-5c04eb71721f.jpg)

### Device info

**Device**: iPhone 8

**iOS version**: 14.3

**Signal version:** 5.1.0.31

### Link to debug log
https://debuglogs.org/b96a088763c890f27218b27521624635d059932699816ed36d9e6efc72fd018e.zip

**Comment by jvanakker** [comment]
This probably has to do with the current Signal server issues..

**Comment by liviakuhn** [comment]
Right, other messages are getting stuck as well now.

Thank you for the quick response.

**Comment by liviakuhn** [comment]
Fixed now.
