### ISSUE TITLE
Thumbnail images don’t appear when url links posted

### ISSUE THREAD

**Issue by TheoMer** [signalapp/Signal-iOS#4764]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When url links are sent they appear without their corresponding thumbnail image.

### Steps to reproduce
- select a video on YouTube 
- click share
- select signal
- select a user/group to send the link to
- click send

**Actual result:** The link is sent without a thumbnail image

**Expected result:** I expected a corresponding image to appear in the chat windows with the link underneath 

### Screenshots
[![image](https://user-images.githubusercontent.com/15969262/104770303-4887b280-5768-11eb-93a7-76960a56c979.png)]()

The links above and below the reply (blue) are sent by an android device

### Device info

**Device**: iPhone 6s Plus

**iOS version**: 14.2

**Signal version:** 5.0.3.0

**Comment by sertsedat** [comment]
Previews are turned off by default. Did you turn it on in the settings?

**Comment by TheoMer** [comment]
@sertsedat That did the trick. Many thanks.
