### ISSUE TITLE
I need help to register my number to signal

### ISSUE THREAD

**Issue by kelly2233444** [signalapp/Signal-iOS#4767]
I can not register my number to signal, after putting in my number.. it shows error message and do not continue.. what can I do?

**Comment by honzab** [comment]
Looks like there are some temporary issues with registering new accounts. See #4758

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp
