### ISSUE TITLE
Why is my signal not working today

### ISSUE THREAD

**Issue by gremlin11** [signalapp/Signal-iOS#4768]
https://debuglogs.org/8e1d35c953078306c06da622d4f9483da83f3d3d5279ce6d42d7714fa5ba8f51.zip

**Comment by Bizzet** [comment]
Same issue for me

**Comment by wark88** [comment]
Same

**Comment by wark88** [comment]
Seems to happened about 13 hrs ago??

**Comment by wark88** [comment]
Sorry for the multiple messages.. wont let me edit for some reason.. 

Went from a pop up about "technical issues" to "send failed - service unavailable"

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp
