### ISSUE TITLE
Can’t connect app on iPhone nor MacBook Pro to Network

### ISSUE THREAD

**Issue by lkfraboni** [signalapp/Signal-iOS#4769]
This just started today or last night and suddenly signal cannot connect to my network where it was working just fine for the last several months. I updated the version on my MacBook Pro and not sure what else to do. It will not connect to the network on my phone nor my MacBook Pro. On my phone it says signal is having technical difficulties. On my MacBook Pro desktop version it says check your network. 

Please advise. Lorinda

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp

**Comment by lkfraboni** [comment]
Resolved

**Comment by lkfraboni** [comment]
You can close this

Thank you, 


Lorinda Fraboni
***@***.***
