### ISSUE TITLE
Logged in with MacOS Signal now can’t send messages with iPhone Signal app

### ISSUE THREAD

**Issue by ryue2000** [signalapp/Signal-iOS#4770]
I downloaded the Signal interface for Mac yesterday. Today im unable to send any messages via the IPhone app.

fyi im using an iphone xr and a Hackintosh running opencore

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp
