### ISSUE TITLE
Cannot send messages or call

### ISSUE THREAD

**Issue by bearhmil** [signalapp/Signal-iOS#4771]
https://debuglogs.org/b519e6b4e26c43df7d3b92ede9e335ea42195145f99a68c1a54f032886bdcaea.zip

**Comment by Bizzet** [comment]
I have the same issue

**Comment by cgovond** [comment]
I have the same issue

**Comment by dorkingbeauty1** [comment]
me to
cant upload my logs either

**Comment by dorkingbeauty1** [comment]
me to
cant upload my logs either

**Comment by abigayle0328** [comment]
I have this same issue

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp
