### ISSUE TITLE
Cant receive messages

### ISSUE THREAD

**Issue by ayebac0n** [signalapp/Signal-iOS#4773]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp
