### ISSUE TITLE
Signal works intermittently

### ISSUE THREAD

**Issue by schlikk** [signalapp/Signal-iOS#4774]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal fails sending a message unless I switch network and resend. 

### Steps to reproduce
- select a chat in the app
- Enter a message and send
- When getting failed send error, switch from wifi to mobile (4G)
- Resend
- Same happens if starting in mobile network, switching back to wifi and resending works. 
- in trying again (to regenerate debug logs), I’ve found it does not consistently happen for all chats. 

**Actual result:** Describe here what 
message cannot be sent or resent until network is switched. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
message is sent first time

### Device info

**Device**: iPhone 8

**iOS version**:14.3

**Signal version:** 5.2.0.4

### Link to debug log

https://debuglogs.org/c702059136c700e7e4744b1fb10997046df29a192f097a103edabe8f96b34671.zip

**Comment by christophevg** [comment]
Thank you for actively supporting Signal. Submitting issues is a valuable contribution. 

At this moment, Signal is experiencing an enormous amount of new registrations and users. The team is working to bring more server capacity into play to cope with the increase in network traffic. 

Please do first search for other issues that already describe this to avoid duplicates, which further increases the amount of work the team has to perform. 

To help, please close this issue yourself and follow up the progress using the following sources:

- https://status.signal.org/
- https://community.signalusers.org/
- https://twitter.com/signalapp

**Comment by schlikk** [comment]
Hi. I reported through the app. I’m not a signal developer, so no idea
about progress.
I still see some delays in sending, but nothing like the 10+ minutes when I
originally reported.
