### ISSUE TITLE
Cant send media (videos) directly from photos

### ISSUE THREAD

**Issue by naushpm** [signalapp/Signal-iOS#4777]
### Bug description
Cant send videos from photos app through signal

### Steps to reproduce
- Open photos from iPhone menu
- Select any video and click share
- Select signal app from application list 

**Actual result:** It is not opening the signal app to select the user to whom I have to share the video.

**Expected result:** It should open the signal app and should be able to select the users to whom I have to share the video.

### Device info

**Device**:  Iphone XS

**iOS version**: 14.3

**Signal version:** 5.2.0.4

### Link to debug log

https://debuglogs.org/2bef402257f6ad56ee59b7c81cc120f96a3f71b9bae5d3eb5eb34163e772e955.zip

**Comment by ShingZhanho** [comment]
Same problem encountered on iPhone 8

**Comment by UrsKahmann** [comment]
On my iPhone 8 (iOS 14.3) this is not an issue.

**Comment by ShingZhanho** [comment]
It is complicated. Some of my friends encontered this problem and fixed by reinstalling Signal app. But this workaround did not work for me. I reinstalled the Signal app twice but the problem persists.

**Comment by OursidusMaximus** [comment]
Same issue.
1/ I reinstalled app twice -> not working
2/ I reset privacy settings-> not working 
🤷🏻

**Comment by technorainbows** [comment]
Question, for you who are having the photo & video share problem, do you also have inability to share a screen shot? Lately that has started to work for me. I'm on an iPhone 12 mini. But I've had issues with sharing for years, definitely the whole time I previously had an iPhone X.

**Comment by rb81** [comment]
**+1**

Facing the same issue.

**Comment by sa1** [comment]
https://debuglogs.org/80a2350db6f03573688af086f91dc26bbf86d686db0a63b9ad059453d0a758cc.zip

It happens even when sharing via other mediums too. Sharing bigger videos is more likely to fail. Copy pasting videos almost always succeeds. Sharing from Photos almost always fails.
