### ISSUE TITLE
Crashes on all features which involve camera & photos

### ISSUE THREAD

**Issue by ShingZhanho** [signalapp/Signal-iOS#4778]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Right now, the Signal app is known to crash on the following operations:
1. Tap the camera button on the home page.
2. Tap the camera button to take a picture in any conversation.
3. Choose pictures from the photo library for sending them to others.
4. Try to share a photo via the Share Sheet.

Whenever you are trying to send a photo, the UI will stop responding for a minute or two, and crashes.

### Steps to reproduce
- See the operations described in the above section

**Actual result:** The app crashes

**Expected result:** The app should open the camera view for sending picture to others.

### Screenshots
Not available as the app crashes and nothing can be captured.

### Device info

**Device**: iPhone 8

**iOS version**: 14.3

**Signal version:** 5.2.0.4

### Link to debug log
https://debuglogs.org/eba612c0ea9a2f9d7d9047c94e952a9f491f6c6bb30683fb889d3eaf1c983dac.zip

**Comment by petrsponer** [comment]
Hi. I tried to reproduce. No success. What does exactly mean "share a photo via the Share Sheet."? Thanks 🙏

**Comment by ShingZhanho** [comment]
> I tried to reproduce. No success.

It's complicated. A few of my friends encountered the same problem, but after a reinstallation, they are able to send photos. But the reinstall does not work forme. I reinstalled Signal app for twice and the problem still persists.


> What does exactly mean "share a photo via the Share Sheet."? Could you add screenshots?

https://user-images.githubusercontent.com/63346990/104830463-4df51200-58ba-11eb-91c4-ae2ce23cccd5.mp4

As you can see from the above video, when I try to share a photo by clicking Signal's icon, it shows nothing.

**Comment by rishid** [comment]
Experiencing same problem, just sharing photo from stock iOS Photos app. iOS 14.3, latest signal app.

**Comment by ShingZhanho** [comment]
#4777 
#4479

**Comment by ShingZhanho** [comment]
#4777

**Comment by ltomasik** [comment]
Hello I experienced same issue. When I want to select multiple photos in photo library, Signal app crashes. 
iphone 7, iOS 14.3, Signal version 5.2.1.3
how to reproduce:
open Signal app -> open chat window  -> click camera button at the bottom right -> click photo library at the bottom left -> select multiple photos from Recents. Signal app crashes with multiple randomly selected photos. It happened with e.g. 12 selected photos, another time with 20 selected photos, etc.

**Comment by ltomasik** [comment]
https://debuglogs.org/228df97e0dab56be326a6201d75cc3fdd5048d3f583af6141c0cbcac3c723be5.zip

**Comment by ltomasik** [comment]
![984CD54B-E542-46D1-B739-2D1754F2184D](https://user-images.githubusercontent.com/77664468/105011327-1d89b100-5a3d-11eb-961d-beea75a6a7a8.png)

**Comment by robiecz** [comment]
Same here. I have reinstalled my iPhone 11 Pro (latest iOS) as a new device and install only Signal as first app. The iOS sharing function worked well. But when I install the rest of my apps the sharing to Signal behavior is the same as is described abov.
It's very common issue: https://www.reddit.com/r/signal/comments/idebne/issues_with_sharing_to_signal_on_ios/
I use https://apps.apple.com/us/app/intelligent-hub/id338761996 with a profile from my company. Maybe it can help.

**Comment by ShingZhanho** [comment]
> 4. Try to share a photo via the Share Sheet.

This problem seems to be fixed on beta (5.3.0.17) on my device whereas the others persist.
