### ISSUE TITLE
Signal is not sending messages and I am not receiving messages

### ISSUE THREAD

**Issue by Smulhern05** [signalapp/Signal-iOS#4779]
- [ ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing. Messages are not being delivered and I am not receiving messages

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Messages should have been delivered But nothing is going through it just shows sent
### Device info

**Device**: iDevice X

**iOS version**: 14.3

**Signal version:** 5.2.04

### Link to debug log
 https://debuglogs.org/ed3675338469839371818b695fe624df242ca19305f68832f54a53f7125f37bd.zip

**Comment by SirTypesALot** [comment]
This is most likely to be caused by the sudden surge of new users using Signal and thus stressing out the server. The usage of Signal should return back to normal once the team has managed to increase the capacity of the servers in the up coming days.
