### ISSUE TITLE
Cannot build the xcworkspace on MacBook with M1 chip

### ISSUE THREAD

**Issue by antonshevchenko** [signalapp/Signal-iOS#4780]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Followed the steps in BUILDING.md, however project does not build. Instead, it shows an error with YYImage dependency.

### Steps to reproduce
- git clone --recurse-submodules https://github.com/signalapp/Signal-iOS
- make dependencies
- open Signal.xcworkspace
- update targets to switch team to my own Apple developer account and remove push notifications and data protection permissions
- Build the project

**Actual result:** 
Getting the following error:
```
ld: in /Users/antonshevchenko/Documents/Signal-iOS/Pods/YYImage/Vendor/WebP.framework/WebP(libwebpencode_la-config_enc.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected result:**
Should be able to build the project and run the app.

### Screenshots
<img width="1512" alt="Screen Shot 2021-01-16 at 08 15 53" src="https://user-images.githubusercontent.com/4459581/104814251-7fdf7900-57d3-11eb-92a2-0fabda288123.png">

### Device info

**Device**: MacBook Pro 13" M1 chip

**iOS version**: 14

**Signal version:** 5.2.0

### Link to debug log
Cannot provide debug log from Signal app.

**Comment by domifab** [comment]
Try building it for a real device.
