### ISSUE TITLE
Problem with sending, receiving and read receipts messages 

### ISSUE THREAD

**Issue by GypsyB11** [signalapp/Signal-iOS#4781]
Does not send messages or receive or show the correct delivered and read status! 
Issue has been going on for some days now. 
thank you! 

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by GypsyB11** [comment]
Issues with sending, receiving, delivered, and read status! I have to keep sending again but still it does not send. And if it sends, it would send the next day or so

**Comment by GypsyB11** [comment]
Issues with sending, receiving, delivered, and read status! I have to keep sending again but still it does not send. And if it sends, it would send the next day or so

**Comment by GypsyB11** [comment]
Issues with sending, receiving, delivered, and read status! I have to keep sending again but still it does not send. And if it sends, it would send the next day or so

**Comment by petrsponer** [comment]
Could you provide more details? This may be related to infrastructure/scaling issues
