### ISSUE TITLE
Unable to view contact profile picture by tapping contact picture

### ISSUE THREAD

**Issue by venkatgb** [signalapp/Signal-iOS#4785]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you tap a contact's profile picture to view it enlarged, it does not show up the picture but rather allowing the user to edit the picture. This is not the same behaviour in android.
Phones used for testing are iPhone 7Plus and Huawei Mate 20 Pro

## iPhone 
- Select a contact
- tap on to the profile picture (This takes us to Chat Settings)
- tap on to the profile picture again (Now it auto-selects the name field to edit)
- tap on to the profile picture again (This will enable the user to select a picture that they want to set for a contact)

**Actual result:** No way to view the profile picture as we can view in any other android phone. Basically, the experience of viewing a contact's profile picture is not the same as android.

**Expected result:** On tapping the profile picture of contact, we should be able to view the picture.

### Device info

**Device**: iPhone 7 Plus

**iOS version**: 14.2

**Signal version:** 5.2.0.4

**Comment by hundehausen** [comment]
It would be cool if you could enlarge the profile pictures of your contacts. Maybe even zoom in.

**Comment by g-savitha** [comment]
The above issue is reproduced in iPhone 11 as well.

**Comment by holoX-dev** [comment]
Can confirm, also not possible on iPhone 11 Pro. However, this has been the default behavior on iPhone for years, so I don't believe it's a bug. 
Feature request are supposed to take place on the forum: https://community.signalusers.org/c/feature-requests

**Comment by nikhiltyagicse** [comment]
update your signal app to 5.3.0.16

**Comment by holoX-dev** [comment]
Thanks for the Update, you guys are awesome!

**Comment by holoX-dev** [comment]
This is not yet possible in group chats. 
To view the profile of a group member, you've to open a private chat with them. Maybe this could be added in the future, since it makes figuring out if you know someone you don't have in your contacts a lot easier.

**Comment by venkatgb** [comment]
Thanks for the update guys. I can confirm its working now.
