### ISSUE TITLE
Own messages from Desktop client don't get synched to iOS client

### ISSUE THREAD

**Issue by LilaQ** [signalapp/Signal-iOS#4789]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I'm having discussions over the Desktop Client (OS X Big Sur) and check the Signal App on iOS later, only the messages of the other party appear, mine are not present and don't seem to get synched at all.

### Steps to reproduce
- Have conversation over OS X Desktop client
- Check iOS app later

**Actual result:** Only messages from other party appear in iOS client

**Expected result:** My replies should appear as well.

### Screenshots
![IMG_FF17EC9849C2-1](https://user-images.githubusercontent.com/2311758/104853304-33458c00-5900-11eb-9d83-df66f49196df.png)

### Device info
**Device**: iPhone 12 

**iOS version**: 14.2.1

**Signal version:** 5.1.0.31

### Link to debug log
no debug log available as it's happening over time

**Comment by bhison** [comment]
For the record, as someone also experiencing this since the server outage, the issue doesn't happen the other way.

**Comment by seehat** [comment]
This also happens to me. I can add a logfile. For example the message with id 1610968836207 didn't get transfered from the desktop app to the ios app. 

[org.whispersystems.signal 2021-01-18--11-07-15-855.log](https://github.com/signalapp/Signal-iOS/files/5830818/org.whispersystems.signal.2021-01-18--11-07-15-855.log)

**Comment by MarcCK** [comment]
Same for me.
Phone suddenly stopped after a while to sync messages. 

Fresh iPhone SE 2020, fresh Macbook Air M1. 
Did a Wipe of Signal App on mobile and desktop. Clean installed all new. Happened again.
Log from phone attached.
https://debuglogs.org/56ea7dd9fdcf0cb800e559d2913e9e868fa46afbe73366677568e6e0a878a88e.zip

**Comment by hopped** [comment]
Same for me as well. I am using the Windows Desktop Client (version 1.39.5) and the current IOS app. All messages that I write on the Desktop Client are not synced to mobile.

**Comment by LilaQ** [comment]
Quick feedback. Had an update for the OS X Client today, messages seem to synch to my iOS client now as well. Can anyone confirm?

**Comment by MarcCK** [comment]
Can confirm. New Version of Desktop app seemed to fix it. (1.39.6)
