### ISSUE TITLE
Messages get sent but can't receive

### ISSUE THREAD

**Issue by r2binx** [signalapp/Signal-iOS#4792]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Outgoing messages are sent but not marked as delivered. The recepient however gets them. Incoming messages do not arrive and are not marked as delivered on the sender. Calls do not arrive as well.

### Steps to reproduce
- can't reproduce on another device

### Device info
**Device**: iPhone 7

**iOS version**: 14.3

**Signal version:** 5.2.0.4

### Link to debug log
https://debuglogs.org/f52a39987ef26fb11cc40ccf713c53cf2687946c220bff12a28a9584aac03b15.zip

**Comment by errn1210** [comment]
I’m having the same issue. 7 hours now.

**Comment by mojeeto** [comment]
Me too

**Comment by meinto** [comment]
Any updates on this? Possibly connected with https://github.com/signalapp/Signal-Android/issues/10727 and https://github.com/signalapp/Signal-Android/issues/10693

**Comment by r2binx** [comment]
So it seems like the session was borked and couldn't decrypt the messages but the refresh session button only appeared in one chat and didn't work. Though linking it to the desktop app fixed it for me.

**Comment by wurstsemmel** [comment]
> Though linking it to the desktop app fixed it for me.

For me, using the Signal Desktop App once restored my Signal Mobile App (Signal 5.2.3, Samsung Galaxy S9, Android 10, One UI-Version 2.5), at least partially.

A few of my contacts receive messages from me and vice versa, but I still do not get the delivered message status (same as before doing the "Desktop-App-Hack"). I only get the sent message status.

**Comment by wurstsemmel** [comment]
> A few of my contacts receive messages from me and vice versa, but I still do not get the delivered message status (same as before doing the "Desktop-App-Hack"). I only get the sent message status.

In the meantime my Signal App works as expected for all contacts. My guess is that all communication partners need to have the most recent App version installed and in addition the Signal network needs time to get back to normal operation.

**Comment by peterchen145** [comment]
I have similar problem on my Iphone. My iOS Signal app suddenly can't receive message days ago. I reinstall it , use another phone number, upgrade my iOS version, didn't work. Finally I use Android , it works well. Still don't know why.
