### ISSUE TITLE
Pairing between 2 iPhones not working

### ISSUE THREAD

**Issue by chimp1984** [signalapp/Signal-iOS#4793]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have 2 iPhones and want to pair both with the same tel. number. I get to the QR code screen and the scan screen on the other phone but it does not recognize the qr code. Nothing happen. The qr code is partly covered by some description text, maybe that renders the qr code unreadable. I repeated several times in both directions (iPhone 8 -> iPhone 6 and the other way round).

Beside that there is another bug that I cannot change the telephone number for registering, so I cannot even register Signal with another telephone number I have. It even detects a wrong tel numnber not the one which is used on that phone. Any attempt to change number or country code (there is an arrow in the UI so it looks like it should be changable) fails. That happened on iPhone 6.

### Steps to reproduce
- Start registering on one phone
- Start on second phone, select use existing account (pairing)
- Try to scan with other phone QR code

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Nothing happens at read QR code

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Pairing should work

### Device info

**Device**: iPhone 6, iPhone 8

**iOS version**: 12.4.5 on  iPhone 6, 13.6 on iPhone 8

**Signal version:** latest version on 17.1.2021

**Comment by NiklasBr** [comment]
Still relevant

**Comment by NiklasBr** [comment]
Still relevant, please stop spamming this question.
