### ISSUE TITLE
Can’t edit group information

### ISSUE THREAD

**Issue by parseiro** [signalapp/Signal-iOS#4799]
Hi, I’m admin but cannot edit information not add or delete people. Log below. 

https://debuglogs.org/0c1c5c5ba9bf3c4a7bc3293b9c535d72c9711c1f1e9c1dc09460919a2ac7dfad.zip

**Comment by parseiro** [comment]
Today things started working again. Maybe there was an update?

**Comment by brotherelric** [comment]
close your issue if it was solved.
