### ISSUE TITLE
Sync issue from desktop app to iOS app

### ISSUE THREAD

**Issue by shiraz** [signalapp/Signal-iOS#4800]
### Bug Description
If the iOS app is linked to the desktop app, and messages are sent to a user (any user), the messages sent from the desktop app are not seen in the iOS app.

### Steps to Reproduce
1. Download the iOS app on an iPhone.
2. Download the desktop app on a Macbook.
3. Link the iOS app to the macOS app.
4. Send a message to someone on the desktop app.
5. Now go to the iOS app, and observe that the messages sent from the desktop app do not make it to the iOS app.

Actual Result:
The messages sent from the desktop app do not make it to the iOS app.

Expected Result:
The messages sent from the desktop app should be seen in the iOS app as well.

### Platform Info

Signal Version: v1.39.5(mac OS), 5.2.1.3(iOS)

Operating System: macOS 10.15.7

Linked Device Version: iOS 14.2

**Comment by greenstevester** [comment]
Directly related to https://github.com/signalapp/Signal-Desktop/issues/4896 ..and either the root cause is server-side, client-side or both.

**Comment by nikhiltyagicse** [comment]
update your signal desktop app
