### ISSUE TITLE
Unable to see Signal contacts

### ISSUE THREAD

**Issue by Sample-User** [signalapp/Signal-iOS#4810]
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to load/retrieve/see any of my Signal contacts, so unless someone text/call me first I cannot contact anyone.
It's a duplicate of this exact issue: https://github.com/signalapp/Signal-Android/issues/10739
The only difference is that I'm running iOS instead of Android so for this reason I've opened another issue.
The only workaround (except the first one) if I want to contact someone is selecting the desired contact and then selecting Signal in the native iOS dialer app.
Another collateral bug is that while inspecting exchanged messages with one of my contacts is that their status is "Sent" and not "Delivered".

### Steps to reproduce
- Install latest compatible Signal version (3.9.1.1) for iPhone 5
- Allow Contacts access

**Actual result:** 
Contacts list isn't displayed

**Expected result:** 
Contacts list should be displayed

### Device info
**Device**: iPhone 5

**iOS version**: 10.3.4

**Signal version:** 3.9.1.1

Debug Log can be provided if strictly required to resolve the issue.

Thanks

**Comment by timmkrause** [comment]
Same here.

**Comment by gir489** [comment]
I had this problem in #4438, the solution was to just uninstall and reinstall Signal a bunch of times and eventually it just worked.

**Comment by Sample-User** [comment]
Already tried the above solution but no luck so far.
Manually searching for a specific number of a Signal user give me "Request failed: client error (429)"

**Comment by timmkrause** [comment]
To be honest, this is not actually a solution, it's a workaround.

If this happens to former WhtsApp users and they identify this misbehavior ("I couldn't find contact X"), it may lead to immediate adoption issues with Signal for them and maybe they'll delete it right away. First user impression: "It doesn't work!"

Just to mention it, another workaround which always worked for me was to search for the phone number (and this again only works without the leading country code format).

**Comment by Clyx** [comment]
Same issue here.
1x iPhone 7 Plus
1x iPhone 8

Contacts are sync from Exchange to the Phone. On iPhone XS with same contacts from Exchange it works fine.
