### ISSUE TITLE
Accessibility: Name of sender of a voice message not available when using voice-over 

### ISSUE THREAD

**Issue by Falcopus1986** [signalapp/Signal-iOS#4811]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When you use voice over and someone sends you a voice message the name of the person isn't shown in the conversation. This makes it difficult to understand the logic of a conversation when you use voice messages the most of the time.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
- Turn voice over on
- Open a conversation 
- When you receive a voice message you only see the length of the message and the time when it was send. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
It is difficult to know who send a specific voice message in a conversation. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
You should see the name of the sender everytime when a voice message is send. It is also better that all the info: name, length, time when send.... is readable on one line.... Otherwise you have to swipe a lot in a conversation when you use voice over.

### Device info

**Device**: iPhone XS

**iOS version**: 14.3.0

**Signal version:** 5.2.1.4

**Comment by VidaHasan** [comment]
Are you still able to repro this in 5.4.0.17? I am not able to repro, though I may not be understanding repro steps correctly.

**Comment by Falcopus1986** [comment]
Hello,

This issue is fixed in version 5.4
