### ISSUE TITLE
High background use in iOS

### ISSUE THREAD

**Issue by brunoalmeida81** [signalapp/Signal-iOS#4812]
Ever since the global outage of the last few days, I’ve been having unusually high background use on my iPhone 11 with iOS 14.3 (1-2h). The app is draining the battery overnight. Here is the debug log:

https://debuglogs.org/d29ac93633405aa090d23f3402cc9e067b8089eff47430bc9a7efda823ac04a0.zip

**Comment by netlazyman** [comment]
i am the same problem. 
it is keep refreshing the session with one of my friend (around 20 times in 30 mins)
battery drain from 70% to 10% in 30mins

signal version: 5.3.1

**Comment by digitlz** [comment]
I have a similar problem but for me it is on my iPad Pro 10.5 on iPadOS 14.4 with Cellular and 512GB. I just uninstalled the app to test if there will be a difference so I don't know the version number anymore (though it was the latest version of today). My battery, which has around 85% of its original maximum capacity, looses around 30% over the course of 8 hours in the night. If I go into the battery details and view the usage for single hours it is always showing Signal as the only app doing something in that time. I don't use the iPad regularly within the week and the standby time is not the best but within the last weeks I noticed that it significantly drops over the course of a day even if I'm doing nothing. It could completely drain within one day and a few hours which is not nice.

**Comment by El-Marti** [comment]
I also find Signal uses a lot of battery. One of the most annoying things is on iPad. If we install Signal on iPad but do not use it, the application is still awake for each message received (even without updating in the background) and therefore the battery also drains slowly without any use of the app and screen turned off.

**Comment by Finally420** [comment]
Same issue, 2hrs of background use over the last 24hrs alone and 20+ % battery drain overnight

**Comment by haszari** [comment]
I am seeing this - heavy battery use. I only installed the app for the first time today, and only have a handful of messages/chats.

Also, typing in the app is incredibly slow and laggy.

**Comment by etavarez** [comment]
wanted to comment in this issue to note that this appears to be an active issue for me on the latest iOS 14.8.1 and iOS 15.2. Background app activity is unusually high (30min onscreen, yet 1hr & 42mins of activity). Background refresh is disabled.

https://debuglogs.org/e84bfe9fc5d6a024c5ce7dc88e1a8df3d291a581bf2b8403d065cf2e84c1c090.zip

**Comment by El-Marti** [comment]
Hi, I have not the issue on my iPad anymore.
All the messages are downloaded at the app's startup.

**Comment by Tarasovych** [comment]
There is an issue with significant battery drain overnight because of notifications, version 7.42.1 (569)
