### ISSUE TITLE
[Bug] thumbnail is displaying half of the photo and other half is blur

### ISSUE THREAD

**Issue by JodyVanden** [signalapp/Signal-iOS#4815]
### Bug description
Thumbnail displays only half of the photo correctly and the other half is blur

### Steps to reproduce
- in a conversation, select the camera
- select any photo to be shared
- once the photo selected click share

**Actual result:**
- photo appears half ok and half blur

**Expected result:**
photo should be entirely displayed

### Screenshots
![Screenshot_20210121_231020](https://user-images.githubusercontent.com/25408202/105350272-01556200-5c3f-11eb-9316-4616fabfefe7.jpg)

### Device info
**Device**: Huawei 20 pro

**Android version**: 10.0.0

**Signal version:** 5.2.3

### Link to debug log
https://debuglogs.org/9b131a4889f86e4d8e5812932fb1791fe5861193a47caf716472d306f45c0f66

**Comment by Daboo1998** [comment]
I think that's the wrong repo to post Android issues. Go to https://github.com/signalapp/Signal-Android/issues instead.

**Comment by JodyVanden** [comment]
damn ... I thought I checked I was! thanks
