### ISSUE TITLE
Video from the DESKTOP is displayed VERTICALLY on the PHONE but SHOULD be HORIZONTAL

### ISSUE THREAD

**Issue by kevinlambert** [signalapp/Signal-iOS#4816]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
WHEN the DESKTOP initiates the video call
AND the PHONE is in portrait orientation
AND the call is answered on the PHONE

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The video from the DESKTOP is displayed vertically on the PHONE

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The video from the DESKTOP SHOULD be displayed horizontally on the PHONE

### Screenshots

DESKTOP
<img width="1250" alt="Bug-on-phone—desktop" src="https://user-images.githubusercontent.com/939866/105377100-5cb52f00-5c02-11eb-8d0f-70315b84b444.png">

PHONE: Video should be displayed horizontally
![Bug-on-phone—phone](https://user-images.githubusercontent.com/939866/105377236-7e161b00-5c02-11eb-84ee-25e62115bc13.PNG)

### Device info

**Device**: iPhone 7 (MN922B/A)

**iOS version**: IOS 14.3

**Signal version:** 5.2.1.3

**Linked Device Version:**
Signal Version: Desktop v1.39.6
Operating System: OSX 10.15.7

**Comment by gir489** [comment]
Why did you bother to blur your face in the screenshot, yet your avatar is your headshot?

**Comment by Imperiopolis-Signal** [comment]
This is by design. Incoming video always fills the screen, you can turn your phone 90º to see them right side up (and you’ll better fill their screen too). If you’d like to suggest a change to this behavior, you can do so on our [community forums](https://community.signalusers.org).

**Comment by kevinlambert** [comment]
You are forcing the user to use their phone in a way that is unnatural and not the behaviour a user would expect - therefore it's a bug (even if by design). Users default to holding their phones in portrait orientation. 

Yes, the incoming video may need to be letterboxed in portrait orientation but users especially on IOS expect that. They know that if they turn the phone to landscape orientation then the video will fill the screen. That's the expected behaviour and has been taught to them through the way FaceTime works. If the user expects a certain behaviour and they get a different result then it's a bug.

**Comment by Imperiopolis-Signal** [comment]
The behavior we use matches the behavior iOS users expect from other apps, like FaceTime. FaceTime does not letter box video.

**Comment by jc-clown** [comment]
Also having this issue. When receiving mobile app calls that are answered with desktop (iMac) the orientation on the callers phone is flipped by 90 degrees on their phone. Obviously I can't flip my 27in iMac around to correct it and if the phone user turns their phone to see me properly, they are then turned 90degrees on my iMac screen.

I would disagree this is how Facetime works... it is worthy of a deeper look and/or change(if implemented by design)

**Comment by kevinlambert** [comment]
> The behavior we use matches the behavior iOS users expect from other apps, like FaceTime. FaceTime does not letter box video.

Hey @Imperiopolis-Signal that's incorrect. FaceTime does letterbox the video on both Phone and Desktop when needed. See the Screenshots below. 

In both cases the user decides how they hold their device. Not the person on the otherwise of the call.

Phone Screenshot
![FaceTime-iphone](https://user-images.githubusercontent.com/939866/105834963-14f82400-5fc3-11eb-998e-2594467566fa.PNG)

Desktop Screenshot
<img width="1680" alt="FaceTime-Desktop" src="https://user-images.githubusercontent.com/939866/105834978-1aee0500-5fc3-11eb-8261-4a3042ea49f8.png">

**Comment by kevinlambert** [comment]
Posted in Signal Community: https://community.signalusers.org/t/video-orientation-issues-across-devices-and-platforms/28272

**Comment by GenosseFlosse** [comment]
I am having the same issue when calling between win10 and iOS. Very strange. 

Even if what @Imperiopolis-Signal says that this is intended behaviour and the iOS user turns the phone, the Desktop version shows a rotated version of their picture and I cannot rotate my desktop 🤷 

Only option at this time is to software-rotate my own webcam picture by 90°. Then iPhone user has my picture upright but my self-view video is rotated. So either way to me this behaviour does not make any sense and drives me crazy 🤯  Upright picture on desktop should result in upright picture on iPhone and vice versa.

**Comment by gitcob** [comment]
Having the same issue on Win10 and Android. Also when I use Nvidia broadcast for filtering, the person on the phone only sees a part of the image.
