### ISSUE TITLE
[Bug] Camera enabled when editing a picture before sending

### ISSUE THREAD

**Issue by ch4tterb0x** [signalapp/Signal-iOS#4817]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The camera is enabled in the editing screen, after a picture has been selected to be send. The activated camera is shown by the green camera indicator of iOS.
The camera should not be activated when edting on or multiple pictures.

### Steps to reproduce
- Open a chat
- Press "+" on the bottom left
- Tap on a pictur
- The camera indicator will show when the editing screen shows

**Actual result:** The camera is turned on while edtiting a picture. (Shown by green camera indicator of iOS)

**Expected result:** The camera should stay disabled when editing a picture.

### Device info

**Device**: iPhone X

**iOS version**: 14.3

**Signal version:** 5.2.1.3

Might be related to #4751

**Comment by lukaskirner** [comment]
Also on iPhone 12 (iOS 14.3) with Signal Version 5.3.1.0

**Comment by MEPoss** [comment]
Also on iPad 6th gen (iPadOS 14.4) with Signal Version 5.4

**Comment by deeps-lab** [comment]
Facing same issue with the latest version of iOS and Signal :(
