### ISSUE TITLE
Adding Gif to message with existing text wipes the existing text

### ISSUE THREAD

**Issue by theyetiman** [signalapp/Signal-iOS#4818]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you start typing a new message, then add a Gif, the text you just typed gets erased and you have to re-type it.

### Steps to reproduce
- Open a chat
- Start typing a message
- Press the "+" icon to attach something
- Choose "GIF"
- Select any gif
- Observe that the previously-typed text has gone
- Press send
- Observe that the text does not send to the chat, either

**Actual result:** The previously-typed text is erased

**Expected result:** Any text you have previously written should remain.

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 14.3

**Signal version:** 5.2.1.3

**Comment by zruiitzuw** [comment]
> * [x]  I have searched open and closed issues for duplicates
> * [x]  I am submitting a bug report for existing functionality that does not work as intended
> * [x]  This isn't a feature request or a discussion topic
> 
> ### Bug description
> When you start typing a new message, then add a Gif, the text you just typed gets erased and you have to re-type it.
> 
> ### Steps to reproduce
> * Open a chat
> * Start typing a message
> * Press the "+" icon to attach something
> * Choose "GIF"
> * Select any gif
> * Observe that the previously-typed text has gone
> * Press send
> * Observe that the text does not send to the chat, either
> 
> **Actual result:** The previously-typed text is erased
> 
> **Expected result:** Any text you have previously written should remain.
> 
> ### Screenshots
> ### Device info
> **Device**: iPhone 8 Plus
> 
> **iOS version**: 14.3
> 
> **Signal version:** 5.2.1.3
> 
> ### Link to debug log
