### ISSUE TITLE
Safety number changing but verified tick mark remaining

### ISSUE THREAD

**Issue by danielschonfeld** [signalapp/Signal-iOS#4819]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Reinstalling signal on a new phone, having changed from an older phone, utilizing the start new method.  Not transferring from another device.  I start a chat with an old contact, which i've verified on my old phone with a tick mark.  I see right away a tick mark, on the newly opened chat.  Curious, I open the safety number and discover the safety number has changed.  Question is, should the verified tick mark still be there if the safety number itself has changed from underneath?

### Steps to reproduce
- Mark someone as verified on a chat you're having with them
- Install signal IOS on a new device
- Select the option of starting anew, not transferring signal from a device near by
- Hit "pencil" button to create a new chat
- Choose the contact with whom you've had a chat before and have verified

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Observe tick mark existing
- Go into 'Safety Numbers' and observe the number itself has changed slightly.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I would have expected for the tick mark to not be there if the numbers have changed.  Or to be there if the numbers are the same.  

**iOS version**: 14.3

**Signal version**: 5.2.1.3

**Comment by Imperiopolis-Signal** [comment]
The safety number is a representation of your identity key and the remote party’s identity key and is purely done this way for convenience in comparing. The verification state is a verification of the remote party’s identity key. When you re-installed, you must have entered your PIN, restoring your saved verification states. You have a new identity key, but the remote party does not, so they remain properly verified even though the visible safety number has changed.
