### ISSUE TITLE
Unlimited attempts to enter the PIN when not clicking on Submit

### ISSUE THREAD

**Issue by cartucciam** [signalapp/Signal-iOS#4820]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Could one use the PIN autoverification as you type to circumvent the maximum number of attempts restriction?

I tried on my phone and was able to type back and forth for a while.

### Steps to reproduce
- when Signal asks for your PIN
- type back and forth

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
A person can try several attempts until they guess the correct PIN.
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
One should have a finite number of attempts.
### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Imperiopolis-Signal** [comment]
PIN reminders are not a security feature, they are intended to prevent you from forgetting your PIN since they cannot be recovered. You can change your PIN at any time without knowing the previous value. 

During registration on a new phone, you are limited to a total of 10 pin guesses before all of your data is lost.

**Comment by cartucciam** [comment]
Thanks for explaining this to me. If I may ask then, if there aren't security repercussions why the submit has a fixed number of attempts?

**Comment by Imperiopolis-Signal** [comment]
> Thanks for explaining this to me. If I may ask then, if there aren't security repercussions why the submit has a fixed number of attempts?

Submitting on the reminder view doesn’t have a fixed number of attempts. The only time attempts are limited are when entering your pin when registering on a new phone.
