### ISSUE TITLE
Can’t share content between apps and Signal

### ISSUE THREAD

**Issue by hugosantos-io** [signalapp/Signal-iOS#4826]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the feature of Share (native iOS) for things like images the pop-up closes

### Steps to reproduce
- Open any app that can share photos for example: WhatsApp, Photos, Telegram
- Select Share (system menu)
- Select Signal

**Actual result:** The pop-up closes

**Expected result:** I'd like to share photos

### Screenshots
Selection
![image](https://user-images.githubusercontent.com/11799652/105606776-05d26580-5d7a-11eb-86d4-ffde3e37af01.png)

I got an error when selecting Signal
![image](https://user-images.githubusercontent.com/11799652/105606790-11be2780-5d7a-11eb-9d9d-aa88eba9bcbe.jpeg)

### Device info
**Device**: iPhone 11 Pro Max

**iOS version**: 14.3

**Signal version:** 5.2.1.3

### Link to debug log
https://debuglogs.org/9c7c3e8f64d471acb2668dee7e8468ef154d0ca845b0191ec65d7e4dd785a420.zip

**Comment by Rostbanker** [comment]
I have the same problem

**Comment by stamceidas** [comment]
Do you guys have logged in with iCloud account in this case?

**Comment by Rostbanker** [comment]
> Do you guys have logged in with iCloud account in this case?

Yes

**Comment by hugosantos-io** [comment]
Yep but what's the link?

**Comment by saikrishnakota** [comment]
This is important to fix

**Comment by technorainbows** [comment]
I've had this issue for years. Recently it starting to work a little. For example, over the last week I seem able to take a screen shot and immediately share it to a contact on Signal, however if I open a photo in the Photos app and try to share to Signal, nothing really happens. The icon kind of expands a little to show it has been clicked but then goes right back to the normal size with out the intended behavior occurring (e.g., I still haven't been able to share a photo to someone on Signal). 

Have you guys noticed any changes in the last week, and further, currently do you find sharing a screen shot works but sharing a photo from the Photos app doesn't?

**Comment by Rostbanker** [comment]
latest version - everything is ok

**Comment by technorainbows** [comment]
> latest version - everything is ok

@Rostbanker - native photo sharing works too? I edited my comment above to be more clear.

**Comment by normamelhoranca** [comment]
Everything ok!

**Comment by hugosantos-io** [comment]
Everything is good now! Thanks Signal community.
