### ISSUE TITLE
Microphone permission not requested before first call received

### ISSUE THREAD

**Issue by adunning** [signalapp/Signal-iOS#4827]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On receiving my first call on Signal for iOS (I had never placed one), the caller at the other end could not hear me. Only after hanging up was I presented with a request from Signal to access the microphone.

### Steps to reproduce
- Install Signal on iOS and run through the normal setup (which will not request microphone/camera permissions)
- Have a call sent to Signal on the phone while it is still locked
- Pick up the call from the lock screen

**Actual result:** No audio is sent to the other caller, because Signal does not have permission to use the microphone.

**Expected result:** The user is given the opportunity to grant permission for Signal to use the microphone, or at least a notification that it cannot access it. It would likely be simplest to request this on first run.

### Device info

**Device**: iPhone 7

**iOS version**: 14.3

**Signal version:** 5.2.1.3

### Link to debug log
<https://debuglogs.org/b989399921387b5b9553d6025fddf29b3fa0ece52bd51d60d9c3c3da6e2c3e4c.zip>

**Comment by elemanhillary** [comment]
@adunning i can confirm its a bug i will work on this
