### ISSUE TITLE
Feature Request: Add support for full resolution image sending

### ISSUE THREAD

**Issue by mlindner** [signalapp/Signal-iOS#4828]
Currently Signal prevents you from sending uncompressed images and insists on decompressing the image. This is a user anti-feature. This pushes people away from using the service and on to using platforms like iMessage that allows uncompressed images.

You say to put this on the forums, but I don't have an account there and I don't use websites for feature requests. Github is sufficient.

This should be trivially simple to add, just don't force the image through Signal's processing that ruins the image.

**Comment by Imperiopolis-Signal** [comment]
Github is reserved for bugs, if you'd like to discuss this you'll need to use our community forums.
