### ISSUE TITLE
Incorrect country code for Bouvet Island

### ISSUE THREAD

**Issue by TCampmany** [signalapp/Signal-iOS#4829]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Bouvet Island is listed as having the country code +55, which belongs to Brazil

### Steps to reproduce
- New message
- Find by Phone Number
- click on Country Code
- Search by number: 55

**Actual result:**
Within the list you will see:
- Bouvet Island (+55)
- Brazil (+55)

**Expected result:**
- Bouvet Island (+[something else]\)
- Brazil (+55)

### Screenshots
![image](https://user-images.githubusercontent.com/4998080/105618508-bb2b0a80-5dc6-11eb-8787-e6eb63cf7bac.png)

### Device info
**Device**:  iPhone 12 Pro Max
**iOS version**: 14.3
**Signal version:** 5.2.1.3

**Comment by bobisapotato** [comment]
Bouvet island country code is +55 (via http://country-dialing-codes.net/Bouvet-Island/ )

**Comment by TCampmany** [comment]
Well, DuckDuckGo (and Google) are wrong in this case. - By the way, all the listed cities from your link are from Brazil.

Please take a look into: 
- [https://en.wikipedia.org/wiki/Country_codes:_B#_Bouvet_Island](https://en.wikipedia.org/wiki/Country_codes:_B#_Bouvet_Island) - by the way, Brazil is the item after Bouvet Island.
- and [https://en.wikipedia.org/wiki/List_of_country_calling_codes](https://en.wikipedia.org/wiki/List_of_country_calling_codes)

In the second Wikipedia link you can also find the source: [https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164D-2016-PDF-E.pdf](https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164D-2016-PDF-E.pdf), and as it looks like, Bouvet Island has no Telephone Country Code (E.164 code).

**Comment by bobisapotato** [comment]
This needs to be changed then. I was wrong.
