### ISSUE TITLE
Signal's contact list seems unreliable and shows non-Singal users as well

### ISSUE THREAD

**Issue by venthur** [signalapp/Signal-iOS#4830]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal shows contacts in its contact list that are not actually Signal users (anymore?) Sending a message to such a contact fails because the other side is no Signal user.

### Steps to reproduce
- search for someone in Signal's contacts
- write a message the them
- press send

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- see it failing with error that the other side is no Signal user. (Number is not registered. (original: promiseAjax: invalid response; code: 404)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Failure to send is not actually the problem here, rather that Signal makes me believe in the first place that the other side is using Signal by showing them in my Contacts.

### Device info

**Device**: iDevice X

**iOS version**: 14.3
**Signal version:** 5.2.1

**Comment by holoX-dev** [comment]
Can confirm the same behavior on iPhone 11 Pro (IOS 14.3) and Signal 5.3.0.16

**Comment by modeitsch** [comment]
me too

**Comment by venthur** [comment]
Unfortunately the issue still exists and is not fixed yet.

**Comment by venthur** [comment]
still an issue, unfortunately.

**Comment by venthur** [comment]
Why is this closed automatically? The issue is still not fixed.
