### ISSUE TITLE
Def

### ISSUE THREAD

**Issue by zruiitzuw** [signalapp/Signal-iOS#4838]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by SpheeresX** [comment]
What?

**Comment by EshtonMartin** [comment]
Hyphens turn into bullet points when text written in Markdown is rendered. Its shorthand is appearing more frequently in apps (incl GitHub), but it's not universal. 

Signal doesn't seem to render markdown (nor html--and I'd bet there's a security reason behind that decision).

It looks like your options are to just use dashes or switch to the alternate numeric keyboard and type the symbol itself instead. 

You can find it by:
• hitting the [123] on the lower left side of your keyboard
• followed by the [#+=] key one row up.
• The bullet symbol is directly above the backspace key. 

Cheers!
