### ISSUE TITLE
FEATURE: Reply privately

### ISSUE THREAD

**Issue by alonbl** [signalapp/Signal-iOS#4843]
Hello,
It would be great if you consider adding an option to reply privately to a message sent in a distribution group. Design wise may be long select of existing reply button as used in other iOS applications. 
Thanks,
Alon

**Comment by g-savitha** [comment]
Hey @alonbl, Please use this [forum](https://community.signalusers.org/c/feature-requests/ios-feature-requests/19) for feature requests.

**Comment by alonbl** [comment]
Sorry
