### ISSUE TITLE
cannot reply properly on audio messages

### ISSUE THREAD

**Issue by ItzSheldor** [signalapp/Signal-iOS#4844]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If i want to reply to a playing audio message its just scrolling through the audio in stead of doing the reply thing.

### Device info
**Device**: iPhone 12 Pro Max

**iOS version**: 14.4

**Signal version:** 5.3.1.0

**Comment by elemanhillary** [comment]
@ItzSheldor you have to tap at the bottom of audio and slide to reply.
