### ISSUE TITLE
Long pressing back button doesn't display proper locations

### ISSUE THREAD

**Issue by thesohelshaikh** [signalapp/Signal-iOS#4845]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When long pressing the back button, the menu doesn't display the locations that can be reached directly. It displays empty screen.

### Steps to reproduce
- click on a chat 
- click on the name of the chat
- long press back button to see location that can be navigated 

**Actual result:** 
The placeholders are empty and do not display the name, however the number of locations that can be reached is correct

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Name of the locations must be displayed, i.e Main Chat Screen, User Chat

### Screenshots

<img src ="https://user-images.githubusercontent.com/26832180/106089921-fe7ed380-614e-11eb-8777-fac9691fbd3b.jpg" width = "50%">

### Device info

**Device**: iPhone X

**iOS version**: 14.3

**Signal version:** 5.3.1

### Link to debug log

Not required

**Comment by LeoniePhiline** [comment]
Same with Signal 5.3.2.1

**Comment by thesohelshaikh** [comment]
Any update on this?
