### ISSUE TITLE
Echo on calls

### ISSUE THREAD

**Issue by lukeaus1974** [signalapp/Signal-iOS#4849]
Own voice is repeated during calls: echo issue

**Comment by Ashok314** [comment]
Can you please provide more details, like app version, OS, and steps to reproduce if any?

**Comment by lukeaus1974** [comment]
Hi,

App version 5.3.1.0
OS 14.4 (apple iphone)

Installed app. Echo problem. Uninstalled app. Reinstalled app. Problem persists...

Thanks!

**Comment by dasco597** [comment]
same thing here:

app version: 5.3.1.0
ios: 12.4.9
iphone 6

when in a video call I hear my own voice loud enough not to hear what's being said on the other end. no problem when using whatsapp.

looks like there's a few others affected on ios: https://old.reddit.com/r/signal/comments/islqok/voice_echo/
