### ISSUE TITLE
Signal crashes on iPhone 5

### ISSUE THREAD

**Issue by Kreader-app** [signalapp/Signal-iOS#4851]
Signal crashes on iPhone 5 after about 5 seconds after launching the app. This started after updating to the newest version three days ago.

**Comment by Ashok314** [comment]
Can you please provide both version details of iOS and the Signal App. Thanks

**Comment by Kreader-app** [comment]
Signal version 5.3.1
iOS 11.2.5

**Comment by Kreader-app** [comment]
Still crashing on version 5.3.2.

How can I revert to version previous to 5.3.1?

**Comment by Kreader-app** [comment]
I timed the crashing. The app crashed like clockwork *exactly* 10 seconds after launch. Each and every time.

**Comment by anshulsamar** [comment]
I am also having this issue - on version 5.4 and iPhone 6 (12.5.1). thank you!

**Comment by Kreader-app** [comment]
Still crashing on  version 5.5.0.  Is this likely ever going to be fixed or have you stopped supporting iOS 11?

**Comment by softviolence** [comment]
I have been experiencing a similar issue (app just won't open at all, I wish I could get in for 10 seconds!) on iphone 6s, now updated to iOs 14.4 and 5.5.0 and no change.

**Comment by Kreader-app** [comment]
Still crashing on version 5.7. Is this likely ever going to be fixed or have you stopped supporting iOS 11?
