### ISSUE TITLE
Invite - No option to change designated telephone number resulting in potential unexpected calls on the landline

### ISSUE THREAD

**Issue by Rh9no** [signalapp/Signal-iOS#4853]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

There is no option to change the phone number when sending an invite link to an existing contact if that contact has multiple numbers associated with them which could result in the text message being sent to a land line, which can cause the landline operator to convert the text message to voice and will repeatedly do this until the message is heard.  All can be avoided by defaulting the invite to the mobile number and not the first entry associated with the contact.

### Steps to reproduce

- Firstly, add a new contact to the phone which has a "home" telephone number first and "mobile" number as well for this same contact.

1. Open Signal.
2. Open Settings.
3. Select "Invite Friends".
4. Select the new contact.
5. Press done.
6. New message is displayed with default invite text automatically insert.
7. Press send and it will send to the first number associated with the contact.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- Invite gets sent to the first number associated with the contact.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- There should be an ability to change the number and/or default to the mobile number.

### Device info

**Device**: iPhone SE

**iOS version**: 14.3

**Signal version:** 5.3.1.0

**Comment by mexson** [comment]
I don't understand the bug. Perhaps complete the steps to reproduce and the expected result?
