### ISSUE TITLE
Share Extension crashes in debug mode

### ISSUE THREAD

**Issue by tomxpcvx** [signalapp/Signal-iOS#4855]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hi I am currently trying to integrate the ability to import chat histories into Signal. 
About my setup, I have the AppStore Signal app and the debug app from Xcode on one phone. 
On my way through the code I came across the SignalShareExtension, with which I now have the following problem.
When I try to share files to the debug app, the screen blurs slightly and tries to open the app. Fails to do so and then crashes.
Now when I debug the SignalShareExtension via Xcode then Xcode throws me into the code, after sharing a file to the debug app via iOS share menu.

`Pods/Pods/SignalCoreKit/OWSSwiftUtils.swift`on line 35
``assertionFailure(formattedMessage)`` and says ``Thread 1: Fatal error: [Error.swift:11 init(_:)]: assertionError: CipherKeySpec inaccessible; not main app.``

In the debugger I get displayed:
``
warning: Swift error in scratch context: error: could not find module 'SignalCoreKit' for target 'arm64e-apple-ios'; found: arm64
.
Shared Swift state for SignalShareExtension has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.
``

### Steps to reproduce
1. Clone master branch
2. Setup project as described in BUILDING.md
3. Install app via Xcode on your phone
4. Login into Signal with QR code from production app
5. Try the share a file via iOS share menu directly to the debug app

**Actual result:** Share extension crashes after a second.

**Expected result:** Share extension opens the share view.

### Device info

**Device**: iPhone 11 Pro (iPhone 12,3)

**iOS version**: 14.4

**Signal version:** current master branch commit: 02042cd26ea7549b5bfc52a3e0048b91eef9b9ce

I have sent a crash log by e-mail.
Greetings from Germany! 👋🏼

**Comment by tomxpcvx** [comment]
Same problem appears on a iPhone 6 (iPhone 7,2) with iOS 12.5.1 installed on it.
Only the debug app is running on this phone.

**Comment by Luke-Filewalker** [comment]
Thank you for this :) 
Hope this is finished soon

**Comment by tomxpcvx** [comment]
Ticket should remain open, issue still exists.

**Comment by tomxpcvx** [comment]
Ticket should remain open, issue still exists.
