### ISSUE TITLE
Profile picture was reset after update

### ISSUE THREAD

**Issue by pilgi3** [signalapp/Signal-iOS#4860]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My profile picture was resetted after the last update 5.3.2.
I could remember this happens also a few previous versions.
Photo library restriction was / is set to "All photos".

### Steps to reproduce
- set a picture for your profile from the photo library
- install the update from the App Store
- that reproduce the bug

**Actual result:** The profile picture is gone and replaced by the default one.

**Expected result:** The profile picture should stay

### Screenshots
![image](https://user-images.githubusercontent.com/44865075/106736017-384f4e80-6615-11eb-9a00-8e8f43eb7174.jpeg)

### Device info

**Device**: iPhone 12 Pro

**iOS version**: 14.4

**Signal version:** 5.3

### Link to debug log

https://debuglogs.org/d07dbfe2901817485295979501a7dba1380cce6839d2b0b6d405c8914b6551d0.zip

**Comment by mthld** [comment]
Same problem here: https://debuglogs.org/a2fb4df21690135d9a14b479aabf39cde712aa9bee0a112bb13621abcb25a15a.zip

**Comment by pilgi3** [comment]
Ìt would be great if somebody from signal could check this out, because this happens to multiple users.
Thanks!

**Comment by pilgi3** [comment]
Happens with the update 5.6 again ☹️

**Comment by hexxxx** [comment]
This happens to me as well, though it isn’t dependent on updates. Every few hours my profile photo will be removed.

**Comment by mthld** [comment]
> This happens to me as well, though it isn’t dependent on updates. Every few hours my profile photo will be removed. 

Yes I don't believe it's related to an update or another. It happens randomly to me.

**Comment by kingchun1991** [comment]
Same here

**Comment by hexxxx** [comment]
I have this temporarily working. I deregistered my phone, removed my PIN, set a new one, delinked all devices and deleted data, then re-installed linked applications. will update if it lasts.

**Comment by mthld** [comment]
> I have this temporarily working. I deregistered my phone, removed my PIN, set a new one, delinked all devices and deleted data, then re-installed linked applications. will update if it lasts.

And loose all messages history, that's clearly not a solution.

**Comment by pilgi3** [comment]
It looks like the issue is fixed right now.
I did not have this problem anymore.

**Comment by mthld** [comment]
> It looks like the issue is fixed right now.
> I did not have this problem anymore.

Another mysterious issue who mysteriously fixed itself without any of Signal's monkey touching anything server-side, what an amazing project. 😎
