### ISSUE TITLE
Forwarded pictures rotated wrong 

### ISSUE THREAD

**Issue by guest-tech** [signalapp/Signal-iOS#4863]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When forwarding a picture the picture gets rotated wrong in the preview before sending. I receive wrongly rotated pictures from people who just sent the forwarded picture without correcting rotation in the preview. 

### Steps to reproduce 
- open a chat which contains a forwarded picture received 
- forward that picture 
- Preview opens and the picture gets rotated wrong
- Click on send and the picture is sent with wrong rotation 

**Actual result:** the picture gets rotated wrong

**Expected result:** the picture should not be rotated 

### Device info

**Device**: iPhone 11 pro

**iOS version**: 14.4

**Signal version:** 5.3.2.1

### Link to debug log

https://debuglogs.org/e82ba79ae235191579bab519b9eb089ecc06b2497a2360334f19ab00a410428c.zip

**Comment by i7u** [comment]
Seeing same bug on iPhone 8, same iOS & app version.
https://debuglogs.org/9bee57ae699760d231f3f2a33b5b67d51d8cc19fc680a82bba03632c3962ccfe.zip

**Comment by maartenhunink** [comment]
In my case the bug also happens when forwarding photo's I have taken myself in Signal.

**Comment by guest-tech** [comment]
Issue solved in Signal version 5.5.0.18. Many Thanks.
