### ISSUE TITLE
Can’t log in to a room – told to upload the app

### ISSUE THREAD

**Issue by vildereichelt** [signalapp/Signal-iOS#4865]
When opening a link to my book club, a room that was set up and my friends have access to, I get a message that there’s an error. I am meant to update the app, but there are no new uodates available
![EFCEF338-257C-450D-8F3B-85951ADCE95B](https://user-images.githubusercontent.com/57251769/106993716-91d18d80-677b-11eb-9b96-44ea850979b2.png)

**Comment by Genis-Sage** [comment]
@vildereichelt
Can you post a debug log?

**Comment by vildereichelt** [comment]
I can’t, I’m sorry. Just trying to use the app – I don’t have time to debug anything.

**Comment by i7u** [comment]
If you click on your avatar in the top left and then “About” (second from the bottom), which version of Signal are you using?

**Comment by Genis-Sage** [comment]
@vildereichelt 
you understood me wrong.... I did not ask you to debug anything

but to simply follow the steps from the bug template:
_Ensure that "Enable Debug Log" is on in Signal's settings then make the bug happen and immediately after that tap "Submit Debug Log" from settings and paste the link below._

alternatively:
https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug

without a debuglog, it's nearly impossible to know, what is happening...


can it be that you have some linked devices? (iPad or PC)
