### ISSUE TITLE
Pics aren’t sending

### ISSUE THREAD

**Issue by frankklinowski** [signalapp/Signal-iOS#4868]
pics aren’t sending.

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by kylemclaren** [comment]
Can confirm this issue on iOS running signal 5.3.2.1

**Comment by romanneso** [comment]
Same problem, photos/videos/gifs won’t send. iPhone 11 Pro, iOS 14.4, Signal 5.3.2.1

**Comment by schmiggedi** [comment]
Hey guys. 

Do you already have a solution for this? My sister has the same problem. I created a topic for this issue. Would be great if you could participate so this issue gets a little more attention.

https://community.signalusers.org/t/unable-to-send-videos-photos/28517

**Comment by kylemclaren** [comment]
@schmiggedi upgrade the app from the App Store

**Comment by schmiggedi** [comment]
Hi @kylemclaren,

thanks for your reply. She is already using the latest Signal and iOS version.
