### ISSUE TITLE
Responding to a specific message with a sticker

### ISSUE THREAD

**Issue by ganeshkumarv10** [signalapp/Signal-iOS#4869]
Selecting a specific message by sliding against it to select it and attempting to send a sticker against that specific message, results in sticker getting sent as a standalone sticker. The specific selected message still remains, with a cursor waiting for the user to type a response.
Not sure if this behaviour is as per intended design.

**Comment by Genis-Sage** [comment]
@ganeshkumarv10
this is intended behaviour
here's the feature request for it
https://community.signalusers.org/t/send-stickers-as-a-reply-to-a-quoted-message/12919

**Comment by ganeshkumarv10** [comment]
Thanks, I'll close this issue.
