### ISSUE TITLE
Hit area for send button

### ISSUE THREAD

**Issue by ganeshkumarv10** [signalapp/Signal-iOS#4870]
While typing at speed within a conversation, a large number of messages aren't sent at the first attempt. This could possibly because the the send button leaves a large number of empty pixels between itself and the right side app border or an implementation bug.

I'm on an android device.

This could be classified as an UI/UX issue possibly. Increasingly it has become painful to assume I, the user have sent the message only to find out it wasn't, because the send didn't work the first time. Posting as an issue here because I'm not sure if it isn't a bug.

If this is not an implementation bug, and is caused as a result of the specific portion of my thumb (not small by any measure) making contact with the screen, slightly to the right of the send button. Then the button along with the text message draft bar could be increased in size slightly so as to 
I) increase the size of the text bar, it's small from an accessibility perspective, especially for the elderly
II) it will result in less blank space between the send button and the border, while increasing the size of the send button "hit area" itself. The thumb naturally uses the edge of the phone as a reference to hit send while typing at speed.

**Comment by Genis-Sage** [comment]
@ganeshkumarv10
if you say, you are using Android, then you should post in the Android issue tracker, not in the iOS one

But I guess, posting on the UX section of the forum would be better
https://community.signalusers.org/c/ux/28

**Comment by ganeshkumarv10** [comment]
Apologies, didn't notice I was on the wrong page. Will re post in the suggested section. Thanks
