### ISSUE TITLE
Videos just won’t upload

### ISSUE THREAD

**Issue by jboycha** [signalapp/Signal-iOS#4872]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by jboycha** [comment]
The videos won't upload even if it is just 5MB, it is so frustrating the platform is practically of no use. The photos & Videos just go on in circles, waiting
Months with support with this issue no resolution after multiple version updates

**Comment by jboycha** [comment]
https://debuglogs.org/c16a064fb4785d606bd56c845a3ac4b729b57353782606fec35f78e9f706f26a.zip

**Comment by jboycha** [comment]
Signals Rocket Scientist's fixed my anxiety with a "Shut Up" and don't understand error, and stop worrying about circles and uncertainty by telling you immediately "We can't do it' Go Fetch" ![image](https://user-images.githubusercontent.com/78777509/107342615-da6dab80-6ad9-11eb-9c64-79a07f2baf2a.jpeg)

**Comment by jboycha** [comment]
Anybody working on this ?

**Comment by jboycha** [comment]
This crap just doesn't work and nobody is working on this, this is like h"hair pulling,![image](https://user-images.githubusercontent.com/78777509/107975923-40729b00-6fd2-11eb-8dcb-9ab20372fa3a.jpeg) frustrating"

**Comment by jboycha** [comment]
https://debuglogs.org/dc394d7744457dcee35cc3927b48b6ca545259b22bc555db650e99a613cee43a.zip

[](https://debuglogs.org/dc394d7744457dcee35cc3927b48b6ca545259b22bc555db650e99a613cee43a.zip)

![image](https://user-images.githubusercontent.com/78777509/108391429-241d6b00-722b-11eb-8b8d-488067d3a2b5.jpeg)

**Comment by jboycha** [comment]
![image](https://user-images.githubusercontent.com/78777509/108541600-1388f580-72fc-11eb-95bf-b54897befcd6.jpeg)

**Comment by jboycha** [comment]
The IOS Signal app still struggles to upload video and can not upload video. Same video can be uploaded smooth with Android Signal app. Nobody is looking into it ?
![image](https://user-images.githubusercontent.com/78777509/109919416-0a236400-7cd2-11eb-890e-9d526615ae99.png)

![image](https://user-images.githubusercontent.com/78777509/109919523-37701200-7cd2-11eb-8017-2b5c7ad8399c.png)

IOS Version: 14.4
Phone: iPhone 12 Pro Max
Signal Version: 5.6.0.14

**Comment by jboycha** [comment]
IOS Version: 14.4.1
Phone: iPhone 12 Pro Max
Signal Version: 5.7.0.18

I still have the problem, the app still struggles to upload even saved  7mb video, I gave more than 30min and it was still struggling to upload ![image](https://user-images.githubusercontent.com/78777509/111494430-e3e0d800-8757-11eb-8848-37035ed00387.png)

**Comment by jboycha** [comment]
We are still struggling more than 5MB ![image](https://user-images.githubusercontent.com/78777509/111893263-ec1c6a00-8a1a-11eb-940c-b453a2d65dcc.jpeg)

**Comment by jboycha** [comment]
Still can not send saved video ![image](https://user-images.githubusercontent.com/78777509/112091579-1ef76700-8baf-11eb-8b74-b4045b3e19ed.png)

![image](https://user-images.githubusercontent.com/78777509/112091630-3898ae80-8baf-11eb-8162-53f2722ee49a.png)

**Comment by jboycha** [comment]
Still no resolution to saved video upload ![image](https://user-images.githubusercontent.com/78777509/112091800-9af1af00-8baf-11eb-8c42-c6e91fb423d2.jpeg)

**Comment by jboycha** [comment]
Saved video still won't upload
![Uploading 112584908...]
I still can't upload, latest IOS and latest Signal app

IOS: 14.5
Signal: 5.10.0.49
![image](https://user-images.githubusercontent.com/78777509/116691332-b8464400-a9cb-11eb-89c1-3cf3bd1cc201.jpeg)

**Comment by GetBoz** [comment]
Do you use an AD filtering DNS, like AdGuard DNS?

**Comment by jboycha** [comment]
No, there is nothing like that.

The video uploads from the desktop app in Mac or an Android phone

**Comment by jboycha** [comment]
I opened this thread 4 months back when most of my contacts had migrated to signal. With no resolution on the video issue in IOS most of them have either gone back to WhatsApp or fallen back to signal as one of the apps they have and are less active on it. WhatsApp has finally able to get its customer back. I occasionally check if this is sorted out in IOS and I find we are still having the problem !!! ![image](https://user-images.githubusercontent.com/78777509/121563734-551ee700-ca38-11eb-96f2-e44224910412.jpeg)

**Comment by jboycha** [comment]
Ha ha 5th Month and still struggling with god damn signal 

(No more very active user, will stop using, request other IOS users to drop signal and go back to WhatsApp, that will save you some anxiety and grey matter)

Signal is still struggling with videos in IOS. Basic need of an user to share is not there in Signal IOS
![image](https://user-images.githubusercontent.com/78777509/124067043-5354ac00-da57-11eb-98bc-90697664d23d.jpeg)

Version 5.15.1.3
IOS: 14.6
