### ISSUE TITLE
Group profile pictures are gone after update to Signal v.5.4 on iOS

### ISSUE THREAD

**Issue by fabifabulousity** [signalapp/Signal-iOS#4873]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to Signal version 5.4. the profile pictures of groups were reset.

### Steps to reproduce
- update to version 5.4 on iOS
- no further steps

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
For each group, where a custom profile picture was set, it is no longer showing up. Group members running earlier versions of Signal e.g. 5.3. still can see the group profile picture.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Custom group profile pictures should be shown.

### Device info

**Device**: iPhone X

**iOS version**: 14.4

**Signal version:** 5.4

**Comment by alongwor** [comment]
This does not seem to affect all groups the same. I suspect, but I cant say for sure as I dont remember 100% who set what. It looks to me like the issue is on groups where I have been the one to set the group image. They now are blank. I have groups where I think the image was set by others, they still display a group image for me.
In the iOS desktop app, I can still see the group image.

**Comment by fabifabulousity** [comment]
> This does not seem to affect all groups the same. I suspect, but I cant say for sure as I dont remember 100% who set what. It looks to me like the issue is on groups where I have been the one to set the group image. They now are blank. I have groups where I think the image was set by others, they still display a group image for me.
> In the iOS desktop app, I can still see the group image.

This issue also appears, when another group member has created the group. I also updated another phone (iPhone 11, iOS 14.4) to Signal version 5.4, and seeing the same issue.

**Comment by fabifabulousity** [comment]
Issue still persistent with the latest official Signal version 5.5.0 for iOS.

**Comment by Imperiopolis-Signal** [comment]
This is unfortunately expected. iOS 5.3 was setting group photos that were very large and we cannot support going forward. If you set the group photo again on 5.4 or newer (or from Android) the photo will start working for everyone again.
