### ISSUE TITLE
New animated stickers never auto-download

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-iOS#4878]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving animated stickers from a pack I haven’t installed, the stickers don’t auto download. I’m prompted to tap on the download icon to download and view them. This happened when I was on WiFi, with two animated sticker packs I’d never received before, with videos and photos set to auto-download on wifi.

Received stickers:
![image](https://user-images.githubusercontent.com/18142893/107603689-a7661c00-6c81-11eb-9e11-eb39f8f28379.png)

I hadn’t installed any of the 3 sticker packs received, nor had I received them before. The static sticker auto downloaded fine (#2) but the two animated stickers (#1 and #3), each from separate packs, did not auto download.

Data usage settings:
![image](https://user-images.githubusercontent.com/18142893/107603697-ae8d2a00-6c81-11eb-90c5-ffbf66db1d5c.png)

### Steps to reproduce
- Ensure photos and videos are set to auto-download on WiFi
- While connected to WiFi, receive a sticker from an animated sticker pack which you've never received before

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- The animated sticker doesn't auto-download

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- The animated sticker would auto-download

### Device info
**Device**: iPhone 11

**iOS version**: 14.4

**Signal version:** 5.4.0.17

### Link to debug log
https://debuglogs.org/951485cf6fd6ca478d08d87ce8197a14f60af77491c86ec3a91c08a62575878c.zip

**Comment by Imperiopolis-Signal** [comment]
this should be resolved in the 5.5 release that went out yesterday.
