### ISSUE TITLE
Audio call sound comes out of the earpiece speaker by default instead of connected headphones

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-iOS#4879]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When receiving an Signal audio call with bluetooth headphones connected, the ringtone plays out of the headphones, but when I pick up the call, the caller's voice comes out of the phone's earpiece speaker.

After picking up the call, I have to manually change the audio device from the earpiece speaker to the headphones using the on-screen button.

This happens consistently with every call I receive while headphones are connected. It also happens with my partner and my sister who are also on iOS when they accept a call with headphones connected.

### Steps to reproduce
- connect iPhone to bluetooth headphones
- receive Signal audio call
- accept call

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Ringtone plays through headphones
- Caller's voice comes out of the iPhone's earpiece speaker by default

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Ringtone plays through headphones
- Caller's voice comes out of the headphones by default

### Device info

**Device**: iPhone 11

**iOS version**: 14.4

**Signal version:** 5.4.0.17

### Link to debug log
https://debuglogs.org/951485cf6fd6ca478d08d87ce8197a14f60af77491c86ec3a91c08a62575878c.zip

**Comment by azuredusk10** [comment]
I think I found the answer - it’s todo with iOS call audio routing:
https://www.iphonelife.com/content/how-to-set-your-speaker-or-headphones-default-audio-iphone

**Comment by krysor** [comment]
I have the same issue on Android 12, MIUI 13, Poco f2 pro
