### ISSUE TITLE
Signal crash when sending picture

### ISSUE THREAD

**Issue by Phobion** [signalapp/Signal-iOS#4880]
Hello,

When I want to send a picture the crashes 8 out of 10 times.
Phone: iPhone 6s Plus with iOS 14.4
Please fix this.

Thank you!

**Comment by jaredlt** [comment]
To add it to this. I can view the list of pictures to send, but once I click on an image and it goes full screen with the option to add a comment, it will crash on this screen, or seemingly if I try to write a comment. Sometimes, if I'm really fast and I just try to hit send immediately, it will work.

**Comment by mikesmsa0861** [comment]
I have the exact same experience as with jaredit.I am on iPhone Xr 14.4. Though I have had this issue with Signal on ios for as long as I can remember.

**Comment by ibvandersluis** [comment]
I also have this problem. I just tried to attach an image several times and it crashed each time. [Debug log](https://debuglogs.org/d01cc2526e6181848886e524857179bfa930ad472893f174d679447aa69218b9.zip)

**Comment by ricco9015** [comment]
Same to me. Ipad pro 3.Gen IOS 14.44.1.

**Comment by ibvandersluis** [comment]
As of the most recent Signal update, this issue has not come up for me again.

**Comment by Phobion** [comment]
Hello,

I agree. It seems that with the latest update it's working fine. Thank you!

Best regards

**Comment by hinnerk** [comment]
Still there with version 5.9.0.49 on iPhone 7 with latest ios.
Could you re-open this please @Phobion ?

**Comment by ricco9015** [comment]
Still there with Vers. 5.0.49 on Ipad pro 3.Gen. 

<rKe\iP>

**Comment by Phobion** [comment]
The bug is still there thus I re-opened the ticket.
Also I created a new one before re-opening this: https://github.com/signalapp/Signal-iOS/issues/4935

**Comment by ricco9015** [comment]
No, please close the ticket. 

<rKe\iP>

**Comment by primethai** [comment]
Exactly the same issue.
iphone 6
iOS 12.5.5
Signal App 5.31.0.14
The photo attachment DID work with previous versions.

**Comment by kaktusztea** [comment]
@primethai, @stephenhartley:
please attach debug log and crash log ips files right after the event, otherwise devs can not track this issue's root cause.
