### ISSUE TITLE
Voice message playback doesn't pause when Siri is in use (AirPods / AirPods Pro)

### ISSUE THREAD

**Issue by lukewlms** [signalapp/Signal-iOS#4884]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Voice messages playing in the background appears to be a bug.  Background audio would be appropriate for something like music playing from Spotify, but if a contact sends a voice message, the recipient very likely wants to hear the whole thing.

Currently if a voice message is playing and Siri is invoked (e.g. to make a voice note based on what a contact is saying), the voice message will continue to play very quietly in the background while Siri is being used.  So the voice message inevitably will have to be rewound.

This behavior would match the Audible app, which I think is an appropriate parallel as the content is important and shouldn't just be skipped over.

I repro this behavior with both AirPods and AirPods Pro.

(When using the iPhone speaker there is a different, more minor bug: The voice message pauses correctly, but then afterward the voice message keeps showing the "pause" button as if Signal keeps thinking it's playing when it's not.  Physically plugged-in headphones work like this too, which is different from the AirPods behavior.)

### Steps to reproduce
- Play a voice message in Signal (preferably a longish one, 1+ min)
- Invoke Siri (by holding the power button)

**Actual result:** Voice message continues to play very quietly in the background

**Expected result:** Playback pauses until Siri is closed

### Screenshots
N/A

### Device info

**Device**: iPhone XS

**iOS version**: 14.3

**Signal version:** 5.4.0.17

### Link to debug log
https://debuglogs.org/4329493098244a5cf4ddafaec33abdb2ea757572a917e4c01f87fcf72d879c8a.zip

**Comment by VidaHasan** [comment]
I'm going to take a look at this.

**Comment by lukewlms** [comment]
This still repros but at this point I'd call it a pretty minor annoyance.  Wontfix would be fine with me, I haven't run into it again in day-to-day.  I can confirm Whatsapp works the same way.
