### ISSUE TITLE
RTL & LTR languages bug

### ISSUE THREAD

**Issue by ZER0-X** [signalapp/Signal-iOS#4885]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It's about right-to-left languages (RTL)
I wrote about it in the forums [here](https://community.signalusers.org/t/rtl-bug-solution/28400) as a feature to cover up this bug, but i think i shoud report it here, maby you can fix it.
🔴**Take a look at the forums. i've wrote more detail about the bug**

### Steps to reproduce
- Write a word from LTR or RTL language as the first word in the message.
- Complete the sentence with words from RTL or LTR language.

_**For example i used English and Arabic language.**_
**Actual result:** The text is considered as LTR so the English word does not appear in its correct place, it appeares in the end of the first line(The left side).

**Expected result:** The English word appear at the right of the first line, and after that the arabic words will starts.

### Screenshots
**_Here i wrote English First:_**
![٢١-٠٢-١٧ ١٢-٠٩-١٤ 1715](https://user-images.githubusercontent.com/65136727/108202382-146e2b80-7132-11eb-9d91-889f47283061.png)
**_More then one word and send it:_**
![٢١-٠٢-١٧ ١٥-٢٠-٣٠ 1718](https://user-images.githubusercontent.com/65136727/108203718-ef7ab800-7133-11eb-9391-0ed6a44810f3.png)

 **_Here i wrote Arabic First:_**
![٢١-٠٢-١٧ ١٢-١٠-٤٧ 1716](https://user-images.githubusercontent.com/65136727/108202412-1c2dd000-7132-11eb-8c52-0ed1b153f5b1.png)

### Device info

**It happens on all platforms**

**Comment by Imperiopolis-Signal** [comment]
Is this behavior different than what you see in other messaging apps like iMessage? can you show screenshots of what you expect the behavior to be? We use Apple's built-in support for mixed directional text and as best I can tell it matches their behavior

**Comment by ZER0-X** [comment]
The same behavior in other messaging apps, so probably this problem is not solvable.

But in the iOS **notes** app i saw that there is a button to manually switch between RTL & LTR to cover this problem.

This is the same problem in the notes app:
![21-02-24 11-23-27 1750](https://user-images.githubusercontent.com/65136727/108975491-9b258a00-7697-11eb-9569-d0e4b1c9bae0.png)


This is the toggle button:
![21-02-24 11-23-34 1751](https://user-images.githubusercontent.com/65136727/108975626-bd1f0c80-7697-11eb-8811-9708fa5be492.png)


After i clicked the button the problem get solved **_(expected behavior)_**:
![21-02-24 11-23-40 1752](https://user-images.githubusercontent.com/65136727/108975659-c90ace80-7697-11eb-9e54-8afe48c51828.png)

**Comment by ZER0-X** [comment]
This is the reason why this problem occurs in Apple support for mixed directional text

**The first character you enter determines the default direction for a paragraph.**
https://support.apple.com/guide/mac-help/change-direction-text-type-mac-mh21243/mac

Apple's support is good, but it is not complete so we need a manual backup method to toggle if we start with a word from a different direction then the rest of the text.
