### ISSUE TITLE
Export WhatsApp conversation

### ISSUE THREAD

**Issue by ChGrand591** [signalapp/Signal-iOS#4886]
Hello

I have try to import a  conversation of 700mo (text and media)
Now Signal crash at the launch.

I have reboot, run signal and very quicly suppress the message file, now it's ok.

I can do it with telegram without issues
https://telegram.org/blog/move-history/

**Comment by Genis-Sage** [comment]
Hey @ChGrand591
Signal does not have any functionality to import WhatsApp chat
So I am not really sure, what you are talking here

What do you mean by importing a conversation?
Please provide steps to reproduce your issue

**Comment by ChGrand591** [comment]
Hui
 
 I try to import my WhatsApp conversation to signal. 
 
For that in WhatsApp I export it 

![13C34A38-60B6-43C4-9CE0-FB75FAAC6D46](https://user-images.githubusercontent.com/76517450/108413512-6777d980-722b-11eb-8df3-e6296af66d0d.jpeg)

![2C263C03-9BCD-4D4C-B21A-9F11057EC194](https://user-images.githubusercontent.com/76517450/108413558-752d5f00-722b-11eb-9d34-de80381b1423.jpeg)
![ECC1A9CC-07E5-4A30-A71D-C201513AC75B](https://user-images.githubusercontent.com/76517450/108413569-75c5f580-722b-11eb-8873-3d9e71d310d4.jpeg)
![9EE98829-2DDC-4C9F-AE11-4A5C64E5EC81](https://user-images.githubusercontent.com/76517450/108413572-765e8c00-722b-11eb-9009-fbeea9eaa939.jpeg)

The file size is 670 mo 

the same thing in telegram works fine.

**Comment by guest-tech** [comment]
Signal does not support import of WhatsApp chats like mentioned before. 

You are trying to send a too big file ;-)

**Comment by ChGrand591** [comment]
It is a real pity that it does not work. Will this be the case in a future update? It's blocking to switch to signal

**Comment by tomxpcvx** [comment]
I was going to try to implement this feature, but until I have feedback on my issue #4855, development is at a standstill.

**Comment by tomxpcvx** [comment]
This feature should be implemented. Ticket should remain open.

**Comment by tomxpcvx** [comment]
This feature should be implemented. Ticket should remain open.
