### ISSUE TITLE
After switching between statuses of "Dark mode" of the brightness bar in iPhone, "System" theme does not change

### ISSUE THREAD

**Issue by Yanazyrf** [signalapp/Signal-iOS#4887]
### Bug description
After switching between statuses of "Dark mode" of the brightness bar in iPhone, "System" theme does not change

https://user-images.githubusercontent.com/79051355/108538040-660fe500-72ef-11eb-88ea-1dc88d5666f5.MOV

### Steps to reproduce:
1. Open your account in "Signal" application
2. Tap "Profile"
3. Go to "Appearance"
4. Tap on "Theme", "System" theme will be choosed by default
5. Tap on "Light" theme
6. Tap on "Dark" theme
7. Go back to "System"
8. Swipe to "Control center" on your iPhone
9. Press and hold the brightness bar to expand it
10. Press on "Dark mode" 2 times

**Actual result:** "System" theme not changed on dark or light

**Expected result:** "System" theme of the application is changing depending on the status of "Dark mode"

### Device info:
**Device**: iPhone Xr

**iOS version**: 14.4

**Signal version:** 5.4.0.17

**Comment by n8udd** [comment]
Unable to reproduce on iPhone 11:

https://user-images.githubusercontent.com/2293192/108983929-4b3ec700-7687-11eb-994f-7df136d4973a.mov
