### ISSUE TITLE
"Invite friends by message" does not allow to choose phone numbers.

### ISSUE THREAD

**Issue by vonorlow** [signalapp/Signal-iOS#4894]
_Originally posted on the [Android repository](https://github.com/signalapp/Signal-Android/issues/11025)_

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the "Invite friends by message" feature, one cannot pick which phone number is used, leading to landline numbers, fax etc. being used.

### Steps to reproduce
- open invite friends by message
- select address book contact with landline and mobile number in address book
- message is sent to landline or fax number

**Actual result:** Can only send invite message to landline or fax number
**Expected result:** Being able to select an appropriate number from my contacts, or landline numbers being auto-ignored

### Device info

**Device:** iPhone 8 Plus

**Comment by nereocystis** [comment]
This bug is still relevant
The problem showed up on an iPhone 6S Plus
software version 15.5, signal 5.41.0.12
