### ISSUE TITLE
Can't receive media from specific contact 

### ISSUE THREAD

**Issue by Paraidomat** [signalapp/Signal-iOS#4900]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't receive pictures or voice messages using my phone. I can receive media using the desktop app just fine.

### Steps to reproduce
- Contact sends media to me
- I don't see a thing about it

**Actual result:** I can't see the media 

**Expected result:** I can see the media

### Device info

**Device**: Device Model: iPhone (iPhone8,2)

**iOS version**: iOS Version: 14.4

**Signal version:** lastAppVersion: 2.35.0

### Link to debug log

https://debuglogs.org/587f18e2a5b9599f3c156642c7cfd7a8458561404c2b1dc8ad6019cf7835a57a.zip

### Related Android Issue:

https://github.com/signalapp/Signal-Android/issues/11010

**Comment by rb81** [comment]
**Related issues:**

- https://github.com/signalapp/Signal-iOS/issues/4872
- https://github.com/signalapp/Signal-iOS/issues/4868
- https://github.com/signalapp/Signal-iOS/issues/4835
- https://github.com/signalapp/Signal-iOS/issues/4778
- https://github.com/signalapp/Signal-iOS/issues/4735
- https://github.com/signalapp/Signal-iOS/issues/4777

**Comment by Paraidomat** [comment]
Hi @rb81

Thanks for your comment, but the issue isn't with sending from the iPhone (or playing the video or whatever), but with receiving the pictures that have been sent from an Android device in the first place. From the iPhones perspective the media (picture / video or voice message) doesn't show up at all.

**Comment by Paraidomat** [comment]
Updating the iPhone App from 2.x to a newer Version fixed the issue.

**Comment by rbadrov** [comment]
Update didn't fix it for me. 
Those on ios receive a blank video when original video sent from android. 
When same video is send from windows desktop, there is no issue.

**Comment by rb81** [comment]
> Thanks for your comment, but the issue isn't with sending from the iPhone (or playing the video or whatever), but with receiving the pictures that have been sent from an Android device in the first place. From the iPhones perspective the media (picture / video or voice message) doesn't show up at all.

I agree. Seems to be the issue.
