### ISSUE TITLE
verification code didn't receive

### ISSUE THREAD

**Issue by new2690** [signalapp/Signal-iOS#4902]
hi. verification code in the step of registration didn't receive. I'm from Iran and didn't get verification codes in both ios and android plafroms. also below page not solve the problem

[https://support.signal.org/hc/en-us/articles/360007318751-Registration-troubleshooting#:~:text=Not%20receiving%20the%20verification%20code,entered%20your%20phone%20number%20correctly.](url)

**Comment by GPX-NSlog** [comment]
The verification code cannot be received in China either.
