### ISSUE TITLE
Search for domain name in URL doesn't work properly on iOS

### ISSUE THREAD

**Issue by ylieder** [signalapp/Signal-iOS#4904]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Searching for a domain name (in my case _twitter_) in a chat yields not all messages with URLs of the form `https://twitter.com/...`.  Strangely, some few twitter URLs are found. On the macOS app, I can find more than 60 URLs of twitter in one chat just with the search keyword _twitter_. In the same chat on iOS only two of those URLs are found. (maybe related to Issue #4461)

### Steps to reproduce
- Send links to several tweets as messages (not the `t.co/...` ones, but `https://twitter.com/...`)
- Search inside the chat for the keyword `twitter`

**Actual result:** Only a few of the messages are found by the search.

**Expected result:** All messages containing such URL should be found.

### Device info

**Device**: iPhone 12 mini

**iOS version**: iOS 14.4

**Signal version:** 5.5.0.18

**Comment by mike-engel** [comment]
This is still an issue with Signal for iOS 5.31.0.14, iOS 15.4, iPhone 11
