### ISSUE TITLE
iPadOS signal app only offers to import from "your old iPad"

### ISSUE THREAD

**Issue by ldanicel** [signalapp/Signal-iOS#4906]
Fresh install on iPadOS ( iPad Air 4 ) -> Transfer Account & Messages screen presents the following:

* Transfer from another iPad - Transfer your account and message history from your old iPad
* Add as New Device - Add this iPad as a new linked device without transferring message history

In the documentation found here: 
https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages
I get the conclusion that transferring from my (old) iPhone to my (new) iPad should work since:
`Which devices can I transfer data from?

    iPhone > iPhone
    iPhone > iPad
    iPad > iPad
    Unlinked iPad > iPhone
`
Did I get something wrong ?

**Comment by b3hni4** [comment]
I am having the same issue. Transfer from an iPhone to iPad does not work!

**Comment by b3hni4** [comment]
You need to register your iPad as a new device, only then you would be able to transfer the data from iOS to iPad.

**Comment by ldanicel** [comment]
How do you transfer it after its registered as a new device ?

**Comment by b3hni4** [comment]
You will be prompted to transfer from another iOS device or register without transferring.

**Comment by ldanicel** [comment]
I was not prompted and wasnt able to find this feature

**Comment by b3hni4** [comment]
On the very first page when you open the app on iPad, you will see a kind of “link” shape icon on the top right corner of the page. Select that and do the registration and follow the steps.

**Comment by pilotime** [comment]
The "link" shape icon no longer exists. Does anyone have a screenshot?

**Comment by mqvortrup** [comment]
The link icon does exist on my uptodate version of Signal - upper right corner - but it difficult to see and it looks like it’s inactive, grayed out. I could still press, though, and the transfer worked.

The documentation on how to transfer is missing a step. 

https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore

Paragraph „iOS“, sub-paragraph „How do I …“, step 1 “… open Signal, and complete registration, if prompted”

The “if prompted” part didn’t happen for me. I had to google the problem, find this thread, reinstall Signal on my iPad twice, and then finally found the link icon :-)

I suggest adding a step 1a “if not prompted, manually complete the registration” with a nice screenshot of the link icon.

**Comment by Wazzymandias** [comment]
I am on Signal version 5.25.0.13 for both iPhone and iPad and don't see any "link" shape icon. I tried deleting, unlinking, and re-installing Signal on iPad multiple times but no prompt ever shows up and no link icon ever appears visible. 

It would be helpful to have more comprehensive documentation on what exactly a user can expect to see when trying to transfer from iPhone to iPad

A screenshot would also be very helpful to see what exactly this "link" shape looks like and where it can be found if one is not prompted to transfer from iOS.

**Comment by johnnyutahh** [comment]
The following article:

https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore

...says that `iPhone → Unlinked iPad` transfer is supported. It's not. UNLESS... it should read `iPhone → iPad that has _never_ been linked`.

Signal v5.49.0.13 on both iPhone and iPad that were used for my testing.
