### ISSUE TITLE
libsignal_ffi.a not built; run the following to build it

### ISSUE THREAD

**Issue by bhadreshtechinnate** [signalapp/Signal-iOS#4907]
Hello There,

After code checkout from the git, I am getting the error in my Xcode when run the code. 

error: libsignal_ffi.a not built; run the following to build it:
CARGO_BUILD_TARGET=x86_64-apple-ios "/Users/XYZ/H_Git Projects/signal_ios/Pods/SignalClient/swift/build_ffi.sh"

Anybody has any idea how can I resolve this issue.

Thanks.

**Comment by anyTask2020** [comment]
Hello there, 

i am also facing this issue, anybody has resolved it?

Thanks

**Comment by anyTask2020** [comment]
Hello, 

I have resolved it by running it on macos 10.15.7 catalina, it is a version specific issue. 

Thanks

**Comment by pradeep7may** [comment]
error: libsignal_ffi.a not built; run the following to build it:
CARGO_BUILD_TARGET=aarch64-apple-ios "/Users/TEST/Signal/Pods/SignalClient/swift/build_ffi.sh"

getting error in latest code, any way to solve this issue
