### ISSUE TITLE
Make it easier to link new devices (alternatives to QR codes)

### ISSUE THREAD

**Issue by mrkiko** [signalapp/Signal-iOS#4915]
Using QR codes isn't always an easy option (e.g.: when you're blind it can be an annoyance).
Maybe let the App handle tsdevice:/?uuid=... URLS?
Or implement some other authentication mechanisms which can be used without the QR code itself?

Edit: something like what has been done in commit ea85d7aebd57f49e953e530bcf8723b941b16271
but for normal builds.

Thanks!!

**Comment by mrkiko** [comment]
Hi all!
This is still relevant (to me at least),.

Inviato da iPhone

**Comment by mrkiko** [comment]
I can't determine at the moment if it's still relevant, since tapping twice on the Settings button doesn't yeld my expected result ("Settings to eppar"). But this might not be a bug, and be a behaviour related to the App asking me to verify my PIN code so I might remember it.
You "cought" me - I didn't remember it :)

**Comment by mrkiko** [comment]
I think this problem is still relevant for me. Still, feel free to close thi issue if there is no intention to "solve" it.

**Comment by EvanHahn-Signal** [comment]
We're trying to use GitHub for bug reports and [the community forums](https://community.signalusers.org/c/feature-requests/17) for feature requests. Please open a thread there (or find an existing one).
