### ISSUE TITLE
Consider allowing installation on M1 macs

### ISSUE THREAD

**Issue by jtg** [signalapp/Signal-iOS#4924]
Signal appears to be disallowing MacBook M1 owners from sideloading the iOS app. This was easy to bypass, but Apple appears to have broken it in the Big Sur 11.3 beta. The proper desktop app, due to the Electron environment, consumes 2GB of RAM on my MacBook. The iOS version was about 200MB. Being able to just run the iOS version was fantastic, as I only have 8GB, and that goes quickly.

This restriction is usually for commercial reasons, and I'm not sure what good it does to block Signal from running. Can this be fixed so users can run it this way if they desire?

This works out of the box by default, so it would not require any work by the Signal team.

**Comment by tkafka** [comment]
I run an iOS signal build extracted via `Apple Configurator 2` on my m1 mac, and it works quite well (sometimes crashing though). And of course, the memory footprint is minimal, compared to desktop app.

However, it doesn't autoupdate this way - if Signal allowed the app to be installed on M1 macs from App Store, it would be the best of both worlds :).

**Comment by jtg** [comment]
> I run an iOS signal build extracted via `Apple Configurator 2` on my m1 mac, and it works quite well (sometimes crashing though). And of course, the memory footprint is minimal, compared to desktop app.
> 
> However, it doesn't autoupdate this way - if Signal allowed the app to be installed on M1 macs from App Store, it would be the best of both worlds :).

Yep, this is what Apple just broke in 11.3. When it drops, Signal won’t launch anymore, and re-installing it won’t work.

**Comment by Dakyne** [comment]
Agreed, the actual ipad version loaded using iMazing works almost perfectly on M1 macs. (And we can send gifs from desktop which is not the case using the proper desktop app.) The only issue I have using it is that it pops up foreground each time something happens in the app.

**Comment by tkafka** [comment]
> The only issue I have using it is that it pops up foreground each time something happens in the app.

That's right, same thing happens with iOS version, but I don't mind much. Since the user has to explicitly switch to iOS store tab in Mac App Store to install iOS version, I would be OK with minor things not working perfectly.

**Comment by jtg** [comment]
Is anyone familiar with the new process, and what the Signal team would have to change to prevent running this from being blocked?

It is my understanding that it's enabled by default, and the Signal team would have had to go out of their way to block it. Is that correct?

**Comment by neophit** [comment]
The process is described in the [Apple Developer Documentation](https://developer.apple.com/documentation/apple-silicon/running-your-ios-apps-on-macos#Choose-Whether-to-Include-Your-iOS-App-on-the-Mac-App-Store).

**Comment by jtg** [comment]
> The process is described in the [Apple Developer Documentation](https://developer.apple.com/documentation/apple-silicon/running-your-ios-apps-on-macos#Choose-Whether-to-Include-Your-iOS-App-on-the-Mac-App-Store).

Great, so can someone from the Signal team just uncheck that box and publish?

**Comment by jtg** [comment]
Come on guys, it's 1 click and would help a lot of people! I'd send a PR, but it's not a code change apparently.

**Comment by Penguinjumper** [comment]
Yes please. Where can we post this to get some attention from the team?

**Comment by vordenken** [comment]
Any update here? Would love to get the native iPad app on my Mac m1 as well.

**Comment by jtg** [comment]
No acknowledgment from the project since March. I am not sure if they have seen it.

**Comment by jspiro** [comment]
This bears repeating:
https://github.com/signalapp/Signal-Desktop/issues/5387#issuecomment-972586417

**Comment by jtg** [comment]
Yes, still relevant. Not sure what is blocking it. It would take 3 seconds, but no comment by the Signal team in nearly a year.

**Comment by mvllow** [comment]
> Yes, still relevant. Not sure what is blocking it. It would take 3 seconds, but no comment by the Signal team in nearly a year.

See https://github.com/signalapp/Signal-Desktop/issues/4461#issuecomment-993917691

**Comment by SeparateRecords** [comment]
This is still relevant and very much desired

**Comment by mvllow** [comment]
> This is still relevant and very much desired

Again, see https://github.com/signalapp/Signal-Desktop/issues/4461#issuecomment-993917691

**Comment by elyscape** [comment]
> Again, see [signalapp/Signal-Desktop#4461 (comment)](https://github.com/signalapp/Signal-Desktop/issues/4461#issuecomment-993917691)

This doesn't address the functionality differences in the iPad app, like the ability to receive notifications while the app is closed.

**Comment by SeparateRecords** [comment]
I'd much rather run the iOS app than the Electron one (which yes, I am aware is now running natively on ARM). Just my preference, so I -- along with many others -- would still like this 🙂

**Comment by mvllow** [comment]
> I'd much rather run the iOS app than the Electron one (which yes, I am aware is now running natively on ARM). Just my preference, so I -- along with many others -- would still like this 🙂

Oops apologies, I thought this issue was related to m1 installation.

**Comment by elyscape** [comment]
This is still relevant.

**Comment by Cerberus0** [comment]
Please ignore the stale bot, it does not know the difference between bugs and feature requests because [this is no longer the right place to submit or discuss feature requests](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md). Please let this GitHub issue be closed and continue this discussion on the community forum:

https://community.signalusers.org/t/ios-version-of-signal-on-apple-silicon-macs/18813

Thanks!

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by EvanHahn-Signal** [comment]
We're trying to use GitHub as a place for bug reports, not feature requests. Please move discussion to [this community forum thread](https://community.signalusers.org/t/ios-version-of-signal-on-apple-silicon-macs/18813) and use the community forum for other feature requests.
