### ISSUE TITLE
Censorship Circumvention Does Not Work in China

### ISSUE THREAD

**Issue by tonyztan** [signalapp/Signal-iOS#4926]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The censorship circumvention feature of the Signal iOS app is not working in China. In [OWSCensorshipConfiguration.m](https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Network/OWSCensorshipConfiguration.m
), `censoredCountryCodes` does not appear to include the +86 (China) country code.

[China has begun blocking access to Signal](https://www.google.com/search?q=signal+china+blocked), making censorship circumvention necessary for Signal users located in China.

(Not part of this issue, but a side note: It also appears that the [Signal proxy](https://signal.org/blog/help-iran-reconnect/) feature is not yet available for iOS.)

### Steps to reproduce
- User launches Signal for iOS while in China
- User attempts to send a message to anyone

**Actual result:** Signal app cannot connect to the Signal server due to China's censorship. Message cannot be sent.

**Expected result:** Censorship circumvention is enabled, and the message is sent via domain fronting or another censorship circumvention method.

### Device info

**Device**: Any iPhone

**Comment by WhyRoy** [comment]
frankly speaking, we need proxy for signal

**Comment by geofurb** [comment]
Wasn't domain fronting doing the trick until recently?

**Comment by r6c** [comment]
we need proxy for ios, like signal android

**Comment by WhyRoy** [comment]
@Ehren Kret

**Comment by WhyRoy** [comment]
@ehrenkret-signal

**Comment by WoodpeckerBaby** [comment]
relevant

**Comment by geofurb** [comment]
This issue is still relevant. The Chinese Communist Party is blocking it. We can move forward by trying domain fronting or some other method if we can determine how GFW is blocking Signal. This might not get as much attention from CCP anymore, since most of the Chinese diaspora is back on WeChat, instead of Signal.

**Comment by evansan** [comment]
This issue is still relevant.

**Comment by UjuiUjuMandan** [comment]
Come on... good bot.
