### ISSUE TITLE
Sending Apple ProRAW images fail

### ISSUE THREAD

**Issue by n0rdlicht** [signalapp/Signal-iOS#4928]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing Apple ProRAW images a blank DNG placeholder is shown and people receiving those images are unable to load them if the message gets sent at all.

### Steps to reproduce
- Enable Apple ProRAW format in camera settings
- Take a picture
- Share an image via the share sheet in Photos / camera roll to Signal

**Actual result:** Image not rendered in message preview nor after sending which half of the time fails/crashes the app. Signal is showing a DNG placeholder instead and is unable to load the image when tapped for full screen viewing.

**Expected result:** DNG being rendered inline just like JPG or PNG. Alternatively using the Photos API to force a conversion to JPG before sending (e.g. like Apples Messages does it).

### Screenshots

<img src="https://user-images.githubusercontent.com/1425577/112750053-7db14c00-8fc6-11eb-80df-92d8c7a77519.png" height="800px">

### Device info

**Device**: iPhone 12 Pro

**iOS version**: 14.4

**Signal version:** 5.8.0.22

**Comment by kriston13** [comment]
I suspect this is actually related to the file size limitations like #4929. Is it possible for you to try a DNG file under the size of 10mb?

**Comment by n0rdlicht** [comment]
Will give it a try, however I think if there is a limit, Signal should automatically force en export to JPG and potentially compress if needed as there is no built in option in iOS to do these except for apps implementing the relevant APIs.

**Comment by epvuc** [comment]
This may be a general issue with large image files, as even large jpegs (such as ones transferred from a DSLR, for example) fail in the same way, both from share sheet and from within the signal app.

**Comment by ianrahman** [comment]
Can this be reopened? The issue is still prevalent and exceedingly frustrating for those of us who default to shooting RAW images.

**Comment by Miguel-Signal** [comment]
I've gone ahead and filed this bug with our engineering team. While our engineers will be working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug included in the release notes for future versions of Signal.

Thanks again for your help in reporting this.

**Comment by rapulum** [comment]
Any news? :) 
The error bothers me several times a day and I regularly have to switch to WhatsApp because of it.

**Comment by ianrahman** [comment]
[Created a PR](https://github.com/signalapp/Signal-iOS/pull/6108) to resolve this.
