### ISSUE TITLE
Opening a group of photos crashes the app

### ISSUE THREAD

**Issue by mehdibo** [signalapp/Signal-iOS#4930]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening a group of photos crashes the app, I'm using the beta version from the Testflight, But a friend reported the same bug to me.

### Steps to reproduce
- Receive more than one photo (only tested in a group chat)
- Click on one of the photos
- The app crashes
Also:
- Receive more than one photo (only tested in a group chat)
- Click on group chat name in the top
- Click on All Media
- Click on one of the received photos
- The app crashes

### Device info
**Device**: iPhone XR

**iOS version**: 14.4.2

**Signal version:** 5.8.0.23 (Beta version)
### Link to debug log
https://debuglogs.org/6c9fe061794890ddce4dde461115ed81efd48fb21250f42fa4ad96e29c09e6b7.zip

I also sent a crash log

**Comment by peterpanondrugs** [comment]
Also for single chats:

Android to iOS
============
- receive group of images
- open by clicking on them
-> app crash immediately

https://debuglogs.org/0c8764a0b0b1d2b006b9d8919c47bca700a0ec283e4906754f0e0ea1c69816e5.zip

Now the fun
receiving much later 1 another picture
let them open the group pictures

https://debuglogs.org/9e0f147f347d692302911b8a52ed5034f277fd3ff5376a01ea73ec3b83a67afb.zip
