### ISSUE TITLE
Group read receipt icon lights up when just one user read it instead of all

### ISSUE THREAD

**Issue by StefPac** [signalapp/Signal-iOS#4931]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In groups, when a message is sent the delivered receipt works as expected, but the read receipt is triggered as soon as just one person in the group reads the message, as opposed to when all people in the group have which is the behavior I expect. 

### Steps to reproduce
- go to a group message with 3 or more users
- send a message
- have one other user in the group read the message

**Actual result:** The double check, read receipt icon is highlighted (white) 
**Expected result:** The double check, read receipt icon is not highlighted (gray) 

### Device info
**Device**: iPhone 11 Pro 

**iOS version**: 14.4.1

**Signal version:** 5.8.0.22

**Comment by StefPac** [comment]
I never received any acknowledgement from the team, so jot really sure how to further contribute here. Please let me know if I can be of help.

**Comment by NiklasBr** [comment]
This is relevant until Signal responds

**Comment by NiklasBr** [comment]
Why did you close this? It is still very relevant and requires a response from Signal.
