### ISSUE TITLE
Audio message recording stops after switching to landscape mode

### ISSUE THREAD

**Issue by pimlock** [signalapp/Signal-iOS#4933]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When recording an audio message, recording stops and a message is discarded (without any notification), after you change orientation of the phone from vertical to landscape/horizontal.

### Steps to reproduce
- start with your phone in a vertical position
- open a conversation with any person
- hold the mic button on the bottom left and slide it up to start recording a message
- record few seconds
- turn the phone to landscape/vertical position
- recording is stopped and the audio that was already recorded is discarded

**Actual result:** Recording should continue after changing the orientation of the phone.

**Expected result:** Recording stops and audio is discarded without any notification.

### Screenshots

Started recording in vertical mode.
![image](https://user-images.githubusercontent.com/1116309/113467203-64f5cb80-93f6-11eb-9295-d1af681cf52b.jpeg)

After turning to horizontal.
![image](https://user-images.githubusercontent.com/1116309/113467211-6fb06080-93f6-11eb-912a-043727e53f51.jpeg)

### Device info

**Device**: iPhone 11

**iOS version**: 14.4.2

**Signal version:** 5.8.1.0

### Link to debug log

https://debuglogs.org/90476d9db41f8f307b9e6233f61af84ac80ddda3038880349126ec5429aacde2.zip

**Comment by DHentzschel** [comment]
That's an annoying incident that happens everytime. I appreciate fixing this.

**Comment by BlizzardWizzard** [comment]
This happens whenever you change the orientation, not just landscape.


Device info:
Device: iPhone XR
iOS version: 14.4.2
Signal version: 5.8.2.0
