### ISSUE TITLE
Unresponsive call button after unsuccessful call or at incoming call

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#4942]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometime 1:1 call button is unresponsive.

### Steps to reproduce
- enter contact chat
- push call button
- sometimes it's OK, but sometimes it is unresponsive
- sometime it happens at incoming call receiving too

**Actual result:** The call button doesn't response.

**Expected result:** Call button should start a call or respond an incoming call.

### Device info

**Device**: iPhone SE 2020
**iOS version**: 14.4

**Signal version:** 5.8

### Link to debug log
This debug log was created after there was an unresponsive call button then I made an app kill and restart, then tapped on call button successfully:
https://debuglogs.org/8655fcd114419cfd4b37b4de67d091b8776421f255c656d4f3814df59a2ccd22.zip

**Comment by holmesworcester** [comment]
I have this too, in the most current release, and I've noticed that when the call button stops being responsive, the voice memos button also stops being responsive. 

in my case, once it stops being responsive only restarting the phone will fix the problem. 

I have to do this once a week or so, with heavy usage of signal.

**Comment by 211217613** [comment]
> I have this too, in the most current release, and I've noticed that when the call button stops being responsive, the voice memos button also stops being responsive.
> 
> in my case, once it stops being responsive only restarting the phone will fix the problem.
> 
> I have to do this once a week or so, with heavy usage of signal.

I've just force exited the app and it solves the problem. But what I have seen is the call button on the top of the screen is unresponsive and the call contact bubble in the chat screen is unresponsive.

**Comment by kaktusztea** [comment]
I didn't see this issue for a long time. I close this ticket, will re-open if the problem appears again.

**Comment by holmesworcester** [comment]
Haven't seen it for a while either! Good stuff!
