### ISSUE TITLE
Crash when attempting to delete message, perhaps too soon after receipt

### ISSUE THREAD

**Issue by icequbes1** [signalapp/Signal-iOS#4945]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Application crashes when attempting to delete a message.

### Steps to reproduce
Potential prerequisites:
- Group message
- Group message with only 1 member (myself)
- One linked device (desktop app)

Steps:
- From desktop app, send a message to the group
- iOS app: Message is received, open group message thread
- Tap and hold the new message to bring up the context menu
- Tap the trash can

**Actual result:** Application immediately crashes, brought to the Spring Board.

**Expected result:** Should have prompted "delete for me" / "delete for everyone"

This seems to happen with new messages that I try to delete relatively quickly after they are sent by me from another linked device. Going back to the thread 5+ minutes later yields the 'Expected result' of prompting delete for me/everyone.

May also be potentially related to the fact the message is sent from the linked device, but attempted to be deleted from the "received" device.

Or perhaps the fact it is a group message with a single member spread to multiple devices.

### Device info

**iOS version**: 14, latest

**Signal version:** 5.8.2.0

### Link to debug log

```
Exception Type: EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x000000010028225c
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [283]
Triggered by Thread: 0

Thread 0 name: Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0 Signal  0x10028225c: base_addr + 1991260 
1 Signal  base_addr + 1991220
2 Signal  base_addr + 1988896
3 Signal  base_addr + 1991004
4 Signal  base_addr + 4949620
5 Signal  base_addr + 1385764
6 Signal  base_addr + 741212
7 Signal  base_addr + 2273844
...

base_addr = base of /var/containers/Bundle/Application/uuid/Signal.app/Signal
base_addr = 0x10009c000 for fault observed
```

**Comment by Alvynskio** [comment]
I am facing the same issue! Disappearing message timer was initially off. Then on Desktop I set the timer to 1 min and sent three messages. Then opened iOS and I set disappearing messages off. The recently sent messages are still there and the app crashes when attempting to delete any of the three. The app does not crash when attempting to delete other messages.

**Comment by icequbes1** [comment]
Closing due to no input.
