### ISSUE TITLE
Sent screenshots are blurry/bad quality

### ISSUE THREAD

**Issue by ylieder** [signalapp/Signal-iOS#4946]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a few days, I observed that screenshots taken with the iPhone are very blurry/ in a bad quality if they are shared via signal from an iPhone (see images). I checked my media history and it seems that this behavior has only been occurring for a few weeks. Maybe related to #4929.

### Steps to reproduce
- Take a screenshot on your iPhone
- Send the screenshot via Signal

**Actual result:** The sent image has a very bad quality.

**Expected result:** The image should be in a good quality, optimally with lossless compression (PNG?).

### Screenshots
![IMG_1057](https://user-images.githubusercontent.com/45064516/114592360-203a2200-9c8b-11eb-93df-d6c4cb19f25a.PNG)
![IMG_1055](https://user-images.githubusercontent.com/45064516/114592384-292af380-9c8b-11eb-8b78-d6ec9dea3a3d.PNG)

### Device info

**Device**: iPhone 12 mini

**iOS version**: 14.4.2

**Signal version:** 5.8.2.0

**Comment by dulnan** [comment]
I‘m experiencing the same behaviour with all screenshots sent via Signal.

I also checked my history and it appears this bug was introduced with the latest version, which my phone installed at or around April 9.

Device: iPhone 12 Pro
iOS version: 14.4.2
Signal version: 5.8.2.0
