### ISSUE TITLE
Profile picture disappears constantly 

### ISSUE THREAD

**Issue by gdnzz** [signalapp/Signal-iOS#4952]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Profile pic disappears constantly and sometimes some users cant see it no matter they are on the same problem or not. But mostly, profile pic disappears for everyone. It sometimes takes minutes, sometimes day to disappear.

### Steps to reproduce
- Upload profile photo
- watch it disappear for everyone

### Device info
IPhone 11 pro max

**iOS version**:
14.4.2

**Signal version:** 
5.8.2

### Link to debug log
https://debuglogs.org/f323b8919d1c4f431c0d3880a101804d4d08602c703484a53dc0757ba6c111c3.zip

*Another weird issue*
![signal-2021-04-16-202046](https://user-images.githubusercontent.com/76991571/115061256-9d66d080-9ef1-11eb-95f7-64f25da44a03.png)

![signal-2021-04-16-202108](https://user-images.githubusercontent.com/76991571/115105714-62a07f00-9f69-11eb-82ea-dab5b1f73d17.png)

Sometimes, some people can't see my profile pic
![Screenshot_2021-04-16-20-39-45-030_org thoughtcrime securesms_1](https://user-images.githubusercontent.com/76991571/115063255-ffc0d080-9ef3-11eb-9b1e-730e03a103c4.jpg)

**Comment by mthld** [comment]
duplicate #4860
