### ISSUE TITLE
Speaker issues when picking up video calls using IOS call API

### ISSUE THREAD

**Issue by comaxlau** [signalapp/Signal-iOS#4959]
When I’m picking up a video call from iOS call api, the speaker wasn’t working, it used the front speaker (Phone Call Speaker) which the volume is very low for video calls. 
https://debuglogs.org/71cefeb90bd3fda4e8f739de6f98f328d28221a98e7fbf16f47c0bf6bfe0c8e9.zip

**Comment by JaviHtn** [comment]
I have the same issue. Is a touch annoying when making multiple video calls in a day. Thanks I’m advance for the fix! x

**Comment by denmarkdavis** [comment]
Same issue here. Tested with multiple iPhones. Not great when trying to move friends over to Signal! Thanks 🤙

**Comment by wtangofoxtrot** [comment]
This looks like a duplicate of https://github.com/signalapp/Signal-iOS/issues/4909

**Comment by GWWallen** [comment]
Same issue here. Tested calling from Android to iOS, and iOS to iOS.

**Comment by wtangofoxtrot** [comment]
@comaxlau please confirm if this is a dupe of https://github.com/signalapp/Signal-iOS/issues/4909 and update the older ticket if it is and close this one.

**Comment by comaxlau** [comment]
Confirm duplicate with #4909, will close this ticket accordingly
