### ISSUE TITLE
Unnecessary keyboard when backgrounding, then foregrounding Signal during group update spinner

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4965]
The keyboard appears unnecessarily while the group update spinner is spinning, if the user "moves" Signal into background and then returns back.

### Steps to reproduce
- In preferences for a group chat, press "Edit".
- Disconnect from the internet.
- Make a change to the group name and press "Update".
- While the spinner is spinning, background Signal (i.e. check Notification/Control Center, App Switcher, etc.) and then return back to Signal.

**Actual result:** The on-screen keyboard appears.
**Expected result:** The keyboard should not appear.

### Screen recording
https://user-images.githubusercontent.com/19972511/115587448-62401500-a2d6-11eb-8fd8-44f1375515cc.mp4

### Device info
**Device**: iPhone XR
**iOS version**: 14.4.2
**Signal version:** 5.10.0.47

### Link to debug log
https://debuglogs.org/3fa267f3f28bc7113e585954585d020f650d354e0d3584bcc0740cc7f83856ee.zip

**Comment by Pragyna-Abhishek** [comment]
I just tried to reproduce it on iPhone SE (iOS 14.4.2) and Signal version 5.9.0.49 (It's the latest I found on the App Store; came out 5 days ago). I did not face this problem. But, when I go to the View Controller where we edit group name, my Text Field has a label "Group Name:" unlike yours.

**Comment by u32i64** [comment]
Closing because I can't reproduce this in Signal iOS `5.27.0.102` (perhaps because the editing flow was changed when group descriptions were introduced).
