### ISSUE TITLE
Archive Release Package Error - [CP] Embed Pods Frameworks

### ISSUE THREAD

**Issue by Zhangguiguang** [signalapp/Signal-iOS#4972]
When I archive the project, I always get an error at build "Build Phases" - [CP] Embed Pods Frameworks

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\ Store\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh (in target 'Signal' from project 'Signal')
    cd /Users/***/Desktop/Work/coming-iOS
    /bin/sh -c /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\\\ Store\\\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh

mkdir -p /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/BuildProductsPath/App Store Release-iphoneos/Signal.app/Frameworks
Symlinked...
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by KishoreKumar-Techment** [comment]
I am also facing the error. - Command PhaseScriptExecution failed with a nonzero exit code

**Comment by KishoreKumar-Techment** [comment]
> When I archive the project, I always get an error at build "Build Phases" - [CP] Embed Pods Frameworks
> 
> ```
> PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\ Store\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh (in target 'Signal' from project 'Signal')
>     cd /Users/***/Desktop/Work/coming-iOS
>     /bin/sh -c /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\\\ Store\\\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh
> 
> mkdir -p /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/BuildProductsPath/App Store Release-iphoneos/Signal.app/Frameworks
> Symlinked...
> Command PhaseScriptExecution failed with a nonzero exit code
> ```

How did you fix ? can you please help me?

**Comment by walelgnw** [comment]
> When I archive the project, I always get an error at build "Build Phases" - [CP] Embed Pods Frameworks
> 
> ```
> PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\ Store\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh (in target 'Signal' from project 'Signal')
>     cd /Users/***/Desktop/Work/coming-iOS
>     /bin/sh -c /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\\\ Store\\\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh
> 
> mkdir -p /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/BuildProductsPath/App Store Release-iphoneos/Signal.app/Frameworks
> Symlinked...
> Command PhaseScriptExecution failed with a nonzero exit code
> ```

hey please tell us if you fixed it yet...... pleaseeeeee

**Comment by walelgnw** [comment]
> > When I archive the project, I always get an error at build "Build Phases" - [CP] Embed Pods Frameworks
> > ```
> > PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\ Store\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh (in target 'Signal' from project 'Signal')
> >     cd /Users/***/Desktop/Work/coming-iOS
> >     /bin/sh -c /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/IntermediateBuildFilesPath/Signal.build/App\\\ Store\\\ Release-iphoneos/Signal.build/Script-59C9DBA462715B5C999FFB02.sh
> > 
> > mkdir -p /Users/***/Library/Developer/Xcode/DerivedData/Signal-chqchylaupakpncjdyelhyptfagd/Build/Intermediates.noindex/ArchiveIntermediates/Signal/BuildProductsPath/App Store Release-iphoneos/Signal.app/Frameworks
> > Symlinked...
> > Command PhaseScriptExecution failed with a nonzero exit code
> > ```
> 
> How did you fix ? can you please help me?

hey brooo... did you fixed it??? please let me know
