### ISSUE TITLE
libsignal_ffi.a not built; run the following to build it

### ISSUE THREAD

**Issue by pradeep7may** [signalapp/Signal-iOS#4973]
error: libsignal_ffi.a not built; run the following to build it:
CARGO_BUILD_TARGET=aarch64-apple-ios "/Users/TEST/Signal/Pods/SignalClient/swift/build_ffi.sh"

getting error in latest code, any way to solve this issue

**Comment by tiendaik** [comment]
I'm getting the same issue with latest code, on mac OS 11.2.3, still not find a way to fix it
