### ISSUE TITLE
Cannot load database, Cannot find any logs

### ISSUE THREAD

**Issue by nl00q1** [signalapp/Signal-iOS#4974]
- [x] I have searched open and closed issues for duplicates (potentially #4963 related)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal fails to launch and generates `Could Not Load Database` error. Attempt to submit debug Log generates `Could not find any logs` error.

### Steps to reproduce
- update to 5.9
- receive notification of image-only message from known contact
- launch Signal

**Actual result:**
- screen shows:
```
Could Not Load Database
Signal can’t launch. Please send a debug log to support@signal.org so that we can troubleshoot this issue.
Submit The Debug Log
```
- tab submit, screen shows:
```
Could not find any logs.
OK
```
- tap ok, screen shows app splash screen

**Expected result:**
App should launch normally

### Screenshots
![IMG_4188](https://user-images.githubusercontent.com/77968899/115995194-2fe23080-a5d2-11eb-947a-59bc5df05ba4.jpeg)
![IMG_4189](https://user-images.githubusercontent.com/77968899/115995197-37093e80-a5d2-11eb-8606-a16ddc81e771.jpeg)
![IMG_4191](https://user-images.githubusercontent.com/77968899/115995200-3a9cc580-a5d2-11eb-9910-16c3428b5617.jpeg)

### Device info
**Device**: iPhone 12 Mini

**iOS version**: 14.4.2

**Signal version:** 5.9

### Link to debug log
App shows `Could not find any logs.`

**Comment by nl00q1** [comment]
No change after updating to 5.10

**Comment by NiklasBr** [comment]
Still relevant

**Comment by NiklasBr** [comment]
Still relevant, please stop spamming this question.

**Comment by nl00q1** [comment]
Still relevant
