### ISSUE TITLE
Error sending attachment: Attachment is too large (10.4MB)

### ISSUE THREAD

**Issue by martinbarlow** [signalapp/Signal-iOS#4976]
Hi

i took a panorama photo and tried to send it and it failed. The preview screen was also black and when i tried to send it had error.

I dont think having a 10MB file limit was intentional so filing a bug.

thank you

signal ios 5.10.0.49

**Comment by martinbarlow** [comment]
![13B84588-9164-4B2D-8045-76D427A67734](https://user-images.githubusercontent.com/2373240/116039776-6e77f980-a66b-11eb-8e17-be9facbc1fd5.png)

**Comment by kaktusztea** [comment]
Same here with same client version.
I'd add that the warning message shows up only for about half a second.

**Comment by martinbarlow** [comment]
tested on new ios 14.5. same issue.

**Comment by RangerDan** [comment]
Same issue on iOS 5.12.0.51. 14.2 MB Panorama. Hard crash

https://debuglogs.org/569a04070fb44300f3bf1cdbde00787fd0ac571e3deafe961d7cb08c4eb3e651.zip

**Comment by wtangofoxtrot** [comment]
This appears to be a duplicate of https://github.com/signalapp/Signal-iOS/issues/4929, please confirm and close to decrease noise.

**Comment by mailinglists35** [comment]
duplicate, but why does it take so long to undo the commit that enforces this stupid limit?

**Comment by martinbarlow** [comment]
agree is duplicate

**Comment by martinbarlow** [comment]
hi, i think maybe was fixed!

![7F777F76-DE67-414B-9051-6122C763C302](https://user-images.githubusercontent.com/2373240/124005044-eef30780-d9d8-11eb-99c5-96b6c44aeefd.jpeg)
