### ISSUE TITLE
“Could Not Load Database”

### ISSUE THREAD

**Issue by cherrytea25** [signalapp/Signal-iOS#4978]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating the app on April 19th I only receive “Could Not Load Database” and am prompted to submit a Debug Log over and over again. I tried to update the app again this morning without any changes.

### Steps to reproduce
- just open the app

**Actual result:** “Could Not Load Database” over and over

**Expected result:** ... the app would open normally and I could send and receive messages

### Screenshots

![image](https://user-images.githubusercontent.com/83222111/116082476-0e7c5580-a661-11eb-903a-dc24b02de39e.png)

### Device info
**Device**: iPhone 11 Pro 

**iOS version**: 14.4.2

**Signal version:** 5.10

### Link to debug log

https://debuglogs.org/45024faec85d44ef8ce53c3c3c82d7c455cc6c8d210201d83ed3813d71ba0708.zip

The app doesn’t crash it just won’t load anything

**Comment by walkingwithsaints** [comment]
I have the same issue for IPhone 6s Plus

**Comment by walkingwithsaints** [comment]
[My debug logs](https://debuglogs.org/361777d82f9e10142257b310f5156d73d3f6f04b499a9e517dfa1b03c8a6a94f.zip) 
My debug logs

**Comment by CometACM** [comment]
Same issue here:

https://debuglogs.org/d926e4181dfb3b3ff5ba8c13b63600b89ea913c4a3480a5e8e50cdfcf9921cbe.zip

**Comment by Loofay** [comment]
Same Issue here:

https://debuglogs.org/df611574df38af406dd39a9cc53123d2f36453084c9247afd43d0bac2072a27a.zip

**Comment by CometACM** [comment]
... in my I case it just started working again. Maybe an update fixed it? Hope that it works for the other ppl too! :)

**Comment by Wollipolli** [comment]
same issue here on an iPhone SE 1, problem occured on iOS 15.1 with Signal v5.29.
update to iOS 15.3 and Signal v5.3 did not solve it.
any suggestions on what I could try?

**Comment by Wollipolli** [comment]
Edit: I also cannot submit a debug log.The app crashes when I click on that button.
Is there any chance to recover the database? Or should I reinstall the app and live with the lost history, similar to the people here:
https://github.com/signalapp/Signal-iOS/issues/4963

**Comment by waltertch** [comment]
> Edit: I also cannot submit a debug log.The app crashes when I click on that button. Is there any chance to recover the database? Or should I reinstall the app and live with the lost history, similar to the people here: #4963

Got the same problem and want suggestions as well.

**Comment by jtg** [comment]
Issue still relevant, problem persists

**Comment by Miguel-Signal** [comment]
@jtg Can you please update to the latest version of Signal and see if this resolves the issue? Then, if the issue is still happening, could you write in to support by sending an email to support@ssignal.org?
