### ISSUE TITLE
Person (non-contact) name appears twice for one-word contacts

### ISSUE THREAD

**Issue by gabrc52** [signalapp/Signal-iOS#4984]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have several contacts with just one word. Their names appear twice for some reason. Names with more than one word appear fine.

### Steps to reproduce
- Use Signal on an Android phone (Edit: doesn't have to be Android, bug can be reproduced with iPhone)
- On the Android phone, save someone on your contacts as only one word (for example "John")
- **Make sure the person is not on the iOS (iPad) device's contacts** (Edit)
- Add an iOS device as a secondary (linked) device

**Actual result:** The contact name appears twice: "John John"

**Expected result:** The contact names appear fine: "John"

### Screenshots

I can attach one if needed

### Device info

**Device**: iPad (7th generation)

**iOS version**: 14.4

**Signal version on iPad:** 5.10.0.49

**Signal version on phone**: 5.8.10

### Link to debug log

https://debuglogs.org/cbcf68b2c7d9835e3347ec6d35f7f207b75147bd57d58a4c2da0fc74bc1e440e.zip

---- 

~~Let me know if the bug is on the Android version to file it there~~ Confirmed that this bug happens when linked to iPhone as well

**Comment by Lapsusone** [comment]
Same thing happened to me. I have signal on iOS and linked an iPad. Contact name appears twice “John John”. Moreover, when I click on the edit button for that contact on iPad, the name is in lowercase in the contact sheet. “john” for instance. 

Maybe related, but my default profile picture shows 2 letters even though I wrote only my first name in the profile details. For example, if my first name was “John”, profile picture would show “JJ”.

**Comment by gabrc52** [comment]
@Lapsusone does this happen only on your iPad, or does the name appear twice on the iPhone too?

**Comment by Lapsusone** [comment]
> @Lapsusone does this happen only on your iPad, or does the name appear twice on the iPhone too?

Only on iPad.

**Comment by gabrc52** [comment]
More information about this issue. It only happens if the person is not in the iPad's system contacts, which is the case for me because I don't have my contacts on the iPad, only on the phone.
