### ISSUE TITLE
Receiving or sending messages sometimes doesn't work

### ISSUE THREAD

**Issue by finako** [signalapp/Signal-iOS#4986]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After sending a message it sometimes isn't received by the other person. Sometimes the message takes days to arrive, sometimes only hours. Sometimes waiting a few minutes and then writing another message fixes the problem. Also, on my device there are still the two "message received" ticks even though the message wasn't received. This bug seems to occur completely random, it sometimes even happens in the middle of a conversation.
The other person also runs iOS. However, another person's device runs Android and the bug happens less often in that conversation.

### Steps to reproduce
- I haven't been able to reproduce this bug
- sometimes it seems to me that the following things make the bug more likely to occur:
  - opening & closing the app "too often"
  - turning airplane mode on while in the app
  - changing other wireless settings while in the app

### Device info

**Device**: Apple iPhone 6s

**iOS version**: 13.7

**Signal version:** 5.7.0.19

### Link to debug log

The message not received in this particular case was sent by me at 8:13 UTC on the 4th of May 2021. It was received after sending another message at 11:34 UTC.
https://debuglogs.org/011a7484fb254ab967d9dbd00f28ee1fcc6a8e4aa12cc3356066a0bc91c20e43.zip

**Comment by finako** [comment]
May also be a bug on the receiving side... _sometimes_ just opening the app on the other person's device solves the problem.

**Comment by altechzilla** [comment]
Having the exact same issue. The receiver is on Android and the sender is on iOS. Only when you send another message you receive the latest message(s) from the receiver.

**Comment by JuicedEagle** [comment]
Having the same issue..
Reciever is on iPhone 12 with iOs 14.5.1 sender is on iPhone 11 with iOs 14.5.1 and same goes the other way around.

**Comment by finako** [comment]
Issue seems to be less common now, but still there.
