### ISSUE TITLE
Voice message recording breaks when a notification is received or the device is rotated 

### ISSUE THREAD

**Issue by lizgjones** [signalapp/Signal-iOS#4987]
### Issue 

Voice recordings do not work if I receive a notification while recording, a timer/alarm goes off, or if my phone rotates orientation (portrait to landscape). It will appear to continue recording but when I try to send it, it will simply disappear.

There may be other things that cause voice messages to stop recording. I know of at least 4 people experiencing this issue. So far, these are the causes I have identified, but other incidents have happened that do not appear to be caused by a notification or rotating the device. 

### Steps to Reproduce

**Timer goes off, notification received**
Video: https://user-images.githubusercontent.com/1807328/117185576-f8307100-ada7-11eb-9ef7-1d6b4ed7fdee.MP4

1. Start a 10 second timer
2. Go to Signal
3. Start recording
4. Wait for the timer to go off 
5. Swipe the notification away
6. Wait another second or two
7. Hit Send.

The recording appears to keep going, but when I hit Send, instead of sending I get the notice telling me to tap and hold to record, and nothing is sent. 

**Device is rotated**
Video: https://user-images.githubusercontent.com/1807328/117185652-0f6f5e80-ada8-11eb-9443-19fb9ef5adca.MP4

1. Start the recording. Wait a few seconds.
2. Turn the device sideways
3. Turn it back upright

The message I was recording is simply gone. 

### Device Info
Note: these recordings were made on Signal version 5.11 on iOS 14.4.2 on iPhone 11

**Comment by bluumb** [comment]
A friend of mine has exactly the same problem. When she records a voice message while rotating the phone, the voice message stops.
On May 21, this happened at about 12:30 (European time), the timings in the logs seem to be 2 hours later.
However, the problem of a voicemail aborting when it receives a notification does not seem to occur.

https://debuglogs.org/efc302e2f2e51e01bff096428d5989b710de097d593e40e91185d20763d60cb4.zip

**Comment by relffok** [comment]
I can confirm that this is still an issue on 5.26.10 (iOS 15.1).
