### ISSUE TITLE
App won’t open

### ISSUE THREAD

**Issue by katleend** [signalapp/Signal-iOS#4989]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing. App won’t open

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour) The app simply won’t open... I can’t do anything 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone 12 Pro 

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by JamesDevJim** [comment]
Same. https://debuglogs.org/ae2a183f1f65683f913f5d64c15249212b5e8264c925a5b9fe4328a905e26d6b.zip
