### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by ChetanRajagiri** [signalapp/Signal-iOS#4992]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes when we click on any mobile number

### Steps to reproduce
- Click on hyperlink with mobile number

**Actual result: App Crashes

**Expected result: We should get a call options

### Device info

**Device**: iDevice 11 ProMax

**iOS version**: 14.5.1

**Signal version:** 5.11.1.1

### Link to debug log
[Link](https://debuglogs.org/062a3c73ac71fd58ba83660ecf1791d76910a43f37d80207ad2f444515923573.zip)

**Comment by shorshe** [comment]
Same here iOS 14.5. iPhone X

https://debuglogs.org/94b040264547bc5dbc023911e5d3ff923b0dd36ea39ff273366b1585ca65053c.zip
