### ISSUE TITLE
ios 14.5.1 Share Sheet suggests sending a message to one contact, but when I select the person, Signal takes me to the contact list and I have to select the person I want to share to

### ISSUE THREAD

**Issue by pb-sobrien** [signalapp/Signal-iOS#4993]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal share sheet has worked fine on my iPhone 11 for months. I got a new iPhone 12 Mini last weekend and this problem has persisted on the new phone the whole time.

My boyfriend and I use Signal to message each other, and I regularly share links/pics with him directly from the Share Sheet. I am used to tapping on his contact image in the Share Sheet and be taken directly to our chat.

However, now when I tap on his contact on the Share Sheet, I have to select his name from the Signal contact list.

I do not like this, as it opens up to me potentially sharing things to people on accident. I prefer selecting him from the Share Sheet and knowing he'll be the only person to get it.

### Steps to reproduce
- open a photo (or website) on iOS 14.5.1
- tap the "Share" button
- See a singular Signal contact appear in the Share Sheet
- Tap the single suggested contact in the share sheet

**Actual result:** I am shown a list of my contacts in Signal, and I have to again select the Signal contact I want to share the item with

**Expected result:** I would be taken directly to the chat with the suggested Contact

### Device info

**Device**: iPhone 12 Mini

**iOS version**: 14.5.1

**Signal version:** 5.11.1.1

### Link to debug log
https://debuglogs.org/b68423446722a09035103e95cc0f8969f25cced743c7c341a7f2303a2a6e9143.zip

**Comment by Paul-Haley** [comment]
This issue is still present to this day.
