### ISSUE TITLE
Signal Crashes When Opening More Than One Photo

### ISSUE THREAD

**Issue by UnitedDugout27** [signalapp/Signal-iOS#4995]
I'm an android user, and my friend's Signal app will crash on ios when opening pictures sent from me. It will crash when I send more than 3 at a time.

**Comment by kaktusztea** [comment]
@UnitedDugout27: it would be useful to attach a crash and debug log to help devs to find the cause of your issue.
https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug
