### ISSUE TITLE
Impossible to create a new group on iPad

### ISSUE THREAD

**Issue by SimonEast** [signalapp/Signal-iOS#4996]
Signal Version 5.11.1.1

(Apologies if this is a duplicate bug. I couldn’t see it in the list.)

When attempting to create a new group on my iPad, I get a screen that looks like this:

![D4E07D0D-FCCD-4202-9F6F-75046C2CB875](https://user-images.githubusercontent.com/813734/118395481-fe6afb00-b68d-11eb-9719-787069cda960.jpeg)

It seems to be asking for a group name, but when I try typing nothing happens. Maybe it’s because I’m using a Bluetooth keyboard? Not sure. It also seems to have a button for attaching a photo but tapping this also does nothing. 

If I try tapping “Create” it tells me I have not entered a name for the group. The screen seems to be broken and the only option is to go back.

Using iOS 13.6.

**Comment by SimonEast** [comment]
I haven’t tested it on iPad for a while, so I’m not sure if the issue
persists. Perhaps it can be closed for now, and only reopened if it
reappears.

**Comment by kaktusztea** [comment]
Hi @SimonEast,
you opened the ticket, so you can also close it 🙂
