### ISSUE TITLE
Signal Turns on SMS Read Receipts without permission 

### ISSUE THREAD

**Issue by MrWaste** [signalapp/Signal-iOS#5000]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal has a feature that allows to READ RECEIPTS. IOS has the same feature. Signal turns on READ RECEIPTS constantly inside the IOS setting page. (Proof 1 Pic) 

### Steps to reproduce
- SMS Read Receipts OFF (IOS Settings Tab)
- Use Signal
- SMS Read Receipts ON (Repeats every time: 5x I have tried,)
- I deleted signal off my phone to stop this from happening and it worked

**Actual result:** Turns ON SMS Read Receipts in the IOS settings tab.

**Expected result:** It should leave the SMS Read Receipts alone and not touch my settings unless its my doing.

### Screenshots

![Proof 1](https://user-images.githubusercontent.com/49108816/118870960-f4b6e280-b89b-11eb-89c4-02c16e58e976.jpeg)

### Device info

**Device**: iPhone 12 Mini

**iOS version**: 14.4.2

**Signal version:** Latest Version

**Comment by jonathancross** [comment]
Are you talking about the *"Send Read Receipts"* setting shown in your screen shot?
I believe that is only for Signal (non-SMS) messages.
Clearly the setting should not _revert itself_, but it's good to be clear what we're talking about here.
