### ISSUE TITLE
Microphone button for Voice Messages Issue 

### ISSUE THREAD

**Issue by Darkhorse02** [signalapp/Signal-iOS#5002]
https://user-images.githubusercontent.com/84575039/119137994-be888700-ba84-11eb-8120-ba13b8046aa4.MP4

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------
Since updating to 5.12 on IOS, when I press the red button to record a voice message, the red button is loose can can move left and right, this behavior was not happening in 5.11.

**Actual result:** Look at the video to see issue 

**Expected result:** The button is meant to stay fixed and only be able to push up to lock if want to record a long voice message (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone 12 Pro 

**iOS version**: 14.5.1

**Signal version:** 5.12

**Comment by azuredusk10** [comment]
And what if you want to cancel the voice message recording? The action to cancel the recording is to slide the button to the left. Would you not expect the button to move as you swipe to the left?

**Comment by Darkhorse02** [comment]
> And what if you want to cancel the voice message recording? The action to cancel the recording is to slide the button to the left. Would you not expect the button to move as you swipe to the left?

Yes I understand that feature but watch the screen recording I did, the red microphone button is still way to loose,and most times when you swipe left it doesn't cancel the voice message, I use the voice messaging alot,  and after 5.12, using the button it's too jumpy if that's the right term
