### ISSUE TITLE
Unable to enable dictation

### ISSUE THREAD

**Issue by apphancer** [signalapp/Signal-iOS#5003]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Tapping on the dictation key (microphone symbol) on the keyboard when dictation has not been previously enabled results in a notification displaying where I should agree to use the service. However, the notification displays only for 1 second or less and then disappears resulting in me being unable to tap on the Accept option to enable it.

### Steps to reproduce
- Open a chat
- Tap in the "New Message" field
- Once the keyboard opens up, tap on the Dictation key

**Actual result:** Notification displays and disappears quickly so quickly that it's impossible to read or to select any of the options

**Expected result:** Notification should display and remain until the user takes an action (e.g. accept, decline, close)

### Workaround
Opening the same functionality in WhatsApp works (i.e. the message stays displayed and I am able to accept the dictation service). Returning back to Signal the dictation feature works as it's already been accepted elsewhere.

### Device info
**Device**: iPhone 8 Plus

**iOS version**: 14.4.2

**Signal version:** 5.12.0

**Comment by Jack15911** [comment]
My iPhone 8 using 14.8 has the same symptoms - not allowing dictation - but only in a moving car; dictation works as expected while not moving. Apple iMessages works in moving car.

**Comment by chris-gillatt** [comment]
Same issue on a iphone 13 Pro Max on iOS 15.

**Comment by te2dy** [comment]
I just got an iPhone and installed Signal without ever having used dictation, and this bug still exists.
