### ISSUE TITLE
unable to send or receive messages from a specific contact: "unexpectedly missing message for reaction"

### ISSUE THREAD

**Issue by luser** [signalapp/Signal-iOS#5006]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My partner has been unable to send or receive Signal messages to and from me in the Signal app on iOS for several days. Messages she attempts to send from the app are stuck with the "sending" spinner. She can communicate with other Signal contacts without problems. Additionally, she has Signal Desktop linked on her MacBook, and she can communicate with me there. I had her generate a debug log (linked below), and the issue seems to be that it's attempting to send a reaction to a message that does not exist, getting [this "unexpectedly missing message for reaction" error](https://github.com/signalapp/Signal-iOS/blob/4666335ffca65589694b1e9fcc162ee1d96143f4/SignalServiceKit/src/Messages/Reactions/OWSOutgoingReactionMessage.m#L56). Relevant log snippet:

```
2021/05/24 22:34:57:366  💛 [MessageSender.m:413 -[MessageSender sendMessage:success:failure:]_block_invoke]: Sending message: OWSOutgoingReactionMessage, timestamp: 1621443637515.
2021/05/24 22:34:57:368  💛 [TSNetworkManager.m:394 -[TSNetworkManager makeRequestSync:completionQueue:success:failure:]_block_invoke]: UD request succeeded : { GET: v1/profile/[ REDACTED_UUID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx82 ]/7fdcd22cf1a9432f4e17369b1c77758bb7c1aecaec78c753c5a14e3ff15d4bca }
2021/05/24 22:34:57:372  💛 [MessageSender.m:969 -[MessageSender _sendMessageToRecipient:]]: attempting to send message: OWSOutgoingReactionMessage, timestamp: 1621443637515, recipient: <SignalServiceAddress phoneNumber: [ REDACTED_PHONE_NUMBER:xxx576 ], uuid: [ REDACTED_UUID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx8B ]>
2021/05/24 22:34:57:373  ❤️ [OWSOutgoingReactionMessage.m:56 -[OWSOutgoingReactionMessage dataMessageBuilderWithThread:transaction:]]: unexpectedly missing message for reaction
2021/05/24 22:34:57:373  ❤️ [TSOutgoingMessage.m:1405 -[TSOutgoingMessage buildDataMessage:thread:transaction:]]: could not build protobuf.
2021/05/24 22:34:57:373  ❤️ [TSOutgoingMessage.m:1430 -[TSOutgoingMessage buildPlainTextData:thread:transaction:]]: could not build protobuf: (null)
2021/05/24 22:34:57:373  🧡 [MessageSender.m:1260 -[MessageSender throws_deviceMessagesForMessageSend:]]: Exception: AxolotlInvalidMessageException Failed to build message proto
2021/05/24 22:34:57:374  🧡 [MessageSender.m:928 -[MessageSender deviceMessagesForMessageSend:error:]]: Could not build device messages: Failed to build message proto
2021/05/24 22:34:57:375  ❤️ [MessageSender.m:294 -[OWSSendMessageOperation didFailWithError:]]: Failed with error: Error Domain=OWSSignalServiceKitErrorDomain Code=30 "Failed to send message." UserInfo={NSLocalizedDescription=Failed to send message.} (isRetryable: 1)
```

The recipient phone number there matches my number.

### Steps to reproduce

I do not have STR.

### Device info

**Device**: iPhone SE (iPhone12,8; D79AP)

**iOS version**: 13.7 (17H35)

**Signal version:**: 5.12.0 (5_12_0_51)

### Link to debug log
https://debuglogs.org/56201d85a96abf7056cb9d9b18bdc3110a65c06419f7ba57708094578f344840.zip

I have physical access to her phone for the next few days if there is anything else I can do to help diagnose. Any suggestions of a workaround that would get her out of this situation would be greatly appreciated, as she is extremely frustrated by it.

**Comment by luser** [comment]
Poking around related code, I see that [in the case where a queued message has been deleted](https://github.com/signalapp/Signal-iOS/blob/4666335ffca65589694b1e9fcc162ee1d96143f4/SignalServiceKit/src/Messages/MessageSender.m#L268) the send is aborted. Is it possible to do the same here?

**Comment by luser** [comment]
Walking up the stack of printed error messages from the log, we have the base error in `[OWSOutgoingReactionMessage dataMessageBuilderWithThread:transaction:]]`:
https://github.com/signalapp/Signal-iOS/blob/4666335ffca65589694b1e9fcc162ee1d96143f4/SignalServiceKit/src/Messages/Reactions/OWSOutgoingReactionMessage.m#L56
which is called by `[TSOutgoingMessage buildDataMessage:thread:transaction:]]`:
https://github.com/signalapp/Signal-iOS/blob/4efc5242cd54ad5c3146d458cbbc6c7141317aaf/SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m#L1403
called by `[TSOutgoingMessage buildPlainTextData:thread:transaction:]]`:
https://github.com/signalapp/Signal-iOS/blob/4efc5242cd54ad5c3146d458cbbc6c7141317aaf/SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m#L1428
called by `[MessageSender throws_deviceMessagesForMessageSend:]]`:
https://github.com/signalapp/Signal-iOS/blob/4666335ffca65589694b1e9fcc162ee1d96143f4/SignalServiceKit/src/Messages/MessageSender.m#L1250
called by `[MessageSender deviceMessagesForMessageSend:error:]]`:
https://github.com/signalapp/Signal-iOS/blob/4666335ffca65589694b1e9fcc162ee1d96143f4/SignalServiceKit/src/Messages/MessageSender.m#L862

That outermost frame handles specific exceptions and sets up errors for the caller, but the inner frames all seem to just log errors and return `nil`. I don't know what the general exception handling story is in this code, but being able to propagate an error upward here would be really useful.

**Comment by luser** [comment]
I guess as an alternative, adding an `error:(NSError**)` outparam to those top three frames would be viable.

**Comment by jonathancross** [comment]
@luser is this still an issue?

**Comment by luser** [comment]
It stopped occurring for my partner, but given my reading of the code it seems like there's a bug in the code for handling reactions to messages that no longer exist.
