### ISSUE TITLE
Power button ends call on loudspeaker mode (it should not)

### ISSUE THREAD

**Issue by balintmaci** [signalapp/Signal-iOS#5010]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Pressing the power button ends the call instead of turning the display off. I end calls all the time accidentally.
This is normal behavior on earspeaker but not loudspeaker.
Bluetooth audio mode is not affected.
When you switch to loudspeaker mode, the button gets highlighted, but then the highlighting disappears sometimes. This suggests that there might be a bug in how the loudspeaker mode is registered for the system. Despite this, the audio always comes through the correct speaker. The main issue seems to be the power button hang up.

### Steps to reproduce
- make or receive a call
- switch to loudspeaker mode (don't have a bluetooth audio device connected)
- press power button to lock screen

**Actual result:** Call is ended

**Expected result:** Screen locks and call stays on

### Device info

**Device**: iPhone SE 2020 (but others seem to be affected as well)

**iOS version**: 14.5.1 (but the bug has been present for a long time, independent of the version)

**Signal version:** 5.12.0.51 (currently, but has been there for many versions)

**Comment by balintmaci** [comment]
it is still relevant

**Comment by balintmaci** [comment]
It is still relevant and signal is the only call app I have that has this problem. Please fix

**Comment by bbk-riact** [comment]
It is

**Comment by readstead** [comment]
It's still relevant and extremely annoying and perfectly reproducible. Not sure why it's still not fixed after years. Duplicate of #4167 and #5313 and probably more.

**Comment by Winterherr** [comment]
how about reopening it? Still having issues with it
