### ISSUE TITLE
Audio message playback stops when device is turned to landscape mode

### ISSUE THREAD

**Issue by LitVul** [signalapp/Signal-iOS#5011]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio message playback stops when the device is turned from portrait to landscape orientation.

### Steps to reproduce
- start playing audio message with the device being in portrait orientation 
- turn the device to landscape orientation 

**Actual result:** Audio message playback stops

**Expected result:** Audio message playback should continue

### Device info

**Device**: iPhone 11

**iOS version**: 14.6

**Signal version:** 5.12.0.51

### Link to debug log

https://debuglogs.org/73c1c96afcfe48e3bc0e23dd92b1080fd64511699fb2c6c6bda61fad1f8f0478.zip

**Comment by DarBeck** [comment]
This is a very annoying problem. It forces me to put my phone in portrait lock.

**Comment by jonathancross** [comment]
Bot: do not close this.
