### ISSUE TITLE
Incoming calls problem

### ISSUE THREAD

**Issue by sarbojit4** [signalapp/Signal-iOS#5012]
Recently I saw that signal app is missing incoming calls. If someone calls me, I cannot see any incoming call on the  app. This is happening quite often.

**Comment by Anonban** [comment]
Same on my iPhone SE 2nd generation

**Comment by sarbojit4** [comment]
This issue is not fixed.

**Comment by atiq-cs** [comment]
This task shouldn't be closed. This is a recurring bug. It should be fixed.

Happening everyday in last week. We cannot accept calls. Our friends using signal app cannot too. This seems to be affecting all mobile platforms (desktop apps might not be affected). Here's example from yesterday.

![image](https://user-images.githubusercontent.com/7858031/168449160-7f5236fc-d344-4e38-beac-e39a0d0a06f8.png)
