### ISSUE TITLE
EXC_BAD_ACCESS on class GRDBDatabaseStorageAdapter sqlite at startup

### ISSUE THREAD

**Issue by dmarras** [signalapp/Signal-iOS#5016]
Hi, i'm experiencing a following issue on iOS devices up to 11.04 os version on line:
`let code = sqlite3_wal_checkpoint_v2(db.sqliteConnection, nil, mode.rawValue, &walSizePages, &pagesCheckpointed)
`
On 11.04 and lower no issue comes up.

thread #2, queue = 'GRDB Checkpointing', stop reason = EXC_BAD_ACCESS (code=1, address=0x24)
frame #0: 0x000000011caae441 libsqlite3.dylibsqlite3Checkpoint + 353 frame #1: 0x000000011caae21e libsqlite3.dylibsqlite3_wal_checkpoint_v2 + 542
frame #2: 0x00000001114a8303 SignalServiceKitclosure #1 in closure #1 in static GRDBDatabaseStorageAdapter.checkpoint(db=0x00007fd3af805e20, startTime=4934.0185850850003, mode=truncate, walSizePages=-1, pagesCheckpointed=-1) at GRDBDatabaseStorageAdapter.swift:719:28 frame #3: 0x00000001114af0ee SignalServiceKitpartial apply for closure #1 in closure #1 in static GRDBDatabaseStorageAdapter.checkpoint(checkpointingQueue:mode:) at :0
frame #4: 0x000000011149ce7f SignalServiceKitthunk for @callee_guaranteed (@guaranteed Database) -> (@error @owned Error) at <compiler-generated>:0 frame #5: 0x00000001114af114 SignalServiceKitthunk for @callee_guaranteed (@guaranteed Database) -> (@error @owned Error)partial apply at :0
frame #6: 0x000000010c41a05d GRDBclosure #1 in SerializedDatabase.sync<T>(self=0x000060000108c300, block=0x00000001114af100 SignalServiceKitreabstraction thunk helper from @callee_guaranteed (@guaranteed GRDB.Database) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@guaranteed GRDB.Database) -> (@out (), @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".53" at ) at SerializedDatabase.swift:98:28
frame #7: 0x000000010c41ad00 GRDBpartial apply for closure #1 in SerializedDatabase.sync<A>(_:) at <compiler-generated>:0 frame #8: 0x000000011b37e041 libswiftDispatch.dylibpartial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> (@out A, @error @owned Swift.Error) to @escaping @callee_guaranteed () -> (@out A, @error @owned Swift.Error) + 17
frame #9: 0x000000011b377912 libswiftDispatch.dylibclosure #1 () -> () in closure #1 (() throws -> A) -> () in (extension in Dispatch):__C.OS_dispatch_queue.(_syncHelper in _F417D752D2C4E9330E1C700411CE0C6A)<A>(fn: (() -> ()) -> (), execute: () throws -> A, rescue: (Swift.Error) throws -> A) throws -> A + 82 frame #10: 0x000000011b37e0bd libswiftDispatch.dylibmerged partial apply forwarder for closure #1 () -> () in (extension in Dispatch):__C.OS_dispatch_queue.(_syncHelper in _F417D752D2C4E9330E1C700411CE0C6A)(fn: (Dispatch.DispatchWorkItem) -> (), flags: Dispatch.DispatchWorkItemFlags, execute: () throws -> A, rescue: (Swift.Error) throws -> A) throws -> A + 29
frame #11: 0x000000011b37e090 libswiftDispatch.dylibpartial apply forwarder for closure #1 () -> () in closure #1 (() throws -> A) -> () in (extension in Dispatch):__C.OS_dispatch_queue.(_syncHelper in _F417D752D2C4E9330E1C700411CE0C6A)<A>(fn: (() -> ()) -> (), execute: () throws -> A, rescue: (Swift.Error) throws -> A) throws -> A + 16 frame #12: 0x000000011b37de41 libswiftDispatch.dylibpartial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> () + 17
frame #13: 0x000000011b37f069 libswiftDispatch.dylibreabstraction thunk helper from @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> ()partial apply forwarder with unmangled suffix ".139" + 9 frame #14: 0x000000011b3718be libswiftDispatch.dylibreabstraction thunk helper from @escaping @callee_guaranteed () -> () to @callee_unowned @convention(block) () -> () + 14
frame #15: 0x000000011b974db5 libdispatch.dylib_dispatch_client_callout + 8 frame #16: 0x000000011b982d08 libdispatch.dylib_dispatch_lane_barrier_sync_invoke_and_complete + 132
frame #17: 0x000000011b377ec8 libswiftDispatch.dylib@nonobjc __C.OS_dispatch_queue.sync(execute: () -> ()) -> () + 152 frame #18: 0x000000011b37bc10 libswiftDispatch.dylibpartial apply forwarder for @nonobjc __C.OS_dispatch_queue.sync(execute: () -> ()) -> () + 16
frame #19: 0x000000011b3777c3 libswiftDispatch.dylib(extension in Dispatch):__C.OS_dispatch_queue.(_syncHelper in _F417D752D2C4E9330E1C700411CE0C6A)<A>(fn: (() -> ()) -> (), execute: () throws -> A, rescue: (Swift.Error) throws -> A) throws -> A + 259 frame #20: 0x000000011b377dff libswiftDispatch.dylib(extension in Dispatch):__C.OS_dispatch_queue.sync(execute: () throws -> A) throws -> A + 143
frame #21: 0x000000010c419ed5 GRDBSerializedDatabase.sync<T>(block=0x00000001114af100 SignalServiceKitreabstraction thunk helper from @callee_guaranteed (@guaranteed GRDB.Database) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@guaranteed GRDB.Database) -> (@out (), @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".53" at , self=0x000060000108c300) at SerializedDatabase.swift:96:30
frame #22: 0x000000010c3109d1 GRDBDatabaseQueue.inDatabase<T>(updates=0x00000001114af100 SignalServiceKitreabstraction thunk helper from @callee_guaranteed (@guaranteed GRDB.Database) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@guaranteed GRDB.Database) -> (@out (), @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".53" at , self=0x0000600001ef1fa0) at DatabaseQueue.swift:346:27
frame #23: 0x00000001114a7ddf SignalServiceKitclosure #1 in static GRDBDatabaseStorageAdapter.checkpoint(checkpointingQueue=0x0000600001ef1fa0, mode=truncate, walSizePages=-1, pagesCheckpointed=-1) at GRDBDatabaseStorageAdapter.swift:708:36 frame #24: 0x00000001114a9aec SignalServiceKitpartial apply for closure #1 in static GRDBDatabaseStorageAdapter.checkpoint(checkpointingQueue:mode:) at :0
frame #25: 0x000000011135463f SignalServiceKitthunk for @callee_guaranteed () -> (@error @owned Error) at <compiler-generated>:0 frame #26: 0x00000001114a9b14 SignalServiceKitpartial apply for thunk for @callee_guaranteed () -> (@error @owned Error) at :0
frame #27: 0x0000000111372782 SignalServiceKitBench<T>(title="Slow checkpoint: truncate", intervalLimit=0.01, logInProduction=true, block=0x00000001114a9b00 SignalServiceKitpartial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> (@error @owned Swift.Error) to @escaping @callee_guaranteed () -> (@out (), @error @owned Swift.Error) at ) at Bench.swift:49:21
frame #28: 0x00000001114a7985 SignalServiceKitstatic GRDBDatabaseStorageAdapter.checkpoint(checkpointingQueue=0x0000600001ef1fa0, mode=truncate, self=SignalServiceKit.GRDBDatabaseStorageAdapter) at GRDBDatabaseStorageAdapter.swift:704:13 frame #29: 0x00000001114a7551 SignalServiceKitGRDBDatabaseStorageAdapter.syncTruncatingCheckpoint(self=0x00007fd3bcd26750) at GRDBDatabaseStorageAdapter.swift:691:53
frame #30: 0x00000001114a7c0a SignalServiceKit@objc GRDBDatabaseStorageAdapter.syncTruncatingCheckpoint() at <compiler-generated>:0 frame #31: 0x000000011675ecc5 SignalMessaging__78+[AppSetup setupEnvironmentWithAppSpecificSingletonBlock:migrationCompletion:]_block_invoke_3(.block_descriptor=0x0000600003afa400) at AppSetup.m:204:21
frame #32: 0x000000011b973d7f libdispatch.dylib_dispatch_call_block_and_release + 12 frame #33: 0x000000011b974db5 libdispatch.dylib_dispatch_client_callout + 8
frame #34: 0x000000011b9777b9 libdispatch.dylib_dispatch_queue_override_invoke + 1022 frame #35: 0x000000011b985632 libdispatch.dylib_dispatch_root_queue_drain + 351
frame #36: 0x000000011b985fca libdispatch.dylib_dispatch_worker_thread2 + 130 frame #37: 0x000000011bd88453 libsystem_pthread.dylib_pthread_wqthread + 244
frame #38: 0x000000011bd87467 libsystem_pthread.dylib`start_wqthread + 15

**Comment by Nagesh-Chandan** [comment]
I'm running the app for the first time and I got this issue. 
MacOS: Big Sur 11.2.3 (20D91)
XCode: 12.4 (12D4e)
Destination: iPhone SE Simulator

**Comment by balupton** [comment]
You should put the log between three backticks, or use the code button on tge wysiwyg toolbar, as currently the log has accidentally tagged a bunch of irrelevant issues
