### ISSUE TITLE
Different color per person in group chat

### ISSUE THREAD

**Issue by tdegeus** [signalapp/Signal-iOS#5017]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

In my household we are two:
* One uses Signal on iOS/macOS 
* One using Signal on Android/macOS.

For the person on Android/macOS group conversations get shown with an individual background color for messages from each participant (e.g. messages from participant A are always red, messages from participant B are always green, etc.). This persists both on Android and on macOS.

For the person on iOS/macOS the send messages are always blue and received messages always gray (when working on "dark" mode), no matter if it is an individual conversation or a group conversation. This persists both on iOS and macOS.

### Device info

**Device**: iPone 7

**iOS version**: 14.4.2

**Signal version:** 5.13.0.33

### Link to debug log

[org.whispersystems.signal 2021-05-31--18-58-08-907.log](https://github.com/signalapp/Signal-iOS/files/6584697/org.whispersystems.signal.2021-05-31--18-58-08-907.log)

**Comment by Nostrocean** [comment]
They expect people cease complain, when the solution are three lines of code, which would leave both systems active, at the user's choice in the color panel.

https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/1241

Do not stop complaining. and do not donate. do not recommend donate, explain the reasons... once captured, you don't matter. Business are business.
