### ISSUE TITLE
Crashes when opening app

### ISSUE THREAD

**Issue by ScalableCodex** [signalapp/Signal-iOS#5019]
Signal crashes upon opening it up after getting messages. Can't seem to recreate it consistently. But it's started today randomly. Never happened before. It's happened over 25 times just today

Restarting the device doesn't help. And I'd rather not try reinstalling as I don't wanna lose my messages at the moment.

**Comment by beret** [comment]
See this for crash logs: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug
