### ISSUE TITLE
Cannot create a new group

### ISSUE THREAD

**Issue by TopMode9499** [signalapp/Signal-iOS#5020]
Whenever I try to create a new chat group, I add members, then it takes me to group name, which is completely blank. Can’t click anything. I try click ‘Create’ but am prompted with ‘a group name is required’

**Comment by NikkyGithub** [comment]
@charlesmchen @Imperiopolis-Signal 

Please, make feature that allows set color on Appearance “Chat color” section in “RGB Hex Code format. Example: #0000FF” but not only slider.
