### ISSUE TITLE
cannot reset appearance after changing chat color

### ISSUE THREAD

**Issue by FloD-B** [signalapp/Signal-iOS#5021]
cannot reset appearance after changing chat color

**Comment by NikkyGithub** [comment]
@charlesmchen-signal @Imperiopolis-Signal 

Please, make feature that allows set color on Appearance “Chat color” section in “RGB Hex Code format. Example: #0000FF” but not only slider.

Something like this:
![E009CD64-08DF-452E-BF71-AEEAF7D2F667](https://user-images.githubusercontent.com/42260998/120895374-5198f380-c625-11eb-8b95-daa6ca37339b.jpeg)

**Comment by FloD-B** [comment]
After many try, it works 🤷🏻‍♂️
