### ISSUE TITLE
Duplicated notifications on iOS when using Desktop

### ISSUE THREAD

**Issue by the-woocash** [signalapp/Signal-iOS#5022]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Chatiing using desktop app (macos), phone with ios keeps bugging me with notifications after every message received.
### Steps to reproduce
-have signal on ios and signal on desktop
-chat with someone on desktop

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
-receive a notification on ios after every message received and read on desktop

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
-do NOT receive a notification on ios after every message received on desktop

### Device info

**Device**: iPhone 7+

**iOS version**: 14.6

**Signal version:** 5.14

### Link to debug log

https://debuglogs.org/3feeba8cf80df4f2e6817264210a03231e4c5a52facd7fb646f0df862000122b.gz

**Comment by cobrabr** [comment]
This is very much still relevant. I don't want to have my phone/watch buzzing with Signal messages if I'm online on the Desktop app.
