### ISSUE TITLE
Can't see face in video call when a shared PDF is open

### ISSUE THREAD

**Issue by jchen975** [signalapp/Signal-iOS#5024]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During a video call, I sent the other person a PDF document. While the PDF was open on Signal, enlarging the video call window (by tapping on the smaller video window, which has their face and background) resulted in a black screen. I was able to tap again to see the smaller window, and exit the PDF; then everything works fine.

**Expected result:** I should be able to see the other person's face even with the PDF open.

### Device info

**Device**: iPhone 11

**iOS version**: 14.4.2

**Signal version:** 5.14.0.35

**Comment by elemanhillary** [comment]
I confirm this tested it out and it occurs
