### ISSUE TITLE
iOS Shortcuts App: Signal action for sending new messages is broken

### ISSUE THREAD

**Issue by moritzluedtke** [signalapp/Signal-iOS#5030]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The action in iOS shortcuts app for sending a new message with Signal is not working. Instead of opening the chat and sending a message it only switches to the app. And shows the screen that was previously open. 

### Steps to reproduce
- Create a new shortcut inside the shortcuts iOS app
- Add a new Text action and type in something
- Add a Signal action like "Send a message to XYZ"
- Execute the shortcut

**Actual result:**
The shortcut only switches to signal but does not send any message or opens the chat for XYZ. 

**Expected result:**
The send message action sends the text it gets to the contact. 

### Device info

**Device**: iPhone XS

**iOS version**: 14.6

**Signal version:** 5.14.0.35

**Comment by rlieving** [comment]
Plus one. Shortcuts for Signal on iOS are not working.

**Comment by moritzluedtke** [comment]
It's still not working with version 5.19.2.0

**Comment by moritzluedtke** [comment]
Still broken in iOS 15 with Signal 5.20.3.1

**Comment by phifa** [comment]
iOS shows auto-generated suggestions for shortcuts, based on your usage. For me it shows for Signal: "Send message to Bob", since I am messaging with Bob on Signal a lot. But when I click it, it opens an iMessage to Bob. But I have sent Bob a text/iMessage.

**Comment by StefanLobbenmeier** [comment]
Relevant PR from 1 year ago: https://github.com/signalapp/Signal-iOS/pull/4856

**Comment by moritzluedtke** [comment]
Still relevant. Missing feedback from the Signal team.

**Comment by moritzluedtke** [comment]
Still relevant.

**Comment by rlieving** [comment]
Still relevant.

**Comment by moritzluedtke** [comment]
Does anyone know if Signal actually looks at these issues? Doesn't seem to be the case sadly.

**Comment by andrewschmidgit** [comment]
Still relevant. Why no response?

**Comment by boettner** [comment]
Still relevant. Tried it on iOS 16.1.1 and Signal 6.2.3.0.

**Comment by bexelbie** [comment]
necro bumping, if I can as this issue is real.  I am not sure how Product Management works at Signal, but I hope they read this.

**Comment by bexelbie** [comment]
@EvanHahn-Signal what I see is this:

Shortcuts suggests a bunch of actions, like "Send a Signal message to X" where X is a person or group.  These do not work as written.

There is no way to use the generic suggested actions for Signal or modify the above suggestions.

Choosing any of them in a shortcut just causes Signal to open to where it was the last time it was opened with no action performed.

**Comment by bexelbie** [comment]
Working under the premise that the closed issue is keeping this off of Signal's radar, I have cross linked this Issue to the relevant Forum post: https://community.signalusers.org/t/shortcuts-integration/19109/12

**Comment by InnovationBuddy** [comment]
True, this issue is still relevant.

**Comment by ITaluone** [comment]
Ping
