### ISSUE TITLE
sending messages

### ISSUE THREAD

**Issue by mysticalsiren** [signalapp/Signal-iOS#5032]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
recently when i send a message it only shows one check mark, and it doesn’t deliver for a little while. sometimes when i’m receiving messages, i don’t receive them until a long time after the person messaging me send them.

### Steps to reproduce
- send a message
- wait for it to have one check mark
- it doesn’t develop 2 check marks for a while after it was sent for whatever reason 

**Actual result:** i dont receive messages or am able to send them at the time i want to 

**Expected result:** it should show one check mark on your message, and it should not send for a good amount of time, you might not be able to receive messages right away either 

### Screenshots 
i’m on mobile it won’t let me upload screenshots but email me @ devinthemineman@gmail.com for the screenshots

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by IronJunkie** [comment]
Maybe same as  
Messages not delivered #5083
