### ISSUE TITLE
Messages do not get received until I send one

### ISSUE THREAD

**Issue by sunflowerspeed** [signalapp/Signal-iOS#5036]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when sending messages to friends on iOS devices, I immediately receive older messages from them that they sent to me long ago. In other words, this is not an issue with my device's battery optimization settings, but rather, the friend's iOS device as near as I can tell. I am an Android/Windows Desktop user, but I experience this issue exclusively with iOS friends. I cannot reproduce this consistently, but this has happened to me several times in recent days. I have included screenshots from both my Android device (which was on but which I was not using) and my Windows Desktop device (which I was using) to confirm both devices received the late message at the same time. I have also included my friend's iOS debug log.

### Steps to reproduce
- Send a message to an iOS user.
- The iOS user responds to your message. (Verify that they have sent a message using a non-Signal channel; if you experience the bug, you will have no way of knowing they have messaged you.)
- Wait at least 30 minutes (or more).
- Send another message to the same iOS user.

**Actual result:** You immediately receive the "old" message the user meant to send to you earlier.

**Expected result:** You receive the message your friend sent you when they send it to you, rather than right after you send your second message.

### Device info

**Device**: iPhone 7

**iOS version**: 14.4.2 (18D70)

**Signal version:** 5.14.0 (5_14_0_35)

### Link to debug log
Android: https://debuglogs.org/bd2da733befd42e9827965a28df042f2db58d0740faf1d8fdfa262ed4e61def7
Windows Desktop: https://debuglogs.org/d5be2d6cfdbfe98cbb7f8458a1d4af4d464cf44e4bc3c13335231613f211f518.gz
Friend's iOS device: https://debuglogs.org/ebc424305ffc38776df1836ff32c19c0452f54f91f3ce60fe0b0b478c9a47f57.zip

**Comment by diskerror** [comment]
I have had a similar problem with my iPhone 8+ and my wife's Android phone. I can't confirm what finally makes my message show on her phone.

**Comment by diskerror** [comment]
Issue seems to have been fixed.

**Comment by palmat13** [comment]
I’m having this problem.

**Comment by andyggg** [comment]
I'm also experiencing this issue...
