### ISSUE TITLE
Signal crashes on almost any action in a thread

### ISSUE THREAD

**Issue by the-x-at** [signalapp/Signal-iOS#5042]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to developer version 5.15.0.53 Signal crashes on virtually any action I perform in a thread. Signal opens without troubles. It's possible to use the configuration menu or open the camera app. It also displays the list of my recent chats. Also, once I enter a thread, it displays the latest messages, and I can scroll maybe a little bit, but then Signal crashes. It furthermore crashes immediately once I try to enter text, the cursor does not even show up, the crash is followed the moment I tap the text entry field. 

I have a new message and even though I am entering the respective thread, after the crash it is still marked new (red circle with the "1" in it - this could give you a hint before which point in time the crash happens). 

By crash I mean Signal closes without any further warning or message and I have to restart it by tapping on the icon. 

### Steps to reproduce
This works every time I try it at the moment. I have tried easily 15 to 20 times. 

- Open Signal version 5.15.0.53 on my iPhone (see below for details).
- Go to any thread by tapping on it in the menu.
- Scroll up a bit *or* tap to enter a message.
- Immediate application close.

**Actual result:** 
Signal closes without any further messages.

**Expected result:** 
Signal allows me to perform my usual tasks: reading and sending messages.

### Screenshots

N/A

### Device info

**Device**: iPhone 5s

**iOS version**: 12.5.4

**Signal version:** 5.15.0.53

### Link to debug log

https://debuglogs.org/bc73b9aff107f2e37fd423d36691b214cfa08a051177905d307cf98166a44031.zip

The crash log (`Signal-2021-06-24-153930.ips.beta`) will be sent to the developer team after submitting this issue.

**Comment by the-x-at** [comment]
Issue persists in Signal v5.15.0.61.

**Comment by j-hmd** [comment]
Also in version 5.15.0.60

**Comment by Vutshi** [comment]
Now it is not a developer version issue anymore. The released iOS version 5.15.0 is crashing for me this way. 

https://debuglogs.org/305c12bf7d98e661dacfc3ec0a3cf3586ae8116e3dfa2b3d569fcd85801e83cd.zip

**Comment by Vutshi** [comment]
@the-x-at I think you may safely substitute Developer with Release in the title of the issue :)

**Comment by the-x-at** [comment]
Changed title of issue to underline that this is no longer restricted to the developer version according to comments in this thread. 
@Vutshi Could you please record a video showing your crash(es) in the release version and send it to the Signal support team with subject "Signal crashes on almost any action in a thread #5042"? I have done so already. Thanks.

**Comment by lenvm** [comment]
Same issue using:

Device: iPhone 6S
iOS version: 12.4.1
Signal version: 5.15.0.60

**Comment by MoritzLerch** [comment]
Same issue using:

Device: iPhone 6 Plus
iOS version: 12.5.4
Signal version: 5.15.0.60

**Comment by symartin** [comment]
Same issue using:
iPhone: 6
iOS: 12.5.4
Signal version: 5.15.0.60

Debug log:
https://debuglogs.org/8ccd87b8578aeb063402e775849da496c9e018ec06b3e26880a75d30312c1375.zip

I can go to the app settings, some chats are working ok, some not. The ones that doesn’t work seem to be the long ones (with a lot of media). The only difference I can find is that all the ones that don’t work do not have gif)

**Comment by Vutshi** [comment]
Indeed, the old long chats are triggering the problem for me as well.

**Comment by jackydwj** [comment]
Same issue using:

Device: iPhone 7 Plus
iOS version: 12.4
Signal version: 5.15.0.60

**Comment by zutz** [comment]
same issue as well

device: iphone 6
ios: 12.5.4
signal version: 5.15

**Comment by qetza** [comment]
same issue 

device : iPhone 6 
ios : 12.5.4
signal : 5.15.0.60 (latest release)

**Comment by the-x-at** [comment]
Empirically, I can confirm others' opinion that longer threads tend to crash Signal.

**Comment by Vutshi** [comment]
@the-x-at I wonder whether this [commit](https://github.com/signalapp/Signal-iOS/commit/3de83de52a7ace24e64b2ebd789078a2c38fb260) is related to the current issue.

**Comment by cbockermann** [comment]
We have the same issue in our group. 
Interesting fact:
It works on an iPhone 8, but the same thread causes a crash on an iPhone 6. 

Version is 5.15.0.60

**Comment by joAschauer** [comment]
Same problem here after updating to latest release 5.15. However, appears to not happen in every thread.
iPhone 5s, iOS 12.5.2

**Comment by MoritzLerch** [comment]
> 
> 
> @the-x-at I wonder whether this [commit](https://github.com/signalapp/Signal-iOS/commit/3de83de52a7ace24e64b2ebd789078a2c38fb260) is related to the current issue.

Yeah a also wondered.

**Comment by qetza** [comment]
Latest version (5.15.1.3) have fixed the issue for me.

**Comment by the-x-at** [comment]
Thanks, waiting for the patched version to appear on my phone to confirm and to close the issue upon success.

**Comment by MoritzLerch** [comment]
Yes, now I got the update too and it works just perfect again.

**Comment by symartin** [comment]
Effectively, it working for me as well
Big thanks to the developers 😀!

**Comment by the-x-at** [comment]
Confirmed, Signal `5.15.1.4` was rolled out to me today and fixed the issue. I add myself to the list of grateful Signal users who have yet again a properly working version of the messenger.

**Comment by Vutshi** [comment]
@the-x-at I am curious where did you get 5.15.1.4? I've got 5.15.1.3 two days ago and that's it no new updates so far.

**Comment by the-x-at** [comment]
@Vutshi Not sure about the dispatching policy of Signal's testing program. I had to wait till today to get the patched version that fixes our issue #5042. Before I was on the buggy version `5.15.0.61`.
