### ISSUE TITLE
Selfies taken on iPhone SE (1st version) gets incorrectly rotated

### ISSUE THREAD

**Issue by jmn** [signalapp/Signal-iOS#5048]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Selfies taken on iPhone SE (1st version) gets incorrectly rotated

### Steps to reproduce
- Take and send a selfie using iPhone SE (1st version)
- Photo gets wrong rotation

### Device info

**Device**: iPhone SE (1st version)

**iOS version**: 14.6

**Signal version:** 5.14.0.35

**Comment by mro** [comment]
same here but not just selfies but all photos taken from within the signalapp.

set the photo orientation prior capturing it (button touchup-inside action) like so:

```swift
            // https://thetopsites.net/article/52911108.shtml
            photoOutput.connection(with: .video)?.videoOrientation = UIDevice.current.orientation // todo: translate type

            let photoCfg = AVCapturePhotoSettings()
            photoOutput.capturePhoto(with:photoCfg, delegate:self) // -> AVCapturePhotoCaptureDelegate.photoOutput
```

**Comment by mro** [comment]
look at `PhotoCapture.takePhoto(...)`
https://github.com/signalapp/Signal-iOS/blob/5054046d03b485d26262287df71526e186d3b5de/Signal/src/ViewControllers/Photos/PhotoCapture.swift#L445

**Comment by mro** [comment]
https://github.com/signalapp/Signal-iOS/blob/5054046d03b485d26262287df71526e186d3b5de/Signal/src/ViewControllers/Photos/PhotoCapture.swift#L730
uses a property value `captureOrientation` and just logs `UIDevice.current.orientation` – I recommend either using the latter or asserting them being equal.

**Comment by mro** [comment]
maybe related https://github.com/signalapp/Signal-iOS/commit/698d0b062e140bdbeb99581a64963067a17aa1e9
