### ISSUE TITLE
Crash when sending movie to group chat

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-iOS#5049]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One of my contacts reported that Signal crashed when sending a movie. After a new try the movie was sent successfully. I asked for a debug report to be able to report this. She said: media loading takes very long, and then the app closes.

### Steps to reproduce
Try sending a movie to a Signal v2 group.

**Actual result:** Signal crashed.

**Expected result:** Signal should send the movie correctly.

### Device info

**Device**: iPhone (iPhone9,3; D101AP)

**iOS version**: 14.4.2 (18D70)

**Signal version:** 5.13.0

### Link to debug log

https://debuglogs.org/e65f6dbeaf2136736d8eb06c858061c8ecefd65f1fe07dd6cfa39201a084c87f.zip

**Comment by jorge-sepulveda** [comment]
Can the app handle big files such as movies? I'd assume there is a file size limit of a couple hundred megabytes. Maybe try using a video sharing service?

**Comment by janvlug** [comment]
I have not heard anyone referring to this problem for a long time, nor did I experience it myself. So, I close this issue.
