### ISSUE TITLE
Signal call not terminated

### ISSUE THREAD

**Issue by JohnDSmart** [signalapp/Signal-iOS#5054]
Having finished a call last evening we found we were still able to converse without our phones showing that a call was in progress!  Neither of us could find an obvious way to terminate the connection;  my friend even killed the Signal App without any effect on the connection. It was only when I killed Signal on my iPhone that the call was terminated. The only unusual circumstance is that the Oticon ON App was streaming my iPhone sound to my hearing aids which has interfered with other features on my iPhone. What went wrong?
John

**Comment by Guolanlan** [comment]
Me too,
When the call hangs up,  callmanager. Hangup() and the camera is not released. There is a green dot in the status bar
