### ISSUE TITLE
Transferring accounts between IOS 14.7 Devices doesn't work

### ISSUE THREAD

**Issue by cswoodruff** [signalapp/Signal-iOS#5060]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a new iPhone that is on iOS 14.7 and am trying to transfer from an older iPhone that is also on iOS 14.7. I'm able to read the QR code with the old phone. I see the "connecting" animation for a number of seconds and then I get the following message.

> The transfer couldn't complete, please
> ensure your devices are near each other
> and try again

iOS14.7 may have new privacy settings for bluetooth per app. Signal is not listed as an app in these settings that allows bluetooth connectivity. I suspect that this change in iOS privacy settings may be the problem. See the screenshot below.

### Steps to reproduce
- power on 2 iPhones with iOS 14.7
- initiate account setup transfer with new phone
- scan QR code with old registered phone

**Actual result:**
Error message indicating that the transfer couldn't complete.

**Expected result:**
Transfer of data from old phone to new phone.

### Screenshots

![IMG_8980](https://user-images.githubusercontent.com/348526/126836450-d60ffc52-d56a-4d54-8cf8-0412427aee4e.jpg)
![IMG_8981](https://user-images.githubusercontent.com/348526/126837863-93239c8e-b89e-4229-a17b-6303307746e4.PNG)

### Device info

**New Device**: iPhone 12 Pro

**iOS version**: 14.7

**Signal version:** 5.16.1.3

**Old Device**: iPhone X

**iOS version**: 14.7

**Signal version:** 5.16.1.3

### Link to debug log

https://debuglogs.org/843ce71a3720ed3466de7e749357b0a2c0cb26cb1ff8fbda61d1bab8f5172fad.zip

**Comment by garz75** [comment]
Hi. I had the same issue, but with 14.6 : see #5061 May be it is just that you did not permit access to contacts, as I had... The workaround is to allow contact access...

**Comment by cswoodruff** [comment]
I just checked and both phones allow contact access for signal. It must be something else.  Thanks for the suggestion.

**Comment by Dr-Big-Man** [comment]
I would like to add, that I am facing exactly the same issue with my two devices:
- Old: iPhone SE (2. Gen), 128 GB
- New: iPhone 11 Pro Max, 512 GB

When I tried to transfer Signal chat for the first time, the old iPhone was still on iOS 14.6. But same error message is still issued after iOS was bumped to 14.7.

I have carefully checked *everything* as recommended & described at https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages

Signal is on both phones given privilege to access local network and to access contacts. I also tested, if it might help to *disable* access to contacts - but didn't help either. 

This is going on for several days now - I would really love to be able to transfer my signal chats to the new device. 

Honestly I believe that transfer or Signal chats is seriously broken at the moment for iOS devices. I would be grateful, if a solution for this would soon be available. Please let me know, if I should provide any further information. Thanks in advance.

**Comment by g-a-c** [comment]
I see this too.

* Old: iPhone 11 (iOS 14.7, Signal 5.16.1.3)
* New: iPhone 12 Pro (iOS, Signal "unknown" because I can't find a version number without completing the failing transfer, but it's recent as it was only downloaded on Friday. So it's got to be higher than 5.9)

On both devices I have the Local Network permission set, Low Power turned off, and have rebooted both devices. I get as far as scanning the QR code on my old device, then it shows a spinner and fails 3-30 seconds later.

I have a Signal support case open about this (with debug logs attached to the support case) as this is the only app now stopping me from wiping and selling the old handset, but if anyone else has any ideas of things to try then I'm all ears. In the meantime it is at least comforting to know it's not just me...

**Comment by g-a-c** [comment]
Both of my devices are now up to date with iOS 14.7.1 and the behaviour is very slightly different.

This time, after I scan the QR code, the "modal dialog" at the bottom of the screen changed to show a progress bar and then started to swipe right to left several times _as if_ it was going to start transferring. Then it failed anyway with the same error message as above. I will upload the debug logs shortly from this latest attempt.

**Comment by cswoodruff** [comment]
I updated both of my devices to iOS 14.7.1 and retested. I get the exact same behavior as I originally reported.

Old phone: https://debuglogs.org/1f8d3e89a2041857814c99b36918d3a5327353edfecb3e9455ae35a2f6569f4f.zip

I'm not sure how to get a debug log from the new phone before it is setup.

**Comment by g-a-c** [comment]
> I'm not sure how to get a debug log from the new phone before it is setup.

If you tap the screen 8 times while the QR code is displaying, there's a menu with the same options (email, share, save to Files, etc) so you should be able to get them from there

**Comment by No0ne** [comment]
Same on iOS 14.7.1!
Old phone: https://debuglogs.org/9098ba800ac1ace2b02079e0316bedc469a483fe5aab054788669b6035a9bba6.zip
New phone: https://debuglogs.org/2cccb92e7d6e1e01b6db08043038f218c7e4c0be39139045e8a7482d316d04cb.zip

**Comment by Dr-Big-Man** [comment]
Yes, can confirm that it also did not work with my two devices (iPhone SE (2.Gen), 128GB & iPhone 11 Pro Max, 512 GB) after both had been upgraded to iOS 14.7.1.

**Comment by Imperiopolis-Signal** [comment]
This bug is not specific to iOS 14.7, but was an intermittent issue with our QR code scanning logic introduced in Signal’s 5.16 release. It’s fixed in 5.17 which you can install via [TestFlight](https://testflight.apple.com/join/8FHtd1Jq) immediately. It will be available on the AppStore this week.

**Comment by Dr-Big-Man** [comment]
Thanks for the helpful resolution - highly appreciated. I installed 5.17 thru TestFlight and transfer worked immediately.
