### ISSUE TITLE
iOS message transfer fails with no explanation if access to contact is not permitted on old phone

### ISSUE THREAD

**Issue by garz75** [signalapp/Signal-iOS#5061]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS message transfer fails with no explanation (DEVICE_TRANSFER_ERROR_GENERIC) if access to contact is not permitted on old phone
### Steps to reproduce
- Have a working signal installation on the old iPhone XS HID: 11,2  iOS Version: 14.6 (18F72), Signal Version: 5.16.1.3
- make sure the contact access is disabled for signal in Settings
- install signal on new iPhone 12 Pro,  iOS Version: 14.6 , Signal Version: 5.16.1.3
- Start phone number registration, and choose Transfer from iOS device
- scan the QR code on the old iPhone

**Actual result:** After a few seconds showing "Connecting…", the transfer stops and a red message appears on the old phone: The transfer couldn't complete, please ensure your devices are near each other and try again

**Expected result:** The transfer should work, or if access to the contacts is for some reason required, a message should be displayed to the user on failure, inviting her to permit access to contacts in Settings. See below how I found out that the lack of access to contacts made the transfer fail:
After enabling the debug log, and reproducing the issue, I noticed in the logs multiple lines like these:
```
2021/07/23 20:18:07:036  ❤️ [SystemContactsFetcher.swift:425 fetchCNContact(contactId:)]: contact fetch failed; no access.
```
So I suspected an issue with contact access permissions. To allow access to contacts again, I just opened the app on the old phone, and created a new  conversation (top right Pencil icon). I was prompted with the "Allow contact access" iOS dialog, and chose yes.

I retried the Transfer operation, and *voila !* No problem at all, all my message history was successfully moved to the new iPhone. 

I do not remember how the contact access was refused at first. I know that I followed the instructions on the support site and reset Location & Privacy, so at that point, the contact access was definitely not granted anymore...

### Device info

Old device: 

**Device**: iPhone XS HID: 11,2  
**iOS version**: 14.6 (18F72)
**Signal version:** 5.16.1.3

New device: 

**Device**: iPhone 12 Pro  
**iOS version**: 14.6
**Signal version:** 5.16.1.3

### Link to debug log

Note : the logs are from a debug session on the old phone, with the previous version of the app, 5.16.0.45, but the source code of the Transfer service has not changed between the two versions so I presume it does not matter much

https://debuglogs.org/a84e63e65f9581f3e35a93d4ee74a6c70619938928c70b350317173e11a445a0.zip

**Comment by Imperiopolis-Signal** [comment]
This bug doesn’t have anything to do with contact access, but was an intermittent issue with our QR code scanning logic. It’s fixed in 5.17 which you can install via [TestFlight](https://testflight.apple.com/join/8FHtd1Jq) immediately. It will be available on the AppStore this week.
