### ISSUE TITLE
App crashes whenever click to chat

### ISSUE THREAD

**Issue by jerichsov** [signalapp/Signal-iOS#5062]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Whenever i click a chat it crashes and kicks me out off the app, no problem with the main menu(where we see our last chats etc) but as i said when i want to enter a chat it crashes.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

I cant enter a chat with someone app crashes when i click to enter a chat

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhoneSE(1.gen)

**iOS version**: 13.0

**Signal version:** 5.16.1.3

### Link to debug log

https://debuglogs.org/2d5039f92dd1fba1ef35d2b5040bccfc308586bc857a3f459a251bdebd8651d6.zip

**Comment by DocEpsilon** [comment]
Same here, except it only happens with one of my chats. 

Debug log here:

https://debuglogs.org/0ea5786439d9a36f0c575a7f2b2dbcfe62357155e30a45c277617c6078c35c65.zip

**Comment by alieyres** [comment]
Same here. I can’t use the app at all.

**Comment by DocEpsilon** [comment]
Some dev-feedback would be much appreciated. After all this bug severely affects usability of the app and seems to affect quite a few people. 

Regards and thanks in advance
