### ISSUE TITLE
Scrolling in GIF search on Iphone 8 turns everything black

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-iOS#5063]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I scroll during a GIF search everything turns black. See pictures.

### Steps to reproduce
1. Open the GIF menu
2. Scroll
3. Everything is now black.

**Actual result:** Everything turns black

**Expected result:** Everything... doesn't turn black.

### Screenshots
![grafik](https://user-images.githubusercontent.com/12563436/127033486-7e435d01-3a15-49e9-a58b-50259a8d05da.png)

### Device info
Device: Iphone 8
iOS: Latest version
Signal: Latest non-beta version

### Link to debug log
https://debuglogs.org/5755660ccb8332c6133ba75ae2f11ab973c87aac6d2d38d3703facc5a8333d2c.zip

### Related
These are the same issue, but they didn't fill out the form:
https://github.com/signalapp/Signal-iOS/issues/5033
https://github.com/signalapp/Signal-iOS/issues/5001

**Comment by stegmannt** [comment]
I'm experiencing this behaviour as well.

iOS: 14.7.1
Signal: 5.16.1.3

https://debuglogs.org/620cedb8c13ff69948e47e5863fedd90d0932d1f6acd32e9a39b2f78e81ab7da.zip

**Comment by stegmannt** [comment]
Possible workaround:
1. Go to Settings>Accessibility>Motion.
2. Disable "Prefer Cross-Fade Transitions".
3. Gif Search works again as expected.

Reproduce:
1. Enable "Prefer Cross-Fade Transitions" again (Reduce motion must be enabled first).
2. Gif search blacks out and is being overlayed by the black Giphy banner.
