### ISSUE TITLE
Very high background activity with background refresh disabled

### ISSUE THREAD

**Issue by itymarcel** [signalapp/Signal-iOS#5071]
I've noticed Signal doing a lot of background activity even with Background App Refresh for Signal disabled. It is therefore draining my battery quite a bit.

Running latest iOS (14.7), latest Signal. iPhone 12 mini.

![0AA0E2BE-E82A-4DCC-BA0A-941536059BC5](https://user-images.githubusercontent.com/5021903/127652564-96dfa158-6969-4dd8-9108-73dd45671b59.png)

Screenshot attached.

**Comment by itymarcel** [comment]
![IMG_1610](https://user-images.githubusercontent.com/5021903/128320183-5ff71e4a-73ee-4444-bb3f-a5eea558712a.PNG)

**Comment by iodar** [comment]
Hi,
I have the same behaviour on my iPhone XR with iOS 14.7.1 and Signal 5.18.3. I think the background activity is very high. The last couple of days I have noticed that it drains the battery pretty fast.
Yesterday I have disable background activity for Signal but it still shows high background activity.

**Usage the last couple of days**
![7E4ED33A-73FD-499E-9952-E0A12D33EEBE](https://user-images.githubusercontent.com/47027105/131242999-6ea436e0-7991-41d5-9e7d-50a7fe545c17.png)

**Usage this night with background activity disabled**
![2E71B099-A8AF-4286-83F4-D5E16D4FED90](https://user-images.githubusercontent.com/47027105/131243032-30612053-2ce9-4fae-b1b4-a07bb0640cf2.png)

**Comment by iodar** [comment]
Same behaviour after I have background app refresh deactivated. Still running in background.
![image](https://user-images.githubusercontent.com/47027105/131515628-328dda15-1829-49c2-8f12-65d54613a203.png)

**Comment by El-Marti** [comment]
Here my battery usage of my iPad Air 4. Only background usage of Signal while I have disabled notifications ! Please, fix this battery drain !

![C042C0B4-B8F0-46BC-981C-E1610DF2107A](https://user-images.githubusercontent.com/82654494/131898784-b8fb15bb-3a43-4fda-afbb-b0c7aaafd01a.jpeg)

**Comment by u32i64** [comment]
Please see [this post by a Signal iOS developer](https://community.signalusers.org/t/high-background-battery-usage-ios/7711/33) (and the topic itself for more context).

**Comment by etavarez** [comment]
wanted to comment in this issue to note that this appears to be an active issue for me on the latest iOS 14.8.1 and iOS 15.2. Background app activity is unusually high (30min onscreen, yet 1hr & 42mins of activity). Background refresh is disabled.

https://debuglogs.org/e84bfe9fc5d6a024c5ce7dc88e1a8df3d291a581bf2b8403d065cf2e84c1c090.zip

![02DB9DEE-6EDA-432C-8F6F-88248F980CA7](https://user-images.githubusercontent.com/12282651/148715317-cfe5e59e-9daa-4f15-b7c0-febba1c848fd.png)

**Comment by El-Marti** [comment]
It seems to be ok for me.

**Comment by iodar** [comment]
I have just checked my battery usage of Signal. It seems fine now. No more excessive background usage by Signal.

**Comment by iodar** [comment]
This seems to be a bit high. On my iPhone XR / iOS 15.4 / Signal 5.36.7 it shows less power consumption with much higher usage.

## Todays Usage
![image](https://user-images.githubusercontent.com/47027105/167599005-4b13563d-6a68-4fef-acd7-c929f513a919.jpeg)
![image](https://user-images.githubusercontent.com/47027105/167599018-abbd34b4-5f6f-4fca-bff8-1625810bbebc.jpeg)

## Usage In The Last 10 Days
![image](https://user-images.githubusercontent.com/47027105/167599062-a33f2307-7104-48b8-b788-a9a98129024b.jpeg)
![image](https://user-images.githubusercontent.com/47027105/167599081-9351a3c6-2dae-47ac-9cd7-865cc965fe51.jpeg)

**Comment by rghedin** [comment]
Spent hours arguing with Apple support only to find out, days later, that Signal might be the issue. When I open Signal and come back to the Home Screen and/or use other apps, it drains a lot of battery. If I force close Signal after using it, I don't see this issue. (WhatsApp also seems to be draining battery as well, which makes me think it may be something messaging related?)

Running iOS 16.5.1 (c) on iPhone SE (3rd gen).

![IMG_2258](https://github.com/signalapp/Signal-iOS/assets/19216581/af522277-f8b9-4fe9-9343-7b8516e35a02)

**Comment by Miguel-Signal** [comment]
Hi @rghedin,

Could you please email support@signal.org with a link to your debug logs and reference this Github issue?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link.

**Comment by rghedin** [comment]
Done, @Miguel-Signal

**Comment by jeroenhabets** [comment]
Signal background usage is still the main battery drain by far on my phone! Why was this Closed without a fix?
