### ISSUE TITLE
Bug: Transfer of Chat Backup is Broken

### ISSUE THREAD

**Issue by mabbamOG** [signalapp/Signal-iOS#5073]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Transferring Signal Chat History from old iPhone to new iPhone. Latest iOS versions, latest Signal versions. 

### Steps to reproduce
- open Signal on new iPhone, start sync procedure
- use old iPhone to capture QR code with camera
- transfer either does not start, or briefly begins

**Actual result:** get red error message about failure to transfer. Suggestion to put devices closer together. You are unable to transfer the chat history, after many repeated tries (the failures can happen at different stages), the sms verification service times out for 1hour. You will get about 1 try per hour after this, which is insufficient to make it work since it is so buggy.

**Expected result:** first try, transfer begins even when holding iPhones at 5-10 can distance, and completed in a few minutes without fuss.

### Device info

**Device**: iOS 12

**iOS version**: 14.7.1

**Signal version:** 5.16.1

**Comment by mabbamOG** [comment]
Relevant: https://github.com/signalapp/Signal-iOS/issues/5039

**Comment by mabbamOG** [comment]
Relevant: https://www.reddit.com/r/signal/comments/jm2f4r/ios_transferring_from_old_iphone_to_the_new/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I have also found other threads online with people complaining about this problem of faulty chat restore feature. It seems strange that such a critical component is this broken.

**Comment by mabbamOG** [comment]
Further description: if the transfer does indeed by miracle begin, it transfers up to 5-7% on the new phone and then an error message appears. It is frozen the entire time on the old phone, the app needs to be restarted as if it had crashed and takes a long time to load up again.

**Comment by mabbamOG** [comment]
Similar issue: https://github.com/signalapp/Signal-iOS/issues/4556

**Comment by mabbamOG** [comment]
Relevant:

https://amp.reddit.com/r/signal/comments/lnt8gt/signal_app_wont_transfer/

https://www.reddit.com/r/signal/comments/mh2tpt/transferring_signal_to_a_new_phone_seems_to_be/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

https://www.reddit.com/r/signal/comments/jsphs6/data_transfer_new_iphone_fails/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by mabbamOG** [comment]
Update: joining TestFlight fixed this nightmare. Leaving open because far too many people have been having a hard time with the backup/restore functionality of Signal, and it definitely needs some work.

**Comment by boreip** [comment]
Same issue here, but I can't install it via TestFlight since replacing the old app for the beta one will erase all the data...

**Comment by Imperiopolis-Signal** [comment]
As already mentioned in other issues here, this was an intermittent issue with our QR code scanning logic introduced in 5.16. It’s fixed in 5.17 which you can install via TestFlight immediately. Installing the build from TestFlight over your current install does not erase your data. The 5.17 build has also now been approved by Apple and is rolling out to the app store.
