### ISSUE TITLE
Missing status bar when Signal is in dark mode

### ISSUE THREAD

**Issue by MacCZ** [signalapp/Signal-iOS#5074]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Status bar in iOS is not visible when Signal is switched to dark mode.

### Steps to reproduce
- Open Signal
- Use switcher to switch dark mode

**Expected result:**
Bug fix of visibility

### Screenshots
![IMG_0322](https://user-images.githubusercontent.com/50764475/127764907-06dcf8cd-df0f-4e4d-b775-a00e208e1614.jpeg)

The red rectangle is representing hidden status bar. 
![IMG_0321](https://user-images.githubusercontent.com/50764475/127764936-bf390769-90f5-4047-91c4-c5146ce76568.jpeg)

### Device info

**Device**: iPhone 6s

**iOS version**: 15.0 beta 4 

**Signal version:** 5.17.0.48

**Comment by michalnowak061** [comment]
I'm trying to fix this bug

**Comment by jonathancross** [comment]
Bot: do not close this.

**Comment by alexandra-erickson** [comment]
Unable to duplicate issue on iPhone 12 mini.  Area in blue indicates location of camera.

![Untitled](https://user-images.githubusercontent.com/77906328/156891893-98cadb39-aa7f-474a-b376-31a48b3e96b5.jpg)
![Untitled1](https://user-images.githubusercontent.com/77906328/156892129-fc125e84-6ab2-4a9a-81da-3fc17769dfc2.jpg)
t

**Comment by NiklasBr** [comment]
People from Signal should respond first, bot.

**Comment by jonathancross** [comment]
WTF @stale
