### ISSUE TITLE
“Change Photos” option disappears when no photos are selected

### ISSUE THREAD

**Issue by ensellharbrish** [signalapp/Signal-iOS#5080]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The “Change Photos” option in the image picker disappears when no photos are selected.

### Steps to reproduce
- Go to Settings > Signal > Photos > Choose “Selected Photos”
- Tap “Edit Selected Photos”
- Select only one photo and tap “Done”
- Open Signal
- Open a conversation
- Tap the “+” button to bring up the image picker
- Tap the “Change Photos” button
- Deselect the previously selected photo, and tap “Done”
- Tap the “X” button to close the image picker
- Tap the “+” button to bring up the image picker again

**Actual result:**
The “Change Photos” button is now missing

**Expected result:**
The “Change Photos” button should still be available.

### Screenshots

None

### Device info

**Device**: iPhone XS Max

**iOS version**: 14.7

**Signal version:** 5.17.0.48

### Link to debug log

N/A (“Could not find any logs”)

**Comment by jonathancross** [comment]
Bot: do not close this.

**Comment by ensellharbrish** [comment]
Yep, still an issue with the latest version of Signal (5.27.0.116), on iOS 15.3
