### ISSUE TITLE
Cannot link iPad with iPhone

### ISSUE THREAD

**Issue by johannesschrimpf** [signalapp/Signal-iOS#5081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to link my iPad to the account in my phone, the iPad reports the following error message when clicking "Finish linking": `Unsupported version - Update Signal on this device to link it with your phone`. Both devices are quite new and run the latest Signal version.

### Steps to reproduce
- Start Signal on iPad
- Follow instructions to add as new device
- Scan the QR code in iphone app (Link new device)

**Actual result:** I get this message: `Unsupported version - Update Signal on this device to link it with your phone`

**Expected result:** The devices link

### Screenshots

![IMG_0007](https://user-images.githubusercontent.com/24889642/128341920-c902205c-3249-43d7-b6a9-e57beff12efa.PNG)

### Device info

**Device**: iPad 8th generation

**iOS version**: 14.6

**Signal version:** 5.17.1

**Comment by scred47** [comment]
I can reproduce this linking the Ipad running signal messenger 5.17.1 and an Android phone running 5.19.4

**Comment by utility73** [comment]
I can reproduce this with iPad not being able to be linked to iPhone, too. iPadOS/iOS 14.7.1, Signal 5.17.1

**Comment by alexaldrick** [comment]
can reproduce this with iPad not being able to be linked to iPhone, too. iPadOS 14.6,, Signal 5.17.1

**Comment by charlesmchen-signal** [comment]
Thank you for reporting this issue @johannesschrimpf . It has been resolved.  The fix will be in the next release, 5.18.0.

**Comment by johannesschrimpf** [comment]
Thank you @charlesmchen-signal. Do you have an estimate when the next version will be released?
