### ISSUE TITLE
Messages not delivered

### ISSUE THREAD

**Issue by shiningmer** [signalapp/Signal-iOS#5083]
facing issue where most messages not delivered although I get a sent receipt

https://debuglogs.org/2ef53f62d408980d5803eaa4a139098336e20ec1b6ba642c04cb3ff4b3bed556.zip

**Comment by MonicaR4901** [comment]
Have the same issue 

https://debuglogs.org/75fa75b04e888f0e09b27b2a3f1d35db119220b2e87858790fe317a7893dc3dd.zip

**Comment by Ashcarp7** [comment]
I have the same problem as well. 

https://debuglogs.org/15c0b7638546901a9f6150a7775174de2ffbcdce26d921d8071bf530084e367d.zip

**Comment by apope13** [comment]
Same issue since last update. I've sent three emails to support with no result or response. 

https://debuglogs.org/3039b8535287557a664f1092c245bbd957388beb354093892a62b5703f9830f9.zip

**Comment by IronJunkie** [comment]
A couple of my iPhone contact suddenly having this issue as well in last week. Sending from android to iphone in Asia region

my phone shows sent but not received receipt (as msg not received until they manually tap, then msg downloaded & I get receipt) Which is annoying as they are not replying

**Comment by parcelcat** [comment]
Possibly related to #5072. I'm seeing this issue outside of the Asia region as well.
