### ISSUE TITLE
Slow and buggy read receipt

### ISSUE THREAD

**Issue by AntonioALEA1996** [signalapp/Signal-iOS#5085]
### Bug description

When I send a message to somebody the read receipt is delayed for like 5-6 secs. 

Also, when somebody reads my last message the read receipt icon is still there on the previous message, but not for all messages and that is confusing me. Make that on each message is read receipt or just the last message, otherwise it's not practical and visually good.

### Screenshots

![image](https://user-images.githubusercontent.com/88661545/128703504-30c8178e-19ff-4e1d-b4cf-6c7926f9ea29.jpeg)

### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 14.7.1

**Signal version:** 5.17.1.2

**Comment by dagobertdebug** [comment]
Maybe related https://github.com/signalapp/Signal-iOS/issues/5072
