### ISSUE TITLE
Dozens of people NOT RECEIVING messages in large group

### ISSUE THREAD

**Issue by maj-tom** [signalapp/Signal-iOS#5089]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have confirmed this to be an issue with a ~650 member group, but suspect it happens with some people in a smaller group. Messages sent to the group are delivered to ~2/3 of the members but just show as sent to ~1/3 of it and MULTIPLE PEOPLE IN THAT GROUP POST IN THE GROUP SAYING THEY DO NOT SEE ANY MESSAGES, including ones with most recent Signal versions.
I understand the warning that large groups are slow in Signal, but we accept it being slow; the problem is that it's not working slow or not for many people. This is a large group and it's making Signal look bad to many people to whom I have to justify that we should not switch to Telegram given its lack of E2E for groups.

### Steps to reproduce
- have large group with almost everyone using recent Signal messenger
- have people send messages to group

**Actual result:** Some members do not see any messages EVEN WHEN VIEWING THE GROUP AND POSTING IN IT

**Expected result:** All messages show up, at least once the app is open (referring to the known ongoing issue where many people don't receive notifications and messages don't load when app is not in foreground)

### Device info

**Device**: iPhone 12 Pro Max (mine, others in the group vary)

**iOS version**: 14.7.1 (mine, others in the group vary)

**Signal version:** 5.17.1.2 (mine, others in the group vary)

### Link to debug log
I can try to get logs from one of the people complaining about not receiving messages, or just provide their Signal IDs, but also happy to invite one of the Signal staff into the group if that might help.

**Comment by maj-tom** [comment]
Can someone comment? What's the use of having an issues board if Signal devs are ignoring posts here...
Wondering if the problem is because of limits on app background execution (assuming iOS has such limits) and there being too many protocol messages with large groups.

**Comment by xC0dex** [comment]
Hey @maj-tom, 
I'm not in such large groups and therefore cannot comment on the problem. I have to agree with you, the potential of this board is not being used. Almost 800 open tickets that are languishing. I guess the main problem of the tickets are the quality of them. People ignore the template, don't check for duplicates and so on. May that's the reason the developers (or the community) doesn't appreciate the issue board.

I hope that things going to be better in the future, because there are many willing people in the community (like you and me) who try to help the developers to make signal even better.

**Comment by WikiM0tty** [comment]
Same problem here!

Small group of 8 peoples : 1 people have iPhone and 2 others peoples in the group does not receive any message from this person.

Even in 1-to-1 discussion these peoples struggled to receive messages from the iPhone contact.

**Comment by maj-tom** [comment]
Hi, things got significantly worse! Now I am unable to send messages to around half of the members of the group. Sent messages fail with saying the message was "partially sent, tap for details". Tapping to send again fails to send to any more members than was already sent on the first attempt (when I go to view who it was sent to). Some other members have reported the same issue. So things are more severer now!
Log:
https://debuglogs.org/9d929d0a00e76bcd74fd73797a9131c208f2e062d7f88f9bf2284292e70e5e3e.zip

**Comment by maj-tom** [comment]
Here’s one more log. This one is from a person who said she hasn’t been seeing any messages in the group for the past week (though there has been active conversation).
https://debuglogs.org/5716985f002ea29184943241dfb3c654fbec6c3e2573260c6644618ab40e5dff

**Comment by maj-tom** [comment]
Any update? It’s now 3 months since I opened this

**Comment by maj-tom** [comment]
This is still an issue with the latest updates...
