### ISSUE TITLE
Can’t load database 

### ISSUE THREAD

**Issue by Aklinker89** [signalapp/Signal-iOS#5094]
- [ ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
I can’t open the signal application, says can’t load database 
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by scott-lydon** [comment]
There aren't any steps to reproduce.  When I open the signal app, I personally don't get this issue. Can you try to think about things you tried prior to this issue and events that transpired the last times you were using the app?
