### ISSUE TITLE
Messages delay 

### ISSUE THREAD

**Issue by Stavaw** [signalapp/Signal-iOS#5095]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send messages to people it always appears with only one tick, sometimes it takes ten minutes and sometimes it take over 12hours, but never receives my messages straight away. However, other people sending messages to the people I send to have no problems at all

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour) 

no improvements after I run the steps above 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iPhone 12

**iOS version**: 14.7.1

**Signal version:** 5.18.0.64

**Comment by dagobertdebug** [comment]
Maybe related https://github.com/signalapp/Signal-iOS/issues/5072
