### ISSUE TITLE
When the call hangs up, call callmanager. Hangup() and the camera is not released. There is a green dot in the status bar

### ISSUE THREAD

**Issue by Guolanlan** [signalapp/Signal-iOS#5096]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Guolanlan** [comment]
iOS 14.4.1

**Comment by elemanhillary** [comment]
Tested this and its not happening.
Testing App (Simulator)
Calling App(Real Device) iPhone 7 iOS 14.5
