### ISSUE TITLE
GIFs sent from built in Signal funcation do not work

### ISSUE THREAD

**Issue by sephethus** [signalapp/Signal-iOS#5102]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sending GIFs on iOS using the built in functionality within Signal, the gifs do not animate.

### Steps to reproduce
- Tap into a chat/message dialogue with anyone.
- Choose the + sign to add a file/image/gif
- Choose GIF
- Tap any GIF and send it to that person.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Actual result is that the gif does not animate. It is not moving.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Gif moves and animates as it would if I sent it any other way. Other methods such as the GIPHY keyboard work fine, even within Signal.

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 14.7

**Signal version:** 5.18.1.1

### Link to debug log

I cannot find this in settings anywhere, in Signal or in the main iOS settings for Signal.

**Comment by chriskosys** [comment]
Same happens to me. gifs have worked before the recent update. also it seems that this issue only appears on iOS.
instead of an animated gif signal sends a png showing the first pic of the gif. but sometimes it works...
