### ISSUE TITLE
Signal on iOS And IPadOS showing only most recent matched result

### ISSUE THREAD

**Issue by zeus65** [signalapp/Signal-iOS#5107]
Seems the search functionality shows the same results for the latest matched search.

![B66E7C23-D74E-414E-8394-EAB15598F5F4](https://user-images.githubusercontent.com/68876933/130539126-5982d5e8-ddf2-4e9a-9c32-c1628e46dd73.jpeg)
![BA46FFB5-41FD-41D1-8838-8E22315A319C](https://user-images.githubusercontent.com/68876933/130539131-71eebf2a-0cf3-4f5e-a4d9-87360ce2137c.png)

**Comment by saintsim** [comment]
I also see this bug:

- Device: iPhone X
- iOS version: 14.8
- Signal version: 5.20.2.27

**Comment by JensTimmerman** [comment]
seems to be fixed in  5.26.2.0
