### ISSUE TITLE
Unread conversation count won’t clear

### ISSUE THREAD

**Issue by adambier** [signalapp/Signal-iOS#5108]
On iOS, the notifications badge won’t clear even though there appear to be no unread messsged.

![CC67EF88-E968-405F-925E-D0C23D92C184](https://user-images.githubusercontent.com/5492108/130685299-11a239be-a7f4-47cc-800d-49e994ad0699.png)

I’ve tried resetting notifications to no avail.

**Comment by adambier** [comment]
Log: https://debuglogs.org/c0d22751075a5ff8d984c3d02aa4000f0342b354e23401f061b2954d8763f6c6.zip

**Comment by faern** [comment]
I have the same issue. It's been like this for a month or so. I have not been able to clear it.

**Comment by adambier** [comment]
Ooh, I solved it by going into my archived chats, where I found a single “so-and-so is now on Signal” chat. Once I read and re-archived it, the badge cleared.

**Comment by faern** [comment]
Thank you! Worked for me as well.

It does not feel right to count archived chats towards the unread count. Something archived is something one has explicitly said they are not very interested in.
