### ISSUE TITLE
Signal not allowing incoming messaging after deleting the app

### ISSUE THREAD

**Issue by Charlottemastan** [signalapp/Signal-iOS#5111]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by michelle-signal** [comment]
It's unclear what issue you're seeing here. You've left the template blank.

Please create a new issue with the template filled out so we can better understand the incorrect behavior you're seeing. Thanks!
