### ISSUE TITLE
Photo viewer zooming bug

### ISSUE THREAD

**Issue by jvanakker** [signalapp/Signal-iOS#5115]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The photo viewer doesn't zoom in properly, when partly zoomed. It centers on the top of the image, so you can never pinch-and-zoom to the center or bottom of an image without releasing the screen, it will move back to the top of the image.

### Steps to reproduce
- Send or receive an photo in a chat.
- Tap the image to show it full screen in Signals build-in image/photo viewer.
- Partly zoom in on the image, using pinch-and-zoom gesture.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The image will not center properly when partly zoomed, it will center towards the top of the image. At certain zoom levels, you will (frustratingly) never be able to watch lower areas of the photo. At higher zoom levels you will be able to center on the lower areas.

The issue **only** appears in portrait mode, not in landscape mode.

**Expected result:**
When zooming in it should keep centered on the part where you zoom in.

### Device info

**Device**: iPhone 12 mini

**iOS version**: 14.7.1

**Signal version:** 5.18.3.0

**Comment by jkuchar** [comment]
Also affected.

**Comment by AntonioALEA1996** [comment]
I can also confirm the bug. iPhone 11 Pro Max iOS 14.7.1 Latest Signal beta version.

**Comment by jvanakker** [comment]
Update: the latest public iOS App Store version 5.19.0.5036 still shows this bug.

**Comment by ItsPaulM** [comment]
Still getting this bug-

App version 5.19.1.3 (latest beta version)
iPhone 12 Pro, iOS 15 dev build 8

**Comment by edwinlai** [comment]
Bug still repros on 5.20.0.93, iPhone X, iOS 14.8

**Comment by AntonioALEA1996** [comment]
Bug is still present at latest beta 5.21.0.29.

Device:iPhone 11 Pro Max
iOS:15.0

**Comment by jvanakker** [comment]
Also still in App Store version 5.20.2.27.

I can add that the problem **only** occurs on landscape-layout photos on an iPhone 12 mini. Zooming portrait-layout (vertical) photos on a portrait-layout phone, does not give any problems.

Anyway, this problem adds frustration on a daily base in using Signal, and I'm not sure if this Github issue section is actively watched by Signal core developers, so I emailed them directly. I hope we'll get some feedback on the issue.

**Comment by ItsPaulM** [comment]
Bug is still a thing on Testflight version 5.21.2.5

Device: iPhone 12 Pro iOS 15

**Comment by adam8833** [comment]
I just updated to the latest Signal version 5.24.0.46 today and this bug still exists.

Device: iPhone 13 Pro Max
iOS: 15.1

**Comment by mickied** [comment]
This issue still exists in v5.25.0.13 (on iPhone 12 Pro Max iOS 15.1.1). I would like to add that it does affect your ability to view zoomed in images while in landscape as well. When in landscape you can see the bottom of the image (which you can’t do in portrait) but you cannot get fully to the right of the image. You can go past the extents of the left side of the image so that you can see black space between the image and the left side of the screen, but you cannot do the same for the right side of the image. If you try the app will rubber-band you back to the left.

**Comment by ItsPaulM** [comment]
This was fixed for me in 5.26.2.1 (beta, iPhone 12 Pro iOS 15.2)

**Comment by jvanakker** [comment]
Yea in (App Store) version 5.26.2.0 this issue appears to be solved!

I will soon check more thoroughly then close the issue.

Thanks devs

**Comment by jvanakker** [comment]
> Is this still relevant?

Closing the issue was fine. After more testing I can only confirm it now works perfectly as supposed.
