### ISSUE TITLE
No longer connected to service on mobile (iOS) and unable to register once again 

### ISSUE THREAD

**Issue by ahmedatia** [signalapp/Signal-iOS#5122]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On iOS and after the upgrade to the latest version (5.19.0), the app was disconnect from the server i.e. unable to send or receive messages. Yet I'm still able to send and receive messages on desktop (a linked device to the same account).

And now when I try to register once again using the same number, I'm getting this error message "Invalid response from service." 

### Screenshots
![image](https://user-images.githubusercontent.com/670770/132346075-29af566e-66db-40ad-a6b1-1ddae629dbb1.png)

### Device info
**Device**: iPhone 11.2

**iOS version**: 14.7.1

**Signal version:** 5.19.0

### Link to debug log
https://debuglogs.org/238002268b185add4a56b689f4537fe6d0fdfdf4bb07c043afad5726e2186585.zip

**Comment by michelle-signal** [comment]
Thanks for reporting this! This issue should be fixed in 5.19.1. It's currently waiting on app store review but it should be available sometime soon. Hopefully in the next few hours. Please let us know if you're still hitting this issue after updating.

**Comment by ahmedatia** [comment]
@michaelkirk-signal everything is back to normal now. Thank you and the team for addressing this issue.

**Comment by stacey0000** [comment]
I was able to register now as well. However my messaged are not being received by my recipient.

**Comment by michelle-signal** [comment]
Your recipient may need to be on 5.19.1 as well
