### ISSUE TITLE
Keyboard hides Sharing actions panel in conversation

### ISSUE THREAD

**Issue by alexchhll** [signalapp/Signal-iOS#5124]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversation keyboard is hiding sharing actions panel after you long-press a picture.

### Steps to reproduce
- Go into a conversation containing a picture.
- Make the keyboard appear.
- Long-press the picture.
- Tap "Share".

**Actual result:** 
Keyboard is hiding the Sharing actions panel.

**Expected result:** 
Keyboard should disappear after the sharing actions panel is showing.

### Screenshots
<img src="https://user-images.githubusercontent.com/48022351/132421470-4263a69e-e064-4014-a625-2a247aa2d92a.jpeg" width="300">

### Device info
**Device**: iPhone Xs Max

**iOS version**: 14.7.1

**Signal version:** 5.18.3.0

### Link to debug log
None

**Comment by blitz12345678** [comment]
So someone is linked
