### ISSUE TITLE
Emoji keyboard bug

### ISSUE THREAD

**Issue by AntonioALEA1996** [signalapp/Signal-iOS#5126]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I click on message box keyboard opens and then I click on emoji icon on bottom left corner and then the keyboard closes.

### Steps to reproduce
- Click on message box 
- click on emoji icon on the bottom left corner of the keyboard
- keyboard closes

**Actual result:** Keyboard closes without opening emojis

**Expected result:** After I click on emoji icon it should open emojis
### Device info

**Device**: iPhone 11 Pro Max

**iOS version**: 14.7.1

**Signal version:** 5.19.1.2

**Comment by Igor3947** [comment]
I followed these exact instructions and didn't get the same result. I was able to select emojis just fine. I'm also on an iPhone 11, running iOS 14.7.
