### ISSUE TITLE
Timestamps are appearing next to messages instead of below them

### ISSUE THREAD

**Issue by sarayourfriend** [signalapp/Signal-iOS#5130]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Timestamps on iOS after the most recent update are displaying next to messages instead of below them. They're also appearing with some vertical offset. It doesn't look right at all.

### Steps to reproduce
- Open Signal updated to version 5.20.0.93
- Send or receive a message

**Actual result:** Note the timestamp position, off to the side of the message and with some vertical offset so it appears slightly below

**Expected result:** The timestamp should either (a) appear next to the message and be vertically aligned properly or (b) go back to the old style (my own personal preference but I don't make these decisions) to appear below the messages.

### Screenshots
![IMG_048732248ECD-1](https://user-images.githubusercontent.com/24264157/133304024-fe3e159a-8875-4c12-b8bc-4f1268a1b9c9.jpeg)

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 14.7.1

**Signal version:** 5.20.0.93

**Comment by Lundeful** [comment]
Same issue here. iPhone 12 signal version 5.20.1.3.

It's supposedly a feature but the misalignment when it's one line of text is really bad. It's horrible to look at. Works fine with multiple lines in a message.

Hope this is a bug and not a feature

**Comment by sarayourfriend** [comment]
Yes this still happens. I guess maintainers don't want to address this? I'd be happy to take a stab at it but I have pretty minimal iOS dev experience... and frankly I'm not sure what the intended behavior is. If a maintainer is willing to at least address whether this in intentional or if there's a specific way of fixing it mind, I can try to open a PR. Just can't spend time on it without knowing where the maintainers want to go with this.
