### ISSUE TITLE
Audio messages won't play after a couple of days

### ISSUE THREAD

**Issue by nelson332** [signalapp/Signal-iOS#5132]
https://user-images.githubusercontent.com/90830637/133598507-4dc4d65a-e3d5-46a5-93c8-173be88e73fa.mov

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Occasionally voice message file won't play anymore, if some time has passed (a couple of days - a week). Concerns both received and recorded files. Audio message with its information is visible in Signal, but nothing happens when pressed the play button. Audio message won't start to play. 

### Steps to reproduce
- applies to sent or received audio messages
- occasionally, after several days - week, audio message won't play anymore. Can be unlistened audio message or old audio message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Play button does not work and start playing the audio file. In video below, I am pressing the play button several times, but nothing happens. Position in audio file can be adjusted, but audio won't play. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Audio message should start to play. 

https://user-images.githubusercontent.com/90830637/133579564-90aadfc3-3cca-4f83-9208-e103bb74bf98.mov

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 14.7.1

**Signal version:** 5.20.1.3

**Comment by kaktusztea** [comment]
I had this issue once previously at end of June, but I receive voice messages very rarely, so I don't know if this happens every time, or just sometimes.

**Comment by kaktusztea** [comment]
Yes, it is still relevant, just no reaction came to it.

**Comment by kaktusztea** [comment]
Still an issue.
Test audio message to Not to Self.
Can not play it after 2 days.
https://debuglogs.org/ios/5.33.1/ee75f23c01bdf4a7f8e160898a06f39b090f7f49aae3f463b449b80315b10219.zip

**Comment by NiklasBr** [comment]
This is still relevant, bot.

**Comment by NiklasBr** [comment]
Why does the bot not remove the label?

**Comment by kaktusztea** [comment]
Did you test it, @NiklasBr?
I tested it a month before and now the issue was resolved for me.

**Comment by NiklasBr** [comment]
Not really using audio message at the moment...

**Comment by kaktusztea** [comment]
I tested it and the issue disappeared.
@NiklasBr, if you don't see the problem, please don't keep the ticket open.

**Comment by NiklasBr** [comment]
I'm not keeping the ticket open, you have to re-configure the bot to not be so stupid.

**Comment by NiklasBr** [comment]
I hope the bot can stop spamming soon.

**Comment by NiklasBr** [comment]
I hope the bot can stop spamming soon.

**Comment by kaktusztea** [comment]
This issue has been resolved and can be closed.
