### ISSUE TITLE
Search results always show text of first match in a conversation instead of text of match

### ISSUE THREAD

**Issue by JensTimmerman** [signalapp/Signal-iOS#5137]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Search results always show text of first match in a conversation instead of text of match

### Steps to reproduce
- have a chat with a word appearing in it multiple times
- search for the given word

**Actual result:** A list of matches for the word, clicking them brings you to each individual match, BUT the preview text is always the text of the latest match.
**Expected result:** the preview text should show the matched text instead of always showing the same text for each match

### Screenshots
![image](https://user-images.githubusercontent.com/281523/134700476-6848a1df-4a40-47aa-8f02-f1bc15b0f940.png)

### Device info

**Device**: iPhone 12
**iOS version**: 15.0

**Signal version:** 5.20.3

**Comment by pbhuss** [comment]
I have been experiencing this issue on iOS for months now. Reinstalling the app does not fix the issue.

**Comment by Geblaat** [comment]
> Yes, this makes search more or less unusable.

Indeed, but it looks finally fixed to me in 5.26 :tada:

**Comment by JensTimmerman** [comment]
Yep, I can confirm this is fixed in 5.26.2.0

**Comment by JensTimmerman** [comment]
> > Yep, I can confirm this is fixed in 5.26.2.0
> 
> Thank you for your hard work!

sorry, I had not part in the fix, I just confirmed that I no longer have this issue on the latest release.
actual fixing credit goes to @michalnowak061
