### ISSUE TITLE
Signal App issues iOS15

### ISSUE THREAD

**Issue by Nafj79** [signalapp/Signal-iOS#5140]
I am running iOS15 and latest Signal and I have problem with getting Signal to receive messages and calls.

When I have Signal app open everything i working great. If Signal is closed or the app has been in the background for some minutes the problem comes. Nobody can call me or send messages to me. But as soon I open Signal the messages get delivered and push notifications as well. I have running troubleshooting guide and look at all permissions. Everything seems right. 

[695a6b61f2d67c8fd81caa54f706f30a7c15199981b422b7c20c802c9a271311.zip](https://github.com/signalapp/Signal-iOS/files/7231179/695a6b61f2d67c8fd81caa54f706f30a7c15199981b422b7c20c802c9a271311.zip)

**Comment by pawelrosada** [comment]
I have same problem but only when sender have iPhone (iOS 15).
When I recive messages from Android then everything works fine.
I have Signal version 5.21.0.54
I sended logs via e-mail.

**Comment by arminder-code** [comment]
@Nafj79 - exactly the same problem here. Tried to reach out to Signal via Twitter and nothing.

**Comment by andrewdefilippis** [comment]
I noticed a similar issue.  Just after upgrading to IOS 15, the notifications for messages failed to be delivered.  It wasn't until I opened the Signal App on my phone, that I saw notifications delivered.

This is still occurring.  I do not have a problem on my iPad, which is somewhat annoying when I hear the audible notification on it, but not on my phone.  Delivery of notifications appears to only affect my iPhone at this time.

**Comment by Nafj79** [comment]
The problem is still there in 5.21.1

**Comment by ikkerus** [comment]
I can confirm. I have problems sending messages on iPhone 8 with iOS 15 on Version 5.21.1

**Comment by pawelrosada** [comment]
Same here, Version 5.21.1 and problem still occurs

**Comment by Nafj79** [comment]
I have reported this to Signal support but nobody has responded

**Comment by pawelrosada** [comment]
@Nafj79 Yea, I reporter twice, but still didn’t git a answer

**Comment by AntonioALEA1996** [comment]
> @Nafj79 Yea, I reporter twice, but still didn’t git a answer

And nobody will reply to you, trust me…

**Comment by Nafj79** [comment]
Sp what is the point of report it? :-)

**Comment by pawelrosada** [comment]
I just installed update to 5.21.2.4 and test notifications - still not working. Sending from iPhone A to iPhone B cause no notification on iPhone B - to time when I open Signal on iPhone B.
From more than week app is unused becouse of this bug

**Comment by edmond1992** [comment]
Same problem here. Tried reinstall signal, re-register push notifications. No help
iPhone X, iOS15.0.1, Signal 5.21.2.4

**Comment by Offbeatmammal** [comment]
similar experience on iPad (wifi only) - I can send messages, and receive then, but I don't get my side of a conversation from a different device (eg if I reply from my Android phone then my message never appears). "Notes to Self" also don't seem to be syncing to the iPad though they do sync to the macOS client.
