### ISSUE TITLE
Signal down

### ISSUE THREAD

**Issue by smithadishesh** [signalapp/Signal-iOS#5142]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is down. Both calls and messages aren’t working on IOS 14 and 15

### Steps to reproduce
- Open signal
-  send a message or call anyone on signal

**Actual result:** The message doesn’t get delivered and the calls don’t ring. 

**Expected result:** 

### Device info

**Device**: iPhone 12

**iOS version**: 14 and 15

**Signal version:** 5.21

### Link to debug log

https://debuglogs.org/7f2ab85fc1c7d4b0f1e65673a4802cb1d644eabb7c7b19a34ce2d21ba8a62ce7.zip

**Comment by arunmv91** [comment]
Yes. Since last 4 hrs.

**Comment by attilagyorffy** [comment]
Hey there @smithadishesh, I think the people behind Signal are aware of the outage most of the time, before you open an issue next time (that is mostly for tracking bugs as opposed to tracking outages), I' d recommend  checking out their [twitter account](https://twitter.com/signalapp) first. They [have notified](https://twitter.com/signalapp/status/1442354759009247232) users already.

**Comment by smithadishesh** [comment]
Fixed
