### ISSUE TITLE
“invalid response from service”

### ISSUE THREAD

**Issue by kalebmking** [signalapp/Signal-iOS#5143]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I’m re-registering my phone on the same phone, redownloaded app, but it is saying invalid response from service 

### Steps to reproduce
- allow permissions
- accept
- enter phone number

**Actual result:** Menu pops up sayin invalid response from service

**Expected result:** I would be reregistering, number accepted again on same device

### Screenshots
< can’t drag and drop >

### Device info

**Device**: iPhone XR 

**iOS version**: iOS 14.2

**Signal version:** V 5.21.0

**Comment by kalebmking** [comment]
https://debuglogs.org/a2ae2bbd119b094f0b2559ebbfce97105b8d97fa8233273eb5edf8db4511bcc2.zip

**Comment by andrew-hill** [comment]
looks like a duplicate of #5141

**Comment by andrew-hill** [comment]
Still relevant

**Comment by msphn** [comment]
I also have that with iPad OS 15.4.1. unable to set it up using iPhone

**Comment by frankfnord** [comment]
I run into the very same issue. iPad OS 15.4.1 and using iPhone.

**Comment by Kylezo** [comment]
Same issue on iOS iphone 12 mini.

**Comment by msphn** [comment]
This disappeared with latest versions and now everything works for me. I can't reproduce any longer.

**Comment by andrew-hill** [comment]
I'm still seeing this issue on Signal 5.49.0.13 and iPad OS 15.6.1

**Comment by a7maadf** [comment]
> I'm still seeing this issue on Signal 5.49.0.13 and iPad OS 15.6.1

Same here, on iPhone XS

**Comment by EvanHahn-Signal** [comment]
Could you include a screencast and debug logs so we can try to figure out what's wrong here?

**Comment by a7maadf** [comment]
> Could you include a screencast and debug logs so we can try to figure out what's wrong here?

I managed to fix my issue, it was related to my phone being jailbroken. Idk about the others but I guess they are doing a similar thing.
