### ISSUE TITLE
Why Some of chats in chat list have light color on dark mode

### ISSUE THREAD

**Issue by sindiguza** [signalapp/Signal-iOS#5152]
Hi there,

I noticed that some of the chats stay pressed or have light color in chat list, Typically 2,3,4 fist position 
![image](https://user-images.githubusercontent.com/77668527/135626916-b62609dc-a84b-47ec-a238-89ad4c7b966f.jpeg)

Is this a bug of the application or maybe a tracking related thing?

Tested on Iphone 13 Pro Max, Iphone 12 Pro Max IOS 15.0

**Comment by AntonioALEA1996** [comment]
Similar thing happens to me but I have problem with light grey top bar. It’s a bug that needs to be fixed.
