### ISSUE TITLE
Listening to voice message stops newly sent messages from appearing in UI

### ISSUE THREAD

**Issue by Kosmai** [signalapp/Signal-iOS#5160]
While listening to a voice message (audio) that I have received, if I send a message it will not appear until the voice message finishes playing. The message **will** be sent when I press the send button but will not appear in the UI. However, it will appear as the last message sent below the recipients name on the left. I have also noticed that this bug only occurs only the FIRST time you listen to a voice message.

**Comment by the-woocash** [comment]
I do confirm, same problem here.

**Comment by Nexusmeister** [comment]
Can confirm it, I have the same problem. Probably since 2-3 months.

**Comment by Nexusmeister** [comment]
Why is this closed? This is still a problem.
