### ISSUE TITLE
Allow mixed ASCII URLs

### ISSUE THREAD

**Issue by phaabe** [signalapp/Signal-iOS#5164]
**Problem**
URLs like `https://www.wikipediä.org` are not parsed and so not made clickable. Being clickable is essential for URLs :-)

**Reason**
Not being an expert of URLs or Swift, I tried to find something in the code: It seems, the behavior for mixed ASCII URLs is expected which shows this test:
https://github.com/signalapp/Signal-iOS/blob/962369b2676a10da9cf130aa27c87f7c45c325cb/SignalServiceKit/tests/Messages/OWSLinkPreviewTest.swift#L80-L81

I stoped here. Probably this has been done for a reason that I am not aware of. 

I opened this issue, because I think reconsidering mixed ASCII URLs may be right. 

Examples of valid URLs:
* https://wassollichhören.de (https://xn--wassollichhren-5pb.de)
* https://bäcker.com/ (https://xn--bcker-gra.com)

**Comment by Genis-Sage** [comment]
hey @phaabe 
you found the correct part in the code...
this is done to protect against [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack)
see [https://github.com/signalapp/Signal-Android/issues/11636](https://github.com/signalapp/Signal-Android/issues/11636#issuecomment-926102063)

I know, this is a reference to the Android repo of Signal, but I assume, it is done out of the same reason on iOS

apart from that, there is already a iOS issue for that topic:
[link is not created automatically when URL contains special character](https://github.com/signalapp/Signal-iOS/issues/4705)


(I am just a signal user, no dev, but normally, Signal Devs ask, that discussion topics are handled on the [community forum](https://community.signalusers.org/))
