### ISSUE TITLE
In a reply to a message containing a picture, the thumbnail of the picture doesn't appear

### ISSUE THREAD

**Issue by autipial** [signalapp/Signal-iOS#5166]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I am member of a Signal group where people sometimes send pictures.
When another member replies to one of my messages containing a picture, the reply doesn't include the original picture/thumbnail.

![IMG_4532](https://user-images.githubusercontent.com/7460404/136691255-d9a227a7-27d6-446e-87ce-4adcbab17a4c.jpg)

When I click on the default "blue file" symbol shown on my example above, the reference is done with the original message.

Replies to messages containing pictures between other members of the groups (not involving me) seems to work fine: the thumbnail of the original picture is shown in the reply.

I'm also experiencing issue #4684 but it seems to be a different issue. 

### Steps to reproduce
- I send a picture
- A member of the group replies
- On my phone (iPhone 6s Plus, using iOS 14.8), the thumbnail of the picture in my original message doesn't appear in the reply.

**Expected result:** The reply shows the thumbnail of the picture of the original message

### Device info
**Device**: iPhone 6s Plus

**iOS version**: 14.8

**Signal version:** 5.21.4.6

**Comment by fgoyti** [comment]
Can confirm this is still present in 5.26.5.0 with IOS 15.1
