### ISSUE TITLE
Photos taken in landscape mode on Android Galaxy A715G submit vertically

### ISSUE THREAD

**Issue by thetroublemaker** [signalapp/Signal-iOS#5167]
### Bug description
- Photos taken in landscape mode on Android Galaxy A715G submit vertically.

### Steps to reproduce
- Take a photo in landscape view.
- Open the Signal app in Android and select the latest snap from the native photo gallery.
- Submit

**Actual result:**
- Photo comes out vertical instead of horizontal.

**Expected result:**
- Photo should submit horizontally.

### Device info

**Device**: Galaxy A715G

**Android version**: 11
**One UI verions**: 3.1

**Signal version:** 5.24.14

**Comment by tanuva** [comment]
Hi. This is the Signal-iOS project, people here won't be able to help with an Android problem. Please submit the bug report over in [Signal-Android](https://github.com/signalapp/Signal-Android).
