### ISSUE TITLE
Signal ipadOS Support Request 

### ISSUE THREAD

**Issue by Meowtsu** [signalapp/Signal-iOS#5168]
https://debuglogs.org/275dd333c15d852c25eee767cee207946ad9707a8cc0eadb3afff2fb5df542fe.zip

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by gabrc52** [comment]
Your issue is completely empty. Could you please describe the issue you're experiencing?
