### ISSUE TITLE
App iOS crashes when viewing media for user

### ISSUE THREAD

**Issue by yitzifranklin** [signalapp/Signal-iOS#5171]
See debug log. 

https://debuglogs.org/28e2646bff8bc6713760cf9252121ee6e1b356f9c0ffd3a1553fb37281db2824.zip

**Comment by codeindustriesnl** [comment]
So I'm not sure if this is the exact same issue, but I seem to be having the same issue. When I go far back in history, and viewing media, it locks up after a while.

**Comment by codeindustriesnl** [comment]
It is even worse. When I scroll back in (the media) one of my groups, the application completely dies and I'm logged out. !!
