### ISSUE TITLE
Can’t download media on mobile devices. 

### ISSUE THREAD

**Issue by 211217613** [signalapp/Signal-iOS#5175]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
media messages like pictures and audio messages aren’t downloaded on mobile devices. 

### Steps to reproduce
- receive a audio message 
- see a retry and the circular arrow 
- Hit retry over and over again but you still can’t download the message. 

### Device info

**Device**: iPhone 13 mini but also present on iPad mini 5

**iOS version**:  15.0.2

**Signal version:** 5.22.0.38

### Link to debug log

https://debuglogs.org/4274ce4e37e3f91539a67528515c837b7a54c3faf830641e6351786f53ef255e.zip

**Comment by CHRINIMUE** [comment]
Having the same problem 😅 (Probably duplicate of #5177) 
Would be nice, if this will be fixed... so I don't have to resend audios beause the other person is not able to play them....

Maby I can get the debug log. Then I will send it here 👍

**Comment by mitchcapper** [comment]
not stale
