### ISSUE TITLE
Audio messages received while phone was offline not playing

### ISSUE THREAD

**Issue by apphancer** [signalapp/Signal-iOS#5177]
### Bug description
Audio messages received while phone was offline not playing. This is happening in a small group of 3 people, and I haven't been able to test it with single chats.
I experience this a lot while I travel and put my phone in airplane mode when taking flights.

### Steps to reproduce
- Phone is in airplane mode
- Contact sends Audio message (10 seconds message)
- Phone is back online
- Audio message shows with the refresh icon and cannot be downloaded or played

I have tried closing the Signal app and re-opening it and also tried rebooting the phone.
Hours later, when opening Signal on MacOS, the messages are there and can be listened to.

### Device info

**Device**: iPhone 12 Mini
**iOS version**: 15.0.2
**Signal version:** 5.22.0.38

The same issue used to happen on my previous phone:
**Device**:  iPhone 8 Plus
**iOS version**: 15.0.1

**Comment by Sgn-32** [comment]
Can you post a debug log after the issue occurred:

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by mitchcapper** [comment]
not stale
