### ISSUE TITLE
Linking Linux Desktop app via iPad fails

### ISSUE THREAD

**Issue by vangberg** [signalapp/Signal-iOS#5178]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to link Signal Desktop for Linux via Signal on iPad fails. I have been trying for two weeks. Always fails with same error message.

### Steps to reproduce

- I open Signal Desktop, and is asked to link my phone to it.
- I open Signal on my iPad, and go to Linked Device -> Link New Device.
- I scan the QR code from the desktop app.
-  I am asked (on the iPad) if I want to link this new device. I press yes.

**Actual result:** "Linking Device Failed. Invalid response from service."

**Expected result:** The device should be linked.

### Device info
**Device**: iPad Pro (9.7-inch) MLMW2LL/A (2016)

**iOS version**: 14.6

**Signal version:** 5.22.1.3
**Signal version (Desktop/Linux)**: 5.20.0

### Link to debug log
https://debuglogs.org/173426cb53f5dc820ab6c96772ae790f394e740b1cfd061122cae07a80997777.zip

**Comment by steakknife** [comment]
Failed to link macOS desktop app 5.24.0 (production) using iPad iOS app 5.25.0.13. "Invalid response from service" on iPad using the QR code on mac. I suspect an app <==> backend API mismatch or similar bug.

https://debuglogs.org/7a258424a7d2b978dba2c566cbc56b8b5b4e408222b577bf8a36ca96b8127e77.zip
