### ISSUE TITLE
Message Options Disappear.

### ISSUE THREAD

**Issue by emresaracoglu** [signalapp/Signal-iOS#5181]
Hello,

I noticed a bug in the latest version of Signal, which was installed on iOS 12.5.4, while there was no problem before.
When I press and hold on to the status of the message or add an emoticon, the options appear and disappear very quickly.

_The same problem does not exist in version iOS 14.x_

https://user-images.githubusercontent.com/297968/138220221-57d191da-6e0f-4ba1-ab0d-7e4843b46d11.mp4

**Comment by xeU77** [comment]
Thanks, OP. Excellent video demonstrating the bug.  I also get this issue in the last few updates.

**Comment by joAschauer** [comment]
Same bug on my device. Does not occur for the first time tapping on a message after restarting the app.
iPhone 5s 
iOS 12.5.4
Signal Version 5.25.0.13

**Comment by rudewire** [comment]
I also have this problem, and thanks to OP for adding the useful video.  Can a Signal developer please chime in on this?  Will you be fixing, and/or revamping the reactions context menu?

-- iPhone 6, iOS 12.5.5
-- Signal 5.26.5.0

**Comment by 2designaduck** [comment]
I see this same bug semi-regularly on iOS 12.4.1 and Signal 5.26.9.2. Can we please get some attention on this rather annoying issue? It is very reproducible. Once the issue starts, it won't stop, and the only way to add a reaction is to force-quit the app and then go back and try again.

**Comment by rudewire** [comment]
At last, Signal update 5.27.0.116 seems to have fixed this incredibly annoying issue!  The reactions menu is still a full-screen eye sore, but at least it stays in place allowing selections.

iPhone 6, iOS 12.5.5

**Comment by xeU77** [comment]
This is also working well for me after, after a few minutes of testing.  Thanks to any devs who worked on it! I like how it looks.

**Comment by 2designaduck** [comment]
I can confirm that this issue is no longer present in Signal 5.32.0.13 on iOS 12. @stalebot, how would a community member close a ticket? I've looked around …

**Comment by emresaracoglu** [comment]
I can confirm this issue.
