### ISSUE TITLE
Notification badge sometimes missing for new messages

### ISSUE THREAD

**Issue by valynor** [signalapp/Signal-iOS#5184]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Signal 5.23.0 on an iPhone 13 Pro Max, iOS 15.0.2

Sometimes when I get a new Signal message I get a notification sound/banner on my iPhone but when I unlock the device the Signal app icon does not show the notification badge. 
Opening the app **without** going into the chat with the new message and back to the homescreen makes the badge appear. It disappears as expected after reading the message.

I first noticed this last week. It doesn't happen consistently, sometimes the badge shows, sometimes it doesn't.

**Comment by valynor** [comment]
Update 3: On 5.24.046 now, woke up to having a new messsage notification on my iPhone but no badge on the app icon again.

**Comment by kaktusztea** [comment]
I have this issue as well.
iOS 15.1
Signal 5.24.0.46
I try to post a debug log next time when it happens.

**Comment by AlexVonB** [comment]
Hi, it happened multiple times over the last few days, so here is my debug log from that time period: https://debuglogs.org/c97ab0a7df7a73e98939365156b426be87a356b0934cbe598cb0f5e7bda2d309.zip Best

**Comment by valynor** [comment]
I'm on 5.26.3 now and just had another new message with no notification badge on the app icon. 
Are you people on this? Because it's really getting annoying and impacting reliability, too.

**Comment by valynor** [comment]
iOS 15.2, Signal 5.26.5 : still getting new messages with no notification badge on the app icon on my iPhone 13.
This is my last report here, it has been almost 2 months with no fix and no reaction. 
Can't be arsed to report bugs if the Signal devs provide zero feedback on bug reports.
