### ISSUE TITLE
dont know if icons are enabled or disabled

### ISSUE THREAD

**Issue by Mspeg** [signalapp/Signal-iOS#5188]
i dont know if my microphone or phone is muted or not. during conversations im told that others hear noise in the background, when i tap the speaker i can hear through speaker phone, when i tap the icon with the line through the mic, i dont know if its muted or not.. need clarity and help with this, how do i know for sure  I am on Mute? this is on my samsung galaxy s9

**Comment by Sgn-32** [comment]
Hi Mspeg,

this github issue is for Signal on iOS, not Android. You can discus this also on the community forum:

https://community.signalusers.org/t/less-confusing-mute-and-video-buttons-during-calls/14245
