### ISSUE TITLE
Part of long text becomes invisible in compose box

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#5189]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I enter a long text with a Youtube link at the end, the last part of the text becomes invisible. Do one backspace from the end and everything reappears again. In broken state the draft can be lost completely if we leave the app and come back later.

### Steps to reproduce
- Open a conversation
- Enter a long text with a Youtube URL at the end, OR paste the same
- Do NOT send it
- the issue may comes at this moment
- exit the conversation
- leave app, wait a little
- open signal again, the draft will disappear

**Actual result:**
The last part of the text becomes invisible. At this state the draft can be lost if we leave this view and the app.

**Expected result:**
Text should not became invisible

### Screenshots
![bug](https://user-images.githubusercontent.com/8868109/139879387-86ce72c8-5313-4a7a-a3e8-88d1d47cd617.jpg)

### Device info

**Device**: iPhone SE 2020

**iOS version**: 15.0.2

**Signal version:** 5.23.1.1

### Link to debug log
1. Entered the long text with link
https://debuglogs.org/18d8bad3d5e1b041f8b0dd0a3094ab8428451ba02dabbfabb498988ef25fbaac.zip

2. Sent debug log, left Signal for a minute. Go back, the draft disappeared:
https://debuglogs.org/0e476a4f839c19498f96abf4777ffc8a2e655e0f1e6940229217dec9be784df4.zip

**Comment by Qata** [comment]
Same issue

iOS 15.1

iPhone 11 Pro

**Comment by kaktusztea** [comment]
Still an issue on Signal iOS 5.27.0.116 - even though in changelog there was the statement that this was fixed.
iPhone SE 2020, iOS 15.3

### Steps
* I pasted a Youtube link: https://youtu.be/TmlUX4mnNY4
* Then I pasted a dummy, 101 character text 5 times. Left the chat, it remained as a draft.
* Re-entered the chat, edited the draft, scrolled to the end. The issue appeared with the missing text part.

### Debug log
https://debuglogs.org/63ee151d6eb64be42c691f9589138bec389609f3d7689a5b8b0cb59f4d56d0aa.zip

### Screenshot
![image](https://user-images.githubusercontent.com/8868109/151866552-ba546532-4a78-4923-b83d-0d2ba757e982.png)

**Comment by kaktusztea** [comment]
Yes, still relevant.

**Comment by kaktusztea** [comment]
Yes, still an issue.

**Comment by NiklasBr** [comment]
Stale. Please remove label.

**Comment by NiklasBr** [comment]
Still a problem.

**Comment by kaktusztea** [comment]
I can't reproduce the issue in 5.57.0.15, closing, will reopen if occurs again.
