### ISSUE TITLE
Volume button no longer takes photos

### ISSUE THREAD

**Issue by bassben1987** [signalapp/Signal-iOS#5190]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Volume button no longer takes photos within the app
### Steps to reproduce
- Open the app
- Go to a chat
- Press the camera button
- Volume buttons only adjust the device volume no longer take a photo

### Device info

Iphone XS
iOS 15.1
Signal V5.24.0.46

**Comment by PalmTamino** [comment]
Tested, but i dont have this issue on 

iPhone 12 Mini iOS 14.1 Jailbroken(u0)

**Comment by kimar** [comment]
I am able to reproduce the issue on an iPhone 13 Pro with iOS 15.1, however I don’t recall the behavior on prior iOS versions.

Looking at the code at

https://github.com/signalapp/Signal-iOS/blob/1f10b9a4ed2c67c05686e9c81e97990155e97e37/Signal/src/util/VolumeButtons.swift#L163

it appears as if private APIs are being used, if the behavior between iOS versions changed, this might explain why it’s not working anymore.

**Comment by bassben1987** [comment]
Appears to be fixed in v 5.25.0.13

thank you
