### ISSUE TITLE
No notification until app is opened

### ISSUE THREAD

**Issue by tapiab** [signalapp/Signal-iOS#5191]
- [x] I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since iOS 15 update, my wife signal app does not notify of new messages. In my app I can see message distributed only when she opens the app.
After updating iOS 15.1 issue is still here.
Background refresh is active for Signal.

### Steps to reproduce
- Send a message, no notification, not marked as distributed for the sender
- Receiver open the app, message appears and is marked as distributed for the sender

### Device info

**Device**: iPhone XS. I have an iPhone 12, same iOS version and no issue.

**iOS version**: 15.1

**Signal version:** 5.24.0.46, 5.25.0.13

### Link to debug log

https://debuglogs.org/98ca8269d206e2e294528c8748bc5df07beeae088d545be11690daa326a4d6d2.zip

### Edit

After upgrading to 5.25.0.13 there is still an issue with notification

**Comment by edwin0401** [comment]
Same here. I am using xs max with iOS 15.1.

Since iOS 15 update, I have to open the app version 5.25.0 to receive the new message. I also using desktop version but no any issue.

**Comment by flostyen** [comment]
Same here. iPhone SE with iOS 15.1. 

I know more people who have the same issue, for example with iPhone XR with 15.1.

When sending a message, the receiver gets no notification and the on the sender the message is not marked as received to the sender.
When the receiver opens the app, message appears and is marked as distributed for the sender.

**Comment by tonytx05** [comment]
I'm experiencing the same issue. iPhone 11, iOS 15.1, signal version 5.26.0.53. 

Here the messages had been sent to me about 10 minutes before the log was generated:
https://debuglogs.org/c9f7dda045f3acde4992351a11c7daae9672baf428230be3ee4eb0c32b61fec3.zip

For this one the messages were sent about 15 minutes prior to generating the log:
https://debuglogs.org/1e56ea5e7805c5349dbebee57e0143e329ad1b97731243dec068a215d0e5f401.zip

**Comment by tapiab** [comment]
Since it's a duplicate I close the issue.

It's not clear for me that it is a Signal issue, it might be iOS.

For anyone waiting a fix, a workaround is to transfer the whole historic on an other device, delete the app, install it again and transfer back.
