### ISSUE TITLE
SQLite error 14: unable to open database file

### ISSUE THREAD

**Issue by undefzheng** [signalapp/Signal-iOS#5194]
SignalCoreKit/OWSSwiftUtils.swift:46: Fatal error: [GRDBDatabaseStorageAdapter.swift:110 init()]: SQLite error 14: unable to open database file
![iShot2021-11-12 16 45 59](https://user-images.githubusercontent.com/29569848/141437828-3a16aa57-968a-437d-b73f-37900fb9a0d4.png)

version：5.24.0

**Comment by cfcor** [comment]
Have you solve the issue? I have met the same issue.
