### ISSUE TITLE
PIN creation failed

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#5196]
delete

**Comment by thegranddesign** [comment]
Duplicate of #4468 

Please post there with any additional information.

**Comment by thegranddesign** [comment]
Pinging recent committers: @michelle-signal @Imperiopolis-Signal this vital component has apparently been broken for _months._  How has this not been moved to the "critical to fix" list?  This prevents _anyone_ with a PIN block from restoring their account without resetting it.

**Comment by thegranddesign** [comment]
BTW I'm ready, willing, and able to send any additional information necessary to help diagnose the issue if it's not clear from what has already been posted.
