### ISSUE TITLE
Voice mails from an Android device are played twice as fast as usual

### ISSUE THREAD

**Issue by kevinlandsberg** [signalapp/Signal-iOS#5202]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed that a friend of mine using current latest Android version Signal app (5.26.11) who sends me voice messages are played on my iOS device twice as fast than it should, without having any option to decrease the speed or anything.

### Steps to reproduce
- send voice message from latest Signal app version from Android device to an iOS device
- on the iPhone play the voice mail

**Actual result:** Voice message is played twice as fast
**Expected result:** Voice message should have normal speed

### Device info
**Device**: iPhone 11 Pro Max

**iOS version**: 15.1

**Signal version:** 5.25.0.13

**Comment by R3m1n0X** [comment]
Same here!

Version: 5.26.3.3 (via TestFlight)

Voice messages form Android-Devices played at double speed.

**Comment by ryanalytic** [comment]
People I know with iPhones are saying the same thing about messages from my friend's Android device, but not from my Android device, so it's not all Android devices for which this is an issue.

**Comment by R3m1n0X** [comment]
Hmmm .... The devices with 2xVM are:

Samsung S21 Ultra 5G & OnePlus 8 Pro

I think its an iOS Signal issue. Signal users on latest android version can increase the playback speed for VMs iOS users cant.

**Comment by rpaillot** [comment]
I have the same problem. Please fix it urgently !! Is freaking annoying !
It drives me CRAZY!

**Comment by videosoul** [comment]
I am also having this problem. It's been going on for about a month, but I have only just got around to investigating, and found this thread.

I'm using Signal 5.26.5.0 on iOS 15.1 (19B74).

When I am sent audio messages from an Android user, they always, for me, playback double speed. I thought maybe I'd changed this without realising – but there appears to be no option to manually change it back.

VERY annoying!

**Comment by rpaillot** [comment]
it's driving me mad. Still no fix as of today

I'm going to leave signal next week :D

**Comment by tommije** [comment]
Reporting that this is still an active issue. 

Tested with these two devices:

iPhone 13 (iOS 15.1.1)
Signal 5.26.5.0

Samsung Galaxy S21 5G (Android 12
Signal 5.27.13

**Comment by m43stro** [comment]
Samsung S21 5.28.5 as sender
iPhone SE 5.26.7 as receiver 

problem persists

**Comment by kevinlandsberg** [comment]
I bet those Signal developers are all Android users and don't give a **** on iOS 🍡

**Comment by m43stro** [comment]
> I bet those Signal developers are all Android users and don't give a **** on iOS 🍡

Kevin let’s be friendly to each other . They do a great job. Besides this bug it’s running smoothly and secure since years. It’s free, yes I hope a lot people donate. The complexity of Signal is also increased over years. Let’s consider this before we write critic stupid words.

thank you

**Comment by kevinlandsberg** [comment]
> > I bet those Signal developers are all Android users and don't give a **** on iOS 🍡
> 
> Kevin let’s be friendly to each other . They do a great job. Besides this bug it’s running smoothly and secure since years. It’s free, yes I hope a lot people donate. The complexity of Signal is also increased over years. Let’s consider this before we write critic words.
> 
> thank you

Wow someone woke up without any sense of humour...haha man chill your words are true but please consider that there are people outside which have more sense of humour than you ;)

**Comment by rpaillot** [comment]
Guys 

It’s been a month that this bug persists.
Open your god damn code application and fix that childish bug. It won’t take you more than 10 minutes.

It’s so incredibly annoying.
I have donated to signal and this is really starting to annoy me like shit.

R

Envoyé de mon iPhone

**Comment by videosoul** [comment]
> > Besides this bug it’s running smoothly and secure

Well, that's not exactly true. This is one of about four bugs I regularly have with Signal.

**Comment by ulonix** [comment]
I have the same problem. My friend has an Android phone and I'm using an iPhone 6s, running iOS 14.4. Audio messages play faster than normal speed. Only on iOS tho, the desktop apps plays them at normal speed

**Comment by R3m1n0X** [comment]
Hmmm ....

I think this has something to do with compression.

Let's summarize:
- Android -> Android = Works
- iOS -> Android = Works
- Any -> WebApp = Works
- Any -> iOS = Does not work

Obviously, it doesn't seem to matter which Android or iOS version is used, just the version of Signal.

The iOS versions are a bit behind. TestFlight-Version on iOS is also behind. I can only imagine that the voice messages - to save bandwidth - are compressed by the new versions. So, that they are sent in 2x speed and later on the device then decompressed. The iOS version lacks this function.

I'll see if I can find a Signal version on an APK mirror that is a bit older or the same as the current version available for iOS.

**Comment by Mlrt55** [comment]
Same issue as well with a Galaxy S21(exynos) since Android 12 and Signal 5.26.11 to an iOS device and the message is playing at 2x speed on iOS.

**Comment by rpaillot** [comment]
Hi 

Happy new year ! 
2022 and still no fix to that issue.

Are you sleeping guys ? 
Hurry up!!!!!!!!!

Envoyé de mon iPhone

**Comment by iw9ftev0ase** [comment]
This is still an issue on iOS devices! (not on macOS)

**Comment by ulonix** [comment]
I've seen a few updates being released but still this issue is not fixed 😌

**Comment by rpaillot** [comment]
This is non sense….
Fuck signal.
Amateurish team.

Envoyé de mon iPhone

**Comment by SigTestingTeam** [comment]
@Imperiopolis-Signal @michelle-signal 
Some of my friends have this problem too. Are you working on it or when can we expect a fix?

**Comment by rpaillot** [comment]
Apparently nothing planned.
I regularly see new signal iOS versions every week, they fix useless things but stil no voice speed x2 fixes….

I guess that’s how it works with an open source app.

Thank you guys.

**Comment by optimiertes** [comment]
I am using a Galaxy S20 FE 5G and the receiver an iPhone 8 plus. 

The funny thing is when you are saving the Audio message as a file and then sending it through WhatsApp the receiver says it also double speed in WhatsApp!

I guess this points to a deeper issue not caused by Signal.

**Comment by rpaillot** [comment]
Problem unsolved since 22 nov 2021.

Is it serious ?

It sounds like a joke.

**Comment by rpaillot** [comment]
> This is non sense…. Fuck signal. Amateurish team. Envoyé de mon iPhone
> […](#)

You can thumbs down me as much as you want. I see that "Sigtestingteam" down thumbed my post. 
Cool guy, do you mind just ANSWERING us on this issue, just explaining us what's happening?

I get dozens of vocal messages a day on my iPhone using signal (professional voices messages)
I use signal because its supposed to be really private.

I need to listen to vocal messages at a fuck*** double speed.

So, "SigTestingTeam", do you mind do your job ? 
I can open the source code if you want, and fix the issue.

**Comment by SigTestingTeam** [comment]
I gave you a negative thumb because you were insulting to Signal. > That is not ok.
Furthermore, I am a normal user (and beta tester) and therefore the username. I have no function at Signal.

**Comment by ulonix** [comment]
Now I'm listening to the messages properly. Is anyone still having issues?. I have not updated the app tho, don't know if this was fixed at data level or something else.

**Comment by videosoul** [comment]
> 

I’ve just seen your message, so got someone with an Android phone to send me a voice note just now. I was previously experiencing this bug with them. Sure enough, it seems to be fixed!

woohoo, *finally*!

Good stuff. Hopefully it stays fixed!

**Comment by rpaillot** [comment]
solved here too.
Great job guys, finally. I guess shouting a bit isn't useless... .)

**Comment by kevinlandsberg** [comment]
Seems to be solved, thx!

**Comment by ulonix** [comment]
Glad to hear it is working for others too. Thank you Signal team!

**Comment by Mlrt55** [comment]
Works! Thanks!!!!
