### ISSUE TITLE
Messages delay all the time

### ISSUE THREAD

**Issue by aliceyuen** [signalapp/Signal-iOS#5203]
These weeks, I receive messages only when I click on the Signal icon. Then, my phone would get very hot and keep loading many new messages that I should have received in several hours ago.
In this moment, my Signal is hanged again and stop loading new messages. When I click in to a group chat, it will close itself in a very odd way. What should I do to get my Signal to become normal again? 😣😣

**Comment by tonytx05** [comment]
Duplicate of #5148
