### ISSUE TITLE
Draft is persistent

### ISSUE THREAD

**Issue by jbhuff** [signalapp/Signal-iOS#5218]
I typed something in a group. Closed app. Came back and it was a draft. Deleted draft. Closed app. Came back to send a video. Sent video and draft was also sent. 

I explained the error to the group. Closed app. Came back and the draft was there again

https://debuglogs.org/7b9dbe21289ea9dfa1d4763423723df809aa3f10f0a80c2dbae90009ffcff776.zip

**Comment by 161110** [comment]
I can confirm this issue. I have an unsent draft in a group chat that reappears whenever the app (ios) reloads.

**Comment by biblicabeebli** [comment]
I have had this occur, but after a couple of days the draft disappeared.

**Comment by kaktusztea** [comment]
I also have this issue.

I create a draft, leave the conversation, go back, edit the draft, send it.
Leave the app.
Re-open the conversation, draft is seen in the conversation list's preview.
When I enter into the conversation then the scroll position goes to the same position where I first created the draft.
Even if I modify the draft, if I leave to app and come back, the old draft comes back. 

If I kill the app from the background, wait then re-start, then the new draft remains there. 

But if I **delete** the draft and kill the app, then the original, **old** draft comes back after re-start!

https://debuglogs.org/ff8b9349eca506cf3ac0e1cdbbe894526e602f1077375c9619aa4323800f524a.zip

Duplicate: https://github.com/signalapp/Signal-iOS/issues/5110

**Comment by biblicabeebli** [comment]
This issue still occurs for me from time to time, I have not had another weirdly-long-instance where the old message stays around for days and days since posting, instead there will be a 10 minute period where an old message shows up, but it will eventually clear out.

I've stayed up to date on the app the whole time.  I don't know when I last had the issue, but something on the order of 3-4 weeks ago.

**Comment by kaktusztea** [comment]
Yeah, I didn't face the issue either.
@jbhuff: can you close it?
