### ISSUE TITLE
I want to know when the answering party’s audio is advanced

### ISSUE THREAD

**Issue by Guolanlan** [signalapp/Signal-iOS#5224]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Genis-Sage** [comment]
hey @Guolanlan 
I am not sure, what you mean by your title...
but it does not sound like you describe a bug...

as the Signal devs want to keep Github reserved for bugs, the better website for your request would be the [community forum](https://community.signalusers.org/)

**Comment by Guolanlan** [comment]
ture,it's not a bug.is my demand

**Comment by jonathancross** [comment]
Then please close this @Guolanlan  and use the link that  Genis provided.
Thanks.
