### ISSUE TITLE
Supporter badge remains in Signal Desktop after it is disabled from the mobile iOS client

### ISSUE THREAD

**Issue by tedohayer** [signalapp/Signal-iOS#5232]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Supporter badge remains in Signal Desktop after it is disabled from the mobile iOS client.

### Steps to reproduce
- Go to profile -> badges
- untoggle 'display badges on profile'
- badge remains in Signal Desktop and persists across upgrades and restarts

**Actual result:** Badge remains

**Expected result:** Badge is removed

### Device info
**Device**: iPhone X/Macbook Pro

**iOS version**: 15.2
**macOS version**: 12.1
**Signal version:** 5.26.9.2
**Signal Desktop version:** 5.27.0 (production, Intel)

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
