### ISSUE TITLE
Opening push notification while in preview (haptic touch) crashes app

### ISSUE THREAD

**Issue by IneffableKoD** [signalapp/Signal-iOS#5233]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I long press on a conversation ("haptic touch"/ex 3D touch) to preview it, keep it open, and tap on a banner notification that rolls in from Signal, I can see the conversation in the background change to the one I received the notification from, but the preview stays open. When tapping outside of the preview to close it, the app crashes immediately. This happens when opening a banner from dm and group notifications. 

### Steps to reproduce
- Haptic touch on a conversation in conversation overview (preview stays open)
- [New message arrives, banner notification rolls in]
- Tap on banner notification
- Try to close the preview by tapping outside of the preview window

**Actual result:** 

App crashes.

**Expected result:** 

Close preview, go into the conversation that delivered the notification.

### Screenshots

None

### Device info

**Device**: iPhone 13 Pro Max

**iOS version**: iOS 15.1.1

**Signal version:** 5.26.9.2

### Link to debug log
(https://debuglogs.org/f451b8f9f9a38b3106312f86eb72273be14b40c63db322468902b73d757c7202.zip)

_FYI
3. Go to ~~Analytics~~ (is now called Analytics & Improvements on iOS 15) or Diagnostics & Usage._

Crash report sent, subject "iOS Crash Log: Opening push notification while in preview (haptic touch) crashes app"

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
