### ISSUE TITLE
Inbound/outbound calls do not seem to work correctly when there's a second line on the phone

### ISSUE THREAD

**Issue by github1299** [signalapp/Signal-iOS#5234]
Both inbound and outbound calls do not seem to work when there's a second line on the phone (e.g. both a physical SIM and the eSIM are in use) and the device is operating over the mobile network (e.g. not on WiFi)

Disabling the second line resolves the issue.

Messaging and attachment transmission seems unaffected.

**Device**: iPhone 11 Pro

**iOS version**: 14.8.1

**Signal version:** 5.26.9.2

**Comment by BugwebCz** [comment]
I have same issue

**Comment by BugwebCz** [comment]
Yes, if Signal Dev team will ignore this issues, there wouldn't be any update...

**Comment by 211217613** [comment]
https://debuglogs.org/ios/5.35.2/2899e5456cdbd860bb1fef9bf13c340522b19581003a28ca6a64b72e655a4591.zip

**Comment by 211217613** [comment]
Yes this is still relevant.

**Comment by NiklasBr** [comment]
Would be nice with some Signal developers chiming in rather than this spammy bot.

**Comment by 211217613** [comment]
yes still relevant!!


Hi @Imperiopolis-Signal I usually don't at people but I would love to help get this debugged. Just tell me what I need to do besides submit debug logs that no one will see.

Based on my limited RTC knowledge I think it would be safe to assume that this is not an iOS client issue but a calling subsystem problem. I'm wondering if anyone on android is having the same issue.

**Comment by BugwebCz** [comment]
Could you be so kind and check this issue? This ignoring of this bug is really annoying.

**Comment by BugwebCz** [comment]
Still not fixed.

**Comment by 211217613** [comment]
There's a new engineer that is working on the calling library. He might be able to figure this one out.

**Comment by Miguel-Signal** [comment]
We just made some changes that should improve this. It is only available right now in the latest Signal Beta released today (6.11.0.9). We'd appreciate anyone willing to join the beta program, test this out, and provide feedback!

Follow steps from the support page here to join the Signal Beta: https://support.signal.org/hc/articles/360007318471

**Comment by Miguel-Signal** [comment]
If you'd rather not join the beta, this change will be available in the production version soon!

**Comment by 211217613** [comment]
I can try when the release goes to prod.

**Comment by 211217613** [comment]
I updated.

My setup is two sim's. One E-SIM and one Physical SIM. I have one sim for data and the other for everything else.

I've only made one phone call and **did not** experience connection issues or the call dropping.

@Miguel-Signal  can you give a high level description of what the fix was.

**Comment by Miguel-Signal** [comment]
For those interested, you can check out our Github commit for the RingRTC updates that were implemented in v6.11.

https://github.com/signalapp/Signal-iOS/commit/423c1d1a7023223bfcf9edd9a2c9d35ef81893ec

**Comment by Miguel-Signal** [comment]
For those interested, you can check out our Github commit for the RingRTC updates that were implemented in v6.11.

https://github.com/signalapp/Signal-iOS/commit/423c1d1a7023223bfcf9edd9a2c9d35ef81893ec

**Comment by BugwebCz** [comment]
I tested it too with O2 simcard on second line (data source) and it looks fixed.
