### ISSUE TITLE
After Blocking/Unblocking profile picture still not visible

### ISSUE THREAD

**Issue by kaulex99** [signalapp/Signal-iOS#5237]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After blocking and **unblocking** another signal user, I never see his profile picture again.

### Steps to reproduce
To reproduce you will need two iPhones with different signal users.

1. Block the other user from one of the phones with a profile picture
2. Load the user on the other phone -> profile picture disappears
3. Unblock the user on the original phone again
4. Load the user on the other phone -> still no profile picutre

I even tried to reset the profile picutre on the "got blocked" User does not fix the problem either.

**Actual result:** Profile picture not visible

**Expected result:** Profile picture visible

### Device info
**Device**: iPhone 12

**iOS version**: 15.2

**Signal version:** 5.26.9.2

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
