### ISSUE TITLE
Voice Messages Disappear After Recording

### ISSUE THREAD

**Issue by IneffableKoD** [signalapp/Signal-iOS#5247]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When recording a voice message and sliding the button up to lock mode, the message disappears when trying to send it. The app tells me to hold the button to record it. 

### Steps to reproduce
- Press the record button
- Slide up to keep recording
- Record message
- Send message

**Actual result:** 

App tells me to "Press hold and record," message disappears. 

**Expected result:** 

The message is recorded and gets sent. 

### Screenshots

![210119_signal_bug_vn](https://user-images.githubusercontent.com/34814092/150187129-86b6e406-dadf-4bd7-97fb-e0f74e152903.jpg)

### Device info

**Device**: iPhone 13 Pro Max

**iOS version**: iOS 15.1.1

**Signal version:** 5.26.9.2

### Link to debug log

https://debuglogs.org/f81dc0b2264610fd7c880fd062a1528eb70ec7f02f27e3b83dde5d1bd3156280.zip

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
