### ISSUE TITLE
Can't get over 4 weeks for disappearing messages

### ISSUE THREAD

**Issue by rpc31** [signalapp/Signal-iOS#5251]
### Bug description
I don't know if it's a feature or a bug or a limitation, but it's impossible to choose more than 4 weeks for disappearing messages, even when choosing custom time. As some of my friends and peers, I'm attracted in the search feature as it's convenient in many situation ("hey, what was the name of the bar we were at last year?"), while still being assurer that I won't accumulate logs over years. That's why we're a bunch of people wanting to setup the disappearing messages up to 1 year/ 1 year and a half, but it seems impossible, even in custom mode. Is there a way to change that or have it really custom ?

### Steps to reproduce
- chat option / disappearing messages / custom time / can't get past over 4 weeks

**Actual result:** Have to choose between the search feature usability OR long-term privacy. Why not have both ? Is this truly a limitations that devices can't handle ?

**Expected result:** Ability to set custom time to at least a year, or more. So we can use search feature to get information back while still knowing that there is no data retention in the long (1-2 years... is not that long) run.

### Device info
Seems to be limited on every platform

**Comment by fingahoverit** [comment]
This is also relevant to me on ios platform because disk size can't be upgraded and backup features is still not available.
Instead of deleting all messages of a group chat, being able to keep almost a year seems a better compromise.
I'm eager to know if there is any technical or conceptual limitations making it impossible.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by rpc31** [comment]
I don’t understand what’s blocking it. Telegram and other apps have implemented this. No devs will answer nor they accept any contribution…

**Comment by fingahoverit** [comment]
Agreed. Bug still relevant.
I'm lost in sources, if anyone can explain what resources are impacted by this bug.
Actually instead of a new year  unit, if the numbers of weeks can be unlimited it can open the features to years.

**Comment by rpc31** [comment]
As relevant as the signal team is participating to this github

**Comment by fingahoverit** [comment]
Feature still needed as there is no real archive feature for ios (that release disk space).
My request is still open : If someone can explain where is the code, I can try to look if I participate. But without a compiler all I can do is update configurations

**Comment by EvanHahn-Signal** [comment]
We try to use GitHub for bugs, not feature requests. If you'd like to request this feature, [check out the Signal Community Forums](https://community.signalusers.org/c/feature-requests/17).
