### ISSUE TITLE
App Crash when sending pictures

### ISSUE THREAD

**Issue by On3Forc3** [signalapp/Signal-iOS#5254]
Whenever I try to add a picture the app suddenly crashes. Using Iphone Pro Max 13 on IOS 15.3. Signal version 5.27 but it’s been doing the same for the past 2 versions. I can view the camera roll but as soon as I pick a picture it crashes 95% of the time.

**Comment by kaktusztea** [comment]
Hi @On3Forc3: you should add details you found in the bug ticket template when you opened it.
Like debug logs, system version you run, exact steps, etc.
Otherwise devs can not investiage your issue.
