### ISSUE TITLE
Signal Calls route to airplay devices 

### ISSUE THREAD

**Issue by 211217613** [signalapp/Signal-iOS#5255]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have checked how this is implemented with the phone app(regular phone calls) and Facetime calls.

If you are playing audio to an airplay connected speaker and you want to make a call or you receive a call the audio and I think the mic is routed to the airplay devices. This doesn't happen on FaceTime calls or regular phone calls.

### Steps to reproduce
- Play podcast to airplay devices
- answer a phone call
- other people can't hear you and audio is routed to airplay devices

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The audio is routed to the airplay device. The mic input might also be routed to airplay device. I'm not sure about this one

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The audio and mic input should be routed to the speaker and mic on the mobile device

### Device info

**Device**: iPhone 13 mini

**iOS version**: 15.3

**Signal version:** 5.27.0.116

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by 211217613** [comment]
Looks like this was fixed in a recent update. I no longer experience this issue.
