### ISSUE TITLE
Unable to set PIN and delete account.

### ISSUE THREAD

**Issue by minsk21** [signalapp/Signal-iOS#5256]
Subject.

Versions
5.27 (App Store) - 5.28 (TestFlight)

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

P.S. Sorry, it's hard for me to send a report in a strict form from the phone.

Similar bug on android  #11958

**Comment by FuzzyQuills** [comment]
I suspect this was on Signal's side as I contacted support about this myself, apparently an issue was identified and fixed server-side so now pin creation/entry and account deletion should work as expected.

**Comment by minsk21** [comment]
Now these options are working again.
