### ISSUE TITLE
Audio playback is stopped when a picture is sent to same chat

### ISSUE THREAD

**Issue by f0xcb** [signalapp/Signal-iOS#5265]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Audio playback is stopped when a picture is sent to the same chat

### Steps to reproduce
- listen to audio
- send image to the chat

**Actual result:** The playback of the audio is stopped when a picture is sent in parallely to the same chat.

**Expected result:** The playback of the audio is not stopped if a picture is sent in parallely to the same chat.

### Device info
**Device**: iPhone XR

**iOS version**: 15.3.1

**Signal version:** 5.28.0.32

### Link to debug log
no debug log found

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by f0xcb** [comment]
I want to listen to some audios from my friends and want to send pictures parallel to them. it is only a small issue but not blocking.
