### ISSUE TITLE
Audio messages won’t play

### ISSUE THREAD

**Issue by Allegra-H** [signalapp/Signal-iOS#5266]
- [ x] I have searched open and closed issues for duplicates
- [xc ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Audio messages won’t play. They have an unfamiliar symbol in front of them. 
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![173F8024-DDF5-460E-A140-A4AA0F9C6E97](https://user-images.githubusercontent.com/99696477/153965888-22094d01-309c-47b4-a27b-1a8914615dcd.jpeg)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z
Not sure 
**Signal version:** Z.Y

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
