### ISSUE TITLE
iOS client is unable to send or receive any messages after latest update

### ISSUE THREAD

**Issue by MarkEstefanos** [signalapp/Signal-iOS#5267]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As of the most recent Signal iOS update (5.28.0) my Signal iOS client can no longer send or receive messages. I am still able to send and receive messages on the desktop client.

### Steps to reproduce
- Open app
- Attempt to send message
- Watch it fail

**Actual result:** When I send a message it never clears, none of my newer received messages are showing

**Expected result:** I am able to send and receive messages

### Device info

**Device**: iPhone 13 Pro Max

**iOS version**: 15.2.1

**Signal version:** 5.28

### Link to debug log

https://debuglogs.org/ios/5.28.0/dfcb2c076490f7059bcead30ac543bea6a14227cfc038827045f6fe31b71efd4.zip

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
