### ISSUE TITLE
The Japanese character string is cut off.

### ISSUE THREAD

**Issue by oyajun** [signalapp/Signal-iOS#5270]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS version,
Settings> Payment function> Deposit
The Japanese character string “あなたのウォレットアドレス” under the QR code that appears in is cut off like under the image.
“あなたのウォレットアドレス” means "your wallet address".

### Steps to reproduce
- Setting language to Japanese

**Expected result:**  The strings should be displayed full.

### Screenshots

<img width="375" alt="signal-2022-02-11-182450" src="https://user-images.githubusercontent.com/81346541/154492867-e0d976a1-99b4-4b60-b111-8f5ed5fcd0c3.png">

### Device info

**Device**: iPhone 7

**iOS version**: 15.3.1

**Signal version:** 5.29.0 (18)

### Link to debug log

https://debuglogs.org/ios/5.29.0/079fa585e4e922fdf3d11bf7b4ad2e5e31f8f34a3b8bfa9c7a9b0fd40daf0968.zip

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
