### ISSUE TITLE
Get rid of "Read More" truncation.

### ISSUE THREAD

**Issue by StevenBlack** [signalapp/Signal-iOS#5278]
Arising from...

* #4394 

**Summary**: when "Read More" truncates a URL the link doesn't work unless you first expand the Read More.

Why is there "Read More" in the first place?

Get rid of this truncation, it's just annoying.

**Comment by StevenBlack** [comment]
Yes this is still relevant.

Why do we even have "Read More..." 🤔  makes no sense from a usability perspective and plus, there is this bug.

**Comment by EvanHahn-Signal** [comment]
The relevant bug should be fixed by 1689aec8c6897d947f933f158c9d5a129ff9e62c. Please take other feature requests to [the community forums](https://community.signalusers.org/c/feature-requests/17).

Thanks!
