### ISSUE TITLE
Crashes when opening app versions 5.29.0 & 5.30 & 5.31 & 5.33 two iPhones

### ISSUE THREAD

**Issue by pierreboudes** [signalapp/Signal-iOS#5279]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes almost instantly on opening, various versions. Two devices.

### Steps to reproduce
- whatever initial state of the phones (fresh reboot, flight mode)
- launch Signal app
- splash blue screen appears briefly and the app crashes

**Actual result:** the app won't launch
**Expected result:** obviously we hope to see a reactive UI like we had before

### Device info
**Device**: iPhone 8 (model: iPhone10,4), iPhone 7 (model:  iPhone9,3)
**iOS version**: iPhone OS 14.8.1 (18H107), iPhone OS 15.1 (19B74), iPhone OS 15.3.1 (19D52)
**Signal version:** 5.29.0, 5.30.0

Two different telecom operators / numbers.

### Link to debug log
  I email to support@signal.org 4 different crash reports (2 per iPhone). 
  
  Here some exerpts.

```txt
Thread 2 crashed with ARM Thread State (64-bit):
   esr: 0xf2000001  Address size fault
```

```txt
"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6556073580,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.root.default-qos","frames":[{"imageOffset":208492,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":300,"imageIndex":8},{"imageOffset":208492,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":300,"imageIndex":8},{"imageOffset":541660,"symbol":"swift_unexpectedError","symbolLocation":556,"imageIndex":8},{"imageOffset":2298692,"imageIndex":9},{"imageOffset":5383616,"imageIndex":9},{"imageOffset":5384580,"imageIndex":9},{"imageOffset":118468,"symbol":"__54+[VersionMigrations performUpdateCheckWithCompletion:]_block_invoke","symbolLocation":60,"imageIndex":10}
```

```txt
"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6567378604,"matchesCrashFrame":1},"far":{"value":6905358648}},"queue":"com.apple.root.default-qos","frames":[{"imageOffset":208556,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":300,"imageIndex":7},{"imageOffset":208556,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":300,"imageIndex":7},{"imageOffset":541736,"symbol":"swift_unexpectedError","symbolLocation":556,"imageIndex":7},{"imageOffset":2245580,"imageIndex":8},{"imageOffset":5306272,"imageIndex":8},{"imageOffset":5307236,"imageIndex":8},{"imageOffset":127360,"symbol":"__54+[VersionMigrations performUpdateCheckWithCompletion:]_block_invoke","symbolLocation":60,"imageIndex":9
```

```txt
"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6542065260,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.root.default-qos","frames":[{"imageOffset":208492,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":300,"imageIndex":7},{"imageOffset":208492,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":300,"imageIndex":7},{"imageOffset":541660,"symbol":"swift_unexpectedError","symbolLocation":556,"imageIndex":7},{"imageOffset":2245580,"imageIndex":8},{"imageOffset":5306272,"imageIndex":8},{"imageOffset":5307236,"imageIndex":8},{"imageOffset":127360,"symbol":"__54+[VersionMigrations performUpdateCheckWithCompletion:]_block_invoke","symbolLocation":60,"imageIndex":9}
```

**Comment by pierreboudes** [comment]
Same problem occurs with the 5.32 version. I think that Signal cannot process its older datas and crashes somewhere here https://github.com/signalapp/Signal-iOS/blob/master/SignalMessaging/environment/VersionMigrations.m. 

I don't know what can help to figure out the problem besides the crash reports I have already sent last week. I can surely restart from a fresh install and say goodbye to older messages. 

Signal is the only app for which I am giving money (not much, 5€/month to the foundation). I don't rely on it for my communication and currently my only usage is discussing with a couple of friends. 

I think this is important for people to have such services but we need some reliability before disseminating its usage. It it crashes on a basic use case how to convice people and myself to use it more? I am quite sure that our problem (two users on two phones) happens to other persons. I am here to participate so please tell me how I can help improve the reliability of the version migration process. Is there a way I can share faulty data? I am on GNU/Linux, but I can find a Mac OS and a developer account, if necessary.

**Comment by Altonss** [comment]
Several users reported me also that their Signal app crashes at startup (several different iphones!).
This bug is really a problem as users can only access Signal on their desktop if they have linked it.

**Comment by pierreboudes** [comment]
Thanks for your concern!  I have sent my crash reports to support@signal.org with #5279 in subject. I can surely produce more. I am not use to IOS debugging but I think some database extraction would be useful to debug. Do not hesitate to be directive and drive me on the way to produce more logs and share some data if necessary.

**Comment by michelle-signal** [comment]
> Thanks for your concern! I have sent my crash reports to [support@signal.org](mailto:support@signal.org) with #5279 in subject. I can surely produce more. I am not use to IOS debugging but I think some database extraction would be useful to debug. Do not hesitate to be directive and drive me on the way to produce more logs and share some data if necessary.

Sorry for the delay here. I've been traveling a bit the past couple of days. I will reach out to our support team and see if they've received this email. Thanks for the report!

**Comment by Altonss** [comment]
> Sorry for the delay here. I've been traveling a bit the past couple of days.

No worries, take care of yourself! :smiley:

**Comment by Altonss** [comment]
> Several users reported me also that their Signal app crashes at startup (several different iphones!).

One of the users informed me again that she could not open Signal for about 3 hours. (I'm sorry I don't know the version number, nor the iOs version, nor have a debug log)

**Comment by pierreboudes** [comment]
Still stuck after an update : app still crashes on launch with 5.33. I am thinking about doing a fresh install to recover the ability to communicate at the expense of keeping some faulty local data for debugging purpose.

**Comment by Flamity** [comment]
I’ve had this bug happen to me twice now. Currently happening on my iPhone XS, signal version 5.33.1. I refuse to delete the app because I really don’t wanna lose all my chat history. I sent my crash log to the signal support email and they told me it’s been filed but I decided to come here and put a bit more information out on this issue. This bug is a pretty big problem, people can’t use the app entirely. And it’s pretty common.

**Comment by pierreboudes** [comment]
To clarify what happened.
- the 2022-02-25 evening (GMT+1) on one of our iphones Signal started crashing on launch, the 2022-03-26 morning this was also the case for the second iphone. From that day we were unable to use Signal on both phones, because the app was systematically crashing on launch (splash screen). The crash logs that I sent by email (I have plenty others) were pointing at VersionMigrations (performUpdateCheckWithCompletion).  
- I have tried rebooting, updating and filling this bug report. One those 2 phones, Signal-iOS  was still crashing every time we tried to open it. We reinstalled Signal on the first iphone (not mine) after 15 days without any progress and as expected we lose all messages (even recent ones) but the groups were still there and this instance of the app recovered the ability to communicate. 
- Being able to perfom some developer tasks I preserved my crashing Signal for further investigation. I was hopping to preserve and share some faulty data to help debug. Living outside the vivarium (aka FB etc.) isn't an easy life and I am used to loose some opportunities to communicate (like I did during that month) with the hope of doing something useful for others. After one month without progress I reinstalled the app. I won't use it more than before and I know now that I can loose all my messages. I will still fund Signal but I am a bit sad that such problems may occur again at large scale and I lost one bit of confidence.

**Comment by Mad-at** [comment]
I would like to support this, I have the same issue and have sent my crash reports to the developers. I have been without signal now since january, because I can't afford to loose my conversations.

**Comment by Mad-at** [comment]
I have to stress that this is not yet fixed in the current version 5.37.1. Please please stop adding useless features or enhancing performance when there are bugs out there that render Signal unusable for some users. This is unbelievable, where is your work ethics?

**Comment by DiagonalArg** [comment]
"No One Assigned"?  Why don't we have any activity on this?  Please, focus on the key issues!

**Comment by Mad-at** [comment]
Yesterday a new version (Version 5.37.2) was released which supposedly fixes the crash issue, but not for me.

**Comment by KatieG285** [comment]
I’m having the same issue. I’ve deleted and reinstalled 4 different times since January. I don’t want to lose my data yet again. Anyone ever get a “Fix” for this?? Thank You

**Comment by sorcerix** [comment]
still facing this issue on my iphone 7, and have been since march.

**Comment by Mad-at** [comment]
Problem persists wit 5.40. but hey, the reminder if your sponsoring subscription fails is now fixed and videocalls use less bandwith
