### ISSUE TITLE
no notifications anymore

### ISSUE THREAD

**Issue by jovh** [signalapp/Signal-iOS#5280]
hi - me and mu friend aren t receiving no more notifications when a message comes in... we need to open the app to know whether there are new messages

**Comment by theschweitz** [comment]
any update on this? Experiencing the same issue. they pushed an update that still hasn't fixed it.

**Comment by jovh** [comment]
i ve sent an email on support.signal.com - it seems that notifications work with wifi but not with 4g - even if data is enabled in the settings

**Comment by T4cC0re** [comment]
Seems to be a dupe of #5072
