### ISSUE TITLE
No notification of new messages

### ISSUE THREAD

**Issue by Diane-87** [signalapp/Signal-iOS#5281]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

###No notification of new messages coming through

**Comment by theschweitz** [comment]
any update on this? Experiencing the same issue. they pushed an update that still hasn't fixed it.

**Comment by AlexGhiondea** [comment]
Still having this issue.

**Comment by T4cC0re** [comment]
Seems to be a dupe of #5072

**Comment by Cerberus0** [comment]
Perhaps it would be better to allow the stale bot to close this issue as a duplicate of #5072, unless the original reporter (@Diane-87) can demonstrate how their issue is uniquely different from the one reported there.
