### ISSUE TITLE
Missing Signal Contacts in sharing sheet

### ISSUE THREAD

**Issue by Jackalkk** [signalapp/Signal-iOS#5282]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am missing Signal contacts in sharing sheet. 

### Steps to reproduce
- select any item you want to share
- touch share button
- There is no Signal contact on the quick contact selection for sharing

**Actual result:** no signal contacts on sharing sheet are visible (i.e. the buggy behaviour)

**Expected result:** Contacts with Signal icon should be visible on the share sheet 

### Device info

**Device**: iPhone 13 Pro Max

**iOS version**: 15.3.1 and 15.4 beta 5 (I have upgrade to check)

**Signal version:** 5.30.0.11

### Link to debug log

https://debuglogs.org/ios/5.30.0/e7a5927a542ccf55d6f746dadd9f5199481818f3214a50bd409a9cae5529ec07.zip

**Comment by Jackalkk** [comment]
Signal Contacts on sharing sheet are back with 5.31.0.9 on iOS 15.4 beta 5.

**Comment by Mark-arsenal** [comment]
> Signal Contacts on sharing sheet are back with 5.31.0.9 on iOS 15.4 beta 5.

Are you sure as n on both versions And mine ain’t back

**Comment by Jackalkk** [comment]
I am sure. This looks even more weird now. Are only we affected with this issue?

**Comment by Mark-arsenal** [comment]
> I am sure. This looks even more weird now. Are only we affected with this issue?
> 
> I have just updated to 5.31.0.12 and still working fine.

strange pal its definitely a signal bug as ive reset my iPhone 13 pro and set up as new device and re installed signal that version and still no joy

**Comment by jarslemonade** [comment]
Not working for me either on 5.31.0.14, the only Signal contacts that show in the share sheet are a couple of group chats 

No individual contacts are showing

**Comment by Jackalkk** [comment]
I am currently on 5.32.0.11 and iOS 15.4 RC. Everything looks fine but I know just realized that I am using Signal for group chats only.

**Comment by Mark-arsenal** [comment]
> I am currently on 5.32.0.11 and iOS 15.4 RC. Everything looks fine but I know just realized that I am using Signal for group chats only.

Is There such a setting group chats only ? As I’ve just looked at my iOS settings within app and couldn’t see such setting ?? Can u share a screenshot to show This ??

**Comment by jarslemonade** [comment]
There isn’t such a setting, the share sheet should be populated with both group chats and contacts you frequently message. 

At the moment it’s only showing groups, prior to that it was broken completely a couple of updates ago

**Comment by Mark-arsenal** [comment]
> There isn’t such a setting, the share sheet should be populated with both group chats and contacts you frequently message.
> 
> At the moment it’s only showing groups, prior to that it was broken completely a couple of updates ago

That’s what I thought as there is only one setting within app regardless wether it’s groups or individual chats , and correct the issue started around a couple of updates ago so therefore it must be a signal issue that has been raised by other users also but hasn’t Been fixed by the app developers despite new app updates being released

**Comment by tclementdev** [comment]
Same here. Broke fairly recently. I now only see conversations from Apple's Messages in the share sheet, Signal conversations are nowhere to be seen. I also slightly remember that there used to be a setting in the app to allow conversations to appear in the share sheet but I couldn't find it anymore, seems to be gone as well. I'm really hoping it's coming back soon, the flow of sharing something with a Signal contact is fairly annoying now.

**Comment by Mark-arsenal** [comment]
> Same here. Broke fairly recently. I now only see conversations from Apple's Messages in the share sheet, Signal conversations are nowhere to be seen. I also slightly remember that there used to be a setting in the app to allow conversations to appear in the share sheet but I can't find it anymore, seems to be gone as well. I'm really hoping it's coming back soon, the flow for sharing something with a Signal contact is fairly annoying now.

![86087925-0C42-40B1-BB78-580DDE08B729](https://user-images.githubusercontent.com/100871698/157935338-240932c8-e405-4a71-94c6-9a790671fa0a.jpeg)


It’s That the setting you was on bout within the app ?? As mine has Always been on i presume that’s what you was on about and still no share sheet contacts

**Comment by tclementdev** [comment]
Thank you @Mark-arsenal, it is indeed the setting (I was looking for it in the wrong place). It is enabled for me too although the feature is now clearly broken.

**Comment by Mark-arsenal** [comment]
> Thank you @Mark-arsenal, it is indeed the setting (I was looking for it in the wrong place). It is enabled for me too although the feature is now clearly broken.

Exactly my friends who use signal on iOS Also having the same issues as stated this stopped working around 2/3 updates ago , have sent numerous emails to signal support and even reached out on twitter and got no response form either

**Comment by kputnam** [comment]
Confirming this issue is happening to me also. iOS 15.3.1, Signal 5.33.0. The "share contacts with iOS" option is enabled.

**Comment by LeoniePhiline** [comment]
Broke for me too, a few days ago.

**Comment by Mark-arsenal** [comment]
> Confirming this issue is happening to me also. iOS 15.3.1, Signal 5.33.0. The "share contacts with iOS" option is enabled.

its now working for me on beta version 5.43.0

**Comment by Mark-arsenal** [comment]
its now working for me on beta version 5.43.0

**Comment by Mark-arsenal** [comment]
> Broke for me too, a few days ago.
> 
> Signal 5.32.0.13

its now working for me on beta version 5.43.0

**Comment by jarslemonade** [comment]
Can confirm it works in 5.34.0 beta

**Comment by Mark-arsenal** [comment]
> Can confirm it works in 5.34.0 beta

Yeah as works for me as well on that beta version
