### ISSUE TITLE
Not receiving message notifications on iPhone

### ISSUE THREAD

**Issue by theschweitz** [signalapp/Signal-iOS#5283]
Signal on iOS no longer receiving notifications. User must open app to see messages.

**Comment by kylebeach91** [comment]
I haven’t been getting notifications for about a week now either. Any updates on this?

**Comment by theschweitz** [comment]
Still no updates. There was an update issued yesterday - still did not fix the issue.

**Comment by Harschism** [comment]
This issue still hasn't been resolved.

**Comment by eeckert0** [comment]
Still not resolved. I spoke to apple support and they walked me through every trouble shooting step to no avail. Said to contact signal

**Comment by ywoly** [comment]
I have the same issue for a few weeks (I would say since December 2021), never happened before.

I am running iOS 15 (always the latest version available), and my current version of Signal is 5.33.0.25 (latest available too).

**Comment by Ashleysimpson93** [comment]
I think this has now been resolved. The most recent update seems to have fixed it for me.

**Comment by ywoly** [comment]
After a new test, the issue is not solved for me with the most recent version available on the App Store.

**Comment by theschweitz** [comment]
The most recent update did fix this for me.
