### ISSUE TITLE
signal proxy doesn't work on iOS

### ISSUE THREAD

**Issue by idavydov** [signalapp/Signal-iOS#5284]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Clicking on signal proxy link in iOS doesn't enable it.

### Steps to reproduce
- send a proxy link to an iOS user
- iOS user clicks on a signal proxy link

**Actual result:** Web browser opens

**Expected result:** Client recognizes a proxy

P.S. It is quite likely that soon many more iOS users from Western Europe will be unable to connect to signal servers.
Related to #4926

**Comment by derekmorr** [comment]
Agreed. This should be reopened.

**Comment by fred-dev** [comment]
Yes, I have also found this. I just made a proxy to share and it works fine on android. On the current build on iOS there is no effect. There is also no option for this in any manual settings. If it does not work please tell https://github.com/meredith-signal to amend the https://signal.org/blog/run-a-proxy/ page to reflect this as well as https://support.signal.org/hc/en-us/articles/360056052052-Proxy-Support page.

**Comment by ChrisRomp** [comment]
Definitely an issue on iOS.

**Comment by u32i64** [comment]
Signal developers implemented [support for the Signal TLS Proxy](https://community.signalusers.org/t/47373/9) in Signal iOS version 5.55.0.12 and newer (currently only in beta). If you'd like to join the beta, please see [this support article](https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta).
