### ISSUE TITLE
App Freezed when Switching to Sticker Selection in Floating Keyboard in iPadOS

### ISSUE THREAD

**Issue by yur1xpp** [signalapp/Signal-iOS#5285]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Switching to sticker selection from normal keyboard that's in floating mode freezed the app, and a manual force kill is needed to do anything with the app. For the love of god could someone please fix this? It's very frustrating that the app freezes every time.

### Steps to reproduce
 - Activate floating keyboard in iPadOS (https://support.apple.com/en-us/HT210758)
- Make sure it's on normal keyboard input mode (language/alphabet)
- Tap the sticker button on the text input field

**Actual result:** The app freezed indefinitely

**Expected result:** Switch to sticker keyboard

### Screenshots
https://user-images.githubusercontent.com/34767893/121205379-32f75e80-c8aa-11eb-97f2-43063fd806da.mov
As you can see from the video, the sticker stop animating (indicating the app freezed - the video is still playing) right after tapped the sticker button, and it's stuck in greyed state.

### Device info

**Device**: iPad Pro 4th Gen

**iOS version**: 15.3

**Signal version:** 5.30

**Comment by yur1xpp** [comment]
The 9 months old issue I opened was closed without any fix ugh

https://github.com/signalapp/Signal-iOS/issues/5029

**Comment by NiklasBr** [comment]
The bot incorrectly closed the previous issue. Do not close this one.

**Comment by yur1xpp** [comment]
Do not close.

**Comment by yur1xpp** [comment]
Don't you dare bot, please remove this useless bot. Or at least respect your users taking time reporting bug by not automatically closing them.

**Comment by NiklasBr** [comment]
Please bot, stop trying to close this issue.

**Comment by yur1xpp** [comment]
Don't you fucking dare bot

**Comment by yur1xpp** [comment]
It's not solved, please reopen this issue

**Comment by Miguel-Signal** [comment]
Can anyone still experiencing this issue update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue? Then, if the issue is still happening, could you provide new debug logs from this new version?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link, then open this email, long-press and choose paste to paste the link.

**Comment by yur1xpp** [comment]
@Miguel-Signal  thanks for your attention in this, I've been waiting for someone from signal to notice this for so long. 

I'm still experiencing them in the latest version, gladly provide the latest logs here:

https://debuglogs.org/ios/6.26.0/b1f31195b162d862bd34acbdb9692e84da150cd3b96baf14039312bd4f02cc3f.zip

**Comment by Miguel-Signal** [comment]
Thanks for responding with the requested info.

I've gone ahead and filed this bug with our engineering team. While our engineers will be working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug included in the release notes for future versions of Signal.

Thanks again for your help in reporting this.

**Comment by yur1xpp** [comment]
Thanks Miguel! Perhaps we should keep this issue open for references?
