### ISSUE TITLE
Picture sometimes disappears and replaced by a grey picture

### ISSUE THREAD

**Issue by El-Marti** [signalapp/Signal-iOS#5289]
Sometimes, when I send a picture, it is replaced by a grey picture, not immediately. Impossible to see it correctly and this issue is definitive but it does not concerns the others. Seems to concern only the sender....

No way to reproduce it...  It's random and happens on almost 1 time over 20.

![signal](https://user-images.githubusercontent.com/82654494/157835449-76431c96-3266-4495-8e17-1c5462e5e5b1.jpg)

Device info
Device: iPhone 13
iOS version: 15.4 
Signal version: last seen on 5.27.x (and since at least 1 year)

**Comment by dr0pd34d** [comment]
I had the same problem today and requested the picture from the sender, it appeared to be a GIF file. Based on the responses of the group, other people could see it.

**Device info**
Device: iPhone 12 Pro
iOS version: 15.4
Signal version: 5.32.0.13

![signal-grey-picture](https://user-images.githubusercontent.com/26057594/161048998-a6dfa847-9b9c-45ae-927e-714726ec3c20.jpg)

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by NiklasBr** [comment]
Happens occasionally still.

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by EvanHahn-Signal** [comment]
If anyone can find a way to reproduce this, we'll take a look. Otherwise, it's very hard for us to fix.

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by NiklasBr** [comment]
This is still relevant.
