### ISSUE TITLE
[iPadOS] Deleting the link preview when sharing a link from another app does not actually delete the preview

### ISSUE THREAD

**Issue by YX42** [signalapp/Signal-iOS#5290]
### Bug description
When you share a link and remove the preview in the share window, in the chat it will still show the preview nonetheless.

### Steps to reproduce
- Share link to Signal chat
- Remove link preview
- Send message
- Open the chat in Signal

**Actual result:**
The preview is still there despite removing it in the share window

**Expected result:**
No link preview

### Device info

**Device**: iPad

**iOS version**: 15.3.1

**Signal version:** 5.31.0.14

**Comment by YX42** [comment]
Yes, still happening.

**Comment by max-signal** [comment]
@YX42 this should be fixed by 66a2638edd72f01bb9476374d40b54a54f1ef9e6, which is available in v5.42. Can you try installing that version from the App Store and let me know if you’re still seeing this issue?

**Comment by YX42** [comment]
@max-signal Issue has been fixed, thank you!
