### ISSUE TITLE
App crashes when send a image.

### ISSUE THREAD

**Issue by tanishq-singh-2301** [signalapp/Signal-iOS#5291]
every time i try to send an image in the chat with the person the app crashes, I'm using Iphon6 with fingerprint enabled privacy.

**Comment by cakaltm** [comment]
Same here. 

iPhone 6Plus
iOS 12.5.5

When in Signal I add an image to a message or new chat box. The image displays for a second, then Signal shuts down. I've rebooted  and toggled photo permissions.
