### ISSUE TITLE
UI issue, grey area

### ISSUE THREAD

**Issue by mthld** [signalapp/Signal-iOS#5298]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since updating to v5.33.0.25 a grey rectangle appeared near the bottom of the screen.

### Steps to reproduce
- Update Signal
- Reopen the app

**Actual result:** see the annoying grey rectangle.

**Expected result:** there is no grey rectangle near the bottom screen.

### Screenshots

![image](https://user-images.githubusercontent.com/41020854/159925608-f6d204ca-004d-407d-9c6a-1fd2b147d888.jpeg)

### Device info

**Device**: iPhone SE 2nd gen

**iOS version**: 15.4 (latest stable)

**Signal version:** 5.33.0.25

**Comment by app-arianamini** [comment]
Same IPhone 13 Pro, iOS 15.4

**Comment by app-arianamini** [comment]
Is fixed now for me 🤔 , do signal have over the air update?

**Comment by mthld** [comment]
> do signal have over the air update?

No.

Not fixed here, tried restarting my phone but still happening.

**Comment by myrdn** [comment]
Happening only sometimes on Iphone SE 2nd Gen.

**Comment by app-arianamini** [comment]
@myrdn yes, is back for me again.

**Comment by app-arianamini** [comment]
🤌 I found the error, it happens when the OS theme is different than the signal app.

For me, I am using dynamic OS theme but my signal app is just Dark.

**Comment by mthld** [comment]
> 🤌 I found the error, it happens when the OS theme is different than the signal app.
> 
> 
> 
> For me, I am using dynamic OS theme but my signal app is just Dark.  

Not related, both app & iOS are using the "auto" setting where it switches light from dark theme. So the Signal theme always match iOS.

**Comment by u32i64** [comment]
I haven't experienced this issue myself, but it looks like there is a potential fix, https://github.com/signalapp/Signal-iOS/commit/27a2d97d3a1d47061fe90b5f42ed94ca48765833, in both:
- `5.34.0.11-beta`, available now via TestFlight (see [this support article](https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta#join) if you'd like to join the beta);
- `5.33.1`, which presumably will appear in the App Store soon.

**Comment by mthld** [comment]
Fixed in v5.33.1.0.
