### ISSUE TITLE
Cant get a message for confirmation of registration. Does signal support iphone 10?

### ISSUE THREAD

**Issue by survivor2022all** [signalapp/Signal-iOS#5301]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Doge7734** [comment]
Not a Signal developer, but is there any chance that your country or ISP could be blocking Signal? You can also ring your cell provider to see if there is anything wrong on their end. As far as I know, Signal should support iPhone 10.

If a Signal devleoper replies, take what they say with more weight as I am just a user.
