### ISSUE TITLE
Recurring requests for Captcha verification 

### ISSUE THREAD

**Issue by free-birdie** [signalapp/Signal-iOS#5303]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is constantly asking for Captcha verification

### Steps to reproduce
- happens when I try to type a message. Not every time, but dozens of times per day
- I have disabled vpn
- I have deleted and reinstalled the app

**Actual result:** No change. Still getting Captcha verification requests

**Expected result:** Signal to operate normally without Captcha interventions

### Screenshots
![23F0EC48-05D5-49B2-A6EC-C47947CC42C2](https://user-images.githubusercontent.com/102745278/161089975-729c8670-a6d5-4f04-8800-52b3d6371572.jpeg)

### Device info

**Device**: iPhone 12

**iOS version**: 15.3.1

**Signal version:** 5.33.1.0

**Comment by free-birdie** [comment]
https://debuglogs.org/ios/5.33.1/6bc6260842e9e2eab096ad52f8d3bba2bf9d64f463eee59c1e25849180cd0983.zip

**Comment by free-birdie** [comment]
Sent from Proton Mail for iOS
This is no longer an issue. You can close the ticket. Thanks

**Comment by drewmccal** [comment]
This is still an issue on Mulvad VPN

**Comment by drewmccal** [comment]
This is still an issue on Mulvad VPN

**Comment by drewmccal** [comment]
Please re-open this issue

**Comment by colingibb** [comment]
What was the fix for this?  I cannot get past this prompt to complete the Captcha either on Signal.
