### ISSUE TITLE
Can't link iphone witb ipad 

### ISSUE THREAD

**Issue by tarafdar** [signalapp/Signal-iOS#5305]
When trying to link after taking picture of qr code on iPad, ipad app says "failed to link your device. Invalid response from system "

Ios log is here.

https://debuglogs.org/ios/5.34.0/3dcd1e7dab6c7017d1650cb803e00b9d1bf373c8b7d6c4c5fbfeadc9564da99a.zip

**Comment by aleksj** [comment]
Similar here: unable to link two phones, reporting that the QR code isn’t valid https://debuglogs.org/ios/5.34.0/be82776f993592fba4998bf7d848f91bffbf8bcf2d96a4d65a2a2a03871164b6.zip

**Comment by aleksj** [comment]
I've had some issues that were addressed by restarting the process a couple of times on both devices.

**Comment by zmilonas** [comment]
Seems duplicate of #5307
