### ISSUE TITLE
Unable to link new iPad with iPhone

### ISSUE THREAD

**Issue by jporter-dev** [signalapp/Signal-iOS#5307]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When attempting to link a brand new iPad with my iPhone, signal respond with a message saying "Failed to Link Your Device. Invalid response from service."

### Steps to reproduce
- Kill app on both devices (also tried full restarts on both too)
- Open Signal
- Go through steps on iPad until QR code (all permissions needed are allowed)
- Go through menus to link new device and scan QR code
- Error

**Actual result:** Failure message as described

**Expected result:** Successful linking of the new device

### Device info
**Device**: iPhone 13 mini, iPad Pro 11"

**iOS version**: iPhone: 15.4.1, iPad: 15.4.1

**Signal version:** 5.34

### Link to debug log
https://debuglogs.org/ios/5.34.0/45a401d26bae912f9401cb6df20838a405021c6039aa43a23203e56c3de8b6ae.zip

**Comment by MrBill1234** [comment]
I am getting this too.  Running iOS 15.5 beta

signal 5.34

iPad 5

if it is relevant, signal was previously installed on this device, removed, and now being reinstalled.

**Comment by zmilonas** [comment]
I am also trying to link Signal on my iPad to by scanning it with my iPhone.

Signal 5.34 on iPad Pro (2018), iOS 15.4.1

Signal 5.34 on iPhone 12 mini, running iOS 15.4

**Comment by asbhat** [comment]
I reported this to support and got the following response:

> Hi,

> This will be fixed in the next update of Signal v5.34.1. It will be made available to you ASAP.

> Thanks again for reporting this.

**Comment by zmilonas** [comment]
Version 5.34.1 solved it for me

**Comment by MrBill1234** [comment]
Still not fixed for me.  5.34.1 on both iPad abs iPhone.

**Comment by jporter-dev** [comment]
@asbhat thanks for the info! The update to 5.34.1 resolves this for me. 

@MrBill1234 you should open a new issue with your debug log since your issue still persists.

**Comment by EmmanuelPREVOST** [comment]
Hey, new Signal version on iPhone fixed it for me too.
Thanks!

**Comment by MrBill1234** [comment]
I didn't change anything - but it is working for me now too.  Glitch in the matrix I suppose.

**Comment by EmmanuelPREVOST** [comment]
> I didn't change anything - but it is working for me now too. Glitch in the matrix I suppose.

Maybe you have automatic update on your phone.

**Comment by MrBill1234** [comment]
No, as I stated above - I manually upgraded to the fixed version on both devices - but it still did not resolve the issue for me.  Then all of a sudden the next day - with no further changes, it worked.
