### ISSUE TITLE
Cannot open any chat after updating to 5.34.1: freeze and crash

### ISSUE THREAD

**Issue by igorkulman** [signalapp/Signal-iOS#5312]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description.
After updating Signal to 5.34.1 I cannot open any chat. Tapping a chat freezes the app and the app then crashes.

### Steps to reproduce
- open Signal
- tap on any chat

**Actual result:** 

The chat gets selected but it does not open the app freezes instead

**Expected result:** 

The chat to open

### Device info

**Device**: iPhone 11

**iOS version**: 15.4.1

**Signal version:** 5.34.1

### Link to debug log

https://debuglogs.org/ios/5.34.1/60e11b67500aba8d05a0b0e52980bba27fea7219c5814abb169ccb901d910973.zip

[crashes.zip](https://github.com/signalapp/Signal-iOS/files/8458502/crashes.zip)

**Comment by strobelm** [comment]
Can confirm the bug. This makes Signal unusable for me on iOS.

Filter: Signal - iOS Debug Log
Hardware: iPhone
HID: 12,3
iOS-Version: 15.4.1 (19E258)
Signal-Version: 5.34.1.0

https://debuglogs.org/ios/5.34.1/b36233ca8184bfb9231e6713869e402707c246619a8f3db85c15a3e7d451dd71.zip

**Comment by strobelm** [comment]
A workaround seems to be:

1. Open Signal
2. Tap on the pencil icon top right 
3. Select a contact -> chat opens normally

This seems to solve the issue for me permanently.

**Comment by Kradio** [comment]
This bug persists in 5.35.1 version as well, the app is unusable it immediately crashes upon launch.
iPhone 14.5
Signal ver 5.35.1

**Comment by Kradio** [comment]
Issue resolved in 5.35.2 ver update
