### ISSUE TITLE
All notifications stopped working after updating

### ISSUE THREAD

**Issue by tara-bartlett** [signalapp/Signal-iOS#5314]
I updated upon getting the 'version expiring' notification/banner and haven't received any notifications since. 

Upon opening the app, 4 group chats/messages (two muted, but also two unmuted) had messages, including tags, where I hadn't been notified.

On an iPhone 8s, iOS 15.2, signal version 5.34.1.0

**Comment by aideya** [comment]
I am also experiencing this issue on my iPhone. Signal 5.39.0.15. iOS 15.4.1.  I am not experiencing this on my iPad or on windows, both of which are linked to the same account as my iPhone.
