### ISSUE TITLE
Signal (5.35.2) crashes on iOS when trying to send attachment

### ISSUE THREAD

**Issue by cJ9889** [signalapp/Signal-iOS#5322]
Hello,

i have the following problem using signal (5.35.2).
When i try to send an attachmend by opening a chat and then tapping on the "+"-Icon next to the wrinting space it shows the recent pictures for a short period of time and then the app crashed.

I am on iOS 15.4.1 unsing an iPhone 12.

Has somebody similiar problems or is this a known issue?

Thanks and best regards

**Comment by SirBuvex** [comment]
Hi, I have the same problem on version 5.36.0.20 (beta). 

Here are my logs:
https://debuglogs.org/ios/5.36.0/b229ff91d843c9b166b847a0ac27a7d7bd130785278aea1f968c7b2de3a1597b.zip

I also have an iPhone 12 mini on iOS 15.4.1

**Comment by cJ9889** [comment]
Hey,
lucky I solved my problem and it was not an issue of Signal primary.
I downloaded some picture and signal could not display one of them in the preview when sending attachments.

Further investigation showed that the image was somehow broken and could not be displayed on other devices too.

Best regards
