### ISSUE TITLE
Can't transfer from old iPad (primary) to new iPad (primary)

### ISSUE THREAD

**Issue by lennartack** [signalapp/Signal-iOS#5327]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to transfer from an old iPad which is the primary Signal device (which was setup using SMS verification) to a new iPad, the new iPad generates a QR code for transferring from a linked device - which, predictably, won't work if the old iPad is a primary device. When I scan the QR code with the old iPad I get the error message: "To set up this iPad as a linked device, you must scan with your old iPad".

### Steps to reproduce
- Setup Signal on an iPad (the "old iPad") as a primary device using SMS verification.
- Instal Signal on another iPad with the same Apple ID. It opens a screen titled "Transfer Account & Messages". Select "Transfer from another iPad".
- It shows a QR code. Scan the QR code with the old iPad.

**Actual result:** The old iPad reports: "To set up this iPad as a linked device, you must scan with your old iPad."

**Expected result:** It should transfer the account and messages from the old to the new Ipad.

### Screenshots
Error message on old iPad after scanning the QR code:
![IMG_1392](https://user-images.githubusercontent.com/17706115/164995738-a5362be9-729c-4f64-9675-c3f9a95c320a.jpeg)

#### New iPad
**iOS version**: 15.4.1
**Signal version:** 5.35.2

#### old iPad
**iOS version**: 12.5.5
**Signal version:** 5.35.2

### Workaround
I was able to force a transfer by hacking the QR code, inspired by amwolff's workaround in #4558.
- Generate the transfer QR code on the new iPad and make a screenshot.
- Scan and decode this QR code on a device you trust (I used zbarimg).
- This generates a link starting with `sgnl://transfer` which includes `transferMode=linked`. Change this to `transferMode=primary`. Generate a new QR code from this link (I used qrencode).
- Scan the new QR code with the old iPad. The transfer should now begin, but it took a long time in my case (about 2 hours).

**Comment by EricBayer** [comment]
I'm getting this issue but the work around doesn't seem to work... wanna make the new ipad master, because if I can't do that then when the old ones dies I'll be dead in the water.

**Comment by lennartack** [comment]
@EricBayer it worked for me, back in April 2022. Do you get an error message?

**Comment by apollopattern** [comment]
I'm getting this message when I'm trying to transfer Signal from my iPhone X to my iPhone 15. Apparently signal thinks the new phone is an iPad. 😡

**Comment by bennbollay** [comment]
Hey @lennartack - any chance you remember what qrencode command line you used?  I'm trying to do an iPad -> iPad transfer right now, changing the `transferMode` to `primary`, but can't get the old iPad to "read" the QR code.  The generated code looks right, parses correctly using my phones camera as a test, but the iPad doesn't see it.
