### ISSUE TITLE
Replies aren't saved as draft

### ISSUE THREAD

**Issue by SirBuvex** [signalapp/Signal-iOS#5332]
If I choose to reply to a message, write something, then switch chats for looking something up etc. 
Then if I go back, the initial message is saved as draft but the message I wanted to reply to is lost so I have to select the message again.

I am not sure if this is intended, so I posted also a feature request on [community.signalusers.com](https://community.signalusers.org/t/save-reply-state/44024?u=sirbuvex).

**Comment by Doge7734** [comment]
Hopefully this will be added. This is a great Quality of Life feature.

**Comment by EvanHahn-Signal** [comment]
This should be fixed in 5.50, which just went to beta. ([Click here][beta] if you're interested in joining the beta.)

I'm going to close this issue because it will be fixed soon.

[beta]: https://support.signal.org/hc/articles/360007318471

**Comment by EvanHahn-Signal** [comment]
For posterity, this was fixed in bb33925499cfab0987efcb3a7dec5a9e75cb7e33.
