### ISSUE TITLE
Crash when sharing donation receipt

### ISSUE THREAD

**Issue by thgoebel** [signalapp/Signal-iOS#5336]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal crashes when sharing a donation receipt.

### Steps to reproduce

- Become a Signal Sustainer
- Open Settings -> Donate to Signal -> Donation Receipts
- Click on a receipt
- Click "Share Receipt"

**Actual result:** Signal crashes and is closed.

**Expected result:** A share dialog should come up.

### Screenshots

n/a

### Device info

**Device**: iPad Pro 11-inch 2nd Gen

**iOS version**: 15.4.1

**Signal version:** 5.36.0.29, 5.36.1.0, 5.37.0.8, 5.37.1.0

Additional info: my phone is an Android running LineageOS w/o GApps, hence no Google Pay, hence I donated via the linked iPad.

### Link to debug log

Crash log sent via email.

**Comment by EvanHahn-Signal** [comment]
I introduced this bug—apologies. Thanks for reporting!

I've got a fix which should go out in an upcoming version.

**Comment by thgoebel** [comment]
Version 5.38.0.18 from the App Store fixed it for me, thx!
Linking the commit for the reference: 6d98d7785072467debce60ccbd2cf8727de00fef
