### ISSUE TITLE
Strange issues with messages not being relayed from or to, either mobile or desktop alternatingly

### ISSUE THREAD

**Issue by Kinnardian** [signalapp/Signal-iOS#5341]
I have been experiencing strange issues with messages not being relayed to or from either mobile or desktop alternatingly.
First on mobile I was unable to sync messages or make calls. Then on desktop. This persisted for weeks across multiple updates and other troubleshooting.

I'm running 5.42.0 on Desktop on Mac and 5.36.1.0 on iOS

There are several co-occurring strange phenomena.

Should each be filed as a separate issue?

**Comment by jrose-signal** [comment]
I think the best option is to file a report at https://support.signal.org, including [debug logs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) from both your iOS and Desktop apps. Hopefully we can help you further there!

**Comment by Kinnardian** [comment]
Sweet. Do you handle all issues there? There's no way to file Signal-Server issues on gh.

**Comment by jrose-signal** [comment]
support.signal.org is for any issues using the official clients (implied: with the official server). If you're running your own server, you can discuss on the unofficial community forums at https://community.signalusers.org/, but that's not something Signal officially supports.
