### ISSUE TITLE
Bug report after crash

### ISSUE THREAD

**Issue by thomassth** [signalapp/Signal-iOS#5348]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

this is a bug report prompted by the app.

My signal client crashes pretty often. If you need more bug reports i can get one easily.
### Device info

**Device**: iPad gen 8

**iOS version**: 15

**Signal version:** 5.32.7

### Link to debug log

https://debuglogs.org/ios/5.37.2/d88bb9c5fde14dd6b89ccb2ee1a7dfcc0bae46cd6c33d6314d341530fe42ef45.zip

https://debuglogs.org/ios/5.37.2/12421d83caba4df36fa57d7e6530d64f1feb446a1fb0595f73f50f1fd0ebc91f.zip

**Comment by thomassth** [comment]
I have sent the email

This is the accompanying debug log, forgot to attach it in

https://debuglogs.org/ios/5.37.2/dd9391bc98d8d1e7a93c32cfbe612f97a116a4a11e8ea70e425ab81053cf7a49.zip

**Comment by KatieG285** [comment]
I don’t know how to get the log. iOS 8+ crashes upon opening

**Comment by thomassth** [comment]
Do you guys need more bug reports from my setup? I can still consistently trigger one even after all the latest updates
