### ISSUE TITLE
https://debuglogs.org/ios/5.37.1/49f5d8fa8bf690a347fadcd34b8662c32ffd12f9791302c311dbc49e722b456d.zip

### ISSUE THREAD

**Issue by ankh1s3s** [signalapp/Signal-iOS#5350]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by max-signal** [comment]
Do you have any additional details about the issue you’re experiencing?
