### ISSUE TITLE
App crashes on open on iPad

### ISSUE THREAD

**Issue by rambler** [signalapp/Signal-iOS#5353]
https://debuglogs.org/ios/5.37.2/13a8f304cc1a1905564a96ae5e38a2a0623715dccdc963aea59aa94347d229df.zip

Immediately upon opening, the app exits.

**Comment by max-signal** [comment]
This should be resolved by 1ba72789cee0a836b34877eaa3d55c9cdcd6b6ce, which is available in the 5.38.0.16 beta or later (and should be available in the App Store soon). If you want to join the beta program to test out of the fix more quickly, there’s instructions [here](https://support.signal.org/hc/en-us/articles/360007318471).

**Comment by EvanHahn-Signal** [comment]
Signal 5.38 has been released and this issue should be resolved. I'm going to close, but let me know if that's wrong.

Thanks for reporting!
