### ISSUE TITLE
When sending a message and then leaving the app after, it doesn't actually get sent and delivered until the app is open again

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-iOS#5354]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm submitting this report for someone I'm talking to that's on Signal-iOS. The messages they send in a 1-1 chat to me sometimes doesn't get delivered, even though their device has sent it. I recognize this by how the sent timestamp is way later than the deliver timestamp. 

This has happened several times in the past and with another iOS user, but I'm only able to get the logs for one instance here. In the past, there were times when the delay is really bad; one instance in the past had a message they sent only getting delivered to me a day later. I don't know if this is due to network conditions, although a day-long delay in the past makes it feel like that wouldn't be the only issue.

Oddly enough, my messages do get delivered to them, but any message that they sent a while ago will have have an older timestamp and looks out of place in the message history. So it ends up being a message timeline that like this in the Android app:

| Sent timestamp of their messages | Sent timestamp of my messages |
| --- | --- |
| 1652914866925 |  |
|  | 1652914933315 |
| | 1652914951507 |
| 1652914923957 (this message got delayed; delivery time is at 4:11pm) | |  
| 1652915498565 | |

Their device seems like it can receive messages fine, because I got a delivery receipts for 1652914933315 and 1652914951507 at 4:02 pm. From my Android logs:

```
[5.37.4] [41   ] 2022-05-18 16:02:14.053 PDT I MessageContentProcessor: [MessageContentProcessor] Processing delivery receipts. Sender: RecipientId::14, Device: 1, Timestamps: 1652914933315
...
[5.37.4] [42   ] 2022-05-18 16:02:32.593 PDT I MessageContentProcessor: [MessageContentProcessor] Processing delivery receipts. Sender: RecipientId::14, Device: 1, Timestamps: 1652914951507
```

It's only later when they read my two messages that I receive 1652914923957

```
[5.37.4] [40   ] 2022-05-18 16:11:18.213 PDT I MessageContentProcessor: [1652914923957] Beginning message processing. Sender: RecipientId::14 (********-****-****-****-**********37.1)
...
[5.37.4] [40   ] 2022-05-18 16:11:18.213 PDT I MessageContentProcessor: [1652914923957] Text message.
[5.37.4] [41   ] 2022-05-18 16:11:18.651 PDT I MessageContentProcessor: [MessageContentProcessor] Processing read receipts. Sender: RecipientId::14, Device: 1, Timestamps: 1652914933315, 1652914951507
```

### Steps to reproduce
- Send a message
- Close the app after sending (?)

**Actual result:** Message doesn't deliver (until the app is opened again?)

**Expected result:** Message gets sent and delivered

### Screenshots

This is for their message 1652914923957, screenshotted from my Android device :

<img src="https://user-images.githubusercontent.com/26474149/169599421-0e3a73b6-c85e-4f3e-a534-b39e5bc23df3.jpeg" width=50%/>

### Device info

**Device**: iPhone XR

**iOS version**: 15.4.1

**Signal version:** 5.37.4

### Link to debug log

Their device: https://debuglogs.org/ios/5.37.2/801ed54e135d1b0bc0cf1f397def8ebda917dcdeb7faa94cd87ada2315326ce2.zip

My device: https://debuglogs.org/android/5.37.4/c0fe5d1ec7a9b290c7652308a63604925a74aeb229e155b1f6f00e2ce340e979

**Comment by inthewaves** [comment]
To me it looks like like iOS is killing/terminating the app after they close it. Immediately after this line in the iOS debug log

```
2022/05/18 23:02:04:030  💛 [Bench.swift:31 BenchAsync(title:logInProduction:block:)]: [Bench] title: Send Message Milestone: Sending (1652914923957), duration: 72.68ms
```

there's a bunch of lines about `OWSURLSession` failing (`2022/05/18 23:02:04:250  💛 [OWSURLSession.swift:672 urlSession(_:task:didCompleteWithError:)]: Error: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=wss://chat.signal.org/v1/websocket/?login=...`) and `applicationWillTerminate`

**Comment by azuredusk10** [comment]
I’m also experiencing this with a contact who uses an iPhone. In her case, messages which she wrote to me didn’t get delivered to me for a whole week. The trigger seemed to be sending me another a couple of messages a week later. I received the whole batch in one go.  

Unfortunately I can’t provide a debug log, but will see if I can reproduce it with her when I next see her in person.

**Comment by marekkrug** [comment]
> I’m also experiencing this with a contact who uses an iPhone. In her case, messages which she wrote to me didn’t get delivered to me for a whole week. The trigger which caused these messages to get delivered to me seemed to be her sending me another a couple of messages a week later. I received the whole batch in one go.
> 
> Unfortunately I can’t provide a debug log, but will see if I can reproduce it with her when I next see her in person.

Exactly that happened to me (Android 15) and my Friend (iOS, iPhone 12):

Sent
15 Apr 2025, 14:46
 (1744721201375)

Received
Yesterday ⁨16:17⁩
 (1744813035407)

That means it took the message over one day until she got send
