### ISSUE TITLE
Unable to open signal app in iPhone 13

### ISSUE THREAD

**Issue by Yogender5** [signalapp/Signal-iOS#5355]
I have new messages in signal app and when trying to open I see a message “downloading data from server, this may take up to few minutes” and after few minutes it still doesn’t show up the app. All the engineers work and resolve the bug dudes, or hire me 😊

**Comment by EvanHahn-Signal** [comment]
Sorry about this. Could you (1) include some screenshots (2) include debug logs, which you can get in Settings → Help → Submit Debug Log?
