### ISSUE TITLE
Signal won’t open iPhone X iOS 15.5

### ISSUE THREAD

**Issue by heykerriann** [signalapp/Signal-iOS#5356]
Won’t open at all, can’t get to QR code to transfer chats to new iPhone. Thanks for your help. 

[Bug report](https://debuglogs.org/ios/5.38.0/1ceb492c2ca2e5ac14f9044eb59f3113b4c378e658a56c8ac00daf36b20af6ec.zip) 
[signal-wont-open_2022-05-22b.zip](https://github.com/signalapp/Signal-iOS/files/8750007/signal-wont-open_2022-05-22b.zip)
[Signal-2022-05-22-142533.zip](https://github.com/signalapp/Signal-iOS/files/8750009/Signal-2022-05-22-142533.zip)

**Comment by heykerriann** [comment]
The Signal settings are incomplete too. Only 4 options, with no Local Network setting. 
![499F3980-46C8-437E-84E9-8123176296CB](https://user-images.githubusercontent.com/106031650/169711353-874557ed-3d6e-42ad-9150-2f68be20d597.png)

**Comment by jrose-signal** [comment]
To be clear, this is the old Signal that won't open, not the one on the new phone?

The crash looks like one of the things that was fixed in 5.39, but I'm not sure we got all instances of it. If 5.39 doesn't fix your issue, 5.40 (currently in beta) has some additional logging; I'd ask you to update to 5.40, try launching again, and resubmit the debug logs. (If you're not in the beta program you can either join or wait until 5.40 is released on the main store.)

Sorry for the trouble!

**Comment by heykerriann** [comment]
Hi. There’s no old/new phone. This just started happening out of the blue, and I haven’t been able to use Signal at all ever since. I updated to 5.38 hoping it would help but no dice. It just crashes in a slightly different way now. I’m updating now to 5.39… wish me luck, and thanks for the advice. I’m so worried I’m going to lose all my messages if I ever DO get the app to start up again. (And how do I join the beta program?)

**Comment by heykerriann** [comment]
JRose, sorry—I see why you were asking about 2 phones. After it stopped opening on my iphone, I installed signal on a spare iphone, just to try to transfer and preserve my messages, but I can’t get to the QR code on MY iPhone to initiate the transfer, so the spare iPhone is no use and I just uninstalled signal from it.

**Comment by heykerriann** [comment]
So no luck. Still won’t open at all with 5.39.

**Comment by jrose-signal** [comment]
Apologies again. [Here's how to join the beta program.](https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta) (You won't lose your messages by installing the beta over the App Store version, and there are instructions on that page on how to leave in the future.)

**Comment by heykerriann** [comment]
![Uploading B16DEC97-D1DE-47AA-BE17-BFA28544BAFC.png…]()

**Comment by heykerriann** [comment]
![AB2E3317-871D-4ACE-8C46-DD1FC6FB0043](https://user-images.githubusercontent.com/106031650/170793233-361024ea-8571-4296-a74e-d6b4933791d8.png)

**Comment by heykerriann** [comment]
Yeah no luck w 5.4 beta either…

[Link to the 5.4 crash log](https://debuglogs.org/ios/5.40.0/d04e1777611fd818c7fef3884f1a6141b782f5b94a405cb09eed273de387393a.zip) 

Should I email the .ips files somewhere too?

**Comment by jrose-signal** [comment]
No, the previous ones have enough information on the crash location, and indeed this new log has the reason included. Thank you!

**Comment by heykerriann** [comment]
Thank you!
