### ISSUE TITLE
Can't backup my own chats

### ISSUE THREAD

**Issue by estiens** [signalapp/Signal-iOS#5357]
### Bug description
There seems to be a bug. I can't back up my own chats with my own friends and family.

### Steps to reproduce
- Use signal on iOS devices. Try to backup.
- No way to back up lose your phone, you're out precious memories

**Actual result:** 

I can't backup

**Expected result:** 

I can backup my own data to where ever I want

**Comment by Doge7734** [comment]
Not a bug, there just isn't a way to backup chats on iOS at the moment. Only Android offers local backups. The best you can do is transfer your messages from iOS to iOS but that requires your old device. This feature has been requested at Signal's official community forums: https://community.signalusers.org/

**Comment by NiklasBr** [comment]
It's a design bug (not giving users access to their own data), not an implementation bug (incorrect code logic).

**Comment by Doge7734** [comment]
Nora Trapp, iOS developer, said reasons as to why they haven't implemented a way [here.](https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones/1736/182)

**Comment by kdambekalns** [comment]
> Nora Trapp, iOS developer, said reasons as to why they haven't implemented a way [here.](https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones/1736/182)

Ah, thanks. But:

> because iOS, until very recently, didn’t give you a place to store and manage files

"Very recently" is no longer true, that was written more than two years ago. _sigh_

**Comment by Doge7734** [comment]
> "Very recently" is no longer true, that was written more than two years ago. sigh
Yes, that is true. I do not how much - if any - work has been done on backup for iOS yet but everything they do is added to GitHub for everyone to view. Just have to wait and see if any commits indicate something about backups. I also haven't seen any comments by the iOS developers about backups since then.

**Comment by kdambekalns** [comment]
Yes, the issue has been stale, but that matches the lack of response on the plans for solving it. I'd love to see it kept open. We can revisit every year on "World Backuo Day"…

**Comment by kdambekalns** [comment]
> We can revisit every year on "World Backuo Day"…

Of course I meant "World Backup Day", and this comment will hopefully count as activity to keep it open. 😆

**Comment by estiens** [comment]
To clarify my original big report was a bit snarky. I know it's not an actual bug. And if signal was just be used as a one time notepad for super secret messages it would be a good design choice. 

Since it's not. And since it is available on other platforms. And since its not a security choice but can have major negative implications for people that may lose years of sentimental or otherwise deeply important records of their own correspondence because of a poor design choice not even fully implemented years ago. 

I think it should be a top priority to fix and many people have raised it as a major issue for years now. 

As of yet the signal developers seem to think it is unimportant. There are ways around it with many varieties of platforms. But if the only place you have years of messages is on your iPhone and you don't want to jailbreak and run a possibly sketchy script, you are stuck...

Plus one for keeping this open until fixed.
