### ISSUE TITLE
iPhone 11, iOS 15.4.1, Signal 5.38 crashes on opening application

### ISSUE THREAD

**Issue by highway900** [signalapp/Signal-iOS#5358]
### Bug description
Signal application crashes on open. Displays 2 buttons for submitting a debug log and continuing to open signal. The debug log button when pressed displays a message saying no logs found. Pressing Ok from here will cause the application to stall at the full blue logo screen and proceeds no further.
The continue opening button shows group chat list very briefly and then crashes application.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

application crashes

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

application opens

### Device info

**Device**: iPhone 11

**iOS version**: 15.4.1

**Signal version:** 5.38

### Link to debug log
crash log submitted to support@signal.org

**Comment by highway900** [comment]
I can confirm that 5.39 does not fix the issue

**Comment by JohannesVerherstraeten** [comment]
Same issue here, including the chat list being shown very briefly before the crash. It started happening a few days ago. But for me the log submission works: 

https://debuglogs.org/ios/5.38.0/a7a08171ea31dc16d81382ffa45baa1463f5aa850e932b1e399c034fc74e65b2.zip

**Comment by highway900** [comment]
I currently have 5.39 (not sure of patch version) installed. Today I checked for version updates and started receiving notifications for new messages, this is something that I have not seen since the issue began.
The application still **crashes** unfortunately. But a sign is welcome.

**Comment by highway900** [comment]
I curious is there anything in signal where hardware changes / modifications would cause it it crash / not trust the device?
