### ISSUE TITLE
Signal crashes after opening app - after last update.

### ISSUE THREAD

**Issue by xandrahoek** [signalapp/Signal-iOS#5359]
https://debuglogs.org/ios/5.38.0/b40a5cca74dc2bc19ac719324d33217a1099729a6a30b5a7ea1fb8b86f2c680c.zip

**Comment by EvanHahn-Signal** [comment]
Sorry you're running into this.

Could you grab the crash reports from your device as well? Those would be helpful for us to continue investigating the issue. You can find instructions for how to submit them [here](https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports).
