### ISSUE TITLE
Unable to initiate new contacts

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#5362]
Iphone SE, gen.1. Signal version 5.38.0.18. iOS version 15.5.

When I try to initiate a new contact, I get a spinner that never resolves.  There are no requests for a capcha and the message never goes through.  This is consistent, and this is the [log](https://debuglogs.org/ios/5.38.0/8c133427e579846c242a97301a2505d591d326ce09da2f2a19c96c87f6a67282.zip) of the most recent time.

On the desktop, I have a similar problem, though there I am met with a request for a capcha, which when completed leads me back to Signal, which then gives me the message "Verification Failed, Please Retry Later."  See [here](https://github.com/signalapp/Signal-Desktop/issues/5938#issuecomment-1136545745).

**Comment by DiagonalArg** [comment]
Here's another one ([log](https://debuglogs.org/ios/5.39.0/da6499017c67840b6c30ee84d578500b78ecbff25b3def8f6e5d2fb93af5565f.zip)) on my iPhone.  Initiation of contact leads to a permanently spinning spinner, and there are no requests to complete a capcha.

**Comment by jrose-signal** [comment]
Thanks for reporting! I think I know what went wrong, but it'll be a bit before I can get it into a PR and then into a build.

**Comment by DiagonalArg** [comment]
@jrose-signal - If you let me know when you think it should be fixed, I'd appreciate it.  I've been reporting *many* bugs, to the point where I'm having difficulty using Signal.

**Comment by jrose-signal** [comment]
If you're part of the [beta program](https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta), you can see if 5.41 fixes any of your issues.

**Comment by jrose-signal** [comment]
5.41 has been released to production (last week, actually, sorry for not pinging).

**Comment by DiagonalArg** [comment]
I have not tried to initiate a new contact, but I am still having substantial issues.  Since @indutny-signal is saying these issues are linked, I'll put the link to my report & log here:

https://github.com/signalapp/Signal-iOS/issues/5361#issuecomment-1160948228

**Comment by DiagonalArg** [comment]
I am unable to initiate a new contact.

From the Desktop side, I end up with the [Verification Failed, Please Retry Later](https://github.com/signalapp/Signal-Desktop/issues/5938) issue.  

    Sent | Today 9:50 PM (1655959851944)

    Pending ...

Here is the desktop [log](https://debuglogs.org/desktop/5.46.0/cfc58b69343cff438d29b7b327a70fc8f30e378142dd97a189c175706e518722.gz).

I cancelled that out and then tried to send via iOS.  I haven't received a request for a capcha.   The spinner is going.  Message info says:

    Sent Today 21:59

    Sending to ...

But it doesn't appear to be getting any further.  Here is the iOS [log](https://debuglogs.org/ios/5.41.0/770b18a3b33bc9d952af6b9391d54e02b448a3be3dd7d1fd7fb3e46500f718e5.zip).

**Comment by DiagonalArg** [comment]
Things have improved substantially.  There are still some glitches, but I'm closing this and as the new situation becomes clear, I'll open new issues as needs be.

Thanks!
