### ISSUE TITLE
Opening Signal iPad via Push Notification does not correctly select Chat in sidebar

### ISSUE THREAD

**Issue by grahams** [signalapp/Signal-iOS#5363]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I get a push notification for a chat and tap it to open signal, the chat opens correctly in the main view, but the chat is not correctly selected in the "Chats" sidebar, leaving whatever the previous chat was that I was viewing appearing to be selected, even though it is no longer the chat which appears in the main right-hand panel.

### Steps to reproduce
- View a chat in signal and switch away from the app
- Receive a message in a different chat than was originally selected and tap the notification when it appears

**Actual result:** Selection in left hand "Chats" does not match the currently viewed chat in the right hand view 

**Expected result:** Selection in left hand "Chats" list reflects the currently viewed chat in the right hand view

### Screenshots

Sorry for the heavy redaction but I use Signal for sensitive chat.
![IMG_43F13C3BD866-1](https://user-images.githubusercontent.com/49202/170366729-3169eeb0-2be9-4acc-a6c0-c2b5ffbbd3fd.jpeg)

### Device info

**Device**: mid 2020 11-inch iPad Pro Wi‑Fi 256GB - Space Gray

**iOS version**: 15.5

**Signal version:** 5.38.0.18

### Link to debug log
I can provide the debug log if truly necessary but am nervous about leaking data via logs.

**Comment by grahams** [comment]
I saw this bug just yesterday, it persists.

**Comment by grahams** [comment]
I just tried to reproduce this issue and was unable to, so I think this was addressed (either intentionally or otherwise :)

**Comment by maederm** [comment]
@grahams I just had the issue today with Signal 6.4.0.10 on iPadOS 16.1.1.
