### ISSUE TITLE
Message not received on IOS emulator

### ISSUE THREAD

**Issue by huainanzi** [signalapp/Signal-iOS#5364]
I use Xcode to run on the simulator, but I can't receive messages

**Comment by jrose-signal** [comment]
We use the iOS simulator for testing regularly, so we'll need a bit more information to help you figure out what's not working.

**Comment by jrose-signal** [comment]
[Can you submit a debug log?](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) (It's the same in the simulator as on a device.)

**Comment by 337077418** [comment]
请问大佬你解决了吗,我也遇到这个问题了
