### ISSUE TITLE
Signal Application Crashed

### ISSUE THREAD

**Issue by Parth7161** [signalapp/Signal-iOS#5365]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Doge7734** [comment]
If you want the iOS developers to fix this problem, you will most likely need to get the crash report from your iPhone if the app crashes on startup. Also helpful if you can fill out the bug template. Here is how you can find and send Signal debug and/or crash [logs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug)
