### ISSUE TITLE
Signal crashes on startup on iPad (long-standing issue)

### ISSUE THREAD

**Issue by pimlottc** [signalapp/Signal-iOS#5367]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on startup on my iPad.  This has been happening for over a year through multiple versions of iPadOS.

At some point in the past, it used to work.  I don't want to uninstall and reinstall as there is over 1G of chat history I would like to preserve.

### Steps to reproduce
- Tap the Signal app icon
- View the Signal logo loading screen

**Actual result:** Signal crashes with no error message and you are returned to iPad home screen

**Expected result:** Signal starts and runs as normal

### Device info
**Device**: iPad (6th Generation)

**iOS version**: 15.4.1

**Signal version:** 5.39

### Link to debug log
- https://debuglogs.org/ios/5.39.0/b16e3a93227cb86a8fef5d235b877c253d26e3edf2c4b05f1d6cefbf920c918b.zip

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. 

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.

Thank you.

**Comment by pimlottc** [comment]
> Please write in from within the app so we can better understand what the issue is.
> 
> Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.

I am clearly unable to do so as the app crashes immediately on startup.

**Comment by finn-signal** [comment]
Apologies. I couldn't tell if this was a a constant or intermittent issue.

We're looking into this.
