### ISSUE TITLE
Can't switch to third party keyboard

### ISSUE THREAD

**Issue by flow7** [signalapp/Signal-iOS#5371]
### Bug description
On Signal IOs I can not change from the IOs Keyboard to a third party keyboard.
Is this a bug, a feature or something I missed?

Any tricks, tips?

### Steps to reproduce
- install and setup 3rd party keyboard (tested SwiftKey and Gboard separately)
- open Signal, hit the globe to change keyboard
- no non-IOs Keyboard is offered. You can however change languages within the IOs keyboard

Also
- open any app, hit the globe and change to a third party keyboard (eg. GBoard)
- open another app, GBoard keyboard is still active
- open Signal >> the keyboard has switched back to the IOs keyboard, no third party keyboard available for selection

**Actual result:** 
no third party keyboard available

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- a third party keyboard option
- 

### Device info

**Device**: IPhone SE

**iOS version**: 15.5

**Signal version:** 5.39.0.15

**Comment by sashaweiss-signal** [comment]
Hi! Thanks for commenting.

Signal doesn't have any restrictions on using a third-party keyboard, so unfortunately I'm not sure what issue you're running into. I also tried installing Swiftkey and was able to use it successfully to send messages in a Signal chat, so while it's strange you're seeing this behavior I don't think this is a Signal-related issue.

I'm going to close for now, please re-open if you have reason to think this is indeed something Signal is doing wrong!
