### ISSUE TITLE
"Sending Paused" - Often failing on the same contacts.

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#5372]
Iphone SE, gen.1. Signal version 5.38.0.18. iOS version 15.5.

I send a message to a group of 240 members.  I see the messsage labled as "sending paused."  I've seen this before and when I check the info for the messages, I see it happens often on the same group of contacts.  [log](https://debuglogs.org/ios/5.39.0/e65ba85a661f525c8d00fb3c5af10f98d3f45019cbc9bf3c0b4079338b984c75.zip).  The Sent Time of the message (in case that will help identify it) was 

Sent time:
1654064495653

![Paused 1](https://user-images.githubusercontent.com/5190243/171595358-baa4ce86-6444-4558-8f3f-9b45db9a4ac3.png)

I send a message to another large list.  I see the same "sending paused."  When I check the info for the message I see a number of paused correspondents and a couple "skipped."

![Paused 2](https://user-images.githubusercontent.com/5190243/171596011-3d233ca7-ab37-46e7-a810-cb8ba798365a.png)

![Skipped](https://user-images.githubusercontent.com/5190243/171596050-f653ad89-0625-41ce-a157-fa0328ea002a.png)

**Comment by jrose-signal** [comment]
I think all of the issues you're hitting are the same #5362. The app has queued up a bunch of work, but is incorrect in how it's resolving the rate limit challenges, and so it neither completes them nor presents a captcha. I'm going to close this and leave it tracked there.

**Comment by DiagonalArg** [comment]
@jrose-signal / JR, what of all the "Unknown"s?  And why the "Paused and "Skipped" contacts?  The ones that are paused are generally consistent, and include some "Unknown"s.

**Comment by jrose-signal** [comment]
Both profile fetches (to learn names) and first-time sends go through the same rate limiting system, and the same issues affect both. :-(

**Comment by DiagonalArg** [comment]
@jrose-signal 

Ok.  I blocked all "Unknown" contacts, hoping that would help.  I haven't noticed a difference.  Should I unblock them?
