### ISSUE TITLE
Can’t make or receive calls on Telstra network (Australia)

### ISSUE THREAD

**Issue by duncangroenewald** [signalapp/Signal-iOS#5376]
I am unable to make or receive calls while roaming on the Telstra (Australia) network.  Is it possible that Telstra are blocking called from being made/received or could this be a bug?

If I make a call it just rings and rings but the received never receives a call and similarly if someone calls me then I never receive the call and their side just rings and rings.

I am pretty sure this used to work fine and only stopped in the last 3 months or so but could be mistaken about that.

https://debuglogs.org/ios/5.40.0/198c83e6d96edbe18723d5aa58544c76157aee026c0ea11b494008bd1def4396.zip

**Comment by duncangroenewald** [comment]
Here is another log - I tried making calls again and managed to briefly receive one incoming call notification but the call failed to connect properly when I picked up.

https://debuglogs.org/ios/5.40.0/391f73fdec0a256fbc9cd2eccb993b6e0ca2e95213bbccf0f5e8c80070817a76.zip

**Comment by julzncatz** [comment]
Hi I’m having the same issue. Optus doesn’t have this problem 
https://debuglogs.org/ios/5.41.0/6fcbdc34a7bf8e32b8dba73ad898392108923802ae0315f4a0d4e2bddf868cec.zip

**Comment by sashaweiss-signal** [comment]
Hey all! The latest 5.42 beta release has a change we believe addresses this issue. Please give that a try, and let us know if you continue to experience issues. See [here](https://support.signal.org/hc/articles/360007318471) for instructions on joining the beta, or these changes will eventually make their way to the App Store.

**Comment by duncangroenewald** [comment]
Works for me now thanks.

**Comment by sashaweiss-signal** [comment]
So glad to hear! Please re-open if you have further issues.
