### ISSUE TITLE
https://debuglogs.org/ios/5.40.0/6e762594ffab981705b6c369c2823fade36ae29c87da47cae05842411bb214a5.zip

### ISSUE THREAD

**Issue by Danutu89** [signalapp/Signal-iOS#5377]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Doge7734** [comment]
Not a developer, but are you able to describe the bug that you are experiencing? Filling out the bug template will help the iOS Signal developers to find and fix the bug.
