### ISSUE TITLE
App does not send verification code

### ISSUE THREAD

**Issue by F1lton** [signalapp/Signal-iOS#5378]
When I try to sign in, the app asks for a phone number, once it is entered, the app is supposed to send a verification code, but in fact it does not, just spins the wheel
At the first time using the app, the code was coming properly, it is not the problem with carrier or network connection
Tried to reinstall and update the app, doesn’t help

**Comment by F1lton** [comment]
https://debuglogs.org/ios/5.41.0/5a79120485bf93685d1e33edc0104188ac7032b5218083f12659b72643081128.zip

**Comment by kaktusztea** [comment]
Hi @F1lton,
I'm not a developer, but maybe you could mention in which country you are (with country code) and which carrier do you use. Maybe Signal registration sms' are blocked in your country 🤷‍♂️ beacuse of some censorship.

Also your used Signal client version, iPhone model and iOS version are helpful informations too.

**Comment by F1lton** [comment]
Signal version - latest one for iPhone SE 1gen
Country code +38 (Ukraine)

**Comment by Doge7734** [comment]
I'm also not a developer. Not sure if Ukraine has ever blocked Signal. The countries I know that do are Iran and China but more is entirely possible. According to this [Wired](https://www.wired.com/story/ukraine-russia-internet-takeover/)post, in the city of Kherson, "anyone connecting to the internet with KhersonTelecom, known locally as SkyNet..." had no internet connection. After 59 minutes it came back online but was now being rerouted through Russia. If this affects you, Russia could be bocking Signal.

**Note:** I am not certain and only speculating. Don't quote me.
