### ISSUE TITLE
my signal app cannot be oppened because of bug issue plrase help 

### ISSUE THREAD

**Issue by malk2ad** [signalapp/Signal-iOS#5381]
- [yes]I have searched open and closed issues for duplicates
- [yes ] I am submitting a bug report for existing functionality that does not work as intended
- [y]This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

### Link to debug log

my Signal app cannot be oppen on iphone 6S because of bugg issue please 
help .

**Comment by sashaweiss-signal** [comment]
Hi! Thanks for commenting.

Unfortunately without a description of the issue, and preferably also debug logs or a crash report, there's not much we can do to help. Going to close for now, please re-open if you have additional information!

**Comment by malk2ad** [comment]
Hi Sasha ,
i have emailed erlier some bug loggs but i can re send it again .
Thank yoo for letting me know ,
Milana

**Comment by malk2ad** [comment]
Hi Sasha ,

i am forwarding anothe bug log report from today . i am not sure 
if you can see my previous one from the other day but i am having the same issure with sgnal app as it was before . i couldn't oppen this app even after i have updated my ipone 6 S with newest software .
i have offloaded app and reinstolled but it didn't helped .
i went througth all troublsouring steps also . Can you please  take a look if anything else can be done to fix this problem .

Sinceraly ,
Milana 






Sent from my iPhone

**Comment by malk2ad** [comment]
Hi Sasha ,
i am forwarding an additional information with description what may help with troublshooting some bug issues with Signal app 
on my iphone 6 S and i have also forwarded with my previous email to you  signal bug log 
please help .
sinceraly ,
Milana
