### ISSUE TITLE
Signal crashes right after start 2022-06-21-22-02

### ISSUE THREAD

**Issue by Tulisuudelma** [signalapp/Signal-iOS#5386]
### Bug description
Signal crashes right after start

### Steps to reproduce
Open signal
**Actual result:** after click open Signal - return to home screen
**Expected result:** Signal opens

### Device info

**Device**: iDevice Iphone 13 pro max

**iOS version**: 15.5

**Signal version:** 5.4.1

### Link to debug log
(https://debuglogs.org/ios/5.41.0/2ffece14e9b2b41a9972a07a02d447e684ded13479810d9b471733858e7d1faf.zip)

If this is a crashing bug, after filing this issue, email a copy of your latest crash report to support@whispersystems.org (done)

**Comment by jackreid** [comment]
Also happening to me on Signal v5.44.3 on Android 10, but specifically when the phone is connected to the network. If it is on airplane mode, it opens fine, suggesting that it might be connected to the old bugs #5300  and #5105 , though I didn't send any voice messages.

My debug logs are available here: https://debuglogs.org/desktop/5.53.0/947090de47cd77b7738fb5e479b633d0c0556a5e8516e3189758026d2cd40f14.gz

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. 

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.

Thank you.
