### ISSUE TITLE
@tobyshorin and @altosaar simultaneous calls result in error

### ISSUE THREAD

**Issue by altosaar** [signalapp/Signal-iOS#5388]
This has been happening for a few years. @tobyshorin and I keep calling each other at the same time. 

When this happens, the call drops. 

We always switch to cellular, or worse, WhatsApp 😭

any ideas on what would be helpful to debug? Sorry if this is the wrong place to post we’ve just had this issue for years and it has taken up a lot of our time.

**Comment by Sgn-32** [comment]
Debug logs of both devices direct after the error would be helpful.

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by altosaar** [comment]
Still an issue unfortunately

**Comment by altosaar** [comment]
Still at issue :$
