### ISSUE TITLE
iOS 16: status bar transparent

### ISSUE THREAD

**Issue by kaulex99** [signalapp/Signal-iOS#5391]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The status bar is transparent since iOS 16 Developer Beta

### Steps to reproduce
- Open signal app
- go to any chat with messages
- scroll through chats

**Actual result:** status bar transparent, navigation bar works like expected. 
**Expected result:** status bar should not be transparent

### Device info

**Device**: iPhone 12

**iOS version**: 16.0 beta 2
**Signal version:** 5.42.0.12

**Comment by braydofficial** [comment]
For reference, this was also mentioned in the Beta feedback category in the community forums, with an included screenshot. 

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-5-43-release/45233/8?u=brayd

**Comment by EvanHahn-Signal** [comment]
Thanks for reporting. We'll take a look as we work on iOS 16 compatibility.

**Comment by tinyoverflow** [comment]
I am on iOS 16 Developer Beta 2 (20A5303i) and I cannot confirm this issue. The bar with the name and call action buttons and the status bar is not fully transparent, but blurred.

**Comment by braydofficial** [comment]
> I am on iOS 16 Developer Beta 2 (20A5303i) and I cannot confirm this issue. The bar with the name and call action buttons and the status bar is not fully transparent, but blurred.


Yes, it is blurred. However, above the status bar it should also be blurred but it's transparent, so you can see text behind it. I linked a thread in the community forum with a screenshot 2 posts above your answer. However, here's the screenshot linked directly for comparison.
![Screenshot from the Signal app](https://community.signalusers.org/uploads/db3609/optimized/3X/1/9/19b37d6ff19909265d33f85e8a1f4393defb8105_2_409x750.jpeg)
As you can see in the screenshot the area above the status bar is fully transparent, which looks a bit weird.

**Comment by u32i64** [comment]
> I am on iOS 16 Developer Beta 2 (20A5303i) and I cannot confirm this issue. The bar with the name and call action buttons and the status bar is not fully transparent, but blurred.

For the record, I'm on the same version on an iPhone XR with Signal 5.44.0.8, and do not observe this issue either, at least not regularly, so it seems that this isn't a universal issue. Both bars are blurred as expected for me:

<img src="https://user-images.githubusercontent.com/19972511/177615357-2feaec39-1923-4d4b-94bc-75ea5416f5e9.jpeg" width=300>

**Comment by kaulex99** [comment]
It looks good on Development Beta 03

**Comment by tinyoverflow** [comment]
> However, above the status bar it should also be blurred but it's transparent, so you can see text behind it.
> @braydofficial 

Yes, I understood what was meant by OP. But it's not the case for me. It's exactly how it should be, as shown by @u32i64 here, for me:
![image](https://user-images.githubusercontent.com/19972511/177615357-2feaec39-1923-4d4b-94bc-75ea5416f5e9.jpeg)

**Comment by braydofficial** [comment]
Update: on iOS 16 Developer Beta 3 it's now looking normal again.

**Comment by max-signal** [comment]
It appears as though beta 3 has resolved the issue. If you’re still seeing it on recent iOS 16 betas, please re-open it!

**Comment by TechnikMax** [comment]
After updating to IOS 16.0 on my iPhone XS i also get this issue. It isn't present all the time but appears very often.
I'm using Signal Version 5.51.0.14

**Comment by EvanHahn-Signal** [comment]
We expect the status bar to be partially transparent. @TechnikMax If this is still an issue for you, could you send a screenshot?

**Comment by TechnikMax** [comment]
It looked like in the screenshot from above.  Since I restarted the Signal App the issue is now gone, maybe I didn't restart the App at all since the IOS update and this was the issue. @EvanHahn-Signal thanks for the quick replay and sorry for the false report.

**Comment by jonsherrard** [comment]
Is anyone else seeing this layout issue on iPhone 14 Pro? (With dynamic island), using iOS 16.01

![image](https://user-images.githubusercontent.com/631670/190877420-3caefc33-b782-460e-94b4-504d0eb22371.jpeg)

**Comment by adam-fallon** [comment]
https://developer.apple.com/documentation/technotes/tn3106-customizing-uinavigationbar-appearance

**Comment by EvanHahn-Signal** [comment]
We've made some changes to the status bar that should improve things in the next version. Please update when it comes out and let us know if that solves your issue!
