### ISSUE TITLE
Crashing while trying to transfer Signal data to new phone

### ISSUE THREAD

**Issue by rpincus-sudo** [signalapp/Signal-iOS#5392]
I hope I’m doing this right. Im trying to move my Signal data from an iPhone X to an iPhone 13 and the transferring is not working. App on the old phone is crashing every time I open it. I am going to try rebooting now…

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. 

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.
