### ISSUE TITLE
iPhones not getting messages when closing the app

### ISSUE THREAD

**Issue by braydofficial** [signalapp/Signal-iOS#5394]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you close the app on iOS you won't get any messages delivered until you reopen the app. Therefore, you also don't get notifications and could miss important messages for days.

### Steps to reproduce
Phone A = Any Smartphone with Signal installed
Phone B = An iPhone
- connect both phones to internet via mobile data or WiFi
- close Signal on Phone B (Swipe the app away)
- send message from Phone A to B

**Actual result:** Message will stay on send but not yet delivered and phone B will not get any notification until reopening Signal.

**Expected result:** Phone B should fetch for messages after a few seconds / minutes and should get the message delivered as well as receive a notification (if notifications are enabled from that contact of course)

### Device info
Tested with 3 iPhones from 3 different contacts
**Device**: iPhone X, iPhone 12 Pro & iPhone 13 Pro

**iOS version**: 15.5

**Signal version:** 5.44.0.8

Edit: 
### A small addition

I think it could have something to do with how iOS is handling apps that are closed and not running in the background. Maybe Apple "whitelists" other messengers where this isn't happening. However, Nextcloud has a feature to sync pictures in the background. They use the location permission to "revive" the app after it's closed every now and then, so the app can "do their thing" and still sync pictures periodically. Maybe the same could be used in Signal, if this is a restriction by Apple and not directly a bug by Signal (?).

**Comment by braydofficial** [comment]
### A small addition I forgot
I think it could have something to do with how iOS is handling apps that are closed and not running in the background. Maybe Apple "whitelists" other messengers where this isn't happening. However, Nextcloud has a feature to sync pictures in the background. They use the location permission to "revive" the app after it's closed every now and then, so the app can "do their thing" and still sync pictures periodically. Maybe the same could be used in Signal, if this is a restriction by Apple and not directly a bug by Signal (?).

**Comment by Doge7734** [comment]
I know Bitwarden requests to allow sending notifications so it can, I believe, sync in the background. But Signal already asks that permission. If this is an iOS issue, we’d have to wait for Apple.

**Comment by Naxterra** [comment]
I have the same issue too. I am not getting any notifications if I lock my phone or switch to another app. Reinstalling app didn't solve any problems, and notifications are enabled.

Device: iPhone 13 Pro Max
OS: iOS 16 Public Beta 4
App: 5.49.0.14

It is not a new issue, it has been like this for months and app is pretty much useless. I tried both stable and beta versions, same with iOS stable and beta too. Signal is not able to send notifications in iOS. Also, issue is not specific to my device. My wife has the same issue for months. She has 11 Pro Max, iOS 15.6.1 and latest stable version of Signal. We are even missing calls, not just messages.

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. 

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.

Thank you.
