### ISSUE TITLE
Unable to select more photos within the app to send

### ISSUE THREAD

**Issue by emreberge** [signalapp/Signal-iOS#5401]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I remember at some point that I was able to edit the list of selected photos, that sign al had access to, from within the app. But this hasn’t been the case for a while. Assuming this is a bug, as it feels like intention should be to allow users to select the photos they want to share through signal, from an interface printed within the signal app.

### Steps to reproduce
- make sure signal only has “selected photos” photo access
- Open a chat
- Go to camera
- Press photo library

**Actual result:** There is no way to select photos

**Expected result:** that a button to prompt the iOS “select more photos” dialog was present

### Device info
iPhone 12 mini iOS 15.4

**Signal version:** 5.44.0.10

**Comment by QuaqSim** [comment]
An important thing to note when trying to reproduce this is that Signal needs to have limited access to photos and none should be selected. When Signal has limited access and no images are selected, it presents the same message that would appear with full access to an empty library

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. 

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.

Thank you.
