### ISSUE TITLE
disabling Signal Pin crashes the App

### ISSUE THREAD

**Issue by dm3jan** [signalapp/Signal-iOS#5402]
### Bug description
When trying to disable the Singal Pin, the App crashes immediately.

This happens both when setting up Signal as well as when trying to deactivate it later on Account -> Advanced Pin Settings. Tested online and offline.

### Device info

**Device**: iPhone 13 mini

**iOS version**: 15.5

**Signal version:** 5.44.0.10

### Link to debug log

https://debuglogs.org/ios/5.44.0/2af0ceea021df7d3f52472b1289bf1e49d3d980a67d9b1d6f6eee3b90a623e19.zip

**Comment by dm3jan** [comment]
Unfortunately share a debug log from Signal's registration or PIN flow as described in [here](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) does not work. 

I do not understand at which menu point you have to press 8x. :)

Thanks once again for your work towards more privacy!

**Comment by clrkio** [comment]
I am also experiencing this issue.

**Comment by max-signal** [comment]
This should be fixed by bde3f174f31fb807fb84d56a989e7d6d044241f0, which is available in v5.47 and later.
