### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by mrpower55** [signalapp/Signal-iOS#5405]
hello i have fork signal and make every point on building the signal and it is build successfully but when it is start running it is showing error on database i guess

here is the flow that printed on log

2022-07-24 12:03:42:197 Signal[23210:210266] ❤️ [AppUpdateNag.swift:234 fetchLatestVersion(lookupURL:)]: assertionError: Missing or invalid record.

so please if anyone can help about that

looking forward for your help guys

thanks

**Comment by YanaSong** [comment]
I have the same problem. Have you solved it?

**Comment by mrpower55** [comment]
> I have the same problem. Have you solved it?

no i am not, i am waiting any help

**Comment by liangshiyi** [comment]
Any news? How to solve this problem？

**Comment by mrpower55** [comment]
> I have the same problem. Have you solved it?

i deleted the downloaded project and just fork and then run the app and it is run normally without doing anything else

don't do any steps on building guide and it will build successfully.

Good luck

**Comment by mrpower55** [comment]
> Any news? How to solve this problem？

i deleted the downloaded project and just fork and then run the app and it is run normally without doing anything else

don't do any steps on building guide and it will build successfully.

Good luck
