### ISSUE TITLE
Signal fails to open

### ISSUE THREAD

**Issue by bremoran** [signalapp/Signal-iOS#5406]
Signal was frozen. When I restarted signal, the problem persisted. After restarting my iOS device it generated this debug log:

https://debuglogs.org/ios/5.44.0/b9da486fe8a13ca5351e3532dafe4fa30c1327e10513d5f02339b9316c4544da.zip

**Comment by max-signal** [comment]
> Signal was frozen.

What was visible on the screen while it was frozen? Was it the logo? Or could you see your list of chats?

**Comment by bremoran** [comment]
It was the list of chats. I could not scroll and I could not enter any chat. When I restarted the app, it returned to the same screen (after the logo appeared, and disappeared) and was still frozen in exactly the same way.

**Comment by ltrainor12** [comment]
I had not used signal for a few months and had messages. The verify pin was frozen. There was message at top to update but that was frozen
