### ISSUE TITLE
https://debuglogs.org/ios/5.46.0/c14cc9e92da454949a7256059624b8d5ca75b482092b063acd1f105434529d49.zip

### ISSUE THREAD

**Issue by TarasTraffic** [signalapp/Signal-iOS#5408]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Doge7734** [comment]
Please fill out the bug report. This will help the developers to fix the bug you are experiencing.

**Comment by EvanHahn-Signal** [comment]
I'm going to close this because there's nothing actionable. Please describe your problem and we can take a look!

**Comment by TarasTraffic** [comment]
I’m not a coder, so I don’t know how to send report about bug. It was proposal from “signal”.
The main problem was it began starting and fly off and the screen returned to “home”. It was all time until reinstalling of app.

Хорошего настроения😀
