### ISSUE TITLE
Nejde spustit aplikace Signal po její aktualizaci

### ISSUE THREAD

**Issue by Jitka88** [signalapp/Signal-iOS#5414]
If you would like to discuss a new feature or submit suggestions, please visit the community forum:
https://community.signalusers.org

If you are looking for support, please visit our support center:
https://support.signal.org/
or email support@signal.org

Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Jitka88** [comment]
![5B059525-E0E8-40BB-AD01-CA4A5346C3EE](https://user-images.githubusercontent.com/110449640/182309573-6f8581aa-acca-43f0-b2ff-390717d8f757.jpeg)

**Comment by EvanHahn-Signal** [comment]
Please send debug logs.

**Comment by Jitka88** [comment]
Už jsem poslala. Nevím co se stalo, ale dceři Aplikace funguje. 

Odesláno z iPhonu

**Comment by EvanHahn-Signal** [comment]
Thank you. We will try to fix it.
