### ISSUE TITLE
Incoming group call only comes as notification, not as a ringing tone and ringing UI like when a contact calls you

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#5415]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Be a member of a group. A group member starts a group call. Instead of seeing the user interface for receiving a call like when a contact calls you, the group call only shows a notification like when you receive a text chat.

### Steps to reproduce
- be a group member
- someone start a group call
- 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

single notification like when receiving a text chat

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

ringing User Interface like when a contact calls you

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

### Link to debug log

https://debuglogs.org/ios/5.47.0/ae59848013ac05728e041c62cbd5a0b2692b394fbe6135a3201b14e12efd1f2a.zip1 

delete the 1 at the end, anti data harvesting bots

**Comment by mailinglists35** [comment]
all signal versions

**Comment by mailinglists35** [comment]
all android signal versions all android devices all android versions

**Comment by mailinglists35** [comment]
a notification is NOT how an incoming call is handled, thus I consider this a BUG in the design

**Comment by finn-signal** [comment]
Would you also be able to get logs from at least one of those other group members, specifically from the person who initiated the group call?

**Comment by EvanHahn-Signal** [comment]
We only use GitHub for bugs, so feature requests should be reported [in the community forum](https://community.signalusers.org/c/feature-requests/17). I'm going to close this.

Also: this is something that's on our radar, and should be released in an upcoming version. Stay tuned!
