### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by melissawellssimpson** [signalapp/Signal-iOS#5416]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ x] I am submitting a bug report for existing functionality that does not work as intended
----------------------------------------

### Bug description
Not receiving notifications on iPhone XR V15.5.

### Device info

**Device**: iPhone XR

**iOS version**: 15.5

**Signal version:** 5.47.0.9

**Comment by finn-signal** [comment]
Would you be able to send me the message ID for one or two of the messages that you did not get a notification for? And could you please include your iOS debug log? _Both items are important._

To send a message ID, long-press on the message bubble, select the info icon that appears at the top of the screen, then long press on the received time stamp to copy the message ID. There will be no feedback in the app to copy the message ID, but it will be copied. Then paste the message ID in this email here.

To share a debug log from Signal iOS, tap your profile, Help, Submit Debug Log, Copy Link, then open this email, long-press and choose paste to paste the link.

**Comment by melissawellssimpson** [comment]
https://debuglogs.org/ios/5.47.0/265a07b69e8744553f3ac11dc9d6b0bf2acb51314738b05d592202b7f26c9f91.zip

When I follow the directions to get the message ID, nothing can be pasted into the email, a note, etc.
I have attached a few screenshots of what I do see.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by finn-signal** [comment]
Ok, not a problem. We're investigating the issue.
