### ISSUE TITLE
Can't see or download videos sent by a Android signal

### ISSUE THREAD

**Issue by oversanne** [signalapp/Signal-iOS#5419]
Hello,

I'm in a signal group of 4 people: 
- 2 android (me 5.44.3, & someone else)
- 1 iOS 15.6 with Signal 5.46.0.12
- 1 other iOS (I don't have the info)

I'm sending a MPEG video of 7MB in the group. 

The 2 Android can see & download the video, but the 2 iOS can't see or download the video.

Screnshot attached to see what they got:
![signal-2022-08-05-105014](https://user-images.githubusercontent.com/1726577/183043068-d86416ca-12a7-49be-a584-be7cc02ecf53.jpeg)

And when clicking on it, "Impossible de voir la vidéo" (French)

Anything you could do to help fixing it?

Thank you a lot for your support!

**Comment by trasba** [comment]
We have the exact same issue.
This is closed but what was the outcome?
