### ISSUE TITLE
Signal app crashes when trying to delete a message

### ISSUE THREAD

**Issue by rizwan95** [signalapp/Signal-iOS#5422]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to delete a conversation, the app crashes. I am attaching the crash report for your reference.

### Steps to reproduce
- Open a conversation that has media also. 
- Try to delete it.
- The app will crash. 

**Actual result:** The conversation must be deleted. 

**Expected result:** The app crashes. 

### Device info

**Device**: iPhone XR

**iOS version**: iOS 16.0 (20A5312j)

**Signal version:** 5.49.0.11

### Link to debug log
I have sent the crash report via email as per your directions.

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. 

Go to Signal Settings (profile) > Help > Contact us. Make sure to include the debug log.

Thank you.
