### ISSUE TITLE
Signal no longer crashing, but manifests bugs with PIN creation, searching for registered users, & receiving messages.

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#5424]
I am picking up on [this issue](https://github.com/signalapp/Signal-iOS/issues/5339), which has improved since the last time I was able to get access to the phone.

iPhone 8 - MQ8X2LL/A
Running iOS 15.4
5.49.0.13 - updated tonight.

Signal at least runs, so now I can get a [debug log](https://debuglogs.org/ios/5.49.0/7ea4d88e3c581ff2e3ccf8aa56a85562c46c5d96e4b4cb54f062f5726a0e9506.zip).

Symptoms:

1. When asked to create a pin, and then for the pin to be confirmed, a spinner is presented and then, "PIN Creation Failed.  Couldn't create your PIN.  Check your connection and try again."  This is repeatable even though he's definitely connected to the internet.

2. When he tries to search for my phone number, or I try to search for his, we get, "Error.  Contact is not a Signal user."  

3. Even though I am in his phone's contact list, and have been for a long time, I do not appear in his Signal contact list.  He does never the less appear in my Signal contacts list.  When I try to text him, I get "Send Failed" and a red circle with an exclamation point in it.   

I see him only occasoinally, but even if he is not very techie, he is motivated to get on.  So I'll get as much info as I can.

**Comment by finn-signal** [comment]
Thanks, this is incredibly helpful and quite a thorough bug report.

It seems you provided your friend's logs, but could you attach your logs as well? Ideally you could reproduce this behavior once more and _then_ send a new set of your logs in. We need both sets of logs generated within a few hours of each other.

**Comment by DiagonalArg** [comment]
@finn-signal 

Here is the [log](https://debuglogs.org/ios/5.49.0/ef40c87106c112bb6ee504faa9a56f754b323d519ab6755bc2d3cd964cb673ba.zip) from my iPhone SE (gen.1), running Signal 5.49.0.13 and on iOS 15.6.1. That log was generated immediately after searching on his number and receiving the response, "ERROR: Contact is not a Signal User."

On my laptop, Ubuntu 22.04 running Signal 5.56.0, I see in our chat log (which contains one message from April this year that did not arrive on his end), I see:

![image](https://user-images.githubusercontent.com/5190243/187002566-7d5114b6-f781-4cf3-b097-e77096fddbae.png)

I'm sorry that I will not be able to do the search on each other's numbers close in time.  As I say I only get to see him occasionally.  Next time I get the chance, and if the behavior hasn't changed, I will try.

**Comment by DiagonalArg** [comment]
@finn-signal - Ok, I got it!

We searched using his phone and got [this log](https://debuglogs.org/ios/5.49.0/b30bf19bed46b82cf2a2db1872178b6fcc9e35eafcb88daed028c1b5880240c7.zip).

Then immediatly after, we searched using my phone, and got [this log](https://debuglogs.org/ios/5.49.0/75e2d96e47949f547001d1f78ce43c2a5d4504e6884bcbb733140bafbbb58b27.zip).

Not that he does appear in my list of chats, though not his.  We used the "Find by Phone Number" function.

**Comment by finn-signal** [comment]
Excellent, thank you.

And to be clear, by using the "Find by Phone Number" function, you eventually were able to message your contact on Signal (although, seemingly unsuccessfully, based off your message that the message is a "red exclamation")? Even still, would you be able to send the Message ID for one of the messages you sent him?

To send the message ID, long-press on the message bubble, select the info icon that appears at the top of the screen, then long press on the received time stamp to copy the message ID. There will be no feedback in the app to copy the message ID, but it will be copied. Then paste the message ID in this email here.

**Comment by DiagonalArg** [comment]
> And to be clear, by using the "Find by Phone Number" function, you eventually were able to message your contact on Signal (although, seemingly unsuccessfully, based off your message that the message is a "red exclamation")? Even still, would you be able to send the Message ID for one of the messages you sent him?

No.  He appears in my list of chats because I had attempted to message him months ago, which was a time when Signal was crashing on his end.  (See the [issue](https://github.com/signalapp/Signal-iOS/issues/5339) I mentioned in the OP.)

> Sent | Apr 7, 2022 12:18 AM (1649315916551)

There is nothing sensitive in the message, which was:

> ... I see you're saying Signal is crashing, but it nevertheless does see you as registered.  So I thought I'd send a message.  Let me know if you get this.

He did not receive it.

**Comment by finn-signal** [comment]
Thanks for the reply.

I oddly don't see that message ID in either set of logs. Did you send it a bit before those logs were generated?

Since I can't seem to find it, could you try one more time to send a message, collect the message ID and then get a new set of both of your logs (including your linked device)?

Since logs only contain a few days' worth of information, we need log links that are all sent within the same time of each other so that the time window contains the corresponding errors. That would be mean that we'd have logs from both you and your contact that were generated within hours of each other. Otherwise, our engineering team isn't able to piece together the errors because the logs don't paint a complete picture.

Again, appreciate your help with all this.

**Comment by DiagonalArg** [comment]
@finn-signal 

> I oddly don't see that message ID in either set of logs. Did you send it a bit before those logs were generated?

Well yes.  You see it was sent on April 7 of this year.  All logs posted here were generated in the last 10 days.

> Since I can't seem to find it, could you try one more time to send a message, collect the message ID and then get a new set of both of your logs (including your linked device)?

I can't send any messages.  I've twice now posted the image that appears on my Desktop Signal when I enter the chat.  It says, "This person isn't using Signal.  Siganal Desktop does not support messaging non-Signal contacts...."

> Since logs only contain a few days' worth of information, we need log links that are all sent within the same time of each other so that the time window contains the corresponding errors. 

Then you will have to foget about this past message on April 7th.  There have been no messages since then, and neither of us can find the other using "Find by Phone Number."  So there is no way to send a message from either side.

> That would be mean that we'd have logs from both you and your contact that were generated within hours of each other. Otherwise, our engineering team isn't able to piece together the errors because the logs don't paint a complete picture.
> 
> Again, appreciate your help with all this.

I've tried the best I can to be clear.  Ask other questions if you need to, but perhaps read this thread again?

**Comment by DiagonalArg** [comment]
Really?  You're not still working on this?  After all thw work I did to get you those debug logs?  And after I was told, "Thanks, this is incredibly helpful and quite a thorough bug report."

This is a serious issue with someone who can't get Signal to work at all on an iPhone 8.  Would you please reopen and do something with this issue?

**Comment by DiagonalArg** [comment]
Could someone please look at this??
