### ISSUE TITLE
Can't leave chat after sending gift badge

### ISSUE THREAD

**Issue by maba4891** [signalapp/Signal-iOS#5425]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send contacts a gift badge (using the new feature) I can't leave the chat after that by clicking on the "back" arrow in the upper left. In fact the whole top navigation bar (back button, profile picture, phone call button, video call button) is not responding when I click on it. After restarting Signal and entering the chat again everything works again. I tried three times and everytime the same behavior.

### Steps to reproduce
- send a contact a gift badge (it's a quite expensive way of bug hunting, I know ;) )
- while still in the chat of that contact try to click the back button (or any other button) in the top navigation bar

**Actual result:** Buttons in the top navigation bar don't work

**Expected result:** That something happens when I click on these buttons

### Device info

**Device**: iPhone XS

**iOS version**: 15.6.1

**Signal version:** 5.49.0.13

### Link to debug log
https://debuglogs.org/ios/5.49.0/6313c51e31171e16f0fb26b835edb623434c82c83e3858515f4168da20fd6440.zip
(I have to restart Signal before generating the bug report because I'm stuck in the chat view)

**Comment by EvanHahn-Signal** [comment]
This is a known issue that should be fixed in an upcoming version. Thanks for supporting Signal!

**Comment by maba4891** [comment]
Great, thanks for the quick reply and keep up the great work!
