### ISSUE TITLE
Send a badge with emoticon as text processes transfer but doesn't send message

### ISSUE THREAD

**Issue by freekvh** [signalapp/Signal-iOS#5427]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I send a badge with an emoticon as text and it processed the transfer but doesn't send the message

### Steps to reproduce
- Send a badge, add an emoticon from the iOS keyboard as text
- Get message that badge can't be delivered

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- It should just send the emoticon text

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![2022-09-06 15-02-09-0](https://user-images.githubusercontent.com/12241293/188642210-3ac125ed-78b8-47e9-aca6-32a8edf2489e.png)

### Device info

**Device**: iDevice X

**iOS version**: 15.6.1

**Signal version:** 5.49.0.13

**Comment by freekvh** [comment]
Actually I think that the payment was also not processed (blocked by my bank) in the transfer that concerns this message. A later transfer did work (without emoticon and with a MasterCard Applepay card).

**Comment by harry-signal** [comment]
Thanks for reporting! I've tracked this issue internally so we can get to it in a future sprint.

If you can, could you go to Signal Settings (profile) > Help > Contact us and send us a bug report with a debug log? Especially if you are able to trigger this again.
