### ISSUE TITLE
SECURITY ISSUE: Signal doesn't strip EXIF from sent images, including precise location data

### ISSUE THREAD

**Issue by databonanza** [signalapp/Signal-iOS#5429]
Bug description

Signal for iOS includes EXIF data in sent images, including precise GPS data if present. Instead, EXIF data should be stripped (possibly except for the absolute bare minimum such as dimension and rotation).
Steps to reproduce

    Enable Location access for Camera.app
    Take a picture with Camera.app
    Send that picture from the Camera Roll using Signal
    Recipient uses the share sheet to save the image, then opens it in an app such as ExifWizPro

Actual result: Recipient sees the precise location the image was taken, along with all other EXIF fields
Expected result: Recipient sees no EXIF data whatsoever, as is the case when using Threema
Device info

Device: iPhone 13 Pro
iOS version: 15.6.1
Signal version: 5.49.0.13

@charlesmchen-signal 
@Imperiopolis-Signal 
@charlesmchen 
@michaelkirk 
@michaelkirk-signal 
@michelle-signal 

^^^ You guys all have over 1000 commits to this repo.  Does someone want to speak up?

**### This ticket was closed multiple times by the "Stale Bot" and then shamelessly copied from:

https://github.com/signalapp/Signal-iOS/issues/1984

We need some response from the developers on this very important issue.  I'd suggest everyone using Signal that cares about security to stop using it to send photos to people until it has proper exif data stripping added to it.**

**Comment by m-graf** [comment]
See https://github.com/signalapp/Signal-iOS/issues/1984#issuecomment-1240890847. 

This is no longer an issue.
