### ISSUE TITLE
Messages from one iOS contact are received several days late 

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-iOS#5431]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm receiving messages from one iOS contact much later than when they were sent. This has happened intermittently for many months. This contact says that she receives notifications for my messages just fine. I have no trouble receiving messages from any other contacts - just this one.

If this contact sends several messages in quick succession, I receive all of those messages at the same time, but often they are delayed by several days.

In the example I have attached debug logs for, I received a group of messages 6 days after the contact sent them.

### Steps to reproduce
I'm not sure. My guess is that this contact might be closing Signal before the messages are sent to the server, and that they only get sent when she opens the app up again several days later to check if she has any messages from me (I'm the only person she uses Signal with).

This could possibly be related to #5354 

**Actual result:**
Messages are received several days after the contact presses "Send" on her device.

**Expected result:**
Messages are received shortly after the contact presses "Send" on her device.

### Screenshots

"Sent" timestamps of messages which were delayed:
1661267863085
1661268055078
1661268103149
1661268159472

### Device info

My device's info:
**Device**: iPhone 11

**iOS version**: 15.6.1

**Signal version:** 5.53.0.5

### Link to debug log

Debug log from my contact's iPhone:
https://debuglogs.org/ios/5.49.0/bf9b72892c7b360ab4a531316ac618c52808ead8fb118dfefc239dc0cd432b1b.zip

Debug log from my iPhone:
https://debuglogs.org/ios/5.52.0/c4c63fad0161029722d1e9eae833e49fd7971189d43d93f21c6f0c3cc075f49e.zip

**Comment by EvanHahn-Signal** [comment]
Looking at their logs, it seems that they tried to send a message but had network difficulties. Days later, the message was resent. It's possible that it was automatically resent, but that would be a bug. I suspect they chose to resend it manually. Could you ask them if that's what happened? Did they intentionally resend these failed messages?

**Comment by azuredusk10** [comment]
I just asked, and yes they said they did resend the messages manually

**Comment by EvanHahn-Signal** [comment]
In that case, this doesn't seem like a bug—it seems like they had network issues. I'm going to close this issue.

Thanks for reporting!
