### ISSUE TITLE
Please reopen #4916

### ISSUE THREAD

**Issue by sgreadly** [signalapp/Signal-iOS#5435]
Please reopen #4916

Signal for iOS/iPadOS is taking up too much space even though all media is deleted #4916

We've been writing there constantly. Issue is not resolved, and is very serious. 

@harry-signal @sashaweiss-signal @igor-signal @Imperiopolis-Signal

**Comment by ferid-akifzade** [comment]
It should be first thing to do.

**Comment by EvanHahn-Signal** [comment]
Done.
