### ISSUE TITLE
Cannot register my account

### ISSUE THREAD

**Issue by Naxterra** [signalapp/Signal-iOS#5436]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ X ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I reformatted my iPhone 13 Pro Max from ipsw file, because I needed to go back from iOS 16.1 Public Beta to iOS 16 Official version. I reinstalled my apps from my previous iCloud backup. After that I tried to setup Signal again but it is not working. 

### Steps to reproduce
- Enter my mobile number
- Get SMS code and pass verification
- Enter PIN code for the account and it blocks my account
- Go back to step one
- App is no longer accepting SMS verification codes. I tried several times after waiting one minute between each verification codes but Signal is rejecting all of them.
- Delete Signal and reinstall from App Store
- Go to step one and it fails again after I enter my PIN code

**Actual result:** Signal blocks my account and wants me to wait 7 days to reset my account, which is not acceptable

**Expected result:** Signal should accept SMS and PIN codes as a normal app would do.

### Screenshots
![grafik](https://user-images.githubusercontent.com/41871948/190873551-b3929587-3426-4c7d-8adf-e0c45aa4c6ed.png)

![grafik](https://user-images.githubusercontent.com/41871948/190873559-19d2b93b-95b7-40b2-acbc-fdb862a549ff.png)

![grafik](https://user-images.githubusercontent.com/41871948/190873564-70be6167-3d01-4125-bd95-50c4a1cc367b.png)

![grafik](https://user-images.githubusercontent.com/41871948/190873577-93fa78ce-3d7e-40b3-97e0-e6d3ca9c964e.png)

![grafik](https://user-images.githubusercontent.com/41871948/190873582-ffabb98e-09be-42b4-8327-be9bae8c615e.png)

![grafik](https://user-images.githubusercontent.com/41871948/190873589-ba47b8e7-012e-484b-8001-0ca46fcd4e2e.png)

![grafik](https://user-images.githubusercontent.com/41871948/190873602-d0d14672-eb11-4a18-899a-25762a46ff11.png)

### Device info

**Device**: iPhone 13 Pro Max

**iOS version**: 16.0

**Signal version:** 5.51

### Link to debug log
There are no logs.

**Comment by GatoPharaoh** [comment]
Did you use a testflight beta of signal before resetting your device? 

I had the exact same issue after setting up a new iPhone and loading Signal from the App Store instead of getting the beta version from testflight i used before. 

Even though the app said my account was blocked for 7 days, it worked prefectly fine after downloading and registering in the the beta app.

**Comment by GatoPharaoh** [comment]
also, you did not redact your phone number in the last screenshot

**Comment by Naxterra** [comment]
> 

Thanks for the info :) I removed last screenshot.

Latest beta in TestFlight worked now but it has bugs. For example if I select restore from old phone and then cancel it, it blocks my account for one hour. Reinstalling app won’t solve that problem but at least after one hour I managed to get my account back

**Comment by harry-signal** [comment]
Thank you for this bug report! What GatoPharaoh said is accurate; we had this issue when "downgrading" from Beta (Testflight) builds to Public (Appstore) builds. This has now been resolved and you should be able to switch between Testflight and the latest Appstore release if you so desire. Sorry for the trouble!
