### ISSUE TITLE
Signal Crashes when Recording a Video

### ISSUE THREAD

**Issue by Doge7734** [signalapp/Signal-iOS#5438]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When recording a video using Signal’s camera it crashes to the Home Screen.

### Steps to reproduce
- start a video recording
- Release finger off of button
- Signal crashes to Home Screen

**Actual result:** Signal crashes to Home Screen. 

**Expected result:** Signal doesn’t crash and I can record a video and send it.

### Device info

**Device**: iPhone 12 Mini

**iOS version**: 16.0

**Signal version:** 5.51.2.0

### Link to debug log
 https://debuglogs.org/ios/5.51.2/6e7a78fbb0bfcf6412f0c3727047de1e0fd0c1c365f0099a7f32d832564b6285.zip

**Comment by Doge7734** [comment]
Additional information: Signal crashes if you do NOT give it microphone permission. Not sure if this is a bug, but since it crashes it seems like one. Maybe Signal could add a message about needing microphone permission enabled?

**Comment by finn-signal** [comment]
We responded to you via the email you sent us. Thank you.
