### ISSUE TITLE
Area behind handle of group call participant sheet is more transparent than the sheet itself

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5445]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The area behind the handle of the group call participant sheet is more transparent than the sheet itself.

### Steps to reproduce
- Join a group call.
- Press the "call participants" button.

**Actual result:** The area behind the handle is more transparent than the sheet itself.
**Expected result:** The area behind the handle should have the same transparency as the sheet itself.

### Screenshots
Note that the video frame continues further below the handle background and has the same color; it doesn't end or change exactly where the handle background ends and the main sheet content begins.

<img width="300" src="https://user-images.githubusercontent.com/19972511/193462922-b9291580-4019-4b6b-9000-bc21995c1fee.jpeg">

### Device info
**Device**: iPhone XR
**iOS version**: iOS 16.1 Public Beta (20B5056e)
**Signal version:** 5.56.0.14

### Link to debug log
n/a

**Comment by harry-signal** [comment]
Thanks for reporting! This will be fixed in the next beta release (coming soon)
