### ISSUE TITLE
Chat header information disappears if iPhone is rotated during media selection / editing

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5446]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Chat header information disappears if iPhone is rotated during media selection / editing.

### Steps to reproduce
- Ensure iPhone is in a portrait orientation, rotation lock is disabled.
- Open a chat.
- Press the "+" button to add an attachment.
- Press the "gallery" button. (Or also select a photo and press the "next" button.)
- Rotate the iPhone to any horizontal orientation.
- Rotate the iPhone back to portrait orientation.
- Press "cancel". (I.e. return to the chat; if you previously started editing a photo this will take more than one button press.)

**Actual result:** The chat header is missing most of the chat information. Sometimes, the group call button appears (this bug also happens for 1:1 chats though, I've not tested whether call buttons can appear there as well but I assume they can).

**Expected result:** The chat header should not be affected and should show all information.

### Screenshots

Before reproducing bug | After reproducing | After reproducing (group call button appeared)
-|-|-
![](https://user-images.githubusercontent.com/19972511/193463888-b2adeedb-0002-4c9c-a18a-9749fc54216f.jpeg) | ![](https://user-images.githubusercontent.com/19972511/193463894-91ba788c-0cb5-4e4d-bc2b-6a64676f2fc9.jpeg) | ![](https://user-images.githubusercontent.com/19972511/193463891-e909698a-d714-4712-8f97-eab4da8ddb2b.jpeg)

### Device info
**Device**: iPhone XR
**iOS version**: iOS 16.1 Public Beta (20B5056e)
**Signal version:** 5.56.0.14

### Link to debug log
https://debuglogs.org/ios/5.56.0/0c4a81d07cdf3ccbae9d16d627f49c47e4fd035635a618e60bd272153ec90fa0.zip

**Comment by Doge7734** [comment]
Interesting. I am unable to reproduce on my iPhone 12 Mini, iOS 16.0.2, Signal version 5.55.0.14

Wait, you’re on the beta. GitHub is only for bug reports for a released version of Signal.

All beta bug reports should be done here in the iOS beta thread: https://community.signalusers.org/c/beta-feedback/25

**Comment by Doge7734** [comment]
Hmm, you may be correct then. AFAIK, if you are on the beta and you discovered a bug to report it on the beta thread. Also probably keeps it easier since someone reporting a bug on the beta (whether it's a new feature/change or not) will be in the same place.

**Comment by u32i64** [comment]
I'm still able to reproduce on:

**Device:** iPhone XR
**iOS version:** iOS 16.3 Public Beta (20D5024e)
**Signal version:** 6.6.0.15

https://debuglogs.org/ios/6.6.0/e944b1c7341f90b4eb62357177568708aed573666c8368292b9b810dd655cbb6.zip

**Comment by u32i64** [comment]
Can't reproduce on:

**Device:** iPhone XR
**iOS version:** iOS 16.5 Public Beta (20F5028e)
**Signal version:** 6.20.0.9
