### ISSUE TITLE
'Read more' missing for longer group descriptions

### ISSUE THREAD

**Issue by nataliasc** [signalapp/Signal-iOS#5448]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If a group description has line breaks, everything after the first line break appears to be cut off, and the full description cannot be accessed from the group information screen.

### Steps to reproduce
- Open group profile with a description that has line breaks
- No "read more" link is visible; group description is cut off

**Actual result:** Full group description cannot be accessed

**Expected result:** A "read more" link should be visible (e.g. like in the macOS version)

### Screenshots

![IMG_9231](https://user-images.githubusercontent.com/4141182/194847504-8c776d38-06e5-42c2-a9b7-0f04591c3024.PNG)

![IMG_9232](https://user-images.githubusercontent.com/4141182/194847620-a5f7f275-cdbe-401d-8dc5-6df62fb3295e.PNG)

### Device info

**Device**: iPhone 12

**iOS version**: 16.0

**Signal version:** 5.56.0.24

**Comment by EvanHahn-Signal** [comment]
Thanks for this. I've filed a bug in our internal tracker.

**Comment by Lunatmp** [comment]
Needless to say, I also suffer this issue. Have been for months. I suffer from it quite a bad cause a group I am in posts frequent updates jn the description, which I am not able to view.

**Comment by briankung** [comment]
We keep a lot of useful information in these descriptions and this has made the app much less usable for us.

**Comment by max-signal** [comment]
This is fixed by 96c4823a8a0393dc659ac80dd753994b112f6cca, which is available in v6.7 and later.
