### ISSUE TITLE
Bug: Fail Transferring from iOS Device

### ISSUE THREAD

**Issue by marco022345** [signalapp/Signal-iOS#5450]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backup and Restore Messages. Cannot transfer from old iPhone(8) to new iPhone(13). Latest iOS versions, latest Signal versions.
Follow every requirements and procedures on https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore . Even tried on Beta.

### Steps to reproduce

- open Signal on new iPhone, start sync procedure
- use old iPhone to capture QR code with camera
- old iPhone changed to connecting than to transferring 
- new iPhone remained in the QR code screen

**Actual result:** The transferring bar on the old iPhone is not moving at all, and the QR code screen remained on the new iPhone screen, i tried to put two phones together for 8-9hrs and the situation remain the same.

**Expected result:** Easy procedure, scan the QR code, start transferring after connecting, wait for 5-10 mins, done done.

### Screenshots
![WhatsApp Image 2022-10-08 at 12 13 05 PM](https://user-images.githubusercontent.com/115474639/194877150-bcd811e1-7623-4694-82d1-5be38ce34307.jpeg)

### Device info

**Device**: iPhone 13 and 8

**iOS version**: 15.7(19H12)

**Signal version:** 5.56.0.24

### Link to debug log
iphone13
https://debuglogs.org/ios/5.56.0/31f74cb8f56335846fb4f481f0275a2aad215b3017684182af227293d6f41cc1.zip
iphone8
https://debuglogs.org/ios/5.56.0/f31d48896c9ee4ad8fb462dd1625a0e3d059fe280fa7cc826a9d9e2cb4f1b6be.zip

**Comment by marco022345** [comment]
Grateful for any help! The chat records are really precious!

**Comment by marco022345** [comment]
i think my old iPhone is crashed every time when it is on the transferring screen. As i cannot press the cross botton to cancel it, i can only turn off the apps and try every procedure again.

**Comment by marco022345** [comment]
keep trying everyday and waiting for help!

**Comment by fabioarnold** [comment]
I have the same issue transferring from an iPhone SE 2020 to an iPhone 14 Pro. Both are on iOS 16.0.3 with the latest Signal version (5.56.0.24).

Logs of the iPhone SE 2020: https://debuglogs.org/ios/5.56.0/8186689641fb12fc8cba6f6dc708a53078bef99062fd6f14b76788a0c27eb93d.zip

Log from the connected debugging Console App:
[signal.log](https://github.com/signalapp/Signal-iOS/files/9771753/signal.log)

Logs of the iPhone 14 Pro:
https://debuglogs.org/ios/5.56.0/db2a153bf453e8ef01ab1d3d22c94ba9429d2aca0778444043cdb6ee56f08cb8.zip

**Comment by marco022345** [comment]
Have updated to Version 5.57, still cannot transfer date successfully.
Please help!

**Comment by marco022345** [comment]
Any hints why this situation occurring?

**Comment by marco022345** [comment]
How can I turn on Location for signal on my new iPhone? 
There is no such options on my new iPhone for signal.
Thank you!

**Comment by marco022345** [comment]
i turned on the location for signal on my new iPhone.
but i can transfer my data successfully.
both of my phone have updated to the new version.
what is the problem?

**Comment by Rubbishe** [comment]
same here, ios transfer to ios keep stuck at "Transferring Data" Keep both device near each other...., the loading bar not loading at all. And error massage popup after few hours said "The transfer couldnt complete, please ensure your devices are near each other."

Ive been trying this for month, tried different methods, sent support tickets & followed every requirements and procedures. Please help.

**Comment by Rubbishe** [comment]
* 		I have searched open and closed issues for duplicates
* 		I am submitting a bug report for existing functionality that does not work as intended
* 		This isn't a feature request or a discussion topic

Bug description
I have a new iPhone that is on iOS 16.0.3 and am trying to transfer from an older iPhone that is also on iOS iOS 16.0.3. I'm able to read the QR code with the old phone. I see the "connecting" animation, then move on to “transferring data” but the bar is not loading for hours, and then I get the following message. “The transfer couldn't complete, please ensure your devices are near each other and try again”

Steps to reproduce
* Power on 2 iPhones with iOS 16.0.3
* Reset privacy and location
* Updated to the latest version and beta version. Check again local network, bluetooth is on on both device
* Initiate account setup transfer with new phone
* Scan QR code with old registered phone

Actual result:
Transferring Data Page popped up but not showing and progress for 15mins to 6hours. Error message indicating that the transfer couldn't complete.

Expected result: Transfer of data from old phone to new phone.

Device info
New Device: iPhone 14Pro
iOS version: iOS 16.0.3
Signal version: 5.59.0 (13)

Old Device: iPhone XS
iOS version: iOS 16.0.3
Signal version: 5.58.0.12

Link to debug log
iPhone 14Pro: https://debuglogs.org/ios/5.59.0/30f92529fc3acd826762a3495cc3c43ab3cc764097d1b7132efab18185fd9629.zip
iPhone XS: https://debuglogs.org/ios/5.58.0/5baa1628acd1ffb061e0727642d815bce7bc3dfc4769f32510b2d7ed47f82e75.zip

**Comment by Edwardbbb123** [comment]
same result as The transferring bar on the old iPhone not moving at, and the QR code screen remained on the new iPhone screen

i am transferring from Xr to 14 pro.

**Comment by NiklasBr** [comment]
I'm still experiencing this, we are awaiting developer response.

**Comment by tilo** [comment]
THIS IS STILL HAPPENING!!! 

@charlesmchen @charlesmchen-signal please re-open or provide a comment with the solution. 

iPhone 11 Pro Max -> iphone 14 Pro Max
iOS 16.5          -> iOS 16.5.1

**Comment by youjackal** [comment]
this ticket should not be Closed, the bug never get fix!

**Comment by guestguestguestguest** [comment]
I have the same issue but never even see a transfer bar, it just immediately displays the "transfer couldn't complete" error after getting the qr image.  Moving from iphone XR to iphone 15 pro, signal version 6.42.0.18
