### ISSUE TITLE
Avatars slightly misaligned in contact pickers

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5451]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The avatars shown at the top of various pickers seem to be slightly lower than they should be. For example, in the viewer picker for private stories, in the picker for adding people to groups, etc.

### Steps to reproduce
1. Create a private story or edit an existing one > tap "Add Viewers".
1. Select one or more users to add to the story.

Or:
1. Go to the chat info / settings of a group.
1. Press "Add Members".
1. Select one or more users to add to the group.

**Actual result:** The avatars shown at the top are not vertically aligned with the background.

**Expected result:** The avatars shown at the top should be vertically aligned with the background.

### Screenshots
<img src="https://user-images.githubusercontent.com/19972511/195091719-f3981ab4-145f-43bb-8081-29f509c84f43.jpeg" width=500>

### Device info
**Device**: iPhone XR
**iOS version**: 16.1 Public Beta (20B5064c)
**Signal version:** 5.57.0.13

### Link to debug log
https://debuglogs.org/ios/5.57.0/059a21eba4c0af7d93f40dd7a13c183be8dacc1040b8c501a9360ab5f7af8dc9.zip

**Comment by EvanHahn-Signal** [comment]
Thanks for reporting. I've filed this bug in our internal tracker.

**Comment by u32i64** [comment]
This is still reproducible on:

Device: iPhone XR
iOS version: iOS 16.3 Public Beta (20D5024e)
Signal version: 6.7.0.20
