### ISSUE TITLE
Overactive background noise suppression/cancellation for iPhone speakerphone

### ISSUE THREAD

**Issue by ElijahLynn** [signalapp/Signal-iOS#5452]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On an iPhone 13 there seems to be overactive background noise suppression/cancellation on the speaking voice to the receiver. 

### Steps to reproduce
- Make a call from an Android to the iPhone, the iPhone needs to be on speaker phone mode, the Android can be speaker or headset, it does not matter
- The iPhone user will talk and the Android user will hear very cut out audio
- If the iPhone user switches to a headset then their audio will sound perfect to the Android user
- OR, if the Android user mutes their microphone then the iPhone user on speakerphone will also have perfect audio when they speak.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behavior)
iPhone microphone is getting actively noise cancelled and voice gets cut off

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Voice doesn't get cut off. 

I'll get more info and populate then, gonna report this for now

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by EvanHahn-Signal** [comment]
Could you get debug logs from your device _and_ your friend's device?

**Comment by ElijahLynn** [comment]
I will see if I can do that soon, thanks for the suggestion. 

I forgot to mention that it also happens with Google Meet (formerly Google Duo), so it almost seems like some layer is doing background noise suppression. And I know that I saw reports of it being removed in iPhone 13. Just talking outloud here. 

I will work on getting the logs during our next call.

**Comment by Tursko** [comment]
We should re open this. Having the same issue.
