### ISSUE TITLE
Donation Bug

### ISSUE THREAD

**Issue by Jeanmarchp** [signalapp/Signal-iOS#5456]
Bug description

I donate every month to signal. After the latest update the donation pop up will pop up every single time you open the app. 

Steps to reproduce

Open Signal
Donate one time donation after that the message will pop up every time. 

Expected result:
Donation pop up should disappear if donation badge is active 

![image](https://user-images.githubusercontent.com/9320159/196333839-118e63f2-adbe-40da-b984-7adebdea6bc4.jpeg)

**Comment by finn-signal** [comment]
Please write in from within the app so we can better understand what the issue is. Go to Signal Settings (profile) > Help > Contact us. 

Make sure to include the debug log.

Thank you.
