### ISSUE TITLE
Last line of unicode text (e.g. emoji / Chinese characters) in photo editing mode is trimmed

### ISSUE THREAD

**Issue by kenime** [signalapp/Signal-iOS#5461]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When adding unicode text (e.g. Emoji / Chinese character) in photo editing mode, the text wrapping is not working and the last line of text is trimmed.

### Steps to reproduce
- Take a photo or select a photo from library
- Enter photo edit mode
- Type unicode characters (e.g. Chinese / emoji)

**Actual result:** The text wrapping is not working as intended. If there is multiple lines, the character will be trimmed vertically.

**Expected result:** It should wrap as intended, and multiple line text should be shown correcting

### Screenshots
![C8F1957A-74E5-4356-88A4-5782C6EA40FE](https://user-images.githubusercontent.com/3585634/196853288-5e77dd9a-9931-46dc-98e6-9030af88bc66.jpg)
![E36258D7-5846-46A1-9C48-23E67ACB1416](https://user-images.githubusercontent.com/3585634/196853297-326a65ff-94cb-46c1-a481-8948c9e5f3e8.jpg)

### Device info

**Device**: iPhone 13 Pro

**iOS version**: 16.0.3 to 16.1

**Signal version:** 5.59.0.5

### Link to debug log
(Signal prompted could not find any logs)

**Comment by harry-signal** [comment]
Thank you for reporting! We are tracking this issue and will try and get a fix out soon.
