### ISSUE TITLE
Photo download should preserve metadata

### ISSUE THREAD

**Issue by jesspaugh** [signalapp/Signal-iOS#5464]
1. Select lots of pictures from a chat to download 
2. Download photos. Examine metadata in iOS photos app

expect: date/time taken was the actual date/time the photo was taken
Actual: the date/time reflects when the photo was downloaded. This means that if I download several photos at once the order in the native app is random instead of chronological.

**Comment by EvanHahn-Signal** [comment]
Image metadata sometimes contains harmless information, but it often contains sensitive data like a location. Many users don't know this and might accidentally send private info without realizing.

Signal intentionally strips image metadata for privacy reasons.

If you'd like to discuss this further, check out [the community forums](https://community.signalusers.org/c/feature-requests/17).

**Comment by NiklasBr** [comment]
©EvanHahn-Signal I think you are misunderstanding this issue. It is not about sending with/without metadata. It is about preserving the metadata which was actually sent.

In very simple terms these steps happen:
1. Prepare to send an image
2. Send an image
3. Receive an image
4. Save an image

You are talking about stripping metadata at step 1, which is very good and a reasonable default is to strip a lot of data here which can be sensitive as you say. But this issue is about preserving the metadata which is still available in later steps in the chain.

**Comment by EvanHahn-Signal** [comment]
Do you mean that the _sender_ should be able to re-download their original image from Signal? Or that some metadata should be kept for the recipient?

**Comment by NiklasBr** [comment]
Neither. I suggest that the metadata that the receiver has received, which is already on the recipients device, be kept intact when downloading photos.

**Comment by EvanHahn-Signal** [comment]
What metadata is that? What metadata do they already have?

**Comment by EvanHahn-Signal** [comment]
But isn't all that metadata stripped when the photo is sent (step 1 in your comment above)?

**Comment by NiklasBr** [comment]
Not at all. Some is even added by Signal, which includes the date and time received.

**Comment by jesspaugh** [comment]
If a PDF is sent in Signal, is the title removed?

It's not intuitive to arbitrarily remove metadata from SOME files. The date
and time a photo was taken is a really important part of the file, and
there is no way to restore this if it's stripped away. I use signal with my
Android friends specifically because they are not downsampled. In this
case, my friend sent me ~50 photos from a three-day weekend and I can't
view them chronologically, and there is no easy way to reorder these
pictures.

**Comment by untereiner** [comment]
@EvanHahn-Signal An honest option would allow end user to decide if complete metadata should be kept or not!

**Comment by qkrrmsdud1** [comment]
> @EvanHahn-Signal An honest option would allow end user to decide if complete metadata should be kept or not!

I agree with this strongly. I fully agree that stripping metadata is useful to protect the privacy of users who may not realize that their media contains sensitive metadata, but sometimes (very often in my case), users are aware of the metadata and would like it to be preserved. I think the best option would be to allow users to choose whether or not to strip metadata.
