### ISSUE TITLE
og:image meta tag for Link preview image not working

### ISSUE THREAD

**Issue by RyanTippsTX** [signalapp/Signal-iOS#5465]
### Bug description
Link Preview is not showing the photo at the url that I provide in my website's og:image meta tag.

### Steps to reproduce
- send a signal message wth a link to a website that has meta tags for link previews: `<meta name="og:image" content='https://website.com/photo.png' />`

**Actual result:** Signal's Link Preview is generated with a Title and Description, but no image. Meanwhile, the Apple iMessage app renders the same link preview with an image.

**Expected result:** Signal app should render link preview with an image.

### Device info
Its happening on both my iphone and macbook, but my iphone is:
**Device**: iPhone 13 mini
**iOS version**: 15.4.1
**Signal version:** 5.58

**Comment by comnerd23** [comment]
It works fine for https://ogp.me page.
Could it be an error in the link?

**Comment by dag0310** [comment]
I found the problem: You need to use double quotation marks (") instead of single quotes (') for the meta tag attributes:

`<meta name="og:image" content="https://website.com/photo.png" />`

**Comment by oliver3** [comment]
I had a similar issue but for me it was fixed by using `https://` instead of `http://`.

PS: it should actually be `property="og:image"` and not `name`
