### ISSUE TITLE
Fail Transfer IOS to IOS

### ISSUE THREAD

**Issue by Rubbishe** [signalapp/Signal-iOS#5466]
* 		I have searched open and closed issues for duplicates
* 		I am submitting a bug report for existing functionality that does not work as intended
* 		This isn't a feature request or a discussion topic

Bug description
I have a new iPhone that is on iOS 16.0.3 and am trying to transfer from an older iPhone that is also on iOS iOS 16.0.3. I'm able to read the QR code with the old phone. I see the "connecting" animation, then move on to “transferring data” but the bar is not loading for hours, and then I get the following message. “The transfer couldn't complete, please ensure your devices are near each other and try again”

Steps to reproduce
* Power on 2 iPhones with iOS 16.0.3
* Reset privacy and location
* Updated to the latest version and beta version. Check again local network, bluetooth is on on both device
* Initiate account setup transfer with new phone
* Scan QR code with old registered phone

Actual result:
Transferring Data Page popped up but not showing and progress for 15mins to 6hours.  Error message indicating that the transfer couldn't complete.

Expected result: Transfer of data from old phone to new phone.

Screenshots
-￼
￼
Device info
New Device: iPhone 14Pro
iOS version: iOS 16.0.3
Signal version: 5.59.0 (13)

Old Device: iPhone XS
iOS version: iOS 16.0.3
Signal version: 5.58.0.12

Link to debug log
iPhone 14Pro: https://debuglogs.org/ios/5.59.0/30f92529fc3acd826762a3495cc3c43ab3cc764097d1b7132efab18185fd9629.zip
iPhone XS: https://debuglogs.org/ios/5.58.0/5baa1628acd1ffb061e0727642d815bce7bc3dfc4769f32510b2d7ed47f82e75.zip

**Comment by andrew-hill** [comment]
looks like #5450?
