### ISSUE TITLE
Top-level LICENSE file should be AGPL

### ISSUE THREAD

**Issue by geofft** [signalapp/Signal-iOS#5471]
Commit 370ff654e714eca24e78117f47534a75eba2dac0 updated the license throughout the code to AGPL, but the top-level LICENSE file is still the text of the GPL, which (among other things) makes GitHub display a little "License" widget on the home page as GPL. Can you please update it to the [text of the AGPL 3.0](https://www.gnu.org/licenses/agpl-3.0.txt)?

**Comment by sashaweiss-signal** [comment]
Hi! Thanks for calling this out - fixed now :)
