### ISSUE TITLE
transferring account iPhone 13 mini @ 16.0.2 to similar device failed / account-data lost

### ISSUE THREAD

**Issue by Privatecoder** [signalapp/Signal-iOS#5474]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Transferred an account from an iPhone 13 mini @ iOS 16.0.2 to another iPhone 13 mini @ iOS 16.0.2.
Progress-bar did move and after some time I got a message that the transfer was unsuccessful.
Now the old phone is unregistered and all data has been removed as per the [docs](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore)
```
The new device has all the account info and message history.
The old device deletes all the account info and message history. 
Message history is not copied to the other device. It is moved.
```
The new Phone is showing me a "_Transfer could not be completed. The Data transferred from your old device could not be restored. Please send a diagnostics-report_...etc." however tapping the submit diagnostic-logs button tells me that "_no protocols could be found_"

### Steps to reproduce
Transfer an account from an iPhone 13 mini @ iOS 16.0.2 to another iPhone 13 mini @ iOS 16.0.2.

**Actual result:** Transfer fails with no option to re-try / recover

**Expected result:** Do not remove old data until the transfer has been completed successfully!

### Screenshots
![IMG_9729](https://user-images.githubusercontent.com/45964815/199964300-b70b461b-bbe2-480a-8d76-f73ecab2612c.PNG)
![IMG_9730](https://user-images.githubusercontent.com/45964815/199964333-940be1ce-47e0-442d-9486-e9289238ccd5.PNG)

### Device info
**Device**: iPhone 13 mini
**iOS version**: 16.0.2

**Signal version:** 5.59.1

**Comment by NiklasBr** [comment]
I'm sorry this happened. This would not have been a problem if we Signal allowed us to back up our important data.

**Comment by Privatecoder** [comment]
Mi macOS Signal Client still has all the Chats and Media files available but I don't know if there is a way to transfer it from there to my iOS device..

**Comment by andrew-hill** [comment]
looks quite similar to #5450 ?

**Comment by Privatecoder** [comment]
No, it doesn‘t, as the transfer itself was successful (and did not get stuck) however after the reboot the transferred data was not usable on the new phone and wiped on the old one.

**Comment by NiklasBr** [comment]
It id missing any response from maintainers, not from the reporters. Not stale.

**Comment by Privatecoder** [comment]
Agree – there is no log, no debug-option just "sry, it is all gone" with no way to go back. Signal does not promote itself as a reliable option when transferring it to a new device.

**Comment by NiklasBr** [comment]
It is missing any response from maintainers, not from the reporters. Not stale.

**Comment by NiklasBr** [comment]
It is missing any response from maintainers, not from the reporters. Not stale.

**Comment by Privatecoder** [comment]
what a joke.
