### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by VladyslavKara** [signalapp/Signal-iOS#5475]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I switched from iPhone XR to iPhone 14 Pro Max, I installed new Signal beta, tried to open it and app crashed.

### Steps to reproduce
Install Signal beta > open app

**Actual result:** App crashed during first open when I installed it.

**Expected result:** It shouldn't crash.

### Device info

**Device**: iPhone 14 Pro Max

**iOS version**: 16.0.3

**Signal version:** 6.1.0 (9)

**Comment by vcrtech** [comment]
I'm in the same boat. If I install 5.58.0 build 13 from TestFlight I am able to use Signal again. Anything higher than that version crashes.

**Comment by vcrtech** [comment]
Here's a link to my crashlog.

https://debuglogs.org/ios/6.2.0/a2eebe555c682f690972f43e50b8d306a580a39ee6bc4d74b5a46f4554165835.zip

**Comment by EvanHahn-Signal** [comment]
Thanks for sharing. This is a known issue and we're looking into it.

**Comment by vcrtech** [comment]
6.2.2 fixed my issue

**Comment by gabrc52** [comment]
[2023.01.01 03.48.16 DDD06166-EC0B-4149-85EE-F854787889B8.zip](https://github.com/signalapp/Signal-iOS/files/10329518/2023.01.01.03.48.16.DDD06166-EC0B-4149-85EE-F854787889B8.zip)

Here's some newer (2023) logs

Possible duplicates: #5375, #5395, #5481, #5475
