### ISSUE TITLE
“Members couldn’t be added to the new group” message persists, does nothing when pressing “add members” button

### ISSUE THREAD

**Issue by JacKaL37** [signalapp/Signal-iOS#5476]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Four members of a group chat have disappeared from it over time. I am now receiving a constant pop-up indicating that these members could not be added to the “New Group”. It asks if I’d like to add them, I confirm yes, and nothing happens. The pop-up persists nearly every time I open the group chat.

I am the only one receiving the pop-up, likely because I’m the one that originally added these members. 

### Steps to reproduce
unclear, as it seems to be an issue of long-term attrition, but:
- Add friends to a group chat
- have some of those friends lapse, likely fail to update the app, their phones, etc 
- upgrade the group chat to “new groups”, (however long ago that was)

**Actual result:** Pop up consistently reappears every time you enter the group chat. 

**Expected result:** The pop-up should either permanently go away when dismissing it, or the members should actually be re-added to the group when confirming to do so. 

### Screenshots

![9E0AA913-159B-480C-BFA8-8A91DB5C6469](https://user-images.githubusercontent.com/1424189/200447114-9a462515-e77b-4a6f-9790-0aeec7bfbfd5.jpeg)
![DB57E324-7794-4547-B993-24EFCF7E4084](https://user-images.githubusercontent.com/1424189/200447119-2b92dab1-f31e-42c2-8f2d-c5b50d936f87.png)

### Device info

**Device**: iPhone XS

**iOS version**: 15.6.1

**Signal version:** 5.59.1.0

### Link to debug log

https://debuglogs.org/ios/5.59.1/1ebecb0b77ed084781a1ce72ee39a43b91b23a1a645fbb92ae66e3f526e468de.zip

**Comment by max-signal** [comment]
We fixed this banner in e924cb50df81790a0e7cdf166ba7e99d548e37e6. Please re-open the issue if you’re still unable to dismiss it permanently after trying twice.
