### ISSUE TITLE
Tall images displayed with visibly lower quality than the (compressed by Signal) file actually has

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5479]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal iOS displays tall images with visibly lower quality than the file actually has.

### Steps to reproduce
- Send a tall image (with high quality) to Signal iOS (from any platform, including the same instance of Signal iOS).
- Tap to view the image in the chat using Signal iOS.

**Actual result:** When viewed in Signal, the sent image appears to be of visibly lower quality than it actually has.

**Expected result:** The image should be displayed in the full quality available.

### Screenshots

Screenshot: page in Safari | Screenshot: PDF full page "screenshot", zoomed in | JPEG made from PDF | Screenshot: JPEG made from PDF, zoomed in | :warning: Screenshot: sent image in Signal (sent with high quality), zoomed in | JPEG received by linked Desktop | Screenshot: JPEG received by linked Desktop, zoomed in
-|-|-|-|-|-|-
![orig+screenshot](https://user-images.githubusercontent.com/19972511/201092351-1c0bd79a-98ca-4efa-aa7f-defde1be2333.jpeg) | ![orig+pdf+screenshot](https://user-images.githubusercontent.com/19972511/201092347-397e05b1-82fb-419e-b086-536e9cfb0c5a.jpeg) | ![orig+jpeg](https://user-images.githubusercontent.com/19972511/201092341-e0c3d12a-ceea-4324-a97d-f6bc28fa88ba.jpeg) | ![orig+jpeg+screenshot](https://user-images.githubusercontent.com/19972511/201092344-7ca0d471-67c7-49d6-8bb6-2084234834b4.jpeg) | ![sent+signal](https://user-images.githubusercontent.com/19972511/201092352-e4b111b8-fec7-4052-b8d5-b7d1b4a41104.jpeg) | ![desktop](https://user-images.githubusercontent.com/19972511/201092333-53ec075e-c7cb-430e-be77-805f907aed08.jpeg) | ![](https://user-images.githubusercontent.com/19972511/201092689-d4a6b8cb-70b4-42bc-81ee-bf7e4e8b0529.png)

### Device info
**Device**: iPhone XR
**iOS version**: iOS 16.2 Public Beta 2 (20C5043e)
**Signal version:** 6.2.0.6

### Link to debug log

https://debuglogs.org/ios/6.2.0/f600d6978177150364a85aef53919721673757f520f34d2a8442534c74c0f6f7.zip

**Comment by EvanHahn-Signal** [comment]
This is working as expected.

We compress outgoing images. This helps users because they can send and receive images faster, and helps Signal keep our costs down.

[We have code](https://github.com/signalapp/Signal-iOS/blob/20c1dd62a7337d076207e15924dd4cf52dbca3c0/SignalMessaging/attachments/SignalAttachment.swift#L1030-L1053) that resizes images to a maximum dimension to keep them small. That means that the width and height have to be less than this.

For images that are very wide or very tall, this resizing is more noticeable. For example: imagine that the maximum dimension is 500 pixels. (It varies, but let's use this as an example.) If you have a 200×4000 image, it will be shrunk to 25×500.

You can partially address this by choosing to send your photos in higher quality before you send them.

**Comment by u32i64** [comment]
I'm aware that Signal does compress media, that there are feature requests to improve that, etc.; however, this issue is *not* about sending media.

The issue is that viewing media in Signal iOS results in it appearing in **lower quality than the file actually has *(after Signal's compression)***.

To simplify, here are two screenshots:


. | Received media, zoomed in | The same received media, also zoomed in
-|-|-
Viewed in | Signal | Photos (saved from Signal)
Quality | :warning: Worse quality than the compressed media actually has | Actual quality (of compressed media)
Screenshot | ![](https://user-images.githubusercontent.com/19972511/201092352-e4b111b8-fec7-4052-b8d5-b7d1b4a41104.jpeg) | ![](https://user-images.githubusercontent.com/19972511/201333841-edc7d239-af5d-48be-a292-ff040bcb238b.jpeg)


---

> You can partially address this by choosing to send your photos in higher quality before you send them.

I have indeed chosen high quality when sending; however, again, the issue is not with sending.

**Comment by clauz9** [comment]
@EvanHahn-Signal sorry to tag you,  

but I think you misunderstood the issue, 
@u32i64  was talking about differences in quality of how images are displayed, when you view the same received image in the signal app versus in the phone's gallery app. 

look at @u32i64  second post.

**Comment by EvanHahn-Signal** [comment]
Ah, sorry I misunderstood. I've added a ticket in our internal tracker.
