### ISSUE TITLE
Sending a ZIP close to 100 MB doesn't work and produces strange behavior (while it works on Desktop)

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5480]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've successfully sent a ZIP file with the size of 96 706 847 bytes using Signal Desktop. However, sending it via Signal iOS doesn't work and produces unexpected behavior.

### Steps to reproduce
- In a chat, tap "+" > "File" > choose the file.

   **Actual result:**
   - Signal's *photo editor* will be shown with no photo.
   - Pressing "send" shows "Attachment to large" error sheet, but it quickly disappears along with the photo editor.

- Try sending the file by sharing it from somewhere (e.g. the Files app) to Signal.

   **Actual result:**
   - The correct media preview for the file is displayed.
   - Pressing "send" will make Signal try to upload the file for a few seconds, after which it will fail with a generic "Unable to Send Attachment" error with an option to retry.
   - For each send attempt, the file will appear in the chat as sent, but it actually isn't (I tried in a lonely group--it doesn't appear on the linked Desktop; in a 1:1 chat I think it may have been correctly marked as "not sent" when I had tried there).

**Expected result:** It should either be possible to send this file using Signal iOS, or the file should be clearly rejected due to its size.

### Screenshots
Aforementioned photo editor with no photo:

<img src="https://user-images.githubusercontent.com/19972511/201103030-386903d7-8d6f-4fd2-9dac-545a49b8ccc4.jpeg" width=200>

### Device info
**Device**: iPhone XR
**iOS version**: iOS 16.2 Public Beta 2 (20C5043e)
**Signal version:** 6.2.0.6

### Link to debug log
https://debuglogs.org/ios/6.2.0/2a56b685a146c9e7d6637337c5d1802d73e51ce7a3edb21c70495b3c5eaece80.zip

**Comment by EvanHahn-Signal** [comment]
Thanks for this report. I've filed a bug in our internal tracker.
