### ISSUE TITLE
App Won't Open

### ISSUE THREAD

**Issue by Shmood00** [signalapp/Signal-iOS#5481]
- [x]  I have searched open and closed issues for duplicates
- [x]  I am submitting a bug report for existing functionality that does not work as intended
- [x]  This isn't a feature request or a discussion topic
<hr >

### Bug Issue

I've been unable to open the Signal app for well over a month. Whenever I tap on the icon, the app simply crashes - this happens with the beta version of the application as well.

I've reached out to support and have sent debug logs and was informed that deleting the app and reinstalling it should fix the issue as it appears my database has been corrupted. Doing this unfortunately does NOT fix the issue. 

According to support, logs show that I have NOT deleted and reinstalled my Signal application. I sent them a video showing the process of me deleting and reinstalling the app - for some reason it's not processing the deletion of the application.

Please let me know if there's any other information needed, thanks.

### App Version

Signal App v6.0 - Prod

Signal App v6.2.0 (6) - Beta

** No version of the Signal app works

### Device Information

iPhone 12 Pro Max iOS Version 16.0.3

### Signal Debug Log
[2cfe39385265b38aac402dd87ebdea51675acc80f06d63cec55e2b0c1792a098.zip](https://github.com/signalapp/Signal-iOS/files/9991720/2cfe39385265b38aac402dd87ebdea51675acc80f06d63cec55e2b0c1792a098.zip)

**Comment by vcrtech** [comment]
Does this happen with 5.58.0 (13)? If not, I'm in the same boat. Signal crashes on builds 5.59.x and higher for me.

https://debuglogs.org/ios/6.2.0/a2eebe555c682f690972f43e50b8d306a580a39ee6bc4d74b5a46f4554165835.zip

**Comment by Shmood00** [comment]
It crashes on 5.58.0 (13) for me as well. No version seems to work.

**Comment by romaintordo** [comment]
For me it won't open since the update made yesterday 6.1 on both my iPhone and iPad.

**Comment by janhartmann** [comment]
Can confirm, unable to open the app.

**Comment by Shmood00** [comment]
It's nice to see others are experiencing the same issue. Unfortunately no version of the application has worked for me for over a month and all communication with support hasn't helped much. 

Every follow up I'm just told engineering is still working on solving the issue.

**Comment by vcrtech** [comment]
I die a little inside when I see releases featuring Instagram-like features such as stories when I know more and more people are being locked out from crashes and unable to use the app at all. When you combine major showstoppers on the iOS side with very unpopular decisions (removing SMS support for Android), I feel like Signal is in real trouble and folks are going to start defecting to more anonymous and polished platforms like Threema. I’m not sure who’s to blame, but I really hope the devs are standing on their product owners desks over this. The Titanic is taking on water and it seems like the product team is more worried about adding new entrées to the chowhall’s menu than stopping the impending disaster.PLEASE put the brakes on new features until these major bugs/crashes are addressed.On Nov 17, 2022, at 09:09, Shmood00 ***@***.***> wrote:﻿
It's nice to see others are experiencing the same issue. Unfortunately no version of the application has worked for me for over a month and all communication with support hasn't helped much.
Every follow up I'm just told engineering is still working on solving the issue.

**Comment by karmasakshi** [comment]
Same, unable to open Singal since v6.1. I am able to use the Desktop app though. Tried v6.2 that became available just now, doesn't work either.

**Comment by max-signal** [comment]
We’ve just released 6.2.1 on the App Store. Please update and let us know if you’re still seeing crashing issues. @Shmood00, we have a separate fix for your issue that should be available in 6.2.2 which is coming soon.

**Comment by maraboshi** [comment]
6.2.1 still broken for me.

**Comment by vcrtech** [comment]
6.2.1 still broken for me as well. Thanks for trying!

https://debuglogs.org/ios/6.2.1/2b70bd34327153adf549678864d5485e5e4046880b38727f1b24451fbf5a577e.zip

**Comment by kmakeel** [comment]
Same, unable to open Singal after update to 6.2.1

**Comment by vcrtech** [comment]
6.2.2 fixed my latest issue.

**Comment by Shmood00** [comment]
> We’ve just released 6.2.1 on the App Store. Please update and let us know if you’re still seeing crashing issues. @Shmood00, we have a separate fix for your issue that should be available in 6.2.2 which is coming soon.

6.2.2 did not fix my issue.

**Comment by maraboshi** [comment]
6.2.2 fixed the crash for me :-)

**Comment by kmakeel** [comment]
6.2.2 fixed the crash. thanks

**Comment by Shmood00** [comment]
As stated previously, 6.2.2 still has not fixed my issue. Here's an updated debug log. 

https://debuglogs.org/ios/6.2.2/8dc437f2b9c0304cf14d3c1313b7c7b868ce3c38fb168ea123147eb79d19559e.zip

**Comment by EvanHahn-Signal** [comment]
Please update to 6.2.3 to see if that fixes your issue.

**Comment by Shmood00** [comment]
Looks like I already have 6.2.3 installed, app still doesn't work.

**Comment by Shmood00** [comment]
> Please update to 6.2.3 to see if that fixes your issue.

My current version is 6.2.3 and the app still doesn't work. Here's another updated log. 

https://debuglogs.org/ios/6.2.3/c97e40b071d3e746d6785efb9826d18f0a1a045a537502fe792dbd1e3ee6bdfb.zip

**Comment by EvanHahn-Signal** [comment]
@Shmood00 Thanks. This is a known issue we're aware of and working on. Sorry for the trouble.

**Comment by Shmood00** [comment]
I appreciate the assistance. It is slightly annoying, I've been unable to use Signal for well over a month at this point. Is the team any closer to pin pointing what the issue might be?

**Comment by EvanHahn-Signal** [comment]
It's a tricky issue that I hope to fix this in the next month. Please keep your app up-to-date. Sorry for the delay.

**Comment by Shmood00** [comment]
> It's a tricky issue that I hope to fix this in the next month. Please keep your app up-to-date. Sorry for the delay.

Thanks for the updates! I'll continue to keep an eye out for new versions.

**Comment by Shmood00** [comment]
Just to provide an update, version 6.5 of Signal did NOT fix the issue. 


Here's an updated debug log:

https://debuglogs.org/ios/6.5.0/e785d0fd7074f877fa1c7da579d0c93b3ca19dd065ed48e08131d53658445913.zip

**Comment by Shmood00** [comment]
Version 6.6 also did NOT resolve the issue. 

Updated debug log: https://debuglogs.org/ios/6.6.0/7a16fb935fcba7e7d305b47697cc20f720d62ff6fa6403d82b820770e6892bee.zip

**Comment by gabrc52** [comment]
[2023.01.01 03.48.16 DDD06166-EC0B-4149-85EE-F854787889B8.zip](https://github.com/signalapp/Signal-iOS/files/10329518/2023.01.01.03.48.16.DDD06166-EC0B-4149-85EE-F854787889B8.zip)

Here's some newer (2023) logs

Possible duplicates: #5375, #5395, #5481, #5475

**Comment by gabrc52** [comment]
It's definitely more than 3 months. I think this issue has been there since at least 2021

**Comment by Shmood00** [comment]
Version 6.7 of the app has NOT solved the issue. 

Update debug log: 

https://debuglogs.org/ios/6.7.0/f3d069c473108eed7a81886407929ff69f5c9d06bda439de7bbaab8b40398472.zip

**Comment by Drewpeaceful** [comment]
Can I also ask help regarding iphone IOS 16, app wont open now, tried reinstalling and restart the phone.
https://debuglogs.org/ios/6.6.0/15b87fced7cb3185d0d555022984cc933eb62bb1ba1494b748a6153f0ff2255a.zip

**Comment by Shmood00** [comment]
Version 6.8 did NOT resolve the issue. 

Update debug log:

https://debuglogs.org/ios/6.8.0/7d726a33cd44ef5cbb62e2e79bdf990f421da966c462fcb8f41448da2c17efde.zip

**Comment by Shmood00** [comment]
Version 6.9 did NOT fix the issue. 

Update debug log:

https://debuglogs.org/ios/6.9.0/a98a92e031d18b3b104695ea8f0b46d0da1a5438a5bab1e8f2b2f0d109a411cb.zip

**Comment by EvanHahn-Signal** [comment]
@Shmood00 Thanks for sending your logs.

I just made a change that may help you, and others, out. I expect it to be added to v6.11. Once you update to that version, let me know if you're still stuck.

If you want to get on that version earlier, you can [join our beta][0].

[0]: https://support.signal.org/hc/articles/360007318471

**Comment by gabrc52** [comment]
# It works!

Thank you so much!

**Comment by dwo** [comment]
similar thing with an iphone 8 @ ios 16.3 https://debuglogs.org/ios/6.10.0/22b9d1661261089d3acc763aef890130603653633442d313164c29ac2b4812be.zip

When is 6.11 dropping?

**Comment by Drewpeaceful** [comment]
Version 6.9 don't resolve issue for me.

https://debuglogs.org/ios/6.9.0/38b2c9fc8d8a5669d9ecf455db730f858e31dc46d46d08a873bcbc425f091a1d.zip

**Comment by EvanHahn-Signal** [comment]
Could you try opening Signal while offline and see if that fixes your issue?

I don't know when 6.11 will be released, but I expect we will start the beta next week.

**Comment by Shmood00** [comment]
> Could you try opening Signal while offline and see if that fixes your issue?
> 
> 
> 
> I don't know when 6.11 will be released, but I expect we will start the beta next week.

This changes nothing for me. Still crashes.

**Comment by Shmood00** [comment]
> @Shmood00 Thanks for sending your logs.
> 
> 
> 
> I just made a change that may help you, and others, out. I expect it to be added to v6.11. Once you update to that version, let me know if you're still stuck.
> 
> 
> 
> If you want to get on that version earlier, you can [join our beta][0].
> 
> 
> 
> [0]: https://support.signal.org/hc/articles/360007318471

I'm happy to say that beta version 6.11 fixed this issue! I luckily had signal working on another device and was able to successfully transfer everything onto the device it wasn't working on. 

Thanks to the Signal team for fixing this issue!

**Comment by dwo** [comment]
still crashing on open @ 6.11 here. 

https://debuglogs.org/ios/6.11.0/148d1996ddb8a4781c01f4459a087e9bcd8e615f4677bb767644c2f9ad9b1b95.zip

**Comment by Drewpeaceful** [comment]
> Could you try opening Signal while offline and see if that fixes your issue?
> 
> I don't know when 6.11 will be released, but I expect we will start the beta next week.

Thank you for response. I tried to go offline if it will open, Yes it open once then when I browse to message it crash again while offline, going online again still crashing.

**Comment by Drewpeaceful** [comment]
Tried to install again 6.11 version but still crashing.

https://debuglogs.org/ios/6.11.0/c7e4d4d55799bec7201e122d58a36b0ef24d4e911777511707b9d5f52ed4888d.zip

**Comment by glamorous** [comment]
For me it's fixed with 6.12 with recovering the messages in offline modus.
