### ISSUE TITLE
Pair device results in "invalid server response"

### ISSUE THREAD

**Issue by Biepa** [signalapp/Signal-iOS#5484]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not able to pair a device with a pc. After scanning the qr code I get a message about the server response being invalid. Tried it on different days. It worked good before and I have multiple paired devices working fine.

### Steps to reproduce
- Open the desktop app (first use there)
- try pairing with the iPhone
- 
**Actual result:**

https://user-images.githubusercontent.com/25102748/202897387-ba408d3d-72f0-418f-9ee4-a0af499c7b10.mp4

**Expected result:** Successful pairing.

### Device info

**mobile Device**: iPhone 11 iOS 16.1.1 - Signal version: 6.2.2.0
**pairing device**: Laptop with Linux - Signal installed as flatpak - version: 5.63.1

### Link to debug log
App says that no debug logs could be found.

**Comment by EvanHahn-Signal** [comment]
Could you post [debug logs](https://support.signal.org/hc/articles/360007318591) from your iOS device?

**Comment by Biepa** [comment]
@EvanHahn-Signal The app says, that not debug logs could be found. Is there another way I could gather additional info?

**Comment by Biepa** [comment]
@EvanHahn-Signal Tested this by reinstalling Linux and a newly installed Win11. Same problem.

**Comment by EvanHahn-Signal** [comment]
Could you take a screenshot of what you see?

**Comment by Biepa** [comment]
On the desktop I see the "scan QR code" screen all the time. On mobile what is shown in the video above.

Or what do you mean?

**Comment by EvanHahn-Signal** [comment]
Sorry. Could you take a screenshot/video of what happens when you can't submit debug logs? We need them in order to investigate this issue.

**Comment by Biepa** [comment]
I tried it again today to pair the device about 08:50 in my timezone. I know could create the debug logs. But looking into them. There doesn't seem to be an entry around this time. 
But here is the log:
[b1cf8581adeb0b04ded2827edaf6d37a23267e7e1b1dc2247b9df3331cd2da14.zip](https://github.com/signalapp/Signal-iOS/files/10130356/b1cf8581adeb0b04ded2827edaf6d37a23267e7e1b1dc2247b9df3331cd2da14.zip)

**Comment by EvanHahn-Signal** [comment]
How many other devices do you have linked to Signal? It looks like you may be hitting the maximum.

**Comment by Biepa** [comment]
Five devices are currently shown as paired.

**Comment by EvanHahn-Signal** [comment]
I believe that's the maximum. You'll need to unlink a device in order to link a new one.

I've filed a ticket in our internal tracker to improve the error message.

**Comment by Biepa** [comment]
Oh. Okay. Yes a change in the message would help. :+1: 
Is this a technical limit or selfmade? If it's the second one, could the limit be increased?

**Comment by EvanHahn-Signal** [comment]
> Pairing worked, once i deleted another device from the list.

Great! I'm going to close this issue. We'll improve the error message at some point in the future.

> Is this a technical limit or selfmade? If it's the second one, could the limit be increased?

Messages are typically sent between Signal _devices_, not between Signal accounts. If you have 5 devices and I send you a message, Signal needs to deliver 5 messages instead of just 1. We have this limit to prevent performance and congestion issues.

If you'd like to discuss an increase to this limit, check out [this thread on the community forums][0].

[0]: https://community.signalusers.org/t/limit-of-5-linked-devices-is-painful/13413
