### ISSUE TITLE
Stories: crash at modifying story text

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#5490]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After completed a text story tried to modify it, then Signal crashed.

### Steps to reproduce
- create text story, enter a text
- set colors, style, background color
- confirm with checkmark
- change your mind and try to modify the text by tapping on it
- crash

### Device info
**Device**: iPhone SE 2020
**iOS version**: 15.7

**Signal version:** 6.2.2.0

### Link to Crash log
→ [Click here](https://drive.proton.me/urls/568G6J9EYM#qeFVs9VhpgNW)

### Link to Debug log
→ [Click here](https://debuglogs.org/ios/6.2.2/9be2b88f231e2c395440ec7ca2a0808a16731e81f6511f14bd102eb67437ea92.zip)

**Comment by EvanHahn-Signal** [comment]
I can't reproduce this issue.

We plan to release Signal iOS v6.4 to production in the next few days. Could you update to that and see if it solves your problem?
