### ISSUE TITLE
Stories: video story doesn't have sound after fresh Signal start, only when volume is adjusted

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#5491]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I start fresh Signal and open someones group story which contains a video then it does not have sound until I adjust the volume with the volume buttons. Then sound comes back.
Then if I re-open the same story without exit from Signal, then there is sound already, no problem.

### Device info
**Device**: iPhone SE 2020
**iOS version**: 15.7
**Signal version:** 6.2.3

### Link to debug log
→ [Click here](https://debuglogs.org/ios/6.2.3/ed36372baac6fc3298395c6b6b3e22d139c598089f0ca4b9edebbdab7047079f.zip)

**Comment by EvanHahn-Signal** [comment]
Is this an issue specific to group stories, or all stories? (It may be intentional—I don't think we want to surprise users with unexpected sound.)

**Comment by kaktusztea** [comment]
To all stories. Now I see that the behavior is the same for Android and Desktop versions as well.
So if this is intentional then I close this ticket. Although the current design is a little rough - I had no clue that it is intentional and maybe I would see a few videos without sound, thinking that they don't have sound originally. So some popup info would be nice about this at first opening a video story.
