### ISSUE TITLE
Can we *please* get some attention into #4916 ?

### ISSUE THREAD

**Issue by sgreadly** [signalapp/Signal-iOS#5494]
It's been over 1.5 years, we've all been providing data again and again showing that we are still affected by this, and it is a serious issue that's driving some away from Signal. 

Can you please prioritise this for those of us who are still loyal and trying our best to get it fixed ?

Thanks.

**Comment by sgreadly** [comment]
#4916

**Comment by EvanHahn-Signal** [comment]
Please keep discussion in the original issue. We'll discuss there.
