### ISSUE TITLE
Empty message caused "You may have new messages" and reaching a rate limit while sending delivery receipts

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5496]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Some kind of empty message (according to the log) was sent to my device, which wasn't properly handled (i.e. "You may have new messages" was shown) and potentially caused too many delivery receipt sends, thus exceeding the rate limit.

1. I've received a notification with (I think) the default iOS notification sound (which isn't the sound set in Signal Settings), which (I think) had the string with the key `APN_Message` as the content (i.e. "You may have new messages" in English).
2. Upon opening Signal, I navigated to Signal Settings but was prompted to complete a CAPTCHA (which I completed successfully).

The linked Desktop didn't seem to experience any noticeable issues, but there also appear to be errors related to the rate limit in its log, hence I'm including it below too.

**Update:** It seems, at least in Desktop's case, multiple such empty messages have previously been received (and dropped).

### Device info
**Device**: iPhone XR
**iOS version**: iOS 16.2 (20C5049e) public beta + iOS 16.2 (b) (20C7750490f)
**Signal version:** 6.4.0.8

### Link to debug log

I've included some excerpts from the debug logs, which may be relevant.

#### iOS

https://debuglogs.org/ios/6.4.0/b619f05b520657e2c3fdd11480ebf022edb9fd19c17f97d5ff78523e0adbcdb9.zip

```
[...]:23:660  🧡 [OWSMessageManager.m:2224 -[OWSMessageManager handleReceivedEnvelope:withDataMessage:thread:plaintextData:wasReceivedByUD:serverDeliveryTimestamp:shouldDiscardVisibleMessages:transaction:]]: Ignoring empty: Incoming message from: Optional(<SignalServiceAddress phoneNumber: [...], uuid: [ REDACTED_UUID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx5C1 ]>).1 for group: [...] with timestamp: 1669738538160, serviceTimestamp: 1669738538368

[...]:35:136  🧡 [TSOutgoingMessage.m:723 -[TSOutgoingMessage updateWithFailedRecipient:error:transaction:]]: Send to recipient failed, address: <SignalServiceAddress phoneNumber: [...], uuid: [ REDACTED_UUID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx5C1 ]>, timestamp: 1669738583694, error: <SignalServiceKit.SpamChallengeRequiredError: [...]> (isRetryable: 0)
[...]:35:139  ❤️ [MessageSender.m:294 -[OWSSendMessageOperation didFailWithError:]]: Failed with error: <SignalServiceKit.SpamChallengeRequiredError: [...]> (isRetryable: 0)
[...]:35:604  ❤️ [OWSOutgoingReceiptManager.m:276 -[OWSOutgoingReceiptManager sendReceiptsForReceiptType:]_block_invoke]: Failed to send Delivery receipts to sender with error: <SignalServiceKit.SpamChallengeRequiredError: [...]>

[...]:44:326  ❤️ [NotificationActionHandler.swift:298 notificationMessage(forUserInfo:)]: assertionError: threadId was unexpectedly nil

[...]:44:357  ❤️ [NotificationActionHandler.swift:21 handleNotificationResponse(_:completionHandler:)]: error: OWSAssertionError(errorCode: 31, description: "threadId was unexpectedly nil")
```

#### Linked Desktop

https://debuglogs.org/desktop/6.0.0-beta.3/a6e6833e36ccca8ac0adde11a8a34b5a3e7309f63de9b400a2f03722a60a7b3c.gz

```
[...] handleDataMessage/groupv2([...]) [REDACTED]5c1.1 1669738538160: Dropping empty message

[...] PUT (WS) https://chat.signal.org/v1/messages/[REDACTED]ee6?story=false 428 Error
[...] delivery receipts job queue: job [REDACTED]6be failed on attempt 1. Error: SendMessageProtoError: SendMessageChallengeError: The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 428) [...]
```

#### `5c1.1`

https://debuglogs.org/ios/6.4.0/c57bbd64c3e6e1244a8e0888bbb03dfca359365fcd71300b0dbdb0f09995723b.zip

**Comment by EvanHahn-Signal** [comment]
Are you able to determine who sent these messages to you? If so, it'd be great to get _their_ debug logs.

**Comment by u32i64** [comment]
According to my logs, the empty messages appear to be sent by a user whose UUID ends with `5c1` (from their device 1 i.e. primary device). I've already got a debug log from their primary device and included it in the original report:

> #### `5c1.1`
>
> https://debuglogs.org/ios/6.4.0/c57bbd64c3e6e1244a8e0888bbb03dfca359365fcd71300b0dbdb0f09995723b.zip
