### ISSUE TITLE
Can’t swipe right to return to the conversation list after unlocking phone

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-iOS#5501]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description 
I can consistently reproduce a state where swiping right from the left-hand edge of the screen while in a chat doesn’t go back to the conversation list screen. 

### Steps to reproduce 
1. Open a chat in Signal
2. Turn phone to landscape
3. Lock the phone
4. While locked, rotate the phone to portrait
5. Unlock the phone
5. Try swiping from the left edge of the screen.

**Expected behaviour:** navigate back to the conversation list.

**Actual behaviour:** The gesture no longer works, and instead it always quotes a message.

I think this is because the “swipe to go back” gesture is only enabled when the phone is in portrait. When locking the phone while in landscape, rotating the phone to portrait, then unlocking the phone, I don’t think Signal is correctly re-enabling the “swipe to go back” gesture

### Device info

**Device**: iPhone 11

**iOS version**: 16.1.1

**Signal version:** 6.6.0.10

### Link to debug log

https://debuglogs.org/ios/6.6.0/455efaf842927a6d1b05e34ef3e44482f18b1f3201c8db60ca4f26ad7994e460.zip

**Comment by Doge7734** [comment]
If you don't mind, I'll tag my issue in here as well as they are very similar and because Stale Bot closed mine. I am also unable to reproduce what you are experiencing.

#5292
