### ISSUE TITLE
Crash when trying to take a picture with flash

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-iOS#5503]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whren tryint to take a picture with flash, app crash. Without flash, everything goes smoothly.

### Steps to reproduce
- open conversation
- push the camera button
- enable flash from camera
- observe the crash

**Actual result:** Picture is taken with flash

**Expected result:** No picture is taken, flash does not fire and the app crash

### Device info

**Device**:iPad mini (5th generation)

**iOS version**: 16.1.1

**Signal version:** 6.5.0.14

### Link to debug log
https://debuglogs.org/ios/6.5.0/a73638143c8a73f2ad97f5b720de785341220d99b9bfd037f554a99730f5fd33.zip

**Comment by finn-signal** [comment]
I've gone ahead and filed this bug with our engineering team. While our engineers will be working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug included in the release notes for future versions of Signal.

Thanks again for your help in reporting this.
