### ISSUE TITLE
Voice Message Recording crashes on incoming PhoneCall

### ISSUE THREAD

**Issue by bircni** [signalapp/Signal-iOS#5507]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

If you are recording a Voice Message and you get a phone call - you can't save your Voice Message, if you push the "send"-button the Voice Message disappears, and you also can't stop the recording.

### Steps to reproduce
- start an audio recording
- get a phone call

**Actual result:** Voice Message Disappears

**Expected result:** Voice Message should be safed, as it is if you close the App while recording
### Screenshots

no Screenshots needed

### Device info

**Device**: iPhone 12 Pro, iPhone 11

**iOS version**: 15.* , 16.*

**Signal version:** 6.* and even before

### Link to debug log

No Logs are being generated - but I sent you my latest logs per Mail

**Comment by finn-signal** [comment]
Thanks for reporting. We'll follow up with you via our Support channel.
