### ISSUE TITLE
Signal messages ignore the Do Not Disturb focus mode

### ISSUE THREAD

**Issue by rloconnor** [signalapp/Signal-iOS#5508]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal messages do not respect the Do Not Disturb focus mode. This [issue](https://github.com/signalapp/Signal-iOS/issues/983) suggests the problem was resolved in 2017 when the CallKit APIs became available; however, it appears that the problem may have been (re)introduced recently. Please feel free to close this if it is still an API access problem as originally suggested in the linked issue.

### Steps to reproduce
- Enable the Do Not Disturb focus mode
- Switch off phone screen 
- Get someone to send you a message

**Actual result:** Phone vibrates/pings and the screen switches on

**Expected result:** Phone doesn't vibrate/ping and the screen does not switch on upon receipt of a message

### Device info
**Device**: iPhone 12 Mini

**iOS version**: 16.1.2

**Signal version:** 6.4.0.10

### Link to debug log
Exported zip file attached below; could not upload from within Signal.

[2022.12.18 11.11.16 885C7B76-2960-41BC-8C92-5E2B119C6D89.zip](https://github.com/signalapp/Signal-iOS/files/10254900/2022.12.18.11.11.16.885C7B76-2960-41BC-8C92-5E2B119C6D89.zip)

**Comment by pat** [comment]
It'd be nice to see this issue reopened and dealt with - as the iOS app continues to ignore Do Not Disturb mode (for calls as well as messages).

**Comment by dan937** [comment]
> It'd be nice to see this issue reopened and dealt with - as the iOS app continues to ignore Do Not Disturb mode (for calls as well as messages).

I can confirm it's still happening.  I also emailed support.

**Comment by AndreFCruz** [comment]
Still happening to me on iOS `18.0.1` and Signal `7.37 (448)`

**Comment by lynchwhy** [comment]
This is definitely still a problem. It's driving me crazy.

**Comment by redmondChris** [comment]
Still happening on iOS `18.4.1` and Signal `7.57.1`.

**Comment by femto-code** [comment]
Same here, still a problem. iOS 18.7, Signal 7.77.
This should be a priority to fix.

**Comment by max-signal** [comment]
I’m still not able to repro this issue. When I turn on “Do Not Disturb”, I don’t receive sounds/alerts/vibrations for incoming calls/messages. Have you configured some of the more advanced options to allow notifications/calls to bypass Do Not Disturb?

**Comment by rloconnor** [comment]
I've got exceptions in the "Do Not Disturb" focus to allow me to recieve calls from immediate family members in emergencies, some of whom also communicate with me via Signal (primarily via a group chat, rather than individually). However, the "Do Not Disturb" mode is also configured to block notifications from any app, hence I was expecting it to prevent notifications from Signal when enabled. I think these exceptions were configured after I opened this issue, but it was too long ago for me to be certain.

**Comment by lynchwhy** [comment]
I think @rloconnor might be on to something.
I think that if you have someone who is "allowed" through Do Not Disturb, then if they are in a group chat on Signal, you will get notifications from that group chat, which can be very spammy.

**Comment by Its-J** [comment]
> I think @rloconnor might be on to something.
> I think that if you have someone who is "allowed" through Do Not Disturb, then if they are in a group chat on Signal, you will get notifications from that group chat, which can be very spammy.

This fixed it for me, thanks!
