### ISSUE TITLE
Voice Memos get lost before sending when notifications / calls interrupt while recording a Voice Memo

### ISSUE THREAD

**Issue by 001101111011101101** [signalapp/Signal-iOS#5509]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Start recording a voice message.
During the recording a notification of an incoming call appears or one accepts an incoming call, the recording does not visibly fail and one is able to continue the recording. 
The recorded voice message disappears as soon as one tries to send it, without an error messages. Basically the app jumps back to the point where one would start recording a voice message. 

### Steps to reproduce
- Start recording a voice memo by sliding the Mic Button up
- while recording receive a call (incoming call notification)
- the recording continues, whether the call is accepted or rejected or ignored

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- pressing the 'Send' Icon does nothing, the recorded Voice Memo just disappears

**Expected result:** Describe here  s dog  food  should happen after you run the steps above (i.e. what would be the correct behaviour)
- to have the recorded voice memo send or at least an error notification and a choice to either trash or send the recording

### Device info

**Device**: iPhone 12 Pro Max

**iOS version**: 16.2.0

**Signal version:**  6.6.0.14

### Link to debug log
https://debuglogs.org/ios/6.6.0/73dccfae382084833405b915a04e9f85da6e82613bfa1f41ba6152a638d011c1.zip

Voice Memo was started at around 2022/12/20 12:40
Call Notification came in at 2022/12/20 12:43

**Comment by Yolakalemowa** [comment]
> I can't reproduce the disappearing message issue, but I'll ask our Product team about what should happen to the recording if you receive a call. We may wish to make small changes here.
> 
> I'm going to close this because I can't reproduce.

Hi, I wanted to ask if you received any info on this issue?

When receiving calls while recording a vn it disappears and I have to record it all over again.
