### ISSUE TITLE
Repeatedly opening and closing message details via swiping causes scrolling / jumping

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#5511]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Repeatedly opening and closing message details by swiping on a message bubble with the keyboard open causes the chat to scroll/jump (by a fixed amount), instead of staying in place.

### Steps to reproduce
1. Open a chat.
1. Tap in the message input field to open the on-screen keyboard.
1. Scroll the chat so that it's not at the very bottom.
1. Then, repeat the following actions:
    - Swipe from right to left on a message bubble so that you feel the haptic feedback of message details opening.
    - While still keeping your finger on the message bubble, swipe slightly from left to right to "cancel" opening message details.

Note: if you don't release your finger, you can keep doing the gesture even if the message you swiped on is not visible on the screen.

**Actual result:** Each time step 4 is repeated, the chat scrolls down by a fixed amount.

**Expected result:** The chat shouldn't scroll.

### Screen recording

https://user-images.githubusercontent.com/19972511/209439015-8a74069d-51bc-46d9-8caa-a3a250cb46a7.mp4

After reproducing the bug, the message bubble you swiped on may get temporarily stuck in a state like this:

<img src="https://user-images.githubusercontent.com/19972511/209439000-c00890ee-e90a-4dfa-808e-55f6874addec.jpeg" width=250>

### Device info
**Device**: iPhone XR
**iOS version**: iOS 16.3 Public Beta (20D5024e)
**Signal version:** 6.6.0.15

### Link to debug log
https://debuglogs.org/ios/6.6.0/9a63a9157a6d90e91f322fbf5593ac11a65561864af417a9c9271c2cabc474de.zip

**Comment by andrew-hill** [comment]
this is repeatable on iPhone XS, Signal version 6.7.0.22, iOS 16.2 (not beta) in both portrait and landscape screen orientation
