### ISSUE TITLE
Crash at tapping group call button

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#5514]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Crash after tapping on group call (camera) icon.

### Steps to reproduce
Not reproducable.

I did this:
- opened a group chat
- browsed between stickers a lot. Not sent any of them
- switched back to keyboard
- tap on group call (camera) button above

### Device info
**Device**: iPhone SE 2020

**iOS version**: 15.7

**Signal version:** 6.6.0

### Link to debug log
Restarted Signal, tried to reproduce the issue (could not), then collected this debug log.
https://debuglogs.org/ios/6.6.0/2350f262071547d7af410f533e5bc45762c04b365ff746872bb98d55af66a37e.zip

**Comment by kaktusztea** [comment]
Crash log sent in email.

**Comment by EvanHahn-Signal** [comment]
I reviewed your logs. It looks like a catastrophic failure creating a system thread, which should be rare.

If it happens again, let us know.

**Comment by kaktusztea** [comment]
OK, will reopen if it happens again.
