### ISSUE TITLE
heard some other conversation for about 8 seconds

### ISSUE THREAD

**Issue by senecaconsultancy** [signalapp/Signal-iOS#5516]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was on an audio call with my son. The call lasted over 10 minutes. At one point in the call, my son's voice faded, there was silence, then I heard someone else talking (in English) for about 5 seconds, then my son's voice was back. The 'interval of disturbance' last approximately 8 seconds.

### Steps to reproduce
- no ideas, not easily reproducible.

**Actual result:** accidental eavesdropping on another call

**Expected result:** hearing only the call in which I believe I am participating: privacy!

### Screenshots
not applicable

### Device info

**Device**: iPhone SE2020

**iOS version**: 16.1.2

**Signal version:** 6.6.0.14

### Link to debug log

none available as this bug is not easy to reproduce
good luck!

**Comment by EvanHahn-Signal** [comment]
Sorry about this.

Something would have to be going _very_ wrong for this to be a Signal issue. You'd have to get the encrypted data for another call (which is very unlikely given how Signal is built) _and_ the decryption key (also very unlikely).

Is it possible your son played some audio into the microphone, or that an app played something on your phone, or something like this?

I don't think this is a Signal bug so I'm going to close. If you can find a way to reproduce this or offer more info, let us know.

**Comment by senecaconsultancy** [comment]
I understand your skepticism. But it was not my son playing audio into the microphone, nor any spurious playback on my device.
It is obviously not something that can be easily reproduced. It will recur, eventually.
There's not much for you to work with here, I understand, but it would be irresponsible of me to leave it unreported.
