### ISSUE TITLE
SignalServiceKit is not sync with the podfile.lock.

### ISSUE THREAD

**Issue by ZaynaxiOSDev** [signalapp/Signal-iOS#5517]
<img width="714" alt="Screenshot 2023-01-03 at 6 35 43 PM" src="https://user-images.githubusercontent.com/89276510/210359228-a5e590fc-fad7-4c26-a73f-9efc4140470c.png">

I can't run Signal-iOS by cloning.

I tried pod install, but it won't work.

**Comment by EvanHahn-Signal** [comment]
Could you try running these commands from the project root?

```sh
make dependencies
bundle exec pod install
```

**Comment by ZaynaxiOSDev** [comment]
Thanks. I just tried both of the commands. But they are showing error.

![Screenshot 2023-01-04 at 12 25 16 PM copy](https://user-images.githubusercontent.com/89276510/210512031-eefcbc7f-5722-4416-9036-05e65db35a70.gif)

After that i tried **bundle install**
But it returns error also :( 

<img width="521" alt="Screenshot 2023-01-04 at 12 29 03 PM" src="https://user-images.githubusercontent.com/89276510/210512188-b547d845-3b30-4876-9063-d87282bbc521.png">

<img width="679" alt="Screenshot 2023-01-04 at 12 29 10 PM" src="https://user-images.githubusercontent.com/89276510/210512197-82e05e10-7f74-49ee-8292-5347cd0544e7.png">

I was using Cocoapods and Gem Version: 

<img width="574" alt="Screenshot 2023-01-04 at 12 18 10 PM" src="https://user-images.githubusercontent.com/89276510/210511674-f4b26770-d59b-4c0b-86bb-ec6f64897b0c.png">

**Comment by EvanHahn-Signal** [comment]
I believe this should now be fixed. Let me know if this still happens.
