### ISSUE TITLE
Not getting Authentication Code in Oman

### ISSUE THREAD

**Issue by maxix9** [signalapp/Signal-iOS#5519]
I have been trying to log in to the app for more than a week now. I tried requesting to resend the code and call me option and still nothing happens. I tried on multiple numbers on the same country code and still no code at all. Please fix this issue. 

This is the second time this has happened. Before it was fixed and I got the code, but now same issue again!

Ps: I am on the latest version on the AppStore.

**Comment by EvanHahn-Signal** [comment]
Have you reached out to Signal support? They may ask you to check your VPN connection and then share a debug log after some troubleshooting steps. You can fill out the form at <https://support.signal.org/hc/requests/new>.
