### ISSUE TITLE
Google Meet Links not clickable

### ISSUE THREAD

**Issue by applechief** [signalapp/Signal-iOS#5521]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing the sharing message from google meet, the url to the meeting is not clickable.

### Steps to reproduce
- Open the gmail app on the iphone, go to the meet tab, click on new meeting, get joining info to share, copy the joining message. it should be similar to the below
``` 
John Doe has invited you to join a video meeting on Google Meet.

Join the meeting: https://meet.google.com/xxx-xxxx-xxx

Dial in (audio only): ‪(US) +1 478-419-3234‬ PIN: ‪775 214 075#‬
Other numbers: https://tel.meet/xxx-xxxx-xxx?pin=0000005063000
```
- paste the message into signal and send the message

**Actual result:** The message will be shared, but the link to the meeting `https://meet.google.com/xxx-xxxx-xxx` will not be clickable

**Expected result:** The user should be able to click on the meeting link directly from the chat to go to the meeting

### Screenshots
![IMG_1539C16E8B7B-1](https://user-images.githubusercontent.com/1122089/210565352-c0da6089-64cd-4473-8e35-1218abc2c960.jpeg)

### Device info

**Device**: iPhone 12 Pro

**iOS version**: 16.1.2

**Signal version:** 6.6.0.14

**Comment by hywongbu** [comment]
The `canParseURLs` func in `LinkValidator` treat the `\u{202C}` as problematic character and refuse to parse anything in the text as URL.
<img width="1230" alt="Screenshot 2023-03-31 at 12 05 09 AM" src="https://user-images.githubusercontent.com/61628589/228897273-13f6900a-f617-460c-af3b-d68b29130035.png">

I guess this is expected to prevent, as the name suggested, problematic character messing up the URL.
