### ISSUE TITLE
Unable to share stories

### ISSUE THREAD

**Issue by mthld** [signalapp/Signal-iOS#5524]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a few days I'm unable to share stories from Signal iOS. However, it works properly on Signal Desktop.

### Steps to reproduce
- Choose any photo
- Select recipients
- Send

**Actual result:** The status of the story is "Sending...", I can wait for a few minutes but it doesn't go through. After a while it's marked as "Send failed".

**Expected result:** The story should goes through as on Signal Desktop

### Screenshots
![IMG_155D2FC65B0F-1](https://user-images.githubusercontent.com/41020854/212672289-cdc98d3b-5ca1-4745-8697-2689de7d6850.jpeg)

### Device info

**Device**: iPhone SE 2nd gen

**iOS version**: 16.2 (20C65)

**Signal version:** 6.7.0.22

### Link to debug log

Tons of errors: https://debuglogs.org/ios/6.7.0/a633612faf40be29a1bc72ff1ea7668ed789255038caeb38e976c9f75fa6272a.zip

**Comment by sarumaj** [comment]
Same issue on Iphone XR iOS 16.2 (+1)

**Comment by EvanHahn-Signal** [comment]
The latest version should have a fix for this bug. Thanks for reporting!

I'm going to close this issue, but feel free to open a new one if you continue to have problems sending stories.
