### ISSUE TITLE
Complete data loss: adding another phone

### ISSUE THREAD

**Issue by richlv** [signalapp/Signal-iOS#5527]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description
This is not a classic bugreport with easy steps to reproduce and a simple display oddity or a similar minor issue.
Still, I sincerely hope somebody at Signal will have the desire to test this scenario.
I've lost all my message history over many years.

This is a tale of two iPhones.
iPhoneX is my "new" phone, and iPhone6 is the old one.
Had used Signal on 6, moved to X later.

Today I "added" Signal on iPhone6, expecting to have messages on both.

Lesson 1
Perhaps the warning when adding a device about other phones being disconnected should be much more obvious.
I actually knew about this limitation. But today I had forgotten, and I did the totally user thing, by not reading the text at the very bottom, not highlighted in red or in any other way.

After I added it, I noticed that some notifications only popped up on the old phone, not on the new one - but did not pay much attention to it... until I attempted to view messages on the new phone.
That was a bit sad moment. But the worst had not even started.

Realising that I had disconnected my new phone, I promptly attempted to re-register it.
Received the confirmation code in SMS, chose the option to switch without transferring the whole history... and then the spinner showed up, and there was no progress. Allowed it to run for some time, perhaps about an hour.
Hit "Cancel".
Now the option to switch without transferring did not work - I could tap it and it flashed, but nothing happened.
I briefly hit the "import from another iOS device", but that was not desirable, so I cancelled that.
Stepped one step back, and it requested the SMS code again.
Received the code... but then it complained that the code is invalid. Re-sending only gave me the same code.
Perplexed, restarted the app. Now it asked for PIN.
But... did not accept my PIN. The same that had worked just recently on the old phone.
Tried many times, even restarted the phone, "just in case" - no luck. Asks for the PIN, does not accept the correct one.

So I decided that I could re-try switching it back to the old phone, then to the new one again.
Went through the dance on the old phone... which now also was hanging on the progress spinner. Cancelled it on the old phone, observed the same effect where that option would flash when tapped, but nothing would happen. Briefly entered the "transfer from another iOS device" option, backed out of it.

Ar a loss, restarted the app on the old phone. It asked for SMS code again, and this time switching without transferring worked.
Except that this time it asked to enter a new PIN, not the old one.

So now I have lost it all - on the new phone, with all the messages, I cannot get anywhere at all, as all it does is asks my PIN. And then rejects the correct one.

I really, really hope that somebody from Signal has some interest in this and some time to do extensive testing of steps that could have caused complete data loss.

About to delete Signal from the new phone, as I cannot access any data anyway.
If somebody can chime with a magic solution before that, that would be a miracle.

Debug log: https://debuglogs.org/ios/6.8.0/8ae9bc1051a543982fafdee4b862f82eee1590852abb96373777cdd7541844d5.zip .

To be safe, a fresh start + failed PIN: https://debuglogs.org/ios/6.8.0/0ad6db49fe3b0424f7a0ac33b411c4d1eb543259240f32ab0f7fe5d06a529640.zip .

**Comment by richlv** [comment]
Well, this is depressing :)
There's an iCloud backup - perhaps whatever got messed up in the app config can be restored from it (without affecting anything else on the phone)?

**Comment by NiklasBr** [comment]
How did you managed to create an iCloud backup of your Signal data? It usually looks like the developers have gone an spent lots of time and energy to go the extra mile just to prevent us from backing up…

**Comment by richlv** [comment]
There's no Signal message data included - I just hope there could be some config that would allow the app to work again.
The messages are still on the new phone, judging by the app size.

**Comment by richlv** [comment]
Interestingly enough, https://support.signal.org/hc/en-us/articles/360007320451-Troubleshooting-multiple-devices#ios_multiple_device says:

"Tap on the "Device no longer registered" banner to re-register Signal on your phone to make it the active device. After registering again, this phone will be connected and your other device will go offline."

But I'm not getting such a banner.

**Comment by richlv** [comment]
Got the initial response from Signal support, nothing since then.
Looks like I'll have to delete Signal, losing all that message history on the phone.

**Comment by richlv** [comment]
Status update: decided to give up.
After entering the (correct) PIN which was not accepted, selected "Need help" and "enter new PIN".
Got an SMS with code again, entered that. Entered my old PIN.
And a very happy surprise - it looks like it allowed access to all the message history on the new phone.

So there's a UX improvement possible (a modal popup when attempting to "add another phone"), and a bug somewhere when doing the transfers.
I'm not volunteering to test for that bug with my phones anymore, though :)
