### ISSUE TITLE
Linking Devices failing - Invalid response from serivce

### ISSUE THREAD

**Issue by TheBeaconCrafter** [signalapp/Signal-iOS#5532]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't link my iPad or any new device (Laptop) to my Signal account. When trying to do so, all I get on my phone is "Invalid response from service". I found a few reports of this issue happening in 2021, see here: https://github.com/signalapp/Signal-Desktop/issues/5529

They changed something in the signal server and that made it working again. Maybe it's a similar issue?

### Steps to reproduce
- open Signal on iPad or Laptop
- Scan QR code on iPhone

**Actual result:** iPhone shows a message saying "Invalid response from service"

**Expected result:** The devices should pair.

### Screenshots

![image](https://user-images.githubusercontent.com/82443014/214031705-ed22346b-1c5b-43bb-94b4-c6b401ec0653.png)

### Device info

**Device**: iPhone 13 + iPad Pro 2017

**iOS version**: Both on 16.2

**Signal version:** Both on 6.8.0.10

### Link to debug log

https://debuglogs.org/ios/6.8.0/8762dc1cf68c8faf80e92752e1a9bcb2d297675fe040e9c481e0b87f33364c91.zip

**Comment by TheBeaconCrafter** [comment]
> Same problem here on my iPhone 12 with iOS 16.3.
> 
>  Let me know if you need more info for debugging.

So Signal Support told me that there is a maximum of 5 devices per account. Maybe that's the problem for you too?

**Comment by tomofdarkness** [comment]
> > Same problem here on my iPhone 12 with iOS 16.3.
> > Let me know if you need more info for debugging.
> 
> So Signal Support told me that there is a maximum of 5 devices per account. Maybe that's the problem for you too?

I have ten linked devices already, so this is demonstrably false...  But also I'm having this problem now.

**Comment by tomofdarkness** [comment]
> > > Same problem here on my iPhone 12 with iOS 16.3.
> > > Let me know if you need more info for debugging.
> > 
> > 
> > So Signal Support told me that there is a maximum of 5 devices per account. Maybe that's the problem for you too?
> 
> I have ten linked devices already, so this is demonstrably false... But also I'm having this problem now.

Ah, ok.  so there's a NEW limit of 5 devices.  I dropped down below 5 for testing and was able to add this new one, but now I don't have it on one other machine that I'd like to have it on.  Why the sudden arbitrary limit?

**Comment by rchost1** [comment]
Do the iPhone and the laptop need to be on the same network subnet in order to do the linked device pairing? Could that be why I'm getting this error?
