### ISSUE TITLE
Cant install Signal app on ios

### ISSUE THREAD

**Issue by sobrudolph** [signalapp/Signal-iOS#5534]
iPhone SE (new model)
iOS 16.2

Signal need update. It was written in AppStore. So my fried push button update. It was only rolling and rolling. Nothing happent. He uninstal Signal app and try to instal again. But the same, it is rolling and nothing happent.

- he tried reset (volume up/down and hold button) iphone -nothing
- he tried instal Signal app over another apple ID - nothing
- he tried instal Signal app on another iPhone with his apple ID - it was not a problem with instalation

uploaded video from instalation: https://ufile.io/16mkf3y6

Thanks for a help

**Comment by Miguel-Signal** [comment]
Hi @sobrudolph, Sorry to hear you are having an issue installing Signal.

In order to look into this further could you please provide the following info?

- Can you go to Settings > General > iPhone Storage and tell me how much available storage space you currently have on this device?
- Can you tell me if you can download other apps from the app store?
- If possible, can you try installing Signal again while on a different wifi network or while on mobile data?

**Comment by sobrudolph** [comment]
@Miguel-Signal 
it is my friend mobile but i did it:
- free storage was over 50GB
- other apps it is possible download, problem is only with signal
- i was try to instal it from wifi or from mobile data - but wasnt possible

**Comment by Miguel-Signal** [comment]
@sobrudolph Can you have your friend check their time/date settings on that device and ensure it is correct?

**Comment by Miguel-Signal** [comment]
@sobrudolph Some other things that may be helpful: 

- What country/locale your friend is in?
- Can they check if a hard reset resolves it? (Press the volume up button and release quickly, press the volume down and release quickly. Then keep holding the side button for a while until the Apple logo appears)

**Comment by sobrudolph** [comment]
@Miguel-Signal yes i was written this steps to my friend, but dont have a time today to try it... i will let you know ;) Give me a time... thx

**Comment by sobrudolph** [comment]
@Miguel-Signal 
- reset - volume +/- and holding side button - after reset nothing happent
- date and time are set right
- he tried another iphone, but the same model iphone SE (2020) with the same iOS 16.3 - there was not a problem with instalation
- he is located in Slovakia
