### ISSUE TITLE
Archived and Muted conversations get unarchived with new messages

### ISSUE THREAD

**Issue by joobei** [signalapp/Signal-iOS#5540]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Muted and Archived group conversations become unarchived when new messages arrive.

### Steps to reproduce
- Mute a conversation
- Archive the conversation
- a new message arrives in that conversation

**Actual result:** Conversation gets unarchived and shows up at the top of the chats list.

**Expected result:** Conversation remains archived.

### Device info
**Device**: iPhone 13

**iOS version**: 16.0

**Signal version:** 6.11.0.11

**Comment by max-signal** [comment]
Can you confirm that “Keep Muted Chats Archived” is enabled in Signal Settings -- Chats?

**Comment by joobei** [comment]
Thank you for your prompt response! Apologies I was unaware of that setting.
