### ISSUE TITLE
iOS app shows wrong time for missed signal call, revealing time zone of caller

### ISSUE THREAD

**Issue by christianzoellner** [signalapp/Signal-iOS#5541]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Missed call showes with the caller's time, not with my own, thus revealing that the caller is in a different time zone. While in this case I was aware of the caller's location, I would generally expect from a privacy-optimized messenger not to reveal such data. (Given that it's +/- 1 hour, it might also be a summer-winter-time screwup.)

When the same caller called and misscalled me on an Android device, my local time was displayed.

### Steps to reproduce
- have someone call you on Signal who is in a different time zone
- do not accept the call
- look at the respective chat in the iOS App

**Actual result:** The missed call showed up in the chat with the callers time zone rather than with my own.

**Expected result:** The missed call shows up with my time zone, just like outgoing calls do.

### Screenshots
![image](https://user-images.githubusercontent.com/4678160/218315189-8b801898-601a-4ddb-b698-113304496e51.png)

### Device info

**Device**: iPad Pro

**iOS version**: iPadOS 16.2

**Signal version:** 6.10.0.86

**Comment by max-signal** [comment]
The timestamps shown here are [Unix times](https://en.wikipedia.org/wiki/Unix_time), which don’t have a time zone associated with them. (One way to think about this is that Signal “converts” the time zone from your local device to UTC.) Based on the behavior you’ve described and the screenshots, your device’s Unix time is one hour ahead of the caller’s Unix time. Even if the time on a device looks right, it may still be wrong if the time zone is set incorrectly. This is most likely what’s happening.
