### ISSUE TITLE
Restore on new iPhone stuck at 99 %

### ISSUE THREAD

**Issue by robinloeffel** [signalapp/Signal-iOS#5545]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to transfer the chats from an old iPhone to a new one, the progress gets stuck at 99 % with 0 seconds remaining.

### Steps to reproduce
- Have a newly set up iPhone
- Have another iPhone
- Open Signal on the new phone
- Type in phone number
- Tap on "Transfer from other iOS device"
- Open up Signal on other phone
- Scan QR code
- Wait

**Actual result:** The progress is stuck at 99 % and with 0 seconds remaining on both devices.

**Expected result:** The chats are transferred from the old iPhone to the new iPhone.

### Screenshots
![IMG_1524](https://user-images.githubusercontent.com/6851646/219364182-d14dd7f3-580d-4fd2-96a1-b8c5fa3d1b8a.PNG)

### Device info

**Device**: iPhone 12 & iPhone 13
**iOS version**: both iOS 16.3.1
**Signal version:** both 6.11.0.11

### Link to debug log
n/a

**Comment by MartinWeindel** [comment]
I had the same problem with transferring from iPhone SE to iPhone 14. 
More than five tries failed with stucking at 99% (iPhone SE was on left side of the iPhone 14).
My wife resolved the issue by moving the iPhone SE to the right side of the iPhone 14  😂. Of course I can say if it was just coincidence, but it may be worth a try.

Signal version: both 6.17.0

**Comment by patricklangerMD** [comment]
Same issue here trying to transfer from an iPhone SE 2020 to an iPhone 13.
Both on iOS 16.4 / Signal 6.17.0.10.
This is very annoying and you can find a lot of similar cases, and most of the cases people solved this by retrying over and over again.
Already the 5th attempt… close to the end of my tether. But I don’t want to loose my message history! 😖

**Comment by kyrylkov** [comment]
Same issue here on iOS 16.4

**Comment by niklaas-0rbit** [comment]
Same issue here, transferring from iPhone SE2 to SE3 and transfer got stuck on 4 tries now... idk what to do to get my chat history on the new device...

**Comment by marcosmolla** [comment]
Same experience (iPhone 11 -> iPhone 13 mini)

**Comment by maxnnina** [comment]
I had the same issue going from iPhone SE2 to SE3 with the transfer getting stuck at 99% (4 tries also).  Here's what worked for me:  I did a "force re-start" on both phones ( https://support.apple.com/guide/iphone/force-restart-iphone-iph8903c3ee6/ios ) and after both phones finished rebooting the transfer worked on the first try.

**Comment by gkuhns** [comment]
> I had the same problem with transferring from iPhone SE to iPhone 14. More than five tries failed with stucking at 99% (iPhone SE was on left side of the iPhone 14). My wife resolved the issue by moving the iPhone SE to the right side of the iPhone 14 😂. Of course I cannot say if it was just coincidence, but it may be worth a try.
> 
> Signal version: both 6.17.0

It was certainly worth the try for me. It failed twice. I changed nothing else except the position of the phones. Initially the XS was (face up) on the left side of the 14. It failed twice in that position. I switched positions and it worked the first time.

**Comment by mrc247-DE** [comment]
Same issue here

**Comment by jeff-dh** [comment]
Same here.

But, maybe some more information: When the transfer got stuck I had two different signal version on the two phones (new: 6.17.x and old: 6.35.x). I updated the new phone to 6.35 and repositioned the phones (as mentioned above) and it worked immediately. Don't know whether it was luck or whether the mismatched versions might have been the issue.

**Comment by high-output** [comment]
Can confirm!

**Comment by turing** [comment]
Same issue. This is a pretty big deal. The transfer also takes about as long as the entire data transfer phone to phone!

**Comment by mrc247-DE** [comment]
The changelog says that the error was fixed with version 6.47:

> We fixed a bug that sometimes caused re-registration to get stuck at 99%, which was 100% annoying if it happened to you. Thanks to everyone who helped us troubleshoot this problem.

https://github.com/signalapp/Signal-iOS/releases

**Comment by AnotherPseudonym** [comment]
I also had this issue (iPhone SE1 on version 6.50.0.13 to iPhone 15 Pro 6.50? - I can't check the version, but no updates show in the app store). I've tried a full reset on both, and positioning them on top of each-other, beside each-other, and a few inches apart. I guess I'll keep trying.

**Comment by davepolit** [comment]
I'm pretty sure this is a Bluetooth issue. The fact that it does work if you move the phones around points in that direction, also the fact that the issue occurs after 99% success und "1" or "0" seconds remaining. I moved the phones around a little and everything went OK. I guess Bluetooth hangs.

**Comment by Jimmer26** [comment]
Just to add, transfer failed 3 times between iPhone 13 Pro and iPhone 16 Pro. I think for all attempts 13 Pro was to the right of the 16 Pro a few cm away, both screen up, both with up to date apps (v7.34). Just tried again, moving 13 Pro above the 16 Pro and rotated 180 degrees (so top of screen to top of screen orientation both screens facing up), about 15 cm apart. The transfer was a success. So yeah could be Bluetooth but who knows. Thanks for the tip!

**Comment by Arthaey** [comment]
I failed for me in the same way, trying to transfer history from a 1st gen SE to a 13 mini. Signal v7.40.5

**Comment by DeepBlueChris42** [comment]
@Jimmer26 That is exactly how I could make the transfer of Sgnal work from iPhone SE 2nd gen. to iPhone 13 Pro: turn the phones so that there tops were facing each other. 👍
That worked after my first attempt with both phones side by side the transfer got stuck at 99% and 0 seconds left.

**Comment by mu-zzi** [comment]
@Jimmer26 I can confirm that rotating the devices and aligning them head-to-head was working for me at first try. Thank you for the hint!

**Comment by jtrumpio** [comment]
Happening to me right now.  This process is absolute trash and has been for years.  Every time I get a new phone or help friends migrate this process is broken in some way, super slow, or never finishes.

  ![image](https://github.com/user-attachments/assets/3d881ec3-70ad-4a05-b335-1f08533d64dd)

**Comment by ELLIOTTCABLE** [comment]
This happened to me last year, I don't recall how I got past it, and now I'm stuck here again. Carrying around two phones all day so that I can continue to talk to my Signal contacts until I can somehow get past this.

One of the biggest annoyances, is that this failure happens *after* 6 hours of data-transfer - if it's an intermittent problem that can be solved by retrying, that's … pretty horrible when you just left your phones (both of them?) behind all day, trying to give them a chance to successfully transfer.

Can we get this re-opened? This is definitely still an issue; and has been for years. (Good lord, I hate stalebots - I understand the value, but christ it's demoralizing when you're on the user end instead of the maintainer end.)

----

**Edit:** FWIW, after trying the "head-to-head" trick, it's succeeded. Hard to tell if that was actually the cause in improved behaviour without more trials. Does, indeed, seem like a wireless failure; but during all of my failed attempts, they were directly side-by-side for the entire process over many hours - it's hard to believe that moving the antennas literally 2 or 3 centimeters closer caused a success.

**Comment by keithbradner** [comment]
Just happened to me again as well. Third try was the charm but this is a pretty terrible UX.

**Comment by max-signal** [comment]
I’m going to keep this issue closed and suggest any future conversation moves to #5647. I suspect the root causes for that issue and this issue are either the same or closely related, and it’s going to be difficult to distinguish the type of failure based on the symptoms.
