### ISSUE TITLE
Photos shot on selfie camera differ from the end result

### ISSUE THREAD

**Issue by cstanislawski** [signalapp/Signal-iOS#5546]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While using the built-in camera in the Signal app & shooting selfies, the actual photos getting shot are mirrored (or more specifically, they do not get mirrored like in other apps/main iOS Camera app). While taking a selfie the user sees while_shooting.jpg, but the actual image being shot & shown to the user/sent in the chat is actual_photo.jpg.

### Steps to reproduce
1 Open the app
2 a) Go into the chat, select camera, switch to front-facing camera, take a photo.
2 b) Use the not-in-the-chat camera, switch to front-facing camera, take a photo.

**Actual result:** 
The end photo is a vertical-mirror of the photo being shown to the user while taking a photo on a front-facing camera.

**Expected result:**
The final photo shown to the user should be mirrored (or unmirrored), or, in other words, actual_photo.jpg should be the same as while_shooting.jpg. 

This is being reported as a bug, as this is the expected & default behavior in most of the popular apps. 
Signal behaving differently in this area is turning off people who might otherwise use it. This is the feedback I've gotten.

### Screenshots
![while_shooting.jpg](https://user-images.githubusercontent.com/57832191/219446218-1c29e740-1623-4db7-b9f2-bbabc68465d0.jpg)
![actual_photo.jpg](https://user-images.githubusercontent.com/57832191/219446209-c02099b8-d545-4e0f-9d82-f9b1424d00ae.jpg)

### Device info
**Device**: 
iPhone 13 Pro Max
from feedback gotten from others the behavior is the same on other devices

**iOS version**: 
16.2

**Signal version:** 
6.11.0.11

**Comment by josphh** [comment]
+1 for this. Really disappointing as it's turned a few of my friends away from using the app. No other app even does it like this, not even the android version of signal is like this. Sucks because it's gonna take them a lot of convincing to use the app again when it was a struggle in the first place.
