### ISSUE TITLE
Signal excruciatingly slow on iPhone

### ISSUE THREAD

**Issue by RobFog** [signalapp/Signal-iOS#5548]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using Signal 6.11 on an iPhone SE with iOS 15.7.3, the app runs excruciatingly slow when dealing with a large channel with over 800 members.

This problem may be more recent, may have appeared with the 6.11 update. The iPhone has plenty of storage space, with 27.2 GB of 32 GB used.

### Steps to reproduce
- Launch Signal.
- Try to open a a large channel. Try to open channel info. Try to close the large channel.

**Actual result:**
 It takes ages. Opening the large channel takes more than 10 seconds. Opening channel info takes a few seconds as does closing the channel.

**Expected result:**
I would expect slightly poorer performance with larger channels and due to the age of the device but not that much.

### Device info

**Device**: iPhone SE

**iOS version**: 15.7.3

**Signal version:** 6.11

**Comment by adiehl96** [comment]
Can reproduce, same problem in my case!

### Device info

**Device**: iPhone SE (2016)

**iOS version**: 15.7.3

**Signal version**: 6.11
