### ISSUE TITLE
Use System Contact Photos stopped working on ipad

### ISSUE THREAD

**Issue by phxnsharp** [signalapp/Signal-iOS#5555]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a recent update (currently using 6.11.0.11), the "Settings/Chats/Use System Contact Photos" option no longer works on iPads. It works fine on iPhones. All contact photos are only whatever default the other user has chosen for their Signal profile, or a plain circle with initials if they have not. I would like it to preferentially use the photo from the system contact photos, if one is set there. 

### Steps to reproduce
- Turn on "Use System Contact Photos"
- Cry

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
System contact photos are never used.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

System contact photos are used, just like on the iPhone

### Device info

**Device**: iPad Air 4th gen

**iOS version**: 16.2

**Signal version:** 6.11.0.11

### Link to debug log

The bug is not an event I can record. It just never uses the correct photos.

**Comment by WorldIRC** [comment]
Same issue here

**Comment by rbajevs** [comment]
Confirmed to be an issue on iPad 11" 2018 on Signal version 6.23.0

**Comment by Miguel-Signal** [comment]
This is expected behavior right now. Our developers will be looking into adding contact photos back to iPad at a later date.

Thanks for reporting this.

**Comment by Kingdom-Of-Heaven** [comment]
> This is expected behavior right now. Our developers will be looking into adding contact photos back to iPad at a later date.
> 
> Thanks for reporting this.

Any feedback on that?

**Comment by Kingdom-Of-Heaven** [comment]
> Confirmed to be an issue on iPad 11" 2018 on Signal version 6.23.0

Same on Signal 6.35.0.9 Ipad 3 12.9 " 2018

**Comment by ventz** [comment]
Seeing the same issue here on v `7.39` on the iPad 18.1.1
