### ISSUE TITLE
Deleted Contact still in contact list

### ISSUE THREAD

**Issue by ImpulsAntwort** [signalapp/Signal-iOS#5563]
This is the same issue as [4892](https://github.com/signalapp/Signal-iOS/issues/4892).
It occurs on Android.
A contact is deleted in the contact list of the phone but still shows up in the contact list of Signal.
I tried to add the contact back to the phone list and deleted it again, but this doesn`t work.

It is basic functiomality and also a __privacy issue__.

**Comment by smishralm10** [comment]
Only issues related to [iOS](https://github.com/signalapp/Signal-iOS) should be raised here. To raise issue for android checkout [Signal for Android](https://github.com/signalapp/Signal-Android).

**Comment by Miguel-Signal** [comment]
Hi @smishralm10,

Completely deleting a contact from Signal isn't currently supported, but we appreciate you taking the time to give us feedback and suggestions.
