### ISSUE TITLE
Signal window isn't blurred during app switching

### ISSUE THREAD

**Issue by VadimMuhtarov** [signalapp/Signal-iOS#5567]
### Bug description
Signal content isn't blurred during app switching

### Steps to reproduce
- turn on Face ID lock in the Signal settings with immediate blocking 
- switch to another app
- swipe to see all opened apps

**Actual result:**
Signal window is still visible and not blurred 

**Expected result:** 
Signal window becomes blurred immediately after switching to another app

### Screenshots
![image](https://user-images.githubusercontent.com/17072773/227302465-03d5d458-4a55-4154-9324-59403965c0dc.jpeg)

### Device info

**Device**: iPhone 13

**iOS version**: 16.3.1

**Signal version:** 6.17

**Comment by sashaweiss-signal** [comment]
Hi! FaceID lock is a separate setting from the app-switcher screen blocking. Can you confirm you've toggled both settings on?

<img width="343" alt="image" src="https://user-images.githubusercontent.com/105739406/227386347-e48f70e2-2e6f-49f5-bac6-01f9ed0e2eb3.png">

**Comment by VadimMuhtarov** [comment]
Damn, it was turned off, closing this issue.
