### ISSUE TITLE
Splash screen is quite light when using dark theme

### ISSUE THREAD

**Issue by rakleed** [signalapp/Signal-iOS#5570]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The splash screen is quite light when using the dark theme, and at night or in a dark room it is quite unpleasant to the eye.

### Steps to reproduce

- Open Signal

**Actual result:** the splash screen is quite light when using the dark theme

**Expected result:** the splash screen is dark when using the dark theme

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/227664421-8721b161-bc26-494b-8a93-b5267460d094.png)

</details>

### Device info

**Device**: iPhone XR

**iOS version**: 16.3.1

**Signal version:** 6.17.0.10

### Link to debug log

https://debuglogs.org/ios/6.17.0/c8425a3b26835e39d8812ed0044bf5a23708784cd9755753bca71449b783d657.zip

---

Follow-up https://github.com/signalapp/Signal-iOS/issues/5318: this is a bug report because you didn't adapt the splash screen to the dark theme. In the repository for the desktop app, you considered this a bug and fixed it: https://github.com/signalapp/Signal-Desktop/issues/5883

**Comment by Miguel-Signal** [comment]
Hi @rakleed,

This isn't currently supported, but we appreciate you taking the time to give us feedback and suggestions.

I've gone ahead and filed this with our engineering team. I unfortunately can't give out a specific timeline for a resolution. 

We would encourage you to provide feature requests on the community forum also, which can be found here: https://community.signalusers.org/
