### ISSUE TITLE
Forwarding a photo which was sent with other photos forwards all photos

### ISSUE THREAD

**Issue by jbg** [signalapp/Signal-iOS#5573]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening a single photo which was sent to me together with other photos, and then forwarding this photo to someone else, forwards all photos that were sent together. There is no indication in the UI that the other photos will be sent. This behaviour can cause users to forward photos that they did not intend to forward.

### Steps to reproduce
1. Using three Signal accounts, A, B and C:
2. Send two or more photos from A to B
3. Open one of the sent photos on B and forward it to C

**Actual result:** All photos sent in step 2 have been sent to C, rather than only the photo that was opened. The UI did not indicate in any way that this would occur.

**Expected result:** Only the photo that was opened when the "forward" button was tapped has been sent to C. Alternatively, the UI should make clear that other photos, that just happened to be sent together with the open photo, would also be forwarded, and perhaps offer the option of sending only the photo that was opened.

**Comment by Miguel-Signal** [comment]
Hi @jbg,

Thanks for bringing this to our attention. I've gone ahead and filed this with our engineering team. While our engineers will be taking a look, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this included in the release notes for future versions of Signal.
