### ISSUE TITLE
Missing UI Feedback while sending a reaction to a contact with a new security number.

### ISSUE THREAD

**Issue by easyMaxi** [signalapp/Signal-iOS#5574]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A contact changed the phone and now has a new security number. I get a short red banner when I open the chat, but it disappears when I scroll. When I send a reaction (click, hold, choose smiley) to the previous message. The reaction appears shortly and then disappears without any explanation.

### Steps to reproduce
- have a contact verified
- the contact changes the phone (security number)
- open an existing chat with the contact
- click an old message, hold and choose smiley

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The smiley appears shortly and then disappears.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
I would expect a warning, just like when I try to send a text message. This happens when I try the same on the MacOS App.
(I also expect the red banner to stay in place and not disappear, but there may be a reason for that.)

### Device info

**Device**: iPhone 12 mini

**iOS version**: 16.4

**Signal version:** 6.17.0.10

### Link to debug log
It is not a crashing bug.

**Comment by Miguel-Signal** [comment]
Hi @easyMaxi, 

I've gone ahead and filed this bug with our engineering team. While our engineers will be working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug included in the release notes for future versions of Signal.

Thanks again for your help in reporting this.
