### ISSUE TITLE
Can't register my phone number (Iraq)

### ISSUE THREAD

**Issue by sososarraa** [signalapp/Signal-iOS#5577]
Hi, it has been a day of endless attempts to register my phone number but this message keeps showing up: "_something went wrong, please try again later_"
I tried all the sloutions I found on google and I emailed them but no response. Can anyone help? Thanks

**Comment by rocodes** [comment]
Reporting (on behalf of another user) the same issue and same error message. The user is on iOS 16.4.1, the user is on Signal version 6.20, and the phone is an iPhone 8+.

In this case the error message appears almost immediately. In terms of debug log, the user does not see a URL they can paste in using [the described method for collecting debug log during registration flow](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug). The user is using a number for registration that cannot receive SMS messages. The user has no other network issues, no firewall or VPN enabled, and has network connectivity (tried on multiple networks).

Please let me know if there is any other helpful information that I can provide.
