### ISSUE TITLE
No keyboard to input verification code

### ISSUE THREAD

**Issue by musbur** [signalapp/Signal-iOS#5579]
I'm trying to install Signal on an IPhone SE. I got to the point where it texts me a message which I'm supposed to enter into signal; however that is not possible because it doesn't show me a keyboard. Just "Please enter the code we have sent you" and then six dashes across the screen. How does this work?

**Comment by Genacide666** [comment]
Same problem on iphone 8. Help solve.

**Comment by harry-signal** [comment]
Hi all! Sorry about this; the tap target to pull up the keyboard is just the first digit. You gotta tap a small area above the first underline, and that should let you proceed!

This is unintentional and we'll be updating it to let you tap anywhere in the entry view to pull up the keyboard. Thanks for reporting!
