### ISSUE TITLE
Scrolling dismisses emoji reaction picker

### ISSUE THREAD

**Issue by skjiisa** [signalapp/Signal-iOS#5591]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Scrolling up (swiping down) while the emoji reaction picker is presented can causes the sheet to minimize or dismiss. The scroll gesture isn't differentiated from a dismiss gesture.

### Steps to reproduce
- Open the emoji reaction picker on a message
- Scroll far down (by swiping up)
- Swipe down

**Actual result:** The emoji picker either minimizes or is dismissed

**Expected result:** The emoji picker scrolls up

### Screenshots

https://github.com/signalapp/Signal-iOS/assets/10291615/8bafccff-aec2-4bd2-b581-94b04b710d67

### Device info

**Device**: iPhone 13 Pro

**iOS version**: 16.4.1 (a)

**Signal version:** 6.22.0.9

### Link to debug log

https://debuglogs.org/ios/6.22.0/05f0fa226f1e6b87976c5660b22a0ad3bdcce274a250153912d2d0eb6535795a.zip

**Comment by claywintringham** [comment]
I can confirm that I am able to reproduce the bug.

Device info

Device: iPhone 12 Pro Max

iOS version: 16.4.1 (a)

Signal version: 6.25

**Comment by elaine-signal** [comment]
8f8445c5a120060eefeae3d880c9fc8511ec651d
