### ISSUE TITLE
Signal not allowing me to disable "Use system contact photos"

### ISSUE THREAD

**Issue by ludverse** [signalapp/Signal-iOS#5594]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I would like my Signal app to not use system contact photos over using regular signal profile photos. The problem is that when I toggle "Use system contact photos" off, nothing happens at all and I've had this issue for months but I've just been ignoring it because I didn't what to do about it.

### Steps to reproduce
- Make sure Signal has access to your iOS Contacts
- Disable `Use system contact photos` under Signal settings.
- Go back to your chats, and notice that the photos are still fetched from the Contacts app

**Actual result:**
ignore my picture of my dad
![bild](https://github.com/signalapp/Signal-iOS/assets/62475903/71384b8c-79e9-4c6d-8855-2aed3f21cf75)

**Expected result:**
(note: i accived this image by turning off Contacts permissions in iOS settings for Signal, witch is not what I want, I want it to still sync my contacts without using their Contacts pfp:s)
![bild](https://github.com/signalapp/Signal-iOS/assets/62475903/1ef29db8-10a6-4d12-8ec4-77d7ca342b27)

### Device info
**Device**: iPhone 8

**iOS version**: 16.3.1

**Signal version:** 6.22.0.9

### Link to debug log
https://debuglogs.org/ios/6.22.0/a7e6b926e9c66a1e70eb1ba92a0d59e6146ef51e44c447f51dd3eac530bf5802.zip

**Comment by ludverse** [comment]
Btw it works on iPad but only in reverse, it doesn't allow me to turn the iOS contact photos on. This toggle switch honestly needs to be reworked.

**Comment by Miguel-Signal** [comment]
Hi @ludverse,

Just to confirm, did you refresh your Signal contacts list after you disabled Use system contact photos?

To refresh your contacts:
Go to iPhone Settings > Signal and toggle contacts permissions off then back on.
Restart the phone then open Signal.
Tap on the message compose icon, and pull down on your contact list until you see a loading icon.

**Comment by ludverse** [comment]
Yup I've done that. I toggled contacts on and off once again and restarted my phone just to be sure, but no it's still there. I've had `Use system contact photos` disabled for months now but the bug hasn't gone away.

**Comment by Fiery-Penguin** [comment]
Still non-working in Nov 2025. Only one of my contacts change its photo since yesterday, other than that the app always uses the contacts photo regardless of if the setting is on or off. Photos do not appear on desktop in Linux, only on the androind phone, running android 15

**Comment by atiabbz** [comment]
Still an issue as of iOS 26.5...
Definitely should not be marked as closed.
