### ISSUE TITLE
6.25: version hit the App Store, but there is no prod tag in the repo, nor release on GitHub

### ISSUE THREAD

**Issue by r-mckay** [signalapp/Signal-iOS#5602]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As a developer and a user, I can see the 6.25 version available on the App Store, but I don't find the production tag in the repository, or the GitHub release entry. It is useful for traceability, transparency and communication. 

Please note: I am absolutely no expert in Signal's release cycle. The tag and its associated GtiHub release could come soon as part of the process. If that is the case, sorry for the noise.

Thank you very much for the awesome work!

### Steps to reproduce
None.

### Screenshots
None.

### Device info
None.

### Link to debug log
None.

**Comment by Miguel-Signal** [comment]
@r-mckay Thanks for bringing this to our attention!

https://github.com/signalapp/Signal-iOS/releases/tag/6.25.0.13

**Comment by r-mckay** [comment]
Thank you very much @Miguel-Signal , you rock.
