### ISSUE TITLE
Call is not ringing on actively used receiver phone

### ISSUE THREAD

**Issue by kaktusztea** [signalapp/Signal-iOS#5603]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Alice called Bob while Bob's phone was unlocked, active and used (browsing the web).
The call didn't ring on Bob's phone AND it is not appeared in call logs at all and neither in the conversation log.

Altough later when Bob fired up his laptop, the unanswered call log was in the conversation log.

### Device info - receiver
**Device**: iPhone 13 mini
**iOS version**: 16.4.1 (a)
**Signal version:** 6.25.0.13

### Device info - caller
**Device**: iPhone 8
**iOS version**: 16.?
**Signal version:** 6.24.0

### Link to debug log

**Receiver iOS (Bob)**
https://debuglogs.org/ios/6.25.0/d994cba5b76c053c086f233afff225300b28e68e352784f47b99acc8e73f77c4.zip

**Receiver Desktop (Bob)**
(it was offline at the moment of the incoming call)
https://debuglogs.org/desktop/6.19.0/ac8561851beecccf08bdb7a21535f5abd388a0e4e62f737bc2bf887cda46b095.gz

**Caller iOS (Alice)**
https://debuglogs.org/ios/6.24.0/a57cffca45afaa39c35532b9d37898eeb8a2a29abd8092b29a48213e6c0230e1.zip

**Comment by Miguel-Signal** [comment]
Hi @kaktusztea 

Could Alice and Bob both update the Signal app on all of your devices, then re-register for push notifications to see if this helps resolves the issue?

Go to Signal Settings  > Notifications > Re-register Push Notifications > OK.

If it's still an issue, please write in to support@signal.org with new debug log links for Alice's phone, and Bobs desktop and phone. Thank you!

**Comment by kaktusztea** [comment]
Bob already did the "re-register" **after** this issue.
Yesterday Bob received a call successfully from Alice with the same circumstances.
I'll close this, will reopen if comes back.
