### ISSUE TITLE
In App camers mirrors the original picture

### ISSUE THREAD

**Issue by namanmish** [signalapp/Signal-iOS#5605]
I have searched open and closed issues for duplicates
 I am submitting a bug report for existing functionality that does not work as intended
 This isn't a feature request or a discussion topic
 
### Bug description
In App Camera produces a mirror image of Pictures

### Steps to reproduce
- Open Signal App(on an ios device)
- In any chats or groups, try to capture a picture

**Actual result:** The picture that gets captured is a mirror image of what you are previewed

**Expected result:** Picture should should be more or less similar to what is previewed

Device info - receiver
Device: iPhone 12 mini
iOS version: 16.4.1 (a)
Signal version: 6.26

**Comment by Miguel-Signal** [comment]
Hi @namanmish 

This is by design, but we appreciate you taking the time to give us feedback and suggestions.

We would encourage you to provide feedback on the community forum also, which can be found here: https://community.signalusers.org/
