### ISSUE TITLE
Signal could get stuck and needs to be killed when taking a photo inside the app

### ISSUE THREAD

**Issue by cyberdynesoftware** [signalapp/Signal-iOS#5608]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Tested on iPad, not on iPhone.
When taking a photo inside the app, it could enter a state which it cannot leave. The app needs to be killed to continue.

### Steps to reproduce
- Take a photo inside the app with the photo button next to the message input area.
- Tap the pencil button in the lower left corner
- One may draw stuff on the photo here. In the lower left corner there is now an X button to leave and discard; in the lower right corner there is an r button to confirm and leave.
- Tap the Aa button in the lower center. Now one may enter text onto the photo.
- Close the keyboard with the keyboard button in the lower right.
- The app is stuck now. One may continue to draw stuff onto the image, but there is now way to leave this stage. The lower button bar is gone. The only thing left to do is to kill the app, which also forfeits the photo taken.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The app is stuck (not dead), but it needs to be killed because there is no way to send the photo or continue using the app.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

After closing the keyboard the lower button bar should be recreated to be able to leave this stage and send the photo.

### Device info

**Device**: iPad 8

**iOS version**: 16.5

**Signal version:** 6.25.0.13

**Comment by Miguel-Signal** [comment]
Hi @cyberdynesoftware, 

Could you write in to https://support.signal.org/ with your debug logs so we can look into this further?

To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, and copy the link.

**Comment by cyberdynesoftware** [comment]
There you go:

https://debuglogs.org/ios/6.27.0/7bcc5388d5077783e22b73f885620fa15d0ab9af6d9908c7a835b647ef883424.zip

I doubt that the log will show anything useful since the app did not crash. Did you reproduce the behaviour I've described?

What exactly is it you want me to do on  https://support.signal.org/ ?

**Comment by Miguel-Signal** [comment]
@cyberdynesoftware can you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue? Then, if the issue is still happening, could you send in new logs from this new version to support@signal.org?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link, then open this email, long-press and choose paste to paste the link.

**Comment by cyberdynesoftware** [comment]
Signal version is now 6.30.0.8. No change, the issue persists.

Have you tried to reproduce the problem with the steps provided above?

You realize that I had to kill the app before I could send the debug log?

Anyway, I've send the debug log to support@signal.org without any further context.

**Comment by cyberdynesoftware** [comment]
I can confirm that this issue has been resolved. The lower button bar is now properly recreated when closing the keyboard.

So why is this issue still open? No comment, no nothing? I'm beginning to suspect that the problem wasn't fixed because of my problem report. Thus, github issues don't seem to be the place to report bugs. Should I in the future rather send emails to support@signal.org?

**Comment by Miguel-Signal** [comment]
Hi @cyberdynesoftware,

Thanks for letting us know the issue has resolved for you. Please feel free to reply here or write into [support@signal.org](mailto:support@signal.org) if the issue reappears.
