### ISSUE TITLE
Invalid Format when verifying phone number on fresh install

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-iOS#5609]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening Signal for the first time after a fresh install it asks for the phone number to send the verification code. 

On the input field, there is the country selection (+xy) and then space for the actual number. I (wrongly) entered ith with the 0-prefix (for inland calls). Instead of +41 79 xxx xx xx I have entered +41 079 xxx xx xx. An error occured that the format is invalid, but then the 'verifying spinner didn't stop spinning - it shouldn't have started in the first place. There is no way to go back expect forcing the app to close and entering again.

The funny thing is, when setting up the iPhone some minutes ago, I was requried to use the +41 079 xxx xx xx-Scheme.

### Steps to reproduce
- Fresh install of signal
- Use phone number in +41 079 xxx xx xx format
- Click Next and 'Yes'

**Actual result:** Endless spinner. No Code gets sent.

**Expected result:** Multiple options:
- Don't even ask the question whether the phone number is correct, when you know that the format is invalid
- Accept the +41 079 xxx xx xx format as well
- At least allow me to cancel the verification process by going back. I shouldn't have to force-close the application.

### Screenshots

![grafik](https://github.com/signalapp/Signal-iOS/assets/62468040/b4f8591b-d8bf-48b8-b438-746051c5623a)

### Device info

**Device**: iPhone 13

**iOS version**: 16.2

**Signal version:** 6.27.0.9

### Link to debug log

https://debuglogs.org/ios/6.27.0/6a0e2e683e6126fe91eb20539fc11d5fee67f3dd6f52043bf3c711b5cb2c19ff.zip

**Comment by Miguel-Signal** [comment]
Hi @MorgeMoensch, thanks for providing your debug logs. 

We are aware of the problem and we are currently looking for a solution. Although our engineers are working on a fix, unfortunately I can't give a specific schedule for resolution. You might see a fix in the release notes for future versions of Signal.

Thanks again for your help in reporting this.
