### ISSUE TITLE
newest Update broke Notifications and worsend Sync

### ISSUE THREAD

**Issue by T3ll1nG** [signalapp/Signal-iOS#5610]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
The newest Update broke and worsened notifications. I needed to restart every device other then my Mac to receive notifications and badge on the App logo at all. It would add the notification and the identification if I open the app. Now it works again on iOS, but it is now way slower then before. The notifications now arrive first on my Mac, then my iPhone and then on my iPad. There is a noticeable delay in notification arrival between the devices. My AppleWatch does not receive notifications from Signal anymore.

### Steps to reproduce
- install the latest update
- restart your devices

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Very noticeable delay between devices on notifications and no functionality on AppleWatch. Also notifications and the badge seems rather buggy on Signal for iOS in general.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Slight delay between devices, reliable badge on the logo, notifications, AppleWatch support like before the latest update.

### Device info

**Device**:  iPhone 14 Pro, Macbook Pro M1 Pro (2021), iPad Air 5, AppleWatch Ultra

**iOS version**:  16.5
**iPadOS version**:  16.5
**watchOs version**:  9.5.1
**macOS version**:  13.4

**Signal version:** 6.27
**Signal Desktop version:** 6.20.2

**Comment by Miguel-Signal** [comment]
Hi @T3ll1nG,

Could you write in to support@signal.org with your debug logs so we can troubleshoot this further? 

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, and copy the link. 

To share a debug log from within Signal Desktop, go to the menu, click on View, Debug Log, Submit, and copy the link.

**Comment by T3ll1nG** [comment]
> Hi @T3ll1nG,
> 
> Could you write in to [support@signal.org](mailto:support@signal.org) with your debug logs so we can troubleshoot this further?
> 
> To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, and copy the link.
> 
> To share a debug log from within Signal Desktop, go to the menu, click on View, Debug Log, Submit, and copy the link.

Hi @Miguel-Signal,

the logs for iPhone, iPad and macOS have been sent to [support@signal.org](mailto:support@signal.org) today. The issue number is mentioned in the email.

**Comment by T3ll1nG** [comment]
Hi @Miguel-Signal ,

so after restarting the devices and ~30 hours of the app in a semi working state it evened out. 
Watch notifications work again, the delay between devices is within normal boundaries and the badges on the icon also work now. 

Definitely weird that the update went so horrible on my devices, but with the problem _solved_, I am no longer able to post logs and answer questions regarding this issue. The logs were submitted as asked.

**Comment by jekbradbury** [comment]
Also experienced something like this, with notification issues extending even to the point of not ringing/notifying on incoming Signal calls if I'm in another app. Seeing if restarting the phone helps.

**Comment by jekbradbury** [comment]
I'm on app version 16.24.0.9 on iOS 16.5, neither of which is all that new, but it seems to have started 2-3 days ago.

**Comment by Miguel-Signal** [comment]
@jekbradbury can you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue? Then, if the issue is still happening, could you send in new logs from this new version to support@signal.org?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link, then open this email, long-press and choose paste to paste the link.
