### ISSUE TITLE
New Message Popup too thin on iPadOS

### ISSUE THREAD

**Issue by thgoebel** [signalapp/Signal-iOS#5615]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

On Signal on iPadOS the content of the "New Message" popup is too thin and not readable.

### Steps to reproduce

- Click the pencil icon
- The "New Message" popup opens

**Actual result:**

The list of contacts is impossibly thin. In portrait it is just readable, in landscape you cannot read anything.

**Expected result:** 

The list should be normal. (It used to -- this bug is a regression.)

### Screenshots

Landscape:
![signal-2023-06-17-173830_002](https://github.com/signalapp/Signal-iOS/assets/33295590/a9064196-3d39-43f2-ad75-519745b2d33e)

Portrait:
![signal-2023-06-17-173830_003](https://github.com/signalapp/Signal-iOS/assets/33295590/2926e3ff-d9da-444d-8760-99ccd821b97e)

### Device info

**Device**: iPad Pro 2020 11 inch

**iPadOS version**: 16.5

**Signal version:** 6.28.0.11

### Link to debug log

Should not be necessary, but I can provide it if you absolutely need it.

**Comment by jonasfeld** [comment]
+1, I experience the same thing on my 3rd Gen. iPad Air. The "New Message" screen is effectively unusable as is.

**Comment by Miguel-Signal** [comment]
Thanks for reporting this. 

We are aware of the problem and we are currently looking for a solution. Although our engineers are working on a fix, unfortunately I can't give a specific schedule for resolution. You might see a fix in the release notes for future versions of Signal.

**Comment by thgoebel** [comment]
This seems to be fixed in 6.33.0.9 (or maybe earlier and I missed it).

**Comment by thgoebel** [comment]
Looks like this broke it: c58de3bb5e58e6e6d3949716f6efa180bbdde3db
And this fixed it: c839720999fc943715265cf33eb019d396a3352d
