### ISSUE TITLE
Signal appears as "SignalSAE" in sharing menu

### ISSUE THREAD

**Issue by aashh** [signalapp/Signal-iOS#5618]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal appears as "SignalSAE" in iOS share menu

### Steps to reproduce
- Select "Share" icon in an iOS app

**Actual result:** 
Signal icon is captioned "SignalSAE"

**Expected result:** 
I would expect the Signal icon to be captioned "Signal"

### Screenshots
![signalsae](https://github.com/signalapp/Signal-iOS/assets/6617828/c815cb7a-6dd5-404b-a916-ffdbb492a912)

### Device info

**Device**: iPhone SE (2016)

**iOS version**: 15.7.7

**Signal version:** latest

**Comment by aashh** [comment]
Probably related to [this commit](https://github.com/signalapp/Signal-iOS/commit/ad4be2d1feded6c674350c91a2ea7c9878bed919) by @charlesmchen-signal

**Comment by arkumari2000** [comment]
I would like to fix this issue @charlesmchen-signal if @aashh is not working on this, please let me know if this is a valid issue and I can work on this or not.
Thanks

**Comment by adityagi02** [comment]
> @arkumari2000 Can you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue? 

Yeah, with version 6.35, this error is resolved. 
**Device**: iPhone 13, iOS 16.6


![IMG_0356](https://github.com/signalapp/Signal-iOS/assets/77538183/a1ada6c8-6a43-4de8-a71f-b67934dff8b0)

**Comment by ddxor** [comment]
@aashh can you close this issue?

**Comment by lowdrag** [comment]
> > [@arkumari2000](https://github.com/arkumari2000) Can you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue?
> 
> Yeah, with version 6.35, this error is resolved. **Device**: iPhone 13, iOS 16.6
> 
> ![IMG_0356](https://github.com/signalapp/Signal-iOS/assets/77538183/a1ada6c8-6a43-4de8-a71f-b67934dff8b0)

this is not resolved in 8.10 on iPhone 18.7.2
