### ISSUE TITLE
iOS app keeps crashing with Japanese input

### ISSUE THREAD

**Issue by u00101010** [signalapp/Signal-iOS#5622]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Recently the app started crashing when using the default Apple Japanese keyboard. If I type and send a message, then attempt to start typing another message, the app crashes the second I press any key on my keyboard, preventing me form typing in a second message. I tested and it doesn't happen with the English keyboard.

### Steps to reproduce
- Set the iOS keyboard to Japanese
- Type any message and send it to someone
- Immediately attempt to press any key on the keyboard

**Actual result:** The app crashes

**Expected result:** I should be able to type in a message as normal.

### Device info

**Device**: iPhone 7

**iOS version**: 15.7.7 (also happened in 15.7.6)

**Signal version:** 6.31

### Link to debug log
https://debuglogs.org/ios/6.31.0/05527f291a01bb89ef24bf8ce9d1a5f3f78238012e0845da79c28c70b9b0cfd0.zip

**Comment by pete-signal** [comment]
Thanks for reporting this! We've [fixed](https://github.com/signalapp/Signal-iOS/commit/5c35e73468e5b118dc93540e99230248eb1a6ac1) the issue and released a [6.31.1 ](https://github.com/signalapp/Signal-iOS/releases/tag/6.31.1.0) hotfix with the change.
