### ISSUE TITLE
The contents of a deleted message are displayed in replies despite its deletion.

### ISSUE THREAD

**Issue by M3DZIK** [signalapp/Signal-iOS#5623]
Detailed description in issue on android: https://github.com/signalapp/Signal-Android/issues/13046

### Screenshots

https://github.com/signalapp/Signal-iOS/assets/87065584/30c3bac6-228d-47d9-8148-2199ad864b9e

**Comment by JhonnyBillM** [comment]
Just copy/pasting from Android's issue closing comment: 
> ... we consider quoted replies to be the equivalent of copy-pasting a message, so this is working as intended.

https://github.com/signalapp/Signal-Android/issues/13046#issuecomment-1629605566
