### ISSUE TITLE
Send button has the wrong color when using different accent color

### ISSUE THREAD

**Issue by br4yd** [signalapp/Signal-iOS#5629]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you change the accent color in the app settings this accent color gets applied to message bubbles, etc. but not for the send button, which stays blue.

### Steps to reproduce
- Change accent color in Signal's settings for e.g. to green
- Type something in the text box
- See that the send button is still blue and doesn't follow the actual design setting as message bubbles do

**Actual result:** Send button stays blue

**Expected result:** Send button should follow theme settings as everything else does. So it should be green in the above mentioned example.

### Device info

**Device**: iPhone 13 Pro

**iOS version**: 17.0 (Developer Beta) (21A5277j)

**Signal version:** 6.32.0.10

**Comment by Miguel-Signal** [comment]
Hi @br4yd,

This isn't currently supported on iOS, but we appreciate you taking the time to give us feedback and suggestions.

We would encourage you to provide feature requests on the community forum also, which can be found here: https://community.signalusers.org/

**Comment by br4yd** [comment]
> Hi @br4yd,
> 
> 
> 
> This isn't currently supported on iOS, but we appreciate you taking the time to give us feedback and suggestions.
> 
> 
> 
> We would encourage you to provide feature requests on the community forum also, which can be found here: https://community.signalusers.org/

Oh okay, so this actually isn’t a bug but it’s just not supported by Apple? Thanks for clarification. I just thought it was forgotten in the UI design.
