### ISSUE TITLE
Push notifications issues

### ISSUE THREAD

**Issue by daapp9** [signalapp/Signal-iOS#5631]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Not receiving push notification or receiving lately.

### Steps to reproduce
- Nothing

**Actual result:** Some messages are never received, or are very delayed. Sometimes just having the icon app with the red number without having the notify sound, sometimes its even needed to open the app to see new messages.

**Expected result:** Be notified instantly when receiving a messages, like any other messaging app do.

### Device info

**Device**: iPhone 14 Pro

**iOS version**: 16.5.1 (latest now)

**Signal version:** latest on App Store

### Personal Note

First I'd thank all people that contributed to make this great open source application.
About the issue, I think it's more a server issue which is known by signal users, it's even there on Android and since we can't create issue on server repo I do there. I'm having this issue from years now, all the people I suggested to install on signal **are annoyed and stop to use the application** only for that issue, they complains to never receive notification or are notified very lately, which is true, I myself expect this and I force myself to open the app sometimes to see if no messages was missed, some contacts even send me a sms to warn me about signal messages. I tried the re-registration of push notifications in app, same. I'd prefer to see much effort for the team about solving that instead of bringing stories which is not really used, it's hard to convince people to switch to signal due to this...

**Comment by jimio-signal** [comment]
hi, @daapp9!

think you could also [submit a debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) to support@signal.org so we can look more closely into what you're experiencing? we had a lot of improvements to notification reliability ship earlier in the year (https://github.com/signalapp/Signal-iOS/issues/5148#issuecomment-1454873738), and I'd love to be able to understand more of the issue that you're seeing. sounds like you've tried some of the suggested [troubleshooting](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#ios_notifications_troubleshooting) steps already. thanks!

**Comment by ddddavidmartin** [comment]
Hmmm, my partner was having similar issues in the past days. Re-registering push notifications seems to have fixed it. She didn't receive any notifications, or super late. In hindsight she likely only got them after actually opening the app again to check whether she maybe missed messages.

We hadn't changed anything and use Signal everyday. This is on an iPhone 14 Pro Max at iOS version 16.5.1. The only thing she noticed is that the Signal UI changed.

Makes me wonder whether this happened because of a recent Signal update.
