### ISSUE TITLE
UI-Bug: Elements overlay

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-iOS#5632]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I experienced various UI-Elements that were overlayed. After I closed (not just returning to home-screen) the app the first time, the bug on the stories overview disappeared. When generating the Debuglogs, the second bug appeared. This one is resolved after closing the app a second time.

### Steps to reproduce
- Cannot reproduce reliably

**Actual result:** UI Elements are not properly aligned

**Expected result:** UI elements are properly aligned

### Screenshots
![grafik](https://github.com/signalapp/Signal-iOS/assets/62468040/6cb02e11-0dfa-4696-9e99-c76f3a5cec23)

![grafik](https://github.com/signalapp/Signal-iOS/assets/62468040/ff21b0d2-2b44-4e3e-aa47-3313657dc85f)

### Device info

**Device**: iPhone 13

**iOS version**: 16.5.1

**Signal version:** 6.32.0.10

### Link to debug log

https://debuglogs.org/ios/6.32.0/c848fb0d58c07f84103a3eb34b08eb82e4135b18fd0347c59ef3e843723ee0ba.zip

**Comment by Miguel-Signal** [comment]
Hi @MorgeMoensch,

Can you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) (v6.35) and see if this resolves the issue? Then, if the issue is still happening, could you send in new logs from this new version?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link.

**Comment by MorgeMoensch** [comment]
Hi @Miguel-Signal 

I can kinda reproduce the one with the logo reliably.

- Tap the own profile picture (so the select Chats and Dropdown menu appears)
- Pull down from the top left (open iPhone notification center)
- close notification center
- tap ok the own profile picture again

This way, the profile picture is not a still duplicate as in my original report. Rather, tje duplicate flyes to the top left and vanishes.

Here's the debug log: https://debuglogs.org/ios/6.35.0/9d22279325522f689aeb3029fc11f25cebbe5f2d6ab0bf72761e5fe6e0bfac3b.zip

**Comment by pjolt** [comment]
> * Tap the own profile picture (so the select Chats and Dropdown menu appears)
> * Pull down from the top left (open iPhone notification center)
> * close notification center
> * tap on the own profile picture again
> 
> This way, the profile picture is not a still duplicate as in my original report. Rather, tje duplicate flyes to the top left and vanishes.
>

I can confirm this behavior. 

https://debuglogs.org/ios/6.35.0/dfa551f00943782b877c942f0bcc7c80a783eec74485e216a5f7e2504b2aa9d3.zip

**Comment by MorgeMoensch** [comment]
I just experienced the original glitch on the Stories Tab again: https://debuglogs.org/ios/6.35.0/bd63502430587e6d2674a04ba60b53720564c42875dcbc9c46450bfed19698ba.zip

Switching to Chats and back did not resolve it. But after entering a Chat, tapping back and switching to the Stories Tab again fixed it.
