### ISSUE TITLE
Clipboard copy/cut always copies/cuts complete message

### ISSUE THREAD

**Issue by Hiltiprant** [signalapp/Signal-iOS#5637]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When editing text in the text field in any chat, you can copy/cut/paste text. But when you only want to copy/cut parts of your message, this is not possible. Signal will always copy/cut the complete message, even if you selected only one word for example.

### Steps to reproduce
- Open Signal, open any chat (note to self also works)
- Type something into the text field (e.g. "This is a stupid test message")
- Select parts of the text (e.g. "stupid")
- Select Copy or Cut (*Kopieren* or *Ausschneiden* in German)
- Paste (*Einfügen*) the text anywhere; it does not matter if it is Signal or any other app

**Actual result:**
The complete message (e.g. "This is a stupid test message") is pasted. There is a difference between copying and cutting, though. When copying, the complete message is copied and pasted. But when cutting, only the selected word is removed from the original message (leaves you with "This is a test message"), but apparently the complete message is copied and put into the clipboard.

**Expected result:**
Only the selected portion of the message (e.g. "stupid") should be copied and pasted on the other end. Not always the complete message.

### Screenshots
Type text, select one word and select copy:
![1_copy](https://github.com/signalapp/Signal-iOS/assets/24189977/9fdf25af-d8d5-4461-bbe7-23f34cf00614)

Add a new line and place cursor:
![2_copy-paste](https://github.com/signalapp/Signal-iOS/assets/24189977/3778927b-4957-4fc3-87a7-140430fc5190)

Select paste: result. Then select one word again and select cut:
![3_cut](https://github.com/signalapp/Signal-iOS/assets/24189977/2919b0d4-de70-4d85-a093-2b9746827aa0)

Add a new line again and place cursor:
![4_cut-paste](https://github.com/signalapp/Signal-iOS/assets/24189977/067b42aa-4b47-4846-8007-6bbaeae4fa5b)

Select paste: end result:
![5_end-result](https://github.com/signalapp/Signal-iOS/assets/24189977/d7bf93dc-3e41-4da2-8b75-160738ee27cd)

### Device info

**Device**: iPhone 13

**iOS version**: 16.6

**Signal version:** 6.34.0.10

### Link to debug log
https://debuglogs.org/ios/6.34.0/fb3584f0f50165ef198dd04b97b79ea6e33db3e35dcf0a48b1ac0021c104f34b.zip

**Comment by Miguel-Signal** [comment]
Hi @Hiltiprant,

Could you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) (v6.35) and see if this resolves the issue?

**Comment by pete-signal** [comment]
This should be [fixed](7abc656f45883845efdfda5181997292084da159) in the upcoming 6.36 relase

**Comment by Hiltiprant** [comment]
Hi guys, thanks for your replies.
I just tested it on v6.35.0.9 and I don't see any issues any more. Looks like I was a little too early, the update reached me shortly after posting the issue, sorry for that.
The issue can be closed from my side.
