### ISSUE TITLE
Crash on send message on iOS if the mention menu of usernames is active.

### ISSUE THREAD

**Issue by ChrisJRock** [signalapp/Signal-iOS#5642]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS app crashes when a message is sent while the mention menu is displayed.

### Steps to reproduce
- Open signal on an iOS device.
- Start a new message.
- Type "@". Notice the list of usernames that displays above your message.
- Press send.

**Actual result:** Giant crash. Upon returning to the chat, it can be seen that the message will have been successfully sent.

**Expected result:** The message is sent without crashing Signal.

### Device info

**Device**: iPhone 13 Pro
(Friends reproed it on other iOS device, but could not repro it on desktop or android.)

**iOS version**: 16.5.1

**Signal version:** 6.34.0.10

### Link to debug log

<!--  If this is a crashing bug, after filing this issue, email a copy of your latest crash report to support@whispersystems.org

To get a crash log:

1. Go to the iOS Settings app.
2. Go to Privacy.
3. Go to Analytics or Diagnostics & Usage.
4. Select Analytics Data or Diagnostics & Usage Data.
5. Locate the .ips crash log for Signal.
    The logs will be named in the format: Signal(DateTime).ips
6. Select the desired Signal log.
7.a iOS 11 users, tap the Share icon in the top right corner and jump to step 10.
7.b iOS 9&10 users, long press to see the option to highlight text and select the entire text of the log. It will end in EOF.
8. Once the text is selected, tap Copy.
9. Paste the copied text into an email.
10. Send the email to support@signal.org with a subject like:
  * "iOS Crash Log: (your github issue)"
  * Example subject: iOS Crash Log: Crash on launch #111
  * Example subject: iOS Crash Log: Crash when sending video #

Emailed crash log.

**Comment by Miguel-Signal** [comment]
Hi @ChrisJRock,

Could you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue? Then, if the issue is still happening, could you send in debug logs from this new version to support@signal.org?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link.

**Comment by ChrisJRock** [comment]
Looks good!
