### ISSUE TITLE
Hebrew text is left-aligned while typing

### ISSUE THREAD

**Issue by eyldlv** [signalapp/Signal-iOS#5643]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When writing a message in Hebrew, text is left-aligned instead of right-aligned.

### Steps to reproduce
- Enter a conversation
- Switch to Hebrew
- Type some text

**Actual result:** While typing, Hebrew text is left-aligned.

**Expected result:** When typing Hebrew text, it should be right-aligned.

### Screenshots
![afa12c0d8b2428d3](https://github.com/signalapp/Signal-iOS/assets/98599102/940691a6-6ace-4e66-8b23-8286480fd185)

### Device info
**Device**: iPhone 13

**iOS version**: 16.6

**Signal version:** 6.35.0.9

### Link to debug log
https://debuglogs.org/ios/6.35.0/8d44a3e0853ec109f1ff274b9a21bb761464a9125205ec973faf78a3ff51c412.zip

**Comment by sashaweiss-signal** [comment]
Hi! We believe this has been fixed. Thanks for reporting it!
