### ISSUE TITLE
Contact pictures doesn't show up

### ISSUE THREAD

**Issue by Kingdom-Of-Heaven** [signalapp/Signal-iOS#5644]
Hi Signal team,
Contact pictures doesn;t show up on chat. My signal version 6.35.0.9 Ipad 12.9 " Gen 3. Any feedback?

**Comment by gkarthikreddi** [comment]
You should try disabling "Use address book photos" option in the settings.

**Comment by Kingdom-Of-Heaven** [comment]
> You should try disabling "Use address book photos" option in the settings.

that didn't help

**Comment by SumanthReddi** [comment]
Yes , it doesnt work for me either using iphone 13.

**Comment by Miguel-Signal** [comment]
Hi @Kingdom-Of-Heaven 

Could you please write in to support@signal.org with a link to your iPad debug logs so we can look into this further?

To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.

**Comment by Miguel-Signal** [comment]
This is expected behavior right now. Our developers will be looking into adding contact photos back to iPad at a later date.
