### ISSUE TITLE
Stickers shown above message field even after uninstalling

### ISSUE THREAD

**Issue by Shnub** [signalapp/Signal-iOS#5648]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description
I do not use stickers. I previously uninstalled all sticker packs so I would not see any stickers offered when typing emojis. This worked as intended until a few days ago. But after reinstalling Signal due to a failed iOS update, default sticker packs were installed again and showed up automatically when typing single emojis. I uninstalled all sticker packs again (and restarted the app to be sure), but stickers are still offered for typed emojis.

### Steps to reproduce
- Uninstall all sticker packs.
- Type a single emoji when composing a message (e.g. "🤔").

**Actual result:**
- Default stickers are offered above the message field. (See screenshot for above example.)

**Expected result:**
- No stickers should be offered above the message field.

### Screenshots
![IMG_589C864194EF-1](https://github.com/signalapp/Signal-iOS/assets/29605254/1f5d9294-b2bd-47d1-b6a7-1c64ff08b086)

![IMG_26667C6E89BA-1](https://github.com/signalapp/Signal-iOS/assets/29605254/76885864-3ce0-474a-867c-5a02415bb474)

### Device info
**Device**: iPhone SE 1st gen

**iOS version**: 15.7.8

**Signal version:** 6.36.0.10

**Comment by david-auk** [comment]
I am still experiencing this issue...

Signal Version 7.62.1 (823)

iOS version 18.5 (22F76)

### Screenshots

![Image](https://github.com/user-attachments/assets/ef54a551-e8db-49a2-9485-a829157f181e)
![Image](https://github.com/user-attachments/assets/75a8bfae-c1fd-4874-8957-ffbeeaa2f2c0)
