### ISSUE TITLE
Link in message is not clickable

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-iOS#5649]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using certain emojis, the Link cannot be clicked in the iOS-Client.

I tried sending from Android, sending from Desktop and sending from Desktop and then redirecting via Android Client. None of them were clickable in Signal iOS. Note how the ▶-Emoji (selected with Windows + . ) turns out as a black triangle, while the one selected on Android (the last message) turns out different.

### Steps to reproduce
- Send a message that contains the ▶ emoji and a Link
- try to tap the link, it is not possible

**Actual result:** Link is not clickable when the ▶ emoji is used

**Expected result:** A link is always clickable, no matter the other text beforehand

### Screenshots

Those are the messages in the same chat, viewed on different clients:

Desktop (Windows)
![grafik](https://github.com/signalapp/Signal-iOS/assets/62468040/01cab2fb-95a6-4232-9e0d-bf4c9da7fee9)

Android
![grafik](https://github.com/signalapp/Signal-iOS/assets/62468040/10088e1c-6cee-4e49-88f7-b43116c0fdb7)

iOS
![grafik](https://github.com/signalapp/Signal-iOS/assets/62468040/576741f9-c6b9-4ede-896a-dfa8c02bbeda)

### Device info

**Device**: iPhone 13

**iOS version**: 16.6

**Signal version:** 6.36.0.10

**Comment by harry-signal** [comment]
A fix for this will go out in the next app update, thanks for the bug report!
