### ISSUE TITLE
Video can't be played from 9gag downloads

### ISSUE THREAD

**Issue by jonasW3F** [signalapp/Signal-iOS#5651]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Many videos that are downloaded from 9gag cannot be viewed by friends that own an iPhone. No issue with those that own an Android. It's mostly .mp4 videos. One (funny) example is: https://github.com/signalapp/Signal-iOS/assets/67730419/1ad133e9-3f66-49e7-8a08-c3d6ef12b990

### Steps to reproduce
**Actual result:** Sending the video will have those affected getting a black frame with the message that the video can't be played.

**Expected result:** The file is clearly intact as only iOS users are affected.

### Screenshots
![signal-2023-08-23-112004_002](https://github.com/signalapp/Signal-iOS/assets/67730419/d47abe17-8bc5-4c24-a612-af98f9521067)

### Device info
**Device**: iPhone - different versions
**Signal version:** newest

**Comment by Miguel-Signal** [comment]
Hi @jonasW3F,

Can you tell me if you are still able to reproduce this issue if all users have updated to the latest available versions of Signal?

**Comment by jonasW3F** [comment]
The issue with .mp4 seems to be resolved, thanks for that. 

While testing we found out that, again only on iOS, .webm videos are not rendering in the app and are sent as attachment. On Android, you can simply watch the video as per usual.

**Comment by m93a** [comment]
I can confirm that WebM playback doesn't work on iOS, while WebM files play just fine on Android. This was first brought up in the issue #902, which has been closed by the _stale bot_ as inactive.

**Comment by adarsh1001** [comment]
+1. I sent a .webm video file from Android to an iOS user. It got sent as an attachment which the iOS user wasn't able to play.

![signal-2023-11-26-16-27-04-950_1.jpg](https://github.com/signalapp/Signal-iOS/assets/8820038/a9ad5495-de09-48fd-8b3e-39f59beb6d69)

Both of us are using the latest versions of Signal.
