### ISSUE TITLE
In app camera bug with flash and recording video

### ISSUE THREAD

**Issue by FocuzJS** [signalapp/Signal-iOS#5652]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
First in app video capture with flash forced on is not recorded with the flash on

### Steps to reproduce
- open the in app camera used to send media to your contacts
- enable flash in the forced on mode
- hold down the capture circle button UI

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The flash briefly turns on at the start of the recording but then turns back off. After discarding the failed attempt, the flash will function as expected on subsequent attempts. After dismissing the in app camera UI, the next time you open it the bug will manifest again. (without app restart, simply by exiting and re-entering the camera view)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The flash should remain on while the video is recorded on the first attempt.

### Screenshots

N/A

### Device info

**Device**: 14 Pro Max

**iOS version**: 16.6

**Signal version:** 6.37.0.8

### Link to debug log
Can provide if bug is not immediately reproducible.

**Comment by harry-signal** [comment]
Thanks for the report! We are tracking this internally.
