### ISSUE TITLE
Editing a contact in Signal app results in the contact being opened in edit view in iOS Contacts

### ISSUE THREAD

**Issue by ikeaRobes** [signalapp/Signal-iOS#5654]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When editing a contact in Signal app, after cancelling out or completing the edit, when you open the contacts app in iOS it auto opens that contact in the editable state.

### Steps to reproduce
- open signal app
- on Chats tab > click into a chat
- click the contact's name at the top
- click Edit in the top right
- click either Cancel or Done
- background the signal app
- open the native iOS Phone app > go to Contacts tab ( you may need to swipe the Phone app up and kill it via task manager then open it again to get it to reliably reproduce )

**Actual result:**
see the "unsaved draft" launch in an editable state for that contact you edited in Signal

**Expected result:**
land at expected list of iOS Contacts

### Device info
**Device**: iPhone 13 Mini

**iOS version**: 16.6

**Signal version:** 6.39.0.11

**Comment by DGrothe-PhD** [comment]
Can absolutely confirm this (iOS 16.6.1)
However, at least from my point of view, it is not a real bug. When I tap on Edit in the top right corner of a signal contact entry I am aware of using the contacts app.

OTOH, when I first added a new contact in contacts app like two years ago I usually got a notice "John Doe is on Signal" or something.
