### ISSUE TITLE
"Turn on Contacts?" pop up does not ask for "Apple contacts permission", it assumes contacts permission are already there 

### ISSUE THREAD

**Issue by hemanthac4github** [signalapp/Signal-iOS#5655]
----------------------------------------

### Bug description
Whenever i do "Reset location and privacy" in iphone, (Setting>General>transfer or reset iphone), this resets all the permission given to all apps. After doing this when i open signal app, there is a pop up saying "Turn on Contacts?"- which redirects to settings to Signal app specific settings where all the permissions are listed. But when the permissions are reset, contacts specific permission is not listed in this signal app specific settings, they need to be re-asked from the apple. Expected behavior is when there is popup of ""Turn on Contacts?"", it should check if the permission is there, if it is not there, ask apple specific contacts permission, obtain the permission of contacts, if it is there, redirect me to the signal app settings.
Currently, a work around for this problem is to click on write a new message, it asks for contacts permission through apple.

### Steps to reproduce
- Reset location and privacy in iphone
- open signal app and see there is pop up - "Turn on Contacts?"
- Asks to goto signal app specific settings

**Actual result:** redirects to signal app specific setting where i cant find a way to enable contacts

**Expected result:**  If contacts permission is not there, ask asking user for contacts permission via apple.

**iOS version**: all versions

**Signal version:** all versions

No screenshots or logs needed as it is easy to reproduce.
----------------------------------------

**Comment by sashaweiss-signal** [comment]
Hi! We're now tracking this internally. Thanks for reporting!

**Comment by hemanthac4github** [comment]
Thanks, let me know if you need help..

**Comment by JonathanLoewe** [comment]
I have the same issue without having reset my privacy settings. The only thing of note that happened before was an error to open signal due to low storage. But I have had low storage errors before without this problem. Today I noticed that signal lost the profile pictures it used from the iOS contacts.
