### ISSUE TITLE
Unable to exit device re-registration

### ISSUE THREAD

**Issue by dotfortun3-code** [signalapp/Signal-iOS#5656]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My iPad prompted me that my device needs to be re-registered. When I touched it, it loaded the registration page, but I no longer have access to the phone number, so I would like to exit the registration process to make a backup, however I am unable to do so. For additional context, I did not realize I did not have access to the old number as it was a Google Voice number that expired, so I had continued to having it send me an code. I **was** able to exit before I had it send me a verification code.

### Steps to reproduce
- get device that requires re-registration
- begin the process
- enter pin
- at verification code screen, touch "Resend code" 
- touch "Edit"
- touch the menu at the top right
- touch "Exit registration"

**Actual result:** Nothing happens

**Expected result:** The app should return to the main screen and allow access to chats.

### Device info

**Device**: iPad Pro 2018

**iOS version**: 16.4.1

**Signal version:** 6.39

### Link to debug log

https://debuglogs.org/ios/6.39.0/8f652f20ec2371236aafccf480b40a8260043a7cedae99c522c16f7e53ee5a85.zip

**Comment by sashaweiss-signal** [comment]
Hi! I'm now tracking this internally. I'll also take a look at why you became deregistered in the first place. Thanks for reporting!

**Comment by dotfortun3-code** [comment]
Hi there, just wondering if there is any hope of recovering the data from the device. Signal still accepts my pin before it pushes me to registration. I don't need messaging to work on the device, but I would like to recover my message history.
