### ISSUE TITLE
Scrolling through pics in a chat sometimes overlaps them

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#5657]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Sometimes when you try to scroll through the pics in a chat, the scroll to the next pic happens before the previous pic has been completely displayed from edge to edge. It's more like sifting through overlapping pics dropped on a desk, than scrolling from pic to pic on a film reel.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

I still can't seem to nail this down. Maybe the behavior is activated by some subtle nuance in the usual swiping gesture. It happens often enough that I encounter it roughly daily. If this is supposed to be a feature, then I can't imagine what purpose it would serve, and at least a Preferences setting to turn it off would be helpful.

This might be easier to reproduce if you're trying to zoom the current pic. When I try to zoom the corners of the current pic, it annoyingly starts sliding to the adjacent pic. While I wish I could disable that behavior somehow, it seems like that's the intended design. But the point is that this overlap issue might happen more readily under such conditions. Again, it's so random that I can't be more precise.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

You see some horizontal fraction of the current pic in the chat. Then suddenly the next pic (or previous one, depending on swipe direction) just overlaps it and scrolls over it.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Let me see the entire pic before you overwrite it with the next one.

### Device info

**Device**: Android 12

**Signal version:** Latest

**Comment by sashaweiss-signal** [comment]
Hi, and thanks for the report! You mentioned that the device is running Android 12 - if that's correct I suggest re-opening this issue in our Android repo, linked below.

https://github.com/signalapp/Signal-Android

**Comment by sailbird** [comment]
@sashaweiss-signal Sorry, my mistake. Unless this also happens on iOS (which it might), then feel free to close this issue. Here's the Android one:

https://github.com/signalapp/Signal-Android/issues/13163
