### ISSUE TITLE
Left groups still appear in search

### ISSUE THREAD

**Issue by BionicBison05** [signalapp/Signal-iOS#5659]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Groups that have been left and deleted still appear in search
### Steps to reproduce
- Join a group
- Leave the group
- Delete the group
- Search for the "deleted" group

**Actual result:**
Group appears in search despite apparent deletion
**Expected result:**
Group is properly deleted upon requested deletion, both for privacy and organization.
### Screenshots

https://github.com/signalapp/Signal-iOS/assets/93722725/9017f93d-575d-4934-b385-97ea9e2827bb

### Device info

**Device**: iPhone 12
**iOS version**: 16.6.0
**Signal version:** 6.39.0.11
### Link to debug log

https://debuglogs.org/ios/6.39.0/7aed2b6048fbf7251267ab87bd29aee272fe5ff9b6895d3f520f0eee95e2243c.zip

### Additional notes
Issue is likely the same as #4542, a 3-year-old bug that has been closed due to inactivity with not even as much as an official acknowledgement of the bug's existence despite multiple user comments confirming it.

**Comment by sashaweiss-signal** [comment]
Hi! I reproduced this, and the behavior I saw was that the messages from the group were in fact deleted, and I can't see the group in my chat list, but it is still appearing in search results.

Thanks for reporting! I'm now tracking it internally.
