### ISSUE TITLE
Duplicate messages in group

### ISSUE THREAD

**Issue by JohanDoe** [signalapp/Signal-iOS#566]
Alice creates a group with Bob titled 'test'. Two persons thus in group. 

Bob updates group title to 'test update'. 

Group title changes. Alice sees this. 
Alice sends a message. 
Bob now receives every message from Alice twice.

**Comment by corbett** [comment]
have been unable to reproduce this.

**Comment by JohanDoe** [comment]
Not sure how I can help reproducing it. Just tried it again. Alice on 2.0.11 on iPhone. Bob on 2.0.11 on iPad. After updating title, bug reappears. One of them gets every message twice.

**Comment by riyapenn** [comment]
Unfortunately, this has resurfaced.  Messages received twice from group creator, Alice. Total members in group: 3

- Alice "did not receive any alerts on this message. And the message looks like it only sent once on the screen from [Alice's] perspective." 
- "When someone else creates the group with the exact same participants, nobody's messages are duplicated."
- None of the members have linked devices.

Signal 2.6.8
Log's sent in immediately after experiencing issue

Alice's logs: https://gist.github.com/cc5676ec2d4e232b23fd93e437652c38 
Bob's logs: https://gist.github.com/14b25432d8f6e0cc77fd34ffd0f3398f

**Comment by michaelkirk-signal** [comment]
This has long since been addressed. If you experience something like this, please open a new issue with a fresh debug log.
