### ISSUE TITLE
payment recovery phrase unreadably truncated with accessibility large text

### ISSUE THREAD

**Issue by cariaso** [signalapp/Signal-iOS#5660]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

while setting up payments I'm shown my "recovery phrase"

one of my words is shown as "respo..." should that be response? respond?

I suspect this truncation is because my iphone has an accessibility feature turned on.
Settings  > Accessibility > Display & Text Size.
https://support.apple.com/guide/iphone/display-text-size-iph3e2e1fb0/16.0/ios/16.0

### Steps to reproduce
- on iphone Settings  > Accessibility > Display & Text Size . set it to 'Larger'
- update signal from app store to latest version via  https://apps.apple.com/us/app/signal-private-messenger/id874139669 
- settings -> payments
- follow steps
- when shown 24 word "recovery phrase" hope for a long one

**Actual result:** 
one of my words was shown as "respo..."

**Expected result:** 
The word wrapped or otherwise not truncated.

### Screenshots
No, sharing my recovery phase any more than I have seems unwise.

### Device info
**Device**: iPhone 12 Pro

**iOS version**: 16.6.1

**Signal version:** 6.40.0.12

### Related
https://github.com/signalapp/Signal-iOS/issues/4495 
https://github.com/signalapp/Signal-iOS/issues/5004
but those issues don't drop security critical information, which this issue does.

**Comment by Miguel-Signal** [comment]
Hi @cariaso 

I'm curious to know if when presented with a recovery phrase that is truncated, if you are able to rotate your device to landscape mode and view the entire phrase?

**Comment by cariaso** [comment]
The setup seems to be 1time only, so I don't believe I have a way to retest, but I suspect I tried that to no avail.

**Comment by Miguel-Signal** [comment]
Signal version 6.40 should allow you to rotate the device and view the entire phrase when in this scenario. But we appreciate you bringing it to your attention!
