### ISSUE TITLE
Cannot send messages on unsupported iOS version anymore

### ISSUE THREAD

**Issue by Nurgak** [signalapp/Signal-iOS#5661]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am using an iPhone 6 with iOS 12.5.7. I am fully aware that Signal has ceased supporting this iOS version. Two days ago messages could not be be sent/received any more and calls could not be made/received. Although, the application has not had any updates for a long time on this version of the iOS, it has worked as expected so far.

It is a great shame, I do support this application and its ideal, but I fail to understand why Signal chose to exclude older phone models. It would not take any effort in **not** excluding this iOS version communication exchanges.

What has changed that suddenly made it impossible to use Signal on iOS 12.5.7?

### Steps to reproduce
- Use an iPhone with iOS 12.5.7.
- Messages cannot go through.
- _Settings_ -> _Donate to signal_ -> _My Support_ has a message saying: `Network error. Check your connection and try again.`, preventing subscription changes.

**Actual result:** application does not allow communication.

**Expected result:** everything works as usual.

### Device info

**Device**: iPhone 6
**iOS version**: 12.5.7
**Signal version:** 6.28.0.11

**Comment by Miguel-Signal** [comment]
Hi @Nurgak 

Apple ended active support for iOS 12 in September of 2019. We support older operating systems for as long as possible unless there is a technical limitation. This is not a decision we took lightly. Please also keep in mind that we have limitations on what operating systems we can support as we are a very small team and a non-profit organization. An iOS device running iOS 13 or later is now required to use Signal.

In regards to changing your subscription, your account should be in an auto-cancel state within a few days and the donation should be cancelled within a billing cycle. So at most, you will only be charged for one more month.

**Comment by Nurgak** [comment]
I understand that there is no support for SIgnal for such old iOS version. I've read announcement and accept that my hardware is not going to get any updates.

My question was rather: with an application that works, even without support, why prevent it from communicating? It feels like some certificate expired or an API incompatibility was introduced upstream that excludes older devices. That's a shame.

**Comment by plia7** [comment]
@Nurgak So for how long Signal version 6.28.0.11 worked for you after the official unsupported status? I'm asking because I got iOS 14.4.1 and got this message:

"Signal will no longer support your device's version of iOS soon. To keep using Signal, update your device to a newer version of iOS by 9/3/24. Update Now"

Do you know if I will be able to use Signal beyond this date on iOS 14?

Thanks.

**Comment by Nurgak** [comment]
@plia7 For a long while, I cannot remember exactly, but it was between a couple of months to a year perhaps?

In the end I got a new phone. It was unfortunate, as I would've continued using my perfectly good and working phone, but needed to update because the OS was made obsolete.
