### ISSUE TITLE
Signal uses the iPhone microphone for audio messages when Bluetooth headset is connected 

### ISSUE THREAD

**Issue by volse01** [signalapp/Signal-iOS#5663]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using Bluetooth headphones, Signal still uses the iPhone microphone to record audio messages

### Steps to reproduce
- wear Bluetooth headset
- record audio message 

**Actual result:** Signal uses the iPhone microphone 
**Expected result:** Signal uses the headset microphone

### Device info

**Device_Phone**: iPhone 12

**Device_Headset**: AirPods Pro 1st Generation (6A300)

**iOS version**: 17.0 (21A329)

**Signal version:** 6.41.1.0

**Comment by Miguel-Signal** [comment]
Hi @volse01 

This is currently working as intended, but we appreciate you taking the time to give us feedback and suggestions.

We would encourage you to provide feature requests on the community forum also, which can be found here: https://community.signalusers.org/

**Comment by volse01** [comment]
Sorry then for opening an issue :)

**Comment by bdorer** [comment]
Sorry, in my opinion this isn't a feature. If I wear a headset, Signal should use the headsets microphone as other apps do.
