### ISSUE TITLE
App icon: original icon displays in a folder on home screen instead of new icon

### ISSUE THREAD

**Issue by allagashSage** [signalapp/Signal-iOS#5664]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I’m noticing an issue on production, iPhone 13 Pro, iOS 17.0

When applying the new app icons, there is not an asset or app icon size when the app icon is located inside a folder on the Home Screen. Please see screenshots:

### Steps to reproduce
- change the app icon within the app
- Navigate back to the Home Screen and verify the original icon displays within the folder

**Actual result:** the original signal icon displays in the folder on the home screen

**Expected result:** After a new icon is selected within the app, the new icons display inside folders on the Home Screen

### Screenshots

![IMG_0529](https://github.com/signalapp/Signal-iOS/assets/88002161/681e1dbc-7ecb-4fcb-9e96-c6d160561fd5)
![IMG_0528](https://github.com/signalapp/Signal-iOS/assets/88002161/0599cfc6-2762-4d27-be4f-4d892671a21e)

### Device info

**Device**: iPhone 13 Pro

**iOS version**: 17.0

**Signal version:** 6.42.0.18

**Comment by Miguel-Signal** [comment]
Hi @allagashSage, thanks for bringing this to our attention!

I've gone ahead and filed this with our engineering team. While our engineers will be working on a fix, I unfortunately can't give out a specific timeline for a resolution.

**Comment by morz** [comment]
I found that if enable “Hide Screen in App Switcher” option in Privacy settings,  original icon does not change.

Look at screenshot below.

![IMG_2359](https://github.com/signalapp/Signal-iOS/assets/35808/309fb62b-2bf6-4942-8b68-59ddec4387e6)

**Comment by Miguel-Signal** [comment]
@morz Changing the app icon will not change the logo that appears when switching the app, so this would be the expected behavior. I'll share this feedback with the team.

Can you tell me if the icon displayed in the folder is correct after you update to[ Signal version 6.54](https://apps.apple.com/us/app/signal-private-messenger/id874139669)?

**Comment by morz** [comment]
@Miguel-Signal, thanks for responding!
I took the screenshot for version 6.54.0.8.
![image](https://github.com/signalapp/Signal-iOS/assets/35808/6690f6ab-77ea-4d59-a67c-27aa334bd640)

**Comment by morz** [comment]
![image](https://github.com/signalapp/Signal-iOS/assets/35808/4cec3791-bdc6-4cb0-bd34-d78db98cfcf9)
