### ISSUE TITLE
Camera icon disappears when you start typing a message

### ISSUE THREAD

**Issue by smss2022** [signalapp/Signal-iOS#5665]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you start typing a message, the camera icon disappears. The only way to attach a new photo to the message is to take the photo first, *then* start typing.

This behavior appeared after upgrading to version 6.42

The previous versions allowed the user to write a message and then take a photo and attach it to the message.

You can always attach a photo from Photos (i.e. one already on your phone), but not an ephemeral new one, if you've started typing a message.

**Device**: iPhone 13

**iOS version**: 17

**Signal version:** 6.42

**Comment by Miguel-Signal** [comment]
Hi @smss2022 

This is working as designed. The camera button always gets replaced by a 'send' button once you start composing a message. 

What's changed is that the 'send' button used to be an arrow pointing right and now it's a smaller arrow pointing up.

**Comment by LinuxOnTheDesktop** [comment]
> This is working as designed.

It seems _broken_ by design, if I may say so. For, what if one wants to type some text and _then_ attach a photo (as one can do in Google Messages and in WhatsApp)?
