### ISSUE TITLE
Share sheet doesn't share to selected contact

### ISSUE THREAD

**Issue by 211217613** [signalapp/Signal-iOS#5669]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
iOS share sheet doesn't select the signal contact from the recommended row in the iOS share sheet

### Steps to reproduce
- Trigger the share sheet from any app by tapping the share icon
- recommended row of contacts shows up on the top of the iOS share sheet
- signal contact is selected to share the content with
- instead of sharing the content directly with the signal contact the signal app opens to the contacts list

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- The actual behaviour should be that the content is shared directly with the signal contact.
- 
### Device info

**Device**: iPhone 13 mini

**iOS version**: 17.0.1

**Signal version:** 6.42.0.18

**Comment by Miguel-Signal** [comment]
Hi @211217613 

Could you please email support@signal.org and reference this Github issue?

**Comment by 211217613** [comment]
this is still an issue @Miguel-Signal

**Comment by 211217613** [comment]
this is still an issue
