### ISSUE TITLE
iPad Stuck at "Finish Linking" Step

### ISSUE THREAD

**Issue by zacbre** [signalapp/Signal-iOS#5671]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I go to link my iPad to signal, I am stuck at the "Finish Linking" page. The progress circle just keeps spinning forever.

### Steps to reproduce
- Open signal app (after clearing data + uninstalling)
- Select Add as New Device
- Scan the QR code with your phone
- Type the name (I have tried many different names, no variations work)
- Hit finish linking
- Wait for progressbar to spin

**Actual result:** The progressbar keeps spinning forever.

**Expected result:** The iPad should load my linked account and log me in.

### Screenshots
![image](https://github.com/signalapp/Signal-iOS/assets/5459179/12895059-42dd-477f-bddb-b4cda01574dd)

### Device info

**Device**: iPad 5th Gen

**iOS version**: 16.3.1

**Signal version:** 6.42

### Link to debug log

https://debuglogs.org/ios/6.42.0/66bab6954ace4e0611d5d707a2e0676bc0defbffe9c2d81e847fed4dac98be3e.zip
https://debuglogs.org/ios/6.42.0/76c87fc6133b576f00556bce007c9a15a388e2bf54fe02e440da0fbb29f8e60e.zip
(I did this multiple times to make sure that I captured the correct logs)

**Comment by Tursko** [comment]
You can access the debug log by doing the following: 

Tap 8x on an empty space on the screen.

**Comment by StefanLobbenmeier** [comment]
Got the debug link, seems to include older logs: https://debuglogs.org/ios/6.43.0/e0863023d3f144fb18f0529b16ce235c13e1c4c99b7d5b91870b2c9427bdc3a2.zip
