### ISSUE TITLE
iOS client doesn't how the edit feature just released in the context menu

### ISSUE THREAD

**Issue by psarossy** [signalapp/Signal-iOS#5674]
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I’ve received the 6.32.0/6.43 update both on my Mac and my iPhone.

On the Mac, the edit option shows up in the menu, as well as the up arrow edit works, but on iOS there is no edit option in the menu, while edits from the desktop client show up properly in both and also have edit history in the info menu option…
Sounds like a bug in the iOS release?

### Steps to reproduce
- Send message on iOS, attempt to find edit button

**Actual result:** Edit button doesn't exist in the context menu.

**Expected result:** Edit button appears in the context menu.

### Screenshots

Desktop: 
![image](https://github.com/signalapp/Signal-iOS/assets/207358/1e5d8c36-b5bb-4c73-80d7-dd343016a690)

iOS 17.0.2: 
![image](https://github.com/signalapp/Signal-iOS/assets/207358/174e9f67-2dee-428d-a7f2-a8854854acbf)

### Device info
**Device**: iPhone 15 Pro Max

**iOS version**: 17.0.2

**Signal version:** 6.43

### Link to debug log
Can't capture debug log of something not existing...

**Comment by Miguel-Signal** [comment]
Hi @psarossy,
Could you update to Signal version 6.45 in the app store and let me know if the edit option is still missing?
