### ISSUE TITLE
Link containing two #s is not clickable

### ISSUE THREAD

**Issue by gabrc52** [signalapp/Signal-iOS#5675]
- [x] I have searched open and closed issues for duplicates **(I could find other link edge cases that are either already fixed, stale or both)**
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Send or receive a link containing https://example.com/#/hello or https://example.com/#/hello/#world or otherwise a message with a similar format.

**Actual result:** Link is not clickable

**Expected result:** Link is clickable

### Screenshots

![image](https://github.com/signalapp/Signal-iOS/assets/24363938/a7f6708a-324c-4f17-a3e5-6bee56c811ef)

### Device info

**Device**: iPhone 6s

**iOS version**: 15.7.8

**Signal version:** 6.43.0.10

### Link to debug log
https://debuglogs.org/ios/6.43.0/fc74a0034212a27cc4d4c24f0a3cd9b4e1d1158c84c3a2a14d1afd78f16a8885.zip

**Comment by TheBlckbird** [comment]
To my understanding this isn’t a Signal specific issue. It seems like Signal uses a link detector embedded in UIKit/Swift or something like this: `NSTextCheckingResult.CheckingType.link.rawValue`.
https://github.com/signalapp/Signal-iOS/blob/2d6fee16cd92cedf20eafaa3908df0be32d4e9b3/Signal/src/util/DisplayableText.swift#L129

**Comment by Miguel-Signal** [comment]
Hi @gabrc52,

Is there a valid URL with two #s that does not linktify? The one provided is just an example domain.

**Comment by gabrc52** [comment]
Yes, links to Matrix rooms have this format: https://matrix.to/#/#matrix:matrix.org

**Comment by TheBlckbird** [comment]
Don‘t close

**Comment by gabrc52** [comment]
Unstale

**Comment by TheBlckbird** [comment]
Installing this won’t help with fixing it
