### ISSUE TITLE
Transfer between 2 iphones is blocked at 99% after 2 hours.

### ISSUE THREAD

**Issue by KatyPurry** [signalapp/Signal-iOS#5679]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- install signal on the new device
- initiate a transfer from old iPhone to new iPhone

**Actual result:** After transferring around 8,5 Gb of data (it takes around 2h!!!), it stucks at 99%

**Expected result:** Finish at 100%

### Device info

**Old Device**: iPhone 11 Pro
**iOS version**: 17.0.3
**Signal version:** 6.45.0.11

**Old Device**: iPhone 15 Pro
**iOS version**: 17.0.3
**Signal version:** 6.45.0.11

### Link to debug log
**Are logs anonymous ? I don't want to send personnal information about me on Github.**

**Comment by ParkyCode** [comment]
This is still happening
