### ISSUE TITLE
 Development Guide wiki page link goes nowhere

### ISSUE THREAD

**Issue by phraemer** [signalapp/Signal-iOS#5681]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The link to the Development Guide wiki in the readme goes nowhere
https://github.com/signalapp/Signal-iOS#contributing-code

Any contributor will need basic info on how to get started developing for Signal-iOS. Building alone is not enough.
E.g. can I test with the simulator at all? If not will a development build pushed to my own iPhone cause problems with my app store installed Signal? And so on.

**Comment by mOctave** [comment]
I am also having issues with the build process, which I can't seem to resolve because BUILDING.md is insufficient and this link is dead. Is there any intention of addressing this issue?
