### ISSUE TITLE
Messages auto-delete despite user not reading the message(s)

### ISSUE THREAD

**Issue by FU3X** [signalapp/Signal-iOS#5682]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you enable auto-delete it explicitly specifies that the recipient has to read the message before the deletion process begins, but when you send a message under auto-delete without the recipient ever viewing the message the timer starts and the message disappears. In reality the auto-delete timer is supposed to start after the message is read

### Steps to reproduce
- Enable auto delete timer (for debugging purposes choose 5 seconds)
- Send a message making sure the recipient doesn't view it

**Actual result:**
Message gets removed 

**Expected result:**
Message is supposed to get removed when the recipient explicitly views the message

**(tested on other platforms as-well, it occurs 100% of the time)**

### Final suggestions related to this issue 

redo the entire message auto-delete functionality to the following options:
- set Expiration duration after sent
- set Expiration duration after read

**Comment by Miguel-Signal** [comment]
Hi @FU3X 

What you are describing is expected behavior. On the sender side, the timer starts as soon as you send the message, the timer doesn't start on the receiver side until after they've read it. 

https://support.signal.org/hc/en-us/articles/360007320771-Set-and-manage-disappearing-messages

**Comment by FU3X** [comment]
> Hi @FU3X 
> 
> 
> 
> What you are describing is expected behavior. On the sender side, the timer starts as soon as you send the message, the timer doesn't start on the receiver side until after they've read it. 
> 
> 
> 
> https://support.signal.org/hc/en-us/articles/360007320771-Set-and-manage-disappearing-messages
> 
> 

before this is concluded, are there any plans for both ended chat history wipes conducted by one person? ofc both ends can agree to opt out

**Comment by FU3X** [comment]
@Miguel-Signal 
and before this is concluded, are there any plans for both end to end chat history wipes conducted by one person? ofc both ends can agree to opt out

telegram has that option
