### ISSUE TITLE
stuck on "Validating Code" when (re)installing

### ISSUE THREAD

**Issue by jasoneppink** [signalapp/Signal-iOS#5686]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal setup hangs on "Validating Code" after I enter the code I received via SMS

### Steps to reproduce
- Delete and reinstall Signal
- Tap "Continue" and "Allow Permissions"
- Allow Notifications and access to Contacts
- Enter phone number, tap Next, tap Yes to confirm
- hCaptcha appears. Tap checkbox next to "I am human"
- solve hCaptcha
- retrieve 6-digit verification code from text message and enter it

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Screen hangs at "Validating Code" with spinning blue circle

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Validating the code and moving on to next setup step

### Device info

**Device**: iPod 7th Generation

**iOS version**: 15.7.1

**Signal version:** 6.45

### Link to debug log

Unable to access settings to submit debug log

**Comment by Miguel-Signal** [comment]
Hi @jasoneppink,

Could you restart Signal and tap 8 times on an empty area of the screen? You should see a prompt to submit debug logs. It would be great if you could send these logs over to support@signal.org and reference this Github ticket.

Thank you!

**Comment by jasoneppink** [comment]
@Miguel-Signal Just sent!

**Comment by jasoneppink** [comment]
Latest update fixes! <3
