### ISSUE TITLE
Using Flipper Zero Apple BLE SPAM Signal crashes

### ISSUE THREAD

**Issue by Mattitriulzi** [signalapp/Signal-iOS#5687]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

Open Signal with lock enabled.
Flipper Zero sending "Random Action" packets every 20ms.
Signal crashes and IOS shuts down

IOS 17.0.3 then eventually reboots

“Signal unable to start
send logs
start Signal anyway”

send logs = “no logs to send”

**Comment by vnj0x61** [comment]
You really should improve your style to open tickets and follow the rules. People make amazing work in this repo and this should be honored!

Anyway, if you don't know what you are doing with your flipper -> DON'T DO IT! 
Then you can decide to study until you know what you are doing or learn by *feeling* it. I think we all do both ways of learning. But if you really decide do involve other People try to reflect or ask ins forums for help.

Please close the Ticket and have a nice week! :) 

Solution:
---
What are you doing with your Flipper i crashing your iPhone. This is why the name of the function which you use has the Name *IOS 17 Lockup Crash*

**FYI: You also crashing all other Devices with iOS 17.x around you. So please always try to understand what are you doing.**
