### ISSUE TITLE
Keyboard changes language after sending message

### ISSUE THREAD

**Issue by drrlvn** [signalapp/Signal-iOS#5690]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since upgrading to 6.46, after writing a Hebrew message and sending it, the keyboard resets to English. This only happens in Signal.

### Steps to reproduce
- Switch keyboard to Hebrew
- Write message and send it

**Actual result:** Keyboard switches to English by itself

**Expected result:** Keyboard should stay as it was

### Device info
**Device**: iPhone 15 Pro Max
**iOS version**: 17.0.3
**Signal version:** 6.46

### Link to debug log
https://debuglogs.org/ios/6.46.0/778cd98616a3b88a6e5eba06795509caa7453521abafe6c2b41cf9da6f9e6537.zip

**Comment by ddxor** [comment]
I'll take this on since it seems to have likely been introduced as a result of my PR.

**Comment by Miguel-Signal** [comment]
Hi,

We are aware of the problem and we are currently looking for a solution. Although our engineers are working on a fix, unfortunately I can't give a specific schedule for resolution. You might see a fix in the release notes for future versions of Signal.

**Comment by ddxor** [comment]
Interestingly, I cannot replicate this in iOS Simulator, but can on my phyisical iPhone.

**Comment by dr3mro** [comment]
I have same issue here with arabic, does that mean it might be related to RTL languages as Arabic and hebrew are both RTL.

**Comment by ddxor** [comment]
I can't progress this because I can't replicate on iOS simulator and don't have a piece of test hardware right now.

**Comment by dimov165** [comment]
> I have same issue here with arabic, does that mean it might be related to RTL languages as Arabic and hebrew are both RTL.

No, it is not connected to the languages being RTL. I noticed the exact same bug with several left-to-right languages as well.

**Comment by marissa-signal** [comment]
This is now fixed in 6.47.0.10 Beta and in 6.46.1 Prod.
