### ISSUE TITLE
Archiving Unread Messages marks them as read

### ISSUE THREAD

**Issue by theschweitz** [signalapp/Signal-iOS#5702]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
----------------------------------------

### Bug description
Archiving a conversation marks it as read

### Steps to reproduce
- Have another signal user send you a message
- Leave message unread and archive

**Actual result:** Sender & Recipient will see their message check-boxes marked as Read 

**Expected result:** Unread messages should stay unread. This is not "consistent across platforms" as stated in https://github.com/signalapp/Signal-Android/issues/9147. Telegram, for example, keeps unread messages as unread upon archiving. This is dangerous to users and Signal needs to prioritize this fix before this becomes a bigger issue than just inconvenience to users (see: the user mentioning a stalker in the comments of the above issue). Refusing to resolve this issue is irresponsible on Signal's part.

**Comment by Herohtar** [comment]
> This is not "consistent across platforms" as stated in [signalapp/Signal-Android#9147](https://github.com/signalapp/Signal-Android/issues/9147). Telegram, for example, keeps unread messages as unread upon archiving.

This comment was misunderstood. By "consistent across platforms" they meant that the individual *Signal* apps for each platform (iOS, Android, and Desktop) have the same (intentional) behavior and the behavior being complained about wasn't an Android -only thing. They didn't mean "well all the other guys are doing it" as several people seem to have taken it.

**Comment by Miguel-Signal** [comment]
Hi @theschweitz,

I've gone ahead and filed this bug with our engineering team. While our engineers are working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug specifically included in the release notes in future versions of Signal.

Thanks again for your help in reporting this and improving Signal for everyone.

**Comment by floatingatoms** [comment]
> Hi @theschweitz,
> 
> I've gone ahead and filed this bug with our engineering team. While our engineers are working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug specifically included in the release notes in future versions of Signal.
> 
> Thanks again for your help in reporting this and improving Signal for everyone.

Amazing! Is there any chance this issue could be fixed for the Android version as well? To keep it consistent bewteen Signal platforms? :)

**Comment by trysten** [comment]
This issue wasn't resolved. It's still an absolutely trivial fix that was basically [laughed](https://github.com/signalapp/Signal-Android/issues/9147#issuecomment-555321568) at by a developer. The last time @Miguel-Signal posted was [May](https://github.com/signalapp/Signal-iOS/issues/5806#issuecomment-2110400136). Should we assume this isn't the real issue tracker for the multi-million dollar open source project we fund? That perhaps there's a non-public issue tracker that Miguel copies issues to? And that for whatever reason, the devs have _again_ rejected the idea of making the app safe, consistent, or sane.

jfc. Why are we doing this? How many [horror stories](https://github.com/signalapp/Signal-Android/issues/9147#issuecomment-803044428) will it take to make the app behave in a safe way?

**Comment by theschweitz** [comment]
Agreed. Many of us donate to signal on a monthly basis. For this **extremely easy fix** to be ignored / pushed aside at the risk of user safety is shameful. 

Ceasing my donations until this issue is fixed. @Miguel-Signal

**Comment by vyeol** [comment]
This is being fixed in the Android version of the app as of https://github.com/signalapp/Signal-Android/issues/9147#issuecomment-2463019081

How about the iOS version?

**Comment by theschweitz** [comment]
@greyson-signal this issue needs addressing in iOS.

**Comment by vyeol** [comment]
Can anyone reopen this issue? Nothing about this has been resolved.

**Comment by sashaweiss-signal** [comment]
This was addressed in 6498163133b41d892f33ed7a9f0025c47fecec6c.

**Comment by trysten** [comment]
Tested on iOS and Android today. I believe the issue to be resolved. Nice work everyone :)
