### ISSUE TITLE
I have same issue stuck at validating code . Someone could help me?

### ISSUE THREAD

**Issue by Eddie940510** [signalapp/Signal-iOS#5712]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Miguel-Signal** [comment]
Hi @Eddie940510 

Could you please email support@signal.org and reference this Github issue?
