### ISSUE TITLE
Uable to transfer from iPhone 5s to another iPhone 6s

### ISSUE THREAD

**Issue by ykne** [signalapp/Signal-iOS#5714]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Uable to transfer from iPhone 5s to another iPhone 6s
### Steps to reproduce
https://community.signalusers.org/t/signal-blog-ios-device-transfer/14889/11
Looks the same as #4547

**Device**: iPhone 5s

**iOS version**: 12.5.7

**Signal version:** 6.28.0.11

**Comment by BurhanBudak** [comment]
Same issie herr, used to be iphone 7 to 11 but 6s to 7 is impossible because of minimum requirement that is ios13

**Comment by Miguel-Signal** [comment]
Apple ended active support for iOS 12 in September of 2019. We support older operating systems for as long as possible unless there is a technical limitation. This is not a decision we took lightly. Please also keep in mind that we are a very small team and have limitations as a non-profit organization.

An iOS device running iOS 13 or later is now required to use Signal and required to perform an account and message history transfer.

**Comment by ykne** [comment]
@BurhanBudak you probably meant 6 and not 6s? 6s is fully compliant.

**Comment by ykne** [comment]
@Miguel-Signal I know it is no longer supported that is why attempted to save my data. Please revisit.
