### ISSUE TITLE
swift version of Signal derived app, scrolling size causes message boxes not being showed correctly

### ISSUE THREAD

**Issue by stark226** [signalapp/Signal-iOS#5717]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm maintaining an app forked by Signal 5.22.1 (cannot update at this moment) app on GitHub for iOS. After updating to iOS 17 scrolling the conversation causes the message boxes to display text size incorrectly. Current signal app seems not being affected by this issue.

In the picture you can see the issue, I used a serie of 4 groups of numbers 1234567890. As you can see the text is not rendered correctly in size, and message is not fully displayed in length, some boxes show only 2 or 3 group of numbers. I looked for issue, but I cannot find references. Could someone help me? I think it could be some Framework, since issue seems to appeared after iOS update. Even some indication could be helpful.

### Steps to reproduce
- open the app
- select a conversation
- scroll up and down messages

**you'll se some message boxes, not always the same, that are displaying the text in different sizes, and not completely.:** 

**I'd like all at the message boxes showing full message in the proper text size:** 

### Screenshots

![IMG_3887F3311FAF-1](https://github.com/signalapp/Signal-iOS/assets/6348412/c0f604b3-14d4-4e99-889b-68f8be4a5cc7)

### Device info

**Device**: iDevice iPhone 11 (2 devices) iPhone X

**iOS version**: iOS 16.1, 17.2

**Signal version:** 5.22.1 (mine is a forked app from this version)

**Comment by Miguel-Signal** [comment]
Hi @stark226, due to some limitations as a non-profit organization we are only able to provide support for non forked versions of the app.

**Comment by stark226** [comment]
hi miguel, thnak for response, I see, for me it could be enough knowledge if you got this issue and if you resolved via code or updating some framework. even getting an hint for the possible origin of the bug. Thanks.
