### ISSUE TITLE
Unencrypted Push Notifications

### ISSUE THREAD

**Issue by JimLoose** [signalapp/Signal-iOS#5720]
Signal is an encrypted messenger and it uses push notifications by default on many mobile devices. I would briefly describe it as a bug that these can be read by goverments: 

https://www.macrumors.com/2023/12/06/apple-governments-surveil-push-notifications/

**Comment by maba4891** [comment]
No they can't:
"First: push notifications for Signal NEVER contain sensitive unencrypted data & do not reveal the contents of any Signal messages or calls–not to Apple, not to Google, not to anyone but you & the people you're talking to."
https://x.com/mer__edith/status/1734320963074797917?s=20
