### ISSUE TITLE
Direct sharing of pdf via browser (Safari) not possible

### ISSUE THREAD

**Issue by Janikson9** [signalapp/Signal-iOS#5722]
- [X ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No pdf documents can be shared with Signal via the browser. The app is not displayed for sharing.
Photos can be shared directly with signal, Signal is available there.

### Steps to reproduce

1. Open browser (Safari)
2. Go to share
3. Signal is not displayed as an available app

**Actual result:** It is not possible to share documents directly in Signal via the browser (Safari)

**Expected result:** It should also be possible to share documents directly in Signal via the browser

### Screenshots

https://github.com/signalapp/Signal-iOS/assets/152014058/759c8a2b-61d1-4cac-aa08-a87f11ab9375

Due to data protection, I had to crop the screen shot considerably

### Device info

**Device**: iPhone 15

**iOS version**: 17.2

**Signal version:** 6.53

**Comment by patjolata** [comment]
This seems to happen for a while. I might not repoduce it now, but sometimes Signal is missing on my Share Sheet too - including the Signal contacts.

This bug was already in iOS 14 around: https://community.signalusers.org/t/add-signal-to-app-list-on-ios-instagram-share-to-button/25703/7?u=patjolata

**Comment by Janikson9** [comment]
I received the following reply from support:
Hello, thank you for your message to Signal support.
 
Sharing PDFs directly from the browser without saving them first is not supported, but we appreciate you taking the time to give us feedback and suggestions.

--
Too bad. Direct sharing would be great

**Comment by Janikson9** [comment]
https://community.signalusers.org/t/ability-to-share-pdfs-from-browser-via-sharesheet/28755/6
