### ISSUE TITLE
Can't expand long messages in message Info or View edit history

### ISSUE THREAD

**Issue by odaom** [signalapp/Signal-iOS#5724]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Nothing happens when tapping "Read more" in the Info view and in View edit history. Expected behavior is that the message box expands to show the whole message.

### Steps to reproduce
- Open message Info view of a long message that is truncated
- Tap "Read more" at bottom of truncated message

**Actual result:** Nothing happens.

**Expected result:** The message expands.

The same is the case for the edit history view, tapping "Read more" does nothing.

### Screenshots
![screenshot](https://github.com/signalapp/Signal-iOS/assets/42997653/61c15a6d-7da0-4f86-989c-f3d40cb51ed8)

### Device info

**Device**: iPhone SE

**iOS version**: 16.6.1

**Signal version:** 6.53.0.7

**Comment by nishantminerva** [comment]
I would like to work on this.

**Comment by nishantminerva** [comment]
What I found is - That the Message Details screen is not intended to take taps on it. So that's why tapping Read More is not working.
<img width="623" alt="Screenshot 2023-12-20 at 2 39 42 PM" src="https://github.com/signalapp/Signal-iOS/assets/53352011/67e906a5-783f-4ab0-8e31-10b1a2cb982a">

Please let me know if I have to implement the functionality of tap to Read More in Message Details Screen.

**Comment by lukasvrenner** [comment]
Perhaps, it would be easier if it simply expanded it by default?

**Comment by odaom** [comment]
> Perhaps, it would be easier if it simply expanded it by default?

Considering messages can have arbitrary lengths, this does not sound user friendly. The message info page would lose most of its utility if I have to scroll through 1000 words to just see when it was sent/read. So the default truncation is there for good reason.

**Comment by odaom** [comment]
Expanding in message info view is actually not that important. You can just go to the message in the chat to read the full length. The actual problem, and the reason I’ve reported this bug, is that it’s the same in message edit history. 

If the edit happened somewhere after the truncation, it’s currently impossible to see what the edit was, on iOS. Fixing the "Read more" in edit history seems more important than fixing it on the message info view (although fixing both would be great).

**Comment by nishantminerva** [comment]
Okay.

**Comment by nishantminerva** [comment]
I need help to understand how signal code works in IOS.

I tried putting breakpoint so navigate to the Read More button - But found that it's a CVLable.

located the - func didTapTruncatedTextMessage(_ itemViewModel: CVItemViewModelImpl) {}
and expandTruncatedTextOrPresentLongTextView(itemViewModel), But not able to understand the code, please help.

I did my best to find and locate the button but was not able to understand the codebase, Can anyone of you explain the whole code base to me? @harry-signal @elaine-signal @sashaweiss-signal @jimio-signal @marissa-signal @pete-signal 

<img width="1512" alt="Screenshot 2024-02-07 at 10 07 44 PM" src="https://github.com/signalapp/Signal-iOS/assets/53352011/df6b9636-915e-4281-9bc3-94ac38530bdb">
<img width="1512" alt="Screenshot 2024-02-07 at 10 07 36 PM" src="https://github.com/signalapp/Signal-iOS/assets/53352011/0b037355-443b-4e69-bbb0-caf5eb15b785">
