### ISSUE TITLE
Video Stories don't pause music

### ISSUE THREAD

**Issue by lukasvrenner** [signalapp/Signal-iOS#5725]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

When watching a story video with sound, it ought to pause any playing music. This behavior is found for every other thing that plays sound, even watching normal videos on Signal. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

- post a Story that's a video containing sound
- play music from device (i.e Apple Music)
- Watch Story video

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Audio of video plays overtop of music

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Video ought to automatically pause music, which is generally the expected behavior

### Device info

**Device**: iPhone 11

**iOS version**: 17.1.2

**Signal version:** 6.54

### Link to debug log

https://debuglogs.org/ios/6.54.0/f961dc891ccf1f4a4398508344c737498ee315674e01ecaf02ba0409b21bf737.zip

**Comment by lukasvrenner** [comment]
![image](https://github.com/signalapp/Signal-iOS/assets/118417051/f68382b9-480d-4c29-9476-b6f4c7e9b7fe) After a quick look around, my best guess is that the issue is here, in the function `reconcileAudioCategory()`, in SignalUI/Utils/AudioSession.swift. If the try succeeds, it calls `try setCategory(.playAndRecord)` and `try avAudioSession.overrideOutputAudioPort(.none)`, but if it fails, it only calls `try setCategory (.playback)`, but not the second one. However, this is only a guess, after a quick look, and I haven't tested it, so I could be totally wrong.

**Comment by lukasvrenner** [comment]
I'm not positive, and I haven't tested it, but the issue appears to be on line 42 of Signal/src/ViewControllers/HomeView/Stories/Context/View, where it says `behavior: .playbackMixWithOthers`, rather than `behavior: .playback`

![image](https://github.com/signalapp/Signal-iOS/assets/118417051/d9159ad5-b3ef-4015-aa65-0c0f9a59d048)

**Comment by blackjackfruit** [comment]
The following commit included the change from .playback to .playbackMixWithOthers on purpose: 
![Screenshot 2024-01-02 at 5 30 35 PM](https://github.com/signalapp/Signal-iOS/assets/2627779/75f9b9bb-c838-4cdd-98d9-ff94cae26eb3)

Not only as a user but as a developer the behavior I would think best is to pause another apps audio to play the story and then let iOS resume the other app's audio once the story has stopped playing. An experience similar to youtube playing a podcast and then going to instagram to view a full screen story should pause youtube until the story is complete or the user dismisses the story.

The fix should be to use .notifyOthersOnDeactivation when setActive is set to false
`
try AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)
`
Also it would be necessary to change from .playbackMixWithOthers back to .playback. 

@lukasvrenner what is the expected experience, is mixWithOthers or resume another app's audio after stopping a story?

**Comment by lukasvrenner** [comment]
> @lukasvrenner what is the expected experience, is mixWithOthers or resume another app's audio after stopping a story?

@blackjackfruit I agree, that makes a lot of sense to have it pause audio, and then resume once the story is over. Mixing with others doesn't make any sense in my opinion, because suddenly you can't hear what you're listening to, and you can't hear the sound in the story either.
