### ISSUE TITLE
Hard to get Capchas to relent.  An old problem is starting again.

### ISSUE THREAD

**Issue by DiagonalArg** [signalapp/Signal-iOS#5727]
iPhone SE (gen.1)
iOS 15.7.9
Signal 6.54.0.8

I've been reporting serious issues with excessive capchas on desktop, [here](https://github.com/signalapp/Signal-Desktop/issues/6714#issuecomment-1868990431).  I'm also seeing excessive capchas on iphone, though not quite as bad.  This is the worst I've seen it so far:

I've been seeing a lot of cases in which I turn on the network, and without posting anything, just after messages are downloading, I get a capcha.  This is one case: [Log](https://debuglogs.org/ios/6.54.0/672aebc94a0fb7f87c0cea1ae66850a6cec2e017c0ac150be0b85a13008b8fc3.zip).  So I sent that debug log link to myself, immediately getting another capcha.  ([Log](https://debuglogs.org/ios/6.54.0/542fd41d1f83e0ecf74963b3e3a72aa4fd192d10d8ee83ef990dd19ed0fcb188.zip)).  In the next 2-3 minutes, I sent that second debug log to myself, perhaps one more text (I don't remember), got a capcha, and then as I was entering text on a group thread, just starting to type, I got a second.  [Log](https://debuglogs.org/ios/6.54.0/cb1b43b21aed1e7ea489d03128435baf5b30a5735fe05a90fde6009f0d918ab8.zip).  So I sent myself *that* debug log, and went back to finish typing that text, getting *another* capcha.  [Log](https://debuglogs.org/ios/6.54.0/1ddef9abaa3b88977efcf2c9cb5d2cd40e1761c6cf77b86dea3a1a21dffd08da.zip).  I sent that log to myself and it seemed to relent.

**Comment by DiagonalArg** [comment]
Another case of just connecting the network, and then as the messages are downloading, I get a capcha.  [Log](https://debuglogs.org/ios/6.54.0/cbc3509dd2252be9a71edc3ea30cdf547f9ccc20c2677c253e56643fb49639d6.zip).

**Comment by DiagonalArg** [comment]
Another case: just connecting, no messages sent.  [Log](https://debuglogs.org/ios/6.54.0/9def787737ce8b0c2a49d3e1ff7324d513432334612630a786694b8ade6c94ea.zip).

**Comment by Miguel-Signal** [comment]
Hi @DiagonalArg, I have a few questions.
How many messages per minute are you typically trying to send?
How many groups are you messaging?
How many members are in these groups?
In your groups, do you see a profile name, a phone number or "unknown" for the other group members?
Are you using a VPN?

**Comment by DiagonalArg** [comment]
Here I started to type a message, and after 3-4 letters, there was a capcha.  Then a half a dozen more letters, and another capcha.  Then I sent the message, and there was a capcha.  I saw an exlalmation point on the message, and then the spinner going, as I got another capcha.  After that 4th one, the message was sent.  [Log](https://debuglogs.org/ios/6.54.0/e76decebbd81d2e8ee8a8c309caee87823869f99082efa69d04d87347cab60dd.zip).  This was a message in the very large group that I've been repeatedly reporting on, [here](https://github.com/signalapp/Signal-Desktop/issues/6714#issuecomment-1895678402).  (I use my phone in a very limited manner, usually messaging from my laptop.)

As for your questions....

Per minute?  That would be too many, though sometimes I find myself forwarding to maybe 3 groups at once.  (Not in this case though - I was typing a message to a single group.)  This latter group is the large one with 668 (now 667) members discussed in that Desktop thread.  Yes, this group has many "unknown" members.  I counted roughly 215 of them.  And yes, I always use a VPN, though as I gather, on iphone those things are leaky.

**Comment by Miguel-Signal** [comment]
@DiagonalArg thanks for that info. If possible, could you try one or both of the following and let me know if things improve?

- A VPN from a different provider.
- Configure your current VPN with the following:

**_Allow *.whispersystems.org, *.signal.org, updates.signal.org, TCP port 443, and UDP traffic. If you have a transparent or reverse proxy it needs to support WebSockets. Signal uses a non-standard TCP port to catch filtering issues at the signaling step and also utilizes a random UDP port. All UDP ports will need to be opened. The underlying IPs are constantly changing, so it'd be hard to define accurate firewall rules.

If the wildcard FQDN config is not working properly and you notice issues with calling, allow turn2.voip.signal.org, turn3.voip.signal.org and sfu.voip.signal.org. These are subject to change at anytime._**

**Comment by DiagonalArg** [comment]
@Miguel-Signal / Hm.  I take it "allow" would go directly rather than through the VPN?

On the iPhone I'm using ProtonVPN.  As far as I can tell, those settings are not accessible, other than I see the option to use Wireguard or Wireguard (TCP).  I'm using the former.

Note that I'm also using ProtonVPN on the desktop, where I'm having parallel problems, and I've chosen to use UDP.

I may be able to switch over to an Android phone soon, and give a report from there; but otherwise I'm not sure what else I can do.

**Comment by DiagonalArg** [comment]
I've got another person on one of my groups using an iPhone 10 and who uses ProtonVPN.  He's probably not as active as me, but he's having trouble with that group asking him to do a capcha every time he posts.  He's saying that changing to "Wireguard (TCP)" seems to have eliminated the capchas.  I'll post back if he tells me that it starts again.

I've never had issues with that specific group myself, but I can run any commands on that group that you might want.

**Comment by DiagonalArg** [comment]
bump.
