### ISSUE TITLE
Not notified about new messages whenever inside the app [IOS]

### ISSUE THREAD

**Issue by exquisite-stupidity** [signalapp/Signal-iOS#5728]
Hello. I seem not to be able to receive message notifications whenever I'm inside the app. Seriously, I only get notified about the new message either if I hopped off the app to home screen, or some other app, or if the phone is turned off. If I open any chat on signal whatsoever, I don't get notified about any new messages from any chat. I'm running it on IOS. I've checked all the phone settings and the internal signal settings. Everything's in order. What should I do? Couldn't even find a single post pertaining to such an issue.

**Comment by marissa-signal** [comment]
Sorry about this issue. Our support team has received some reports of this as well. We have found what broke foreground notifications and are working on a fix.

**Comment by exquisite-stupidity** [comment]
> Sorry about this issue. Our support team has received some reports of this as well. We have found what broke foreground notifications and are working on a fix.

Hi. Thanks for taking the time to respond to my inquiry. Please, please do so. This bug basically renders the whole app useless for me. Henceforth, how will I able to find out that you've actually fixed the issue? Could someone notify me?

**Comment by blapcity** [comment]
Release 6.56 has resolved this issue for me. But I have noticed that if I’m on the Chat tab and I receive a message I still receive a banner notification. Is this the intended behavior?
