### ISSUE TITLE
In main screen, animations of read message go weird

### ISSUE THREAD

**Issue by pylapp** [signalapp/Signal-iOS#5729]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Given I started my Signal application to display my list of groups and messages, when the list of groupes and messages is displayed, I have the image about read messages which has a weird animation with endless rotation.
I restarted my app and the bug disappeared.

### Steps to reproduce
- open the app
- get the list of messages displayed 
- the "read" icons of the last pinned group chat is weirdly animated 

**Actual result:** Failed to reproduce but thought it could be interesting to report it 

**Expected result:** Failed to reproduce but thought it could be interesting to report it 

### Screenshots

https://github.com/signalapp/Signal-iOS/assets/7559007/b8f7682f-cabe-4e7d-87ba-4db1d36578cd

### Device info

**Device**: iPhone 14 Pro

**iOS version**: 17.2.1

**Signal version:** 6.54.0.8

**Comment by Miguel-Signal** [comment]
Hi @pylapp 

I've gone ahead and filed this with our engineering team. Thanks for your help in reporting it and improving Signal for everyone.
