### ISSUE TITLE
⚠️ How to crash Signal on an iPad in seconds (Flash Bug)

### ISSUE THREAD

**Issue by TheAresjej** [signalapp/Signal-iOS#5736]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The bug relates to the iPad 6th gen which does not have a built-in flash for photos so selecting flash when taking photos the app automatically crashes.

### Steps to reproduce
- Select the flash option on an ipad 6 gen or other iDevice that does not have flash built in.
- Take a picture
- Crash

**Actual result:** Application crashes

**Expected result:** In order not to change too much in the code, it is sufficient to block the ability to interact with the flash button.

### Device info
**Device**: iPad 6
**iOS version**: 17.2 (latest at the moment)
**Signal version:** 6.54.0.8

**Comment by Miguel-Signal** [comment]
Hi @TheAresjej 

I've gone ahead and filed this bug with our engineering team. While our engineers are working on a fix, I unfortunately can't give out a specific timeline for a resolution. 

Thanks again for your help in reporting this and improving Signal for everyone!
