### ISSUE TITLE
Accept URL and text from iOS share sheet, instead of just URL

### ISSUE THREAD

**Issue by jasongitmail** [signalapp/Signal-iOS#5737]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I'm developing an iOS app that uses NativeScript's `shareUrl()` functionality, which leverages iOS's native sharesheet.

Apps are able to provide a URL and text to prepopulate into a message app's compose box. 

For example: `https://example.com Check out this app!`

Signal populates only the URL into it's compose box and omits the text. Other messengers like WhatsApp or iOS Messages, include both the URL and text as intended.

### Steps to reproduce

1. Install NativeScript's Preview app on iPhone https://apps.apple.com/us/app/nativescript-preview/id1264484702
2. Visit [NativeScript's demo app for social sharing](https://docs.nativescript.org/plugins/social-share#demo-app), wait for Stackblitz to load, and then scan the QR code shown. The NativeScript preview app will load and run the demo iOS application.
3. Click the "Share URL" link shown in the demo app.
4. The sharesheet will open. Choose Signal, then Note To Self, and then arrow to continue.

### Actual result:

The URL is populated into Signal's compose box.

![signal](https://github.com/signalapp/Signal-iOS/assets/50032291/7971dff8-6bea-47fa-bdc4-165e09f80f15)

### Expected result:

The URL and the text of `Home of NativeScript` should both be populated into the compose box, like in these examples:

WhatsApp:
 
![whatsapp](https://github.com/signalapp/Signal-iOS/assets/50032291/00c2a1aa-0acc-4a27-b556-657154e6c92a)

iOS Messages

![messages](https://github.com/signalapp/Signal-iOS/assets/50032291/368934cd-bf50-4aba-9910-b17041a2b113)

### Device info

**Device**: iPhone 14 Pro
**iOS version**: 17.2.1
**Signal version:** 6.56

**Comment by bexelbie** [comment]
Likely duplicate of #5641
