### ISSUE TITLE
Bug: message notification missing while CarPlay connected

### ISSUE THREAD

**Issue by secoepdev** [signalapp/Signal-iOS#5738]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While the iPhone is connected via CarPlay incoming messages is delivered, but without a notification sound and display do not light up either, while incoming voice call notification works as normal.

### Steps to reproduce
- Connect iPhone to CarPlay
- Send message from another device to the iPhone

**Actual result:** on iPhone no notification of incoming message

**Expected result:** incoming message should give notification sound and pop-up message in car system while CarPlay is activated

### Device info

**Device**: iPhone 15 Pro Max

**iOS version**: 7.2.1

**Signal version:** 6.56.0.13

**Comment by Miguel-Signal** [comment]
Hi @secoepdev, thanks for bringing this to our attention. 

Please note that CarPlay is not officially supported, and we cannot guarantee its functionality.
