### ISSUE TITLE
How to disable weird emois

### ISSUE THREAD

**Issue by danispringer** [signalapp/Signal-iOS#5741]
When I type wink emoji I am suggested some hot pepper GIF, uhm NO THANK YOU. Turn off. Thanks.

![IMG_1163](https://github.com/signalapp/Signal-iOS/assets/19246409/76e901dc-e674-4fbd-b395-18ac7a5442cd)

**Comment by D3nn7** [comment]
Hey you can easily uninstall such sticker packs in 2 ways:

## Uninstall the simplest way
1. Sent Sticker to "Note to Self" and click on the sticker
<img src="https://github.com/signalapp/Signal-iOS/assets/79147263/68c478ef-705e-47a6-97ed-ae384ddc663f" height="250">

2. Click *uninstall* to fully uninstall sticker pack
<img src="https://github.com/signalapp/Signal-iOS/assets/79147263/811baf19-5dff-4f0d-89ec-accac8eff87a" height="250">

## Uninstall
1. Click on sticker icon in input bar
<img src="https://github.com/signalapp/Signal-iOS/assets/79147263/a0882a07-11ef-4cd3-bcbf-9334585488eb" height="250">

2. Click on the "+" icon
<img src="https://github.com/signalapp/Signal-iOS/assets/79147263/f1f6c92d-edc6-49da-8d66-6b914c8cabde" height="250">

3. Select Sticker pack
<img src="https://github.com/signalapp/Signal-iOS/assets/79147263/ece23b63-1269-4703-b87f-bdd90f472999" height="250">

4. Click *uninstall*
<img src="https://github.com/signalapp/Signal-iOS/assets/79147263/811baf19-5dff-4f0d-89ec-accac8eff87a" height="250">

**Comment by danispringer** [comment]
@D3nn7 thanks! that seems to have worked

I would recommend NOT preinstalling sticker packs (especially questionable ones).

Thanks
