### ISSUE TITLE
Push Notifications Do Not Work With Power Saving Enabled

### ISSUE THREAD

**Issue by Rahcx** [signalapp/Signal-iOS#5746]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With power saving enabled. Signal does not send any push notifications, Video and normal calls are recievd as normal and pop-up onto the screen with power saving on and off. Turning power saving off immediately resolves the issue. One observation I made is when power saving is enabled, Signal's 'Background App Refresh' permission is taken away and cannot be turned back on.

### Steps to reproduce
- Enable power saving
Note: Does not matter whether the app is open in the background or not.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
I simply do not receive any push notifications.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
When I turn power saving off, I receive push notifications.

### Device info
**Device**: iPhone 12 Pro

**iOS version**: 17.2.1

**Signal version:** 6.58

### Link to debug log

N/A

**Comment by Miguel-Signal** [comment]
Hi @Rahcx, I have a few questions. 

- Is this only happening with Signal notifications?
- Does the issue persist after you restart your device?
- Do you have an Apple Watch? If so, can you test something for us by removing Signal from the list of apps getting notifications to the watch and tell me if notifications on your phone improve?
- Could you try to re-register for push notifications to see if this helps resolves the issue? Go to Signal Settings > Notifications > Re-register Push Notifications > OK
- Can you share your debug logs? To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link.

**Comment by Rahcx** [comment]
Hey Miguel,

- Only Signal notifications
- Yes
- No
- Doing this resolved the issue

Many thanks Miguel.
