### ISSUE TITLE
Delete for me / everyone in "Note to Self"?

### ISSUE THREAD

**Issue by danispringer** [signalapp/Signal-iOS#5749]
**Signal iOS version 6.59**

Why are there two options? Is there a functional difference? If there is, it's unclear either way. Probably there should only be a single option.

![IMG_1336](https://github.com/signalapp/Signal-iOS/assets/19246409/3d4e3504-84d8-4259-999c-485a54ca906a)

**Comment by Miguel-Signal** [comment]
Hi @danispringer

Both options appear because you can link secondary devices to your Signal account. Delete for me deletes the message from the device you are currently using. Delete for everyone deletes the message from the device you are using as well as any linked devices.

**Comment by danispringer** [comment]
> Is there a functional difference? If there is, it's unclear either way.

Issue closed?
Signal really isn’t helping itself.
A subpar project that refuses help, or to recognize it needs work.
Good luck.
