### ISSUE TITLE
Why is Amazon contacted by app?

### ISSUE THREAD

**Issue by danispringer** [signalapp/Signal-iOS#5760]
Why is Amazon contacted by app?
![Screenshot 2024-02-11 at 2 27 11 AM](https://github.com/signalapp/Signal-iOS/assets/19246409/528c094a-7552-426a-bb9d-99f81bf7c7b0)

**Comment by NicholasRebello** [comment]
Did you or someone you chatted with send a link to Amazon?

**Comment by danispringer** [comment]
@NicholasRebello yes I think so, would that be it?
Would turning off “generate link previews” avoid that?

thanks

**Comment by NicholasRebello** [comment]
@danispringer Yes I believe that would be the case. I have had the “generate link previews” off for a while now and in my app privacy report I don’t see any calls to Amazon or any of the other links I’ve shared in my chats.

**Comment by danispringer** [comment]
@NicholasRebello got it, thanks!
