### ISSUE TITLE
Can someone get off their high horse and sort out #4916 ? We're asking since 2021

### ISSUE THREAD

**Issue by sgreadly** [signalapp/Signal-iOS#5766]
Seriously, several releases throughout and all you push out is emojis, while we have serious bugs like #4916 that need to be addressed, and a dozen people that are there to provide you with any data you need - as we already did provide multuple times.

Can you please assign #4916 to someone so we can get this resolved before more start quitting Signal? Already a large chunk of my family and friends left it a while back, and we're trying to hold on as much as possible.

**Comment by joshaustintech** [comment]
I have ended donations to Signal over #4916 being ignored. I really hope this gets addressed and that this app is not treated as Open Source In Name Only.

**Comment by sgreadly** [comment]
Marking as resolved as the referenced bug is now resolved.
