### ISSUE TITLE
`make dependencies` fails with Python `SSL: CERTIFICATE_VERIFY_FAILED` error

### ISSUE THREAD

**Issue by sharplet** [signalapp/Signal-iOS#5768]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After cloning the repository and following the steps in [`BUILDING.md`][building-md], I encounted the Python error `SSL: CERTIFICATE_VERIFY_FAILED` when running the `make dependencies` step.

I've opened a PR with a proposed fix here: https://github.com/signalapp/Signal-Pods/pull/9

### Steps to reproduce
- Open a shell environment where only the system `python3` is available
- Clone the repository following the steps in [`BUILDING.md`][building-md]
- Run `make dependencies`

**Actual result:** Setting up dependencies fails with a Python 3 exception.

**Expected result:** Expected dependencies to be set up.

### Screenshots
N/A

### Device info
**macOS version:** 14.3.1
**Python version:** 3.11.4
**Signal version:** Signal-iOS @ 75b1b04c05abf1e19c7c04a570236cb0399fcec6

### Link to debug log
N/A

[building-md]: /signalapp/Signal-iOS/blob/75b1b04c05abf1e19c7c04a570236cb0399fcec6/BUILDING.md

**Comment by Fireroman** [comment]
Same here

**Comment by igormagurean** [comment]
As easy as that
![Screenshot 2024-05-22 at 14 00 10](https://github.com/signalapp/Signal-iOS/assets/15688672/5a74e70a-7730-40e5-a6be-82c32599f6e1)

**Comment by jaycex** [comment]
Encounter this problem again. While running make dependencies after clone the repo, got following error.
downloading webrtc-7204a-ios-release.tar.bz2...
...
...
urllib.error.URLError: <urlopen error [SSL] record layer failure (_ssl.c:1028)>

And I tried to visit https://build-artifacts.signal.org/libraries/webrtc-7204a-ios-release.tar.bz2 in chrome, got this error:

<img width="640" height="337" alt="Image" src="https://github.com/user-attachments/assets/5cab7beb-2056-4ef0-9f36-d8f6a4fe37c5" />

Is there something wrong with the build-artifacts.signal.org server ?

**Comment by max-signal** [comment]
I think this is happening because Python can’t find any certificates to validate the connection. These StackOverflow posts have some more details and potential mitigation steps:
- https://stackoverflow.com/questions/77442172/ssl-certificate-verify-failed-certificate-verify-failed-unable-to-get-local-is
- https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by jaycex** [comment]
But I can not download it(https://build-artifacts.signal.org/libraries/webrtc-7204a-ios-release.tar.bz2) via my browser. 
And there is someone else facing the same problem as I do.
https://community.signalusers.org/t/signal-ios-download-webrtc-failed/70496
