### ISSUE TITLE
Audio output randomly disabled on calls until app restart

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#5769]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I'm on Android. This only seems to happen with my peers on iOS. It's being going on for months if not years. For some reason, when they answer my call, they can't hear anything. I can hear them, though. They can call me back, or I can call them back, and the silence persists. It's only when they close Signal (swipe it away) and reopen it by tapping on the icon that they can again hear me. This has happened regardless of which of my Android phones I've been on, and it seems unpredictable, affecting maybe 5% of calls.

### Steps to reproduce

- Open Signal on Android (or maybe iOS).
- Voice call your friend on iOS.
- Let them answer.
- Randomly, they won't be able to hear you.
- There is probably something else necessary to reproduce this. It might be, for instance, that the receiving phone needs to have been idle long enough to fall asleep first. I've just never been able to nail it.

I'm pretty sure this has happened when the recipients were not actually listening to a voice message. Nevertheless there might be a common cause here:

https://github.com/signalapp/Signal-iOS/issues/5493

Also, I haven't asked my iOS peers to try muting and then unmuting, as described in this vaguely related issue:

https://github.com/signalapp/Signal-iOS/issues/5689

If this occurs again, I'll try asking them to do that.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Randomly, my peer can't hear me.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

They would be able to hear me.

**Device**: iPhone 13, at least, and I believe others, but it's been too long to remember.

**iOS version**: Various over many months.

**Signal version:**: Latest over many months.

**Comment by sailbird** [comment]
Confirmed that this also occurs on iPhone 15, so probably it occurs on 14 as well. In the most recent case, my peer was doing nothing with the phone at the moment I called. Their screen was lit up with another app but no user interaction was occurring. They were not playing a voicemail or doing anything with Signal. As always, a restart of Signal (not the phone) fixed the lack of received audio on their side.

**Comment by marissa-signal** [comment]
Thank you for reporting! I'm thinking this may be more on the RingRTC (https://github.com/signalapp/ringrtc) side of things. I passed it along to someone on that team.

**Comment by sailbird** [comment]
Thanks @marissa-signal . One correction is that it has been confirmed on iPhone 13 and 14, but not 15. Not that it likely matters. Also, this might not be a purely statistical thing. Like if you call 1000 times in a row, they might all work fine. I suspect that some sort of sleep state is involved, either of the app or the relevant hardware. Maybe even the Airpods. No clue.
