### ISSUE TITLE
Opus files cannot be played

### ISSUE THREAD

**Issue by avidseeker** [signalapp/Signal-iOS#5771]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opus files cannot be played from iPhone

### Steps to reproduce
- Send an opus file from Android to iPhone
- Shows up in chat as a recording
- Plays perfectly on Android
- Doesn't play on iPhone

**Actual result:** clicking the recording doesn't play it

**Expected result:** plays just like Android

### Device info

**Device**: iPhone 12

**iOS version**: 17

**Signal version:** 7.1

**Comment by Miguel-Signal** [comment]
Hi @avidseeker 

Could you please write into support@signal.org with a link to your debug logs and reference this github issue? 

To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.

**Comment by iromeister** [comment]
I don't use iOS myself, but my friends do. I can confirm this and it's really annoying. I share a voice message from Telegram or WhatsApp to Signal on my Android phone, which works as expected there. But my iOS friends cannot play the voice message on their phones.

**Comment by rubdos** [comment]
Would adding Opus/Ogg/Vorbis to the supported mime type lists be enough to get over this issue? I don't have any iOS development experience, but I imagine supporting (and using) Opus might relieve some storage stress. Context for me: I'm implementing sending voice notes in Whisperfish, and it'd be rather neat if we could use Opus.

```diff
diff --git a/SignalServiceKit/src/Util/MIMETypeUtil.m b/SignalServiceKit/src/Util/MIMETypeUtil.m
index 0511962325..617eaee37e 100644
--- a/SignalServiceKit/src/Util/MIMETypeUtil.m
+++ b/SignalServiceKit/src/Util/MIMETypeUtil.m
@@ -85,6 +85,7 @@ NSString *const kLottieStickerFileExtension = @"lottiesticker";
             @"audio/x-aiff" : @"aiff",
             @"audio/3gpp2" : @"3g2",
             @"audio/3gpp" : @"3gp",
+            @"audio/ogg" : @"ogg",
         };
     });
     return result;
@@ -180,7 +181,9 @@ NSString *const kLottieStickerFileExtension = @"lottiesticker";
             @"bwf" : @"audio/wav",
             @"m4a" : @"audio/x-m4a",
             @"m4b" : @"audio/x-m4b",
-            @"m4p" : @"audio/x-m4p"
+            @"m4p" : @"audio/x-m4p",
+            @"ogg" : @"audio/ogg",
+            @"opus" : @"audio/ogg",
         };
     });
     return result;
```

**Comment by c-harding** [comment]
This is still an issue @Miguel-Signal, I encountered it today when an Android user forwarded me a voice memo from WhatsApp.

**Comment by Ennneerrrgggyyy** [comment]
I can also confirm that this still is an issue. Is there an open ticket anywhere?

**Comment by reneneee** [comment]
I can confirm that this issue is still open. We had a WhatsApp audio message forwarded to a Signal group today. All Android users in the group could play the message. All iPhone users could not.
Converting the Opus file to MP3 and reposting it helped. Everyone was able to play the message, both Android and iPhone users.

**Comment by Ennneerrrgggyyy** [comment]
How can we reopen this ticket?
