### ISSUE TITLE
Can't unblock contact

### ISSUE THREAD

**Issue by HawaiianPizza** [signalapp/Signal-iOS#5776]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't unblock a specific contact on Signal. They're in the same group chat as myself and whenever I send messages in the group chat, they can't see the message. However, I'm able to message them directly with no issues.

I've tried leaving the group and rejoining but to no avail. Same goes for him. We've also tried blocking each other and unblocking, but that also didn't work. 

### Steps to reproduce
Settings > Privacy > Blocked > Contact Name > Click on Unblock > Says contact has been unblocked, but he still appears on the blocked list.

**Actual result:** Contact remains blocked on list, but I can still message them directly.

**Expected result:** I should be able to message them normally in group chat, and they shouldn't be appearing on the block list. 

### Screenshots

https://i.imgur.com/RPajGHn.png

### Device info

**Device**: iPhone XR

**iOS version**: 17.3.1

**Signal version:** 7.2.0.11

### Link to debug log
https://debuglogs.org/ios/7.2.0/2029880b7527584fa1dcf6091c67c4f4ea921ee6eb71701ee7c2faaad02036d5.zip

**Comment by HawaiianPizza** [comment]
I found a solution.

I download Signal on an iPad, added my account there, and then unblocked the contact.

**Comment by invrainbow** [comment]
I have the same issue (on iOS they're in the blocklist, when I tap unblock it says "unblocked" but they're still in the list), except that on desktop, I'm periodically unable to message them. It says "unblock this contact to send a message" even though it does not show that they're blocked. I have to "re-block" and unblock them to send them a message.

This is happening regularly and extremely annoying. Is there a fix?

**Comment by invrainbow** [comment]
It appears to only happen with people I know who were contacts previously. I was able to unblock a couple of random spammers who had messaged me before.

**Comment by invrainbow** [comment]
I just uninstalled and reinstalled Signal on my phone. (Lost all my chat history though.)
