### ISSUE TITLE
Strange square and overflow in conversation header

### ISSUE THREAD

**Issue by pylapp** [signalapp/Signal-iOS#5778]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Given a thread of messages between me and a contact also in other groups
When I go to the top of the thread
Then I saw two kinds of glitches: a square and an overflow 

### Steps to reproduce
- get a thread of messages with someone you have in your contacts and also in common groups 
- go to the top of the thread until the start with the header containing the photo and details about the contact

**Actual result:** There is a lighter vertical rectangle in the phone number area, and also the text about groups which ends outside the background  

**Expected result:** All texts should be in the header of the threads, our outside, and such strange rectangle list not appear 

#### Strange square

![image](https://github.com/signalapp/Signal-iOS/assets/7559007/75544550-8bfd-4016-ae53-c72f8a062cb1)

#### Strange square qnd text outside the header 
![image](https://github.com/signalapp/Signal-iOS/assets/7559007/1223334a-8a0e-438b-8060-068d710f8419)

### Device info

**Device**: iPhone 14 Pro

**iOS version**: 17.4

**Signal version:** 7.2.0.11

**Comment by Miguel-Signal** [comment]
Hi @pylapp 

Could you please write into support@signal.org with a link to your debug logs and reference this github issue?

To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.
