### ISSUE TITLE
Videos that I add to "My Story" have no audio when played back

### ISSUE THREAD

**Issue by azuredusk10** [signalapp/Signal-iOS#5782]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I post a video to "My Story" and then play it back from the "Stories" tab, it doesn't have any audio.

When one of my contacts opens my story on their Android phone, they can hear the video's audio.

### Steps to reproduce
- Add a video to "My story" that contains audio
- Wait for the video to be sent
- Tap on the story you just added to play it back

**Actual result:** The video plays but it has no audio. There is no option to unmute it and the physical volume buttons have no effect.

**Expected result:** The video plays back with audio

### Device info

**Device**: iPhone 11

**iOS version**: 17.3.1

**Signal version:** 7.5.0.7

### Link to debug log

https://debuglogs.org/ios/7.5.0/e2deab9391f68b5e92a2cfeb365d2dd0574577b5e273353e428f4eef833ec847.zip

**Comment by azuredusk10** [comment]
According to a post on the Signal Community forums, Stories don’t play any sound if the phone ringer is off:
https://community.signalusers.org/t/complicated-sound-settings-for-stories/60349/2

This may have been the original issue in this bug report. 

If that’s true, then I didn’t know this was the case and it wasn’t the behaviour I was expecting.

**Comment by erwanor** [comment]
Same thing, it's just a bit odd that having sound or not is controlled "at a distance" by silent mode instead than by a knob in the app like other iOS uxs
