### ISSUE TITLE
Front camera does not allow QR scanning for transfer to new device

### ISSUE THREAD

**Issue by zambetti** [signalapp/Signal-iOS#5785]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

When transferring from an old device to a new device, my old device displays the front-facing "selfie" camera in the UI (in the circle). When positioning the QR code in the circle, it does not initiate the transfer.

### Steps to reproduce

- Initiate "transfer to new device" process
- On old device, use front-facing camera. For my phone, the front-facing camera is used by Signal as default since the main camera is disconnected/not-working.
- Position the QR code in the view as the UI describes.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Nothing happens, transfer does not start

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

QR code is scanned, transfer begins

### Device info

**Device**: iDevice X

iPhone 8

**iOS version**: X.Y.Z

iOS 16

**Signal version:** Z.Y

Latest/current app store version

**Comment by Miguel-Signal** [comment]
Hi @zambetti, sorry to hear you are having trouble with a device transfer. 

Could you please email support@signal.org with debug logs from your devices and reference this GitHub issue?
To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.
