### ISSUE TITLE
Search fails to find many messages despite highlighting them

### ISSUE THREAD

**Issue by maa-x** [signalapp/Signal-iOS#5786]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When searching a conversation on iOS, only the first 256 results are returned. As these are chronological, it means Signal doesn't search past the 256th result (i.e., the most recent matching messages are not included). 
This is particularly problematic when searching for links for example (query: http)

### Steps to reproduce
- search a conversation with a keyword which occurs more than 256 times in the searched conversation (eg: http)
- note that no recent matching items are included in the results

**Actual result:**
Search does not return more than 256 results. 

**Expected result:**
Search returns more than 256 results (or if we're stuck with a single byte, consider flipping the sort to search from the most recent messages). 

### Device info
**Device:** iPhone 12 Pro Max

**iOS version:** 17.4.1 (EDIT: 17.5 as well)

**Signal version:** 7.4.0.9 (EDIT: 7.10 as well)

**Comment by DGrothe-PhD** [comment]
Could not reproduce it
"au" - 375 hits, "und" - 356 hits
iOS: 17.4.1
Signal version: 7.8 (55)

**Comment by maa-x** [comment]
That's helpful, and quite odd indeed. 

Searching for "to" for example, I get 400+ results. 

However, searching for "htt", I only get 256 results, the latest being in 2022 when hundreds of messages were exchanged since with "http" in them. However, this problem isn't limited to links with "http", "re" does the same.

**Comment by DGrothe-PhD** [comment]
Strange that for 'ie' I get 'No results' even if there are a lot.

**Comment by maa-x** [comment]
And I get 8..! But if I scroll up past the 8th, there are dozens and dozens highlighted. How peculiar!

**Comment by DGrothe-PhD** [comment]
![image](https://github.com/signalapp/Signal-iOS/assets/64636863/729ba92c-5c45-42a2-a5a1-fac7926b7412)
So this is absolutely proving that it's a bug.
I am searching for 'ie' in my longest signal thread. Scrolling some weeks back to find lots of hits yellowed but no hits is what it says 🤔

**Comment by maa-x** [comment]
Issue still present in v7.24

**Comment by DGrothe-PhD** [comment]
Still present in 7.25!

**Comment by maa-x** [comment]
I again searched for `http` in a different, also long running, conversation and noticed that it also returns a different and incorrect number of results. 

Interestingly, in one conversation, the most recent result is from September 26 2022. In the other, October 1 2022. 

For "ee": 24/7/10 and 24/7/24. 

However, for "ed", I get 24/6/4 and 24/8/14. 

I have absolutely no idea what's going on..!
