### ISSUE TITLE
After installation an old group picture is shown 

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-iOS#5791]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a new installation and restoring the contact info by providing the PIN all contacts are restored but one group shows an old profile picture. Trying to change the profile picture results in a failure 'group cannot be updated'. Also if an other group member updates the profile picture this is not updated in the app. This is the first time using the IOS app. The previous phone was an Android so the retrieved contact info that was restored through the PIN was provided by the Android app. Not sure if that is related.

### Steps to reproduce
- See description

**Actual result:** After restoring contact data a group contains an old profile picture and cannot be updated.

**Expected result:** After restoring contact data all received contact info contains the latest data.

### Device info

**Device**: iphone13

**iOS version**: 17.4.1

**Signal version:** 7.6.0

### Link to debug log

https://debuglogs.org/ios/7.6.0/d64dded9272a3a5736b07bcb5ccc1ac22adee82af1d0be4d704792a137386864.zip

**Comment by bme13** [comment]
In addition it turns out that messages can be send from this phone to the group however messages are not received. Tried to leave the group but that's still pending. Is there any way to restore this group?

**Comment by lobrau** [comment]
Also experiencing this issue on my iphone. My laptop is getting messages just fine however.

**Comment by matthinc** [comment]
I'm experiencing the same issue. After a fresh install, some groups are completely broken:

- Outdated group name and profile picture
- **No new messages are received on the iPhone** (Linked Desktop app works fine)
- Member list misses members that are definitely in the group

@bme13 I suggest you edit the title of this issue, since it's magnintudes more severe than just the picture.

**Comment by matthinc** [comment]
Attaching my debug logs as well:

https://debuglogs.org/ios/7.8.0/2998c31b185140ea230b1d5e2be24707e8ca132940a2afe1c821a0cd9c734be3.zip

**Comment by lobrau** [comment]
I messaged signal support as well. They said they were aware of this issue and are working on a fix but no timeline could be given.
I do hope there is a resolution soon though as not having half my group convos working is quite annoying.

**Comment by matthinc** [comment]
@lobrau I'm currently leaving all the relevant groups and ask for getting invited again. This seems to "solve" the issue but this clearly has to be fixed. Not receiving messages is one of the most severe bugs in a messenge IMO. Thanks for contacting the support!

**Comment by lobrau** [comment]
Interesting, I'm not able to leave affected groups even. I just get a spinning wheel forever.

**Comment by matthinc** [comment]
I use the deskop app to leave the groups
