### ISSUE TITLE
Transferred data to new phone - App won't open

### ISSUE THREAD

**Issue by rwjack** [signalapp/Signal-iOS#5795]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

No I'm just fascinated how some genius thought it's a good idea to delete the original data without ensuring that the new copy of data is actually fucking valid.

I followed the procedure to do the transfer from an old device, waited an hour for the data to sync, old phone auto deleted everything, and here's what I'm left with:

### Device info

**Device**: iPhone 15 Pro

**iOS version**: 17.4.1

**Signal version:** Can't open the app.

**Comment by rwjack** [comment]
https://github.com/signalapp/Signal-iOS/assets/59068073/c3a59d9a-b33c-458c-8ac5-65c5a5a77467

**Comment by rwjack** [comment]
Old phone version was 7.6.1, new one was 7.8 - Automatically downloaded the latest version from the app store.

**Comment by rwjack** [comment]
Tried logging in on my old phone again, no messages there, but judging by the size of the data on my new phone, the data is surely there, I just cannot open the app.

**Comment by SebastianMauchly** [comment]
Same exact sequence for me. Transferred from old XS iOS 15.4.1, to a 15 Pro, iOS 17.4.1. Updated to latest Signal on both phones.

**Comment by santjaume15** [comment]
Same exact results here. Changed from 11 to 15 Pro, both iOS 17.4.1 Data wiped on 11, transferred 6 GB to 15 Pro, but inaccessible. Wants to do a fresh install (asks for my phone number) when Signal is opened via App Store.

**Comment by rwjack** [comment]
I made my peace with losing the data and reinstalled. Quoting @fiveangle from the other issue linked above:

> "They [devs] don't think most iOS users would be familiar with having to generate separate backup files from within each app, copy around 30-digit passphrases, and then have to move the backup files around and restore them manually."

> Yet Android users are? Do they even have a clue what the bulk of Android users are? They are not the "Power Users" the devs arrogantly think they are. They are the majority of people on earth who can only afford the free subsidized smartphone available though their carrier. They are more often than not the poor and the uneducated, yet somehow these masses are more capable than iPhone users?

> Call a spade a spade; the Devs are condescending arrogant supercilious curmudgeons.

This is a major league fuck up, so unless one of the devs takes charge on fixing the important issues, we're SOL.

**Comment by duke7901** [comment]
No news on that?
Got one (!) reply from the support. 
That‘s it. No assistance at all. No feedback…
It‘s a shame that there isn‘t any other way to backup data or at least single chats. 
I do have very important and sensitive business chats which I even can‘t see/backup/restore!

**Comment by Smaku13** [comment]
bump for this topic... version 7.10 still affected.
1. Transfer data from iPhone 13 mini to 15 about 1GB took 15-20 min.
2. Old device deactivated, so no more data available on that one. 
3. Signal on new device won't start exact same behaviour as on attached movie.

Off-loading signal (without data removal) and installing it again didn't solve problem.

**Comment by rwjack** [comment]
@cloudgreen Go to settings > storage > signal > offload

I did the same thing then, no fix.

They never replied to my crash logs. I suppose they were too busy spending donation money and implementing new shitcoins into the app.

**Comment by Smaku13** [comment]
> > Off-loading signal (without data removal) and installing it again didn't solve problem.
> 
> How do you uninstall Signal without data removal?
> 
> Btw, support have been informed about the same issue in #5796 and I sent them a crash log. They are looking into it.

it is possible to remove app without data loss in iOS.

![image](https://github.com/signalapp/Signal-iOS/assets/169709107/95caafc7-0acb-4cf9-b1b7-33068471424d)

**Comment by nvsystems** [comment]
This bug has cost me my entire history. Deleting the source without asking/checking if the destination actually works is a very foolish decision. I’m not sure if offloading would have helped, my data is already gone for good 😢

**Comment by tohoku** [comment]
Same here. I upgraded to a new iPhone, the transfer from the old to the new phone was "successful". But the app crashed immediately when launching it on the new phone. That version was 7.10.  After upgrading to 7.11, everything works as expected. (The transferred data is visible.)
