### ISSUE TITLE
Cannot read group messages from group members

### ISSUE THREAD

**Issue by Buriburiki** [signalapp/Signal-iOS#5799]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I am not able to see message from other ppl in the group after I reset my account as I forget the pin. But they could see my message and I could see them typing, but not the message.

### Steps to reproduce
- my fds sent a message to group 
- I cannot receive the msg but I can see them typing
- But I when I sent a message 
- They all Can see

**Actual result:**  I cannot receive the msg from my friends in group chat

**Expected result:**I could receive msg from my friends in group chat

### Device info

**Device**: iPhone 13 Pro 

**iOS version**: 17.4.1

**Signal version:** 7.9(82)

### Link to debug log

https://debuglogs.org/ios/7.9.0/9c9ed51c4a969bb66ae8f35f983cb7202d4523335ba82d4e26c33f4ec45f51e7.zip

**Comment by NFM-8** [comment]
I have observed this first over a year ago, and now again during last week. Perhaps linked devices during re-register is triggering this, as linked devices still receive messages.

Interesting part (hopefully) of a debug log from desktop when sending failed to one member (1714902967904 is timestamp of the message and [REDACTED]1ad is the member that failed to receive the message on the primary iOS client):

INFO  2024-05-05T09:56:07.939Z conversation job queue, job ID [REDACTED]417, attempt 1: sending group message
INFO  2024-05-05T09:56:07.939Z Sending a message with 0 mentions, 0 placeholders, and 0 other ranges
INFO  2024-05-05T09:56:07.939Z sendToGroupViaSenderKey/groupv2([REDACTED]a+I=): Starting 1714902967904, recursion count 0...
INFO  2024-05-05T09:56:07.939Z getSenderKeyExpireDuration: using expire duration of 1209600000
INFO  2024-05-05T09:56:07.939Z sendToGroupViaSenderKey/groupv2([REDACTED]a+I=): 5 accounts for sender key (8 devices), 0 accounts for normal send (0 devices)
INFO  2024-05-05T09:56:07.940Z Successfully fetched sender key (cache hit): [REDACTED]1ad:[REDACTED]1ad.2--[REDACTED]f8c
INFO  2024-05-05T09:56:07.940Z commitZoneChanges(saveSenderKey): pending sender keys 1, pending sessions 0, pending unprocessed 0
INFO  2024-05-05T09:56:07.941Z markConversationRead(groupv2([REDACTED]a+I=)) {"newestSentAt":1714902967904,"newestUnreadAt":1714808379762,"unreadMessages":0,"unreadReactions":0}
INFO  2024-05-05T09:56:07.942Z Sender certificate service found a valid no-E164 certificate in storage; skipping fetch
INFO  2024-05-05T09:56:07.942Z PUT (WS) https://chat.signal.org/v1/messages/multi_recipient?ts=1714902967904&online=false&urgent=true&story=false (unauth)
INFO  2024-05-05T09:56:08.078Z PUT (WS) https://chat.signal.org/v1/messages/multi_recipient?ts=1714902967904&online=false&urgent=true&story=false (unauth) 200 Success
INFO  2024-05-05T09:56:08.080Z conversation.queueJob(groupv2([REDACTED]a+I=), conversationQueue/sendNormalMessage): took 141ms
WARN  2024-05-05T09:56:08.083Z lookupOrCreate: Called with neither e164 nor serviceId! reason: MessageModel.getSenderIdentifier
WARN  2024-05-05T09:56:08.083Z lookupOrCreate: Called with neither e164 nor serviceId! reason: MessageModel.getSenderIdentifier
INFO  2024-05-05T09:56:08.089Z Message.tsx: Rendered 'send complete' for message 1714902967904; took 185ms
INFO  2024-05-05T09:56:08.097Z enqueueSessionJob(603): queuing task doSendMessage([REDACTED]1ad:[REDACTED]1ad.4, 1714902967904), waited 0ms
INFO  2024-05-05T09:56:08.097Z enqueueSessionJob(603): running task doSendMessage([REDACTED]1ad:[REDACTED]1ad.4, 1714902967904), waited 0ms
INFO  2024-05-05T09:56:08.097Z enqueueSessionJob(604): queuing task doSendMessage([REDACTED]1ad:[REDACTED]1ad.3, 1714902967904), waited 0ms
INFO  2024-05-05T09:56:08.097Z enqueueSessionJob(604): running task doSendMessage([REDACTED]1ad:[REDACTED]1ad.3, 1714902967904), waited 0ms
INFO  2024-05-05T09:56:08.097Z enqueueSessionJob(605): queuing task doSendMessage([REDACTED]1ad:[REDACTED]1ad.1, 1714902967904), waited 0ms
INFO  2024-05-05T09:56:08.097Z enqueueSessionJob(605): running task doSendMessage([REDACTED]1ad:[REDACTED]1ad.1, 1714902967904), waited 0ms
INFO  2024-05-05T09:56:08.098Z commitZoneChanges(storeSession): pending sender keys 0, pending sessions 1, pending unprocessed 0
INFO  2024-05-05T09:56:08.098Z commitZoneChanges(storeSession): pending sender keys 0, pending sessions 1, pending unprocessed 0
INFO  2024-05-05T09:56:08.098Z commitZoneChanges(storeSession): pending sender keys 0, pending sessions 1, pending unprocessed 0
INFO  2024-05-05T09:56:08.101Z PUT (WS) https://chat.signal.org/v1/messages/[REDACTED]1ad?story=false
INFO  2024-05-05T09:56:08.249Z PUT (WS) https://chat.signal.org/v1/messages/[REDACTED]1ad?story=false 200 Success
WARN  2024-05-05T09:56:08.253Z lookupOrCreate: Called with neither e164 nor serviceId! reason: MessageModel.getSenderIdentifier
WARN  2024-05-05T09:56:08.253Z lookupOrCreate: Called with neither e164 nor serviceId! reason: MessageModel.getSenderIdentifier

**Comment by Gajusbonus** [comment]
Some problem here. I send a group message and several people in this group text me, they didn't receive the message.
This happens over several groups.
