### ISSUE TITLE
Voice message playback not working; skipping results in crash

### ISSUE THREAD

**Issue by ffffabian** [signalapp/Signal-iOS#5806]
### Bug description
Voice message playback not working; when draggin the playback indicator Signal crashes

### Steps to reproduce
- open Signal
- try to play voice message
- hold playback indicator and try to skip forward
- release playback indicator 
- Signal crashes

**Actual result:** 
no audio is played & app crashes

**Expected result:**
playback of voice message & being able to skip forward 

### Device info

**Device**: iPhone 13 mini 

**iOS version**: 17.4.1

**Signal version:** 7.11 (95)

### Link to debug log
https://debuglogs.org/ios/7.11.0/3534ada50274f43e4d24c9a2b20698124d922affdb5b640d55d9fc6384fe55c4.zip

**Comment by Miguel-Signal** [comment]
Hi @ffffabian,

Thanks for reporting this. Could you please email your iOS crash log to support@signal.org and reference this Github issue?

Go to iOS Settings > Privacy (& Security) > Analytics (& Improvements) > Analytics Data.
Locate and select the .ips crash log for Signal. **The logs will likely be named in the format: Signal(DateTime)(DeviceName).ips, but please also ignore logs that have 'wakeups' in the file name**.
Tap the Share icon in the top corner. Share the entire .ips file.

This information is also on the support page here: https://support.signal.org/hc/articles/360007318591

**Comment by ffffabian** [comment]
Thanks @miguel-signal, the newest beta 7.11 (105) seemed to have fixed this. I will still email the iOS cash log.
