### ISSUE TITLE
Cannot share files or voice messages

### ISSUE THREAD

**Issue by jandamm** [signalapp/Signal-iOS#5808]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not able to share files or voice messages via the native share sheet.

### Steps to reproduce
- Select any file you sent or received
- Hold the "message" of that file
- The UIMenu is opening but no `Share` entry.

**Actual result:** There is no `Share` in the menu.

**Expected result:** There is a `Share` in the menu as was with 7.10 and earlier.

### Screenshots

![image](https://github.com/signalapp/Signal-iOS/assets/5963139/0e997695-0df1-48c2-bb0a-103a61aa27c6)

### Device info

**Device**: iPhone 14 Pro

**iOS version**: 17.5.0

**Signal version:** 7.11

**Comment by abjbhat** [comment]
I can also confirm that this bug is happening in v7.11 of the app. I can reproduce this on iOS and iPadOS devices running iOS 17.5.1

**Comment by edsimpsons83** [comment]
Getting this issue as well. Running latest iOS and Signal.

**Comment by ViB2323** [comment]
Also having the same issue 
(iPhone 13; v17.4.1; Signal v7.11 and 13)

Any word on this yet?

**Comment by johnwittacre** [comment]
Just received the new Signal v7.13 and still getting this issue.

**Comment by jandamm** [comment]
It's fixed for me with `7.15` 👍
