### ISSUE TITLE
When accepting a call via CallKit sometimes there is no sound

### ISSUE THREAD

**Issue by Cheesooo** [signalapp/Signal-iOS#5819]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a Signal Call is accepted via the CallKit (Apple Call Screen thing) the sometimes there is no audio.
The other side can hear you. But you can't hear them. Video calls have the same issue.
Only when restarting the call, the audio comes back.

### Steps to reproduce
- Let somebody call you via Signal Audio/Video call
- Accept the call while the phone is locked over the Apple CallKit screen

**Actual result:** sometimes - not always there will be no sound

**Expected result:** audio should always connect

### Device info

**Device**: iPhone 15 pro max

**iOS version**:  17.5.1

**Signal version:** 7.14 (140)

**Comment by Cheesooo** [comment]
Issue still happens sometimes on Version 7.26(301) IOS 17.6.1

**Comment by clemlesne** [comment]
Seems a duplicate from https://github.com/signalapp/Signal-iOS/issues/5222.
