### ISSUE TITLE
Inconsistent file attachment UI between iOS and Android

### ISSUE THREAD

**Issue by sailbird** [signalapp/Signal-iOS#5826]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Feel free to say this isn't a bug but I don't know where else to report it and it has resulted in a lot of wasted time with chat peers. iOS has the "+" for attaching files or images on the lower left and Android has it on the lower right (and in blue). This leads to miscommunication when someone new to Signal asks how to attach a file. "How can you not see the blue plus sign? All my other (Android) friends can see it!"

### Steps to reproduce
Look at the bottom of the single-peer chat interface on iOS and Android.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Everything works fine but it's annoying and causes confusion for some users.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Just choose one way to render the "+" and make it consistent across both builds.

**Comment by keshawkk** [comment]
This seems very obvious difference. More like a design choice for iOS system.
