### ISSUE TITLE
LibMobileCoin report:Undefined symbol: _mc_string_free

### ISSUE THREAD

**Issue by Aviicii** [signalapp/Signal-iOS#5829]
<img width="273" alt="image" src="https://github.com/signalapp/Signal-iOS/assets/17735397/dfb90553-e544-4127-b904-00dbd9121fc4">

**Comment by Bardashevsky** [comment]
I changed pod file to: 
pod 'LibMobileCoin/CoreHTTP', git: 'https://github.com/signalapp/libmobilecoin-ios-artifacts', :commit => '5cd4f39a24d06708d1c19aced8384740689d7f61'
pod 'MobileCoin/CoreHTTP', git: 'https://github.com/mobilecoinofficial/MobileCoin-Swift', tag: 'v5.0.0' 
Error did disappear!
