### ISSUE TITLE
Captcha limbo (Cannot send DM upon successful captcha puzzle)

### ISSUE THREAD

**Issue by alltheseas** [signalapp/Signal-iOS#5840]
- [x] I have searched open and closed issues for duplicates (there is a :hankey: issue with incomplete details - I recommend to delete this one: https://github.com/signalapp/Signal-iOS/issues/5800)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Successful captcha verification on invite 'DM me on Signal' does not result in a successfuly sent DM.

### Steps to reproduce
- click on DM link (https://signal.me/etc...)
- write message in signal
- hit send
- proceed to captcha puzzle
- successfully solve captcha puzzle
- return to DMs view, with "verification complete" toast

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- DM is *not* sent.
-  I remain in unsent DM limbo ("send paused" with exclamation mark)
- Signal keeps asking me to captcha solve perpetually 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Automatically send DM upon successful verification. 
- Do not prompt me to keep submitting captchas perpetually, upon successful captcha submission.

### Screenshots
![sigfail](https://github.com/user-attachments/assets/5b36a41d-304e-4c2e-b927-fb2fe80da6f4)

### Device info

**Device**: 13 mini
**iOS version**: 17.5.1
**Signal version:** 7.19.1 (208)

### Link to debug log
https://debuglogs.org/ios/7.19.1/17991851722c5cb83f9bb06aba5d122ebc8bd4964b71d52ccca873191294c756.zip

**Comment by sanziodeurbino** [comment]
I have been experiencing identical and persistent issues along the same lines as @alltheseas across two different iOS devices for several months now. 

Device info:

Device: iPhone 12
iOS version: 17.6.1
Signal version: 7.24 (270)

![signal-2024-08-22-154050_002](https://github.com/user-attachments/assets/f0dd9ec7-a955-4bab-802e-4a93eed101cc)
