### ISSUE TITLE
Status message spoofs contact verification

### ISSUE THREAD

**Issue by ethrgeist** [signalapp/Signal-iOS#5847]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

At multiple places in the UI a personal status set to `✓ Verified` looks near identical the contact verified mark.

HTML Char `&#10003;` // [Source](https://altcodeunicode.com/alt-codes-check-mark-cross-x-mark-ballot-box-symbols/)

### Steps to reproduce
- Set the status on iOS to `✓ Verified`
- Look at places where the status is displayed

![grafik](https://github.com/user-attachments/assets/6586f6e2-aa97-4587-b29b-25a7d7769253)

**Actual result:**

It looks a lot like people have verified my contact on their end, while they have not, this might help imposters or scammers to look trustworthy.

**Expected result:**

There is a clear distinction between the verified mark from the chat client and user controlled input from contacts.

In a group members list the verified mark even replaces the status in the same line if contact is verified with no notice or anything that could help to spot this simple manipulation.

This security feature should not be so easy to spoof.

### Screenshots
For reference, a verified friend of mine in a shared group looks like this.

![grafik](https://github.com/user-attachments/assets/be8b9e66-3d6b-4ce5-8788-6fcddc44dece)

After i set my status to `✓ Verified`, from the perspective of another account, it looks like they verified my account, when in fact, it's just my status message.

![grafik](https://github.com/user-attachments/assets/ae272991-752e-4efb-bf08-d0d762e79a3b)

This is what my profile looks like, if some set my account to verified, could you tell which `✓ Verified` is the one from the client and which is from my status? I sure could not.

![grafik](https://github.com/user-attachments/assets/9269899c-fae1-4499-a9f3-5a3771e3d1cd)

The details page makes a small difference between my status and the actual verified, but it's not great.

![grafik](https://github.com/user-attachments/assets/6614dbf0-50d9-47c9-88c6-311bf968d728)

But it get's worse, when a contact looks at my profile, which has not been set to verified by them, now it looks like i am verified to them.

![grafik](https://github.com/user-attachments/assets/5648bd1d-aa21-4cc7-8ddb-74042bfff166)

Details page is no help to figure this out..., the pen could mean anything here.

![grafik](https://github.com/user-attachments/assets/a4894112-7aa2-4640-9ab7-95be5cbdc649)

### Device info
**Device**: iPhone 12 Pro

**iOS version**: 17.6.0

**Signal version:** 7.22 (246)

### Link to debug log
No debug since this is UI only

**Comment by elaine-signal** [comment]
Thanks for pointing this out! We've updated the verified icon to be unique. 474c8c2ed627e854ca9b4ea276f0a03e71ce7c56
