### ISSUE TITLE
Media overview - Files 

### ISSUE THREAD

**Issue by Janikson9** [signalapp/Signal-iOS#5852]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

It would be nice if files were also displayed in the media overview.

Currently only images, videos and gifs can be displayed.

### Steps to reproduce
- Go to media overview in the chat

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![IMG_4433](https://github.com/user-attachments/assets/b1480d94-21f1-4529-b540-b0064bc5b288)

### Device info

**Device**: iPhone 16

**iOS version**: 17.6.1

**Signal version:** 7.24

**Comment by darkCavalier11** [comment]
@Janikson9 When you refer to files, do you mean docs, cause audios and voices are coming under category of files. I guess its more on the line of pdf, docx files.

**Comment by Janikson9** [comment]
Yes exactly, I mean pdf, docx files
