### ISSUE TITLE
Voice messages are not loading

### ISSUE THREAD

**Issue by SchwatteDuevel** [signalapp/Signal-iOS#5862]
Incoming voice messages are not loading. I can see the voice message in the chat with date/time of arrival. But the loading circle never stops and the length of the voice message remains on 0:00.

I think (i am not sure!) it depends on the length of the voice message, sometimes it works with shorter messages (1-2 min.)

I have closed the app, deleted the chat and restarted the phone.

No problems on Signal Desktop, that works fine.

iOS 17.6.1, Signal 7.26

![IMG_1487](https://github.com/user-attachments/assets/a43ed8bd-1270-49b5-a2bc-a2c0008d48b5)

**Comment by one-adam-nolan** [comment]
Same issue, here. It seems to have started over the weekend for myself and another friend. 

I have a group chat that is exclusively audio messages- it happens on my  iPhone 11 Pro and the other member of the chat with an iPhone that is a bit older than the 11 pro.

IIRC- I just upgraded to the latest OS, not sure if that’s a factor 🤷

**Comment by leetipton** [comment]
Same issue here on an Iphone X, with a 1.5mb voice message. I got a smaller audio message last night okay.

**Comment by SchwatteDuevel** [comment]
After some testing I think it depends on the length of the voice message. Till now, all messages < 5.30/6.00 min. are ok, all voice messages greater than around 5.30/6.00 min. are causing this issue.

One more friend has the same issue.

**Comment by Will-Signal** [comment]
Hello, 

Please update Signal to the latest version v7.26.1.321, as it contains fixes to a bug that caused performance issues. Visit https://signal.org/install on your phone to be directed to the store page where you can update.

If the issue remains after updating, please contact us from within the app: Go to Signal Settings (profile) > Help > Contact us. Make sure to include a debug log and github number.

**Comment by SchwatteDuevel** [comment]
Thanks for your response. Issue seems to be fixed: old messages and new messages are now loaded. Thanks!
