### ISSUE TITLE
The developer has removed this app from the App Store

### ISSUE THREAD

**Issue by qingfengfenga** [signalapp/Signal-iOS#5868]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The developer has removed this app from the App Store

Unable to update app, installed apps cannot be opened, black screen

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

### Link to debug log

![c6f5ab7a9966543198b833818950236](https://github.com/user-attachments/assets/a4271037-505f-4f05-b13c-69b06979c4a5)

![33bfc46e7b3cab988f4e543f0f83575](https://github.com/user-attachments/assets/9eb7afbf-72f6-428d-9ce5-f5f87db13186)

**Comment by masterbruce99** [comment]
Is this real? Or it may be geo location. Try using a vpn

**Comment by qingfengfenga** [comment]
> Is this real? Or it may be geo location. Try using a vpn

After uninstalling the old app, reinstalling it worked fine. It may be because I haven't updated it for too long. Thank you
