### ISSUE TITLE
YouTube link previews are not loading on iOS, Android, or the macOS app.

### ISSUE THREAD

**Issue by quad-u** [signalapp/Signal-iOS#5874]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
YouTube link previews are not loading on iOS, Android, or the macOS app. 
This was previously working properly as recently as 2024-08-22.

### Related issue:
https://github.com/signalapp/Signal-Android/issues/9086

### Steps to reproduce
- Open Signal
- Paste/type a youtube.com or youtu.be link
- Send
- Observe the YouTube "preview" that only scrapes the boilerplate text for YouTube (below)
<img width="400" alt="image" src="https://github.com/user-attachments/assets/b1320a1d-b042-434c-b22c-3ab120e423ec">

**Actual result:** 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/b1320a1d-b042-434c-b22c-3ab120e423ec">
#### Boilerplate text from YouTube service: 
 **- YouTube**
Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube. 

**Expected result:** Something along these lines:
![IMG_7F8CE38F9D35-1](https://github.com/user-attachments/assets/f314c4dd-5684-476a-9e0c-87298a02147c)

### Device info

**Device**: iPhone 15 Pro Max

**iOS version**: 18.0

**Signal version:** 7.28 (328)

**Comment by Kingwad** [comment]
Same issue with NYTimes mini crossword. Here is what it looked like previously:

![IMG_3380](https://github.com/user-attachments/assets/e019c6b2-1d86-49e1-95bb-ac470d298bc0)

and here is what it looks like today:

![IMG_3381](https://github.com/user-attachments/assets/863d4ca8-5581-45b5-acef-13a744187dfa)

**Comment by donutlookaway** [comment]
this is still happening for me today. specifically with youtube

**Comment by quad-u** [comment]
I’ve discovered that using a VPN that dynamically assigns IP’s will cause this to occur. A VPN with a static IP will allow content to be thumbnailed.

**Comment by asdfmonster261** [comment]
Same problem has been happening to me for a while and usually the only option is to change my IP address. The problem is I can't always get my ISP to change my IP. Signal is the only app this happens on.

**Comment by jjazar** [comment]
> I’ve discovered that using a VPN that dynamically assigns IP’s will cause this to occur. A VPN with a static IP will allow content to be thumbnailed.

Interesting, but my link preview don't load even on a self-hosted VPS VPN with a static IP.
