### ISSUE TITLE
Deactivate calls 

### ISSUE THREAD

**Issue by Dabendorf** [signalapp/Signal-iOS#5880]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is not possible to to deactivate calls in signal. I do not want anybody to ring me and I sometimes click on the ringing button by accident

### Steps to reproduce
- open signal and search for the deactivation button for calls. It does not exist :( 

**Actual result:** People ring me. I pocketring them

**Expected result:** It is possible to deactivate this 

### Device info

**Device**: iPhone 16

**iOS version**: 18.0.0

**Signal version:** 7.29

**Comment by max-signal** [comment]
Please discuss feature requests on the [community forum](https://community.signalusers.org/c/feature-requests/ios-feature-requests/19).
