### ISSUE TITLE
Doesn't work on Apple Macbook M1 Silicone.

### ISSUE THREAD

**Issue by mr-nabeel** [signalapp/Signal-iOS#5885]
### Bug description

I'm trying to run Signal iOS on my MacBook Air M1, but I'm encountering several errors in SignalServiceKit, as shown in the attached screenshot. I've followed all the commands listed in the BUILDING.md file.

Are there any specific steps needed to run this code on a MacBook with M1 silicon?

### Screenshots
<img width="1400" alt="Screenshot 2024-10-01 at 12 45 50 AM" src="https://github.com/user-attachments/assets/7abda701-e4fd-4f74-be8f-c25c4970c5e8">

### Device info
**Device**: IPhone 15 Pro

**iOS version**: 17.0

**Signal version:** 7.30

**Comment by max-signal** [comment]
Signal requires Xcode 16 to build successfully.
