### ISSUE TITLE
Improved Group Management

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#607]
- [ ]  Drop image copy in thread model.
- [ ] Updates can only contain one piece of info for now. This is a problem because a user could change title name and add someone and only one of these actions would be displayed.
- [ ] Display adapted warnings when group update messages are received from someone who's not part of a group.

**Comment by abolishme** [comment]
Would this include improvements to the UI of building a new group conversation? Originally I had a design that combined both individual or group conversations into a single "new conversation" flow. @FredericJacobs, let me know if you think that belongs in this release or a subsequent one.

**Comment by FredericJacobs** [comment]
We could start discussing that. But not for 2.0.1, more like 2.1 or something. Bugfixes first.

**Comment by pjctech** [comment]
+1

**Comment by michaelkirk** [comment]
@pjctech - don't bump issues. Use github's "reaction" feature if you want to voice support for an issue.

**Comment by FredericJacobs** [comment]
This is by far no longer relevant
