### ISSUE TITLE
When opening a thread, I should be at the oldest unread message, instead of the bottom of the thread.

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [signalapp/Signal-iOS#638]
Thank you for releasing the TextSecure protocoll to iOS for the public! 

In group chats the scrolling behavior is unfavorable in my opinion. When I reopen a group chat after absence it is always scrolled all the way down to the most recent message. So in a group chat with a lot going on I have to manually scroll up and find the point where I left the chat each time.

Could this be fixed easily? For most of my friends this is the main show stopper that keeps us from moving our group from whatsapp.

**Comment by FredericJacobs** [comment]
Duplicate of #769

**Comment by diegode** [comment]
@FredericJacobs i think that this is a somewhat different issue. The other one is about automatic scroll down on open conversations, and this one about opening a conversation showing the last seen message.

**Comment by aaa11235** [comment]
@FredericJacobs — I agree that this is a different issue, and in my experience as a Signal evangelist, this is a significant issue keeping people from switching over from WhatsApp.

**Comment by michaelkirk-signal** [comment]
This behavior was implemented long ago.
