### ISSUE TITLE
missing feature: search conversation(s)

### ISSUE THREAD

**Issue by vv01f** [signalapp/Signal-iOS#646]
I'd expect a search field both on conversations overview and on single conversation to find contents later.

**Comment by lazlolazlolazlo** [comment]
This is a really important enhancement. I think a lot of people miss search functionality, especially in large group chats.

**Comment by pjctech** [comment]
I really miss the search feature!

**Comment by michaelkirk** [comment]
@pjctech stop bumping issues. Each time you do every subscriber to the repository gets an email which adds nothing to the discussion.

**Comment by michaelkirk-signal** [comment]
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-
