### ISSUE TITLE
No way to highlight a user as active/not active or unlist a user based on long inactivity

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#664]
I believe there should be a way to visually differentiate users with long inactivity from people who are active based on when they were last connected to the servers.

I have several friends who no longer used the application (TextSecure+RedPhone) 8 months ago, and never returned again  and yet they still remain active, others who had Signal 1.0 on their device which was stolen and yet when i call them i hear it rings from my side although their phone is off and they won't install Signal without me installing it on new phones... others who had TextSecure installed and when i send them a message it appears "light blue"... showing it was not delivered.

One of the main issues i have difficulty using iMessage is not being sure this person has an iOS device thus having iMessage, so it automatically makes me consider iMessage should not be the default communication method, i think you are hitting a similar problem but in a different way, users appearing to be "Active" but they might have already uninstalled the application long time ago and the only way to verify is through trial and error.

**Comment by TheStash** [comment]
Here is for example how Telegram implements "account deletion" through giving user a choice to set the period after which his account is deleted:

![img_3164](https://cloud.githubusercontent.com/assets/11326414/6504122/fc6057aa-c333-11e4-8069-a3a8c64cec86.PNG)

**Comment by pfctdayelise** [comment]
somewhat related https://github.com/signalapp/Signal-Android/issues/8689
