### ISSUE TITLE
Enable searching for a contact while creating a group

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#669]
To add contacts to a group conversation, you have to scroll down your contact list, i believe it would be much easier if you could search for contacts and mark them for joining the group.

**Comment by FredericJacobs** [comment]
That workflow is going to be enhanced in 2.1.

**Comment by ericmeltzer** [comment]
+1 making groups is a huge hassle without a search

**Comment by ericmeltzer** [comment]
Bumping this, this remains a very bad experience and a big impediment to using signal for groupchat

**Comment by denver-s** [comment]
As of 2.38.1.2, you still have to choose contacts from a list without beign able to search through it.

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Comment by girving** [comment]
Am I correct in assuming that none of the existing feature requests were ported over, including this one?

**Comment by michaelkirk-signal** [comment]
We did not create a forum topic for each pre-existing feature request. One of the advantages of the forum is that it facilitates discussion at a higher level, and can include discussion across apps. 

There's a higher-level discussion about group UI here: https://community.signalusers.org/t/improving-signal-group-chats/979 which might be a good place to get involved.
