### ISSUE TITLE
Not listing all members of Group

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#679]
a Signal user is not listed in the list of group members which is inconsistent with the Android implementation.

**Comment by FredericJacobs** [comment]
Does he get messages?

**Comment by TheStash** [comment]
Yes he does

**Comment by christophhagen** [comment]
Similar problem:

Two signal users missing in group member list on my friends device (iOS, Signal 2.7.1).
Correct number is 12, but showing only 10. A group update by me (through changing the group picture) resolved the issue.

There are more problems with this group, I'll update this post once I created or found similar issues
