### ISSUE TITLE
Scrolling exposes on-screen keyboard even when using external keyboard

### ISSUE THREAD

**Issue by askielboe** [signalapp/Signal-iOS#683]
I'm using Signal on my iPad with an external (bluetooth) keyboard. After sending a message in a conversation, if you scroll up in the message view, the on-screen keyboard is displayed.

The on-screen keyboard should never show when using an external keyboard.

Steps to reproduce:
1. Connect external keyboard to iOS device.
2. Send a message.
3. Scroll up in the message view (actually any direction works).
4. The on-screen keyboard is displayed (this is a bug).

iOS: 8.1.3
Signal: 2.0

**Comment by Imperiopolis-Signal** [comment]
This should no longer happen in the 3.0 beta
