### ISSUE TITLE
URL Scheme

### ISSUE THREAD

**Issue by claesjacobsson** [signalapp/Signal-iOS#706]
Any plans on implementing a URL scheme for contacting people from other app? Would be great. 

sgnl://call/[number]
sgnl://message/[number]

Or even better, if it was to include callbacks, for example using the http://x-callback-url.com/ spec. 

sgnl://x-callback-url/call?
   x-success=sourceapp://x-callback-url/callSuccess&
   x-source=SourceApp&
   x-error=sourceapp://x-callback-url/callError&
   number=[number]

sgnl://x-callback-url/message?
   x-success=sourceapp://x-callback-url/messageSuccess&
   x-source=SourceApp&
   x-error=sourceapp://x-callback-url/messageError&
   number=[number]

**Comment by lode** [comment]
I'm curious about this as well.
We would like to help our users to become more privacy-minded and are writing about it. When sharing the article, our users can share via all kinds of media, of which WhatsApp is one. It would be great to offer them to share via Signal as well.

**Comment by stephenlindauer** [comment]
I would love to see a feature like this as well. We need a way to be able to promote Signal in a website or email signature. Maybe have the ability to contact without giving out my telephone number as well via some other unique ID or username?

**Comment by MattDelmarter** [comment]
Would be good to be able to specify the actual message in the URL scheme as well. 

/message/[number/[text/

**Comment by MattDelmarter** [comment]
This is an example similar to Telegram 

Please allow the URL to include the actual text to send to the specified number.

signl://msg?text=Hi&to=+1555999

**Comment by hboettger** [comment]
This would be great together with the iOS workflow app. Enabling to use Signal as default in many situations.

**Comment by HaBaLeS** [comment]
Any news on this? I would also love to be able to Trigger a call in Signal from a 3rd party App

**Comment by ameesme** [comment]
Also very much interested in this. Telegram also offers a nice share-page, preventing users from hitting an unknown URL-scheme error when they don't have the app installed.

[Example](https://telegram.me/share/url?url=https://example.com/&text=Test%20url)

**Comment by conoro** [comment]
Big 👍 for this. Specifically "Add me on Signal" in email sig. Would help drive adoption too.

**Comment by tomj** [comment]
Please note that as of iOS 9 this _could_ now be implemented as an [iOS Universal Link](https://developer.apple.com/ios/universal-links/) as compared to the [Custom URL Scheme](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app) described above.

So in the case of Signal, the link would simply be to `https://signal.org/call/[number]` with the link handled gracefully on the website for if a user doesn't have the app installed (in this case likely redirecting to an installation link).

**Note:** I can't even begin to imagine the security considerations for implementing a Universal Link in the context of the overall Signal iOS app (I'm only cursorily familiar with the architecture) but am merely pointing out how it could be implemented in the current version of iOS.  There are a couple of attack vectors for intercepting custom URL scheme calls if I remember correctly, in addition to custom schemes being an attack vector for bad actors to provide malicious links (Apple even [say as much](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app) on the documentation).

**Comment by bikemule** [comment]
This list of iOS x-callback-urls lists Signal: https://github.com/bhagyas/app-urls I assume this is incorrect?

**Comment by leipert** [comment]
@bikemule Seems like it is used for adding Sticker packs and Verifying devices:
﻿https://github.com/signalapp/Signal-iOS/blob/e76583ac7d521e32f5de8ba4001f1847dea19c6e/Signal/src/AppDelegate.m#L540-L555

**Comment by jasonprado** [comment]
Is this feature not implemented due to the difficulty of doing so securely, or is it just not done yet? I'd be interested in attempting to contribute it if it's desired by the maintainers.

**Comment by KlemensStrasser** [comment]
Another 👍 for this. We and our users would love to see an integration of Signal in our app Cardhop, which would be possible with through the URL scheme

**Comment by ChaseHall** [comment]
Another +1, would love to add a direct link to my resume as my number I'm using for signal doesn't accept SMS.

**Comment by NSCoder** [comment]
Are pull requests welcome for this issue?

**Comment by saizai** [comment]
@NSCoder Aren't they always? 😉

**Comment by joeinnes** [comment]
I see it's been nearly 5 years since this was initially requested - are we getting any closer to this now with the group links and stickers etc?

Would love to see this!

**Comment by KaiOelfke** [comment]
I make a [contact manager app](https://apps.apple.com/app/id1481868897) for keeping in touch. It has a contact method feature that opens directly the conversation in a messaging app like Signal. Several customers (including myself) want Signal support here. But I need universal links or an URL scheme for this.

Ideally, initiating a call and passing a text message as parameter would be supported as well.

There's almost no communication app, which doesn't support this. It enables many use cases.

**Comment by Tsjippy** [comment]
+1 for this

**Comment by camxcube** [comment]
+1 for this too!

**Comment by ThirupathiRaoM** [comment]
Hi 
Hope you are doing great;
i am try to Open App Via schema it is Opening But I need to Go to Exact Contact To Send A message to Particular Contact When tried different Ways I am Only Opening The App Not the Particular Contact Please Help Me to Solve this issue  
Thanks & Regads
IOS Developer

**Comment by ThirupathiRaoM** [comment]
> This is an example similar to Telegram
> 
> Please allow the URL to include the actual text to send to the specified number.
> 
> signl://msg?text=Hi&to=+1555999

Hi 
Hope you are doing great 
i used same Way In My Project but it is not opening the Particular contact  for chat option
"sgnl://msg?text=Hi&to=+1555999" this is opening the App

**Comment by de1mat** [comment]
> > This is an example similar to Telegram
> 
> > 
> 
> > Please allow the URL to include the actual text to send to the specified number.
> 
> > 
> 
> > signl://msg?text=Hi&to=+1555999
> 
> 
> 
> Hi 
> 
> Hope you are doing great 
> 
> i used same Way In My Project but it is not opening the Particular contact  for chat option
> 
> "sgnl://msg?text=Hi&to=+1555999" this is opening the App

The feature is not implemented yet, so that is why it is not working...

**Comment by ThirupathiRaoM** [comment]
Means in ios we are unable to open Particular Conatct In signal ??

**Comment by CySchneider** [comment]
Big need. 👍

**Comment by sreedev98** [comment]
Just bumping this as this is an absolutely necessary feature.

**Comment by arronmabrey** [comment]
Same ^^

**Comment by nelsoncarr** [comment]
If there was this custom URL scheme which would allow to prefill a text (and/or number), all websites could have a "share on signal" or "text me on signal" button. would be a great boost for signal!

**Comment by marcinkoziej** [comment]
Hey why is this issue from prepandemic times still not resolved???

**Comment by primu5** [comment]
Any update on URL schema implementations/adaptations plans? Would be really amazing to use Signal as a "Contact Me" option in Email Signatures & literally everywhere on web.

**Comment by nabilfreeman** [comment]
Nice 7 year old issue 🤣

p.s. sending nothing but love to the Signal team!

**Comment by brodyhoskins** [comment]
Would love to see this too! 😬

**Comment by pawlean** [comment]
Would 💜 this too!

**Comment by Tsjippy** [comment]
I would love to hear any official comment whether this coming at some point

**Comment by Cerberus0** [comment]
Hello everyone,

It has already been "leaked" that [the Signal team is working on this feature](https://community.signalusers.org/t/2362/82). Of course, they don't like to talk about timelines or new features until they're ready.

Please note that this issue tracker is no longer used for feature requests, as stated in the project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#issues):

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests/17). The purpose of this issue tracker is to track bugs in the iOS client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

If you would like to continue this discussion, please do so on the community forum:

https://community.signalusers.org/t/add-custom-url-scheme-signal-or-sgnl-for-share-or-call-buttons-on-websites/2362

You can easily join the forum with your existing GitHub account. Thanks!

**Comment by primu5** [comment]
Alright, this works. It exposes my number but idc this works for me.

`https://signal.me/#p/+{COUNTRY_CODE}{NUMBER}`

Finally!

**Comment by uok** [comment]
Nice find!
Signal App and Signal Desktop can already handle this link

I hope there will also be a `t` or `text` parameter, which lets you share text

**Comment by de1mat** [comment]
> Is this still relevant? If so, what is blocking it?

The bot asks some good questions.

Yes this is still relevant.

**Comment by saizai** [comment]
Reopened at https://community.signalusers.org/t/url-scheme-706/44998/1

**Comment by iSebastin** [comment]
> Means in ios we are unable to open Particular Conatct In signal ??

We can open a a particular chat window using https://signal.me/#p/[number], but I'm still figuring a way to append a message along with it.

**Comment by jkatzx** [comment]
Why was this closed?

**Comment by LBBO** [comment]
For posterity: the deeplink posted by @iSebastin works, but it's opened in the browser and then redirects to Signal (at least that's the case on macOS). If you're already running outside of a browser and want to avoid the detour, you can replace `https` with `sgnl`. So both `https://signal.me/#p/+1234567890` and `sgnl://signal.me/#p/+1234567890` lead to the same chat, but the latter will not open the browser first.
