### ISSUE TITLE
Conversation date is rendered over user/group avatar in Right-to-Left

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#707]
In Right-to-Left languages (specifically Arabic), the date of the conversation is rendered over the user/group avatar in "conversations" view.

![img_0001](https://cloud.githubusercontent.com/assets/11326414/6635525/85112e56-c967-11e4-9b31-11e2161b6cfa.PNG)

Please also note that the avatar is exactly on the edge of the screen while in English interface there is some spacing.

Please tell me if you prefer listing all comments in one thread or opening a different issue for each.

**Comment by riyapenn** [comment]
@TheStash would you be interested in contributing to Signal's [Arabic translations](https://www.transifex.com/open-whisper-systems/signal-ios/language/ar/) and testing out RTL language support in a future Signal beta? Contact support@whispersystems.org if you are :)

**Comment by charlesmchen** [comment]
@TheStash A large number of improvements around RTL languages are coming soon - not in the forthcoming v2.14 release but probably in v2.15.

**Comment by michaelkirk-signal** [comment]
This should be working in the latest Signal.
