### ISSUE TITLE
Call button orientation in Right-to-Left

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#710]
In the "New Message" screen in which you choose a contact to either send a message or call, the call button is on the left of the contacts' names which is wrong, instead it should be on the right of the contacts' names.

![img_0002](https://cloud.githubusercontent.com/assets/11326414/6635521/6f2d91ba-c967-11e4-9fbd-200d084f7389.PNG)

**Comment by michaelkirk-signal** [comment]
This should be working in the latest Signal.
