### ISSUE TITLE
"Send" button and chat bubbles are misoriented in Right-to-Left

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#711]
In the chat view, the "send" button is on the left side of the screen while in iMessage the "send" button on the right side which would be very confusing for users, also as you can see the chat bubbles are misoriented too.

![img_0008](https://cloud.githubusercontent.com/assets/11326414/6635459/a17ae9d4-c966-11e4-869a-96252553960d.PNG)

**Comment by michaelkirk-signal** [comment]
This should be working in the latest Signal.
