### ISSUE TITLE
Groups can be created without inviting any group member

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#714]
Groups can be created without inviting any member to the group , i believe users should not be able to create a group unless they invite someone to the group.

**Comment by FredericJacobs** [comment]
You can create a group with yourself to try and then invite people later. Fine to me.

**Comment by 2-4601** [comment]
You can also send messages to this empty group. This is somewhat confusing especially when the messages seem to get stuck on a pending state.

TextSecure for Android prevents the user from creating empty groups.

**Comment by riyapenn** [comment]
https://github.com/WhisperSystems/Signal-iOS/issues/835

**Comment by tzs1** [comment]
This can be closed now since it’s not a bug but instead a feature.
