### ISSUE TITLE
Show contact profile photo and phone number for contacts in “New Message”

### ISSUE THREAD

**Issue by mmkassem** [signalapp/Signal-iOS#721]
When either more than one person are sharing the same first and last name or a person has more than one phone number, it is impossible to identify the person or the number you would like to send a message to until you have created a conversation.

It can be better to add both the contact profile photo if available and the phone number in the “New Message”.

**Comment by FredericJacobs** [comment]
Yeah, I don't think profile photo is a must but having a way to see what number it is would be a good addition. Thoughts @abolishme? I think we need an interaction or design enhancement to show this.

**Comment by abolishme** [comment]
To clarify, the suggestion is to add a phone number to the contact table cell in the new message composer? I think that's a good suggestion, we'll do something like this in a future release.

**Comment by michaelkirk** [comment]
note that while currently ios9+ only, the invite flow contact picker incorporates this design: https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/view%20controllers/ContactsPicker.swift

**Comment by michaelkirk-signal** [comment]
This was fixed long ago...
