### ISSUE TITLE
Typing indicator

### ISSUE THREAD

**Issue by jackflips** [signalapp/Signal-iOS#730]
Typing indicators make chat apps feel much more fluid to me. This is one of the features I miss most from other chat apps. There is already support for this in JSQ. A `typing` field would need to be added to the TextSecure protocol.

**Comment by FredericJacobs** [comment]
Closing this because it's not something specific to the client but a feature request for the protocol.

**Comment by rocknjohn** [comment]
@FredericJacobs Where would be the appropriate place to create a feature request to add support for a typing indicator? I'll create a github issue.

https://github.com/WhisperSystems/AxolotlKit
https://github.com/trevp/axolotl

**Comment by jm3** [comment]
Hi @FredericJacobs, this (IMHO, important) issue was closed in 2015 and never got re-filed against the Signal protocol. Is [SignalProtocolKit](https://github.com/WhisperSystems/SignalProtocolKit) the best place for us to file this?

**Comment by michaelkirk** [comment]
This is the right place for it - but it would require changes to the other clients as well.

See related thread on Signal-Android: https://github.com/WhisperSystems/Signal-Android/issues/1121

**Comment by grovesp** [comment]
The Signal-Android issue list experienced a, "Clean-Up," and closed all of the tickets related to this issue. It's now May of 2018 - can we assume that since this has been ongoing for four-plus years, the Signal project is never going to address this?

**Comment by Tlamatinime** [comment]
This issue can be closed now, right?
