### ISSUE TITLE
It is hard on the eye to differentiate the sender of a message in group conversation

### ISSUE THREAD

**Issue by TheStash** [signalapp/Signal-iOS#736]
In a group conversation all messages sent from other group members look alike, there is no coloring of names or avatars that would help differentiate the sender and how the conversation flows, instead you have to look at the name under each message to know who sent it, in contrary on Android you use colored avatars, WhatsApp uses colored names...etc.

**Comment by diegode** [comment]
+1
Also, it is kind of confusing the fact that the name is under the message instead of above, specially for long messages.

**Comment by mxmerz** [comment]
+1
Would appreciate a more colorful conversation view as well, the current implementation makes it very difficult to follow a group conversation in Signal.

**Comment by rainerzufall** [comment]
I apologise for pumping this issue! But I really feel this is a must have, UX wise. I have convinced many friends of mine to use Signal and they all complain about this fact. Especially when they see my Android version with its individual colours. 
@michaelkirk is this planned? is this too big a change for your limited time? Thanks for reading and keep up the good work on the iOS client!

**Comment by michaelkirk-signal** [comment]
We've made some changes to address this in the 2.28 release.
