### ISSUE TITLE
Using last word as last name does not work for hispanic names

### ISSUE THREAD

**Issue by diegoe** [signalapp/Signal-iOS#754]
Hispanic names are incorrectly displayed on Signal because it uses the anglo-centric criteria of using the last word as the last name.

Example:
- My name is Diego Escalante Urrelo. Signal will show me as Diego Urrelo.
- A friend I text is Jorge García Pérez. Signal will show him as Jorge Pérez.

This is not legally valid, nor makes any sense to hispanic users who would expect me to be Diego Escalante (and my friend to be Jorge García) when my name is presented in "short" form.

TextSecure on Android, and other iOS apps like Messages, simply default to using the full name from the contact card. This is safe in 95% of cases for hispanic names (your obnoxious friend using his 3 first names too will deserve a quick edit in the contact card). In my experience most English users go with just one name, one last name. Those who go with more usually use initials or are hispanics.

I have been using my bi-cultural address book like that for years without any major issue, except one or two long names I edited explicitly. Editing ALL my contacts to explicitly separate name from last name(s) would be hell.

It's worth noting that this is a more evident issue when you are using Google imported/synced contacts. Since Google Contacts only has a "Name" field by default, thus, not having an explicit first/last name difference.

On Signal 2.0.2 on iOS 8.2 (12D508).

**Comment by FredericJacobs** [comment]
Thanks for pointing that out. 

Gonna work on that for the next update.

**Comment by michaelkirk** [comment]
related to #1158

**Comment by Mihahn** [comment]
Should be fixed in the future with the new profile names, right?
