### ISSUE TITLE
Group Key Change UI

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#755]
- [x] Issue with duplicate messages after accepting new key.
- [ ] Better way of displaying whose key has changed.

**Comment by diegode** [comment]
+1 to the second item. The message is very confusing since it doesn't specify whose key was changed, unlike TextSecure's.

**Comment by michaelkirk-signal** [comment]
> it doesn't specify whose key was changed, unlike TextSecure's.

This has long since been resolved.
