### ISSUE TITLE
Swiping left or right on a photo should show the next or previous photo in the conversation

### ISSUE THREAD

**Issue by rocknjohn** [signalapp/Signal-iOS#759]
When in a conversation and having clicked a photo to view it large, swiping left or right on the photo should show the next or previous photo in the conversation. 

This create a quick and intuitive way to view other photos in the conversation.

**Comment by chodid** [comment]
As #765 got closed - is there any progress on this feature? A lot of the users I tried to convince to switch to Signal found this one of the main drawbacks.

**Comment by chodid** [comment]
Just started a bounty on this:
https://www.bountysource.com/issues/10529779-swiping-left-or-right-on-a-photo-should-show-the-next-or-previous-photo-in-the-conversation/backers

**Comment by justjoeyuk** [comment]
Working on it.

**Comment by rocknjohn** [comment]
Done by PR https://github.com/signalapp/Signal-iOS/pull/3133 🎉
