### ISSUE TITLE
Choose which number to use for a specific contact

### ISSUE THREAD

**Issue by runasand** [signalapp/Signal-iOS#764]
I have a contact named Bob. In my address book, I have both his mobile and work number listed. When I select "Bob" in the list to send him a new message, I am not prompted to select which of the two numbers I want to send the message to. I then add a new contact named "Bob Work" with only Bob's work number. After I select "Bob Work" and send him a new message, the name that is listed at the top of the Signal interface is "Bob" (as if it pulls the number from the other contact I have, and not the one I selected when I sent the message). It would be great if Signal could let me choose which number to send a message to.

**Comment by riyapenn** [comment]
Correct me if I'm wrong, but Sounds like you did not remove the 'work' number for the entry "Bob" but have his work number stored in "Bob" and "Bob Work".  

Similar to https://github.com/WhisperSystems/Signal-iOS/issues/624

**Comment by runasand** [comment]
Yes, this is similar to #624 except that I only see one contact ("Bob", not "Bob Work"). Ideally, I would like Signal to ask me which number I want to use when a contact has more than one number.

**Comment by riyapenn** [comment]
Also, similar to https://github.com/WhisperSystems/Signal-iOS/issues/720

**Comment by riyapenn** [comment]
Similar solution to https://github.com/WhisperSystems/Signal-iOS/issues/721

**Comment by Baigle** [comment]
Also have this issue, it keeps me from easily messaging and limits usage between others that get new plans often.
