### ISSUE TITLE
Argentina - libPhoneNumber parses incorrectly mobile phone prefixes

### ISSUE THREAD

**Issue by diegode** [signalapp/Signal-iOS#766]
I use Signal and my friend uses TextSecure. Our country code is "+54". He wasn't showing up on my Signal's contact list, until i added manually the prefix "+549" to his number (the 9 in our country is used for mobile numbers). I explain all this because maybe you already consider the missing country code from the number, but not the 9.
Whatsapp, for instance, handles it fine.

**Comment by FredericJacobs** [comment]
Are you using it on an iPhone with a Argentinian SIM card in it?

**Comment by diegode** [comment]
@FredericJacobs yes

**Comment by FredericJacobs** [comment]
Is it a jailbroken device?

**Comment by diegode** [comment]
@FredericJacobs no and no :)

**Comment by hubert3** [comment]
I saw a similar issue when roaming - I'm normally in in +61 (Australia) and all mobile numbers here are 04xx xxx xxx. I have the mobile numbers for my contacts saved as a mixture of just '04xxxxxxxx' and some in international format like '+614xxxxxxxx'

Going overseas to Singapore (+65) and temporarily switching to a local SIM card with a Singaporean number (+65 xxxx xxxx), existing conversations with contacts whose numbers were saved as '04xxxxxxxx' were now missing contact names and displayed as numbers only in the conversation overview.

I had to update contacts to use international format phone numbers to make them appear again.

**Comment by diegode** [comment]
@hubert3 the behavior of the app in your case was not a bug. It's ok for it to assume that the missing country code is that of the SIM card (if not, there would be a dangerous ambiguity).

**Comment by hubert3** [comment]
@diegode fair enough. I agree the behaviour is not a bug, but it will look like a bug to many/most users in a similar situation (why are all my conversations missing names all of a sudden?)

**Comment by diegode** [comment]
@FredericJacobs now I can confirm that this bug is caused by the "9" after "+54". This is how I tested it:
Another friend of mine registered in Signal without the "9" after "+54" (so it seems that it is optional, since the SMS arrived just fine).
I had him in my contact list with "+549", and he wasn't showing up on my Signal's contact list. Then I removed the "+549" prefix from his number, and now he is showing up :)

**Comment by michaelkirk-signal** [comment]
This should no longer be an issue. Please let us know if you experience further issues.

**Comment by ByFede** [comment]
I'm experience this issue with Signal 5.11.1.1 and iOS 14.5.1
All contacts that have Signal but saved with +549 don´t shown in Signal, deleting the 9 "fix" the issue like @diegode explain.

I think that it's a problem to new users cause 9 it's mobile number code, many new users will not see contacts that actualy use Signal.

**Comment by diegode** [comment]
@ByFede please report this via https://support.signal.org/hc/en-us/requests/new
otherwise it will probably be ignored, since this issue is already closed and the participants don't work for OWS anymore.
