### ISSUE TITLE
Automatic scroll down on new message is annoying

### ISSUE THREAD

**Issue by diegode** [signalapp/Signal-iOS#769]
When reading old messages in a conversation, on each new message recieved (on the same conversation), Signal automatically scrolls down to the latest message.
This is really annoying since e.g. in a group chat you can't keep up with a long conversation while it's still getting place.

**Comment by JohanDoe** [comment]
+1
Suggestion would be to present an arrow overlay that one can click if one wants to go to last message (instead of automatically scrolling down when new message arrives). 

See for an example how telegram handles this.

**Comment by rsmn** [comment]
+1

**Comment by aaa11235** [comment]
Handling scrolling properly for group chats is pretty important to those who use group chats. And, as indicated in #638, it is a reason why many people do not switch over from WhatsApp. (e.g., I'm on the verge of losing a group of about 20 people to WhatsApp over this single issue, and this isn't unique.)

Ideally, this issue and #638 could be fixed at the same time with:

1 - When you open a thread, the view starts with the oldest unread message, perhaps with a visual indication of the line between what you've read and haven't read (WhatsApp has a banner separating read from unread).

2 - When you're reading a thread and a new message comes in, the view stays where you are, but an arrow appears with a badge showing how many new messages there are, and when you tap on it, it takes you down to those new messages.

**Comment by marcelodeaguiar** [comment]
The is any update on this issue?

**Comment by michaelkirk-signal** [comment]
This issue was resolved long ago.

It works basically as @aaa11235 described:

> 1 - When you open a thread, the view starts with the oldest unread message, perhaps with a visual indication of the line between what you've read and haven't read (WhatsApp has a banner separating read from unread).
> 
> 2 - When you're reading a thread and a new message comes in, the view stays where you are, but an arrow appears with a badge showing how many new messages there are, and when you tap on it, it takes you down to those new messages.
