### ISSUE TITLE
Feature request: Invite links for group chat

### ISSUE THREAD

**Issue by Geblaat** [signalapp/Signal-iOS#777]
Telegram just introduced a new feature to easily migrate existing group chats from another app to their own app. Given a feature like this will make transition to Signal easier, I think it's a good idea to implement something similar.
https://telegram.org/blog/invite-links

**Comment by heblol** [comment]
Is this made in the meanwhile? I think this would be an excelent improvement

**Comment by FedericoCeratto** [comment]
The same should exist for the desktop app and Android

**Comment by tomj** [comment]
Related to/subset of #706

**Comment by denver-s** [comment]
You should open a discussion on https://community.signalusers.org/

**Comment by michaelkirk-signal** [comment]
We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
