### ISSUE TITLE
Feature request: Deleting multiple messages

### ISSUE THREAD

**Issue by pzi** [signalapp/Signal-iOS#781]
Hey, would be great if a user can delete multiple messages from within a conversation.

I imagine something like the following:

``` feature
When a user is viewing a conversation
  she/he can tap Edit in the top right corner
    then the label 'Edit' becomes 'Cancel'
    then '<' becomes 'Delete all'
    then the messages slide to the right
    then checkboxes become visible
  she/he can activate the checkboxes of the messages she/he intends to delete

When a user is selecting x message she/he intends to delete
  then the label 'Delete all' becomes 'Delete (x)'
  she/he can tap 'Delete (x)'
    then there is dialog box requesting for confirmation of deletion
```

Something along these lines would be great. Similar to how Messages app and other communication apps do it.

Thanks for your consideration & cheers
Patrik

**Comment by mrphs** [comment]
+1

**Comment by jstray** [comment]
+1. Extremely important for the scenario where the adversary can compel you to type your password, in which case you need to be regularly deleting old messages. This is a realistic and common threat in many regimes.

Even better would be automated deletion, e.g. dont keep anything older than X days.

**Comment by mrphs** [comment]
The ability to selectively delete certain messages (not the conversation as a whole, since it's already there) is indeed very important. Sometime you want to have a history of a chat with a contact, but don't want one or two specific messages stay there...

I can totally see various scenarios where this is important and would be happy to elaborate if needed.

**Comment by michaelkirk** [comment]
Here's a related upstream issue for the library we're using to display messages: https://github.com/jessesquires/JSQMessagesViewController/issues/235

**Comment by neptunal** [comment]
Came here to request this, as the feature does exist in Android and is really the only thing the app is missing, to me.

**Comment by kevinp2** [comment]
Can we please have this feature implemented?  Most other messaging apps have it.  It’s important for security!

**Comment by michaelkirk-signal** [comment]
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/
