### ISSUE TITLE
Registered number shown in notification instead of name in addess book after having killed app

### ISSUE THREAD

**Issue by NicolasCGN** [signalapp/Signal-iOS#797]
If I kill Signal and then I receive a message, the message is decrypted by the app and the notification shows the message (when option "show sender & message" is active) but the name of the contact in the address book is not shown. Only the registered number: 

![img_4204](https://cloud.githubusercontent.com/assets/10416484/7823393/7798c7c4-03fb-11e5-9c7c-731d2aa88990.jpeg)

This is a similar behaviour like the default Messages App in iOS receives a message after booting the iPhone and before unlocking it for the first time using the code.

Nevertheless, I won't see this issue as a high priority one.

**Comment by NicolasCGN** [comment]
I had a similar problem without having killed the app:

The same contact sent 3 messages and the notification from the first one wasn't showing the name in my contact's book but the registered number with TextSecure. The other 2 messages were showing the contact's name

![img_2098](https://cloud.githubusercontent.com/assets/10416484/7903402/b4518da2-07db-11e5-8f78-51b3ed8fa51d.jpg)

**Comment by maltemayer** [comment]
I have the same problem from time to time with two contacts using Android. Instead of the name the number is shown.

**Comment by FredericJacobs** [comment]
Thanks for reporting this. It's well known and exists due to latency in processing large address books. If the network is acquired and the network connects before the address book is processed, the phone number will be displayed instead of the name that is "not yet available".
