### ISSUE TITLE
Can´t see contacts

### ISSUE THREAD

**Issue by theseer1990** [signalapp/Signal-iOS#82]
Hi, i just installed Signal on Iphone 4S and 5S. I validated for bith devices and on 5S i can see the user who validates with 4S, which is also in my contact list. In my 5S i can´t see the user which validated with 4S, he is ofc also in contact list.
Its possible that we can call, but in my 4S the user is still unknown. Is that a Problem wit Iphone 4S ? Both devices running IOS 7.1.2
Pls help me to figure that out

**Comment by hollyhudson** [comment]
I am also unable to see my contacts who I know have Signal in my contacts (I just downloaded and tried this out last night, so the fix hasn't happened).  In fact, I am the only person in my contacts.  My husband, for instance, can call me, and he will appear as a recent caller -- but there is not way to move him into my contact list that I can see.  Help?
