### ISSUE TITLE
testGroupMessagesDeletedOnThreadDeletion is not testing anything and creating bad data

### ISSUE THREAD

**Issue by Strilanc** [signalapp/Signal-iOS#827]
The [testGroupMessagesDeletedOnThreadDeletion test](https://github.com/WhisperSystems/Signal-iOS/blob/d347df9a46b8537d053bddababb5b23f496a0d36/Signal/test/textsecure/TSMessageStorageTests.m#L158) is broken.

The issue seems to be the combination of

```
uint64_t timestamp = 666;
```

and

```
for (uint64_t i = timestamp; i<100; i++)
```

meaning the loops are not running even once. I tried fixing the issue, and the test deadlocked instead of succeeding. it needs attention.

Also, or maybe as a result, the TSAttachmentStream that's created is never deleted. And, because it has an unsupported content type (data/random) Signal starts crashing on startup after you've run the tests, due to [unsupported streams resulting in nil files](https://github.com/WhisperSystems/Signal-iOS/blob/d347df9a46b8537d053bddababb5b23f496a0d36/Signal/src/util/MIMETypeUtil.m#L184) and that nil [being put into an array](https://github.com/WhisperSystems/Signal-iOS/blob/d347df9a46b8537d053bddababb5b23f496a0d36/Signal/src/textsecure/Messages/Attachements/TSAttachmentStream.m#L33).

**Comment by Strilanc** [comment]
Also, the setUp of the test class puts a fun message into your inbox from "aStupidId".

**Comment by michaelkirk-signal** [comment]
This test has long since been replaced.
