### ISSUE TITLE
More Secure Discovery Alternative

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#83]
A more secure discovery alternative, that would prevent phone numbers from being revealed, would be to give the user the option to include first and last name, and optionally email address along with phone number in a hash sending that hash to the server. This way, unless you have the user's full name and (optionally) email address, along with phone number, you can't deduce the communication between both parties. This would also permit for pseudo names to be used. Now, with that comes some potential for spelling mistakes and other things getting in the way. To address this, and add a further layer of abstraction through hashing, I propose having a look at this Stanford paper on document fingerprinting, which employs a sliding winnowing algorithm to generate sets of hashes based on fuzzy matching. This works on small data sets too, such as names and email addresses, or even authentication words, allowing you to further account for spelling, but also further abstract names and identifying information from a final hash.

http://theory.stanford.edu/~aiken/publications/papers/sigmod03.pdf

**Comment by lcfr123** [comment]
Maybe it's an idea to have something like Threema's 'Threema ID'? The ID is a reasonably short (and unique) string that is the primary lookup mechanism. A phone number (and/or) email address are optional search mechanisms. It's up to you to allow yourself to be 'discovered' by those. And there is no direct relationship between your ID and you.

**Comment by caveman1973** [comment]
Telegram has an interesting implementation of usernames. [Optionally] In Settings you register one (that is linked to your phone number. If you do, anyone will be able to find you by your username and contact you – without having to know your phone number.

**Comment by pjctech** [comment]
I vote for the optionally usernames...

**Comment by 0x6b-dev** [comment]
Reopen, this still remains an essential feature.

**Comment by caveman1973** [comment]
> Reopen, this still remains an essential feature.

Yes but they don't want to implement it. It's been four years since they said it was coming. Nothing to see here
