### ISSUE TITLE
Feature request: Ding when call drops to prevent embarrassing rambling :)

### ISSUE THREAD

**Issue by ailanthus8** [signalapp/Signal-iOS#842]
When Signal calls drop, they often do so silently and users continue to talk not realizing that no one is listening. This becomes an awkward situation over time. 

Can you create a pleasant sound that both parties hear when a call drops?

**Comment by caveman1973** [comment]
Same when a call is established.

**Comment by thecure** [comment]
Seems plausible to ding at the beginning when the call is established (or perhaps play the sound of a coin dropping?) as there is sometimes a long pause before the call starts. But definitely a sound when the call drops so that one doesn't keeping talking.

**Comment by PowerPress** [comment]
This is a great idea

**Comment by wallclockbuilder** [comment]
:+1:

**Comment by denver-s** [comment]
This should have been fixed in version 2.40.1
