### ISSUE TITLE
Improve selectability of messages with links.

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#849]
See discussion in #834 and #836

**Comment by olbrew** [comment]
It is still very difficult, if not nigh impossible, to get the Signal popup to reply to or delete an individual message containing only a link since the iOS data selector on links takes precedence. #1756 describes it pretty well but since that was closed I'm commenting here.

**Comment by u32i64** [comment]
@olbrew Are you aware that you can hold outside the message bubble on the same line to get that popup?

**Comment by olbrew** [comment]
I wasn't. Will try that the next time. Thanks!
