### ISSUE TITLE
New Image/Video Picker

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#858]
- [ ] Let users select multiple items
- [ ] Let users review media selection before sending

**Comment by samer** [comment]
Suggestions:
- [ ] Let users rotate images
- [ ] Let users crop images
- [ ] Let users attach a string to an image (i.e., a "caption").

**Comment by michaelkirk** [comment]
I think we're conflating two things here:

1. The first roughly corresponds to: https://github.com/WhisperSystems/Signal-iOS/issues/1132
2. The second is about extra tools for the media picker, and sounds similar to how iOS Messages does media attachments:

![image](https://cloud.githubusercontent.com/assets/217057/14296760/a26c1438-fb49-11e5-972a-85b8c2b280a6.png)

I think this issue should just represent the second meaning, as the first has value in and of itself (and blocks past functionality).

**Comment by mrphs** [comment]
I just want to emphasize on the importance of the image review before pressing send. Specially since a lot of journalist and typically at risk people use Signal, the cost of sending any wrong document or image to the wrong person because sender has accidentally tapped on them is extremely high.

**Comment by chodid** [comment]
Any progress on this? Once again, when trying to convince people to switch to signal, this was one of the problems a lot of them mentioned in the first days of usage.

**Comment by tzs1** [comment]
@michaelkirk-signal I think this can be closed now.

**Comment by samer** [comment]
@tzs1 cropping and rotating (as would on Whatsapp) would still be a handy feature to have.

**Comment by tzs1** [comment]
Those features are now available in beta 2.38.

**Comment by tomj** [comment]
For completeness to ensure that this has made it to the App Store, I can confirm that the following have all shipped to production in 2.38.1.2:

- [x] Let users select multiple items
- [x] Let users review media selection before sending
- [x] Let users rotate images
- [x] Let users crop images
- [x] Let users attach a string to an image (i.e., a "caption")

so this can be closed.

nb: this includes the cropping and rotating you've suggested @samer
