### ISSUE TITLE
Settings UI Tweaks

### ISSUE THREAD

**Issue by huertanix** [signalapp/Signal-iOS#862]
![signal_ui_tweaks](https://cloud.githubusercontent.com/assets/72914/9024151/1c411b94-388d-11e5-8902-8d5bb5ace278.png)

Hi there,

I've been helping folks use Signal at cryptoparties in NYC and have noticed some recurring questions regarding the Settings panel, and in particular the use of the word "fingerprint." Since new iPhones have a biometric fingerprint reader, mentioning fingerprints has been causing some confusion over why a privacy app would need to scan their finger, etc. Once the concept of a fingerprint is explained, people wonder how to practically use one, and so far there hasn't been a consistent answer for that, would be great if the concept and usage were explained, maybe inline or in a little question link that brings up a new screen?

Another thing bringing up questions on the same screen is the idea of "Screen Security." Some people assume it means "So and so took a screenshot" type functionality, but that doesn't seem to be the case. It might be helpful to have an explaination of how the screen is being secured.

Aside from that Signal has been a breeze to get people up and running with. A++ would use again.

.dh

**Comment by FredericJacobs** [comment]
Great, thanks for the feedback. Will see what I can come up with to clarify what these are doing.

**Comment by mxmerz** [comment]
I was also confused by what “Screen Security” would do. I found it in the FAQ, but a short description under the setting wouldn’t hurt.

**Comment by huertanix** [comment]
@FredericJacobs: This is a lo-fi mockup of what I came up with for a revised design for the Settings > Privacy screen: https://live.uxpin.com/85cc7864d1b0411c605354da3d92a046e27652cc#/pages/33973257?mode=m.

![default-0-settings-privacy-34020137](https://cloud.githubusercontent.com/assets/72914/12254482/234ccc26-b8b7-11e5-8e8f-6488d655984a.png)

I decided it would make more sense to have inline text under the option to harmonize with current iOS HIG recommendations: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/FeedbackCommunication.html#//apple_ref/doc/uid/TP40006556-CH56-SW1 . It seems like it'd make more sense to show the Signal Identity in its entirety (like in the Android app) without having to copy it to an unspecified application. I like Signal Identity better than fingerprint, but left it in the definition copy, emphasized, to make it easy to realize they're the same since experienced users will still end up referring to it as a fingerprint. See page 2 of this report from a usability study I helped out with on CryptoCat and the problems around "fingerprint" https://crypto.cat/documents/UX_Report.pdf.

**Comment by tomj** [comment]
Both parts of this feature request look to have been shipped to prod.

* Explanatory copy has been added for the footer on the **Screen Security** UITableView section (see screenshot below from App Store version 2.38.1.2)

* Also apologies if I'm missing something glaringly obvious (I'm new here) but the second part requesting changes to the "Fingerprint" / "Identity Verification" section is now seemingly redundant, given the implementation of [per conversation safety numbers](https://signal.org/blog/safety-number-updates/) and removal of per user fingerprints.
  * side note: it was actually tough to work out from signal.org what a safety number actually *is* technically, which made working out 100% whether the second half of this could be recommended as closed quite tough also.  Started a [conversation on the support forum](https://community.signalusers.org/t/what-is-a-safety-number/7234) with further thoughts.

![screen_security](https://user-images.githubusercontent.com/66176/56096840-9c27f500-5f1f-11e9-843f-c2d6c53d4d39.PNG)

**Comment by huertanix** [comment]
I agree; the current implementation addresses the issues I was thinking of; Mainly explaining what features were and avoiding confusion in the crowded namespace that is _fingerprint_. I'll close this issue if that sounds good to everyone.
