### ISSUE TITLE
Implement ContactsUI framework

### ISSUE THREAD

**Issue by FredericJacobs** [signalapp/Signal-iOS#898]
https://developer.apple.com/library/prerelease/ios/documentation/ContactsUI/Reference/ContactsUI_Framework/index.html

**Comment by Baigle** [comment]
Enhancement?

**Comment by bouk** [comment]
ContactsUI is iOS 9+ only, does the app need to remain 8+ or can it be restricted to 9+? Could probably support both too. I'd be interested in implementing this.

**Comment by tomj** [comment]
I'm seeing ContactsUI in use in [ContactsViewHelper.m](https://github.com/signalapp/Signal-iOS/blob/53299c139f38ca7ff2b107d95b78d4b8dcb9b74e/SignalMessaging/Views/ContactsViewHelper.m) as an import and then when [presenting a CNContactViewController](https://github.com/signalapp/Signal-iOS/blob/53299c139f38ca7ff2b107d95b78d4b8dcb9b74e/SignalMessaging/Views/ContactsViewHelper.m#L377) to edit a contact.

I have also confirmed that editing a contact inside Signal iOS 2.38.1.2 is reflected in the contact's record in the system wide contacts list.

I have not directly confirmed that the vc which is presented when a contact avatar is tapped for editing from within Signal actually invokes the method linked to above which displays the ContactsUI vc, but I suspect any maintainer reading this will know immediately whether this is the case.  If I don't hear back I'll build the app on a device and set a breakpoint to confirm my suspicion.

**Comment by michaelkirk-signal** [comment]
This was completed long ago.
