### ISSUE TITLE
WebM support

### ISSUE THREAD

**Issue by rmueller83** [signalapp/Signal-iOS#902]
As the new TextSecure Android 2.27.0 beta supports larger attachments now, I tried to send some .webm videos to my iPhone. There I only get a "Received unsupported attachment type." message.
Here is a sample file: https://webm.html5.org/test.webm
Safari also does not seem to open the file, but in WhatsApp it works.

**Comment by mikeokner** [comment]
Right now the supported attachment types are in this file:

https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/util/MIMETypeUtil.m

I'll look into support for webm when I update my pull request for gifs ( #886 )

**Comment by Swivelgames** [comment]
Any update on this?

**Comment by dud1337** [comment]
Any updates here? Quite a common file format.

**Comment by jumper444** [comment]
I'm trying to send a small (8 meg!) *.webm audio file to contacts using windows signal desktop (v1.32.1).  Clicking "+" attach and selecting the file from disk causes a file attachment placeholder to appear above (to left) of the message box (like images appear), but then it immediately is cleared and goes away.

This issue has nothing to do with file size.  Is this thread and my resulting program behavior indicating I can't send a simple audio file to recipients (to download then play using another application...I'm NOT asking for some sort of built-in player or functionality).

I thought signal let me send whatever I want to people (within size limits).  Is there actually a small filter list???
NOTE: that the post above from Nov 2015 which says "supported attachment types" is 404 Not found.

Explanations for what is happening here? Thanks.

**Comment by jumper444** [comment]
(note: if there is some sort of approved list of what the program will and won't allow it would be much more user friendly if a small dialog popped up and said something coherent. I tried an attach multiple times, the started searching, etc.  Instead (if true) would be nice just to get a dialog saying "Permitted file size must be <100MB.  Permitted file types are .png, .jpg, etc, etc..")

**Comment by p-vernaeckt** [comment]
Hi! Digging out this issue as WebM becomes more and more popular each day. Any support planned?

**Comment by q2apro** [comment]
Recent state is: 

1. Choose a webm video file
2. Shows up in your own phone (Android) as playable
3. Receiving users text back (iOS) "I cannot open the file"

Android works! 👍 

It would be epic if Signal could play the webm file on iOS too. Thanks.

**Comment by slingr-dev** [comment]
This issue/feature request needs a much higher priority in my humble opinion.

It breaks the user experience for iOS users who have migrated group chats from WhatsApp, only to have incoming content from Android phones fail to render at all (WEBM).

**Comment by dud1337** [comment]
The bot should not have moved this to won't fix.

**Comment by slingr-dev** [comment]
between failure to action this over 7 years combined with zero CarPlay support (not even notification there is an unread message or anything) I may be forced to crawl back to WhatsApp. This isn't a threat or anything, its that there are standardized features this app is missing and the developers don't even acknowledge it. I've donated a couple times because I know this app is free, but I'm not sure what else I can do to help this along. If anyone has suggestions please let me know.

**Comment by slingr-dev** [comment]
this stale bot is an utter POS. yes, this is this relevant. what is blocking it? devs refuse to actually do anything about it.

**Comment by NiklasBr** [comment]
> what is blocking it? devs refuse to actually do anything about it.

This.

**Comment by jumper444** [comment]
This is of similar issue: more and more websites are using AVIF images.  So lately (increasingly) I right click and 'copy image' then go to paste/share it into Signal yet signal doesn't recognize it as an image type.  Instead it just displays a download placeholder 'page' with "AVIF" in it.  (This means that that neither the sender nor recipient see the image...you have to instead treat it like a spreadsheet or other 'app needed' document...aka...download/save it, then open it with another program like an image viewer.)

Signal is years behind the curve on what is considered 'modern' and 'in common use' for audio, video, and image formats.  Yes, these were esoteric and experimental years ago, but they are now native and built into all browsers as well as phones.

**Comment by jumper444** [comment]
I haven't checked Signal with Jpeg XL either.  That format was fixed and is now moving into common usage as well.

I'm not familiar with Signals internal design.  I presume the team didn't code their own implementations of all these formats.  Isn't there just a widespread open source AV library that is being used (or COULD be used???) that would easily keep up with evolving formats?  Imagemagick? something like that?  

For security Signal could disable MOST of the AV library permitted formats (we don't need 100 of them), but then just enable the 5 or 10 that are needed and then the library (and those other developers) keep us up to date?

**Comment by NiklasBr** [comment]
Stale bot, you should ask the devs to answer this, they need to do something.

**Comment by NiklasBr** [comment]
I wish the bot would stop spamming.

**Comment by MartijnGevaert** [comment]
bump

**Comment by midibyte** [comment]
This is still an issue.

**Comment by spitemim** [comment]
Why is this not a feature yet? This kills the app.

**Comment by MartijnGevaert** [comment]
It looks like IOS doesn't support webm video playback directly, I can see why the Signal team is hesitant to implement it if it's not even supported by IOS itself. But it is possible, a number of third party apps support it on IOS, such as VLC media player.

**Comment by NiklasBr** [comment]
The [third party code for webp](https://cocoapods.org/pods/libwebp) is already imported via [CocoaPods](https://cocoapods.org/) here:

https://github.com/signalapp/Signal-iOS/blob/a81cb65e5b7906ae392249cac9d5c6fffe4096ba/Podfile#L52

**Comment by jumper444** [comment]
> It looks like IOS doesn't support webm video playback directly, I can see why the Signal team is hesitant to implement it if it's not even supported by IOS itself.

Can I suggest (if Signal team is using this as a reason) that they allow senders and receivers to handle their OWN concerns about whatever AV files they want to send to each other (and what THEY want to do with them) instead of hand-holding or acting like somebody's parent? (no offense)  Webp and webm are not insignificant formats and I personally don't care what Apple thinks or wants to support or 'allow'.   They can run their own little walled garden or disneyland park as they see fit.  The rest of us have actual files and formats and need to get things done in life.  (I would also point out that webm/webp are from Google and so we can also expect ulterior motives here.)

>The third party code for webp is already imported via here

I can't interpret this statement.  Are you replying somehow to say that Signal now has webm/webp/etc support?

**Comment by NiklasBr** [comment]
Signal has third-party code for webp (unclear if webm is included). My post should be read as a response to the question whether or not Signal is comfortable with including third-part image formats, which I showed they are.

**Comment by gredin** [comment]
Still relevant. This should be reopened.

**Comment by jm355** [comment]
Yeah I sent a video to my friend and they can't see it, apparently cause it's webm and signal doesn't support it on ios for some reason

**Comment by MarlowBrown** [comment]
Hey everyone. I'm continuing the [conversation](https://github.com/signalapp/Signal-iOS/issues/5930#issuecomment-2948168621) over on #5930 as that is the currently open Webm ticket.
