### ISSUE TITLE
Support for headset call end trigger

### ISSUE THREAD

**Issue by anselmh** [signalapp/Signal-iOS#909]
Hey guys,

as far as I could find out, currently it‘s not possible to end a call by pressing the (play/pause) button on the Apple headset. It would be great to have that option as it’s necessary when driving.

Cheers,
Anselm

**Comment by tomj** [comment]
I can confirm that while on a voice call on Signal iOS 2.38.1.2 pressing the "middle" (ie:play/pause) button on the Apple EarPods remote ends the call.

(this assumes that @anselmh is referring to EarPods when he uses the term *Apple headset*)

**Comment by anselmh** [comment]
Works here now, too in the latest version. For reference, I was referring to non AirPods but the Apple wired headphones. Closing this issue therefore now.

**Comment by tomj** [comment]
No problem :)  Not wanting to pollute the thread, but just for posterity/completeness and anyone reading this in future the _EarPods_ are actually the Apple wired headphones with lightning connector which ship with iPhone ([store link](https://www.apple.com/shop/product/MMTN2AM/A/earpods-with-lightning-connector)) which is what I tested against.

I also found the name a little confusing, and indeed only discovered that was the correct name when I posted the comment on this ticket :)
