### ISSUE TITLE
Who did just call me?!

### ISSUE THREAD

**Issue by mrphs** [signalapp/Signal-iOS#920]
I have this issue with notifications when someone calls me and my phone is locked that leads to two different failed scenarios to answer the call or see who was calling:

Scenario 1:  Unlock the phone and instead of tapping on the notification, open the app. all of a sudden the notification is gone and the app doesn't show you who has been calling.
Scenario 2: If the last app that was open before locking the phone, regardless of swiping right on the notification before unlock or unlocking the phone without tapping on notification, it opens the app and doesn't show you who has been calling.

PS: sorry about the title, couldn't think of any better :) feel free to change it to something more appropriate.

**Comment by ElmerLastdrager** [comment]
I have the same...

**Comment by freddymartinez9** [comment]
Can confirm Scenario 1 as well @mrphs

**Comment by michaelkirk-signal** [comment]
We've long since rolled out a new calling system which has clearer notifications. I believe this is resolved.
