### ISSUE TITLE
Message export/Backup

### ISSUE THREAD

**Issue by davidglidden** [signalapp/Signal-iOS#967]
Hello,
Thanks to everyone at WhisperSystems for Signal. I use it everyday. I am starting to accrue many messages and have searched for a way to export an encrypted backup. I see that it is possible on Android, but I can't find a way to do this on iOS.
Thanks in advance.

**Comment by likyng** [comment]
I think that that feature is not available on android anymore, you can "only" export an unencrypted xml file of all conversations. 
I strongly agree however, that the iOS client should offer that functionality and hopefully be compatible with the android generated xml file to facilitate platform/device switches.

**Comment by lcfr123** [comment]
In the mean time, could it be possible to simply backup to iTunes/iCloud? I know this is a security risk, but if I _want_ to backup it should be possible... Maybe a simple setting that toggles the 'NSURLIsExcludedFromBackupKey ' flag, like in Technical Q&A QA1719. I prefer the automatic backup above a manual and hand-rolled backup scheme.

**Comment by ludovicaelbrecht** [comment]
As far as I can see, there's no way whatsoever to do an export using Signal on iOS. Is that correct, or does someone know of a workaround?

I'm moving from iOS to Android, and want to take my Signal messages with me.

I suppose an iTunes backup probably will contain Signal's files, which can then be exported out of the backup using e.g. iphonebackupbrowser (FLOSS). But I don't know if it's possible to import those files again afterwards (e.g. using Signal on Android).

**Comment by lcfr123** [comment]
As far as I know, no workarounds... And the iTunes backup does NOT contain the data files! I understand from a security point that you want that as an option, but from a usability (in case of loss/damage/new device/...) I also want/need the option to backup my message history.

**Comment by grahovam** [comment]
+1

**Comment by ludovicaelbrecht** [comment]
This is really a blocker for me to continue using Signal. Losing all your messages when switching to another device doesn't make sense. 

Would be great if the devs could find a way to allow exporting to (preferably) a format supported by "SMS Backup & Restore".

**Comment by moxie0** [comment]
@ludovicaelbrecht Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by thomasrive** [comment]
Seconding this option to allow for export of messages. But I would also like to suggest the option to control what gets exported if you want to remove timestamps, contact names, etc.

**Comment by NiklasBr** [comment]
Not being able to export or back up my own data is a bug, not a feature, in my world. I suspect this was done for some unspoken security reason. But why? What do I, who want to continue my conversations on a new device, have to forgo all my data if I want to use this app? Why is this limitation not more prominently displayed?

This app is about secure communication, I get that and it's really really god at securing _communication_, my data at rest is my data. Right?

**Comment by likyng** [comment]
Would it be possible to [include an option to] include Signal's files in an encrypted iTunes backup before the release of iOS10 and/or the release of the next iPhone? I dug a little into how to mark files to be included in a backup and it does not seem to difficult. However, I do not know how files are stored internally in Signal so I cannot really comment on the difficulty of such a bug fix/feature.

**Comment by jonathanweinberg** [comment]
I can understand it being a toggle, even defaulting to off. But no prominent info that my encrypted iCloud, or encrypted iTunes backup does not also contain my Signal data is quite surprising. No way to export. Very disappointing. If you can't back it up and restore it, does it really exist? :-)

**Comment by EvanHahn-Signal** [comment]
As was mentioned, we'd like to use GitHub for bug reports, not feature requests. Please use [this community forum thread][0] to discuss this feature further, and the community forums to discuss other feature requests in general.

[0]: https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones/1736
