### ISSUE TITLE
Sending/receiving pictures/attachments to members in a group that has two signal numbers fails

### ISSUE THREAD

**Issue by eaon** [signalapp/Signal-iOS#972]
I hope I got this one right, it's hard to test with my friends phone: I have a group of a couple people one of which uses iOS. I have two phones both of which have Signal accounts, and they were both part of the same contact on my friends iOS device. While this was the case, neither my friend could receive my attachments (only tried images) in a group, nor did I receive their attachments. Once I separated the contact info, receiving and sending of attachments seems to work again.

On an iOS device, my friend sees "attachment is being downloaded" but it doesn't go away, while I didn't get any message for a sent attachment on either of my phones. Other members of the group received everything fine.

Now #873 might be related to this but this looks like more low-level stuff and isn't only UX/UI related.

**Comment by 2-4601** [comment]
More related issues caused multiple numbers on a single contact: #624, #720, #721, #764.
